### ISSUE TITLE
Add "pong" logic in websocket server

### ISSUE THREAD

**Issue by damioune123** [apache/pulsar#10014]
**Is your enhancement request related to a problem? Please describe.**
As described in the websocket protocol, the ping/pong would allow to have a control frame to detect network issue in the websocket layer.

**Describe the solution you'd like**
When message sent to server via websocket via a "ping", the server should send a "pong" back.

**Describe alternatives you've considered**
Message acknowledgment of the pulsar layer can be used currently, but a not received ack could be caused  by other reasons than network issue. Plus it's a bit weird to have to detect network issue in the application layer.

Here is a description of the "ping/pong" websocket control frame : 
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers

**Comment by lhotari** [comment]
@damioune123 do you have more details about this issue? Which Pulsar version was this report about? In #20733, @michaeljmarshall noticed that Websocket ping-pong support works out-of-the-box. Perhaps that changed over time?
