### ISSUE TITLE
pulsar admin  not acessing bookies

### ISSUE THREAD

**Issue by DonHaul** [apache/pulsar#10018]
Hello I am trying to look at a message on the ledgers via the admin command of the pulsar client:
```/bin/pulsar-admin topics get-message-by-id persistent://public/default/testtopic9 -l 4 -e 3``` however it doesnt work, returning the following error:
````
null

Reason: java.util.concurrent.CompletionException: org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$RetryException: Could not complete the operation. Number of retries has been exhausted. Failed reason: pulsar-broker-3.pulsar-broker.pulsar.svc.cluster.local
````

I've done  ```bin/pulsar-admin brokers list``` and it returns all bookies as expected:

```
"pulsar-broker-0.pulsar-broker.pulsar.svc.cluster.local:8080"
"pulsar-broker-1.pulsar-broker.pulsar.svc.cluster.local:8080"
"pulsar-broker-2.pulsar-broker.pulsar.svc.cluster.local:8080"
"pulsar-broker-3.pulsar-broker.pulsar.svc.cluster.local:8080"
```
I have also verified that that ledfer id and entry exist using the reader api.

 I am running this on kubernetes via minikube and I installed using the the helm chart for with 1 replica of each, but changed it the replicas from 1 to 4:, https://github.com/apache/pulsar-helm-chart/blob/master/examples/values-minikube.yaml . 

Other than that all configurations remain unchanged.

**Comment by zymap** [comment]
The request looks like redirected to another broker. Can you try with pulsar proxy? You can expose the proxy port on local and use pulsar-admin to connect proxy then execute that command.

**Comment by DonHaul** [comment]
That was it, I was connecting directy to the broker service instead of to the proxie's webservice webServiceUrl
