### ISSUE TITLE
Websocket Encryption

### ISSUE THREAD

**Issue by kjaggann** [apache/pulsar#10021]
A producer is sending a messages using encryption while the consumer should be able to consume the encrypted message using the websocket 
wanted an help 

If no is there a way 
 we can configure to
start websocket proxy with option to avoid decryption, and let it pass same payload to web-socket client
the configuration settings or the steps required to change 
or any other option where we can resolve the issue

**Comment by rdhabalia** [comment]
@kjaggann I think this will help: https://github.com/apache/pulsar/pull/10026

**Comment by kjaggann** [comment]
Is this change is in pulsar 2.7.1 version.
however we have upgraded the websocket version in our websocket proxies but still the user is unable to connect the when the encryption is enabled 

![image](https://user-images.githubusercontent.com/59704044/118825194-1904c600-b880-11eb-9a30-4c4aa54f140c.png)
![Uploading image (4).png…]()

**Comment by kjaggann** [comment]
The recent change to the pulsar websocket allows the encrypted payload to be passed thru to the client.
However,  it does not appear that the (aes) encrypted data key is included with the message that we get.
How does a websocket client get this key?

**Comment by rdhabalia** [comment]
websocket just pass through message payload with key to client without modifying anything.

**Comment by chris-gentile** [comment]
Can someone please tell me if the above mentioned "key" ("Original routing key set by producer") is actually the '(aes) encrypted data key' ?

**Comment by kjaggann** [comment]
https://github.com/apache/pulsar/issues/11197

**Comment by MarvinCai** [comment]
it is not, the **key** mentioned here is used to determine which partition a message will be sent to: https://pulsar.apache.org/docs/en/admin-api-topics/#publish-to-partitioned-topics
