### ISSUE TITLE
[Docs] Invalid instructions for generating license headers

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#10030]
On this page: https://pulsar.apache.org/en/contributing/
the instruction to generate license headers is to run:
`mvn license:format`
Running that command produces this error:

> [ERROR] Failed to execute goal com.mycila:license-maven-plugin:4.0.rc2:check (default-cli) on project pulsar-functions: Execution default-cli of goal com.mycila:license-maven-plugin:4.0.rc2:check failed: Cannot read header document ${pulsar.basedir}/src/license-header.txt. Cause: Resource ${pulsar.basedir}/src/license-header.txt not found in file system, classpath or URL: no protocol: ${pulsar.basedir}/src/license-header.txt -> [Help 1]

The correct command is:
`mvn initialize license:format`

The docs should be updated.

**Comment by Anonymitaet** [comment]
Hi @devinbost thanks for reporting this. Would you like to update the doc (`pulsar/site2/website/contributing.md`)?
