### ISSUE TITLE
refresh delay time for "Delayed message delivery"

### ISSUE THREAD

**Issue by hoswey** [apache/pulsar#10042]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

For the [delayed message delivery](https://pulsar.apache.org/docs/en/concepts-messaging/#producer), the delay time will be fixed when the message is produced. There is no way to update the delay time in the future even when the message is not been deliveried.

But in some business scenario like auction, the auction will keep active when the player bid price. So we need to refresh the delay time(end time)

**Describe alternatives you've considered**
**Additional context**

**Comment by codelipenghui** [comment]
@hoswey You can resend a new delay message when received the old one.

**Comment by hoswey** [comment]
> @hoswey You can resend a new delay message when received the old one.

It is a work around. But it seems it is not so  efficient.

**Comment by codelipenghui** [comment]
@hoswey Yes, it's not efficient for handling this case but seems this is only a way to achieve the purpose. Supports update delay time of the message will introduce more complex in Pulsar or a message system.

**Comment by hoswey** [comment]
> @hoswey Yes, it's not efficient for handling this case but seems this is only a way to achieve the purpose. Supports update delay time of the message will introduce more complex in Pulsar or a message system.

Ok.
