### ISSUE TITLE
Apply-config-from-env.py to comment values

### ISSUE THREAD

**Issue by klwilson227** [apache/pulsar#10058]
When values exist in the environment that match commented out keys in the file those key values should be placed into the file. It is common practice to leave default values commented out in the configuration files. These values cannot be replaced by apply values currently. For example bookkeeper has a mix of commented and I commented values to adjust disk almost full checks. One one may be modified since it is not commented. However it’s value if modified conflicts with the other commented values. This leads to a frustrating support situation in which the end user would need to jump through hoops trying to get a uncommented value into the image so that the script could  apply the value.

A small adjustment to the parsing can handle the use case. And leave the values as commented if not in the env.

**Comment by klwilson227** [comment]
Please assign back to me I have begun work on code change.

**Comment by klwilson227** [comment]
https://github.com/apache/pulsar/pull/10060

**Comment by codelipenghui** [comment]
close via #10060
