### ISSUE TITLE
Use EventLoopGroup for internal consumers on PartitionedConsumerImpl

### ISSUE THREAD

**Issue by sschepens** [apache/pulsar#1007]
With the changes from #963 `PartitionedConsumerImpl` uses Consumers in a non-blocking way, we could make `PartitionedConsumerImpl` instantiate `ConsumerImpl` with an `EventLoop` from `EventLoopGroup`.

I had a go at this, but a few questions raised.

- I realised we only use a single thread executor per Consumer instance, is there a reason for this?
- I think it would be nice to be able to disable `externalExecutorProvider` in `PulsarClientImpl`, maybe by setting `conf.getListenerThreads() == 0`, I imagine this would either use EventLoopGroup for getting Executors. Another option would be to allow to customize ExecutorProvider. This could be useful for apps that have fast, nonblocking listeners.
- If implementing the previous, it would probably make more sense to use `MoreExecutors.newDirectExecutorService()` though we probably shouldn't use a single instance but a few, but it could be hard to track them and shut them down.

What are your opinions?

**Comment by merlimat** [comment]
> I realised we only use a single thread executor per Consumer instance, is there a reason for this? 

The main reason is to retain the message ordering. This might not be important in a shared subscription but it is for the other types.

> I think it would be nice to be able to disable externalExecutorProvider in PulsarClientImpl 

Sounds good to me. As long as we document the behavior and the user knows that it has to do non-blocking operations (or else slow down potentially the consumption for other consumers in the same client).

> If implementing the previous, it would probably make more sense to use MoreExecutors.newDirectExecutorService() though we probably shouldn't use a single instance but a few, but it could be hard to track them and shut them down.

I think that `newDirectExecutorService()` should just return a simple lambda that execute directly, there shouldn't be the need to have multiple instances of it, no?

**Comment by sschepens** [comment]
If we need ordering the probably it makes more sense to use `EventLoopGroup` as an executor rather than using DirectExecutors

**Comment by sijie** [comment]
any updates @sschepens , @merlimat ?

**Comment by sijie** [comment]
close it since there is no activities. please reopen it if there is anything required to be done here.
