### ISSUE TITLE
Ability to temporarily pause topic replication.

### ISSUE THREAD

**Issue by gauravAshok** [apache/pulsar#10137]
**Is your feature request related to a problem? Please describe.**
Currently, there is no provision to temporarily pause a topic's geo-replication. 

The namespace's "--clusters" configuration acts as both, a way to configure the list of clusters across which geo-replication will happen and a way to tell where its topics will be available for msg production and consumption.

Removing a cluster from the namespace's "--clusters" list stops the replication and also makes the topic from that cluster unavailable.

**Describe the solution you'd like**
It will be preferable to have the replication and availability to be configurable separately. These can be configured at the namespace level, but if the replication part is configurable at topic level too, that will give us much better control. With the replication lever, we should be able to pause the replication too.

**Describe alternatives you've considered**
Tried namespace's --cluster config and wasn't helpful. Also thought of a way to "stop" the topic's replicating subscription as a way to pause the replication, but didn't find an api for it in admin client.

**Additional context**
None.

**Comment by codelipenghui** [comment]
Implemented in #12136
