### ISSUE TITLE
Partitioned topics not served enough active brokers

### ISSUE THREAD

**Issue by thanhcb** [apache/pulsar#10143]
**Describe the bug**
I have 3 active brokers in the picture, using pulsar-admin brokers list to show
![image](https://user-images.githubusercontent.com/34120284/113657748-c81e8100-96c8-11eb-95e0-9fa62cb22ff1.png)
When i create partitioned topics with number of partitions for the topic is 8, using pulsar-admin topics partitioned-lookup
![image](https://user-images.githubusercontent.com/34120284/113657810-eb493080-96c8-11eb-9439-e26d67325083.png)
it only serves 2 of 3 active brokers,
Pulsar version: 2.7.0
**Expected behavior**
Serving all 3 active brokers

**Comment by michaeljmarshall** [comment]
@thanhcb - I have some questions based on what you provided. Are you actively producing to all topic partitions? Can you also provide the current number of bundles for the namespace? Do you have any bundle limits on the topic's namespace? Further, what is your bundle splitting configuration?

**Comment by thanhcb** [comment]
i thought each of internal topics was split across to all active brokers at first, after reading the bundles you said, maybe i have some misunderstanding here.
The bundles in broker.conf i keep all default

# When a namespace is created without specifying the number of bundle, this
# value will be used as the default
defaultNumberOfNamespaceBundles=4

# enable/disable namespace bundle auto split
loadBalancerAutoBundleSplitEnabled=true

# enable/disable automatic unloading of split bundles
loadBalancerAutoUnloadSplitBundlesEnabled=true

# maximum topics in a bundle, otherwise bundle split will be triggered
loadBalancerNamespaceBundleMaxTopics=1000

Could you explain what is the link between the configs and the issue i wrote above? Why the internal topics in partitioned topic is not split across all the brokers? Thanks u so much

**Comment by michaeljmarshall** [comment]
The following documentation describes Pulsar's load balancing feature: https://pulsar.apache.org/docs/en/2.7.0/administration-load-balance/. I think it should help explain these configurations and their impact on your cluster. Note that if your topics do not have much data flowing through them, they will not get unloaded, which means they will not get distributed across all 3 brokers. Feel free to let me know if you have follow up questions.

**Comment by thanhcb** [comment]
ok, i've got it, close issue
