### ISSUE TITLE
Support bytes message key

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#1016]
Currently the message key is string. It would be good to make the key also be bytes backed. so people can configure a SerDe on the message key, which message router can use to compute which partitions a message should be routed to.

It should be considered together with schema registry.

**Comment by sijie** [comment]
based on the discussion before, we don't want to support bytes key. current string key is already enough to support bytes. so close it for now.

**Comment by sijie** [comment]
this is being implemented in #2612

**Comment by ivankelly** [comment]
This is done in #2612

**Comment by ivankelly** [comment]
This is done in #2612
