### ISSUE TITLE
[Doc] generate 2.7.2 docs

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#10236]
2.7.1 has been released and the Pulsar is on the way to 2.7.2 (and 2.8.0). 

Since 2.7.2 docs might be different from 2.7.1, but now we[ do not have the 2.7.2 docs](https://github.com/apache/pulsar/tree/master/site2/website/versioned_docs) and can not update the 2.7.2 docs if needed. Consequently, 2.7.2 docs need to be generated.

**Comment by Anonymitaet** [comment]
Hi @eolivelli seems that you are the release manager of Pulsar 2.7.2? If so, would you like to generate 2.7.2 docs? Thanks

**Comment by eolivelli** [comment]
Okay. Let me try to do it

**Comment by Anonymitaet** [comment]
@eolivelli thanks! FYI: @Jennifer88huang is documenting the doc release process for a minor release.

**Comment by eolivelli** [comment]
Thanks

**Comment by Jennifer88huang** [comment]
I'll share the link when it's ready. Thank you all.

**Comment by eolivelli** [comment]
it looks to me that here https://github.com/aahmed-se/pulsar-wiki/blob/master/Release-process.md it reads that we should update the website only after the release has been closed

**Comment by Anonymitaet** [comment]
Hi @eolivelli, @Jennifer88huang is updating the release process. 

We'd better generate docs for x.y.z after x.y.z-1 is released. Reason:
If we have docs specific for 2.7.2, and if we do not generate docs [after 2.7.1 is released] and [before 2.7.2 is released], then users can not update 2.7.2 docs. 
(P.S. for docs, a new release is a full set of a previous one. For example, 2.7.2 is a full set of 2.7.1.)

BTW, if we have docs appropriate for 2.7.1, 2.7.2, and 2.8.0, then users can update 2.7.1, 2.7.2, and master accordingly. 

@Jennifer88huang Please correct me if I'm incorrect, thanks.

**Comment by eolivelli** [comment]
@Anonymitaet 
makes sense to me.
let me create the structure for 2.7.2, I will send a PR

**Comment by Jennifer88huang** [comment]
@eolivelli thank you for making the effort. I've updated the workflow at https://github.com/apache/pulsar/wiki/Release-process#update-the-site-for-minor-releases
@Anonymitaet thank you for driving the process.
