### ISSUE TITLE
Failed to produce/consumer partitioned topic if updated the topic partition number

### ISSUE THREAD

**Issue by dragonls** [apache/pulsar#10300]
**Describe the bug**
While using partitioned topic, if we control the authorization of the topic in topic level and update the topic partiton number, new producer/consumer will recerive auth error `org.apache.pulsar.client.api.PulsarClientException$LookupException: Proxy Client is not authorized to Lookup`

**To Reproduce**
1. Having a pulsar cluster using JWT for authentication
2. Create a partitionen topic `persistent://test/auth/topic` with 2 partitions: `./bin/pulsar-admin topics create-partitioned-topic -p 2 persistent://test/auth/topic`
3. Grant `produce` and `consume` permissions to role `roleA`: `./bin/pulsar-admin topics grant-permission --role roleA --actions produce,consume persistent://test/auth/topic`
4. Try produce and consume this topic using subscription `roleA-test`, shoule be normal till now
5. Update the topic partition number: `./bin/pulsar-admin topics update-partitioned-topic -p 4 persistent://test/auth/topic`
5. Try to use role `roleA` to produce/consume the topic using subscription `roleA-test` again, we will get error:
   - produce get error: `org.apache.pulsar.client.api.PulsarClientException$LookupException: Proxy Client is not authorized to Lookup`
   - consume get error: `org.apache.pulsar.client.api.PulsarClientException$LookupException: Failed to subscribe persistent://test/auth/topic with 4 partitions`

**Expected behavior**
After updating the partitioned topic, new producer/consumer of this topic should not get error.

**Additional context**
I tried branch 2.7 and master, both having this bug.

**Comment by linlinnn** [comment]
This issue is caused by when updated the partition number of topic, triggering `TopicsPartitionChangedListener` look up the partition number of topic, but `roleA` do not have been granted `LOOKUP`

**Comment by dragonls** [comment]
> This issue is caused by when updated the partition number of topic, triggering `TopicsPartitionChangedListener` look up the new partition number of topic, but `Proxy Client` do not have been granted `LOOKUP`

Is that any solution or suggestion for this?

**Comment by linlinnn** [comment]
@dragonls you can add such config in broker.conf
```
proxyRoles=my-proxy-role
superUserRoles=my-proxy-role
```

**Comment by dragonls** [comment]
> @dragonls you can add such config in broker.conf
> 
> ```
> proxyRoles=my-proxy-role
> superUserRoles=my-proxy-role
> ```

@linlinnn I am using pulsar on k8s, and tried the config as you said. Still getting the same error.
 We can look into the exception, https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java#L408 , it is not about pulsar proxy component but the authorization control.

**Comment by dragonls** [comment]
There are 2 ways to solve this bug:
1. After updating the partition num of the topic, try to regrant the permissions of the topic. It is to say that in the end of [`org.apache.pulsar.broker.admin.impl.PersistentTopicsBase#updatePartitionedTopic`](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L3446) , try to get the topic level permissions of the topic and regrant them by calling `internalGrantPermissionsOnTopic`.
2. In [`org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider#checkPermission`](https://github.com/apache/pulsar/blob/889b9b8e5efc62d2d0cbc761205fba5759c97af0/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java#L394) , for example, if the topic is a sub-partitioned topic `persistent://test/auth/topic-partition-4` of the partitioned topic `persistent://test/auth/topic`, try to check the permission of  `persistent://test/auth/topic` again.

I can not tell which solution is better.
I prefer the first solution but that may change the permissions of previous sub-partitioned topics.

**Comment by linlinnn** [comment]
Emm.. If the permission granularity is partition, you are right.
