### ISSUE TITLE
[Documentation] Add documentation about Pulsar Broker 64-bit JVM requirement

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#10311]
**Is your enhancement request related to a problem? Please describe.**

Pulsar Broker isn't thread safe when running on 32 bit JVM. The requirement is a 64-bit JVM. This isn't currently documented.

**Describe the solution you'd like**

Document the requirement of using a 64-bit JVM.

**Additional context**

See comments in discussion https://github.com/apache/pulsar/pull/10280#discussion_r616891925

**Comment by Anonymitaet** [comment]
@lhotari thanks for raising this up. Would you like to update the docs? Then I'd like to help review, thanks.

**Comment by Anonymitaet** [comment]
@lhotari does this change apply to both Pulsar 2.7.2 and 2.8.0?

**Comment by lhotari** [comment]
> @lhotari does this change apply to both Pulsar 2.7.2 and 2.8.0?

yes.

**Comment by Anonymitaet** [comment]
@lhotari thanks for your code work. I’ve added the doc accordingly (https://github.com/apache/pulsar/pull/10605). Could you please help review it? Thanks
