### ISSUE TITLE
[Blog] announce Pulsar 2.7.2

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#10355]
Hi @eolivelli 

I see you are cutting the 2.7.2 release, thanks for your great effort!

To announce the new release officially, would you like to write a blog for 2.7.2 as we did before? After that, I can help review.

In this blog, I suggest highlighting major enhancements/bug fixes and adding necessary explanations for them instead of putting every enhancement/bug fix in it. In this way, users can catch up the points quickly rather than being overwhelmed by information. If they want to know the complete list, they can check the release note.

FYI: you can take the [previous release blogs ](https://pulsar.apache.org/blog/) as references.

Any thoughts on this?

**Comment by eolivelli** [comment]
Sure. I am happy to do it

**Comment by Anonymitaet** [comment]
@eolivelli thanks. You can ping me once you finish.

**Comment by eolivelli** [comment]
Sure.
I am still fixing a few problems with the release

**Comment by tuhaihe** [comment]
Hi @eolivelli , I have an idea that shall we add a new module named "List of Contributors" at the end of the blog? This module could show the contributors involved in this release. [Flink example](https://flink.apache.org/news/2021/05/03/release-1.13.0.html) can be a reference. How about that?

**Comment by Anonymitaet** [comment]
Done.
