### ISSUE TITLE
pulsar-broker not writing in log

### ISSUE THREAD

**Issue by stanbog** [apache/pulsar#10434]
Hello,

We have a pulsar-broker cluster made from 3 nodes.
We would like to forwards the logs into splunk so we are reading the file` /opt/pulsar/logs/pulsar-broker.log`.
However, the pulsar-broker service doesn't write anything in this file. The only logging that we have is the systemd logging via journalctl.

If we remove the` pulsar-broker.log` file and restart the service, the file will be re-created again but it will stay empty, so the service knows about the logs location, but for some reason cannot write there.

The permissions look correct:
```
[root@sveverdpulsar01 logs]# ls -l /opt/pulsar/logs/pulsar-broker.log
-rw-r--r-- 1 pulsar pulsar 0 Apr 29 08:39 /opt/pulsar/logs/pulsar-broker.log
```

Those are the log settings that we have in the binary:

```
# log directory & file
PULSAR_LOG_DIR=${PULSAR_LOG_DIR:-"$PULSAR_HOME/logs"}
PULSAR_LOG_APPENDER=${PULSAR_LOG_APPENDER:-"RoutingAppender"}
PULSAR_LOG_ROOT_LEVEL=${PULSAR_LOG_ROOT_LEVEL:-"info"}
PULSAR_LOG_LEVEL=${PULSAR_LOG_LEVEL:-"info"}
PULSAR_ROUTING_APPENDER_DEFAULT=${PULSAR_ROUTING_APPENDER_DEFAULT:-"Console"}
```

Any help would be appriciated.

Thank you.

**Comment by lhotari** [comment]
logging to the log file can be achieved by setting `PULSAR_ROUTING_APPENDER_DEFAULT=RollingFile` . 
The roll-over happens once per day or when the size of the log file reaches 1GB. This can be adjusted by customizing the `conf/log4j2.yaml` file.

**Comment by stanbog** [comment]
Thank you.
That indeed was the issue.
