### ISSUE TITLE
Discovery Service Lookup does not work with Partitioned Non-Persistent Topics

### ISSUE THREAD

**Issue by wmccarley** [apache/pulsar#10443]
**Describe the bug**

Current implementation of the Discovery Service hard-codes the topic domain as persistent:

https://github.com/apache/pulsar/blob/master/pulsar-discovery-service/src/main/java/org/apache/pulsar/discovery/service/BrokerDiscoveryProvider.java#L108

This means the lookup of a partitioned non-persistent topic will return zero instead of >0 partitions. The pulsar client will try to connect to the partitioned topic as if it were a normal topic.

If the cluster has geo-replication on the producer will error out with:
org.apache.pulsar.client.api.PulsarClientException$ProducerBusyException: non-persistent://X/Y/Z failed to start replicator for ABCD

I believe the correct implementation should use:

`topicName.getDomain().value()` instead of hard-coding `"persistent"`

**Comment by MarvinCai** [comment]
seems a easy fix, are you interested in working on it?
