### ISSUE TITLE
[Docs] Need docs for how to configure function logging

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#10458]
PR https://github.com/apache/pulsar/pull/10389 enabled configurable function logging. 
However, this capability is not documented for users.
We need to update the docs pages to at least inform users that they can use the XML file to configure the function log level.

**Comment by Anonymitaet** [comment]
@devinbost thanks for your code work. Could you please help add docs accordingly? Then I can help review, thanks

**Comment by Anonymitaet** [comment]
Hi @devinbost thanks for your great work!
I'm adding docs for this PR but have some questions documented [here](https://docs.google.com/document/d/1FgeagvB7Nqefe5zxu--wKlEYzr3OoiOp3dWvEGGSRjM/edit), could you please take a look? Many thanks!

**Comment by Anonymitaet** [comment]
Done in https://github.com/apache/pulsar/pull/10617
