### ISSUE TITLE
HasMessageAvailable incorrectly returns "true" when there are no available messages

### ISSUE THREAD

**Issue by Lanayx** [apache/pulsar#10515]
**Describe the bug**
I want to read messages starting from some timestamp, for that I use `startMessageFromRollbackDuration` configuration. If there are messages available i expect `hasMessageAvailable` to return true, and if no messages are available it should return false. However it still returns true in the latter case.

**To Reproduce**

```java
            Producer<byte[]> producer = client.newProducer()
                    .topic(topicName)
                    .enableBatching(false)
                    .sendTimeout(0, TimeUnit.MILLISECONDS)
                    .create();
            MessageId msgId = producer.newMessage().value(("Hello").getBytes()).send();
            Thread.sleep(4000); // wait 4 seconds

            Reader<byte[]> reader = client.newReader()
                .topic(topicName)
                .startMessageFromRollbackDuration(1, TimeUnit.SECONDS)
                .create();
            Boolean result = reader.hasMessageAvailable();
            System.out.printf("Result: %b\n", result); // returns true
```

**Expected behavior**
HasMessageAvailable should return false in the case above

**Additional context**
Client and Broker version 2.7.1 (reproduced in previous versions as well)

**Comment by gaozhangmin** [comment]
please assign to me, if no one working on this

**Comment by Technoboy-** [comment]
Fixed by https://github.com/apache/pulsar/pull/16443
