### ISSUE TITLE
CLI tools should have a command for showing the currently running/installed version.

### ISSUE THREAD

**Issue by bdunn313** [apache/pulsar#10577]
**Is your enhancement request related to a problem? Please describe.**
When using the pulsar suite of CLI tools, there is no way to find the currently installed version of the tool. If one exists, the mechanism is undocumented and doesn't follow CLI conventions of displaying the version with the `-v` short flag or `--version` flag.

**Describe the solution you'd like**
When running any of the pulsar CLI tools, passing in the flag `-v` or `--version` should show the current version of that tool.

**Describe alternatives you've considered**
- Showing the version while running the `help` command would be helpful, but the convention is described above.
- At a minimum, the version could be tracked in a README associated with the pulsar project or adjacent to the tool / in the `bin` directory, but this is not ideal.

**Additional context**
This is an important tool for debugging purposes. I was looking to record and file a separate issue, and I wanted to provide specific information about the version of `pulsar-admin` I was running, but I could not find a way to do so.

**Comment by linlinnn** [comment]
Related [PR-9975](https://github.com/apache/pulsar/pull/9975)

**Comment by bdunn313** [comment]
@linlinnn I tried to figure out if this was already tracked as an issue, but I didn't find this one! Should I close this as a duplicate?

**Comment by linlinnn** [comment]
@bdunn313 We already have this feature in [PR-9975](https://github.com/apache/pulsar/pull/9975) which will be released on 2.7.2.

**Comment by bdunn313** [comment]
> @bdunn313 We already have this feature in [PR-9975](https://github.com/apache/pulsar/pull/9975) which will be released on 2.7.2.

Awesome! Since this is already tracked in a separate issue and PRed, I'll close this one! Thank you for clarifying for me!
