### ISSUE TITLE
Cannot produce message to those topics without  setting topic policies, when enable preciseTopicPublishRateLimiterEnable

### ISSUE THREAD

**Issue by gaozhangmin** [apache/pulsar#10603]
**Describe the bug**
Topics without setting topic level publishRate and namespace level publishRate(without setting policies or rate  <= 0), cannot produce message to it. when setting:
preciseTopicPublishRateLimiterEnable=true. I found those topics  are throttled by default.

**to reproduce**
enable 
preciseTopicPublishRateLimiterEnable=true
systemTopicEnabled=true
topicLevelPoliciesEnabled=true

create a topic without setting topic level policies and namespace level policies:
bin/pulsar-perf produce -o 10000 -p 100000 -s 1024  -r 1000 -bm 1 1p

throttling should be disabled by default when topics level policies are not set.

**Comment by lhotari** [comment]
several problems are fixed in draft PR #10384 .

**Comment by gaozhangmin** [comment]
this issue is caused by:

when topic and namespace publish rate are not set or its value <=0,  updatePublishDispatcher would return PublishRateLimiter.DISABLED_RATE_LIMITER. which caused 
`return preciseTopicPublishRateLimitingEnable && !this.topicPublishRateLimiter.tryAcquire(numberMessages, bytes);`always true,

**Comment by lhotari** [comment]
> this issue is caused by:
> 
> when topic and namespace publish rate are not set or its value <=0, `updatePublishDispatcher` would return `PublishRateLimiter.DISABLED_RATE_LIMITER`. which caused
> `@Override public boolean isTopicPublishRateExceeded(int numberMessages, int bytes) { return preciseTopicPublishRateLimitingEnable && !this.topicPublishRateLimiter.tryAcquire(numberMessages, bytes); }`
> always true.

@gaozhangmin Thanks for pointing that out. Yes, it's a clear issue. I'll include the fix to #10384 since it fixes various other preciseTopicPublishRate limiter issues and those fixes are needed for using the feature.

**Comment by lhotari** [comment]
I added a fix to #10384
