### ISSUE TITLE
QA: Pulsar multi-topic subscriptions questions

### ISSUE THREAD

**Issue by leiless** [apache/pulsar#10610]
Hi, Pulsar developers, I have a question about docs of multi-topics subscriptions.

> **No ordering guarantees across multiple topics** When a producer sends messages to a single topic, all messages are guaranteed to be read from that topic in the same order. However, these guarantees do not hold across multiple topics. So when a producer sends message to multiple topics, the order in which messages are read from those topics is not guaranteed to be the same.
https://pulsar.apache.org/docs/en/concepts-messaging/#multi-topic-subscriptions

My question is, in a multi-topic subscription, does the message order within a specific topic in the same order?
Say, my topics are `persistent://foobar/.*`, so does messages in topic `persistent://foobar/queue1` came in same order?

My assumption is that, for a specific topic within the regex subscription, the order is the same. however, messages from multiple topics may be interleaved.

--

(Claim: this issue isn't an enhancement issue since I cannot find an appropriate label)

**Comment by linlinnn** [comment]
We guarantee the order of message from the same partition(One topic may have multi partitions).
