### ISSUE TITLE
[Java][Client] Important behaviour changes on empty key from 2.7.x to 2.8.x

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#10625]
In Pulsar 2.8 when you send a message without a key it is received with a null key.
In Pulsar 2.7  when you send a message without a key it is received with a EMPTY key.

**To Reproduce**

Add this test case to org.apache.pulsar.schema.SchemaTest.java, it passes on 2.8, it fails on 2.7.2

```
    @Test
    public void testNullKey() throws Exception {
        final String tenant = PUBLIC_TENANT;
        final String namespace = "test-namespace-" + randomName(16);
        final String topicName = "test-schema-" + randomName(16);

        final String topic = TopicName.get(
                TopicDomain.persistent.value(),
                tenant,
                namespace,
                topicName).toString();

        admin.namespaces().createNamespace(
                tenant + "/" + namespace,
                Sets.newHashSet(CLUSTER_NAME));

        admin.topics().createPartitionedTopic(topic, 2);

        Producer<String> producer = pulsarClient
                .newProducer(Schema.STRING)
                .topic(topic)
                .create();

        Consumer<String> consumer = pulsarClient.newConsumer(Schema.STRING)
                .subscriptionName("test-sub")
                .topic(topic)
                .subscribe();

        producer.send("foo");

        Message<String> message = consumer.receive();
        assertNull(message.getKey());
        assertEquals("foo", message.getValue());
    }
```

**Expected behaviour**

It would be better to see a "null" key, as now it is in 2.8,
but 2.7 users that will upgrade to latest version will see this behaviour that would lead to NPEs and unpredictable consequences

**Suggestions**
Mimic 2.7 behaviour on 2.8, but setting an "empty string" key as default.
This is only a mitigation because it looks like in 2.7.2 if you set a NULL key you still see a empty string on the Consumer side

**Comment by codelipenghui** [comment]
I have added the `release/note-required` label, I agree the correct behavior is return null to the consumer side if the message without a key.
