### ISSUE TITLE
Documentation: Suggest adding documentation for supported bundle split algorithms 

### ISSUE THREAD

**Issue by frankjkelly** [apache/pulsar#10627]
**Is your enhancement request related to a problem? Please describe.**
Add documentation for how to choose between load balancing algorithms 

**Describe the solution you'd like**
* `supportedNamespaceBundleSplitAlgorithms` supports two algorithms for namespace bundle split `range_equally_divide,topic_count_equally_divide`
* Suggest adding some documentation around that to here https://pulsar.apache.org/docs/en/administration-load-balance/ including (1) documentation how each algorithm works and how each algorithm can be adjusted (any parameters to control operation) (2) documentation how and when to choose between the default `range_equally_divide` and `topic_count_equally_divide`

CC: @Jennifer88huang

**Comment by Anonymitaet** [comment]
@frankjkelly thanks for raising this up. Would you like to add docs accordingly? Then we can help review, thanks

**Comment by frankjkelly** [comment]
@Anonymitaet I would love to but I really do not have the expertise to understand how these mechanisms work at a detailed level and to provide some guidance on how to choose between them.

**Comment by Anonymitaet** [comment]
@frankjkelly we have documented the usage in `broker.conf` as below:

```
# Supported algorithms name for namespace bundle split.
# "range_equally_divide" divides the bundle into two parts with the same hash range size.
# "topic_count_equally_divide" divides the bundle into two parts with the same topics count.
supportedNamespaceBundleSplitAlgorithms=range_equally_divide,topic_count_equally_divide
```

Does this work for you?

**Comment by Anonymitaet** [comment]
I have a few questions:

- How does each algorithm work with other [split bundle configurations](https://github.com/apache/pulsar/blob/b1ff552333c20b081e914766ba54a17037e3231f/conf/broker.conf#L988)?

- Is each algorithm limited by other split bundle configurations?

**Comment by frankjkelly** [comment]
Thanks @Anonymitaet exactly - it gets pretty interesting to understand how all those parameters will interact.
I'm particularly interested in how each algorithm behaves when we add brokers (we're hoping to implement Kubernetes autoscaling)- how quickly would those brokers be discovered and how  quickly some load would be redirected to those new brokers.
In my limited experience with `range_equally_divide` it's not until we hit the `loadBalancerBrokerOverloadedThresholdPercentage` and the broker is overloaded that some namespace bundles will be split and offloaded but at that point usually the load on the broker is pretty high so that the offload seems to be "expensive" or at least take a long time and then our Pulsar Clients start timing out.
For us we'd rather have a way that was a faster balancing (but perhaps less precisely load balanced) than one that was more accurately load balanced but takes longer to shed load. Again we're pretty new to this but would appreciate to hear perspectives or pointers to code. Thanks!

**Comment by congbobo184** [comment]
> I have a few questions:
> 
> * How does each algorithm work with other [split bundle configurations](https://github.com/apache/pulsar/blob/b1ff552333c20b081e914766ba54a17037e3231f/conf/broker.conf#L988)?
>   ![image](https://user-images.githubusercontent.com/50226895/119072811-ba298300-ba1e-11eb-9264-c0c0074c4a1b.png)
> * Is each algorithm limited by other split bundle configurations?

**Comment by congbobo184** [comment]
@Anonymitaet each algorithm is affected by these configurations the same. `range_equally_divide` use hash range, `topic_count_equally_divide` is evenly distributed.

**Comment by frankjkelly** [comment]
Thanks @codelipenghui this is super helpful!
