### ISSUE TITLE
[Performance] DimensionStats implementation uses inefficient Prometheus client method CollectorRegistry.getSampleValue which is only intended for use in unit tests

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#10654]
**Is your enhancement request related to a problem? Please describe.**

The Prometheus https://github.com/prometheus/client_java/blob/master/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java class is creating exceptions as part of ordinary execution path. This causes an additional performance overhead.

example in exceptions flamegraph:
![image](https://user-images.githubusercontent.com/66864/118958813-6d847000-b96a-11eb-881f-c8e7e71df0f6.png)

it also looks like the same metrics are gathered multiple times:

![image](https://user-images.githubusercontent.com/66864/118959504-0fa45800-b96b-11eb-9e7c-b1b1e9d0883e.png)

**Describe the solution you'd like**

The javadoc of CollectorRegistry.getSampleValue method states: ["This is inefficient, and intended only for use in unittests.".](https://github.com/prometheus/client_java/blob/8fcc7bc03dfbabd0c15776640d5fe52942aa9309/simpleclient/src/main/java/io/prometheus/client/CollectorRegistry.java#L261) . The [usage of the CollectorRegistry.getSampleMethod method in DimensionStats implementation](https://github.com/apache/pulsar/blob/102fa9de03509b86e47f58ab8e1c0dde2095da3b/pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/DimensionStats.java#L107-L108) should be replaced somehow. Perhaps this causes a larger refactoring?

**Comment by lhotari** [comment]
There seems to be a design issue in how org.apache.pulsar.broker.stats.DimensionStats is implemented. What happens it that for each call to the getDimensionX methods, all samples are collected for all Prometheus client collectors and filtered. 

https://github.com/prometheus/client_java/blob/8fcc7bc03dfbabd0c15776640d5fe52942aa9309/simpleclient/src/main/java/io/prometheus/client/CollectorRegistry.java#L258-L274

The javadoc of getSampleValue method states: "This is inefficient, and intended only for use in unittests.".

This is amplifying the performance issue in the Prometheus client's hotspot.StandardCollector implementation.

**Comment by lhotari** [comment]
@addisonj Would you also like to take this one?

**Comment by lhotari** [comment]
@rdhabalia Do you have suggestions for fixing this performance issue in broker's DimensionStats implementation? The javadoc of CollectorRegistry.getSampleValue method states: ["This is inefficient, and intended only for use in unittests.".](https://github.com/prometheus/client_java/blob/8fcc7bc03dfbabd0c15776640d5fe52942aa9309/simpleclient/src/main/java/io/prometheus/client/CollectorRegistry.java#L261)

**Comment by rdhabalia** [comment]
Yes, `CollectorRegistry::getSampleValue()` can be inefficient and we can improve it but just wanted to understand performance impact. It is used to generate Prometheus stats and that is called at every 60 secs by dedicated [Pulsar-stats thread](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarStats.java#L183) so, it should not impact client flow. so, can you please confirm if you are seeing any performance impact in broker due to this usage?

**Comment by lhotari** [comment]
> Yes, `CollectorRegistry::getSampleValue()` can be inefficient and we can improve it but just wanted to understand performance impact. It is used to generate Prometheus stats and that is called at every 60 secs by dedicated [Pulsar-stats thread](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarStats.java#L183) so, it should not impact client flow. so, can you please confirm if you are seeing any performance impact in broker due to this usage?

I haven't measured the performance impact for an end-to-end scenario. This problem shows up when profling exceptions. I don't think this is a major performance issue for Pulsar users.
