### ISSUE TITLE
[Performance] AuthenticationProviderToken.authenticateToken (JWT token parsing) creates a lot of allocations

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#10652]
**Is your enhancement request related to a problem? Please describe.**

The performance of `AuthenticationProviderToken.authenticateToken` is bad. It seems that the JWT parsing classes get loaded for each call

This shows up in the allocation flame graph:
![image](https://user-images.githubusercontent.com/66864/118953740-c43b7b00-b965-11eb-80ac-de446335a0f7.png)

**Describe the solution you'd like**

Optimize the performance so that the parser is cached and isn't instantiated for each call.

**Comment by addisonj** [comment]
I can take this
