### ISSUE TITLE
[Website + Doc] Generate 2.7.3 docs

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#10665]
The community is preparing to announce the 2.7.2 release (almost done) and Pulsar is on the way to 2.7.3 (and 2.8.0). 

Since 2.7.3 docs might be different from 2.7.2, but now we [do not have the 2.7.3 docs](https://github.com/apache/pulsar/tree/master/site2/website/versioned_docs) and can not update the 2.7.3 docs if needed (in fact, now we have a [PR](https://github.com/apache/pulsar/pull/10638) labeled w/ 2.7.3 which needs to add docs.) 

Consequently, 2.7.3 docs need to be generated.

**Comment by Anonymitaet** [comment]
@eolivelli would you like to generate the 2.7.3 docs? Many thanks.

**Comment by Anonymitaet** [comment]
@wolfstudy would you like to generate the 2.7.3 docs? Many thanks.

**Comment by wolfstudy** [comment]
> @wolfstudy would you like to generate the 2.7.3 docs? Many thanks.

ok, will process it.

**Comment by eolivelli** [comment]
@wolfstudy @Anonymitaet are you planning to cut a new 2.7.3 soon ?

**Comment by Anonymitaet** [comment]
@eolivelli no, we just got [doc requirement](https://github.com/apache/pulsar/pull/10638) for 2.7.3 and want to process it.
