### ISSUE TITLE
Cannot completely delete partitioned-topic when frequently and repeatedly created and deleted a topic

### ISSUE THREAD

**Issue by wuzhanpeng** [apache/pulsar#10687]
**Describe the bug**
The admin command can not completely delete partitioned-topic when I repeat this process (created a specific topic and deleted it) frequently and constantly. The partitioned-topic is gone but its partition (X-partition-0) still existed.

**To Reproduce**
My reproduced test:
```java
String url = "http://brokerA:8080";
//String url = "http://brokerB:8080";
PulsarAdmin admin = PulsarAdmin.builder()
        .serviceHttpUrl(url)
        .build();

String name = "persistent://public/default/X";

for (int i = 0; i < 100; i++) {
    System.out.println("Round: " + i);
    admin.topics().createPartitionedTopic(name, 1);

    // method existTopic to determine if a specific topic exists
    if (existTopic(admin, name)) {
        admin.topics().deletePartitionedTopic(name);
        if (!existTopic(admin, name)) {
            continue;
        } else {
            System.err.println("Cannot delete");
            break;
        }
    } else {
        System.err.println("Cannot create");
        break;
    }
}
```

Sometimes it works fine, and sometimes I get error output like:
```
Round: 0
Round: 1
Cannot delete
```

**Expected behavior**
Ability to create and delete topics continuously.

**Screenshots**
After I executred the delete command:
```bash
bin/pulsar-admin topics delete-partitioned-topic persistent://public/default/X
```
I can get the output like:
```bash
$ bin/pulsar-admin topics list public/default
"persistent://public/default/X-partition-0"    <--- the problem occurred
"persistent://public/default/A-partition-0"
"persistent://public/default/B-partition-0"
"persistent://public/default/B-partition-2"
"persistent://public/default/B-partition-1"
"persistent://public/default/B-partition-3"
$ bin/pulsar-admin topics list-partitioned-topics public/default
"persistent://public/default/A"
"persistent://public/default/B"
```

**Additional context**
Our pulsar test cluster has 2 nodes and its version is `2.8.0-rc-202105182205`. What is confusing is that sometimes there are no error conditions. For example it may work well when make `PulsarAdminClient` connect to `brokerA`, or we fall into the problem situation when we connects to `brokerB`.

I hope to get some suggestions so that I can better fix this problem.

**Comment by hangc0276** [comment]
This issue has been addressed by #10862.
