### ISSUE TITLE
Support config remote clusters' TLS settings for geo-replicator

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#10693]
This issue is similar to #10242

**Is your feature request related to a problem? Please describe.**
Currently the pulsarClient for geo-replicator using the local cluster's TLS configuration in broker.conf. If the remote cluster is using a different TLS certificate, the geo-replicator will fail to connect.

**Describe the solution you'd like**
Add TLS parameters for each remote cluster to `ClusterData`, when adding a remote cluster, the TLS settings of the cluster could be configured.

**Comment by linlinnn** [comment]
@sijie Should we use unify configuration from remote cluster for geo-replicator, and remove the former logic that using the local cluster's configuration? or there are other reasons for keeping former logic.

**Comment by sijie** [comment]
@linlinnn We need to keep the former logic for backward compatibility.
