### ISSUE TITLE
Provide a nodejs client 

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#1070]
A lot of web services written in nodejs. It would be great to provide a nodejs client for interacting with pulsar cluster, without setting a rest gateway/proxy to handle the messages. This issue is to track the development of a nodejs client.

**Comment by sijie** [comment]
https://github.com/hangqi/node-hedwig can be a good reference for implementing a nodejs client.

**Comment by XiaoZYang** [comment]
I'm going to have a try.

**Comment by sneerin** [comment]
yeap, that would be really great

**Comment by mujimu** [comment]
bump

**Comment by mujimu** [comment]
more recent example of wrapping an underlying C++ lib as a node library:
https://github.com/Blizzard/node-rdkafka

**Comment by merlimat** [comment]
@mujimu There are indeed plans to start soon working on this. Thanks for the link. If you have JS experience it would be also good to have feedback on API ergonomics once we start working on it.

**Comment by thatcort** [comment]
Just a suggestion to use TypeScript, rather than JavaScript.

**Comment by nick-allen** [comment]
Agree with @thatcort, starting with TypeScript would be great. @merlimat has that work started and is it available to review anywhere?

**Comment by merlimat** [comment]
pinging @nkurihar on this

**Comment by nkurihar** [comment]
Hi, Yahoo Japan are now starting to develop Node.js client by wrapping C++ Client, and planning to open first minimal Pull-Request as soon as possible.

**Comment by sijie** [comment]
The nodejs client is under development at https://github.com/apache/pulsar-client-node . So close this issue here.
