### ISSUE TITLE
Cant update topic policies more than once

### ISSUE THREAD

**Issue by danielsinai** [apache/pulsar#10749]
**Describe the bug**
Cannot update topic policies more than once

It seems that broker failed to write to the __change_events internal topic. (From error logs)

**To Reproduce**
1. Create a pulsar multi cluster with topic policies enabled
2. Create tenant, namespace, topic
3. Update topic publish rate
4. Update it again
5. Wait for internal server error 500 to the admin client
6. Look at broker error logs for "Failed to create producer" to __change_events topic

**Expected behavior**
I should be able to update topic policies more than once

**Screenshots**
Broker Error logs:

![image](https://user-images.githubusercontent.com/51213812/120173168-739d0b00-c20c-11eb-9337-f313ffc1bc47.jpeg)

**Desktop (please complete the following information):**
 - OS: redhat 7.8

**Additional context**
My cluster is using JWT authentication and the broker is configured to use it with brokerClientAuthenticationParameters in order to be able to publish and read from __change_events topic

**Comment by galrose** [comment]
I'm working with Daniel on this and we realized this happens because preciseTopicPublishRateLimiterEnable=true sets everything to 0 but only takes effect after the first message, which is why we were able to write one message (change the policy once).
