### ISSUE TITLE
This is the bug causing both #10443 and #10449

### ISSUE THREAD

**Issue by yangou** [apache/pulsar#10789]
https://github.com/apache/pulsar/blob/e6bf50e919b2872dada0df2b0bb1fd6a5dafcf79/pulsar-discovery-service/src/main/java/org/apache/pulsar/discovery/service/BrokerDiscoveryProvider.java#L112

**Comment by lhotari** [comment]
Please provide more context in the title and issue description. It will waste everyone's time if issues are reported this way.
