### ISSUE TITLE
Pulsar Java Client 2.8.x does not work on Alpine Linux

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#10798]
**Describe the bug**
I am trying to upgrade from Pulsar Client 2.7.1 to Pulsar Client 2.8.0-SNAPSHOT an application that runs on a docker container based on jdk15-alpine, so with JDK15 and Alpine Linux.

It crashes with a core dump.

This is a regression because it used to work with Pulsar Client 2.7.1 and it prevents the application to be upgrade.

The problem seems related to Netty Native

```
---------------  S U M M A R Y ------------

Command Line: nb.jar run driver=pulsar yaml=/config/pulsar.yaml config=/config/config.txt cycles=1..100

Host: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, 10 cores, 23G, Alpine Linux v3.12
Time: Thu Jun  3 06:53:51 2021 UTC elapsed time: 3.377851 seconds (0d 0h 0m 3s)

---------------  T H R E A D  ---------------

Current thread (0x000055edc903bb00):  JavaThread "scenarios:001" [_thread_in_native, id=83, stack(0x00007f50991d6000,0x00007f50992d6aa8)]

Stack: [0x00007f50991d6000,0x00007f50992d6aa8],  sp=0x00007f50992d2318,  free space=1008k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x0000000000003efe
C  [liborg_apache_pulsar_shade_netty_transport_native_epoll_x86_648601706269064153288.so+0xb487]  netty_jni_util_JNI_OnLoad+0x67
C  [libjava.so+0xf4bd]  Java_jdk_internal_loader_NativeLibraries_load+0xdd
j  jdk.internal.loader.NativeLibraries.load(Ljdk/internal/loader/NativeLibraries$NativeLibraryImpl;Ljava/lang/String;ZZ)Z+0 java.base@15-ea
j  jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open()Z+57 java.base@15-ea
j  jdk.internal.loader.NativeLibraries.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)Ljdk/internal/loader/NativeLibrary;+256 java.base@15-ea
j  jdk.internal.loader.NativeLibraries.loadLibrary(Ljava/lang/Class;Ljava/io/File;)Ljdk/internal/loader/NativeLibrary;+51 java.base@15-ea
j  java.lang.ClassLoader.loadLibrary(Ljava/lang/Class;Ljava/io/File;)Ljdk/internal/loader/NativeLibrary;+31 java.base@15-ea
j  java.lang.Runtime.load0(Ljava/lang/Class;Ljava/lang/String;)V+61 java.base@15-ea
j  java.lang.System.load(Ljava/lang/String;)V+7 java.base@15-ea
j  org.apache.pulsar.shade.io.netty.util.internal.NativeLibraryUtil.loadLibrary(Ljava/lang/String;Z)V+5
v  ~StubRoutines::call_stub
V  [libjvm.so+0x75dbe2]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x2a2
V  [libjvm.so+0xb8066b]  invoke(InstanceKlass*, methodHandle const&, Handle, bool, objArrayHandle, BasicType, objArrayHandle, bool, Thread*) [clone .constprop.126]+0x85b
V  [libjvm.so+0xb81156]  Reflection::invoke_method(oopDesc*, Handle, objArrayHandle, Thread*)+0x106
V  [libjvm.so+0x814c83]  JVM_InvokeMethod+0xf3
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0 java.base@15-ea
```

**To Reproduce**
In order to reproduce you have to run a Java application that boots the Pulsar Client on a docker container with an imaged based on alpine linux.

**Expected behavior**
The client works as for Pulsar 2.7.x

**Desktop (please complete the following information):**
- Docker, Alpine linux

**Comment by eolivelli** [comment]
I am trying to upgrade Netty TC Native now, crossed fingers

**Comment by eolivelli** [comment]
Unfortunately the path #10800 does not fix the issue.
I opened a ticket on TC Native
https://github.com/netty/netty-tcnative/issues/649

**Comment by eolivelli** [comment]
I still see the same error.
let me do other tests.
I am sorry, I could not test and work on this during the weekend

**Comment by eolivelli** [comment]
I was wrong.
the stacktrace reads about native epoll and not tc-native, that is for TLS

**Comment by eolivelli** [comment]
it looks like that the problem is more about "epoll" and not about tc-native.
and also it looks like that with `adoptopenjdk/openjdk15:alpine-slim` docker image the problem does not reproduce

@codelipenghui I am testing about simply reverting "Rollback netty-tc-native version to 2.0.33.Final (#10833) "

**Comment by codelipenghui** [comment]
@eolivelli Can we close this issue for now?

**Comment by eolivelli** [comment]
Yes. We can

**Comment by jonasbark** [comment]
Sorry to hijack this but in case anyone stumbles upon this:
We were using pulsar java 2.7.1 and it caused an immediate EXCEPTION_ACCESS_VIOLATION crash on Microsoft Azure App Service. Updating it to 2.8.1 fixed it.

**Comment by lhotari** [comment]
Since adoptopenjdk is deprecated, it's recommended to use eclipse-temurin:17-alpine base image if one wants to use an alpine base image. [Eclipse Temurin images](https://hub.docker.com/_/eclipse-temurin) are maintained by [Adoptium](https://adoptium.net/) and it provides pre-built OpenJDK binaries.
