### ISSUE TITLE
"mvn package" has not built any jar

### ISSUE THREAD

**Issue by tomyouyou** [apache/pulsar#10791]
D:\work\pulsar\pulsar-2.7.2>mvn -s d:\work\mvn\maven\conf\settings.xml package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.classifier: windows-x86_64
[INFO]
[INFO] ----------------------< org.apache.pulsar:pulsar >----------------------
[INFO] Building Pulsar 2.7.2
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven) @ pulsar ---
[INFO]
[INFO] --- maven-remote-resources-plugin:1.5:process (process-resource-bundles)
@ pulsar ---
[INFO]
[INFO] --- maven-site-plugin:3.5.1:attach-descriptor (attach-descriptor) @ pulsa
r ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.977 s
[INFO] Finished at: 2021-06-03T10:59:31+08:00
[INFO] ------------------------------------------------------------------------

D:\work\pulsar\pulsar-2.7.2> mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: D:\work\erlang3\apache-maven-3.6.3\bin\..
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: D:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

Is there anything wrong with the command? thanks

**Comment by lhotari** [comment]
@tomyouyou is the result different if you pass `-Pmain` on the command line?

**Comment by tomyouyou** [comment]
With parameter '-Pmain', it works normally. thanks!

**Comment by lhotari** [comment]
> With parameter '-Pmain', it works normally. thanks!

In that case, it's probably some issue with #10340 changes. In Maven, there's not an explicit way to always activate a maven profile. The current solution is to check if pom.xml exists, which should always evaluate to true. I guess that solution doesn't work for some reason and should be replaced with a different solution.

**Comment by lhotari** [comment]
Can you test if you modify this to pom.xml starting on line number 1866 
```
      <id>main</id>
      <activation>
        <!-- always activate this profile by default. Use "-main" or "!main" in the "-P" parameter to exclude it -->
        <!-- for example use "-Pcore-modules,-main" to activate the core-modules profile -->
        <property>
          <name>disableMainProfile</name>
          <value>!true</value>
        </property>
      </activation>
```

**Comment by lhotari** [comment]
@tomyouyou I pushed #10814 as a fix. Thanks for reporting the issue!

**Comment by tomyouyou** [comment]
@lhotari  After the above modification, the test is successful.

**Comment by lhotari** [comment]
> @lhotari  After the above modification, the test is successful.

Thanks for verifying.
