### ISSUE TITLE
[docs] Need clarification around batch indexing configs

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#10821]
In https://pulsar.apache.org/docs/en/reference-configuration/#broker, the docs mention this setting for batch indexing:
`acknowledgmentAtBatchIndexLevelEnabled`

However, batch indexing is also mentioned [in this doc ](https://pulsar.apache.org/docs/en/concepts-messaging/#batching) with the `batchIndexAcknowledgeEnable` parameter. 

We need some clarification in the docs regarding what is the difference between these parameters. It doesn't look like the newer `acknowledgmentAtBatchIndexLevelEnabled` setting has been documented much yet.

**Comment by Anonymitaet** [comment]
Hi @codelipenghui I find that you [introduced `batchIndexAcknowledgeEnable` in Pulsar 2.6.0](https://pulsar.apache.org/blog/2020/06/18/Apache-Pulsar-2-6-0/#pip-54-support-acknowledgment-at-the-batch-index-level) and allowed users to set this configuration in `broker.conf`.

Question:

1. I search `batchIndexAcknowledgeEnable` in `broker.conf`, but got nothing. Do we need to add it to `broker.conf`?

2. `batchIndexAcknowledgeEnable` is similar to [`acknowledgmentAtBatchIndexLevelEnabled`](https://pulsar.apache.org/docs/en/reference-configuration/#broker), which can be set in `broker.conf` as well. What's the difference between them? Thanks.

**Comment by wolfstudy** [comment]
> I search batchIndexAcknowledgeEnable in broker.conf, but got nothing. Do we need to add it to broker.conf?

In `broker.conf`, `acknowledgmentAtBatchIndexLevelEnabled` is the answer you want.

**Comment by wolfstudy** [comment]
@Anonymitaet It seems that `batchIndexAcknowledgeEnable` and `acknowledgmentAtBatchIndexLevelEnabled` are confused in the documentation. I will send a pr to fix this problem.

**Comment by Anonymitaet** [comment]
@wolfstudy many thanks for your contribution. I've reviewed the PR.
