### ISSUE TITLE
[Community] add contributor over time graph to README

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/pulsar#10875]
Hi community!

We're the maintainers of [Apache APISIX](https://github.com/apache/apisix). To better present how our community grows, we develop a tool to show contributors growing history on https://github.com/api7/contributor-graph. Since we found it helpful, we think maybe if it could help some other community.

### WHAT IT IS

Basically, it just shows the contributors growth over time. All of the procedures are running on GCP, and it would automatically update the graph each day, so the link would always present the real-time data. There is some other stuff to [play around](https://www.apiseven.com/en/contributor-graph) with if you would like to give it a try~

[![Contributor over time](https://contributor-graph-api.apiseven.com/contributors-svg?chart=contributorOverTime&repo=apache/pulsar)](https://www.apiseven.com/en/contributor-graph?chart=contributorOverTime&repo=apache/pulsar)

### HOW IT WORKS

We use Github API to get all commits, try to find the “Github way” to filter commits so the result data would be similar to Github, and then get the first commit time of each contributor. We also support importing contributors from svn, and aggregating contributors from multiple repos if needed.

Currently I find it might be a good place to place it at https://pulsar.apache.org/en/contributing/. Don't hesitate to tell us if there is a better place to present this graph other than this, or there are some other worries or other features you would like to have~🍻

**Comment by Anonymitaet** [comment]
@Yiyiyimu thanks for sharing this useful tool, which shows the stats intuitively and clearly.

**Comment by Anonymitaet** [comment]
@Yiyiyimu any more issues need to be discussed? If no more, I'll close this issue. 
Feel free to communicate with us if you have more questions, thanks.

**Comment by Yiyiyimu** [comment]
Hi @Anonymitaet Is there any good place you recommend to place this graph?

**Comment by Anonymitaet** [comment]
@Yiyiyimu users can check the growth [here](https://streamnative.io/en/blog/community/2021-06-14-pulsar-hits-its-400th-contributor-and-passes-kafka-in-monthly-active-contributors)

**Comment by Yiyiyimu** [comment]
Hi @Anonymitaet Yes the graph is from us 😁 I created a PR so we could see the latest graph.

**Comment by Yiyiyimu** [comment]
Close since don't need this
