### ISSUE TITLE
[Transactions] Problems in case of transactionCoordinatorEnabled=true and allowAutoTopicCreation=false

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#10871]
**Describe the bug**
While testing the 2.8.0rc2 I found that if you start a Pulsar broker with transactionCoordinatorEnabled=true and allowAutoTopicCreation=false the broker does not work.

I see these errors:

> 2021-06-09 12:39:19,214 - ERROR - [bookkeeper-ml-scheduler-OrderedScheduler-2-0:ServerCnx@1292] - [/192.168.1.111:58508] Failed to create topic persistent://public/default/__transaction_buffer_snapshot, producerId=1
> java.util.concurrent.CompletionException: java.util.NoSuchElementException: No value present
> 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
> 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
> 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
> 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
> 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
> 	at org.apache.pulsar.broker.service.BrokerService$3.openLedgerFailed(BrokerService.java:1261)
> 	at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl.lambda$asyncOpen$8(ManagedLedgerFactoryImpl.java:402)
> 	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
> 	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
> 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
> 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
> 	at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl$2.initializeFailed(ManagedLedgerFactoryImpl.java:397)
> 	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl$1.operationFailed(ManagedLedgerImpl.java:396)
> 	at org.apache.bookkeeper.mledger.impl.MetaStoreImpl.lambda$getManagedLedgerInfo$2(MetaStoreImpl.java:87)

It looks like that the only way to make the system work it to manually create a topic named:
`persistent://public/default/__transaction_buffer_snapshot`

Please note that the topic MUST NOT be partitioned

One important fact is that the broker is configured for transactionCoordinatorEnabled=true **but NO CLIENT is using transactions** and this looks like a problem because in order to use transactionCoordinatorEnabled=true  and allowAutoTopicCreation=false  you probably have to manually create such topic for every namespace.

**Comment by michaeljmarshall** [comment]
I believe this is because the topic is not included here: https://github.com/apache/pulsar/blob/85a60b0de8c7e53747ee491350f7b21fba90099e/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L2487-L2499.

**Comment by michaeljmarshall** [comment]
I raised this issue in my PR here: https://github.com/apache/pulsar/pull/10254#discussion_r615315057. In that PR, I proposed making all topics that begin with two underscores (`__`) system topics. This was deemed to be too large of a change, however. I think we can modify that `isAllowAutoTopicCreation` method here as a hot fix.

**Comment by michaeljmarshall** [comment]
I am working on a fix for this now. I should have a PR up soon.
