### ISSUE TITLE
Update documentation to suggest running  'ldconfig' after installing C++ libs from RPMs

### ISSUE THREAD

**Issue by gimmeshelter** [apache/pulsar#10893]
**Is your enhancement request related to a problem? Please describe.**
My team was trying to use the Node.js client for Pulsar.  We had installed the RPMs and the libs were present in /usr/lib, but our app still wouldn't start.  We kept getting the error that 'libpulsar.so: cannot open shared object file: No such file or directory'.  I found the solution after searching for Node.js C++ add-ons with the same issue and someone suggested that you need to run 'ldconfig'.  That turns out to have solved our problems.

**Describe the solution you'd like**
I would like to see that the documentation for installing the C++ libs from RPMs be updated to include a note that you might need to run 'ldconfig'.

**Describe alternatives you've considered**
There are no alternatives needed.

**Additional context**
N/A

**Comment by Anonymitaet** [comment]
@gimmeshelter many thanks for your info. Would you like to add docs accordingly? Then I can help review, thanks

**Comment by Anonymitaet** [comment]
Hi @gimmeshelter any feedback on this?

**Comment by gimmeshelter** [comment]
I am not a contributor and I don't really see the need for a pull request to add one line to your documentation.  That being said, I will do this if necessary to save someone else the headache we went through.
