### ISSUE TITLE
Allow to configure all options when using Kafka wrapper

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#1090]
#### Expected behavior

Currently, we can only configure authentication on the Pulsar client instance when using the Kafka wrapper. 

We can also configure few options for which there is a Kafka correspective, using the Kafka own properties, so that existing applications will behave in the same way. 

Apart from that, we should be able to configure all the other Pulsar client option, maybe through a set of Java properties that are being passed to the Kafka client anyway.

**Comment by Horaddrim** [comment]
I'll try to do it :D Any firstcommer help?

**Comment by sijie** [comment]
@Horaddrim you are welcome to send a pull request. if you encounter any problems, feel free to ask questions at here, or mailing list dev@pulsar.incubator.apache.org or join the slack channel for https://pulsar.incubator.apache.org/contact/

**Comment by merlimat** [comment]
@Horaddrim We added a number of config for Kafka wrapper in 2.0 release. 

The list was documented at http://pulsar.apache.org/docs/latest/adaptors/KafkaWrapper/#CustomPulsarconfigurations-eshp5

The config classes can be found at https://github.com/apache/incubator-pulsar/tree/master/pulsar-client-kafka-compat/pulsar-client-kafka/src/main/java/org/apache/pulsar/client/kafka/compat 

I'm sure there will be some settings that were added since and are missing from there.

**Comment by Horaddrim** [comment]
Really thank you @merlimat and @sijie ! I've already checked these materials, so ASAP I'll start working in this :smile:

**Comment by ConcurrencyPractitioner** [comment]
Ok, I found out that a list of Pulsar consumer configs could be found in the class ```ConsumerConfigurationData```. I noticed that there is a map which allows for other properties to be added in the class itself. So I want to know if there is possibly a list of configs which Pulsar's ConsumerImpl uses which I could draw from as a resource.
