### ISSUE TITLE
Python pulsar-client 2.8.0 raise ModuleNotFoundError No module named 'fastavro'

### ISSUE THREAD

**Issue by ca-simone-chiorazzo** [apache/pulsar#10929]
**Describe the bug**
If you try to import the 2.8.0 python pulsar client, you get a ModuleNotFoundError. This happens with python 3.8.

**To Reproduce**
1. Install python 3.8.6
2. Install pulsar-client==2.8.0
3. Instantiate a consumer
4. You get ModuleNotFoundError

**Expected behavior**
We expect to not have ModuleNotFoundError

**Screenshots**

**Desktop (please complete the following information):**
 - Tested with the python:3.8 Docker image

**Additional context**
Logs of a Docker build that has this problem
```
#9 0.335 Traceback (most recent call last):                                                                                                                                                                                                 
#9 0.335   File "consumer.py", line 1, in <module>                                                                                                                                                                                          
#9 0.335     from consumer import Consumer, ConsumerConfig
#9 0.335   File "/usr/local/lib/python3.8/site-packages/consumer/consumer.py", line 2, in <module>
#9 0.335     import pulsar
#9 0.335   File "/usr/local/lib/python3.8/site-packages/pulsar/__init__.py", line 112, in <module>
#9 0.335     from pulsar import schema
#9 0.335   File "/usr/local/lib/python3.8/site-packages/pulsar/schema/__init__.py", line 23, in <module>
#9 0.335     from .schema import Schema, BytesSchema, StringSchema, JsonSchema, AvroSchema
#9 0.335   File "/usr/local/lib/python3.8/site-packages/pulsar/schema/schema.py", line 23, in <module>
#9 0.335     import fastavro
#9 0.335 ModuleNotFoundError: No module named 'fastavro'
```

**Comment by merlimat** [comment]
@ca-simone-chiorazzo The Avro dependency was made optional. You can install it with :

```
pip install pulsar-client=='2.8.0[avro]'
```

See: https://pulsar.apache.org/docs/en/client-libraries-python/#optional-dependencies

**Comment by merlimat** [comment]
though I agree that it must not fail if someone is not trying to use Avro schema...

**Comment by merlimat** [comment]
@aahmed-se PTAL

**Comment by ca-simone-chiorazzo** [comment]
> though I agree that it must not fail if someone is not trying to use Avro schema...

Exactly, we are not using Avro schema so we do not want to install the optional dependency.
