### ISSUE TITLE
cannot found jar when start bookie and broker

### ISSUE THREAD

**Issue by gaozhangmin** [apache/pulsar#10946]
ls: cannot access apache-pulsar-2.8.0/lib/org.aspectj-aspectjweaver-*.jar: No such file or directory
Version: 2.8.0

**Comment by gaozhangmin** [comment]
is it because of missing aspectjrt and aspectjweaver dependency in pom.xml?

**Comment by aloyszhang** [comment]
https://github.com/apache/pulsar/pull/10533   This PR removed aspectj, so, for pulsar 2.8.0, besides `lib`, you need to replace `bin` directory also.
