### ISSUE TITLE
[Doc] Transaction

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#10971]
Recently, Pulsar 2.8 has been released and one of the highlights is transaction API, which supports atomic writes and acknowledgments across multiple topics. It completes our vision of making Pulsar a complete unified messaging and streaming platform.

The [transaction docs](https://pulsar.apache.org/docs/en/next/transactions/) need to be improved, so I've re-architectured the doc and drafted one [here](https://docs.google.com/document/d/1rChR2ZScYxCDKUmkQTg6inbuhyfrz_jJfdQOFtwO8P0/edit#). 

Feel free to comment, thanks.

**Comment by Anonymitaet** [comment]
@congbobo184 since you are the lead developer of the transaction, could you please help review overall and answer the questions marked in the doc? 

It would be much appreciated if you could provide any feedback by EOD 6/23 GMT+8, many thanks!

**Comment by newur** [comment]
Really good idea to update the docu on this one. I was wondering a lot about how this feature works and missing examples, after reading the release notes and the blog post.

For me the last chapter in the draft, called 'Integration' only made it clear in which case the transactional feature applies. Maybe wanna move that chapter/picture a bit up?

**Comment by Anonymitaet** [comment]
@newur thanks for your feedback. Does it make sense to move the contents of `integration` to the `what feature do transactions provide` section under the `overview` chapter?

**Comment by newur** [comment]
@Anonymitaet I would say so, yes. For me transaction are all about the boundaries, so I want to know where does it start and till which point can it rollback. And pictures are pretty useful to illustrate borders. :D 

Btw. I would drop statement like "Today’s businesses need to handle ever-increasing amounts of live data." This probably sounds great in marketing, but is fluff for most people who will actually read the documentation. Or actually implement a transactional boundary. ^^ Just my 2 cents of course

**Comment by Anonymitaet** [comment]
Hi @newur thanks for your suggestions.

After discussing w/ @congbobo184, we've adjusted the doc architecture and want to make the following changes:

1. Move the following contents to the `What is txn` chapter since they are general explanations and appropriate for stream processing (like Pulsar Flink connector, Pulsar Spark connector, and Function)

![image](https://user-images.githubusercontent.com/50226895/122909263-993eaf80-d387-11eb-9085-737497bac99c.png)

2.  Add `Use Case` chapter 

(1) Currently, only the Pulsar Flink connector supports txn. Pulsar function and Pulsar spark connector may support txn in the future, we can add links to them later.

(2) Move the following contents to the Pulsar Flink connector guide and add the link here

![image](https://user-images.githubusercontent.com/50226895/122909515-d99e2d80-d387-11eb-8d0c-c6cb3fd45d7c.png)

Does this make sense to you?

Besides, "Today’s businesses need to handle ever-increasing amounts of live data." demonstrates the fact (processing a lot of streaming data is in great demand), I think it is OK to say that. :-D

**Comment by newur** [comment]
Sounds good. Maybe you can add a brace to the picture from which start to which end the transaction applies (I think I understand it from the text now, but would be nice anyway).

Nit: I think `writes the resulting messages to another topic` is more like `writes the result to one or more topics`?

> Currently, only the Pulsar Flink connector supports txn. Pulsar function and Pulsar spark connector may support txn in the future.
Hu? I was under the impression I can write my own transaction in a pulsar function? Thought there were some code examples either on the pulsar side or in the linked blog post, no?

**Comment by Anonymitaet** [comment]
>Sounds good. Maybe you can add a brace to the picture from which start to which end the transaction applies (I think I understand it from the text now, but would be nice anyway).

Thanks for your suggestion. I think the directions of these arrows already point out the start and end (from left to right), correct?

![image](https://user-images.githubusercontent.com/50226895/123019754-abf6ca00-d403-11eb-88b3-d2c262a59664.png)


> Nit: I think writes the resulting messages to another topic is more like writes the result to one or more topics? At least there are multiple topics in the picture, and the sentence about the source is in a similar fashion.

Thanks for reminding me, I've updated it to `writes the result to one or more topics`.

> Currently, only the Pulsar Flink connector supports txn. Pulsar function and Pulsar spark connector may support txn in the future.
> Hu? I was under the impression I can write my own transaction in a pulsar function? Thought there were some code examples either on the pulsar side or in the linked blog post, no?

Hi @congbobo184 for this question, could you please help explain? thanks
