### ISSUE TITLE
MutliConsumer not released after calling method unsubscribe

### ISSUE THREAD

**Issue by Shoothzj** [apache/pulsar#10996]
**Describe the bug**
MutliConsumer not released after calling method unsubscribe, and can't be released by other method.

**To Reproduce**
1. Create a MultiTopicConsumer
2. Unsubscribe the topoc
3. Jmap print live objects
4. See MultiTopicConsumer stiil there

**Expected behavior**
Jmap live objects do not show MultiTopicConsumer

**Demo Code**
```java
public class PulsarMutliConsumerMemoryLeak {

    public static void main(String[] args) throws Exception {
        TopicService.createTopic("test-multi-topic", 2);
        final ConsumerBuilder<byte[]> consumerBuilder = PulsarUtil.pulsarClient().newConsumer();
        final Consumer<byte[]> consumer = consumerBuilder.topic("test-multi").subscriptionName("sub-1").subscribe();
        consumer.unsubscribe();
        CommonUtil.sleep(TimeUnit.DAYS, 1);
    }

}
```
**Screenshots**
![image](https://user-images.githubusercontent.com/12933197/122735904-0849d480-d2b2-11eb-93a1-925845532b30.png)

**Comment by BewareMyPower** [comment]
Does `consumer.close()` work? `unsubscribe()` is just to send an UNSUBSCRIBE command to broker. For `MultiTopicsConsumer`, it calls `unsubscribe()` method for each single topic.

**Comment by Shoothzj** [comment]
> Does `consumer.close()` work? `unsubscribe()` is just to send an UNSUBSCRIBE command to broker. For `MultiTopicsConsumer`, it calls `unsubscribe()` method for each single topic.

`Consumer.close()` work， but when you call `unsubscribe()`, it changes the state to `Closing`, and then U can't call `close` any more. And the `ConsumerImpl` close the consumer, while `MultiConsumerImpl` doesn't.

**Comment by Shoothzj** [comment]
Fixed in this PR
https://github.com/apache/pulsar/pull/10997
