### ISSUE TITLE
[Doc] generate 2.8.1 doc set

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#10994]
2.8.0 has been released and the Pulsar is on the way to 2.9.0 (and 2.7.3 and 2.8.1). 

Since 2.8.1 docs might be different from the master, but now we [do not have the 2.8.1 docs](https://github.com/apache/pulsar/tree/master/site2/website/versioned_docs) and can not update the 2.8.1 docs if needed. Consequently, the 2.8.1 doc set needs to be generated.

Here are some examples of generating versioned docs:
- [2.7.3](https://github.com/apache/pulsar/pull/10666)
- [2.7.2](https://github.com/apache/pulsar/issues/10236)
- [2.6.4](https://github.com/apache/pulsar/pull/10783)

Anyone can help generate the 2.8.1 doc set? Thanks

**Comment by wolfstudy** [comment]
I will process it.
