### ISSUE TITLE
confusing documentation for bookkeeper.httpServerPort

### ISSUE THREAD

**Issue by Zhen-hao** [apache/pulsar#10990]
On https://pulsar.apache.org/docs/en/reference-configuration/,
Under bookkeeper.httpServerPort, it says
```
The http server port to listen on. By default, the value is 8080. Use 8000 as the port to keep it consistent with prometheus stats provider.
```
But the default value in the table has the value `8000`. 
If I don't set this in the config, is it `8000` or `8080`?

**Comment by murong00** [comment]
The default value is `8080` as below:
```
    public int getHttpServerPort() {
        return getInt(HTTP_SERVER_PORT, 8080);
    }
```

**Comment by murong00** [comment]
If you keep this value as `httpServerPort=8000` then it will use `8000` as recommended. If this value is not set, then it will use `8080` as default.

**Comment by Zhen-hao** [comment]
thanks!
