### ISSUE TITLE
PulsarDebeziumSourcesTest does not run on CI

### ISSUE THREAD

**Issue by dlg99** [apache/pulsar#11099]
**Describe the bug**

AFAICT PulsarDebeziumSourcesTest does not run on CI currently.

**To Reproduce**

Check CI logs.

**Expected behavior**

Test suite runs on CI

**Additional context**

There were refactorings of tests that created tests/integration/target/test-classes/pulsar-io-[suite|sinks|sources].xml (PulsarDebeziumSourcesTest moved to pulsar-io-sources.xml, included into pulsar-io-suite.xml) and refactoring/optimization of CI that created build/run_integration_group.sh and PulsarDebeziumSourcesTest fell through the cracks there (new xml files/suites not referred to in the run_integration_group.sh).

**Comment by dlg99** [comment]
Definitely does not run on CI because it fails locally:

- MongoDb source's test fails with some docker error - instead of some expected output it returns docker's help screen
- MySql source's test fail when it tries to get state of source: expects running, gets not running
- Postgres one was failing because it expected one message on record delete, got two. 
  - Second one is expected, it is a tombstone message produced by debezium and [documented](https://debezium.io/documentation/reference/configuration/event-flattening.html#event-flattening-behavior)
  - I have a fix for that; postgres' test passed locally
  
I ran it using
```
mvn test -f tests/pom.xml test -DintegrationTestSuiteFile=pulsar-io-sources.xml -DintegrationTests -Dtest=org.apache.pulsar.tests.integration.io.sources.debezium.PulsarDebeziumSourcesTest
```

Before running the test I did
```
docker pull debezium/example-postgres:0.10
docker pull debezium/example-mysql:0.8
docker pull debezium/example-mongodb:0.10
```

**Comment by lhotari** [comment]
I was wondering when this happened. The Pulsar IO tests got removed out of CI as a consequence of #10140 . 

Thanks for reporting and fixing the issue.
