### ISSUE TITLE
Please help me to unlist my email id from receiving emails. 

### ISSUE THREAD

**Issue by BOYINASAI** [apache/pulsar#11127]
Hello Team,

This is not related to pulsar but i failed to find a way to unsubscribe from flood of emails. Hence this request, appreciate your help.

I sent an email to below emails.
from: | Saikrishna Boyina <sae.boyina@gmail.com>
-- | --
to: | users-unsubscribe@pulsar.incubator.apache.org,unsubscribe@pulsar.incubator.apache.org
cc: | mykidong@gmail.com

Still i'm getting emails from below. I think i am part of dev@ commits@ list which is why i have been receiving these emails.

<html>
<body>

from: | GitBox <git@apache.org>
-- | --
reply-to: | dev@pulsar.apache.org
to: | commits@pulsar.apache.org
date: | Jun 28, 2021, 12:23 PM

Could someone please help me to get my email unlisted from all pulsar related emails.

Thanks,
Sai

**Comment by aarondonwilliams** [comment]
this is for users: 
To remove your address from the list, send a message to:
   <users-unsubscribe@pulsar.apache.org>

so just change users to the list that you would like to be removed from...

**Comment by lhotari** [comment]
the unsubscribe addresses for all 3 mailing lists can be found on this page: https://pulsar.apache.org/en/contact/
