### ISSUE TITLE
Document that the message key is the partition key in the Protobuf message

### ISSUE THREAD

**Issue by Geal** [apache/pulsar#11193]
The reference (ex: https://pulsar.apache.org/docs/en/cookbooks-compaction/ ) and the API docs ( https://pulsar.apache.org/api/client/2.8.0-SNAPSHOT/org/apache/pulsar/client/api/Message.html#getKey-- and https://pulsar.apache.org/api/client/2.8.0-SNAPSHOT/org/apache/pulsar/client/api/TypedMessageBuilder.html#key-java.lang.String- ) mention a message key but the Protobuf definition does not indicate a message key ( https://github.com/apache/pulsar/blob/master/pulsar-common/src/main/proto/PulsarApi.proto#L111 )

Arguably it is an implementation detail that is not user facing, and it's logical that the partition key would be used for that, but I have heard multiple conversations about it already, so it is a confusing point.

Could the documentation clarify that?

**Comment by Anonymitaet** [comment]
Hi @Geal can you share the info of "multiple conversations about it"? (so that we can know your needs more clearly) thanks

**Comment by Anonymitaet** [comment]
@freeznet could you please help look into this issue? Thanks

**Comment by freeznet** [comment]
@Anonymitaet agree with @Geal, it is quite confusing about the message key and the partition key. From the interface of `Message`, we have `getKey()` but the implementation of `getKey()` returns the partition key.
https://github.com/apache/pulsar/blob/fe7cf676e59e08b34b388fce3a190133d390d61c/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java#L561-L567
According to @Geal's suggestion, a clarified doc should be added to let users aware that for the implementation of `Message`, we use the partition key as the message key.

**Comment by Anonymitaet** [comment]
@freeznet thanks for your explanations!

I'll add the clarification (`Partition key is used as the message key`) [here](http://pulsar.apache.org/docs/en/next/develop-binary-protocol/#message-metadata).

![image](https://user-images.githubusercontent.com/50226895/124541218-8fbb4a00-de53-11eb-9d93-d7a22097d4e2.png)

**Comment by Geal** [comment]
@Anonymitaet great, thanks!
