### ISSUE TITLE
pulsarAdmin topic list non-persistent is empty

### ISSUE THREAD

**Issue by shibd** [apache/pulsar#11212]
**Describe the bug**

Use PulsarAdmin to create a non persistent topic, But the query topic list is empty

**To Reproduce**
1. `pulsar-admin topics create-partitioned-topic non-persistent://public/default/my-topic -p 3`
2. `pulsar-admin topics list public/default`

**Expected behavior**
can see the topic

**Screenshots**
![image](https://user-images.githubusercontent.com/33416836/124350932-0e34a380-dc2a-11eb-861a-b60aab17d794.png)

**Desktop:**
 - OS:  mac os

**version**
- pulsar 2.8.0

**Comment by Jason918** [comment]
@shibd Maybe you should use `list-partitioned-topics`

**Comment by liangyuanpeng** [comment]
> @shibd Maybe you should use `list-partitioned-topics`

@shibd  Hi, Does it solved your problem?

**Comment by shibd** [comment]
> Maybe you should use list-partitioned-topics

Thanks, It can work.
