### ISSUE TITLE
Retention size policy may delete too much ledgers

### ISSUE THREAD

**Issue by aloyszhang** [apache/pulsar#11241]
**Describe the bug**
If namespaces is enable Retention size policy, broker may delete too much ledgers if all cursors have no backlog.

Assume that we have a topic with retentino size is 5MB, and retention time is -1.
And this topic have 10 ledgers  in `ManagedLedger` and each ledger has 1MB size,  and all cursors has no backlog.
when the retention size policy works, i't will delete the first 9 ledgers.

**To Reproduce**
1. Create a topic , set retention size policy to a proper size and set retention time to -1(disable )
2. Create a subscritption(cursor) for this topic
3. send some messages to make sure ledgers rollover several times
4. consume all the messages from the topic using the created subscription
5. broker will delete all the ledgers besides the last ledger

**Expected behavior**
Broker should maintain proper size of message according to the retention size instead of deleting all acked ledgers

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by zymap** [comment]
We need to cherry-pick this patch for 2.7.x. The 2.7.x also has this issue
