### ISSUE TITLE
Intermittent test failure in testSkipCorruptDataLedger

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#1126]
https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/1274/testReport/junit/org.apache.pulsar.broker.service/BrokerBkEnsemblesTests/testSkipCorruptDataLedger/

```
Method org.apache.pulsar.broker.service.BrokerBkEnsemblesTests.testSkipCorruptDataLedger() didn't finish within the time-out 6000
```

**Comment by merlimat** [comment]
@rdhabalia I have seen this test failing several times in the last few days. Can you take a look when you have the chance?

**Comment by ivankelly** [comment]
@merlimat Can this be closed?
