### ISSUE TITLE
[Doc] Remove Pulsar Dashboard contents

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#11291]
Fix https://github.com/apache/pulsar/pull/11284

**Comment by Jennifer88huang** [comment]
@sijia-w could you please help work on this issue?

**Comment by Anonymitaet** [comment]
@sijia-w 
 
#1
I think we can not remove the content in `administration-dashborad.md` because other `.md` files (old version doc) might reference some content in `administration-dashborad.md`. Besides, there is a note in `administration-dashborad.md` which already reminds and guides users to the right place. 
![image](https://user-images.githubusercontent.com/50226895/129009875-b9a9b18d-237f-41ae-baa5-a0602b6c5d84.png)

#2
Agree with you on that.

@eolivelli @Jennifer88huang thoughts?

**Comment by Jennifer88huang** [comment]
@Anonymitaet agree.
The current Pulsar dashboard is not displayed on Pulsar website; yet if you search, you can find it.
