### ISSUE TITLE
[Topic Policy] Delete the topic policy for the topic when the topic been deleted.

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#11308]
**Describe the bug**
Currently, when the topic has been deleted, the topic policy will retain in the system topic, and this will also introduce a problem when a new topic with the same name is created. The new topic will apply the policy of the old one.

So, when the topic has been deleted, we should also remove the topic policy from the system topic.

- The topic can be deleted manually.
- The topic can be deleted automatically since we support inactive topic auto-deletion.

For more details about the topic policy can see: https://github.com/apache/pulsar/wiki/PIP-39%3A-Namespace-Change-Events and http://pulsar.apache.org/tools/pulsar-admin/2.8.0-SNAPSHOT/#-em-set-backlog-quota-em--46

**Comment by horizonzy** [comment]
Hi, I will try to fix it, you can assign it to me.

**Comment by codelipenghui** [comment]
Thanks, @horizonzy, Looking forward to your contribution.
