### ISSUE TITLE
AutoRecovery failed replicate ledger which in open state, because, it would read lac from failed bookie. 

### ISSUE THREAD

**Issue by gaozhangmin** [apache/pulsar#11320]
As title, When bookie is lost, the ledger which state is open cannot replicated because of reading lac from failed bookie.
it would failed read lac from failed bookie, because it cannot be connected.

How bookkeeper auto recovery deal with open ledger in failed bookie ? 

I don't know if it's a bug or not.

The error log:
```
12:29:57.072 [main-EventThread] INFO  org.apache.bookkeeper.client.DefaultBookieAddressResolver - Cannot resolve x.x.x.x:3181, bookie is unknown org.apache.bookkeeper.client.BKException$BKBookieHandleNotAvailableException: Bookie handle is not available
12:29:57.072 [main-EventThread] ERROR org.apache.bookkeeper.proto.PerChannelBookieClient - Cannot connect to x.x.x.x:3181 as endpoint resolution failed (probably bookie is down) err org.apache.bookkeeper.proto.BookieAddressResolver$BookieIdNotResolvedException: Cannot resolve bookieId x.x.x.x:3181, bookie does not exist or it is not running
12:29:57.078 [BookKeeperClientWorker-OrderedExecutor-29-0] INFO  org.apache.bookkeeper.client.PendingReadLacOp - While readLac ledger: 96789 did not hear success responses from all of ensemble
12:29:57.078 [ReplicationWorker] INFO  org.apache.bookkeeper.replication.ReplicationWorker - BKReadException while rereplicating ledger 96789. Enough Bookies might not have available So, no harm to continue
````

**Comment by frankjkelly** [comment]
@gaozhangmin I think I am seeing something similar and I am using Pulsar 2.7.2 on Kubernetes.
Which version are you seeing this on?

**Comment by gaozhangmin** [comment]
> @gaozhangmin I think I am seeing something similar and I am using Pulsar 2.7.2 on Kubernetes.
> Which version are you seeing this on?

I think bookkeeper version matters,  I am using bookkeeper-4.14.1

**Comment by gaozhangmin** [comment]
reason: http://mail-archives.apache.org/mod_mbox/bookkeeper-dev/202109.mbox/browser

**Comment by frankjkelly** [comment]
@gaozhangmin @Vanlightly Thanks for posting that update - I had no idea that an Ack Quorum of 1 could cause a problem like that.
