### ISSUE TITLE
Pulsar Admin List Subscription lists only subscriptions created for Partition-0 when partition specific subscriptions are created

### ISSUE THREAD

**Issue by manjupriya-ar** [apache/pulsar#11339]
**Describe the bug**

Pulsar Admin List Subscription lists only subscriptions created for Partition-0 when partition specific subscriptions are created

**To Reproduce**
Pulsar Version: 2.7.0 and 2.7.2.

	1. Create a topic with N partitions [./pulsar-admin topics create-partitioned-topic public/default/nodatahere1 -p 3]
	2. Create Partition specific Subscriptions [ Example:  pulsar-admin topics create-subscription -s 0_abc -m earliest persistent://public/default/nodatahere1-partition-0, pulsar-admin topics create-subscription -s 0_abc_1 -m earliest persistent://public/default/nodatahere1-partition-0, pulsar-admin topics create-subscription -s 1_abc -m earliest persistent://public/default/nodatahere1-partition-1]
	3. Listing partitions specific subscription works fine [pulsar-admin topics subscriptions persistent://public/default/nodatahere1-partition-0, pulsar-admin topics subscriptions persistent://public/default/nodatahere1-partition-1]. For partition-0, 0_abc and 0_abc_1 is listed. For partition-1, 1_abc is listed. 
	4. List the partitions at the topic level [pulsar-admin topics subscriptions persistent://public/default/nodatahere1] 
		a. List partitions lists "0_abc" and "0_abc_1" alone. It does not list "1_abc". 

Expectation: It should list all partition specific topics or None of the partition specific topics.  Currently, if we have a subscription "abc_all" that is across the partitions, then list subscriptions will list "0_abc", "0_abc_1", "abc_all". 

**Expected behavior**
It should list all partition specific topics or None of the partition specific topics.  Currently, if we have a subscription "abc_all" that is across the partitions, then list subscriptions will list "0_abc", "0_abc_1", "abc_all". 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Technoboy-** [comment]
I will try to fix it.
