### ISSUE TITLE
[Pulsar admin] Can not get leader broker in non-leader brokers.

### ISSUE THREAD

**Issue by zhanghaou** [apache/pulsar#11348]
**Describe the bug**
I can use admin cmd to get the leader broker in leader broker, but can not get the info from non-leader broker.

**To Reproduce**
1. enter non-leader broker
2. run ' pulsar-admin brokers leader-broker'
3. output: 

Couldn't find leader broker

Reason: Couldn't find leader broker

link PR: https://github.com/apache/pulsar/pull/9799

**Comment by zhanghaou** [comment]
@linlinnn @codelipenghui Please take a look and check, thanks.

**Comment by Demogorgon314** [comment]
I will try to fix it.
