### ISSUE TITLE
CLI in TTL config is not clear

### ISSUE THREAD

**Issue by Jennifer88huang** [apache/pulsar#11380]
**Is your enhancement request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/47805623/106427770-e71f4d80-64a2-11eb-8fc3-a467b1e9c6b8.png)

Not quite understand what does "N/A", "100" mean in a separate CLI in https://pulsar.apache.org/docs/en/next/admin-api-namespaces/#configure-message-ttl

Is it the returned value?

**Describe the solution you'd like**
Give clear and concise description for the above values.

**Comment by Jennifer88huang** [comment]
@sijia-w could you like to investigate and try to fix the issue? Thank you.

**Comment by sijia-w** [comment]
@Jennifer88huang I checked this page https://pulsar.apache.org/docs/en/cookbooks-retention-expiry/#clear-backlog and the `N/A`s seem to be empty returned messages. If they are not, I will update my changes accordingly.
