### ISSUE TITLE
[Docs] oauth sample code does not match api

### ISSUE THREAD

**Issue by rfigueroa** [apache/pulsar#11397]
[Java](https://pulsar.apache.org/docs/en/security-oauth2/#java) code sample uses string when the actual API expects URLs

Update sample from the docs to reflect the api

**Comment by Anonymitaet** [comment]
@rfigueroa would you like to help fix? Thanks

**Comment by Anonymitaet** [comment]
@rockybean could you please help review this PR from the technical perspective? Thanks

**Comment by Anonymitaet** [comment]
Done in https://github.com/apache/pulsar/pull/11398
