### ISSUE TITLE
JVM Core dumps on 8-jre-alpine docker image

### ISSUE THREAD

**Issue by santhoshsath** [apache/pulsar#11415]
I have an existing  lightbend Play server in production running as a docker image 
recently I added a pulsar client library to it (org.apache.pulsar:pulsar-client:2.7.2)
I tested the connectivity on my laptop and everything runs well
After testing, I created a docker image of my server
When I run it in docker, the JVM core dumps when I try to create the client instance 
PulsarClient.builder().
    serviceUrl(serviceUrl).
    allowTlsInsecureConnection(false).
    tlsTrustCertsFilePath(tlsTrustCertsFile.getAbsolutePath).
    authentication(authClassName, authParams.asJava).
    connectionTimeout(connectionTimeout,TimeUnit.MILLISECONDS).
    build()
Attached is the java core dump file
[hs_err_pid1.log](https://github.com/apache/pulsar/files/6856984/hs_err_pid1.log)

**Comment by santhoshsath** [comment]
At the very least is there a way to disable epoll and use java nio in pulsar client ?

**Comment by santhoshsath** [comment]
I had to upgrade to 2.7.2 because the lower versions had security vulnerabilities as reported by blackduck.
It's that .so file packaged with 2.7.2 jar, I think it was a mistake to package a buggy .so

**_pulsar-client-2.7.2.jar/META-INF/native/liborg_apache_pulsar_shade_netty_transport_native_epoll_x86_64.so_**

If I remove that .so from the jar file, and rebuild the docker image it runs fine

**Comment by tisonkun** [comment]
Closing as stale. If it's still relevant to maintained versions, feel free to open a new issue.
