### ISSUE TITLE
[Question][Protocol Handler] Does single broker node support multi msg protocols in config?

### ISSUE THREAD

**Issue by ericsyh** [apache/pulsar#11436]
**Is your enhancement request related to a problem? Please describe.**
When setting the `KoP`, `MoP`, `AMQP` and `RoP`, we should use the config of `messagingProtocols` in broker and it seems that one single broker node only supports one message protocol at same time.

I wanna check that whether the config `messagingProtocols` could set multi protocol at same time like `messagingProtocols=[amqp,kafka,mqtt]`.

**Describe the solution you'd like**
If single broker node only supports to set one message protocol, under the scenario that users have multiple message protocols in usage they have to put much more broker nodes.

**Comment by codelipenghui** [comment]
@ericsyh You can enable multiple protocol handlers for one broker. Can you share your configurations?

**Comment by ericsyh** [comment]
> @ericsyh You can enable multiple protocol handlers for one broker. Can you share your configurations?

@codelipenghui I didn't make this test so could you share a sample config that how to enable multiple protocol handlers in one broker? I checked on Pulsar docs and KoP/MoP/AMQP/RoP repos and didn't find related sample.

**Comment by codelipenghui** [comment]
You can just set the `messagingProtocols=kafka,mqtt` and copy the kop and mop Nar package to the protocolHandlerDirectory

**Comment by ericsyh** [comment]
@codelipenghui got it, many thanks. Maybe we can add this sample to [broker.conf](https://github.com/apache/pulsar/blob/master/conf/broker.conf) and [standalone.conf](https://github.com/apache/pulsar/blob/master/conf/standalone.conf) so that others can also know the way to enable multiple protocol handlers.
