### ISSUE TITLE
Topic-Level Metrics That Are Partition-Inclusive

### ISSUE THREAD

**Issue by evfurman** [apache/pulsar#11432]
**Is your enhancement request related to a problem? Please describe.**
We'd love to be able to get topic-level metrics that are partition-inclusive. We use the openmetrics integration in Datadog but when we break out the metric by `topic` it includes the partition number in the topic name.

**Describe the solution you'd like**
Would like `topic` tag to be the actual topic (without partition number) and then have a separate `partition` tag

_**CURRENT**_
`this-pulsar-topic-partition-1`

_**DESIRED**_
`this-pulsar-topic`

**Describe alternatives you've considered**
We could write a script to rewrite the metrics and publish them to prometheus but a native solution within pulsar itself would be much cleaner.

**Comment by Technoboy-** [comment]
Currenly, pulsar broker owns the topic based on namespace bundles, that means : a topic with 3 partitions may own by different brokers, so topic level metrics is hard to aggregate between brokers.
