### ISSUE TITLE
Python client documentation is incorrect

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#11449]
**Describe the bug**
In the latest [documentation](https://pulsar.apache.org/docs/en/client-libraries-python/) on the Python client library, the installation instructions for the optional components is wrong.

The commands ` pip install pulsar-client=='2.8.0[avro]' ` using invalid syntax

**To Reproduce**
1. Open a terminal window
2. Run the command ` pip install pulsar-client=='2.8.0[avro]'`
3. See error, "ERROR: Extras after version '==2.8.0[avro]'."

**Expected behavior**
The commands provided to install the optional components should either work, or be removed if they are no longer necessary.

**Desktop (please complete the following information):**
 - OS: MacBook Pro
 - Python 3.8

**Comment by ericsyh** [comment]
This command works for me `pip install pulsar-client[avro]==2.8.0` and my env below:

**Comment by Anonymitaet** [comment]
@david-streamlio thanks for your suggestions! Would you like to help update the docs?

**Comment by david-streamlio** [comment]
@Anonymitaet , Yes, I can update the docs to include a section that have installation instructions for MacBooks.

**Comment by Anonymitaet** [comment]
Hi @david-streamlio any progress on the docs? Thanks

**Comment by david-streamlio** [comment]
I have a preliminary version out, but I am waiting for confirmation as to whether the single `pip install pulsar-client` command actually installs all of the optional components that you have to install manually in Linux, e.g., functions runtime and Avro serialization.
