### ISSUE TITLE
Zookeeper stats_server_port override is not respected in version 2.8.0

### ISSUE THREAD

**Issue by yabinmeng** [apache/pulsar#11467]
**Describe the bug**
I'm installing Apache Pulsar 2.8.0 on VM host, sharing the same host for all components (zookeeper, bookie, broker). According to the document, I need to start zookeeper with an extra option, as below

```
$ PULSAR_EXTRA_OPTS="-Dstats_server_port=8001" bin/pulsar-daemon start zookeeper
```

It turns out that zookeeper still starts metrics port at 8000. The log file snippet is as below (httpPort=8000)

```
22:16:23.241 [main] INFO  org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider - Initializing metrics, configuration: {exportJvmInfo=true, httpPort=8000}
22:16:23.242 [main] INFO  org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider - Starting /metrics HTTP endpoint at port 8000 exportJvmInfo: true
22:16:23.266 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @1049ms to org.eclipse.jetty.util.log.Slf4jLog
22:16:23.337 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.42.v20210604; built: 2021-06-04T17:33:38.939Z; git: 5cd5e6d2375eeab146813b0de9f19eda6ab6e6cb; jvm 11.0.11+9-Ubuntu-0ubuntu2.18.04
22:16:23.371 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@5778826f{/,null,AVAILABLE}
22:16:23.392 [main] INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@78fbff54{HTTP/1.1, (http/1.1)}{0.0.0.0:8000}
22:16:23.392 [main] INFO  org.eclipse.jetty.server.Server - Started @1176ms
....
```

This cause the issue when I try to start bookies, complaining about port conflict. 

I tested this in version 2.7.2 as well and it doesn't have this problem. 

**To Reproduce**
I'm following exactly the procedure as described in Pulsar doc:
https://pulsar.apache.org/docs/en/deploy-bare-metal/

**Expected behavior**
zookeeper is started at the specified port in "-Dstats_server_port" option

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18

**Additional context**

**Comment by Technoboy-** [comment]
I will try to confirm,  and if this is a bug ,we will fix it later.

**Comment by Technoboy-** [comment]
Due to zookeeper 3.6.0+ has add internal prometheus metric provider, So we remove old prometheus metric provider in `ZooKeeperStarter` and `ConfigurationStoreStarter`
The ZooKeeper metrics are exposed under "/metrics" at port `8000`. You can use a different port by configuring the `metricsProvider.httpPort` in conf/zookeeper.conf.
