### ISSUE TITLE
Why use == instead of equals to compare strings in PulsarColumnMetadata

### ISSUE THREAD

**Issue by skyguard1** [apache/pulsar#11462]
In `PulsarColumnMetadata`, use == instead of equals to compare strings
https://github.com/apache/pulsar/blob/master/pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarColumnMetadata.java#L190

Is there any special reason for this? if not, I can provide a pr to fix it, thanks

**Comment by Technoboy-** [comment]
I think you @skyguard1  can make a pr to fix it.
@codelipenghui, could you help to confirm ?
