### ISSUE TITLE
Get the number of references to the given pulsar client instance at a given point of time.

### ISSUE THREAD

**Issue by manjupriya-ar** [apache/pulsar#11493]
**Is your feature request related to a problem? Please describe.**
Pulsar Version: 2.7.2
Pulsar Client: Pulsar CPP Client

In Pulsar, we use a single client to create multiple producers/consumers/readers. Is there any method/attribute that can give information on number of producers/readers/consumers connected to the given pulsar client instance at the given point of time?

Say there is a single pulsar client instance. Multiple consumers and readers are created from the given client instance. This client needs to be cleaned up when all the references are closed. In this case, it would be of help, to get information on the number of the consumers/readers/ getPartitionsForTopic calls are active on the given client. Ie, having the number of references for the given client can provide information on whether it is fine to clean up the client instance at the given point of time.

**Describe the solution you'd like**
A way to get the number of references to the given pulsar client instance at a given point of time.

**Comment by Sunny-Island** [comment]
I'll handle this issue.

**Comment by Sunny-Island** [comment]
I'll add method to `ClientImpl`:
- getNumberOfProducer()
- getNumberOfConsumer()
- getNumberOfReader()
These method will scan state of all kinds of Producer/Consumer/Reader (with lock) and return number of connected instance.

**Comment by Sunny-Island** [comment]
I have open a [PR](https://github.com/apache/pulsar/pull/11535). There are two questions:

1. For PartitionedProducer/PartitionedConsumer/MultiTopicConsumer which consist of more than one consumer/producer. They should be counted as one or more reference？
2. When created reader from client, client add reader's consumer to its consumer list. Should we remove `getNumberOfReader()`? I haven't implemented this function yet.
