### ISSUE TITLE
[release notes] Document the requirement of ZooKeeper 3.6.x or greater for Pulsar 2.9 onwards

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#11617]
In 2.9.0 we are now using ZooKeeper Persistent Recursive Watches.
This feature is supported only from ZooKeeper 3.6.x onwards.

Users that upgrading from Pulsar 2.7.x, that bundles ZooKeeper 3.5.x must upgrade the ZooKeeper nodes before upgrading the brokers.

The same applies to users that are running their own ZooKeeper cluster, they must upgrade to ZooKeeper 3.6.x or greater before upgrading Pulsar.

Currently in ZooKeeper 3.6.x and 3.7.x Persistent Recursive Watches are supported only when using the standard "watch manager", and not `zookeeper.watchManagerName`=`WatchManagerOptimized`
http://zookeeper.apache.org/doc/r3.7.0/zookeeperAdmin.html

**Comment by tisonkun** [comment]
Closed as delivered in https://pulsar.apache.org/release-notes/versioned/pulsar-2.9.0/
