### ISSUE TITLE
[doc] Message redelivery and acknowledgement

### ISSUE THREAD

**Issue by Jennifer88huang** [apache/pulsar#11625]
**Is your feature request related to a problem? Please describe.**
In the current [messaging docs](https://pulsar.apache.org/docs/en/concepts-messaging/), there is no content related to message redelivery and acknowledgement.

**Describe the solution you'd like**
Add clear and concise description of message redelivery and acknowledgement.

**Comment by lhotari** [comment]
> In the current [messaging docs](https://pulsar.apache.org/docs/en/concepts-messaging/), there is no content related to message redelivery and acknowledgement.

Yes this is a gap. It might help to reference the "Message retention and expiry" docs ( https://pulsar.apache.org/docs/en/cookbooks-retention-expiry/ ) since that is related to redelivery and acknowledgement.
