### ISSUE TITLE
Inconsistency in backlog quota configuration

### ISSUE THREAD

**Issue by abhilashmandaliya** [apache/pulsar#11647]
**Describe the bug**
A backlog quota in the broker is configured differently from the broker's configuration file than the admin CLI. A configuration file accepts the limit in GB only as [backlogQuotaDefaultLimitGB](https://github.com/apache/pulsar/blob/402a88dae680c825b548f10e9aa5eb39d12b932b/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java#L342) param whereas you can [update it from the CLI](https://github.com/apache/pulsar/blob/402a88dae680c825b548f10e9aa5eb39d12b932b/pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java#L1089) in KB, MB, GB and TB which is parsed by the [common code](https://github.com/apache/pulsar/blob/402a88dae680c825b548f10e9aa5eb39d12b932b/pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CliCommand.java#L81). Also, the parsing code [assumes](https://github.com/apache/pulsar/blob/402a88dae680c825b548f10e9aa5eb39d12b932b/pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CliCommand.java#L101) that the value is numeric if it is not any of the KB, MB, GB and TB which may cause NumberFormatException at the run time.

**Expected behavior**
Broker file should also accept it in KB, MB, GB and TB. In the default case of parsing, we should check for the numeric value and throw some appropriate Pulsar Exception if the value is non-numeric.

I can take this up if it looks legitimate.

**Comment by abhilashmandaliya** [comment]
@eolivelli @lhotari PTAL

**Comment by liangyuanpeng** [comment]
Seems like we support now. (master)
