### ISSUE TITLE
deadLetterPolicy is not working with key shared subscription

### ISSUE THREAD

**Issue by srouthu1** [apache/pulsar#11652]
#### Expected behavior

I have created consumer with the following code.
Consumer consumer = client.newConsumer()
                .topic("persistent://mytenant/myns/mytopic")
                .subscriptionName(userName+"-default")
                 .subscriptionType(SubscriptionType.Key_Shared).keySharedPolicy(KeySharedPolicy.autoSplitHashRange())
                .receiverQueueSize(10)
                .deadLetterPolicy(DeadLetterPolicy.builder()
                        .maxRedeliverCount(3)
                        .deadLetterTopic("persistent://mytenant/myns/mytopic-userName-default.DLQ")
                        .build())
        .ackTimeout(40,TimeUnit.SECONDS)
                .subscribe();

My my publisher sends messages with different keys.

My consumer receives the messages but it does not acknowledge the message because I want the messages to be moved to dead letter topic.

I am expecting the messages to redelivered to my consumer 3 times and then they should be published to dead letter topic.

#### Actual behavior

The messages are getting redelivered to my consumer unlimited times. They never moved to dead letter topic.
If I change the subscription type to shared then the messages are moving to dead letter topic. 

#### System configuration
Pulsar version: Tried with both 2.6.0 and 2.8.0
Pulsar Client: 2.6.0

**Comment by leizhiyuan** [comment]
in DeadLetterTopicTest

**Comment by codelipenghui** [comment]
@srouthu1 Have you tried a new Pulsar Client version? I noticed the client version is 2.6.0 which released almost 2 years ago.

**Comment by srouthu1** [comment]
Hi @codelipenghui @leizhiyuan I am able to reproduce this issue with multi-topic consumer of a key shared subscription, can you please check if you can reproduce this issue

**Comment by codelipenghui** [comment]
@srouthu1 Which Pulsar version are you testing? /cc @Technoboy-

**Comment by srouthu1** [comment]
@codelipenghui I am using 2.8 version

**Comment by Technoboy-** [comment]
@codelipenghui @srouthu1 
When is the partitioned topic, broker (2.8, latest version), client version (2.6, 2.8) could reproduce this issue.
We will fix this later. Please assign to me.
