### ISSUE TITLE
install on mac client fail

### ISSUE THREAD

**Issue by xtuyaowu** [apache/pulsar#11747]
-- ARCHITECTURE: x86_64
-- BUILD_DYNAMIC_LIB:  ON
-- BUILD_STATIC_LIB:  ON
-- BUILD_TESTS:  ON
-- BUILD_PYTHON_WRAPPER:  ON
-- BUILD_PERF_TOOLS:  OFF
-- LINK_STATIC:  OFF
-- USE_LOG4CXX:  OFF
-- CMAKE_BUILD_TYPE:  RelWithDebInfo
-- Threads library: 
Failed to find Protobuf in config mode, try to find it from system path
-- Protobuf_LIBRARIES: /usr/local/lib/libprotobuf.dylib
-- Protobuf_INCLUDE_DIRS: /usr/local/include
-- Found Boost: /usr/local/include (found version "1.76.0")  
-- Using std::regex
-- PYTHON: 3.7.7
-- DETECTED Python 3
-- Found Boost: /usr/local/include (found version "1.76.0") found components: python39 
-- HAS_ZSTD: 1
-- HAS_SNAPPY: 0
-- Using Boost Python libs: /usr/local/lib/libboost_python39-mt.dylib;Boost_PYTHON37-MT_LIBRARY_RELEASE-NOTFOUND
CMake Error at python/CMakeLists.txt:85 (MESSAGE):
  Could not find Boost Python library

-- Configuring incomplete, errors occurred!
See also "/Users/admin/Documents/study/workspace/trade-test/third_party/pulsar/pulsar-client-cpp/CMakeFiles/CMakeOutput.log".

**Comment by DAvalentinC** [comment]
Same error on macos 12.0.1 (monterey)

**Comment by Andreashej** [comment]
I get the same error on MacOS 12.0.1

**Comment by BewareMyPower** [comment]
A simple patch is to remove these lines https://github.com/apache/pulsar/blob/d033e726e0981851d9d196da0e4fe3d12c11b863/pulsar-client-cpp/python/CMakeLists.txt#L74-L80
