### ISSUE TITLE
[website] website upgrade

### ISSUE THREAD

**Issue by urfreespace** [apache/pulsar#11766]
## Preview
- [x] make preview supported on netlify https://github.com/apache/pulsar/pull/11770?w=1

## New syntax rules
Click [here](https://docs.google.com/document/d/1IV35SI_F8G8cL-Vuzknc6RTGLK9_edRMpZpnrHvAWNs/edit#) to see details.

### Base framework
- [x] init website-next base project https://github.com/apache/pulsar/pull/11770?w=1

### Compatibility process 
1. [x] implement custom link remark parser match {@inject: prefix:name:path}
2.[ ] implement custom link remark parser match {@inject: endpoint|POST|/admin/v3/sources/:tenant/:namespace/:sourceName|operation/registerSource?version=[[pulsar:version_number]]}
3. [x] md tabs migration https://github.com/apache/pulsar/pull/11908
4. [x] html tags compatibility process for br
5. [x] html tags compatibility process for li
6. [x] html tags compatibility process for span & style
7. [x] html tags compatibility process for table
8. [x] md internal jumper link fix
9. [x] static resource link fix, assets/xxx -> /assets/xxx

### Docs migration

**Detail**
<details>
<summary>Click Show List</summary>
<pre>
<code>
</code>
</pre>
</details>

### Pages migration
//TODO 

### Scripts migration
//TODO

### Css migration
//TODO

### Swagger migration
//TODO

### Other migration
//TODO

**Comment by dave2wave** [comment]
You can find the Incubator releases here: https://archive.apache.org/dist/incubator/pulsar/

**Comment by Anonymitaet** [comment]
Hi @dave2wave Thanks for your answer. However, https://archive.apache.org/dist/incubator/pulsar/ hosts code files rather than doc files. We are looking for doc files (source files) of these versions, do you know where hosts them? Thanks again

- 2.0.1-incubating
- 2.0.0-rc1-incubating
- 1.22.0-incubating
- 1.21.0-incubating
- 1.20.0-incubating
- 1.19.0-incubating
