### ISSUE TITLE
ConcurrentModificationException occurs when failPendingMessages

### ISSUE THREAD

**Issue by Shoothzj** [apache/pulsar#11783]
### Describe the bug
![image](https://user-images.githubusercontent.com/12933197/130885099-ecb22a9c-5422-4057-9f00-d85d1c24b84b.png)

### To Reproduce
It's hard to reproduce.

### Expected behavior
Keep the list operation safely.

Additional context
It occurs when restarting one of brokers(there were 2 running brokers), first client recevied `DisConnected` event, and then ConcurrentModificationException and some recycled already exception in timer task's OpSendMsg

**Comment by Shoothzj** [comment]
I just figure out why, because the client code retry to send messages when exception occurred to avoid network "Jitter"(Translate on google). the sample code are like this
```java
 String topic = "test";
        PulsarClient pulsarClient = PulsarClient.builder()
                .serviceUrl("http://127.0.0.1:8080")
                .build();
        ProducerBuilder<String> producerBuilder = pulsarClient.newProducer(Schema.STRING).enableBatching(true);
        Producer<String> producer = producerBuilder.topic(topic).create();

        final TypedMessageBuilder<String> stringTypedMessageBuilder = producer.newMessage();
        final TypedMessageBuilder<String> value = stringTypedMessageBuilder.key("1").value("2");
        final CompletableFuture<MessageId> completableFuture = value.sendAsync();
        completableFuture.exceptionally(throwable -> {
            producer.sendAsync("xxxx");
            return null;
        });
```
The `exceptionally` is called from `ProducerImpl.failPendingMessages`'s forEachLoop, and `sendAsync` will add messages to `pendingMessages`, then the error ocurred.

I have a question. Should we allow to retry on `exceptionally` callback or prohibit usage like that ?

@315157973 @eolivelli @merlimat , thanks

**Comment by 315157973** [comment]
In my opinion, we can only use interfaces to restrict the use of methods, verbal conventions are not a good way

**Comment by eolivelli** [comment]
Cannot prevent the user to call `sendAsync` that way.
We have to deal with this case.
Now that you have a reproducer it will be easier to create a test case that reproduces the issue.
good catch !

**Comment by lhotari** [comment]
Good catch @Shoothzj !

> I have a question. Should we allow to retry on exceptionally callback or prohibit usage like that ?

I think that this is a bug that needs to be fixed. I took a quick look and I have a relatively simple way to solve it.

**Comment by lhotari** [comment]
I created #11884 as a draft PR to fix the issue. I don't have a way to reproduce the problem in a test case and that's one of the problems.

**Comment by 315157973** [comment]
Is there any progress here? Why not just set the queue to concurrent?

**Comment by lhotari** [comment]
> Is there any progress here? Why not just set the queue to concurrent?

there's progress in #11884, it's currently in draft. 

@315157973 I replied in https://github.com/apache/pulsar/pull/11884#issuecomment-911169103 . Does that answer your question?
