### ISSUE TITLE
[Doc] missed doc for topic lookup metrics

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#11805]
https://github.com/apache/pulsar/pull/8272 introduced some new metrics for the topic lookup but looks like we don't have any documentation for the new metrics

**Comment by sijia-w** [comment]
@Anonymitaet Just wanna confirm with you: should I add the metrics [here](https://pulsar.apache.org/docs/en/next/reference-metrics/#topic-metrics)? Thanks in advance.

**Comment by Anonymitaet** [comment]
@sijia-w I think you can add a `Topic lookup metrics` subsection after `Replication metrics` subsection.
@codelipenghui @merlimat please correct me if I'm wrong, thanks.

![image](https://user-images.githubusercontent.com/50226895/131940496-73d6b6d6-080b-47ef-99b1-2bfc2bf37743.png)

**Comment by sijia-w** [comment]
@Anonymitaet Thank you for your reply. That's also what I thought. Will do accordingly.
