### ISSUE TITLE
after split bundle,what happened next

### ISSUE THREAD

**Issue by NothinkingGao** [apache/pulsar#11836]
if a topic request to broker1,after a while the bundle of the topic be splited to broker2,then the topic still request broker1,what happened next,the broker1 handle this request or broker2 handle it,what the flow,could anyone can help

**Comment by liangyuanpeng** [comment]
I think you can talk about this in mail list or slack.

**Comment by lhotari** [comment]
Besides the mailing list or Pulsar Slack, you can also ask questions on Stackoverflow, please use the [apache-pulsar tag](https://stackoverflow.com/tags/apache-pulsar).
