### ISSUE TITLE
[Java client] Allow consumer to be created in a paused state

### ISSUE THREAD

**Issue by zwalsh-toast** [apache/pulsar#11846]
**Is your enhancement request related to a problem? Please describe.**
Our applications currently start up and immediately subscribe and consume pulsar messages. We would like to decouple deployment from activation, and then use pause/resume to safely turn different deploys on and off.

**Describe the solution you'd like**
Add an option to the consumer builder to subscribe in a paused state, e.g.:
```kotlin
val consumer = pulsarClient.newConsumer()
    .topic(topic)
    .subscriptionName(name)
    .subscriptionType(SubscriptionType.Shared)
    .receiverQueueSize(1000)
    // ...
    .paused(true)
    .subscribe()
```

**Describe alternatives you've considered**
* Subscribe and then pause immediately
   * This will increment the number of permits up to `receiverQueueSize`, making those messages inaccessible to active consumers
* Override `subscribeAsync` to defer the initial subscribe
   * This is not backwards compatible for most of our applications
   * Can't verify authentication/configuration until the subscribe occurs
   * Adds unnecessary complexity

**Comment by codelipenghui** [comment]
@zwalsh-toast Are you interested in contributing the feature in Pulsar?  Sounds good if we have an option to control the message flow when creating a consumer.

**Comment by zwalsh-toast** [comment]
> @zwalsh-toast Are you interested in contributing the feature in Pulsar? Sounds good if we have an option to control the message flow when creating a consumer.

Hi @codelipenghui - yes, I'll be working on it this week!

**Comment by codelipenghui** [comment]
@zwalsh-toast Cool! Looks forward to your great contribution.
