### ISSUE TITLE
Deleting a topic should succeed even if data is gone from bookies

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#1190]
If the data is completely gone from all the bookies replicas, the delete topic operation should anyway succeed as it should only depend on ZooKeeper

**Comment by MarvinCai** [comment]
@merlimat 
Looking into the code, [PersistentTopic#delete](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L838) will first remove cursor metadata then remove cursor ledgers, but it doesn't care about result of deleting cursor ledger so it'll proceed even with failure. Then it'll try [delete all ledgers](https://github.com/apache/pulsar/blob/master/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L2195-L2202), and this method will treat BKException.Code.NoSuchLedgerExistsException as succeed  and proceed to delete ledger metadata from ZK if all ledger either deleted successfully or doesn't exist anymore. 
So seems current logic to delete topic can handle the situation you mentioned properly when ledgers are already gone from bookkeeper. Is there any further change need to made?

**Comment by merlimat** [comment]
The error was not referring to the `NoSuchLedgerExistsException`. That is when the metadata for the ledger is not found. 

There are still examples in which the topic will fail to get deleted: 
 1. Create a topic, create some subscription and publish some data
 2. Delete the data from the bookie (all the replicas)
 3. Kill broker
 4. Try to delete topic

What will happen is that a new broker will first try to load the topic, triggering the ledger recovery operation, which will fail since the data is gone.

**Comment by MarvinCai** [comment]
can be close via https://github.com/apache/pulsar/pull/7131

**Comment by tisonkun** [comment]
Closed.
