### ISSUE TITLE
use helm install pulsar on k8s, how change the nodeport, then can connect from machine b.

### ISSUE THREAD

**Issue by chlyzzo** [apache/pulsar#11909]
# What issue do you find in Pulsar docs?

from https://pulsar.apache.org/docs/zh-CN/kubernetes-helm/, use helm install pulsar on k8s, and get the services:
<img width="842" alt="9bf8b42d0b5e4207a1e887a88b60deee" src="https://user-images.githubusercontent.com/19646469/131947256-dac7149f-8346-40b1-8e7c-3251494efad2.png">

but the service, like pulsar-spatio-pulsar-manager, the port 31335 is random change, when uninstall then install again,
pulsar-spatio-pulsar-manager   NodePort       10.233.46.47    <none>        9527:31335/TCP                8s

because my k8s only 8*** port can connect from other machine, so how can i define the port, for example, define :
 pulsar-spatio-pulsar-manager   NodePort       10.233.46.47    <none>        9527:8527/TCP                8s

# What is your suggestion?

(For example, add explanations about xx, correct descriptions of xx, delete information about xx, etc)

# Do you have any references?

(For example, website links, etc)?

# Would you like to fix this issue?

(Welcome to contribute docs! Pulsar grows from a tiny seed to a big tree with every little effort by us! Your contribution is the sunlight, water, and air!)

**Comment by michaeljmarshall** [comment]
@chlyzzo - Node ports are random if they are not declared in the yaml. The current helm chart does not allow for setting the node port for the pulsar manager. Are you trying to connect to it from inside the k8s cluster or from outside the cluster? Also, it looks like you want the port to be 4 digits. This is not possible in k8s, as node ports range from 30000 to 32767. https://kubernetes.io/docs/concepts/services-networking/service/#nodeport

**Comment by lhotari** [comment]
@michaeljmarshall provided an answer to the problem as a resolution to this issue. Closing this.
