### ISSUE TITLE
help Java client topicsPattern 

### ISSUE THREAD

**Issue by siaron** [apache/pulsar#11914]
**Describe the solution you'd like**
```
 pulsarClient.newConsumer()
                .topicsPattern("persistent://*/default/pattern-topic")
```
- Is it possible to consume topics from multiple tenants
- Whether to automatically consume when adding tenant's topic

**Comment by codelipenghui** [comment]
@siaron Currently you can only apply the regex patterns under a namespace, there is a PR for supporting the regex patterns across tenants and namespaces but have not merged yet.

**Comment by siaron** [comment]
针对此功能后续的如何计划的?

**Comment by tisonkun** [comment]
See https://github.com/apache/pulsar/discussions/18862

Currently, there is no active development on this direction.

Close as duplicate.
