### ISSUE TITLE
Can't use "bin/pulsar standalone" cmd on powershell in Windows 10

### ISSUE THREAD

**Issue by SonMooSans** [apache/pulsar#11926]
I am new to pulsar, when I follow the doc to setup pulsar
The doc tells me use "bin/pulsar standalone" cmd to start Pulsar standalone
but the system only ask me to choose software to open the file
What should I do, am I missed something?

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant in maintained versions.

Also, the issue report is lack of log, error message or reproduce steps so that we can hardly look into it.
