### ISSUE TITLE
Forget to call Sendcallback on a branch of closeAsync

### ISSUE THREAD

**Issue by Shoothzj** [apache/pulsar#11936]
In #11906 , it fixed the update of memory usage, but still one branch of `closeAsync` doesn't call callback too.

But this seems hard to write an unit test. This needs during the producer close, the broker is ready, and there are still remaining pending messages.

Any idea for how to add tests? 

@codelipenghui @merlimat @michaeljmarshall

**Comment by codelipenghui** [comment]
@Shoothzj Maybe we can disable the channel auto_read at the broker side for simulating the messages pending in the queue.

**Comment by Shoothzj** [comment]
> @Shoothzj Maybe we can disable the channel auto_read at the broker side for simulating the messages pending in the queue.

But we still need a close success resp from broker side. How ?

**Comment by codelipenghui** [comment]
@Shoothzj You can create a method for handling the close producer response, then you can call it directly. If the code is untestable, we should make it testable.

**Comment by Shoothzj** [comment]
> @Shoothzj You can create a method for handling the close producer response, then you can call it directly. If the code is untestable, we should make it testable.

Thanks a lot for your help, I found the way to add test.
