### ISSUE TITLE
Pulsar client oauth2 client support optional parameter scope

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar#11932]
Please answer the following questions before submitting your doc issue. Thanks!

# What issue do you find in Pulsar docs?

(For example, something missing, inaccurate, incomplete, hard to use/understand/find, etc)

# What is your suggestion?

(For example, add explanations about xx, correct descriptions of xx, delete information about xx, etc)

# Do you have any references?

(For example, website links, etc)?

# Would you like to fix this issue?

(Welcome to contribute docs! Pulsar grows from a tiny seed to a big tree with every little effort by us! Your contribution is the sunlight, water, and air!)

**Comment by lhotari** [comment]
#11931 was merged. Closing this one.
