### ISSUE TITLE
Pulsar-Client Has Too Much Third Jars

### ISSUE THREAD

**Issue by wangqianfront** [apache/pulsar#11968]
When I use pulsar-client to provide a  message-client to my customer, I found pulsar-client has 40MB Size，it's really too large.

Then I look at why it's so big, I found the shade-plugin include so much third jars.

**Comment by eolivelli** [comment]
you can use "pulsar-client-original" that does not include shaded jars.
it will probably play well with other dependencies.
but you sure take care of version compatibility

**Comment by tisonkun** [comment]
Closed as answered. If you have a specific deps to exclude for good, like https://github.com/apache/pulsar/pull/20687, feel free to proceed. Vague blame won't help.
