### ISSUE TITLE
Why is the topic of the pulsar protocol not like the mqtt protocol, it can support aaa/bbb/ccc or aaa/# or aaa/+/bbb

### ISSUE THREAD

**Issue by beyondyinjl2** [apache/pulsar#11978]
The topic of the pulsar protocol: persistent://public/default/my-topic, why the last local-name does not support/, like the mqtt protocol, it can support aaa/bbb/ccc or aaa/# or aaa/+/bbb, I Think it should be easy to achieve

**Comment by MarvinCai** [comment]
From my point of view, Pulsar is already using `/` as a special character to separate different part in the topic name, like schema, tenant, namespace, topic
`/` in topic name will just be misleading as user will think there're more level of topic grouping while there isn't.

**Comment by liangyuanpeng** [comment]
@beyondyinjl2 
Actually, Pulsar support  this format of topic now，like persistent://public/default/my-topic/A/B.

And you can use `topicsPattern` for consumer to receive multiple topics message.

**Comment by beyondyinjl2** [comment]
topicsPattern cannot use * wildcards for tenants and namespaces

**Comment by lhotari** [comment]
@beyondyinjl2 please discuss this type of topics on the mailing list or on Pulsar Slack.
