### ISSUE TITLE
Zookeeper prometheus metrics inconsistent with Docs.

### ISSUE THREAD

**Issue by senax** [apache/pulsar#11984]
**Describe the bug**
The [documentation ](https://pulsar.apache.org/docs/en/reference-metrics/#zookeeper) and [zookeeper dashboard](https://github.com/streamnative/apache-pulsar-grafana-dashboard.git) use prometheus metrics prefixed with 'zookeeper_server_' which are no longer there.

For example `zookeeper_server_connections`

**To Reproduce**
1. `docker run --rm -d -p 2181:2181 --name zk apachepulsar/pulsar:2.8.0  bin/pulsar zookeeper`
2. `curl -s localhost:8000/metrics |grep ^zoo`
3. No zookeeper named metrics.
4. `curl -s localhost:8000/metrics`
5. Lots of output, so prometheus is working.
6. `docker rm -f zk`

**Expected behavior**
The documentation and grafana dasboards should use the correct metrics.

**Comment by Anonymitaet** [comment]
Hi @senax Thanks for raising this up. Can you update docs accordingly? Then you can ping me to review, thanks

**Comment by Anonymitaet** [comment]
Confirmed w/ @codelipenghui, the content in the red box is out-of-date, they should be replaced with the latest ZK metrics.
But there are no metrics descriptions on [ZK doc website](https://zookeeper.apache.org/doc/r3.7.0/zookeeperMonitor.html#Metrics), we might need to find the appropriate ZK metrics used in Pulsar and update the doc accordingly.

@senax could you please update the docs? Then you can ping me to review, thanks

![image](https://user-images.githubusercontent.com/50226895/132791840-bdc21e18-e012-487d-a823-63efc487482c.png)
