### ISSUE TITLE
ZK Unable to read additional data from server while initialize-cluster-metadata

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#11996]
**Describe the bug**
![image](https://user-images.githubusercontent.com/54351417/132820281-a3df9d3c-947d-4d53-b23b-65caa582fa4d.png)

**To Reproduce**
1. bin/pulsar initialize-cluster-metadata XXXX

**Comment by MarvinCai** [comment]
From ZK side, it seems an acceptable behavior: https://github.com/apache/zookeeper/blob/master/zookeeper-server/src/main/java/org/apache/zookeeper/ClientCnxn.java#L1283-L1290
Also pulsar metadata initialization seems completed as log `Cluster metadata for 'xxx' setup correctly`
Is the cluster not working as expected after the init script?

**Comment by xuesongxs** [comment]
> From ZK side, it seems an acceptable behavior: https://github.com/apache/zookeeper/blob/master/zookeeper-server/src/main/java/org/apache/zookeeper/ClientCnxn.java#L1283-L1290
> Also pulsar metadata initialization seems completed as log `Cluster metadata for 'xxx' setup correctly`
> Is the cluster not working as expected after the init script?

Pulsar cluster works normally.

**Comment by tisonkun** [comment]
Closes as answered. This is a warning and the final state is clean.
