### ISSUE TITLE
Some errors A few minutes after the container starts

### ISSUE THREAD

**Issue by billyShen198602** [apache/pulsar#11999]
I use the standalone image pulled by docker for deployment，Why is there such an error report？
WARN  org.apache.bookkeeper.stream.storage.impl.sc.ZkStorageContainerManager - Failed to start storage container (1)
java.util.concurrent.CompletionException: org.apache.distributedlog.exceptions.BKTransmitException: Failed to open ledger handle for log segment [LogSegmentId:1, firstTxId:1, lastTxId:-999, version:VERSION_V5_SEQUENCE_ID, completionTime:0, recordCount:0, regionId:0, status:0, logSegmentSequenceNumber:1, lastEntryId:-1, lastSlotId:-1, inprogress:true, minActiveDLSN:DLSN{logSegmentSequenceNo=1, entryId=0, slotId=0}, startSequenceId:0] : -10

**Comment by eolivelli** [comment]
which is your command to start Pulsar ?

**Comment by billyShen198602** [comment]
docker run -itd --name my_pulsar -p 6650:6650 -p 8080:8080 --mount source=pulsardata,target=/pulsar/data --mount source=pulsarconf,target=/pulsar/conf my_pulsar:v1.0.feature_test

**Comment by liangyuanpeng** [comment]
> docker run -itd --name my_pulsar -p 6650:6650 -p 8080:8080 --mount source=pulsardata,target=/pulsar/data --mount source=pulsarconf,target=/pulsar/conf my_pulsar:v1.0.feature_test

So what's mean `my_pulsar:v1.0.feature_test` of docker image?

**Comment by tisonkun** [comment]
Close. We cannot debug a personal fork, especially no source code even.
