### ISSUE TITLE
pulsar-client>=2.8.0 is missing dependencies that used to be specified for pulsar-client==2.7.0. 

### ISSUE THREAD

**Issue by thesquiff** [apache/pulsar#12002]
pulsar-client==2.7.0 had the following dependencies listed (pip show):

certifi, protobuf, fastavro, apache-bookkeeper-client, ratelimit, prometheus-client, six, grpcio

pulsar-client>=2.8.0 only lists the following dependencies:

certifi, six

This means that when python-instance tries to start up it complains about not being able import from protobuf etc until they are all installed manually. I can't find anywhere that specifies the versions of the packages that should be installed for 2.8.0.

This was observed in a cluster environment rather than the standalone install. Centos 7 / Python 3.6.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant in maintained versions.

BTW, the development of the Python client is permanently moved to https://github.com/apache/pulsar-client-python.
