### ISSUE TITLE
Tenant namespace topic length limit

### ISSUE THREAD

**Issue by beyondyinjl2** [apache/pulsar#12023]
What are the length limits for tenants, namespaces, and localnames?

**Comment by Anonymitaet** [comment]
Hi @beyondyinjl2 thanks for your question.  

If you want to create a doc issue, please use the [doc issue template](https://github.com/apache/pulsar/issues/new?assignees=&labels=doc-required&template=doc_request.md&title=) and answer the questions there. 
Please show your research, question, and potential solution. In this way, others know your thoughts more clearly, thanks.

**Comment by RobertIndie** [comment]
Currently, Pulsar didn't introduce the length limit for the name of tenants, namespaces and topic.

**Comment by momo-jun** [comment]
> @momo-jun should this be documented?
> 
> > Currently, Pulsar didn't introduce the length limit for the name of tenants, namespaces, and topics.

I think it is not necessary. If there is a limit, we should document it; if not, it's good to go and don't over-communicate.

**Comment by Anonymitaet** [comment]
I think it makes sense to document this to reduce guesswork. Other users may have the same issue if we do not explain it explicitly.

**Comment by michaeljmarshall** [comment]
I don't know of length restrictions, but there are character restrictions for tenants and namespaces. Here is the comment in the code:

https://github.com/apache/pulsar/blob/eec46ddcba4d2b4f956e1b4d63154cc43087f507/pulsar-common/src/main/java/org/apache/pulsar/common/naming/NamedEntity.java#L30-L33

Note that the logic does not apply to topic names for some reason. I don't know why.

**Comment by momo-jun** [comment]
Closed the issue since the original question has been addressed. Feel free to reopen it when it's relevant.
