### ISSUE TITLE
Topic does not have schema to check

### ISSUE THREAD

**Issue by beyondyinjl2** [apache/pulsar#12048]
The specified object subscription data error: Topic does not have schema to check
code:
Consumer<DeviceDataBean> consumer = pulsarClient.newConsumer(Schema.JSON(DeviceDataBean.class))
					.topicsPattern(topicsPattern)
					.subscriptionName(subscriptionName)
					.subscriptionTopicsMode(RegexSubscriptionMode.AllTopics)
					.subscribe();

**Comment by Shawyeok** [comment]
How did you get this issue? Have you enable `brokerDeleteInactiveTopicsEnabled`, or could you share your `broker.conf`?
