### ISSUE TITLE
Docker and dashboard

### ISSUE THREAD

**Issue by ZedZipDev** [apache/pulsar#12050]
I run the app CsharpExamples and RunSimple() function only.

If I run the docker as wrote in the doc
`docker run -it -p 6650:6650 -p 8080:8080 --mount source=pulsardata,target=/pulsar/data --mount source=pulsarconf,target=/pulsar/conf apachepulsar/pulsar:2.8.0 bin/pulsar standalone
`
and then run the test app it works fine.

If I run the docker-compose file
https://github.com/apache/pulsar/tree/master/docker-compose/standalone-dashboard
then:
1. the dashbord works fine on http://localhost:80
2. my app cannot connect and send message to the pulsar://locahost:6650

What is wrong?

**Comment by michaeljmarshall** [comment]
@Oleg26Dev - I would recommend working with the [Pulsar Manager](https://pulsar.apache.org/docs/en/administration-pulsar-manager/). The Pulsar Dashboard is deprecated in 2.8.x and is removed in 2.9.0. This was discussed recently on the dev mailing list [here](https://lists.apache.org/x/thread.html/red2428e8a50fa93dbdd5bdc950cf60dbe6839c322c0ad662b4786107@%3Cdev.pulsar.apache.org%3E) and it was already removed in https://github.com/apache/pulsar/pull/11284.

**Comment by tisonkun** [comment]
Closed as described above.
