### ISSUE TITLE
pulsar-admin sinks localrun options

### ISSUE THREAD

**Issue by allnode-github** [apache/pulsar#12055]
The program example in the sins pulse to PostgreSQL document is based on the cluster environment. The database table cannot be successfully inserted in the stand-alone mode. Can you create a new configuration example in the stand-alone mode? In stand-alone mode, pulsar 2.8.1.0, mop 2.8.1.0, pulsar-io-jdbc-postgres-2.8.0.nar

**Comment by Shoothzj** [comment]
You mean stand-alone pulsar ? 
What's the program example ?

**Comment by allnode-github** [comment]
Thank you for your attention. Yes, I have successfully run the local stand-alone mode pulsar according to the document. Now I need to run the stand-alone mode pulsar admin sins localrun options in the same computer. I have operated according to the document and found no problems at all, but I still can't write the pulsar message into the PostgreSQL database table in the end, Although this message can be subscribed to the mqtt client normally. Pulsar admin sins localrun options only indicates that there are no single mode routines. The routines in the document are in cluster mode D

**Comment by Shoothzj** [comment]
Could you please give me the example link ?

**Comment by allnode-github** [comment]
[](https://pulsar.apache.org/docs/zh-CN/io-quickstart/#connect-pulsar-to-postgresql)
I just refer to this document completely. However, data cannot be inserted into the table in the database.

**Comment by allnode-github** [comment]
https://pulsar.apache.org/docs/zh-CN/io-quickstart/#connect-pulsar-to-postgresql

**Comment by Shoothzj** [comment]
> https://pulsar.apache.org/docs/zh-CN/io-quickstart/#connect-pulsar-to-postgresql

https://github.com/apache/pulsar/pull/12124. You can look if this PR fix your problem
