### ISSUE TITLE
PersistentReplicator Unexpected exception: null

### ISSUE THREAD

**Issue by sruon** [apache/pulsar#12074]
**Describe the bug**
Whenever replication is enabled between two clusters, we come across the following error messages:

```
17:09:22.536 [bookkeeper-ml-workers-OrderedExecutor-3-0] ERROR org.apache.pulsar.broker.service.persistent.PersistentReplicator - [persistent://xxx/xxx/default-partition-1][xxxA -> xxxB] Unexpected exception: null
```

- The messages appear every couple seconds
- The messages appear on both ends
- The replication appears to be operating properly
- Replication was enabled and disabled a couple of times with no meaningful progress, the error keeps appearing.
- There's no stack trace occuring with the message

**To Reproduce**
- Unclear how to reproduce the issue, it appears on a specific pair of clusters.

**Expected behavior**
- No error messages

**Screenshots**

**Desktop (please complete the following information):**
- Pulsar 2.6.1
- Kubernetes
- AWS environment on both ends

**Additional context**
We're not clear if this is causing any actual issue, the exception happens in this block https://github.com/apache/pulsar/blob/v2.6.1/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java#L332 but we're not sure exactly which code line is causing this.

I found #9763 that may be related, let me know if it is the case.

**Comment by gaoran10** [comment]
It seems that PR #9763 fixed an NPE problem, but this issue didn't have clear error information. The topic replication could work well, right? Could the remote topic receive all replicated messages?

**Comment by tisonkun** [comment]
Closed as inactive. If it's still relevant to the maintained versions, please open a new issue.
