### ISSUE TITLE
PIP 96: Message payload processor for Pulsar client

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar#12087]
## Motivation

The initial motivation was from Kafka's protocol handler, i.e. KoP (https://github.com/streamnative/kop). KoP allows Kafka producer to configure entry format to `kafka`, which means the message from Kafka producer can be written to bookies directly without any conversion between Kafka's message format and Pulsar's message format. This improves the performance significantly. However, it also introduced the limit that Pulsar consumer cannot consume this topic because it cannot recognize the entry's format.

The existing `ConsumerInterceptor` cannot work for this case because it's based on a `Message<T>` object that is converted from an entry with valid Pulsar format. 

## Goal

This proposal tries to introduce a payload processor for Pulsar client, which performs a conversion for payload (without metadata parts) at client side. The processor is responsible to transfrom a raw buffer to some messages, then triggers some callbacks so that consumers can consume these messages or handle the error.

This proposal is mainly for protocol handlers because they can access `PersistentTopic` and write bytes to bookies directly. In a rare case, if users want to write something to the topic's ledger directly by BookKeeper client, the payload processor can also handle the case.

## API Changes

Since we cannot add any dependency to the pulsar-client-api module to avoid cyclic dependency while we need to access `BrokerEntryMetadata`, `MessageMetadata` and `ByteBuf`, this proposal adds following two interfaces.

```java
/**
 * The context of an entry, which usually represents a message of a batch if batching is enabled.
 */
public interface EntryContext {

    /**
     * Get a value associated with the given key.
     *
     * @param key
     * @return the value associated with the key or null if the key or value doesn't exist
     */
    String getProperty(String key);

    /**
     * Get the number of messages.
     *
     * Since the message could be batched, a message could have multiple internal single messages.
     *
     * @return the number of internal single messages or 1 if the message is not batched.
     */
    int getNumMessages();

    /**
     * Check whether the entry is a batch.
     *
     * @return true if the entry is a batch.
     */
    boolean isBatch();

    /**
     * Get the internal single message with a specific index from a payload if the entry is a batch.
     *
     * @param index the batch index
     * @param numMessages the number of messages in the batch
     * @param payload the message payload
     * @param containMetadata whether the payload contains the single message metadata
     * @param schema the schema of the batch
     * @param <T>
     * @return the single message
     * @implNote The `index` and `numMessages` parameters are used to create the message id with batch index.
     *   If `containMetadata` is true, parse the single message metadata from the payload first. The fields of single
     *   message metadata will overwrite the same fields of the entry's metadata.
     */
    <T> Message<T> getMessageAt(int index,
                                int numMessages,
                                MessagePayload payload,
                                boolean containMetadata,
                                Schema<T> schema);

    /**
     * Convert the given payload to a single message if the entry is non-batched.
     *
     * @param payload the message payload
     * @param schema the schema of the message
     * @param <T>
     * @return the converted single message
     */
    <T> Message<T> asSingleMessage(MessagePayload payload, Schema<T> schema);
}
```

```java
/**
 * The abstraction of a message's payload.
 */
public interface MessagePayload {

    /**
     * Copy the bytes of the payload into the byte array.
     *
     * @return the byte array that is filled with the readable bytes of the payload, it should not be null
     */
    byte[] copiedBuffer();

    /**
     * Release the resources if necessary.
     *
     * NOTE: For a MessagePayload object that is created from {@link MessagePayloadFactory#DEFAULT}, this method must be
     * called to avoid memory leak.
     */
    default void release() {
        // No ops
    }
}
```

- `EntryContext` is the abstraction of metadata and some resources of `ConsumerImpl`. `getProperty()`  is used to check the format tag. `getMessageAt()` and `asSingleMessage()` are used to create messages baed on a `MessagePayload`.

  > It should be noted that `getNumMessages()` and `isBatch()` only retrieve metadata from the `MessageMetadata` (see `PulsarApi.proto`). They should only be used for the default Pulsar format. Because in other Entry format, the actual metadata could be recorded inside the payload.

- `MessagePayload` is the abstraction of a payload buffer. The only usage for user is being passed to `EntryContext`'s methods to create `Message<T>`, which uses a Netty `ByteBuf` as the storage. Since users might pass a custom defined `MessagePayload`, it provides a `copiedBuffer()` method to copy bytes to a Netty `ByteBuf`.

  > We add this class mainly because **pulsar-client-api** module should not rely on Netty. If users still want to operate on the internal `ByteBuf`, see the **Implementation** section of this proposal.

In addition, a factory class is added for user to use the built-in `MessagePayload` implementation.

```java
public interface MessagePayloadFactory {

    MessagePayloadFactory DEFAULT = DefaultImplementation.getDefaultImplementation().newDefaultMessagePayloadFactory();

    /**
     * Create a payload whose underlying buffer refers to a byte array.
     *
     * @param bytes the byte array
     * @return the created MessagePayload object
     */
    MessagePayload wrap(byte[] bytes);

    /**
     * Create a payload whose underlying buffer refers to a NIO buffer.
     *
     * @param buffer the NIO buffer
     * @return the created MessagePayload object
     */
    MessagePayload wrap(ByteBuffer buffer);
}
```

The built-in `MessagePayload` implementation is backed by a Netty `ByteBuf`. So when it's converted to `ByteBuf`, no bytes copy will happen.

The core interface `PayloadProcessor` is based on the these two interfaces:

```java
/**
 * The processor to process a message payload.
 *
 * It's responsible to convert the raw buffer to some messages, then trigger some callbacks so that consumer can consume
 * these messages and handle the exception if it existed.
 *
 * The most important part is to decode the raw buffer. After that, we can call {@link EntryContext#getMessageAt} or
 * {@link EntryContext#asSingleMessage} to construct {@link Message} for consumer to consume. Since we need to pass the
 * {@link MessagePayload} object to these methods, we can use {@link MessagePayloadFactory#DEFAULT} to create it or just
 * reuse the payload argument.
 */
public interface PayloadProcessor {

    /**
     * Process the message payload.
     *
     * @param payload the payload whose underlying buffer is a Netty ByteBuf
     * @param context the message context that contains the message format information and methods to create a message
     * @param schema the message's schema
     * @param messageConsumer the callback to consume each message
     * @param <T>
     * @throws Exception
     */
    <T> void process(MessagePayload payload,
                     EntryContext context,
                     Schema<T> schema,
                     Consumer<Message<T>> messageConsumer) throws Exception;

    // The default processor for Pulsar format payload. It should be noted getNumMessages() and isBatch() methods of
    // EntryContext only work for Pulsar format. For other formats, the message metadata might be stored in the payload.
    PayloadProcessor DEFAULT = new PayloadProcessor() {

        @Override
        public <T> void process(MessagePayload payload,
                                EntryContext context,
                                Schema<T> schema,
                                Consumer<Message<T>> messageConsumer) {
            if (context.isBatch()) {
                final int numMessages = context.getNumMessages();
                for (int i = 0; i < numMessages; i++) {
                    messageConsumer.accept(context.getMessageAt(i, numMessages, payload, true, schema));
                }
            } else {
                messageConsumer.accept(context.asSingleMessage(payload, schema));
            }
        }
    };
}
```

Finally, we can configure our processor in `ConsumerBuilder`:

```java
    /**
     * If it's configured with a non-null value, the consumer will use the processor to process the payload, including
     * decoding it to messages and triggering the listener.
     *
     * Default: null
     */
    ConsumerBuilder<T> payloadProcessor(PayloadProcessor payloadProcessor);
```

## Implementation

For `EntryContext` and `MessagePayload` in **pulsar-client-api** module, there're the corresponding implementation classes `EntryContextImpl` and `MessagePayloadImpl`.

- `EntryContextImpl` holds references to metadata and consumer so that it can use `ConsumerImpl`'s methods to create a non-batched message or a single message of a batch using a `MessagePayload`.
- `MessagePayloadImpl` is just a wrapper of Netty `ByteBuf`.

We provided a util method `MessagePayloadUtils#convertToByteBuf` to convert `MessagePayload` to `ByteBuf`. It's simple so I just show the code.

```java
    public static ByteBuf convertToByteBuf(final MessagePayload payload) {
        if (payload instanceof MessagePayloadImpl) {
            return ((MessagePayloadImpl) payload).getByteBuf().retain();
        } else {
            return Unpooled.wrappedBuffer(payload.copiedBuffer());
        }
    }
```

Therefore, we recommend users to use `MessagePayloadFactory.DEFAULT` to create a `MessagePayloadImpl` to avoid coping bytes. Combining with `convertToByteBuf`, users could not use `MessagePayloadImpl` directly.
1. Use `MessagePayloadFactory.DEFAULT` to create a `MessagePayload` as the argument of `EntryContext`'s method.
2. Use `convertToByteBuf` to retrieve a Netty `ByteBuf` for read operations.

> I tried to wrap `ByteBuf`'s methods into `MessagePayload`. But it made code too huge. Otherwise it's still not flexible as `ByteBuf`'s original methods.

`ConsumerImpl` is refactored just to remove the repeated code and provide `newSingleMessage`/`newMessage` methods for `EntryContextImpl` to reuse.

By default, if no payload processor is configured, `ConsumerImpl` will still go through the original process. But if a processor is configured, the original process will be skipped and the process will process the payload instead.

The following tests should be added:

1. Unit tests for `MessagePayloadUtils#convertToByteBuf`.
2. Tests for `PayloadProcessor#DEFAULT`. It should cover the different scenarios, like one topic vs multiple topics, batching vs non-batching, batch size 1 vs N.
3. A custom process that decodes a specific format of message into messages that Pulsar consumer can recognize. The raw bytes are published by `PersistentTopic` directly.

## Reject Alternatives

There was [a proposal](https://github.com/apache/pulsar/issues/11962) that was discarded before. It tried to perform the conversion at the broker side before dispatching entries. However, the dispatcher run in a single thread when dispatching entries. The conversion cost might be affect all other topics.

Therefore, we should do it at the client side. It could bring overhead for Pulsar consumer but doesn't affect other topics.

Also, this proposal tried to load converter before, but it will be hard to maintain the compatibility.

This proposal has used the payload converter that converts a payload to `Iterable<Message<T>>` before, but the implementation is complex and has some flaws.

**Comment by BewareMyPower** [comment]
There're something in addition to the implementation.

Before this proposal, I tried to add following method.

```java
    /**
     * Set the payload converter class.
     *
     * The class must implement org.apache.pulsar.common.api.raw.PayloadConverter in pulsar-common module. Otherwise,
     * this method will fail silently. If this method was called successfully, each time a message arrived, the raw
     * payload will be replaced by a new payload returned by PayloadConverter#convert(ByteBuf).
     *
     * @param clazz
     * @return
     */
    ConsumerBuilder<T> payloadConverterClass(Class<?> clazz);
```

It's simple but looks ugly. After discussing with @codelipenghui, I adopted the current way to load converter at runtime. But there's something different. @codelipenghui's original opinion was that no changes should be made for client configs like `ConsumerBuilder`. However, there're some flaws for this solution. Because reflection brings overhead when creating a consumer. Though the overhead might not be significant, we should still avoid it for the regular cases.

I've thought of another solution that all consumers share the same converter so that the class loader could only be called once. But it might become complicated if there're multiple entry formats. For example, assuming we've enabled KoP, AoP, MoP for the same broker and there're three different entry formats. With PIP 96, we can implement three converters like:

- org.apache.pulsar.client.converter.kop.KafkaPayloadConverter
- org.apache.pulsar.client.converter.aop.AmqpPayloadConverter
- org.apache.pulsar.client.converter.mop.MqttPayloadConverter

Then we can create three consumers using a common `PulsarClient`. It's also why I configured the converter package at consumer level instead of client level.

**Comment by eolivelli** [comment]
Why can't we pass an instance of the converter instead of using classpath lookup?

**Comment by BewareMyPower** [comment]
@eolivelli `ConsumerBuilder` is a class in **pulsar-client-api** module that has no dependency. If **pulsar-common** was added as the dependency of **pulsar-client-api** because it will cause cyclic dependency.

```
org.apache.pulsar:pulsar-common:jar:2.9.0-SNAPSHOT
+- org.apache.pulsar:pulsar-client-api:jar:2.9.0-SNAPSHOT:compile
```

Also we can't put `PayloadConverter` into **pulsar-client-api** package because we must import `BrokerEntryMetadata` and `MessageMetadata` from **pulsar-common** package.

If we changed the `PayloadConverter` interface to

```java
interface PayloadConverter {
    ByteBuf convert(ByteBuf headerAndPayload);
}
```

Maybe it could work, but we need to parse `BrokerEntryMetadata` and `MessageMetadata` repeatedly in all valid implementations. BTW, we need to import netty dependency for `ByteBuf`. I'm not sure if it's proper for **pulsar-client-api** package to do that.

**Comment by eolivelli** [comment]
Now I understand better the problem.
Let me think more about it....

My first thought is that if we want this to be part on the client supported API then we must explicitly link to those APIs.

Maybe in some new Pulsar client API extensions package ?

Otherwise we risk to fail to support compatibility for future versions.

**Comment by BewareMyPower** [comment]
@eolivelli 

> Otherwise we risk to fail to support compatibility for future versions.

I don't understand well for the compatibility issue. The interface is a part of **pulsar-common** package. If there're no compatibility changes for `BrokerEntryMetadata` and `MessageMetadata`, it should be stable.

----

Actually there's a similar API. When creating a producer, we can configure a `BatcherBuilder` interface.

https://github.com/apache/pulsar/blob/fccc1cf60467bc0600c6507271cff85146d9f9e8/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/BatcherBuilder.java#L56-L60

However, this `build` method is meaningless. The actual type is `BatchMessageContainer`. However, the actual required type is `BatchMessageContainerBase`.

https://github.com/apache/pulsar/blob/fccc1cf60467bc0600c6507271cff85146d9f9e8/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L235-L236

`BatchMessageContainerBase` needs to depend `OpSendMsg`, `ProducerImpl`, etc. So it cannot be a part of **pulsar-client-api** package. `BaseMessageContainer` is just a fake interface.

We can also take the similar way for `PayloadConverter` but it's not better than loading class at runtime IMO.

**Comment by eolivelli** [comment]
Another thought about this PIP, thinking out loud:
The selection  of the decidere should be automatic, depending on some metadata in the message, the same way we do with compression (probably compression could be made pluggable one day when  we solve the problem for the payload converter...)

**Comment by eolivelli** [comment]
@BewareMyPower 
I think that we have to think more in general about these extensibility points that we add to Pulsar, especially on the client.

On one hand we need the power to access the internals of Pulsar (and use internal APIs, Netty....)
On the other hand we must provide to the end user something that:
- it is able to deal with backward/forward compatibility
- it does not add additional dependencies on the client (pulsar-common??)

I believe that those things can only be implemented if we create a public API and maintain it, so we have to create public interfaces in pulsar-client-api module that represent the internal components that we want to manage.

For instance we cannot expose Netty here, because in that case clients that use a Shaded version of Netty will not work.
We do not want to access Broker Message Metadata....

so we need something like:

`ByteBuffer convert(MessageContext message, ByteBuffer content)` -> No good, ByteBuffer does not fully represent ByteBuf
 or
`byte[] convert(MessageContext message, byte[] content) `-> very bad, everybody knows...
 or
`Payload convert(MessageContext message, Payload payload)`
     
 with
 ```
interface MessageContext {
              ... getMetadata(....)   
      }
```
 and a high level wrapper
 ```
  interface Payload {
        int size()
        getInputStream()
        copyTo(....)
        static Payload wrap(byte[])
        static Payload wrap(ByteBuffer....)
        ...add whatever is needed...
      }
```

**Comment by eolivelli** [comment]
second topic:
the client must be able to auto detect the "format" of the payload and then apply it automatically to the messages tagged with that format, the only constraint is that in the classpath you have the proper "MessageConverter"

**Comment by BewareMyPower** [comment]
> `Payload convert(MessageContext message, Payload payload)`
> 
> with
> 
> ```
> interface MessageContext {
>              ... getMetadata(....)   
>      }
> ```
> 
> and a high level wrapper
> 
> ```
>  interface Payload {
>        int size()
>        getInputStream()
>        copyTo(....)
>        static Payload wrap(byte[])
>        static Payload wrap(ByteBuffer....)
>        ...add whatever is needed...
>      }
> ```

Good suggestion. I'll think about some proper interfaces for it.

> second topic:
> the client must be able to auto detect the "format" of the payload and then apply it automatically to the messages tagged with that format, the only constraint is that in the classpath you have the proper "MessageConverter"

If I didn't understand wrong, I think it's a part of converter's implementation. In the previous PIP, I used two methods, one of them is for detecting the format. In this PIP, I merged them into one because the format detection is usually simple. See https://github.com/apache/pulsar/pull/12088/files#diff-f1e742e597b262e9da738239c878d0a0f3429f4484bc9461cb6a6f838c6a138a as an example.

**Comment by eolivelli** [comment]
> if I didn't understand wrong, I think it's a part of converter's implementation. 
Sorry, I didn't check the implementation (this is expected, because if I take a look to the implementation we could miss some details here in the document).
So the example implementation simply skips messages that are not handled by the Converter.

I see only one problem with this approach: if the Consumer does not load the Converter the application will receive some corrupted data, because it fails to decode it.

If we explicitly add a metadata field "messageFormat" to the metadata, then the PulsarClient can:
1) lookup the Converter, given the format
2a) fail: report an error to the user and prevent the application to process garbage
2b) process the conversion

We can do this in two ways:
- have a dictionary inside the Pulsar Client that maps the MessageConverted to a format
- add a "acceptFormat(String format)" to the MessageConverted interface (and let the Pulsar Client fail the read if no MessageConverted accepted the format)

**Comment by BewareMyPower** [comment]
I think our goal is to configure multiple converters and choose the proper one for the message. Since I missed the case in this PIP, I merged them into one. You're right that the `accept` method should be separated.

> If we explicitly add a metadata field "messageFormat" to the metadata

But existing messages don't have this field, for example, KoP adds the property `entry.format=kafka` to mark messages as Kafka format. I think the detail steps should be:

1. Check the `format` field of metadata
2. If it's set, lookup the converter according to the `format` field
    1. fail: report an error to the user and prevent the application to process garbage
    2. process the conversion
3. Otherwise, iterate over all converters to find the first converter that accepts the message.
    1. If no converter was found, fallback to the default converter that returns the payload simply.
    2. Process the conversion.

**Comment by BewareMyPower** [comment]
@eolivelli I've just made a lot of changes for this proposal. PTAL

Some differences from the previous thoughts:
1. Only configure one converter to avoid extra complexity.
2. The `messageFormat` field was not added to MessageMetadata, though it doesn't take much effort to do that. Checking the property could be compatible with messages produced by older Pulsar API.

Here's the branch for the latest proposal but still needs some work: https://github.com/BewareMyPower/pulsar/tree/TEST-PIP-96

@codelipenghui Please also take a look since I've changed the returned value to `Iterable<Message<T>>`.

**Comment by eolivelli** [comment]
I really love this new proposal.
But I don't understand how newSingleMessage works.
it is for creating batched messages ?

can you sketch an example in pseudo code ?

apart from that I think we are on our way

**Comment by BewareMyPower** [comment]
@eolivelli 

See this commit: https://github.com/BewareMyPower/pulsar/commit/e51486357e42af73a70a5ea697e64c67914f9922

- DefaultPayloadConverter is an implementation for the default case. It uses `newSingleMessage` to create each single message of a batch.
- The actual implementation is in `ConsumerImpl#newSingleMessage`, which is simply called in `MessageContextImpl#newSingleMessage`.
- See the removed code in `ConsumerImpl#messageReceived` for comparison.

**Comment by eolivelli** [comment]
from your example it looks like newSingleMessage is useful to extract a Message from a batch.
how can you apply this to KOP ?

do we need to refactor  ConsumerImpl ?
I though that this would be a simpler change, but in fact you have to deal with the fact that the Converter may decide to split the single message into multiple messages.

I am not sure if we should have a `DefaultConverter`.
if you really need it please make it more evident in the PIP description.

I am not sure about the overhead we are introducing with the DefaultConverter.
isn't it possible to do like:

if (I have a converter) .... run the new code
else .... run the optimized existing code without the the Converter ?

we will avoid many allocations and using many CPU cycles

cc @merlimat

**Comment by BewareMyPower** [comment]
@eolivelli 

> how can you apply this to KOP ?
Each entry produced by KoP is a buffer that can be converted to a `MemoryRecords`.

```java
    public static MemoryRecords readableRecords(ByteBuffer buffer) {
        return new MemoryRecords(buffer);
    }
```

Then we can reuse the method of `MemoryRecords` to create iterable records

```java
    public Iterable<Record> records() {
        return records;
    }
```

Each `Record` is a single message, i.e. `MessageImpl<T>`.

> I though that this would be a simpler change, but in fact you have to deal with the fact that the Converter may decide to split the single message into multiple messages.

No, the converter did the same as the code before. The buffer is an entry but not a single message.

The default converter's behavior is:
1. If the entry is a single message, use `newMessage` to create a `Iterable<Message<T>>` that can only iterate once because it only contains one message.
2. If the entry is a batched message, create a `Iterable<Message<T>>`, during each iteration, use `newSingleMessage` to create single messages.

The difference is, the previous implementation uses a for loop, the current implementation creates a iterator. The overhead is the allocation of the iterator.

**Comment by BewareMyPower** [comment]
> if (I have a converter) .... run the new code
> else .... run the optimized existing code without the the Converter ?

I think yes. Maybe the code will look ugly. I'll try this way soon.

**Comment by BewareMyPower** [comment]
In addition, actually it only affect the client side that usually consumes not many topics, the overhead of iterator allocations might not be significant IMO. But it still need tests to prove that. I think we can skip the converter for the default case as you've said. @eolivelli Though there will still be some refactors to `ConsumerImpl`.

**Comment by BewareMyPower** [comment]
I have simplified this design and update the description, PTAL again. @eolivelli 

Some changes:
1. Rename `MessageContext` to `EntryContext` to avoid misunderstanding. Because `MessageContext` looks like a context of `Message<T>`.
2. Simplify the `MessagePayload` interface. It's only responsible to convert itself to `ByteBuf` now.
3. Don't apply a default converter for consumer.

You can also see https://github.com/apache/pulsar/pull/12088 for detail.

**Comment by eolivelli** [comment]
`default void cleanup() {}`
It is not clear to me when this method will be called, when we are closing the `Consumer` ?
Because it has not reference to the `EntryContext`, so it is not related to `convert`

**Comment by eolivelli** [comment]
I am still not sure about this:
```
<T> Message<T> newSingleMessage(int index,
                                    int numMessages,
                                    MessagePayload payload,
                                    boolean containMetadata,
                                    Schema<T> schema);
```

problems:
- we are passing `numMessages` for each message, and so we can pass different values. My understanding is that you should use the same value for each message in the new batch
- it is not clear if we can create a new batch that has a different number of messages then the original batch
- why we have to call "newSingleMessage" on `EntryContext` is the `EntryContext` a wrapper for the original Message (Entry) on Pulsar ? 

if `EntryContext` is a wrapper for an `Entry` maybe we can call it `EntryWrapper`
if it adds more functionalities to a pure wrapper, can we have two objects ?
- `EntryWrapper` -> contains methods to access the original Entry and the Message in the batch
- `ConverterContext` -> contains utility methods to build Messages 

```
interface ConverterContext {
       <T> BatchBuilder<T> newBatch(int numberOfMessages, Schema<T> schema);
       <T> Message<T> newMessage(MessagePayload payload, Schema<T> schema);
  }
```
  
```
interface BatchBuilder<T> {
         Message<T> newMessage(int index, MessagePayload payload....) // not sure if we need to pass index, we can compute it automatically probably
         Iterator<Message<T>> buildMessages();
}
```

**Comment by BewareMyPower** [comment]
@eolivelli Thanks for your feedback! Here're my answers.

> `default void cleanup() {}`
> It is not clear to me when this method will be called, when we are closing the `Consumer` ?
> Because it has not reference to the `EntryContext`, so it is not related to `convert`

Since `PayloadConverter#convert` returns a iterable messages, it's called in this way in `ConsumerImpl`:

```java
for (Message<T> msg : converter.convert(entryContext, payload, schema)) {
    // Do something with msg
}
converter.cleanup();
```

For example, if we want to collect the total bytes of each conversion and expose it to outside, we might implement the converter as

```java
    private long totalBytes = 0;

    @Override
    public <T> Iterable<Message<T>> convert(EntryContext context, MessagePayload payload, Schema<T> schema) {
        /* ... */
        return () -> new Iterator<Message<T>>() {
            /* ... */

            @Override
            public Message<T> next() {
                final Message<T> msg = isBatch
                        ? context.newSingleMessage(index, numMessages, payload, true, schema)
                        : context.newMessage(payload, schema);
                totalBytes += msg.getData().length;
                return msg;
            }
        };
    }

    @Override
    public void cleanup() {
        recordStatistics(totalBytes);  // pseudo code
    }
```

I'm not sure whether there's a better name.

Regarding to `newSingleMessage` API design, you're right that `numMessages` parameter should be removed.

> if EntryContext is a wrapper for an Entry maybe we can call it EntryWrapper
No, it's only a wrapper for Entry's metadata, not including the payload. So I think the name `Context` is better.

And the key point of the latest design is to **avoid building the batch**. Because if we built a batch using the converter, in `ConsumerImpl` needs to deserialize the batch into multiple single messages. It's unnecessary.

1. If the entry is a batch, call `newSingleMessage` in each iteration.
2. Otherwise, call `newMessage` to convert the entry payload to a message.

**Comment by eolivelli** [comment]
Regarding `default void cleanup() {}`

The word 'cleanup' reads like something that is to be performed to "clean" after some operation or in the end.
But if I understand correctly it is unrelated to any "convert" operation.

I believe that we should pick a better name:
1) afterConvert(EntryContext....) : if we want to call it after every "convert"
2) close(): if we want to call it when shutting down the Consumer
3) update(): if we want to call it sometimes, without any constraint

I like 1) and 2) (we can do both), because from a developer perspective it is clear "when" the method is called.
Option 3) does not guarantee that the method will be ever called, so it would be good only to update some metrics as in your example

**Comment by eolivelli** [comment]
So can we name `newSingleMessage` to `getMessageAt` and `newMessage` to `asSingleMessage`

```
EntryContext {
     int numMessages();
     Message getMessageAt(index.....)
     Message asSingleMessage()
}
```

**Comment by BewareMyPower** [comment]
@eolivelli Regarding to the `numMessages` parameter, I found it's still necessary when I tried to remove it.

The entry context is based on the `MessageMetadata`. However, the actual number of messages might be contained in the payload. For example, if the message was published from KoP, the actual metadata is contained in the payload and the `MessageMetadata` is a false header. In this case, we need to parse the payload, then pass the actual number of messages.

Similarly, these methods are all based on `MessageMetadata`:

```java
public interface EntryContext {

    String getProperty(String key);

    int getNumMessages();

    boolean isBatch();
```

That's also one of the reasons that I renamed the `MessageContext` to `EntryContext`. Because the context of the entry might not be the same context of the message.

**Comment by BewareMyPower** [comment]
The current design of `MessagePayload` might still looks a little weird, especially for the `copiedBuffer()` method. I might make some changes for `MessagePayload` tomorrow.

**Comment by BewareMyPower** [comment]
I added a `MessagePayloadFactory` interface with a `DEFAULT` instance to avoid users using `MessagePayloadImpl` directly. Regarding to the `BatchMessageAcker` issue, I added the `acknowledge` and `acknowledgeCumulative` invocations in tests. It might not affect the proposal itself, and should be discussed in PR review phase.

/cc @codelipenghui @hangc0276 @315157973

**Comment by BewareMyPower** [comment]
Update: `PayloadConverter#whenInterrupted()` method was added according to @eolivelli 's suggestion.

**Comment by eolivelli** [comment]
we should also make it clear to what happens to the we should move everything in this form

`void  convert(EntryContext context, MessagePayload payload, Schema<T> schema, Consumer<Message<T> consumer);`
this way the loop is performed inside the method body:
* the lifecycle is clearer
* no need for additional lifecycle methods
* in the future it can be called by **multiple threads**
* the `convert` method has full control over the loop and can handle errors/refcounts better

**Comment by BewareMyPower** [comment]
Since the code needs a lot of changes, I updated the proposal first. PTAL @eolivelli 

In addition to your suggestion, I added a `Consumer<Throwable>` parameter to handle the exceptional case, in this case, Pulsar consumer will discard the message and send the `CommandAck` with a `ValidationError.BatchDeSerializeError`.

**Comment by eolivelli** [comment]
catching `Throwable` is not good, we should not ask to the PayloadProcessor developer to do this.

Why not change the signature to 
```
public <T> void process(MessagePayload payload,
                                EntryContext context,
                                Schema<T> schema,
                                Consumer<Message<T>> messageConsumer) throws Exception
```

then we deal with catching any Throwable in Pulsar code ?

**Comment by BewareMyPower** [comment]
Makes sense. I updated the proposal again. PTAL @eolivelli

**Comment by codelipenghui** [comment]
The proposal LGTM, thanks @eolivelli @BewareMyPower for the great context and discussion. I only have one point about the name `EntryContext`, because you know the entry is the concept from BookKeeper and currently we don't have any concepts about the entry at the client-side, so maybe BatchContext is more reasonable here? Greate proposal! @BewareMyPower

**Comment by BewareMyPower** [comment]
> so maybe BatchContext is more reasonable here? 

I think not. Because the Entry might just be a single message, not the batch. You can also see related docs in `EntryContext`:

```
    /**
     * Check whether the entry is a batch.
     *
     * @return true if the entry is a batch.
     */
    boolean isBatch();
```

I've used `MessageContext` before, but it might be misunderstood as the context of a `Message<T>`.

Your concern is right. `Entry` is a concept from BookKeeper. For Pulsar client users, it might look a little unfamiliar. I think we can rename it `PayloadContext`? Since it's a context of a payload.

**Comment by BewareMyPower** [comment]
I thought for a while, `PayloadContext` is more clear. My previous concerns can be solved by the document.

- PayloadContext: the context of a message payload
- MessagePayload: the message payload itself
- PayloadProcessor: the processor for a message payload

It looks more consistent.

**Comment by codelipenghui** [comment]
@BewareMyPower LGTM.
