### ISSUE TITLE
Apache Pulsar delayed messages are not redelivered when consumers were offline during that time

### ISSUE THREAD

**Issue by vvijayv** [apache/pulsar#12091]
**Describe the bug**
When consumers loose the messages that were supposed to be delayed messages when they are offline during the time frame scheduled messages have to be consumed. The broker does not attempt to redeliver the messages when consumers are back online.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a persistent topic with some partitions
2. Create a producer that produce messages after a short delay or at specific time. I used `deliverAfter` with 15 seconds delay.
3. Let the 15 seconds (or the scheduled time pass)
4. Bring up the consumers who consume messages from the topic. The consumers wont receive the messages.

**Expected behavior**
When the consumers are back online, the broker should attempt to push messages that are not delivered to them while they were offline

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MACOS

**Additional context**
Used Java
Used shared mode in consumers
Used Latest to consume from

**Comment by shibd** [comment]
@vvijayv Can you show your consumer configuration？Maybe you should use `SubscriptionInitialPosition.Earliest` when create consumer.

Example:
```java
Consumer<byte[]> subscribe = client.newConsumer()
        .topic(topic)
        .subscriptionName("my-subscribe")
        .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
        .subscribe();
```

**Comment by vvijayv** [comment]
@shibd I will try this. But does it mean every time this consumer starts (restart/deployment/crash recovery) it will start consuming from the most earliest?

**Comment by shibd** [comment]
> @shibd I will try this. But does it mean every time this consumer starts (restart/deployment/crash recovery) it will start consuming from the most earliest?

No, If you use `subscribe api`, `SubscriptionInitialPosition` just take effect when first create subscribe. Pulsar can record(persistent) the position of subscribers.

**Comment by shibd** [comment]
@vvijayv  Hi, Does it solved your problem?

**Comment by vvijayv** [comment]
Yes @shibd I think the subscription position solves this problem. I am closing this issue
