### ISSUE TITLE
Support hostname verification in C++ client

### ISSUE THREAD

**Issue by rdhabalia** [apache/pulsar#1215]
Pulsar java client lib already supports hostname verification with #1208. We should support the same for C++ client library.

**Comment by sijie** [comment]
This is related to #2475

**Comment by srkukarni** [comment]
@sijie @merlimat pl review

**Comment by srkukarni** [comment]
@sijie @merlimat can you guys please review this?

**Comment by ivankelly** [comment]
Fixed by #2475
