### ISSUE TITLE
NPE When create OpReadEntry

### ISSUE THREAD

**Issue by Shoothzj** [apache/pulsar#12159]
**Describe the bug**
NPE When `OpReadEntry.create()`. When the `ledgerId` in `ManagedLedgerImpl.ledgers` is  null.
the call to `OpReadEntry.create()` will trigger `readEntryFailed` callback but this time the cursor of `OpReadEntry` is still unseted.

More seriously, it will make the variable `havePendingRead` can't become true again.

**To Reproduce**
It's quitely hard to reporduce the problem. In our environment, we shutdown all bookkeepers meanwhile, has the probability to reporduce it.

**Screenshots**
![image](https://user-images.githubusercontent.com/12933197/134504093-fbd6b444-ef56-4917-b393-2b7391234507.png)

**Comment by Shoothzj** [comment]
@codelipenghui @merlimat @wolfstudy @eolivelli @sijie @BewareMyPower @lhotari 

IMHO, it probably need a sync callback failure instead of async callback failure.
Any better idea to fix this problem ? Thanks for your help.

**Comment by lhotari** [comment]
@Shoothzj is this related to #11796 / #11282 ? There's PR #11813 to fix that issue.

**Comment by Shoothzj** [comment]
> @Shoothzj is this related to #11796 / #11282 ? There's PR #11813 to fix that issue.

Thanks, that's same as #11282/#11796. I should search more carefulness before I submit the issue. Thank you very much.
