### ISSUE TITLE
pulsar offload into hdfs, offload-status is success, but hdfs has no file and topics stats-internal return "offloaded" : false

### ISSUE THREAD

**Issue by chlyzzo** [apache/pulsar#12156]
# What issue do you find in Pulsar docs?

     https://pulsar.apache.org/docs/en/tiered-storage-filesystem/#hadoop-profile-path-required

     when i set the broker.conf
     -----------
   managedLedgerOffloadDriver=filesystem
   fileSystemURI=hdfs://hadoop-cluster:54310
   fileSystemProfilePath=../conf/filesystem_offload_core_site.xml
   
   managedLedgerMinLedgerRolloverTimeMinutes=2
   managedLedgerMaxEntriesPerLedger=5000
     ------------
   
     and filesystem_offload_core_site.xml
--------------

<configuration>
    
    <property>
        <name>fs.defaultFS</name>
        <value>hdfs://hadoop-cluster:54310</value>
    </property>
    <property>
        <name>hadoop.tmp.dir</name>
        <value>/app/dt/data/pulsar_data</value>
    </property>
    <property>
        <name>hadoop.job.ugi</name>
        <value>user,useruser</value>
        <description>username, password used by client</description>
    </property>
    <property>
        <name>io.file.buffer.size</name>
        <value>4096</value>
    </property>
    <property>
        <name>io.seqfile.compress.blocksize</name>
        <value>1000000</value>
    </property>
    <property>
        <name>io.seqfile.compression.type</name>
        <value>BLOCK</value>
    </property>
    <property>
        <name>io.map.index.interval</name>
        <value>128</value>
    </property>

</configuration>
------------
and use the command:
pulsar-admin topics offload --size-threshold 10M persistent://my-tenant/my-namespace/topic1
pulsar-admin topics offload-status -w persistent://my-tenant/my-namespace/topic1

return Offload was a success,

but the hdfs has no files, and ./bin/pulsar-admin topics stats-internal persistent://my-tenant/my-namespace/topic1
------
{
  "entriesAddedCounter" : 4481,
  "numberOfEntries" : 4481,
  "totalSize" : 176732369,
  "currentLedgerEntries" : 4481,
  "currentLedgerSize" : 176732369,
  "lastLedgerCreatedTimestamp" : "2021-09-23T15:58:10.818+08:00",
  "waitingCursorsCount" : 0,
  "pendingAddEntriesCount" : 0,
  "lastConfirmedEntry" : "68:4480",
  "state" : "LedgerOpened",
  "ledgers" : [ {
    "ledgerId" : 68,
    "entries" : 0,
    "size" : 0,
    "offloaded" : false,
    "underReplicated" : false
  } ],
  "cursors" : { },
  "schemaLedgers" : [ {
    "ledgerId" : 69,
    "entries" : 1,
    "size" : 758,
    "offloaded" : false,
    "underReplicated" : false
  } ],
  "compactedLedger" : {
    "ledgerId" : -1,
    "entries" : -1,
    "size" : -1,
    "offloaded" : false,
    "underReplicated" : false
  }
}
------

the hadoop cluster already install ( company install, not on install pulsar machine)。 

# What is your suggestion?
      when i has a hadoop cluster, so how config, the pulsar offload data into hdfs,

# Do you have any references?

# Would you like to fix this issue?

**Comment by hangc0276** [comment]
It has only one ledger `ledgerId=68` and in `open` state, and only the `closed` state ledger can be offload to tiered storage. You can produce more message to the topic and wait for up to `managedLedgerMinLedgerRolloverTimeMinutes` to ensure the current ledger rollover. @chlyzzo
