### ISSUE TITLE
pulsar C++ client

### ISSUE THREAD

**Issue by LunckyB** [apache/pulsar#12154]
**Describe the bug**
file could not be found. in ./googlemock/libgmock.a 
**To Reproduce**
$ sudo apt-get install cmake libssl-dev libcurl4-openssl-dev liblog4cxx-dev \
  libprotobuf-dev protobuf-compiler libboost-all-dev google-mock libgtest-dev libjsoncpp-dev
$ cd /usr/src/googletest
$ sudo cmake .
$ sudo make
$ sudo cp ./googlemock/libgmock.a ./googlemock/gtest/libgtest.a /usr/lib/

**Desktop (please complete the following information):**
 - OS: ubuntu20.04

**Comment by BewareMyPower** [comment]
I think the document might be a little old. I'll take a look at it soon.

**Comment by BewareMyPower** [comment]
In Ubuntu 20.04, the libraries are generated under `./lib` subdirectory, not `./googlemock`. So you should run

```bash
sudo cp ./lib/libgmock.a ./lib/gtest/libgtest.a /usr/lib/
```

BTW, GMock is not required now.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant in maintained versions.

BTW, the development of the C++ client is permanently moved to https://github.com/apache/pulsar-client-cpp.
