### ISSUE TITLE
Helm installation fails

### ISSUE THREAD

**Issue by vvijayv** [apache/pulsar#12177]
**Describe the bug**
The Pulsar Helm installation to EKS fails with the below message.
`Error: INSTALLATION FAILED: failed to create resource: ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found t, error found in #10 byte of ...|bleData":true,"broke|..., bigger context ...|tMemorySize=256m\n","autoSkipNonRecoverableData":true,"brokerServicePort":"6650","clusterName":"puls|...`

command `helm install pulsar apache/pulsar --namespace <my-ns> --set initialize=true --set volumes.persistence=false --set affinity.anti_affinity=false --set components.autorecovery=false --set zookeeper.replicaCount=1 --set bookkeeper.replicaCount=1 --set broker.replicaCount=1 --set broker.configData.autoSkipNonRecoverableData="true" --set broker.configData.managedLedgerDefaultEnsembleSize="1" --set broker.configData.managedLedgerDefaultWriteQuorum="1" --set broker.configData.managedLedgerDefaultAckQuorum="1" --set proxy.replicaCount=1`

**To Reproduce**
1. Create a EKS cluster
2. Run the helm installation with `values-one-node.yaml` as values file from the `examples` directory of helm chart repo

**Expected behavior**
Should install pulsar components with only one instance

**Screenshots**
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/72122946/134720354-213234e6-9e02-4b85-9c20-174f9c703669.png">

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Helm Chart has been permanently moved to https://github.com/apache/pulsar-helm-chart. If it's still relevant, please open an issue there.
