### ISSUE TITLE
ratePeriodInSecond in DispatchRate should be non-positive

### ISSUE THREAD

**Issue by glcrazier** [apache/pulsar#12185]
**Is your enhancement request related to a problem? Please describe.**
If set ratePeriodInSecond of DispatchRate as 0 when setting namespace policy, the admin api indicates success. However, successive operations like creating subscriptions under this namespace would fail and the caller doesn't know why due to improper settings. 

**Describe the solution you'd like**
When calling admin api, check ratePeriodInSecond value if it's non-positive, failed the calling to let the caller try correct values.

**Comment by hellomyboy** [comment]
> **Is your enhancement request related to a problem? Please describe.**
> If set ratePeriodInSecond of DispatchRate as 0 when setting namespace policy, the admin api indicates success. However, successive operations like creating subscriptions under this namespace would fail and the caller doesn't know why due to improper settings.
> 
> **Describe the solution you'd like**
> When calling admin api, check ratePeriodInSecond value if it's non-positive, failed the calling to let the caller try correct values.

How do you use it, can you tell me the steps?

**Comment by glcrazier** [comment]
> > **Is your enhancement request related to a problem? Please describe.**
> > If set ratePeriodInSecond of DispatchRate as 0 when setting namespace policy, the admin api indicates success. However, successive operations like creating subscriptions under this namespace would fail and the caller doesn't know why due to improper settings.
> > **Describe the solution you'd like**
> > When calling admin api, check ratePeriodInSecond value if it's non-positive, failed the calling to let the caller try correct values.
> 
> How do you use it, can you tell me the steps?

I called like the following:           
```
            adminClient.namespaces().setDispatchRate("namespace",
                    new DispatchRate(configuration.getDispatchThrottlingRateInMsg(),
                            configuration.getDispatchThrottlingRateInByte(),
                            0));

```
I accidentally created DispatchRate object with third parameters as 0. Then subsequent operations like creating subscription would fail.

**Comment by tisonkun** [comment]
@glcrazier I guess you'd like to mention "non-negative" here? That is, `ratePeriodInSecond` should be always `> 0`?

**Comment by tisonkun** [comment]
I try out:

```
./bin/pulsar-admin namespaces set-subscription-dispatch-rate public/default --dispatch-rate-period 0
./bin/pulsar-client consume -s mysub -p Earliest persistent://public/default/topic 
```

And it seems can proceed properly. Maybe it's fixed on master branch. Please open a new issue with repro if it's still relevant.
