### ISSUE TITLE
How to get the messageID

### ISSUE THREAD

**Issue by azui007** [apache/pulsar#12189]
Please answer the following questions before submitting your doc issue. Thanks!

# What issue do you find in Pulsar docs?

I want to know how to get the messageID
The docs does not describe this
can you help me?
thanks

# What is your suggestion?

add the describe and demo

# Do you have any references?

no

# Would you like to fix this issue?

(Welcome to contribute docs! Pulsar grows from a tiny seed to a big tree with every little effort by us! Your contribution is the sunlight, water, and air!)

**Comment by Shoothzj** [comment]
What timing or phase do you want to get the messageID, consumer?

**Comment by BewareMyPower** [comment]
```java
        try (PulsarClient client = PulsarClient.builder().serviceUrl("pulsar://localhost:6650").build()) {
            final String topic = "topic";
            final Consumer<byte[]> consumer = client.newConsumer()
                    .topic(topic)
                    .subscriptionName("sub")
                    .subscribe();
            final Producer<byte[]> producer = client.newProducer()
                    .topic(topic)
                    .create();
            final CountDownLatch latch = new CountDownLatch(1);
            producer.sendAsync("hello".getBytes(StandardCharsets.UTF_8)).whenComplete((id, e) -> {
                if (e == null) {
                    System.out.println("Send to " + id + ", type: " + id.getClass().getTypeName());
                }
                latch.countDown();
            });
            final Message<byte[]> message = consumer.receive();
            final MessageId id = message.getMessageId();
            System.out.println("Received from " + id + ", type: " + id.getClass());
            latch.await(); // wait until send callback is triggered
        } catch (PulsarClientException | InterruptedException e) {
            e.printStackTrace();
        }
```

**Comment by liangyuanpeng** [comment]
You can get the messageId when you send message success or received message.

**Comment by azui007** [comment]
> What timing or phase do you want to get the messageID, consumer?

i want use this api: `reset-cursor`
the options need messageId

**Comment by azui007** [comment]
> You can get the messageId when you send message success or received message.

How can i get the messageid on i received message.
Can you tell me which API I should use

**Comment by liangyuanpeng** [comment]
> ```java
>         try (PulsarClient client = PulsarClient.builder().serviceUrl("pulsar://localhost:6650").build()) {
>             final String topic = "topic";
>             final Consumer<byte[]> consumer = client.newConsumer()
>                     .topic(topic)
>                     .subscriptionName("sub")
>                     .subscribe();
>             final Producer<byte[]> producer = client.newProducer()
>                     .topic(topic)
>                     .create();
>             final CountDownLatch latch = new CountDownLatch(1);
>             producer.sendAsync("hello".getBytes(StandardCharsets.UTF_8)).whenComplete((id, e) -> {
>                 if (e == null) {
>                     System.out.println("Send to " + id + ", type: " + id.getClass().getTypeName());
>                 }
>                 latch.countDown();
>             });
>             final Message<byte[]> message = consumer.receive();
>             final MessageId id = message.getMessageId();
>             System.out.println("Received from " + id + ", type: " + id.getClass());
>             latch.await(); // wait until send callback is triggered
>         } catch (PulsarClientException | InterruptedException e) {
>             e.printStackTrace();
>         }
> ```

@azui007  see consumer.receive();
