### ISSUE TITLE
User can only excute bin/pulsar in $PULSAR_HOME

### ISSUE THREAD

**Issue by asagjj** [apache/pulsar#12199]
Similiar as  [ISSUE-5650.](https://github.com/apache/pulsar/issues/5650)
#### Expected behavior
when use bin/pulsar shell, like generate public key or token, we should can excute it in any dirs and specify a relative path. 

#### Actual behavior

If current dir is not  $PULSAR_HOME,  the relative path specified for bin/pulsar,will not  work, throw exception like "file doesn't exist"

#### Steps to reproduce
1、cd $PULSAR_HOME/bin;
2、./pulsar tokens create --secret-key ../token_key/my-secret.key --subject pulsar

How can we reproduce the issue

#### System configuration
**Pulsar version**: 2.8.2
Maybe we should remove  [change the working directory?]( https://github.com/apache/pulsar/blob/master/bin/pulsar#L314)

**Comment by tisonkun** [comment]
Closed as won't do. I believe this is by design. Always pass absolute path for arguments is more stable.
