### ISSUE TITLE
Document when Pulsar configuration settings or changes were introduced

### ISSUE THREAD

**Issue by kellyfj** [apache/pulsar#12201]
Please answer the following questions before submitting your doc issue. Thanks!

# What issue do you find in Pulsar docs?

It's hard to tell when Configuration parameters were introduced
https://pulsar.apache.org/docs/en/reference-configuration/
We are currently using 2.7.2 and there are new parameters in 2.8.0 that we might 

# What is your suggestion?

Please add a column the tables indicating which version the parameter was introduced 
https://pulsar.apache.org/docs/en/reference-configuration/

# Do you have any references?

https://pulsar.apache.org/docs/en/reference-configuration/

# Would you like to fix this issue?

If someone could suggest a reasonable process to track down historical code changes (is there a way to find the earliest commit that references a variable and then find which git tag that was released in)? Or perhaps diff the documentation?

**Comment by momo-jun** [comment]
Closed the issue since it hasn't been planned yet at this moment. Feel free to reopen it when it's relevant.
