### ISSUE TITLE
[Website] generate CLI docs for minor releases 

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#12211]
## Issue

Currently, automatic CLI docs (`pulsar-client`, `pulsar-perf`, and `pulsar`) are [only available for major releases](https://pulsar.apache.org/tools/).

For example,

- If click `Pulsar Perf` on `next` version, it goes to the https://pulsar.apache.org/tools/pulsar-perf/2.9.0-SNAPSHOT/ (this page is generated **automatically**), which is the correct behavior.

![image](https://user-images.githubusercontent.com/50226895/134897490-44db9f06-1814-40e4-9f2b-d421c42f44ec.png)

- But if click `Pulsar Perf` on `2.8.1` version, it goes to the https://pulsar.apache.org/docs/en/reference-cli-tools/#pulsar-perf (this page is maintained **manually**), which is not the expected behavior. We expect minor releases have their corresponding "automatically generated pages".

![image](https://user-images.githubusercontent.com/50226895/134897338-6cac9a87-a737-47ef-a1db-83e57c62ec2a.png)

## Potential solution

I've discussed this issue with @tuteng and @urfreespace, we have the following solutions:

### Solution 1: build CLI docs for minor releases automatically based on `tag`

Currently, CLI tool docs (websites) are automatically generated based on the branch (`master`). Building these websites consumes resources. To generate CLI docs for minor releases, we can change it to based on `tag`. We have many minor releases so we have many `tags`, which means **consuming much more resources and taking too long to build websites**. So this makes us think it is not a good solution.

### Solution 2: build CLI docs for minor releases manually

Another way is to create content for minor releases manually under the [`asf-site` branch](https://github.com/apache/pulsar/tree/asf-site/content/tools).

For example,

We can create different folders for each minor release and then copy contents there, so that the CLI tool websites can be generated as well. But it takes some time to investigate how to implement it. **Can anyone help with this? Or anyone has a better solution?** Many thanks!

![image](https://user-images.githubusercontent.com/50226895/134899546-d19975c5-64aa-4117-8601-a5c2686225bd.png)

**Comment by tisonkun** [comment]
Closed as fixed.

IIUC https://pulsar.apache.org/reference hosts all CLI docs for minor releases.
