### ISSUE TITLE
java annotations for "SchemaDefinition to generate struct schema" and method builder() won't make it compile

### ISSUE THREAD

**Issue by saveriogzz** [apache/pulsar#12226]
Please answer the following questions before submitting your doc issue. Thanks!

# What issue do you find in Pulsar docs?

On the page [https://pulsar.apache.org/docs/en/schema-understand/#complex-type](), under **struct/SchemaDefinition**, there is some java code explaining how to create a schema for a `User`. The code has three annotations (`@Builder, @AllArgsConstructor, @NoArgsConstructor`) but it's not written the library from which these annotations are imported.  

Also, at the same page but one code block below, the class `User` will call a method named `builder()` that is not letting the code compile! Is there anything that the final user should now before trying to reproduce this example?

# What is your suggestion?

I would suggest to explicit that, with possible a short explanation on their usage or a link to that.

# Do you have any references?

 [https://pulsar.apache.org/docs/en/schema-understand/#complex-type]()

# Would you like to fix this issue?
I am not a Java expert and I assumed the annotation were imported by [Project Lombok](https://projectlombok.org/). If that is the case, sure I can fix it!

**Comment by momo-jun** [comment]
@congbobo184 @liangyepianzhou @RobertIndie can anyone pls take a look at this issue and advise?

**Comment by liangyepianzhou** [comment]
@saveriogzz Thanks for you point that out.
https://github.com/apache/pulsar/pull/18434 has given some new examples without the annotations.
