### ISSUE TITLE
Partitions rebalance listener for Consumer

### ISSUE THREAD

**Issue by sollecitom** [apache/pulsar#12224]
When using processors with in-memory state, it's important to know the partitions assigned and de-assigned. This allows to load and unload the state, and to recover based from a durable eventually consistent snapshot by loading it based on these partitions.

At the moment, you can try to derive this information from the Message IDs, but there are 2 problems with this approach.

1. You don't know when a partition is de-assigned for a Consumer. This forces you to use a time-based cache eviction policy.
2. When you recover from a crash, you don't know the whole set of partitions assigned, meaning you're forced to load from durable storage the state for each partition when you encounter it in a MessageID. This means a less efficient startup.

Ideally, you should expose something like the [ConsumerRebalanceListener](https://kafka.apache.org/30/javadoc/org/apache/kafka/clients/consumer/ConsumerRebalanceListener.html) in Kafka.

**Comment by BewareMyPower** [comment]
I think there's no rebalance concept in Pulsar. Pulsar consumer doesn't maintain a partition assignment internally like what Kafka consumer does. Pulsar's consumption model is push, while Kafka's is pull. In Pulsar, the dispatcher at broker side determines which partition should the message be sent.

**Comment by Jason918** [comment]
Maybe you can check the docs in `org.apache.pulsar.client.api.ConsumerEventListener`. 
Once the broker choose a consumer for receiving messages in failover mode, it will send an event to client. You can add a listener to this event through ConsumerEventListener.

**Comment by Jason918** [comment]
@sollecitom Close this for now, feel free to reopen this if you have further questions.

**Comment by tsturzl** [comment]
@Jason918 I believe the author of this ticket was talking about Pulsar through their understanding of Kafka. I've been looking for something similar to this in Pulsar and have not been able to find it, nor find a work around. Pulsar key shared subscriptions work similarly to Kafka, where as Kafka balances assignment of partitions to consumers Pulsar key shared subscriptions just divide the hash key space among all consumers which are consuming the same key shared subscriptions. The key difference here is that Pulsar is not assigning partitions to consumers, but rather assigning them a key space for which they'll received the messages for. In this context "rebalancing" might be the wrong word, but ultimately what it being talked about is letting consumers know when their hash ranges have changed.

This is common in distributed data processing work flows where the data you see come in informs you to consume other topics and combine the latest from each source. So I might have a key share subscription to feed out work to a pool of consumers, and based on the data they see they might consumer other subscriptions to retrieve dependent data. If another consumer joins it will subdivide the key space on another consumers therefore the other consumer needs to know to stop consuming these other topics, as they are no longer needed and the key shared subscription will no longer send them. In Kafka you handle this issue by notifying the consumer that a rebalance occurred. That means that the client can evaluate what it should stop consuming.

`ConsumerEventListener` might be a good place to expand into for providing this feature, but as it stand the functionality of this event listener does not provide similar functionality to the mentioned `ConsumerRebalanceListener` in Kafka. Pulsar may not do partition reassignment, but Pulsar doesn't provide similar functionality to handle changes in a key shared consumer's keyspace, making it difficult to effectively implement combined latest processing strategies, and even simple things like invalidating local caches which might cache based on previously seen data from that key shared subscriptions.

**Comment by sollecitom** [comment]
You can create a consumer listener and register it on your consumer. Pulsar indeed has a subscription type that behaves exactly like Kafka does when it comes to partitions and partition assignment changes.

The `ConsumerListener`

```
class PublishingConsumerEventListener : ConsumerEventListener {

    private val changes = MutableSharedFlow<PartitionAssignmentChange>()
    val partitionAssignmentChanges: Flow<PartitionAssignmentChange> get() = changes

    override fun becameActive(consumer: Consumer<*>, partitionId: Int) = runBlocking {
        changes.emit(PartitionWasAssigned(partitionId, consumer.topic, consumer.consumerName))
    }

    override fun becameInactive(consumer: Consumer<*>, partitionId: Int) = runBlocking {
        changes.emit(PartitionWasUnassigned(partitionId, consumer.topic, consumer.consumerName))
    }
}
```

And you can register it with `consumerBuilder.consumerEventListener(consumerEventListener).subscribe()`.

I hope it helps.
