### ISSUE TITLE
Bookie OOM

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#12231]
**Describe the bug**
Pulsar v2.8.1
cluster: 3 zks、5 brokers、5 bookies
topics: 14
topic partitions: 40

![image](https://user-images.githubusercontent.com/54351417/135189450-af79ed1b-ce75-47b1-91be-e5b4551f1c26.png)

**To Reproduce**
1. Start bookies and brokers with direct memory 80GB
2. Start producers

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tisonkun** [comment]
Closing as stale. If it's still relevant to maintained versions, feel free to open a new issue
