### ISSUE TITLE
Admin API V2: swagger.json misses full declaration of /definitions/OutputStream

### ISSUE THREAD

**Issue by edgebroker** [apache/pulsar#12253]
Please answer the following questions before submitting your doc issue. Thanks!

# What issue do you find in Pulsar docs?

The declaration of `/definitions/OutputStream` is just a generic JSON object:

`"OutputStream" : {
      "type" : "object"
    }`

# What is your suggestion?

Exactly define the schema of the JSON object.

# Do you have any references?

Most of the definitions (if not all) have the schema correctly defined, this one is missed.

# Would you like to fix this issue?

No.

**Comment by momo-jun** [comment]
@edgebroker sorry for the late response. Can you pls help address this issue by providing the link to the docs?
