### ISSUE TITLE
High Memory consumption by cluster

### ISSUE THREAD

**Issue by arihantdaga** [apache/pulsar#12275]
#### Actual behavior

I just started with pulsar, i setup the cluster on a single node, keeping just 1 instance of bookkeeper, zookeeper and broker, following the instructions in the docs. And i want to scale it later.
I took a 4GB server, thinking it should be enough since my load right now is almost nil.
But i have seen that pulsar is consuming 100% memory, even when there is no load, not even a single topic. Is it normal, does pulsar require that much memory? or it could be some version-specific bug? I am using 2.8.1. with Java 11. 
Also, i noted, the memory consumed is growing over time, initially, it was only 1.2GB. 

#### Steps to reproduce

Following instructions on https://pulsar.apache.org/docs/en/deploy-bare-metal/  deploy on a single node. 

#### System configuration
**Pulsar version** : 2.8.1
Ubuntu 20, Open JDk 11. 
![image](https://user-images.githubusercontent.com/4976460/135909409-39f78dd7-a318-4e40-b468-34a212de4a41.png)

**Comment by Shoothzj** [comment]
Have you already change the java heap memory config?

**Comment by tisonkun** [comment]
Closing as stale. If it's still relevant to maintained versions, feel free to open a new issue
