### ISSUE TITLE
PROBLEM: messages come as encoded

### ISSUE THREAD

**Issue by saveriogzz** [apache/pulsar#12274]
#### Expected behavior
I am trying to send messages to an Apache Pulsar cluster from a [Java application](https://github.com/saveriogzz/weather-collector/tree/data-streaming).

#### Actual behavior

The messages that I see from a consumer used as monitoring, come as **encoded**! Apart from the ones I send as **Strings**.  
e.g. `"\u0000\u0000\u0000\u0004\u0018l@\u0000\u0000\u0000�@�\u000fV�\u0001\u0000\u00006B\u0000\u0000�@\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000�\t���AUU�A\u0002(2021-10-04T14:00:00Z\u0002H88c8dc24-233c-45f5-b366-85382d7d52c6\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0000"`

Also, when running the code, I see this WARNING here:
```
[pulsar-client-io-1-1] WARN org.apache.pulsar.common.util.SecurityUtility - Unable to get security provider for class org.conscrypt.OpenSSLProvider
java.lang.ClassNotFoundException: org.conscrypt.OpenSSLProvider
```
Could this be the reason?

#### Original issue
goeh/weather-collector#11

#### System configuration
Ubuntu 20.04 and RaspberryPi 3A+ with Raspbian 32bit
**Pulsar Client Javaversion**: 2.8.0

**Comment by MarvinCai** [comment]
Hi, from the code snippet you provided, the producer is not sending message in string, it's sending message with an Avro schema, so the consumer will need to use same schema to receive corresponding message: 
https://github.com/saveriogzz/weather-collector/blob/8f0c590916d9c3d6047c40799bb079e1ce016ce9/src/main/java/nl/tudelft/davisstreaming/PulsarDataStore.java#L99-L101

**Comment by eolivelli** [comment]
Are you using the Java client?
In that case you must use Schema.AUTO_CONSUME() to handle correctly the Schema.

**Comment by saveriogzz** [comment]
> Are you using the Java client?

For the producer, yes! For the consumer (as it is just for monitoring purposes), I am using a Python client.

> In that case you must use Schema.AUTO_CONSUME() to handle correctly the Schema.

Do you mean on the consumer's side, correct?

Thanks!

**Comment by eolivelli** [comment]
I am not sure it is available for Python.

@congbobo184 @codelipenghui @sijie do you have suggestions ?

**Comment by congbobo184** [comment]
python don't support Schema.AUTO_CONSUME()
