### ISSUE TITLE
Pulsar vs ...

### ISSUE THREAD

**Issue by alexec** [apache/pulsar#12282]
Hi,

I'm trying to write up an unbiased table of data on different message technologies, would you be willing to help check my assessment of Pulsar? If not, just close the issue.

https://github.com/argoproj-labs/argo-dataflow/issues/321

**Comment by addisonj** [comment]
Hey @alexec 

Happy to give feedback!

Your assessment looks to be pretty close, but a few minor corrections:

For order, Pulsar offers per topic (if using a non-partitioned topic), per partition (if used partitioned topics), or per key ordering (with any number of consumers). 
For transactions, Pulsar supports transactions as of 2.8 release
Pulsar does not directly implement a priority queue, but it can be implemented using multiple topics fairly easily.

Hopefully that helps! We are always interested in supporting other projects integrating with Pulsar, if you have any other questions, please feel free to reach out! The Apache Pulsar Slack is a good place for any other questions

**Comment by addisonj** [comment]
Closing this issue but please open again if any more questions!

**Comment by alexec** [comment]
One other question, reliability is paramount to our users. What kind of durability does Pulsar support?
