### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pulsar-client==2.8.1

### ISSUE THREAD

**Issue by grantmagdanz** [apache/pulsar#12293]
**Describe the bug**
I cannot install `pulsar-client` 2.8.1 on macOS 11.6 with Python 3.8.8.

**To Reproduce**
1. Run `pip install pulsar-client==2.8.1` on macOS 11.6 with python 3.8.8.

**Expected behavior**
`pulsar-client` is installed successfully

**Desktop (please complete the following information):**
 - OS: macOS 11.6
 - Python: 3.8.8

**Additional context**
Looking at PyPI it looks like there are wheels missing that were previously published. For example in `pulsar-client` version 2.7.3 the wheel `pulsar_client-2.7.3-cp38-cp38-macosx_10_15_x86_64.whl` exists but does not for version `2.8.1`. The wheels built for macOS in 2.8.1 are targeting python 3.7.

Is it possible to get the wheel published for Python 3.8 for macOS? Is there any way to ensure those wheels get published for future versions? Without them we can't upgrade consistently. Thank you in advance!

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Python client has been permanently moved to https://github.com/apache/pulsar-client-python. If it's still relevant, please open an issue there.

2.10.1 should work well.
