### ISSUE TITLE
Git repository is huge because of asf-site branch

### ISSUE THREAD

**Issue by Radrik5** [apache/pulsar#12365]
`git clone https://github.com/apache/pulsar` downloads 1.2 GB of data which takes a long time.

`asf-site` branch takes more than 1 GB
All other branches take 92 MB.
I suggest moving `asf-site` branch to separate repository.

Top 10 folders by total size of all file revisions in git history:

Folder | Size | % of Size
-- | -- | --
content/ | 1,482,355,882 | 87.90%
deployment/ | 47,104,568 | 2.79%
site2/ | 43,924,062 | 2.60%
pulsar-broker/ | 35,072,607 | 2.08%
pulsar-client-tools/ | 13,235,219 | 0.78%
site/ | 10,799,749 | 0.64%
pulsar-client/ | 6,297,518 | 0.37%
pulsar-functions/ | 6,205,700 | 0.37%
pulsar-function-go/ | 4,964,813 | 0.29%

Detailed statistics per file and per folder: [file-stats.xlsx](https://github.com/apache/pulsar/files/7345052/file-stats.xlsx)

**Comment by merlimat** [comment]
Fixed as the `asf-site` updates were all collapsed into a single commit. The total download is now 159.99 MiB
