### ISSUE TITLE
[tiered storage] filesystem offloader use hadoop aliyun fileSystemURI broker config not worked 

### ISSUE THREAD

**Issue by haormj** [apache/pulsar#12377]
**Describe the bug**
1. use filesystem offloader hadoop aliyun impl
2. it will storage data to /user/root/pulsar dir, rather than fileSystemURI (oss://bucket/xxx)

**To Reproduce**
1. pulsar 2.7.2
2. pulsar broker config
    - managedLedgerOffloadDriver: filesystem
    - fileSystemURI: oss://bucket/xxx
    - fileSystemProfilePath: /pulsar/conf/filesystem_offload_core_site.xml
3. ./bin/pulsar-admin topics offload --size-threshold 10M topic
4. ./bin/pulsar-admin topics offload-status topic

**Expected behavior**
it will storage to fileSystemURI config dir

**Comment by codelipenghui** [comment]
Here is the documentation for offload data to ali cloud OSS https://pulsar.apache.org/docs/en/tiered-storage-aliyun/
