### ISSUE TITLE
Adjust the judgment logic of topic schema operation permissions

### ISSUE THREAD

**Issue by yuruguo** [apache/pulsar#12419]
**Is your enhancement request related to a problem? Please describe.**
The `role`(not super-user) that has the `lookup` topic permission should also have the operation permission of the topic schema, for example, the `role` could get topic schema through `./bin/pulsar-admin schemas get tenant1/ns1/tp1`.
But I found that we first judge whether the `role` has access to the `tenant` of this topic, as below:
https://github.com/apache/pulsar/blob/a455d06af19a30aae6edf56d0b6570b23973c48d/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/SchemasResource.java#L82-L91
https://github.com/apache/pulsar/blob/a455d06af19a30aae6edf56d0b6570b23973c48d/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java#L87-L94
https://github.com/apache/pulsar/blob/a455d06af19a30aae6edf56d0b6570b23973c48d/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java#L309-L312
`L311`'s effect is to `check the http client role has admin access to the specified tenant`. 
Since the `role` only has the authority to `lookup` this topic, so it cannot be passed. 
I have doubts about the rationality of this judgment( call `L311`), and we should converge the scope of this judgment.

**Describe the solution you'd like**
Remove this judgment, and replace it with a judgment whether the `role` has the `lookup` permission for this topic, as below:
```
    private void validateDestinationAndAdminOperation(boolean authoritative) {
        try {
            // validateAdminAccessForTenant(topicName.getTenant());
            validateTopicOwnership(topicName, authoritative);
            validateTopicOperation(topicName, TopicOperation.LOOKUP);
```

**Comment by yuruguo** [comment]
@merlimat @eolivelli @codelipenghui can you look at this issue?

**Comment by tisonkun** [comment]
@yuruguo Perhaps we should reopen this issue before #16018 merged?

**Comment by yuruguo** [comment]
> @yuruguo Perhaps we should reopen this issue before #16018 merged?

Yep, done.
