### ISSUE TITLE
pulsar ledger delete but disk not clearing

### ISSUE THREAD

**Issue by azeng528** [apache/pulsar#12445]
**Describe the bug**
pulsar 2.4.0
3 node cluster
but one node disk not clearing
![image](https://user-images.githubusercontent.com/19300752/138204826-2260be09-62cd-45ce-9e8e-2b4eb8bbe846.png)

**To Reproduce**
通过：./bin/bookkeeper shell listledgers在三台服务器执行，ledger数量差别不大，都有3600左右的ledger，并且隔10min查询，前后ledger确实有部分不一样

日志里面现实启动了grabage线程，但是30min，磁盘仍然没有释放，请问有没有手动加速清理的方法或者磁盘空间回收的参数是那一部分？

**Comment by azeng528** [comment]
应该不是ledger的问题，感觉就是后台磁盘回收的程序没生效，重启了好几次bookie，现在看bookie在正常进行磁盘回收了
![image](https://user-images.githubusercontent.com/19300752/138206727-a3a84fa0-c299-4949-85a6-fecd5322fe36.png)

**Comment by codelipenghui** [comment]
@azeng528 The issue has been fixed in https://github.com/apache/bookkeeper/pull/2121, please make sure the bookie version is greater than 4.10
