### ISSUE TITLE
what's error of 'Proxy Client is not authorized to Get Partition Metadata'

### ISSUE THREAD

**Issue by Feng-Xg** [apache/pulsar#12459]
it will  occured the error of **Proxy Client is not authorized to Get Partition Metadata** when producer client send message.
who had same problem?

**Comment by wx7614140** [comment]
I got an error log in pulsar 2.9.3: "Proxy Client is not authorized to Get Partition Metadata with role xxxxxx on topic persistent://public/default/xxxxxxxxxxxxxxxxx". should I grant consume permission to this topic ?

**Comment by nodece** [comment]
> I got an error log in pulsar 2.9.3: "Proxy Client is not authorized to Get Partition Metadata with role xxxxxx on topic persistent://public/default/xxxxxxxxxxxxxxxxx". should I grant consume permission to this topic ?

You need to grant consume/produce permission for your role.

**Comment by wx7614140** [comment]
> > I got an error log in pulsar 2.9.3: "Proxy Client is not authorized to Get Partition Metadata with role xxxxxx on topic persistent://public/default/xxxxxxxxxxxxxxxxx". should I grant consume permission to this topic ?
> 
> You need to grant consume/produce permission for your role.

Oh，I forgot the prefix "persistent://public/tenent_name" when subscribing data.THX!

**Comment by codelipenghui** [comment]
Thanks for the help @nodece 
Close the issue for now.
