### ISSUE TITLE
Add support to release Linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [apache/pulsar#12501]
On aarch64, ‘pip install pulsar-client’ gives the following error:

```
ERROR: Could not find a version that satisfies the requirement pulsar-client (from versions: none)
ERROR: No matching distribution found for pulsar-client
```

Please let me know your interest in releasing Linux aarch64 wheels. I can help with this.

**Comment by odidev** [comment]
Team, Please let me know your interest in releasing Linux aarch64 wheels.

**Comment by odidev** [comment]
@sijie, can you please let me know if the community is open to accept this PR on this topic.

**Comment by tisonkun** [comment]
It should be fixed at least for https://pypi.org/project/pulsar-client/#files 3.2.0.
