### ISSUE TITLE
How to use custom ports when installing pulsar?

### ISSUE THREAD

**Issue by Jzow** [apache/pulsar#12529]
I didn't see the custom port start pulsar on the official website. My command is as follows. After startup, the port is monitored, but I can't connect through manager

```
docker run -it -p 6650:6650 -p 8087:8087 --mount source=pulsardata,target=/pulsar/data --mount source=pulsarconf,target=/pulsar/conf apachepulsar/pulsar:2.8.1 bin/pulsar standalone

```

**Comment by Jzow** [comment]
```
$ docker run -it \
  -p 6650:6650 \
  -p 8087:8080 \
  --mount source=pulsardata,target=/pulsar/data \
  --mount source=pulsarconf,target=/pulsar/conf \
  apachepulsar/pulsar:2.8.1 \
  bin/pulsar standalone

```
@nodece  Is that so?

**Comment by nodece** [comment]
@Jzow Yeap.

**Comment by Anonymitaet** [comment]
Hi @Jzow if you want to customize the port, you need to take Docker guides as references. 

Since your issue has been resolved, can we close this issue and uncheck the `doc-required` label?

**Comment by Jzow** [comment]
Thanks,Let me try tomorrow
