### ISSUE TITLE
bookie entry的p999写入时间达到5秒可能是什么原因？

### ISSUE THREAD

**Issue by hepyu** [apache/pulsar#12533]
前提：3台8c16g的pulsar集群

现象&问题：一个节点的entry的写入P999达到5秒，且持续至少30秒。而其他两个节点的写入是正常的，有可能是什么原因呢？

![image](https://user-images.githubusercontent.com/3917749/139403345-40bae858-fef9-4a8e-a662-57f11d47996f.png)

是bookie发生了不同节点间的数据迁移？还是说在这一区间把jounal日志大量向多个ledger中写入？

其他数据：
写入tps：3500~4000
读取tps：1.5w~2w

这个30秒～60秒区间的异常情况：
1130次发送失败中，有912次是网络超时，218次是因为pulsar发送队列满
再细查日志可以看到，912次网络超时在前，218次pulsar-queue满造成超时在后，可以说明是一个前因后果的关系。
![image](https://user-images.githubusercontent.com/3917749/139403434-fd1cb54e-b8ed-44bf-a473-100562eb54c3.png)

这个异常节点在这个异常区间的bookie日志：
![image](https://user-images.githubusercontent.com/3917749/139403491-4205044e-8d76-4dd7-8dc8-aa16daa84363.png)

貌似从journal到写入ledger的这个时间太长了吧？
和这个有关系么？这是在做从journal（预写日志）到持久化日志（ledger）的操作

同一时间的journal写入时间也是5秒
![image](https://user-images.githubusercontent.com/3917749/139403582-a18122de-9317-42ce-93ce-e2b0f81a6674.png)

**Comment by Jason918** [comment]
You can check if there is a long java gc in bookie first.

**Comment by hangc0276** [comment]
Your journal and ledger disks are HDD or SSD? `journalSyncData` is set to `true` or `false`?

**Comment by hepyu** [comment]
@Jason918 
I can't remember clearly. Do I vaguely remember that bookie or broker has GC, 50ms ~ 100ms? But I'm not sure. Now the Prometheus Metris data is gone, and I can't verify it anymore.
But will 50ms ~ 100ms GC cause bookie to write p999 for about 5 seconds?

@hangc0276 
ledger disks: aws ssd(gp3)
journalSyncData in bookkeeper.conf：journalSyncData=true. It must not be changed to false here. If it is changed to false, isn't the financial grade business cool?

**Comment by Jason918** [comment]
> But will 50ms ~ 100ms GC cause bookie to write p999 for about 5 seconds?

No, but a long STW event could. It's better to add "-XX:+PrintGCApplicationStoppedTime" in JVM OPTS, to make sure there is no long STW time. I am not sure if all STW event will appear in your prometheus metrics.

**Comment by hepyu** [comment]
> > But will 50ms ~ 100ms GC cause bookie to write p999 for about 5 seconds?
> 
> No, but a long STW event could. It's better to add "-XX:+PrintGCApplicationStoppedTime" in JVM OPTS, to make sure there is no long STW time. I am not sure if all STW event will appear in your prometheus metrics.

ok. this issue I closed. the problem only occur once.
