### ISSUE TITLE
Python client: Ordering bug when generating schema definition that makes schema incompatible with topic's registered schema

### ISSUE THREAD

**Issue by branhoff** [apache/pulsar#12574]
**Describe the bug**
When generating a schema definition with the same fields as a topic's registered schema, if the the generated schema is in a different order than the registered schema, will be labeled as incompatible. 

**To Reproduce**

1. Go to https://github.com/ta1meng/pulsar-python-avro-schema-examples
2. Read the `README` file at the root directory as well as `README` file in:
     * example02_nested_schema
3. Change the order of the `MySubRecord` instance arguments in the producer to be out of sync with the `MySubRecord` class
4. RRun the `producer` and `consumer` in the pulsar standalone environment

**Expected behavior**
The documented [example](https://pulsar.apache.org/docs/fr/client-libraries-python/#complex-types) should work out of the box. There should be support for common Avro keywords like `doc`.

**Screenshots**
N/A

**Desktop (please complete the following information):**

    OS: MacOS

**Additional context**
 Tested against Pulsar 2.7.2 and Pulsar 2.8.1. Using both Python Pulsar client 2.7.2 and Pulsar 2.8.1 under Python 3.7.
 
Issue originally reported in ticket [#10596](https://github.com/apache/pulsar/issues/10596)

**Comment by codelipenghui** [comment]
@branhoff I think the issue has been fixed by #12232 and it will be released in 2.8.2 maybe in 2 weeks. If you want an earlier release version you can get here https://github.com/streamnative/pulsar/releases/tag/v2.8.1.20

**Comment by branhoff** [comment]
@codelipenghui Is there an updated` python pulsar-client` that is necessary as well? Or will this `2.8.1.20` release you provided have the fixes that will work with the python `pulsar-client==2.8.1`
