### ISSUE TITLE
Python client: No support for doc attribute

### ISSUE THREAD

**Issue by branhoff** [apache/pulsar#12572]
**Describe the bug**
No support for `doc` attribute

**To Reproduce**

1. Go to https://github.com/ta1meng/pulsar-python-avro-schema-examples
2. Read the README file at the root directory as well as README file in:
     * example03_nested_schema_with_doc_namespace
3. Run the `producer` and `consumer` in the pulsar standalone environment

**Expected behavior**
The documented [example](https://pulsar.apache.org/docs/fr/client-libraries-python/#complex-types) should work out of the box. There should be support for common Avro keywords like `doc`.

**Screenshots**
N/A

**Desktop (please complete the following information):**

    OS: MacOS

**Additional context**
 Tested against Pulsar 2.7.2 and Pulsar 2.8.1. Using both Python Pulsar client 2.7.2 and Pulsar 2.8.1 under Python 3.7.
 
Issue originally reported in ticket [#10596](https://github.com/apache/pulsar/issues/10596)

**Comment by tisonkun** [comment]
Closed as stale. The development of the Python client has been permanently moved to https://github.com/apache/pulsar-client-python. If this is still relevant, please open an issue there.
