### ISSUE TITLE
[BUG]KOP failed to get partition offset

### ISSUE THREAD

**Issue by xiaotongwang1** [apache/pulsar#12616]
@hangc0276 @BewareMyPower @codelipenghui 紧急求助

[https://github.com/apache/pulsar/pull/11912](https://github.com/apache/pulsar/pull/11912)

这个PR，在asyncReadEntry的时候做了ledger map匹配校验

```
    public void asyncReadEntry(PositionImpl position, ReadEntryCallback callback, Object ctx) {
        LedgerHandle currentLedger = this.currentLedger;
        if (log.isDebugEnabled()) {
            log.debug("[{}] Reading entry ledger {}: {}", name, position.getLedgerId(), position.getEntryId());
        }
        if (!ledgers.containsKey(position.getLedgerId())) {
            log.error("[{}] Failed to get message with ledger {}:{} the ledgerId does not belong to this topic "
                    + "or has been deleted.", name, position.getLedgerId(), position.getEntryId());
            callback.readEntryFailed(new ManagedLedgerException.NonRecoverableLedgerException("Message not found, "
                + "the ledgerId does not belong to this topic or has been deleted"), ctx);
            return;
        }
```

但是原有的接口：
```
   public PositionImpl getFirstPosition() {
        Long ledgerId = ledgers.firstKey();
        if (ledgerId == null) {
            return null;
        }
        if (ledgerId > lastConfirmedEntry.getLedgerId()) {
            checkState(ledgers.get(ledgerId).getEntries() == 0);
            ledgerId = lastConfirmedEntry.getLedgerId();
        }
        return new PositionImpl(ledgerId, -1);
    }
```

相关日志：

2021-11-03 20:10:04.378 [bookkeeper-ml-scheduler-OrderedScheduler-0-0] INFO  o.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [XXX/XXX/persistent/__consumer_offsets-partition-39] Start checking if current ledger is full
2021-11-03 20:10:04.381 [main-EventThread] INFO  o.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [XXXX/XXX/persistent/__consumer_offsets-partition-39] Creating a new ledger
2021-11-03 20:10:04.381 [main-EventThread] INFO  o.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [XXX/XXX/persistent/__consumer_offsets-partition-39] Creating ledger, metadata: {component=[B@685c61b2, pulsar/managed-ledger=[B@764fe8e9, application=[B@6d075d7a} - metadata ops timeout : 60 seconds
2021-11-03 20:10:04.382 [BookKeeperClientWorker-OrderedExecutor-2-0] INFO  o.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - : [XXX/XXX/persistent/__consumer_offsets-partition-39] Start TrimConsumedLedgers. ledgers=[33] totalSize=65
2021-11-03 20:10:04.382 [BookKeeperClientWorker-OrderedExecutor-2-0] INFO  o.apache.bookkeeper.mledger.impl.ManagedLedgerImpl -: [XXX/XXX/persistent/__consumer_offsets-partition-39] Slowest consumer ledger id: 34
2021-11-03 20:10:04.386 [main-EventThread] INFO  o.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - : [XXX/XXX/persistent/__consumer_offsets-partition-39] Created new ledger 205

2021-11-03 21:11:15.991 [BookKeeperClientWorker-OrderedExecutor-2-0] INFO  o.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [XXXX/XXXX/persistent/__consumer_offsets-partition-39] Checking ledger 33 -- time-clock: 1635945075991 ms -- time-ledger: 1635941404381 ms -- **expired: true** -- over-quota: false -- current-ledger: 205 -- current-retention: 3600000

2021-11-04 10:51:02.032 [pulsar-io-4-8] ERROR i.s.pulsar.handlers.kop.KafkaRequestHandler - [PersistentTopic{topic=persistent://XXXX/XXXX/__consumer_offsets-partition-39}] Failed to get offset for position 33:0
org.apache.bookkeeper.mledger.ManagedLedgerException$NonRecoverableLedgerException: Message not found, the ledgerId does not belong to this topic or has been deleted

2021-11-04 03:08:14.994 [pulsar-io-4-8] WARN  o.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - : getFirstPosition ledgerId 205 and lastConfirmedEntryLedgerId is 33 , entryid 0 

当前出现场景，当一个分区创建了一个新的ledger，但是没有新消息发送，当前lastConfirmedEntry还是指向该分区的前一个ledger,当这个ledger过期之后,KOP目前去获取当前分区消息数会查询首个offset的时候，一直失败。

io.streamnative.pulsar.handlers.kop.utils.OffsetFinder
```
    public static PositionImpl getFirstValidPosition(ManagedLedgerImpl managedLedger) {
        PositionImpl firstPosition = managedLedger.getFirstPosition();
        if (firstPosition == null) {
            return null;
        } else {
            return managedLedger.getNextValidPosition(firstPosition);
        }
    }
```
如果修改KOP的OffsetFinder，是不是获取到firstPosition之后，判断下ledger是否过期？还是直接修改ManagedLedgerImpl的getFirstPosition逻辑？不知道会不会引入其他问题，还请各位专家帮忙看下，谢谢。

**Comment by BewareMyPower** [comment]
I think we should fix it at KoP side.

**Comment by xiaotongwang1** [comment]
> I think we should fix it at KoP side.

any idea?

**Comment by hangc0276** [comment]
> > I think we should fix it at KoP side.
> 
> any idea?

It's better to check whether the `firstPosition` exists in ManagedLedger in KOP side.

**Comment by BewareMyPower** [comment]
Move this issue to KoP repo.

**Comment by BewareMyPower** [comment]
Reopen this issue since it might also be a bug at Pulsar side.

**Comment by Jason918** [comment]
> Reopen this issue since it might also be a bug at Pulsar side.

+1, it seems that lastConfirmedEntry is not updated in ManagedLedgerImpl#internalTrimLedgers.

**Comment by BewareMyPower** [comment]
@Jason918

`internalTrimLedgers` should not update the `lastConfirmedEntry`, which represents an entry that has been written to BK successfully. After a rollover, the `lastConfirmedEntry` could be invalid if the ledger was removed. However, there is no proper new value for it. So we should just keep it unchanged.

See `ManagedLedgerImpl#getFirstPosition`, which handles the corner case.

```java
    public PositionImpl getFirstPosition() {
        Long ledgerId = ledgers.firstKey();
        if (ledgerId == null) {
            return null;
        }
        
        if (ledgerId > lastConfirmedEntry.getLedgerId()) { // 1. It means the `lastConfirmedEntry` is invalid
            // 2. In this case, the first ledger must be empty because once a new entry was added, the `lastConfirmedEntry` should be updated.
            checkState(ledgers.get(ledgerId).getEntries() == 0);
            ledgerId = lastConfirmedEntry.getLedgerId();
        }
        return new PositionImpl(ledgerId, -1);
    }
```

However, the `isValidPosition` check doesn't consider the case when `lastConfirmedEntry` is invalid.

```java
    public boolean isValidPosition(PositionImpl position) {
        PositionImpl last = lastConfirmedEntry;
        if (position.getEntryId() < 0) {
            return false;
        } else if (position.getLedgerId() > last.getLedgerId()) {
            return false;
        } else if (position.getLedgerId() == last.getLedgerId()) {
            // `last` could be an invalid position, so even position's ledger id is the same, it could still be invalid
            return position.getEntryId() <= (last.getEntryId() + 1);
        } else {
```

Then it affects the `getNextValidPosition` method that is called in KoP to get the first valid position. You can see https://github.com/streamnative/kop/pull/894 for more details about how this corner case is handled in KoP.

But the current `isValidPosition` semantics also affects other methods like `asyncOffloadPrefix` and `asyncResetCursor`. So we must take it more carefully to determine whether the semantics should be changed.

**Comment by Jason918** [comment]
> However, there is no proper new value for it.

Consider the situation that, the topic is reloaded by a load balance operation at that moment. Does the value of `lastConfirmedEntry` keep the  same?

**Comment by Jason918** [comment]
> However, there is no proper new value for it.

Consider the situation that, the topic is reloaded by a load balance operation at that moment. Does the value of `lastConfirmedEntry` keep the  same?

**Comment by BewareMyPower** [comment]
@Jason918 

I tried to modify my test to

```java
        managedLedger.getConfig().setRetentionTime(0, TimeUnit.MILLISECONDS);
        managedLedger.rollCurrentLedgerIfFull(); // the rollover is asynchronous

        // unload and load
        admin.topics().unload(topic);
        Thread.sleep(2000);
        admin.lookups().lookupTopic(topic);

        final ManagedLedgerImpl managedLedger2 = pulsar.getBrokerService().getTopicIfExists(partitionName).get()
                .map(topicObject -> (ManagedLedgerImpl) ((PersistentTopic) topicObject).getManagedLedger())
                .orElse(null);
        assertNotNull(managedLedger2);

        final List<LedgerInfo> ledgerInfoList2 = managedLedger2.getLedgersInfoAsList();
        final Position lastConfirmedEntry2 = managedLedger2.getLastConfirmedEntry();
```

The `lastConfirmedEntry` didn't change. At the same time, instead of removing old ledgers, after `unload` and `lookup` again, the old ledgers were not removed.

**Comment by Jason918** [comment]
I mean `lastConfirmedEntry` is init as "(currentLedger, -1)" in this method, if we have no other ledgers.

https://github.com/apache/pulsar/blob/98e2c66a7b2d5fd42641527cd9ad6c3b497d65c7/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L478

In the case above that all ledgers are deleted in `internalTrimLedgers`, lastConfirmedEntry is like "(lastDeleteedLedger, someEntryId)", points to a previous existed but deleted position.
But if the topic reload to maybe another broker, the `lastConfirmedEntry` would changed to "(newCreatedLedger, -1)".
During the situation shift, no new message was produced, but the `lastConfirmedEntry` was changed.
It's a little confusing, right? 

And in my understanding, if we update `lastConfirmedEntry` in `internalTrimLedgers`, it should works for the other methods. it's the consist with the latter case with reload.

**Comment by BewareMyPower** [comment]
We should evaluate the influence if we updated `lastConfirmedEntry` in `internalTrimLedgers`. Because some methods might rely on the current semantics that `lastConfirmedEntry` can point to a deleted entry.

Unless we can add a unit test to prove the current semantics might cause some problems, we should not change it.
