### ISSUE TITLE
Unable to install pulsar-client to alpine

### ISSUE THREAD

**Issue by nlandeker** [apache/pulsar#12623]
**Describe the bug**
I am unable to install pulsar-client (https://pypi.org/project/pulsar-client/) to alpine Docker container.

**To Reproduce**
1. Use python:3.8-alpine3.14
2. Try to install pulsar-client (`pip install -v pulsar-client`)
3. Try specific version 2.8.0, 2.8.1
4. Error: Could not find a version that satisfies the requirement

**Expected behavior**
Package successfully installed

If I understand correctly this should work. (https://github.com/apache/pulsar/pull/7101)

**Comment by codelipenghui** [comment]
@timmyyuan Could you please help take a look at this issue?

**Comment by nlandeker** [comment]
Hi, any news on this? Do you need any additional info?

**Comment by thacoon** [comment]
@nlandeker according to Issue #12293 the package is currently not available/published for Python versions 3.8, 3.9 and 3.10

**Comment by nlandeker** [comment]
Hi, thanks for issue link. When can we expect this to be resolved? Thanks a lot.

**Comment by timmyyuan** [comment]
Hi, @nlandeker this may have to wait for PMC members with sufficient authority to release it, I think if you need to use it urgently, maybe you can build it yourself.

**Comment by timmyyuan** [comment]
@hangc0276 Could you take a look if you have time, it seems that the alpine python client has not been added to the apache/pulsar release process. Thanks.

**Comment by nlandeker** [comment]
@timmyyuan any idea when PMC members will get to this? I have build it myself but it is much more convenient to have it available via PyPi :)

**Comment by timmyyuan** [comment]
@nlandeker Sorry for the late reply, I'll take a look this weekend

**Comment by nlandeker** [comment]
Hi, any updates on this? :)

Thanks a lot.

**Comment by JanVosNL** [comment]
@b0mbays 

Apache Pulsar C++ client is available on Alpine Linux

```
# apk search pulsar-client
py3-pulsar-client-cpp-2.9.1-r0
pulsar-client-cpp-static-2.9.1-r0
pulsar-client-cpp-2.9.1-r0
pulsar-client-cpp-dev-2.9.1-r0

# apk info py3-pulsar-client-cpp
py3-pulsar-client-cpp-2.9.1-r0 description:
Python bindings for Apache Pulsar C++ client

py3-pulsar-client-cpp-2.9.1-r0 installed size:
4996 KiB

# apk info pulsar-client-cpp
pulsar-client-cpp-2.9.1-r0 description:
Apache Pulsar C++ client

pulsar-client-cpp-2.9.1-r0 installed size:
3168 KiB

# apk add py3-pulsar-client-cpp
(1/1) Installing py3-pulsar-client-cpp (2.9.1-r0)

# python3 --version
Python 3.10.3
```

**Comment by tisonkun** [comment]
Closed as stale and it seems to work well in the latest version.

The development of the C++ client has been permanently moved to https://github.com/apache/pulsar-client-cpp. If it's still relevant, please open an issue there.

The development of the Python client has been permanently moved to https://github.com/apache/pulsar-client-python. If it's still relevant, please open an issue there.
