### ISSUE TITLE
PIP 87: Upgrade Pulsar Website Framework

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#12637]
Design proposal, solution, implementation progress, and all details are available [here](https://docs.google.com/document/d/1IV35SI_F8G8cL-Vuzknc6RTGLK9_edRMpZpnrHvAWNs/edit).

**Comment by codelipenghui** [comment]
@Anonymitaet Looks the link is for Pulsar bot.

**Comment by Anonymitaet** [comment]
@codelipenghui thanks for reminding me, I've corrected the URL.

**Comment by tisonkun** [comment]
Closed as delivered.
