### ISSUE TITLE
Pass all Apache Podling Website Checks

### ISSUE THREAD

**Issue by maskit** [apache/pulsar#1266]
#### Expected behavior

All Apache Podling Website Checks are green
https://whimsy.apache.org/pods/project/pulsar

#### Actual behavior

Some are red

**Comment by merlimat** [comment]
@maskit fixes few links. There are 2 items still pending: 

 * Image. How do we upload the logo on `http://apache.org/img/` ? 
 * Events: we should ideally have an "events" page on the website, where we can list all upcoming & past meetups and presentations.

**Comment by maskit** [comment]
> Image. How do we upload the logo on http://apache.org/img/ ?

We might be able to commit a file onto the svn? or we might need to ask infra team.
https://github.com/apache/whimsy/blob/master/tools/site-scan.rb#L25

**Comment by maskit** [comment]
Generated a 212px width PNG logo image from the SVG in site/img/ that satisfies the requirement[1].

![pulsar](https://user-images.githubusercontent.com/153144/37105921-c014356c-2273-11e8-9a79-108372169b58.png)


[1] https://svn.apache.org/repos/asf/infrastructure/site/trunk/content/img/HEADER.html

**Comment by maskit** [comment]
I added the logo to the svn repo. Seems like all committers have the access.
https://svn.apache.org/repos/asf/infrastructure/site/trunk/content/img/pulsar.png

**Comment by maskit** [comment]
Yay, "Image" row got green.

**Comment by merlimat** [comment]
Thanks @maskit . We are almost there, the only missing piece now is the "Events" page in website now.

**Comment by maskit** [comment]
We have an event page but the check result is still red.

It seems like the check script expects an absolute URL.
https://github.com/apache/whimsy/blob/master/tools/site-scan.rb#L73

**Comment by maskit** [comment]
I got an email on another project, and it encourages to add ApacheCon promotion to our project site.
http://apache.org/events/README.txt

I think changing the URL for *our* current-event-page to an absolute URL is not a good idea because it doesn't work on a local copy, but putting another link for ApacheCon as an absolute URL would be a good idea to make the check result green.

The logo will be updated automatically and will show the next event, so we can put the logo on our site permanently (no need to put, remove, put, remove, ...).

Where should we put the logo? While I think it should be above the fold, I don't want to break current cool design.

**Comment by lucperkins** [comment]
I can create an events page

**Comment by lucperkins** [comment]
Oh whoops, looks like that was already taken care of

**Comment by maskit** [comment]
@lucperkins As I wrote on my last comment, we have an event page but we haven't passed the check because the check is a bit strict. It would be great if you could add a link for ApacheCon page with the logo. Then we probably be able to dodge the check.

**Comment by sijie** [comment]
(Move this to 2.1.0, since it is not a blocker for 2.0)

**Comment by sijie** [comment]
Pulsar already graduated :)
