### ISSUE TITLE
PIP 78: Generate Docs from Code Automatically

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#12664]
Design proposal, solution, implementation progress, and all details are available [here](https://docs.google.com/document/d/18kCBG5nyp0BsscFDyQyUERHrCMRcKmzyk1RMaD4hECg/edit#heading=h.vi6h0opyf73o).

**Comment by tisonkun** [comment]
All subtasks have been done.

If there're any outstanding issues, we can open new ones for them.
