### ISSUE TITLE
Improve failover subscription for non-partitioned topic

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#1267]
*Problem*

Currently failover subscription is sorting the consumers. so if a consumer who consumer name is always the first consumer after sorting and the consumer has flaky network where it joins and leaves, this would cause the whole subscription getting into a *flaky* state, where the "active" consumer joins and leaves, no consumer is actually elected as "active" and consuming the messages.

The sorting logic is useful for partitioned topics. However it is not necessarily required by non-partitioned topic. So we should change the logic to not sort the consumers and make the "active" consumer stabilize no matter how other consumers joining the subscription.

**Comment by jerrypeng** [comment]
+1

**Comment by sijie** [comment]
fixed by #1156

**Comment by merlimat** [comment]
This should be easy to do, since we're already checking the topic/partition name (to know which Nth partition we're looking at).

**Comment by MarvinCai** [comment]
Part of the problem has been fix by https://github.com/apache/pulsar/pull/2954, now dispatcher will sort consumer based on priority level and consumer name then distributed sub for partitioned topic evenly through all consumers with same priority level.
For non partitioned topic the problem described is still there, I have a pr to fix active consumer for FailOver subscription on non partitioned topic to always be the first one. And consumer will be picked in the order they subscribe to the non partitioned topic.

**Comment by Lanayx** [comment]
@MarvinCai or @sijie  Can you please explain the phrase "The sorting logic is useful for partitioned topics."? Why is it different for partitioned and non-partitioned topics?

**Comment by MarvinCai** [comment]
@sijie Please correct me if my explanation is wrong. 
Partitioned topic is implemented as N internal topics, so non-partitioned topic map to single internal topic and partitioned topic map to X of internal topic depends on number of partitions. 
And for partitioned topic with failover subscription active consumer will be pick for each partition(internal topic),  if more than one consumer connect the sorting is important to make sure assignment happens evenly across highest priority consumers, while for non-partitioned topic there'll be single active consumer so all the sorting is not very necessary.

**Comment by Lanayx** [comment]
@MarvinCai Ah, it seems I understand now - by orderring we want to avoid the situation when subconsumers from one partitioned consumer are  mixed with subsconsumers from another partitioned consumer.

**Comment by MarvinCai** [comment]
Yeah,  that's true if we have X consumer subscribe to partitioned topic with X partition where X > Y with failover sub mode, then each partition of the topic will have a different active consumer picked by priority level then consumer name.
