### ISSUE TITLE
I'm getting an error while building

### ISSUE THREAD

**Issue by frkn4129** [apache/pulsar#12728]
I want to install pulsar_client_cpp but I get an error while building. I couldn't understand why

.
.
.
.
[ 55%] Building CXX object lib/CMakeFiles/PULSAR_OBJECT_LIB.dir/stats/ProducerStatsImpl.cc.o
[ 55%] Building CXX object lib/CMakeFiles/PULSAR_OBJECT_LIB.dir/__/generated/lib/PulsarApi.pb.cc.o
[ 55%] Built target PULSAR_OBJECT_LIB
Scanning dependencies of target pulsarStatic
[ 56%] Linking CXX static library libpulsar.a
[ 56%] Built target pulsarStatic
Scanning dependencies of target pulsarShared
[ 57%] Linking CXX shared library libpulsar.so
[ 57%] Built target pulsarShared
Scanning dependencies of target SampleAsyncProducer
[ 58%] Building CXX object examples/CMakeFiles/SampleAsyncProducer.dir/SampleAsyncProducer.cc.o
[ 58%] Linking CXX executable SampleAsyncProducer
[ 58%] Built target SampleAsyncProducer
Scanning dependencies of target SampleConsumer
[ 59%] Building CXX object examples/CMakeFiles/SampleConsumer.dir/SampleConsumer.cc.o
[ 59%] Linking CXX executable SampleConsumer
[ 59%] Built target SampleConsumer
Scanning dependencies of target SampleConsumerListener
[ 60%] Building CXX object examples/CMakeFiles/SampleConsumerListener.dir/SampleConsumerListener.cc.o
[ 61%] Linking CXX executable SampleConsumerListener
[ 61%] Built target SampleConsumerListener
Scanning dependencies of target SampleProducer
[ 61%] Building CXX object examples/CMakeFiles/SampleProducer.dir/SampleProducer.cc.o
[ 62%] Linking CXX executable SampleProducer
[ 62%] Built target SampleProducer
Scanning dependencies of target SampleProducerCApi
[ 62%] Building C object examples/CMakeFiles/SampleProducerCApi.dir/SampleProducerCApi.c.o
[ 63%] Linking C executable SampleProducerCApi
[ 63%] Built target SampleProducerCApi
Scanning dependencies of target SampleFileLogger
[ 63%] Building CXX object examples/CMakeFiles/SampleFileLogger.dir/SampleFileLogger.cc.o
[ 64%] Linking CXX executable SampleFileLogger
[ 64%] Built target SampleFileLogger
Scanning dependencies of target SampleConsumerCApi
[ 65%] Building C object examples/CMakeFiles/SampleConsumerCApi.dir/SampleConsumerCApi.c.o
[ 65%] Linking C executable SampleConsumerCApi
[ 65%] Built target SampleConsumerCApi
Scanning dependencies of target SampleConsumerListenerCApi
[ 65%] Building C object examples/CMakeFiles/SampleConsumerListenerCApi.dir/SampleConsumerListenerCApi.c.o
[ 66%] Linking C executable SampleConsumerListenerCApi
[ 66%] Built target SampleConsumerListenerCApi
Scanning dependencies of target SampleReaderCApi
[ 66%] Building C object examples/CMakeFiles/SampleReaderCApi.dir/SampleReaderCApi.c.o
[ 67%] Linking C executable SampleReaderCApi
[ 67%] Built target SampleReaderCApi
[ 68%] Generating ../generated/tests/PaddingDemo.pb.cc
**PaddingDemo.proto:25:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
make[2]: *** [tests/CMakeFiles/main.dir/build.make:69: generated/tests/PaddingDemo.pb.cc] Error 1
make[1]: *** [CMakeFiles/Makefile2:556: tests/CMakeFiles/main.dir/all] Error 2
make: *** [Makefile:130: all] Error 2**

**Comment by eolivelli** [comment]
which branch are you building ?
which command are you using ?

**Comment by frkn4129** [comment]
master branch building

Step by Step ->
$ cd /usr/src/googletest
$ sudo cmake .
$ sudo make
$ sudo cp ./googlemock/libgmock.a ./googlemock/gtest/libgtest.a /usr/lib/


$ cd /usr/src/gtest
$ sudo cmake .
$ sudo make
$ sudo cp libgtest.a /usr/lib

$ cd /usr/src/gmock
$ sudo cmake .
$ sudo make
$ sudo cp libgmock.a /usr/lib

$ cd pulsar-client-cpp
$ cmake .
$ make **I am getting the error here**

**Comment by frkn4129** [comment]
**when i try to relocate the directory and get "make".**


(base) gurkan@gurkanseker:~/pulsar-client-cpp$ make 
make[2]: *** No rule to make target 'lib/../../pulsar-common/src/main/proto/PulsarApi.proto', needed by 'generated/lib/PulsarApi.pb.cc'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:286: lib/CMakeFiles/PULSAR_OBJECT_LIB.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
**it gave error like this**

**Comment by codelipenghui** [comment]
Looks like you have installed protobuf3 but Pulsar uses protobuf2,

You can try 

```
pulsar-client-cpp/pkg/rpm/docker-build-rpm.sh

pulsar-client-cpp/pkg/deb/docker-build-deb.sh
```

which can build by docker.

**Comment by tisonkun** [comment]
Closed as stale.

The development of the C++ client has been permanently moved to https://github.com/apache/pulsar-client-cpp. If it's still relevant, please open an issue there.
