### ISSUE TITLE
How to debug pulsar protocol handler in the local development environment?

### ISSUE THREAD

**Issue by Richard-Yi** [apache/pulsar#12750]
I added some code in aop and wanna test and debug it. 
Is the only way to test my code is through Pulsar (start a standalone broker and load the plugin)?
How to debug pulsar protocol handler such as aop/kop in my local dev environment IDE ?

**Comment by codelipenghui** [comment]
There is a test framework which used by Pulsar protocol handlers, details see here, the example of mop: https://github.com/streamnative/mop/tree/master/tests

You can just run `mvn clean install -DskipTests` under the repo and then write a test to connect to the test Pulsar service for debugging.

**Comment by Richard-Yi** [comment]
thx, I think i know how to do it now~

**Comment by tisonkun** [comment]
Close as answered.
