### ISSUE TITLE
Support enable or disable schema upload at the broker level

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#12757]
For users who want to avoid the client side upload schemas to the topic, we can only change the namespace policy to disable the schema auto upload, it's better to have a broker level control to avoid setting policies for every namespace.

```
isSchemaAutoUploadEnabled=true
```

**Comment by Jason918** [comment]
I can work on it. :)

**Comment by codelipenghui** [comment]
Thanks, @Jason918 assigned to you.
