### ISSUE TITLE
In the process of perf,Failed to open connection to pulsar.

### ISSUE THREAD

**Issue by xiaobing0508** [apache/pulsar#12772]
My pulsar version 2.8.1.

Broker logs is 
WARN  org.apache.pulsar.broker.service.ServerCnx - [/192.168.149.32:39008] Got exception io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer.
INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /192.168.149.32:36726
INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /192.168.149.32:40560
INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /192.168.149.32:36756

why is that?

Performance Tuning can be solved ?

**Comment by codelipenghui** [comment]
@xiaobing0508 Here is a related issue https://github.com/reactor/reactor-netty/issues/1469, I think you should to check your  test env network.
