### ISSUE TITLE
Migrate Maven projects to Gradle 

### ISSUE THREAD

**Issue by mattisonchao** [apache/pulsar#12783]
**Do we plan to migrate the maven project to Gradle?**

![40kom3wn1z](https://user-images.githubusercontent.com/74767115/141612684-8e580a00-c9cc-48d6-9343-d5d0e2232a05.png)

this image show the Gradle is 3-10 times faster in clean builds, about 85 times faster in incremental builds, and 13 times faster when Gradle task output is cached.

**Comment by merlimat** [comment]
Yes, this has been discussed some time ago. The point there was to wait for the BookKeeper migration to Gradle to be completed (https://bookkeeper.apache.org/bps/BP-43-gradle-migration/) before starting with Pulsar. The BK change is close to completion and will be released in BK-4.15

**Comment by mattisonchao** [comment]
could I do something to help with this?

**Comment by yangl** [comment]
Yes, but I'm currently using [mvnd](https://github.com/mvndaemon/mvnd) which is also quite fast as Gradle.
