### ISSUE TITLE
Ensure the deletion consistency of topic and schema

### ISSUE THREAD

**Issue by yuruguo** [apache/pulsar#12795]
**Is your enhancement request related to a problem? Please describe.**
Currently, we can delete the topic without deleting its schemas (I think the topic and the schema are managed separately to make this behavior possible) through `bin/pulsar-admin topics delete-partitioned-topic persistent://tenant/namespace/topic`. in this case, there will be a significant problem for topic with schemas, that is,  its schemas still remain but the topic no longer exists.

I'm not sure what is the biggest benefit of these remained schemas, perhaps these remained schemas can be reused when we recreate topic. However, when these remained schemas are no longer suitable for the reconstructed topic, it will obviously become a burden.

In addition, a series of schema operations (`get`, `delete`, `upload`, etc.) also need to be controlled after enabling auth. At present, the role with the tenant permission can complete the above operations of the schema. Obviously, the control granularity should be further converged. In fact, the operations on the schema should be reduced to the role with the `lookup` topic permission(details in this [issue](https://github.com/apache/pulsar/issues/12419)). Unfortunately, the case that schemas exists but topic no longer exists causes not get topic auth policies.

**Describe the solution you'd like**
1. One of the most direct ways is to delete the topic and delete the schema at the same time. In the implementation, we can remove the `deleteSchema` option, but this will be inconsistent with the behavior of the previous version, because this is a breaking API change.
https://github.com/apache/pulsar/blob/ba5809553344f074c5dce15618a70f3b20d368c7/pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java#L481-L498
**NOTE**：When `brokerDeleteInactiveTopicsEnabled` is true, the broker will delete topics and the schema will also be deleted by default, as below：
https://github.com/apache/pulsar/blob/099c958395b5618c80e10c36f04c8f53a6c999bd/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L2246-L2247

2. In fact, maybe we  can add a key ~~`allowedAutoTopicDeletion`~~  -> `allowedAutoDeleteSchemas` in `broker.conf`, so schemas that topic not exists can be automatically deleted when ~~`allowedAutoTopicDeletion`~~ -> `allowedAutoDeleteSchemas` value is true (default: false). And in this case, we can determine whether the role is allowed to operate the schema according to the topic auth policies.

**Comment by codelipenghui** [comment]
Very confused, not sure why the topic was removed but the schema is still there. I think we can start a discussion to remove the `--deleteSchema` option, to make sure the schema should be deleted when deleting the topic.

For the topic auto-deletion, we should enable topic auto-creation and schema auto upload, so I think it's not reasonable to keep the schema after the topic has been deleted. It will bring surprises to a newly created topic with the same name as deleted one, users don't upload any schemas but the new topic will with an existing schema automatically.

**Comment by yuruguo** [comment]
> Very confused, not sure why the topic was removed but the schema is still there. I think we can start a discussion to remove the `--deleteSchema` option, to make sure the schema should be deleted when deleting the topic.
> 
> For the topic auto-deletion, we should enable topic auto-creation and schema auto upload, so I think it's not reasonable to keep the schema after the topic has been deleted. It will bring surprises to a newly created topic with the same name as deleted one, users don't upload any schemas but the new topic will with an existing schema automatically.

I think it is necessary to discuss about ‘remove the **--deleteSchema** option’, because it is more profitable to ensure that the consistency of the topic and the schema exist than the inconsistency, mainly in two points:
1. Avoid the impact of residual schema on new topic(has same name with the deleted topic)
2. Able to better converge schema operation permissions

In addition, I am sorry and I need to correct that the possible configuration is `allowedAutoDeleteSchemas`  not `allowedAutoTopicDeletion`, its effect is to delete the schema when deleting the topic.
