### ISSUE TITLE
bookie 缩容

### ISSUE THREAD

**Issue by azeng528** [apache/pulsar#12835]
集群结构：
pulsar版本：2.4.0
3节点：zk+bookie+broker
扩容5节点192.168.1.1-5

缩容操作：
操作第一台主机：
systemctl stop broker
systemctl stop bookie
./bin/bookkeeper shell decommissionbookie -bookieid 192.168.1.1:3181
执行后报错如下：
22:27:10.876 [main] INFO  org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl - Not weighted
22:27:10.878 [main] INFO  org.apache.bookkeeper.client.BookKeeper - Weighted ledger placement is not enabled
22:27:10.903 [BookKeeperClientScheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.net.NetworkTopologyImpl - Adding a new node: /default-rack/10.22.131.5:3181
22:27:10.904 [BookKeeperClientScheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.net.NetworkTopologyImpl - Adding a new node: /default-rack/10.22.131.56:3181
22:27:10.905 [BookKeeperClientScheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.net.NetworkTopologyImpl - Adding a new node: /default-rack/10.22.131.55:3181
22:27:10.906 [BookKeeperClientScheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.net.NetworkTopologyImpl - Adding a new node: /default-rack/10.22.131.54:3181
22:27:10.907 [BookKeeperClientScheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.net.NetworkTopologyImpl - Adding a new node: /default-rack/10.22.131.4:3181
22:27:10.908 [BookKeeperClientScheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.net.NetworkTopologyImpl - Adding a new node: /default-rack/10.22.131.3:3181
22:27:10.909 [BookKeeperClientScheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.net.NetworkTopologyImpl - Adding a new node: /default-rack/10.22.131.2:3181
22:27:10.992 [main] INFO  org.apache.bookkeeper.client.BookKeeperAdmin - Resetting LostBookieRecoveryDelay value: 0, to kickstart audit task
22:29:41.233 [main] INFO  org.apache.bookkeeper.client.BookKeeperAdmin - Count of Ledgers which need to be rereplicated: 257098
22:29:41.233 [main] ERROR org.apache.bookkeeper.bookie.BookieShell - Received exception in DecommissionBookieCmd 
java.lang.IllegalArgumentException: timeout value is negative
        at java.lang.Thread.sleep(Native Method) ~[?:1.8.0_212]
        at org.apache.bookkeeper.client.BookKeeperAdmin.waitForLedgersToBeReplicated(BookKeeperAdmin.java:1528) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
        at org.apache.bookkeeper.client.BookKeeperAdmin.decommissionBookie(BookKeeperAdmin.java:1500) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
        at org.apache.bookkeeper.bookie.BookieShell$DecommissionBookieCmd.runCmd(BookieShell.java:2664) [org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
        at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:277) [org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
        at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:3081) [org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
        at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:3172) [org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
22:29:41.248 [main] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x2000001073e02b0 closed

**Comment by Technoboy-** [comment]
This is a known bug with fix [bookkeeper#2284](https://github.com/apache/bookkeeper/pull/2284)

**Comment by hangc0276** [comment]
You can follow the steps to fix the bug.
1. cherry-pick this pr(https://github.com/apache/bookkeeper/pull/2284) to your bookkeeper code, 
2. build the bookkeeper server module
3. replace the bookkeeper jar into one of your bookies
4. run decommissionbookie command on the updated bookie

Notice: before run decommissionbookie command, you should ensure there is not under replicating ledgers.

**Comment by azeng528** [comment]
14:12:56.982 [main] INFO  org.apache.bookkeeper.client.BookKeeperAdmin - Count of Ledgers which need to be rereplicated: 272752
14:12:56.983 [main] ERROR org.apache.bookkeeper.bookie.BookieShell - Received exception in DecommissionBookieCmd 
java.lang.IllegalArgumentException: timeout value is negative
	at java.lang.Thread.sleep(Native Method) ~[?:?]
	at org.apache.bookkeeper.client.BookKeeperAdmin.waitForLedgersToBeReplicated(BookKeeperAdmin.java:1528) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.bookkeeper.client.BookKeeperAdmin.decommissionBookie(BookKeeperAdmin.java:1500) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.bookkeeper.bookie.BookieShell$DecommissionBookieCmd.runCmd(BookieShell.java:2664) [org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:277) [org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:3081) [org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
	at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:3172) [org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
14:12:57.013 [main] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x206189927840052 closed


Count of Ledgers which need to be rereplicated: 272752
num：272752表示的是某台bookie上的ledger数量还是所有ledger的总数？

**Comment by azeng528** [comment]
![image](https://user-images.githubusercontent.com/19300752/142156062-989662bb-bb9d-4b5c-80c3-47eee2e7965f.png)
通过图上所示，
问题1：通过命令行获取的ledger数量和监控取值的，两个差别怎么如此巨大？
问题2：如果ledger的数量是图上listledgers获取的值所示，那么bookie后台还在清理过期消息，为啥还有那么多的ledger呢？请问导致这种大的ledger是什么原因导致的呢？

**Comment by azeng528** [comment]
[zk: localhost:2181(CONNECTED) 0] ls /ledgers/underreplication/ledgers
[]
情况描述：
有3节点，我重启第一台bookie后，发现zk里面这个/ledgers/underreplication/ledgers节点下面存在数据，是不是表示有消息没有复制完成，这样我就不能马上重启第二台bookie节点，否则有丢失数据的风险？

**Comment by hangc0276** [comment]
> 14:12:56.982 [main] INFO org.apache.bookkeeper.client.BookKeeperAdmin - Count of Ledgers which need to be rereplicated: 272752 14:12:56.983 [main] ERROR org.apache.bookkeeper.bookie.BookieShell - Received exception in DecommissionBookieCmd java.lang.IllegalArgumentException: timeout value is negative at java.lang.Thread.sleep(Native Method) ~[?:?] at org.apache.bookkeeper.client.BookKeeperAdmin.waitForLedgersToBeReplicated(BookKeeperAdmin.java:1528) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2] at org.apache.bookkeeper.client.BookKeeperAdmin.decommissionBookie(BookKeeperAdmin.java:1500) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2] at org.apache.bookkeeper.bookie.BookieShell$DecommissionBookieCmd.runCmd(BookieShell.java:2664) [org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2] at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:277) [org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2] at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:3081) [org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2] at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:3172) [org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2] 14:12:57.013 [main] INFO org.apache.zookeeper.ZooKeeper - Session: 0x206189927840052 closed
> 
> Count of Ledgers which need to be rereplicated: 272752 问题： num：272752表示的是某台bookie上的ledger数量还是所有ledger的总数？

272752 ledgers to be replicated.

**Comment by hangc0276** [comment]
> ![image](https://user-images.githubusercontent.com/19300752/142156062-989662bb-bb9d-4b5c-80c3-47eee2e7965f.png) 通过图上所示，监控上没有发现backlog堆积 问题1：通过命令行获取的ledger数量和监控取值的，两个差别怎么如此巨大？ 问题2：如果ledger的数量是图上listledgers获取的值所示，那么bookie后台还在清理过期消息，为啥还有那么多的ledger呢？请问导致这种大的ledger是什么情况会触发【例如：大量写入消息】？

`bin/bookkeeper shell listledgers` represent all ledgers in your bookkeeper cluster.

**Comment by hangc0276** [comment]
> [zk: localhost:2181(CONNECTED) 0] ls /ledgers/underreplication/ledgers [] 情况描述： 有3节点，我重启第一台bookie后，发现zk里面这个/ledgers/underreplication/ledgers节点下面存在数据，是不是表示有消息没有复制完成，这样我就不能马上重启第二台bookie节点，否则有丢失数据的风险？

you can use `bin/bookkeeper listuderreplicated` command to check whether there are ledgers to be replicated.

you can roll restart all bookies without considering the replicated process. But if you do decommission operation, you should ensure all ledgers replicated before starting next bookie decommission.

**Comment by azeng528** [comment]
> > ![image](https://user-images.githubusercontent.com/19300752/142156062-989662bb-bb9d-4b5c-80c3-47eee2e7965f.png) 通过图上所示，监控上没有发现backlog堆积 问题1：通过命令行获取的ledger数量和监控取值的，两个差别怎么如此巨大？ 问题2：如果ledger的数量是图上listledgers获取的值所示，那么bookie后台还在清理过期消息，为啥还有那么多的ledger呢？请问导致这种大的ledger是什么情况会触发【例如：大量写入消息】？
> 
> `bin/bookkeeper shell listledgers` represent all ledgers in your bookkeeper cluster.

通过监控提取的值：
![image](https://user-images.githubusercontent.com/19300752/142158109-757ab490-009d-44a5-8293-b7cad2bb5cfb.png)
就算现有我们集群所有ledger加起来，也没有我们listledgers的多啊？

**Comment by azeng528** [comment]
> > [zk: localhost:2181(CONNECTED) 0] ls /ledgers/underreplication/ledgers [] 情况描述： 有3节点，我重启第一台bookie后，发现zk里面这个/ledgers/underreplication/ledgers节点下面存在数据，是不是表示有消息没有复制完成，这样我就不能马上重启第二台bookie节点，否则有丢失数据的风险？
> 
> you can use `bin/bookkeeper listuderreplicated` command to check whether there are ledgers to be replicated.
> 
> you can roll restart all bookies without considering the replicated process. But if you do decommission operation, you should ensure all ledgers replicated before starting next bookie decommission.

问题

`bin/bookkeeper listuderreplicated`反应的是整个bookie集群，所有未复制ledger还是我执行命令那台bookie上所属ledger？

**Comment by sl1316** [comment]
just related to the scaling down process of bookies. does pulsar provide any automatic bookie hosts scale down/up strategies? if not, is there a good strategy to estimate how many bookies we can release? 
the use case is we usually have the peek traffic for few days a month and the remaining days the usage is rather low

**Comment by tisonkun** [comment]
Closed as answered.
