### ISSUE TITLE
go client: message ID serialization / deserialization, then AckID failed

### ISSUE THREAD

**Issue by storm-5** [apache/pulsar#12832]
**Describe the bug**
message ID serialization / deserialization, then AckID failed.

**To Reproduce**
1. receive a message
2. Serialize the messageID
3. DeserializeMessageID
4. Ack the message by id

**Expected behavior**
AckID success.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: debian 11
![2021-11-16_18-16](https://user-images.githubusercontent.com/731347/141966775-35fcb95a-fe71-40de-b4e0-02e6a4d6a13e.png)

**Additional context**

**Comment by nodece** [comment]
@storm-5 could you provide the pulsar version and go client version?

**Comment by storm-5** [comment]
> @storm-5 could you provide the pulsar version and go client version?

the pulsar vesion is: 2.7.2
the go client version is: v0.6.0. I have try v0.7.0, the same error.

**Comment by nodece** [comment]
could you provide the go code to test this issue?

**Comment by storm-5** [comment]
> could you provide the go code to test this issue?

here is. I have wipe the sensitive info.

```go

package main

import (
	"context"
	"fmt"
	"time"

	"github.com/apache/pulsar-client-go/pulsar"
)

func main() {
	url := ""
	token := ""
	topic := ""
	subscName := ""

	client, _ := pulsar.NewClient(pulsar.ClientOptions{
		URL:               url,
		Authentication:    pulsar.NewAuthenticationToken(token),
		OperationTimeout:  30 * time.Second,
		ConnectionTimeout: 30 * time.Second,
	})

	producer, _ := client.CreateProducer(pulsar.ProducerOptions{
		Topic: topic,
	})
	snmid, _ := producer.Send(context.Background(), &pulsar.ProducerMessage{
		Payload: []byte("hello"),
	})
	fmt.Printf("%x", snmid.Serialize())

	consumer, err := client.Subscribe(pulsar.ConsumerOptions{
		Topic:            topic,
		SubscriptionName: subscName,
		Type:             pulsar.Shared,
		RetryEnable:      true,
		DLQ: &pulsar.DLQPolicy{
			MaxDeliveries:    1,
			RetryLetterTopic: topic + "-RETRY",
			DeadLetterTopic:  topic + "-DLQ",
		},
	})
	fmt.Printf("%s", err)
	ctx, cancel := context.WithTimeout(context.Background(), 10000*time.Millisecond)
	defer cancel()
	for {
		msg, _ := consumer.Receive(ctx)
		midOri := msg.ID()
		midBytes := midOri.Serialize()
		midNew, _ := pulsar.DeserializeMessageID(midBytes)
		consumer.AckID(midNew)
		// consumer.AckID(midOri)
		// consumer.Ack(msg)
		fmt.Printf("%s, ", msg.Payload())
	}
}
```

**Comment by nodece** [comment]
@storm-5 You should pass the `msg.ID()` to `consumer.AckID()`, it is working. When you call the `pulsar.DeserializeMessageID(midBytes)` to get the message ID and pass it to ack, it is not working, the `messageID` doesn't include the consumer, you can check out this: https://github.com/apache/pulsar-client-go/blob/master/pulsar/consumer_multitopic.go#L133, maybe we can use the consumer of the current instance.

**Comment by storm-5** [comment]
@nodece Yes, it should be a solution.  But in my scene, i want to hide the mq detail to my client, so my code act as a agent. And  i also want to balance the client work with multiple agents. Then the problem is, the client fetch a message and ack the message might consult diffent agent, and the ack can fail.

Maybe the Serialize operate should move to the consumer, so that the serialized message id contains the consumer info.
