### ISSUE TITLE
How to set pulsar producer conf

### ISSUE THREAD

**Issue by mattisonchao** [apache/pulsar#12867]
In the original docs 

> Chunking
When you enable chunking, read the following instructions.

>Batching and chunking cannot be enabled simultaneously. To enable chunking, you must disable batching in advance.
>Chunking is only supported for persisted topics.
>Chunking is only supported for the exclusive and failover subscription types.
>When chunking is enabled (chunkingEnabled=true), if the message size is greater than the allowed maximum publish-payload size, the producer splits the original message into chunked messages and publishes them with chunked metadata to the broker separately and in order. At the broker side, the chunked messages are stored in the managed-ledger in the same way as that of ordinary messages. The only difference is that the consumer needs to buffer the chunked messages and combines them into the real message when all chunked messages have been collected. The chunked messages in the managed-ledger can be interwoven with ordinary messages. If producer fails to publish all the chunks of a message, the consumer can expire incomplete chunks if consumer fail to receive all chunks in expire time. By default, the expire time is set to one hour.

>The consumer consumes the chunked messages and buffers them until the consumer receives all the chunks of a message. And then the consumer stitches chunked messages together and places them into the receiver-queue. Clients consume messages from the receiver-queue. Once the consumer consumes the entire large message and acknowledges it, the consumer internally sends acknowledgement of all the chunk messages associated to that large message. You can set the maxPendingChunkedMessage parameter on the consumer. When the threshold is reached, the consumer drops the unchunked messages by silently acknowledging them or asking the broker to redeliver them later by marking them unacknowledged.

>The broker does not require any changes to support chunking for non-shared subscription. The broker only uses chunkedMessageRate to record chunked message rate on the topic.

How can i set **maximum publish-payload size**.

**Comment by leizhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2684384/142369478-8ed303c7-3845-467b-a948-7f5b3e8a111f.png)

you can set this, when broker has this setting, CommandConnected will be sent to producer

![image](https://user-images.githubusercontent.com/2684384/142369643-1c9d4339-b593-4188-b23e-6db2b821913e.png)

**Comment by mattisonchao** [comment]
Oh, i see.  thank you so much. : )

**Comment by mattisonchao** [comment]
i will close this issue.
