### ISSUE TITLE
Pulsar Manager Docker Image v0.2.0 - needs some updates

### ISSUE THREAD

**Issue by nddipiazza** [apache/pulsar#12952]
**Is your feature request related to a problem? Please describe.**
The `apachepulsar/pulsar-manager:v0.2.0` docker image is getting pretty out of date.

I cannot install it in my org because the containers are so out of date they need bumped for versions to fix known CVEs.

**Describe the solution you'd like**
Let's bump the pulsar-manager container to get some fixes for java libraries and container libraries.

**Describe alternatives you've considered**
n/a

**Comment by tuteng** [comment]
I think I need to take the time to look at it

**Comment by tisonkun** [comment]
Pulsar Manager has released a 0.3.0 and the 0.4.0 in under-voting - https://lists.apache.org/thread/qrobzlrcsvbz18j6ft5vhwy5p8665k9x

Also, it has a dedicated repo https://github.com/apache/pulsar-manager to handle issues.

So close this issue here.
