### ISSUE TITLE
`AutoConsume` should support protobuf schema

### ISSUE THREAD

**Issue by freeznet** [apache/pulsar#12969]
**Describe the bug**
When consuming protobuf schema messages with `AUTO_CONSUME` consumer, will get `Retrieve schema instance from schema info for type 'PROTOBUF' is not supported yet` exception.

**Expected behavior**
Consume protobuf as `GenericRecord` with `AUTO_CONSUME`

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mattisonchao** [comment]
@freeznet 
Can i try to work on it ?

**Comment by freeznet** [comment]
@mattisonchao thanks and sure, I just assigned this issue to you, let me know if you need any help.

**Comment by mattisonchao** [comment]
maybe we can not support this feature ?

**Comment by mattisonchao** [comment]
@freeznet 
According to this description of pip, we seem to be unable to support AutoConsume protobuf.
https://docs.google.com/document/d/1XR_MNOuSXyig-CKsdVhr6IXvFwziBRdSoS3oEUiLFe8/edit

Could you give me more advice?

**Comment by mattisonchao** [comment]
According to this description of pip, we seem to be unable to support AutoConsume protobuf.

https://docs.google.com/document/d/1XR_MNOuSXyig-CKsdVhr6IXvFwziBRdSoS3oEUiLFe8/edit

Could you give me more advice for this?

**Comment by eolivelli** [comment]
It should already work with protobuf native

**Comment by eolivelli** [comment]
Did you try? Which error you see?

**Comment by mattisonchao** [comment]
The details please see #13094, closed.
