### ISSUE TITLE
Add more detail regarding how pulsar treats newly added broker/bookies nodes

### ISSUE THREAD

**Issue by sl1316** [apache/pulsar#12967]
Please answer the following questions before submitting your doc issue. Thanks!

# What issue do you find in Pulsar docs?
I am investigating how pulsar treat the newly added nodes in detail but unable to find useful information under the public pulsar doc and google. the only thing I found is pulsar load balancing and it's mostly talking about how pulsar group topics into bundles, split a bundle with heavy load and load shedding for overloaded brokers(seems bookie is not the concern here). so I have some questions which needs more insights.

For newly added broker nodes.
1. could it be idle/low usage for a long time? or pulsar has some mechanism to immediately unload some topics from existing brokers when it discovers the newly added brokers. say if the load is low in average and I am trying to add more brokers just for better latency. if topics can not be moved to the new brokers, then it's not feasible.
2. I am more concerned about thundering herd problems. it's nature to add more brokers when the cluster is overloaded. since the newly added brokers have very low usage, many topics could be assigned to the few newly added broker nodes(assume we only add few).

# What is your suggestion?
an example with a few lines of explanation/a diagram should be sufficient. this section can be added to FAQ if you think the public doc is overloaded. this is very important for customers interested in migrating from kafka to pulsar since we needs the detail to convince the SRE this is what pulsar provide to reduce the maintenance burden since kafka already has ops tools to deal with the issue(although painful and manual)

# Do you have any references?

(For example, website links, etc)?

# Would you like to fix this issue?
yes but I don't have the required knowledge to contribute on this matter.
(Welcome to contribute docs! Pulsar grows from a tiny seed to a big tree with every little effort by us! Your contribution is the sunlight, water, and air!)

**Comment by Jason918** [comment]
> 1. could it be idle/low usage for a long time?

With default conf in broker.conf,  pulsar will try to do auto rebalance every `loadBalancerSheddingIntervalMinutes` (default 1) minutes if `loadBalancerSheddingEnabled` is true.

you can refer to **Load balancer** part in broker.conf for more details.

**Comment by Jason918** [comment]
> 2\. I am more concerned about thundering herd problems. it's nature to add more brokers when the cluster is overloaded. since the newly added brokers have very low usage, many topics could be assigned to the few newly added broker nodes(assume we only add few).

The auto balance mechanism will shed topics from overloaded brokers. And these topics will be loaded agains on some broker according to "loadmanager", which should be the least loaded.

And we have "loadBalancerSheddingGracePeriodMinutes" to avoid repeated shedding and loading.

**Comment by sl1316** [comment]
@Jason918  thank you for your reply. 1st question is answered and thank you!

I need to clarify my second question since it seems you didn't get my point. say you have an overloaded broker fleet and you need to add a host(just to simplify since you need some in real production). now each overloaded broker try to shed the load to the newly added host, which is much more beyond what it can process, so those topics are doomed for a while(maybe loadBalancerSheddingGracePeriodMinutes from what you mentioned above). I am looking for if there is anything like maxAllowedTopic per x min stuff, which only allow each node take x topic in a given time so each node can accept the traffic within it's capability. this is what I mean by the thundering herd problem above

**Comment by Jason918** [comment]
There are several `LoadSheddingStrategy` can be configured, default is `org.apache.pulsar.broker.loadbalance.impl.OverloadShedder`, which will select one namespace bundle at a time for shedding. 
Also you can always try to define your own LoadSheddingStrategy or do it manually with `admin.namespaces().unloadNamespaceBundle(...)`.

**Comment by Jason918** [comment]
@sl1316  Close this issue for now. You can reopen this if you have further questions.
