### ISSUE TITLE
Pulsar IO support Clickhouse Load Balance

### ISSUE THREAD

**Issue by huzk8** [apache/pulsar#12998]
**Describe the solution you'd like**
 Pulsar IO support Clickhouse Load Balance.

**Comment by nlu90** [comment]
@huzk8 could you provide some more details regarding `clickhouse load balance`? Any doc or link could be helpful

**Comment by huzk8** [comment]
> 

use `BalancedClickhouseDataSource` to get clickhouse connection.
example: `jdbc:clickhouse://host1:port1;host2:port2;host3:port3`

**Comment by tisonkun** [comment]
Pending to implement with a version bump to 0.3.3 https://github.com/ClickHouse/clickhouse-jdbc/issues/894.

**Comment by tisonkun** [comment]
It turns out that 0.3.2-patch11, which supports this feature, has been released under the group `com.clickhouse`.

FYI #18774

**Comment by tisonkun** [comment]
@huzk8 may you test whether #18774 meets your requirement?
