### ISSUE TITLE
Expose backlogSize for the topic stats and prometheus metrics

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#12991]
**Is your enhancement request related to a problem? Please describe.**

Currently, we are able to get the backlog size of the topic by using `bin/pulsar-admin topics stats`, but we are not exposing the backlog size to the Prometheus metrics. The backlog size is very important for users to monitor the data deletion, the large backlog size will lead to the topic data will not being deleted. So it will very helpful for exposing the backlog size through the Prometheus endpoint so that users can add an alert very conveniently.

Now, we have `pulsar_storage_backlog_size` which is aggregated at the namespace level, we should expose it to the topic level if the topic level metrics is enabled, and if the topic level metrics is enabled, we should not expose the namespace level `pulsar_storage_backlog_size` again to keep consistent with the Prometheus format.

**Comment by Jason918** [comment]
I can work on it.

**Comment by codelipenghui** [comment]
Close the issue since we already have `pulsar_storage_backlog_size` for topics.
