### ISSUE TITLE
pulsar-io-elasticsearch-sink support rolling create index

### ISSUE THREAD

**Issue by ignacioli** [apache/pulsar#13019]
**Background describe**
Current [elasticsearch-sink](https://pulsar.apache.org/docs/en/io-elasticsearch-sink/#configuration) has a solid([code here](https://github.com/apache/pulsar/blob/master/pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java#L61)) `indexName` configuration, which is inflexible, we must specific the index name accurately when creating the  elasticsearch-sink.
```bash
$ bin/pulsar-admin sinks create \
    --tenant public \
    --namespace default \
    --name elasticsearch-test-sink \
    --sink-config-file elasticsearch-sink.yml \
    --inputs elasticsearch_test
$ cat elasticsearch-sink.yml 
configs:
    elasticSearchUrl: "http://localhost:9200"
    indexName: "my_index"
    typeName: "doc"
    username: "scooby"
    password: "doobie"
```

**Enhancement request**
Request to support  rolling create index configuration like following:
```bash
$ cat elasticsearch-sink.yml 
configs:
    elasticSearchUrl: "http://localhost:9200"
    indexName: "my_index-%Y-%m-%d"
    typeName: "doc"
    username: "scooby"
    password: "doobie"
```
key feature: 
`indexName: "my_index-%Y-%m-%d"`, which is a common use of elasticsearch client.

**PS**: The indexName combined with $PREFIX plus $DATE is enough, like: "$PREFIX-%Y-%m-%d", no regular expression or wildcard is wanted.

**Comment by mattisonchao** [comment]
i can work on it :)

**Comment by fantapsody** [comment]
Hi @mattisonchao , any updates on this?
