### ISSUE TITLE
[Bug] Topic Lookup on non-existent topics unexpected response.

### ISSUE THREAD

**Issue by ronfarkash** [apache/pulsar#13028]
**Describe the bug**
When using the Rest API to look up a topic
http://{broker}/lookup/v2/topic/persistent/{tenant}/{namespace}/{topic}
**on a topic that does not exist**, two things can happen:
1. I receive a redirect (307) to another broker 
2. I receive a response (200) containing a broker

**To Reproduce**
1. Setup a normal cluster, BookKeeper/ZooKeeper/Configuration Store/2+ Brokers
2. Look for a topic that does not exist using http://{broker}/lookup/v2/topic/persistent/{tenant}/{namespace}/{topic}
3. See a response as if the topic exists.

**Expected behavior**
I expect to receive 404 Topic not found.

**Desktop (please complete the following information):**
 - OS: Linux (KDE Neon 5.21 User Edition)

**Additional Context**
To my understanding when performing Rest API requests for topics/namespaces (anything related to ownership) the broker will first check if it owns the object you were referring to, else it will return a redirect (307) to the broker who owns the topic.
In this case the Topic does not exist, therefore I should not get a 200 with a broker name, I should instead get 404 not found.

**Comment by aloyszhang** [comment]
I can help with this problem.

**Comment by ronfarkash** [comment]
> I can help with this problem. @ronfarkash Can you provide which verison of pulsar you used ?

2.8.1
