### ISSUE TITLE
RateLimiterTest is flaky

### ISSUE THREAD

**Issue by mgodave** [apache/pulsar#1303]
Most likely due to a hard coded ScheduledExecutorService in RateLimiter.

**Comment by sijie** [comment]
@mgodave how often do you see this happen and what type of machine you are running the tests?

**Comment by mgodave** [comment]
It's been awhile. Let me rerun and let you know.

**Comment by mgodave** [comment]
I'm looking through the Guava code and documentation to understand if the analysis in Pulsar's implementation is indeed accurate.

**Comment by sijie** [comment]
thank you @mgodave . will take a look at this.

**Comment by sijie** [comment]
close this issue for now. If the test fails again, please reopen the issue again.
