### ISSUE TITLE
Operation failed on schema upload to a topic while configuring a jdbc sink 

### ISSUE THREAD

**Issue by pgandhap** [apache/pulsar#13046]
Getting an error while running command to upload a schema to a topic . 

I got an error like below :

![schema-upload](https://user-images.githubusercontent.com/71866730/144030011-244defa8-d04e-4a49-85ee-f3899ead8a7f.PNG)

avro-schema file :
-------------------
{
    "type": "JSON",
    "schema": "{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"com.foo\",\"fields\":[{\"name\":\"file1\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"file2\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"file3\",\"type\":[\"null\",\"string\"],\"default\":null}]}",
    "properties": {}
}

Below are the logs for pulsar-standalone :
----------------------------------------------
5] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [30/Nov/2021:10:20:38 +0000] "POST /admin/v2/schemas/public/default/my-topic/schema HTTP/1.1" 409 226 "-" "Pulsar-Java-v2.8.1" 108

10:20:48.240 [pulsar-web-63-15] INFO  org.eclipse.jetty.server.RequestLog - 172.17.0.4 - - [30/Nov/2021:10:20:48 +0000] "GET /admin/v2/clusters HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" 3

10:20:48.264 [pulsar-web-63-3] INFO  org.eclipse.jetty.server.RequestLog - 172.17.0.4 - - [30/Nov/2021:10:20:48 +0000] "GET /admin/v2/clusters/standalone/failureDomains HTTP/1.1" 200 2 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" 4

10:20:48.298 [pulsar-web-63-9] INFO  org.eclipse.jetty.server.RequestLog - 172.17.0.4 - - [30/Nov/2021:10:20:48 +0000] "GET /admin/v2/brokers/standalone HTTP/1.1" 200 18 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" 2

10:20:48.324 [pulsar-web-63-6] INFO  org.eclipse.jetty.server.RequestLog - 172.17.0.4 - - [30/Nov/2021:10:20:48 +0000] "GET /admin/v2/clusters/standalone HTTP/1.1" 200 230 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" 2

10:20:49.085 [pulsar-web-63-12] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [30/Nov/2021:10:20:49 +0000] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false&subscriptionBacklogSize=false HTTP/1.1" 200 1981 "-" "Pulsar-Java-v2.8.1" 3

10:20:49.092 [pulsar-web-63-7] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [30/Nov/2021:10:20:49 +0000] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false&subscriptionBacklogSize=false HTTP/1.1" 200 1981 "-" "Pulsar-Java-v2.8.1" 3

10:20:58.125 [pulsar-web-63-14] INFO  org.eclipse.jetty.server.RequestLog - 172.17.0.4 - - [30/Nov/2021:10:20:58 +0000] "GET /admin/v2/clusters HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" 3

10:20:58.244 [pulsar-web-63-11] INFO  org.eclipse.jetty.server.RequestLog - 172.17.0.4 - - [30/Nov/2021:10:20:58 +0000] "GET /admin/v2/clusters/standalone HTTP/1.1" 200 230 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" 6

10:20:58.374 [pulsar-web-63-5] INFO  org.eclipse.jetty.server.RequestLog - 172.17.0.4 - - [30/Nov/2021:10:20:58 +0000] "GET /admin/v2/clusters HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" 2

10:20:58.473 [pulsar-web-63-13] INFO  org.eclipse.jetty.server.RequestLog - 172.17.0.4 - - [30/Nov/2021:10:20:58 +0000] "GET /admin/v2/clusters/standalone HTTP/1.1" 200 230 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" 4

10:21:18.474 [pulsar-web-63-16] INFO  org.eclipse.jetty.server.RequestLog - 172.17.0.4 - - [30/Nov/2021:10:21:18 +0000] "GET /admin/v2/clusters HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" 2

10:21:18.487 [pulsar-web-63-1] INFO  org.eclipse.jetty.server.RequestLog - 172.17.0.4 - - [30/Nov/2021:10:21:18 +0000] "GET /admin/v2/clusters/standalone/failureDomains HTTP/1.1" 200 2 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" 3

10:21:18.500 [pulsar-web-63-2] INFO  org.eclipse.jetty.server.RequestLog - 172.17.0.4 - - [30/Nov/2021:10:21:18 +0000] "GET /admin/v2/brokers/standalone HTTP/1.1" 200 18 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" 4

10:21:18.512 [pulsar-web-63-4] INFO  org.eclipse.jetty.server.RequestLog - 172.17.0.4 - - [30/Nov/2021:10:21:18 +0000] "GET /admin/v2/clusters/standalone HTTP/1.1" 200 230 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" 4

10:21:19.103 [pulsar-web-63-8] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [30/Nov/2021:10:21:19 +0000] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false&subscriptionBacklogSize=false HTTP/1.1" 200 1981 "-" "Pulsar-Java-v2.8.1" 21

10:21:19.135 [pulsar-web-63-15] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [30/Nov/2021:10:21:19 +0000] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false&subscriptionBacklogSize=false HTTP/1.1" 200 1981 "-" "Pulsar-Java-v2.8.1" 3

10:21:46.087 [GarbageCollectorThread-11-1] INFO  org.apache.bookkeeper.bookie.EntryLogger - Failed to get ledgers map index from: 80.log : No ledgers map index found on entryLogId 80

10:21:46.089 [GarbageCollectorThread-11-1] INFO  org.apache.bookkeeper.bookie.GarbageCollectorThread - Extracting entry log meta from entryLogId: 82

10:21:46.091 [GarbageCollectorThread-11-1] INFO  org.apache.bookkeeper.bookie.EntryLogger - Failed to get ledgers map index from: 82.log : No ledgers map index found on entryLogId 82

10:21:46.092 [GarbageCollectorThread-11-1] INFO  org.apache.bookkeeper.bookie.GarbageCollectorThread - Extracting entry log meta from entryLogId: 86

10:21:46.094 [GarbageCollectorThread-11-1] INFO  org.apache.bookkeeper.bookie.EntryLogger - Failed to get ledgers map index from: 86.log : No ledgers map index found on entryLogId 86

270 [GarbageCollectorThread-11-1] INFO  org.apache.bookkeeper.bookie.EntryLogger - Failed to get ledgers map index from: 116.log : No ledgers map index found on entryLogId 116

10:21:46.271 [GarbageCollectorThread-11-1] INFO  org.apache.bookkeeper.bookie.GarbageCollectorThread - Extracting entry log meta from entryLogId: 117

10:21:46.273 [GarbageCollectorThread-11-1] INFO  org.apache.bookkeeper.bookie.EntryLogger - Failed to get ledgers map index from: 117.log : readerIndex(0) + length(4) exceeds writerIndex(0): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeNoCleanerDirectByteBuf(ridx: 0, widx: 0, cap: 1024)

10:21:48.548 [pulsar-web-63-9] INFO  org.eclipse.jetty.server.RequestLog - 172.17.0.4 - - [30/Nov/2021:10:21:48 +0000] "GET /admin/v2/clusters HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" 3

10:21:48.561 [pulsar-web-63-6] INFO  org.eclipse.jetty.server.RequestLog - 172.17.0.4 - - [30/Nov/2021:10:21:48 +0000] "GET /admin/v2/clusters/standalone/failureDomains HTTP/1.1" 200 2 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" 4

10:21:48.573 [pulsar-web-63-14] INFO  org.eclipse.jetty.server.RequestLog - 172.17.0.4 - - [30/Nov/2021:10:21:48 +0000] "GET /admin/v2/brokers/standalone HTTP/1.1" 200 18 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" 3

10:21:48.585 [pulsar-web-63-11] INFO  org.eclipse.jetty.server.RequestLog - 172.17.0.4 - - [30/Nov/2021:10:21:48 +0000] "GET /admin/v2/clusters/standalone HTTP/1.1" 200 230 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_212)" 4

10:21:49.087 [pulsar-web-63-5] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [30/Nov/2021:10:21:49 +0000] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false&subscriptionBacklogSize=false HTTP/1.1" 200 1981 "-" "Pulsar-Java-v2.8.1" 5

re.uniAcceptStage(CompletableFuture.java:731) ~[?:?]

Please help on the same . Thanks !!!

**Comment by mattisonchao** [comment]
@hangc0276 
i can work on it.

**Comment by hangc0276** [comment]
@mattisonchao Thanks for you help, I have assigned this issue to you.

**Comment by casuallc** [comment]
You can not change schema type of a topic.

Recreate topic and try again. :)

**Comment by mattisonchao** [comment]
Please see @casuallc answer. This issue will re-open when reproduced.
