### ISSUE TITLE
[Doc] add docs for configuring rack

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#13052]
Context:

Raghavender Mittapalli, Thu 10:17 PM, Edited
What is expected in the below scenario:
We started the publish with the below configuration.
bookie0-rackb0
bookie1-rackb1
bookie2-rackb1
bookie3-rackb2

And after some msgs are produced, killed the bookie3(rack b2). So in this scenario, all the ledgers that are in rackb2 while trying to rereplicate should have said not enough non-faulty bookies. But we have seen that there are no underreplicated ledgers. And the ledger meta data is showing the ledgers are part of booki0, bookie1, and bookie2.

Penghui Li, Thu 10:54 PM
Ok, will check more details.

Penghui Li, Mon 10:42 PM
@Raghavender Mittapalli I found the previous documentation for the bookie racks but looks does not contains the autorecovery part, we will verify the configuration and update the documentation today or tomorrow https://docs.google.com/document/d/1B4DfrJsHMCP_FmG6eu3c-hKrTxpYXtqMpsWkQX7yMSk/edit#heading=h.i6uxuw75673z

Ankur Jain, Mon 11:13 PM
Not clear on how isolation groups are related to racks? We are not configuring any isolation group as of now and I was hoping that we don't have to because we want to go live soon and have limited time to check and test isolation groups.

Ankur Jain, Mon 11:17 PM
Auditor has this config auditorPeriodicPlacementPolicyCheckInterval What is this about and how is this different from regular underreplication check. Same goes for auditorReplicasCheckInterval

Penghui Li, Mon 11:20 PM
@Ankur Jain Have you set bookie affinity group for the namespace?

Penghui Li, Mon 11:24 PM
> And after some msgs are produced, killed the bookie3(rack b2). So in this scenario, all the ledgers that are in rackb2 while trying to rereplicate should have said not enough non-faulty bookies 

Just want to confirm here means the msgs are produced and write to rack b2 and then killed some bookie of the rack b2 then the data replicated to other bookies not of rack b2 right?

Ankur Jain, Mon 11:26 PM
Yes. In that test, there was only one bookie in rack b2. So when it was killed, we ended up in a situation with bookies of only 2 racks in the cluster (1 of rack b0 and 2 of rack b1)

Yet the ledgers completed replication

Penghui Li, Mon 11:29 PM
So the expected behavior from your side is if the data are written to rack b0, if rack b0 does not have any available bookies, the data should not replicate to rack b1 without any bookie affinity group configurations right?

Ankur Jain, Mon 11:35 PM, Edited
The expected behaviour is that a ledger should always be across three unique racks. So when a ledger is created it can go in rack (b0,b1,b2). Pulsar's placement policy ensures the correct spread initially.

When a bookie goes down (let say it was in rack b2), autorecovery would distribute its ledgers to other bookies. For these ledgers, any of these configuration is valid:
(b0,b1,b2) -> here ledger got replicated on another bookie of rack b2
(b0,b1,bx) where x != 0 and x != 1-> we are not specific that ledger has to go to another bookie of rack b2. It can go to some other rack too till that rack is not b0 or b1 to ensure that the ledger is always spread across three unique racks.

Following is not valid:
New ensemble for the ledger: (b0,b1,b1) or (b0,b1,b0) because at this point this ledger is violating the rack placement policy.

If the bookie failures are such that there are < 3 racks available, then we would want autorecovery to throw error just like pulsar broker does (not enough non faulty bookies available) rather than replicating in such a way that it violates 3 unique rack constraint.

Penghui Li, Mon 11:40 PM
Oh I see. Sorry looks we misunderstand the problem. It clear for now. Will create a ticket for tracking this issue and investigating the details soon

Penghui Li, Yesterday 12:12 AM
Because the rack information is stored in the zookeeper (bin/pulsar-admin bookies set-bookie-rack this one will write the rack data into the broker's local zk), so we need to use the ZkIsolatedBookieEnsemblePlacementPolicy for the ensemblePlacementPolicy in bookkeeper.conf. We are also working on the test and If you want to test if it can works, you can just update the configuration in bookkeeper.conf ensemblePlacementPolicy=org.apache.pulsar.zookeeper.ZkIsolatedBookieEnsemblePlacementPolicy

Raghavender Mittapalli, Yesterday 12:13 AM
ohh okay..we will also check this

Raghavender Mittapalli, Yesterday 12:40 AM
We are getting this error. We are using the 2.7.2.8

Penghui Li, Yesterday 12:43 AM
Let me check

Penghui Li, Yesterday 12:47 AM
How do you set the ensemblePlacementPolicy? I also tried 2.7.2.8, I can start the bookies successfully

Raghavender Mittapalli, Yesterday 12:50 AM
Using this PULSAR_PREFIX_ensemblePlacementPolicy: "ZkIsolatedBookieEnsemblePlacementPolicy" in bookkeeper-configmap and redeploying

Penghui Li, Yesterday 12:52 AM
It should be org.apache.pulsar.zookeeper.ZkIsolatedBookieEnsemblePlacementPolicy

Raghavender Mittapalli, Yesterday 12:52 AM
ohh okay.

Penghui Li, Yesterday 1:22 AM
@Raghavender Mittapalli I have tested it, I have create 2 racks "default    {127.0.0.1:3181=BookieInfo(rack=r0, hostname=null), 127.0.0.1:3281=BookieInfo(rack=r0, hostname=null), 127.0.0.1:3381=BookieInfo(rack=r1, hostname=null)}" and then set 3 replicas for the namespace and then produce messages, I got ledger metadata  LedgerMetadata{formatVersion=3, ensembleSize=3, writeQuorumSize=3, ackQuorumSize=3, state=OPEN, digestType=CRC32C, password=base64:, ensembles={0=[127.0.0.1:3281, 127.0.0.1:3381, 127.0.0.1:3181]}, customMetadata={component=base64:bWFuYWdlZC1sZWRnZXI=, pulsar/managed-ledger=base64:cHVibGljL2RlZmF1bHQvcGVyc2lzdGVudC95eXk=, application=base64:cHVsc2Fy}}, So the ZkIsolatedBookieEnsemblePlacementPolicy can't match the requirement.

I will check more details for how to achieve the purpose.

Penghui Li, Yesterday 3:20 AM
For the broker.conf, we need to set the bookkeeperClientMinNumRacksPerWriteQuorum=3 and bookkeeperClientEnforceMinNumRacksPerWriteQuorum=true. For the bookkeeper.conf, we need to set the minNumRacksPerWriteQuorum=3 and enforceMinNumRacksPerWriteQuorum=true and reppDnsResolverClass=org.apache.pulsar.zookeeper.ZkBookieRackAffinityMapping, after that I think it should works for the above case.

Penghui Li, Yesterday 3:39 AM
10:37:20.724 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.client.LedgerRecoveryOp - Failure NotEnoughBookiesException: Not enough non-faulty bookies available while writing entry: 1 while recovering ledger: 41
10:37:20.724 [PendingReplicationTimer] ERROR org.apache.bookkeeper.replication.ReplicationWorker - BKException while fencing the ledger 41 for rereplication of postponed ledgers

LedgerMetadata{formatVersion=3, ensembleSize=3, writeQuorumSize=3, ackQuorumSize=3, state=IN_RECOVERY, digestType=CRC32C, password=base64:, ensembles={0=[backuprestore-pulsar-bookie-5.backuprestore-pulsar-bookie.backuprestore.svc.cluster.local:3181, backuprestore-pulsar-bookie-6.backuprestore-pulsar-bookie.backuprestore.svc.cluster.local:3181, backuprestore-pulsar-bookie-7.backuprestore-pulsar-bookie.backuprestore.svc.cluster.local:3181]}, customMetadata={pulsar/managed-ledger=base64:cHVibGljL2RlZmF1bHQvcGVyc2lzdGVudC96eGM=, component=base64:bWFuYWdlZC1sZWRnZXI=, application=base64:cHVsc2Fy}}

I have scale down bookie-7 and I have only bookie 7 in rack7 and bookie-6 in rack-6, bookie-5 in rack-5, other bookies does not in any racks, so the replication failed.

@Raghavender Mittapalli @Ankur Jain

Ankur Jain, Yesterday 4:25 AM
and what ensemble policy to use?

the default rackaware one or the zkisolated one that you mentioned

Raghavender Mittapalli, Yesterday 5:33 AM
Could you share the Bookkeeper config file for the reference

Penghui Li, Yesterday 6:45 AM
@Ankur Jain The default rackaware policy

Penghui Li, Yesterday 6:49 AM
@Raghavender Mittapalli I just add these configs in the configmap, others are default value

Raghavender Mittapalli, 4:55 AM
This is working as expected after the suggested changes. Closing this

Ankur Jain, 5:19 AM
@Penghui Li can you update pulsar documentation around this since this is a common use-case for anyone configuring rack awareness?

and these steps are not obvious

![image](https://user-images.githubusercontent.com/50226895/144037196-67168c4d-fccf-4116-ad38-8eef047fa6cb.png)

**Comment by Anonymitaet** [comment]
Hi @momo-jun could you please help resolve this doc issue? Thanks

References:
- https://pulsar.apache.org/docs/en/next/administration-isolation/ 
- https://streamnative.io/blog/tech/2021-03-02-taking-an-in-depth-look-at-how-to-achieve-isolation-in-pulsar/
- https://streamnative.io/blog/tech/2021-06-03-pulsar-isolation-for-dummies-separate-pulsar-clusters/

**Comment by momo-jun** [comment]
Checked with @hangc0276 , we'd like to add a new section for the concepts/procedures of data replacement policy to enhance the Isolation feature. 
ETA: middle of April.
