### ISSUE TITLE
Provide Docker Image for Pulsar 2.9.0

### ISSUE THREAD

**Issue by oscerd** [apache/pulsar#13056]
**Describe the bug**
Just noticed Pulsar 2.9.0 has been released but the related docker image doesn't.

This is probably more a task than a bug, but just wanted to report it.

**Comment by eolivelli** [comment]
Hello,
I am the release manager for Pulsar 2.9.0.

I am still in the middle of the "release" procedure.
We still miss some other pieces, like the website update.

https://github.com/apache/pulsar/wiki/Release-process

We will announce the release when everything will be done, just stay tuned

**Comment by oscerd** [comment]
Thanks, sorry for the noise, I thought the release was completed and there was just the image missing.

**Comment by eolivelli** [comment]
The image should be available now.

Please note that we found a regression in 2.9 after closing the VOTE.
You can use 2.9 for testing the new features but I would wait 2.9.1 (that will come soon, in a couple of weeks) before going to production with the update
