### ISSUE TITLE
[Doc] add explanations for function (autoack and nack)

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#13051]
This is something we need to improve in Pulsar Functions documentation.:

It is an inconsistent behavior that resulted from using autoAck and manual nack . 

In Pulsar Functions, if you want to control the ack behavior, people should disable autoAck and call record.ack() / record.fail() explicitly. 

If you want to let Pulsar control the acknowledge behavior, people should enable autoAck and reply on the throwing exception to fail/nack the message instead of using record.fail().

**Comment by momo-jun** [comment]
Checked with @freeznet - This issue has been fixed through #16279, which adds a new `MANUAL` semantic. It allows users to use `context.getCurrentRecord().ack()`/`context.getCurrentRecord().fail()` to manually control the ACK behavior.
