### ISSUE TITLE
What is the minimal cpu/memory request to run pulsar in production?

### ISSUE THREAD

**Issue by xiaofan-luan** [apache/pulsar#13078]
Please answer the following questions before submitting your doc issue. Thanks!

# What issue do you find in Pulsar docs?
In the document, it didn't mention what's the minimal memory requirement to run pulsar in high availability mode, and how we split memory into different node(zk,bookie,broker...)

# What is your suggestion?
offer a minimal setting list, such as 16c64g, and the minimal requirement for each component

# Do you have any references?

# Would you like to fix this issue?
Would like to, but we are also facing OOM issues, so help wanted~

**Comment by xiaofan-luan** [comment]
Any suggestion are welcomed, we are also an OSS project(Milvus the vector database) using pulsar as are message store. 
The write request is kind of large(few megabytes), and we are trying to setup a minimal usage requirement for our user. 3ks!

**Comment by hangc0276** [comment]
Please provide your max throughput and QPS, the requirements are depend on your throughput and QPS to support.

If you just want to test the pulsar, you can setup the pulsar on your laptop in standalone mode. That maybe the minimal usage requirement.

**Comment by xiaofan-luan** [comment]
> 

Hi there, we are targeting to production with high availability, the qps could be really small such as 10 MB/s, just want to know what is the smallest memory config for production, 3ks

**Comment by Anonymitaet** [comment]
@xiaofan-luan FYI:
![image](https://user-images.githubusercontent.com/50226895/145147049-14004b04-9007-4aad-b35e-0c18ba2a15ff.png)
![image](https://user-images.githubusercontent.com/50226895/145147072-80c0cad5-d4c6-4272-adac-e83bf29c416f.png)

I've added basic and recommended hardware settings to Pulsar doc in https://github.com/apache/pulsar/pull/13187, PTAL, thanks

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan FYI: ![image](https://user-images.githubusercontent.com/50226895/145147049-14004b04-9007-4aad-b35e-0c18ba2a15ff.png) ![image](https://user-images.githubusercontent.com/50226895/145147072-80c0cad5-d4c6-4272-adac-e83bf29c416f.png)
> 
> I've added basic and recommended hardware settings to Pulsar doc in #13187, PTAL, thanks

Nice！ thanks Anonymitaet , we will try to do some pressure test and see.
