### ISSUE TITLE
Go client keep receive close from broker 

### ISSUE THREAD

**Issue by xiaofan-luan** [apache/pulsar#13084]
**Describe the bug**
We've seen that go client keep receive closed info from broker, the log as following, is that correct behaviour?

time="2021-12-02T01:21:39Z" level=info msg="[Reconnected consumer to broker]" consumerID=8 name=dhnik subscription=by-dev-queryNode-13-429498844746874881-6545233210522002565 topic="persistent://public/default/by-dev-rootcoord-dml_5"
time="2021-12-02T01:21:39Z" level=info msg="[Connected consumer]" consumerID=9 name=cqkwv subscription=by-dev-queryNode-13-429498844746874881-4863815511074142649 topic="persistent://public/default/by-dev-search-0"
time="2021-12-02T01:21:39Z" level=info msg="[Created consumer]" consumerID=9 name=cqkwv subscription=by-dev-queryNode-13-429498844746874881-4863815511074142649 topic="persistent://public/default/by-dev-search-0"
time="2021-12-02T01:21:39Z" level=info msg="[Created producer]" cnx="10.26.55.44:41262 -> 10.27.241.73:6650" producerID=10 producer_name=milvus-pulsar-23-2723 topic="persistent://public/default/by-dev-searchResult-0"
time="2021-12-02T01:21:39Z" level=info msg="Broker notification of Closed consumer: 9" local_addr="10.26.55.44:41262" remote_addr="pulsar://milvus-pulsar-proxy:6650"
time="2021-12-02T01:21:39Z" level=info msg="[Reconnecting to broker in  105.683492ms]" consumerID=9 name=cqkwv subscription=by-dev-queryNode-13-429498844746874881-4863815511074142649 topic="persistent://public/default/by-dev-search-0"
time="2021-12-02T01:21:39Z" level=info msg="[Connected consumer]" consumerID=9 name=cqkwv subscription=by-dev-queryNode-13-429498844746874881-4863815511074142649 topic="persistent://public/default/by-dev-search-0"
time="2021-12-02T01:21:39Z" level=info msg="[Reconnected consumer to broker]" consumerID=9 name=cqkwv subscription=by-dev-queryNode-13-429498844746874881-4863815511074142649 topic="persistent://public/default/by-dev-search-0"
time="2021-12-02T02:15:58Z" level=info msg="[Created producer]" cnx="10.26.55.44:41262 -> 10.27.241.73:6650" producerID=11 producer_name=milvus-pulsar-23-2951 topic="persistent://public/default/query-node-time-tick-0"
time="2021-12-02T02:15:58Z" level=info msg="[Connected consumer]" consumerID=10 name=rxkxg subscription=by-dev-queryNode-13-429499676778823681-4290867280910344190 topic="persistent://public/default/by-dev-rootcoord-dml_7"
time="2021-12-02T02:15:58Z" level=info msg="[Created consumer]" consumerID=10 name=rxkxg subscription=by-dev-queryNode-13-429499676778823681-4290867280910344190 topic="persistent://public/default/by-dev-rootcoord-dml_7"
time="2021-12-02T02:15:58Z" level=info msg="Broker notification of Closed consumer: 10" local_addr="10.26.55.44:41262" remote_addr="pulsar://milvus-pulsar-proxy:6650"
time="2021-12-02T02:15:58Z" level=info msg="[Reconnecting to broker in  106.244662ms]" consumerID=10 name=rxkxg subscription=by-dev-queryNode-13-429499676778823681-4290867280910344190 topic="persistent://public/default/by-dev-rootcoord-dml_7"
time="2021-12-02T02:15:58Z" level=info msg="[Connected consumer]" consumerID=10 name=rxkxg subscription=by-dev-queryNode-13-429499676778823681-4290867280910344190 topic="persistent://public/default/by-dev-rootcoord-dml_7"
time="2021-12-02T02:15:58Z" level=info msg="[Reconnected consumer to broker]" consumerID=10 name=rxkxg subscription=by-dev-queryNode-13-429499676778823681-4290867280910344190 topic="persistent://public/default/by-dev-rootcoord-dml_7"
time="2021-12-02T02:15:58Z" level=info msg="[Created producer]" cnx="10.26.55.44:41262 -> 10.27.241.73:6650" producerID=12 producer_name=milvus-pulsar-23-2952 topic="persistent://public/default/query-node-time-tick-0"
time="2021-12-02T02:15:58Z" level=info msg="[Connected consumer]" consumerID=11 name=pdqni subscription=by-dev-queryNode-13-429499676778823681-5511517715403210568 topic="persistent://public/default/by-dev-rootcoord-dml_6"
time="2021-12-02T02:15:58Z" level=info msg="[Created consumer]" consumerID=11 name=pdqni subscription=by-dev-queryNode-13-429499676778823681-5511517715403210568 topic="persistent://public/default/by-dev-rootcoord-dml_6"
time="2021-12-02T02:15:58Z" level=info msg="Broker notification of Closed consumer: 11" local_addr="10.26.55.44:41262" remote_addr="pulsar://milvus-pulsar-proxy:6650"
time="2021-12-02T02:15:58Z" level=info msg="[Reconnecting to broker in  117.945466ms]" consumerID=11 name=pdqni subscription=by-dev-queryNode-13-429499676778823681-5511517715403210568 topic="persistent://public/default/by-dev-rootcoord-dml_6"
time="2021-12-02T02:15:59Z" level=info msg="[Connected consumer]" consumerID=11 name=pdqni subscription=by-dev-queryNode-13-429499676778823681-5511517715403210568 topic="persistent://public/default/by-dev-rootcoord-dml_6"
time="2021-12-02T02:15:59Z" level=info msg="[Reconnected consumer to broker]" consumerID=11 name=pdqni subscription=by-dev-queryNode-13-429499676778823681-5511517715403210568 topic="persistent://public/default/by-dev-rootcoord-dml_6"
time="2021-12-02T02:15:59Z" level=info msg="[Connected consumer]" consumerID=12 name=glqvr subscription=by-dev-queryNode-13-429499676778823681-169579361635081028 topic="persistent://public/default/by-dev-search-0"
time="2021-12-02T02:15:59Z" level=info msg="[Created consumer]" consumerID=12 name=glqvr subscription=by-dev-queryNode-13-429499676778823681-169579361635081028 topic="persistent://public/default/by-dev-search-0"

**To Reproduce**

**Expected behavior**
just wondering if that is the correct behavior, because we've seen the backlog is keep increasing

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
broker log is list below

**Comment by xiaofan-luan** [comment]
[milvus-pulsar-broker-58bc5db7cc-ws225.log.zip](https://github.com/apache/pulsar/files/7640518/milvus-pulsar-broker-58bc5db7cc-ws225.log.zip)

**Comment by hangc0276** [comment]
It looks like the consumer doing reconnecting to the broker. Does this logs keep appear?

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Go client has been permanently moved to https://github.com/apache/pulsar-client-go. If it's still relevant, please open an issue there.
