### ISSUE TITLE
pulsar with kop,run in standalone model cannot change zookeeper port 2181 to other port

### ISSUE THREAD

**Issue by WrathLi** [apache/pulsar#13083]
In my project, I run pulsar with kop plugin,and change the port 2181 to 12181.
Pulsar Version:2.8.1
Kop Version:2.8.1.23
This is my standalone.conf file.
![image](https://user-images.githubusercontent.com/3929247/144377450-eae6986b-aec4-4d33-8375-5f4a1b5501f5.png)

when I run the script 
`./bin/pulsar standalone` 
pulsar start failed. pulsar create a zookeeper client with port 2181 to connect to zookeeper,but the zookeeper has change port 2181 to 12181,so it failed.
here is the log file.
![image](https://user-images.githubusercontent.com/3929247/144375583-2dbfbdbe-5835-48a0-bdea-59889f2c5420.png)
![image](https://user-images.githubusercontent.com/3929247/144375660-de090f86-4009-4db9-8778-de367c557844.png)
finally,I located where the bug is.
In the method distributedlog-core -> BKNamespaceDriver -> initializeBookKeeperClients()
![image](https://user-images.githubusercontent.com/3929247/144376019-1cfb63cd-05c0-4154-bbef-d8dac84471cc.png)
bkdlConfig.getBkZkServersForWriter() always return the port 2181.

I replace "bkdlConfig.getBkZkServersForWriter()" with "getZKServersFromDLUri(namespace)" , and build a new distributedlog-core.jar replace the original lib. Then the pulsar finally work.

I hope Pulsar can fix this bug in the later version.

**Comment by BewareMyPower** [comment]
You can run following command without any code change or config change.

```bash
./bin/pulsar standalone --zookeeper-port 12181 -nss
```

The `-nss` option is to disable the stream storage, which is an unstable feature (distributed log as you mentioned in `dl`). It's not required if you started standalone without existing data.

But if your scenario is that you have already run KoP standalone with 2181 port before and want to modify the config, you have to add the `-nss` option.
