### ISSUE TITLE
Add a watchdog monitor to monitor and log long-running metadata-store callback tasks

### ISSUE THREAD

**Issue by bharanic-dev** [apache/pulsar#13129]
**Is your enhancement request related to a problem? Please describe.**
There can be instances when the metadata-store callback tasks take a very long time, sometimes even block forever (https://github.com/apache/pulsar/issues/12929). 

**Describe the solution you'd like**
When issues like the above happen in production environments, it is non-trivial to debug and figure out what the underlying issue is. It would be good to add some monitoring to monitor the callback tasks and log the stack trace if the callback is taking an inordinate amount of time.

**Comment by tisonkun** [comment]
Closed by #15155.
