### ISSUE TITLE
Consumer subscription type - behavior not working properly

### ISSUE THREAD

**Issue by thiagohernandes** [apache/pulsar#13154]
**Describe the bug**
I created a sample generic class to use in some anothers beans. However, the subscription type of a consumer haven't working correctly.

Below the images:

![01-connect](https://user-images.githubusercontent.com/2352110/144892586-56b0a2e5-8ba5-482d-8121-66036318adb2.png)
![02-producer-consumer](https://user-images.githubusercontent.com/2352110/144892592-5323784c-c6d9-45af-bdf5-0ee97dd7ab80.png)
![03-bean-consumer](https://user-images.githubusercontent.com/2352110/144892598-292836a5-1ee5-439a-8471-e8d5c6884d54.png)
![04-bean-config](https://user-images.githubusercontent.com/2352110/144895102-a405c0f6-02c1-4103-996b-4f8719b1d570.png)
![05-producer-scheduler](https://user-images.githubusercontent.com/2352110/144897993-c3c4b4f9-2fbd-4048-bc61-ac5d832abe26.png)

**To Reproduce**
1. Declare instance of the generic class;
2. Instantiate a producer method
3. Instantiate two consumers method

**Expected behavior**
Emit an error when trying to create the second consumer while a first consumer of subscription type "Exclusive" have been created.

**Occurred behavior**
Both consumers continued to receive messages persisted in the topic. I believe only the first, by the subscription type should receive the producer's messages.

**Desktop (please complete the following information):**
 - Linux, Java 11 - IDE Intellij Jetbrains

**Comment by mattisonchao** [comment]
i will work on it. :)

**Comment by Shoothzj** [comment]
You need use the same subscriptionName. The `SubscribeType` only works in the same subscritpionName

**Comment by thiagohernandes** [comment]
Did u simulate that? No make sense @Shoothzj the answer. Current posted example should emit an exception when the second consumer try to connect at the same topic.

**Comment by Shoothzj** [comment]
> Did u simulate that? No make sense @Shoothzj the answer. Current posted example `should` emit an exception when the second consumer try to connect at the same topic.

I didn't simulate that. You can try with same `subscriptionName`.  What's the reason for this `should`, did you see any doc for this behavior?

**Comment by thiagohernandes** [comment]
> > Did u simulate that? No make sense @Shoothzj the answer. Current posted example `should` emit an exception when the second consumer try to connect at the same topic.
> 
> I didn't simulate that. You can try with same `subscriptionName`. What's the reason for this `should`, did you see any doc for this behavior?

I saw the doc. No make sense i try to connect in the same topic with the same "subscriptionName". I believe and the docs show that in this case is a probably problem.
[Subscriptions Types](
https://pulsar.apache.org/docs/en/concepts-messaging/#subscriptions)

**Comment by thiagohernandes** [comment]
Make sense to connect in cases subscription type "shared". First one is "exclusive", and should block any others new connects.

**Comment by Shoothzj** [comment]
@thiagohernandes Currently, the "exclusive" only works on same `subscritpionName` :)

**Comment by Shoothzj** [comment]
> > @thiagohernandes Currently, the "exclusive" only works on same `subscritpionName` :)
> 
> Yes u're correctly!! But the behavior is wrong when a second, .. n.... consumers try to connect. Above example illustrate that.

I don't think so. If you want the exclusive behavior, you can use the same consumer name.

**Comment by thiagohernandes** [comment]
> > > @thiagohernandes Currently, the "exclusive" only works on same `subscritpionName` :)
> > 
> > 
> > Yes u're correctly!! But the behavior is wrong when a second, .. n.... consumers try to connect. Above example illustrate that.
> 
> I don't think so. If you want the exclusive behavior, you can use the same consumer name.

Why don't think? It's so easy to see that behavior on **exclusive** case. If it is exclusive type, **no more one can connect in that**. Shared, everyone can connect. Key based every configured subscriber. Failover the reserve instance keep waiting a fail.

**Comment by Shoothzj** [comment]
@Anonymitaet could you please help to see if the documentation is ambiguous, we can only exclusive on same `subscritpionName` :)

**Comment by Anonymitaet** [comment]
Hi @Shoothzj @thiagohernandes 

IMO, the doc has already pointed out that `If multiple consumers subscribe to a topic **using the same subscription**, an error occurs.`, this means only exclusive **on the same subscription name**, correct?

![image](https://user-images.githubusercontent.com/50226895/145965131-bfb8b841-596e-4130-a9e5-8556342e87da.png)

**Comment by Shoothzj** [comment]
> Hi @Shoothzj @thiagohernandes
> 
> IMO, the doc has already pointed out that `If multiple consumers subscribe to a topic **using the same subscription**, an error occurs.`, this means only exclusive **on the same subscription name**, correct?
> 
> ![image](https://user-images.githubusercontent.com/50226895/145965131-bfb8b841-596e-4130-a9e5-8556342e87da.png)

Thank you, that's clear :)

**Comment by thiagohernandes** [comment]
> Hi @Shoothzj @thiagohernandes
> 
> IMO, the doc has already pointed out that `If multiple consumers subscribe to a topic **using the same subscription**, an error occurs.`, this means only exclusive **on the same subscription name**, correct?
> 
> ![image](https://user-images.githubusercontent.com/50226895/145965131-bfb8b841-596e-4130-a9e5-8556342e87da.png)

@Anonymitaet That's nice! Thanks!
