### ISSUE TITLE
Python pulsar-client not available for Apple Silicon (M1)

### ISSUE THREAD

**Issue by krissetto** [apache/pulsar#13153]
**Describe the bug**
When trying to build a dockerized python application that has pulsar-client <2.8.0 & >= 2.7.1 as a dependency, the build always fails with
`ERROR: Could not find a version that satisfies the requirement pulsar-client`

**To Reproduce**
1. Create a dockerized python app with a pulsar-client dependency >= 2.7.1 in the requirements.txt file and a RUN command in the dockerfile to install them
2. Build container, pip will try to Install the dependencies
3. See error

**Expected behavior**
Dependency installs without issues

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1
 - Arch: ARM64 (Apple silicon)

**Comment by deadwind4** [comment]
I have the same problem.

**Comment by yaalsn** [comment]
Good news! Pulsar python client supports Arm64 now since 2.9.2.

**Comment by tisonkun** [comment]
Closed as fixed. I can install 2.10.1 on Apple M1.
