### ISSUE TITLE
Pulsar admin api golang client

### ISSUE THREAD

**Issue by sl1316** [apache/pulsar#13174]
**Is your feature request related to a problem? Please describe.**
we are looking into automating some maintenance work by calling pulsar admin api in a service(could call it autoscaling service) but pulsar only provide java client/website pages/rest api: https://pulsar.apache.org/docs/en/admin-api-overview/. we would like to use golang client if possible. 

**Describe the solution you'd like**
provide the golang client or at lease something like protobuf. 

**Describe alternatives you've considered**

**Additional context**

**Comment by codelipenghui** [comment]
@sl1316 Here is a go client admin tool for Pulsar https://github.com/streamnative/pulsarctl

**Comment by sl1316** [comment]
@codelipenghui it's a cli tool which operator runs manually. we would like to use the client like the consumer/producer client package which you can run your application on top of it programatically.

**Comment by tuteng** [comment]
> @codelipenghui it's a cli tool which operator runs manually. we would like to use the client like the consumer/producer client package which you can run your application on top of it programatically. 

https://github.com/apache/pulsar-client-go Maybe you need this

**Comment by sl1316** [comment]
@tuteng  this package only contains the producer/consumer apis but not the admin apis

**Comment by tuteng** [comment]
https://github.com/streamnative/pulsarctl/blob/master/docs/en/overview_of_pulsarctl.md#admin-api This sdk for admin api
https://github.com/apache/pulsar-client-go This sdk for consume and produce @sl1316

**Comment by sl1316** [comment]
@tuteng thank you! feel free to close the issue

**Comment by tisonkun** [comment]
Closed as answered.
