### ISSUE TITLE
[Pulsar 2.9.0] ZK callbacks are sometimes unresponsive

### ISSUE THREAD

**Issue by nodece** [apache/pulsar#13211]
**Describe the bug**

When I call the `pulsarctl topics compact test-compact-topic` command, which cannot get a response from the pulsar.

I check out this codebase, this [code](https://github.com/apache/pulsar/blob/master/pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java#L148) doesn't work when receiving the request from the pulsarctl, the `zkc.multi()` doesn't call the callback, I am not sure what happened, but the zk client is connected and active, and Pulsar will shutdown in about 30 seconds because the zk timeout.

This will be triggered when you operate on a non-exist topic.

**To Reproduce**
```
docker run -itd \
  -p 6650:6650 \
  -p 8080:8080 \
 --name pulsar-2.9 \
  apachepulsar/pulsar:2.9.0 \
  bin/pulsar standalone

# Pulsar will stop working after execute this command.
pulsarctl topics compact test-compact-topic

# Check the Pulsar service.
docker ps | grep pulsar-2.9
```

**Expected behavior**

It is working.

**Comment by nodece** [comment]
I will work on this.

**Comment by codelipenghui** [comment]
@nodece Can you share the jstack? looks like a deadlock in the zk callback process?
