### ISSUE TITLE
 Only 0 bookies are live since 1629 seconds elapsed, wait for another 1 bookies for another 1 second

### ISSUE THREAD

**Issue by Dulingxiao** [apache/pulsar#13228]
log keep hitting

03:48:26.020 [LedgerDirsMonitorThread] WARN  org.apache.bookkeeper.bookie.LedgerDirsMonitor - LedgerDirsMonitor check process: All ledger directories are non writable
03:48:26.020 [LedgerDirsMonitorThread] INFO  org.apache.bookkeeper.bookie.BookieStateManager - Disable high priority writes on readonly bookie.
03:48:26.021 [LedgerDirsMonitorThread] ERROR org.apache.bookkeeper.util.DiskChecker - Space left on device data/standalone/bookkeeper0/current : 254738432, Used space fraction: 0.993955 > threshold 0.99.
03:48:26.859 [main] INFO  org.apache.bookkeeper.stream.server.service.BookieWatchService - Only 0 bookies are live since 1629 seconds elapsed, wait for another 1 bookies for another 1 second
03:48:27.860 [main] INFO  org.apache.bookkeeper.stream.server.service.BookieWatchService - Only 0 bookies are live since 1630 seconds elapsed, wait for another 1 bookies for another 1 second
03:48:28.861 [main] INFO  org.apache.bookkeeper.stream.server.service.BookieWatchService - Only 0 bookies are live since 1631 seconds elapsed, wait for another 1 bookies for another 1 second
03:48:29.862 [main] INFO  org.apache.bookkeeper.stream.server.service.BookieWatchService - Only 0 bookies are live since 1632 seconds elapsed, wait for another 1 bookies for another 1 second

startup script
docker run -it -p 6650:6650  -p 8180:8080 -d  apachepulsar/pulsar:2.8.1 bin/pulsar standalone

**Comment by hangc0276** [comment]
The reason is you have no available bookies, and the starter waiting for new writeable bookies.
