### ISSUE TITLE
PIP 45: Update zookeeperServers to metadataStoreUrl

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#13229]
As discussed with @codelipenghui, https://github.com/apache/pulsar/pull/13077 changes `zookeeperServers` to `metadataStoreUrl`.

Consequently, the flag `zookeeperServers` of `pulsar-perf managed-ledger` should be changed to `metadataStoreUrl`. Code files should be updated.

https://pulsar.apache.org/tools/pulsar-perf/2.10.0-SNAPSHOT/#managed-ledger

![image](https://user-images.githubusercontent.com/50226895/145517533-26d7cb29-e95a-4941-aadc-6b252ec5ef55.png)

Any one would like to contribute? Thanks

**Comment by liangyuanpeng** [comment]
Thanks for your confirmation, i will update for it.

**Comment by liangyuanpeng** [comment]
https://github.com/apache/pulsar/pull/13777 resolved this issue.

**Comment by Anonymitaet** [comment]
Thanks @liangyuanpeng
