### ISSUE TITLE
Submitting a community blog for Pulsar's 10k+ Github stars milestone

### ISSUE THREAD

**Issue by alicebi-streamnative** [apache/pulsar#13220]
Please answer the following questions before submitting your doc issue. Thanks!

# What issue do you find in Pulsar docs?

I would like to post a community blog for Pulsar's 10k+ Github stars milestone.

# What is your suggestion?
I would like to post a blog to the apache-pulsar.org site

# Do you have any references?
[Apache Pulsar hits 10,000 GitHub stars. .md](https://github.com/apache/pulsar/files/7687046/Apache.Pulsar.hits.10.000.GitHub.stars.md)
https://streamnative.io/blog/community/2021-12-07-pulsar-hits-10000-github-stars-milestone/
(For example, website links, etc)?

# Would you like to fix this issue?
Yes
(Welcome to contribute docs! Pulsar grows from a tiny seed to a big tree with every little effort by us! Your contribution is the sunlight, water, and air!)

**Comment by tisonkun** [comment]
Closed as stale. Feel free to just submit a patch to https://github.com/apache/pulsar-site/tree/main/site2/website-next/blog
