### ISSUE TITLE
Deploy function worker in a separate kubernetes

### ISSUE THREAD

**Issue by sl1316** [apache/pulsar#13227]
Please answer the following questions before submitting your doc issue. Thanks!

# What issue do you find in Pulsar docs?
we are looking into deploy the connector in a separate kubernetes cluster to achieve resource isolation. from the document for setting up the function worker, https://pulsar.apache.org/docs/en/functions-worker/#run-functions-worker-separately, the process mentioned in the section seems to be applied for vm/physical machines. for example,
1. it asks for workerHostname/port etc. what should I put here for a kubernetes cluster
2. what image should i use for the connector only? I checked the pulsar repository and it looks like the connectors are bundles with pulsar service in the same one but not sure if the image bundles all in one.
3. how can i upload the connector config files? say if i only need to bootstrap kafka connector.

also this section compares the Run-with-Broker and Run-separately modes. One interesting thing it mentions for Run-with-Broker mode, here i quote : "if you configure the functions-worker to run functions on Kubernetes (where the resource isolation problem is addressed by Kubernetes)."
could you provide more detail? if the functions worker run with the broker in a pod, they will impact each others right? not sure how the resource isolation problem is addressed by kubernetes here and it would be good to add some explanation

# What is your suggestion?
add steps for setting up connectors in a separate kubernetes clusters

# Do you have any references?
https://pulsar.apache.org/docs/en/functions-worker/#run-functions-worker-separately

# Would you like to fix this issue?

(Welcome to contribute docs! Pulsar grows from a tiny seed to a big tree with every little effort by us! Your contribution is the sunlight, water, and air!)

**Comment by momo-jun** [comment]
Check with @freeznet - It is unavailable in the Pulsar helm charts yet.

**Comment by momo-jun** [comment]
Close the issue at this moment since there is no plan for it yet.
