### ISSUE TITLE
PIP 113: Update Pulsar Website Design & Content

### ISSUE THREAD

**Issue by loganloganlogan** [apache/pulsar#13235]
## Motivation and Goal
Several ML threads indicated that the Pulsar site underrepresented the technology and community. Our goal is to make the Pulsar website the premier destination for end users and current/prospective community members with a holistic update to the design and content -- get a full picture of Pulsar in one place.

## Implementation
The community has voted on a new design for the Pulsar website. ML thread:  https://lists.apache.org/thread/xshx8hf5b2lhq1jlld4zjlww6nwjt61t 

The chosen design is viewable here: https://www.dropbox.com/sh/rwvnb36g7zmxptz/AAAIKHqfkWD6OwdY-OSG7Ovoa?dl=0 

Front-end design and content updates will be implemented in collaboration with the back-end work on PIP 87 (upgrading the website framework Docusauraus): https://github.com/apache/pulsar/wiki/PIP-87%3A-Upgrade-Pulsar-Website-Framework-%28Docusaurus%29

* Homepage template design/dev - Estimated Completion Date 12/23/2021  
* Landing page template design/dev -  Estimated Completion Date 1/7/2022
* General page template design/dev - Estimated Completion Date 1/7/2022
* Library page template design/dev - Estimated Completion Date 1/7/2023
* Events page template design/dev - Estimated Completion Date 1/14/2022
* Blog landing template design/dev - Estimated Completion Date 1/14/2022
* Blog detail template design/dev - Estimated Completion Date 1/21/2022
* Docs skin template design/dev - Estimated Completion Date 1/21/2022
* Front-end development for all templates
* Ensure ASF compliance
* Quality assurance
* Launch

We will also be providing recommended content updates to fit the new layout here:
https://docs.google.com/document/d/1rcmTcAGrf6lrDMHf_SRwD4xQp8mZddSoFjkgwc3OO6M/edit 

## Reject Alternatives
Four designs were presented to the community for a vote; the one with the most votes was chosen.

**Comment by loganloganlogan** [comment]
The website redesign project is almost complete. We have been attending weekly calls on Tuesdays at 4pm PT for the past 3 weeks to coordinate efforts with the docs contributors. We started a #website channel on Slack for real-time collaboration. 

A staging environment was created (https://github.com/apache/pulsar/pull/13855). Before we can submit the design to commit, we are waiting for a resolution on an issue we raised last week regarding duplicative design work being created on PIP 87 that broke @Paul-TT's updates; being discussed on #website. 

Updates:
- Design/dev: All pages are done — we’re making final refinements to copy and design/dev this week.
- Content: We shared updated content for the case studies and ecosystem pages on #dev Slack last week for input. Our approach was to only include those we could source on the web to ensure we don't run afoul of logo permissions issues and to be in compliance with ASF. There are several “powered by” logos on the current site we couldn’t find case studies for — if anyone has links to those, [please add to this doc](https://docs.google.com/spreadsheets/d/1Kk6jwhYoDXGVR7Y3HSzx_pian4qFqQqNVH3WhPQmWwI/edit#gid=1962619808).
- Ecosystem: That doc also includes a tab for adapters, connectors, and third-party ecosystem items that work with Pulsar. Suggestions and amendments greatly appreciated. Once the site is up, additional items can be added via a pull request.

Once people are back from holiday next week or the week after, we anticipate being able to submit the request to go live shortly thereafter.

**Comment by loganloganlogan** [comment]
From our weekly website call, we are close to launch.

Next steps:
- Submitting to website-next repo 
- Li Li to resolve changes that were conflicting w/ local build
- Constantia team to do final site QA/proof in staging environment
- Group to make any final modifications
- Li Li to merge and update new site

**Comment by loganloganlogan** [comment]
Final steps toward launch summarized [here](https://docs.google.com/document/d/1KDGHyr7dr_vKM9fILWfoNa3hAu7rjtShDkPJ2TPc4hE/edit#) under March 8 Meeting.

Next steps:
- Paul’s current PR approved by Yu (w/ any changes)
- Everyone will review updated staging site; Yu to send form/request to user community (survey, keep it time bound)
- In tandem Paul will work on next round of updates (above)
- Paul will incorporate any final updates from team + users and submit PR
- Final review by team ([checklist](https://docs.google.com/document/d/1IV35SI_F8G8cL-Vuzknc6RTGLK9_edRMpZpnrHvAWNs/edit#heading=h.2yfi0ld4ykmh)) and go live

**Comment by tisonkun** [comment]
Closed as delivered. The new website is online.
