### ISSUE TITLE
delayed message other than delivered right away

### ISSUE THREAD

**Issue by DongbinNie** [apache/pulsar#133]
Delayed message, it's better to can have different delayed time for subscriptions on the same topic.

[merlimat]
This one is interesting. I'd like to see how is feasible to do it in a highly scalable way. Perhaps this might be a good candidate to be implemented as a recipe (a ready-made solution built on top of the client library), rather than directly in the server.

[DongbinNie]
Agree, it can be implemented in the client side to alleviate server's burden.

**Comment by merlimat** [comment]
Other than just delaying the message delivery, I think we could also provide a more general use distributed event scheduler, that can be implemented with multiple cascading queues.

**Comment by DongbinNie** [comment]
@merlimat could you please give a detailed description of the solution "multiple cascading queues", thanks.

**Comment by XiaoZYang** [comment]
Cool, that sounds interesting !

**Comment by ivankelly** [comment]
@merlimat did anything ever happen with this?

**Comment by ivankelly** [comment]
Closing as duplicate of #2375
