### ISSUE TITLE
Wheel for pulsar-client 2.8.1, Python 3.9 and OS X x86_64 is missing

### ISSUE THREAD

**Issue by sarimak** [apache/pulsar#13334]
**Describe the bug**

**To Reproduce**
1. Go to https://pypi.org/project/pulsar-client/2.8.1/#files
2. Wheel for pulsar-client 2.8.1, CPython 3.9 and OS X 11 on x86_64 is not available
(but wheel for pulsar-client 2.8.1, CPython 3.9 and OS X 11 on arm64 (M1) is available)

**Expected behavior**
Intel HW on OS X is supported for all combinations of pulsar-client + OS X versions whenever Apple Silicon is also supported.

**Additional context**
Linux wheels are also missing for pulsar-client 2.8.1 and CPython 3.9. But it is possible to build them in Docker on my own by backporting the build script from master to tag v2.8.1. Building for OS X 10.14 could be possible using the provided Vagrant box but there is no Vagrant box for OS X 11, see https://app.vagrantup.com/apachepulsar. Perhaps publishing a reproducible procedure which was already used for building the offical wheel for M1 could allow users to self-build the missing packages until the full version matrix will be covered (or source distributions will be avalaible).

**Comment by tisonkun** [comment]
Closed as stale. The development of the Python client has been permanently moved to http://github.com/apache/pulsar-client-python. Please open an issue there if it's still relevant.
