### ISSUE TITLE
[Blog] 2.9.0 announcement blog 

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#13338]
Hi @eolivelli 

Thanks for creating 2.9.0 release notes https://github.com/apache/pulsar/pull/12425 
(P.S. there are still some issues in this release note, for example, many inconsistencies). 

Just a soft reminder: since you are the 2.9.0 release manager, please do not forget to create the 2.9.0 announcement blog, thanks.
Example: https://pulsar.apache.org/blog/2021/09/23/Apache-Pulsar-2-8-1/

**Comment by tisonkun** [comment]
Closed as won't do. IIRC we intentionally lower this version :)
