### ISSUE TITLE
PIP-122: Change loadBalancer default loadSheddingStrategy to ThresholdShedder

### ISSUE THREAD

**Issue by hangc0276** [apache/pulsar#13340]
### Motivation
The ThresholdShedder load balance policy since Pulsar 2.6.0 by https://github.com/apache/pulsar/pull/6772. It can resolve many load balance issues of `OverloadShedder` and works well in many Pulsar production clusters.

In Pulsar 2.6.0, 2.7.0, 2.8.0 and 2.9.0, Pulsar's default load balance policy is `OverloadShedder`.

I think it's a good time for 2.10 to change default load balance policy to `ThresholdShedder`, it will make throughput more balance between brokers.

### Proposed Changes
In 2.10 release，for `broker.conf`, change `loadBalancerLoadSheddingStrategy` from `org.apache.pulsar.broker.loadbalance.impl.OverloadShedder` to `org.apache.pulsar.broker.loadbalance.impl.ThresholdShedder`

**Comment by rdhabalia** [comment]
this is not backward compatible change and one usecase can't make decision, this will impact existing users.

**Comment by Jason918** [comment]
> this is not backward compatible change

Hi @rdhabalia 
Any specific compatible issue for this change?

**Comment by hangc0276** [comment]
@rdhabalia The two load balance policy are has no state, and users can switch between them at any time. IMO, there is no incompatible issue for this change. Do you have any case for the compatible issue?
