### ISSUE TITLE
[Doc] Pulsar Client Libraries Page has a Dead Link

### ISSUE THREAD

**Issue by dave2wave** [apache/pulsar#13414]
### What issue do you find in Pulsar docs?

The link in the section [here](https://pulsar.apache.org/docs/en/client-libraries/#feature-matrix) refers to a wiki page which is missing.

Instead the information is in a [Google](https://docs.google.com/spreadsheets/d/1YHYTkIXR8-Ql103u-IMI18TXLlGStK8uJjDsOOA0T20/edit#gid=1784579914) doc which is not editable by any committer through a PR nor is it describing the status for historical releases.

### What is your suggestion?

Please convert the google doc to either a markdown or wiki page.

### Do you have any references?

They are in the first question, but I will repeat:

1. https://pulsar.apache.org/docs/en/client-libraries/#feature-matrix
2. https://docs.google.com/spreadsheets/d/1YHYTkIXR8-Ql103u-IMI18TXLlGStK8uJjDsOOA0T20/edit#gid=1784579914

### Would you like to fix this issue?

No, those PMC members who have kept this information in google docs need to fix this.

### Note

- [X] I have made some research on my question and I need help on docs.

**Comment by Anonymitaet** [comment]
1. fixes the invalid URL issue.
2. [The google doc](https://docs.google.com/spreadsheets/d/1YHYTkIXR8-Ql103u-IMI18TXLlGStK8uJjDsOOA0T20/edit#gid=1784579914) can be editable by some committers and the content in that doc is appropriate for `master`.
3. As you can see from [the google doc](https://docs.google.com/spreadsheets/d/1YHYTkIXR8-Ql103u-IMI18TXLlGStK8uJjDsOOA0T20/edit#gid=1784579914), the structure is complicated with many contents, it is inconvenient to handle them in markdown or wiki page. Besides, it is easier to coordinate with others (e.g., make comments) in google doc .
