### ISSUE TITLE
[pulsar-cpp-client] Consumer should be able to read messages in batch

### ISSUE THREAD

**Issue by lalit-g-deepr** [apache/pulsar#13432]
**Consumer batch reading of messages**
There is important feature to consumer messages in batch for a message broker. Apache pulsar java client is providing this feature by function consumer config property batchreceive policy. This should be available for pulsar-cpp-client as well. It would help in increasing read capacity of consumer.

**Describe the solution you'd like**
consumer would read the message in batch. There would be time limit to wait for message to create batch. Pulsar should have way to know internally that there are messages available to fill the batch or not. If there are no available message than it can fill the read batch with less messages.
i.e.
there are 13 messages. batch size to read is 10 msg. timeout is 100 millisecond
first read consumer would return with 10 messages
second read consumer would return with 3 message and immediately. It would not wait whole 100 millisecond. 

**Describe alternatives you've considered**
may be read message by multiple consumer. That would make reading faster but computer resource used would be high. 
I am open for suggestion if there is some way I can do batching.
please take a look @BewareMyPower @merlimat @jerrypeng @lhotari @sijie

**Comment by BewareMyPower** [comment]
I assign this issue to me first. But I might not have much time for it recently. If anyone is interested in this issue, please ping me and I will assign it to you.

**Comment by merlimat** [comment]
@lalit-g-deepr The consumer is already internally receiving the messages in batches and doing prefetching. There is no performance difference in calling `receive()` or `batchReceive() ` in Java.

**Comment by lalit-g-deepr** [comment]
@merlimat nice. Can I know how batching is being done?

**Comment by BewareMyPower** [comment]
Consumer reads entries from broker one by one. Each entry represents a batch. Then consumer will deserialize single messages from the batch.
