### ISSUE TITLE
[bug](broker): brokerDeleteInactiveTopic should exclude pulsar internal topics

### ISSUE THREAD

**Issue by ericsyh** [apache/pulsar#13479]
**Describe the bug**
On the Pulsar 2.8.1, we found that `brokerDeleteInactiveTopicsEnabled=true` will make pulsar internal topics like healthcheck deleted by inactivity.

<img width="1748" alt="截屏2021-12-24 上午10 35 10" src="https://user-images.githubusercontent.com/10498732/147309937-ab833432-53f2-4726-9a10-fd4a416c5d45.png">

**To Reproduce**
1. Set up pulsar cluster
2. Config `brokerDeleteInactiveTopicsEnabled=true` 
3. Monitor broker logs, you will get the healthcheck deleted by inactivity.

**Expected behavior**
InactiveTopics config should exclude some pulsar internal topics.

**Additional context**
Pulsar version: 2.8.1

**Comment by ericsyh** [comment]
@zymap @hangc0276 PTAL
cc @codelipenghui

**Comment by gaozhangmin** [comment]
Should we check why this topic become  inactive, I think this topic should not become inactive.

**Comment by ericsyh** [comment]
> Should we check why this topic become inactive, I think this topic should not become inactive.

In below broker log, you can get the life cycle of healthcheck from creating to deleting by inactivity.

[broker.log](https://github.com/apache/pulsar/files/7773314/broker.log)

**Comment by mattisonchao** [comment]
@ericsyh 

can i try to work on it ?

**Comment by hangc0276** [comment]
@mattisonchao  Thanks for your help, I have assigned this issue to you.
