### ISSUE TITLE
[PIP-127] Support Consul metadata

### ISSUE THREAD

**Issue by mattisonchao** [apache/pulsar#13474]
## Motivation

In many companies today, Consul is used in microservices to achieve related business requirements.
If we can support Consul metadata, it will bring a better user experience.

After PIP-45, I think we can support consul metadata.

PIP-45: https://github.com/apache/pulsar/wiki/PIP-45%3A-Pluggable-metadata-interface

## Goal

Support consul metadata.

## API Changes

- Add ``ConsulMetadataStore``

**Comment by benlongo** [comment]
Why was this closed?

**Comment by benlongo** [comment]
Why was this closed?

**Comment by eolivelli** [comment]
Maybe it was closed by mistake

**Comment by eolivelli** [comment]
The author of the issue closed it. Maybe there is no more interest from his point of view

**Comment by benlongo** [comment]
I'd be very interested to see support for Consul metadata. There are several other direct mentions of consul as a backend here https://github.com/apache/pulsar/issues/572#issue-243298720
