### ISSUE TITLE
[Doc]  Want to find the corresponding metrics

### ISSUE THREAD

**Issue by zcola** [apache/pulsar#13486]
### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/en/2.8.0/reference-metrics/

### What is your suggestion?

https://segmentfault.com/a/1190000023706815 

In addition to the following metrics, I have found all the metrics that the article recommends to observe
The metrics that need to be focused on are as follows:

1. Pulsar Broker

* loadbalance
* Cache hit rate on the broker side
* bookie client quarantine ratio
* bookie client request queue

2. BookKeeper
* bookie request queue size
* bookie request queue wait time
* journal create log latency
* ledger write cache flush latency
* entry read throttle

### Do you have any references?

no

### Would you like to fix this issue?

yes

### Note

- [X] I have researched my question.

**Comment by Jason918** [comment]
You mean you can't find the corresponding metrics? like 
> * loadbalance

pulsar_lb_unload_broker_count
pulsar_lb_unload_bundle_count

> * Cache hit rate on the broker side

pulsar_ml_cache_hits_rate
pulsar_ml_cache_misses_rate
pulsar_ml_cache_xxx

**Comment by Anonymitaet** [comment]
Hi @zcola 

I've discussed with @hangc0276, the author of https://segmentfault.com/a/1190000023706815, here is the reply:

## 1. Pulsar Broker

### loadbalance

- pulsar_lb_unload_broker_count
- pulsar_lb_unload_bundle_count

They have been documented here: https://pulsar.apache.org/docs/en/next/reference-metrics/#bundleunloading-metrics. Please read the docs carefully.

### Cache hit rate on the broker side

- pulsar_ml_cache_hits_rate
- pulsar_ml_cache_hits_throughput
- pulsar_ml_cache_misses_rate
- pulsar_ml_cache_misses_throughput

They have been documented here: https://pulsar.apache.org/docs/en/next/reference-metrics/#managedledgercache-metrics. Please read the docs carefully.

### bookie client quarantine ratio

- bookkeeper_server_BOOKIE_QUARANTINE_count

Thanks for reminding us, we've added it here: https://github.com/apache/pulsar/pull/13574

### bookie client request queue

As suggested by @hangc0276, users do not need to care about this. 

## 2. BookKeeper

### bookie request queue size

- bookkeeper_server_BookieReadThreadPool_queue_{thread_id}

Thanks for reminding us, we've added it here: https://github.com/apache/pulsar/pull/13574

### bookie request queue wait time

- bookkeeper_server_BookieReadThreadPool_task_queued
- bookkeeper_server_BookieReadThreadPool_task_execution

Thanks for reminding us, we've added them here: https://github.com/apache/pulsar/pull/13574
 
### journal create log latency

- bookie_journal_JOURNAL_CREATION_LATENCY

Thanks for reminding us, we've added it here: https://github.com/apache/pulsar/pull/13574

### ledger write cache flush latency

- bookie_flush

Thanks for reminding us, we've added it here: https://github.com/apache/pulsar/pull/13574

### entry read throttle

- bookie_throttled_write_requests

Thanks for reminding us, we've added it here: https://github.com/apache/pulsar/pull/13574
