### ISSUE TITLE
minio support 

### ISSUE THREAD

**Issue by rj1031cp** [apache/pulsar#13493]
**Is your feature request related to a problem? Please describe.**
from now ,  Tiered Storage had bean support like s3 etc, but did not support native storege solution such as minio  
**Describe the solution you'd like**
do u have any plan to support minio?

**Comment by ericsyh** [comment]
@rj1031cp minio supports s3, it is supported to offload to minio. Just config the s3 endpoint to minio service and use ak sk generated by minio.

**Comment by tisonkun** [comment]
Closed as answered. I believe the most general usage of minio is via S3 interface.
