### ISSUE TITLE
provide a lua  plugin for pulsar in  wireshark 

### ISSUE THREAD

**Issue by leizhiyuan** [apache/pulsar#13517]
**Is your feature request related to a problem? Please describe.**

https://github.com/apache/pulsar/tree/master/pulsar-client-cpp/wireshark

this is difficult in many different operation systems， I can write a Lua plugin for pulsar。 which will be easy to change and run in different systems， if it is ok， you can assigin to me

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hangc0276** [comment]
Good job. Hoping for your plugin. @leizhiyuan
