### ISSUE TITLE
[pulsar-client] Support receiverQueueRefillThreshold configuration.

### ISSUE THREAD

**Issue by mingyifei** [apache/pulsar#13524]
`org.apache.pulsar.client.impl.ConsumerImpl#receiverQueueRefillThreshold`

`        this.receiverQueueRefillThreshold = conf.getReceiverQueueSize() / 2;
`

Currently the configuration is fixed, do you consider letting the user decide?

**Comment by mattisonchao** [comment]
@mingyifei 

Why do you want to change this threshold ?

**Comment by mingyifei** [comment]
> 

I can control how often it initiates a pull request to the broker

**Comment by mingyifei** [comment]
> 

I can control how often it initiates a pull request to the broker

**Comment by mingyifei** [comment]
This value is determined by the consumption rate. If the consumption is very slow, it may be better to configure it to 0.7-0.9. 0.5 may be a compromise

**Comment by hangc0276** [comment]
I wonder whether different value has better performance. You'd better give more reason to make the value configurable. @mingyifei

**Comment by tisonkun** [comment]
This config option no longer exists. Closed as stale.
