### ISSUE TITLE
[Doc] add examples of "how to use metrics" to "Metrics" guide

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#13588]
Add examples of "how to use metrics" to https://pulsar.apache.org/docs/en/next/reference-metrics/

Reference: https://github.com/streamnative/apache-pulsar-grafana-dashboard/tree/master/dashboards

**Comment by momo-jun** [comment]
Can this [doc page](https://pulsar.apache.org/docs/next/deploy-monitoring#collect-metrics) be helpful?

**Comment by tisonkun** [comment]
Closed as stale. Feel free to open a new issue if there's a concrete proposal on what to add.
