### ISSUE TITLE
[Doc] add docs for "how to develop plugin" in "development" guide

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#13585]
Need to add docs for the following missing contents:

![image](https://user-images.githubusercontent.com/50226895/147803490-d78734af-7c26-4b8e-b2b5-2bc04c72f72f.png)

Related code PR: https://github.com/apache/pulsar/pull/12536

**Comment by momo-jun** [comment]
Status update: Pending.
Confirmed with @codelipenghui today.

**Comment by momo-jun** [comment]
Hi @codelipenghui, any updates or plan for this doc?

**Comment by momo-jun** [comment]
@codelipenghui 
Does this new doc-required PR #14729 have dependency on this issue?

**Comment by tisonkun** [comment]
Closed as stale and no interest. This can be part of #18272 when we later touch it.
