### ISSUE TITLE
[Doc] pulsar-manager installation and deployment documentation optimization sequence

### ISSUE THREAD

**Issue by fanla2021** [apache/pulsar#13583]
### What issue do you find in Pulsar docs?

Currently, when deployed according to the documentation, the structure is confusing and not easy to install quickly.

### What is your suggestion?

The overall installation and deployment documentation is based on the docker method of deployment, with other installation methods as supplementary instructions. 
The general idea is as follows:

- 1 Easy installation based on docker image
  - 1.1 If database and JWT authentication are not required, install the following.
     Install Pulsar Manager
  - 1.2 If you need to configure database or JWT authentication, add the following steps.
     Configure the database
     Enable JWT
  - 1.3 Set the administrator account and password
  - 1.4 Configure the environment
     Login to the system Visit http://localhost:9527 to login.
- 2 Other Installation
   Bare-metal installation and custom docker image installation
- 3 Configuration instructions

### Do you have any references?

no

### Would you like to fix this issue?

I can

### Note

- [X] I have researched my question.

**Comment by Anonymitaet** [comment]
Hi @fanla2021 can you help update docs?

**Comment by fanla2021** [comment]
> Hi @fanla2021 can you help update docs?

No problem
