### ISSUE TITLE
[Doc] add examples of "

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#13587]
Add examples for how to use metrics

Reference: https://github.com/streamnative/apache-pulsar-grafana-dashboard/tree/master/dashboards

**Comment by mattisonchao** [comment]
@Anonymitaet  same to #13588 ?

**Comment by Anonymitaet** [comment]
Oh yes, it's a mistake, I'll close this. Thanks for reminding me. @mattisonchao
