### ISSUE TITLE
Vulnerability in gson version 2.8.6

### ISSUE THREAD

**Issue by Markfesenk0** [apache/pulsar#13607]
**Is your enhancement request related to a problem? Please describe.**
gson version 2.8.6 is vulnerable to desirealization of untrusted data, as shown here:
https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLECODEGSON-1730327

**Describe the solution you'd like**
Upgrade gson version to 2.8.9

**Comment by mattisonchao** [comment]
i can work on it. :)
