### ISSUE TITLE
[ PIP 134 ] Support Pulsar system event.

### ISSUE THREAD

**Issue by mattisonchao** [apache/pulsar#13628]
## Motivation

In some case or for better observability. We can support Pulsar event notification mechanism, that can let user subscribe this system topic to receive some **"we need notice to user"** event.

## Goal

Enable users to receive Pulsar system event.

## API Changes

1. Add config ``pulsarSystemEventEnabled``

```java
pulsarSystemEventEnabled=false
```
2. Add ``SystemEventMessageBuilder``
```java

public interface SystemEventMessageBuilder {

    SystemEventMessageBuilder eventType(SystemEvent event);

    SystemEventMessageBuilder properties(Map<String,Object> properties);
    
    SystemEventMessageBuilder addProperty(String key, Object value);

    SystemEventMessage build();

}

```
3. Add ``SystemEventService``

```java

public interface SystemEventService {
    
    void init();
    
    CompletableFuture<MessageId> trigger(SystemEventMessage message);
    
    void close();
}

```

## Implementation

This PIP just is a simple version, it's purpose is to discuss what event we need to trigger? how to trigger? and what is the event message structure.

I think we need to trigger some event as bellow:

- [ ] Client connected
- [ ] Client disconnected
- [ ] Consumer subscribe
- [ ] Consumer unsubscribe
- [ ] Producer publish
- [ ] Message delivered
- [ ] Message acked
- [ ] ... ( Some other event like node change, ledger deleted etc. )

These are far from enough, and we need to continue to make supplements here.
Please feel free to give me more advice for this PIP.

## Reject Alternatives

none.

**Comment by eolivelli** [comment]
Some preliminary questions:
- Where are you going to store this data? (Think about a huge cluster with thousands of independent, isolated tenants)
- How do we deal with authorisation? Who can subscribe and who can write?
- can you implement this with Broker interceptors and write your events to a topic?

**Comment by mattisonchao** [comment]
> Some preliminary questions:
> 
> * Where are you going to store this data? (Think about a huge cluster with thousands of independent, isolated tenants)
> * How do we deal with authorisation? Who can subscribe and who can write?
> * can you implement this with Broker interceptors and write your events to a topic?

**Answer 1**
I think this PIP face to middleware team,  business team do not have interest to care about system event.
Therefor, We can store that event to global **System Topic**. 
**Answer 2**
Maybe we need to create a new authority to handle this.
**Answer 3**
Maybe not, because we need report some internal event, like node changed, ledger deleted ... etc.

@eolivelli
What do you think about my idea ? 
You are welcome to make more good suggestions.
