### ISSUE TITLE
Some questions about bookeeper.

### ISSUE THREAD

**Issue by mingyifei** [apache/pulsar#13635]
After the bookeeper obtains the FileChannel, it writes the called write(), reads the called read(), write() writes to the system buffer, and force writes to the disk through fileChannel.force(). Why not use mmap here?

**Comment by Jason918** [comment]
Aha, this should be asked in Bookkeeper project.

**Comment by mingyifei** [comment]
> 

You’re right, I’m going to bookeeper to ask questions, but if you know, you can reply to me.
