### ISSUE TITLE
Subscribing non persistent topic error if cluster disallow auto subscription creation

### ISSUE THREAD

**Issue by dragonls** [apache/pulsar#13640]
**Describe the bug**
I am trying to use non persistent topic on pulsar 2.7.2 non persistent topic. Pulsar cluster disallow auto subscription creation, `allowAutoSubscriptionCreation=false`.

I tried to create subscription using pulsar admin api but receiving error `Create subscription on non-persistent topic can only be done through client`

**To Reproduce**
1. Delopy a Pulsar cluster with `allowAutoSubscriptionCreation=false`
2. Create a non persistent topic `non-persistent://test/test/topic1`
3. Create a consumer to subscribe the topic

**Expected behavior**
The consumer can subscribe the non persistent topic correctly.

**Additional context**
The pulsar admin disallow creating subscription on non persistent topic:
https://github.com/apache/pulsar/blob/016fb87039f44bdf3f8829797bb08a71e61483ab/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java#L1347-L1350

The broker reject the subscription:
https://github.com/apache/pulsar/blob/016fb87039f44bdf3f8829797bb08a71e61483ab/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java#L1013-L1022

**Comment by shibd** [comment]
Hi, Why create subscription on non persistent topic is not support by admin api? @hangc0276

**Comment by dragonls** [comment]
> Hi, Why create subscription on non persistent topic is not support by admin api? @hangc0276

Relative issue: #7397

**Comment by codelipenghui** [comment]
@shibd For the non-persistent topic, the broker will not hold any messages. It looks like a message is forwarded between channels, from the producer channel to the consumer channel, so it does not make sense to create a subscription without a connected consumer
