### ISSUE TITLE
[PIP-134] Pulsar consumer support auto acknowledge.

### ISSUE THREAD

**Issue by gaozhangmin** [apache/pulsar#13661]
## Motivation

Pulsar should support auto commit offset in background like what KAFKA did.

## Goal

Consumer support config `autoAckEnabled` and `autoAckIntervalMs` which control auto acknowledge enabled or not and the time duration between two  acks.

## Implementation

ConsumerConfigurationData add three new configuration
```
autoAckEnabled=false
autoAckIntervalMs=5000
```

```
private void maybeAutoAckonwledgeAsync(MessageId  messageId) {
        if (autoAckEnabled) {

        }
    }


private void maybeAutoAckonwledgeSync(MessageId  messageId) {
    if (autoAckEnabled) {

    }
}


```
When call `consumer.receive()` We check if auto ack enabled  and it's time to `maybeAutoAckonwledgeAsync`
When call `consumer.close()` ,`maybeAutoAckonwledgeSync` will be called, make sure all the consumed offset committed to pulsar successfully

## Reject Alternatives

none

**Comment by mattisonchao** [comment]
One Preliminary question:

- If user set ``autoAckEnabled=ture`` and then user invoke negative ack, what things will happen ?

**Comment by gaozhangmin** [comment]
> One Preliminary question:
> 
> * If user set `autoAckEnabled=ture` and then user invoke `negative ack`, what things will happen ?

We should avoid this, We forbid negative ack If We set autoAckEnabled=ture`

**Comment by merlimat** [comment]
@gaozhangmin 

> Pulsar should support auto commit offset in background like what KAFKA did.

But why?

The problem with Kafka acks is that if you ack each message, the performance is terrible. This is definitely not the case in Pulsar consumer.
