### ISSUE TITLE
[Doc] dead link in https://pulsar.apache.org/docs/en/concepts-messaging/

### ISSUE THREAD

**Issue by vkuznecovas** [apache/pulsar#13667]
### What issue do you find in Pulsar docs?

In https://pulsar.apache.org/docs/en/concepts-messaging/ the negative acknowledgement link returns a 404.
Below is the paragraph:

> If the consumption of a message fails and you want this message to be consumed again, then you can enable the automatic redelivery of this message by sending a negative acknowledgement to the broker or enabling the acknowledgement timeout for unacknowledged messages.

### What is your suggestion?

https://pulsar.apache.org/docs/en/concepts-messaging/ should point to a link that's not dead.

This is the dead link.
https://pulsar.apache.org/docs/en/concepts-messaging/negative-acknowledgement

### Do you have any references?

https://pulsar.apache.org/docs/en/concepts-messaging/ 

This is the dead link.
https://pulsar.apache.org/docs/en/concepts-messaging/negative-acknowledgement

### Would you like to fix this issue?

Not really.

### Note

- [X] I have researched my question.

**Comment by dave2wave** [comment]
This was already fixed by `Fix hyperlinks typo (#13593)`, but maybe typos still exist in versioned docs?

**Comment by Anonymitaet** [comment]
@vkuznecovas which version do you refer to?
(docs on `master` is correct https://pulsar.apache.org/docs/en/next/concepts-messaging/)

**Comment by vkuznecovas** [comment]
Sorry for the long time with no reply. I'm refering to the live version.

1) Open https://pulsar.apache.org/docs/en/concepts-messaging/ 
1) Click the link under "a negative acknowledgement"
1) See <img width="768" alt="Screenshot 2022-01-17 at 12 45 57" src="https://user-images.githubusercontent.com/18392269/149755581-d8729198-e004-4f28-9a20-551f6b2bef45.png">

**Comment by Anonymitaet** [comment]
Oh, I see, corrected in https://github.com/apache/pulsar/pull/13802, PTAL
