### ISSUE TITLE
Subscribing on dedicated position

### ISSUE THREAD

**Issue by DongbinNie** [apache/pulsar#137]
Subscribing on other position instead of the last committed position on the first subscription.

[merlimat]
That would be only meaningful if the retention-time has been specified, otherwise the messages might have been already deleted. Also, what should the outcome be if subscribing to a position that is not available anymore?

[DongbinNie]
It may be a error or subscribing to the first available position. 

[merlimat]
An option that is kind of similar is to subscribe and then rollback the subscription to X hours  before.
 
[DongbinNie]
Yes, it can be achieved by this way.

**Comment by ivankelly** [comment]
@DongbinNie Does subscriptionInitialPosition solve this for you?
http://pulsar.apache.org/api/client/org/apache/pulsar/client/api/ConsumerBuilder.html#subscriptionInitialPosition-org.apache.pulsar.client.api.SubscriptionInitialPosition-

**Comment by ivankelly** [comment]
Closing for now since there's been no response. It looks like subscriptionInitialPosition solves the usecase
