### ISSUE TITLE
Netty - set EndpointIdentificationAlgorithm to get rid of CWE-295

### ISSUE THREAD

**Issue by nicoloboschi** [apache/pulsar#13705]
`EndpointIdentificationAlgorithm` parameter must be set to "HTTPS" to properly perform hostname validation during `SslEngine` creation.
As far as I can see in the Pulsar codebase this parameter is left to the default value; this means that the hostname validation is disabled.

More context here
* https://github.com/netty/netty/issues/9930
* https://github.com/netty/netty/issues/8537
* https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLParameters.html#setEndpointIdentificationAlgorithm-java.lang.String-
* https://netty.io/4.1/api/io/netty/handler/ssl/SslContext.html#newHandler-io.netty.buffer.ByteBufAllocator-java.util.concurrent.Executor-

**Comment by eolivelli** [comment]
@nicoloboschi do you have a proposal ?
Which are the cons of setting a value ?

**Comment by nicoloboschi** [comment]
I don't see cons in a correctly configured environment. BTW I consider it a breaking change but it's worth because of security

The fix is to configure the parameter whenever a SSLEngine is created. I can work on it this week

**Comment by lhotari** [comment]
@nicoloboschi There are tests in https://github.com/apache/pulsar/blob/master/pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthenticationTlsHostnameVerificationTest.java , do you think that there's a gap?

In Pulsar client, there's custom logic to do the hostname validation: https://github.com/apache/pulsar/blob/1a3688c936bb2320db34ccfbef08500f2c522591/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java#L311-L316

**Comment by michaeljmarshall** [comment]
Fixed by https://github.com/apache/pulsar/pull/15824.
