### ISSUE TITLE
[Doc] Incorrect description in https://pulsar.apache.org/docs/en/concepts-messaging/#retry-letter-topic

### ISSUE THREAD

**Issue by vhaisong** [apache/pulsar#13719]
### What issue do you find in Pulsar docs?

In https://pulsar.apache.org/docs/en/concepts-messaging/#retry-letter-topic, it said "For many online business systems, a message is re-consumed due to exception occurs in the business logic processing. To configure the delay time for re-consuming the failed messages, you can configure the producer to send messages to both the business topic and the retry letter topic, and enable automatic retry on the consumer.".    
To the best of my knowledge, no fixed parameters that to set the delay time for reconsuming the failed messages. You can try acknowledgement timeout and set `acktime` for reconsume in original topic ( or send a negative acknowledgement ), or use api like `consumer.reconsumeLater(msg,3,TimeUnit.SECONDS);` for reconsume in retry letter topic. Finally, all of this is done on the consumer side.  
But in docs, like broker ( set the delay time? ) and producer ( send message to business topic and retry letter topic? ) need have something do. If there is any wrong understanding, please let me know, thanks.

### What is your suggestion?

Maybe delete or put it another way.

### Do you have any references?

Not really.

### Would you like to fix this issue?

Not really.

### Note

- [X] I have researched my question.

**Comment by liudezhi2098** [comment]
Acknowledgment timeout triggers are triggered when an ACK acknowledgment message is not acknowledged within a specified time, such as when an ACK is forgotten, or when the business logic takes too long to process.
`client.newConsumer().ackTimeout(10, TimeUnit.SECOND)` All messages follow the same delay strategy.

Negative acknowledgment is when a user actively triggers message retries, such as when business logic processing fails and needs to be consumed again, All messages follow the same delay strategy.
```
client.newConsumer().negativeAckRedeliveryDelay(1, TimeUnit.SECOND)
try {
	// Process message...
	consumer.acknowledge(msg);
} catch (Throwable t) {
	log.warn("Failed to process message");
	consumer.negativeAcknowledge(message);
}

```


Reconsumelater behaves similarly to negative acknowledgment, different places, reconsumeLater will use retry topic to persist retry messages, which has the advantage of delaying granular messages at any time, and can accommodate a large number of retry message scenarios, this will suit a more flexible scenario.
```
try {
	// Process message...
	consumer.acknowledge(msg);
} catch (Throwable t) {
	log.warn("Failed to process message");
	consumer.reconsumeLater(msg, 1000, TimeUnit.MILLISECONDS);
}
```
For the user, there is no need to care about the internal implementation logic.

**Comment by vhaisong** [comment]
It's not about usage, it's about documentation.

**Comment by liudezhi2098** [comment]
> It's not about usage, it's about documentation.

I try to improve the documentation

**Comment by momo-jun** [comment]
#14498
