### ISSUE TITLE
[Doc] Update the C# client page to use newer version of the client library

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#13730]
### What issue do you find in Pulsar docs?

The current version of the docs uses version 0.11 of the C# client library, and the newest version of that library is now 2.0.1. 

### What is your suggestion?

There have been some changes to the API between these versions, starting with the namespace, so we need to update these docs to reflect the API of the most recent version, 2.0.1

We definitely need to show the required imports in the code as well, e.g.

using DotPulsar;
using DotPulsar.Abstractions;
using DotPulsar.Extensions;

### Do you have any references?

Code examples can be found here: https://github.com/apache/pulsar-dotpulsar/wiki

### Would you like to fix this issue?

Maybe, if I have time

### Note

- [X] I have researched my question.

**Comment by RobertIndie** [comment]
@david-streamlio I can help with this.
