### ISSUE TITLE
Possible code changes required for #13077

### ISSUE THREAD

**Issue by momo-jun** [apache/pulsar#13760]
As per https://github.com/apache/pulsar/pull/13077, `zookeeperServers` and `configurationStoreServers` need to be renamed to `metadataStoreUrl` and `configurationMetadataStoreUrl`.

When implementing doc changes with a global search, I found the following files have parameter named `zookeeper-servers` and `configuration-store-servers`/`configuration-store`, which might need to be renamed as well.

Submit this issue to track whether the code needs to be changed like that in https://github.com/apache/pulsar/pull/13758.
![image](https://user-images.githubusercontent.com/60642177/149497825-e0ed4d2a-da51-4ae0-a6c4-804f9bd6babc.png)

Doc File1 with code sample:
![image](https://user-images.githubusercontent.com/60642177/149496960-7f358c6c-8376-4613-940e-3718c8217697.png)

Doc File2 with code sample:
![image](https://user-images.githubusercontent.com/60642177/149497660-850055db-5fd5-422e-8467-67ec7bb496d6.png)

**Comment by RobertIndie** [comment]
@codelipenghui I can work on it.

**Comment by gaozhangmin** [comment]
I added metadataStoreUrl support for pulsar proxy and function_worker already.  
#13777 #13782。 You just need update broker's doc.

**Comment by RobertIndie** [comment]
Here is another PR related to this issue: https://github.com/apache/pulsar/pull/14384

**Comment by momo-jun** [comment]
@RobertIndie @Anonymitaet I think this issue can be closed.
