### ISSUE TITLE
Topic can't unsubscribe subscription

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#13787]
**Describe the bug**
Pulsar: v2.8.1
Topic partition: 20

There are three subscriptions on this topic. Now delete the second subscription. As a result, another partition has not been deleted. It shows that there are active consumer processes, we go to the host and check the process through this port. We find that there is no process, Then we can't delete it through unsubscribe. 

![image](https://user-images.githubusercontent.com/54351417/149745071-57cc27ae-1fd2-45b0-90e7-9293edcb0b7b.png)
![image](https://user-images.githubusercontent.com/54351417/149746339-101699d4-a566-4c61-ac1b-53a87cebf37d.png)

```
bin/pulsar-admin topics unsubscribe -s housekeeping_ignite persistent://pulsar/iagw/21_rate_out_b
17:35:36.602 [AsyncHttpClient-7-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://localhost:30200/admin/v2/persistent/pulsar/iagw/21_rate_out_b/subscription/housekeeping_ignite?force=false] Failed to perform http delete request: javax.ws.rs.NotFoundException: HTTP 404 Not Found
Subscription not found

Reason: Subscription not found
```

**Comment by codelipenghui** [comment]
Have you tried to use the PulsarAdmin to list the subscriptions or check the active consumers/producers? I'm not sure if the problem is related to Pulsar Manager or Pulsar, PulsarAdmin can help to determine the problem

**Comment by xuesongxs** [comment]
***@***.***
 
From: lipenghui
Date: 2022-01-17 22:59
To: apache/pulsar
CC: xuesongxs; Author
Subject: Re: [apache/pulsar] Topic can't unsubscribe subscription (Issue #13787)
Have you tried to use the PulsarAdmin to list the subscriptions or check the active consumers/producers? I'm not sure if the problem is related to Pulsar Manager or Pulsar, PulsarAdmin can help to determine the problem
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xuesongxs** [comment]
> Have you tried to use the PulsarAdmin to list the subscriptions or check the active consumers/producers? I'm not sure if the problem is related to Pulsar Manager or Pulsar, PulsarAdmin can help to determine the problem
bin/pulsar-admin topics partitioned-stats:
![image](https://user-images.githubusercontent.com/54351417/150043446-28c3865b-e28d-45ab-9757-a9507a3bd58d.png)

**Comment by xuesongxs** [comment]
Prompt "subscription has active consumers" when deleting topic, but no consumers are actually connected.
It may be that the consumerList is not deleted in the consumerList after the consumer is disconnected.
![image](https://user-images.githubusercontent.com/54351417/150045756-51a245a2-89fe-4d0f-9e97-fe55cda07588.png)

**Comment by xuesongxs** [comment]
Looking at the broker process stack, I feel that this problem can not be solved without restarting the broker.
[broker.txt](https://github.com/apache/pulsar/files/7893631/broker.txt)
[broker1.txt](https://github.com/apache/pulsar/files/7893632/broker1.txt)

**Comment by poorbarcode** [comment]
@xuesongxs Do you see the same thing happening here #15050

**Comment by Technoboy-** [comment]
https://github.com/apache/pulsar/pull/21687
