### ISSUE TITLE
Support auto increment PIP number.

### ISSUE THREAD

**Issue by mattisonchao** [apache/pulsar#13795]
## Motivation

Recently, I found many PIP number has been conflict, i think it's a good way to use Github open API to auto increment pip number.

## Goal

Solve the problem of incorrect sorting of PIP numbers and conflicts.

## Implementation

- When the user creates a PIP ``xxxxxxxxxxxx``, we can call the GIthub open api to get the pip title and calculate the last title number according to the callback event, and then add one to change the pip title to [ PIP-xxx ] xxxxxxx.

**Comment by michaeljmarshall** [comment]
@mattisonchao - this problem as well as our current solution was discussed here: https://lists.apache.org/thread/vw25onjyo18trfysd7x9k9wrs2tyqfok. The process is documented in the PIP issue template. If you'd like to discuss changing it, please send a note to `dev@pulsar.apache.org`.
