### ISSUE TITLE
Incompatible Schema using ALWAYS_COMPATIBLE

### ISSUE THREAD

**Issue by BramVanImpeAc** [apache/pulsar#13804]
**Describe the bug**
Using version 2.9.0, connecting with a producer to a topic using ALWAYS_COMPATIBLE results in the following error: java.lang.RuntimeException: Writing to a topic which have incompatible schema.

**To Reproduce**

1. Namespace that topic belongs to is configured with settings:
"schema_compatibility_strategy" : "ALWAYS_COMPATIBLE",
"is_allow_auto_update_schema" : true,
"schema_validation_enforced" : false,
2. The topic has no schemas, producers or consumers registered.
3. Consumer connects with the topic and register a STRING schema.
4. Producer connects to the same topic and tries to register a JSON schema.
5. Producer throws error java.lang.RuntimeException: Writing to a topic which have incompatible schema

**Expected behavior**
Since the compatibility strategy is set to "ALWAYS_COMPATIBLE", the schema registration is allowed.

**Additional context**
Doing it the other way round (first connecting with producer (using JSON schema) and then with consumer (using STRING schema)) works as expected.

**Comment by gaozhangmin** [comment]
I followed your step, I could send message successfully, Please check your schema-compatibility-strategy again by command:
`bin/pulsar-admin namespaces get-schema-compatibility-strategy public/default`

**Comment by BramVanImpeAc** [comment]
Thanks for looking into this.

After retrying all the steps I've noticed that our producer (streamnative/pulsar-flink) makes the decision that the schema is incompatible before submitting it to the broker.

Sorry for the trouble.
