### ISSUE TITLE
[Doc] Broken links on "concepts-messaging" page

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#13818]
### What issue do you find in Pulsar docs?

There are two broken links on the following [page](https://pulsar.apache.org/docs/en/concepts-messaging/)

The links to [negative acknowledgement](https://pulsar.apache.org/docs/en/concepts-messaging/negative-acknowledgement) and [acknowledgement timeout](https://pulsar.apache.org/docs/en/concepts-messaging/acknowledgement-timeout)  are broken and return 404s

### What is your suggestion?

Fix the broken links to point to the correct pages

### Do you have any references?

![Screen Shot 2022-01-18 at 8 52 58 AM](https://user-images.githubusercontent.com/35466513/149982574-7c3804f5-afd9-46a5-9200-20240247eb0f.png)

### Would you like to fix this issue?

Maybe

### Note

- [X] I have researched my question.

**Comment by Anonymitaet** [comment]
Fix in https://github.com/apache/pulsar/pull/13802
