### ISSUE TITLE
close

### ISSUE THREAD

**Issue by 346359827** [apache/pulsar#13825]
#13788

**Comment by 346359827** [comment]
log 
pulsar-broker-hzsd-service-12-92.getui.log-01-17-2022-1.log.gz:21:59:26.924 [pulsar-io-4-5] WARN  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://b2d/rcp-new/rcp-normal#msg-topic#keyed#OtJQ5Kw6F36GSKbC8A3CY-partition-1][rcp-normal-queue-subscription] Failed to delete message at 31590:-1: org.apache.bookkeeper.mledger.ManagedLedgerException: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position
pulsar-broker-hzsd-service-12-92.getui.log-01-17-2022-1.log.gz:21:59:26.932 [pulsar-io-4-9] WARN  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://b2d/rcp-new/rcp-normal#msg-topic#keyed#OtJQ5Kw6F36GSKbC8A3CY-partition-1][rcp-normal-queue-subscription] Failed to delete message at 31590:-1: org.apache.bookkeeper.mledger.ManagedLedgerException: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position
pulsar-broker-hzsd-service-12-92.getui.log-01-17-2022-1.log.gz:21:59:26.956 [pulsar-io-4-7] WARN  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://b2d/rcp-new/rcp-normal#msg-topic#keyed#OtJQ5Kw6F36GSKbC8A3CY-partition-1][rcp-normal-queue-subscription] Failed to delete message at 31590:-1: org.apache.bookkeeper.mledger.ManagedLedgerException: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position
pulsar-broker-hzsd-service-12-92.getui.log-01-17-2022-1.log.gz:21:59:26.975 [pulsar-io-4-4] WARN  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://b2d/rcp-new/rcp-normal#msg-topic#keyed#OtJQ5Kw6F36GSKbC8A3CY-partition-1][rcp-normal-queue-subscription] Failed to delete message at 31590:-1: org.apache.bookkeeper.mledger.ManagedLedgerException: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position
pulsar-broker-hzsd-service-12-92.getui.log-01-17-2022-1.log.gz:21:59:27.001 [pulsar-io-4-8] WARN  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://b2d/rcp-new/rcp-normal#msg-topic#keyed#OtJQ5Kw6F36GSKbC8A3CY-partition-1][rcp-normal-queue-subscription] Failed to delete message at 31590:-1: org.apache.bookkeeper.mledger.ManagedLedgerException: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position
pulsar-broker-hzsd-service-12-92.getui.log-01-17-2022-1.log.gz:21:59:27.022 [pulsar-io-4-63] WARN  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://b2d/rcp-new/rcp-normal#msg-topic#keyed#OtJQ5Kw6F36GSKbC8A3CY-partition-1][rcp-normal-queue-subscription] Failed to delete message at 31590:-1: org.apache.bookkeeper.mledger.ManagedLedgerException: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position
pulsar-broker-hzsd-service-12-92.getui.log-01-17-2022-1.log.gz:21:59:27.023 [pulsar-io-4-5] WARN  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://b2d/rcp-new/rcp-normal#msg-topic#keyed#OtJQ5Kw6F36GSKbC8A3CY-partition-1][rcp-normal-queue-subscription] Failed to delete message at 31590:-1: org.apache.bookkeeper.mledger.ManagedLedgerException: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position
pulsar-broker-hzsd-service-12-92.getui.log-01-17-2022-1.log.gz:21:59:27.036 [pulsar-io-4-9] WARN  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://b2d/rcp-new/rcp-normal#msg-topic#keyed#OtJQ5Kw6F36GSKbC8A3CY-partition-1][rcp-normal-queue-subscription] Failed to delete message at 31590:-1: org.apache.bookkeeper.mledger.ManagedLedgerException: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position
pulsar-broker-hzsd-service-12-92.getui.log-01-17-2022-1.log.gz:21:59:27.057 [pulsar-io-4-7] WARN  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://b2d/rcp-new/rcp-normal#msg-topic#keyed#OtJQ5Kw6F36GSKbC8A3CY-partition-1][rcp-normal-queue-subscription] Failed to delete message at 31590:-1: org.apache.bookkeeper.mledger.ManagedLedgerException: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position
pulsar-broker-hzsd-service-12-92.getui.log-01-17-2022-1.log.gz:21:59:27.075 [pulsar-io-4-4] WARN  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://b2d/rcp-new/rcp-normal#msg-topic#keyed#OtJQ5Kw6F36GSKbC8A3CY-partition-1][rcp-normal-queue-subscription] Failed to delete message at 31590:-1: org.apache.bookkeeper.mledger.ManagedLedgerException: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position
pulsar-broker-hzsd-service-12-92.getui.log-01-17-2022-1.log.gz:21:59:27.089 [pulsar-io-4-8] WARN  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://b2d/rcp-new/rcp-normal#msg-topic#keyed#OtJQ5Kw6F36GSKbC8A3CY-partition-1][rcp-normal-queue-subscription] Failed to delete message at 31590:-1: org.apache.bookkeeper.mledger.ManagedLedgerException: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position
pulsar-broker-hzsd-service-12-92.getui.log-01-17-2022-1.log.gz:21:59:27.122 [pulsar-io-4-63] WARN  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://b2d/rcp-new/rcp-normal#msg-topic#keyed#OtJQ5Kw6F36GSKbC8A3CY-partition-1][rcp-normal-queue-subscription] Failed to delete message at 31590:-1: org.apache.bookkeeper.mledger.ManagedLedgerException: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position
pulsar-broker-hzsd-service-12-92.getui.log-01-17-2022-1.log.gz:21:59:27.124 [pulsar-io-4-5] WARN  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://b2d/rcp-new/rcp-normal#msg-topic#keyed#OtJQ5Kw6F36GSKbC8A3CY-partition-1][rcp-normal-queue-subscription] Failed to delete message at 31590:-1: org.apache.bookkeeper.mledger.ManagedLedgerException: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position

**Comment by 346359827** [comment]
https://github.com/apache/pulsar/issues/13788

**Comment by michaeljmarshall** [comment]
@346359827 - it looks like you wanted this issue closed. I am going to close it for now. Please re-open if I am mistaken.
