### ISSUE TITLE
[Doc] add docs for topic policy and system topic

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#13856]
Currently, we have documented "operations" for https://pulsar.apache.org/tools/pulsar-admin/2.10.0-SNAPSHOT/#topicpolicies but do not document explanations (like concepts) for topic policy and system topic.

Context: https://streamnative.slack.com/archives/C01J6DMU24W/p1642674448092300?thread_ts=1642671724.086100&cid=C01J6DMU24W

**Comment by momo-jun** [comment]
@Anonymitaet This issue can be closed. Docs have been added.

**Comment by Anonymitaet** [comment]
@momo-jun OK, done.
