### ISSUE TITLE
Add ability to disable statistics reporting at namespace level

### ISSUE THREAD

**Issue by klevy-toast** [apache/pulsar#13863]
**Is your enhancement request related to a problem? Please describe.**
In our pulsar cluster, we are running into issues due to the number of metrics being reported. We would like to disable the `exposeTopicLevelMetricsInPrometheus` setting for a subset of our topics that have many subscriptions, but keep it on for other topics where we need those statistics. Currently, this can only be configured in `broker.conf` as a global setting.

**Describe the solution you'd like**
Add new namespace settings to configure statistic generation, like: 
- `pulsar-admin namespaces set-stats-override topic <namespace>`
- `pulsar-admin namespaces delete-stats-override consumer <namespace>`
- also allow configuration of `producer`, `managed-ledger`, `managed-cursor`

The namespace-level flags will default to null, so that it defaults to however `broker.conf` is set. If the flags are set on the given namespace, it will use that instead of the setting in `broker.conf`

**Describe alternatives you've considered**
- This flag could also be configured at the tenant level. It doesn't seem like there are many tenant-level flags though.
- The settings could be removed from `broker.conf` and only be configured at the namespace/tenant level. This may cause issues with backwards compatibility.

**Additional context**

**Comment by gaozhangmin** [comment]
Two doubles?
1、Why you need config it at tenant level? 
2、why you want remove from broker.conf?

**Comment by klevy-toast** [comment]
@gaozhangmin I do not intend to implement it with those alternatives.. they were simply alternatives to consider. I plan to implement it on the namespace level, without removing it from broker.conf

**Comment by liangyuanpeng** [comment]
It is possible to ignore this metrics when get the metrics, like relabel in prometheus.

**Comment by klevy-toast** [comment]
I believe I've found a workaround for my use-case

**Comment by joshcusano** [comment]
Hi @klevy-toast, 
I'm experiencing the same issue and I'm curious if you found a workaround

**Comment by avinash-fk** [comment]
> Hi @klevy-toast, I'm experiencing the same issue and I'm curious if you found a workaround

+1

**Comment by klevy-toast** [comment]
@joshcusano @avinash-fk apologies I never saw these comments. We implemented a workaround by filtering the metrics on the collector (in our case, the datadog agent). It is unfortunately still rather slow because the prometheus endpoint is generating a lot of metrics that we are not reporting, but we were able to cut down on the cardinality a lot this way.
