### ISSUE TITLE
pulsar_out_bytes_total is not pegged for non-persistent topic

### ISSUE THREAD

**Issue by zzzming** [apache/pulsar#13893]
**Describe the bug**
pulsar_out_bytes_total is not pegged for non-persistent topic

**To Reproduce**
1. Send messages to a non-persistent topic
2. Wait for a few minutes
3. pulsar_out_bytes_total is not pegged for the non-persistent topic

**Expected behavior**
There should be the number of bytes for this metrics

This was tested on 2.8.

**Comment by mattisonchao** [comment]
#13827  can fix this issue ?

**Comment by gaozhangmin** [comment]
> #13827 can fix this issue ?

I think so.

**Comment by gaozhangmin** [comment]
@zzzming  #13827  has merged, please help close this issue. THx.
