### ISSUE TITLE
[Python Client] New consumer type: TableView

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#13931]
**Is your feature request related to a problem? Please describe.**
This is a feature catchup of Python client for a new consumer type: TableView which was introduced in Pulsar 2.10.0

The proposal: https://github.com/apache/pulsar/issues/12356
The Java implementation: https://github.com/apache/pulsar/pull/12838

**Comment by tisonkun** [comment]
Closed as stale. The development of the Python client has been permanently moved to http://github.com/apache/pulsar-client-python. Please open an issue there if it's still relevant.
