### ISSUE TITLE
Endless Topic HTTP Request Redirects

### ISSUE THREAD

**Issue by ronfarkash** [apache/pulsar#13946]
**Describe the bug**
Admin REST HTTP Request on topic may redirect multiple times to different broker endlessly.

This bug occurs randomly and at inconsistent times.

(The HTTP request must be related to topic ownership, e.g. get topic subscription, stats, etc...)

**To Reproduce**
1. Setup a Pulsar Cluster with 3 BookKeepers, 3 Global ZooKeepers, 3 ZooKeepers and 3 Brokers, and add JWT Authentication.
2. Open Postman (or any HTTP Client) and disable "Automatically follow redirects" in Settings.
3. Have the cluster up for a while (can be hours/days).
4. Send an HTTP request to create a topic.
5. If you get a redirect, follow the redirect (send the request to the IP in the "Location" header).
6. Keep following the redirects and you never get a response.

**I used this [broker.conf](https://gist.github.com/ronfarkash/e70b88cde57e5f0984ded0795bb62eaf).**

**If you enable automatically follow redirects, the request will eventually return unauthorized 401 even though I provide a valid JWT that works with other non-topic related requests.**

Shutting down 2 brokers (out of 3), inevitbly resolves the issue since there would be only one topic owner.

**Expected behavior**
I expect the redirects to eventually give me a broker that has the response for my request.

**Desktop (please complete the following information):**
 - OS: CentOS 7

**Additional context**
Pulsar Version: 2.8.2 - 2.8.3 (may affect more versions, not tested)

As requested by @lhotari 
**jstack dumps:**
Bugged when 3 brokers are up:
- [Broker 1 - when it's bugged](https://gist.github.com/ronfarkash/bdb3f84d15a4e15cadd5b9a6a67c012d)
- [Broker 2 - when it's bugged](https://gist.github.com/ronfarkash/f23b61a75afe112e38020ced68fbeca4)
- [Broker 3 - when it's bugged](https://gist.github.com/ronfarkash/2f0a134293c6b51a9b8412108a489a55)

Not bugged when 1 broker is up:
- [Broker 1 - when it works](https://gist.github.com/ronfarkash/a30b2a3812f57b4d642058b0a98fc45c)

**Comment by mattisonchao** [comment]
I think i can help with it.

**Comment by ronfarkash** [comment]
@mattisonchao Are there any updates related to this issue?

**Comment by lhotari** [comment]
@ronfarkash Do you use the Pulsar Proxy?

**Comment by ronfarkash** [comment]
> @ronfarkash Do you use the Pulsar Proxy?

No, 3 brokers and I send requests directly to them.

**Comment by ronfarkash** [comment]
@mattisonchao Asking again if there is anything in the works for this issue?

**Comment by eolivelli** [comment]
It it not clear to me which API has the problem.
Do we have a simple reproducer?

**Comment by eolivelli** [comment]
Which pulsar version?

**Comment by ronfarkash** [comment]
> It it not clear to me which API has the problem. Do we have a simple reproducer?

Admin Rest API v2, as stated in the issue, if the HTTP request is related to topic ownership, it can start happening, and when it does start happening, a broker reset is required.



> Which pulsar version?

Stated above, 2.8.2

**Comment by eolivelli** [comment]
Thank you very much for your answers.
Do you see loads in the broker about bundle unloading or bundle splitting related to that namespace?

There were (and probably still they are) problems with unloading. Last week I was investigating some of these problems in case of OOM during bundle unloading.

**Comment by ronfarkash** [comment]
> Thank you very much for your answers. Do you see loads in the broker about bundle unloading or bundle splitting related to that namespace?
> 
> There were (and probably still they are) problems with unloading. Last week I was investigating some of these problems in case of OOM during bundle unloading.

I am not entirely sure if bundle unloading/splitting is the cause of the issue since I have not noticed any OOM problems, it almost seems random.

To my knowledge, there are multiple topic metadata & ownership issues that were being worked on, but sadly I am unaware of their status and have a hard time catching up due to busy schedule.

**Comment by mattisonchao** [comment]
@ronfarkash 
Sorry for the late reply, I will check it and try to reproduce it.

**Comment by ronfarkash** [comment]
As requested by @lhotari 
**jstack dumps:**

- [Broker 1 - when it's bugged](https://gist.github.com/ronfarkash/bdb3f84d15a4e15cadd5b9a6a67c012d)
- [Broker 2 - when it's bugged](https://gist.github.com/ronfarkash/f23b61a75afe112e38020ced68fbeca4)
- [Broker 3 - when it's bugged](https://gist.github.com/ronfarkash/2f0a134293c6b51a9b8412108a489a55)
- [Broker 1 - when it works](https://gist.github.com/ronfarkash/a30b2a3812f57b4d642058b0a98fc45c)

**I made Broker 1 work forcibly by shutting down the two other brokers therefore Broker 1 can't direct me to brokers which are down.**

**Comment by ronfarkash** [comment]
@mattisonchao added some more information on how to attempt to reproduce the issue.

**Comment by lhotari** [comment]
@ronfarkash What type of deployment is this? Is it a Kubernetes deployment?

**Comment by mattisonchao** [comment]
Hi, @ronfarkash 
When you get a new address, you need to make `authoritative=true`.

If you open the `Automatically follow redirects`, the broker will help you do that thing when redirected.

**Comment by mattisonchao** [comment]
Hi, @shaniMaayan 

Would you like to check PR #17401? it probably fixes this problem.

I will close this PR and I will reopen it when the problem appears again.
