### ISSUE TITLE
java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:8000

### ISSUE THREAD

**Issue by walkhan** [apache/pulsar#13982]
![a02ffd172af554ac4fcd4c5170c61c4](https://user-images.githubusercontent.com/16821730/151331558-ad5c8a4b-582b-4fd3-8b6a-e2d3016ae51c.png)

**Comment by Technoboy-** [comment]
How to reproduce this ?

**Comment by tisonkun** [comment]
Close as stale. Without a concrete reproduce we can nearly do nothing. Fail to bind a port is generally a local environment issue, said port occuiption, rather than any bug in upstream.
