### ISSUE TITLE
[Doc] Two environment variables about LOG_LEVEL are not documented

### ISSUE THREAD

**Issue by dave2wave** [apache/pulsar#13992]
### What issue do you find in Pulsar docs?

reference-cli-tools.md does not include descriptions of `PULSAR_LOG_LEVEL` and `PULSAR_LOG_ROOT_LEVEL` which in the cli tools default to `info` and override any setting in `PULSAR_LOG_CONF`

### What is your suggestion?

include these descriptions in the environment variable section.

### Do you have any references?

Review
```
bin/pulsar
bin/pulsar-admin-common.sh
bin/pulsar-perf
bin/pulsar-client
```

### Would you like to fix this issue?

Maybe, but there is a lot going on with documentation right now with three or four threads of change.

### Note

- [X] I have researched my question.

**Comment by momo-jun** [comment]
Ping @RobertIndie for taking a look.

**Comment by liangyepianzhou** [comment]
@dave2wave Do you mind adding the PULSAR_LOG_LEVEL and PULSAR_LOG_ROOT_LEVEL to the environment variable section in reference-cli-tools.md?

**Comment by tisonkun** [comment]
This seems something we should update the bin scripts instead of the docsite.
