### ISSUE TITLE
Make PersistentTopicsBase some methods async

### ISSUE THREAD

**Issue by Technoboy-** [apache/pulsar#14013]
## Motivation
PersistentTopicsBase has some sync methods. Decide to make them async.
Volunteers wanted for this.

## Methods
- [x] createNonPartitionedTopic @Technoboy- #14030
- [x] updatePartitionedTopic @Technoboy-  #14141
- [x] getPartitionedMetadata @Technoboy- #14153
- [x] getPartitionedTopicList @mattisonchao #14059
- [x] getStats @mattisonchao #14048
- [x] getInternalStats @mattisonchao #14047
- [ ] getManagedLedgerInfo @shibd No need to do
- [x] getBacklog @shibd #14057
- [x] getPermissionsOnTopic @liudezhi2098 #14179
- [x] grantPermissionsOnTopic @liudezhi2098 #14152
- [x] revokePermissionsOnTopic @liudezhi2098 #14149
- [x] skipMessages @liudezhi2098 #14045
- [x] peekNthMessage @liudezhi2098 #14039
- [x] examineMessage @RobertIndie #14062 
- [x] terminate @RobertIndie #14064 
- [x] compactionStatus @RobertIndie #14066 
- [x] deleteTopic @RobertIndie #14069 
- [x] triggerOffload @HQebupt #14027
- [x] offloadStatus @HQebupt #14027

**Comment by liudezhi2098** [comment]
getPermissionsOnTopic
 grantPermissionsOnTopic
 revokePermissionsOnTopic
 skipMessages
 peekNthMessage

**Comment by HQebupt** [comment]
I  can fix some @Technoboy-

**Comment by Technoboy-** [comment]
> I can fix some @Technoboy-

Thanks for your help. assigned.

**Comment by shibd** [comment]
Hi, I can fix some @Technoboy-

**Comment by HQebupt** [comment]
> getPermissionsOnTopic
> grantPermissionsOnTopic
> revokePermissionsOnTopic
> skipMessages
> peekNthMessage

I can fix some of them. @liudezhi2098

**Comment by HQebupt** [comment]
@mattisonchao Can I fix getStats and getInternalStats ? Thanks in advance.

**Comment by shibd** [comment]
@Technoboy- Current `getManagedLedgerInfo`  method are already async.

**Comment by RobertIndie** [comment]
* [x]  examineMessage @RobertIndie https://github.com/apache/pulsar/pull/14062
* [x]  terminate @RobertIndie https://github.com/apache/pulsar/pull/14064
* [x]  compactionStatus @RobertIndie https://github.com/apache/pulsar/pull/14066
* [x]  deleteTopic @RobertIndie https://github.com/apache/pulsar/pull/14069

**Comment by lhotari** [comment]
> PersistentTopicsBase has some sync methods. Decide to make them async.
Volunteers wanted for this.

@Technoboy- @codelipenghui @merlimat Why are these changes made? The issue description doesn't describe any problem, just a decision. 

Since there are a lot of these sync -> async changes, it would be good to always open a discussion on the dev-mailing list to get a consensus of the problem that is being solved. In Apache Pulsar, we make all major decisions on the mailing list.

@Technoboy- Could you start a dev-mailing list thread on the topic which describes the problem, the assumptions and the solution? /cc @mattisonchao

**Comment by lhotari** [comment]
I didn't receive a reply to my questions. I have taken these sync->async changes to discussion on the mailing list in the 2.10.0 release thread. https://lists.apache.org/thread/ggsywqsvwpb1yw8wh490mp8mbgzgxch5 .

**Comment by lhotari** [comment]
@codelipenghui Thank you for replying on the mailing list in thread https://lists.apache.org/thread/tn7rt59cd1k724l4ytfcmzx1w2sbtw7l . I have followed up with PR #14320 .

**Comment by Technoboy-** [comment]
All the tracked methods have been resolved.
