### ISSUE TITLE
Prometheus summaries for rate_in or rate_out are incorrect when using short connections for production or consumption

### ISSUE THREAD

**Issue by codertmy** [apache/pulsar#14023]
**Describe the bug**
Prometheus summaries for rate_in or rate_out are incorrect when using short connections for production or consumption.

**To Reproduce**
1、Producing message as follow:
while (true) {
   Producer<String> stringProducer = client.newProducer(Schema.STRING)
        .topic("my-topic")
        .create();
   stringProducer.send("My message");
   stringProducer.close();
}
2、View metrics
pulsar_rate_in{cluster="pulsar-cluster-iot"} 0 1643423953979
pulsar_rate_in{cluster="pulsar-cluster-iot",namespace="public/default"} 0.0 1643423955593
pulsar_throughput_in{cluster="pulsar-cluster-iot",namespace="public/default"} 0.0 1643423955593
pulsar_in_bytes_total{cluster="pulsar-cluster-iot",namespace="public/default"} 357648079110085 1643423955593
pulsar_in_messages_total{cluster="pulsar-cluster-iot",namespace="public/default"} 2378188398726 1643423955593

From metrics，we see that there are messages being produced all the time, but the rate_in is incorrect. The same problem exists in the scenario of consumption using short connections.

**Screenshots**
![image](https://user-images.githubusercontent.com/49866918/151644390-4086d52d-7256-403e-87ca-d580a3587615.png)

**Comment by tjiuming** [comment]
The metric calculated by a scheduler, schedule interval default 60s. So if you request /metric endpoint more than once in a same interval, the metric value isn't changed.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
