### ISSUE TITLE
[Doc] Loadconf parameters of producer/consumer may need updates in Java client page

### ISSUE THREAD

**Issue by momo-jun** [apache/pulsar#14042]
### What issue do you find in Pulsar docs?

Suggested by @RobertIndie, the loadconf parameters of producer/consumer in Java client page is very likely out-of-date and not aligned with code.

### What is your suggestion?

Need to update the loadconf parameters of producer/consumer in Java client page to align with code.

### Do you have any references?

https://pulsar.apache.org/docs/en/client-libraries-java/#configure-producer
https://pulsar.apache.org/docs/en/client-libraries-java/#configure-consumer

### Would you like to fix this issue?

Love to. File a record here to track the issue.

### Note

- [X] I have researched my question.

**Comment by Anonymitaet** [comment]
@momo-jun @RobertIndie what are the original code files? I want to check whether these configurations (doc) can be generated from code files automatically.

**Comment by RobertIndie** [comment]
@Anonymitaet Here are the original code files: https://github.com/apache/pulsar/tree/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf The parameters in the loadConf come from the fields in the configuration data class such as `ProducerConfigurationData`. It seems difficult to generate the doc automatically.

**Comment by Anonymitaet** [comment]
@RobertIndie seems it is workable. I've recorded here: https://github.com/apache/pulsar/issues/14184

**Comment by momo-jun** [comment]
Closed the issue since it has been tracked in https://github.com/apache/pulsar/issues/14184.
