### ISSUE TITLE
Failed to get Manifest for - pulsar-client-2.9.1.jar

### ISSUE THREAD

**Issue by rillo-carrillo** [apache/pulsar#14132]
For some reason I keep getting this error when try: mvn install package

with next dependency:
<dependency>
      <groupId>org.apache.pulsar</groupId>
      <artifactId>pulsar-client</artifactId>
      <version>2.9.1</version>
</dependency>

Error:
Error assembling JAR: Failed to get Manifest for - pulsar-client-2.9.1.jar. Please verify if jar file is valid, the MANIFEST.MF should be first or second entry in the jar file. Use Command - jar tf <Jar_File_Path> to verify.

**Comment by tisonkun** [comment]
I remember that 2.9.1 is a yanked version. It should work well if you use any current maintained versions.
