### ISSUE TITLE
A Broker was shutdown.

### ISSUE THREAD

**Issue by xiaobing0508** [apache/pulsar#14140]
**Describe the bug**
Topic cannot read and write.

**To Reproduce**
1. Create a role.
2. Grant permission.

**Additional context**
Consumer was not registered on the connection , Producer was not registered on the connection , There are a lot of in the log.

**Comment by eolivelli** [comment]
Can you please share more details?
Which Pulsar version? How did you deploy it? How did you create the topic? How did you set permissions? How did you configured authentication on the client?

**Comment by xiaobing0508** [comment]
Pulsar version is 2.9.1. Just upgraded. Running on four physical machine. We use authentication is JWT. Not one topic cannot be used, but the whole tenant. The cluster was running normally before.

**Comment by nodece** [comment]
Could you provide the broker log?

**Comment by nodece** [comment]
Could you build a Pulsar by using the master branch codebase?  I guess it has been fixed by #13885.

**Comment by xiaobing0508** [comment]
How use master branch build Pulsar ?

**Comment by nodece** [comment]
@xiaobing0508 See https://github.com/apache/pulsar#build-pulsar

**Comment by xiaobing0508** [comment]
Which version is the main branch? Do I want to Canary upgrade?

**Comment by nodece** [comment]
You can build the Pulsar on your computer for testing.
```
git clone https://github.com/apache/pulsar
mvn clean install -DskipTests

### Config authentication in standalone.conf
### Do somethings

bin/pulsar standalone
```

**Comment by xiaobing0508** [comment]
@nodece I failed to compile with Maven.

**Comment by nodece** [comment]
Could you provide the build log?

**Comment by xiaobing0508** [comment]
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (rename-epoll-library) on project pulsar-broker-shaded: Command execution failed.: Process exited with an error: 127 (Exit value: 127) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :pulsar-broker-shaded

**Comment by nodece** [comment]
Try `mvn install -Pcore-modules,-main -DskipTests`.

**Comment by xiaobing0508** [comment]
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13:34 min
[INFO] Finished at: 2022-03-01T13:33:39+08:00
Is this compilation successful?
What should I do next?

**Comment by nodece** [comment]
You can find Pulsar package in `/Users/$yourname/.m2/repository/org/apache/pulsar/pulsar/$version/pulsar-2.10.0-SNAPSHOT.tar.gz`.

**Comment by xiaobing0508** [comment]
Is this package binary?

**Comment by nodece** [comment]
Yes

**Comment by nodece** [comment]
Sorry, This correct path: `distribution/server/target/apache-pulsar-2.10.0-SNAPSHOT-bin.tar.gz`.

**Comment by tisonkun** [comment]
Closed as stale.
