### ISSUE TITLE
hub.docker.com apachepulsar/pulsar-standalone Apple Silicon arm64 M1 processor

### ISSUE THREAD

**Issue by axiopisty** [apache/pulsar#14174]
**Is your enhancement request related to a problem? Please describe.**
A clear and concise description of what the enhancement is.

*Docker images made available at hub.docker.com are only available for linux/amd64.*

**Describe the solution you'd like**

*Docker images made available at hub.docker.com are made available for multiple architectures, specifically for linux/arm64, to support Apple Silicon.*

**Describe alternatives you've considered**

*None.*

**Additional context**

*None*

**Comment by axiopisty** [comment]
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by tisonkun** [comment]
Now we support Apple M1.
