### ISSUE TITLE
[Website] generate pages automatically for producer/consumer parameters (Java client)

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#14184]
When resolving https://github.com/apache/pulsar/issues/14042, I'm wondering whether we can generate docs automatically for [producer/consumer parameters of the Java client](https://pulsar.apache.org/docs/en/client-libraries-java/#configure-producer) to avoid much manual work.

![image](https://user-images.githubusercontent.com/50226895/153133314-ea6f619b-cb1d-4d84-b7cb-1c82baf806c9.png)

Then I discussed w/ @tuteng, he thought yes:
- Docs can be generated automatically from the [code files](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ProducerConfigurationData.java).
- These "docs" are independent web pages (just like [pulsar-admin website](https://pulsar.apache.org/tools/pulsar-admin/)) rather than tables in the existing documentation.

Anyone would like to implement this automation? Thanks

**Comment by tisonkun** [comment]
Closed as done.
