### ISSUE TITLE
Integrate package service with function

### ISSUE THREAD

**Issue by hangc0276** [apache/pulsar#14224]
**Is your enhancement request related to a problem? Please describe.**
Currently, I'm implementing PIP-117 https://github.com/apache/pulsar/issues/13302 , changing from using DistributedLog to using local filesystem to store the jars directly in the data folder instead of uploading them into BK. 

However, I found the current function creation will directly store the jar file into DistributedLog by calling `WorkerUtils.uploadFileToBookkeeper` no matter we create function by jar file or functionPkgUrl. It doesn't store the jar file by the unified package service interface. Thus it is hard to store the jars into filesystem by configuration.

**Describe the solution you'd like**
We'd better integrate the package service into function, and use the unified package service api to read and write jar files.

**Comment by gaozhangmin** [comment]
Can I help with it?

**Comment by hangc0276** [comment]
@gaozhangmin Thanks for your help, I have assigned this issue to you.

**Comment by liangyuanpeng** [comment]
remove-lifecycle stale
