### ISSUE TITLE
what mean about：boundary of batching delay

### ISSUE THREAD

**Issue by startjava** [apache/pulsar#14234]
https://pulsar.apache.org/docs/en/concepts-messaging/#routing-modes

Please note that round-robin is not done per individual message but rather it's set to the same boundary of batching delay, to ensure batching is effective.

**Comment by NiceChi** [comment]
当初看到这段话的时候也有同样的疑惑，现在回过头来看的话，我的理解是，这里面的轮询并不是只针对单个 message 的轮询，如果 producer 开启了 batch 的话，那就是以 batch 作为单位来进行轮询

不知道这么理解对不对

**Comment by startjava** [comment]
感谢，期待官方或大佬确认




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/pulsar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月11日(星期五) 下午4:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/pulsar] 文档读不懂，请求帮助 (Issue #14234)





 
当初看到这段话的时候也有同样的疑惑，现在回过头来看的话，我的理解是，这里面的轮询并不是只针对单个 message 的轮询，如果 producer 开启了 batch 的话，那就是以 batch 作为单位来进行轮询
 
不知道这么理解对不对
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shibd** [comment]
> 当初看到这段话的时候也有同样的疑惑，现在回过头来看的话，我的理解是，这里面的轮询并不是只针对单个 message 的轮询，如果 producer 开启了 batch 的话，那就是以 batch 作为单位来进行轮询
> 
> 不知道这么理解对不对

That's right

**Comment by startjava** [comment]
那个什么批处理延迟和边界，代表什么意思呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/pulsar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月11日(星期五) 下午4:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/pulsar] 文档读不懂，请求帮助 (Issue #14234)





  
当初看到这段话的时候也有同样的疑惑，现在回过头来看的话，我的理解是，这里面的轮询并不是只针对单个 message 的轮询，如果 producer 开启了 batch 的话，那就是以 batch 作为单位来进行轮询
 
不知道这么理解对不对
  
That's right
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Jason918** [comment]
> 那个什么批处理延迟和边界，代表什么意思呢

Basically, switch to next partition every `batchingMaxPublishDelay`.
