### ISSUE TITLE
[Performance Tuning] The performance improvement of Apache pulsar has encountered a bottleneck. No matter how to modify the configuration parameters, the performance can not be effectively improved

### ISSUE THREAD

**Issue by NiceChi** [apache/pulsar#14233]
### Deployment environment

Apache pulsar is deployed in a standalone manner. The three components of zookeeper, bookkeeper and broker are deployed on the same server (8-core CPU, 16g memory and a 7200 RPM HDD). At the same time, this server is basically only used to run pulsar services

In addition, there are two other servers in the same LAN (the specificationof these two servers is consistent with that of the server running pulsar), which run pulsar perf producer and pulsar perf consumer clients respectively, and publish and consume msg to pulsar server respectively

- The default size of MSG sent by pulsar perf producer is 1KB

### Throughput  
At present, no matter how to adjust the JVM size of the component, the publish pending queue size of the broker, the managedledgercache size, the write / read cache size of bookie, the number of related worker threads, the sending queue size of pulsar perf producer and other parameters, the throughput of pulsar perf producer is always about 8W MSG / S ~ 9W MSG / s
- The amount of data sent by pulsar-perf is almost 600 MIB / S ~ 700 MIB / s. 
- The write pressure of the hard disk on the pulsar server is almost always about 160 MIB / S ~ 190 MIB / s. 
- The total utilization rate of the CPU is almost below 50%, but the iowait of some cores can reach 95%,
- there is basically no read pressure on the disk, It should be because the consumer directly takes the data from the managedledgercache
- the server running pulsar still has a lot of space in memory that has not been used

### My question

Finally, my question is: in this case, is it because the write capacity of the hard disk of the pulsar server has reached the bottleneck that can not improve the throughput of the producer?

Thx a lot :)

**Comment by NiceChi** [comment]
### test result via pulsar-perf producer 

08:13:19.198 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Throughput produced:  875381 msg ---  87516.3 msg/s ---    683.7 Mbit/s --- failure      0.0 msg/s --- Latency: mean:  52.876 ms - med:  20.207 - 95pct: 249.615 - 99pct: 455.123 - 99.9pct: 502.465 - 99.99pct: 508.589 - Max: 508.685
08:13:29.746 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Throughput produced: 1849891 msg ---  91580.3 msg/s ---    715.5 Mbit/s --- failure      0.0 msg/s --- Latency: mean: 498.103 ms - med: 515.241 - 95pct: 960.091 - 99pct: 1093.815 - 99.9pct: 1122.831 - 99.99pct: 1131.015 - Max: 1131.223
08:13:40.364 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Throughput produced: 2905938 msg ---  99398.3 msg/s ---    776.5 Mbit/s --- failure      0.0 msg/s --- Latency: mean: 1088.251 ms - med: 1089.967 - 95pct: 1561.623 - 99pct: 1677.375 - 99.9pct: 1733.335 - 99.99pct: 1741.903 - Max: 1742.007
08:13:50.596 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Throughput produced: 3810687 msg ---  88421.4 msg/s ---    690.8 Mbit/s --- failure      0.0 msg/s --- Latency: mean: 1611.106 ms - med: 1502.415 - 95pct: 2161.119 - 99pct: 2506.303 - 99.9pct: 2525.871 - 99.99pct: 2527.695 - Max: 2528.335
08:14:00.684 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Throughput produced: 4716034 msg ---  89742.4 msg/s ---    701.1 Mbit/s --- failure      0.0 msg/s --- Latency: mean: 1594.227 ms - med: 1489.903 - 95pct: 2224.655 - 99pct: 2335.935 - 99.9pct: 2482.719 - 99.99pct: 2484.191 - Max: 2484.927
08:14:10.774 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Throughput produced: 5615882 msg ---  89195.6 msg/s ---    696.8 Mbit/s --- failure      0.0 msg/s --- Latency: mean: 1631.398 ms - med: 1521.023 - 95pct: 2285.535 - 99pct: 2413.855 - 99.9pct: 2445.103 - 99.99pct: 2446.287 - Max: 2446.655
08:14:20.863 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Throughput produced: 6507666 msg ---  88378.4 msg/s ---    690.5 Mbit/s --- failure      0.0 msg/s --- Latency: mean: 1669.414 ms - med: 1560.631 - 95pct: 2295.327 - 99pct: 2558.671 - 99.9pct: 2576.607 - 99.99pct: 2577.631 - Max: 2577.887
08:14:30.950 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Throughput produced: 7425263 msg ---  90974.2 msg/s ---    710.7 Mbit/s --- failure      0.0 msg/s --- Latency: mean: 1730.611 ms - med: 1649.391 - 95pct: 2397.487 - 99pct: 2599.951 - 99.9pct: 2652.735 - 99.99pct: 2654.143 - Max: 2654.431
08:14:41.055 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Throughput produced: 8299595 msg ---  86562.4 msg/s ---    676.3 Mbit/s --- failure      0.0 msg/s --- Latency: mean: 1657.870 ms - med: 1572.207 - 95pct: 2387.599 - 99pct: 2430.863 - 99.9pct: 2444.319 - 99.99pct: 2446.687 - Max: 2447.167
08:14:51.154 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Throughput produced: 9235450 msg ---  92741.4 msg/s ---    724.5 Mbit/s --- failure      0.0 msg/s --- Latency: mean: 1615.089 ms - med: 1512.783 - 95pct: 2243.711 - 99pct: 2356.495 - 99.9pct: 2366.927 - 99.99pct: 2367.519 - Max: 2367.887
08:15:01.242 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Throughput produced: 10089040 msg ---  84536.6 msg/s ---    660.4 Mbit/s --- failure      0.0 msg/s --- Latency: mean: 1664.701 ms - med: 1563.031 - 95pct: 2200.735 - 99pct: 2847.119 - 99.9pct: 2861.167 - 99.99pct: 2862.719 - Max: 2863.071
08:15:10.114 [pulsar-perf-producer-exec-1-1] INFO  org.apache.pulsar.testclient.PerformanceProducer - ------------------- DONE -----------------------
08:15:10.208 [pulsar-perf-producer-exec-1-1] INFO  org.apache.pulsar.testclient.PerformanceProducer - Aggregated latency stats --- Latency: mean: 1384.224 ms - med: 1488.583 - 95pct: 2223.519 - 99pct: 2526.335 - 99.9pct: 2876.991 - 99.99pct: 2959.215 - 99.999pct: 3059.823 - Max: 3060.239
08:15:15.211 [Thread-1] INFO  org.apache.pulsar.testclient.PerformanceProducer - Aggregated throughput stats --- 10951697 records sent --- 86800.055 msg/s --- 678.125 Mbit/s
08:15:15.272 [Thread-1] INFO  org.apache.pulsar.testclient.PerformanceProducer - Aggregated latency stats --- Latency: mean: 1925.447 ms - med: 1855.311 - 95pct: 2669.967 - 99pct: 2677.551 - 99.9pct: 2679.759 - 99.99pct: 2679.919 - 99.999pct: 2679.951 - Max: 2679.951

**Comment by eolivelli** [comment]
hello, if you want to do performance testing I suggest you to:
- install the component on separate machines
- for write workloads the bottleneck is usually the disk of the Journal on the bookie, ensure to have a good disk
- usually it is better to enlarge the writeCache on the Bookie in conf/bookkeeper.conf:
```
  dbStorage_rocksDB_blockCacheSize: '4294967296'
  dbStorage_writeCacheMaxSizeMb: '2048'
```
- you can use partitioned topics in order to spread the load among several brokers, and also even with a single broker with partitioned topics you can use better the resources of the broker

**Comment by lhotari** [comment]
> The three components of zookeeper, bookkeeper and broker are deployed on the same server (8-core CPU, 16g memory and a 7200 RPM HDD)

> Finally, my question is: in this case, is it because the write capacity of the hard disk of the pulsar server has reached the bottleneck that can not improve the throughput of the producer?

It is crucial for performance to use fast SSD disks for Zookeeper and Bookkeeper. Using spinning HDD disks with Pulsar is not recommended since performance can suffer.

If you cannot afford SSDs for all data, it's possible to use HDD disks for Bookkeeper ledger disks. Bookkeeper can use separate journal and ledger disks. When using HDD disks on bare metal, a battery backed write cache (BBWC) setup improves write throughput performance and reduces write latency drastically.

Besides bottlenecks in Disk IO, there might be multiple reasons why you have performance problems. Jack Vanlightly has also blog posts about this in https://medium.com/splunk-maas/the-importance-of-mental-models-for-incident-response-da1bfcfdcacd . Having Prometheus/Grafana dashboards will help understand the bottlenecks and what is needed to resolve the issues.
