### ISSUE TITLE
[2.9.1]python client define schema ,value 0 become None

### ISSUE THREAD

**Issue by algoqt** [apache/pulsar#14264]
**Describe the bug**
python client define schema, Integer() Float() when set to 0 become unset ,see example code below?

`class Example(Record):
    a = String()
    b = Integer()
    c = Boolean()
    d = Float()

test1=Example(a='Hello1', b=1,d=0.0)
test2=Example(a='Hello2', b=0,d=5.3)

print(test1.b,test1.d)          # why test1.d is set to 0.0 then become None
print(test2.b,test2.d)

print(test1.b==0,test1.d==0.0)   #  # why test1.d donest equal 0.0
print(test2.b==0,test2.d==0.0)
`

![image](https://user-images.githubusercontent.com/93410715/153814360-54782593-53f3-467c-8097-b2c13a92ec30.png)

**Comment by yaalsn** [comment]
This bug is same with https://github.com/apache/pulsar/issues/12485, and it'll be fixed in 2.9.2 version https://github.com/apache/pulsar/pull/12489/files.
