### ISSUE TITLE
If the producer name is not set, is the default value "default"?

### ISSUE THREAD

**Issue by startjava** [apache/pulsar#14272]
Producer name：The name of the producer who produces the message. If you do not specify a producer name, the default name is used.

Whether this default value is default or other default values, please refer to the website:
https://pulsar.apache.org/docs/en/concepts-messaging/
“If you do not specify a producer name, the default name is used.”   Default does not use italics font

thank you !

**Comment by gaozhangmin** [comment]
the default name begin with `producer`. You can check the cod self.

**Comment by startjava** [comment]
@gaozhangmin But I'm a beginner and haven't involved the code yet,
