### ISSUE TITLE
please Can briefly explain Avro

### ISSUE THREAD

**Issue by startjava** [apache/pulsar#14275]
pulsar doc say：
It is used to construct a message. You can set message properties such as the message key, message value with TypedMessageBuilder.
When you set TypedMessageBuilder, set the key as a string. If you set the key as other types, for example, an AVRO object, the key is sent as bytes, and it is difficult to get the AVRO object back on the consumer.

I don't know what Avro is, and google.com has less information. Can you explain it briefly, thank you

**Comment by tuhaihe** [comment]
@startjava Hi, welcome to join [Apache Pulsar slack](https://apache-pulsar.slack.com/) channel to ask. I think this issue shouldn't be labeled `type/bug`.

**Comment by startjava** [comment]
@tuhaihe  bu new issues  no has "type/question" option

**Comment by BewareMyPower** [comment]
You can use `help wanted` label.

**Comment by codelipenghui** [comment]
@startjava Here is the Avro spec https://avro.apache.org/docs/current/
