### ISSUE TITLE
when Consumer close,retryLetterProducer and deadLetterProducer will not close

### ISSUE THREAD

**Issue by leizhiyuan** [apache/pulsar#14284]
**Describe the bug**
when Consumer close,retryLetterProducer and deadLetterProducer will not close, it will produce 

Topic reached max producers limit  for retry topic sometimes 

**To Reproduce**

review the code 

**Expected behavior**
when Consumer close,retryLetterProducer and deadLetterProducer will close

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tisonkun** [comment]
Closed by https://github.com/apache/pulsar/pull/19858.
