### ISSUE TITLE
[Doc search] Missing search results in 2.9.1 Documentation

### ISSUE THREAD

**Issue by momo-jun** [apache/pulsar#14285]
## Issue Description ##
When searching for "delayed message" in 2.9.1 documentation, we cannot get the correct search results as expected.
### Seach Results of 2.9.1 ###
![image](https://user-images.githubusercontent.com/60642177/153982180-89d7fa34-dd77-4003-87a2-a4e9a1416342.png)

### Seach Results of other versions ###
![image](https://user-images.githubusercontent.com/60642177/153982235-41fe074e-9a9c-469c-ba4b-31e7d1b8a6d8.png)

## Analysis ##
Discussed with @tuteng and @urfreespace, we found the following issues that lead to the current one:
1. The data for 2.9.1 failed to be successfully crawled.
2. The Algolia docsearch repo (https://github.com/algolia/docsearch-configs) has been archived without maintenance, and there is no way to submit issue or pull requests.

## Suggested Actions ##
1. Keep Algolia as it is since the doc site is being upgraded as a whole.
2. Look for an alternative doc search engine that can be adapted to a newly upgraded doc site.

Hi @tuteng and @urfreespace, feel free to add if I missed anything.

**Comment by geomagilles** [comment]
FYI, the email to contact for assistance is: documentationsearch@algolia.com

**Comment by Anonymitaet** [comment]
As discussed w/ @urfreespace, this issue is caused by Algolia ('s limitation), it's hard to fix it from our side.
