### ISSUE TITLE
Error: could not open `{testJacocoAgentArgument}'

### ISSUE THREAD

**Issue by congbobo184** [apache/pulsar#14294]
If run testNG in local throw this issue, we need to change the config of this idea.  uncheck argLine

![image](https://user-images.githubusercontent.com/39078850/154028702-619da70a-55a9-4894-86be-8b27c7f24704.png)
link https://github.com/apache/pulsar/pull/14278

**Comment by lhotari** [comment]
I found the IntellIJ bug that is marked as fixed although it's not resolved.

**Comment by lhotari** [comment]
This seems to be the open bug in IntelliJ https://youtrack.jetbrains.com/issue/IDEA-278750
