### ISSUE TITLE
[Doc] How does pulsar achieve synchronous replication of data across IDCs for disaster recovery?

### ISSUE THREAD

**Issue by iamqq23ue** [apache/pulsar#14291]
### What issue do you find in Pulsar docs?

geo-replication can only replicate data asynchronously.

If bookkeeper is deployed across IDCs, there is no way to ensure that entry replicas are distributed in different 

IDCs

Is there a better disaster recovery plan?

### What is your suggestion?

I hope there can be an official disaster recovery plan.

### Do you have any references?

no

### Would you like to fix this issue?

If no one answers, I'll do some research

### Note

- [X] I have researched my question.

**Comment by Anonymitaet** [comment]
@iamqq23ue welcome to research and update docs, thanks

**Comment by gaoran10** [comment]
Sorry, I'm not sure about your question, could you describe more details?

**Comment by tisonkun** [comment]
Closed as stale and no response.

You can ask questions on https://github.com/apache/pulsar/discussions/categories/q-a instead.
