### ISSUE TITLE
help/want：what mean "total number of batches"？

### ISSUE THREAD

**Issue by startjava** [apache/pulsar#14292]
Batching
When batching is enabled, the producer accumulates and sends a batch of messages in a single request. The batch size is defined by the maximum number of messages and the maximum publish latency. Therefore, the backlog size represents the total number of batches instead of the total number of messages.

help/want：what mean "total number of batches"？the "total number" represents byte unit ? or in "backlog status" batches number ? or Number of batch packets to be sent in the future？？

thank you !

**Comment by Jason918** [comment]
One `batch` means one send request, also means one entry in bookkeeper.

**Comment by Jason918** [comment]
There may be multi messages in one batch
