### ISSUE TITLE
Adding Ectd integration tests 

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#14295]
**Is your enhancement request related to a problem? Please describe.**
Pulsar supports Ectd as metadata service backend in https://github.com/apache/pulsar/pull/13225
It's better to have an integration test to use ectd as the metadata service of bookkeeper and pulsar.

**Comment by gaozhangmin** [comment]
@codelipenghui  Please assign to me.

**Comment by tisonkun** [comment]
Closing as stale and no one worked on it. Please open a new issue if you volunteer to do it.
