### ISSUE TITLE
expose git info to endpoint of webservice

### ISSUE THREAD

**Issue by leizhiyuan** [apache/pulsar#14307]
**Is your enhancement request related to a problem? Please describe.**

1. now ,we only print the info to log, but when we want to inspect the git info after a while, the log maybe deleted .

<img width="720" alt="image" src="https://user-images.githubusercontent.com/2684384/154168970-68a78434-d774-45da-acce-e151186b87be.png">

2. if we want to expose rop and aop info to this endpoint, now it is impossible, because webservice started first, and protocol Handler started later, they cannot add endpoint dynamically, we need a new way to allow protocol handers add endpoint in init method
**Describe the solution you'd like**

<img width="799" alt="image" src="https://user-images.githubusercontent.com/2684384/154169031-db281517-bd8f-4f8c-98f8-a98d7b7b3526.png">

add a servlet

**Describe alternatives you've considered**

**Additional context**

**Comment by codelipenghui** [comment]
https://github.com/apache/pulsar/pull/11498 you should use the additional servlet to add new servlets.  Here is an example in mop https://github.com/streamnative/mop/blob/d280dc7cec003fa0832a2530fdfdb6969774377f/mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTAdditionalServlet.java
