### ISSUE TITLE
Pulsar release 2.8.2 documentation package is missing

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#14312]
**Describe the bug**

The 2.8.2 release isn't listed on this page:
https://pulsar.apache.org/en/versions/

The documentation is missing for 2.8.2:
https://pulsar.apache.org/docs/en/2.8.2/
(compare to 2.8.1: https://pulsar.apache.org/docs/en/2.8.1/ )

Pulsar 2.8.2 can be found on the download page and release notes. These are fine:
https://pulsar.apache.org/download
http://pulsar.apache.org/release-notes

**Comment by lhotari** [comment]
@315157973 Could you please take a look? I believe that the step [Update the site for minor releases](https://github.com/apache/pulsar/wiki/Release-process#update-the-site-for-minor-releases) is missing for 2.8.2 .

**Comment by 315157973** [comment]
OK, I will take a look

**Comment by Anonymitaet** [comment]
Hi @315157973 

For a minor release, we need to modify the following types of files:
- doc set (includes more than 100+ .md files)
- version-x.x.x-sidebars.json
- release.json
- versions.json

I've checked the 2.8.2 PR history, the [versions.json](https://github.com/apache/pulsar/blob/master/site2/website/versions.json) has not been updated. I guess you need to update it.

<img width="709" alt="image" src="https://user-images.githubusercontent.com/50226895/154236575-51de6bd1-8eba-450e-a79d-d791dacca51b.png">
