### ISSUE TITLE
[idea] NamespaceProducer 

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#1432]
*Problem*

If a namespace has lots of topics and each topic might have relative low traffic, it is not every efficient to create a producer for each topic. It might be nice to have a namespace-level producer to allow producing messages to topics within it.

something like:

```
public interface NamespaceProducer {

     CompletableFuture<MessageId> produce(String topic, Message msg);

}
```

**Comment by sijie** [comment]
this is an idea brought up at pulsar slack channel. bringing it up here to see what people is thinking about this.

**Comment by zubchenok** [comment]
This is really needed to implement an efficient way for millions to millions messaging.

**Comment by tisonkun** [comment]
Closed as stale.

The development of this initiative seems stalled and this thread doesn't contain too much information. If one wants to revive the proposal, please open a brand new thread.
