### ISSUE TITLE
[SECURITY] Hardcode the password in RabbitMQAbstractConfig

### ISSUE THREAD

**Issue by AliIoT** [apache/pulsar#14326]
https://github.com/apache/pulsar/blob/64dc5374b6f6eb59a69a036697e16c8b21a31b16/pulsar-io/rabbitmq/src/main/java/org/apache/pulsar/io/rabbitmq/RabbitMQAbstractConfig.java#L74

Is it ok to hardcode the password in RabbitMQAbstractConfig? It may have a security risk

**Comment by tisonkun** [comment]
This is a config that you can overwrite by passing a new value.

Closed as invalid.
