### ISSUE TITLE
How to create coverage report by jacoco when run unit test?

### ISSUE THREAD

**Issue by liruixl** [apache/pulsar#14322]
### What issue do you find in Pulsar docs?

How to create coverage report by jacoco when run unit test? 
when I run `mvn test`, nothing was be created. It should be created by jacoco at target/site/index.html.
Refer to:https://www.eclemma.org/jacoco/trunk/doc/maven.html

### What is your suggestion?

add explanations about unit test and coverage report.

### Do you have any references?

Jacoco doc: https://www.eclemma.org/jacoco/trunk/doc/maven.html

### Would you like to fix this issue?

I have researched my question, but the coverage report is still not created, I dont know what the problem is.

### Note

- [X] I have researched my question.

**Comment by lhotari** [comment]
Passing `-Pmain,coverage` can be used on the maven command line. Jacoco configuration is part of the `coverage` maven profile. @nicoloboschi is working on a contribution to enable code coverage and collect and report the coverage reports using codecov.io .

**Comment by liruixl** [comment]
thanks,  I have got the coverage data for unit tests. Now I know  how to use maven profile, it need activation!

**Comment by Anonymitaet** [comment]
@liruixl is this an issue related to doc?

**Comment by liruixl** [comment]
Oh, sorry. It is not. I created a test issue: #14321
