### ISSUE TITLE
[SECURITY] Hardcode the password in debezium-{}-config.yaml

### ISSUE THREAD

**Issue by AliIoT** [apache/pulsar#14324]
Hi, Should use "*****" to replace the password in debezium-{}-config.yaml? It may have a security risk

pulsar/pulsar-io/debezium/src/main/resources/
- debezium-mssql-source-config.yaml
- debezium-oracle-source-config.yaml
- debezium-postgres-source-config.yaml

**Comment by tisonkun** [comment]
I think they're placeholder only. But still confused about how they're in use.

@dlg99 as you implemented #12256 include part of these files, do you have ideas on this question?

**Comment by dlg99** [comment]
these aren't real (or default) passwords AFAIK. These are just examples.

**Comment by tisonkun** [comment]
Close as not an issue.

If anyone has a concrete suggestion on "improving" here, they can open a new issue.
