### ISSUE TITLE
[SECURITY] Weak security algorithm used by AuthenticationProviderBasic

### ISSUE THREAD

**Issue by AliIoT** [apache/pulsar#14323]
https://github.com/apache/pulsar/blob/64dc5374b6f6eb59a69a036697e16c8b21a31b16/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderBasic.java#L92

**Comment by tisonkun** [comment]
I believe this is by design that from the `encryptedPassword` it's inferred to be md5 algorithm.

Closed as invalid.
