### ISSUE TITLE
[Doc] Link to C++ client API docs does not work

### ISSUE THREAD

**Issue by pksilen** [apache/pulsar#14339]
### What issue do you find in Pulsar docs?

On page: https://pulsar.apache.org/docs/en/client-libraries-cpp/

Link to API docs does not work. The link https://pulsar.apache.org/api/cpp/2.9.0-SNAPSHOT does not work.

### What is your suggestion?

Correct the link

### Do you have any references?

No

### Would you like to fix this issue?

No

### Note

- [X] I have researched my question.

**Comment by BewareMyPower** [comment]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/18204803/154432799-b3aeca3f-f39d-4867-a5ee-3212519127c4.png">

https://pulsar.apache.org/api/cpp/2.9.0-SNAPSHOT works well. Regarding to the https://pulsar.apache.org/docs/en/client-libraries-cpp/ page, it looks like the Pulsar website is being updated at this moment.

**Comment by Anonymitaet** [comment]
@BewareMyPower +1

@pksilen you can access the same documentation via here
https://pulsar.staged.apache.org/docs/en/next/client-libraries-cpp/
<img width="1960" alt="image" src="https://user-images.githubusercontent.com/50226895/154433240-6e1c2de2-4b0a-4165-9f3e-8d2a59d6e49d.png">

**Comment by Anonymitaet** [comment]
Ping @urfreespace

**Comment by Anonymitaet** [comment]
https://pulsar.apache.org/api/cpp/2.9.0-SNAPSHOT does work now
