### ISSUE TITLE
Pulsar stucked and all producer on topic disconnected

### ISSUE THREAD

**Issue by xiaofan-luan** [apache/pulsar#14337]
**Describe the bug**
Hi all, the detailed discussion can be seen here:
https://github.com/milvus-io/milvus/issues/15535#issuecomment-1042597113

From the user's log there is producerBlocked Quota exception and we've seen some Connection reset by peer exception as well.
Could this be related? How do we know which consumer is not consuming correctly and causing the producerBlocked Quota exception ?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by codelipenghui** [comment]
Looks like we can close the issue since https://github.com/milvus-io/milvus/issues/15535#issuecomment-1042597113 has provided the solution.

**Comment by xiaofan-luan** [comment]
thanks for the help, we hit many backlog issues and we will try to sum up some rules to follow

**Comment by sicklife** [comment]
> Looks like we can close the issue since [milvus-io/milvus#15535 (comment)](https://github.com/milvus-io/milvus/issues/15535#issuecomment-1042597113) has provided the solution.

In this issue you mentioned above, they solved the problem by clear the backlog，which I think didn't real solve the problem.

I have met with the same problem. Shut down all proudcers forcely and wait for a long time then restart can solve the problem. But I want to know why this happen? What I need to do to solve this problem completely~
