### ISSUE TITLE
[Website] The new version website broken the CLI tab

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#14332]
**Describe the bug**
There are for options under the CLI tab

<img width="1461" alt="image" src="https://user-images.githubusercontent.com/12592133/154400493-c5941a96-0a65-4119-991f-bcd9ab07d582.png">

But each of them will return 404

<img width="877" alt="image" src="https://user-images.githubusercontent.com/12592133/154400539-718f74d6-9890-4e22-a586-2ea37d21ebe5.png">

**Comment by ethqunzhong** [comment]
had same problem， is it something wrong in pulsar.apache.org website? 
https://pulsar.apache.org/docs/zh-CN/pulsar-admin/
<img width="940" alt="image" src="https://user-images.githubusercontent.com/16517186/154401570-7716d1bd-4bae-4860-a602-d6aec3bb0ff7.png">

**Comment by ethqunzhong** [comment]
> 

you can visit in this link temporary
https://pulsar.apache.org/docs/next/
