### ISSUE TITLE
[Helm] Website update broke Helm charts

### ISSUE THREAD

**Issue by SakaSun** [apache/pulsar#14335]
**Describe the bug**
Website update broke Pulsar install through Helm charts

**To Reproduce**
1. Execute:
`helm repo add apache https://pulsar.apache.org/charts`
2. Following error appears:
`Error: looks like "https://pulsar.apache.org/charts" is not a valid chart repository or cannot be reached: failed to fetch https://pulsar.apache.org/charts/index.yaml : 404 Not Found`

**Expected behavior**
1. Execute:
`helm repo add apache https://pulsar.apache.org/charts`
2. Expected message:
`"apache" has been added to your repositories`

**Screenshots**
![helm-chart-not-found](https://user-images.githubusercontent.com/12901209/154410592-8c740c34-8bf8-45e1-891b-a242e8be73a6.png)

**Comment by dave2wave** [comment]
This was a temporary issue. We have reverted the change. Please create a new issue if this breaks once the new site goes live.
