### ISSUE TITLE
HttpLookupService do not support pulsar proxy

### ISSUE THREAD

**Issue by leizhiyuan** [apache/pulsar#14349]
**Is your enhancement request related to a problem? Please describe.**
A clear and concise description of what the enhancement is.

HttpLookupService do not support pulsar proxy, if  we use proxyip:8080 to conect ,it will not use proxy to send message, it will use the real broker. 

**Describe the solution you'd like**

BinaryProtoLookupService is ok

**Describe alternatives you've considered**

**Additional context**

**Comment by codelipenghui** [comment]
@leizhiyuan Interesting, if the client connects to pulsar proxy, the client should send messages to the proxy directly, not the broker. How do you check if the messages is send to the proxy first or not?
