### ISSUE TITLE
help:want：Does it support consumers to use different subscription modes to the same subscription?

### ISSUE THREAD

**Issue by startjava** [apache/pulsar#14369]
Does it support consumers to use different subscription modes to the same subscription?

**Comment by AnonHxy** [comment]
Not support. If consumers use different subscrption types,  the subscription type is decided by the consumer who first connects to the broker, and others will throw `new SubscriptionBusyException("Subscription is of different type")`. See for details: `org.apache.pulsar.broker.service.persistent.PersistentSubscription#addConsumer` @startjava
