### ISSUE TITLE
`acknowledge_cumulative()` does not work with a consumer subscribed to multiple topics. 

### ISSUE THREAD

**Issue by swjz** [apache/pulsar#14372]
**Describe the bug**
On `pulsar-client==2.9.1` (python), `acknowledge_cumulative()` does not work with a consumer subscribed to multiple topics. 

**To Reproduce**
Set up a pulsar server on `localhost:6650`. Create two topics `topic1` and `topic2`. Make sure each topic has at least one message in it so we can consume them later.

Run the following code to consume a message.

```python
import pulsar
from _pulsar import InitialPosition

client = pulsar.Client(service_url='pulsar://localhost:6650')

consumer = client.subscribe(['topic1', 'topic2'], subscription_name='test', initial_position=InitialPosition.Earliest)
msg = consumer.receive()

consumer.acknowledge_cumulative(msg)
```

The last line `acknowledge_cumulative()` throws `RuntimeError: bad_function_call`.

**Expected behavior**
No error should be raised.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Python 3.8.10
 - `pulsar-client==2.9.1`

**Comment by swjz** [comment]
It looks like each consumer iterator is erased https://github.com/apache/pulsar/blob/773f9197cfb83092fb6ee2bf1b9ec38143f3c8b0/pulsar-client-cpp/lib/MultiTopicsConsumerImpl.cc#L393-L396
within the for loop
https://github.com/apache/pulsar/blob/773f9197cfb83092fb6ee2bf1b9ec38143f3c8b0/pulsar-client-cpp/lib/MultiTopicsConsumerImpl.cc#L377-L385
so `consumer++` throws a segfault.

Please correct me if I'm wrong since I'm new to this project. I'll also try to submit a fix soon.

**Comment by tisonkun** [comment]
Closed as stale. The development of the Python client has been permanently moved to http://github.com/apache/pulsar-client-python. Please open an issue there if it's still relevant.
