### ISSUE TITLE
[Website + Doc] generate connector configuration info automatically

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#14393]
When updating docs for https://github.com/apache/pulsar/pull/14383, @fantapsody suggests **generating connector configuration tables automatically** rather than updating them manually.

I've discussed w/ @urfreespace, he thinks it is workable. For example:

For [the configuration table of the Elasticsearch sink connector](https://pulsar.apache.org/docs/en/next/io-elasticsearch-sink/#configuration), we can get this info from the source code file ([ElasticSearchConfig.java](https://github.com/apache/pulsar/blob/master/pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java)) 

<img width="1960" alt="image" src="https://user-images.githubusercontent.com/50226895/154889729-7aeedafa-b673-44d9-b6ed-b4a60e8d3f02.png">
 
One thing we need to consider is how to display the info. 
@urfreespace believes we can generate **independent** web pages for each connector configuration info (as below), but it's too redundant to show all info connector configuration on the Pulsar home page. We need to **figure out the best way to show the info**.
<img width="915" alt="image" src="https://user-images.githubusercontent.com/50226895/154890169-04ddc1f4-bac7-4bd3-bcd7-e684607fbaa8.png">

Anyone would like to help? Thanks!

**Comment by tisonkun** [comment]
Closed as stale and no progress.

**Comment by Anonymitaet** [comment]
Why close this issue? What are the criteria for keeping an issue open or closed?

**Comment by tisonkun** [comment]
@Anonymitaet Thanks for bubbling up this issue :)

I'll move this thread to the General discussion forum since there's no clear plan (how to implement it) or volunteers working on it.
