### ISSUE TITLE
[Doc] Zookeeper metrics are incorrect

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#14423]
Doc: https://pulsar.apache.org/docs/en/2.8.2/deploy-monitoring/#zookeeper-stats

Context: https://www.mail-archive.com/commits@pulsar.apache.org/msg76624.html

**Comment by Anonymitaet** [comment]
Hi @momo-jun could you please work with @Technoboy- to update the docs? Thanks

**Comment by momo-jun** [comment]
I've sumitted https://github.com/apache/pulsar/pull/14445. PTAL.
@Technoboy- @Anonymitaet
