### ISSUE TITLE
NPE error with KOP

### ISSUE THREAD

**Issue by zcola** [apache/pulsar#14427]
**Describe the bug**

**To Reproduce**
KoP 2.9.2.3
pulsar 2.9.2

```
16:02:48.983 [pulsar-msg-expiry-monitor-28-1] WARN  org.apache.pulsar.broker.service.persistent.PersistentTopic -
 [persistent://public/__kafka/__consumer_offsets-partition-49] Error while getting the oldest message
java.lang.NullPointerException: null
16:02:48.983 [pulsar-msg-expiry-monitor-28-1] WARN  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/__kafka/__consumer_offsets-partition-34] Error while getting the oldest message
java.lang.NullPointerException: null
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by eolivelli** [comment]
Did you follow the guide for the configuration and configured the broker side interceptors?

**Comment by zcola** [comment]
> Did you follow the guide for the configuration and configured the broker side interceptors?

I have not configured broker side interceptors, my network environment is very simple

**Comment by eolivelli** [comment]
You need them.
Otherwise kop doesn't work.
I am referring to the ApppendIndex interceptor

**Comment by eolivelli** [comment]
You need them.
Otherwise kop doesn't work.
I am referring to the ApppendIndex interceptor

**Comment by codelipenghui** [comment]
@BewareMyPower Could you please help check this issue?

**Comment by BewareMyPower** [comment]
The provided info is too little. I've checked similar logs from @zcola, there is no stack trace about the NPE. So it's hard to detect where the NPE happened. Maybe we need to custom the JVM options for OpenJDK. /cc @Demogorgon314
