### ISSUE TITLE
[Doc][Client] explanations for hostname verification configuration are inaccurate

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#14432]
Here is an issue from Pulsar users:

🔷🔷🔷

Please consider this page, https://pulsar.apache.org/docs/en/security-tls-transport/#cli-tools

```
By default, Pulsar clients disable hostname verification, as it requires that each broker has a DNS record and a unique cert.

The examples below show hostname verification being disabled for the Java client, though you can omit this as the client disables the hostname verification by default. C++/python/Node.js clients do now allow configuring this at the moment.
(See the screenshot for the examples)
```

I am trying to understand why the CLI and Java sample configuration disable hostname verification, but the Python and C++ sample configurations enable hostname verification.

If as quoted, “By default, Pulsar clients disable hostname verification”, and “C++/python/Node.js clients do now allow configuring this at the moment.“, then the Python and C++ sample configurations do nothing when they attempt to set hostname verification to true?

If that is true, why have such confusing sample configurations?

Normally, sample configurations are identical across different programming languages. Why in this case is “enableTlsHostnameVerification” set to different values across different programming languages?

🔷🔷🔷

Feedback from @BewareMyPower: The default value in C++ client is false. I'm also confused by these examples and the document. I think it's more like an issue about documents.

**Comment by Anonymitaet** [comment]
@momo-jun could you please help resolve this issue? Thanks

**Comment by momo-jun** [comment]
Hi @Anonymitaet I've submitted the doc PR for review.
