### ISSUE TITLE
[Doc] Terminology? Message and Sequence Id

### ISSUE THREAD

**Issue by larshp** [apache/pulsar#14455]
### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/en/concepts-messaging/#messages mentions that each message has a "Sequence Id", and does not mention anything regarding "Message Id", which is used in the node client, https://github.com/apache/pulsar-client-node/blob/master/index.d.ts#L146 and in the java client https://pulsar.apache.org/api/client/org/apache/pulsar/client/api/MessageId.html

What is the relation, if any, between message and sequence id?

### What is your suggestion?

.

### Do you have any references?

.

### Would you like to fix this issue?

.

### Note

- [X] I have researched my question.

**Comment by momo-jun** [comment]
I'm looking into this issue with @RobertIndie. Will add docs to clarify the differences soon.
