### ISSUE TITLE
Compiling Pulsar C++ Client on NVIDIA Jetson Xavier 

### ISSUE THREAD

**Issue by tspannhw** [apache/pulsar#14457]
**Describe the bug**
Compile fails

 53%] Building CXX object lib/CMakeFiles/PULSAR_OBJECT_LIB.dir/ProducerImpl.cc.o
[ 54%] Building CXX object lib/CMakeFiles/PULSAR_OBJECT_LIB.dir/ProtobufNativeSchema.cc.o
/home/nvidia/nvme/PulsarOnRaspberryPi/pulsar/pulsar-client-cpp/lib/ProtobufNativeSchema.cc: In function ‘pulsar::SchemaInfo pulsar::createProtobufNativeSchema(const google::protobuf::Descriptor*)’:
/home/nvidia/nvme/PulsarOnRaspberryPi/pulsar/pulsar-client-cpp/lib/ProtobufNativeSchema.cc:51:47: error: ‘class google::protobuf::FileDescriptorSet’ has no member named ‘ByteSizeLong’; did you mean ‘ByteSize’?
     std::vector<char> bytes(fileDescriptorSet.ByteSizeLong());
                                               ^~~~~~~~~~~~
                                               ByteSize
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-stringop-truncation’ [-Werror]
cc1plus: all warnings being treated as errors
lib/CMakeFiles/PULSAR_OBJECT_LIB.dir/build.make:920: recipe for target 'lib/CMakeFiles/PULSAR_OBJECT_LIB.dir/ProtobufNativeSchema.cc.o' failed
make[2]: *** [lib/CMakeFiles/PULSAR_OBJECT_LIB.dir/ProtobufNativeSchema.cc.o] Error 1
CMakeFiles/Makefile2:220: recipe for target 'lib/CMakeFiles/PULSAR_OBJECT_LIB.dir/all' failed
make[1]: *** [lib/CMakeFiles/PULSAR_OBJECT_LIB.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

**To Reproduce**
make

**Expected behavior**
Build executable

**Screenshots**
N/A

**Desktop (please complete the following information):**

**Additional context**

**Comment by BewareMyPower** [comment]
> error: ‘class google::protobuf::FileDescriptorSet’ has no member named ‘ByteSizeLong’; did you mean ‘ByteSize’?

It looks like your protobuf dependency is wrong. The latest C++ client depends on protobuf 3, which has the `ByteSizeLong` method, not `ByteSize`.

**Comment by tisonkun** [comment]
Closed as information delievered.

The development of the C++ client has been permanently moved to https://github.com/apache/pulsar-client-cpp. If it's still relevant, please open an issue there.
