### ISSUE TITLE
Missing pulsar_consumer_receive_async

### ISSUE THREAD

**Issue by Matt-Esch** [apache/pulsar#14452]
**Is your enhancement request related to a problem? Please describe.**
The c api is missing async definitions of `pulsar_consumer_receive_with_timeout` and `pulsar_consumer_receive`. 

**Describe the solution you'd like**
I think `pulsar_consumer_receive_with_timeout_async` and `pulsar_consumer_receive_async` should be added.

**Describe alternatives you've considered**
I have considered directly using the C++ api but this involves switching over everything simply because a couple of async definitions are missing. I have also considered writing these functions myself within my own code but it's not possible without being able to unwrap the c types.

**Additional context**
I am trying to port pulsar-client-node to relying exclusively on async operations rather than worker threads.

**Comment by nkurihar** [comment]
Fixed by
* https://github.com/apache/pulsar/pull/17452
* https://github.com/apache/pulsar-client-node/pull/252
