### ISSUE TITLE
[Broker] Expose prometheus metric for current and max number of http server threads

### ISSUE THREAD

**Issue by frankjkelly** [apache/pulsar#14459]
**Is your enhancement request related to a problem? Please describe.**
I'd like to monitor to ensure that Jetty has enough server threads to handle the number of incoming requests.

As discussed by @lhotari here https://github.com/apache/pulsar/issues/14329
"Since Pulsar Admin API uses the blocking servlet API, all Jetty threads might be occupied and this causes unavailability of the Pulsar Admin API. "

**Describe the solution you'd like**
Expose Prometheus metrics for the following
1) Max configured size of the Jetty thread pool (I assume it's a pool?)
2) Current number of threads in use

**Describe alternatives you've considered**
Logging of number of threads is not very actionable.

**Comment by frankjkelly** [comment]
@sijie here is the enhancement request we discussed yesterday

**Comment by tjiuming** [comment]
@codelipenghui  I'd like to handle the issue, please assign to me

**Comment by frankjkelly** [comment]
Hello @tjiuming have you been able to make any progress on this? Thanks! CC: @sijie

**Comment by tjiuming** [comment]
@frankjkelly Hi frank, I had created the pr (https://github.com/apache/pulsar/pull/14742) weeks ago and it's in reviewing now

**Comment by frankjkelly** [comment]
Great - thanks @tjiuming. @sijie is it possible to get some eyes on that PR and then maybe we could seek to backport it to some prior maintenance releases?

**Comment by frankjkelly** [comment]
Congrats on the merge - any chance we can get this backported? @sijie @tjiuming
