### ISSUE TITLE
[Doc] Posting a blog to celebrate Pulsar hits 500 contributors milestone

### ISSUE THREAD

**Issue by alicebi-streamnative** [apache/pulsar#14462]
### What issue do you find in Pulsar docs?

Recently, the Pulsar community reached 500 contributors. This blog, co-authored by Matteo Merli with Karin Landers and Alice Bi, provides an overview of the growth of the Pulsar community, product updates, and celebrates this community milestone.
[the-apache-pulsar-community-welcomes-500th-contributor.md](https://github.com/apache/pulsar/files/8135030/the-apache-pulsar-community-welcomes-500th-contributor.md)

### What is your suggestion?

Posting this blog to [the community site ](https://pulsar.apache.org/blog/)

### Do you have any references?

[the-apache-pulsar-community-welcomes-500th-contributor.md](https://github.com/apache/pulsar/files/8135046/the-apache-pulsar-community-welcomes-500th-contributor.md)

### Would you like to fix this issue?

Yes

### Note

- [X] I have researched my question.

**Comment by alicebi-streamnative** [comment]
@david-streamlio

**Comment by Anonymitaet** [comment]
Hi @alicebi-streamnative since this is a blog, I've labeled this PR w/ `blog` and removed `doc-required`.

**Comment by codelipenghui** [comment]
close by https://github.com/apache/pulsar/pull/14464
