### ISSUE TITLE
Cannot start postgres connector in pulsar io

### ISSUE THREAD

**Issue by thaihuyphan** [apache/pulsar#14476]
**Describe the bug**
When I start Postgres connector with config file and actually pulsar function doesn't start and raise an error message 'must be superuser or replication role to start walsender'

**Expected behavior**
Can start Postgres connector into pulsar standalone (I am using 'pgoutput' plugin with Postgres version larger than 10)

**Screenshots**
<img width="1277" alt="Screen Shot 2022-02-26 at 12 23 25 PM" src="https://user-images.githubusercontent.com/6122160/155830425-9b9df66a-c155-46a1-a9db-f76ecf7e4bd3.png">

**Comment by tisonkun** [comment]
Closed as stale and no one worked on it. Please open a new issue if it's still relevant to the latest version.
