### ISSUE TITLE
KEYS file missing newline which breaks gpg

### ISSUE THREAD

**Issue by benlongo** [apache/pulsar#14484]
The `KEYS` file at [https://www.apache.org/dist/pulsar/KEYS](https://www.apache.org/dist/pulsar/KEYS) is missing whitespace under the block header `-----BEGIN PGP PUBLIC KEY BLOCK-----` for "Chris Kellogg (CODE SIGNING KEY) <cckellogg@apache.org>". 
This causes `gpg --import KEYS` to fail 
```
gpg: invalid armor header: mQINBGF/AVcBEADXMPmN6oD7FQLriwJHKbDCbVE/B0uABJeNCfvW074YyRNek/RF\n
gpg: CRC error; D2C92B - FB9A00
gpg: [don't know]: invalid packet (ctb=17)
gpg: read_block: read error: Invalid packet
gpg: import from 'KEYS' failed: Invalid keyring
```

I'm not sure where this file lives or how to fix it.

**Comment by codelipenghui** [comment]
I think the issue has been fixed.
I have verified 2.8.3 RC, 2.9.2 release RC, looks like I have imported the KEYS correctly.

I will close this issue first, feel free to reopen it if the problem still there.
