### ISSUE TITLE
pulsar broker feature request

### ISSUE THREAD

**Issue by hepyu** [apache/pulsar#14499]
Pulsar cluster has three brokers: broker 1:6650, broker 2:6650 and broker 3:6650

Now I replace the original broker with three new broker nodes. The new brokers are broker 4:6650, broker 5:6650 and broker 6:6650

My server config the new broker (4 ~ 6),  but when I started server, I found that the old broker (1 ~ 3)  was connected either. Why? Should the broker be connected with what I configed ?

**Comment by liudezhi2098** [comment]
broker.conf  `advertisedAddress` whether there is a set value？

**Comment by hepyu** [comment]
> broker.conf `advertisedAddress` whether there is a set value？

new broke node config right value to advertisedAddress in broker.conf.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant in maintained versions.

This seems not a feature request. If you'd like to ask a question, you can go to https://github.com/apache/pulsar/discussions/categories/q-a.
