### ISSUE TITLE
Add metrics for the skipped entries count

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#14507]
**Is your enhancement request related to a problem? Please describe.**
Pulsar uses a marker approach to achieve the replicated subscription https://github.com/apache/pulsar/wiki/PIP-33%3A-Replicated-subscriptions or transaction buffer. For the messages dispatching, we should filter out the markers.
But currently, we don't have any metrics or stats to indicate how many entries are filtered, this will confuse users there are backlogs for a subscription, but can't receive messages from the topic.

**Describe the solution you'd like**
Add skip entries count in the subscription stats under the topics stats, so that users can get the information from `pulsar-admin topics stats`

Details for entries filter: https://github.com/apache/pulsar/blob/603d252ed6e405d2015d2d0fb73047bb9a96b268/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java#L129

**Comment by tjiuming** [comment]
@codelipenghui  assign to me please

**Comment by vkuznecovas** [comment]
Could this also be exported as a prometheus metric please?
