### ISSUE TITLE
Pulsar Client can connect to Pulsar Proxy but not the Pulsar brokers

### ISSUE THREAD

**Issue by anant-ahuja** [apache/pulsar#14548]
I have Pulsar deployed on Kubernetes with the Pulsar Proxy ingress enabled. My Pulsar clients are NOT in the kubernetes cluster, they are on a different server which is not a part of the Kubernetes cluster. The Pulsar clients can connect to the Pulsar Proxy just fine, however they get an internal address for the Pulsar brokers and thus can't connect to the broker.

Here is screenshots of logs my Pulsar Python client:
![image (3)](https://user-images.githubusercontent.com/89229732/156665538-0014f9c5-a3ce-4611-b7a2-f3ba1bac9f5d.png)

And here are my Pulsar Proxy logs:
![image (4)](https://user-images.githubusercontent.com/89229732/156665585-d4e5aa24-c821-4e68-b997-4a3ab52d0197.png)

I also can't find any example documentation of deploying Pulsar with Pulsar proxy ingress enabled. So here is a screenshot of my Pulsar values file with the Ingress config.

![image](https://user-images.githubusercontent.com/89229732/156665904-e5e67ad7-ce88-4657-bbb0-6a1c4594054e.png)

Note: The ingress only gets enabled for port 80 and not for port 6650. Is that the issue?

**Comment by anant-ahuja** [comment]
Edit: My Pulsar Client Service URL was incorrect. After correcting it, I am getting this error.

![image](https://user-images.githubusercontent.com/89229732/156850403-2fd03976-9404-4d09-92f9-77ffba7ffe63.png)

**Comment by codelipenghui** [comment]
@anant-ahuja It's expected behavior. when the client tries to look up the topic, Pulsar will return an internal address to the client to which the client is not able to connect. so we need pulsar-proxy, with pulsar proxy, the proxy will do the topic lookup can and combine connections between clients and broker.

**Comment by anant-ahuja** [comment]
@lhotari Pulsar 2.7.4

**Comment by tisonkun** [comment]
Closed as answered.
