### ISSUE TITLE
Retention Policy is resetted when restarting Pulsar-Broker in a Cluster

### ISSUE THREAD

**Issue by daniwb** [apache/pulsar#14567]
**Describe the bug**
When Pulsar-Broker is restarted in a Cluster, the Retention Policy will be resetted for public/default

**To Reproduce**
1. Set Retention Policy:
bin/pulsar-admin namespaces set-retention public/default --size 11G --time 1h

2. Show Retention Policy:
bin/pulsar-admin namespaces policies public/default
...
  "retention_policies" : {
    "retentionTimeInMinutes" : 60,
    "retentionSizeInMB" : 11264
  },
...

3. Restart Pulsar Broker
bin/pulsar-daemon stop broker
bin/pulsar-daemon start broker

4. Check Policies again
bin/pulsar-admin namespaces policies public/default
...
  "retention_policies" : {
    "retentionTimeInMinutes" : 4320,
    "retentionSizeInMB" : -1
  }, 
...
**Expected behavior**
The retention policy should not be changed at all.

  "retention_policies" : {
    "retentionTimeInMinutes" : 60,
    "retentionSizeInMB" : 11264
  },

**Screenshots**

**Desktop (please complete the following information):**
CentOS 7
Pulsar 2.9.1

**Additional context**

**Comment by eolivelli** [comment]
Are you using Pulsar standalone?

**Comment by mattisonchao** [comment]
Could you provide the broker logs when you set the policy and get the policy?

**Comment by codelipenghui** [comment]
@daniwb I think there are other operations that changed the configuration, from your steps, the `retentionTimeInMinutes ` change to 4320 and `retentionSizeInMB ` change to `-1`, 4320 is not a default value for Pulsar, so Pulsar will not set to 4320, maybe someone changed during the broker restart.

**Comment by daniwb** [comment]
Thanks for your help! I found out, it was **KoP (Kafka on Pulsar)**.
In the logs I can see, that after Kafka on Pulsar starts, it sends the Query to change the default.

@eolivelli We have a Cluster up and running with Centos 7.
