### ISSUE TITLE
Provide the delayed message publish rate stats

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#14581]
**Is your enhancement request related to a problem? Please describe.**
Currently, the producer stats contains the following information

```
{
    "accessMode" : "Shared",
    "msgRateIn" : 0.016669007231704083,
    "msgThroughputIn" : 11.384931939253889,
    "averageMsgSize" : 683.0,
    "chunkedMessageRate" : 0.0,
    "producerId" : 2,
    "metadata" : { },
    "address" : "/xxxx",
    "connectedSince" : "2022-03-07T14:32:57.52849Z",
    "producerName" : "xxx"
  }
```

From the stats, we are not able to know whether the problem
is sending delayed messages or not, it will be useful for some cases
to troubleshoot problems.

**Describe the solution you'd like**
Add "delayedMsgRateIn" in the producer stats

**Comment by shibd** [comment]
@codelipenghui 
The delays is placed in the `MessageMetadata`. This feature will make the broker additional a deserialization `MessageMetaData` when receiving the producer message. Can we accept the performance impact?

**Comment by shibd** [comment]
> @codelipenghui
The delays is placed in the MessageMetadata. This feature will make the broker additional a deserialization MessageMetaData when receiving the producer message. Can we accept the performance impact?

Or, We need add new field `hasDeliver` to `CommandSend`, This can avoid  deserialization  the data of `MessageMetadata`. This is an API protocol change,  We need to discuss first.

@codelipenghui @Technoboy-  PTAL

**Comment by Technoboy-** [comment]
> > @codelipenghui
> > The delays is placed in the MessageMetadata. This feature will make the broker additional a deserialization MessageMetaData when receiving the producer message. Can we accept the performance impact?
> 
> Or, We need add new field `hasDeliver` to `CommandSend`, This can avoid deserialization the data of `MessageMetadata`. This is an API protocol change, We need to discuss first.
> 
> @codelipenghui @Technoboy- PTAL

I will help to check first and then decide to send out a discussion email.

**Comment by Technoboy-** [comment]
> > > @codelipenghui
> > > The delays is placed in the MessageMetadata. This feature will make the broker additional a deserialization MessageMetaData when receiving the producer message. Can we accept the performance impact?
> > 
> > 
> > Or, We need add new field `hasDeliver` to `CommandSend`, This can avoid deserialization the data of `MessageMetadata`. This is an API protocol change, We need to discuss first.
> > @codelipenghui @Technoboy- PTAL
> 
> I will help to check first and then decide to send out a discussion email.

Yes, you're right. If add this field in the `CommandSend`, it is duplicated with `MsgMetadata`, and deserialization is much heavier, so after discussion, we decide to close this issue now.
