### ISSUE TITLE
[Doc] Remove references to the deleted CGo client

### ISSUE THREAD

**Issue by ZiyaoWei** [apache/pulsar#14609]
### What issue do you find in Pulsar docs?

It appears the CGO client has been removed in https://github.com/apache/pulsar/pull/8514 but the doc page still references it in a few places - e.g., https://pulsar.apache.org/docs/en/client-libraries-cgo/.

### What is your suggestion?

 We should probably remove these references to it and point people to the native Golang client (https://github.com/apache/pulsar-client-go) instead.

### Do you have any references?

N/A

### Would you like to fix this issue?

Yes, although I might not be the best person for this

### Note

- [X] I have researched my question.

**Comment by codelipenghui** [comment]
@ZiyaoWei Would you like to push a PR to fix the problem?

**Comment by ZiyaoWei** [comment]
Sure, I'll be happy to do it, feel free to assign it to me. Thanks!
