### ISSUE TITLE
Question about the design of pulsar schema

### ISSUE THREAD

**Issue by MatrixHB** [apache/pulsar#14627]
```
Producer producer = client.newProducer(Schema.AVRO(User.class)).create();

Producer producer = client.newProducer(Schema.generic(schemaInfo)).create();
```

When a pulsar producer is created, it is binding with a specific schema. May I ask what is the advantage of this design？

In kafka, one Producer is not binding with schema, so it can support message sending with multiple schemas. Is it possible for Pulsar to do that？

**Comment by tjiuming** [comment]
```
Producer producer = client.newProducer(Schema.BYTES).create();
```
You can use BYTES schema as above. I think the schema mostly designed for pulsar-sql

**Comment by codelipenghui** [comment]
@MatrixHB Please check the schema documentation https://pulsar.apache.org/docs/en/schema-get-started/#why-use-schema which shows why to use Pulsar Schema.

> You can use BYTES schema as above. I think the schema mostly designed for pulsar-sql

It's not only for pulsar-sql, it allows users to send type messages, not only binary stream.

**Comment by tisonkun** [comment]
Closed as answered and no response.

Feel free to open a Q&A discussion at https://github.com/apache/pulsar/discussions if it's still relevant for maintained versions.
