### ISSUE TITLE
[Doc] Set schema compatibility check strategy not available of v2.9.1

### ISSUE THREAD

**Issue by stricker023** [apache/pulsar#14636]
### What issue do you find in Pulsar docs?

I am using Pulsar 2.9.1, I found server problems of your doc.

I am using this the admin-cli tool to [update schema compacibility of topic level](https://pulsar.apache.org/docs/en/next/schema-manage/#set-schema-compatibility-check-strategy), but ./pulsar-admin topicsPolicies seems not available.

![image](https://user-images.githubusercontent.com/15939734/157574617-a12ead77-72f3-4fe6-9cca-37474e987fb0.png)
![image](https://user-images.githubusercontent.com/15939734/157574686-07e8a975-79a5-4339-970a-c568c9d60b69.png)

And I found another problem, [Negative acknowledgment redelivery backoff](https://pulsar.apache.org/docs/en/next/client-libraries-java/#negative-acknowledgment-redelivery-backoff) is also not available in Pulsar-Java-Client.
![image](https://user-images.githubusercontent.com/15939734/157575282-757dd658-918f-451f-bbcb-510b3a56ab36.png)

![image](https://user-images.githubusercontent.com/15939734/157575010-34a9eb29-20a3-45df-8d4c-76170a1fa206.png)

### What is your suggestion?

Correct the document.

### Do you have any references?

973777898@qq.com

### Would you like to fix this issue?

o

### Note

- [X] I have researched my question.

**Comment by nodece** [comment]
This feature should be available at Pulsar 2.9.2 and Pulsar 2.10.

The doc has an error command: `pulsar-admin topicsPolicies` -> `pulsar-admin topicPolicies`

**Comment by nodece** [comment]
I submitted https://github.com/apache/pulsar/pull/14637 to fix this doc.

**Comment by Anonymitaet** [comment]
@stricker023 

`Negative acknowledgment redelivery backoff` feature is available from 2.10. Code PR: https://github.com/apache/pulsar/pull/12566 

The [doc](https://pulsar.apache.org/docs/en/next/client-libraries-java/#negative-acknowledgment-redelivery-backoff) you read is `next`, which means it's next release (2.10) docs.

<img width="1693" alt="image" src="https://user-images.githubusercontent.com/50226895/157776780-651acac7-b5de-4bc8-b219-4162845f85d2.png">

Besides, before submitting a doc issue, it's recommended to research it. You can search the relevant info on the PR/issue list to get more context quickly.

**Comment by Anonymitaet** [comment]
@nodece thanks for your quick fix!
