### ISSUE TITLE
[Doc] Add doc for basic authentication

### ISSUE THREAD

**Issue by momo-jun** [apache/pulsar#14661]
### What issue do you find in Pulsar docs?

When updating doc for security with @tuteng, we found that Pulsar supports basic authentication as one of the authentication providers. However, in the Security chapter, there is no topic talking about basic authentication like those for TLS, Athenz and etc.
![image](https://user-images.githubusercontent.com/60642177/157834413-6a75494f-da6a-4b24-8955-3c2be95afebf.png)

### What is your suggestion?

Confirmed with @codelipenghui:
In parallel with other available authentication providers, add a new topic for basic authentication, introducing the required concept and configurations.

### Do you have any references?

N/A

### Would you like to fix this issue?

In the backlog.

### Note

- [X] I have researched my question.

**Comment by thalesmg** [comment]
This is still relevant, as there is no documentation for basic authentication.
