### ISSUE TITLE
DeadLetterPolicy should not allow Redelivery Count to be set to 0

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar#14704]
**Describe the bug**

When the user uses the function of DeadLetterPolicy, it is better than misoperation. MaxRedeliverCount may be set to 0. When it is set to 0, according to the current processing logic of the Java Client, the message will be pushed to the DeadLetter Topic every time. Not what we expected to see. Because one of the biggest features of DeadLetterTopic is, when message exceeding the maximum number of redeliveries, message will send to the Dead Letter Topic and acknowledged automatic.

![wecom-temp-651e2f4263c076b2bb7c347f8f6d8058](https://user-images.githubusercontent.com/20965307/158510326-eb1dc489-bd7f-4bb7-bbcc-f7abc2fb5e1d.png)

![wecom-temp-4b11083eaf5a1dd81541592af414d3ad](https://user-images.githubusercontent.com/20965307/158510334-609a3259-a349-4431-b9e7-d5bb1d5e170c.png)

**Comment by codelipenghui** [comment]
Nice catch! @wolfstudy Do you want to push a PR to fix the issue?
