### ISSUE TITLE
[Question] will pulsar roll over if there is only one topic in a namespace

### ISSUE THREAD

**Issue by zcola** [apache/pulsar#14728]
I would like to ask friends who have used online, will pulsar roll over if there is only one topic in a namespace? Too much pressure on zk? The reason for this question is to assume that I want to adjust only one topic to write only some brokers and bookies, and do not want to affect other topics, because I need to unload to force disconnection

**Comment by codelipenghui** [comment]
> I would like to ask friends who have used online, will pulsar roll over if there is only one topic in a namespace? Too much pressure on zk?

What does rollover mean here?
And it depends on how many topics/namespaces you have. If only have thousands of topics/namespaces, don't need to worry about the pressure on zk.

> The reason for this question is to assume that I want to adjust only one topic to write only some brokers and bookies, and do not want to affect other topics, because I need to unload to force disconnection

do you want to do the isolation for some topics?
Yes, currently only namespace can apply isolation policies.

for unloading, you can only unload a topic, not the whole namespace.

**Comment by zcola** [comment]
I tested the unload topic to no avail. Both bk and broker are the same, so I have to unload namespace.

**Comment by codelipenghui** [comment]
@zcola It's better to share more information about the issue that you have to unload the namespace to recover. If the bug has been fixed, you don't need to use one topic per namespace.

**Comment by zcola** [comment]
Ok, I will open another issue
