### ISSUE TITLE
Create Vagrant Image for MacOS 10.14 to build Python Client

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#14751]
**Is your enhancement request related to a problem? Please describe.**
When releasing 2.8.3, I discovered that we do not have a vagrant image for MacOS 10.14. Without that image, we cannot create a python client for that target OS.

**Describe the solution you'd like**
Create an image, or figure out an alternative way to build the python client for MacOS 10.14.

**Additional context**
Related issues: https://github.com/apache/pulsar/issues/4540, https://github.com/apache/pulsar/issues/13334, #13429, #12293, #8794

**Comment by michaeljmarshall** [comment]
@merlimat @codelipenghui @eolivelli - The MacOS 10.14 image is not available. I could not build the 2.8.3 Python Client for MacOS 10.14. It looks like there are several issues where users are asking for such a version. I created this issue to raise visibility about this missing image. Both of these URLs currently result in a 404.

https://app.vagrantup.com/apachepulsar/boxes/osx-10.14-python-dev/versions/0.1/providers/download/virtualbox.box
https://app.vagrantup.com/apachepulsar/boxes/osx-10.14-python-dev/versions/0.2/providers/download/virtualbox.box

**Comment by eolivelli** [comment]
Also it is not clear to me how do we maintain those images.
Is there any documentation?
In theory they are under the control of the Pulsar PMC

**Comment by michaeljmarshall** [comment]
That would make sense. During the community meeting yesterday, @merlimat mentioned that the vagrant images are hard to build, and that we're missing several versions of MacOS. It seems that we probably need to take a closer look at this part of our build/release process.

**Comment by yaalsn** [comment]
@michaeljmarshall @codelipenghui @BewareMyPower Is it necessary for us to build pulsar c++ in the specific macOS version? If so, how about using the cmake parameter `MACOSX_DEPLOYMENT_TARGET`?

**Comment by BewareMyPower** [comment]
> Is it necessary for us to build pulsar c++ in the specific macOS version? 

I think it depends on the compiler.

> If so, how about using the cmake parameter MACOSX_DEPLOYMENT_TARGET

I'm not sure which compiler the older macOS uses. But it looks like this flag doesn't work for Clang. See https://stackoverflow.com/questions/25352389/what-is-the-difference-between-macosx-deployment-target-and-mmacosx-version-min

**Comment by tisonkun** [comment]
@BewareMyPower @michaeljmarshall @merlimat is it still relevant? I can build the Python client on my macOS 12.6 now.

**Comment by BewareMyPower** [comment]
No. The script in pulsar-client-python repo works well now.

**Comment by tisonkun** [comment]
Closed as fixed.
