### ISSUE TITLE
Need an api interface for the process to start working normally for rolling restart of pulsar

### ISSUE THREAD

**Issue by zcola** [apache/pulsar#14767]
The official website documentation tells us that we can restart one by one after the canary test.

But in extreme cases, is it possible that the updated broker process starts too slowly or crashes shortly after startup?

Therefore, when we make operation and maintenance scripts, we need to consider that once the previous update fails to cancel all update tasks, we need an api for detection and judgment. If we observe from monitoring traffic, this method is not universal and provides business.

Or is there an existing way to do it now?

**Comment by codelipenghui** [comment]
@zcola Looks like you are finding a way to check if the broker is healthy or not? 

Maybe https://pulsar.apache.org/admin-rest-api/?version=2.9.1&apiversion=v2#operation/healthcheck can help.

**Comment by zcola** [comment]
> 
yes 
https://pulsar.apache.org/docs/en/administration-upgrade/ not mentioned

**Comment by codelipenghui** [comment]
@zcola Ok, thanks for the update, we will consider to add it the administration upgrade part 
/cc @Anonymitaet
