### ISSUE TITLE
Topic stats cannot work with transaction_coordinator_assign topic

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#14790]
**Describe the bug**
```
Can not create transaction system topic persistent://pulsar/system/transaction_coordinator_assign-partition-1

Reason: Can not create transaction system topic persistent://pulsar/system/transaction_coordinator_assign-partition-1
```

**To Reproduce**
1. Deploy pulsar cluster
2. Enabled transaction
3. Disabled the topic auto creation
4. init the transaction metadata https://pulsar.apache.org/docs/en/txn-use/
5. Create the missed partitions: bin/pulsar-admin topics create-missed-partitions persistent://pulsar/system/transaction_coordinator_assign
6. get the topic stats
7. See the above error

**Expected behavior**
The topic stats should work with `transaction_coordinator_assign` topic

**Additional context**
Version: the latest branch-2.9

**Comment by liangyepianzhou** [comment]
`persistent://pulsar/system/transaction_coordinator_assign` is only used by lookup, it have not managerLedger. 
So this is a normal performance.
you can use `bin/pulsar-admin topics list-partitioned-topics pulsar/system `to check if the metadata of this topic has been created.

**Comment by congbobo184** [comment]
https://github.com/apache/pulsar/pull/14965 will fix this issue

**Comment by chenjing1294** [comment]
I still have this problem in apache-pulsar-2.11.0.
```
[GET] http://node1:8080/admin/v2/persistent/pulsar/system/transaction_coordinator_assign/internalStats
```
```json
{
    "reason": "Can not create transaction system topic persistent://pulsar/system/transaction_coordinator_assign"
}
```
