### ISSUE TITLE
400 appears when start  sink

### ISSUE THREAD

**Issue by 704237006** [apache/pulsar#14812]
**Describe the bug**
download [apache-pulsar-2.9.1-bin.tar.gz](https://www.apache.org/dyn/mirrors/mirrors.cgi?action=download&filename=pulsar/pulsar-2.9.1/apache-pulsar-2.9.1-bin.tar.gz)

simple start with standalone  and without other config:
./pulsar-daemon start standalone 

my sink config is:
![image](https://user-images.githubusercontent.com/42430068/159616858-a0ac9cec-8ca0-4e2a-9ad5-455eed38d700.png)

cmd:
bin/pulsar-admin schemas upload test-jdbc-postgres -f avro-schema/avro_postgres

![image](https://user-images.githubusercontent.com/42430068/159614995-4c232d30-4f0e-4b14-ad41-c86593d39a75.png)
400 appears when start sink
![image](https://user-images.githubusercontent.com/42430068/159615089-2004ff13-a521-4ede-af5c-dc603cb8476e.png)

**Desktop **
 - OS: [Linux  3.10.0-957.el7.x86_64]

**Additional context**
Sink has been started when it is created. Error 400 will be reported when starting again

**Comment by Demogorgon314** [comment]
Can you provide the broker-side log, is are any error logs?
