### ISSUE TITLE
Website build is broken

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#14824]
**Describe the bug**
The build has not passed for the most recent 10 runs. 9 failures were due to timeout. 1 failure was because of a broken master build.

**To Reproduce**
Here are the builds: https://github.com/apache/pulsar/actions/workflows/ci-pulsar-website-build.yaml

Here are the timeouts: https://github.com/apache/pulsar/runs/5653053711?check_suite_focus=true (failed during upload) and https://github.com/apache/pulsar/runs/5659883571?check_suite_focus=true (failed during download)

**Expected behavior**
The website build should succeed almost all of the time.

**Comment by michaeljmarshall** [comment]
It seems the build is temporarily fixed by #14825. That isn't a long term fix though. I think we'll likely want to review #14837.

**Comment by tisonkun** [comment]
Closed as stale. Now the website build should work well.
