### ISSUE TITLE
TableViewImpl leaking internal state via accessors

### ISSUE THREAD

**Issue by ZiyaoWei** [apache/pulsar#14821]
**Describe the bug**

Currently TableViewImpl methods that access the underlying map, e.g., TableViewImpl::KeySet() (https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewImpl.java#L141) returns views of the underlying map, which means users could modify the returned value and accidentally change the internal state of TableViewImpl.

**To Reproduce**

If we remove a key from the KeySet in `TableViewTest::testTableView`, the test would fail.

**Expected behavior**

Modifying the returned key set/values/etc. shouldn't change the internal state of the TableViewImpl.

**Additional context**

We should probably fix it before people start relying on this behavior :-)

**Comment by ZiyaoWei** [comment]
cc: @nlu90 since we discussed this via Slack

**Comment by Technoboy-** [comment]
> cc: @nlu90 since we discussed this via Slack

I will work on this.
