### ISSUE TITLE
[Website] Stop re-generating client docs based on SNAPSHOT versions

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#14838]
**Is your enhancement request related to a problem? Please describe.**
We currently generate docs for our clients and tools based on master and publish them under the current snapshot version. This process is not ideal, and it is confusing, as the website URLs are https://pulsar.apache.org/tools/pulsar-client/2.9.0-SNAPSHOT/.

**Describe the solution you'd like**
It'd be better to update the build so that we generate this static content once, based on the correct tag of the project, and then never again.

The scripts that would benefit are here: https://github.com/apache/pulsar/tree/master/site2/tools. Anything that outputs directories with SNAPSHOT in the name are part of the problem.

**Describe alternatives you've considered**
I don't currently see any alternatives.

**Additional context**
I just completed similar work for the python client. See the following PRs for complete context: https://github.com/apache/pulsar/pull/14788, https://github.com/apache/pulsar/pull/14828, https://github.com/apache/pulsar/pull/14835

**Comment by Anonymitaet** [comment]
Similar to https://github.com/apache/pulsar/issues/13916 

I've discussed this issue w/ @tuteng and @urfreespace 

in fact, “snapshot” is “release version”, the name “x.x.x-SNAPSHOT”  is inaccurate, we should remove  -SNAPSHOT
this is a known issue and we’ve reported it to the community, but no one has been volunteered to resolve it yet

feel free to fix, thanks

**Comment by michaeljmarshall** [comment]
@Anonymitaet - thanks for the other issue reference, I hadn't seen that one. I opened this issue to aggregate several issues, as well as to provide context on how to solve the underlying issue. I fixed the python client documentation in https://github.com/apache/pulsar/pull/14788. I haven't been able to fix any of the other issues yet.

**Comment by tisonkun** [comment]
Anyway, the documents under `/tools` are officially moved to https://pulsar.apache.org/reference.

Closed.
