### ISSUE TITLE
[Website] Upgrade crowdin cli to latest version

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#14837]
**Is your enhancement request related to a problem? Please describe.**
We use crowdin to manage translations of the Pulsar documentation. The crowdin cli client is at least one major version behind. We often timeout when completing uploads and downloads to crowdin.

**Describe the solution you'd like**
We should upgrade cli client versions to get the benefit of its most recent features, like multi-threaded uploads.

**Describe alternatives you've considered**
I don't believe there are any alternatives.

**Comment by Anonymitaet** [comment]
@urfreespace

**Comment by urfreespace** [comment]
@michaeljmarshall The latest version of crowdin client is incompatible with docusaurus v1.x, please do not upgrade, And In fact, we used the latest version of crowdin client in our [new website](https://pulsar-next.staged.apache.org/)

**Comment by michaeljmarshall** [comment]
@urfreespace - thank you for the context. I opened this issue to discuss what I noticed about the website build and some failures. If we've already upgraded in the new website, then we can close this issue.
