### ISSUE TITLE
[Test] org.apache.pulsar.broker.admin.AdminApi2Test in branch-2.9 have multiple failed tests

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#14863]
**Describe the bug**

**To Reproduce**
1. Build from branch-2.9
2. Run all tests of org.apache.pulsar.broker.admin.AdminApi2Test
3. See multiple failed tests

**Expected behavior**
The tests should get passed
The CI should check this test in branch-2.9

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by poorbarcode** [comment]
All unit test passed on my computer.

![test passed](https://user-images.githubusercontent.com/25195800/160756813-eed65881-379c-43ad-b337-8e0835fca08b.png)
![all test passed](https://user-images.githubusercontent.com/25195800/160756826-e512efd9-8473-4535-8f7e-83b75a4324b7.png)

**Comment by shibd** [comment]
@poorbarcode  Hi, It's this unit test [AdminApiTest2](https://github.com/apache/pulsar/blob/branch-2.9/pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest2.java),  I find 5 fail test:
- brokerNamespaceIsolationPoliciesUpdateOnTime
- namespaceAntiAffinity
- testDistinguishTopicTypeWhenForceDeleteNamespace
- testForceDeleteNamespace
- testMaxTopicsPerNamespace

**Comment by poorbarcode** [comment]
> @poorbarcode Hi, It's this unit test [AdminApiTest2](https://github.com/apache/pulsar/blob/branch-2.9/pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest2.java), I find 5 fail test:
> 
> * brokerNamespaceIsolationPoliciesUpdateOnTime
> * namespaceAntiAffinity
> * testDistinguishTopicTypeWhenForceDeleteNamespace
> * testForceDeleteNamespace
> * testMaxTopicsPerNamespace

You're right. I used the wrong branch: "origin/branch-2.9", doesn't pull the latest updates.

Thanks.

**Comment by poorbarcode** [comment]
these problem has fixed at master, but has not cherry-pick to branch-2.9

- In this PR #13644, these tree problem fixed
  - fixed `brokerNamespaceIsolationPoliciesUpdateOnTime`
  - removed test-case: `testDistinguishTopicTypeWhenForceDeleteNamespace`
  - fixed `testMaxTopicsPerNamespace`
  - fixed `namespaceAntiAffinity`
  - fixed `testForceDeleteNamespace`

**Comment by poorbarcode** [comment]
these problem has fixed at master, but has not cherry-pick to branch-2.9

- In this PR #13644, these tree problem fixed
  - fixed `brokerNamespaceIsolationPoliciesUpdateOnTime`
  - removed test-case: `testDistinguishTopicTypeWhenForceDeleteNamespace`
  - fixed `testMaxTopicsPerNamespace`
  - fixed `namespaceAntiAffinity`
  - fixed `testForceDeleteNamespace`

**Comment by BewareMyPower** [comment]
This issue should not be closed because #13644 is not cherry-picked or migrated to branch-2.9 and branch-2.10, I opened a new issue for it. /cc @poorbarcode @codelipenghui @shibd 

First of all, we need to rename `AdminApiTest2` to `AdminApi2Test` for branch-2.9 and branch-2.10.
