### ISSUE TITLE
Linux/Homebrew Package for apache-pulsar

### ISSUE THREAD

**Issue by coderfender** [apache/pulsar#1490]
I am planning to develop a homebrew and a Linux packages which install apache-pulsar on the local machines.

With the effective package installed, the command to install apache-pulsar would be "brew install apache-pulsar" and "apt-get apache-pulsar" reducing the installation overhead and jump directly into developing applications on pulsar.

I would be happy if the dev community could provide feedback/comments or suggestions on the task.

Thank you

Bhargava

**Comment by merlimat** [comment]
@coderfender Nice! For homebrew there was some work done here https://github.com/streamlio/homebrew-formulae/blob/master/pulsar.rb by @aahmed-se

It would be nice to have all packaging in same repo.

**Comment by sijie** [comment]
@coderfender any updates from this issue?

**Comment by coderfender** [comment]
Hi @sijie ,

I am sorry i didnt get time to finish this.I am still working on this and aiming at pushing the changes in couple of weeks for review

**Comment by sijie** [comment]
@coderfender any updates about this task?

**Comment by sijie** [comment]
Closed this issue due to inactivities.
