### ISSUE TITLE
[Doc] Need fix on Geo Replication chapter

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#14917]
### What issue do you find in Pulsar docs?

In the doc, it says there are three producers, but there are only two.
![Uploading image.png…]()

### What is your suggestion?

We may need to fix it in this image:  https://pulsar.apache.org/docs/assets/full-mesh-replication.svg

### Do you have any references?

https://pulsar.apache.org/docs/en/next/concepts-replication/

### Would you like to fix this issue?

Since we may need to fix the image, could you please take a look: @momo-jun 

### Note

- [X] I have researched my question.

**Comment by momo-jun** [comment]
Thanks @RobertIndie for reporting this issue. I'll update the illustration.
