### ISSUE TITLE
[feat][website] REST API URL does not go to the correct place 

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#14928]
All REST API URL on Pulsar documentation has this issue.

Website: https://pulsar.apache.org/docs/en/next/admin-api-tenants/

<img width="1542" alt="image" src="https://user-images.githubusercontent.com/50226895/160593074-f088dabc-d181-4c55-afc5-fd88e4235efb.png">

@urfreespace thinks the anchor does not work correctly but we have not figured out how to solve this issue

Anyone would like to fix it? Thanks

**Comment by Anonymitaet** [comment]
Feedback from @BewareMyPower:

Hi, I'm reporting a bug of the new website again:joy:The rendering of the REST API is wrong. See https://pulsar.apache.org/docs/next/schema-manage/#topic-level.

We can see `GET /admin/v2/topics/:tenant/:namespace/:topic`. However, the original text is
{@inject: endpoint|GET|/admin/v2/topics/:tenant/:namespace/:topic|operation/schemaCompatibilityStrategy?version=[[pulsar:version_number]]}

It's frustrated that I cannot compare it with the rendering of the old website. (should we add an entry point to the old website?) But the rendering result should be like the 2nd image.

BTW, I think the description `Send a PUT request to this endpoint:` is redundant. See the 3rd image from https://pulsar.apache.org/docs/next/admin-api-topics. 

![image](https://user-images.githubusercontent.com/50226895/169248333-acc1c8de-e296-4a2c-a669-0662631ff343.png)
![image](https://user-images.githubusercontent.com/50226895/169248310-59af2318-91f3-41dd-98a0-0c648b861c9e.png)
![image](https://user-images.githubusercontent.com/50226895/169248354-9b08d4a2-22c7-45c4-853e-3766622fa415.png)

**Comment by urfreespace** [comment]
@Anonymitaet you can access the old website here: https://pulsar.staged.apache.org/ (it's the old website backup, it will be closed AFTER the new site is stable)

**Comment by Anonymitaet** [comment]
@urfreespace OK, thanks!

**Comment by horizonzy** [comment]
The pr https://github.com/apache/pulsar-site/pull/127 submit, maybe fix this problem

**Comment by Anonymitaet** [comment]
@momo-jun I check some occurrences on `master`, and they do not function well. For example: 
![image](https://user-images.githubusercontent.com/50226895/177741977-ee7ffda0-4ee6-4203-9a8f-4e1caf28d645.png)
https://pulsar.apache.org/docs/next/admin-api-functions

Can you take a look? Thank you!

**Comment by Anonymitaet** [comment]
@momo-jun your PR was merged 3 hours ago and the website build was done 4 hours ago, maybe that is the reason why the new changes do not take effect. Let's wait for a while to see if it works. Thank you.

**Comment by Anonymitaet** [comment]
@momo-jun do you update all occurrences only for `master` or `master + other versions`?

**Comment by momo-jun** [comment]
> @momo-jun do you update all occurrences only for `master` or `master + other versions`?

Master only. I want to verify whether they work well before applying the changes to more versions.

**Comment by Anonymitaet** [comment]
@momo-jun 

I check some occurrences randomly and find that:

1. It shows `loading` all the time, do you have the same issue?
package: https://pulsar.apache.org/docs/next/admin-api-packages 
<img width="1960" alt="image" src="https://user-images.githubusercontent.com/50226895/177899427-2dfbf5bb-f3ef-47ad-a12a-f167ba7a9382.png">

3. Some contain `version` while others not, is this intended behavior?
- Left: https://pulsar.apache.org/docs/next/admin-api-packages
- Right: https://pulsar.apache.org/docs/next/admin-api-tenants
<img width="1631" alt="image" src="https://user-images.githubusercontent.com/50226895/177899647-ce296482-525b-4fd9-af70-040d80c09d66.png">

**Comment by momo-jun** [comment]
Same on my side. I checked the MD file and its syntax `{@inject: endpoint|POST|/admin/v3/packages/:type/:tenant/:namespace/:packageName/:version}` doesn't contain any anchor nor the version number variable, that's why it cannot be loaded. Since it doesn't contain the version number variable, such cases are not covered in the previous fix. I need to use a new search term to clean up this type of occurrence. Thanks for your check.

> 1. It shows `loading` all the time, do you have the same issue?
>    package: https://pulsar.apache.org/docs/next/admin-api-packages
> 
> <img alt="image" width="1960" src="https://user-images.githubusercontent.com/50226895/177899427-2dfbf5bb-f3ef-47ad-a12a-f167ba7a9382.png">

The `version` we can see here does not refer to the injected version number, but a static text. The display text is correct. The only issue is the same as above - the syntax needs to be fixed by adding a version number variable and an anchor.

> 2. Some contain `version` while others not, is this intended behavior?
> 
> * Left: https://pulsar.apache.org/docs/next/admin-api-packages
> * Right: https://pulsar.apache.org/docs/next/admin-api-tenants
> 
> <img alt="image" width="1631" src="https://user-images.githubusercontent.com/50226895/177899647-ce296482-525b-4fd9-af70-040d80c09d66.png">

**Comment by momo-jun** [comment]
When searching for the remaining incorrect REST API links, I found the REST API docs missed "lookup topic" and "get bundles".
@shibd helped checked the issue in code and pushed a PR-#16470  to fix it.

I've fixed other incorrect REST API links in #16433 and will update for  "lookup topic" and "get bundles" as soon as #16470 is merged.

**Comment by momo-jun** [comment]
This issue can be closed after #16746 is merged. Any other problematic occurrence is an individual case of error.
