### ISSUE TITLE
Disk space is not freed

### ISSUE THREAD

**Issue by huangzx3** [apache/pulsar#14923]
> configuration: default
> deploy: docker

## Disk space is not freed, is this normal? If it is normal, how long will it take to release?

![image](https://user-images.githubusercontent.com/34366684/160564536-b9d16aa8-90bd-4572-b521-9da911cf8da2.png)

![image](https://user-images.githubusercontent.com/34366684/160564483-d0c0945d-231b-417f-8ac8-a061890cb858.png)

**Comment by huangzx3** [comment]
![image](https://user-images.githubusercontent.com/34366684/160584010-3e166fc0-9c2e-4d2e-b2df-5fd319caae9d.png)

> The disk will periodically get smaller, but it will increase again after a while

**Comment by huangzx3** [comment]
# It is automatically deleted after 4 hours of storage, but the disk is still the original size

![image](https://user-images.githubusercontent.com/34366684/160594145-eeff8c4a-7551-4c35-8d5a-ec02aced1cc6.png)
![image](https://user-images.githubusercontent.com/34366684/160594182-6599efdd-e957-4897-a8cc-f9083a5569c9.png)

**Comment by huangzx3** [comment]
```

-rw-r--r-- 1 root root 1.1G 3月  30 07:46 0.log
-rw-r--r-- 1 root root 1.3G 3月  30 08:29 17fcfe79619.txn
-rw-r--r-- 1 root root 253M 3月  30 08:29 1.log
-rw-r--r-- 1 root root    0 3月  30 07:46 2.log
-rw-r--r-- 1 root root    2 3月  30 07:46 lastId
-rw-r--r-- 1 root root   16 3月  30 08:29 lastMark
drwxr-xr-x 2 root root 4.0K 3月  30 08:17 ledgers
drwxr-xr-x 2 root root 4.0K 3月  30 08:17 locations
-rw-r--r-- 1 root root  118 3月  28 17:42 VERSION

```
## Is it related to TNX files?

**Comment by huangzx3** [comment]
```

journalMaxSizeMB	2048
journalMaxBackups	5

```
## My understanding is whether it is related to these two parameters. When 10g is reached, TxN and log files will be deleted

**Comment by zhaoli2333** [comment]
Hello, how did you solve this problem finally?
