### ISSUE TITLE
reconsumeLater can't receive message while restart all brokers

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#14937]
**Describe the bug**
Pulsar v2.8.1/v2.8.3
Consumer running in real time, reconsumeLater can't receive message while restart all brokers.
![image](https://user-images.githubusercontent.com/54351417/160737523-6d3bda77-226b-478c-81ed-026455c0bebc.png)

Cluster:
1 broker
3 bookies

**To Reproduce**
1. create consumer:
```
    public static void main(String[] args) throws Exception{
        PulsarClient client = PulsarClient
                .builder()
                .serviceUrl("pulsar://127.0.0.1:6650")
                .build();

        ConsumerBuilder<NlMessage> consumerBuilder = client.newConsumer(Schema.JSON(NlMessage.class)).topic("batchtest")
                .subscriptionName("batchTest")
                .subscriptionType(SubscriptionType.Shared)
                .enableRetry(true)
                .enableBatchIndexAcknowledgment(true)
                .receiverQueueSize(1000)
                .negativeAckRedeliveryDelay(20, TimeUnit.SECONDS)
                .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest);
        // DLQ
        DeadLetterPolicy deadLetterPolicy = DeadLetterPolicy.builder()
                .deadLetterTopic("persistent://public/default/batchtest-dlq")
                .retryLetterTopic("persistent://public/default/batchtest-retry")
                .maxRedeliverCount(3)
                .build();
        consumerBuilder.deadLetterPolicy(deadLetterPolicy);
        consumerBuilder.negativeAckRedeliveryDelay(10, TimeUnit.MICROSECONDS);
        // 需要在死信策略设置以后 再设置ackTimeout (如果ackTimeout == 0)
        consumerBuilder.ackTimeout(0, TimeUnit.SECONDS); // 如果receiverQueueSize或者deadLetterPolicy后，ackTimeout又变为30s。

        Consumer<NlMessage> consumer = consumerBuilder.subscribe();
        while (true) {
            Message<NlMessage> message = consumer.receive();
            System.out.println("message:" + message.getMessageId());
            consumer.reconsumeLater(message, 1, TimeUnit.SECONDS);
        }
    }
```
2. create producer:
```
    public static void main(String[] args) throws PulsarClientException {
        PulsarClient pulsarClient = PulsarClient.builder().serviceUrl("pulsar://127.0.0.1:6650").build();

        Producer<NlMessage> producer = pulsarClient.newProducer(Schema.JSON(NlMessage.class))
                .topic("persistent://public/default/batchtest")
                .blockIfQueueFull(true)
                .sendTimeout(0, TimeUnit.SECONDS)
                .create();
        long i = 1;
        while(i < 1000000L){
            producer.sendAsync(new NlMessage());
            i++;
        }
    }
```
3. start consumer
4. start producer
5. stop broker
6. start broker
7. See error

**Expected behavior**
Continue receiving messages.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by poorbarcode** [comment]
Let me try

**Comment by xuesongxs** [comment]
> Let me try

Can you reproduce it？

**Comment by xuesongxs** [comment]
> > > Let me try
> > 
> > 
> > Can you reproduce it？
> 
> How many broker have you started ?

only 1

**Comment by poorbarcode** [comment]
> > > > Let me try
> > > 
> > > 
> > > Can you reproduce it？
> > 
> > 
> > How many broker have you started ?
> 
> only 1

Hao many bookie count have you started ?

**Comment by xuesongxs** [comment]
> > > > > Let me try
> > > > 
> > > > 
> > > > Can you reproduce it？
> > > 
> > > 
> > > How many broker have you started ?
> > 
> > 
> > only 1
> 
> Hao many bookie count have you started ?

3 bookies

**Comment by poorbarcode** [comment]
> > > > > > Let me try
> > > > > 
> > > > > 
> > > > > Can you reproduce it？
> > > > 
> > > > 
> > > > How many broker have you started ?
> > > 
> > > 
> > > only 1
> > 
> > 
> > Hao many bookie count have you started ?
> 
> 3 bookies

 I'll try to set up a same environment

**Comment by poorbarcode** [comment]
> > > > > > > > Let me try
> > > > > > > 
> > > > > > > 
> > > > > > > Can you reproduce it？
> > > > > > 
> > > > > > 
> > > > > > How many broker have you started ?
> > > > > 
> > > > > 
> > > > > only 1
> > > > 
> > > > 
> > > > Hao many bookie count have you started ?
> > > 
> > > 
> > > 3 bookies
> > 
> > 
> > I'll try to set up a same environment
> 
> my wechat: daxia_xue

The problem was reproduced .  But only if  "topicName" is exactly the same as "subscriptionName", just like this: 
```
client.newConsumer(Schema.JSON(NlMessage.class)).topic("same_as_topic_name").subscriptionName("same_as_topic_name")
```

**Comment by xuesongxs** [comment]
The problem can be solved by using try catch.
