### ISSUE TITLE
[CI] `Auto Labeling` failed

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#14942]
**Describe the bug**
The `Auto Labeling` sometimes failed. See [here](https://github.com/apache/pulsar/actions/workflows/ci-documentbot.yml?query=is%3Afailure)
 It should not fail. Instead, It should leave a comment on the PR if there is something wrong.
**To Reproduce**
1. Create a PR
2. May result in `Auto Labeling` workflow failure

**Expected behavior**
Should not fail.

**Screenshots**
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/16974619/160774423-ee2fb49b-efe3-46ff-80c0-8a337d5226f1.png">

**Additional context**
```
Run apache/pulsar-test-infra/doc-label-check@master
--- https://github.com/apache/pulsar/pull/14913 ---
[ 'doc-info-missing' ]
Labels to ignore:

-------------------------------
[]
Labels to process:
- { name: 'doc', checked: true }

Labels to remove:

[ 'doc' ]
-----------------------
[ 'doc', 'doc-info-missing' ]
-----------------------
doc issue exists
doc-info-missing issue exists
Error: Label does not exist
```

**Comment by tisonkun** [comment]
Closed as stale. The current docbot should work well. If you find furthering issues, please open one at http://github.com/apache/pulsar-test-infra.
