### ISSUE TITLE
[Doc] Regression in pulsar CLI docs

### ISSUE THREAD

**Issue by sbourkeostk** [apache/pulsar#14946]
### What issue do you find in Pulsar docs?

The new style pulsar CLI docs do not show the required arguments. Example from the new style docs for pulsar-admin:

> grant-permission
> Grant a new permission to a client role on a single topic.
> 
> Usage
> $ pulsar-admin topics grant-permission options
> Options
> 
> Flag	Description	Default
> --role	Client role to which grant permissions	null
> --actions	Actions to be granted (produce,consume)	null

It does not display the required `topic` argument. This is just an example. As far as I can see, all required arguments are missing throughout the documentation.

### What is your suggestion?

Fix or revert docs back to previous style.

### Do you have any references?

https://pulsar.apache.org/tools/pulsar-admin/2.9.0-SNAPSHOT/

### Would you like to fix this issue?

-

### Note

- [X] I have researched my question.

**Comment by tisonkun** [comment]
Closed. We have a new reference page: https://pulsar.apache.org/reference/
