### ISSUE TITLE
[Doc] Create documentation about Monitoring of Tiered Storage

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#14967]
### What issue do you find in Pulsar docs?

There is no documentation about Tiered Storage operations and monitoring.

This is basically because we still don't have enough features to allow easy operations.

### What is your suggestion?

We should add a new section about this topic.

### Do you have any references?

Relevant PRs:
https://github.com/apache/pulsar/pull/14966
https://github.com/apache/pulsar/pull/14930

### Would you like to fix this issue?

I can help, but has it is a brand new section I would prefer to help with the content and not with creating and designing the architecture of this new section

### Note

- [X] I have researched my question.

**Comment by momo-jun** [comment]
Hi @eolivelli I can do the information design work. Can you pls provide source material in a google doc?

**Comment by momo-jun** [comment]
Hi @eolivelli Noticed you have labeled the relevant PR https://github.com/apache/pulsar/pull/14930 as `doc-complete` while the other PR https://github.com/apache/pulsar/pull/14966 is closed. Does it mean that this issue can be closed?

**Comment by momo-jun** [comment]
Closed the issue since the relevant PRs have been closed or labeled `doc-complete`. Feel free to reopen it when it's relevant.
