### ISSUE TITLE
[Doc] Pulsar-Admin docs miss some new features

### ISSUE THREAD

**Issue by polyzos** [apache/pulsar#14987]
### What issue do you find in Pulsar docs?

```
  Commands:
    tenants      Operations about tenants
      Usage: tenants [options]

    proxy-stats      Operations to collect Proxy statistics
      Usage: proxy-stats [options]

    brokers      Operations about brokers
      Usage: brokers [options]

    functions      Interface for managing Pulsar Functions (lightweight,
            Lambda-style compute processes that work with Pulsar)
      Usage: functions [options]

    sources(source)      Interface for managing Pulsar IO Sources (ingress
            data into Pulsar)
      Usage: sources(source) [options]

    sinks(sink)      Interface for managing Pulsar IO sinks (egress data from
            Pulsar)
      Usage: sinks(sink) [options]

    documents      Generate documents automatically.
      Usage: documents [options]

    topics      Operations on persistent topics
      Usage: topics [options]

    resource-quotas      Operations about resource quotas
      Usage: resource-quotas [options]

    packages      Operations about packages
      Usage: packages [options]

    ns-isolation-policy      Operations about namespace isolation policy
      Usage: ns-isolation-policy [options]

    bookies      Operations about bookies rack placement
      Usage: bookies [options]

    broker-stats      Operations to collect broker statistics
      Usage: broker-stats [options]

    schemas      Operations about schemas
      Usage: schemas [options]

    functions-worker      Operations to collect function-worker statistics
      Usage: functions-worker [options]

    clusters      Operations about clusters
      Usage: clusters [options]

    resourcegroups      Operations about ResourceGroups
      Usage: resourcegroups [options]

    namespaces      Operations about namespaces
      Usage: namespaces [options]
```
There are some commands included in the **pulsar-admin** that are note included in the docs like **packages**, **proxy-stats**, **resource-groups** and **functions-worker**
https://pulsar.apache.org/tools/pulsar-admin/2.9.0-SNAPSHOT/

### What is your suggestion?

They should be documented as its hard to understand what they do 

### Do you have any references?

no

### Would you like to fix this issue?

.

### Note

- [X] I have researched my question.

**Comment by Anonymitaet** [comment]
@polyzos could you please rename the issue (to let others know the issue clearly)? Thanks

**Comment by Anonymitaet** [comment]
- resourcegroups, proxy-stats: I search them on GitHub but no result. I ask the platform engineer team, no one knows when they were added to Pulsar. Community may help if they see the issue.

- packages:  [it was added from 2.8.0](https://github.com/apache/pulsar/pull/8816), so it should be shown on https://pulsar.apache.org/tools/pulsar-admin/2.9.0-SNAPSHOT/

**Comment by dave2wave** [comment]
@polyzos sorry you have not received a proper reply here. Please add your comments to #15813

**Comment by momo-jun** [comment]
@polyzos as Dave suggested, you can add comments to https://github.com/apache/pulsar/issues/15813.
I will close this issue as it's duplicated with https://github.com/apache/pulsar/issues/15813.
