### ISSUE TITLE
 attempt to update the table failed

### ISSUE THREAD

**Issue by 704237006** [apache/pulsar#14984]
**Describe the bug**

**To Reproduce**
1. A topic is defined, which has the same structure as the table in SQL server.
2. Define a sink and try to update the data in the SQL Server table. Use the following configuration。
![image](https://user-images.githubusercontent.com/42430068/161235889-690d7fec-8989-4929-90b4-019789ec8657.png)
3.The error is as follows.
![cf7e19091c9392b347ee5e93d1d59f5](https://user-images.githubusercontent.com/42430068/161236551-6b8c0221-8d2d-4438-a14f-9a8f604e6b2c.png)

**Desktop (please complete the following information):**
 - OS: [linux]

**Comment by gaozhangmin** [comment]
The error is very obvious. duplicate key found, no related with pulsar function.

**Comment by 704237006** [comment]
> The error is very obvious. duplicate key found, no related with pulsar function.

This configuration key = "Id", isn't it an updated configuration?
