### ISSUE TITLE
[Tiered Storage] Objects from `persistent/healthcheck` topic are offloaded

### ISSUE THREAD

**Issue by MMirelli** [apache/pulsar#14990]
**Describe the bug**

Data in `persistent://pulsar/<host>:8080/healthcheck` is offloaded. 

**To Reproduce**

1. Deploy pulsar using the DS helmchart and setting the property `storageOffload.managedLedgerOffloadAutoTriggerSizeThresholdBytes` to a low number (e.g. 1000);
2. ingest an arbitrary number of messages into a topic `public/default/test`;
3. wait for the ledger rollover time to elapse;
4. consume all the messages from `public/default/test`;
5. unsubscribe from `public/default/test`;
6. check the content of the bucket using JClouds.

From the metadata of the offloaded objects you can observe the source topic is `<cluster_name>/pulsar/<host>:8080/persistent/healthcheck`.

**Expected behavior**

To my understanding, data from `<cluster_name>/pulsar/<host>:8080/persistent/healthcheck` should never be offloaded, that  topic is used for the cluster operation.

**Desktop:**
 - Kubernetes deployment

**Additional context**

This issue has manifested on all major cloud provider currently supported (GCP, AWS and Azure).

**Comment by MMirelli** [comment]
I plan to address this issue asap.

**Comment by Technoboy-** [comment]
> I plan to address this issue asap.

Already make sense, I will work on this.
