### ISSUE TITLE
[Doc] Java client examples for protobuf native schema

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar#15035]
### What issue do you find in Pulsar docs?

The [ProtobufNative example of Java client](https://pulsar.apache.org/docs/en/client-libraries-java/#protobufnativeschema-example) links to https://pulsar.apache.org/docs/en/schema-understand/#complex-type but there are no examples code for Java client.

Currently, users can find some examples in https://github.com/apache/pulsar/pull/8372. But they are not well documented. We should add some Java code examples like [C++ client](https://pulsar.apache.org/docs/en/client-libraries-cpp/#protobufnative-schema).

### What is your suggestion?

Add Java code examples for ProtobufNative schema. 

### Do you have any references?

no

### Would you like to fix this issue?

Yes.

### Note

- [X] I have researched my question.

**Comment by momo-jun** [comment]
The required code example has been added [here](https://pulsar.apache.org/docs/2.11.x/schema-get-started/#protobufnative).
