### ISSUE TITLE
Consumer doesn't consume

### ISSUE THREAD

**Issue by Tlaloc-Es** [apache/pulsar#15052]
**Describe the bug**
After call `consumer.negative_acknowledge(msg)` a lot suddenly the consumer doesn't consumer any message, I change the cursor name several times but didn't work.

The new consumers were created with 

```
consumer = pulsar.Client(
            PULSAR_URL,
            authentication=AuthenticationOauth2(params)
        ).subscribe(
            topic=PULSAR_TOPIC,
            initial_position=_pulsar.InitialPosition.Earliest,
            subscription_name=PULSAR_SUBSCRIPTION_NAME
        )
```
or with
```
consumer = pulsar.Client(
            PULSAR_URL,
            authentication=AuthenticationOauth2(params)
        ).subscribe(
            topic=PULSAR_TOPIC,
            initial_position=pulsar.InitialPosition.Earliest,
            subscription_name=PULSAR_SUBSCRIPTION_NAME
        )
```

**To Reproduce**
 ```
while True:
        msg = consumer.receive()
        ex = msg.value()
        data = json.loads(ex)
        try:
            print(data)
            consumer.negative_acknowledge(msg)
        except Exception as e:
            consumer.negative_acknowledge(msg)
```
**Expected behavior**
Consume messages, and consume all messages from the earliest position.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mattisonchao** [comment]
Hi @Tlaloc-Es 

Could you provide more information about this issue?
like broker version, client language, client version and broker logs.

**Comment by Tlaloc-Es** [comment]
Currently, I can get the messages, was there any not reachable error but currently, I can process all subscriptions.
