### ISSUE TITLE
does pulsar have plan to improve delay message deliver 

### ISSUE THREAD

**Issue by john1337** [apache/pulsar#15146]
i am considering using  delay message deliver using mq, found some solutions: rabbitmq,rocketmq and pulsar, when i dig deep into pulsar i found pulsar is using memory to realize delay deliver feature so it can't handle heavy load,so i was wondering does pulsar have any plan to improve it and when?

thanks

**Comment by tjiuming** [comment]
Pulsar use `InMemoryDelayedDeliveryTracker` to schedule delay messages,  and each message costs 24bytes(deliverAt,ledgerId,entryId), which means 1G direct memory could schedule more than 4200000 backlog messages, isn't enough?
