### ISSUE TITLE
Problem in developing a pulsar-io-mqtt

### ISSUE THREAD

**Issue by 704237006** [apache/pulsar#15154]
**Describe the bug**
I got the mqtt message in the open method in MqttSource, which can be seen from the print. When I tried to push the message to a pulsar topic, nothing happened in the pulsar topic, no errors, no messages.

 1.push code
![image](https://user-images.githubusercontent.com/42430068/163132016-b18ca99c-25d9-4e8c-af31-bd54f901864b.png)

2.source connector running stats
![image](https://user-images.githubusercontent.com/42430068/163132201-865d015c-d054-4c9e-8844-c124105880c6.png)

3.source connector running status
![image](https://user-images.githubusercontent.com/42430068/163134578-507d9bb2-3ab9-4d67-a89c-cf64c3702c53.png)

**Comment by 704237006** [comment]
@ngjaying

**Comment by caihualin** [comment]
pulsar-io-mqtt source code where can be found
