### ISSUE TITLE
pulsar doesn't support springboot  well

### ISSUE THREAD

**Issue by john1337** [apache/pulsar#15169]
pulsar project has started more than 5 years,and springboot is a well used architecture,but pulsar doesn't support the arch as well as rocketmq or kafka,hope you can devote some time into improving this

**Comment by lhotari** [comment]
There's a Spring Boot starter for Reactive Pulsar, you can find more information at https://github.com/datastax/reactive-pulsar#spring-boot-starter

**Comment by lhotari** [comment]
related to #10588

**Comment by lhotari** [comment]
I'm planning to contribute Reactive Pulsar and the Spring Boot Starter to the Pulsar project. Please show your interest on the dev mailing list in this thread: https://lists.apache.org/thread/x4htj65mvysxyx430rqrplc066jjsj5z

**Comment by lhotari** [comment]
[Introducing Experimental Spring Support for Apache Pulsar](https://spring.io/blog/2022/08/16/introducing-experimental-spring-support-for-apache-pulsar) provides an answer to this question.

**Comment by lhotari** [comment]
[Spring for Pulsar](https://github.com/spring-projects/spring-pulsar) is now GA and it's [included in Spring Boot 3.2](https://spring.io/blog/2023/11/23/spring-boot-3-2-0-available-now) . Marking this as complete. /cc @onobc
