### ISSUE TITLE
Reader resource leakage in TableView

### ISSUE THREAD

**Issue by freeznet** [apache/pulsar#15166]
**Describe the bug**
When set `autoUpdatePartitionsInterval` to a small value like 1 second in `TableViewBuilder`, the table view client will keep create new reader (consumer) in each interval and causing resource leaks. 

The main reason is the TableViewImpl is not cache existing reader, see https://github.com/apache/pulsar/blob/04aa9e8e51869d1621a7e25402a656084eebfc09/pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewImpl.java#L77-L81

**To Reproduce**
use pulsar 2.10.0, create TableView client with a small `autoUpdatePartitionsInterval`, and you will see the consumers are created in each loop from the logs.

**Comment by nlu90** [comment]
I will create a PR for the fix
