### ISSUE TITLE
PIP-155: Drop support for Python2

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#15185]
## Motivation

Python 2.x has been deprecated for many years now and it was officially end-of-lifed 2.5 years ago (https://www.python.org/doc/sunset-python-2/). 

We have well reached the point by which we need to drop Python 2.7 compatibility for Pulsar client and for Pulsar functions.

Based on Python end-of-life policies, there are 4 versions of Python that are currently supported: 3.7, 3.8, 3.9 and 3.10. https://endoflife.date/python

That gives a 5 years support schedule from release to EoL.

## Goal

Support only the last 4 Python releases Pulsar client and for Pulsar functions, currently 3.7, 3.8, 3.9 and 3.10. Once 3.7 reaches end-of-life, it will be dropped by Pulsar too.

This policy will be also applied to the Pulsar patch releases which will stop providing Python wheel files for the deprecated versions.

## API Changes

No changes at this time, though Pulsar Python client library will be now free to use Python3 specific syntaxes and libraries.

## Changes

1. Switch the CI build to run Python client lib tests with Python3
2. Switch integration tests to use Python3
3. Stop building and distributing wheel files for Python 2.7

**Comment by zbentley** [comment]
Thoughts on minimum py3 version? 3.6+ and 3.7+ are common choices in the python ecosystem.

**Comment by merlimat** [comment]
Do you know where to find a list of feature/syntax that were change in 3.6 or 3.7? 
As in: what could we be free to use if we didn't have to support Py 3.5 and 3.6?

**Comment by zbentley** [comment]
Most details are here: https://docs.python.org/3/whatsnew/index.html

**Comment by merlimat** [comment]
This is actually helpful: https://endoflife.date/python 

3.6 has already reached end of life and here will be no more security updates. It does indeed make sense for us to stop supporting it too.

**Comment by dimaqq** [comment]
Poke

**Comment by tisonkun** [comment]
Closed as resolved. I don't find outstanding dependencies.
