### ISSUE TITLE
Pulsar should support cluster metadata store with etcd backend with SSL(https://...)

### ISSUE THREAD

**Issue by lyxly** [apache/pulsar#15205]
I hope Pulsar‘s components configuration support etcd with ssl access (metadataStoreUrl can use metadataServiceUri=metadata-store:etcd:**https:**//my-etcd:2379)

In some secure or existing environments, there has been existing a etcd cluster with SSL  authentication。When I use the etcd service for Pulsar cluster medata store, I meet the problem that I can't configure Pulsar cluster for SSL authenticated etcd cluster like https://.....

**Comment by nodece** [comment]
I will working on this.

**Comment by lyxly** [comment]
> I will work on this.

**Comment by lyxly** [comment]
> I will work on this.

That's wonderful.  When I finish switching to Apache Pulsar, I think I will also devote to this excellent component.

**Comment by nodece** [comment]
@lyxly I submitted #15270 to fix this, could you help review this PR?

**Comment by lyxly** [comment]
@nodece  I’m sorry that I'm not good at the Java development, even a freshman. Before I begin the apache pulsar development, I will learn the tech stack about the Java especially in this MQ component.
