### ISSUE TITLE
[Doc] Documentation links to client feature matrix are broken

### ISSUE THREAD

**Issue by zbentley** [apache/pulsar#15213]
### What issue do you find in Pulsar docs?

The below links to the client feature matrix are broken and go to the main wiki index:

https://pulsar.apache.org/docs/en/client-libraries/#feature-matrix
https://github.com/apache/pulsar/wiki/#committers-documentation
https://pulsar.apache.org/docs/en/2.2.1/client-libraries/#feature-matrix

### What is your suggestion?

Those links should be updated to point to this GH node, or directly to the spreadsheet in that node:

https://github.com/apache/pulsar/wiki/PIP-108%3A-Pulsar-Feature-Matrix-%28Client-and-Function%29

### Do you have any references?

See issue description.

### Would you like to fix this issue?

Sure.

### Note

- [X] I have researched my question.

**Comment by Anonymitaet** [comment]
1. The below links to the client feature matrix are not broken 
https://pulsar.apache.org/docs/en/client-libraries/#feature-matrix
https://github.com/apache/pulsar/wiki/#committers-documentation

They all go to https://docs.google.com/spreadsheets/d/1YHYTkIXR8-Ql103u-IMI18TXLlGStK8uJjDsOOA0T20/edit#gid=1784579914

2. Would you like to correct the link on https://pulsar.apache.org/docs/en/2.2.1/client-libraries/#feature-matrix? Thanks!
It should go to https://docs.google.com/spreadsheets/d/1YHYTkIXR8-Ql103u-IMI18TXLlGStK8uJjDsOOA0T20/edit#gid=1784579914

**Comment by zbentley** [comment]
1. The link under "committers documentation" is broken; it goes back to the main wiki index. The link body is `https://github.com/apache/incubator-pulsar/wiki/Client-Features-Matrix`.

2. I posted the wrong link previously. The 2.2.1 docs aren't the only place that link is broken; if I follow the link on https://pulsar.apache.org/docs/en/2.9.2/client-libraries/#feature-matrix, it takes me to the wiki root as well.

**Comment by Anonymitaet** [comment]
Fixed in https://github.com/apache/pulsar/pull/15309

**Comment by zbentley** [comment]
Thanks!
