### ISSUE TITLE
[C++] Use CMake 3.13 to build C++ client in CI

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar#15232]
**Is your enhancement request related to a problem? Please describe.**
Currently the `cmake_minimum_required` version is 3.4, which is wrong because some features from higher version CMake are used, like [target_link_options](https://cmake.org/cmake/help/git-stage/command/target_link_options.html).

https://github.com/apache/pulsar/blob/caf7648653c140c9f922e86425585ab7b5ed3ed6/pulsar-client-cpp/CMakeLists.txt#L20

**Describe the solution you'd like**
Fix the wrong `cmake_minimum_required` declaration, and use the minimum required version of CMake (it should be 3.13) to build C++ client in CI.

**Comment by BewareMyPower** [comment]
The document [here](https://github.com/apache/pulsar/tree/master/pulsar-client-cpp#requirements) is also wrong.

<img width="584" alt="image" src="https://user-images.githubusercontent.com/18204803/164681938-c05de623-cd2b-4a8d-b970-0b1542daddab.png">

**Comment by tisonkun** [comment]
Closed. The development of the C++ client has been moved out.
