### ISSUE TITLE
Reader to Read Events by Key(s)

### ISSUE THREAD

**Issue by DR9885** [apache/pulsar#15268]
**Is your enhancement request related to a problem? Please describe.**
When using the reader, it should be able to filter on a list of keys

**Describe the solution you'd like**
C# example: of reading events for Key 123
```
await _client.NewReader()
                .Topic($"persistent://public/default/{bucket}")
                .StartMessageId(MessageId.Earliest)
                .Keys(new[] {"123"})
                .CreateAsync();
```

**Describe alternatives you've considered**
Possible TEMP options
- Using a Sink Connector, and reading from that database (but eventual consistency issue)
- Using Trino, but that doesn't seem like the right way to go.
- Manually consume events and write to data store to query from.

**Comment by Lanayx** [comment]
Seems to be related
https://github.com/apache/pulsar/pull/8544

**Comment by DR9885** [comment]
closing and following #8544
