### ISSUE TITLE
[transaction] Standalone mode, Transaction coordinator with id 0 not found

### ISSUE THREAD

**Issue by TakaHiro0208** [apache/pulsar#15272]
**Describe the bug**
I try to test transaction as the doc described, https://pulsar.incubator.apache.org/docs/en/txn-use/
And it throw such error, "Transaction coordinator with id 0 not found"

![企业微信截图_6d311e6b-130a-47dd-aa46-a108ada89be2](https://user-images.githubusercontent.com/13505225/164694033-20d70de7-2c04-448b-9a96-85af146d9c7c.png)

My standalone.conf only modify the following conf
- transactionCoordinatorEnabled=true
- allowAutoTopicCreationType=partitioned
- allowAutoTopicCreation=true

I have tried using pulsar-2.9.2 and pulsar-2.10.0, both of them has the same problem
I also have tried add -nfw in standalone,  but the problem still exist

And it seems only occur in standalone, in normal cluster the problem would not occur

**To Reproduce**
1. change standalone.conf, start standalone
2. run demo

**Desktop (please complete the following information):**
 - OS: mac

**Comment by Technoboy-** [comment]
For not blocking your test, you can try to create `admin.topics().createPartitionedTopic(TopicName.TRANSACTION_COORDINATOR_ASSIGN.toString(), 1)`.
I will try to work on this issue.

**Comment by TakaHiro0208** [comment]
> For not blocking your test, you can try to create `admin.topics().createPartitionedTopic(TopicName.TRANSACTION_COORDINATOR_ASSIGN.toString(), 1)`. I will try to work on this issue.

Actually i have noticed the pr-10238 and , and this system topic has been created. So i think maybe this is not the reason

**Comment by Technoboy-** [comment]
Not reproduced.  Could you share your client demo ?

**Comment by Technoboy-** [comment]
Ah, what is your client version ? is it matched the broker version ?

**Comment by TakaHiro0208** [comment]
> Ah, what is your client version ? is it matched the broker version ?

My fault, my maven project depends pulsar-flink-connector which is not pulsars-2.9.2
And after matching client version the problem is solved, thanks for your reply. I will close this issue
