### ISSUE TITLE
Partitioned topic termination often blocks indefinitely, but succeeds immediately upon retry

### ISSUE THREAD

**Issue by zbentley** [apache/pulsar#15278]
**Describe the bug**
Sometimes, when terminating a partitioned topic via the management API, termination blocks "forever" (until I time out the HTTP request). However, no matter when I time out that request, a subsequent request to terminate the topic always succeeds.

This happens regardless of whether I'm connected to a broker or a proxy, and doesn't seem to coincide with any stacktraces in the broker logs, though I didn't check for "distant" log entries from the moment of termination.

**To Reproduce**
This does not reliably reproduce. I've seen it happen most frequently when attempting to terminate partitioned topics that were created very shortly before doing this (seconds or less beforehand).

1. Create a partitioned topic.
2. Immediately try to terminate it via the management API.
3. Observe that sometimes termination times out with an HTTP timeout.
4. When a timeout occurs, immediately re-attempt termination (send the exact same HTTP request).
5. Observe that subsequent requests succeed.

**Expected behavior**
Termination requests shouldn't block forever, and should return success/failure when the broker has terminated a topic. 

The fact that an immediate followup request succeeds indicates to me that the broker has successfully terminated the topic before that point, but the handling code for the first (timing out) request doesn't know about it.

Broker 2.9.1, MacOS and Linux, standalone and SN platform brokers reproduced.

**Comment by Technoboy-** [comment]
We have fixed this by https://github.com/apache/pulsar/pull/13890 and released in pulsar 2.10.0
