### ISSUE TITLE
[Bug] pulsar-io-jdbc-sink get table definition possible error

### ISSUE THREAD

**Issue by jianyun8023** [apache/pulsar#15285]
**Describe the bug**

I used mysql as the implementation of `io-jdbc-sink`, and during the process, I encountered that some columns of sink were always null when inserting table data. opening debug found that it was wrong to get the table schema.

**To Reproduce**

This problem occurs in the following scenario:

I have two databases, `databaseA` and `databaseB`.
They both have a table `test-table`.
- The `test-table` in `databaseA` has columns `key`, `value1`
- The `test-table` in `databaseB` has columns `key`, `value1`, `value2`.

At this time I use sink to write data to `databaseB.test-table`, which contains `value2` field, but `value2` in `databaseB.test-table` is always empty.

**Expected behavior**

The value of `value2` in `databaseB.test-table` can be written successfully

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jianyun8023** [comment]
I have fixed this issue. Please assign it to me.

The MySQL Connection is not forcibly bound to a library,

In the code, the method to get the table information did not specify which database to use, which led to finding the wrong library information.

**Comment by jianyun8023** [comment]
`metadata.getTables` does not specify the database to be used, which also results in getting the wrong database.
https://github.com/apache/pulsar/blob/8679ef5da9d9f10a2e64832ac69a67ecf135ec81/pulsar-io/jdbc/core/src/main/java/org/apache/pulsar/io/jdbc/JdbcUtils.java#L92-L112

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
