### ISSUE TITLE
Macos pulsar-client-cpp 2.8 VersionTest.cc error

### ISSUE THREAD

**Issue by zzs258** [apache/pulsar#15299]
**Describe the bug**
/Users/zzs258/pulsar/pulsar-client-cpp/tests/VersionTest.cc:24:5: error: expected expression
    ASSERT_GE(PULSAR_VERSION, 2000000);
    ^
/usr/local/include/gtest/gtest.h:1893:31: note: expanded from macro 'ASSERT_GE'
#define ASSERT_GE(val1, val2) GTEST_ASSERT_GE(val1, val2)
                              ^
/usr/local/include/gtest/gtest.h:1869:3: note: expanded from macro 'GTEST_ASSERT_GE'
  ASSERT_PRED_FORMAT2(::testing::internal::CmpHelperGE, val1, val2)
  ^
/usr/local/include/gtest/gtest_pred_impl.h:148:3: note: expanded from macro 'ASSERT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_FATAL_FAILURE_)
  ^
/usr/local/include/gtest/gtest_pred_impl.h:134:41: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), on_failure)
                                        ^
/Users/zzs258/pulsar/pulsar-client-cpp/tests/VersionTest.cc:25:5: error: expected expression
    ASSERT_LE(PULSAR_VERSION, 999999999);
    ^
/usr/local/include/gtest/gtest.h:1885:31: note: expanded from macro 'ASSERT_LE'
#define ASSERT_LE(val1, val2) GTEST_ASSERT_LE(val1, val2)
                              ^
/usr/local/include/gtest/gtest.h:1865:3: note: expanded from macro 'GTEST_ASSERT_LE'
  ASSERT_PRED_FORMAT2(::testing::internal::CmpHelperLE, val1, val2)
  ^
/usr/local/include/gtest/gtest_pred_impl.h:148:3: note: expanded from macro 'ASSERT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_FATAL_FAILURE_)
  ^
/usr/local/include/gtest/gtest_pred_impl.h:134:41: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), on_failure)
                                        ^
2 errors generated.
make[2]: *** [tests/CMakeFiles/main.dir/VersionTest.cc.o] Error 1
make[1]: *** [tests/CMakeFiles/main.dir/all] Error 2

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tisonkun** [comment]
Closed as stale.

The development of the C++ client has been permanently moved to https://github.com/apache/pulsar-client-cpp. If it's still relevant, please open an issue there.
