### ISSUE TITLE
enhance validation when updating transaction topic

### ISSUE THREAD

**Issue by wuzhanpeng** [apache/pulsar#15302]
### Motivation

Currently executing the command `bin/pulsar initialize-transaction-coordinator-metadata` will directly update the number of partitions of `persistent://pulsar/system/transaction_coordinator_assign`.

When accidentally misoperation, the number of partitions is directly modified, and there is no way to roll back (the number of partitions cannot be reduced).

### Modifications

Simplely add an argument to determine whether forced update is allowed.

**Comment by tisonkun** [comment]
Closed. See https://github.com/apache/pulsar/pull/15301#issuecomment-1240140655.
