### ISSUE TITLE
Standardize PR naming convention using GitHub Action

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#15311]
We've created [[Guideline] Pulsar PR Naming Convention](https://docs.google.com/document/d/1d8Pw6ZbWk-_pCKdOmdvx9rnhPiyuxwq60_TrD68d7BA/edit#) and many contributors in Pulsar community follow the rules, which is great!

And we want to research whether we can improve this workflow furthermore by **standardizing PR naming convention using GitHub Action**.

@RobertIndie and @nodece have provided some references, which might be the potential solutions:
- https://github.com/amannn/action-semantic-pull-request
- https://github.com/zeke/semantic-pull-requests
- https://github.com/apache/apisix/blob/master/.github/workflows/semantic.yml

Besides, to reduce manual work, @codelipenghui suggests that a PR can be labeled automatically based on `[xxx][xxx]` in a PR title.

Anyone would like to help implement this idea? Thanks!

**Comment by Anonymitaet** [comment]
Thanks @nodece !
You mean we should select https://github.com/amannn/action-semantic-pull-request, correct？

**Comment by nodece** [comment]
> Thanks @nodece ! You mean we should select https://github.com/amannn/action-semantic-pull-request, correct？

Yes, you are right.

**Comment by mangoGoForward** [comment]
Hi @Anonymitaet I'd like to work on it, please assign to me

**Comment by Anonymitaet** [comment]
@mangoGoForward thanks! Assigned.

**Comment by tisonkun** [comment]
The change may require a dev doc for itself and I'm curious whether there's a discussion on dev@ since it can significantly change developer experience.

**Comment by tisonkun** [comment]
@nodece notify me about a previous discussion: https://lists.apache.org/thread/sk9ops3t94jmzc5tndk08y9khf7pj6so

Looks good!

**Comment by dave2wave** [comment]
I am -1 on this and #16836 until the "standard" has been moved into a PMC controlled resource. A google doc is NOT PMC controlled. I also ask if these changes have gone through the PIP process?

**Comment by nodece** [comment]
I agreed with @dave2wave, and I think we should make a PIP to add a contribution guide and continue developing this PR.

**Comment by Anonymitaet** [comment]
@dave2wave what is `PMC controlled resource`? Like moving the standards from google doc to Pulsar WIKI?
Or grant edit access to PMC members on google docs? → which is much simpler

**Comment by nodece** [comment]
Any updates?

**Comment by tisonkun** [comment]
Implemented at https://github.com/apache/pulsar/pull/17961. @nodece @Anonymitaet you may close this issue as completed.

**Comment by nodece** [comment]
Closed by #17961, thank you all for your contributions!

**Comment by Anonymitaet** [comment]
Thank you all! @mangoGoForward @maxsxu @tisonkun @nodece
