### ISSUE TITLE
Key_Shared Nack causes events to be played out of order for a specific key.

### ISSUE THREAD

**Issue by DR9885** [apache/pulsar#15317]
**Describe the bug**
If events are consumed as key_shared, and the first event was nacked it changes the order of the events for that key. It has that event pushed to the end.

Expected Order: 0,1,2,3,4
Actual Order: 1,2,3,4,0

This is an issue, when building a materialized view based off a key/id. If the events are played out of order it could change the resulting object.

**To Reproduce**
C# test example
``` 
public class ExampleTest
{
    [Fact]
    public async Task Test()
    {
        const int size = 5;
        const string key = "123";
        const string topic = "persistent://public/default/topic";

        var client = await new PulsarClientBuilder()
            .ServiceUrl("pulsar://localhost:6650")
            .BuildAsync();

        var producer = await client.NewProducer()
            .Topic(topic)
            .BatchBuilder(BatchBuilder.KeyBased)
            .CreateAsync();

        for (var i = 0; i < size; i++)
        {
            var payload = Encoding.UTF8.GetBytes($"message-{i}");
            var msg = producer.NewMessage(payload, key);
            await producer.SendAsync(msg);
        }

        var subscribe = await client.NewConsumer()
            .Topic(topic)
            .SubscriptionName("test-group")
            .SubscriptionType(SubscriptionType.KeyShared)
            .SubscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
            .SubscribeAsync();

        var batch = await subscribe.ReceiveAsync();
        await subscribe.NegativeAcknowledge(batch.MessageId);


        for (var i = 0; i < size; i++)
        {
            var item = await subscribe.ReceiveAsync();
            var msg = Encoding.UTF8.GetString(item.Data);
            Assert.Equal($"message-{i}", msg);
        }
    }
}
```

**Expected behavior**
It should wait to further events from that key

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
Note: if retry limit is hit, the messages would never play. so maybe there should also be a way to reset retry counts to try again.

**Comment by codelipenghui** [comment]
@DR9885 For the Key_Shared subscription, the redelivery operation will cause the message to redeliver to the same consumer again, you can retry the message locally, don't need to call the redelivery method, the redelivery operation will break the message reading order.

**Comment by DR9885** [comment]
@codelipenghui, but lets say a specific key is failing again and again. If we did this locally, we could block the queue from processing and the subscription could timeout... It would be better if we could use a re-queue mechanism to backlog all subsequent keys... Otherwise I'm just going to throw them in a queue to be reprocessed later... but this should be a pulsar mechanism.

Isn't event order important for event sourcing? and isn't this a stream processing system to support event sourcing?
