### ISSUE TITLE
PIP-162: Enable system topic by default

### ISSUE THREAD

**Issue by Technoboy-** [apache/pulsar#15333]
## Motivation
In [PIP-39](https://github.com/apache/pulsar/wiki/PIP-39%3A-Namespace-Change-Events), we have introduced namespace event to support topic level policy. This feature was released in Pulsar 2.6.

Then [PIP-92](https://github.com/apache/pulsar/wiki/PIP-92%3A-Topic-policy-across-multiple-clusters), we support topic policy to replicate across clusters and release in Pulsar 2.10.

And with version iteration, the corresponding topic policy CLI and functions are mature and stable, but users need to enable system topic to support these features.  So it's better to enable system topic by default.

## Proposed changes

In 2.11 release, change :

 *  `systemTopicEnabled`:  false -> true
 *  `topicLevelPoliciesEnabled`: false -> true

**Comment by asafm** [comment]
I think the numbering collides as there is an existing [PIP-156](https://github.com/apache/pulsar/issues/15207)

**Comment by Technoboy-** [comment]
> I think the numbering collides as there is an existing [PIP-156](https://github.com/apache/pulsar/issues/15207)

Thanks, I have updated it to PIP-162.
