### ISSUE TITLE
[Doc] Terminology? Message Key, Partition Key, Ordering Key

### ISSUE THREAD

**Issue by larshp** [apache/pulsar#15380]
### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/en/concepts-messaging/#messages introduces the concept of a message

In my application I wanted to set the message key, to my surprise, the type contained a "PartitionKey" and "OrderingKey", which at first sight does not seem identical to the message key?

https://github.com/apache/pulsar-client-node/blob/master/index.d.ts#L123-L134

The Java client contains "Key" and "OrderingKey"

https://pulsar.apache.org/api/client/2.10.0-SNAPSHOT/org/apache/pulsar/client/api/Message.html

Only by looking at https://github.com/apache/pulsar/issues/9317 I can deduce that "PartitionKey" is the same as a message "Key"

### What is your suggestion?

Update the documentation to clarify that message key and partition key is the same concept.

Also suggest adding a note that the key is textual, as I would have guessed it to be raw, just like the message payload.

### Do you have any references?

.

### Would you like to fix this issue?

.

### Note

- [X] I have researched my question.

**Comment by Anonymitaet** [comment]
Hi @momo-jun can you take a look at this issue? Thanks

**Comment by momo-jun** [comment]
@larshp thanks for filing the issue. Your concern has been addressed in #15469.
Thanks @RobertIndie for looking into this issue.

**Comment by larshp** [comment]
thanks, looks good to me 👍
