### ISSUE TITLE
Delayed message delivery intermittently fails to deliver messages until consumers reconnect when a KeyShared consumer is used and delays are randomized

### ISSUE THREAD

**Issue by zbentley** [apache/pulsar#15397]
**Describe the bug**
When consuming from a topic with a KeyShared consumer, messages with delayed delivery are often not returned from the consumer. This doesn't happen with all delayed messages, but seems to happen with around half.

This issue doesn't occur when using Shared subscriptions.

After the consumer is restarted, all messages that should have been delivered but were not are immediately delivered.

This only happens when delayed messages are not sequentially scheduled; i.e. it won't happen if I publish messages in order with equal or increasing delays, since those messages "come due" in publish order. For example, it will happen if I publish two messages, the first with a delay of 10sec and the second with a delay of 5sec.

**To Reproduce**
1. In one terminal, run the below code snippet with the command line argument `consume`. Verify it connects and waits for messages.
2. In another terminal, run the below snippet with the command line argument `produce`; observe that it prints out messages that it published and their delays.
3. In the first terminal, wait for 12 seconds (the maximum possible delay published by the producer script). 
4. In the first terminal, observe that all messages were *not* delivered.
5. Restart (CTRL+C and run again) the consumer in the first terminal. Observe that it immediately receives all of the messages that were missed in step 4.

Code to reproduce:
```python
import sys
import time
from datetime import timedelta, datetime
import random
import pulsar

topic = "persistent://public/default/foobar"


def main():
    client = pulsar.Client(service_url='pulsar://localhost:6650')
    if sys.argv[-1] == "produce":
        p = client.create_producer(topic=topic)
        for i in range(10):
            data = f"msg-{i}".encode()
            delay = timedelta(milliseconds=random.randint(1000, 2000))
            rv = p.send(data, deliver_after=delay, partition_key=str(i))
            print("sent", data, "delay:", delay, rv)
            time.sleep(1)
    if sys.argv[-1] == "consume":
        c = client.subscribe(
            topic=topic,
            subscription_name="chariot_subscription-heartbeat-heartbeat",
            consumer_type=pulsar.ConsumerType.KeyShared
        )

        while True:
            try:
                msg = c.receive(timeout_millis=1000)
            except pulsar.Timeout:
                pass
            else:
                c.acknowledge(msg)
                print(datetime.now(), msg.message_id(), msg.data())


if __name__ == "__main__":
    main()
```

**Expected behavior**
All messages should print out as received in step 3 above.

**Desktop (please complete the following information):**
 - OS: MacOS monterey.
 - Pulsar: 2.9.2 via Homebrew; also repro'd on latest standalone Docker image as of 4/29.

**Additional context**

KeyShared consumers are necessary for our use case: topics sometimes contain delayed messages, and sometimes contain **non**-delayed messages with a partition key set across groups of messages for ordered, single-consumer delivery. 

We know that combining delays with a partition key can cause problems; so we enforce that delayed messages have UUID partition keys at our client layer. 

To facilitate delayed delivery, we could work around the problem by periodically reconnecting consumers (hacky, induces extra delays) or by running a second Shared subscriber next to our KeyShared subscribers (complicated and potentially expensive in terms of consumer memory). We would prefer to keep the system simple and use a single KeyShared consumer for both types of messages.

**Comment by zbentley** [comment]
Additional interesting info: if I call `redeliver_unacknowledged_messages()` on the consumer periodically (when there are no unacknowledged messages--i.e. if I replace the `pass` in the `except Timeout` in the example code with `c.redeliver_unacknowledged_messages()`), the consumer gets more, but not all, delayed messages. In the above test, periodically calling redeliver regularly gets 7-9/10 messages, where omitting that call sometimes only gets 1-3/10.

**Comment by zbentley** [comment]
Also reproduced on 2.10

**Comment by merlimat** [comment]
This looks to be caused by #12890. 

We're calling `this.getMessagesToReplayNow(1)` (which  pops the message out of the delayed-delivery tracker) but then we're not doing anything with that message because `minReplayedPosition == null`

**Comment by zbentley** [comment]
Thanks, I will test against a master build and respond here with results.
