### ISSUE TITLE
[Doc] inappropriate/Outdated description for metric pulsar_storage_backlog_size for namespace

### ISSUE THREAD

**Issue by MarvinCai** [apache/pulsar#15439]
### What issue do you find in Pulsar docs?

Description of  pulsar_storage_backlog_size for namespace (https://pulsar.apache.org/docs/en/reference-metrics/#namespace-metrics) said this metric is message count.
But looking into the code of how this metric get calculated, it's actually in byte.

### What is your suggestion?

Update to accurate description (in byte) if that's the case.

### Do you have any references?

Code reference:
https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java#L339
https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java#L79
https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java#L157
https://github.com/apache/pulsar/blob/master/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedger.java#L397-L402

### Would you like to fix this issue?

N/A

### Note

- [X] I have researched my question.

**Comment by Anonymitaet** [comment]
Hi @momo-jun can you take a look at this issue? Thanks

**Comment by momo-jun** [comment]
@MarvinCai thanks for filing this issue.
@tjiuming will follow up with the doc updates. Thanks for your volunteering.
