### ISSUE TITLE
[Doc] JSON/AVRO SerDe for Functions and Connectors  

### ISSUE THREAD

**Issue by cometa-haley** [apache/pulsar#15434]
### What issue do you find in Pulsar docs?

I am having a lot of issues while working with Functions and Connectors for the following reason: 
If a create a producer using python like this:
```
class InfluxTestSchema(Record):
    measurement = String()
    tags = Map(String())
    fields = Map(Integer())



client = pulsar.Client('pulsar://localhost:6650')
producer = client.create_producer('another-test-topic', schema=JsonSchema(InfluxTestSchema))
while True:
    msg = InfluxTestSchema(
        measurement='test_measurement',
        tags={"name": f'mickey_mouse'},
        fields={"age": random.randint(0, 100)}
    )
    producer.send(msg)
    sleep(5)
```

I am then able to use connectors for loading the data somewhere else. BUT if I try to use a function to preprocess the data in some way,  Connectors (I have tried Postgres and Influx) don't seem to be able to deserialize the data correctly. 
Currently I am trying to use a custom SerDe class for achieving the same effect as  `schema=JsonSchema(InfluxTestSchema)` in create_producer, but it doesn't seem to work. (Serialization seems to work, but connectors don't seem to understand the messages)
Here is my SerDe class:

```
class InfluxTestSchemaSerDe(SerDe):
    def __init__(self):
        self.schema = JsonSchema(InfluxTestSchema)

    def serialize(self, input):
        return self.schema.encode(input)

    def deserialize(self, input_bytes):
        return self.schema.decode(input_bytes)
```
(I tried the same approach with AVRO and postgres with similar outcome)

I would like to know how can I achieve the same behavior or how can I tell my sink that I am using a custom SerDe class (since I cannot give the sink my python code).
Sorry if it is a dumb question, I am kind of a Pulsar n00b.

### What is your suggestion?

Maybe some documentation in the functions section would help. If I figure out how to accomplish the task, would be glad to help out documenting it =)

### Do you have any references?

Main source: https://pulsar.apache.org/docs/en/functions-develop/

### Would you like to fix this issue?

Yes <3!

### Note

- [X] I have researched my question.

**Comment by Anonymitaet** [comment]
FYI @momo-jun since u'r working on the function docs.

**Comment by momo-jun** [comment]
Hi @freeznet can you take a look at this issue? Shall we clarify more in the SerDe section? It's beyond my knowledge.

**Comment by freeznet** [comment]
Hi @cometa-haley, currently the python functions do not support customize the schema, so all messages send from python functions are in BYTES schema, and this is why the other connectors cannot handle the messages correctly. 
There is a hacky way to do:

- use a Java function with the SerDe to convert the messages from Python (BYTES) to Avro Schema messages as an intermediate step, then use the output of Java function to the connectors.

**Comment by momo-jun** [comment]
Close the issue because of no plan for it yet, and a workaround has been provided instead.
