### ISSUE TITLE
CPU usage 100% when use Key_Shared

### ISSUE THREAD

**Issue by Shawyeok** [apache/pulsar#15445]
**Describe the bug**
When use `Key_Shared`, if one consumer consume slowly and others are normal, `MessageRedeliveryController#messagesToRedeliver` will keep growing and could be very large.

`MessageRedeliveryController#getMessagesToReplayNow` will be very expensive cause `messagesToRedeliver.items()` is a O(n) operation in both time and space complexity.
https://github.com/apache/pulsar/blob/2b2e0c50183c71e954f5c6e8bfcd7e36130279a5/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageRedeliveryController.java#L109-L122

In this situation, one thread cpu usage could be 100%, this could effects the publish latency of other topics on the same broker instance.

**To Reproduce**
1. start a standalone cluster
2. start a producer
```shell
$ bin/pulsar-perf produce -mk random persistent://public/default/test
```
4. start a slow consumer and a normal consumer
```shell
$ bin/pulsar-perf consume -st Key_Shared persistent://public/default/test
$ bin/pulsar-perf consume -st Key_Shared -r 0.1 persistent://public/default/test
```

**Screenshots**
CPU flame graph
![image](https://user-images.githubusercontent.com/5058708/166888460-8e70310e-3929-4c18-916d-431445e53ea7.png)

**Additional context**
- pulsar: `2.8.1`

**Comment by Shawyeok** [comment]
> When use Key_Shared, if one consumer consume slowly and others are normal, MessageRedeliveryController#messagesToRedeliver will keep growing and could be very large.

Additional context:
The slow consumer will ends with zero availablePermits, and message positions will be recorded in `MessageRedeliveryController#messagesToRedeliver`, when none of the whole batch of messages sent to consumer, `isDispatcherStuckOnReplays` will be marked.
https://github.com/apache/pulsar/blob/2b2e0c50183c71e954f5c6e8bfcd7e36130279a5/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java#L310-L330

Next time call `getMessagesToReplayNow` in readMoreEntries, it'll returns empty, then it'll read next batch of messages by cursor, therefor more message positions will be recorded.
https://github.com/apache/pulsar/blob/2b2e0c50183c71e954f5c6e8bfcd7e36130279a5/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java#L436-L446
https://github.com/apache/pulsar/blob/2b2e0c50183c71e954f5c6e8bfcd7e36130279a5/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java#L310-L330

**Comment by Shawyeok** [comment]
> @Shawyeok Can you attach the flame graph directly?

@merlimat  [cpu_profile.html.zip](https://github.com/apache/pulsar/files/8637078/cpu_profile.html.zip) attached

**Comment by surahman** [comment]
This is a very interesting issue to examine.

I think the time bound is likely `O(n*log(n))` due to the `TreeSet` generation (sorting) here:
https://github.com/apache/pulsar/blob/2b2e0c50183c71e954f5c6e8bfcd7e36130279a5/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageRedeliveryController.java#L116

**Comment by WJL3333** [comment]
fix by #17804

**Comment by zhanghaou** [comment]
We also encounter such problem，topics in the same broker publish latency is very high.  Any suggestions？ @merlimat @codelipenghui

**Comment by codelipenghui** [comment]
The issue should be fixed  by https://github.com/apache/pulsar/pull/17804
@zhanghaou @Shawyeok

**Comment by zhanghaou** [comment]
@codelipenghui  Does the fix pr can be cherry pick to branch 2.8.X?

**Comment by codelipenghui** [comment]
@zhanghaou We are only applying security patches for 2.8.x release for now.

**Comment by zhanghaou** [comment]
@codelipenghui OK, thanks.
