### ISSUE TITLE
 get a PulsarAdmin in function ,and then error calling pulsar interface

### ISSUE THREAD

**Issue by 704237006** [apache/pulsar#15443]
**Describe the bug**

When developing a function, I get pulsaradmin from the context and try to get the schema of the target outputtopic, but there was an error.

function code:
![image](https://user-images.githubusercontent.com/42430068/167084213-e0ba3133-18c7-4c70-96b2-7dca8010a4c1.png)
An error occurred while running function:
![cdcf0329ebb90b752ba9f5ce6eefaf1](https://user-images.githubusercontent.com/42430068/167083839-cc194c69-8a6d-432e-82f2-a7b8b81a7a7e.png)

**Comment by tisonkun** [comment]
Closing as stale. If it's still relevant to maintained versions, feel free to open a new issue
