### ISSUE TITLE
[feat](replicator): reset-cursor supports geo-replicator's subsription. 

### ISSUE THREAD

**Issue by ericsyh** [apache/pulsar#15466]
**Is your feature request related to a problem? Please describe.**

I want to use geo-replicate to migrate data from existing Pulsar cluster to a new Pulsar cluster by:
1. Create geo-replicate rule between exising cluster and new empty cluster.
2. Reset replicator cusror to earliest then migrate data. 

But i found that geo-replicator's subsription is an internal subs and cannot be reset by `reset-cursor`.

**Describe the solution you'd like**
I hope geo-replicator's subsription can be reset cursor by `reset-cursor` API.

**Comment by mattisonchao** [comment]
Hi, @ericsyh  What about this PR?
https://github.com/apache/pulsar/pull/14887

**Comment by mattisonchao** [comment]
The details please see #14887. closed.
