### ISSUE TITLE
NPE during get topic stats

### ISSUE THREAD

**Issue by Shoothzj** [apache/pulsar#15471]
### screenshot
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/12933197/167137942-20cb9264-3842-4644-acbd-72b44f3106c2.png">

### which version do you use
compile the master code for test

### content
I think it's a regression by https://github.com/apache/pulsar/pull/12401 when client `isSupportsPartialProducer` is false.
@equanz please have take a look

**Comment by Technoboy-** [comment]
Which test?

**Comment by Shoothzj** [comment]
@Technoboy- Sorry for misleading, we use pulsar nightly code for some tests. Not tests in pulsar repo.

**Comment by Shoothzj** [comment]
@Technoboy- @equanz It's caused by using null value for comparator. When `isSupportsPartialProducer ` is false, `PublisherStatsImpl::getProducerName` return null.

**Comment by equanz** [comment]
Thank you for sharing the issue. Could you tell me full stack traces and use cases, please? (I'm not sure when the publisher's producerName is null.)

The `isSupportsPartialProducer` is false means the broker conf `aggregatePublisherStatsByProducerName` is true and old publishers connects to the topic? Or, `aggregatePublisherStatsByProducerName` is false?
https://github.com/apache/pulsar/blob/f5019c81d2680b816eac768b1896333e04ab4214/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java#L131-L139

**Comment by Shoothzj** [comment]
@equanz Sorry for my late reply, I don't save the full stacktraces. But I think it's easy to reproduce using lower-version client like 2.8.0.

**Comment by equanz** [comment]
I've created the PR https://github.com/apache/pulsar/pull/15502 to fix the issue.

And I forgot the specification written below.
https://github.com/apache/pulsar/pull/15502#issuecomment-1122374761

**Comment by michaeljmarshall** [comment]
@Shoothzj - it would have been really helpful if your screen shot was actually text so that it could be indexed and searchable. I would have found this issue much sooner when debugging #15152, which was the same issue. I think it would be worth discussing the issue wording to remove "screenshot" since copied and pasted logs are much more valuable.
