### ISSUE TITLE
REST API  send message fail: cannot look up topic

### ISSUE THREAD

**Issue by xyhmnb** [apache/pulsar#15484]
**Describe the bug**
i use the latest version pulsar and find use the rest api to send message for some of the topics is error

**To Reproduce**
i have topic is "/persistent/public/default/my-topic"
use the url "http://pulsar.fscut.com:8080/topics/persistent/public/default/my-topic" to send http post request
but it response is network 
and then, i use the "/persistent/public/default/my_topic", its ok!
The difference between them is one used the "-",another one used the "_"

**Expected behavior**
I want it to be normal

**Screenshots**
log
![image](https://user-images.githubusercontent.com/30762020/167242757-2677c8c5-bc38-4f73-ac4b-09f7e7fb770f.png)
![企业微信截图_16519041715718](https://user-images.githubusercontent.com/30762020/167242790-87ef656c-1a8f-45be-b67e-3836f758025d.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by wuxuanqicn** [comment]
@xyhmnb Can you provide the request detail and response detail?
![image](https://user-images.githubusercontent.com/89442834/167248029-bf1acc51-d466-4ecc-8c8b-cdf638264058.png)

my local pulsar works fine
```
curl -X POST -H 'Content-Type: application/json' localhost:8080/topics/persistent/public/default/my-topic --data '{"messages":[{"payload":"RestProducer:1","key":"my-key","eventTime":"1603045262772","sequenceId":1,"disableReplication":false,"deliverAt":0,"deliverAfterMs":0,"schemaVersion":0},{"payload":"RestProducer:2","key":"my-key","eventTime":"1603045262772","sequenceId":2,"disableReplication":false,"deliverAt":0,"deliverAfterMs":0,"schemaVersion":0},{"payload":"RestProducer:3","key":"my-key","eventTime":"1603045262772","sequenceId":3,"disableReplication":false,"deliverAt":0,"deliverAfterMs":0,"schemaVersion":0}]}'
```

**Comment by xyhmnb** [comment]
thx, i try it . the rest api on local pulsar is ok.
but the problem is not there.
we have three brokers on the lan and have one proxy to forwarding the request on the internet.
now, the rest api only request some one of the machines. some topics are fail because no-partation topic exist one machine.(if not on this machine)

**Comment by xyhmnb** [comment]
@wuxuanqicn hello,i try to send it on the local pulsar.but its has other problem.
![image](https://user-images.githubusercontent.com/30762020/167358950-3fd7a200-b897-4f9a-8bc2-cb1adf355d02.png)

**Comment by wuxuanqicn** [comment]
> 

@xyhmnb Please provide more information, for instance curl with "-v" option. 
As you mentioned, proxy server is used to forward request, relative log maybe helpful too.

![image](https://user-images.githubusercontent.com/89442834/167760405-0d6a2ab2-af8a-44f0-83fe-775c7475e15a.png)
