### ISSUE TITLE
pulsar2.9.2 in C++ conflict with protobuf 3.17.2

### ISSUE THREAD

**Issue by ZGHAP** [apache/pulsar#15504]
when I compile the C++ source, it prompt as below:

[libprotobuf FATAL google/protobuf/stubs/common.cc:87] This program was compiled against version 3.3.0 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.17.2).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/pulsar/pulsar-client-cpp/pkg/deb/BUILD/apache-pulsar-2.8.3-src/pulsar-client-cpp/generated/lib/PulsarApi.pb.cc".)

############source section##############
pulsar::Client client("pulsar://10.1.11.122:6650");
pulsar::Consumer consumer;
pulsar::ConsumerConfiguration config;
config.setSubscriptionInitialPosition(pulsar::InitialPositionEarliest);
pulsar::Result result = client.subscribe("persistent://public/default/my-topic3", "consumer-1", config, consumer);

###########makefile##################
CC = g++ -std=c++17 -g -O3 -DNDEBUG -Werror=format

OBJS =  main.o SpSig.o libNanoLog.a BroadCastSig.o

LLFLAGS = -L/usr/local/lib/ -L/home/fhu/MM/C -L.
CCFLAGS = -I/usr/local/include/ -I/home/fhu/MM/C -I/home/fhu/MM/C/NanoLog/runtime
LDFLAGS = -lpthread -lzmq -ltinyxml -lprotobuf -lquickfix -lringbuffer -lNanoLog -lrt -lpulsar

NANOLOG_RUNTIME_DIR=./NanoLog/runtime

ALL:$(OBJS) decompressor
	$(CC) $(OBJS) $(LDFLAGS) $(CCFLAGS) $(LLFLAGS) -o  MM 

main.o:MamoruSpNano.cpp 
	$(CC) -g -c MamoruSpNano.cpp $(CCFLAGS) $(LLFLAGS) $(LDFLAGS) -o  main.o

SpSig.o:MamoruSp.pb.cc MamoruSp.pb.h
	$(CC) -c MamoruSp.pb.cc $(CCFLAGS) $(LLFLAGS) $(LDFLAGS) -o SpSig.o

BroadCastSig.o:MamoruStruct.pb.cc MamoruStruct.pb.h
	$(CC) -c MamoruStruct.pb.cc $(CCFLAGS) $(LLFLAGS) $(LDFLAGS) -o BroadCastSig.o

libNanoLog.a:
	$(MAKE) libNanoLog.a -C $(NANOLOG_RUNTIME_DIR)
	cp $(NANOLOG_RUNTIME_DIR)/libNanoLog.a .

decompressor: libNanoLog.a
	$(MAKE) decompressor -C $(NANOLOG_RUNTIME_DIR)
	cp $(NANOLOG_RUNTIME_DIR)/decompressor .	

clean:
	rm -rf *.o test
	@rm -f *.o compressedLog

clean-all:
	rm -rf *.o test
	@rm -f libNanoLog.a decompressor
	$(MAKE) clean-all -C $(NANOLOG_RUNTIME_DIR)

**Comment by tisonkun** [comment]
Closed as stale.

The development of the C++ client has been permanently moved to https://github.com/apache/pulsar-client-cpp. If it's still relevant, please open an issue there.
