### ISSUE TITLE
[Doc] Specify which ElasticSearch and Opensearch versions are compatible with Pulsar IO ElasticSearch Sink

### ISSUE THREAD

**Issue by nicoloboschi** [apache/pulsar#15514]
### What issue do you find in Pulsar docs?

In the Elastic Search Sink doc it is not specified which ElasticSearch and Opensearch versions are supported.
https://pulsar.apache.org/docs/en/io-elasticsearch-sink

### What is your suggestion?

Inform the users which versions are supported.

### Do you have any references?

ElasticSearch and Opensearch
https://pulsar.apache.org/docs/en/io-elasticsearch-sink

### Would you like to fix this issue?

no time

### Note

- [X] I have researched my question.

**Comment by Anonymitaet** [comment]
@momo-jun can you take a look at this issue? Thanks

**Comment by Anonymitaet** [comment]
Fix in https://github.com/apache/pulsar/pull/15515
