### ISSUE TITLE
Supporting Java 9 Modular System

### ISSUE THREAD

**Issue by drriguz** [apache/pulsar#15523]
**Is your feature request related to a problem? Please describe.**
I'm currently trying to build a java gui browser for pulsar, however, I found that pulsar jars are not compatible with java 9. 

**Describe the solution you'd like**
Please consider to support the java 9 modular system.

**Additional context**
I'm using javafx/jdk11, and the shaded libraries(client.jar/client-admin.jar, etc) seems to cause errors when using modular system, the errors shows like the following:

```
1 actionable task: 1 executed
错误: 未命名的模块同时从 pulsar.client 和 pulsar.client.admin.api 读取程序包 org.apache.pulsar.common.stats
错误: 未命名的模块同时从 pulsar.client 和 pulsar.client.admin.api 读取程序包 org.apache.pulsar.common.protocol.schema
错误: 未命名的模块同时从 pulsar.client 和 pulsar.client.admin.api 读取程序包 org.apache.pulsar.common.policies
错误: 未命名的模块同时从 pulsar.client 和 pulsar.client.admin.api 读取程序包 org.apache.pulsar.common.policies.impl
错误: 未命名的模块同时从 pulsar.client 和 pulsar.client.admin.api 读取程序包 org.apache.pulsar.common.policies.data
```

I've no idea how to fix that, is there any workaround if it's not possible to support java 9 now?

**Comment by heesung-sn** [comment]
Please refer to this runtime Java version recommendation, https://github.com/apache/pulsar#pulsar-runtime-java-version-recommendation

**Comment by tisonkun** [comment]
Closed as answered. It cannot reproduce.

Please open a new issue if it's still relevant to the maintained versions.
