### ISSUE TITLE
[Doc] Update encryption and decryption documentation for cpp, python and nodejs clients

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar#15522]
### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/en/security-encryption/#get-started
The cpp, python and nodejs clients do not support the ecdsa algorithm and we should consider highlighting it in the documentation

### What is your suggestion?

https://pulsar.apache.org/docs/en/security-encryption/#get-started
The cpp, python and nodejs clients do not support the ecdsa algorithm and we should consider highlighting it in the documentation

### Do you have any references?

https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/lib/MessageCrypto.cc
No ecdsa algorithm related content found

### Would you like to fix this issue?

The cpp, python and nodejs clients do not support the ecdsa algorithm and we should consider highlighting it in the documentation

### Note

- [X] I have researched my question.

**Comment by Anonymitaet** [comment]
@momo-jun can you take a look at this issue? Thanks

**Comment by momo-jun** [comment]
Hi @tuteng , this issue has been addressed in #15526 . Can you pls review that PR? Thanks.
