### ISSUE TITLE
[Discussion] New Pulsar Website

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#15538]
[We've launched the New Pulsar Website on May 11, 2022 (UTC +8).](https://lists.apache.org/thread/7nx3rm3cmpbw0ws1b62k17935xgyw2tj)

Now everything goes fine except for a few known issues as below. 

### `Search` does not fully work
🙌 Status: WIP. 
🙌 Technical details and progress see [here1](https://apache-pulsar.slack.com/archives/C02Q4JLUB38/p1649233950692869) and [here2](https://apache-pulsar.slack.com/archives/C02Q4JLUB38/p1657259250440579)
Issue:
![image](https://user-images.githubusercontent.com/50226895/177932445-e4cf5288-43ed-410a-8f66-1d1f200ff894.png)

### Some new contents are not completely ready
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/50226895/167792907-42ca0152-5707-499a-a9fc-c6afc4615ef7.png">

**We're continually improving them all the time**. 🙌
Feel free to comment if you have any suggestions for the New Pulsar Website, thanks!

**Comment by hpvd** [comment]
looks awesome!!

when looking in devtools (firefox) there seems to be a small error:
![2022-05-11_12h55_29](https://user-images.githubusercontent.com/5681880/167833801-44c6b9b7-7960-4722-9477-dc6b2050060e.png)

**Comment by hpvd** [comment]
it's a little bit irritating that not the latest release is advertised (probably missing blog content...maybe linking to changelog https://github.com/apache/pulsar/releases/tag/v2.10.0 ?)
![2022-05-11_13h11_05](https://user-images.githubusercontent.com/5681880/167836690-051a5569-34b2-4d52-80c5-7b371f2b61c5.png)

**Comment by hpvd** [comment]
stunning fast!

**Comment by hpvd** [comment]
depending on browser used: the step is less or more visible:
![2022-05-11_13h17_08](https://user-images.githubusercontent.com/5681880/167837437-037e916c-60b7-49f1-a02d-ade90859e1a2.png)

**Comment by Anonymitaet** [comment]
@hpvd Thanks for raising this up! @Paul-TT will look into #1 and #3 issues.

**Comment by Anonymitaet** [comment]
> it's a little bit irritating that not the latest release is advertised (probably missing blog content...maybe linking to changelog https://github.com/apache/pulsar/releases/tag/v2.10.0 ?) ![2022-05-11_13h11_05](https://user-images.githubusercontent.com/5681880/167836690-051a5569-34b2-4d52-80c5-7b371f2b61c5.png)

@hpvd Now the latest tech blog is 2.9.2. 
2.10 tech blog is not available, @DaveDuggins is working on it, stay tuned.

**Comment by dave2wave** [comment]
> depending on browser used: the step is less or more visible (sceenshot was taken from firefox)
> ![2022-05-11_13h17_08](https://user-images.githubusercontent.com/5681880/167837437-037e916c-60b7-49f1-a02d-ade90859e1a2.png)

This is the animated sine wave graphic. @hpvd di this ever animate? What brower, version, and os are you on? Do you allow javascript or block it?

**Comment by dave2wave** [comment]
Here's what I see on macOS Catalina, Firefox 99.0.1
<img width="1187" alt="Screen Shot 2022-05-11 at 9 14 51 PM" src="https://user-images.githubusercontent.com/29803617/167991114-1a03ab33-d692-48bb-b771-189c8e1c179d.png">

**Comment by hpvd** [comment]
@dave2wave 

seems like a grabbed an extreme case with Firefox 100 @ W10 @ 4K screen, everything is animated perfectly, js active..
![2022-05-11_13h17_08](https://user-images.githubusercontent.com/5681880/168011964-2ec6b069-b4aa-4a8f-8b46-38c4cd11995b.png)

**Comment by hpvd** [comment]
@dave2wave
in other environments it's visible but not that extreme:

always latest browser versions:


![2022-05-12_08h55_06](https://user-images.githubusercontent.com/5681880/168012331-efcc1db6-f056-4751-bba4-cb4b119fb494.png)
![2022-05-12_08h57_05](https://user-images.githubusercontent.com/5681880/168012336-d4fdb080-3fe6-47e8-ab21-21414da39b86.png)
![2022-05-12_09h02_07](https://user-images.githubusercontent.com/5681880/168012339-65005449-39b8-4afb-8a00-dcc8d20afab5.png)

**Comment by Anonymitaet** [comment]
I got much negative feedback about the **blue** background color, it **decreases readability significantly**. 

They prefer the **white** background color as before, which looks more clearly.

Feel free to +1 if you feel the same, thanks!

**Comment by jinmu003** [comment]
Can we redesign this part?
<img width="603" alt="Screen Shot 2022-05-12 at 8 09 32 PM" src="https://user-images.githubusercontent.com/103222375/168204155-80c233ce-0d03-4d72-b089-61a8267d878b.png">

**Comment by Anonymitaet** [comment]
Hi @jinmu003 thanks for your feedback! Can you explain more about your requirements? Do you mean re-categorize the industries or something else?

P.S. We plan to [add filters for the Case Studies page](https://github.com/apache/pulsar/issues/15550) to keep things organized.  . 
<img width="954" alt="image" src="https://user-images.githubusercontent.com/50226895/168224688-82d3a5a0-1dcb-46df-bfb3-a0f9dc9b943c.png">

**Comment by hpvd** [comment]
what do think of documenting and highlighting the project quality with hard facts and numbers
using automatic badges summarizing some interesting/important quality markers?

e.g.
activity: date of latest commit, latest release, number of contributers
check status: tests, owasp-dep-check
popularity: number of downloads

this could be done either on the new website
or in the readme.md shown on github (or both:-)

for how to see:

https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

and search for github on https://shields.io/

**Comment by dave2wave** [comment]
> We got much negative feedback about the **blue** background color, it **decreases readability significantly**.

Who is the "we" here? On what channel was this feedback received?

**Comment by hpvd** [comment]
@Anonymitaet  showing github stars on the website as already planned in https://github.com/apache/pulsar/issues/15550 task 4
goes into the same direction as proposal in https://github.com/apache/pulsar/issues/15538#issuecomment-1126064195

The other markers named there, goes more into detail and give every prospect/interested party and also existing users a great peace of mind to use / to start using pulsar - it could perfectly argued/justified to rely on pulsar (beside the great feature sets) even in large projects...

**Comment by Anonymitaet** [comment]
@hpvd thanks for your valuable suggestions! Adding badges to README.md is a good way to show community growth.

**Comment by Anonymitaet** [comment]
@dave2wave Pulsar Website User Survey and Slack.

**Comment by hpvd** [comment]
two things that are not that great for seo (ranking in search engines) and accessibility:

- alt tag of pulsar logo is misspelled
- title of svg (images) are pretty generic 
-
![2022-05-16_12h56_30](https://user-images.githubusercontent.com/5681880/168578738-1481ce84-c4b5-4aae-8620-a003fb62307c.png)

![2022-05-16_12h53_48](https://user-images.githubusercontent.com/5681880/168578811-fe606c12-80f6-4948-882e-e1a1f03e51f2.png)

**Comment by Anonymitaet** [comment]
@hpvd good catch! We'll update them

**Comment by Anonymitaet** [comment]
@zhaoyajun2009 thanks for your feedback! We need to check other people's thoughts on this.
If you feel the same, please 👍

**Comment by Anonymitaet** [comment]
> It is too much white space！ <img alt="image" width="1677" src="https://user-images.githubusercontent.com/92070379/168842667-f8569fe4-0227-429f-a8e7-39d19603d342.png">

@zhaoyajun2009 thanks for your feedback! We need to check other people's thoughts on this.
If you feel the same, please 👍 on @zhaoyajun2009's comment.

**Comment by hpvd** [comment]
doc/connectors:

- tiny: should be plural (see attachment)
- when following link to "elastic search" config: the menu disappears 
https://pulsar.apache.org/docs/io-elasticsearch-sink/
- "elastic" could not be found by search

![2022-05-18_16h03_01](https://user-images.githubusercontent.com/5681880/169061472-5685dbae-273b-47e2-bf17-a3c98dc28cd5.png)


![2022-05-18_16h03_46](https://user-images.githubusercontent.com/5681880/169061509-b8aed0f5-da30-4cee-a8be-afa09dcbc6c5.png)

**Comment by hpvd** [comment]
the visible structuring of blog-posts is not that clear,
for comparison, simple release notes are much easier to understand
- both at 100% zoom:
![2022-05-18_16h46_24](https://user-images.githubusercontent.com/5681880/169071806-28c1226f-eca0-4e01-9a87-d2a0d5acbea5.png)

**Comment by Anonymitaet** [comment]
@hpvd thanks for your feedback! Please see my interlined reply: 

> * tiny: should be plural (see attachment)

OK, we're redesigning the Pulsar Information Architecture. Re-constructing the connector doc is on the way. 
/ cc @D-2-Ed @DaveDuggins @momo-jun 

> * when following link to "elastic search" config: the menu disappears
>   https://pulsar.apache.org/docs/io-elasticsearch-sink/

All connectors do not have the left navigation. They only have the right panel.

> * "elastic" could not be found by search

`Search does not work properly` is a known issue recorded [here](https://github.com/apache/pulsar/issues/15538).

**Comment by Anonymitaet** [comment]
> the visible structuring of blog-posts is not that clear, for comparison, simple release notes are much easier to understand/overview both at 100% zoom: 

Hi @DaveDuggins you're the author of the 2.10.0 tech blog, any thoughts on this comment?

**Comment by hpvd** [comment]
@Anonymitaet  regarding blog structure, it's possibly mostly about predifined css for different elements (headlines, p, lists) like
- font sizes 
- whitespaces
- margins/intend
- ...

**Comment by asafm** [comment]
Notes on Main Page
![image](https://user-images.githubusercontent.com/989425/169349752-59a9b9cb-2721-4850-8d8a-0defe6befa69.png)

1. Background color: I can express this technically as I'm not a designer, but I can say it doesn't feel right. Something about the contrast to the other colors on the page and that vague color to it, instead more bright and vivid colors, broadcast that sense of "gloominess" to it. Not sure I'm expressing my self correctly  - it's just doesn't feel right :)
2. The following items - Search bar, Sun, Github stars - just seem to be in the wrong place visually. It creates a big whitespace gap and the alignment and spacing between them is not symmetrical. It's just fees like they are in the wrong place.
3. Logo positioning and white space - it's as if it's just thrown out there without any "anchor" to it, maybe due to the large whitespace this opening part of the main page has in general.

**Docs section**
![image](https://user-images.githubusercontent.com/989425/169351900-145073a6-4ae2-4d7c-bcfe-4ec2b736bf90.png)

1. There is a very large section of whitespace between the actual docs content to the upper section (bar).
2. The logo looks mis-aligned relative to the content section below IMO, as if it is just "thrown there" in metaphorical speaking.

IMO we should aim for a more "neat"/clean look, maybe in it's own page like [here](https://docs.pinot.apache.org)?

**Comment by Anonymitaet** [comment]
@hpvd @asafm I feel the same as you.

Here is the feedback from the website designer team:
> We've run the beta version of the new website for more than 3 months. The beta period has passed. The design was approved by the community and executed. As representatives to the community and members of the design team, we have to commit to the design that has been implemented. Once a decision is made, we support that decision. We can revisit in 3-6 months as needed and after appropriate usability testing, etc.

But do not hesitate to add more comments! Suggestions are always welcome!

**Comment by hpvd** [comment]
@Anonymitaet 

did some optimizations on the wave images, to cut size down (both are near 1 MB)
to improve download time, client and server load...
Got less than 1/3 for each image with IMHO near identically visual quality.

just have a look:

originals (downloaded from website):
![feature-waves-top_original-918KB](https://user-images.githubusercontent.com/5681880/171376152-eccf21e6-dce6-448a-ba74-7237b04b485e.png)
![feature-waves-btm_original-930KB](https://user-images.githubusercontent.com/5681880/171376155-7b83dbb7-0102-417f-8dce-52d4fa586542.png)

optimized versions:
![feature-waves-btm_opti-267KB](https://user-images.githubusercontent.com/5681880/171376228-d300f0ac-0ced-4a63-962f-daf5783b5116.png)
![feature-waves-top_opti-259KB](https://user-images.githubusercontent.com/5681880/171376232-3ac70c80-ee62-48f1-b0cf-1b67650cb613.png)

**Comment by Anonymitaet** [comment]
Hi @hpvd thanks for your great idea, that makes sense! Would you like to replace the old one with the new image? Please submit the new image to [pulsar repo](https://github.com/apache/pulsar). Thanks!

cc @Paul-TT

**Comment by hpvd** [comment]
@Anonymitaet please let your designer double check if quality target is reached with the new image versions.
He/she could easily save the images from my comment and integrate them into the website.

**Comment by visortelle** [comment]
I'm watching @sijie's video on YouTube and the website looks much more readable and modern than it looks now.

<img width="1438" alt="Screenshot 2023-02-10 at 7 44 50 AM" src="https://user-images.githubusercontent.com/9302460/218021524-17c7200a-b338-435f-8871-4d9870fd7ece.png">

**Comment by tisonkun** [comment]
@visortelle Good to know, lol.
