### ISSUE TITLE
REST API Redirect（307） location is error

### ISSUE THREAD

**Issue by xyhmnb** [apache/pulsar#15546]
**Describe the bug**
i use the rest api to send message,but it return the err.
![image](https://user-images.githubusercontent.com/30762020/167828304-58d93fc5-7059-46d8-aadc-e4cd5ec8241f.png)

the 105 broker donnt own the topic（my1）

**To Reproduce**
1. create some topics on the Cluster.
2. select one topic and one broker.（the broker donot own this topic ）
3. use the rest api to send message

because this broker donot own this topic, the rest api return to redirect (307)  to the correct address.
and then, the problem is return location address is err.

**Expected behavior**
i hope to redirect the correct address.

**Screenshots**
![image](https://user-images.githubusercontent.com/30762020/167827653-df90d23d-88ee-4b5c-a7b7-9b95bf5b0bc9.png)

**Comment by xyhmnb** [comment]
@wuxuanqicn hello, I described the problem well, can you help me?

**Comment by Technoboy-** [comment]
Fixed by #15551
