### ISSUE TITLE
[Improvements] New Pulsar Website

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#15550]
We launched the [New Pulsar Website](https://pulsar.apache.org/) on May 11, 2022.

If you have more suggestions on the website, feel free to discuss [here](https://github.com/apache/pulsar/issues/15538).

➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖

This issue records the improvements that will be implemented based on our consensus.

Please submit your code to the [pulsar-site repo](https://github.com/apache/pulsar-site).

The framework of the New Pulsar Website: https://docusaurus.io/

🔸🔸🔸🔸🔸🔸

### 1. Show line NO. in code blocks

⭐️ Task status: Done in https://github.com/apache/pulsar-site/pull/75

Examples:
- https://docs.taichi.graphics/
<img width="696" alt="image" src="https://user-images.githubusercontent.com/50226895/168029272-a8255537-a523-476f-b4e2-f0dd49286b77.png">

- https://github.com/taichi-dev/docs.taichi.graphics/pull/139/files 
- https://gist.github.com/uditalias/3969a20ef759bf3a8757499429b30063 

🔸🔸🔸🔸🔸🔸

### 2. Add filters to the [Ecosystem](https://pulsar.apache.org/ecosystem) and the [Case Studies](https://pulsar.apache.org/case-studies) pages

⭐️ Task status: 

Examples: 
https://en.pingcap.com/customers/
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/50226895/167985599-c8e20641-334d-4d42-882b-02cd26c7978e.png">

Requirements:
- For the Ecosystem page: `Filter by Type` + `Search` box
- For the Case Studies page: `Filter by Industry` + `Search` box

🔸🔸🔸🔸🔸🔸

### 3. Add floating window 

⭐️ Task status: Done in https://github.com/apache/pulsar-site/pull/76

Examples:
https://kubesphere.io/
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/50226895/167986563-b5412ad9-7d57-4ac2-bf5c-1e2ec918895a.png">

Requirements:
- Context: 🚀 Pulsar Summit San Francisco 2022 will take place on August 18th, 2022. [Register now](https://pulsar-summit.org/) and help us make it an even bigger success by spreading the word on social media!

🔸🔸🔸🔸🔸🔸

### 4. Show GitHub Star NO. 

⭐️ Task status: 

Examples:
https://clickhouse.com/ 
<img width="523" alt="image" src="https://user-images.githubusercontent.com/50226895/167986260-0dad9aad-699a-43ea-8608-c49450f3adca.png">

Requirements:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/50226895/167986846-75c51734-f64d-4aa3-90fa-e463958ba0c0.png">

cc @urfreespace

**Comment by Anonymitaet** [comment]
@zrsaber will finish issues 2 & 4

**Comment by SignorMercurio** [comment]
Shall we close this issue?

**Comment by Anonymitaet** [comment]
@SignorMercurio yes, closed.
