### ISSUE TITLE
[Doc] The contributing page URL in CONTRIBUTING.md is not correct

### ISSUE THREAD

**Issue by boatrainlsz** [apache/pulsar#15561]
### What issue do you find in Pulsar docs?

The contributing page URL(https://pulsar.apache.org/en/contributing) in CONTRIBUTING.md is not correct, as shown below:
![image](https://user-images.githubusercontent.com/18243785/168031011-0fd525fd-3494-4f03-9454-f479942ea979.png)
after some researching, I think the right URL might be https://pulsar.apache.org/contributing.

### What is your suggestion?

change the contributing page URL to https://pulsar.apache.org/contributing

### Do you have any references?

https://github.com/apache/pulsar/blob/master/CONTRIBUTING.md
https://pulsar.apache.org/en/contributing
https://pulsar.apache.org/contributing

### Would you like to fix this issue?

sure

### Note

- [X] I have researched my question.

**Comment by Technoboy-** [comment]
Fixed by https://github.com/apache/pulsar/pull/15595
