### ISSUE TITLE
[python] Pulsar Client 2.10.0 package is missing from PyPi for Macosx 12

### ISSUE THREAD

**Issue by ca-simone-chiorazzo** [apache/pulsar#15585]
On Pypi, there are only wheels built for MacOS 11. The current stable version of macOS is the 12 and I would expect to have wheels built also for such a version

**Comment by merlimat** [comment]
@ca-simone-chiorazzo @zhavir  The version compiled for MacOS 11.0 is supposed to work on any version >= 11.0, including 12.1, 12.2, ... 

If you do `pip3  debug --verbose` you should be able to see all the tags supported by your python version. Can you share yours?

**Comment by zhavir** [comment]
> @ca-simone-chiorazzo @zhavir The version compiled for MacOS 11.0 is supposed to work on any version >= 11.0, including 12.1, 12.2, ...
> 
> If you do `pip3 debug --verbose` you should be able to see all the tags supported by your python version. Can you share yours?

mine is: 
https://www.codepile.net/pile/vEgpoxA1

but when I try to install the pulsar-client dep I get: 
```
pip install pulsar-client==2.10
Looking in indexes: https://pypi.org/simple
ERROR: Could not find a version that satisfies the requirement pulsar-client==2.10 (from versions: 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.3, 2.7.0, 2.7.1, 2.7.2, 2.7.2.post0, 2.7.3, 2.8.0, 2.8.0.post0)
ERROR: No matching distribution found for pulsar-client==2.10
```

**Comment by ca-simone-chiorazzo** [comment]
I'm using a python 3.8.6 virtualenv on a mac with MacOS 12.3.1 (21E258), this is the output of pip debug:
```
python -m pip debug | grep -i macosx

WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
  cp38-cp38-macosx_10_16_x86_64
  cp38-cp38-macosx_10_16_intel
  cp38-cp38-macosx_10_16_fat64
  cp38-cp38-macosx_10_16_fat32
  cp38-cp38-macosx_10_16_universal2
  cp38-cp38-macosx_10_16_universal
  cp38-cp38-macosx_10_15_x86_64
  cp38-cp38-macosx_10_15_intel
  cp38-cp38-macosx_10_15_fat64
  cp38-cp38-macosx_10_15_fat32
```

The output is weird, looks like the platform tags haven't been updated along with the OS major update.
Installing a python 3.8.13 from scratch I got the following output instead

```
python -m pip debug | grep -i macosx
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
  cp38-cp38-macosx_12_0_x86_64
  cp38-cp38-macosx_12_0_intel
  cp38-cp38-macosx_12_0_fat64
  cp38-cp38-macosx_12_0_fat32
  cp38-cp38-macosx_12_0_universal2
  cp38-cp38-macosx_12_0_universal
  cp38-cp38-macosx_11_0_x86_64
  cp38-cp38-macosx_11_0_intel
  cp38-cp38-macosx_11_0_fat64
  cp38-cp38-macosx_11_0_fat32
```

@merlimat Do you think I should raise a ticket to virtualenv / python for this? Looks like that the platform tags are not updated along with a major upgrade of the OS. The only solution that I've found is to re-install the python interpreter to get the right tags.

**Comment by merlimat** [comment]
@zhavir Looks like you're on MacOS 10.15? The wheels are compiled with 11.0 as the min version. 

We wanted to try to target 10.15 instead. There were few issues before, though hopefully we can get away with it. 

@ca-simone-chiorazzo Maybe the pre-compiled Python was compiled targeting MacOS 10.16 and that's why pip will not fetch any wheel tagged with 11.0. As above, if we target 10.15, it should be "fixing" this issue.

**Comment by tisonkun** [comment]
Closed as stale. The development of the Python client has been permanently moved to http://github.com/apache/pulsar-client-python. Please open an issue there if it's still relevant.
