### ISSUE TITLE
Python pulsar-client 2.8 is not compatible with broker 2.10.0

### ISSUE THREAD

**Issue by zbentley** [apache/pulsar#15610]
**Describe the bug**
The Python `pulsar-client` package at version 2.8.1 on Macos cannot connect to Pulsar brokers at version 2.10.0.

**To Reproduce**
1. Ensure a 2.10 broker standalone instance is running (I used `brew install apache-pulsar` and confirmed the version with `brew info apache-pulsar`).
1. With a working Python environment, do `pip install 'pulsar-client>2.8'`
1. Do `python -c "import pulsar; pulsar.Client('pulsar://localhost:6650').get_topic_partitions('foo')"`
1. Observe that a ConnectError is raised.
1. Do `pip install pulsar-client>=2.10`
1. Do `python -c "import pulsar; pulsar.Client('pulsar://localhost:6650').get_topic_partitions('foo')"`
1. Observe that a ConnectError is not raised.

**Expected behavior**
Old clients should be forwards-compatible with new broker versions unless documented not to be. I couldn't find any docs indicating that this will not work.

**Desktop (please complete the following information):**
 - OS: MacOS 12, Python 3.7.13 via pyenv.

**Comment by merlimat** [comment]
@zbentley It looks some weird stuff with the local DNS. 

I can repro locally too and switching the url to `pulsar://127.0.0.1:6650` works. I don't think the 2.10 broker is involved at all in the interaction. 

The 2.8.1 client is connecting to the IPv6 address first and not trying any other one: 

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/62500/168506715-1d1340de-12dd-450c-91a3-ae20eb9de6e4.png">

2.10 client is trying all the IP addresses instead, first IPv6 and then it falls back to IPv4: 

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/62500/168506855-f77089ac-266b-48e3-ac01-340f7c980a7d.png">

**Comment by zbentley** [comment]
Is this a regression of https://github.com/apache/pulsar/issues/11950 ?

**Comment by merlimat** [comment]
Yes. That fix was backported to 2.8.2 and that's why 2.8.1 has the issue

**Comment by zbentley** [comment]
That makes sense. In this case, this issue can be closed (unless y'all would like to document the incompatibility somehow).
