### ISSUE TITLE
[PIP-168]  Support zero-copy of NIC to NIC on Proxy

### ISSUE THREAD

**Issue by coderzc** [apache/pulsar#15631]
Mailing list thread: https://lists.apache.org/thread/gjys9tvbd5hy28mbkbcq7wkqfldycn7v

## Motivation

Currently, when the `Proxy` server transfer data will have four triggered the user mode and kernel mode of context switching, respectively is the read() / write() call and return when cut, it is inefficient for the `Proxy`.

There is an efficient way of reducing the times of copies of data and reducing CPU load. for the Linux system, we can use [`splice`](https://man7.org/linux/man-pages/man2/splice.2.html) system call.

Data transfer process diagram of `read` and `write`:

<img width="618" alt="image" src="https://user-images.githubusercontent.com/26179648/169450870-ce6bd264-0362-41ad-b676-106f0c8fab9f.png">

Data transfer process diagram of `splice`:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/26179648/169450908-9cbe9561-2c88-410b-ac38-9c7ec6df3d34.png">

More details about the proxy protocol see:
* [man splice](https://man7.org/linux/man-pages/man2/splice.2.html)
*  [design_and_implementation_of_zero_copy_data_path_for_efficient](https://static.aminer.org/pdf/PDF/000/253/158/design_and_implementation_of_zero_copy_data_path_for_efficient.pdf)
* [Two new system calls: splice() and sync_file_range()](https://lwn.net/Articles/178199/)
* [Netty's splice support](https://netty.io/news/2015/05/07/4-0-28-Final.html#:~:text=This%20release%20includes%20support%20for%20splice%20when%20using%20the%20native%20epoll%20transport.%20Splicing%20allows%20to%20directly%20transfer%20bytes%20from%20one%20filedescriptor%20to%20another%20without%20copy%20data%20from%20kernel%20to%20user%2Dspace.%20This%20makes%20splice%20a%20perfect%20fit%20i.e%20when%20you%20want%20to%20write%20a%20TCP%20proxy.)

## Goal

Support zero-copy of NIC to NIC on Proxy, we can get some benefits:
* Reduce the CPU load
* Improve the network throughput
* Reduce the delay

## Implementation

* add a new config `proxyZeroCopyModeEnabled` in the proxy server, If enabled, we will Use [splice](https://netty.io/news/2015/05/07/4-0-28-Final.html#:~:text=This%20release%20includes%20support%20for%20splice%20when%20using%20the%20native%20epoll%20transport.%20Splicing%20allows%20to%20directly%20transfer%20bytes%20from%20one%20filedescriptor%20to%20another%20without%20copy%20data%20from%20kernel%20to%20user%2Dspace.%20This%20makes%20splice%20a%20perfect%20fit%20i.e%20when%20you%20want%20to%20write%20a%20TCP%20proxy.) system call instead of read() / write() for linux system.
* It should only work as `proxyLogLevel == 0`
* It can't work when the connection opens TLS

**Comment by lhotari** [comment]
@coderzc Are you thinking of covering TLS too? Is it technically even possible in that case?

**Comment by lhotari** [comment]
> Use [splice](https://man7.org/linux/man-pages/man2/splice.2.html) system call instead of read() / write() for linux system.

@coderzc I suppose you mean to use [Netty's splice support](https://netty.io/news/2015/05/07/4-0-28-Final.html#:~:text=This%20release%20includes%20support%20for%20splice%20when%20using%20the%20native%20epoll%20transport.%20Splicing%20allows%20to%20directly%20transfer%20bytes%20from%20one%20filedescriptor%20to%20another%20without%20copy%20data%20from%20kernel%20to%20user%2Dspace.%20This%20makes%20splice%20a%20perfect%20fit%20i.e%20when%20you%20want%20to%20write%20a%20TCP%20proxy.)?

I can see that it could work when TLS isn't used. With TLS, I don't think it could work unless SNI proxying is used. Perhaps that would be a way forward, introducing SNI proxying in the Pulsar Proxy itself? I guess it would also require client side SNI proxying support which already exists, but has to be explicitly enabled.

**Comment by coderzc** [comment]
> @coderzc Are you thinking of covering TLS too? Is it technically even possible in that case?
> 
> I guess a SNI Proxy could handle that with TLS, but not Pulsar Proxy.

yes, I thinking of covering TLS too, but I want to try transform the `SslHandler` to make it possible.

**Comment by coderzc** [comment]
> [improve][proxy] Support zero-copy of NIC to NIC on Proxy #15678

yes, I will use [Netty's splice support](https://netty.io/news/2015/05/07/4-0-28-Final.html#:~:text=This%20release%20includes%20support%20for%20splice%20when%20using%20the%20native%20epoll%20transport.%20Splicing%20allows%20to%20directly%20transfer%20bytes%20from%20one%20filedescriptor%20to%20another%20without%20copy%20data%20from%20kernel%20to%20user%2Dspace.%20This%20makes%20splice%20a%20perfect%20fit%20i.e%20when%20you%20want%20to%20write%20a%20TCP%20proxy.)

I want remove the `SslHandler` after completed handshake, I still try again.

**Comment by lhotari** [comment]
> I want remove the `SslHandler` after completed handshake, I still try it.

I don't think that it could work without implementing SNI  proxying.

**Comment by coderzc** [comment]
> > I want remove the `SslHandler` after completed handshake, I still try it.
> 
> I don't think that it could work without implementing SNI proxying.

That's indeed so.

**Comment by coderzc** [comment]
@lhotari @merlimat @cbornet @nodece  I have sent a vote email, could you take a look.
https://lists.apache.org/thread/2ycpoltmh7z76nj62bz35q5o64x7by1w

**Comment by rdhabalia** [comment]
@coderzc why can't we use SNI routing and use enterprise solution 
https://github.com/apache/pulsar/wiki/PIP-60%3A-Support-Proxy-server-with-SNI-routing
eg: ATS, HAProxy?  why are we adding unnecessary component and complex module in pulsar git repo?
