### ISSUE TITLE
Bookie存储占用的存储一直不释放，且没有topic堆积（三节点bookie）

### ISSUE THREAD

**Issue by MrKong6** [apache/pulsar#15644]
![image](https://user-images.githubusercontent.com/19570750/168966111-216bdd58-632d-4819-a539-c74f67862eaa.png)
![image](https://user-images.githubusercontent.com/19570750/168966154-3fe1aa96-b7e3-4b7e-b1b8-2d8f9fbd5b5f.png)
![image](https://user-images.githubusercontent.com/19570750/168966205-bf4714e5-dc0d-4e78-af48-a017e7bcec93.png)

**Comment by MrKong6** [comment]
版本是2.4.0

**Comment by tisonkun** [comment]
Closed as stale. Feel free to open a new issue if it's still relevant for maintained versions.

2.4.0 is end of life. And the latest stable version now is 2.10.2.
