### ISSUE TITLE
[New Website] Set up Matomo (an alternative to Google Analytics)

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#15664]
Comments from @dave2wave: 

Google Analytics are no longer allowed on ASF websites due to privacy concerns. See https://privacy.apache.org/policies/website-policy.html 

This is a new policy. The privacy committee has setup an alternative Matomo service [- ](https://privacy.apache.org/matomo/)[https://privacy.apache.org/matom](https://privacy.apache.org/matomo/)o/

🔹🔹🔹🔹🔹🔹

Comments from @Anonymitaet: 

Currently, Pulsar is using Google Universal Analytics. Google Universal Analytics will no longer process new data in standard properties beginning July 1, 2023. Organizations that use Google Universal Analytics need to [switch over to a Google Analytics 4 property](https://support.google.com/analytics/answer/11583528). 

If we make a consensus on migrating from Google Universal Analytics to Matomoto, we do not need to do that switchover.

Since GA is much more powerful than Matomo, may we keep both GA and Matomo for now? 
GA will expire next year, we'll only use Matomo them.

**Comment by dave2wave** [comment]
@Anonymitaet
1. How does Google Analytics 4 property fix the PII issues with GA? Nothing on that link you provided indicates any improvements.
2. Here is what Google has about GDPR - https://support.google.com/analytics/answer/6366371?hl=en#zippy=%2Cin-this-article
3. The ASF has taken several years to address GDPR and this issue should be fully decided by the Foundation in one month. This is being done to protect the Foundation. This will become a hard policy of the ASF - No Google Analytics.

**Comment by tisonkun** [comment]
I'm going to send an email to privacy@apache.org, asking for a site ID and integrating the website with the Matomo service.

In the first place, we keep the Google Analytics settings until it's forcibly forbidden by the ASF or we're confident that the Matomo solution has completed replace.

**Comment by tisonkun** [comment]
FYI @urfreespace
