### ISSUE TITLE
[New Website] Wrong NO. in steps 

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#15662]
@BewareMyPower has reported this issue:

I found another bug of the new website again.:wink: See the following screenshot (https://pulsar.apache.org/docs/next/schema-understand). The indexes should be 1,2,3, not 1,11,16.
In other tab pages, the indexes are 1,9 and 1,11,17. It looks like a problem related to the Markdown rendering.

![image](https://user-images.githubusercontent.com/50226895/169245584-1096560f-0de1-4254-924f-6c3ec822df14.png)

**Comment by dave2wave** [comment]
I've found with Github Flavored Markdown / CommonMark that you will get proper renumbering if and only if you indent your code examples three spaces. (I'm not sure what flavor of Markdown is used by Docusaurus.

**Comment by dave2wave** [comment]
The example box numbering with the copy icon is getting in the way of the steps. This markdown with html does not seem to be compatible with Docusaurus 2.
