### ISSUE TITLE
`topicName` should not be a `required` config for source connector

### ISSUE THREAD

**Issue by freeznet** [apache/pulsar#15667]
**Describe the bug**
For some of the source connectors, like debezium connector, it actually not sending any messages to the `topicName`. And the `topicName` cannot be null: https://github.com/apache/pulsar/blob/branch-2.10/pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SourceConfigUtils.java#L296-L298

But from the java instance, if no topic is provided, it will use [PulsarSinkDisable](https://github.com/apache/pulsar/blob/branch-2.10/pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSinkDisable.java) instead. 

We should remove the strict validation on `topicName` for the source connector.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by momo-jun** [comment]
@freeznet I'm adding the information for this issue. Can you pls address the involved versions that the issue applies to?

**Comment by tisonkun** [comment]
Closed as stale and no one worked on it. Please open a new issue if it's still relevant to the maintained versions.

For this issue, it seems you can directly submit a patch to remove the validation.

I cannot read the description that you talk about the source config but refer to [PulsarSinkDisable](https://github.com/apache/pulsar/blob/branch-2.10/pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSinkDisable.java). Perhaps more concrete context helps contributors to continue it.

Feel free to reopen with additional context.

**Comment by tisonkun** [comment]
I get the point now. Coming up with a patch soon..
