### ISSUE TITLE
PulsarAdmin Java library: sometimes it fails with NullPointerException

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#15673]
**Describe the bug**
Sometimes I see this error using the PulsarAdmin API, using Pulsar 2.10.x

> java.lang.NullPointerException
> 2022-05-19T11:19:42.2536607Z 	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:740)
> 2022-05-19T11:19:42.2537320Z 	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:675)
> 2022-05-19T11:19:42.2538025Z 	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
> 2022-05-19T11:19:42.2538746Z 	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
> 2022-05-19T11:19:42.2539410Z 	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:292)
> 2022-05-19T11:19:42.2540015Z 	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:274)
> 2022-05-19T11:19:42.2540997Z 	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:205)
> 2022-05-19T11:19:42.2541706Z 	at org.apache.pulsar.shade.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
> 2022-05-19T11:19:42.2542454Z 	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
> 2022-05-19T11:19:42.2543170Z 	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:674)
> 2022-05-19T11:19:42.2543870Z 	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:450)
> 2022-05-19T11:19:42.2544551Z 	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$Builder.put(JerseyInvocation.java:334)

**To Reproduce**
I can't reproduce consistently, it happens more often is the server is unreachable

**Comment by boatrainlsz** [comment]
@eolivelli could you please provide more detail? is it cluster or standalone? code sample and detail logs would much useful. I'm new to Pulsar and trying to learn Pulsar by fixing issues. Many thanks!

**Comment by eolivelli** [comment]
@mattisonchao would you be interested in taking a look ?

**Comment by VinnuReddy18** [comment]
can i work on this issue? @eolivelli  @tisonkun

**Comment by dao-jun** [comment]
> can i work on this issue? @eolivelli @tisonkun

Great!

**Comment by VinnuReddy18** [comment]
How can i reproduce the error ? Can Anyone help me @dao-jun

**Comment by eolivelli** [comment]
Hello,
It passed a lot of time, I don't know how to reproduce the error with the latest version.

I am leaning towards closing this issue with 'Obsolete'
