### ISSUE TITLE
[Website] The Slack joining instructions are missing and "Pulsar Slack" button does a google search

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#15672]
**Describe the bug**

The Slack joining instructions are missing and "Pulsar Slack" button does a google search.

https://pulsar.apache.org/community#section-discussions

The old content seems to be available at https://pulsar.apache.org/contact/

**To Reproduce**
1. Go to https://pulsar.apache.org/community#section-discussions
2. The information to join Pulsar Slack is missing. Previous there was a link to https://apache-pulsar.herokuapp.com/ .
3. Clicking "Pulsar Slack" does a Google search instead of going directly to Pulsar Slack, 

**Expected behavior**
Providing this information is necessary about Pulsar Slack:
>The Slack instance is at https://apache-pulsar.slack.com/
>
>You can self-register at https://apache-pulsar.herokuapp.com/

**Comment by Anonymitaet** [comment]
This issue has been resolved. Thanks for your confirmation. @SignorMercurio
