### ISSUE TITLE
[DISCUSS] Gather missing permission granularity

### ISSUE THREAD

**Issue by mattisonchao** [apache/pulsar#15711]
### Motivation

According to issue https://github.com/apache/pulsar/issues/5720, we introduced more fine-grained authorization, named `XXXOperations`. (package path: `org.apache.pulsar.common.policies.data`)

After summarizing all the operations, it is found that we have missed some `Operations`, which may be caused by new features and so on.

In this discussion, we want to collect all the missing permission granularity to provide basic full permission control.

### Process

Everyone please feels free to make a suggestion, We will collect all suggestion into the list first and then start a vote to delete unnecessary operations.

### Operations List

| Operation Type | Operation | Remarks |
| --- | --- | --- |
| TenantOperation | CREATE_NAMESPACE |  |
| - | DELETE_NAMESPACE |  |
| - | LIST_NAMESPACES |  |
| NamespaceOperation | CREATE_TOPIC |  |
| - | GET_TOPIC |  |
| - | GET_TOPICS |  |
| - | DELETE_TOPIC |  |
| - | ADD_BUNDLE |  |
| - | DELETE_BUNDLE |  |
| - | GET_BUNDLE |  |
| - | GET_PERMISSION |  |
| - | GRANT_PERMISSION |  |
| - | REVOKE_PERMISSION |  |
| - | CLEAR_BACKLOG |  |
| - | UNSUBSCRIBE |  |
| - | PACKAGES |  |
| NamespacePolicyOperation | READ |  |
| - | WRITE |  |
| TopicOperation | LOOKUP |  |
| - | PRODUCE |  |
| - | CONSUME |  |
| - | COMPACT |  |
| - | EXPIRE_MESSAGES |  |
| - | OFFLOAD |  |
| - | PEEK_MESSAGES |  |
| - | RESET_CURSOR |  |
| - | SKIP |  |
| - | TERMINATE |  |
| - | UNLOAD |  |
| - | GRANT_PERMISSION |  |
| - | GET_PERMISSION |  |
| - | REVOKE_PERMISSION |  |
| - | ADD_BUNDLE_RANGE |  |
| - | GET_BUNDLE_RANGE |  |
| - | DELETE_BUNDLE_RANGE |  |
| - | SUBSCRIBE |  |
| - | GET_SUBSCRIPTIONS |  |
| - | UNSUBSCRIBE |  |
| - | GET_STATS |  |
| - | GET_METADATA |  |
| - | GET_BACKLOG_SIZE |  |
| - | SET_REPLICATED_SUBSCRIPTION_STATUS |  |
| - | GET_REPLICATED_SUBSCRIPTION_STATUS |  |

**Comment by tisonkun** [comment]
@mattisonchao may I ask what's the conclusion of this issue?
