### ISSUE TITLE
Rename doc label (Bot)

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#15732]
# Requirement
Rename doc labels as below
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/50226895/169936714-affd24fe-281e-4717-9571-3b3f9754c284.png">

# References
- [Instructions](https://docs.google.com/document/d/1Qw7LHQdXWBW9t2-r-A7QdFDBwmZh6ytB4guwMoXHqc0/edit#bookmark=id.5d66olk7l4oz)
- [Implementation process](https://docs.google.com/document/d/1bQfZkSu5nG1tNycpmXXtUFn-Z5-h-uqHv6IXsCEySQ8/edit#)
- [Flowchart](https://lucid.app/lucidchart/2e71291d-7882-4c61-86c1-0711a007ce58/edit?beaconFlowId=CE4A5D8BF4076F72&invitationId=inv_0fe733d2-a1dd-425d-807d-ac11ad9dc39d&page=0_0#)
- [Script file](https://github.com/apache/pulsar-test-infra/blob/76c227dea32f3b9be99558d4f2c22f1e70252839/doc-label-check/dist/index.js#L2617)

**Comment by Anonymitaet** [comment]
@maxsxu would you like to take care of this issue? Thanks

**Comment by maxsxu** [comment]
> @maxsxu would you like to take care of this issue? Thanks

@Anonymitaet  Sure, I'll be working on it. Please assign to me.

**Comment by maxsxu** [comment]
@Anonymitaet We need to do one more thing before the two above PRs were merged. 

Please create the following label manually to ensure the Bot works properly:

- `doc-not-needed`
- `doc-complete`

**Comment by maxsxu** [comment]
Thanks our genius @Anonymitaet , we just need to rename labels:

- `no-need-doc` -> `doc-not-needed`
- `doc-added` -> `doc-complete`
- `doc-info-missing` -> `doc-label-missing`

**Comment by Anonymitaet** [comment]
@maxsxu thanks for your great and super fast contribution! 🚀
