### ISSUE TITLE
About TripleLongPriorityQueue thread safety.

### ISSUE THREAD

**Issue by mingyifei** [apache/pulsar#15735]
Don't TripleLongPriorityQueue.add() and TripleLongPriorityQueue.pop() methods have thread safety issues?
In pulsar, we don't see thread safety using two methods.

**Comment by yxl1014** [comment]
Triplelongpriorityqueue is obviously not a thread safe queue. It is just an ordered queue based on bytebuf, which is used to store the index of long type and the delay time of long type. When you use it in the outer layer, you need to lock it to ensure its thread safety.

**Comment by mingyifei** [comment]
> Triplelongpriorityqueue is obviously not a thread safe queue. It is just an ordered queue based on bytebuf, which is used to store the index of long type and the delay time of long type. When you use it in the outer layer, you need to lock it to ensure its thread safety.

ok. thanks. add() and pop() methods, i see PersistentDispatcherMultipleConsumers is  the lock object.
