### ISSUE TITLE
Following the getting started guide results in a ClassNotFound exception at runtime.

### ISSUE THREAD

**Issue by Martin-Narvar** [apache/pulsar#15791]
### What issue do you find in Pulsar docs?

The getting started guide doesn't work, and this makes it very hard to get off the ground.
According to https://pulsar.apache.org/docs/2.2.1/client-libraries-java/ I just need to add 
```xml
<!-- in your <properties> block -->
<pulsar.version>2.2.1</pulsar.version>

<!-- in your <dependencies> block -->
<dependency>
  <groupId>org.apache.pulsar</groupId>
  <artifactId>pulsar-client</artifactId>
  <version>${pulsar.version}</version>
</dependency>
```
to pom.xml, but when I do this and add a call to 
```java
PulsarClient.builder().serviceUrl(applicationProperties.getPulsarUrl()).build();
```
The code compiles OK. but I get a `ClassNotFound` error at runtime like this:
```
java.lang.ClassNotFoundException: org.apache.pulsar.client.impl.PulsarClientImplementationBindingImpl
```
Which is super unhelpful.

I suppose that there is a piece missing in the getting started page.

### What is your suggestion?

I have no idea how to fix this, and therefore I can't get off the ground with Pulsar at this time. 

### Do you have any references?

https://pulsar.apache.org/docs/2.2.1/client-libraries-java/

### Would you like to fix this issue?

I would, but I have no idea where to begin to resolve this.

### Note

- [X] I have researched my question.

**Comment by Demogorgon314** [comment]
I have tried the 2.2.1 version of the pulsar client, but it doesn't get the `ClassNotFound ` error. 

Can you provide more context here? For example, you can give the minimal failed code to a Github repo. It can help us diagnose.

**Comment by Anonymitaet** [comment]
@Martin-Narvar can you retitle this issue to make it more clear?

**Comment by momo-jun** [comment]
Close the issue because it cannot be reproduced and no further context to help with the diagnosis.
