### ISSUE TITLE
non-persistent的topic 在消费能力不够出现堆积的时候限制使用内存的大小放置OOM

### ISSUE THREAD

**Issue by hzluyang** [apache/pulsar#15794]
non-persistent的topic 的消息数据是在内存中的
但是如果消费组消费能力弱，但是生产者生产大那么可能出现堆积大量数据在内存中的情况导致OOM的可能。

在5月份的开发用户沟通会上确认了确实会有OOM的风险

建议限制一下non-persistent topic的可以堆积消息的数量 避免这种场景下的OOM

**Comment by tisonkun** [comment]
Close as stale and it seems little interest and no volunteer wants to do it.
