### ISSUE TITLE
Android java Cilent MeesageLissener 

### ISSUE THREAD

**Issue by yhjlsy123** [apache/pulsar#15803]
**Describe the bug**
Android 
    api ('org.apache.pulsar:pulsar-client:2.10.0'){
        exclude group: 'org.bouncycastle'
    }
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g.  android]
 MeesageLissener  发布后接收不到message 信息
**Additional context**
![image](https://user-images.githubusercontent.com/17937790/170452122-88c041aa-7604-4fe0-a845-faefd169c8db.png)

**Comment by tisonkun** [comment]
Closing as stale. If it's still relevant to maintained versions, feel free to open a new issue.

The screenshot is partial so it's very hard for debugging.
