### ISSUE TITLE
[Doc] [New Website]

### ISSUE THREAD

**Issue by MarvinCai** [apache/pulsar#15813]
### What issue do you find in Pulsar docs?

Many CLI commands are missing from new website
e.g. the command  to trigger offload on topic is missing: 
it's there on old website but missing from new website
<img width="1688" alt="image" src="https://user-images.githubusercontent.com/13480084/170665883-dc43f80f-f0be-4339-bc3f-b92405afa77d.png">

Also on new website CLI command no longer have detailed options explained,
take `pulsar-admin topics set-offload-policies options` as an example
on old website it lists each option:
<img width="1723" alt="image" src="https://user-images.githubusercontent.com/13480084/170666243-610feeb6-0ebc-470e-95fa-dd2c91bf150f.png">
while on new website it simply says there're options, but doesn't tell users what are the options
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/13480084/170666362-9ca4830e-4b6c-4caa-81a0-864a1e96dacb.png">

### What is your suggestion?

CLI command doc on new website should provide same level of detail as old one.

### Do you have any references?

https://pulsar.apache.org/tools/pulsar-admin/2.10.0-SNAPSHOT/#-em-offload-em-
https://pulsar.apache.org/tools/pulsar-admin/2.10.0-SNAPSHOT/#-em-set-offload-policies-em--88

### Would you like to fix this issue?

N/A

### Note

- [X] I have researched my question.

**Comment by michaeljmarshall** [comment]
I think this is a function of how the docs are generated. It's also relevant that these docs are generated as `-SNAPSHOT` docs. Ideally, the docs would be generated as part of each release.

I found that the `bookies` sub-command was missing last week. I tried to fix it here https://github.com/apache/pulsar-site/pull/80. However, either the new docs haven't been built or there is another place that needs fixing.

Related issues: https://github.com/apache/pulsar/issues/14987 https://github.com/apache/pulsar/issues/14946 https://github.com/apache/pulsar/issues/14838 https://github.com/apache/pulsar/issues/13916

**Comment by Anonymitaet** [comment]
@MarvinCai 
`Admin API` chapter is not actively maintained. This important notice was added previously (and might need to be shown more prominent). Please click the link in the red circle. 
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/50226895/170904533-5914cc0e-5745-4cc6-bfb2-cc7cf52be8fd.png">

/cc @momo-jun @D-2-Ed @DaveDuggins

**Comment by MarvinCai** [comment]
that's just so weird that part of the doc are migrated but part of them are not, this is not good UX IMO.

**Comment by dave2wave** [comment]
I agree with @MarvinCai - this is an incomplete part of the new website. These issues may require a more general discussion on the dev@pulsar mailing list so that we can find consensus on (a) the most important parts to complete, and (b) the best approach to fixing the issues. One thing for sure the problems here would not be as critical if site search was fixed.

**Comment by dave2wave** [comment]
> Admin API chapter is not actively maintained. 

@Anonymitaet - Who made the decision to stop maintaining this chapter?

**Comment by Anonymitaet** [comment]
Docs are generated from code files as HTML pages (as below) rather than manually maintained in .md files, which is a more efficient and scalable way.

- https://pulsar.apache.org/tools/pulsar-admin/
- https://pulsar.apache.org/api/
- https://pulsar.apache.org/admin-rest-api/?version=master

**Comment by MarvinCai** [comment]
I think no matter how we maintain the doc, current status is we have incomplete info here, user following just this doc can't use the commands, like `pulsar-admin topics set-offload-policies` I mentioned, what options should they put in the command?

**Comment by Anonymitaet** [comment]
The website shows complete info containing flags
https://pulsar.apache.org/tools/pulsar-admin/2.11.0-SNAPSHOT/#-em-set-offload-policies-em--88
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/50226895/174248087-5409f3a5-6871-4763-8dbf-9f771ee97d70.png">

**Comment by dave2wave** [comment]
The bad UX is here: https://pulsar.apache.org/tools/pulsar-admin/

**Comment by dave2wave** [comment]
I also find the generated documents to be scattered and unsorted and dependent on good code comments.

Doc writers are not coders. Coders tend to always check the "no need docs" button. A hand written md file will provide examples and appropriate use. These can be written in proper English and translated if there is effort.

**Comment by tisonkun** [comment]
Closed. I think we have a new reference page now: https://pulsar.apache.org/reference/
