### ISSUE TITLE
Python Client doesn't clean up reserved field when publishing message with Schema

### ISSUE THREAD

**Issue by zhavir** [apache/pulsar#15844]
**Describe the bug**
If you have a complex schema, the reserved keys `_default`, `_required` and `_required_default` are not cleaned up

**To Reproduce**
```


class SchemaB(Record):
    field = String(required=True)

class SchemaA(Record):
    field = SchemaB()

a = SchemaA(field=SchemaB(field="something"))
b = JsonSchema(SchemaA).encode(a)
print(b)

b'{\n "field": {\n  "_required_default": false,\n  "_default": null,\n  "_required": false,\n  "field": "something"\n }\n}'

```

**Expected behavior**
reserved keys are cleaned up recursively.

**Desktop (please complete the following information):**
 - MacOS 12.3.1

**Additional context**
the problem seems to be [here](https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/python/pulsar/schema/schema.py#L97). The cleanup is not made recursively

**Comment by boatrainlsz** [comment]
I can fix this, I'm working on it
