### ISSUE TITLE
Topic internalStats/stats get failed: Topic not found

### ISSUE THREAD

**Issue by Gleiphir2769** [apache/pulsar#15871]
**Describe the bug**
Pulsar v2.8.2
I craete a topic by using https://pulsar.apache.org/admin/v2/persistent/{tenant}/{namespace}/{topic}, then use https://pulsar.apache.org/admin/v2/persistent/{tenant}/{namespace}/{topic}/internalStats and https://pulsar.apache.org/admin/v2/persistent/{tenant}/{namespace}/{topic}/stats to check it. It will be failed and return "404 "reason": "Topic not found"". But I can successfully request some time after topic is created, so why these two requests return this error when topic is just created? Under what circumstances can I get the correct result?

**Comment by nodece** [comment]
Could you try the Pulsar 2.8.3?

**Comment by Gleiphir2769** [comment]
> Could you try the Pulsar 2.8.3?

It still doesn't work. I also test it in v2.9.1 and get the same result. So can you reproduct it? By the way, I uesed pulsar cluster with 3 brokers.

Topic List Response:
`[
    "persistent://public/lxx-consumer-test/consumer-partition-0"
]`

Topic internal stats Response:
`{
    "reason": "Topic not found"
}`

**Comment by liangyuanpeng** [comment]
topic of `consumer-partition-0` and `consumer`, which one is you use when you request for the topic?

**Comment by Gleiphir2769** [comment]
> Topic of `consumer-partition-0` and `consumer`, which one is you use when you request for the topic?

Tnx, I have get the right response using  `consumer-partition-0` .
