### ISSUE TITLE
[Doc] broken link

### ISSUE THREAD

**Issue by miton18** [apache/pulsar#15879]
### What issue do you find in Pulsar docs?

Broken link on Pulsar sql doc:

https://github.com/apache/pulsar/blob/master/site2/docs/sql-deployment-configurations.md?plain=1#L144

### What is your suggestion?

Update the link

### Do you have any references?

https://github.com/apache/pulsar/blob/master/site2/docs/sql-deployment-configurations.md?plain=1#L144

### Would you like to fix this issue?

yes

### Note

- [X] I have researched my question.

**Comment by Anonymitaet** [comment]
The link is not broken, I can access it
<img width="1855" alt="image" src="https://user-images.githubusercontent.com/50226895/171590082-958a81b8-c689-4f51-a77d-525699a92263.png">

How about you? @momo-jun

**Comment by momo-jun** [comment]
It works well on my side too.

**Comment by miton18** [comment]
hum...
1. I go on https://pulsar.apache.org/docs/sql-deployment-configurations/
2. I hit F5
3. I clic on `[Query data](https://pulsar.apache.org/docs/sql-deployment-configurations/sql-getting-started)`
I land on a 404 page


![pulsar](https://user-images.githubusercontent.com/5887985/171602429-7c94a62c-f47c-4b27-b175-08528d0fa09e.png)

**Comment by urfreespace** [comment]
It works well on my side too. @miton18 could you please have a test again?

**Comment by Anonymitaet** [comment]
The links work well.
