### ISSUE TITLE
Fatal  error with pulsar client and Java 17(open jdk 17.0.2_8-7-1937)

### ISSUE THREAD

**Issue by vamsiprasanth-narvar** [apache/pulsar#15882]
**Describe the bug**
We are deploying our consumer app using pulsar client 2.9.1(tried with 2.10 version too) with java version 17(open jdk 17.0.2_8-7-1937) and we are getting fatal error during init of PulsarClient. The app is working with Java 11 and Java 15. 

**To Reproduce**
Error occurs in this statement -  PulsarClient.builder().serviceUrl(broker).connectionsPerBroker(4).ioThreads(Runtime.getRuntime().availableProcessors()).build();

**Expected behavior**
Pulsar client init and running fine

**Screenshots**
<img width="822" alt="image" src="https://user-images.githubusercontent.com/86304046/171476439-7d97a49a-3c86-45d7-af95-51986dfba47a.png">
**Desktop (please complete the following information):**

**Comment by boatrainlsz** [comment]
@vamsiprasanth-narvar could you please kindly provide the core dump file and error report file?
![image](https://user-images.githubusercontent.com/18243785/171975588-93874e7a-8484-4d4d-8682-839b8d2ee31c.png)

**Comment by tisonkun** [comment]
Closed as stale.

Please open a new issue if it's still relevant to master version and latest JDK 17 patch versions.
