### ISSUE TITLE
[improve][doc] highlight important notice

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#15892]
Some important notices are not highlighted, they are buried in the running texts.  
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/50226895/171573740-03db8548-7b8d-4bac-85b3-acce03e9a0f4.png">

We can make it more prominent by using `tip`, so that they are in green background.
![image](https://user-images.githubusercontent.com/50226895/171573957-900c83bd-6f15-49e5-a3ac-009a160a2623.png)

[This PR](https://github.com/apache/pulsar/pull/15890) only fixes some occurrences as an example.

Anyone would like to update all occurences? Thank you

**Comment by mendonk** [comment]
I can help with this.

**Comment by azhsmesos** [comment]
please assigned it to me ~

**Comment by Anonymitaet** [comment]
@azhsmesos thanks! Assigned. Looking forward to your contribution!

**Comment by azhsmesos** [comment]
收到！


| |
11
|
|
***@***.***
|
签名由网易邮箱大师定制


On 06/6/2022 ***@***.***> wrote：

@azhsmesos thanks! Assigned. Looking forward to your contribution!

**Comment by hpa16** [comment]
I'd like to take this up this docs issue if it is available.

**Comment by hpa16** [comment]
I'd like to take up this docs issue if no one is working on it.

**Comment by Anonymitaet** [comment]
@hpa16 thanks! You can ping me to review your PR.

**Comment by hpa16** [comment]
@Anonymitaet I have updated the PR. Can you please assign this issue to me and merge the PR? Thanks!

**Comment by Anonymitaet** [comment]
@hpa16 assigned. Feel free to ping me to merge your PR after all checks pass.

**Comment by hpa16** [comment]
@Anonymitaet the checks have passed, you can merge it now. Thanks for the quick turnaround.
