### ISSUE TITLE
[Doc] website about pulsar java client

### ISSUE THREAD

**Issue by MichaelDeSteven** [apache/pulsar#15906]
### What issue do you find in Pulsar docs?

![image](https://user-images.githubusercontent.com/51652084/171679391-841dc564-7344-444c-869e-9e60bc619a47.png)

### What is your suggestion?

plz make the form right.

### Do you have any references?

[Pulsar Clients](https://pulsar.apache.org/zh-CN/docs/next/client-libraries-java#configure-messages)

### Would you like to fix this issue?

I would like to.

### Note

- [X] I have researched my question.

**Comment by Anonymitaet** [comment]
Similar case: https://github.com/apache/pulsar/issues/15925#issuecomment-1146977584

**Comment by dave2wave** [comment]
The main English version is correct. The `zh-CN` translation is still broken.

**Comment by tisonkun** [comment]
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/18818196/205866718-4d720fb4-751c-4ef6-a7d1-8b5d463b4b8e.png">

Closed as fixed. Translations are archived at #17810 .
