### ISSUE TITLE
[Doc] Load Balancer - Broker overload thresholds does not apply to some Shedding algorithms

### ISSUE THREAD

**Issue by frankjkelly** [apache/pulsar#15904]
### What issue do you find in Pulsar docs?

In talking with @sijie he mentioned that the `loadBalancerBrokerOverloadedThresholdPercentage` setting does not apply to the ThresholdShedder

However if you look at the documentation for "Broker overload thresholds" that heading comes at the same level and right after "UniformLoadShedder"

https://pulsar.apache.org/docs/next/administration-load-balance#broker-overload-thresholds

So it reads as if `loadBalancerBrokerOverloadedThresholdPercentage` might be a setting use across all shedding algorithms?

### What is your suggestion?

Clarify if `loadBalancerBrokerOverloadedThresholdPercentage` applies to some or all shedding algorithms and place that setting in the appropriate section

### Do you have any references?

@sijie is my reference :-) 

### Would you like to fix this issue?

Sorry - probably needs to be clarified by those who know more about the load balancer :-) 

### Note

- [X] I have researched my question.

**Comment by frankjkelly** [comment]
Great - thank you @momo-jun - will the PR be linked in here when submitted?

**Comment by momo-jun** [comment]
> Great - thank you @momo-jun - will the PR be linked in here when submitted?

Yes, you will be notified.

**Comment by frankjkelly** [comment]
Thanks @Anonymitaet and @momo-jun
