### ISSUE TITLE
[Cli tools] Add command line option for configuring the memory limit

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#15912]
**Is your enhancement request related to a problem? Please describe.**
Cli tools such as `pulsar-perf` don't contain a way to configure the Pulsar client memory limit. 

**Describe the solution you'd like**
Cli tools should have a way to configure the Pulsar client memory limit.

**Additional context**
See https://github.com/apache/pulsar/pull/15748#issuecomment-1145013379

**Comment by tisonkun** [comment]
Cross-post -

I notice that we do have some utils to implement this future. See https://github.com/apache/pulsar/pull/20646#pullrequestreview-1497799011.

Closing as stale...

But anyone can take over this work as it's clear to follow now.

_Originally posted by @tisonkun in https://github.com/apache/pulsar/issues/19434#issuecomment-1606839264_

**Comment by tisonkun** [comment]
@JooHyukKim Sure. Go ahead :D
