### ISSUE TITLE
downloads page link in documentation is not correct

### ISSUE THREAD

**Issue by boatrainlsz** [apache/pulsar#15925]
### What issue do you find in Pulsar docs?

The downloads page link in [this guide](https://pulsar.apache.org/zh-CN/docs/next/getting-started-standalone/#install-pulsar-standalone) can not be accessed:
![image](https://user-images.githubusercontent.com/18243785/171862060-ddfaeb58-e8d6-4d1b-aaa3-a3b1bed544d6.png)

### What is your suggestion?

fix it

### Do you have any references?

https://pulsar.apache.org/zh-CN/docs/next/getting-started-standalone/#install-pulsar-standalone

### Would you like to fix this issue?

sure

### Note

- [X] I have researched my question.

**Comment by dave2wave** [comment]
The `download from the Apache mirror` is also incorrect. This looks like a Docusaurus problem.

**Comment by Anonymitaet** [comment]
@urfreespace is this a Docusaurus issue?

The links in English docs work well but Chinese do not.

**Comment by urfreespace** [comment]
> @urfreespace is this a Docusaurus issue?
> 
> The links in English docs work well but Chinese do not.
> 
> And here is a similar issue: #15906

no, due to a multi-language build failure, I will fix it

**Comment by momo-jun** [comment]
Hi @boatrainlsz, thanks for reporting this issue. It has been fixed in this PR(https://github.com/apache/pulsar-site/pull/120). Please try again and let us know of any questions.
