### ISSUE TITLE
[Doc] Get Started in Kubernetes Step 4 - Use Pulsar Manager to manage the cluster is incorrect

### ISSUE THREAD

**Issue by grahambunce** [apache/pulsar#15927]
### What issue do you find in Pulsar docs?

Follow instructions in this URL:

https://pulsar.apache.org/docs/getting-started-helm/#step-4-use-pulsar-manager-to-manage-the-cluster

The Helm script does not appear to install the Pulsar Manager nodes. Therefore Step 4 is not possible.

### What is your suggestion?

Fix the script to install pulsar manager as described or change the instructions in step 1.4 to include any appropriate settings to force this to occur

### Do you have any references?

https://pulsar.apache.org/docs/getting-started-helm/#step-4-use-pulsar-manager-to-manage-the-cluster

### Would you like to fix this issue?

I cannot fix the issue - I do not know if this is a Helm script error or a setup error.

### Note

- [X] I have researched my question.

**Comment by liangyepianzhou** [comment]
@zymap Could you please take a look at this Issue？

**Comment by zymap** [comment]
Looks like the pulsar manager [disabled by default](https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/values.yaml#L128), could you please enable it and then retry the steps?

**Comment by grahambunce** [comment]
@zymap maybe so, but then the docs are wrong which was the reason why I raised the ticket 😀

they should list the steps to enable this setting when you invoke the helm script

**Comment by zymap** [comment]
Let's enable it in the examples values file. The minikube values file should enable all the features we have documented on the GetStarted page, because it is a demo project.

Would you like to contribute to fixing that? Enabling the pulsar-manager in the [minikube values](https://github.com/apache/pulsar-helm-chart/blob/master/examples/values-minikube.yaml). That should be an easy fix.

**Comment by Anonymitaet** [comment]
Hi @momo-jun this issue is related to getting started with Pulsar. It would be grateful if you can take care of it, thanks!

**Comment by momo-jun** [comment]
@Anonymitaet it's not a doc issue. As suggested by @zymap, the Pulsar Manager should have been enabled in the [minikube values](https://github.com/apache/pulsar-helm-chart/blob/master/examples/values-minikube.yaml). With this file update, there is no need to update docs.
