### ISSUE TITLE
Compiling pulsar-client-cpp on Ubuntu Server 20.04 did not work as intended

### ISSUE THREAD

**Issue by boatrainlsz** [apache/pulsar#15935]
**Describe the bug**
Compiling pulsar-client-cpp on Ubuntu Server 20.04 did not work as intended

**To Reproduce**
1. follow the [compile instruction](https://github.com/apache/pulsar/tree/master/pulsar-client-cpp#compile-on-ubuntu-server-2004)
2. the first step works fine
3. the second and third step reports a error: `cp: cannot stat '*.a': No such file or directory`:
![image](https://user-images.githubusercontent.com/18243785/172033068-09c9afd5-7631-4a73-b5e5-a8076078e438.png)
![image](https://user-images.githubusercontent.com/18243785/172033073-cd1f380e-703c-4019-9fc4-2d8ac643bee8.png)
4. the fourth step also reports a error:
![image](https://user-images.githubusercontent.com/18243785/172033118-ce087cca-7572-4379-9ae9-bde9a72b6fdb.png)

**Expected behavior**
Compiling pulsar-client-cpp on Ubuntu Server 20.04 should work as intended

**Desktop (please complete the following information):**
`cat /etc/os-release`
```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
**Additional context**
more details in CMakeOutput.log and  CMakeError.log
[CMakeError.log](https://github.com/apache/pulsar/files/8839242/CMakeError.log)
[CMakeOutput.log](https://github.com/apache/pulsar/files/8839243/CMakeOutput.log)

**Comment by lgxbslgx** [comment]
> the second and third step reports a error: cp: cannot stat '*.a': No such file or directory

Please note that the command `sudo cp *.a /usr/lib` only intends to copy the libs `*.a` (you just built) to the path `/usr/lib` so that you can use them in pulsar.

From your log, I kown that in your local env, the libs `*.a` after linking were put into path `/usr/src/gtest/lib` and `/usr/src/gmock/lib` instead of the source code root path `/usr/src/gtest` and `/usr/src/gmock`. So you need to use command `sudo cp lib/*.a /usr/lib` instead of `sudo cp *.a /usr/lib`.

Maybe the compile instructions need to be adjusted to meet such situation. I will submit a patch to fix the document.

**Comment by boatrainlsz** [comment]
> > the second and third step reports a error: cp: cannot stat '*.a': No such file or directory
> 
> Please note that the command `sudo cp *.a /usr/lib` only intends to copy the libs `*.a` (you just built) to the path `/usr/lib` so that you can use them in pulsar.
> 
> From your log, I kown that in your local env, the libs `*.a` after linking were put into path `/usr/src/gtest/lib` and `/usr/src/gmock/lib` instead of the source code root path `/usr/src/gtest` and `/usr/src/gmock`. So you need to use command `sudo cp lib/*.a /usr/lib` instead of `sudo cp *.a /usr/lib`.
> 
> Maybe the compile instructions need to be adjusted to meet such situation. I will submit a patch to fix the document.

Thanks
