### ISSUE TITLE
[Doc] The powered-by link in contributing page is broken

### ISSUE THREAD

**Issue by boatrainlsz** [apache/pulsar#15959]
### What issue do you find in Pulsar docs?

The powered-by link in[contributing page](https://pulsar.apache.org/contributing/) is broken, located at `Updating user logo` part:
![image](https://user-images.githubusercontent.com/18243785/172347852-e34a1272-e9f1-4eb6-9c1f-7e06744225c9.png)

### What is your suggestion?

I would suggest making a full check to all doc pages to avoid such problems:
#15925
#15561

### Do you have any references?

https://pulsar.apache.org/contributing/

### Would you like to fix this issue?

I would like to

### Note

- [X] I have researched my question.

**Comment by Anonymitaet** [comment]
Hi @boatrainlsz thanks for your interest in fixing this issue.

The correct URL should be https://pulsar.apache.org/powered-by/ and https://github.com/apache/pulsar-site/blob/main/site2/website-next/data/users.js

And you can use https://www.drlinkcheck.com/ to check all URLs and fix invalid ones.

Look forward to your PR, thanks! 😊

**Comment by boatrainlsz** [comment]
> Hi @boatrainlsz thanks for your interest in fixing this issue.
> 
> The correct URL should be https://pulsar.apache.org/powered-by/ and https://github.com/apache/pulsar-site/blob/main/site2/website-next/data/users.js
> 
> And you can use https://www.drlinkcheck.com/ to check all URLs and fix invalid ones.
> 
> Look forward to your PR, thanks! 😊

Thanks for your information

**Comment by Anonymitaet** [comment]
@boatrainlsz feel free to ping me to review if you submit a PR, thanks.

**Comment by Anonymitaet** [comment]
This issue has been fixed.
