### ISSUE TITLE
[feat][website] add badges to README

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#15958]
Can we add some badges to `README`？

- https://docs.jupyter.org/en/latest/contributing/docs-contributions/doc-new-repos.html#badges-in-readme

<img width="894" alt="image" src="https://user-images.githubusercontent.com/50226895/172283585-feda8dca-1b6e-4824-bf74-ff8bcd23bba6.png">

- https://github.com/apache/pulsar/issues/15538#issuecomment-1126064195

**Comment by SignorMercurio** [comment]
I would like to help with this. Could you please assign this to me?

**Comment by Anonymitaet** [comment]
@SignorMercurio cool! Assigned.
