### ISSUE TITLE
[Doc] docker improvments

### ISSUE THREAD

**Issue by pablopla** [apache/pulsar#15972]
### What issue do you find in Pulsar docs?

1. The instructions on Docker hub and the Pulsar docs are different, one use volumes and the other mounts. In addition, Docker hub is missing the conf volume.
2. Both pages missing basic instruction how to modify the config (add a file named broker.conf under pulsarcof/broker.conf ...).
3. The container log is very noisy. For a new user like me it looks like something is broken. 

### What is your suggestion?

1. Same instructions on Docker hub and Pulsar docs.
2. Explain how to modify the config. Link to default config files on github source code.
3. Decrease the default log level. Only show a message that each component is running successfully.

### Do you have any references?

https://pulsar.apache.org/docs/standalone-docker/
https://hub.docker.com/r/apachepulsar/pulsar

Not sure which config file is relevant to the docs:
https://github.com/apache/pulsar/blob/master/conf/standalone.conf
https://github.com/apache/pulsar/blob/master/conf/broker.conf
https://github.com/apache/pulsar/blob/master/conf/zookeeper.conf
https://github.com/apache/pulsar/blob/master/conf/bookkeeper.conf

### Would you like to fix this issue?

no

### Note

- [X] I have researched my question.

**Comment by Anonymitaet** [comment]
Hi @momo-jun this issue is related to getting started with Pulsar. It would be grateful if you can take care of it, thanks!

**Comment by momo-jun** [comment]
@pablopla Thanks for reporting this issue.

#1. The instructions on the Docker hub have been updated by removing the commands and referencing Pulsar docs only.
#2. I will follow up with a pull request to explain how to modify the config. 
#3. To improve the log readability, can you open another issue to track?

Thanks to @zymap for technical guidance.

**Comment by benbro** [comment]
I don't think the log level changed. This is still an issue.

**Comment by momo-jun** [comment]
We closed this doc issue because the reported doc gaps have been fulfilled. Regarding the log levels, the doc cannot be changed unless the code is changed. So you can create a new thread for log issue triage and scope if required. Hope it helps.
