### ISSUE TITLE
[Doc] The page https://pulsar.apache.org/api/ needs to be a true map into all api versions

### ISSUE THREAD

**Issue by dave2wave** [apache/pulsar#15984]
### What issue do you find in Pulsar docs?

It is very hard to find the versioned api docs - when you navigate to https://pulsar.apache.org/api/ you can only go one level down.

### What is your suggestion?

Instead of the httpd default index page there should be a resource js driven docusaurus page that provides mapping to almost all of these api docs

### Do you have any references?

https://pulsar.apache.org/api/

There is no obvious way to find - https://pulsar.apache.org/api/python/2.8.3/pulsar.html

### Would you like to fix this issue?

I currently lack the time.

### Note

- [X] I have researched my question.

**Comment by michaeljmarshall** [comment]
Adding some context. There used to be a javascript program that was run as part of the website build and updated references so that they pointed to the correctly versioned docs. It appears that is broken at the moment.

**Comment by michaeljmarshall** [comment]
@urfreespace @Anonymitaet - is there any way you can help debug this? A few months ago, I understood how the docs were built and how to make sure the `replace.js` script properly replaced the links in the docs. Those files are now moved and I don't know what the current workflow is. Is there anywhere that we document how the `pulsar` and the `pulsar-site` repositories relate to each other? Thanks.

**Comment by michaeljmarshall** [comment]
Following up here, I now see how the docs are made. Some docs are synced from this repo to the pulsar-site repo. Then, there are scripts in the site2/website site2/website-next directories. Scripts are run against the `main` branch there, and then the final website build is pushed to `asf-site-next`. (We no longer build the `website` or the `asf-site` version of the website, we only build the `-next` version.)

**Comment by michaeljmarshall** [comment]
Confirming that the website-next built and works correctly!
