### ISSUE TITLE
Add getLastMessageId feature to Python Client

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#15985]
**Is your feature request related to a problem? Please describe.**
The `getLastMessageId` feature is available in the C++ client, but not in the python client.

**Describe the solution you'd like**
It'd be great if we can add the necessary python bindings to call the C++ client code.

**Comment by BewareMyPower** [comment]
I think it's a simple job because it can leverage the C++ reader's API directly.

**Comment by michaeljmarshall** [comment]
@BewareMyPower - that's great! The C++ consumer (or possibly ConsumerImpl) has the specific method, so it doesn't even need to be switched between reader/consumer.

**Comment by michaeljmarshall** [comment]
Here is a draft PR to resolve this issue: https://github.com/apache/pulsar/pull/15993. If it is really just that simple, I will probably go through and add several features that are currently present in the C++ client but missing in the Python client.
