### ISSUE TITLE
Zombie Producers could potentially disallow genuine new Producer

### ISSUE THREAD

**Issue by srkukarni** [apache/pulsar#1600]
#### Expected behavior

Pulsar standalone cluster had a producer connected to it with broker assigned 'standalone-0-2' name. I teared down the standalone cluster, deleted all data and started it fresh. However the producer was still up. Now when another producer for the same topic name tried connecting, it got the error that Producer 'standalone-0-2' is already connected. I would have expected either a new Producer name being given to the new producer, or a message to the old producer that you need a new client or something along those lines.

#### Actual behavior

Tell us what happens instead

#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**Pulsar version**: x.y

**Comment by srkukarni** [comment]
@merlimat @sijie

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
