### ISSUE TITLE
[Discuss][Doc]: Remove active-standby replication mode on Geo Replication doc

### ISSUE THREAD

**Issue by ericsyh** [apache/pulsar#16017]
### What issue do you find in Pulsar docs?

I think this mode on [Geo Replication doc](https://pulsar.apache.org/zh-CN/docs/concepts-replication/#active-standby-replication) is quite easy to misunderstand for users.

Because the [replicated-subscriptions](https://pulsar.apache.org/docs/administration-geo/#replicated-subscriptions) needs two-way replication which means if users config one-way replication like the active-standby replication mode describes, their subscriptions status will not be replicated from active cluster to standby cluster.

And if the application connects to the standby cluster after the active cluster is in failure, its replication status in the active cluster will be lost.

### What is your suggestion?

Delete Active-standby replication mode on Geo Replication mode, we just recommand Active-active replication mode.

### Do you have any references?

I tested this before and check with @codelipenghui and @hangc0276 about this limitation.

### Would you like to fix this issue?

Yes

### Note

- [X] I have researched my question.

**Comment by momo-jun** [comment]
Does it make sense to add the limitation instead of removing the option? In case there is a need for this use case without the concern of the limitation.

**Comment by ericsyh** [comment]
Because the limitation of the active-standby mode is it cannot achieve the target of the active-standby. If users want to achieve the target of the active-standby, they should config the active-active replication mode.

**Comment by momo-jun** [comment]
@codelipenghui can you pls share your idea on this?
