### ISSUE TITLE
[feat][workflow] add interactive features to bot

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#16038]
# Features

Can we enforce the Bot to execute the following commands?

- [ ] Assignee is automatically assigned to a PR author after the PR is submitted.

- [ ] assign
<img width="1515" alt="image" src="https://user-images.githubusercontent.com/50226895/170635224-d906b49e-a33a-4fc7-82f9-7e5c3995c5c5.png">

- [ ] help wanted + good first issue
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/50226895/170635180-31d56362-8fae-4751-82cb-1acfd8ccec32.png">

- `cherry-pick` may not fit because it works between branches and we want to work between folders. Need to research more.
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/50226895/170634793-1198d5bd-bd69-4ca3-8a26-6e505e585065.png">

**Comment by Anonymitaet** [comment]
@maxsxu thanks for your great help on this! Feel free to add more ideas! 💡

**Comment by dave2wave** [comment]
Please do not automate cherry pick. Each cherry pick must be a deliberate action by the developer of the PR.

**Comment by lhotari** [comment]
-1 for cherry picking in a bot

**Comment by lhotari** [comment]
@Anonymitaet please add some motivation to the feature requests. Why do we need those features?

**Comment by Anonymitaet** [comment]
@dave2wave @lhotari thanks for your feedback! I should clarify more clearly. 
We want to cherry-pick only documentation PRs (not code PRs) to reduce manual maintenance work.
Some doc changes are applicable to multiple doc versions. Currently, we need to copy them manually.

**Comment by michaeljmarshall** [comment]
We could also reduce manual work by changing the workflow. Do we have documentation explaining why we still need this repo?

> Some doc changes are applicable to multiple doc versions.

Can you explain this more? Doc version changes are not cherry picked, they are copied to the appropriate files.

**Comment by lhotari** [comment]
> We want to cherry-pick only documentation PRs (not code PRs) to reduce manual maintenance work.

That can be solved outside a docbot. There are security considerations so it's not just about convenience or preference using a bot. I'd suggest that there's a script that a committer can run to semi-automate your process.

**Comment by Anonymitaet** [comment]
> We could also reduce manual work by changing the workflow. Do we have documentation explaining why we still need this repo?
> 
> > Some doc changes are applicable to multiple doc versions.
> 
> Can you explain this more? Doc version changes are not cherry picked, they are copied to the appropriate files.

Yes, they are manually copied to files rather than cherry-pick to multiple branches (I use the inaccurate word `cherry-pick`, sorry, it results in confusion).

**Comment by Anonymitaet** [comment]
> > We want to cherry-pick only documentation PRs (not code PRs) to reduce manual maintenance work.
> 
> That can be solved outside a docbot. There are security considerations so it's not just about convenience or preference using a bot. I'd suggest that there's a script that a committer can run to semi-automate your process.

@lhotari 
1. can you explain what the security concerns are?
2. any examples or resources for the script? Thanks!

**Comment by maxsxu** [comment]
> @maxsxu thanks for your great help on this! Feel free to add more ideas! 💡

Thanks for bringing this out!

**Comment by tisonkun** [comment]
Closed as stale and no activities.
