### ISSUE TITLE
[Doc] Some reference links are 404

### ISSUE THREAD

**Issue by FushuWang** [apache/pulsar#16036]
### What issue do you find in Pulsar docs?

On this page https://pulsar.apache.org/docs/concepts-messaging/#messages, the reference link `schemas`, and `topic compaction ` are not found.

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/93108425/173327471-fd062934-cead-4fe3-8e96-616a361b7a19.png">

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/93108425/173326053-e93582f1-60b4-44aa-adef-a6a5aeae77fc.png">

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/93108425/173325894-6650abd1-1066-4acb-a467-ea2e559d1f63.png">

### What is your suggestion?

I found that the url will be added extra content `concepts-messaging` in the path when clicking the links above.
<img width="931" alt="image" src="https://user-images.githubusercontent.com/93108425/173327179-ffbc0707-e1e7-467a-8e8e-17bbe474da48.png">
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/93108425/173327471-fd062934-cead-4fe3-8e96-616a361b7a19.png">

### Do you have any references?

https://pulsar.apache.org/docs/concepts-messaging/#messages

### Would you like to fix this issue?

It might be the issue of the frontend plugin.

### Note

- [X] I have researched my question.

**Comment by dave2wave** [comment]
The links are invalid. The first link should be: `schema-get-started`

**Comment by momo-jun** [comment]
Ping @urfreespace.

**Comment by momo-jun** [comment]
Hi @FushuWang thanks for reporting this issue. It has been fixed in this PR(https://github.com/apache/pulsar-site/pull/120). Please try again and let us know of any questions.
