### ISSUE TITLE
The new Docbot spams PRs with multiple comments

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#16046]
**Describe the bug**
The new Docbot (#15797) added in #16027 spams PRs with multiple comments.

**To Reproduce**
There's an example in https://github.com/apache/pulsar/pull/16045
https://github.com/apache/pulsar/actions/workflows/ci-documentbot.yml

Example jobs:
![image](https://user-images.githubusercontent.com/66864/173501851-477c0d85-08e9-46e7-856e-eae05a8140a5.png)
Logs:
https://github.com/apache/pulsar/runs/6874257583?check_suite_focus=true
https://github.com/apache/pulsar/runs/6874257484?check_suite_focus=true
https://github.com/apache/pulsar/runs/6874256005?check_suite_focus=true

**Expected behavior**
The docbot shouldn't spam users with the same nagging message multiple times on the same PR.

**Additional context**
You can find workflow runs in https://github.com/apache/pulsar/actions/workflows/ci-documentbot.yml .
The workflow has been disabled until the problem is solved.

**Comment by lhotari** [comment]
@maxsxu @Anonymitaet I have disabled the docbot until this problem has been addressed since it's also spamming users with GitHub notifications.

**Comment by lhotari** [comment]
In https://github.com/apache/pulsar/blob/master/.github/workflows/ci-documentbot.yml
there should be config to limit the concurrency so that there's one build job handling events for a single PR at a time.

Adding this to the yaml will accomplish that:
```
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
```
docs for concurrency: https://docs.github.com/en/actions/using-jobs/using-concurrency

**Comment by Anonymitaet** [comment]
@lhotari thanks for your guidance and resource! @maxsxu is fixing this issue and will keep you updated.
