### ISSUE TITLE
Wrong swagger definitions for POST /admin/v2/namespaces/sample/ns1/deduplicationSnapshotInterval

### ISSUE THREAD

**Issue by visortelle** [apache/pulsar#16073]
This endpoint doesn't have DELETE method. The `undefined` request body is used instead to remove this policy.

Source: https://github.com/apache/pulsar/blob/e6b12c64b043903eb5ff2dc5186fe8030f157cfc/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java#L1395

The topic-level policy has DELETE method. Probably there is a sense to implement it for namespace-level policy.

Source: https://github.com/apache/pulsar/blob/e6b12c64b043903eb5ff2dc5186fe8030f157cfc/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java#L552

**Comment by tisonkun** [comment]
Closing as stale and no one worked on it. Please open a new issue if you volunteer to do it.
