### ISSUE TITLE
GET admin/v2/namespaces/public/default/topics?mode=ALL returns persistent topics only.

### ISSUE THREAD

**Issue by visortelle** [apache/pulsar#16081]
**To Reproduce**

You can start Pulsar in docker with: 

`docker run -it -p 8080:8080 apachepulsar/pulsar:2.10.0 bin/pulsar standalone`

Run:

```
#!/usr/bin/env bash

echo "Create topics"

pulsar-admin topics create persistent://public/default/p1
pulsar-admin topics create persistent://public/default/p2
pulsar-admin topics create persistent://public/default/p3

pulsar-admin topics create non-persistent://public/default/np1
pulsar-admin topics create non-persistent://public/default/np2
pulsar-admin topics create non-persistent://public/default/np3

echo ""
echo "Get all topics"
curl http://localhost:8080/admin/v2/namespaces/public/default/topics?mode=ALL

echo ""
echo "Get non-persistent topics"
curl http://localhost:8080/admin/v2/namespaces/public/default/topics?mode=ALL
curl http://localhost:8080/admin/v2/namespaces/public/default/topics?mode=NON_PERSISTENT
```

For both curl calls, non-persistent topics are missing:

<img width="992" alt="Screen Shot 2022-06-15 at 5 35 39 PM" src="https://user-images.githubusercontent.com/9302460/173867837-e3b4e9ef-b5a2-4c17-a5a5-1f562e3eb16d.png">

If you use pulsar-admin, you'll get the right result by running `pulsar-admin topics list public/default`. This command uses other API endpoints.

<img width="458" alt="Screen Shot 2022-06-15 at 5 37 31 PM" src="https://user-images.githubusercontent.com/9302460/173868244-e74818cf-5eb5-4a05-879c-d9b73e086aff.png">

**Comment by Technoboy-** [comment]
Fixed by #16170 .
