### ISSUE TITLE
[Doc] Javadoc links point to a snapshot repository

### ISSUE THREAD

**Issue by nicoloboschi** [apache/pulsar#16094]
### What issue do you find in Pulsar docs?

There are many links that point to https://pulsar.apache.org/api/ which contains javadocs content of very old versions (2.4.x) and snapshot versions. Also the user has to navigate in a archive which leads to very poor UX

### What is your suggestion?

Inside a doc page the current versions is known. It should be possible to point directly to the related javadoc.

### Do you have any references?

https://pulsar.apache.org/docs/next/client-libraries-java -> click on packages
https://pulsar.apache.org/docs/next/txn-use -> click on the first line link "Transactions API"

### Would you like to fix this issue?

no

### Note

- [X] I have researched my question.

**Comment by momo-jun** [comment]
Related issue: #14838, #13916.

**Comment by michaeljmarshall** [comment]
+1. I think we need to fix this. I plan to spend some time next week looking at this.
