### ISSUE TITLE
[Doc] Pulsar dashboard link in the pulsar-manager doc note section is broken

### ISSUE THREAD

**Issue by mans2singh** [apache/pulsar#16101]
### What issue do you find in Pulsar docs?

The pulsar-dashboard link in pulsar-manager page note section (https://pulsar.apache.org/docs/administration-pulsar-manager/) is broken and leads to a page not found (https://pulsar.apache.org/docs/administration-pulsar-manager/administration-dashboard). 

Here is the pulsar manager page

<img width="1318" alt="PulsarDashboardLinkOnPulsarManager" src="https://user-images.githubusercontent.com/8467404/174198443-8ff9caa2-e7d7-44ea-9bbe-316328106505.png">

Here is the pulsar dashboard page when the link for dashboard in the note is clicked.

<img width="1208" alt="PulsarDashboardLinkOnPulsarManager404" src="https://user-images.githubusercontent.com/8467404/174198536-98e3edb4-4b86-4614-b039-deee9bd65586.png">

### What is your suggestion?

The link should point to the dashboard link (https://pulsar.apache.org/docs/administration-dashboard/). 

### Do you have any references?

https://pulsar.apache.org/docs/administration-pulsar-manager

### Would you like to fix this issue?

Yes, but need your help in understanding how fix and validate it.

### Note

- [X] I have researched my question.

**Comment by momo-jun** [comment]
Hi @mans2singh thanks for reporting this issue.
It is a known issue and has been occurring in many places recently. The topic ID (administration-pulsar-manager in this case) is mistakenly added to the URL string in the front-end processing. 
@urfreespace is investigating it. Will keep you posted as soon as it is fixed.

**Comment by mans2singh** [comment]
@momo-jun - Thanks for your response.   Mans

**Comment by urfreespace** [comment]
fixed with https://github.com/apache/pulsar-site/pull/120 @momo-jun @Anonymitaet @mans2singh you could have a test again, thanks.
