### ISSUE TITLE
allow custom sequence numbers in the producer for dedup

### ISSUE THREAD

**Issue by nareshv** [apache/pulsar#16107]
**Is your enhancement request related to a problem? Please describe.**
Current producer api allows for creation of messages and the sequence numbers logic is not exposed to the programmers.

**Describe the solution you'd like**
Provide a mechanism using which the sequence numbers can be controlled by the developers instead of the Producer api

**Describe alternatives you've considered**
Not available

**Additional context**
This would help external system's sequence numbers to be used in the Messages before sent on wire and take advantage of the deduplication provided by pulsar.

**Comment by nareshv** [comment]
can you give some suggestions on this ?

**Comment by eolivelli** [comment]
@nareshv I think that we need a PIP for this feature and someone who wills to code it.
I understand your problem and it makes sense to me.
Thanks for sharing your problem.

Maybe you can advertise it on the mailing list (dev@pulsar.apache.org) in order to get more visibility, unfortunately not everyone is following the huge flow of notifications from github

**Comment by nareshv** [comment]
I am willing to write one if needed. Going through the JAVA SDK, looks most of the code is auto generated and doesn't expose any way to change the sequence numbers today.

**Comment by eolivelli** [comment]
here we handle the sequenceId
https://github.com/apache/pulsar/blob/b94588310eede61b417f40ca44e446470b58f6bf/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L610

we just need some way to set the sequence id while building a Message

**Comment by merlimat** [comment]
There is already a way to override it: https://pulsar.apache.org/api/client/2.10.0-SNAPSHOT/org/apache/pulsar/client/api/TypedMessageBuilder.html#sequenceId(long)

**Comment by nareshv** [comment]
This is useful @merlimat and @eolivelli.

**Comment by nareshv** [comment]
closing.
