### ISSUE TITLE
[bug][docs] Develop Pulsar Functions page does not show Python and Go examples

### ISSUE THREAD

**Issue by dave2wave** [apache/pulsar#16112]
**Describe the bug**
https://pulsar.apache.org/docs/functions-develop/ the Python and Go tabs do nothing.

**To Reproduce**
1. Go to https://pulsar.apache.org/docs/functions-develop/
2. Click on `Python` or `Go` tabs
3. Nothing happens

**Expected behavior**
The Python or Go examples should be displayed

**Browser**
 - Google Chrome

**Comment by momo-jun** [comment]
@urfreespace can you pls take a look? It worked well last week.

**Comment by urfreespace** [comment]
> @urfreespace can you pls take a look? It worked well last week.

OK, I will take a look later.

**Comment by urfreespace** [comment]
@dave2wave @momo-jun Fixed, PTAL, thanks.

**Comment by momo-jun** [comment]
@urfreespace this issue reopens on this page: https://pulsar.apache.org/docs/2.10.0/admin-api-brokers/.

**Comment by urfreespace** [comment]
> 

fixed, pls check, and https://pulsar.apache.org/docs/2.10.0/admin-api-brokers/ is wrong link, the correct URL is https://pulsar.apache.org/docs/admin-api-brokers/

**Comment by momo-jun** [comment]
@urfreespace thank you. @Anonymitaet then this issue can be closed.
