### ISSUE TITLE
KCA Sink needs an e2e integration test

### ISSUE THREAD

**Issue by dlg99** [apache/pulsar#16162]
Kafka Connect Adaptor source has integration test via debezium sources.
KCA Sink does not have implementations in Apache Pulsar but it needs e2e tests to ensure it runs on the function worker without classloader conflicts.
FileSink can be used for the tests, similarly to the unit tests.

**Comment by tisonkun** [comment]
Closing as stale and no one worked on it. Please open a new issue if you volunteer to do it.

Or if you can point out where is the source e2e test, it can help other contributors to do further investigates.
