### ISSUE TITLE
Normal & Delay Message stuck monitor

### ISSUE THREAD

**Issue by imqishi** [apache/pulsar#16173]
Keypoint is to **monitor message consuming is correct and not stuck**. Now I want to monitor this.
First I found there's GetLatestMessageID method to get partition's latest message_id, then I can sub current consuming message_id to calculate the partition's backlog;
but delayed message cannot be count by this, and I don't find any method to access delayed message num or position info, so is there anyway to get it?

**Comment by tjiuming** [comment]
@codelipenghui please assign to me.

**Comment by imqishi** [comment]
Thanks for your support, I will verify it later, and ask you if you have any questions
