### ISSUE TITLE
[Doc] Batch index acknowledgment doc doesn't mention requirement to enable it in client

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#16203]
### What issue do you find in Pulsar docs?

In the doc for batching (https://pulsar.apache.org/docs/next/concepts-messaging/#batching), it mentions the need to enable batch index acknowledgment on the broker, but it omits the important detail of enabling it in the consumers. 

As you can see from https://github.com/apache/pulsar/blob/bb0e0f2b432bbcdd67a59d8c08cf768811c459ec/pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ConsumerConfigurationData.java#L154, the default setting for the consumer is `batchIndexAckEnabled = false`, and the consumer can call this method to enable it: https://github.com/apache/pulsar/blob/adc1bb7d26752cb9e85c2303f2f637c995e8d33d/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java#L672

### What is your suggestion?

Give example of enabling it in the client. 

### Do you have any references?

See above.

### Would you like to fix this issue?

Yes, I'll connect the PR.

### Note

- [X] I have researched my question.

**Comment by momo-jun** [comment]
@devinbost Thank you for reporting and fixing this issue.
@Anonymitaet We can close this issue now.
