### ISSUE TITLE
Exception when iterating through the ledgers to check for over-replication

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#16207]
**Describe the bug**
![image](https://user-images.githubusercontent.com/54351417/175454358-fba12119-7274-4446-a5ca-10f24d3503d4.png)
Pulsar v2.8.1
Exceptions thrown when pulsar cluster is running.

**Comment by tisonkun** [comment]
Closing as stale. If it's still relevant to maintained versions, feel free to open a new issue.
