### ISSUE TITLE
pulsar-io-hdfs3 error

### ISSUE THREAD

**Issue by 704237006** [apache/pulsar#16206]
**Describe the bug**
try to create a pulsar-io-hdfs3 sink connector get error

**To Reproduce**
1. create sink-config-file as Picture 1。Make sure core-site.xml and hdfs-site.xml is correct，and directory exist 。
2.  create sink:
bin/pulsar-admin sink create \
--archive connectors/pulsar-io-hdfs3-2.10.0-SNAPSHOT.nar \
--inputs persistent://public/default/hdfs_test_3 \
--name hdfs3_sink \
--sink-config-file connector_yaml/hdfs_sink.yaml \
--parallelism 1

functioin worker error as Picture 2.
hdfs stats as  Picture 3.file is empty.

**Screenshots**
Picture 1：
![4eef818262656afed297c5ba1357ca8](https://user-images.githubusercontent.com/42430068/175441180-862b67bc-be2e-47f3-b488-d0442aab440b.png)
Picture 2：
![20220624094516](https://user-images.githubusercontent.com/42430068/175445775-96cbe0f2-cdc1-4b0d-a82f-e92327e5ce1d.png)
Picture 3：
![image](https://user-images.githubusercontent.com/42430068/175445883-86e58596-5ec6-455a-8fd8-ef1d5adc1faa.png)

**Comment by tisonkun** [comment]
Closing as stale. If it's still relevant to maintained versions, feel free to open a new issue.
