### ISSUE TITLE
Optimize AbstractTopic#getBytesOutCounter and AbstractTopic#getMsgOutCounter

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#16214]
**Is your enhancement request related to a problem? Please describe.**
In reading through the `AbstractTopic` code, I noticed that there are some inefficient stat generations. Specifically:

https://github.com/apache/pulsar/blob/b23689930e3af65cfc913e2890164a071acda440/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java#L1135-L1141

**Describe the solution you'd like**
Based on quickly reading through the usages of these methods and the definition of `getStats`, I think we should find a more direct way to compute the values for these counters.

**Additional context**
I am happy to help review any PRs for this enhancement.

**Comment by nahguam** [comment]
I can look at this one

**Comment by michaeljmarshall** [comment]
@nahguam - thanks for contributing the fix for this issue!
