### ISSUE TITLE
[feat][community] Enable GitHub Discussions

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#16275]
## Context

ML:
https://lists.apache.org/thread/83pst643h9cqcryo3zsjd240jmqzvn73
https://lists.apache.org/thread/1y7zbchlbokwnpd0jv2tt5jtzg6px6yn

We need to define what kind of messages that should be synced between GitHub Discussion and ML and research on how to achieve that.

Anyone would like to help? Thank you!

**Comment by dave2wave** [comment]
https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-GitHubDiscussions

I've conversed with ASF infra before and there is the thread here: https://lists.apache.org/thread/wtk7wm5wp33vgjchv06m75y8n04zk9pv

**Comment by dave2wave** [comment]
I created INFRA-23477

**Comment by dave2wave** [comment]
Merge PR #16528 once INFRA has completed INFRA-23477

**Comment by tisonkun** [comment]
Hi @dave2wave since we created an explicit consensus, you can update [INFRA-23477](https://issues.apache.org/jira/browse/INFRA-23477) as waiting for infra to nudge the process :)
