### ISSUE TITLE
Partitioned topics stats doesn't appear in "pulsar-admin broker-stats topics" response until get the specific topic stats manually

### ISSUE THREAD

**Issue by visortelle** [apache/pulsar#16284]
**How to reproduce**

- Create a partitioned topic
 
  `pulsar-admin topics create-partitioned-topic -p 2 persistent://public/default/prt-1`

- Wait for about a minute and try to get broker topics stats
  
  `pulsar-admin broker-stats topics -i | grep prt`

  You'll get an empty output.

- Now try to get the specific topic stats

  `pulsar-admin topics partitioned-stats persistent://public/default/prt-1`

  You'll get the topic's stats.

- Wait for wait about a minute and try to get broker topics stats again.

  `pulsar-admin broker-stats topics -i | grep prt`

  You'll get the topic's stats now.

  ```
  "persistent://public/default/prt-1-partition-1": {
  "persistent://public/default/prt-1-partition-0": {
  ```

---
Pulsar v2.10.0

**Comment by AnonHxy** [comment]
The topic's stats comes from `PulsarStats`, which updated at fix rate. You can set `statsUpdateFrequencyInSecs`(default 60) and `statsUpdateInitialDelayInSecs`(default 60) to config it.

**Comment by visortelle** [comment]
@AnonHxy, thank you for the reply.

I wait 120 seconds here and get no output:

<img width="664" alt="Screen Shot 2022-06-29 at 2 52 57 PM" src="https://user-images.githubusercontent.com/9302460/176440869-c2f18b15-8d09-4720-a7b8-94bf0cc97b40.png">

I waited about 5 minutes with the same result.

This behavior is only for partitioned topics.

Please try to reproduce it.

**Comment by coderzc** [comment]
I think the partition topic has not been created until when we really use it (create a producer/consumer).

**Comment by visortelle** [comment]
@coderzc 

I use `apachepulsar/pulsar:2.10.0` docker image with `bin/pulsar standalone` command.

I have only one standalone.conf (broker.conf) option override:

```
brokerDeleteInactiveTopicsEnabled=false
```

If the step you mentioned is critical to reproduce, feel free to ask me to record a video or create a repo with docker-compose and the configs.

**Comment by Technoboy-** [comment]
`broker-stats` will list the topics which are loaded by the current broker.  So if you create the partitioned topic but without loading it (create producer/consumer),  it can't be listed. Even if you use the `topics partitioned-stats`.

**Comment by Technoboy-** [comment]
`broker-stats` will list the topics which are loaded by the current broker.  So if you create the partitioned topic but without loading it (create producer/consumer),  it can't be listed. Even if you use the `topics partitioned-stats`.

**Comment by visortelle** [comment]
Aha! @Technoboy- Thank you for the explanation.

For the context, I'm building UI for Pulsar https://www.youtube.com/watch?v=0Xs8phdnta4

And now I see my mistake that I build it against a single-node cluster.

Am I understanding it right that everything under `broker-stats` APIs should be considered broker-specific and to get the whole Pulsar instance picture, I should ask each broker in my Pulsar instance?

And other resources like tenants, namespaces, functions, etc. aren't broker-specific. I can ask any broker and should get complete (paying eventual consistency into attention) results, right?
