### ISSUE TITLE
Flaky-test: Segmentation fault in CPP Tests

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#16296]
There is a segmentation fault in the CPP test. I couldn't find the specific failing test in the log. Could someone take a look? Thanks.

[example failure](https://github.com/apache/pulsar/runs/7125015873?check_suite_focus=true)

```
..................E................................../run-unit-tests.sh: line 93:  2850 Segmentation fault      (core dumped) python3 pulsar_test.py
+ RES=139
+ '[' 139 -ne 0 ']'
+ cd /home/runner/work/pulsar/pulsar
+ mkdir -p test-logs
+ cd test-logs
++ docker ps -a -q --filter label=pulsartests=5756
+ container_id=75946c038356
+ '[' -n 75946c038356 ']'
+ docker commit 75946c038356 pulsartests/75946c038356
sha256:07e1b8ab31a0e5717bcccdc1909d8561757284afa2f61533aa3a0dede3a822bc
+ docker run -i --rm pulsartests/75946c038356 bash -c 'cd /tmp; tar zcf - gtest-parallel-logs gtest_parallel_results.json pulsar-test-dist/logs'
+ tar zxvf -
```

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

**Comment by tisonkun** [comment]
Closed as stale.

The development of the C++ client has been permanently moved to https://github.com/apache/pulsar-client-cpp. If it's still relevant, please open an issue there.
