### ISSUE TITLE
The link to the Pulsar admin doc is invalid.

### ISSUE THREAD

**Issue by liangyepianzhou** [apache/pulsar#16297]
**Describe the bug**
The [link](https://pulsar.apache.org/zh-CN/docs/next/admin-api-clusters#:~:text=see%20Pulsar%20admin%20doc) to pulsar admin doc is invalid.
![image](https://user-images.githubusercontent.com/55571188/176620785-644f0771-69a0-48f6-b188-181b37e37fe5.png)

**Comment by tisonkun** [comment]
This issue should be resolved in the latest version.
