### ISSUE TITLE
Add gzip compression before http service response

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#16321]
**Is your feature request related to a problem? Please describe.**
With the continuous expansion of the tenant / namespace /topic/ application of pulsar cluster, the index text output by the broker is getting larger and larger. If promethues requests the /metrics URL time of the broker to be fixed, such as 10s, with the index getting larger and larger, this 10s will definitely timeout, so the following error will be reported:
![3ae6e378bc103bb1afcea9db85ddec2](https://user-images.githubusercontent.com/54351417/176842173-1f74a682-b88b-493a-8f13-3f1293d29ab9.png)

This will sometimes lead to incomplete indicators of promethues, and sometimes there are problems in the display on grafana, so we add gzip handler to the HTTP response of /metrics to reduce the network transmission volume.

**Describe the solution you'd like**
Add gzip handler to the HTTP response of /metrics

**Comment by tisonkun** [comment]
@xuesongxs is the Prometheus client timeout or the Pulsar channel timeout?
