### ISSUE TITLE
feat(pulsar-io): Add support for jdbc-sink connector for Oracle

### ISSUE THREAD

**Issue by ericsyh** [apache/pulsar#16393]
**Is your feature request related to a problem? Please describe.**
Compared to the Kafka Connector ecosystem, I think Pulsar is missing the JDBC sink connector for Oracle: https://docs.confluent.io/kafka-connect-jdbc/current/#oracle-database

**Describe the solution you'd like**
Add support for JDBC-sink connector for Oracle

**Describe alternatives you've considered**

**Additional context**

**Comment by tisonkun** [comment]
Closed as stale and no one worked on it. "Support X" cannot be implemented automatically but requires someone's design or working on it.

It's too common to host a list for "Supporting X integration". Please come up with a concrete plan or patch.
