### ISSUE TITLE
Aggregates test reports failed in CI - Unit - Brokers - Broker Group 1

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#16445]
**Describe the bug**
Aggregates test reports failed in CI - Unit - Brokers - Broker Group 1

**To Reproduce**
See: https://github.com/apache/pulsar/runs/7229588051?check_suite_focus=true#step:12:22

**Expected behavior**
Should not fail in this CI step.

**Additional context**
```
Prepare all required actions
Run ./.github/actions/copy-test-reports
Run $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh move_test_reports
Copying reports from ./pulsar-broker/target/surefire-reports
rm: cannot remove './pulsar-broker/target/surefire-reports': Directory not empty
Error: Process completed with exit code 1.
```

**Comment by tisonkun** [comment]
Closed as stale. IIRC we change the reporting logic a lot.
