### ISSUE TITLE
[Doc] Algolia Crawler cannot parse four critical pages

### ISSUE THREAD

**Issue by dave2wave** [apache/pulsar#16486]
### What issue do you find in Pulsar docs?

The Algolia crawler which prepares the search index fails to parse these pages including in versioned docs:

1. https://pulsar.apache.org/docs/reference-pulsar-admin/
2. https://pulsar.apache.org/docs/reference-metrics/
3. https://pulsar.apache.org/docs/pulsar-admin/
4. https://pulsar.apache.org/docs/reference-configuration/

The error is "Extractors returned too many records" for reference-configuration further detail is "Extractors returned 1518 records, the maximum is 750". In looking the maximum we need seems to be 2000.

### What is your suggestion?

Either we find out how to increase the maximum, or we need to break up these pages into multiple pages.

### Do you have any references?

Only three people can currently look at https://crawler.algolia.com/admin/crawlers/7a3458ba-2373-47d5-9520-90cc9cc10736/monitoring/details?reason=extracted_too_many_records&url=https%3A%2F%2Fpulsar.apache.org%2Fdocs%2Fnext%2Freference-metrics%2F

### Would you like to fix this issue?

I will look into increasing the maximum.

### Note

- [X] I have researched my question.

**Comment by dave2wave** [comment]
I've sent an email to Algolia crawler support.

**Comment by dave2wave** [comment]
I'm not getting support from Algolia. I think we will need to look at splitting up these pages. I think that the experience will be improved if we do this.

**Comment by SignorMercurio** [comment]
I'm currently working on generating configuration docs from source code, and also found that the `reference-configuration` page is too long. I think I'll split this page into subpages while trying to generate configuration docs. Like this:

![image](https://user-images.githubusercontent.com/32540679/179227282-e1dee625-bda3-46e1-892e-8eea1d820230.png)

**Comment by dave2wave** [comment]
@SignorMercurio That would an awesome way to split these pages up. A great improvement!

**Comment by tisonkun** [comment]
Closed as we use docsify to host references now.
