### ISSUE TITLE
Java client: batch messages - do not create a batch message of 1 single message

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#16547]
I think that we could implement a small but effective enhancement to batching.

It may happen that even if you enable batching you come to create entries with 1 only message.

Processing batch messages requires a good amount of resources, both on the broker and on the client side.

Especially when you are using PIP-105, Broker side filtering, you have to unpack (and decompress) the whole entry in order to process the very single message.

So my proposal is to change the (Java) producer, to make it produce a regular message instead of a batch message if the batch contains only 1 message.

Testing should cover:
- regular batch sending using the Java producer
- KEY based batcher builder

**Comment by AnonHxy** [comment]
I am working on that, thanks
