### ISSUE TITLE
Confused with method getMemUsage() in LinuxBrokerHostUsageImpl.java

### ISSUE THREAD

**Issue by zhanghaou** [apache/pulsar#16564]
**Environment**
1. broker run in kubernetes, set memory request to 20GB and limit to 20GB
2. pulsar version 2.8.1
3. os:ubuntu:20.04
4. jdk: openjdk version "11.0.11" 2021-04-20
5. PULSAR_GC:   -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.linkCapacity=1024 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=4 -XX:ConcGCThreads=4 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem
6. PULSAR_MEM:  -Xms8G -Xmx8G -XX:MaxDirectMemorySize=8G

**Describe the bug**
When running broker in our cluster, some broker pod may occur memory usage over 85%, and then cause to unloading namespace bundles from this broker, but from monitor of pod, we found the usage of memory is not high；on the other side, we found that when unloading bundles,  jvm heap memory is very high, and the monitoring curve of `jvm_memory_bytes_used` is very similar to `pulsar_lb_memory_usage`

**Question**
Does LinuxBrokerHostUsageImpl.getMemUsage() return error results? Why get different result in same pod?

**To Reproduce**
1. test in the broker pod
```
import com.sun.management.OperatingSystemMXBean;
import java.lang.management.ManagementFactory;

public class MemTest {

    public static void main(String[] args) {
        OperatingSystemMXBean systemBean = (OperatingSystemMXBean) ManagementFactory.getOperatingSystemMXBean();
        double total = ((double) systemBean.getTotalPhysicalMemorySize()) / (1024 * 1024);
        double free = ((double) systemBean.getFreePhysicalMemorySize()) / (1024 * 1024);

        System.out.println("total:" + total);
        System.out.println("free:" + free);
    }
}
```
and result of limit is 20GB.

![image](https://user-images.githubusercontent.com/5668441/178664087-8cfb9b42-6876-4d9c-9e41-8258686d40bc.png)
2. use arthas to see the real return of LinuxBrokerHostUsageImpl.getMemUsage, and can see that the limit is 8GB.
![image](https://user-images.githubusercontent.com/5668441/178664310-eac62b1c-63f1-435f-899e-fcb3ab7d6fad.png)

**Expected behavior**

LinuxBrokerHostUsageImpl.getMemUsage return the real memory of pod rather than the heap memory of jvm.

**Screenshots**
1.monitor of broker pod 
![image](https://user-images.githubusercontent.com/5668441/178664667-f4dd890a-7697-4bb7-be36-d5d84d482177.png)
2.monitor of pulsar_lb_memory_usage
![image](https://user-images.githubusercontent.com/5668441/178664715-bb12f5ed-a767-4d3e-9fb9-6eeba1a84adf.png)

Thanks for any suggestions.

**Comment by hangc0276** [comment]
OpeJDK should be "container aware" now. See https://bugs.openjdk.java.net/browse/JDK-8203357.

Would you please try the higher JDK version?

**Comment by zhanghaou** [comment]
> OpeJDK should be "container aware" now. See https://bugs.openjdk.java.net/browse/JDK-8203357.
> 
> Would you please try the higher JDK version?

Thanks for this tip, I will try.

**Comment by zhanghaou** [comment]
I had changed to openjdk 17, but it does not work.

**Comment by tisonkun** [comment]
@zhanghaou So why do you close this issue as completed while JDK17 doesn't help?

**Comment by zhanghaou** [comment]
@tisonkun 

It seems to a bug of arthas, not connected to jdk version. When I add more log in method getMemUsage(), total and used is correct. BTW, the memory of pod is useless, because of the override of jvm heap and direct memory in `LoadManagerShared:getSystemResourceUsage()  `
![企业微信截图_e7c24f36-7669-40bd-b663-58193ae45f14](https://user-images.githubusercontent.com/5668441/186805181-7b973b34-4964-475a-bae9-28ea68f54801.png)
![企业微信截图_b6b3cbec-f278-4441-81e4-2ca535d3a92e](https://user-images.githubusercontent.com/5668441/186805209-11d8342f-4253-45a7-af33-d0cf6494c940.png)
![企业微信截图_af9fc3f7-3097-4476-9aa5-bcd8e7ce88c8](https://user-images.githubusercontent.com/5668441/186805233-2d417ca4-e672-496c-a072-b9615a0232f0.png)

**Comment by lhotari** [comment]
There's a proposal for addressing this with a solution described in #21973
