### ISSUE TITLE
Build C++ Client Error

### ISSUE THREAD

**Issue by cjfff** [apache/pulsar#16566]
**Describe the bug**
I'm following the [guide](https://pulsar.apache.org/zh-CN/docs/client-libraries-cpp/#macos) about in the macOS how to install the c++ client of the pulsar.

But at the end of the steps.  when I try to run the "make" command in my terminal. I get an error...

**Screenshots**

Just according to my description at the end of the building, the pulsar-client-cpp throws an error...

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/20502762/178674255-650d0349-b3cc-4019-8288-5d8078d923a7.png">

**Expected behavior**
Success to install the c++ pulsar client.

**Desktop (please complete the following information):**
 - OS: [MacOS Apple M1 Pro version 12.4]
 - pulsar repository version v2.10.1

**Comment by shibd** [comment]
Hi, you need to use google test version 1.12.1, refer to this pr: https://github.com/apache/pulsar/pull/16776

**Comment by cjfff** [comment]
> Hi, you need to use google test version 1.12.1, refer to this pr: #16776

Thank you for your reply, It's completely installed for your recommended version of google-test.
