### ISSUE TITLE
Is there any way to delete a broken topic

### ISSUE THREAD

**Issue by truong-hua** [apache/pulsar#16571]
### What issue do you find in Pulsar docs?

Do not found any way to resolve or delete a topic which can not be deleted with API or pulsar-admin even with force=true.

We are under this situation https://github.com/apache/pulsar/issues/15891 and the broken topics of these issue can not be deleted (even forced). Someone also suggest a way to manually delete the znode of the topic like this https://github.com/apache/pulsar/issues/15891#issuecomment-1178512034 but we can not sure it's safe to do it or not.

### What is your suggestion?

Add more doc to help delete broken topics or any way to add a option to force delete broken topic like currently ?force=true only enforce the subscriptions to be terminated, so is it possible to add a param like ?halt=true to enforce removal of the topic?

### Do you have any references?

https://github.com/apache/pulsar/issues/15891#issuecomment-1178512034

### Would you like to fix this issue?

Not ready yet.

### Note

- [X] I have researched my question.

**Comment by momo-jun** [comment]
@Technoboy- you resolved https://github.com/apache/pulsar/issues/15891, so can you pls take a look at this issue as well?

**Comment by Technoboy-** [comment]
Hi @truong-hua 
The topic policy issue has been fixed. You don't need to delete it manually.
