### ISSUE TITLE
Add Broker Cache Entry Eviction Rate Metric

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#16584]
**Is your enhancement request related to a problem? Please describe.**
The current broker cache eviction metric, `pulsar_ml_cache_evictions`, measures when the cache's [hasSpaceInCache](
https://github.com/apache/pulsar/blob/e4092498cc01473a8a67441b082b9d86ed06890d/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheManagerImpl.java#L112-L138) triggers an eviction. There are no other cache eviction metrics right now, making it hard to gain insight into cache evictions.

**Describe the solution you'd like**
I would like to see metrics providing insight into the rate at which entries are getting evicted from the cache. I'm not sure if entry invalidations should also be included in this metric, but we should consider a metric for that as well.

These metrics would only be computed at the broker level.

**Describe alternatives you've considered**
I don't see another metric that gives insight into broker cache evictions.

**Additional context**

**Comment by michaeljmarshall** [comment]
@lhotari - I think additional metrics like the one described above could help make an issue like https://github.com/apache/pulsar/issues/16054 easier to observe.

**Comment by tjiuming** [comment]
@michaeljmarshall I'd like to fix the issue

**Comment by michaeljmarshall** [comment]
@tjiuming - sorry, I missed your comment. I implemented the metrics today. Feel free to review the PR if you have time.
