### ISSUE TITLE
PIP-190: Simplify documentation release and maintenance strategy

### ISSUE THREAD

**Issue by momo-jun** [apache/pulsar#16637]
- Status: Accepted/Implemented
- Author: momo-jun
- Pull Request: [#16938](https://github.com/apache/pulsar/issues/16938), https://github.com/apache/pulsar-site/pull/157
- Mailing List discussion: [Discussion](https://lists.apache.org/thread/g5b8lcwtn10ox7vd67n31om9w1rxn4l7), [Vote](https://lists.apache.org/thread/0h9s79yt9kd20ogqk8q42vbd64s2k5jc)
- Release: applies to 2.8.x and later versions

## Motivation

This proposal is focused on improving and simplifying the release and maintenance strategy of the existing Apache Pulsar documentation.

In general, this proposal provides equal values and a better user experience without making overwhelming sacrifices in the release and maintenance process. The benefits include:
* Improve user experience when they look for the documentation of a specific release.
* Optimize the doc development and release process for bug-fix releases:
   * Turn doc development for bug-fix releases from post-release into just-in-time. 
   * Save Release Manager’s effort in generating doc files for bug-fix releases.
* Save a great amount of the community’s effort in syncing doc improvements and fixes to historical doc versions that are in the maintenance cycle.

## Summary of the current strategy and activities

Pulsar version number is comprised of 3 components: major.minor.bug-fix. See [definition](https://github.com/apache/pulsar/wiki/PIP-47%3A-Time-Based-Release-Plan#what-about-version-numbers).

The current practice of the Pulsar documentation is releasing and maintaining individual versions of documentation for each bug-fix releases, including: 
1. The Release Manager needs to generate doc-related files for each bug-fix release. ----_This activity is canceled in this proposal._
2. The doc development for bug-fix releases can only be implemented after a release (due to item1). ----_This activity can be turned into just-in-time doc development in this proposal._
     1) The labeling process of bug-fix releases usually happens after a PR is merged. When a contributor submits a PR to change docs, he/she usually changes the doc in the master branch only, because he/she doesn’t know which release the change will be included. 
     2) The doc development for bug-fix releases has a dependency on the release of the new doc version. It requires someone to manually catch up with the doc changes for bug-fix releases after the doc set is generated by the Release Manager. What’s worse, this action is sometimes missed. 
3. The community keeps updating all the doc versions (15+) that are in the maintenance cycle. ---- _This activity can be narrowed down to 4 doc versions in this proposal._
4. Users have to go through [an endless list](https://pulsar.apache.org/versions/) when they want to look for the documentation of a specific release. 

### 1. Maintain doc sets for the last 4 minor releases

Pulsar is evolving very fast and generally has a 3-month release cycle, that is, 4 minor versions per year (sometimes 3 minor versions), with even more bug-fix versions. There is a high cost to maintain a lot of old releases, backport bug fixes, and security patches. In general, the last 4 minor releases are actively supported while the next minor release is being developed. For example, the community provides bug-fix releases for 2.7, 2.8, 2.9, and 2.10, while 2.11 is under development. See [PIP-47](https://github.com/apache/pulsar/wiki/PIP-47%3A-Time-Based-Release-Plan#what-is-our-eol-policy) for more details.

Accordingly, this proposal includes the first attempt to establish the doc maintenance strategy aligned with code, that is, we only keep maintaining doc sets for the last 4 minor releases: 2.7.x, 2.8.x, 2.9.x, and 2.10.x, while 2.11.0 is under development.

### 2. Release one doc version for each minor release and bug-fix release behind

The proposal introduces a simplified strategy for releasing and maintaining an all-in-one doc version for each minor release and more bug-fix releases behind, as shown below. 
<img width="652" alt="image" src="https://user-images.githubusercontent.com/60642177/180153794-bc9812e4-c012-40fe-80b7-e17ac3fa48aa.png">

#### Doc version page mockup

The following diagram shows the mockup of how the information architecture for [the Pulsar doc version page](https://pulsar.apache.org/versions) can be simplified with clarity for entry.
<img width="862" alt="image" src="https://user-images.githubusercontent.com/60642177/180154432-41c26c60-cd75-4101-8eea-7e2c2fb40d2e.png">

The key change on this page is about the fewer, simplified menus and links for documentation, and this new structure is also easier to maintain and scale.

**Note:** This is a mockup to demo the BEFORE & AFTER. When it comes to implementation, we need to make a compromise to only apply the strategy to doc sets for 2.8.x and later versions by balancing the workload differences.

#### Compare outcomes

The biggest difference between the proposal and the current practice is the strategy of releasing docs for bug-fix releases, and the outcome is compared in the following diagram. 
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/60642177/180474601-3ab65e77-9aed-4949-8936-069416bfdea1.png">

#### Just-in-time doc development for bug-fix releases

As one of the outcomes, just-in-time doc development for bug-fix releases is feasible with the following facts taken into consideration.

**Facts**
* The latest stable doc set for the minor version is up and running, like 2.10.x. As soon as a few doc PRs are labeled for a bug-fix version (2.10.1), the related doc changes can be implemented right away on top of 2.10.x doc set. The dependency with generating a new version of the doc set no longer exists. 
* Doc changes for improvements in bug-fix releases are limited (less than 10 PRs per version) based on previous releases. Take 2.10.1 for example:
<img width="706" alt="image" src="https://user-images.githubusercontent.com/60642177/180470087-81d59820-857c-4cf0-b1e9-6c0c2a456af8.png">

**Proposed solution**
Add an additional annotation like “This enhancement is only available for 2.10.1 and later versions.” for enhancements with doc requests in each bug-fix release. This needs to be added to the [Contribution Guide](https://docs.google.com/document/d/11DTnNPpvcPrebLkMAFcDEIFlD8ARD-k6F-LXoIwdD9Y/edit#).

### Apply the strategy to 2.8.x and later versions of documentation

By balancing the predictable workload introduced by the proposal and the unpredictable maintenance effort using the current strategy, we have to make a compromise that we only apply the strategy to 2.8.x and later versions.

The actions to change these versions of docs sets include: 
1. Add annotation for 2.M.1~2.M.n-specific doc changes to the 2.M.x docs(M⪰8)
2. Rename versioned-docs/2.M.0 to versioned-docs/2.M.x 
3. Remove versioned-docs/2.M.1~2.M.n from the Pulsar repo

### Update the doc version page

Use 2.10.x as the latest doc version and refresh the information for 2.8.x and 2.9.x. 

### Update the release document

Remove the section of [Update the site for minor releases](https://github.com/apache/pulsar/wiki/Release-process#update-the-site-for-minor-releases). 
Note that the minor releases mentioned in this section actually refer to bug-fix releases according to [the version number definition in PIP-47](https://github.com/apache/pulsar/wiki/PIP-47%3A-Time-Based-Release-Plan#what-about-version-numbers).
<img width="798" alt="image" src="https://user-images.githubusercontent.com/60642177/180153487-585e5a76-fe12-4435-bc0e-79799d613abb.png">

The reason is Release Managers will not need to generate documentation and update the doc site for bug-fix releases. Take 2.10.1 for example, they can skip the following pull requests and much more effort in their local processing.
<img width="795" alt="image" src="https://user-images.githubusercontent.com/60642177/180153511-d777fe79-d3bd-4053-9a82-4a9ea100e405.png">

**Note:** The release notes for bug-fix releases are still required. 

### Update the contribution guide

Update the [doc contribution guide](https://docs.google.com/document/d/11DTnNPpvcPrebLkMAFcDEIFlD8ARD-k6F-LXoIwdD9Y/edit#) to clarify the standard processing for the doc changes in bug-fix releases.

**Comment by Anonymitaet** [comment]
Thanks for your contribution! I've left some comments, PTAL. Feel free to let me know if you have any concerns. 😊

**Comment by momo-jun** [comment]
@Anonymitaet can you pls help update the release document and contribution guide? Both the new doc sets `2.8.x/2.9.x/2.10.x` and the new `versions` page are in place.

**Comment by Anonymitaet** [comment]
@momo-jun sure, I'll do that and request your review.

**Comment by tisonkun** [comment]
Now we encounter a new issue that the version number is `2.10.x` so all the placeholder `@pulsar:version_number@` becomes `2.10.x`. It will generate some fake info:

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/18818196/185567812-8dc88372-708a-4cf5-a89e-42554160bd15.png">

We only provide `2.10.0` or `2.10.1`, no `2.10.x`.

**Comment by tisonkun** [comment]
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/18818196/185569364-96c07f2f-1eb5-4b01-bd36-8d691d4267fd.png">

One more fake: all these links to maven central are broken links due to we don't publish version exact `2.10.x`

**Comment by momo-jun** [comment]
@tisonkun Thanks for the finding. Maybe we can add a tip/note to notify users to instantiate the version number. Any better ideas?

The doc files with this issue include:
* client-libraries-java.md
* client-libraries-python.md
* deploy-bare-metal.md
* io-debezium-source.md
* io-cdc-debezium.md
* standalone.md
* getting-started-standalone.md

**Comment by momo-jun** [comment]
> Two placeholders `@pulsar:version@` and `@pulsar:version_number@` are widely used in a dozen of doc pages in terms of:
> 
> * **Static text** - maybe add a tip/note to notify users to instantiate the version number.
> * **Links to REST APIs** - can we use the latest instance of X to generate REST APIs to serve the purpose? @urfreespace
> * **Links to Maven** - users can continue to select a specific version number there, which is not bad. Any better ideas?

Many thanks to @urfreespace for providing a resolution/patch to fix the issue, which covers all the above three categories.

**Comment by momo-jun** [comment]
Closed the issue since the PIP has been implemented.

**Comment by tisonkun** [comment]
@momo-jun @Anonymitaet is it possible to name the doc version as `2.11` instead of `2.11.x` and ditto for the following new versions? I don't think it's a brand new proposal here but a `.x` brings unnecessary confusion from my perspective.

For example:

* https://hbase.apache.org/2.4/book.html
* https://nightlies.apache.org/flink/flink-docs-release-1.15/

I agree it's a good idea to merge patch releases into one URL since no significant changes would be made. I'm glad to know whether there're other projects using `.x` versions in the docs site and URL and see how it works.

**Comment by Anonymitaet** [comment]
@tisonkun thank you!

🔹🔹🔹

Here are some similar cases to Pulsar (use `.x` in doc management and URL)

- [Kong docs](https://docs.konghq.com/mesh/1.8.x/)
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/50226895/192919817-6eccba1f-680f-46c3-9be2-462d2f9029d5.png">

- [RocketMQ](https://rocketmq.apache.org/en/docs/4.x/)
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/50226895/192919906-57b939c8-28b3-49ad-bbf5-fb6b08e812cc.png">

🔹🔹🔹

Here are some similar cases to Kafka (use `.x` in doc management but **not in URL**)

- [Kubesphere](https://v3-2.docs.kubesphere.io/docs/)
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/50226895/192920081-82efb3ba-2b4a-41e6-9448-3701b583d9ce.png">

- [Docusaurus](https://v1.docusaurus.io/)
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/50226895/192920257-d00de8a4-08fb-4678-8af3-40b6d667cda6.png">

🔹🔹🔹

I think `2.11.x` is OK since `.x` is commonly used and everyone may know the meaning at the 1st glance.

@D-2-Ed @DaveDuggins @momo-jun thoughts?

**Comment by tisonkun** [comment]
@Anonymitaet Thanks for your information! This makes many sense.
