### ISSUE TITLE
Build the docker image without dockerfile-maven-plugin

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#16652]
As described in https://github.com/apache/pulsar/discussions/16642, dockerfile-maven-plugin doesn't support Apple M1 and the project itself is end-of-life.

For supporting developers using Apple M1 clip, we can migrate the building logic to other plugin. Here's some candidates:

* [docker-maven-plugin](https://github.com/fabric8io/docker-maven-plugin) is provided by fabric8io and actively maintained. However, the plugin logic is quite different from dockerfile-maven-plugin as the former may be over fruitful.
* maven-exec-plugin. dockerfile-maven-plugin is effectively a thin wrapper of `docker` commands. We may directly run those commands with maven-exec-plugin.
* A makefile. Apache SkyWalking uses a [Makefile](https://github.com/apache/skywalking/blob/master/Makefile) to hold logics about building docker image. It should be in the same direction with maven-exec-plugin but switches build system switch to Makefile.

cc @lhotari what do you think? At least I'd like to know the effectively executed `docker` commands so that I can run from command line interface and build those images manually.

**Comment by lhotari** [comment]
> cc @lhotari what do you think? At least I'd like to know the effectively executed `docker` commands so that I can run from command line interface and build those images manually.

@tisonkun I'd prefer the `maven-exec-plugin` solution.

**Comment by tisonkun** [comment]
Related PR #16099.

**Comment by merlimat** [comment]
The next step after this would be to enable building multi-arch image :)

**Comment by xiaods** [comment]
use Jib — build Java Docker images better to build your image.

**Comment by hpvd** [comment]
since its about the future evolutions of the docker images in this issue,
maybe one should already also have a look on the topic distroless images:
just put together a short doc about
- the typical advantages and
- the latest gen of tooling
in the pulsar function-mesh project
where it may directly help solving some security problems in an image:
Build distroless package for better security, smaller size and more https://github.com/streamnative/function-mesh/issues/448

**Comment by tisonkun** [comment]
@xiaods with a quick glance of Jib, it seems a Java-specific image builder based on buildkit. Our logic is currently based on Dockerfile so I don't want to spend too much time learning a new flavor.
