### ISSUE TITLE
Windows support for admin CLI tools

### ISSUE THREAD

**Issue by nicoloboschi** [apache/pulsar#16688]
Currently for Windows users there's no easy way to run Pulsar CLI tools such as `pulsar-admin`, `pulsar-shell`, and so on.

The goal would be to give the possibility to a Windows user to download the Pulsar tarball and administrate a remote Pulsar cluster from their own Windows machine. 

Since the Pulsar Admin is a java application, the only implementation needed would be to:
* Create a .cmd file for pulsar-admin (`bin/pulsar-admin.cmd`)
* Replicate the same logic from the bash files (actually `bin/pulsar-admin-common.sh`)

This will become more useful starting from Pulsar 2.11 which will contains the Pulsar Shell artifact.

**Comment by lhotari** [comment]
I wonder if Powershell (`.ps1` extension) would be an option?

**Comment by dave2wave** [comment]
For those interested the shell scripts are here: https://github.com/apache/pulsar/tree/master/bin

**Comment by mangoGoForward** [comment]
I would like to help

**Comment by nicoloboschi** [comment]
@mangoGoForward have you started working on this? do you have any update?

**Comment by mangoGoForward** [comment]
> @mangoGoForward have you started working on this? do you have any update?

Thanks for your reminder, I will push it later
