### ISSUE TITLE
Flaky-test: CPP BasicEndToEndTest.testpatternMultiTopicsHttpConsumerPubSub

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#16693]
BasicEndToEndTest.testpatternMultiTopicsHttpConsumerPubSub is flaky. It fails sporadically.

[example failure](https://pipelines.actions.githubusercontent.com/serviceHosts/365d4aae-a024-4701-977d-a4807b036dda/_apis/pipelines/1/runs/614022/signedlogcontent/2?urlExpires=2022-07-20T05%3A43%3A44.4856693Z&urlSigningMethod=HMACV1&urlSignature=TuVX3CLalfAc3bt%2FiF4tz7a8m%2FNlDOn507vWf%2BjThz8%3D)

CI doesn't report the logs of the failure

it is failing quite often

**Comment by RobertIndie** [comment]
Another failure: https://github.com/apache/pulsar/runs/7532772064?check_suite_focus=true#step:11:448

```
Expected equality of these values:
  ResultTimeout
    Which is: TimeOut
  consumer.receive(m, 1000)
    Which is: Ok
```

**Comment by eolivelli** [comment]
it will be fixed by 
https://github.com/apache/pulsar/pull/16812

**Comment by eolivelli** [comment]
@BewareMyPower FYI
