### ISSUE TITLE
CI: Replace current GitHub Actions test reporting solution with less verbose solution

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#16736]
**Is your enhancement request related to a problem? Please describe.**

We are currently using a test reporting solution based on https://github.com/dorny/test-reporter and there's a copy of this action in https://github.com/apache/pulsar-test-infra/tree/master/test-reporter .

The problem with this solution is that the test reporting is very verbose since it creates new check runs for the PR. 
When there are failed tests, the PR will be marked failing even in cases where the tests pass in a later retry.

**Describe the solution you'd like**

There's an alternative solution in https://github.com/mikepenz/action-junit-report which is actively maintained. 
It's possible to use this action with `annotate_only: 'true'` so that check runs aren't created at all. This is to mitigate the gap in GitHub Actions solution that check results cannot target a specific workflow when there are multiple active ones (more details in https://github.com/mikepenz/action-junit-report/issues/40#issuecomment-1192309267). 
The action will create a report for each build job using [a new method available in GitHub Actions](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/). example: https://github.com/mikepenz/action-junit-report/actions/runs/2717236074#summary-7464569272

**Comment by lhotari** [comment]
The change could be tested in your own fork (some instructions in https://pulsar.apache.org/contributing/#ci-testing-in-your-fork) before submitting a PR.
The copy of https://github.com/mikepenz/action-junit-report would have to be added to https://github.com/apache/pulsar-test-infra since only whitelisted or trusted locations can be used in GH actions workflows for apache/pulsar.

**Comment by lhotari** [comment]
running an experiment in https://github.com/lhotari/pulsar/pull/78

**Comment by eolivelli** [comment]
The experiments looks promising

**Comment by tisonkun** [comment]
https://github.com/apache/pulsar/pull/17282/checks?check_run_id=8047947991 I notice another issue on test reports that the report can be assigned to multiple jobs.
