### ISSUE TITLE
[PIP-169] Support split bundle by flow or qps

### ISSUE THREAD

**Issue by lordcheng10** [apache/pulsar#16782]
## Motivation
As we all know, Bundle split has 3 algorithms:
- range_equally_divide
- topic_count_equally_divide
- specified_positions_divide

However, none of these algorithms can divide bundles according to flow or qps, which may cause bundles to be split multiple times.

## Goal
Our goal is to split bundles according to flow or QPS, so we propose a PIP to introduce a split algorithm based on flow or QPS.
The main idea is that we can get the flow or qps information of a topic contained in a bundle,
then split according to loadBalancerNamespaceBundleMaxMsgRate or loadBalancerNamespaceBundleMaxBandwidthMbytes configuration

For example, there is bundle with boundaries 0x00000000 to 0x00000200, and six topics : t1 , t2 , t3 , t4, t5, t6.
loadBalancerNamespaceBundleMaxMsgRate=1100
loadBalancerNamespaceBundleMaxBandwidthMbytes=110

**Step 1: Get their hash position and corresponding flow and QPS:**

> t1 with hashcode 10 msgRate 100/s throughput 10M/s
> 
> t2 with hashcode 20 msgRate 200/s throughput 20M/s
> 
> t3 with hashcode 80 msgRate 300/s throughput 30M/s
> 
> t4 with hashcode 90 msgRate 400/s throughput 40M/s
> 
> t5 with hashcode 100 msgRate 500/s throughput 50M/s
> 
> t6 with hashcode 110 msgRate 600/s throughput 60M/s

**Step 2: Calculate the total flow and qps of the bundle:**

> bundleMsgRate = 100 + 200 + 300 + 400 + 500 + 600 = 2100
> bundleThroughput = 10 + 20 + 30 + 40 + 50 + 60 = 210MB

**Step 3: Calculate the position to split and split:**

> QPS: (100 + 200 + 300 + 400 ) < loadBalancerNamespaceBundleMaxMsgRate=1100 & (100+200+300+400+500) > loadBalancerNamespaceBundleMaxMsgRate=1100
> flow: (10 + 20 + 30 + 40 ) < loadBalancerNamespaceBundleMaxBandwidthMbytes=110 & (10 + 20 + 30 + 40 + 50 ) > loadBalancerNamespaceBundleMaxBandwidthMbytes=110
> 
> Split between t4 and t5:
> splitStartPosition = 90
> splitEndPosition = 100
> splitPosition = (90 + 100) / 2 = 95

## API Changes

1. Add a split algorithm class based on flow or qps:

`public class FlowOrQpsEquallyDivideBundleSplitAlgorithm implements NamespaceBundleSplitAlgorithm `

2. update the default configuration:
```
private List<String> supportedNamespaceBundleSplitAlgorithms = Lists.newArrayList("range_equally_divide", "topic_count_equally_divide",
   "specified_positions_divide", "flow_count_equally_divide");
```
3. added configuration 
```
@FieldContext(
        dynamic = true,
        category = CATEGORY_LOAD_BALANCER,
        doc = "Acceptable difference between qps and loadBalancerNamespaceBundleMaxMsgRate "
                + " or flow and loadBalancerNamespaceBundleMaxBandwidthMbytes "
)
private int flowOrQpsDifferenceThresholdPercentage = 10;
```

## Implementation
The execution steps of the FlowOrQpsEquallyDivideBundleSplitAlgorithm#getSplitBoundary method are as follows:
1. Get the hash position of each topic and the corresponding msgRate and msgThroughput, and sort them according to the position size：

```
List<Long> topicNameHashList = new ArrayList<>(topics.size());
Map<Long, Double> hashAndMsgMap = new HashMap<>();
Map<Long, Double> hashAndThroughput = new HashMap<>();
```

2. According to the topic hash position, traverse all topics from small to large, 
and split the bundle according to the configured loadBalancerNamespaceBundleMaxMsgRate or loadBalancerNamespaceBundleMaxBandwidthMbytes:

```
  double bundleMsgRateTmp = 0;
  double bundleThroughputTmp = 0;
  for (int i = 0; i < topicNameHashList.size(); i++) {
      long topicHashCode = topicNameHashList.get(i);
      bundleThroughputTmp += hashAndThroughput.get(topicHashCode);
      bundleMsgRateTmp += hashAndMsgMap.get(topicHashCode);

      if (bundleMsgRateTmp > loadBalancerNamespaceBundleMaxMsgRate
            || bundleThroughputTmp > loadBalancerNamespaceBundleMaxBandwidthBytes) {
            long splitStart = i > 0 ? topicNameHashList.get(i - 1) : topicHashCode;
            long splitEnd = i > 0 ? topicHashCode : topicNameHashList.get(i + 1);
            long splitMiddle = splitStart + (splitEnd - splitStart) / 2;
            splitResults.add(splitMiddle);
            bundleMsgRateTmp =  hashAndMsgMap.get(topicHashCode);
            bundleThroughputTmp = hashAndThroughput.get(topicHashCode);
      }
  }

```

**Comment by lordcheng10** [comment]
discuss thread https://lists.apache.org/thread/cshyt10fwcjjxs93g8yf0svgwcgnshmg

**Comment by codelipenghui** [comment]
@lordcheng10 The PIP number is duplicated with https://github.com/apache/pulsar/issues/15463

**Comment by lordcheng10** [comment]
> @lordcheng10 The PIP number is duplicated with #15463

fixed

**Comment by Technoboy-** [comment]
> @codelipenghui Need to resend the discussion email? Because the email header shows 164.

No need to re-send, you can reply to the latest PIP in the original email

**Comment by lordcheng10** [comment]
> > @codelipenghui Need to resend the discussion email? Because the email header shows 164.
> 
> No need to re-send, you can reply to the latest PIP in the original email

OK

**Comment by eolivelli** [comment]
Do you have some numbers about experiments ?
Before accepting the proposal we must be sure that this algorithm works on only on the paper but also on some real benchmark/test env

**Comment by lordcheng10** [comment]
> Do you have some numbers about experiments ? Before accepting the proposal we must be sure that this algorithm works on only on the paper but also on some real benchmark/test env

OK

**Comment by lordcheng10** [comment]
> Do you have some numbers about experiments ? Before accepting the proposal we must be sure that this algorithm works on only on the paper but also on some real benchmark/test env

Test steps：
1.create Topic:

```
sh bin/pulsar-admin tenants create test-tenant1
sh bin/pulsar-admin namespaces create test-tenant1/test-namespace1
sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test1  -p    20
sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test2  -p    20
sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test3  -p    20
sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test4  -p    20
sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test5  -p    20
sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test6  -p    20
sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test7  -p    20
sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test8  -p    20
sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test9  -p    20
sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test10  -p    20
sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test11  -p    20
sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test12  -p    20
sh bin/pulsar-admin topics  create-partitioned-topic  persistent://test-tenant1/test-namespace1/test695  -p    1
```

2.generate data:

```
nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test1  -threads 1  -n 1 -r 1000 > log1 &
nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test2  -threads 1  -n 1 -r 1000 > log2 &
nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test3  -threads 1  -n 1 -r 1000 > log3 &
nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test4  -threads 1  -n 1 -r 1000 > log4 &
nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test5  -threads 1  -n 1 -r 1000 > log5 &
nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test6  -threads 1  -n 1 -r 1000 > log6 &
nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test7  -threads 1  -n 1 -r 1000 > log7 &
nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test8  -threads 1  -n 1 -r 1000  > log8 &
nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test9  -threads 1  -n 1 -r 1000  > log9 &
nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test10  -threads 1  -n 1 -r 1000 > log10 &
nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test11  -threads 1  -n 1 -r 1000 > log11 &
nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test12  -threads 1  -n 1 -r 1000 > log12 &
nohup sh  bin/pulsar-perf produce persistent://test-tenant1/test-namespace1/test695 -threads 1  -n 11 -r 1010 > log695 &
```

3.the configuration is as follows:
#defaultNamespaceBundleSplitAlgorithm=topic_count_equally_divide
defaultNamespaceBundleSplitAlgorithm=flow_or_qps_equally_divide
loadBalancerNamespaceBundleMaxMsgRate=1010
flowOrQpsDifferenceThresholdPercentage=10
exposeBundlesMetricsInPrometheus=true

The comparison effect is as follows:
1.Using the topic_count_equally_divide algorithm, pulsar_bundle_msg_rate_in is monitored as follows:
The number of bundles after splitting is 21, and the pulsar_bundle_msg_rate_in of a single bundle is: 49 msg/s ~ 1010 msg/s：
![image](https://user-images.githubusercontent.com/19296967/185866809-30818541-1f95-484a-955a-2896125cac3f.png)



2.Using the new algorithm flow_or_qps_equally_divide the effect is as follows:
The number of bundles after splitting is 13, and the pulsar_bundle_msg_rate_in of a single bundle is: 997 msg/s ~ 1010 msg/s：
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/19296967/185864580-198b92fb-ef0b-4390-9bfc-56a03a1b19f0.png">

**Comment by lordcheng10** [comment]
> > Do you have some numbers about experiments ? Before accepting the proposal we must be sure that this algorithm works on only on the paper but also on some real benchmark/test env
> 
> ### Test steps：
> 1.create Topic:
> 
> ```
> sh bin/pulsar-admin tenants create test-tenant1
> sh bin/pulsar-admin namespaces create test-tenant1/test-namespace1
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test1  -p    20
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test2  -p    20
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test3  -p    20
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test4  -p    20
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test5  -p    20
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test6  -p    20
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test7  -p    20
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test8  -p    20
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test9  -p    20
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test10  -p    20
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test11  -p    20
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test12  -p    20
> sh bin/pulsar-admin topics  create-partitioned-topic  persistent://test-tenant1/test-namespace1/test695  -p    1
> ```
> 
> 2.generate data:
> 
> ```
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test1  -threads 1  -n 1 -r 1000 > log1 &
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test2  -threads 1  -n 1 -r 1000 > log2 &
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test3  -threads 1  -n 1 -r 1000 > log3 &
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test4  -threads 1  -n 1 -r 1000 > log4 &
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test5  -threads 1  -n 1 -r 1000 > log5 &
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test6  -threads 1  -n 1 -r 1000 > log6 &
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test7  -threads 1  -n 1 -r 1000 > log7 &
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test8  -threads 1  -n 1 -r 1000  > log8 &
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test9  -threads 1  -n 1 -r 1000  > log9 &
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test10  -threads 1  -n 1 -r 1000 > log10 &
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test11  -threads 1  -n 1 -r 1000 > log11 &
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test12  -threads 1  -n 1 -r 1000 > log12 &
> nohup sh  bin/pulsar-perf produce persistent://test-tenant1/test-namespace1/test695 -threads 1  -n 11 -r 1010 > log695 &
> ```
> 
> 3.the configuration is as follows: #defaultNamespaceBundleSplitAlgorithm=topic_count_equally_divide defaultNamespaceBundleSplitAlgorithm=flow_or_qps_equally_divide loadBalancerNamespaceBundleMaxMsgRate=1010 flowOrQpsDifferenceThresholdPercentage=10 exposeBundlesMetricsInPrometheus=true defaultNumberOfNamespaceBundles=1
> 
> ### The comparison effect is as follows:
> **1.Using the topic_count_equally_divide algorithm:**
> 
> The number of bundles after splitting is 21, and the **pulsar_bundle_msg_rate_in** of a single bundle is: **49 msg/s ~ 1010 msg/s**：
> 
> ![image](https://user-images.githubusercontent.com/19296967/185867834-543e8443-de48-48a4-b254-e5af7ddf2209.png)
> 
> **2.Using the new algorithm flow_or_qps_equally_divide:** The number of bundles after splitting is 13, and the **pulsar_bundle_msg_rate_in** of a single bundle is: **997 msg/s ~ 1010 msg/s**： <img alt="image" width="1282" src="https://user-images.githubusercontent.com/19296967/185864580-198b92fb-ef0b-4390-9bfc-56a03a1b19f0.png">

@eolivelli @codelipenghui PTAL,thanks!

**Comment by lordcheng10** [comment]
> > Do you have some numbers about experiments ? Before accepting the proposal we must be sure that this algorithm works on only on the paper but also on some real benchmark/test env
> 
> 
> 
> ### Test steps：
> 
> 1.create Topic:
> 
> 
> 
> ```
> 
> sh bin/pulsar-admin tenants create test-tenant1
> 
> sh bin/pulsar-admin namespaces create test-tenant1/test-namespace1
> 
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test1  -p    20
> 
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test2  -p    20
> 
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test3  -p    20
> 
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test4  -p    20
> 
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test5  -p    20
> 
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test6  -p    20
> 
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test7  -p    20
> 
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test8  -p    20
> 
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test9  -p    20
> 
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test10  -p    20
> 
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test11  -p    20
> 
> sh bin/pulsar-admin topics  create-partitioned-topic  test-tenant1/test-namespace1/test12  -p    20
> 
> sh bin/pulsar-admin topics  create-partitioned-topic  persistent://test-tenant1/test-namespace1/test695  -p  1
> 
> ```
> 
> 
> 
> 2.generate data:
> 
> 
> 
> ```
> 
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test1  -threads 1  -n 1 -r 1000 > log1 &
> 
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test2  -threads 1  -n 1 -r 1000 > log2 &
> 
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test3  -threads 1  -n 1 -r 1000 > log3 &
> 
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test4  -threads 1  -n 1 -r 1000 > log4 &
> 
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test5  -threads 1  -n 1 -r 1000 > log5 &
> 
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test6  -threads 1  -n 1 -r 1000 > log6 &
> 
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test7  -threads 1  -n 1 -r 1000 > log7 &
> 
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test8  -threads 1  -n 1 -r 1000  > log8 &
> 
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test9  -threads 1  -n 1 -r 1000  > log9 &
> 
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test10  -threads 1  -n 1 -r 1000 > log10 &
> 
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test11  -threads 1  -n 1 -r 1000 > log11 &
> 
> nohup sh bin/pulsar-perf produce test-tenant1/test-namespace1/test12  -threads 1  -n 1 -r 1000 > log12 &
> 
> nohup sh  bin/pulsar-perf produce persistent://test-tenant1/test-namespace1/test695 -threads 1  -n 11 -r 1010 > log695 &
> 
> ```
> 
> 
> 
> 3.the configuration is as follows:
> 
> ```
> 
> #defaultNamespaceBundleSplitAlgorithm=topic_count_equally_divide
> 
> defaultNamespaceBundleSplitAlgorithm=flow_or_qps_equally_divide
> 
> loadBalancerNamespaceBundleMaxMsgRate=1010
> 
> flowOrQpsDifferenceThresholdPercentage=10
> 
> exposeBundlesMetricsInPrometheus=true
> 
> defaultNumberOfNamespaceBundles=1
> 
> ```
> 
> 
> 
> ### The comparison effect is as follows:
> 
> **1.Using the topic_count_equally_divide algorithm:**
> 
> 
> 
> The number of bundles after splitting is **21**, and the **pulsar_bundle_msg_rate_in** of a single bundle is: **49 msg/s ~ 1010 msg/s**：
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/19296967/185867834-543e8443-de48-48a4-b254-e5af7ddf2209.png)
> 
> 
> 
> 
> 
> 
> 
> **2.Using the new algorithm flow_or_qps_equally_divide:**
> 
> The number of bundles after splitting is **13**, and the **pulsar_bundle_msg_rate_in** of a single bundle is: **997 msg/s ~ 1010 msg/s**：
> 
> <img width="1282" alt="image" src="https://user-images.githubusercontent.com/19296967/185864580-198b92fb-ef0b-4390-9bfc-56a03a1b19f0.png">
> 
> 
> 
> 
> 
> 

@eolivelli @Technoboy- @codelipenghui PTAL,thanks!

**Comment by lordcheng10** [comment]
https://github.com/apache/pulsar/pull/16557

**Comment by lordcheng10** [comment]
discuss thread https://lists.apache.org/thread/cshyt10fwcjjxs93g8yf0svgwcgnshmg

**Comment by heesung-sn** [comment]
+1 LGTM.

**Comment by aloyszhang** [comment]
LGTM
+1

Heesung Sohn ***@***.***> 于2022年8月23日周二 13:40写道：

**Comment by lordcheng10** [comment]
vote thread:  https://lists.apache.org/thread/g6stjsrymmq3850pdt9whzgx91tx33v8
