### ISSUE TITLE
Sytem topic (change_events) became temporarily unavailable after expansion of broker

### ISSUE THREAD

**Issue by TianFeng111** [apache/pulsar#16811]
**Describe the bug**
We found a system topic (persistent://xxx/xxx/__change_events) became "temporarily unavailable" after  expansions of broker,  and we can't create producer on that namespace anymore, and even can't create topics . Here's some log from brokers and bookies below.
**Pulsar version**: apache-pulsar-2.10.0
**Logs**
1、**All bookies of this cluster got these log:**
![image](https://user-images.githubusercontent.com/28603029/181160538-65784364-467c-455c-9e8a-03ad6a894d86.png)
2、**log of the broker mentioned in bookie's log:**
![image](https://user-images.githubusercontent.com/28603029/181161361-56af2923-65e7-417b-8ed6-3d1ea1859df1.png)
3、**when I tried to lookup this system topic**
![image](https://user-images.githubusercontent.com/28603029/181159570-d83fc9f9-f871-41bc-ae40-6a4560c1f5da.png)

Sorry about mosaic in pics ，in case of sensitive info.

**Comment by Technoboy-** [comment]
From the pic 2~3, it's about unloading the topic that causes the system topic not to be available.
Does this issue going for a long time ?

**Comment by TianFeng111** [comment]
Finally，we found that caused by expansion and shrinkage of bookie.
