### ISSUE TITLE
Download Python Client as document steps throw errors

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#16849]
Python Client document writes:

```
# avro serialization
$ pip install pulsar-client[avro]=='2.10.1'

# functions runtime
$ pip install pulsar-client[functions]=='2.10.1'

# all optional components
$ pip install pulsar-client[all]=='2.10.1'
```

However, all these optional features return not found:

```
ERROR: Could not find a version that satisfies the requirement pulsar-client[avro]==2.10.1 (from versions: 2.8.0, 2.8.1, 2.9.1, 2.9.2, 2.10.0)
ERROR: No matching distribution found for pulsar-client[avro]==2.10.1
```

It seems we don't release pypi packages for 2.10.1?

cc @BewareMyPower @codelipenghui

**Comment by BewareMyPower** [comment]
Could you confirm whether the Python client has been released since you're the release manager of 2.10.1? @codelipenghui 

BTW, the command should be `pip3 install 'pulsar-client[all]==2.10.1'` on macOS.

**Comment by tisonkun** [comment]
@BewareMyPower I think the quote issue is introduced by zsh syntax. Here is a pull request to adapt the case #16851

**Comment by codelipenghui** [comment]
The Python Client for macos haven't push yet, I will push it later.

**Comment by tisonkun** [comment]
@codelipenghui still not found. Is there any estimate? Since 2.10.1 is an official release we must fix this issue though ><

**Comment by tisonkun** [comment]
This can be related to https://github.com/apache/pulsar/issues/17468.

**Comment by tisonkun** [comment]
Works for me now. Closing...
