### ISSUE TITLE
Pulsar broker with TLS failing when function worker enabled

### ISSUE THREAD

**Issue by rillo-carrillo** [apache/pulsar#16856]
**Describe the bug**
Pulsar broker not able to start when functionsWorkerEnabled set to true.

Pulsar Broker has TLS Enc enabled
```
tlsRequireTrustedClientCertOnConnect=true
tlsCertificateFilePath=/volume/broker/certs/tls.crt
tlsKeyFilePath=/volume/broker/certs/tls.key
tlsTrustCertsFilePath=/volume/broker/certs/ca.crt
```
Pulsar Proxy has TLS Env enabled
```
brokerClientTrustCertsFilePath=/volume/broker/certs/ca.crt
tlsEnabledWithBroker=true
tlsEnabledInProxy=true
tlsCertificateFilePath=/volume/broker/certs/tls.crt
tlsKeyFilePath=/volume/broker/certs/tls.key
tlsTrustCertsFilePath=/volume/broker/certs/ca.crt
```
We have configured function_worker.yml to use same certificates to connect with broker. But it fails on startup due to next error:
`PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

here is the config:

```
useTls: true
# For TLS:
# brokerServiceUrl: pulsar+ssl://localhost:6651/
pulsarServiceUrl: pulsar+ssl://localhost:6651/
# For TLS:
#webServiceUrl: https://localhost:8443/
pulsarWebServiceUrl: https://localhost:8443/
brokerClientTrustCertsFilePath: /volume/broker/certs/ca.crt

tlsEnabled: true
tlsCertificateFilePath: /volume/broker/certs/tls.crt
tlsKeyFilePath: /volume/broker/certs/tls.key
tlsTrustCertsFilePath: /volume/broker/certs/ca.crt
```
**To Reproduce**
1. Enable TLS on Broker
2. Enable functionsWorkerEnabled=true
3. Configure function_worker.yml to use TLS to connect broker

**Expected behavior**
If certificates are fine should be able to start up without issues

**Additional context**
We have made it work by changing a property on broker.conf to true
`tlsAllowInsecureConnection=true`

**Comment by nodece** [comment]
@rillo-carrillo There is a bug I need to fix, the current solution is add `brokerClientAuthenticationEnabled: true` to `functions_worker.yml`.

**Comment by bublikhpt** [comment]
I have the same error message after upgrade one node to 2.10.1 the others are still 2.7.x. But I'm using separate function workers and I don't have proxy. In addition I'm using commercial certificate for brokers interfaces and self signed certificate for auth. Is there any workaround for this setup or I must wait for fix? Solution in @nodece comment is not working because I'm using authentication and authorization so I have this option enabled "by default".

**Comment by rillo-carrillo** [comment]
Hi, @nodece thank you for the workaround, now my broker/function worker is starting successfully.

**Comment by michaeljmarshall** [comment]
I am going to close this since there was a workaround. Please reopen if that is incorrect.

**Comment by bublikhpt** [comment]
As I said, workaround doesn't work with my setup, so I stick on version 2.10.0. I haven't tried any newer versions of pulsar yet, but if this bug remains in all other newer versions, than I can't upgrade anyway.
