### ISSUE TITLE
[broker] Cursor status has always been SwitchingLedger and  pendingMarkDeleteOps has accumulated tens of thousands of requests

### ISSUE THREAD

**Issue by poorbarcode** [apache/pulsar#16859]
**Describe the bug**
The pendingMarkDeleteOps has accumulated tens of thousands of requests, and the cursor status has always been `SwitchingLedger`, and the retention cannot be executed, resulting in the situation that the disk space cannot be reclaimed. 

**Screenshots**
![181666034-f073360f-1f09-4261-95d9-4cdcac255aa8](https://user-images.githubusercontent.com/25195800/181667483-c545bd37-638f-4734-8992-e25c9a2b780c.png)

**Comment by poorbarcode** [comment]
Hi @keyboardbobo

Could you please provide the version used? If possible, you can upload the dump file (which may cause data leakage of the company).

**Comment by keyboardbobo** [comment]
My version is 2.9.2, the dump file is very large, and it is difficult to upload it on the intranet due to security reasons. The values of the ManagedCursorMXBean mbean are as follows:

> persistLedgeSucceed：cellsBusy=0,base=63308,cells:null
> persistLedgeFailed：cellsBusy=0,base=1,cells:null
> persistZookeeperSucceed：cellsBusy=0,base=1,cells:null
> persistZookeeperFailed：cellsBusy=0,base=0,cells:null
> writeCursorLedgerSize：cellsBusy=0,base=3437666,cells:null
> writeCursorLedgerLogicalSize：cellsBusy=0,base=1718833,cells:null
> readCursorLedgerSize：cellsBusy=0,base=9,cells:null

**Comment by poorbarcode** [comment]
Hi @keyboardbobo 

I now suspect that something is wrong with the `pendingMarkDeletedSubmittedCount`. Could you show the property `ManagedCursorImpl.pendingMarkDeletedSubmittedCount` ?

**Comment by keyboardbobo** [comment]
> Hi @keyboardbobo
> 
> I now suspect that something is wrong with the `pendingMarkDeletedSubmittedCount`. Could you show the property `ManagedCursorImpl.pendingMarkDeletedSubmittedCount` ?

`pendingMarkDeletedSubmittedCount `=0

**Comment by poorbarcode** [comment]
Hi @keyboardbobo 

> pendingMarkDeletedSubmittedCount =0

Thanks, then it is not `pendingMarkDeletedSubmittedCount`'s problem. Is there any other error log？

**Comment by keyboardbobo** [comment]
@poorbarcode 
At that time, an abnormal scenario with a large network delay from the broker to the bookie was simulated, and there were many errors similar to the following:

> Write of ledger entry to quorum failed
> NotEnoughBookiesException: Not enough non-faulty bookies available 
> UpdateLoop(ledgerId=2780774,loopId=54e667fe) Exception updating

Then the disk space increases, and some partitions cannot be reclaim.

**Comment by poorbarcode** [comment]
Hi @keyboardbobo 

> there were many errors similar to the following:

Could you show more detail about the error log?

**Comment by keyboardbobo** [comment]
@poorbarcode 
![C44760E7-903B-497C-BA96-2301ED769E30](https://user-images.githubusercontent.com/9923278/181719588-b2dbaa51-38e1-4b7a-aa99-59f873f15d6b.png)

**Comment by keyboardbobo** [comment]
![4EBC67CE-742F-4DC7-AB8E-4BF189D5FFCB](https://user-images.githubusercontent.com/9923278/182098369-03d91228-ecf7-443d-a4b5-334af3ee80a5.png)

**Comment by poorbarcode** [comment]
Hi @keyboardbobo 

> I found that there are thousands of tasks in the "BookKeeperClientWorker-OrderedExecutor-59-%d" thread group, and I don't know what caused it. SafeRunnable should catch the exception, but I don't know why this happens

`BoundedExecutorService` used in these  is used in the following three scenarios: 

- Write Bookie
- Read Bookie
- Send messages to the client

@hangc0276 Is it normal to have so many tasks in the queue?

**Comment by keyboardbobo** [comment]
@poorbarcode 
I took a look at some thread groups. Other thread groups are all 0. Only this one has a backlog of more than 7,000 tasks.

**Comment by keyboardbobo** [comment]
![82460ACC-897B-4F3E-A891-0EBF74C94D09](https://user-images.githubusercontent.com/9923278/182102479-70726c53-f8b6-489e-b5b2-be73a4e5306f.png)

**Comment by poorbarcode** [comment]
Hi @keyboardbobo 

>  The stack of the three threads of this thread group is as follows:

It seems that one topic is busy while others are not, but this seems have not related to the `cursor` state always being `SwitchingLedger` or maybe I didn't understand enough to realize the problem

**Comment by keyboardbobo** [comment]
> It seems that one topic is busy while others are not, but this seems have not related to the cursor state always being SwitchingLedger or maybe I didn't understand enough to realize the problem
@poorbarcode I suspect that when SwitchingLedger, some tasks are blocked in the queue, which makes it impossible to complete the execution.

**Comment by poorbarcode** [comment]
Hi @keyboardbobo 

Could you provide the BK configuration? 

- Ensemble size
- Write quorum size
- Ack quorum size

E.g. Ensemble size = 3, and Write quorum size = 3, When a bookie server does not work, the first write request will timeout, and other requests will backlog

**Comment by keyboardbobo** [comment]
@poorbarcode 
```
managedLedgerDefaultEnsembleSize=3
managedLedgerDefaultWriteQuorum=3
managedLedgerDefaultAckQuorum=2
```
If the bookie is unavailable and the write request blocks, will it block in the queue?

**Comment by keyboardbobo** [comment]
@poorbarcode  There is a new development on the question, but I'm not sure if it's the same problem:
 https://github.com/apache/pulsar/issues/17967

**Comment by poorbarcode** [comment]
This issue might be fixed by https://github.com/apache/pulsar/pull/17971
