### ISSUE TITLE
[branch-2.9] Some broken tests are ignored in CI

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar#16854]
**Describe the bug**
https://github.com/apache/pulsar/pull/13644 is not cherry-picked into branch-2.9 and branch-2.10, the `AdminApiTest2` will be ignored in CI so that some failed tests won't be exposed.

**To Reproduce**

Run `AdminApiTest2#brokerNamespaceIsolationPoliciesUpdateOnTime`, it will fail in branch-2.9 and branch-2.10.

**Expected behavior**
https://github.com/apache/pulsar/pull/13644 should be cherry-picked or migrated into branch-2.9 and branch-2.10.

**Additional context**
In branch-2.8, I pushed two commits (ad868ac and c817873) directly to fix this issue.

**Comment by BewareMyPower** [comment]
https://github.com/apache/pulsar/blob/branch-2.9/pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest2.java

**Comment by tisonkun** [comment]
Closed as stale and it seems to be fixed. Please open a new issue if it's still relevant to the maintained versions.
