### ISSUE TITLE
Tidy issue templates and remove redundant entries

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#16868]
I propose to make the following changes on our issue template:

1. [`.github/ISSUE_TEMPLATE.md`](https://github.com/apache/pulsar/blob/master/.github/ISSUE_TEMPLATE.md) is no more used, we can remove it.
2. We only use [yaml format](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) for doc issue template now, and we can adopt it to other entries.

I'm going to prepare a draft for preview in the next week. It should not change experience too much. But later we don't edit markdown template, instead, we fill text box and select checkbox.

cc @Anonymitaet @codelipenghui @hangc0276

**Comment by Anonymitaet** [comment]
@tisonkun thanks! 
When I created [doc_request.yaml](https://github.com/apache/pulsar/blob/master/.github/ISSUE_TEMPLATE/doc_request.yml), I thought issue raisers need to go through some "required" questions to remind them to think about and research on what they need, and then ask.

**Comment by tisonkun** [comment]
@Anonymitaet thanks for sharing the background. I submit a patch at #16902.
