### ISSUE TITLE
[Doc] wrong pip in 2.10.0 release notes

### ISSUE THREAD

**Issue by youzipi** [apache/pulsar#16911]
### What issue do you find in Pulsar docs?

In `2.10.0` 's release notes:
```
[PIP 106] Broker extensions to provide operators of enterprise-wide clusters better control and flexibility [#12536](https://github.com/apache/pulsar/pull/12536)
```
the link and description is not the `negative ack backoff`  PIP.

in issue, i found the `broker extensions...` is **PIP-106** too.

PIP-106_nack is in 2.10.0,
PIP-106_broker_extension is in 2.11.0

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5629307/182279964-6f8fc82b-155b-4340-a4b3-8ace315a9bbb.png">

### What is your suggestion?

-

### Do you have any references?

-

### Would you like to fix this issue?

yes, but i do not know how to modify the github release note, maybe i do not have access. 

### Note

- [X] I have researched my question.

**Comment by RobertIndie** [comment]
They were both released in the 2.10.0:
* [PIP 106] Broker extensions to provide operators of enterprise-wide clusters better control and flexibility : https://github.com/apache/pulsar/pull/12536
* PIP 106: Negative acknowledgment backoff : https://github.com/apache/pulsar/pull/12566

And they were all described in the 2.10.0 release note. You can see the PR for Negative acknowledgment backoff in the 'Clients' section.

**Comment by youzipi** [comment]
> And they were all listed in the 2.10.0 release note. You can see the PR for Negative acknowledgment backoff in the 'Clients' section.

no, the nack PR is not listed there.
I think the duplicate PIP number is the reason.

https://pulsar.apache.org/release-notes/versioned/pulsar-2.10.0#clients
![image](https://user-images.githubusercontent.com/5629307/183570172-c0ac8699-89be-4af7-a9f7-333f66836612.png)

**Comment by momo-jun** [comment]
Closed the issue since it hasn't been planned yet at this moment. Feel free to reopen it when it's relevant.
