### ISSUE TITLE
Get rid of powermock

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#16912]
In this comment https://github.com/apache/pulsar/pull/16884#issuecomment-1201512995 I wrote:

> I don't like powermock as it lacks maintenance. It seems all usage of powermock is `Whitebox`. We can get rid of it with simple reflections. This can be a separate issue, though.

Thus I file this issue to investigate whether we can remove powermock from our testing framework.

WDTY @merlimat @lhotari @codelipenghui @nicoloboschi?

**Comment by Shoothzj** [comment]
I think we can simply modify the access modifiers, and mark `@VisableForTesting` .We have used this in many codes.

**Comment by tisonkun** [comment]
@Shoothzj IIUC do you suggest a replacement of powermock here?

**Comment by Shoothzj** [comment]
@tisonkun Yes, I suggest to replace powermock. Using `@VisableForTesting` instead of reflections

**Comment by tisonkun** [comment]
@Shoothzj thank you. I'll consider this approach. There're some cases we try to hijack third-party lib's field, like `eventLoopGroup` in bookkeeper code. In those situations, we should still use reflections. (... or patching upstream, or change testing logics)

**Comment by tisonkun** [comment]
I draft an incompleted patch on #16997.

However, I notice that there's some code we hack in "set final" field, like:

https://github.com/apache/pulsar/blob/21634edd30bbe33d231ec73e8045d7666a8ad366/pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java#L1071-L1072

.. or even "set static final" field, like:

https://github.com/apache/pulsar/blob/21634edd30bbe33d231ec73e8045d7666a8ad366/pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/thread/ThreadRuntimeFactoryTest.java#L111

It seems `powermock-reflect` is the better library existing to handle these cases since JDK12+ it's banned changing `final` field instead you have to use `Unsafe`. I tend not to maintain such unsafe hacks within Pulsar codebase. And perhaps we should gradually refactor code to avoid depending on such manners.

cc @Shoothzj @eolivelli
