### ISSUE TITLE
[Security] [Doc] no advice on how to report vulnerabilities

### ISSUE THREAD

**Issue by hpvd** [apache/pulsar#16919]
**Describe the bug**
security: no advice on how to report vulnerabilities

**To Reproduce**
1. visit: https://github.com/apache/pulsar/issues/new/choose
2. click button "view policy": https://github.com/apache/pulsar/security/policy
3. follow link to: https://pulsar.apache.org/docs/security-policy-and-supported-versions/

see screenshot

**Expected behavior**
an advice how to report vulnerabilities - or is it fine to just open an issue?

**Screenshots**
![2022-08-02_15h43_40](https://user-images.githubusercontent.com/5681880/182392310-87521018-285b-40ae-a344-e01cba04d625.png)

**Comment by hpvd** [comment]
@sijie @Anonymitaet Do you have any idea/advice on this?

**Comment by tisonkun** [comment]
Hi @hpvd,

Thanks for reporting this issue! I think we can add a short statement to report security vulnerabilities via private mailing list or the ASF security mailing list.

**Comment by tisonkun** [comment]
I'll prepare a patch and ask for PMC members to review.

**Comment by Anonymitaet** [comment]
"How to report a Pulsar security issue" is documented in the [Contribution guide](https://pulsar.apache.org/community/#section-contribute).

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/50226895/183322039-83d6c44b-2342-46cd-bb94-89963fe5be86.png">

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/50226895/183322068-26d0950a-8129-4185-b8d3-45b8f2288848.png">

**Comment by tisonkun** [comment]
@Anonymitaet

The only link in SECURITY.md redirects users to "Security Policy and Supported Versions". To reduce confusion, either change the link to "Reporting a Vulnerability" or duplicate the info to the "Security Policy and Supported Versions" page. I prepare a patch of the latter way in #16962, you may give a review comment there.

**Comment by lhotari** [comment]
https://pulsar.apache.org/docs/next/security-policy-and-supported-versions/ contains the new version, but it is missing from https://pulsar.apache.org/docs/security-policy-and-supported-versions/ . @Anonymitaet I'm reopening this issue until that is resolved.

**Comment by tisonkun** [comment]
@lhotari do you mean that we should cherry-pick (to master) this change to other versioned docs?

**Comment by lhotari** [comment]
> @lhotari do you mean that we should cherry-pick (to master) this change to other versioned docs?

I guess that is need. In addition I think it's necessary to inline the information to SECURITY.md so that the information isn't missing at least from that page.

**Comment by lhotari** [comment]
@Anonymitaet how can we get https://pulsar.apache.org/docs/security-policy-and-supported-versions/ to match what is seen at https://pulsar.apache.org/docs/next/security-policy-and-supported-versions/ (to include #16962 changes)?

**Comment by Anonymitaet** [comment]
@lhotari Do you mean bringing #16962 changes to 2.10.1? If so, just copy and paste

**Comment by michaeljmarshall** [comment]
Great catch, @hpvd. I didn't realize I had missed advising _how_ to report a vulnerability. I agree with duplicating the information in the `SECURITY.md` file. This information won't change with any frequency, and it is imperative to make it easy to find.

I'd like to propose that we don't version the security page, but instead have some top level tab (or something like that) to make it easy to find and maintain.

**Comment by tisonkun** [comment]
@michaeljmarshall shall we close this issue since #17039 merged? Or you'd like to complete it after we move the doc outside from versioned ones.

**Comment by michaeljmarshall** [comment]
Thanks for following up @tisonkun, yes, I believe #17039 completes this issue. Please reopen the issue if you see any issues @hpvd.
