### ISSUE TITLE
PIP-190-Part2: Modify the Versions page

### ISSUE THREAD

**Issue by momo-jun** [apache/pulsar#16938]
**Is your feature request related to a problem? Please describe.**
Refer to [PIP-190](https://github.com/apache/pulsar/issues/16637).

**Describe the solution you'd like**
As part of PIP-190 implementation, we will narrow the listing of doc versions by modifying the `versions.json` file. Correspondingly, it brings changes to the last column of release notes, which is auto-generated by scripts. 

Considering the main purpose of the [Versions](https://pulsar.apache.org/versions/) page and we already offer a [summary page of release notes](https://pulsar.apache.org/release-notes/), we can modify the [Versions](https://pulsar.apache.org/versions/) page as follows.
1. remove the last column of specific release notes.
2. add a sentence to navigate users to the [Release notes](https://pulsar.apache.org/release-notes/) page.
<img width="745" alt="image" src="https://user-images.githubusercontent.com/60642177/182745204-5cab8c4a-1449-406a-b6e2-ce65352f1133.png">

cc @urfreespace

**Comment by momo-jun** [comment]
@urfreespace thanks for implementing this change.
After #16925 is merged, we want to add one more sentence at the bottom of the page to explain a bit about this versioning change.

`Note that starting from 2.8.x, we release and maintain one set of documentation for each minor release and following bug-fix releases. `

**Comment by urfreespace** [comment]
@momo-jun  https://github.com/apache/pulsar-site/pull/157 versions page is modified.

**Comment by momo-jun** [comment]
@urfreespace #17074 has been merged, can you pls implement this change?

> @urfreespace thanks for implementing this change. After #17074 is merged, can you pls add one more sentence at the bottom of the page to explain a bit about this versioning change.
> 
> `Note that starting from 2.8.x, we release and maintain one set of documentation for each minor release and following bug-fix releases. `
