### ISSUE TITLE
Failed to start standalone pulsar service with tiered storage due to class not found problem 

### ISSUE THREAD

**Issue by lujiwen** [apache/pulsar#16955]
**Describe the bug**
Failed to start standalone pulsar service with tiered storage due to class not found problem :
ERROR org.apache.pulsar.broker.PulsarService - Failed to start Pulsar service: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.hdfs.DistributedFileSystem not found

**To Reproduce**
1. config hdfs tiered storage by following the steps described in https://pulsar.apache.org/docs/cookbooks-tiered-storage/, and ensure that offloader nar files in the offloader directory 
2 log shows that 2 offloader nar files are loaded as : 

![image](https://user-images.githubusercontent.com/3608828/183021551-65777e23-3ca6-406b-8d5a-5e93cceb3d7d.png)

3. start standalone pulsar service: ./bin/pulsar standalone
4. an exception is thrown

**Expected behavior**
service starts and runs normally at least

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  linux 

**Additional context**

**Comment by fishisnow** [comment]
the same as me, i'am just follow the installed guide one by one, but it can't be work
https://pulsar.apache.org/docs/2.11.x/tiered-storage-filesystem/
![image](https://user-images.githubusercontent.com/11990268/234442094-4a7dd74a-604a-4e4f-adf9-4ea755e954d9.png)

**Comment by ethqunzhong** [comment]
I have also encountered this bug, and I will try to fix the issue.
