### ISSUE TITLE
Flaky-test: org.apache.pulsar.tests.integration.presto.TestBasicPresto.testForSchema

### ISSUE THREAD

**Issue by AnonHxy** [apache/pulsar#16975]
org.apache.pulsar.tests.integration.presto.TestBasicPresto.testForSchema is flaky. It fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/7713785320?check_suite_focus=true)

```
  2022-08-07T15:28:25,634 - ERROR - [docker-java-stream--278407304:DockerUtils$2@279] - DOCKER.exec(pulsar-sql-test-presto-worker:/bin/bash -c /pulsar/bin/pulsar sql --execute 'select * from pulsar."public/default"."schema_key_value_separated_test_ghyiy" order by entryid;'): completed with non zero return code: 1
  stdout: 
  stderr: Query 20220807_152823_00003_wcx2v failed: Decoding avro record failed.
```

I find this issue  https://github.com/apache/pulsar/issues/9704  has related on the test failure.  And I can reproduce it on my Mac  if I follow the steps,  even build from master branch.

What confused me is that  this test can pass on other PR, e.g,: [success test](https://github.com/apache/pulsar/runs/7686565421?check_suite_focus=true),  but always fail on [example failure](https://github.com/apache/pulsar/runs/7713785320?check_suite_focus=true), and always fail on Mac  when I try to  reproduce it.

I'll appreciate it very much if anyone can explain it.

error stack here.
<img width="942" alt="image" src="https://user-images.githubusercontent.com/10233437/183299505-761ec476-39d4-41d7-93b1-d73793e62ecf.png">

query sql is :
```
select * from pulsar."public/default"."kv-schema-test2";
```

**Comment by codelipenghui** [comment]
@gaoran10 Do you have some ideas about this issue?
