### ISSUE TITLE
[Website] Remove general content from Pulsar version specific content

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#17052]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

There's current a problem in maintaining content that isn't Pulsar version specific. For example, the content for https://pulsar.apache.org/docs/security-policy-and-supported-versions/ comes from the most recently released Pulsar version docs and there's a copy of this page for previous releases. This makes it hard to keep the content updated. 
The problem was mentioned in this comment: https://github.com/apache/pulsar/pull/17039#issuecomment-1211108262

### Solution

I would suggest a further PR removes all of these and instead in the versioned menus refers to the common and most current version.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Refer to #18103

**Comment by tisonkun** [comment]
Superseded by #18103.
