### ISSUE TITLE
key-shared keyHashRange() dont't cacultate 

### ISSUE THREAD

**Issue by luhea** [apache/pulsar#17073]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

hello,when i consume a topic, topic message is like this:"1001":{"test1":"test1"}
"1002":{"test2":"test2"} , in pulsar topic key is : 1001,1002 ,value is {"test1":"test1"}，{"test2":"test2"} .when i use key-shred consume this topic，i want to get key：1001，i see Reader has func  keyHashRange() ，but i don't know the key：1001 this HashRange , i want to know i should how to cacultate key HashRange or key-shred consume mode has key filter?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
@luhea I see you check the box "I'm willing to submit a PR!" but in the description, it likes [a bug report](https://github.com/apache/pulsar/issues/new?assignees=&labels=type%2Fbug&template=bug-report.yml&title=%5BBug%5D+) or [a user question](https://github.com/apache/pulsar/discussions/new?category=q-a)?

**Comment by luhea** [comment]
> @luhea I see you check the box "I'm willing to submit a PR!" but in the description, it likes [a bug report](https://github.com/apache/pulsar/issues/new?assignees=&labels=type%2Fbug&template=bug-report.yml&title=%5BBug%5D+) or [a user question](https://github.com/apache/pulsar/discussions/new?category=q-a)?

is a user question

**Comment by tisonkun** [comment]
In the issue template, we suggest you ask in the [Discussions](https://github.com/apache/pulsar/discussions/new?category=q-a) forum to get dedicated attention. The Pulsar community uses issues to track bug reports and actionable tasks.

Could you close this issue and ask there with concrete Pulsar version, and detailed reproduce steps if any?

If by any chance you'd prefer ask in Chinese, you may try out [this forum](https://forum.streamnative.io/c/native/zh/22).
