### ISSUE TITLE
[Bug] python use tls connect error

### ISSUE THREAD

**Issue by liliang950210** [apache/pulsar#17097]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.7.4

### Minimal reproduce step

class TestPulsarClient():
    def test_instance(self):
        server_url = "pulsar+ssl://xxxxx:xxx/"
        self._instance = pulsar.Client(server_url, tls_validate_hostname=False, tls_trust_certs_file_path="trust.pem", tls_allow_insecure_connection=False)
        while True:
            try:
                consumer = self._instance.subscribe("persistent://public/default/test003", 'test01')
                msg = consumer.receive(timeout_millis=3000)
                print("msg:", msg)
                consumer.acknowledge(msg)
            except KeyboardInterrupt as e:
                print("Process terminated by manual stop!{}", e)
            except BaseException as e:
                print("error:", e)
            finally:
                self._instance.close()
                print("c")

### What did you expect to see?

connect to pulsar

### What did you see instead?

ssh://ossuser@xxx:22/opt/share/oss/xxxx/infers/venv/bin/python -u /tmp/pycharm_project_181/pulsarTest/TestTlsConnection.py
0000-00-00 00:00:00.000 INFO  [0000-00-00 00:00:00.000 INFO  [
Process finished with exit code 139

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by nodece** [comment]
I tried using the pulsar-client@2.10.1 to request the broker@2.7.4, it works fine.

The following is my broker config:
```
brokerServicePortTls=6651
webServicePortTls=8081
tlsCertificateFilePath=broker.pem
tlsKeyFilePath=broker-key-pk8.pem
tlsTrustCertsFilePath=ca.pem
```

Client log:
```
2022-08-15 18:31:44.527 INFO  [0x10bc01600] Client:88 | Subscribing on Topic :persistent://public/default/test003
2022-08-15 18:31:44.527 INFO  [0x10bc01600] ClientConnection:190 | [<none> -> pulsar+ssl://127.0.0.1:6651/] Create ClientConnection, timeout=10000
2022-08-15 18:31:44.529 INFO  [0x10bc01600] ConnectionPool:84 | Created connection for pulsar+ssl://127.0.0.1:6651/
2022-08-15 18:31:44.530 INFO  [0x70000eb25000] ClientConnection:376 | [127.0.0.1:51214 -> 127.0.0.1:6651] Connected to broker
2022-08-15 18:31:44.556 INFO  [0x70000eb25000] HandlerBase:55 | [persistent://public/default/test003, test01, 0] Getting connection from pool
2022-08-15 18:31:44.558 INFO  [0x70000eb25000] ClientConnection:190 | [<none> -> pulsar+ssl://127.0.0.1:6651/] Create ClientConnection, timeout=10000
2022-08-15 18:31:44.559 INFO  [0x70000eb25000] ConnectionPool:84 | Created connection for pulsar+ssl://localhost:6651
```

Could you provide your broker config or client log to help me find your issue?

**Comment by liliang950210** [comment]
i use 2.10.1 ，log like these 

/opt/share/oss/xxxx/infers/venv/bin/python -u /tmp/pycharm_project_181/pulsarTest/TestTlsConnection.py
2022-08-16 14:08:01.905 INFO  [139791013365568] Client:88 | Subscribing on Topic :persistent://public/default/test003
2022-08-16 14:08:01.905 INFO  [139790747305728] ExecutorService:41 | Run io_service in a single thread
2022-08-16 14:08:01.905 INFO  [139791013365568] ClientConnection:189 | [<none> -> pulsar+ssl://xxxx:xxxx/] Create ClientConnection, timeout=10000
Segmentation fault (core dumped)

**Comment by BewareMyPower** [comment]
Could you generate the core dump and use GDB to show the stack traces (via `bt all` command)?

**Comment by nodece** [comment]
I cannot reproduce this issue :(

**Comment by liliang950210** [comment]
which python version you used? my python version is 3.9.

**Comment by liliang950210** [comment]
> 
gdb /opt/share/oss/NetEco/NAIEDeployCombAgent/infers/venv/bin/python -u /tmp/pycharm_project_460/pulsarTest/TestTlsConnection.py
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named os
Interpreter `/tmp/pycharm_project_460/pulsarTest/TestTlsConnection.py' unrecognized

**Comment by nodece** [comment]
I'm using the Python 3.7.

**Comment by liliang950210** [comment]
gdb /opt/share/oss//infers/venv/bin/python -u /tmp/pycharm_project_460/pulsarTest/TestTlsConnection.py
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named os
Interpreter `/tmp/pycharm_project_460/pulsarTest/TestTlsConnection.py' unrecognized

**Comment by BewareMyPower** [comment]
Could you generate the core file (assuming the name is `core`) and just run `gdb python core`?

In addition, could you share your Python script with the correct indent so we can just paste it to our local env?

**Comment by liliang950210** [comment]
Security hardening has been performed on my environment, gdb these need to be reinstalled, I am trying to reinstall.
Is it true that our pulsar client does not support Python 3.9?

**Comment by BewareMyPower** [comment]
> Is it true that our pulsar client does not support Python 3.9?

It supports Python 3.9.

**Comment by BewareMyPower** [comment]
You can verify if the library supports Python 3.9 with a simple e2e case on a Pulsar standalone (no TLS or authentication configured).

**Comment by liliang950210** [comment]
[coredump.log](https://github.com/apache/pulsar/files/9461686/coredump.log)
please help check it,thanks

**Comment by BewareMyPower** [comment]
Could you provide your OS version and how did you install the Python client? Installed from `pip` or building from source?

Could you try the wheel from [StreamNative's 2.10.1.6 release](https://github.com/streamnative/pulsar/releases/tag/v2.10.1.6)?

**Comment by liliang950210** [comment]
Linux kwephis349347 4.18.0-147.5.1.6.h579.eulerosv2r9.x86_64 #1 SMP Wed Sep 8 09:00:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

pip install *.whl

**Comment by liliang950210** [comment]
After the TLS is loaded to the Python client, a core dump occurs. According to the analysis, the ARM version is correct, but the x86 version is incorrect. The difference is that the OpenSSL version in the .so file is different. The ARM version is 1.1.1, and the x86 version is 1.1.0. Is this the cause?

**Comment by liliang950210** [comment]
Could you try the wheel from [StreamNative's 2.10.1.6 release](https://github.com/streamnative/pulsar/releases/tag/v2.10.1.6)?
--- i tried, core too。

can make the openssl to 1.1.1?

**Comment by BewareMyPower** [comment]
> can make the openssl to 1.1.1?

Maybe we need to enhance the Python wheel build script. @RobertIndie would you like to take over this task?

**Comment by liliang950210** [comment]
Can we put out a temporary package first, and we'll check if it's feasible?

**Comment by nodece** [comment]
My OpenSSL version is 2.8.3.

**Comment by liliang950210** [comment]
> My OpenSSL version is 2.8.3.

The version is a bit high, I don't know if it's feasible. Or can the so file dynamically depend on OpenSSL without specifying the version?

**Comment by liliang950210** [comment]
This issue has a great impact on the version release. When will this issue be resolved?

**Comment by liliang950210** [comment]
> My OpenSSL version is 2.8.3.

hi，Any progress?

**Comment by nodece** [comment]
Cannot reproduce this issue on OpenSSL 1.1.1.

- Linux
Linux 900b7587f8c0 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- OpenSSL
OpenSSL 1.1.1f  31 Mar 2020
- Python 3.9.6

**Comment by BewareMyPower** [comment]
I think the core question is that how did you generate the certificates? What's the version of the `openssl` you used? It could help reproduce the issue.

**Comment by liliang950210** [comment]
> my openssl version:  openssl version
OpenSSL 1.1.1f  31 Mar 2020

**Comment by liliang950210** [comment]
[root@DisbNode02 site-packages]# strings _pulsar.cpython-39-x86_64-linux-gnu.so|grep -i openssl|grep OpenSSL
UI_OpenSSL
OpenSSL_version_num
OpenSSL_version
DH_OpenSSL
DSA_OpenSSL
EC_KEY_OpenSSL
RAND_OpenSSL
RSA_PKCS1_OpenSSL
OpenSSL
OpenSSL SSL_read: %s, errno %d
OpenSSL SSL_connect: %s in connection to %s:%ld
OpenSSL SSL_read on shutdown: %s, errno %d
OpenSSL SSL_write: %s, errno %d
OpenSSL was built without SSLv2 support
OpenSSL was built without SSLv3 support
OpenSSL was built without TLS 1.3 support
could not load PEM client certificate, OpenSSL error %s, (no key found, wrong pass phrase, or wrong file format?)
could not load ASN1 client certificate, OpenSSL error %s, (no key found, wrong pass phrase, or wrong file format?)
BIO_new return NULL, OpenSSL error %s
could not parse PKCS12 file, check password, OpenSSL error %s
could not load PKCS12 client certificate, OpenSSL error %s
unable do create OpenSSL user-interface method
OpenSSL 1.1.0j  20 Nov 2018
OpenSSL CMAC method
%s:%d: OpenSSL internal error: %s
OpenSSL 1.1.0j  20 Nov 2018
OpenSSL X9.42 DH method
OpenSSL PKCS#3 DH method
OpenSSL DH Method
OpenSSL DSA method
OpenSSL EC algorithm
OpenSSL EC_KEY method
OpenSSL X25519 algorithm
OpenSSL HMAC method
OpenSSL RSA method
OpenSSL PKCS#1 RSA
OpenSSL default user interface
OpenSSL 'dlfcn' shared library method
You need to read the OpenSSL FAQ, https://www.openssl.org/docs/faq.html
OpenSSL default
OpenSSL_version_num
DSA_OpenSSL
RAND_OpenSSL
RSA_PKCS1_OpenSSL
OpenSSL_version
EC_KEY_OpenSSL
DH_OpenSSL
UI_OpenSSL
[root@DisbNode02 site-packages]#


you can see the iso  in whl files,the openssl version is 1.1.0.

so  I hope that the OpenSSL version in this WL file is 1.1.1.

**Comment by liliang950210** [comment]
The OpenSSL is carried during Python compilation. The OpenSSL version is 1.1.1n. The .so file in the pulsar client also contains the OpenSSL static compilation. The OpenSSL version appears to be 1.1.0j. Therefore, the Python version does not match the client version.
Can you compile the pulsar client without OpenSSL so that the client can dynamically connect to OpenSSL?

**Comment by RobertIndie** [comment]
I find that we are already using the OpenSSL 1.1.1n in the 2.10.1: https://github.com/apache/pulsar/blob/0702b51ce09cc99044f4110e6bf98e82a0e86283/pulsar-client-cpp/docker/manylinux2014/Dockerfile#L59. But the released python wheels still using the OpenSSL1.1.0j. I think there may be a problem during the release process. I have created a PR to fix it: https://github.com/apache/pulsar/pull/17536

> Can you compile the pulsar client without OpenSSL so that the client can dynamically connect to OpenSSL?

You can check here for the context: https://github.com/apache/pulsar/blob/0702b51ce09cc99044f4110e6bf98e82a0e86283/pulsar-client-cpp/docker/manylinux2014/Dockerfile#L45-L48

**Comment by liliang950210** [comment]
> release

Can you send a whl file and I'll verify it first?

**Comment by liliang950210** [comment]
Why Is the OpenSSL Version in the Wheel File Compiled by Ubuntu Still 1.1.0? The local OpenSSL version is 1.1.1f. How Do I Specify the OpenSSL Version?

**Comment by BewareMyPower** [comment]
@liliang950210 Did you build the wheel file using latest https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/docker/build-wheels.sh? It should use OpenSSL 1.1.1n dependency now.

**Comment by liliang950210** [comment]
Is there a new whl package based on this? It is difficult to compile on the intranet.

**Comment by BewareMyPower** [comment]
You can wait StreamNative's next release (2.10.1.9) on branch-2.10. The latest release is [2.10.1.8](https://github.com/streamnative/pulsar/releases/tag/v2.10.1.8) that doesn't include https://github.com/apache/pulsar/pull/17538.

**Comment by liliang950210** [comment]
When is this expected to be released? Can I test a temporary version?

**Comment by BewareMyPower** [comment]
Maybe next week. You can build the wheel by yourself. Or do you want anyone to build the wheel for you?

**Comment by liliang950210** [comment]
Yes, I want to help me compile a whl file first, I'll verify it on the environment first.

**Comment by BewareMyPower** [comment]
> In addition, why the Python client of 2.7.x does not support Python 3.9? Can the OpenSSL upgrade be integrated into other versions, such as 2.7.x and 2.8.x?

I'm afraid not. You'd better use a newer Python client.

**Comment by liliang950210** [comment]
> Maybe next week. You can build the wheel by yourself. Or do you want anyone to build the wheel for you?

Is there a release now? The project is about to go live. I want to try it.

**Comment by BewareMyPower** [comment]
@liliang950210 I'm afraid the upgrade doesn't work because the base image to build Python wheel is somehow wrong. For now, I can build a wheel for Python 3.9 for x86_64 arch for your temporary use.

@merlimat This issue is exactly what I've concerned in https://github.com/apache/pulsar/pull/17536, uploading an image manually in DockerHub is not good for maintain and the changes for Dockerfile might not be applied.

**Comment by liliang950210** [comment]
> @liliang950210 I'm afraid the upgrade doesn't work because the base image to build Python wheel is somehow wrong. For now, I can build a wheel for Python 3.9 for x86_64 arch for your temporary use.

OK, thank you very much, can give me one, I'll test it first.

**Comment by BewareMyPower** [comment]
@liliang950210 https://drive.google.com/drive/folders/10KYlvcins_cE3YEHCD7x4_UPiu0YpL02?usp=sharing

**Comment by BewareMyPower** [comment]
It should be fixed by new releases of https://github.com/apache/pulsar-client-python

**Comment by liliang950210** [comment]
[2.10.1 ](https://pypi.org/project/pulsar-client/2.10.1/#files) will these file update?

**Comment by BewareMyPower** [comment]
No. You can look forward to the upcoming 3.0.0 release.

**Comment by liliang950210** [comment]
I tried the latest version and still seems to have problems.
