### ISSUE TITLE
PIP-199: Create a robust and inline Client Feature Matrix page

### ISSUE THREAD

**Issue by momo-jun** [apache/pulsar#17098]
### Motivation

As the outcome of PIP-108, the [Client Feature Matrix](https://docs.google.com/spreadsheets/d/1YHYTkIXR8-Ql103u-IMI18TXLlGStK8uJjDsOOA0T20/edit#gid=1784579914) has addressed the [initial user request](https://github.com/apache/pulsar/issues/9723) for technology evaluation and selection. It has been linked on [Pulsar doc site](https://pulsar.apache.org/docs/next/client-libraries#feature-matrix), providing an overview of feature supportability on language-specific clients.

However, it has the following limitations to continually serving the purpose over time:
1. **Visibility:** Not prominent for users/maintainers to notice.
2. **Process control:** No required review/approval or version control.
3. **Accuracy:** A bit out-of-dated with limited chances to get it updated (possibly caused by 1&2).

### Goal

As an extension/enhancement to PIP-108, this proposal aims to make the existing client feature matrix more robust and prominent to address the above pain points and better serve the adoption purpose.

### Implementation

> Note: Instead of showing a full version to duplicate the existing feature matrix, this PIP aims to build a compact version with key features listed to serve the adoption purpose better.

1. Deliver a more robust Client Feature Matrix and required documentation through a thorough review and update. 
----@RobertIndie and @shibd will be working on adding the information for missing features and supportability in language-specific clients.
2. Work out a [compact feature list](https://docs.google.com/document/d/1zyDrIeqH5BpXrQp5kOkw_X2m33M7GiDX6oXISvFY1go/edit?usp=sharing) that makes more sense for adoption from a user perspective. ---- @ericsyh @liudezhi2098 reviewed the feature list.
3. Build the compact matrix on a web page to provide a better reading experience. [Reference](https://beam.apache.org/documentation/runners/capability-matrix/when-in-processing-time/).  ---- @urfreespace has researched it.

**Comment by tisonkun** [comment]
Thanks for starting this discussion. I'd like to mention my previous attempt on this direction https://github.com/apache/pulsar-site/issues/146.

I will take a closer look at this proposal. Generally, I'd prefer inline the current feature matrix into each client's document entries instead of displaying the big feature matrix map in another approach - it consumes substantial developer efforts while it may not provide too much value.

**Comment by momo-jun** [comment]
@tisonkun thanks for your suggestion. Maintaining a matrix provides a chance to do a horizontal comparison within the same set of features. I think it provides value to both maintainers and users in the whole picture.

**Comment by tisonkun** [comment]
@momo-jun Yeah. If only there were volunteers who are willing to do it instead of "need developer resources".

Do you have a more concrete design and implementation? This proposal is far more than actionable now.

**Comment by momo-jun** [comment]
@tisonkun This is just a heads-up. I haven't got a concrete design or implementation plan yet.
The questions you listed are good ones that need to be clarified. I will add more details and discuss it in the community soon.

**Comment by momo-jun** [comment]
Move it to pending at this time point since there has been no feedback on the [discussion thread](https://lists.apache.org/thread/k376q0tgsrjr1wdqc8r9hqqtt1kl4qxx) yet and no engineering resources to build the page. 
Will revisit it later.

**Comment by momo-jun** [comment]
This PIP has been WIP since last week. I've updated the description and will add more details as soon as we have a bare bone to demo.

**Comment by hpvd** [comment]
awesome!
