### ISSUE TITLE
[Doc]  admin-api-topics contains wrong paragraph for concepts-messaging

### ISSUE THREAD

**Issue by alpreu** [apache/pulsar#17101]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The admin-api-topics page contains information on how to administrate topics using the admin API.
Towards the end there is a section that explains using the Client APIs Producer to write to a partitioned-topic.
https://pulsar.apache.org/docs/next/admin-api-topics/#publish-to-partitioned-topics
This section is in parts a duplicate of https://pulsar.apache.org/docs/next/concepts-messaging/#partitioned-topics but also contains some more information that does not belong on the Admin API page.

### What is your suggestion?

This section is in parts a duplicate of https://pulsar.apache.org/docs/next/concepts-messaging/#partitioned-topics but also contains some more information. I believe this section should be removed from the admin API page and maybe parts of it should be merged into the concepts-messaging page.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by RobertIndie** [comment]
Good catch! Thanks. I am working on it.
