### ISSUE TITLE
Flaky-test: [CI - Unit - Brokers - Broker Group 2] running over 1 hour

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#17112]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/runs/7849998733?check_suite_focus=true

### Exception stacktrace

NA

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by codelipenghui** [comment]
Another one: https://github.com/apache/pulsar/runs/7851405789?check_suite_focus=true

**Comment by tjiuming** [comment]
@codelipenghui how about split it into 2 parts?

**Comment by poorbarcode** [comment]
assign to me

**Comment by lhotari** [comment]
another one: https://github.com/apache/pulsar/runs/8261825287?check_suite_focus=true#step:11:556

**Comment by nodece** [comment]
Link to #17017 and #16538.
