### ISSUE TITLE
[Bug] It should be mandatory to provide a schema in Context::newOutputRecordBuilder

### ISSUE THREAD

**Issue by cbornet** [apache/pulsar#17114]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Currently the API to create a Record from the Function Context is
```java
<X> FunctionRecord.FunctionRecordBuilder<X> newOutputRecordBuilder();
```
It should be
```java
<X> FunctionRecord.FunctionRecordBuilder<X> newOutputRecordBuilder(Schema<X> schema);
```
to ensure the record has a Schema since the record will be used to publish to a Pulsar topic.

### Anything else?

This should be done before the release of 2.11 since it's an API change.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by eolivelli** [comment]
@codelipenghui @merlimat I think that we must fix this before releasing 2.11.
It is a new API that is broken.

The fix is simply, I hope that @cbornet will be able to send a PR soon
