### ISSUE TITLE
[Doc] Add list of 3rd party pulsar clients / make it findable

### ISSUE THREAD

**Issue by hpvd** [apache/pulsar#17113]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

There are some interesting 3rd party clients around.
e.g.

> **Pulsar Flex**
> for node.js
> Pulsar Flex is a modern Apache Pulsar client for Node.js, developed to be independent of C++. 
> https://github.com/ayeo-flex-org/pulsar-flex

But its hard to find them.

Being able to find them:
- pulsar users can take benefit from
- pulsar official community may learn from them
- maybe some are willing to donate to the project if there was some interaction between community
- ...

### Solution

would be great to add a list of them to the official pulsar doc, maybe just (like above for example)
- the name
- the language
- simple 1 sentence description (copied from the about section)
- link to repository

### Alternatives

not adding them and miss some opportunities to grow adaption and user base of pulsar

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by sOfekS** [comment]
They're all listed here.
https://pulsar.apache.org/docs/client-libraries/

**Comment by hpvd** [comment]
oh thats great! Of course I did search in the doc but didnt find them :-(

was expecting
- "3rd party" as own menu item or
- finding them in client type e.g. node, but there is only talked about the official client

![2022-08-16_13h32_58](https://user-images.githubusercontent.com/5681880/184870501-4d8bc8fe-2b82-4af7-812a-530960bf4eb2.png)

**Comment by hpvd** [comment]
if you are looking for something concrete, like a client for node.js you may not look in the overview section...

**Comment by tisonkun** [comment]
It's Pulsar's official website so it's unreasonable that we maintain the document of third-party clients.

All necessary information about third-party clients is listed under the overview page. It might be helpful to list third-party clients on a dedicated page and you're welcome to prepare a patch to preview.

**Comment by momo-jun** [comment]
Closed the issue since it‘s not planned. Feel free to reopen it when it's relevant.
