### ISSUE TITLE
[Bug][pulsar-client-admin-api] Topics.getInternalInfo() returns 500 for not existing topic

### ISSUE THREAD

**Issue by alpreu** [apache/pulsar#17121]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

macOS, master branch, commit bc68f02a

### Minimal reproduce step

1) Create a PulsarAdmin object
2) Use `admin.topics().getInternalInfo("this-topic-does-not-exist")

### What did you expect to see?

Response is HTTP 404 Not Found (as described in the docs)

### What did you see instead?

Response is HTTP 500 Internal Server Error

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by MarvinCai** [comment]
do you see any server log that can help diagnose?

**Comment by alpreu** [comment]
Unfortunately I cannot provide meaningful logs, I also am running on an M1 mac so I have to use the 'kezhenxu94/pulsar' image instead of the official one. I also found more inconsistencies in the admin API. I will close this ticket and create a larger one tracking all of the efforts.
