### ISSUE TITLE
[Doc] Fix the RabbitMQ connector docs

### ISSUE THREAD

**Issue by polyzos** [apache/pulsar#17133]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

inaccurate

### What is your suggestion?

![Screenshot 2022-08-16 at 8 27 04 PM](https://user-images.githubusercontent.com/23555517/185047364-670fd20c-a9d6-4160-998a-7fe9510252ac.png)

### Any reference?

requestedHeartbeat and exchangeName confgurations are mixed.
Also (empty string) isn't quite user friendly imho.
There are also a few configurations missing like exchangeType

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by momo-jun** [comment]
Hi @nicoloboschi, a quick check-in - did you have time to process this issue?

**Comment by momo-jun** [comment]
Unassigned @nicoloboschi since he has no plans on this issue.

**Comment by tisonkun** [comment]
I submit https://github.com/apache/pulsar-site/pull/517 to fix the incorrect issue for maintained versions.

For missing properties, I'll appreciate it if any further contribution to fix it up.
