### ISSUE TITLE
[feature request] C++ and Python support include message header size when check maxMessageSize.

### ISSUE THREAD

**Issue by shibd** [apache/pulsar#17188]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

[PIP 132 Include message header size when check maxMessageSize for non-batch message on the client side](https://github.com/apache/pulsar/issues/13591)

Current c++ the implementation also has this problem.

```c++
    const bool compressed = !canAddToBatch(msg);
    const auto payload =
        compressed ? applyCompression(uncompressedPayload, conf_.getCompressionType()) : uncompressedPayload;
    const auto compressedSize = static_cast<uint32_t>(payload.readableBytes());
    const auto maxMessageSize = static_cast<uint32_t>(ClientConnection::getMaxMessageSize());

    if (compressed && compressedSize > ClientConnection::getMaxMessageSize() && !chunkingEnabled_) {
        LOG_WARN(getName() << " - compressed Message payload size " << payload.readableBytes()
                           << " cannot exceed " << ClientConnection::getMaxMessageSize()
                           << " bytes unless chunking is enabled");
        handleFailedResult(ResultMessageTooBig);
        return;
    }

```

### Solution

Refer java client PR: https://github.com/apache/pulsar/pull/14007

### Anything else?

This is a PR to match the Java implementation. It is best to first prove whether the problem exists in the C++ client, and then solve it.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by coderzc** [comment]
Please assign it to me.
