### ISSUE TITLE
[Bug] Increase websocket connection timeout in apache pulsar

### ISSUE THREAD

**Issue by kaushalmadani** [apache/pulsar#17203]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

1. docker-compose = "3.4"
2. Apache Pulsar docker image = 2.6.0 , 2.9.3, 2.10.1

### Minimal reproduce step

I have a full description here:

https://stackoverflow.com/questions/73404101/increase-websocket-connection-timeout-in-apache-pulsar

### What did you expect to see?

Idle Websocket should be active until specified time in configuration.In my case it should be 36000000

### What did you see instead?

Idle websocket connection is being disconnected after 30 seconds that is default behaviour.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

Sorry I am not understanding configuration part or missing anything.

Thanks in advance.

**Comment by codelipenghui** [comment]
Thanks for raising the Github issue. We will take a look at the details soon.

**Comment by codelipenghui** [comment]
@kaushalmadani I have replied here https://stackoverflow.com/a/73453084/19798114

**Comment by kaushalmadani** [comment]
@codelipenghui Thanks for reply. Let me confirm this and will get back.

**Comment by kaushalmadani** [comment]
Hi @codelipenghui . I have replied on the same question.So it was from browser side.Need to handle this from either client side or need to send ping from producer this this consumer in specific interval. You can close this issue. Thanks for supprot.

**Comment by codelipenghui** [comment]
Thanks for the update, close the issue for now.
