### ISSUE TITLE
[Doc] Missing documentation for topic level policy settings

### ISSUE THREAD

**Issue by xiaogang-sn** [apache/pulsar#17274]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The current admin API doc page at https://pulsar.apache.org/docs/admin-api-topics does not include the features of [topic level policies](https://pulsar.apache.org/release-notes/versioned/pulsar-2.7.0/#topic-policy) introduced in Apache Pulsar 2.7.0.

They are [announced in the release post for 2.7.0](https://streamnative.io/blog/release/2020-12-25-pulsar-270/) as well.

### What is your suggestion?

Add them to the page at https://pulsar.apache.org/docs/admin-api-topics for the features under https://pulsar.apache.org/release-notes/versioned/pulsar-2.7.0/#topic-policy

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by xiaogang-sn** [comment]
It's interesting that the legacy admin CLI doc page has them under https://pulsar.apache.org/docs/pulsar-admin/#topics-1 but it's deprecated already. On the top of it as well as the page at https://pulsar.apache.org/docs/admin-api-topics, the [Pulsar Admin doc](https://pulsar.apache.org/tools/pulsar-admin/) is referred but the format there is not very friendly for end user consumption.

**Comment by momo-jun** [comment]
@xiaogang-sn as mentioned at the beginning of [this doc page](https://pulsar.apache.org/docs/admin-api-topics) - It only introduces some frequently used operations. For the latest and complete list of APIs, you can visit the corresponding docs. 

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/60642177/188409739-11bb11fc-d2ea-4481-ac52-57bb0db29882.png">

**Comment by xiaogang-sn** [comment]
Yes I noticed the [Pulsar Admin doc](https://pulsar.apache.org/tools/pulsar-admin/) site before. It's just not very friendly for end user to consume.
