### ISSUE TITLE
[ Doc ] I can't configure TLS vector to pulsar like vector to kafka

### ISSUE THREAD

**Issue by nguyenthanhlong98** [apache/pulsar#17294]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

Vector TLS pulsar
I can't configure TLS vector to pulsar like vector to kafka
![image](https://user-images.githubusercontent.com/45157728/186860893-ec81f596-4a55-45ab-a1a4-9cda868a9ae8.png)
Vector to pulsar 
![image](https://user-images.githubusercontent.com/45157728/186861269-5f34bf57-2439-4b3b-848d-8899418888f0.png)
Vector to kafka 

Config vector kafka 
![image](https://user-images.githubusercontent.com/45157728/186862589-1421722b-7118-45ff-bc35-12d26e34894a.png)

**Comment by nodece** [comment]
See https://pulsar.apache.org/docs/next/security-tls-transport and https://pulsar.apache.org/docs/next/security-tls-keystore.

**Comment by nguyenthanhlong98** [comment]
@nodece thank you but the problem I have is when configuring the TLS vector with pulsar it doesn't have the same TLS attribute as kafka

**Comment by nguyenthanhlong98** [comment]
@nodece kafka example has config vector
tls
tls.ca_file
tls.crt_file
tls.key_file
tls.key_pass
and for vector to pulsar there is no this attribute to config

**Comment by nodece** [comment]
tls.ca_file -> tlsTrustCertsFilePath
tls.crt_file -> tlsCertificateFilePath
tls.key_file -> tlsKeyFilePath
tls.key_pass -> not supported

See https://pulsar.apache.org/docs/next/security-tls-transport#configure-broker

If you want to learn the authentication and authorization, see https://pulsar.apache.org/docs/next/security-extending

**Comment by nguyenthanhlong98** [comment]
@nodece Thank you, but this config is only for pulsar client and broker of pulsar. I want config for vector and pulsar
https://vector.dev/docs/reference/configuration/sinks/pulsar/
Because in vector's doc there is no config tls for vector and pulsar so i don't know how to configure effectively
Thanks @nodece

**Comment by nodece** [comment]
Sorry, I don't know how to config the vector, but it looks like not supported the TLS.

**Comment by nguyenthanhlong98** [comment]
@nodece, yes, there are vectors in the doc that don't support tls, but i hope there is a configuration that can replace tls for example
Thanks

**Comment by nodece** [comment]
I suggest you can make an issue to request help on the vector repo. If someone in the Pulsar community is willing to support it, that would be great.

**Comment by nguyenthanhlong98** [comment]
@nodece, Hi nodece, I am configuring python basic auth credentials but it does not support config so do you have a link or doc to help me solve this problem

**Comment by nodece** [comment]
The Pulsar client doesn't support basic authentication, I submitted #17482 to support that.

**Comment by nguyenthanhlong98** [comment]
Ok, Thanks nodece, and the problem is still not solved

**Comment by nodece** [comment]
@nguyenthanhlong98 Sorry, should be Python client doesn't support basic authentication.

**Comment by nguyenthanhlong98** [comment]
@nodece, Hi nodece don't know if vector supports pulsar with token have you done it, if yes, can you confirm it for me
https://vector.dev/docs/reference/configuration/sinks/pulsar/#auth.token
vector support pulsar token

**Comment by nodece** [comment]
vector looks support token authentication.

**Comment by nguyenthanhlong98** [comment]
token and author basic just tokens and have you done this or you guessed it about using tokens with vectors

**Comment by nodece** [comment]
Guessed. The basic authentication and token authentication are different.

**Comment by tisonkun** [comment]
Closed as answered.

If you have further issue, welcome to open a question at https://github.com/apache/pulsar/discussions/categories/q-a.
