### ISSUE TITLE
[Doc] Fix the example for metadata store with etcd

### ISSUE THREAD

**Issue by xiaogang-sn** [apache/pulsar#17298]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

In the [current configuration example](https://pulsar.apache.org/docs/next/administration-metadata-store#use-etcd-as-metadata-store), it shows as follows.

```
metadataStoreUrl=etcd:my-etcd-1:2379,my-etcd-2:2379,my-etcd-3:2379
```

It will not work per https://github.com/apache/pulsar/pull/16309#issue-1290303315.

### What is your suggestion?

Change it to the format as below per https://github.com/apache/pulsar/pull/16309 with URL schema.

```
metadataStoreUrl=etcd:http://my-etcd-1:2379,http://my-etcd-2:2379,http://my-etcd-3:2379
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Pradhyumnakashyap** [comment]
Hi @sijie , 

I'm interested in updating this doc could you please assign this to me.

TIA,
Pradhyumna K R

**Comment by RobertIndie** [comment]
> Hi @sijie ,
> 
> I'm interested in updating this doc could you please assign this to me.
> 
> TIA, Pradhyumna K R

Thanks. I have assigned it to you.

**Comment by Pradhyumnakashyap** [comment]
Hi @RobertIndie , 

Thanks for assigning this to me and my PR got merged : https://github.com/apache/pulsar/pull/17341
