### ISSUE TITLE
Turn on syntax highlight for all related programming languages

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#17307]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

This can be a trivial config change on the [docusaurus.config.js](https://github.com/apache/pulsar-site/blob/1d837ec3bda5c6bad69200fb9422a79d4298860e/site2/website-next/docusaurus.config.js#L355) file:

```js
    prism: {
      // theme: lightCodeTheme,
      // darkTheme: darkCodeTheme,
      theme: require("prism-react-renderer/themes/dracula"),
      additionalLanguages: ["powershell", "java", "go", "c", "cpp", "python"],
    },
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by dave2wave** [comment]
Please submit a PR

**Comment by tisonkun** [comment]
See also https://github.com/apache/pulsar-site/pull/187.

**Comment by tisonkun** [comment]
See also https://github.com/apache/pulsar/pull/17342 for the main repo part.

Thanks for your reminder @dave2wave!
