### ISSUE TITLE
[Doc] Remove first and last newline in code block

### ISSUE THREAD

**Issue by labuladong** [apache/pulsar#17384]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

Every code block in [pulsar document](https://pulsar.apache.org/docs/) has redundant newlines:

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/37220920/187814413-695a34cc-42de-4e5d-b1dd-779f650daa91.png">

If I click the copy button, `\n` was copied as well, which is inconvenient to change args and may run commands unexpectedly because of the tailing `\n`:

![image](https://user-images.githubusercontent.com/37220920/187814103-afbfe063-1105-43ee-bda7-d8080df01000.png)

### What is your suggestion?

Trim all redundant newlines of code blocks like this:

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/37220920/187815034-da01d19c-84f2-4818-83f5-13e4fa9f40e1.png">

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Make sense. I'm doing this when touching related documents. I don't make a patch to apply it globally yet, though. If you have some time to do it and we get two or more committers' approval, we can try to take the move. Otherwise, it's quite easily to conflict with continuous contributions.

**Comment by tisonkun** [comment]
cc @Anonymitaet @momo-jun @Huanli-Meng

**Comment by momo-jun** [comment]
I'm working on this. https://github.com/apache/pulsar/pull/17355

**Comment by labuladong** [comment]
> I've already been working on this: #17355.

Seems great, thanks.  I'll close this issue.
