### ISSUE TITLE
[Doc] Simplify the get started page for local cluster

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#17409]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The current [Get Started page for local cluster](https://pulsar.apache.org/docs/next/getting-started-standalone) is too much redundant than it should be. Most users want a short happy path to boot a Pulsar cluster and play with it by producing and consuming messages. Although, the current page begins the "Start Pulsar standalone" at almost 2/3 below the whole page.

1. We don't have to teach users to install JDK on M1. They can Google it, and there're a large portion of users who don't use M1. At least troubleshooting should go at last.
2. We don't have to mention how to install connectors or offloaders, it's unused on the quickstart page. We can mention them on the overview/quickstart page of connectors and offloaders.
3. We don't have to talk in detail about the layout of the binary release directory. It's intuitive and can be read from their name.
4. Currently, if you go through the page, you won't get the message consumed as it said. Because we don't even produce any message yet. Also, Pulsar CLI has some significant arguments to play with basic messaging, like how to consume from Earliest, how to keep consuming messaging instead of consuming only one message, and how to produce multiple messages in one turn. I have a draft to rewrite the section.

### What is your suggestion?

I'll make a draft patch to cover all of the topics listed above in a few days.

cc @merlimat @Anonymitaet @momo-jun @lhotari @codelipenghui 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by DaveDuggins** [comment]
@tisonkun, I was preparing to edit these docs today.  Thank you very much for your help! I'll work together with you and Yu to improve the documentation. I'll wait until you submit your draft to take any action.

**Comment by tisonkun** [comment]
@Anonymitaet Thanks for your information! I'll try to integrate your comment, submit the patch and answer which ones I accepted.

@DaveDuggins Good to know :) Looking forward to co-work on the content.

FYI - the estimate is by the next Monday (20220905).

**Comment by tisonkun** [comment]
@Anonymitaet Patch at https://github.com/apache/pulsar/pull/17475. For your suggestions:

> Next steps (It provides hints and related useful resources). For example,

Good point! Addressed at https://github.com/apache/pulsar/pull/17475/commits/e1bd5cece9c13ef2f0d84fe938b394a5077116e2.

> Binary release info - If so, suggest keeping this part

Accepted. Addressed at https://github.com/apache/pulsar/pull/17475/commits/e758f05411fc75f84a396eebe2c461e1e706cc4c.

> FAQ

"how to install JDK on M1" is not suitable to document on the Get Started page. Imagine that you don't tell users how to buy a computer. It's far away from Pulsar topics. Users can resolve it with Google, StackOverflow, etc.

For the FAQ topic itself, I think we can adopt both of them according to the concrete situation. Since it's unrelated to this patch, I'd like to skip the decision but prompt when we meet a real issue.
