### ISSUE TITLE
[Doc] Support switching versions on the same topic page

### ISSUE THREAD

**Issue by momo-jun** [apache/pulsar#17415]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

To change the doc version, there are only two ways available:
1. Manually modify the version number in the URL, which is not intuitive for non-developers.
2. Select another version on the `Version` page, but this redirects users to the home page and requires them to address the topic again, which is troublesome.

Also got a user feedback as below:
> One painful experience I have about pulsar doc website: as a heavy google user, I search pulsar related question from [google.com](http://google.com/). Here is my scenario:
> 1. in [google.com](http://google.com/) search box, I type “apache pulsar geo-replication” and then click on the result link pointing to apache pulsar doc site
> 2. I found geo-replication page, but it is version 2.x ( x is not what I looking for).
> 3. I click the version drop down and pick 2.10.  
> 4. it link to 2.10 doc home page !!!?????

### What is your suggestion?

Add the ability to let users switch versions on the same topic page.

### Any reference?

https://docusaurus.io/docs/2.0.0-rc.1/installation

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by momo-jun** [comment]
@urfreespace Can you pls take a look and evaluate? 
CC @Anonymitaet The label may need an update to `doc`.

**Comment by urfreespace** [comment]
https://github.com/apache/pulsar-site/pull/201

**Comment by urfreespace** [comment]
https://github.com/apache/pulsar-site/pull/202
