### ISSUE TITLE
Unusual jar naming strategy

### ISSUE THREAD

**Issue by adrian-tarau** [apache/pulsar#17412]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

The naming of the Pulsar jars is a bit unusual. If the project provides shaded JARs, they are named _*-shaded.jar_, and the original JAR is left as is. Most of the time, projects will include the non-shaded jar since it is not desired to duplicate another 20MB of dependencies. There are exceptions when there are version conflicts, and that's when you include the shared jar.

### Solution

Add a classifier (shaded) and leave the original file name as is.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Is it a big deal about the name? Every project can has its own preference and if only it doesn't become a trouble for some integrations, it looks neutral to me to use `pulsar-client` as the shaded version and `pulsar-client-original` as the slim version.

If we just change `pulsar-client` to the slim version, it will shock users who already use it as a shaded version. This is a user-facing interface change, but I don't see some reasonable advantages to doing so.

**Comment by adrian-tarau** [comment]
I would not say it is a big deal ... it's just unusual. Honestly, I used hundreds of libraries, and none of them have this file name policy in reverse. The shaded JAR has a different name, and the original JAR is based on the artifact identifier.

**Comment by Shoothzj** [comment]
I agree it's unusual. But that's a kind of breaking change. I don't think we have enough motivation to change the name.

**Comment by tisonkun** [comment]
Closed as won't do.
