### ISSUE TITLE
[Doc] Create an alias with version number to latest stable version

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#17438]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

You can find docs for `2.9.x` at: https://pulsar.apache.org/docs/2.9.x, for `2.10.1` at https://pulsar.apache.org/docs/2.10.1, but the latest stable version `2.10.x` only lives at `https://pulsar.apache.org/docs`, not at `https://pulsar.apache.org/docs/2.10.x`.

This becomes a serious issue that users of the latest stable version can only share links to an unstable prefix https://pulsar.apache.org/docs, so that the result can change or the link can be broken later.

### What is your suggestion?

We should generate a stable link for the latest stable version also.

cc @Anonymitaet @urfreespace 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
@tisonkun thanks for reporting this issue! 
It makes sense to update `https://pulsar.apache.org/docs` to `https://pulsar.apache.org/docs/2.10.x` for 2.10.x doc URL. @momo-jun thoughts?

**Comment by momo-jun** [comment]
I don't have any objection to this request. CC @urfreespace.

In my understanding, `https://pulsar.apache.org/docs` always represents the latest stable doc, which is version-neutral and good for doc iteration. When 2.10.x became an older version, it will have the URL `https://pulsar.apache.org/docs/2.10.x` then.

**Comment by tisonkun** [comment]
@momo-jun yes. Please be aware that I'm _not_ proposing **remove** `docs` and adding `docs/2.10.x`, but **barely adding an alias**.

Supposed you're a user using 2.10.x, you share a link to the latest doc with your colleague, then 2.11.0 is released, and the link result changes.

**Comment by momo-jun** [comment]
@tisonkun I understand your concern. But I do think it somehow has a positive effect by sharing a version-neutral doc link, since we are continuously improving the existing content. The links pointing to the latest stable version can enable users to always look at a better version of the doc. If there are new features out of their reach in the new versions, they can switch doc versions then or even consider an upgrade.

**Comment by tisonkun** [comment]
See https://github.com/apache/pulsar/issues/18026#issuecomment-1288331662 and https://github.com/apache/pulsar/issues/18026#issuecomment-1288334832.

@urfreespace you may take a look and I'm gonna to work on it in the next month if there is no objection and no progress :)

**Comment by urfreespace** [comment]
> See [#18026 (comment)](https://github.com/apache/pulsar/issues/18026#issuecomment-1288331662) and [#18026 (comment)](https://github.com/apache/pulsar/issues/18026#issuecomment-1288334832).
> 
> @urfreespace you may take a look and I'm gonna to work on it in the next month if there is no objection and no progress :)

I know what you mean, I have no objection
