### ISSUE TITLE
[Doc] [Website] Rest API page broker

### ISSUE THREAD

**Issue by MarvinCai** [apache/pulsar#17460]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

https://pulsar.apache.org/admin-rest-api/#/ is broken
<img width="1814" alt="image" src="https://user-images.githubusercontent.com/13480084/188345441-b9ecaf8b-b26e-43cb-872b-44dab10b4c9c.png">

### What is your suggestion?

N/A

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by labuladong** [comment]
Seems it's our network issue?

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/37220920/188346497-ff0e1fe0-e311-49ef-956d-6750667ff652.png">

**Comment by MarvinCai** [comment]
weird, will let one more user to confirm

**Comment by momo-jun** [comment]
The link https://pulsar.apache.org/admin-rest-api/#/ works well on my side.

**Comment by MarvinCai** [comment]
ok, then it might be issue with my browser or network, closing it
