### ISSUE TITLE
[Doc] Rename "Admin API" to "Admin Interfaces"

### ISSUE THREAD

**Issue by xiaogang-sn** [apache/pulsar#17473]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

On the left navigation bar, "Admin API" is a bit misleading. People tend to take it as "Rest API" or similar stuff while most of the time they are just looking for admin commands. 

### What is your suggestion?

Change it to "Admin Interfaces" which may cover both API and CLI although CLI is just a wrapper of API.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
@xiaogang-sn thanks for your suggestion! I've double-checked the word usage with the engineering team (+@codelipenghui) from the technical side. It's rare/inaccurate to use "Admin Interfaces" to describe admin APIs. The team suggests replacing "Admin API" with "Admin (API + CLI)" to include both API and CLI.
