### ISSUE TITLE
[Bug][Java client] main thread won't exit if not close pulsar client

### ISSUE THREAD

**Issue by labuladong** [apache/pulsar#17480]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

macOS 12.5.1 

Pulsar 2.10.1

Pulsar Java client 2.10.1

### Minimal reproduce step

Run this snippet:

```java
public class Main {
    public static void main(String[] args) throws PulsarClientException {
        PulsarClient client = PulsarClient.builder()
                .serviceUrl("pulsar://localhost:6650")
                .build();

        System.out.println("hello world"); // print successfully
        // without client.close(), `main` will be hanging, never exit
    }
}
```

### What did you expect to see?

Print `hello world` then exit normally.

### What did you see instead?

Print `hello world` but never exit.

### Anything else?

I know I should always `close` the client manually. But if I don't close it, is hanging to be the expected behavior?

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by labuladong** [comment]
We (+ @yaalsn) discuss this, seems that netty has a shutdown hook to prevent client exit.

**Comment by nicoloboschi** [comment]
@labuladong if you close the Pulsar client (`client.close()`) the process exits?

**Comment by lhotari** [comment]
> We (+ @yaalsn) discuss this, seems that netty has a shutdown hook to prevent client exit.

Live non-daemon threads are a common reason why normal shutdown doesn't happen in a Java application.

The [javadoc of java.lang.Thread](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html):

>  When a Java Virtual Machine starts up, there is usually a single non-daemon thread (which typically calls the method named main of some designated class). The Java Virtual Machine continues to execute threads until either of the following occurs:
> 
> * The exit method of class Runtime has been called and the security manager has permitted the exit operation to take place.
> * All threads that are not daemon threads have died, either by returning from the call to the run method or by throwing an exception that propagates beyond the run method.

I believe that Pulsar client creates threads that are non-daemon threads. This might be intentional. 
I assume that it's better to handle the shutdown in a controlled way in any case. 
A simple fix to your problem is to add a shutdown hook that calls `client.close()`. 

@labuladong What is your actual use case? Could you share more of the scenario that you have in mind?

**Comment by labuladong** [comment]
> @labuladong if you close the Pulsar client (`client.close()`) the process exits?

Yes, it will.

**Comment by labuladong** [comment]
@lhotari Hi, I'm just curious about how to exit even if missing `client.close()`. Now I figured it out from your answer. Thanks a lot!
