### ISSUE TITLE
[Doc] C++ Client API docs are incompleted

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#17498]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

If you check https://pulsar.apache.org/api/cpp/

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/18818196/188773010-c48cc025-b093-4ba8-9069-d8ccc69072a2.png">

There's no stable release after 2.5.0. All are snapshots and don't distinguish by patch versions.

### What is your suggestion?

Figure out the reason, regenerate the content, and fix references to these pages.

cc @urfreespace @BewareMyPower 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by BewareMyPower** [comment]
I realized this issue as well. The release process doesn't include the release of C++ docs.

**Comment by tisonkun** [comment]
cc @BewareMyPower @Anonymitaet @merlimat @michaeljmarshall 

May I ask how we generate C++ API docs now? I don't find an entry talking about it...

**Comment by BewareMyPower** [comment]
@tisonkun https://github.com/apache/pulsar-client-cpp/pull/103 will fix the doxygen generation.
