### ISSUE TITLE
[Doc] Add prompt to users who are reading old version doc

### ISSUE THREAD

**Issue by labuladong** [apache/pulsar#17501]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

There is no prompt if users read the old version document.

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/37220920/188780881-7a5221ed-1795-41a6-bfbc-d542c8bc1358.png">

Users may be confused if they read the wrong version doc.

### What is your suggestion?

Remind users that this version is not the newest, like this:

![image](https://user-images.githubusercontent.com/37220920/188781284-0a354c86-8b17-41b6-9b9f-fa93dd0231a4.png)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by labuladong** [comment]
cc @tisonkun  @Anonymitaet @momo-jun @urfreespace

**Comment by Anonymitaet** [comment]
Thanks! @labuladong 
This feature is supported by Docusaurus. Info like below can be added.

<img width="1697" alt="image" src="https://user-images.githubusercontent.com/50226895/188792714-424312cd-ffc1-43b5-93e5-eb40667f204a.png">

**Comment by tisonkun** [comment]
+1 Also refer to how Flink displays this infohttps://nightlies.apache.org/flink/flink-docs-release-1.12/:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/18818196/188793273-32cc40db-7c33-4754-b847-59afc7c380a5.png">

**Comment by urfreespace** [comment]
Done, screenshot here:
![image](https://user-images.githubusercontent.com/76024046/189021261-50b9f509-aee8-4a1f-adbd-36d0d8ac08df.png)

**Comment by tisonkun** [comment]
@urfreespace Thanks! I added some comments after merge for following improves :)

This issue can be closed as completed, though.

**Comment by labuladong** [comment]
@urfreespace Looks great, thanks! I'll close this issue.

**Comment by momo-jun** [comment]
@urfreespace thanks for the quick implementation!
Only one concern on the wording - actually, we maintain the last four minor versions, e.g., 2.8.x, 2.9.x, and 2.10.x. Shall we differentiate that in the prompt? @Anonymitaet any thoughts?

**Comment by Anonymitaet** [comment]
@momo-jun that's already done, you can check the website

2.8.x
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/50226895/189058748-9fa0b181-e8d2-4534-a85c-345c15745a99.png">

2.9.x
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/50226895/189058800-8680f532-b80d-4f1f-a9f9-c808d3ac79a4.png">

2.10.x
No tip

**Comment by Anonymitaet** [comment]
@urfreespace thanks for your contribution!

One question: 
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/50226895/189060046-0a51ec92-0d48-44c5-ae0e-d5b2ff465866.png">

Reasons: https://github.com/apache/pulsar-site/pull/176#issuecomment-1239013191

**Comment by labuladong** [comment]
I found that only versions in sidebar have the banner, but many old versions in [other version page](https://pulsar.apache.org/versions) do not have the banner. For example [Pulsar V2.6.3](https://pulsar.apache.org/docs/2.6.3/):

![image](https://user-images.githubusercontent.com/37220920/190555323-42ad9df8-bd65-4a1e-af82-0696ca90b590.png)

Reopen this issue.

**Comment by Anonymitaet** [comment]
@labuladong https://github.com/apache/pulsar-site/pull/207#issuecomment-1250665086 is the proposed solution

**Comment by urfreespace** [comment]
@labuladong fixed; pls close this issue after you checked

**Comment by labuladong** [comment]
Thanks for your work, it looks good to me. I'll close this issue : )
