### ISSUE TITLE
[website][feat] Pulsar All Releases Page

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#17514]
### Discussed in https://github.com/apache/pulsar/discussions/17310

<div type='discussions-op-text'>

<sup>Originally posted by **Anonymitaet** August 27, 2022</sup>
Hi team,

1. How about providing more useful content to the [Pulsar Release Notes > All Releases](https://pulsar.apache.org/release-notes/) page as [below](https://docs.google.com/spreadsheets/d/1XHmzno-1kbHvPp7eogri8XAiShH-EgpEG40svte-qxM/edit#gid=1677243891)?

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/50226895/187336497-95a68232-36e5-4fc7-a0c0-7b3788ba78a6.png">

2. This table should be updated automatically. 

Info | Info can be pulled from
---|---
Release note URL | https://pulsar.apache.org/release-notes/
Release blogs name and URL | https://pulsar.apache.org/blog
Documentation URL | [Versions page](https://pulsar.apache.org/versions), so this page can be removed since the info is consolidated into the `All Releases` page.
Release date </br> Release manager| https://github.com/apache/pulsar/releases.

</div>

**Comment by Anonymitaet** [comment]
@SignorMercurio will help implement it, thank you!

cc @urfreespace

**Comment by SignorMercurio** [comment]
Should we close this issue as it's implemented in apache/pulsar-site#227?

**Comment by urfreespace** [comment]
> 

@Anonymitaet

**Comment by Anonymitaet** [comment]
I'll close this once the new feature is stable and the [workflow](https://docs.google.com/document/d/1cwNkBefKyV6OPbEXnUrcCdVZi0i2BezqL6vAL7VqVC0/edit?pli=1#heading=h.9j49rsvsbimy) is finalized.
