### ISSUE TITLE
[Transactions] Add pulsar-admin commands to lookup Coordinators

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#17513]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Actually there is no way using pulsar-admin to get the list of coordinators and to know which broker is running them.

I am using this command
`bin/pulsar-admin topics partitioned-lookup pulsar/system/transaction_coordinator_assign`

There are a few problems:
- it is basically impossible to users to know that you can do it (I had to look at Pulsar code)
- it returns information about only topics that are currently owned

Also I have observed that listing the topics inside `pulsar/system` returns an empty list even while disabling authn/authz
This should be unblocked in order to allow troubleshooting

### Solution

Add a new command 
pulsar-admin transactions list-coordinators

the command should list:
- the coordinator
- the coordinator id (used by other commands)
- the broker that is running the service

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by michaeljmarshall** [comment]
What kind of authorization will ` pulsar-admin transactions list-coordinators` require?
