### ISSUE TITLE
[Doc] There are many broken links in Pulsar IO chapter

### ISSUE THREAD

**Issue by labuladong** [apache/pulsar#17555]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

When I read the Pulsar IO document,  I found many links got 404 errors.

### What is your suggestion?

Find out and fix them.

### Any reference?

For example:

https://pulsar.apache.org/docs/io-overview/#set

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/37220920/189262876-6c597207-d66f-4032-a777-2a4538f4cfa2.png">

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Set cross-reference to https://github.com/apache/pulsar/issues/17495. You can comment there if find any further related issues. We can play a bash to handle them :)

**Comment by labuladong** [comment]
@tisonkun Great, thanks!
