### ISSUE TITLE
[CI] Replace `runs-on: ubuntu-latest` with `runs-on: ubuntu-20.04` in GitHub Action workflows

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#17560]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

The workflows currently contained mixed usage of `runs-on: ubuntu-latest` and `runs-on: ubuntu-20.04`.
It's better to be consistent and use `runs-on: ubuntu-20.04` for all cases. It's better to be able to control when we switch to use `ubuntu-22.04` image instead of letting GitHub decide.
For macOS, we should replace `macos-latest` with `macos-11` for the similar reason.

Available image definitions are listed at https://github.com/actions/runner-images#available-images

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Sounds good! I just do the same thing in incubator-kvrocks days before.
