### ISSUE TITLE
[Doc] Authentication documentation mismatch / outdated

### ISSUE THREAD

**Issue by alpreu** [apache/pulsar#17561]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The documentation regarding authentication methods is mismatched/outdated.

On the security overview page, it lists most providers (it is missing SASL though):
https://pulsar.apache.org/docs/2.10.1/security-overview/#authentication-providers

On the java client page, it lists only three providers:
https://pulsar.apache.org/docs/2.10.1/client-libraries-java/#authentication

### What is your suggestion?

If you go to the security overview page and select an authentication method you will reach a page that also contains a code configuration example:
https://pulsar.apache.org/docs/2.10.1/security-tls-authentication/#java-client

I think it would be good to remove the list on the java client page and just link to the security page. 
Another option would be to update the java client page (but I think it will go out of sync again at some point if we maintain it in two places)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by momo-jun** [comment]
@alpreu thanks for raising this up. I will follow up with the updates.
