### ISSUE TITLE
[CI] Change branch workflows so that they are triggered only upon request or scheduled

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#17567]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

We have many active branches and many commits are pushed to these branches. master branch gets commits by merging PRs and in most cases, commits are pushed by cherry-picking commits from master branch to maintenance branches (branch-2.11, branch-2.10, branch-2.9, branch-2.8 and branch-2.7).
In most cases, nobody pays attention to the results of individual builds for commits pushed to maintenance branches.

Therefore, it would be a way to save CI resources if CI builds are only available upon request or in a scheduled manner.

### Solution

GitHub Actions has a feature for manually triggering the workflow. Documentation:
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#defining-inputs-for-manually-triggered-workflows
workflow_dispatch is the event type. Docs for workflow_dispatch 
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
The GitHub UI lets the user choose the branch. The minimum way to add support for manual triggering is adding `on: workflow_dispatch` to the workflow.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
In addition, master could have a scheduled workflow to run in the similar way as the existing "CI - Maven Dependency Cache Update" workflow. That workflow after having a scheduled workflow for master branch.

**Comment by nicoloboschi** [comment]
We can set the manual trigger for branch-2.11. For branch-2.10 and previous, the workflow Pulsar CI doesn't exist. A good solution would be to:
- Remove the post-commit trigger for all the jobs in branch-2.10 (and prev) branches. When the release manager needs to validate the branch, it has to open a pull. It's not very common that we open pulls against release branches so it will reduce the CI loads a lot.
- For branch-2.11 (and future release branches) we can do the same and additionally add the workflow_dispatch trigger.

**Comment by lhotari** [comment]
@nicoloboschi makes sense. triggering 25+ workflows in branch-2.10 (and before) in the UI wouldn't be very usable.
