### ISSUE TITLE
slowly-test: ClusterMetadataSetupTest

### ISSUE THREAD

**Issue by poorbarcode** [apache/pulsar#17621]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

This test run took more than 5 minutes

![截屏2022-09-14 01 03 42](https://user-images.githubusercontent.com/25195800/189963148-59cb6d08-3b83-4459-9314-b9c41ce8c561.png)

https://github.com/apache/pulsar/actions/runs/3023647567/jobs/4867728935

### Solution

Make the test run faster

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by coderzc** [comment]
I push a PR(#17627) to improve it.
