### ISSUE TITLE
slowly-test: org.apache.pulsar.client.api.SimpleSchemaTest

### ISSUE THREAD

**Issue by poorbarcode** [apache/pulsar#17644]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

This test run took more than 5 minutes

![截屏2022-09-14 15 51 23](https://user-images.githubusercontent.com/25195800/190094540-f03fef2f-4958-44b9-bc01-628e71729f5d.png)

https://github.com/apache/pulsar/actions/runs/3038983441/jobs/4915130539

### Solution

Make the test run faster

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
@poorbarcode could you batch these slow-tests with a tracking issue like https://github.com/pingcap/tidb/issues/26022 so that we have a global comment-able view about the situation?

**Comment by poorbarcode** [comment]
Hi @tisonkun 

> could you batch these slow-tests with a tracking issue like [pingcap/tidb#26022](https://github.com/pingcap/tidb/issues/26022) so that we have a global comment-able view about the situation?

I have created the tracking issue: #17657
