### ISSUE TITLE
Tracking issue for slow tests 

### ISSUE THREAD

**Issue by poorbarcode** [apache/pulsar#17657]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

This issue tracks efforts to optimize slow testing(which took more than 5 minutes), focusing on unit tests.

### Slowly Test

- [x] #17644
- [x] #17643
  - https://github.com/apache/pulsar/pull/17887
- [x] #17642
- [x] #17641
- [x] #17640
- [x] #17639
- [x] #17637
- [x] #17636 
- [x] #17635 
- [x] #17634 
  - https://github.com/apache/pulsar/pull/17887 
- [x] #17623 
- [x] #17622 
  - https://github.com/apache/pulsar/pull/17875 
- [x] #17621

**Comment by lhotari** [comment]
@poorbarcode This is a really good initiative. Thanks for starting this!

**Comment by lhotari** [comment]
There are some memory leaks in tests that cause slow down. 
Pulsar CI collects a heap dump when an OOM happens. There are 2 recent examples of this:
#17714 and #17655

When there's a memory leak, it can slow down tests when there's constant GCs happening due to very limited available heap.

**Comment by codelipenghui** [comment]
@poorbarcode It looks like all the tests that took more than 5 min are fixed. Do you want to recheck the CI for the time-consuming test？

**Comment by tisonkun** [comment]
All subtasks are fixed. Closed as done.

If you find more slow tests after a recheck, feel free to reopen the issue. Or prefer to open a new issue to another turn.
