### ISSUE TITLE
Broker metrics on `/metrics/` not `/metrics` [Doc]

### ISSUE THREAD

**Issue by oliverisaac** [apache/pulsar#17678]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The broker metrics are behind `/metrics/` _not_ `/metrics` as documented. (Not the trailing slash.)

### What is your suggestion?

Update docs (for all versions) to reflect the trailing slash.

Would also be nice to fix this so that `/metrics` and `/metrics/` both work.

### Any reference?

https://pulsar.apache.org/docs/reference-metrics/#broker

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by momo-jun** [comment]
@tjiuming can you pls take a look at this issue?

**Comment by tisonkun** [comment]
Generally, the trailing slash should be able to omit. It may not a doc issue but less than awesome software experience :)

**Comment by tisonkun** [comment]
@oliverisaac I try `localhost:8080/metrics` and the browser automatically directs me to http://localhost:8080/metrics and returns the correct result. This manner should be fine to me.

Do you encounter a case that 404 or other critical error when open `/metrics`?

**Comment by oliverisaac** [comment]
Ah, yes! That endpoint returns a 302 and it didn't occur to me to try the `curl -L`! 🤦‍♂️ 

> It may not a doc issue but less than awesome software experience 

I'm going to close this issue as, technically, `/metrics` works even though the metrics are "actaully" at `/metrics/`. On the other hand, having to do `curl -L` instead of just a `curl` probably falls under the "less than awesome software experience" umbrella. 🤷‍♂️ 

Thanks for the quick response!
