### ISSUE TITLE
[Bug] NoClassDefFoundError when using the pulsar admin tools

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#17683]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

86ea31b2409a7b62624278dc133d443ca62ffb76

### Minimal reproduce step

* Build the project
* run `bin/pulsar-admin`

### What did you expect to see?

Able to run

### What did you see instead?

➜  pulsar git:(master) ✗ bin/pulsar-admin
Error: Unable to initialize main class org.apache.pulsar.admin.cli.PulsarAdminTool
Caused by: java.lang.NoClassDefFoundError: org/apache/pulsar/admin/cli/extensions/CommandExecutionContext

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by nicoloboschi** [comment]
@RobertIndie I'm not able to reproduce it from the current master.
