### ISSUE TITLE
Duplicate data stored in loadbalance/brokers/

### ISSUE THREAD

**Issue by thetumbled** [apache/pulsar#17738]
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

i find that method getBundleStats return member lastStats, causing  duplicate data stored in ZK when Jackson serializing LocalBrokerData, and the size of data in lastStats is pretty large, consisting of metrics data concerning to every bundles that belong to this broker, and i find that the method LocalBrokerData.getBundleStats is not used anywhere, i wonder whether we can deduplicate that. 

org.apache.pulsar.policies.data.loadbalancer.LocalBrokerData#getBundleStats
<img width="488" alt="image" src="https://user-images.githubusercontent.com/52550727/191214108-a77c09d9-59d2-4e13-85a2-b60aa622f425.png">

we could verify this by retrieving data from ZK.
<img width="420" alt="image" src="https://user-images.githubusercontent.com/52550727/197128529-2d43ecb3-3f8c-4ec3-a843-2c6eec90534e.png">
<img width="417" alt="image" src="https://user-images.githubusercontent.com/52550727/197128586-f55c9f92-abbb-4869-b4d2-94942605513e.png">

### Solution

do not serialize field bundleStats.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by mattisonchao** [comment]
Thanks a lot for your contribution.

**Comment by thetumbled** [comment]
> Thanks a lot for your contribution.

PTAL
