### ISSUE TITLE
[Bug] Cannot get replicatedFrom in EntryFilter

### ISSUE THREAD

**Issue by lwclover** [apache/pulsar#17731]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

linux cenos
pulsar version 2.10.1

### Minimal reproduce step

Configure topic level Geo Replicator bidirectional synchronization.
Implement Entryfilter below:
```
    @Override
    public FilterResult filterEntry(Entry entry, FilterContext context) {
        MessageMetadata messageMetaData = context.getMsgMetadata();
        if(!messageMetaData.hasReplicatedFrom()) {
            LOG.info("VDCPreferred has no replicatedFrom field, accept");
        }
        LOG.info("VDCPreferred ReplicatedFrom {}, ReplicateTosList {}", messageMetaData.hasReplicatedFrom() ? messageMetaData.getReplicatedFrom() : "none", messageMetaData.getReplicateTosList());
        List<KeyValue> keyValues = messageMetaData.getPropertiesList();
        for(KeyValue kv : keyValues) {
            LOG.info("VDCPreferred key {}, value {}", kv.getKey(), kv.getValue());
        }
        return FilterResult.ACCEPT;
    }
```

### What did you expect to see?

I want get replicatedFrom in EntryFilter.

### What did you see instead?

Cannot get replicatedFrom in EntryFilter,

see log:
`VDCPreferred has no replicatedFrom field, accept
`

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by eolivelli** [comment]
Do you know why is this possible?
The filter has access to low level data.

**Comment by lwclover** [comment]
> 
Thank you for your reply.

Pulsar native protocol has no problem. I test the case Using kop.
I read the code of kop, it does not support entryfilters now.
