### ISSUE TITLE
Kafka Source: add option to copy Kafka Headers to Pulsar properties

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#17760]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Currently in the Kafka Source we are not copyng the headers  but only the payload.
I would be great to have all Kafka Headers and maybe some additional metadata, like the original topic, partition, offset....

### Solution

Add a flag in the Kafka Source 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by aymkhalil** [comment]
I'm working on it.
