### ISSUE TITLE
[Doc] Deploy Docker: outdated

### ISSUE THREAD

**Issue by hpvd** [apache/pulsar#17774]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

in https://github.com/apache/pulsar/issues/14092#issuecomment-1253650641

> > Do we have to make any changes in text or link targets in doc on https://pulsar.apache.org/docs/next/deploy-docker ?
> 
> That document looks very much outdated. It doesn't make sense to me.

### What is your suggestion?

update

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
@hpvd I think this issue can be an instance of #17495 and all these related documents should be considered in a rewrite on the topic "get started in containers (cluster)":

* https://pulsar.apache.org/docs/next/deploy-docker
* https://pulsar.apache.org/docs/next/getting-started-helm
* https://pulsar.apache.org/docs/next/helm-install
* https://pulsar.apache.org/docs/next/getting-started-docker
* https://pulsar.apache.org/docs/next/deploy-kubernetes

Perhaps with some redirections and content merges.

**Comment by liangyepianzhou** [comment]
>@hpvd I think this issue can be an instance of https://github.com/apache/pulsar/issues/17495 and all these related documents should be considered in a rewrite on the topic "get started in containers (cluster)":

@tisonkun I think your mind is 'deployment in containers(cluster) '

**Comment by momo-jun** [comment]
Closed the issue since the reported topic has been updated and refreshed in #17853. 
Regarding the doc improvements for Kubernetes deployments, I drafted https://github.com/apache/pulsar/pull/18015 to follow up.  //cc @tisonkun
