### ISSUE TITLE
[Bug] python function does not respect `--retain-ordering` flag

### ISSUE THREAD

**Issue by dionjansen** [apache/pulsar#17776]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Pulsar version: 2.10.1

### Minimal reproduce step

Follow [Pulsar functions quickstart](https://github.com/apache/pulsar/blob/master/site2/website/versioned_docs/version-2.3.0/functions-quickstart.md#writing-and-running-a-new-function). I'm using Docker to run Pulsar standalone:

### 1. Run pulsar standalone

First, create a new Python file:

```bash
$ touch fn.py
```

In that file, add the following:

```python
def process(input: bytes):
    if "B" in str(input):
        raise Exception("Fail on 'B'")
    return input
```

This function will raise an exception when the message context text contains the character `"B"`

### 2. Start the function with `--retain-ordering` flag

```bash
$ docker exec -it pulsar bash -c "/pulsar/bin/pulsar-admin functions localrun \
  --py '/pulsar/fn.py' \
  --classname fn \
  --inputs persistent://public/default/input \
  --output persistent://public/default/output \
  --tenant public \
  --namespace default \
  --subs-name 'test' \
  --retain-ordering \
  --name fn"
```

### 3. Consume output topic

```bash
$ docker exec -it pulsar bash -c "bin/pulsar-client consume \
  persistent://public/default/output \
  --subscription-name test \
  --num-messages 0"
```

### 3. Produce messages to the source topic containing `"B"`

```bash
$ docker exec -it pulsar bash -c "/pulsar/bin/pulsar-client produce \
  persistent://public/default/input \
  --messages 'A,B,C,D,E,F'"
```

### What did you expect to see?

The consumer in step (3) should output messages in the order that they were provided (so `A` and nothing more)

### What did you see instead?

It continues processing messages after `B` (`C`, `D` ..) and thus does not retain the order anymore:

```bash
----- got message -----
key:[null], properties:[__pfn_input_msg_id__=CAoQACAA, __pfn_input_topic__=persistent://public/default/input], content:A
----- got message -----
key:[null], properties:[__pfn_input_msg_id__=CAoQAiAA, __pfn_input_topic__=persistent://public/default/input], content:C
----- got message -----
key:[null], properties:[__pfn_input_msg_id__=CAoQAyAA, __pfn_input_topic__=persistent://public/default/input], content:D
----- got message -----
key:[null], properties:[__pfn_input_msg_id__=CAoQBCAA, __pfn_input_topic__=persistent://public/default/input], content:E
----- got message -----
key:[null], properties:[__pfn_input_msg_id__=CAoQBSAA, __pfn_input_topic__=persistent://public/default/input], content:F
```

### Anything else?

Perhaps I do not understand the flag's description from the [functions-cli docs](https://pulsar.apache.org/docs/functions-cli):

> retain-ordering: *Function consumes and processes messages in order.*`

So I would expect that unhandled exceptions are taken into account to ensure that the messages are processed in the order they are sequenced in the source topic.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by mattisonchao** [comment]
Hi @freeznet 
Would you like to take a look at it?

**Comment by dionjansen** [comment]
@mattisonchao @freezenet just wondering, is there any update on this? I would be willing to submit a PR, but I'd need some direction on what the approach for this should be.

**Comment by dionjansen** [comment]
@mattisonchao @freeznet @codelipenghui any update on this?

**Comment by jiangpengcheng** [comment]
msg which has an error will be nacked and then retried, functions even with the `--retain-ordering` will not wait for this failed msg to be succeeded but will continue to process other messages

so the `--retain-ordering` just ensures the order of msgs that can be processed successfully

you can try with a java function too:


```
package org.example;

import java.util.function.Function;

public class JavaNativeExclamationFunction implements Function<String, String> {
    @Override
    public String apply(String input) {
        if (input.contains("B")) {
            throw new RuntimeException("fail on B");
        }
        return String.format("%s!", input);
    }
}
```

**Comment by dionjansen** [comment]
> so the `--retain-ordering` just ensures the order of msgs that can be processed successfully

@jiangpengcheng clear, then indeed I have misunderstood the description for this flag in the [functions-cli docs](https://pulsar.apache.org/docs/functions-cli), thank you for clarifying.

I think this can be closed.

**Comment by tisonkun** [comment]
Closed as answred.
