### ISSUE TITLE
[Bug] Broken link: https://pulsar.apache.org/docs/develop-binary-protocol

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#17791]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

The link https://pulsar.apache.org/docs/develop-binary-protocol is first hit for google search "[pulsar binary protocol](https://www.google.com/search?q=pulsar+binary+protocol)". It is broken. 

We should redirect links referring to old content location so that they work with the new website. There might be also a lot of other broken links.

### Minimal reproduce step

click https://pulsar.apache.org/docs/develop-binary-protocol

### What did you expect to see?

It should redirect to https://pulsar.apache.org/docs/next/developing-binary-protocol

### What did you see instead?

a 404 page

### Anything else?

Please ensure that all old content locations (links) are mapped to new locations on the new website.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Related changes https://github.com/apache/pulsar/pull/17265

It actually doesn't place on every versions but fair enough to adopt the redirection approach.

**Comment by tisonkun** [comment]
@lhotari this issue should be resolved now. Please confirm and close if it works for you.

**Comment by momo-jun** [comment]
Closed this issue as it has been fixed through https://github.com/apache/pulsar-site/pull/219.
