### ISSUE TITLE
Hosting blogs content on pulsar-site repo only

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#17817]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Currently, we host blogs in the main repo and sync the files to the pulsar-site repo regularly.

This doesn't produce extra benefits. We can keep those files on the pulsar-site repo only.

### Solution

Keep those files on the pulsar-site repo only. That is, removed from the main repo and update the sync logic.

### Anything else?

cc @Sherlock113 @momo-jun @merlimat @urfreespace 

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by Sherlock113** [comment]
I agree. We can use the pulsar-site repo to host blogs. I don't think this will affect our blogs.

**Comment by momo-jun** [comment]
CC @Anonymitaet
