### ISSUE TITLE
[Bug] PerformanceReader needs one more message than numMessages

### ISSUE THREAD

**Issue by andrasbeni** [apache/pulsar#17823]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

master; hash: 08df28a616

### Minimal reproduce step

Start `bin/pulsar-perf read -u pulsar://localhost:6650 -n 100 topic`.
Run `bin/pulsar-perf produce -u pulsar://localhost:6650 -m 100 topic` in parallel.

### What did you expect to see?

`pulsar-perf read` quits and prints its statistics soon after the producer process finishes.

### What did you see instead?

`pulsar-perf read` indefinitely waits for the next message

### Anything else?

The ReaderListener increments the counter after checking the limit. Changing the order of the two solves the problem.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by mattisonchao** [comment]
Cool and thanks!
