### ISSUE TITLE
[Bug] PerformanceConsumer and PerformanceReader run with -time quit only after another message  

### ISSUE THREAD

**Issue by andrasbeni** [apache/pulsar#17824]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

master; hash: 8e855bc694b97cc0bac3861e3c24d63d7ef883f2

### Minimal reproduce step

Start `bin/pulsar-perf read -u pulsar://localhost:6650 -time 15 topic`
Run ` bin/pulsar-perf produce -u pulsar://localhost:6650 -m 10 topic` in parallel.

### What did you expect to see?

`pulsar-perf read` quits after 15 seconds.

### What did you see instead?

`pulsar-perf read` continued waiting for the next message

### Anything else?

The time limit is only checked in the MessageListener / ReaderListener, so if no new message arrives after the time limit, the consumer/reader waits indefinitely.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by mattisonchao** [comment]
RC: In the current implementation, we put the time check in the listener. If we can't receive any message, the `PerfClientUtils` will never exit. I think.

Would you like to fix it? @andrasbeni

**Comment by andrasbeni** [comment]
@mattisonchao, I don't think I have time this week, so if anybody else wants to take it in the meantime, I'm fine. But I might come back to fix this later.

**Comment by mattisonchao** [comment]
@andrasbeni I see, thanks. I marked this PR with the `help-wanted` label.

**Comment by labuladong** [comment]
@mattisonchao Could you please assign this issue to me? I will fix it.
