### ISSUE TITLE
[Doc] Fix Admin Interface docs for Managing partitioned topics

### ISSUE THREAD

**Issue by Apurva007** [apache/pulsar#17878]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The pulsar docs for updating partitioned topics states that it works only for non-global topics. This seems to be incorrect as per the below pull request:
https://github.com/apache/pulsar/pull/5306

### What is your suggestion?

Please can we remove this statement from the explanation provided for the Update Partitioned topic piece:
"if the topic is non-global"

### Any reference?

https://pulsar.apache.org/docs/next/admin-api-topics/#update

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by momo-jun** [comment]
@liangyepianzhou can you pls help double-check the issue from a technical accuracy perspective?

**Comment by momo-jun** [comment]
@Apurva007 welcome to the Pulsar community. It's a good first issue. Would you like to fix it?

**Comment by Apurva007** [comment]
@momo-jun Thanks alot! I was trying to learn about Apache Pulsar and stumbled upon this issue. I would gladly help fix this issue. 😄

**Comment by tisonkun** [comment]
@Apurva007 are you still working on this issue?

**Comment by Apurva007** [comment]
> @Apurva007 are you still working on this issue?

Hey @tisonkun . Yes will work on it this weekend.

**Comment by jak78** [comment]
Hello @Apurva007 ! Are you still working on this issue?

**Comment by Apurva007** [comment]
@jak78 Yes. I finished the tests this week. Will work on the PR this weekend. Apologies for the delay.

**Comment by jak78** [comment]
Hello @Apurva007 ! Are you still working on this issue?

**Comment by tisonkun** [comment]
@jak78 I found there is an ongoing patch https://github.com/apache/pulsar-site/pull/473 but it seems the author doesn't move forward for some weeks.

**Comment by Apurva007** [comment]
@tisonkun / @jak78 Yes, I am still working on this issue.

**Comment by Apurva007** [comment]
Created the PRs. Waiting for the CIs to pass. Currently the CI checks are failing due to #19952

**Comment by Apurva007** [comment]
Fixed the CI checks using the codecov suggestion by adding a token.
