### ISSUE TITLE
[Bug] TransactionCoordinatorClientImpl.start() hangs forever

### ISSUE THREAD

**Issue by syhily** [apache/pulsar#17876]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Pulsar Java Client 2.10.0
Pulsar 2.10.0

### Minimal reproduce step

Enable the transaction in Pulsar 2.10.0 docker. Create a `PulsarClient`. Then we may see the `TransactionCoordinatorClientImpl.start()` hangs and block the whole process.

### What did you expect to see?

`TransactionCoordinatorClientImpl.start()` shouldn't wait for a long time.

### What did you see instead?

`TransactionCoordinatorClientImpl.start()` block the execution and nothing has showed.

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/1761698/192848499-62a664f5-f594-4b14-b5c5-c467f9906e87.png">

### Anything else?

The jstack file.
[195.log](https://github.com/apache/pulsar/files/9667518/195.log)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by syhily** [comment]
Another jstack file.
[210.log](https://github.com/apache/pulsar/files/9670957/210.log)

**Comment by syhily** [comment]
@congbobo184 Can you help me find out the real cause.

**Comment by syhily** [comment]
The detailed test log is here: [mvn-1.log](https://github.com/apache/pulsar/files/9672766/mvn-1.log).

**Comment by congbobo184** [comment]
Hi @syhily 
TransactionCoordinator loadBalance base on partition topic `persistent://pulsar/system/transaction_coordinator_assign` , so when starting transaction client, make sure that partition topic `persistent://pulsar/system/transaction_coordinator_assign` has been created. Otherwise `persistent://pulsar/system/transaction_coordinator_assign` will be automatically created as Non-partition topic, Pulsar Transaction dnot support Non-partition `persistent://pulsar/system/transaction_coordinator_assign`

**Comment by syhily** [comment]
I don't think the end user should care about these system topic design. This should be a system topic initialization issue.

**Comment by congbobo184** [comment]
@syhily  What users should care about is whether the transaction is fully enabled, rather than using it when it is not fully enabled, isn't it? If there are no other issues, I will close this issue

**Comment by codelipenghui** [comment]
@congbobo184 I think we should provide clear information while the transaction coordinator does not enable it on the broker side. It will help users to understand the problem quickly.

**Comment by congbobo184** [comment]
https://github.com/apache/pulsar/pull/18276 fix this problem, so close this issue
