### ISSUE TITLE
Algolia search doesn't work

### ISSUE THREAD

**Issue by visortelle** [apache/pulsar#17897]
https://user-images.githubusercontent.com/9302460/170059683-887cb086-5836-4d00-8e65-def534fdfbea.mov

Checked with Chrome and Firefox.

**Comment by alpreu** [comment]
Bumping because the search still does not work.

To reproduce simply open this link: https://pulsar.apache.org/search/?q=test

**Comment by urfreespace** [comment]
associate issues created in `docusaurus` and `algolia docsearch` repos
https://github.com/facebook/docusaurus/issues/9200
https://github.com/algolia/docsearch/issues/2008

**Comment by urfreespace** [comment]
fixed

![search](https://github.com/apache/pulsar/assets/76024046/5419ea74-8ac6-4328-b083-bfd743e9197f)
