### ISSUE TITLE
I/O connectors pages loose the navigation

### ISSUE THREAD

**Issue by ddieruf** [apache/pulsar#17895]
When navigating from the connectors listing [https://pulsar.apache.org/docs/next/io-connectors] to an individual connector page [https://pulsar.apache.org/docs/next/io-canal-source#configuration], the left navigation dissappears.

**Comment by Anonymitaet** [comment]
I'll close this issue since it has been transferred to `pulsar`.
For more context, see https://github.com/apache/pulsar-site/pull/236
