### ISSUE TITLE
Only Index Docs from Currently Supported Versions

### ISSUE THREAD

**Issue by dave2wave** [apache/pulsar#17898]
In Algolia there is a crawler configuration which skips "incubating" docs. I think that we should stop creating an index for versions of pulsar components which are no longer supporting.

(1) We can either remove these pages from the site.

or more likely

(2) Include those versions in the exclude pattern.

**Comment by tisonkun** [comment]
FYI @urfreespace

**Comment by tisonkun** [comment]
Closed as done. The incubating pages are removed from the page.

About other unmaintained docs pages, we may later come up with another proposal.

@dave2wave How does Algolia works to exclude those unmaintained docs? I need some technical income to find a way to continue this cleanup work.

**Comment by tisonkun** [comment]
I notice that the version config contains a option `noIndex` https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#VersionsConfig to hint the search engine index those version, will investigate.

**Comment by tisonkun** [comment]
Delivered `noIndex` config. But I'm not sure if Algolia omit ancient versions now or we should still make more configs.

**Comment by tisonkun** [comment]
Closed as somehow we now have only indices for new versions. I'm not sure why but let's open a new issue if there is any regressions.

<img width="1728" alt="image" src="https://github.com/apache/pulsar/assets/18818196/89dd87d5-f4d6-4872-8fbc-28a2599b7989">

**Comment by tisonkun** [comment]
Maybe the `noIndex` metadata helps.
