### ISSUE TITLE
Data driven pages - How to Submit New Content

### ISSUE THREAD

**Issue by dave2wave** [apache/pulsar#17900]
There needs to be a way for users to submit new content for these pages on these pages.

The javascript files that contain this data are here - https://github.com/apache/pulsar-site/tree/main/site2/website-next/data

- ? - [connectors.js](https://github.com/apache/pulsar-site/blob/main/site2/website-next/data/connectors.js) is this still live?
- Ecosytem - [ecosystem.js](https://github.com/apache/pulsar-site/blob/main/site2/website-next/data/ecosystem.js)
- Events - [events.js](https://github.com/apache/pulsar-site/blob/main/site2/website-next/data/events.js)
- Resources - [resources.js](https://github.com/apache/pulsar-site/blob/main/site2/website-next/data/resources.js)
- Meet the Community - [team.js](https://github.com/apache/pulsar-site/blob/main/site2/website-next/data/team.js)
- Case Studies - [users.js](https://github.com/apache/pulsar-site/blob/main/site2/website-next/data/users.js)

What is the proposed workflow?
- for most of these pages it should start with an explanation with a link to create a PR or Issue at the bottom of the page.
- for the team / community the PMC as whole should be responsible. Members of the PMC are PMC Members and not **PMCs**. PMCs are ambiguous, it could mean a group of people or more than one project management committee. The format of the Meet the Community section is another issue.

**Comment by tisonkun** [comment]
I'm going to write down my understanding about the technical part to update content on the website in this week or the next.

About the approval process, I'll submit a separate draft for comment.
