### ISSUE TITLE
[Doc] Migrate C++ and Python client API docs generate process

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#17917]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

After https://github.com/apache/pulsar/issues/17724 moves pulsar-client-cpp and pulsar-client-python to new repository, the original `doxygen-doc-gen.sh` and `pdoc` generation process can break.

### What is your suggestion?

We should investigate them and migrate if necessary.

The Python part should be done by:

* [x] https://github.com/apache/pulsar/issues/18347

### Any reference?

@urfreespace @SignorMercurio @michaeljmarshall please take a look.

cc @Anonymitaet @momo-jun 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Mini256** [comment]
When I installed the pulsar client according to the documentation, I found that the pulsar-client-cpp has been migrated, will this issue be used to track the issue of updating the repo link in the documentation?

https://pulsar.apache.org/docs/client-libraries-cpp/

**Comment by tisonkun** [comment]
@Mini256 I think in this PR https://github.com/apache/pulsar/pull/18140 we already update references of the C++/Python clients' repo. Do you spot any reference unexpected? Or do you think we should add more references at the beginning?

Please share more details you'd like to achieve here :)

**Comment by Mini256** [comment]
https://pulsar.apache.org/docs/client-libraries-cpp#macos

The first step for MacOS tells me that:

> Clone the Pulsar repository.
>
> $ git clone https://github.com/apache/pulsar
> ...
> $ cd pulsar-client-cpp
> $ cmake .
> $ make

And when I execute the `cmake` command, I found that the code of the client has been migrated.

**Comment by tisonkun** [comment]
@Mini256 Good point. In the next version, we change this section directly to the new repo's README. Let me cherry-pick to to other maintained versions.

**Comment by michaeljmarshall** [comment]
Where should we move the python doc process? It's in the pulsar-site right now. I think we could leave the process there and just update the relevant release process docs so that the release manager knows how to generate the docs.

**Comment by tisonkun** [comment]
@michaeljmarshall agree and file https://github.com/apache/pulsar/issues/18347. I'm doing this now.
