### ISSUE TITLE
[Bug] There's no proper NOTICE file provided for pulsar-client-all

### ISSUE THREAD

**Issue by XComp** [apache/pulsar#17949]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.10.0

### Minimal reproduce step

`org.apache.pulsar:pulsar-client-all:2.10.0` provides a kind of empty NOTICE file:
```
$ unzip -p ~/.m2/repository/org/apache/pulsar/pulsar-client-all/2.10.0/pulsar-client-all-2.10.0.jar META-INF/NOTICE

Pulsar Client All
Copyright 2017-2020 Apache Software Foundation

This product includes software developed at
The Apache Software Foundation (http://www.apache.org/).


$
```

### What did you expect to see?

I would expect shaded dependencies (see [apache/pulsar:pulsar-client-all/pom.xml:L120](https://github.com/apache/pulsar/blob/master/pulsar-client-all/pom.xml#L120)) being mentioned in the NOTICE file.

### What did you see instead?

NOTICE file being empty

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by michaeljmarshall** [comment]
@lhotari @nicoloboschi - are either of you familiar with this part of the artifact generation? Thanks!

**Comment by michaeljmarshall** [comment]
I can confirm the same results for a recent build of master branch:
```
$ unzip -p /Users/michaelmarshall/.m2/repository/org/apache/pulsar/pulsar-client-all/2.11.0-SNAPSHOT/pulsar-client-all-2.11.0-SNAPSHOT.jar META-INF/NOTICE

Pulsar Client All
Copyright 2017-2020 Apache Software Foundation

This product includes software developed at
The Apache Software Foundation (http://www.apache.org/).

```

The copyright dates even look wrong.

**Comment by tisonkun** [comment]
Closed. Apache license doesn't enforce the root `NOTICE` file to contain all the NOTICE content from dependencies, but only if we convey the NOTICEs content from dependencies in _some_ way: you can read them at `META-INF/NOTICE.md` or `META-INF/NOTICE.markdown`.

**Comment by tisonkun** [comment]
Above the copyright year issue, it seems about build time. @michaeljmarshall IIRC you submitted a patch to improve it.
