### ISSUE TITLE
[BUG] Site build consistently fails

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#17960]
@merlimat @Anonymitaet @urfreespace @momo-jun 

Since @DaveDuggins doesn't upload these SVG files, the site build is currently broken: https://github.com/apache/pulsar-site/actions/runs/3204572728/jobs/5236018179.

If @DaveDuggins can provide the files, I'm glad to help with submitting a patch. Otherwise, we may firstly revert this commit.

_Originally posted by @tisonkun in https://github.com/apache/pulsar/pull/17863#discussion_r990174850_

**Comment by tisonkun** [comment]
@DaveDuggins So, the answer is, opening another pull request :)

**Comment by DaveDuggins** [comment]
OK
