### ISSUE TITLE
[Bug] getUnackedMessages() always return 0

### ISSUE THREAD

**Issue by startjava** [apache/pulsar#17983]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

pulsar 2.10.1

https://github.com/apache/pulsar/discussions/17978

### Minimal reproduce step

https://github.com/apache/pulsar/discussions/17978

### What did you expect to see?

https://github.com/apache/pulsar/discussions/17978

### What did you see instead?

https://github.com/apache/pulsar/discussions/17978

### Anything else?

https://github.com/apache/pulsar/discussions/17978

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by startjava** [comment]
5 message , ack 1 message , but result 0：

[ghy@localhost bin]$ .//pulsar-admin topics stats myTopic1
{
  "msgRateIn" : 0.0,
  "msgThroughputIn" : 0.0,
  "msgRateOut" : 0.0,
  "msgThroughputOut" : 0.0,
  "bytesInCounter" : 1170,
  "msgInCounter" : 15,
  "bytesOutCounter" : 1170,
  "msgOutCounter" : 15,
  "averageMsgSize" : 0.0,
  "msgChunkPublished" : false,
  "storageSize" : 1170,
  "backlogSize" : 1170,
  "publishRateLimitedTimes" : 0,
  "earliestMsgPublishTimeInBacklogs" : 0,
  "offloadedStorageSize" : 0,
  "lastOffloadLedgerId" : 0,
  "lastOffloadSuccessTimeStamp" : 0,
  "lastOffloadFailureTimeStamp" : 0,
  "publishers" : [ {
    "accessMode" : "Shared",
    "msgRateIn" : 0.0,
    "msgThroughputIn" : 0.0,
    "averageMsgSize" : 0.0,
    "chunkedMessageRate" : 0.0,
    "producerId" : 0,
    "supportsPartialProducer" : false,
    "metadata" : { },
    "producerName" : "standalone-41-6",
    "connectedSince" : "2022-10-10T15:34:33.518+08:00",
    "address" : "/192.168.3.188:60416",
    "clientVersion" : "2.10.1"
  } ],
  "waitingPublishers" : 0,
  "subscriptions" : {
    "myTopic1_subscriptionName1" : {
      "msgRateOut" : 0.0,
      "msgThroughputOut" : 0.0,
      "bytesOutCounter" : 1170,
      "msgOutCounter" : 15,
      "msgRateRedeliver" : 0.0,
      "messageAckRate" : 0.0,
      "chunkedMessageRate" : 0,
      "msgBacklog" : 12,
      "backlogSize" : 0,
      "earliestMsgPublishTimeInBacklog" : 0,
      "msgBacklogNoDelayed" : 12,
      "blockedSubscriptionOnUnackedMsgs" : false,
      "msgDelayed" : 0,
      "unackedMessages" : 0,
      "type" : "Exclusive",
      "activeConsumerName" : "消费者1",
      "msgRateExpired" : 0.0,
      "totalMsgExpired" : 0,
      "lastExpireTimestamp" : 0,
      "lastConsumedFlowTimestamp" : 1665387297333,
      "lastConsumedTimestamp" : 1665403383584,
      "lastAckedTimestamp" : 1665403383761,
      "lastMarkDeleteAdvancedTimestamp" : 0,
      "consumers" : [ {
        "msgRateOut" : 0.0,
        "msgThroughputOut" : 0.0,
        "bytesOutCounter" : 1170,
        "msgOutCounter" : 15,
        "msgRateRedeliver" : 0.0,
        "messageAckRate" : 0.0,
        "chunkedMessageRate" : 0.0,
        "consumerName" : "消费者1",
        "availablePermits" : 985,
        "unackedMessages" : 0,
        "avgMessagesPerEntry" : 1,
        "blockedConsumerOnUnackedMsgs" : false,
        "lastAckedTimestamp" : 1665403383761,
        "lastConsumedTimestamp" : 1665403383584,
        "metadata" : { },
        "connectedSince" : "2022-10-10T15:34:57.319+08:00",
        "address" : "/192.168.3.188:60461",
        "clientVersion" : "2.10.1"
      } ],
      "isDurable" : true,
      "isReplicated" : false,
      "allowOutOfOrderDelivery" : false,
      "consumersAfterMarkDeletePosition" : { },
      "nonContiguousDeletedMessagesRanges" : 3,
      "nonContiguousDeletedMessagesRangesSerializedSize" : 32,
      "subscriptionProperties" : { },
      "durable" : true,
      "replicated" : false
    }
  },
  "replication" : { },
  "deduplicationStatus" : "Disabled",
  "nonContiguousDeletedMessagesRanges" : 3,
  "nonContiguousDeletedMessagesRangesSerializedSize" : 32,
  "compaction" : {
    "lastCompactionRemovedEventCount" : 0,
    "lastCompactionSucceedTimestamp" : 0,
    "lastCompactionFailedTimestamp" : 0,
    "lastCompactionDurationTimeInMills" : 0
  }
}
[ghy@localhost bin]$

**Comment by liangyuanpeng** [comment]
You're use acknowledgeCumulative and nod ack method , see https://github.com/apache/pulsar/discussions/17978#discussioncomment-3835999 , so you got the unackmessages is 0.

I have test this case:

1. consumer subscribe topic of `persistent://public/default/test`
2. producer send 10 messages to `persistent://public/default/test`
3. consumer ack the first message
4. check unackMessages from `pulsarctl topics stats persistent://public/default/test-partition-0`   (this is a partition topic )
5. got the `unackMessages ` is 9.

/cc  @Technoboy-  @startjava

**Comment by startjava** [comment]
How do I change my code so that the result is 9?






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月11日(星期二) 中午12:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/pulsar] [Bug] getUnackedMessages() always return 0 (Issue #17983)





 
You're use acknowledgeCumulative and nod ack method , see #17978 (reply in thread) , so you got the unackmessages is 0.
 
I have test this case:
  
consumer subscribe topic of persistent://public/default/test
 
producer send 10 messages to persistent://public/default/test
 
consumer ack the first message
 
check unackMessages from pulsarctl topics stats persistent://public/default/test-partition-0   (this is a partition topic )
 
got the unackMessages  is 9.
  
/cc  @Technoboy-  @startjava

**Comment by liangyuanpeng** [comment]
> How do I change my code so that the result is 9?

https://github.com/apache/pulsar/discussions/17978#discussioncomment-3844883

**Comment by startjava** [comment]
(4)check unackMessages from pulsarctl topics stats persistent://public/default/test-partition-0 (this is a partition topic )

can only use ??:
persistent://public/default/test

**Comment by startjava** [comment]
i use ""myTopic1-partition-0""

result exception:
org.apache.pulsar.shade.javax.ws.rs.NotFoundException: HTTP 404 Partitioned Topic not found: persistent://public/default/myTopic1-partition-0 has zero partitions

**Comment by liangyuanpeng** [comment]
Your topic is not partition topic ,so you should check the status from topic of `persistent://public/default/myTopic1`.

**Comment by startjava** [comment]
but this issues top has my check status json result , unackmsgcount value is 0.
in addition， value not is 0 ,must partition topic??
@liangyuanpeng

**Comment by startjava** [comment]
pulsar 2.10.1 version 。

```

package com.ghy.www.cumulativeacknowledgement.consumer.listener;


import org.apache.pulsar.client.api.Consumer;
import org.apache.pulsar.client.api.Message;
import org.apache.pulsar.client.api.MessageListener;
import org.apache.pulsar.client.api.PulsarClientException;
import org.springframework.stereotype.Component;

@Component
public class MyMessageListener1 implements MessageListener {
    @Override
    public void received(Consumer consumer, Message msg) {
        try {
            String messageString = new String(msg.getData());
            System.out.println(messageString);
            if (messageString.equals("acknowledge消息1")) {
                consumer.acknowledge(msg);
                System.out.println(messageString + "执行了acknowledge");
            }
        } catch (PulsarClientException e) {
            throw new RuntimeException(e);
        }
    }
}

```
```

package com.ghy.www.cumulativeacknowledgement.consumer.listener;

import org.apache.pulsar.client.api.Consumer;
import org.apache.pulsar.client.api.Message;
import org.apache.pulsar.client.api.MessageListener;
import org.apache.pulsar.client.api.PulsarClientException;
import org.springframework.stereotype.Component;

@Component
public class MyMessageListener2 implements MessageListener {
    @Override
    public void received(Consumer consumer, Message msg) {
        try {
            String messageString = new String(msg.getData());
            System.out.println(messageString);
            if (messageString.equals("acknowledgeCumulative消息1")) {
                consumer.acknowledgeCumulative(msg);
                System.out.println(messageString + "执行了acknowledgeCumulative");
            }
        } catch (PulsarClientException e) {
            throw new RuntimeException(e);
        }
    }
}
```

```
    @RequestMapping("getUnAckMsgCount")
    public String getUnAckMsgCount() throws PulsarClientException, PulsarAdminException {
        {
            List<? extends ConsumerStats> consumers = pulsarAdmin.topics().getStats(myTopic1).getSubscriptions().get(myTopic1_subscriptionName).getConsumers();
            for (int i = 0; i < consumers.size(); i++) {
                ConsumerStats consumerStats = consumers.get(i);
                System.out.println(myTopic1 + " getConsumerName=" + consumerStats.getConsumerName() + " getUnackedMessages=" + consumerStats.getUnackedMessages());
            }
        }
        System.out.println();
        {
            List<? extends ConsumerStats> consumers = pulsarAdmin.topics().getStats(myTopic2).getSubscriptions().get(myTopic2_subscriptionName).getConsumers();
            for (int i = 0; i < consumers.size(); i++) {
                ConsumerStats consumerStats = consumers.get(i);
                System.out.println(myTopic2 + " getConsumerName=" + consumerStats.getConsumerName() + " getUnackedMessages=" + consumerStats.getUnackedMessages());
            }
        }
        return "成功获得";
    }
```

run url "getUnAckMsgCount" , print info ：
myTopic1 getConsumerName=消费者1 getUnackedMessages=0

myTopic2 getConsumerName=消费者2 getUnackedMessages=0

alway value is 0 .

i where error ?

**Comment by startjava** [comment]
@liangyuanpeng  thank you
