### ISSUE TITLE
Topic metadata unable to be updated using the admin REST API - Error 405 Method not Allowed

### ISSUE THREAD

**Issue by Addyvan** [apache/pulsar#18011]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.10.1

### Minimal reproduce step

I'm running a python script:
```python
import requests

properties = { "test": "test" }

headers={ 'Content-Type': 'application/json' }
resp = requests.put(
    f"{PULSAR_ADMIN_ENDPOINT}/admin/v2/persistent/{tenant}/{namespace}/{topic}/properties",
    data=properties,
    headers=headers
)

print(resp)
print(resp.reason)
```

Response:
```
<Response [405]>
Method Not Allowed
```

This should be the equivalent curl command: 
```bash
curl -L http://<ENDPOINT>:8080/admin/v2/persistent/<tenant>/<namespace>/<topic>/properties -X PUT -H 'Content-Type: application/json' -d '{"test":"test"}'
```

### What did you expect to see?

Response code 200 or 204 with the topic's properties having been updated. 

### What did you see instead?

Response code 405 with the topic's properties remaining the same. 

### Anything else?

Based the request off the docs page: 
![image](https://user-images.githubusercontent.com/24901494/195167551-24dbfea6-478a-49fb-ac56-a13a880daf3f.png)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
`curl -L http://<ENDPOINT>:8080/admin/v2/persistent/<tenant>/<namespace>/<topic>/properties -X PUT -H 'Content-Type: application/json' -d '{"test":"test"}'`

The above command is working for me in my local.

**Comment by Addyvan** [comment]
> 

@Technoboy- Can you confirm that the change did take place by editing the properties then running `curl -L http://<ENDPOINT>:8080/admin/v2/persistent/<tenant>/<namespace>/<topic>/properties` to see if they did in fact change? 

The curl command doesn't throw an error or return anything.

**Comment by Technoboy-** [comment]
> > 
> 
> @Technoboy- Can you confirm that the change did take place by editing the properties then running `curl -L http://<ENDPOINT>:8080/admin/v2/persistent/<tenant>/<namespace>/<topic>/properties` to see if they did in fact change?
> 
> The curl command doesn't throw an error or return anything.

yes, it works.
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/6297296/195490745-0130012c-76a2-4bd9-9140-601aab68ced2.png">
