### ISSUE TITLE
[Doc] Improve geo-replication example

### ISSUE THREAD

**Issue by AlvaroStream** [apache/pulsar#18016]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

Explanation from the [replication clusters](https://pulsar.apache.org/docs/administration-geo/#connect-replication-clusters ) could be improved, after reading several times the geo-replication I was a little bit lost.

### What is your suggestion?

- I think the first example should be just between 2 clusters. And put an example with more differences in the names. Sometimes it is difficult to follow `us-west`, `us-cent`, and `us-east` clusters. I would rename them to Original and Replicated.
- There could be another second example with 3 clusters but easier to follow.
- I missed in the explanation of geo-replication that replication behaves like a “subscription” in Cluster Origin that connect as a producer  into Cluster Replica. So that explains what happens on next command, why you execute it in Origin and the information you need to provide.
```
$ bin/pulsar-admin clusters create \
  --broker-url pulsar://<DNS-OF-REPLICA>:<PORT> \
  --url http://<DNS-OF-REPLICA>:<PORT> \
  replica-cluster
```

### Any reference?

N/A

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Hongten** [comment]
Question: 
There are two pulsar clusters(A and B) and we enabled the Geo-Replication. e.g. `my_tenant/my_namespace/my_topic`, we can produce the data to the A cluster and consume the data from the B cluster. How to delete this topic? If we can delete the topic, can you share the details?

**Comment by gaoran10** [comment]
@Hongten Sorry, I'm not sure about your question, do you want to delete the topic in both clusters?

**Comment by Hongten** [comment]
> @Hongten Sorry, I'm not sure about your question, do you want to delete the topic in both clusters?

yes, correct. Can you advise? thanks.

**Comment by AlvaroStream** [comment]
There has been some improvement lately and I didn't have time to improve it I will close this and review it more.
