### ISSUE TITLE
[drafting]PIP-213: Add per-thread CPU usage metrics 

### ISSUE THREAD

**Issue by tjiuming** [apache/pulsar#18038]
### Motivation

Introduce the metrics for thread CPU usage which can help Pulsar maintainers to detect performance issues related to parts of threads that run with high CPU usage, especially the IO thread.

This part is also the missing part of Apache Pulsar. The thread pool and thread CPU usage are very useful for troubleshooting performance issues like publishing latency spikes.

And we can also adjust the ThreadPool according to the metrics, increase the number of threads of a certain type, or decrease. It’s useful to help our users to improve broker performance by operations.

### Goal

1. Provide per-thread CPU usage metrics.

### Implementation

Java provides MXBean to monitor JVM inner stats, I’ll implement per-thread CPU usage by [ThreadMXBean](https://github.com/openjdk/jdk/blob/master/src/java.management/share/classes/java/lang/management/ThreadMXBean.java).

**Comment by codelipenghui** [comment]
@tjiuming Could you please help put a summary for this proposal? Maybe some users also try to find a solution to get the metrics of threads.

**Comment by tjiuming** [comment]
@codelipenghui OK
