### ISSUE TITLE
[Bug] delete-partition-topics error

### ISSUE THREAD

**Issue by kukuzidian** [apache/pulsar#18046]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

system os centos 7.8 
jdk 1.8.0_191
pulsar version  2.10.1

### Minimal reproduce step

bin/pulsar-admin topics delete-partitioned-topic persistent://public/default/tt1

### What did you expect to see?

delete partitioned-topic  success

### What did you see instead?

server print some Exception 

![issus](https://user-images.githubusercontent.com/3753735/195783214-46713316-2d0f-4daf-b089-4a761cdf20fb.jpg)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liangyuanpeng** [comment]
Could you try it on 2.10.2?

**Comment by tisonkun** [comment]
Cannot reproduce on master - 

```
bin/pulsar-admin topics create-partitioned-topic -p 4 persistent://public/default/tt1
bin/pulsar-admin topics delete-partitioned-topic persistent://public/default/tt1
```

correctly.
