### ISSUE TITLE
[Bug] Broker's CPU remains high after some data buildup due to some application (consumer) restarts

### ISSUE THREAD

**Issue by shenweiran** [apache/pulsar#18055]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.9.3

### Minimal reproduce step

Recently upgraded from 2.6.3 to 2.9.3 with this problem;
Some of consumers rebooted and subscribed to about 17,000 topics

### What did you expect to see?

Even if some consumers reboot, after affecting Pulsar Cluster should be restored to stability

### What did you see instead?

Broker's CPU remains high

![image](https://user-images.githubusercontent.com/1320933/195887380-8e07ff3c-2892-4e53-894c-554125753a36.png)
![image](https://user-images.githubusercontent.com/1320933/195888637-0d022457-0fe1-48e7-ba56-6039c3e85dea.png)

### Anything else?

If you need to get more information you can contact me (shenweiran@xlink.cn)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by shenweiran** [comment]
![image](https://user-images.githubusercontent.com/1320933/195998963-9991edfe-a170-4e88-9b6c-bc605201dab2.png)
![image](https://user-images.githubusercontent.com/1320933/195998970-2b69d091-e073-4184-93b7-ea309d5f5272.png)

**Comment by shenweiran** [comment]
![image](https://user-images.githubusercontent.com/1320933/195999053-9742a671-dca5-47f0-a1a9-283094887ebf.png)

**Comment by shenweiran** [comment]
heap dump file: 
link:https://pan.baidu.com/s/1YdXn7qC32Ybgl6Ux4A_sng  
pwd:7mdw

**Comment by WJL3333** [comment]
after analysis the heap, a lot of task is submit by ProducerImpl created by `TransactionBufferSystemTopicClient` for broker side code those task will be scheduled at pulsar-io thread and will consume a lot cpu for priorityQueue change.

**Comment by WJL3333** [comment]
![image](https://user-images.githubusercontent.com/13600283/196017780-12c0b553-a59f-4a79-9f2f-c6516a46d309.png)
![image](https://user-images.githubusercontent.com/13600283/196017829-74a51ac9-0088-43fd-a00a-6e8c0690618e.png)
![image](https://user-images.githubusercontent.com/13600283/196017838-810248d3-db4c-4842-8a7a-5e45ce2a5b53.png)

**Comment by eolivelli** [comment]
Did you enable transactions?

If you are coming from 2.6 then you don't need it.

Also transactions code is more mature on 2.10 if you need TC then move to 2.10

**Comment by michaeljmarshall** [comment]
A fix was merged into branch-2.9, but master is not yet updated. Master has a slightly different design, but would still probably benefit from using a more optimized timer implementation.

**Comment by shenweiran** [comment]
After disabling the transac
![image](https://user-images.githubusercontent.com/1320933/197088696-af53c2f1-95b6-4774-8712-3e0c2f0684e8.png)
tion configuration, restart all brokers, the problem is restored.

**Comment by shenweiran** [comment]
update broker.conf :
transactionCoordinatorEnabled=false
