### ISSUE TITLE
[Doc] improve style of shell commands

### ISSUE THREAD

**Issue by labuladong** [apache/pulsar#18088]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

When I read the [admin interface doc](https://pulsar.apache.org/docs/next/admin-api-tenants), I found that it's hard to distinguish between shell command and output.

For example:

![image](https://user-images.githubusercontent.com/37220920/196405883-577913af-f22b-4219-8c57-82946189ecaf.png)

![image](https://user-images.githubusercontent.com/37220920/196408351-9b08aa81-9552-40aa-b3e0-07017b30f634.png)

### What is your suggestion?

I suggest unifying the style of all shell commands:

1. separate output and command this way:
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/37220920/196408006-2f26b47f-1ea2-4f93-8503-f23aaba7f5c6.png">

2. if it is a multi-line command, start with an indent and end with a slash, for example:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/37220920/196408519-1048fd7b-b8d4-49ea-a4ea-7ed354c51e3d.png">

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by labuladong** [comment]
cc @Anonymitaet @momo-jun

**Comment by momo-jun** [comment]
@labuladong thanks for the finding. It makes sense to improve as you suggest.

**Comment by Anonymitaet** [comment]
Good catch! @labuladong
