### ISSUE TITLE
[Bug] why remove the method getClientConfigData from pulsarAdmin interface after 2.7？ how can I getAuthentication data in 2.8？

### ISSUE THREAD

**Issue by krishhh5** [apache/pulsar#18087]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.8.1

### Minimal reproduce step

1 

### What did you expect to see?

why remove the method getClientConfigData from pulsarAdmin interface after 2.7？ how can I getAuthentication data in 2.8？

### What did you see instead?

why remove the method getClientConfigData from pulsarAdmin interface after 2.7？ how can I getAuthentication data in 2.8？

### Anything else?

why remove the method getClientConfigData from pulsarAdmin interface after 2.7？ how can I getAuthentication data in 2.8？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by mattisonchao** [comment]
See: https://github.com/apache/pulsar/pull/10563 

Maybe you can try `((PulsarAdminImpl) pulsar.getAdminClient()).getClientConfigData()`

**Comment by mattisonchao** [comment]
Close this issue because the issue has been to be Stale.
