### ISSUE TITLE
[Bug] delete tenant after read tenant list exception： HTTP 404 Tenant does not exist

### ISSUE THREAD

**Issue by startjava** [apache/pulsar#18095]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.10.1

### Minimal reproduce step

    @RequestMapping("delete")
    public String delete() throws IOException, PulsarAdminException {
        if (pulsarAdmin.tenants().getTenants().indexOf(tenantName) == -1) {
        } else {
            pulsarAdmin.tenants().deleteTenant(tenantName, true);// 1 step :delete
        }
        System.out.println();
        read();// 2 step :read tenant list ,result exception：
        // org.apache.pulsar.shade.javax.ws.rs.NotFoundException: HTTP 404 Tenant does not exist
        return "delete";
    }

### What did you expect to see?

yes

### What did you see instead?

?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by startjava** [comment]
deleteTenant and readTenant() method asynchronzied run ?

deleteTenant() method source：
```
    public void deleteTenant(String tenant, boolean force) throws PulsarAdminException {
        this.sync(() -> {
            return this.deleteTenantAsync(tenant, force);
        });
    }
```
inner asynchronzied run? no result ?

**Comment by startjava** [comment]
```
    @RequestMapping("read")
    public String read() throws IOException, PulsarAdminException {
        List<String> tenantList = pulsarAdmin.tenants().getTenants();
        if (tenantList.size() != 0) {
            for (int i = 0; i < tenantList.size(); i++) {
                String tenantName = tenantList.get(i);
                System.out.println("tenantName：" + tenantName);
                System.out.println("begin");
                TenantInfo tenantInfo = pulsarAdmin.tenants().getTenantInfo(tenantName);
                System.out.println("  end");
                {
                    Set<String> allowedClusters = tenantInfo.getAllowedClusters();
                    Iterator<String> iterator = allowedClusters.iterator();
                    while (iterator.hasNext()) {
                        System.out.println("  allowedClusters：" + iterator.next());
                    }
                }
                {
                    Set<String> adminRoles = tenantInfo.getAdminRoles();
                    Iterator<String> iterator = adminRoles.iterator();
                    while (iterator.hasNext()) {
                        System.out.println("  adminRoles：" + iterator.next());
                    }
                }
            }
        } else {
            System.out.println("没有任何租户！");
        }
        return "read";
    }
```

run result ：
tenantName：ghy-tenant
begin


not print String "end" . beacuse tenant delete ... get tenantinfo exception.

**Comment by startjava** [comment]
run result ：
tenantName：ghy-tenant
begin

note：The tenant name that was just deleted was printed！！！！！！

**Comment by startjava** [comment]
@eolivelli 
this issues and https://github.com/apache/pulsar/pull/11039 is same bug???

**Comment by startjava** [comment]
@hangc0276 
this issues and https://github.com/apache/pulsar/pull/11039 is same bug???
How to solve my code

**Comment by nodece** [comment]
The master branch has been verified, it works fine.
