### ISSUE TITLE
[Doc] Move `Security Policy and Supported Versions` to an appropriate category in the website

### ISSUE THREAD

**Issue by momo-jun** [apache/pulsar#18103]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

When improving the content under the security chapter, I found this [security policy and supported versions](https://pulsar.apache.org/docs/security-policy-and-supported-versions/) topic is not appropriately nested there, which is not about Pulsar features but the project information.

### What is your suggestion?

This has been discussed in https://github.com/apache/pulsar/pull/10829 where the change was implemented. And I agree with @Anonymitaet that we should have a better place for this information, for example, in the [community > governance](https://pulsar.apache.org/community#section-governance) page, a new security page, or the developer guide.

//cc @tisonkun @labuladong 

### Any reference?

This link is being referenced in other repos, such as [Pulsar C++ Client](https://github.com/apache/pulsar-client-cpp/blob/main/SECURITY.md). 

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Reference: https://github.com/apache/pulsar-site/pull/21

**Comment by tisonkun** [comment]
I don't think that this page should live under the contribution guide also. It should have a dedicate page.
