### ISSUE TITLE
Add CI for checking code style of pulsar connectors

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#18131]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Recently, there has been a checkstyle issue in the jdbc connector core.(https://github.com/apache/pulsar/pull/18122) It seems that there is no CI to check the code style of these modules. Need to make this check happen in the CI.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Agree. I think...wait a minute, IIRC we have a checkstyle goal here previously:

https://github.com/apache/pulsar/blob/0c326c0845eb66f513a5f199308620074cdb9b04/.github/workflows/pulsar-ci.yaml#L106-L107

**Comment by tisonkun** [comment]
@RobertIndie I'm opening a PR #18142 against this issue. But it's highly possible that we have some remaining violence to fix.
