### ISSUE TITLE
[Doc] Refactor the information architecture and content of Schema 

### ISSUE THREAD

**Issue by momo-jun** [apache/pulsar#18151]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

This idea popped up when I was thinking about how to improve the client libraries docs - it's very likely that because we haven't got a robust and structured topic-based authoring model to host the docs for various features, contributors/maintainers don't know what's the proper place to fit the information in so they keep tiling the content in clients' docs, which causes many duplicates and inconsistencies, and somehow isolated and difficult to consume. So I started with Security doc improvements and now Schema.

Schema content is scattered and not easy to read and understand, including:
1. The overall Information Architecture can be better organized and reused.
2. Similar to the Security - authentication section, the schema examples and references for multi-language clients can be incorporated into the Schema chapter and only keeps a link in the `Client Libraries` chapter. ---- also has a dependency on this [client doc issue](https://github.com/apache/pulsar/issues/17302).
3. Administrative tasks using APIs should be relocated to the `Admin Interfaces` chapter.
4. Outdated content needs a revisit and refresh.

### What is your suggestion?

1. Redesign the information architecture through content mapping. The following is an initial thought. **Feel free to leave your suggestions regarding schema content, as a user or an expert.**
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/60642177/198610461-3aa71158-96d8-4540-a807-bde6d6d395c0.png">
2. Improve the content with engineering experts in a follow-up PR.

### Any reference?

The applied methodology and expected outcome for refactoring the IA and content are similar to the following chapters:
* [Functions](https://pulsar.apache.org/docs/next/functions-overview) implemented in https://github.com/apache/pulsar/pull/15975
* [Security](https://pulsar.apache.org/docs/next/security-overview) implemented in 
    * https://github.com/apache/pulsar/pull/17615
    * https://github.com/apache/pulsar/pull/17666
    * https://github.com/apache/pulsar/pull/17808
    * https://github.com/apache/pulsar/pull/18035

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### Implementation

- [X] #18242

**Comment by momo-jun** [comment]
Ping @congbobo184 @RobertIndie to take a look at the proposal.
//cc @Anonymitaet  @DaveDuggins @D-2-Ed

**Comment by yuweisung** [comment]
what kinds of schema protocol do we support?  json, avro, protobuf, thrift?

**Comment by momo-jun** [comment]
> what kinds of schema protocol do we support? json, avro, protobuf, thrift?

@yuweisung thrift is not supported; for the other three, Yes!
