### ISSUE TITLE
[update][dependency] Please update openssl to 1.1.1r

### ISSUE THREAD

**Issue by dave2wave** [apache/pulsar#18155]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Keep OpenSSL in C++ up to date. See https://www.openssl.org/news/openssl-1.1.1-notes.html

### Solution

Update the C++ builds.

### Alternatives

None

### Anything else?

No

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by hpvd** [comment]
or directly to v3.0 which is the latest major version with LTS

which has beside new features an easier licence than the dual licence of 1.x...
https://www.openssl.org/source/license.html

migration guide:
https://www.openssl.org/docs/man3.0/man7/migration_guide.html

**Comment by dave2wave** [comment]
Dual license is not difficult we choose the one that is best for an Apache project.

Regarding migration or not. Upgrading to 1.1.1r will handle two CVEs immediately.

**Comment by hpvd** [comment]
> Dual license is not difficult we choose the one that is best for an Apache project.
this is why I suggested v3...

> For the 3.0 release, and later releases derived from that, [the Apache License v2](https://www.openssl.org/source/apache-license-2.0.txt) applies.

**Comment by merlimat** [comment]
This is already addressed in the `pulsar-client-cpp-3.0.0` release. You can find the list of dependencies here: https://github.com/apache/pulsar-client-cpp/blob/main/dependencies.yaml

**Comment by merlimat** [comment]
> or directly to v3.0 which is the latest major version with LTS

we need to validate how that works well with boost::asio and libcurl

**Comment by merlimat** [comment]
To clarify: we're using `1.1.1q` and not `1.1.1r`, though the only main difference is a compile error fix, not any security issues. https://www.openssl.org/news/cl111.txt

Also, please open C++ client issues on https://github.com/apache/pulsar-client-cpp

**Comment by dave2wave** [comment]
Thank you @merlimat I'm glad you have already taken this into account. I will close this issue. If @hpvd wishes they can open an issue in the other repository.
