### ISSUE TITLE
Release all static resources under `$WEBSITE/static` in the site repo

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#18174]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Currently, we only move part of the static resources under `$WEBSITE/static` to the final website deployment:

https://github.com/apache/pulsar-site/blob/c30db65192c9f1791bf4bd2cf1b300124643933a/site2/tools/build-site.sh#L45-L62

I think it breaks the assumption of Docusaurus that all stuff under `static` is released to the final deployment as is. Also, this assumption break causes a follow-up to https://github.com/apache/pulsar-site/pull/261 as stated at https://github.com/apache/pulsar-site/pull/259#issuecomment-1288736359.

### Solution

Release all static resources under `$WEBSITE/static` in the site repo.

### Anything else?

cc @urfreespace 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by urfreespace** [comment]
@tisonkun  tests show that hidden files are not copied by default. as you know, files whose names start with a dot are hidden files https://github.com/apache/pulsar-site/pull/263 PTAL, thanks.
