### ISSUE TITLE
[Bug] [Backport]  #14814 -> 2.8.x (pulsar-managed runtimes fail to start function with package URL)

### ISSUE THREAD

**Issue by flowchartsman** [apache/pulsar#18213]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

If it is possible, could #14814 be cherry-picked to 2.8? I tried applying the change to the 2.8 branch, and aside from a minor conflict on import ordering, it looks as if it would apply cleanly. This would allow 2.8 to run pulsar functions from the package manager.

### Minimal reproduce step

Attempt to deploy pulsar function from package management.

### What did you expect to see?

Success.

### What did you see instead?

In the logs:
```
2022-03-23T07:00:52,589+0000 [worker-scheduler-0] ERROR org.apache.pulsar.functions.worker.FunctionActioner - public/default/1ib0g63yjm6hw Error starting function
org.apache.distributedlog.exceptions.InvalidStreamNameException: Invalid stream name : 'Invalid log name "/function://public/default/function@0.1.0" caused by empty node name specified @11'
    at org.apache.dist…
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by codelipenghui** [comment]
@flowchartsman I have cherry-picked the PR into branch-2.8. Close the issue for now.
