### ISSUE TITLE
PIP-221: Make TableView support TTL

### ISSUE THREAD

**Issue by Demogorgon314** [apache/pulsar#18229]
### Motivation

Currently, the table view only supports removing messages 
when receiving tombstone messages.

However, some old keys may be useless after a while, 
but we won't be able to remove them unless we manually scan the map. 
Like load data in PIP-192 [#16691](https://github.com/apache/pulsar/issues/16691). 

This PIP will introduce the TTL to delete the old data, 
and the TTL will be based on the message publish time.

### Goal

Add TTL for persistent and non-persistent topic data in the table view.

### API Changes

```java
public interface TableViewBuilder<T> {
// ...

    /**
     * Set key to expire after written TTL. 
     * If not set, the key will never expire unless received the tombstone(The value is null) message.
     *
     * @param ttl The key time to live.
     * @param unit The ttl unit.
     * @return The {@link TableViewBuilder} builder instance
     */
    TableViewBuilder<T> ttl(int ttl, TimeUnit unit);
}
```

### Implementation

The data can be stored in a caffeine cache. 
We can easily use `expireAfter` API to add TTL support.

### Alternatives

Users manually maintain another cache to scan 
and remove it by tombstone messages.

### Anything else?

No response

**Comment by codelipenghui** [comment]
@Demogorgon314 It's a little confusing if the TTL can only apply to the table view that is based on the non-persistent topic. Or can it also apply to the persistent topic?

And the TTL is based on the message publish time or the time arrive the consumer.

**Comment by Demogorgon314** [comment]
@codelipenghui I have changed the PIP describe base on your comment. Please take a look again! Thanks.

**Comment by codelipenghui** [comment]
@Demogorgon314 LGTM

**Comment by eolivelli** [comment]
I don't think that TTL is related to supporting non-persistent topics.

Maybe the TTL feature is worth a PIP, but supporting non-persistent topics is like a small enhancement (or completing the TableView) feature to me and it doesn't need a PIP, as it doesn't need API changes

**Comment by heesung-sn** [comment]
@Demogorgon314 Should we close this PIP if we decide not to work on this?
