### ISSUE TITLE
[Doc] Fix links to Google docs page in the documentation guide

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#18297]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

There are still several links to Google Docs at https://pulsar.apache.org/contribute/documentation/overview

### What is your suggestion?

Replace with links to the corresponding doc site files.

### Any reference?

Subtask of #18272.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Well. I notice that these three files are still not ported to a markdown file:

* [Pulsar Documentation Writing Style Guide](https://docs.google.com/document/d/1lc5j4RtuLIzlEYCBo97AC8-U_3Erzs_lxpkDuseU0n4/edit#)
* [Pulsar Design Style Guide](https://docs.google.com/document/d/16Hp7Sc86MQtL0m8fc2w_TrcKXAuglwRwHmdmwfk00mI/edit#heading=h.b8ogodj5sj0)
* [Pulsar API Documentation Guide](https://docs.google.com/document/d/1-I1oQp1_HUaQopqilU-JdC-ksrLAgYNi93FZVnECwV8/edit#heading=h.wu6ygjne8e35)

cc @Anonymitaet do you have a plan to migrate them? For example:

1. Pulsar API Documentation Guide can be merged with `Documentation Contribution Guide` as the latter contains a section talking about the api/reference page.
2. Pulsar Design Style Guide may be merged into the syntax guide or be ported as a lightweight new page.
3. Pulsar Documentation Writing Style Guide seems a heavyweight page to migrate.

**Comment by Anonymitaet** [comment]
1. `Pulsar API Documentation Guide` can be ignored temporarily since it does not have much content. I'll add more content if I have more in the future.

2. `Pulsar Design Style Guide` should be a separate guide on an independent page, it has nothing to do with the syntax guide.

3. Yes, it's a large one and updated continuously.

**Comment by tisonkun** [comment]
This can be referred to https://github.com/apache/pulsar/issues/13288. I'm trying to pick up this issue in this month.

**Comment by tisonkun** [comment]
https://github.com/apache/pulsar/issues/18272#issuecomment-2053889607
