### ISSUE TITLE
[Doc] 

### ISSUE THREAD

**Issue by startjava** [apache/pulsar#18301]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/next/concepts-messaging/#subscriptions

“In the diagram below, Consumer A is the master consumer while Consumer B would be the next consumer in line to receive messages if Consumer B is disconnected.”

Can you optimize this paragraph? I feel I can't understand it now

@Anonymitaet @momo-jun 

### What is your suggestion?

?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by momo-jun** [comment]
I think there is a typo error out there. It should be like this:

“In the diagram below, Consumer A is the master consumer while Consumer B would be the next consumer in line to receive messages if Consumer **A** is disconnected.”

@startjava Thanks for reporting this issue. Would you like to fix it?

**Comment by startjava** [comment]
@momo-jun  no , thank you ! please you fix it !

**Comment by nilanjanH** [comment]
@startjava - Would love to work on this issue. 
Thanks.

**Comment by Xuanwo** [comment]
Although this issue has been triaged, I still suggest the update this issue's title to reflect the real problem.

**Comment by tisonkun** [comment]
@startjava please try to fill a expressive issue title the next time you report one.
