### ISSUE TITLE
[cleanup] Avoid unnessary method call if txn disabled.

### ISSUE THREAD

**Issue by lifepuzzlefun** [apache/pulsar#18324]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Avoid unnessary method call if txn disabled.

### Solution

check before method called although we have `TransactionBufferDisable` which i think a little help for performance.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Closed. See also https://github.com/apache/pulsar/pull/18323#issuecomment-1342490892.
