### ISSUE TITLE
[Doc] Unable to get a permanent link to current Pulsar version docs

### ISSUE THREAD

**Issue by visortelle** [apache/pulsar#18355]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The current version of Pulsar is 2.10.2

Let's say, I read some specific article and want to put a link to the specific version of this article in our company's internal documentation.

<img width="884" alt="Screenshot 2022-11-06 at 11 52 32 AM" src="https://user-images.githubusercontent.com/9302460/200166591-c852c592-8a8d-43f3-a342-90944e16d297.png">

In the case of the previous version, I can use such link:

https://pulsar.apache.org/docs/2.9.x/tiered-storage-overview/

<img width="914" alt="Screenshot 2022-11-06 at 11 56 51 AM" src="https://user-images.githubusercontent.com/9302460/200166764-66f3dd4a-57e9-4831-b492-86e23c40a760.png">

In the case of the current version I see `Not found` page:

<img width="669" alt="Screenshot 2022-11-06 at 11 59 05 AM" src="https://user-images.githubusercontent.com/9302460/200166857-ba0187ed-68bc-4bc7-b6e1-2ec194c5f27a.png">

### What is your suggestion?

The documentation of the current Pulsar version should be available on both paths:

- Canonical URL like https://pulsar.apache.org/docs/tiered-storage-overview/
- Versioned URL like https://pulsar.apache.org/docs/2.10.x/tiered-storage-overview/

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by momo-jun** [comment]
@visortelle thanks for filing this issue. I think it's somehow duplicated with https://github.com/apache/pulsar/issues/17438. Is it the same request?

**Comment by visortelle** [comment]
Yes, it’s a duplicate.
Closing.

**Comment by tisonkun** [comment]
@visortelle this has been fixed now. You're welcome to verify it.

**Comment by visortelle** [comment]
@tisonkun thank you! 
I confirm that it works, but I see another bug now: https://github.com/apache/pulsar/issues/18479
