### ISSUE TITLE
[Bug] The msgBacklog has a large impact on broker memory usage

### ISSUE THREAD

**Issue by shenweiran** [apache/pulsar#18381]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.9.3

### Minimal reproduce step

There is a namespace msgBacklog that was added in the last two days

### What did you expect to see?

My guess is that msgBacklog should only be a static value, since no client is consuming it and there is no impact on broker performance.

### What did you see instead?

![image](https://user-images.githubusercontent.com/1320933/200473271-9c5efe99-0aa9-4972-8978-a773fd60c964.png)

After executing the command ：after clear back-log pulsar-admin topics clear-backlog ...
![image](https://user-images.githubusercontent.com/1320933/200473507-df0237e1-f719-4389-b6d5-1547107962b9.png)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by leizhiyuan** [comment]
maybe you can do a heap dump ? so we can see why

**Comment by shenweiran** [comment]
ok
