### ISSUE TITLE
[Bug] [Dockerfile build] Malformed entry 3 in list file /etc/apt/sources.list (URI parse)

### ISSUE THREAD

**Issue by nullscript** [apache/pulsar#18442]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

OS: win10
Java: 18.0.2.1
maven: 3.8.6
WSL2: Ubuntu-20.04
docker: 4.13.1

### Minimal reproduce step

after sucessfully running 
`mvn clean install -DskipTests`
run
`mvn package -Pdocker,-main -am -pl docker/pulsar-all -DskipTests`

get this errors

### What did you expect to see?

Build sucess

### What did you see instead?

![image](https://user-images.githubusercontent.com/84658856/201504529-6b99f1c8-e245-45b6-8f36-71624070d6c1.png)

### Anything else?

I run this `sed `command in my wsl2, and `apt-get update`, it works fine.
I don't know why it gets (uri parse) error in dockerfile.
I modified this `sed` command in many ways, it all failed.
I just annotated this `sed `command, it works fine, and get ` build success` info
Seems something is wrong with sed command line

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Error code 100 is generally about network failure. Retry or setting another mirror proxy via `UBUNTU_MIRROR=` would help.

**Comment by tisonkun** [comment]
Closed as no response.
