### ISSUE TITLE
[Doc] Does this "cluster-specific" represent the zk cluster?

### ISSUE THREAD

**Issue by startjava** [apache/pulsar#18460]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/concepts-architecture-overview/

One or more brokers handles and load balances incoming messages from producers, dispatches messages to consumers, communicates with the Pulsar configuration store to handle various coordination tasks, stores messages in BookKeeper instances (aka bookies), relies on a cluster-specific ZooKeeper cluster for certain tasks, and more.

doc：
cluster-specific ZooKeeper cluster
Can it be simplified to:
relies on a ZooKeeper cluster for certain tasks, and more.

@momo-jun 

### What is your suggestion?

？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by startjava** [comment]
cluster-specific represent ZooKeeper cluster?
cluster-specific represent Pulsar cluster?
cluster-specific represent BookKeeper cluster?

**Comment by momo-jun** [comment]
The paragraph starts with `In a Pulsar cluster` so I think it represents a Pulsar cluster. 
What you are suggesting is also correct. The difference is the original sentence adds an emphasis on the 1-on-1, that is, one ZooKeeper cluster serves a specific Pulsar cluster. Hope it helps.
> relies on a ZooKeeper cluster for certain tasks, and more.

**Comment by startjava** [comment]
@momo-jun thank you very much !
