### ISSUE TITLE
[Doc] A configuration store quorum stores configuration，what mean ?

### ISSUE THREAD

**Issue by startjava** [apache/pulsar#18468]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/next/concepts-architecture-overview/#metadata-store

A configuration store quorum stores configuration for tenants, namespaces, and other entities that need to be globally consistent.

bottom text:
“A configuration store quorum stores configuration”
I don't understand. What does the whole thing mean?

i understand “ tenants, namespaces, and other entities that need to be globally consistent.”

but before I don't understand。

@momo-jun 

thank you !

### What is your suggestion?

?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by startjava** [comment]
配置存储仲裁的结果，存储租户、命名空间和其它实体需要全局一致性的配置。
Can you translate it that way

**Comment by startjava** [comment]
configuration represent what ??

configuration is Configuration.java??

**Comment by startjava** [comment]
or 
"配置存储仲裁的结果，配置存储租户、命名空间和其它实体需要全局一致性的配置。"
can this ?

**Comment by momo-jun** [comment]
> A configuration store quorum stores configuration for tenants, namespaces, and other entities that need to be globally consistent.

This sentence introduces two meanings:
* The configurations for tenants, namespaces, and other entities need to be globally consistent.
* These configurations are stored in a configuration store quorum.

**Comment by startjava** [comment]
thank you very much !
