### ISSUE TITLE
[Doc] Bug - Missing slash in link generated by the version switcher dropdown

### ISSUE THREAD

**Issue by visortelle** [apache/pulsar#18479]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

`Not found` page as result:

https://user-images.githubusercontent.com/9302460/201922226-1869cfbb-40ba-4553-8dc8-be212016028e.mov

### What is your suggestion?

to fix it :)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
I notice it just now. I made the bug and fixed at https://github.com/apache/pulsar-site/commit/9bff0fe0e46a6ec971be6ae98eb609f3e0d7f98f :)

**Comment by visortelle** [comment]
Cool!
