### ISSUE TITLE
[site][fix] Display issues on Reference site 

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#18495]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

We (@tisonkun) have found some issues on the [Pulsar Reference Site](https://pulsar.apache.org/reference/#/next/).

/cc @SignorMercurio @urfreespace 

There are other tricky issues with the site navigation. 
Try to clear the cache and re-visit to see if those issues exist.
If still have, feel free to add your suggestions under this issue, thanks! 

/cc @momo-jun @DaveDuggins @D-2-Ed 

### 1. Fix 404 issues
https://pulsar.apache.org/reference/#/next/client/client-libraries-java
<img width="854" alt="image" src="https://user-images.githubusercontent.com/50226895/202121013-db55e2d4-4cb1-43f1-b6aa-892ea0232441.png">

#### 2.1 Remove this for 2.6.x, 2.7.x, 2.8.x, 2.9.x
https://pulsar.apache.org/reference/#/2.9.x/config/reference-configuration
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/50226895/202120334-e3f301d1-4b7a-42a5-bc39-4167c78ea426.png">

#### 2.2 Remove this for 2.6.x, 2.7.x, 2.8.x, 2.9.x
https://pulsar.apache.org/reference/#/2.6.x/client/client-libraries-java
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/50226895/202120858-6ce0d94f-56d5-4015-b0dd-3be66c3ae02f.png">

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Issue 1 has been fixed. I'm looking into Issue 2s in this week.
