### ISSUE TITLE
[Doc] Improve Pulsar Pub/Sub Throttling Doc

### ISSUE THREAD

**Issue by heesung-sn** [apache/pulsar#18506]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The current documentation about Pulsar message pub/sub throttling is insufficient. 

### What is your suggestion?

- Have a central page about Pulsar message throttling.
- Explain the goal of Pulsar message throttling.
- Explain how and where Pulsar throttling works.
- Explain what configs and admin APIs are available to set throttling.
- Explain how throttling broker configs and admin APIs are working together if they are configured at the same time. (explain config-adminAPI compatibility)
- Explain how throttling works with different features: message batching, compression, chunking, backlog, non-durable topics, partitions, replicas, entry filter, flink, sink/source, functions, offload and etc. (explain feature compatibility)
- Explain how throttling can be monitored
- Give example setups for best throttling practices

### Any reference?

https://pulsar.apache.org/docs/2.10.x/admin-api-namespaces/#configure-dispatch-throttling-for-topics

pulsar % grep Throttling conf/broker.conf
topicPublisherThrottlingTickTimeMillis=10
brokerPublisherThrottlingTickTimeMillis=50
brokerPublisherThrottlingMaxMessageRate=0
brokerPublisherThrottlingMaxByteRate=0
subscribeThrottlingRatePerConsumer=0
dispatchThrottlingRateInMsg=0
dispatchThrottlingRateInByte=0
dispatchThrottlingRatePerTopicInMsg=0
dispatchThrottlingRatePerTopicInByte=0
dispatchThrottlingOnBatchMessageEnabled=false
dispatchThrottlingRatePerSubscriptionInMsg=0
dispatchThrottlingRatePerSubscriptionInByte=0
dispatchThrottlingRatePerReplicatorInMsg=0
dispatchThrottlingRatePerReplicatorInByte=0
dispatchThrottlingRateRelativeToPublishRate=false
dispatchThrottlingOnNonBacklogConsumerEnabled=true
dispatchThrottlingForFilteredEntriesEnabled=false

Secondary configs that could be related to throttling behavior:
dispatcherMaxReadBatchSize
avgMessagesPerEntry

Pulsar-admin brokers update-dynamic-config --config dispatcherMaxReadBatchSize —value 100

Some references regarding the above configs:
https://github.com/apache/pulsar/pull/5710
https://github.com/apache/pulsar/pull/11325
https://github.com/apache/pulsar/pull/2977
https://github.com/apache/pulsar/pull/754
https://github.com/apache/pulsar/pull/4273
https://github.com/apache/pulsar/pull/5804
https://github.com/apache/pulsar/pull/12294
https://github.com/apache/pulsar/pull/17686

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Hongten** [comment]
I think [this document](https://pulsar.apache.org/docs/2.10.x/admin-api-namespaces/#configure-dispatch-throttling-for-topics) is very SIMPLE. The document doesn't show us how to verify the throttle, just call the `get-...` API to show the values which come from the ZK(We can tell users we save these throttling values with the exact path in ZK, right?). 

So there are some suggestions you can refer to
- How to set the publish rate? How to verify it(e.g. we can refer to some metrics `pulsar_throughput_in`)? Based on my test, it seems not to work when I set the publish rate(both bytes and message).
- How to set the dispatch rate? How to verify it(e.g. we can refer to some metrics `pulsar_throughput_out`)?
- What's the difference when we set broker, topic publish/dispatch rate?
- What's the difference between setting publish/dispatch rate and setting a sourcegroup(Please refer to `[PIP-82](https://github.com/apache/pulsar/wiki/PIP-82:-Tenant-and-namespace-level-rate-limiting)`)?


For the sourcegroup. I have some test results, which show the sourcegroup throttling does not work exactly.
A: Only set the message publish rate = 100. One message size = 1024. However, the result is 14.7MB/s. The excepted result is 1MB/s.
`bin/pulsar-admin resourcegroups create rs_name --msg-publish-rate 100`
![image](https://user-images.githubusercontent.com/3076703/204990081-576ed2a8-9f34-45b3-938c-f521a3bfc4be.png)

B: Only set the byte publish rate = 10000(1MB). One message size = 1024. However, the result is 11MB/s. The excepted result is 1MB/s.
`bin/pulsar-admin resourcegroups create rs_name --byte-publish-rate 10000`
![image](https://user-images.githubusercontent.com/3076703/204990861-370ca096-4544-4d1b-807f-728f947cb7b9.png)

Thanks
Hongten
