### ISSUE TITLE
[PulsarStandalone]The PulsarStandalond mode allows you to configure multiple brokers and multiple bookie launches.

### ISSUE THREAD

**Issue by mingyifei** [apache/pulsar#18515]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

To facilitate testing of broker functions, such as topic ownership transfer, simulating outages in extreme scenarios, etc.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by labuladong** [comment]
For now standalone can start multiple bookies with `--num-bookies`, try this for more information:

```shell
./bin/pulsar standalone --help
```

And I think this is a good suggestion to explore Pulsar locally if we can start multiple brokers. But seems it's not supported now.

**Comment by tisonkun** [comment]
Closed as answered.
