### ISSUE TITLE
[Doc] centos8 seq command -t error !

### ISSUE THREAD

**Issue by startjava** [apache/pulsar#18517]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/next/getting-started-standalone/#write-some-more-messages

bin/pulsar-client produce my-topic --messages "$(seq -s, -f 'Message NO.%g' -t '\n' 1 10)"

CentOS8 has error：
[ghy@localhost bin]$ pwd
/home/ghy/T/apache-pulsar/bin
[ghy@localhost bin]$ ./pulsar-client produce my-topic --messages "$(seq -s, -f 'Message NO.%g' -t '\n' 1 10)"
seq: 不适用的选项 -- t
请尝试执行 "seq --help" 来获取更多信息。

use bottom command run ok：
./pulsar-client produce my-topic --messages "$(seq -s, -f 'Message NO.%g' 1 10)"

### What is your suggestion?

?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by labuladong** [comment]
Seems `-t` option is only for macOS:

```bash
-t string, --terminator string
     Use string to terminate sequence of numbers.  The string can contain character escape sequences in backslash notation as
     defined in ANSI X3.159-1989 (“ANSI C89”).  This option is useful when the default separator does not contain a \n.
```

It's reasonable to remove this option in doc for common Linux.
