### ISSUE TITLE
[Enhancement] Only print 4xx RestException message without stacktrace in broker log.

### ISSUE THREAD

**Issue by lifepuzzlefun** [apache/pulsar#18541]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

i think for 4xx http response code relate exception. stack can be avoid in error log.

<img width="1555" alt="image" src="https://user-images.githubusercontent.com/13600283/202673843-761d57fe-854b-4c21-b476-70add38e76cf.png">

### Solution

drop stack trace if RestException in 4xx family.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Closed as won't do. If we have a real-world case that this trace overwhelms prod logs, we may review this proposal.
