### ISSUE TITLE
Remove `Timeline` since there's no clear plan

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#18614]

**Comment by tisonkun** [comment]
"Coming soon" is easy to be a liar. I don't find any clear plan or contributors active working on this page: https://pulsar.apache.org/release-notes/timeline

If there's any, I'm happy to close this issue and follow that initiative.

**Comment by tisonkun** [comment]
cc @Anonymitaet @dave2wave

**Comment by Anonymitaet** [comment]
> "Coming soon" is easy to be a liar. I don't find any clear plan or contributors active working on this page: https://pulsar.apache.org/release-notes/timeline
> 
> If there's any, I'm happy to close this issue and follow that initiative.

OK
