### ISSUE TITLE
[Doc] 404 URL for openssl.cnf example

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#18656]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

There are many url like `wget https://raw.githubusercontent.com/apache/pulsar-site/main/site2/website/static/examples/openssl.cnf` link to the openssl.cnf. But this file was deleted at https://github.com/apache/pulsar-site/pull/215.

### What is your suggestion?

* Restore the openssl.cnf file
* Fix the URL link

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by michaeljmarshall** [comment]
Is the file here: https://raw.githubusercontent.com/apache/pulsar-site/main/site2/website-next/static/examples/openssl.cnf?

**Comment by michaeljmarshall** [comment]
Here is the stable link: https://pulsar.apache.org/examples/openssl.cnf. I wouldn't recommend linking to anything in the `pulsar-site` github repo.

**Comment by tisonkun** [comment]
I second @michaeljmarshall's comment and already commented at https://github.com/apache/pulsar-site/pull/307#pullrequestreview-1196819268.

**Comment by RobertIndie** [comment]
@michaeljmarshall @tisonkun I didn't notice that we already have the link  https://pulsar.apache.org/examples/openssl.cnf. I agree we shouldn't link to the GitHub repo. And I created a PR to fix all that 404 links: https://github.com/apache/pulsar/pull/18667. PTAL. Thanks.

I'm curious about where the source file for this link(https://pulsar.apache.org/examples/openssl.cnf) is maintained.

**Comment by michaeljmarshall** [comment]
The source that is put on the website is https://github.com/apache/pulsar-site/blob/main/site2/website-next/static/examples/openssl.cnf. Note that the file is copied to the `asf-site-next` branch when updates are published. Here is the current version that is available on the website: https://github.com/apache/pulsar-site/blob/f699156eaa2d39bbd999387a00163288f1dbfeb6/content/examples/openssl.cnf. 

The files in the `static` directory map directly to the website as static files.
