### ISSUE TITLE
Add Javascript/Nodejs runtime environment for Functions

### ISSUE THREAD

**Issue by wmelton** [apache/pulsar#18678]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

The documentation for Functions shows existing support for Java, Python, & Go, but no current support for nodejs based Functions. Given the enormity of the JS community, it would seem like a huge value-add to support JS Functions, especially for folks looking for open source alternatives to AWS Lambdas.

### Solution

If someone on the core team can help me get up to speed on how the current Python/Go Function runtimes are  built within the Pulsar library, I would be happy to submit a PR to enable Javascript runtime for Functions.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
cc @fantapsody @nlu90 @freeznet

**Comment by nlu90** [comment]
@wmelton Thanks for your suggestion.

You can start by checking the python instance implementation:
https://github.com/apache/pulsar/tree/master/pulsar-functions/instance/src/main/python

If you have further question, feel free to leave comments here. We are glad to help you out.

**Comment by tisonkun** [comment]
Move to discussions since it's no more than an idea.
