### ISSUE TITLE
Flaky-test: ShadowTopicTest.testShadowTopicConsuming

### ISSUE THREAD

**Issue by coderzc** [apache/pulsar#18705]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3571079392/jobs/6002742031#step:10:1118

### Exception stacktrace

<details>
<summary>Full exception stacktrace</summary>
<pre><code>
    Error:  Tests run: 24, Failures: 1, Errors: 0, Skipped: 20, Time elapsed: 27.066 s <<< FAILURE! - in org.apache.pulsar.broker.service.persistent.ShadowTopicTest
  Error:  testShadowTopicConsuming(org.apache.pulsar.broker.service.persistent.ShadowTopicTest)  Time elapsed: 6.247 s  <<< FAILURE!
  java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.client.api.Message.getMessageId()" because "msg" is null
  	at org.apache.pulsar.broker.service.persistent.ShadowTopicTest.testShadowTopicConsuming(ShadowTopicTest.java:155)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
</code></pre>
</details>

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by labuladong** [comment]
I reproduced this bug locally, seems something didn't replicate correctly.

Some information:

```shell
$ ./bin/pulsar-admin topics stats-internal sourceTopic-shadow
{
  "entriesAddedCounter" : 0,
  "numberOfEntries" : 0,
  "totalSize" : 0,
  "currentLedgerEntries" : 0,
  "currentLedgerSize" : 0,
  "lastLedgerCreatedTimestamp" : "1970-01-01T08:00:00+08:00",
  "waitingCursorsCount" : 1,
  "pendingAddEntriesCount" : 1,
  "lastConfirmedEntry" : "120:-1",
  "state" : "LedgerOpened",
  "ledgers" : [ {
    "ledgerId" : 120,
    "entries" : 0,
    "size" : 0,
    "offloaded" : false,
    "underReplicated" : false
  } ],
  "cursors" : {
    "sub" : {
      "markDeletePosition" : "120:-1",
      "readPosition" : "120:0",
      "waitingReadOp" : true,
      "pendingReadOps" : 0,
      "messagesConsumedCounter" : 0,
      "cursorLedger" : -1,
      "cursorLedgerLastEntry" : -1,
      "individuallyDeletedMessages" : "[]",
      "lastLedgerSwitchTimestamp" : "2022-12-02T13:23:58.878+08:00",
      "state" : "NoLedger",
      "active" : true,
      "numberOfEntriesSinceFirstNotAckedMessage" : 1,
      "totalNonContiguousDeletedMessagesRange" : 0,
      "subscriptionHavePendingRead" : true,
      "subscriptionHavePendingReplayRead" : false,
      "properties" : { }
    }
  }
}


$ ./bin/pulsar-admin topics stats-internal sourceTopic
{
  "entriesAddedCounter" : 1,
  "numberOfEntries" : 1,
  "totalSize" : 43,
  "currentLedgerEntries" : 1,
  "currentLedgerSize" : 43,
  "lastLedgerCreatedTimestamp" : "2022-12-02T13:23:58.934+08:00",
  "waitingCursorsCount" : 1,
  "pendingAddEntriesCount" : 0,
  "lastConfirmedEntry" : "122:0",
  "state" : "LedgerOpened",
  "ledgers" : [ {
    "ledgerId" : 122,
    "entries" : 0,
    "size" : 0,
    "offloaded" : false,
    "underReplicated" : false
  } ],
  "cursors" : {
    "pulsar.repl-sourceTopic-shadow" : {
      "markDeletePosition" : "120:-1",
      "readPosition" : "122:1",
      "waitingReadOp" : true,
      "pendingReadOps" : 0,
      "messagesConsumedCounter" : 0,
      "cursorLedger" : -1,
      "cursorLedgerLastEntry" : -1,
      "individuallyDeletedMessages" : "[]",
      "lastLedgerSwitchTimestamp" : "2022-12-02T13:23:58.749+08:00",
      "state" : "Open",
      "active" : true,
      "numberOfEntriesSinceFirstNotAckedMessage" : 2,
      "totalNonContiguousDeletedMessagesRange" : 0,
      "subscriptionHavePendingRead" : false,
      "subscriptionHavePendingReplayRead" : false,
      "properties" : { }
    }
  }
}

```

**Comment by codelipenghui** [comment]
+1

https://github.com/apache/pulsar/actions/runs/3599845456/jobs/6063986976
