### ISSUE TITLE
[Bug][CI] `CodeCov` should wait all tests pass

### ISSUE THREAD

**Issue by labuladong** [apache/pulsar#18713]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Master branch.

### Minimal reproduce step

I noticed that `CodeCov` always runs even if CI failed due to flaky tests. For example, see https://github.com/apache/pulsar/pull/18701.

### What did you expect to see?

Codecov report should be commented after all tests are passed.

### What did you see instead?

If CI failed, the coverage report will be inaccurate and useless.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by labuladong** [comment]
cc @yaalsn

**Comment by yaalsn** [comment]
- Flaky tests is a allow-failure job, and will not block the CI.
- If `CodeCov` run with flaky test group, then the code coverage will not be accurate.
- `CodeCov` can update the code coverage after CI success.

So there's no need to wait all tests pass.

**Comment by labuladong** [comment]
If there is any test failed, the coverage report is meaningless. To save CI resources, can we let CodeCov run only when all tests pass?

**Comment by yaalsn** [comment]
`CodeCov` runs together with every test, so it doesn't waste any CI resources.
