### ISSUE TITLE
[Doc] customizing log levels for java functions is not clear

### ISSUE THREAD

**Issue by vagetablechicken** [apache/pulsar#18861]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

Following the step 1 https://github.com/apache/pulsar/blob/0d707aec92595868192380758a46f8f02886128f/site2/docs/functions-develop-log.md?plain=1#L57-L64
I've changed the property `pulsar.log.level` to debug in `functions_log4j2.xml`.

But the step 2 is confused. The root log level is hard code in file https://github.com/apache/pulsar/blob/ac7a34fe757fd8acaf7b87aac427b9e515b0aa7c/conf/functions_log4j2.xml#L123

But the doc says the level is `${sys:pulsar.log.level}`
https://github.com/apache/pulsar/blob/0d707aec92595868192380758a46f8f02886128f/site2/docs/functions-develop-log.md?plain=1#L66-L76

So I forgot to change the root log level, can't get the debug level log, spent so mujch time to debug.

### What is your suggestion?

If we should change the root logger level, the doc should remind us. Or can we change the root logger level to `${sys:pulsar.log.level}`?

Or perhaps it should be `${sys:pulsar.log.root.level}`, like 
https://github.com/apache/pulsar/blob/0d707aec92595868192380758a46f8f02886128f/conf/log4j2.yaml#L134-L141

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by RobertIndie** [comment]
@vagetablechicken Thanks for your issue!
@freeznet Could you take a look at this issue? I think it may be the log configuration issue that we need to fix.

**Comment by freeznet** [comment]
@vagetablechicken nice catch and I see you have checked the ` I'm willing to submit a PR!` box, so I will assign this task to you.
