### ISSUE TITLE
[Bug] pulsarctl library does not have any option of backlog type option.

### ISSUE THREAD

**Issue by jyoti112** [apache/pulsar#18879]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

v2.8.3.2
https://github.com/streamnative/pulsarctl/releases/download/v2.8.3.2/pulsarctl-amd64-linux.tar.gz

### Minimal reproduce step

/home/pulsar/pulsarctl-amd64-linux/pulsarctl namespaces set-backlog-quota --limit-size 1G --limit-time  3600 type "message age" --policy producer_request_hold <namespace_name> --token  --admin-service-url  --tls-allow-insecure

### What did you expect to see?

Backlog has to set with the corresponding topic. 

### What did you see instead?

<img width="783" alt="Capture11" src="https://user-images.githubusercontent.com/8852175/206919712-35054c46-1206-4f64-8e04-555dcfdf5978.PNG">

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by mattisonchao** [comment]
Refer https://github.com/streamnative/pulsarctl

**Comment by jyoti112** [comment]
https://github.com/streamnative/pulsarctl/issues/914

**Comment by tisonkun** [comment]
Closed as superseded by https://github.com/streamnative/pulsarctl/issues/914.
