### ISSUE TITLE
[Client] Drop jcommander dependency in Pulsar java client

### ISSUE THREAD

**Issue by syhily** [apache/pulsar#18932]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Pulsar add the `jcommander` as dependency in `pulsar-common` module, but it should be an optional dependency because most people don't need it in client side.

### Solution

Make the `jcommander` in `pulsar-common` with `<optional>true</optional>`.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
I agree. Actually, this can be a bad design since the CLI tools is used for generating docs only. We may totally move the functionalities to `pulsar-client-tools` related modules.

cc @nicoloboschi @urfreespace @SignorMercurio

**Comment by tisonkun** [comment]
A test script to guard this refactor if it happens is [reference-doc-generator.py](https://github.com/apache/pulsar-site/tree/main/tools/pytools#reference-doc-generator) in the site repo.

**Comment by tisonkun** [comment]
We may move out these classes to a dedicated module.

One class needs more consideration is `org.apache.pulsar.client.impl.conf.CmdGenerateDocumentation` in `pulsar-client-original`. It depends on jcommander transitively. And its FQN is referred by [reference-doc-generator.py](https://github.com/apache/pulsar-site/tree/main/tools/pytools#reference-doc-generator) in the site repo.

Either we move it to another module while keep its FQN, or we should update the FQN and do some compatibility logics in the pytools in the site repo.

**Comment by etcZYP** [comment]
assign to me

**Comment by tisonkun** [comment]
@etcZYP Assigned. Go ahead!

... and feel free to ask if you are uncertain.

**Comment by etcZYP** [comment]
> @etcZYP Assigned. Go ahead!
> 
> ... and feel free to ask if you are uncertain.

can you plz tell me which branch should i merge into?

**Comment by tisonkun** [comment]
@etcZYP I think you should directly send a patch against the master branch.

**Comment by jak78** [comment]
Hello @etcZYP ! Are you still working on this issue?

**Comment by tisonkun** [comment]
Unassign the previous inactive assignee. @jak78 Would you like to take over this issue?

**Comment by jak78** [comment]
OK I'll try to fix it by next week

**Comment by tobehardest** [comment]
Maybe I can try to see if I can solve this, can you assign it to me?

**Comment by tisonkun** [comment]
@tobehardest there are three assignees from then here. I suggest you make a patch and I'll be glad to review and assign this ticket to you.

Also cc @jak78 do you still work on this ticket?

**Comment by jak78** [comment]
@tobehardest I’m glad you can make it, you can go ahead. Thanks!

**Comment by tisonkun** [comment]
I remove part of the usage in https://github.com/apache/pulsar/pull/20700, while there are still several others. What a mess 🤣.

**Comment by tisonkun** [comment]
Extend #20700 to fix this issue.
