### ISSUE TITLE
[Doc] Deploy docker-compose command is incorrect

### ISSUE THREAD

**Issue by luweiqianyi** [apache/pulsar#18952]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

docker-compose.yaml in this url "https://pulsar.apache.org/docs/next/deploy-docker/#deploy-a-cluster-by-using-docker-composeyaml" cannot be deployed on docker. Maybe the format is error,please fix it!

### What is your suggestion?

Before offerring  some configure file on website,please do some test to make sure it works

### Any reference?

https://pulsar.apache.org/docs/next/deploy-docker/#deploy-a-cluster-by-using-docker-composeyaml

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
@luweiqianyi could you attach the error log when running `docker-compose up -d`?

**Comment by liangyepianzhou** [comment]
@luweiqianyi Thanks for your pointing this out. I have fixed it.
https://github.com/apache/pulsar/pull/18994

**Comment by tisonkun** [comment]
@liangyepianzhou Cool!

**Comment by luweiqianyi** [comment]
@liangyepianzhou  when using key words "depends_on" ,as below":
```
    depends_on:
      zookeeper:
        condition: service_healthy
```
my goland reports error: "Array is required. Scalar value expected" . Is this configuration correct?

**Comment by luweiqianyi** [comment]
@liangyepianzhou version: '3' in docker-compose.yml is not correct! 版本不对 是不是你使用
```
depends_on:
      zookeeper:
        condition: service_health
```这种写法时这个dokcer-compose.yml的最低版本支持是多少？我换成3.9就没有上面的报错了

pulsar-init这个容器启动不了，启动就关闭
