### ISSUE TITLE
[Doc] Java Client Cluster-Level Failover sample code

### ISSUE THREAD

**Issue by mnit016** [apache/pulsar#19073]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

I see that in documents 2.10.x, part **[Java Client - Cluster-level Failover](https://pulsar.apache.org/docs/2.10.x/client-libraries-java/#cluster-level-failover)**
The sample code looks difference with the real API
**secondaryTlsTrustCertsFilePath** expects a Map<String,String>, but there's just a String
**secondaryAuthentication** expects a Map<String, Authen>, but there's both String.

![image](https://user-images.githubusercontent.com/37934995/209639886-6b147126-230a-4c82-a5cf-27b660164586.png)

### What is your suggestion?

So what's exactly I need to put to? What is the **key** in Map should be?
Could someone please point me out what am I missing here
Thanks

### Any reference?

**[Java Client - Cluster-level Failover](https://pulsar.apache.org/docs/2.10.x/client-libraries-java/#cluster-level-failover)**

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by momo-jun** [comment]
@labuladong @hangc0276 can you pls take a look at this question?

**Comment by labuladong** [comment]
Sorry, I missed this issue. I'll fix this error.
