### ISSUE TITLE
[Bug] The master branch cannot build docker image

### ISSUE THREAD

**Issue by yaalsn** [apache/pulsar#19098]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

master

### Minimal reproduce step

```
mvn clean install -DskipTests
mvn package -Pdocker,-main -am -pl docker/pulsar-all -DskipTests
```

### What did you expect to see?

Build docker image successfully

### What did you see instead?

```bash
Error:  DOCKER> Unable to build image [pulsar] : "The command '/bin/sh -c sed -i \"s|http://archive\\.ubuntu\\.com/ubuntu/|${UBUNTU_MIRROR:-mirror://mirrors.ubuntu.com/mirrors.txt}|g\" /etc/apt/sources.list      && echo 'Acquire::http::Timeout \"30\";\\nAcquire::ftp::Timeout \"30\";\\nAcquire::Retries \"3\";' > /etc/apt/apt.conf.d/99timeout_and_retries      && apt-get update      && apt-get -y dist-upgrade      && apt-get -y install --no-install-recommends netcat dnsutils less procps iputils-ping                  python3 python3-kazoo python3-pip                  curl ca-certificates wget apt-transport-https' returned a non-zero code: 100"  ["The command '/bin/sh -c sed -i \"s|http://archive\\.ubuntu\\.com/ubuntu/|${UBUNTU_MIRROR:-mirror://mirrors.ubuntu.com/mirrors.txt}|g\" /etc/apt/sources.list      && echo 'Acquire::http::Timeout \"30\";\\nAcquire::ftp::Timeout \"30\";\\nAcquire::Retries \"3\";' > /etc/apt/apt.conf.d/99timeout_and_retries      && apt-get update      && apt-get -y dist-upgrade      && apt-get -y install --no-install-recommends netcat dnsutils less procps iputils-ping                  python3 python3-kazoo python3-pip                  curl ca-certificates wget apt-transport-https' returned a non-zero code: 100" ]
```

### Anything else?

I did the test in Azure self-hosted runner and Github hosted runner, after the apt mirror removed from Dockerfile, the image can be built successfully. 

The mirror is imported in this PR https://github.com/apache/pulsar/pull/14095 

@lhotari Could you take a look at this?  It seems that the mirror is unstable and I think It's better to use the official apt source.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
error code 100 is timeout from ubuntu pkg registry IIRC.

**Comment by yaalsn** [comment]
This issue can be closed as we can use `UBUNTU_MIRROR` to point the right one.
