### ISSUE TITLE
[Doc] Mount client version to the latest release version

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#19121]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

According to https://github.com/apache/pulsar-site/pull/352#issuecomment-1368228919, we don't release any more new versions for C++ and Python clients. That means the `@pulsar:version@` placeholder will generate incorrect results for the maintained versions (2.8~2.10).

### What is your suggestion?

Since no more new versions will be released, we can replace the placeholder with resolved fixed versions.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by BewareMyPower** [comment]
2.10.2, 2.9.4 and 2.8.4.

C++ RPM and DEB packages can be found here: https://archive.apache.org/dist/pulsar/

For example, you can found the `DEBS/` and `RPMS/` directories under https://archive.apache.org/dist/pulsar/pulsar-2.10.2/

Python wheels can be found here: https://pypi.org/manage/project/pulsar-client/releases/
