### ISSUE TITLE
PIP-240: A new API to unload subscriptions

### ISSUE THREAD

**Issue by poorbarcode** [apache/pulsar#19187]
### Motivation

We sometimes try to unload the topic to resolve some consumption-stop issues. But the unloading topic will also impact the producer side.

### Goal

Providing a new API to unload the subscription dimension triggers reconnection of all consumers on that subscription and reconnection is guaranteed by the client. The API will be used in these ways:
- unload special subscription of one topic(or partitioned topic)
- unload all subscriptions of one topic(or partitioned topic)
- unload subscriptions of one topic(or partitioned topic) by regular expression
  - If a reader's subscription name is not set, a random subscription name prefixed with 'multiTopicsReader-' or 'reader-' will be used, and users can uninstall these subscriptions using regular expressions. 

In addition to triggering consumer disconnection, Unload Subscribers will restart the Dispatcher, which resets the redeliver message queue and delayed message queue in the Broker's memory, which can help resolve issues caused by an abnormal dispatcher state. However, the execution flow of Unload Subscribers does not include a restart of the Managed Cursor related to this dispatcher; if there is a problem with the cursor, we can only rely on the unload topic to solve it.

Note: From the client's perspective, this connection may be shared by consumers, producers, and transactions, so Unload Subscribers maybe impact the producer and transaction.

#### These scenarios are not supported
- Functions `message-dedup`, `geo-replication,` and `shadow-topic` also read messages from the topic, but Unload Subscribers will not support triggering restarts of these three functions( because the cursor is used directly to read the data in these scenarios, not the consumer or reader ).
- The Compression task(subscription name is `__compaction`) also use a reader to read data, but Unload Subscribers does not support it because this task creates a new reader each time it starts.
- Do not support all topics related to Transaction features.
  - `__transaction_buffer_snapshot` works with the task TB recover,  and this task will create a new reader each time they start.
  - `__transaction_pending_ack` works with the task Transaction Pending Ack Store replay,  and this task will use managed cursor directly to read data.
  - `__transaction_log_xxx` works with the task Transaction Log, which will use managed cursor directly to read data.
  - `transaction_coordinator_assign` No data will be written on this topic.

#### Special system topic supports
The system topic `__change_events` is used to support topic-level policies, there may also be some message delivery issues in this scenario, so Unload Subscribers will support this topic.

##### For topics
```
pulsar-admin topics unload {topic_name} -s {sub_name}
```

##### Explain the param `-s`
- set param `-s` to special sub name to unload special subscription
- set param `-s` to `**` to unload all subscriptions under this topic
- set param `-s` to `regexp` to unload a batch subscriptions under this topic 

##### PersistentTopics.java
```java
/**
 * @subscription The value can be "**" to indicate all subscriptions under the topic of unload, a regular expression to indicate the part of the subscription whose name conforms to the rule of unload, or a specified subscription name
 */
@PUT
@Path("/{tenant}/{namespace}/{topic}/{subscription}/unload")
public void unloadSubscription(String tenant, String namespace, String topic, String subscription);
```

**Comment by eolivelli** [comment]
In my experience if a subscription is stuck, the problems are:
- the client has some problems - 99.9%
- there is a bug in Pulsar - 0.1%

Unloading a topic is an operation that triggers some reset of the state on both the broker and the clients and this usually TEMPORARY unblocks the subscription.

If there is a problem we should spend time on investigating the problem and not in adding this kind of tools.

**Comment by dave2wave** [comment]
I think that the terminology of `unload` is wrong. These are `reset` operations.

**Comment by poorbarcode** [comment]
Hi @eolivelli 

> If there is a problem we should spend time on investigating the problem and not in adding this kind of tools.

You are right. When a user encounters a problem, it often takes a while actually to solve the root cause. It is important to provide a tool to recover services quickly, and cmd 'unload topic' is often used to solve problems temporarily. 

But now a topic can be used by multiple teams, such as Business-team A to produce messages, Business-team B and C to consume messages (each using a different subscription name), and Data-team D to read messages using reader api (using a random subscription name). When there is a consumption problem in subscription B, if we do unload the topic, this will affect teams A, B, C, D, and when we provide a new API to reset subscribers, the impact can be controlled only to affect team B.

So I think a new API is necessary。

Thanks

**Comment by poorbarcode** [comment]
Hi @dave2wave 

> I think that the terminology of unload is wrong. These are reset operations.

already change `unload` to `reset`

**Comment by zbentley** [comment]
As much as I also like `unload`ing topics to resolve mysterious issues, I'd rather pulsar not add additional "band-aid/manual reset" command functionality to work around either misbehaving clients or broker state-corrupting bugs. I think doing that has a short-term benefit of providing a tool for expert operators to use to resolve issues, but has a long-term cost of making brand new adopters of pulsar find it less reliable than they want it to be.

I'm not saying "fix the bugs _instead_" (though we should also fix things!), but rather that building more support code for stuff like this may come at a time/complexity cost with actually fixing the issues that would make a "reset" necessary.
