### ISSUE TITLE
"latest" tag in Docker Hub points to a 6 month old version, but 2.11.0 image is 2 days old

### ISSUE THREAD

**Issue by zbentley** [apache/pulsar#19195]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

"latest" docker image.

### Minimal reproduce step

Navigate to https://hub.docker.com/r/apachepulsar/pulsar/tags

Observe that "latest"'s push date is 6 months ago, and 2.11.0's push date is more recent.

### What did you expect to see?

"Latest" should refer to the latest image. This is a widely-assumed docker convention shared across many, many projects.

### What did you see instead?

"latest" does not refer to the latest image version.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Fixed. Now latest is the same as the latest release (3.0.0)
