### ISSUE TITLE
[Doc] 2.10* docs provide incorrect command for `namespace set-backlog-quota`

### ISSUE THREAD

**Issue by zbentley** [apache/pulsar#19196]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

[This reference](https://pulsar.apache.org/docs/2.10.x/pulsar-admin/#set-backlog-quota) requests the following command:

```bash

pulsar-admin namespaces set-backlog-quota my-tenant/my-ns \
--limitTime 3600 \
--policy producer_request_hold \
--type message_age
```

That command does not work, and results in this error:
`The following option is required: [-l | --limit]`

### What is your suggestion?

1. The command should work.
2. Command examples should be provided that *only* adjust size-based thresholds.
3. Command examples should be provided that *only* adjust time-based thresholds.
4. Command examples should be provided that adjust *both* time- and size-based thresholds.

### Any reference?

https://pulsar.apache.org/docs/2.10.x/pulsar-admin/#set-backlog-quota

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
cc @labuladong @nodece

**Comment by tisonkun** [comment]
Perhaps also place a `--limit 2G` above?

**Comment by zbentley** [comment]
@tisonkun that would make the command valid, but ideally examples would exist for all three limit cases: just size, just time, and both.

**Comment by labuladong** [comment]
> but ideally examples would exist for all three limit cases: just size, just time, and both.

I agree. I think this is a bug in the admin interface, I'll create a pr to fix it.
