### ISSUE TITLE
[Doc] Example Window Function has different names in docs and in the examples folder

### ISSUE THREAD

**Issue by yonigibbs** [apache/pulsar#19299]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The example window function supplied with 2.11 is called `example` (see https://github.com/apache/pulsar/blob/master/pulsar-functions/java-examples/src/main/resources/example-window-function-config.yaml#L22). However in the documentation it expects it to be called `window-example`. See step 3 at https://pulsar.apache.org/docs/2.11.x/functions-quickstart/#start-window-functions, where it asks you to type in this command:

```
bin/pulsar-admin functions get \
   --tenant test \
   --namespace test-namespace \
   --name window-example
```

### What is your suggestion?

Either fix the documentation or the example file supplied with the build. Suggest the latter, as otherwise the other issue is that there's another example called `example`, and if you follow the docs, as I did, and try to install one example function followed by another it fails (the second attempt to create a function fails, as the function already exists from the previous step).

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yonigibbs** [comment]
Found one more thing: the docs around starting window functions (https://pulsar.apache.org/docs/2.11.x/functions-quickstart/#start-window-functions) give these two commands:
```
bin/pulsar-client consume -s test-sub -n 0 test_window_result
```
and
```
bin/pulsar-client produce -m "3" -n 10 test_window_src
```
However in the actual supplied example (see https://github.com/apache/pulsar/blob/master/pulsar-functions/java-examples/src/main/resources/example-window-function-config.yaml#L24-L25) we see this:
```
inputs: ["test_src"]
output: "test_result"
```
Notice the the topic names are different: they're missing the word `window` in their names.

**Comment by nlu90** [comment]
@yonigibbs Thank you for reporting this issue.

I created a PR to fix the example yaml file
