### ISSUE TITLE
SQL HTTP 404 schema not found

### ISSUE THREAD

**Issue by suhoangson** [apache/pulsar#19338]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.10.3

### Minimal reproduce step

i ran sql query for show data from table schema_test

### What did you expect to see?

data from table schema_test

### What did you see instead?

- i want to query data from table schema_test but error happen, while query data from table test is ok
![image](https://user-images.githubusercontent.com/5100961/215104644-0193f451-40f3-4e88-9d9a-32f25413fc09.png)
- i check schema of topic schema-test is ok
![image](https://user-images.githubusercontent.com/5100961/215105928-c6440ff7-e002-444f-9e8f-d82a47c34546.png)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
@suhoangson Can you provide a complete reproduce steps? Said how you define table schema.

**Comment by tisonkun** [comment]
Close as stale. It's hard to investigate without a repro.
