### ISSUE TITLE
PIP-244: Refactor ByteBuf release method

### ISSUE THREAD

**Issue by StevenLuMT** [apache/pulsar#19350]
### Motivation

It may throw an exception when release a `ByteBuf` object. so the exception in `ByteBuf.release` should be checked.

### Goal

Use `ReferenceCountUtil.safeRelease()` instead of `ByteBuf.release()` in all Pulsar's classes.

### Implementation

1. Use `ReferenceCountUtil.safeRelease()` instead of `ByteBuf.release()`.

**Comment by lhotari** [comment]
Rejecting this proposal since it's the wrong solution to use `safeRelease`. It hides real issues.
