### ISSUE TITLE
[Bug][pulsar-functions][worker] --update-auth-data fails if  Config is identical

### ISSUE THREAD

**Issue by alpreu** [apache/pulsar#19375]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Master, 17c58a539315cc4ea39655d4328c5caf55f87d3d

### Minimal reproduce step

The issue is the same for Functions, Sources, Sinks. The following is just an example for Sinks but the issue happens for all:

1. Create Sink (e.g. using pulsar-admin)
2. Update sink keeping `sinkConfig` identical, only using `--update-auth-data`

### What did you expect to see?

Successful update of the sink with the new auth data

### What did you see instead?

HTTP 400 - "Update contains no changes"

### Anything else?

The reason this happens is that in `SinksImpl` we first compare the new `SinkConfig` with the existing one and if they are the same we throw an error: https://github.com/apache/pulsar/blob/master/pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SinksImpl.java#L304-L320

The code for updating the auth data is below that (https://github.com/apache/pulsar/blob/master/pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SinksImpl.java#L361-L397) so it never gets called due to the exception above.

The problem is the same in `SourcesImpl` and `FunctionsImpl`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by labuladong** [comment]
Thanks for pointing it out, I'll take a look.
