### ISSUE TITLE
[Doc] https://pulsar.apache.org/docs/2.11.x/admin-api-get-started/reference-configuration.md/#client

### ISSUE THREAD

**Issue by bsandy999** [apache/pulsar#19373]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The link is broken.  Getting page not found on Admin setup and client conf configuration link.  

Reproduce Issue

1. Navigate / Open [this](https://pulsar.apache.org/docs/2.11.x/admin-api-get-started/#admin-setup)   in the browser. 
2. Search for this content `conf/client.conf file` and click on the link. 
3.  You will get redirected to a new tab with 404 not found

### What is your suggestion?

Kindly fix the content link issue. 

### Any reference?

[Link
](https://pulsar.apache.org/docs/2.11.x/admin-api-get-started/reference-configuration.md/#client)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by momo-jun** [comment]
This issue has been fixed through https://github.com/apache/pulsar-site/pull/403.
