### ISSUE TITLE
[Doc] "pulsar-admin schemas delete" description is confusing

### ISSUE THREAD

**Issue by visortelle** [apache/pulsar#19406]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

Documentation tells me that all schema versions will be deleted. That's indeed how it works now.

<img width="845" alt="Screenshot 2023-02-02 at 4 58 09 PM" src="https://user-images.githubusercontent.com/9302460/216375269-690c8d1f-1259-45cc-9bf8-703eb2a2f166.png">

Pulsar admin tells me that only the latest schema will be deleted.

<img width="481" alt="Screenshot 2023-02-02 at 4 57 15 PM" src="https://user-images.githubusercontent.com/9302460/216374991-f8a1e0db-d230-4235-beff-dcef89eb9543.png">

https://github.com/apache/pulsar/blob/81af293c842c1fc7f42e13ac4203f287e4b619bb/pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSchemas.java#L77

I'm confused. Is it a mistake, or does "latest schema" doesn't mean "latest schema version"?

It's easy to misunderstand it and accidentally delete all topic schemas.

### What is your suggestion?

Make the pulsar-admin flag description more descriptive.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
Hi @congbobo184 as we discussed just now, can you test this? Thank you!

**Comment by Anonymitaet** [comment]
Another issue found in the Schema doc, the items in red are not shown on the sidebar, is it an intended behaviour? 
<img width="1531" alt="image" src="https://user-images.githubusercontent.com/50226895/216496391-c5efe478-a4cb-4097-af16-daee7501ac12.png">

**Comment by congbobo184** [comment]
https://github.com/apache/pulsar/pull/19411 will fix the description

**Comment by congbobo184** [comment]
> Another issue found in the Schema doc, the items in red are not shown on the sidebar, is it an intended behaviour? <img alt="image" width="1531" src="https://user-images.githubusercontent.com/50226895/216496391-c5efe478-a4cb-4097-af16-daee7501ac12.png">
it should be a intended behavior, manage schema move to the Admin API 
![image](https://user-images.githubusercontent.com/39078850/216500853-c4e6aafa-98a0-4e60-bdab-1528199af668.png)
@momo-jun right?

**Comment by momo-jun** [comment]
@congbobo184 @Anonymitaet  correct, it's by design. The admin API category is a central reference place so we put Schema-related admin API in there and only left a link in the feature content.
