### ISSUE TITLE
[Bug] pulsar-client-all 2.11.0 transitively bringing in log4j2 implementation

### ISSUE THREAD

**Issue by onobc** [apache/pulsar#19484]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

- **OS:** `<not applicable>`
- **Pulsar:** `2.11.0`

#### Problem 
The `pulsar-client-all:2.11.0` dependency transitively includes Log4j2 (see [ here](https://mvnrepository.com/artifact/org.apache.pulsar/pulsar-client-all/2.11.0)) rather than just the SLF4J api and logging bridge. 
Whereas the `pulsar-client-all:2.10.3` does **NOT** bring a logging impl in (see [here](https://mvnrepository.com/artifact/org.apache.pulsar/pulsar-client-all/2.10.3)).

#### Symptoms
If the consuming app is already using a logger impl then a conflict can occur at startup (when using SLF4J) telling user to pick one or the other.

If the consuming application is not already using a logger impl then `pulsar-client-all` effectively chooses LOG4J2 for the app.

### What did you expect to see?

Adding the dependency `org.apache.pulsar:pulsar-client-all:2.11.0` should **NOT** transitively bring in the log4j2 implementation. 

### What did you see instead?

Adding the dependency `org.apache.pulsar:pulsar-client-all:2.11.0` transitively **DID** bring in the log4j2 implementation. 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Thanks for reporting this issue. It seems we accidentally change log4j libs from test dep to compile dep. I'm looking into this one now.

cc @Technoboy- @codelipenghui @eolivelli possible related release manager

**Comment by tisonkun** [comment]
This seems a bookkeeper issue https://github.com/apache/bookkeeper/commit/f0988ddf250440813866849cef4f734174a48fc4#r106236889.

We can force all log4j deps in test scope to workaround the case for now.

**Comment by tisonkun** [comment]
Fixed and cherry-picked to 2.11 at 2d8af31007a94c8c126b77333188b8a98a2a37cf.
