### ISSUE TITLE
[Doc] Broken links at https://pulsar.apache.org/docs/2.11.x/security-tls-transport/

### ISSUE THREAD

**Issue by visortelle** [apache/pulsar#19491]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/2.11.x/security-tls-transport/

<img width="832" alt="Screenshot 2023-02-11 at 9 01 17 AM" src="https://user-images.githubusercontent.com/9302460/218247435-b6cca326-386e-47a8-ac10-6966504d4a39.png">

Links to pulsar-admin, pulsar-perf and pulsar-client are broken.

<img width="756" alt="Screenshot 2023-02-11 at 9 02 10 AM" src="https://user-images.githubusercontent.com/9302460/218247470-b42a66e7-763a-4e28-8a61-c4b22b675a39.png">

### What is your suggestion?

Fix broken links.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Perhaps changed to https://pulsar.apache.org/reference/ related pages.

**Comment by Anonymitaet** [comment]
> Perhaps changed to https://pulsar.apache.org/reference/ related pages.

+1

**Comment by momo-jun** [comment]
> Perhaps changed to https://pulsar.apache.org/reference/ related pages.

I have a concern regarding the version number. E.g., https://pulsar.apache.org/reference/#/next/pulsar-admin/, the `next` version number in this link may not be always appropriate for a released version, but we have to always use it in the development phase of the `next` doc version. Shall we manually rename it to `2.11.x` after 2.11 is released, or any other better solutions?

**Comment by Anonymitaet** [comment]
@momo-jun suggests using the general link https://pulsar.apache.org/reference/ instead of specific links (e.g., https://github.com/apache/pulsar-site/pull/406/files?diff=split&w=0#diff-d1ce2c52744517a9c8a04c1cb1791292be5d97cf977723b804c3881aace8e8f7R139) for all versioned docs to reduce maintenance costs. Readers can choose their desired pages after they are navigated to the home page.
