### ISSUE TITLE
[Bug] A large number of non-persistent messages are lost

### ISSUE THREAD

**Issue by a11enhuang** [apache/pulsar#19509]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.10.3

### Minimal reproduce step

Create a non-persistent topic and set up three partitions.

### What did you expect to see?

Messages can be consumed normally

### What did you see instead?

Messages are lost in large numbers. The loss statistics are as follows:
 - Sent 1000 only received 283
 - Sent 1000 only received 601
 - Sent 1000 only received 623
 - Sent 5000 only received 481
 - Sent 5000 only received 544
 - Sent 10 received all

The cluster has 3 nodes, each node has a heap memory of 32GB and a direct memory of 32GB

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by syhily** [comment]
Did you disable this option `brokerDeleteInactiveTopicsEnabled`?

**Comment by tisonkun** [comment]
Closing...

No response.
