### ISSUE TITLE
[Doc] ( or ] ？

### ISSUE THREAD

**Issue by startjava** [apache/pulsar#19511]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/next/concepts-messaging/#sticky

![image](https://user-images.githubusercontent.com/49554320/218647286-00d918fe-8458-4471-a3c0-2d1631dae31b.png)

two '(' ， i think a '(' ，a ']'。

@momo-jun 

### What is your suggestion?

?

### Any reference?

?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by startjava** [comment]
![image](https://user-images.githubusercontent.com/49554320/218648501-05f9f3dc-004e-4cd3-af00-f9058d5d6c5a.png)
top pic i edit , it right ?

**Comment by shy-share** [comment]
> ![image](https://user-images.githubusercontent.com/49554320/218648501-05f9f3dc-004e-4cd3-af00-f9058d5d6c5a.png) top pic i edit , it right ?

@startjava yes，you are right and documentation is wrong

**Comment by startjava** [comment]
@shy-share 
number  49152  is right ??

**Comment by shy-share** [comment]
> number 49152 is right ??

@startjava yes, what do you think is wrong? what should be

**Comment by startjava** [comment]
49152）
[49152

but now two ") "

@tisonkun edit
