### ISSUE TITLE
[bug][site] 3rd-level menus at the left navigation can't be previewed (Reference site)

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#19549]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

## Issue 

The 3rd-level menus on the left navigation on the Reference site can’t be previewed.

## Context

For the Reference site, the 1st and 2nd-level content and their pages can be previewed on http://localhost:3000/reference/ (with the command `./preview.sh current`), while the 3rd-level navigations can’t be previewed.

![image](https://user-images.githubusercontent.com/50226895/219557704-06cd24bc-f345-40fe-8e1f-679c251f4023.png)

![image](https://user-images.githubusercontent.com/50226895/219557725-5033b91a-0cc5-4cee-82fb-bbf9f6ea5b9f.png)

Seems that this is not caused by my environment because there is no relevant error reported, and @momo-jun encounters this issue as well.

![image](https://user-images.githubusercontent.com/50226895/219557740-e793438c-01ac-4fcf-ac70-c1ac1b2f55f5.png)

### Solution

1. Resolve this issue

2. Document the workflow of "how to preview reference page" to the contribution guide
![image](https://user-images.githubusercontent.com/50226895/219557822-a147b54a-a2c7-4251-8178-ced60207f35a.png)

cc @tisonkun @urfreespace @DaveDuggins @D-2-Ed 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
cc @SignorMercurio

**Comment by SignorMercurio** [comment]
Not sure why this happens. Are there any JS errors in developer tools? Perhaps a couple of JS files failed to load and caused this problem.

**Comment by tisonkun** [comment]
Closing...

1. Cannot preview 3rd-level menus is not an issue. Just click the 2nd-level menu and you can preview the one more nested menu.
2. https://pulsar.apache.org/reference/#/next/config/ sidebar looks correct now.
3. Preview changes cannot list out all pages, if you think it's an issue, please directly submit a patch against the site repo and I'm glad to merge it.
