### ISSUE TITLE
[Doc]  Support chunking with Shared subscription

### ISSUE THREAD

**Issue by startjava** [apache/pulsar#19567]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/2.11.x/concepts-messaging/#chunking

limt ：
second item：Chunking is only available for the exclusive and failover subscription types.

but now support "Shared subscription"

@momo-jun 

### What is your suggestion?

?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by momo-jun** [comment]
@startjava is this a feature request? Do you want to enable the chunking feature when using the shared subscription?

**Comment by startjava** [comment]
2.11 version Chunking support key_shared，
but doc is old ：Chunking is only available for the exclusive and failover subscription types.

**Comment by labuladong** [comment]
@startjava Thanks for pointing it out, I'll update the doc.
