### ISSUE TITLE
[Doc] HashingScheme url 404 

### ISSUE THREAD

**Issue by shy-share** [apache/pulsar#19621]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/2.11.x/concepts-messaging/#hashing-scheme
For more info on using hashing-scheme, see the "HashingScheme":  https://pulsar.apache.org/api/client/org/apache/pulsar/client/api/HashingScheme  is 404.
And other versions of documents also exist in this problem

### What is your suggestion?

Nothing at all

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by nikam14** [comment]
You can raise this issue [Here](https://github.com/apache/pulsar-site) might be more suitable

**Comment by tisonkun** [comment]
Closed by https://github.com/apache/pulsar-site/pull/436.

I'll cherry-pick to previous versions.

**Comment by tisonkun** [comment]
FYI https://github.com/apache/pulsar-site/commit/31df14885dc305a40e771f1ffee9831e931da85f

But it may introduce false-positive broken links report. So a clean solution should be add a TSX component to correctly render versioned API docs link.

cc @momo-jun @urfreespace
