### ISSUE TITLE
[Doc] Page crash when click the link to REST API

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#19644]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The page crashes when clicking the link to the REST API in https://pulsar.apache.org/docs/next/admin-api-topics such as:

<img width="777" alt="image" src="https://user-images.githubusercontent.com/16974619/221514264-d2f27f99-2676-4ac1-b5f8-1b2c58239372.png">

And here is the link: https://pulsar.apache.org/admin-rest-api/?version=2.11.0&apiversion=v2#operation/getStats

The crash info:
<img width="637" alt="image" src="https://user-images.githubusercontent.com/16974619/221514535-566db351-27f3-4006-bce7-1f7535f45b5c.png">

### What is your suggestion?

Don't crash

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by momo-jun** [comment]
The same error message at my side. 
@urfreespace do you have any ideas on this issue? Guessing it has something to do with specific global configs?

**Comment by urfreespace** [comment]
> The same error message at my side. @urfreespace do you have any ideas on this issue? Guessing it has something to do with specific global configs?

I will take a look

**Comment by urfreespace** [comment]
https://github.com/apache/pulsar-site/pull/439 @momo-jun
