### ISSUE TITLE
[Doc] The link to C++ client doxygen doc is 404

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#19675]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The link here is not found:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/16974619/222106813-26c48325-04e8-43bf-8ce4-e50cb1e102df.png">

Here is the link: https://pulsar.apache.org/api/cpp/2.11.x

Seems only affect the `next` version.

### What is your suggestion?

Link to c++ doxygen doc

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
@RobertIndie https://pulsar.apache.org/api/cpp/ does not contain 2.11.x. I'll change the link to the general one https://pulsar.apache.org/api/cpp/ to reduce maintenance costs.

**Comment by Anonymitaet** [comment]
Fix in https://github.com/apache/pulsar-site/pull/450, PTAL, @RobertIndie
