### ISSUE TITLE
[Bug] Java Client's Seek Logic Not Threadsafe

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#19671]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Master

### Minimal reproduce step

Review the usage of the `duringSeek` atomic boolean, and it is clear that if a client were to execute two concurrent seek async calls, the client would not handle the logic correctly.

See:

https://github.com/apache/pulsar/blob/e0b50c9ec5f12d0fb8275f235d8ac00e87a9099e/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L2141

https://github.com/apache/pulsar/blob/e0b50c9ec5f12d0fb8275f235d8ac00e87a9099e/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L924-L925

The first seek will likely return first and reset the subscription, but the second will silently fail.

### What did you expect to see?

I expect the client to either cancel the first operation or to fail the second operation due to an illegal call.

### What did you see instead?

Unexpected state would occur.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tobehardest** [comment]
Maybe I can try to see if I can solve this, can you assign it to me?

**Comment by tisonkun** [comment]
@tobehardest go ahead!

**Comment by xiang092689** [comment]
what problem may cause by this issue?

**Comment by Abhijeetmishr** [comment]
@michaeljmarshall @tisonkun can I work on this if @tobehardest is not working on this ?

**Comment by tisonkun** [comment]
@Abhijeetmishr May I ask what's your plan to handle this issue? I've seen people ask for assigned and hard to make progress, so maybe a brief introduction can help instead of "please assign me but I don't know what to do".

**Comment by Abhijeetmishr** [comment]
@tisonkun I could have provided brief introduction beforehand only sorry for that.

>  I think making this AtomicBoolean seek asynchronous will help us.

**Problem :-** 

> Suppose you have a shared AtomicBoolean variable named flag and two threads, Thread A and Thread B. Thread A sets the value of flag to true, and Thread B reads the value of flag. If Thread B reads the value of flag before Thread A sets it to true, then Thread B might enter an infinite loop because it assumes that the value of flag is false.

**Solution :-** 

> we need to use a synchronization mechanism, such as an asynchronous behavior, to ensure that the value of flag is set before it is read. 
> we use a CompletableFuture or a Future object to run the task asynchronously.

**Comment by tisonkun** [comment]
Assigned. Thank you and I'll try to give the patch a review.
