### ISSUE TITLE
[Doc] Fix the Pulsar Functions pom.xml example, it's invalid in the docs

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#19680]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The pom.xml in https://pulsar.apache.org/docs/2.11.x/functions-package-java/ is invalid. If you copy-paste the pom to your project and try to use it, it will fail in compilation.

### What is your suggestion?

The plugin versions should be added. Maven defaults to use very old versions. The default version doesn't support `<release>`.
For example, for maven-compiler-plugin, the latest version is `<version>3.11.0</version>`.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
Hi @freeznet can you help answer the following questions? Thank you!

1. There are 2 pom.xml files in https://pulsar.apache.org/docs/2.11.x/functions-package-java/, are they incorrect? If no, what kind of changes should be made?

2. How about this?

> The plugin versions should be added.

**Comment by tisonkun** [comment]
@lhotari Could you double check https://github.com/apache/pulsar-site/pull/446?

Also, I'm considering providing maven archetypes for such sample usage. But it should be a separate issue.
