### ISSUE TITLE
[Doc] only has size no time about demo code。

### ISSUE THREAD

**Issue by startjava** [apache/pulsar#19685]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/2.11.x/cookbooks-retention-expiry/#set-sizetime-thresholds-and-backlog-retention-policies

title is bottom：
Set size/time thresholds and backlog retention policies

but demo code only size，not time，but title has "/time"

@momo-jun 

### What is your suggestion?

?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by momo-jun** [comment]
Hi @startjava, if I understand your concern correctly, the following code sample shows how to set the time threshold.

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/60642177/222343255-35c2c621-aa10-4120-a762-01b49f9a5235.png">

**Comment by startjava** [comment]
yes，but java code no has time demo !  @momo-jun

**Comment by RobertIndie** [comment]
Thanks for your report. I will fix it.
