### ISSUE TITLE
[Doc] Table was removed on 2.11 version of schema manage docs

### ISSUE THREAD

**Issue by dave2wave** [apache/pulsar#19697]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

In https://pulsar.apache.org/docs/2.10.x/schema-manage/ there is a table (poorly formatted)
![image (2)](https://user-images.githubusercontent.com/29803617/222577857-14b6d227-da79-4cff-af5b-8d7fba7af873.png)
But on version 2.11.x it is missing.
![image (4)](https://user-images.githubusercontent.com/29803617/222577943-77fb91dd-4437-43ef-8946-32505945ce21.png)

### What is your suggestion?

Please restore the table with corrected formatting. The **blank** case is lost with the update.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
Thanks! I'll fix them.

**Comment by Anonymitaet** [comment]
Fix in https://github.com/apache/pulsar-site/pull/450, PTAL @dave2wave

**Comment by momo-jun** [comment]
@dave2wave @Anonymitaet The table was removed from the task topic during the schema doc refactoring, because it's a common reference that can be found [here](https://pulsar.apache.org/docs/2.11.x/schema-understand/#schema-definition), not specific for `Upload a schema`.

**Comment by dave2wave** [comment]
That does not convey the same information. One has three parts and the other has four. Also the removed information explained about leaving one parameter empty and the link did not. Unless something was incorrect before then we should fix this isssue.
