### ISSUE TITLE
[Doc] Improve the release process doc

### ISSUE THREAD

**Issue by liangyepianzhou** [apache/pulsar#19701]
cc @tisonkun 
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

Because the upload of the file takes a lot of time, so I think we should add some notice before `svn add *`  and `svn ci -m 'Staging artifacts and signature for Pulsar release 2.X.0'`.
https://pulsar.apache.org/contribute/release-process/#sign-and-stage-the-artifacts-on-svn

### What is your suggestion?

1. Check the size of apache-pulsar-2.x.0-src.tar.gz.
     - It should be like `39028421` instead of `1129229821`. Otherwise, the upload will always fail without a clear error. 
2. Check if `file.asc` and `file.sha512` have been generated.     

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Thanks for reporting this! I'll try to take a look in this weekend :)

**Comment by tisonkun** [comment]
Also cc previous RM FYI:

@Technoboy- @congbobo184 @Jason918 @codelipenghui @BewareMyPower @eolivelli

**Comment by tisonkun** [comment]
> It should be like 39028421 instead of 1129229821. Otherwise, the upload will always fail without a clear error.

@liangyepianzhou could you elaborate a bit how the case occurs? I may add only the verification for signing and checksum.

**Comment by congbobo184** [comment]
> 1. Check the size of apache-pulsar-2.x.0-src.tar.gz.
>    
>    * It should be like `39028421` instead of `1129229821`. Otherwise, the upload will always fail without a clear error.


Good work. All changes to release documents need to be discussed. I have the same question as tison, can you explain option 1 in detail

**Comment by liangyepianzhou** [comment]
>@liangyepianzhou could you elaborate a bit how the case occurs? I may add only the verification for signing and checksum.

This problem is actually caused by the local environment of the release manager.
For example, 
1. he run the process of [verifying release](https://pulsar.apache.org/contribute/validate-release-candidate/) first, and not cleaned up the connectors and offloaders in time. Then the `apache-pulsar-2. x.0-src. tar.gz`. generated by the `mvn clean install` will be too large, resulting in the failure of uploading all the time.  
2. The project looks clean, but there are some things hidden in unexpected places. Then the `apache-pulsar-2. x.0-src. tar.gz`. generated by the `mvn clean install` will be too large, 

Because this upload takes a long time, network problems may occur. This failure is easily identified as the result of network instability. So I think it is necessary to add a reminder.

**Comment by tisonkun** [comment]
@liangyepianzhou I don't think we can cover every person-by-person biased potential mistake. Also, the number like `39028421` instead of `1129229821` seem magic numbers and cannot maintain.

Although, we can add a note for release managers that he/she should build the artifacts with a _clean_ workspace.

@liangyepianzhou do you have ideas where we can add such a note?

**Comment by liangyepianzhou** [comment]
I found another issue when running the shell `$PULSAR_PATH/src/stage-release.sh .`.

``` shell
Issue: GPG fails to sign with the error "Screen or window too small" due to the terminal window being too small to display the necessary user interface.
```
``` shell
Solution: You can try adjusting the size of the terminal window by dragging its edges or corners to make it larger. If the problem persists, wait for a while and try again to ensure that the terminal window is large enough. Alternatively, you can try using other terminal applications such as iTerm2 or PuTTY to see if they can solve this issue.
```
Do you think we should add notes to the doc?

**Comment by liangyepianzhou** [comment]
Another point: the [section](https://pulsar.apache.org/contribute/release-process/#stage-docker-images) of the docker image is expired. The `pulsar-grafana` and `pulsar-standalone` are not built at the current implementation, so we should delete them.


``` shell
After that, the following images will be built and pushed to your own DockerHub account:

* pulsar
* pulsar-all
* pulsar-grafana
* pulsar-standalone
```

**Comment by Jason918** [comment]
> Another point: the [section](https://pulsar.apache.org/contribute/release-process/#stage-docker-images) of the docker image is expired. The `pulsar-grafana` and `pulsar-standalone` are not built at the current implementation, so we should delete them.
> 
> ```shell
> After that, the following images will be built and pushed to your own DockerHub account:
> 
> * pulsar
> * pulsar-all
> * pulsar-grafana
> * pulsar-standalone
> ```

+1，it's true.

**Comment by Jason918** [comment]
> This problem is actually caused by the local environment of the release manager. For example,
> 
> 1. he run the process of [verifying release](https://pulsar.apache.org/contribute/validate-release-candidate/) first, and not cleaned up the connectors and offloaders in time. Then the `apache-pulsar-2. x.0-src. tar.gz`. generated by the `mvn clean install` will be too large, resulting in the failure of uploading all the time.
> 2. The project looks clean, but there are some things hidden in unexpected places. Then the `apache-pulsar-2. x.0-src. tar.gz`. generated by the `mvn clean install` will be too large,
> 
> Because this upload takes a long time, network problems may occur. This failure is easily identified as the result of network instability. So I think it is necessary to add a reminder.

Yes, similar thing happens to me at the first release. If I remember correctly, my case is that I downloaded the svn directory into PULSAR_HOME, it makes the src file very large.

I think maybe we can add a size check about how large the uploaded file should be.

**Comment by tisonkun** [comment]
@Jason918 you can review https://github.com/apache/pulsar-site/pull/474
