### ISSUE TITLE
[Bug] Cannot update Pulsar function in Pulsar standalone

### ISSUE THREAD

**Issue by abeliangroupie** [apache/pulsar#19721]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

**OS version:** Ubuntu 22.04
**Pulsar version:** 2.11.0 (using apachepulsar/pulsar-all:2.11.0 Docker image)

### Minimal reproduce step

Run 2.11.0 standalone:

```
$ docker run -it apachepulsar/pulsar:2.11.0 bin/pulsar standalone
```

Go into the container and create an arbitrary Pulsar function `test_function.py`.

Then register it:

```
$ bin/pulsar-admin functions create \
  --py test_function.py \
  --classname test_function.ExamplePulsarFunction \
  --tenant public \
  --namespace default \
  --name test-function \
  --inputs persistent://public/default/test-input-topic \
  --output persistent://public/default/test-output-topic
Created successfully
```

Now try to update it:

```
$ bin/pulsar-admin functions update \
  --py test_function.py \
  --classname test_function.ExamplePulsarFunction \
  --tenant public \
  --namespace default \
  --name test-function \
  --inputs persistent://public/default/test-input-topic \
  --output persistent://public/default/test-output-topic
```

### What did you expect to see?

I'd expect to see the `Updated successfully` message from updating a Pulsar function.

### What did you see instead?

I get the error

```
Package 'function://public/default/test-function@0' metadata already exists`.
```

The logs look a bit like this:

```
2023-03-06T06:34:58,426+0000 [pulsar-web-38-2] ERROR org.apache.pulsar.functions.worker.rest.api.FunctionsImpl - Failed process Function public/default/test-function package: 
org.apache.pulsar.client.admin.PulsarAdminException$NotFoundException: Package 'function://public/default/test-function@0' metadata already exists
        at org.apache.pulsar.client.admin.PulsarAdminException.wrap(PulsarAdminException.java:252) ~[org.apache.pulsar-pulsar-client-admin-api-2.11.0.jar:2.11.0]
        at org.apache.pulsar.client.admin.internal.BaseResource.sync(BaseResource.java:316) ~[org.apache.pulsar-pulsar-client-admin-original-2.11.0.jar:2.11.0]
        at org.apache.pulsar.client.admin.internal.PackagesImpl.upload(PackagesImpl.java:90) ~[org.apache.pulsar-pulsar-client-admin-original-2.11.0.jar:2.11.0]
        at org.apache.pulsar.functions.worker.rest.api.ComponentImpl.getFunctionPackageLocation(ComponentImpl.java:411) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
        at org.apache.pulsar.functions.worker.rest.api.FunctionsImpl.updateFunction(FunctionsImpl.java:459) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
        at org.apache.pulsar.broker.admin.impl.FunctionsBase.updateFunction(FunctionsBase.java:326) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        ...
```

### Anything else?

As far as I can tell `ComponentImpl.getFunctionPackageLocation()` is getting called when updating the Pulsar function, but when non-BookKeeper package management is being used (which is the case for standalone) it looks like `PackagesManagementImpl.upload()` happens, and that checks whether metadata exists or not + throws an error if it doesn't...

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by anthonyikeda** [comment]
I've had the same problem when deleting and re-creating a function in standalone mode:

```
(base) ➜  apache-pulsar-2.11.0 bin/pulsar-admin functions create --function-config-file basic-function.yaml --jar basic-function-0.0.1-SNAPSHOT.nar
Created successfully
(base) ➜  apache-pulsar-2.11.0 bin/pulsar-admin functions delete --tenant test --namespace test-namespace --name string-to-string
Deleted successfully
(base) ➜  apache-pulsar-2.11.0 bin/pulsar-admin functions create --function-config-file basic-function.yaml --jar basic-function-0.0.1-SNAPSHOT.nar
Package 'function://test/test-namespace/string-to-string@0' metadata already exists

Reason: Package 'function://test/test-namespace/string-to-string@0' metadata already exists
```

For some reason the `{PULSAR_HOME}/packages-storage/function/<tenant>/<namespace>/<function-name>` doesn't get removed causing this error.

If you manually delete the folder, you can recreate (maybe also update) the function.

**Comment by jiangpengcheng** [comment]
I met the same problem and found the reason:

When `--py` or `--jar`, `--go` is specified while updating functions, Pulsar will upload the given file to the package path like `function://public/default/test-function@0`, but this package path is used when the function is created, so we should add 1 to the function's version and use package path: `function://public/default/test-function@1`

if you do not specify the `--py|--go|--jar`, it will success, and the function version is updated to 1, and then update the function again with `--py|--go|--jar`, it will succeed too since it will use path `function://public/default/test-function@1` while such package doesn't exist yet

and this is the same for `source` and `sink`

**Comment by flowchartsman** [comment]
Does this relate to non-standalone as well? I also submitted a few similar bugs related to updating pulsar functions, so tagging them here, since there PRs:

#18966
#18973 
#18972

It's still not clear to me what the function workflow is supposed to be like, and which technique we should use:

- `pulsar-admin function upload`
- `pulsar-admin packages upload`
- `pulsar-admin functions create --py|--go|--jar <path>`

This could use some documentation help, I think, to make things more clear on the function lifecycle so that we know how to

1. Provide a py/go/jar function package to pulsar at version 0
2. Run new functions with this package
3. Add a new version of the package
4. Update running functions to use the new version
5. list all versions of a function package and, finally
6. delete old versions when they are no longer necessary.

**Comment by jiangpengcheng** [comment]
@flowchartsman I haven't tested with non-standalone mode, but it should have the same behavior

The are two workflows, I think:

### Use file path for `--py|--go|--jar`, and set `functionsWorkerEnablePackageManagement` to true in `conf/broker.conf`

1. create a function with `--py|--go|--jar`, followed by a file path, when `functionsWorkerEnablePackageManagement` in `conf/broker.conf` is true(which is defaulted to true in standalone mode, while default to false in non-standalone mode), this file will be automatically uploaded as a pulsar package, and the pkg url looks like `function://public/default/myFunc@0`

2. if the function code should be updated, you can update this function with `--py|--go|--jar` specified to the new code file, and then pulsar will automatically upload the file to a new package path: `function://public/default/myFunc@1`

3. you can list all versions of packages using `pulsar-admin packages list public/default/myFunc --type function`, it will list all versions of automatically uploaded packages

4. then you can delete old version packages as your wish

### Use package path for `--py|--go|--jar`

1. manually upload a pulsar package: `pulsar-admin packages upload function://public/default/myPkg@0 --path /your/code/path --description "my func"`

2. create a function with the uploaded package: `--go function://public/default/myPkg@0`

3. if you want to change the code, manually upload a new pulsar package: `pulsar-admin packages upload function://public/default/myPkg@1 --path /your/code/path --description "my func v1"`

4. update function with `--go function://public/default/myPkg@1`

5. you can list all packages with: `pulsar-admin packages list public/default/myPkg --type function`

6. then delete pkg versions as your wish

**Comment by flowchartsman** [comment]
@jiangpengcheng: I tried applying this fix to pulsar-admin and rebuilding with `mvn -pl pulsar-client-tools install -DskipTests`, and it still does not work:

```
./pulsar-admin functions update --tenant mytenant --namespace mynamespace --name myfunction --go function://mytenant/mynamespace/myfuncpkg@1.0
2023-04-05T00:11:26,978-0400 [AsyncHttpClient-7-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://10.13.2.236:8081/admin/v3/functions/mytenant/mynamespace/myfunction] Failed to perform http put request: javax.ws.rs.BadRequestException: HTTP 400 Bad Request
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Invalid package name 'myfunction'

```

**Comment by flowchartsman** [comment]
I also cannot delete a function package, despite it being empty:

```
$ ./pulsar-admin packages list --type function mytenant/mynamespace
myfuncpkg
functionbeta

$ ./pulsar-admin packages list --type function mytenant/mynamespace/functionbeta
#nothing prints
$ ./pulsar-admin packages delete function://mytenant/mynamespace/functionbeta
2023-04-05T00:24:37,222-0400 [AsyncHttpClient-7-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://10.13.2.236:8081/admin/v3/packages/function/mytenant/mynamespace/functionbeta/latest] Failed to perform http delete request: javax.ws.rs.InternalServerErrorException: HTTP 500 Server Error
Encountered zookeeper issue on deleting log stream function/mytenant/mynamespace/functionbeta/latest/meta

Reason: Encountered zookeeper issue on deleting log stream function/mytenant/mynamespace/functionbeta/latest/meta
```

And of course it is error 500. About the only clue I see is it attempting to delete `latest`.  Has this never worked and no one has ever used it, or am I doing something dreadfully wrong?

**Comment by flowchartsman** [comment]
I used mitmproxy to sniff the traffic from pulsar-admin and this is what I see:

```
Accept:          application/json
Content-Type:    multipart/form-data;boundary=Boundary_1_1365578081_1680670177535
MIME-Version:    1.0
content-length:  680
host:            10.13.2.236:8081
user-agent:      Pulsar-Java-v2.10.3

--Boundary_1_1365578081_1680670177535
Content-Type: text/plain
Content-Disposition: form-data; name="url"

function://mytenant/mynamespace/myfuncpkg@1.0
--Boundary_1_1365578081_1680670177535
Content-Type: application/json
Content-Disposition: form-data; name="functionConfig"

{"tenant":"mytenant","namespace":"mynamespace","name":"myfunction","outputSchemaType":"","forwardSourceMessageProperty":true,"go":"function://mytenant/mynamespace/myfuncpkg@1.0","subscriptionPositi
on":"Latest"}
--Boundary_1_1365578081_1680670177535
Content-Type: application/json
Content-Disposition: form-data; name="updateOptions"

{"updateAuthData":false}
--Boundary_1_1365578081_1680670177535--
```

**Comment by oneebhkhan** [comment]
@flowchartsman did you end up figuring this out? Im working with Java functions for Pulsar and coming across similar issues. My concerns are multiple:
1. There is no documentation on how to use "packages" for functions. What purpose is this fulfilling? What is the expected order of executing commands?
2. Im trying to use the Pulsar REST APIs to deploy a Pulsar Function. My Client sends a POST Request to create the function with the path provided to the Java executable in the --jar field and I come across `Function package is not provided` error. I then try to "upload" the function package as suggested by the documentation. And then when I send my request again, there is no change. 

Im also trying to figure out if Im missing something really obvious here and if someone has actually ever used package management before
