### ISSUE TITLE
[doc] C++ API doc link

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#19745]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

Hi @tisonkun 

Currently, `API docs` is set to `@pulsar:apidoc:cpp@` and pointed to the latest C++ version site (https://pulsar.apache.org/api/cpp/3.1.x/).
 
<img width="769" alt="image" src="https://user-images.githubusercontent.com/50226895/223614010-7bc2c03c-32de-4325-a24c-afae44e4cdaf.png">

Does it mean that, as time goes by, the `API docs link` in the "old" Pulsar C++ docs always points to the latest version of the C++ API Reference site? 

If so, should we correct it to `https://pulsar.apache.org/api/cpp/` (home page) to allow users to pick up desired versions (since we do not know the version relationships between Pulsar and C++ client)?

cc @momo-jun @DaveDuggins 

### What is your suggestion?

Stated above ⬆️

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
I'd like to listen to @BewareMyPower @RobertIndie suggestion on version table.

**Comment by BewareMyPower** [comment]
I think we should still reference the latest docs. The version relationships between Pulsar and C++ client should be maintained in the API docs of the C++ client. Regarding the version relationships between Pulsar and C++ client, we should maintain it in the C++ API docs, for example, a new interface requires the Pulsar version >= x.y.z and enable a specific configuration.

You can see [the Go client API docs](https://pkg.go.dev/github.com/apache/pulsar-client-go/pulsar) also reference the latest by default.

**Comment by tisonkun** [comment]
@BewareMyPower Thanks for your input. Closing now as work as expected.

Also, the page https://pulsar.apache.org/api/cpp is not an optimal page for version selecting...
