### ISSUE TITLE
[Bug] Topics with slashes cannot be queried

### ISSUE THREAD

**Issue by KamenRiderKuuga** [apache/pulsar#19770]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

standalone Pulsar cluster in Kubernetes with image tag apachepulsar/pulsar:2.10.2

### Minimal reproduce step

This is all the code I use:
```java
public static void main(String[] args) throws PulsarClientException, PulsarAdminException, InterruptedException {
    AuthenticationBasic auth = new AuthenticationBasic();
    auth.configure("{\"userId\":\"superuser\",\"password\":\"admin\"}");
    String serviceHttpUrl = "http://127.0.0.1:8080";
    String serviceUrl = "pulsar://127.0.0.1:6650";
    String tenant = "demo-tenant";
    String namespace = "demo-tenant/demo-namespace";
    PulsarAdmin admin = PulsarAdmin.builder().serviceHttpUrl(serviceHttpUrl).authentication(auth).build();
    if (!admin.tenants().getTenants().contains(tenant)) {
        admin.tenants().createTenant(tenant, TenantInfo.builder().adminRoles(Set.of("superuser")).allowedClusters(Set.of("standalone")).build());
    }
    if (!admin.namespaces().getNamespaces(tenant).contains(namespace)) {
        admin.namespaces().createNamespace(namespace);
    }
    PulsarClient pulsarClient = PulsarClient.builder().serviceUrl(serviceUrl).authentication(auth).build();
    Producer<String> producer = pulsarClient.newProducer(Schema.STRING).topic("persistent://" + namespace + "/level1/level2/level3").create();
    producer.newMessage().value("demo-data").send();
    // wait for few seconds
    Thread.sleep(3000);
    // print the topics
    List<String> topics = admin.topics().getList(namespace);
    // the list of topics will be empty
    topics.forEach(System.out::println);
    producer = pulsarClient.newProducer(Schema.STRING).topic("persistent://" + namespace + "/level1").create();
    producer.newMessage().value("demo-data").send();
    // wait for few seconds
    Thread.sleep(3000);
    topics = admin.topics().getList(namespace);
    // the list of topics is : ["persistent://demo-tenant/demo-namespace/level1"]
    topics.forEach(System.out::println);
}
```

### What did you expect to see?

When I use the topic `persistent://demo-tenant/demo-namespace/level1/level2/level3`, I think I should also see it in the query results of topic list

### What did you see instead?

I can only get the `persistent://demo-tenant/demo-namespace/level1` in the query results

### Anything else?

#19752 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by KamenRiderKuuga** [comment]
#6885

**Comment by KamenRiderKuuga** [comment]
Should I avoid topic names with slashes?

**Comment by tisonkun** [comment]
> Should I avoid topic names with slashes?

Yes for now.

IIRC https://github.com/apache/pulsar/issues/19239 makes some topic name restrictions. @mattisonchao maybe you can take a look at this issue?

**Comment by mattisonchao** [comment]
Yes, the topic name should follow the rule as follow:
```java
    // allowed characters for property, namespace, cluster and topic names are
    // alphanumeric (a-zA-Z_0-9) and these special chars -=:.
    // % is allowed as part of valid URL encoding
    public static final Pattern NAMED_ENTITY_PATTERN = Pattern.compile("^[-=:.\\w]*$");
```

Pulsar hasn't a good topic name limit yet, but it is being added.

/cc @tisonkun @KamenRiderKuuga

**Comment by mattisonchao** [comment]
It should be limited.

**Comment by KamenRiderKuuga** [comment]
OK, I think I will use the `-` for splitting, thank you very much!
Also, the description of these restrictions will be placed in the official documentation, right?

**Comment by tisonkun** [comment]
@KamenRiderKuuga may I ask how this issue gets resolved for you?

**Comment by KamenRiderKuuga** [comment]
> @KamenRiderKuuga may I ask how this issue gets resolved for you?

Just avoid using these characters as Topic in the code, we use the hyphens to replace the slashes.
