### ISSUE TITLE
Flaky-test: org.apache.pulsar.broker.stats.MetadataStoreStatsTest.testBatchMetadataStoreMetrics

### ISSUE THREAD

**Issue by lifepuzzlefun** [apache/pulsar#19792]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/4383540966/jobs/7674179427

### Exception stacktrace

i don't known where to find unit test fail stacktrace. please let me know.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by coderzc** [comment]
+ 1 https://github.com/apache/pulsar/actions/runs/4413158692/jobs/7736015420#step:11:2577

**Comment by nodece** [comment]
Reopen this issue by https://github.com/apache/pulsar/actions/runs/4424020709/jobs/7763604452#step:11:1277

**Comment by lifepuzzlefun** [comment]
fixed by https://github.com/apache/pulsar/pull/19829
