### ISSUE TITLE
[Bug] Pulsar standalone does not read the Zookeeper port form zookeeper.conf

### ISSUE THREAD

**Issue by lk-1984** [apache/pulsar#19799]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Docker version 20.10.23, build 7155243
Docker Compose version v2.15.1
Apache Pulsar 2.9.3
Ubuntu 22.04

### Minimal reproduce step

Change the port for Zookeeper in zookeeper.conf

https://github.com/apache/pulsar/blob/master/conf/zookeeper.conf#L31

and then start up the Pulsar in standalone mode:

entrypoint: ["bin/pulsar", "standalone"]

### What did you expect to see?

Zookeeper listening at port 2182.

### What did you see instead?

Zookeeper still listening at port 2181.

The zookeeper.conf in the docker container did have the new port, 2182.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by nicoloboschi** [comment]
In Pulsar standalone you can configure the zookeeper port by passing the arg `--zookeeper-port`:

```
PULSAR_STANDALONE_USE_ZOOKEEPER=1 bin/pulsar standalone --zookeeper-port 2281
```

**Comment by lk-1984** [comment]
> In Pulsar standalone you can configure the zookeeper port by passing the arg `--zookeeper-port`:
> 
> ```
> PULSAR_STANDALONE_USE_ZOOKEEPER=1 bin/pulsar standalone --zookeeper-port 2182
> ```

Sure, but this is not about that argument. It's about the configuration file.
