### ISSUE TITLE
[Doc] Developers landing page throws 404 Not Found error

### ISSUE THREAD

**Issue by harikrishna553** [apache/pulsar#19809]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

Navigate to the page 'https://pulsar.apache.org/docs/2.11.x/' and click on 'Pulsar For Developers' link to check the issue

### What is your suggestion?

Please point to the developers documentaiton

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
@harikrishna553 Thanks for reporting this! I've fixed it in https://github.com/apache/pulsar-site/pull/469, PTAL.
