### ISSUE TITLE
Poor autorecovery performance on dedicated hosts

### ISSUE THREAD

**Issue by bardock** [apache/pulsar#1981]
We have a cluster of 20 bookies and another cluster of 15 instances running autorecovery. We've just lost a bookie (physically) and right now there are 10k ledgers marked as underreplicated (approximately 100 GB of data).

Autorecovery is replicating 50-100 ledgers per minute. Is there any way to improve this performance?

There are enough resources (CPU, RAM and network bandwidth), however publish times increased from 10 to 100 ms (pct99).

We are using EC2 instances ([i3.2xlarge](https://aws.amazon.com/ec2/instance-types/i3/#Product_Details) for bookies and [c5.large](https://aws.amazon.com/ec2/instance-types/c5/#Product_Details) for autorecovery) and bookkeeper version 4.3.1.91-yahoo with the default config except these settings:

```
dbStorage_readAheadCacheMaxSizeMb=4096,
dbStorage_rocksDB_blockCacheSize=4294967296
flushInterval=10000
```

**Comment by sijie** [comment]
@bardock so I think it is throttled by this setting: https://github.com/yahoo/bookkeeper/blob/yahoo-4.3/bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/AbstractConfiguration.java#L189

`rereplicationEntryBatchSize` 

that says if you have 15 instances running autorecovery, for each instance it will only replicate one ledger at a time, for replicating a ledger, it will only replicate `rereplicationEntryBatchSize` at a time. I would suggest you increase this `rereplicationEntryBatchSize` to a larger value to speed up the recovery process.

However you might consider doing some calculation to not use all the network bandwidth for rereplication.

**Comment by sijie** [comment]
@bardock any updates from this issue?

**Comment by sijie** [comment]
Close due to inactivities.
