### ISSUE TITLE
[Doc] admin overview links to pulsar-admin page that does not exist

### ISSUE THREAD

**Issue by jbellis** [apache/pulsar#19853]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/2.11.x/admin-api-overview/ links to https://pulsar.apache.org/reference/#/2.11.x/pulsar-admin which does not exist

### What is your suggestion?

remove or fix link

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Thanks for reporting this issue. I'm working on a fix now :)
