### ISSUE TITLE
Verify at least one URL is present for cluster creation

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#19866]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

With https://github.com/apache/pulsar/pull/19151 and https://github.com/apache/pulsar/pull/19762, we verify that cluster urls are valid. It seems like we could also verify that there is at least one `serviceUrl`/`serviceUrlTls` and at least one `brokerServiceUrl`/`brokerServiceUrlTls` set.

### Solution

Update the following code to add a check that some of those variables are set:

https://github.com/apache/pulsar/blob/e829672b84c15a596574da25205d32ae7b1abf4b/pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/ClusterDataImpl.java#L412-L430

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by niharrathod** [comment]
I can take up this. Could you please assign this to me?

**Comment by michaeljmarshall** [comment]
Sure, thanks @niharrathod

**Comment by niharrathod** [comment]
@michaeljmarshall 

I have raised a [PR](https://github.com/niharrathod/pulsar/pull/2) having fix for this issue on my personal fork. Could you please take a quick look at it? 

I need to patch many existing unit test cases. So want confirm before fixing them.

**Comment by niharrathod** [comment]
@michaeljmarshall : FYI

unassigning myself

I tried to fix this and raised PR. In-fact actual change is easy and small, But the same change breaks almost all unit test-cases around broker sub-systems. So, overall fix becomes really huge. 

If anyone looking into this issue and wants help, feel free to DM me.

**Comment by michaeljmarshall** [comment]
I am not sure what the right solution is. Given that it sounds like there is a large diff, it might be more complicated than it is worth.

**Comment by tisonkun** [comment]
https://github.com/apache/pulsar/blob/aa7decc5b75894e864f3c5962c5cffad255abf25/pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java#L1469-L1480

I'm now suspecting the condition of this issue -

From the source code it seems we actually tolerate only one of `ServiceUrl ` or `BrokerServiceUrl` configured.

**Comment by tisonkun** [comment]
@JooHyukKim If you take a closer look at https://github.com/apache/pulsar/issues/19866#issuecomment-1556077694, it supports fallback to `serviceUrl` when `brokerServiceUrl` is not configured.

The other use case of `ClientDataImpl` is:

https://github.com/apache/pulsar/blob/aa7decc5b75894e864f3c5962c5cffad255abf25/pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java#L239-L245

So...I must say here we have a series of config problems:

* Can `serviceUrl` be a legacy option key of `brokerServiceUrl`?
* Can `serviceUrlTls` be a legacy option key of `brokerServiceUrlTls`?
* What's more vague, `tlsEnable` is deprecated and it seems no options fall back here, but it's dependent by `NamespaceService` logics.

Perhaps we can open a new issue to investigate these issues and see if we can have a clear model.

> we still need to fix all tests that configures only one of ServiceUrl or BrokerServiceUrl.

Theoretically, I agree, while it's already different from the proposal of this issue:

> verify that there is at least one serviceUrl/serviceUrlTls and at least one brokerServiceUrl/brokerServiceUrlTls set.

... although, if `BrokerServiceUrl` takes precedence over `ServiceUrl`, perhaps a warning is enough. That said, a clear model of these options is somehow missing.

**Comment by tisonkun** [comment]
We have a good start point with @JooHyukKim's #20541. There is not yet a consensus on if we want to apply strict rules on these options. We can see how the warnings hint users.

Closing as no consensus...

If anyone has a proposal for changing the current behavior (I suspect we don't need eagerly), please open a new issue with the details.

**Comment by lhotari** [comment]
For Pulsar, it's sufficient that one of the 4 urls is present. Pulsar client will use http/https based lookup if the Pulsar binary protocol url is missing.
