### ISSUE TITLE
[Doc] Add API doc for the C# client

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#19877]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

There is no API doc for [the C# client](https://github.com/apache/pulsar-dotpulsar) in the pulsar website.

### What is your suggestion?

Add API doc for the C# client.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
I've discussed with @RobertIndie, to resolve this issue, we need to finish the following tasks:

1. Generate the API reference doc.

    We want to generate C# client API reference doc (like what we did for [Python Client API](https://pulsar.apache.org/api/python/3.1.x/)). 

    @RobertIndie can help generate the doc but has no idea on [how to interact with the pulsar-site repo](https://github.com/apache/pulsar-client-python/pull/68/files#diff-2b1b69303b927a484e02c7fad9fc87d0d3ff0dc22ae1da0ecd0dc935d922a23cR197). @tisonkun Do you know how to handle this part? thank you!

2. Document the "how-to" process.

      Like what we did for [Python client API doc](https://github.com/apache/pulsar-client-python/pull/68/files#diff-2b1b69303b927a484e02c7fad9fc87d0d3ff0dc22ae1da0ecd0dc935d922a23cR195).

**Comment by tisonkun** [comment]
I suggest we pull dotpulsar authors @entvex @blankensteiner for comments and helps :)

I'm unfamiliar with C# API doc generation yet.

**Comment by entvex** [comment]
Dear @tisonkun, @Anonymitaet, and @RobertIndie,

To generate API documentation for a C# project, I would suggest using [docfx](https://github.com/dotnet/docfx). I have used it before to create API documentation for a small open-source project of my own. There is a [tutorial available here](https://blog.taranissoftware.com/document-your-net-code-with-docfx-and-github-actions). We are open to pull requests if any of you would like to take on this issue, as we are currently busy with other tasks.

Best regards.

**Comment by tisonkun** [comment]
I'm trying to take a look into this ticket in the following weeks.

**Comment by tisonkun** [comment]
Blocked by upstream issue https://github.com/dotnet/docfx/issues/8702.

**Comment by tisonkun** [comment]
Upstream fixed and released. Locally test fine. Going to proceed.

**Comment by tisonkun** [comment]
Closed. The technical part is implemented.

We need to wait for the next release to integrate with the release process.

@entvex can you open an issue in the dotpulsar repo to track this effort?

**Comment by entvex** [comment]
> Closed. The technical part is implemented.
> 
> We need to wait for the next release to integrate with the release process.
> 
> @entvex can you open an issue in the dotpulsar repo to track this effort?

Yes, we also have a few wishes we want to add. I'll create an issue and reference you in it.
