### ISSUE TITLE
[Doc] Add API doc for NodeJS client

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#19876]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

There is no API doc for the NodeJS client on the pulsar website.

### What is your suggestion?

Add API doc for the NodeJS client

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
Similar to https://github.com/apache/pulsar/issues/19877#issuecomment-1478858980

**Comment by tisonkun** [comment]
I'm working on this issue now.
