### ISSUE TITLE
[Doc] 404 links in the java client config doc

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#19878]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

There are serval 404 links in http://localhost:3000/docs/next/client-libraries-java-configs

For example:
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/16974619/226567231-b45bb686-6115-4750-8731-dbfb84a57495.png">

The link here should be `https://pulsar.apache.org/api/client/2.11.x/org/apache/pulsar/client/api/PulsarClient`, but it's `https://pulsar.apache.org/api/client/org/apache/pulsar/client/api/PulsarClient` which lost the version information.

### What is your suggestion?

Use the link like `https://pulsar.apache.org/api/client/org/apache/pulsar/client/api/PulsarClient`

### Any reference?

I'm not sure how we can use the version variable like `2.11.x` in the doc. Could someone help?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
I'm handling this now.
