### ISSUE TITLE
[Doc] the "default configuration file" link no page !

### ISSUE THREAD

**Issue by startjava** [apache/pulsar#19872]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/2.11.x/getting-started-docker/

the "default configuration file" link no page !

### What is your suggestion?

??

### Any reference?

??

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
It links to https://github.com/apache/pulsar/blob/e6b12c64b043903eb5ff2dc5186fe8030f157cfc/conf/standalone.conf which is a valid page.

Please provide a screen recording if it doesn't work for you.
