### ISSUE TITLE
Metrics: seperate topic-partion into topic and partion

### ISSUE THREAD

**Issue by NiuBlibing** [apache/pulsar#19886]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

`pulsar_msg_backlog` is use tag with "topic-partion-#" like "topic:persistent://test/test-ns/topic1-partition-1" which will generate lots of alerts in prometheus.

### Solution

generate `pulsar_msg_backlog` with two tags: topic name and partion num

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
cc @asafm since you spend a lot of time to work on Pulsar metrics, can you take a look at this issue?

**Comment by asafm** [comment]
We have this already. 
https://pulsar.apache.org/reference/#/3.0.x/config/reference-configuration-standalone?id=splittopicandpartitionlabelinprometheus

**Comment by tisonkun** [comment]
<img width="816" alt="image" src="https://github.com/apache/pulsar/assets/18818196/4010d229-2a9e-4b28-ac6d-75a24d7b4a62">

Thanks for your information! Closed as answered.
