### ISSUE TITLE
Support basic-authentication in function url

### ISSUE THREAD

**Issue by vanhtuan0409** [apache/pulsar#19910]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

reopen for https://github.com/apache/pulsar/issues/7354

When registering or updating a function via the REST API using a jar url that has the user:pass basic auth scheme is unsupported.

### Solution

The basic-auth credentials in the jar url should be forwarded along to the destination url and used to download the function jar

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by vanhtuan0409** [comment]
submitted PR https://github.com/apache/pulsar/pull/19750
@tisonkun could  you help me to check this PR?

**Comment by tisonkun** [comment]
Thanks for looking into this @vanhtuan0409! I'm reviewing the PR now.
