### ISSUE TITLE
[Bug] Current maven pulsar-client source jar empty

### ISSUE THREAD

**Issue by lifepuzzlefun** [apache/pulsar#19918]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.10.3, 2.11.0 I didn't test other versions

### Minimal reproduce step

down load source jar from central maven repository.
pulsar-client-2.11.0-sources.jar https://repo1.maven.org/maven2/org/apache/pulsar/pulsar-client/2.11.0/pulsar-client-2.11.0-sources.jar download this jar  decompress it no source code is found.

### What did you expect to see?

in IDE we need source code to debug problems.

### What did you see instead?

source code.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
I'm afraid that the real source code comes from `pulsar-client-original` and you should configure the source there.

cc @merlimat thoughts?

**Comment by lifepuzzlefun** [comment]
the intellj idea IDE default will download this jar. I tried to download many times finally find it is empty.

**Comment by tisonkun** [comment]
@lifepuzzlefun OK. I find a way to create a source jar. You may help test or wait for the next release.

**Comment by lifepuzzlefun** [comment]
@tisonkun thanks for the feedback. And we can help more people if we can re-upload the origin release missing source jar in the maven central repository. Hope to see to see the fix.

**Comment by tisonkun** [comment]
@lifepuzzlefun FYI - #19956. Be aware that you need to install client original source jar for picking it in shading pulsar-client-all.

Run:

```
mvn clean install -P apache-release -DskipTests -Dlicense.skip=true -Drat.skip=true -Dcheckstyle.skip=true
```

can verify the result.

> re-upload

I don't think so. Released artifacts should be immutable. I don't know even if Maven central support editing existing artifaces.
