### ISSUE TITLE
[Doc] Deploy on bare metal doc is having wrong URL format for metadataStoreUrl and configurationMetadataStoreUrl 

### ISSUE THREAD

**Issue by niharrathod** [apache/pulsar#19920]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

[Deploy a cluster on bare metal](https://pulsar.apache.org/docs/2.11.x/deploy-bare-metal/#deploy-pulsar-brokers) doc is having wrong url format for `metadataStoreUrl` and `configurationMetadataStoreUrl` for broker config.

Doc suggests (`zk://xyz.com:2181`)
```
metadataStoreUrl=zk://zk1.us-west.example.com:2181,zk2.us-west.example.com:2181,zk3.us-west.example.com:2181
configurationMetadataStoreUrl=zk://zk1.us-west.example.com:2181,zk2.us-west.example.com:2181,zk3.us-west.example.com:2181

```
Instead it should be (`zk:xyz.com:2181`)
```
metadataStoreUrl=zk:zk1.us-west.example.com:2181,zk2.us-west.example.com:2181,zk3.us-west.example.com:2181
configurationMetadataStoreUrl=zk:zk1.us-west.example.com:2181,zk2.us-west.example.com:2181,zk3.us-west.example.com:2181

```
or (`xyz.com:2181`)
```
metadataStoreUrl=zk1.us-west.example.com:2181,zk2.us-west.example.com:2181,zk3.us-west.example.com:2181
configurationMetadataStoreUrl=zk1.us-west.example.com:2181,zk2.us-west.example.com:2181,zk3.us-west.example.com:2181

```

### What is your suggestion?

While running single node zookeeper, single Bookie and singe Pulsar broker on my local machine, broker startup failed with below exception because of wrong metadataUrl format (`zk://localhost:2181`):
```
java.lang.IllegalArgumentException: Invalid path string "//localhost:2181" caused by empty node name specified @1
	at org.apache.zookeeper.common.PathUtils.validatePath(PathUtils.java:91) ~[org.apache.zookeeper-zookeeper-3.8.0.jar:3.8.0]
	at org.apache.zookeeper.client.ConnectStringParser.<init>(ConnectStringParser.java:61) ~[org.apache.zookeeper-zookeeper-3.8.0.jar:3.8.0]
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.<init>(ZKMetadataStore.java:92) ~[org.apache.pulsar-pulsar-metadata-2.11.0.jar:2.11.0]
	at org.apache.pulsar.metadata.impl.MetadataStoreFactoryImpl.newInstance(MetadataStoreFactoryImpl.java:56) ~[org.apache.pulsar-pulsar-metadata-2.11.0.jar:2.11.0]
	at org.apache.pulsar.metadata.impl.MetadataStoreFactoryImpl.createExtended(MetadataStoreFactoryImpl.java:36) ~[org.apache.pulsar-pulsar-metadata-2.11.0.jar:2.11.0]
	at org.apache.pulsar.metadata.api.extended.MetadataStoreExtended.create(MetadataStoreExtended.java:41) ~[org.apache.pulsar-pulsar-metadata-2.11.0.jar:2.11.0]
	at org.apache.pulsar.broker.PulsarService.createLocalMetadataStore(PulsarService.java:1051) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:719) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]

```

Setting metadataUrl to `zk:localhost:2181` or `localhost:2181` worked for me

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
Hi @BewareMyPower can you help answer the following questions? Thank you!

===============

1. Should we update the doc as below?

    Change

    `metadataStoreUrl=zk://zk1.us-west.example.com:2181,zk2.us-west.example.com:2181,zk3.us-west.example.com:2181`

    to 

    ```
    metadataStoreUrl=zk:zk1.us-west.example.com:2181,zk2.us-west.example.com:2181,zk3.us-west.example.com:2181
    configurationMetadataStoreUrl=zk:zk1.us-west.example.com:2181,zk2.us-west.example.com:2181,zk3.us- 
   west.example.com:2181
    ````

    or

    ```
    metadataStoreUrl=zk1.us-west.example.com:218,zk2.us-west.example.com:2181,zk3.us-west.example.com:2181
    configurationMetadataStoreUrl=zk1.us-west.example.com:2181,zk2.us-west.example.com:2181,zk3.us- 
     west.example.com:2181
    ```

    ?

    If both of them are workable, then they should be added to the docs.

2. What are the differences (usage) between the two methods? Any considerations when using each of them? (If any, this might be pointed out in docs).

**Comment by BewareMyPower** [comment]
Both of them are okay. The 2nd way does not have a "zk:" prefix for each `host:port` pair to be compatible with the format of the previous `zookeeperServers` config, which is deprecated now. So users can just rename the `zookeeperServers` config with the `metadataStoreUrl` config without any change.

I'd prefer the 1st way, which indicates the metadata store is ZK.

**Comment by Anonymitaet** [comment]
@BewareMyPower OK, thank you!

One more quick question:
This occurrence exists in next, 2.11.x, and 2.10.x. Should I update it in these versions? (which Pulsar version did this change introduce to?)

**Comment by Anonymitaet** [comment]
@BewareMyPower thank you! Fix in https://github.com/apache/pulsar-site/pull/492, PTAL/
