### ISSUE TITLE
[Doc] Wrong REST API doc link in Admin API - Get Started

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar#19933]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/2.11.x/admin-api-get-started/

![image](https://user-images.githubusercontent.com/18204803/227870903-11d2f591-1cc8-4415-a416-88be9041a0a6.png)

The link with the red underline above is https://pulsar.apache.org/docs/2.11.x/admin-api-get-started/reference-rest-api-overview.md/, which references an invalid link.

### What is your suggestion?

Maybe it should link to https://pulsar.apache.org/docs/2.11.x/reference-rest-api-overview/?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
GitHub Actions is downgrade now, maybe we should retrigger the website build later.
