### ISSUE TITLE
[Bug][site] The font type issue on some reference page

### ISSUE THREAD

**Issue by FushuWang** [apache/pulsar#19949]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

OS: macOS monterey
Browser: Chrome 111.0.5563.64
Pulsar Version: 2.11

### Minimal reproduce step

The font type on these three pages is different from the other pages.
https://pulsar.apache.org/reference/#/2.11.x/bookkeeper/bookkeeper
https://pulsar.apache.org/reference/#/2.11.x/pulsar-shell/pulsar-shell
https://pulsar.apache.org/reference/#/2.11.x/pulsar-daemon/pulsar-daemon

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/93108425/228205354-a52532f0-8b0a-4541-bcb2-dabed1454fbe.png">
<img width="1706" alt="image" src="https://user-images.githubusercontent.com/93108425/228206037-e6c7aa3f-f814-4f17-a9b9-a67bc6cab8be.png">
<img width="1705" alt="image" src="https://user-images.githubusercontent.com/93108425/228206110-0fb6a984-5779-465c-b73c-344ec5cad495.png">

### What did you expect to see?

Use the same font type as other pages. such like this
<img width="1721" alt="image" src="https://user-images.githubusercontent.com/93108425/228206409-d388956e-493c-43dc-9d0e-15827450054d.png">

### What did you see instead?

Different font type

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zuobiao-zhou** [comment]
I have found the problem and will make a Pr later.
