### ISSUE TITLE
[Bug][site] The right navigation doesn't work well on some reference page

### ISSUE THREAD

**Issue by FushuWang** [apache/pulsar#19948]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

OS: macOS monterey
Browser: Chrome
Pulsar Version: 2.11

### Minimal reproduce step

On this page https://pulsar.apache.org/reference/#/2.11.x/pulsar-admin/brokers, you can find the right navigation doesn't work well.

https://user-images.githubusercontent.com/93108425/228203407-758147cd-f4da-4cfe-a5ef-f1b8de7872fa.mp4

### What did you expect to see?

The right navigation works well.

### What did you see instead?

The right navigation doesn't work well on some reference page

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zuobiao-zhou** [comment]
I have found the problem and will make a Pr later.
