### ISSUE TITLE
Flaky-test: CI - Integration - Standalone, cache not found for input keys

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#19953]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/devinbost/pulsar/actions/runs/4547247024/jobs/8019335994

### Exception stacktrace

Warning: Failed to restore: The operation cannot be completed in timeout.
Cache not found for input keys: Linux-m2-dependencies-core-modules-9a40a8425648109ba46c545b035b6c8eaa0d988ecad26f356b8a56f2a992fdaf, Linux-m2-dependencies-core-modules-

More context:

##[debug]Cache Result:
##[debug]{"scope":"refs/pull/15/merge","cacheKey":"Linux-m2-dependencies-core-modules-9a40a8425648109ba46c545b035b6c8eaa0d988ecad26f356b8a56f2a992fdaf","cacheVersion":"2e1ac70454fd0cabdfd450387b61ab767e8274b896d4ca9074b9a2feace654a0","creationTime":"2023-03-28T22:45:47.5866667Z","archiveLocation":"***"}
##[debug]Archive Path: /home/runner/work/_temp/779b9bd5-1716-4dc3-8bd9-29ca90f81a62/cache.tzst
##[debug]Use Azure SDK: true
##[debug]Download concurrency: 8
##[debug]Request timeout (ms): 30000
##[debug]Cache segment download timeout mins env var: undefined
##[debug]Segment download timeout (ms): 600000
##[debug]Lookup only: false
##[debug]Downloading segment at offset 0 with length 134217728...
Received 41943040 of 927695887 (4.5%), 40.0 MBs/sec
Received 125829120 of 927695887 (13.6%), 60.0 MBs/sec
##[debug]Downloading segment at offset 134217728 with length 134217728...
Received 163577856 of 927695887 (17.6%), 52.0 MBs/sec
Received 255852544 of 927695887 (27.6%), 61.0 MBs/sec
##[debug]Downloading segment at offset 268435456 with length 134217728...
Received 314572800 of 927695887 (33.9%), 60.0 MBs/sec
Received 398458880 of 927695887 (43.0%), 63.3 MBs/sec
##[debug]Downloading segment at offset 402653184 with length 134217728...
Received 452984832 of 927695887 (48.8%), 61.7 MBs/sec
##[debug]Downloading segment at offset 536870912 with length 134217728...
Received 536870912 of 927695887 (57.9%), 63.0 MBs/sec
Received 599785472 of 927695887 (64.7%), 62.7 MBs/sec
Received 658505728 of 927695887 (71.0%), 62.0 MBs/sec
##[debug]Downloading segment at offset 671088640 with length 134217728...
Received 696254464 of 927695887 (75.1%), 59.7 MBs/sec
Received 9[235](https://github.com/devinbost/pulsar/actions/runs/4547247024/jobs/8019335994#step:6:236)01583 of 927695887 (99.5%), 14.4 MBs/sec
Received 923501583 of 927695887 (99.5%), 14.2 MBs/sec
Received 923501583 of 927695887 (99.5%), 13.9 MBs/sec
Received 923501583 of 927695887 (99.5%), 13.7 MBs/sec
Received 923501583 of 927695887 (99.5%), 13.5 MBs/sec
Received 923501583 of 927695887 (99.5%), 13.3 MBs/sec
Received 923501583 of 927695887 (99.5%), 13.1 MBs/sec
Received 923501583 of 927695887 (99.5%), 12.9 MBs/sec
Received 923501583 of 927695887 (99.5%), 12.7 MBs/sec
Received 923501583 of 927695887 (99.5%), 12.5 MBs/sec
Received 923501583 of 927695887 (99.5%), 12.4 MBs/sec
Received 923501583 of 927695887 (99.5%), 12.2 MBs/sec
Received 923501583 of 927695887 (99.5%), 12.0 MBs/sec
Received 923501583 of 927695887 (99.5%), 11.9 MBs/sec
Received 923501583 of 927695887 (99.5%), 11.7 MBs/sec
Received 923501583 of 927695887 (99.5%), 11.6 MBs/sec
Received 923501583 of 927695887 (99.5%), 11.4 MBs/sec
Received 923501583 of 927695887 (99.5%), 11.3 MBs/sec
Received 923501583 of 927695887 (99.5%), 11.1 MBs/sec
Received 923501583 of 927695887 (99.5%), 11.0 MBs/sec
Received 923501583 of 927695887 (99.5%), 10.8 MBs/sec
Received 923501583 of 927695887 (99.5%), 10.7 MBs/sec
Received 923501583 of 927695887 (99.5%), 10.6 MBs/sec
Received 923501583 of 927695887 (99.5%), 10.5 MBs/sec
Received 923501583 of 927695887 (99.5%), 10.3 MBs/sec
Received 923501583 of 927695887 (99.5%), 10.2 MBs/sec
Received 923501583 of 927695887 (99.5%), 10.1 MBs/sec
Received 923501583 of 927695887 (99.5%), 10.0 MBs/sec
Received 923501583 of 927695887 (99.5%), 9.9 MBs/sec
Received 923501583 of 927695887 (99.5%), 9.8 MBs/sec
Received 923501583 of 927695887 (99.5%), 9.7 MBs/sec
Received 923501583 of 927695887 (99.5%), 9.5 MBs/sec
Received 923501583 of 927695887 (99.5%), 9.4 MBs/sec
Received 923501583 of 927695887 (99.5%), 9.3 MBs/sec
Received 923501583 of 927695887 (99.5%), 9.2 MBs/sec
Received 923501583 of 927695887 (99.5%), 9.2 MBs/sec
Received 923501583 of 927695887 (99.5%), 9.1 MBs/sec
Received 923501583 of 927695887 (99.5%), 9.0 MBs/sec
Received 923501583 of 927695887 (99.5%), 8.9 MBs/sec
Received 923501583 of 927695887 (99.5%), 8.8 MBs/sec
Received 923501583 of 927695887 (99.5%), 8.7 MBs/sec
Received 923501583 of 927695887 (99.5%), 8.6 MBs/sec
Received 923501583 of 927695887 (99.5%), 8.5 MBs/sec
Received 923501583 of 927695887 (99.5%), 8.4 MBs/sec
Received 923501583 of 927695887 (99.5%), 8.4 MBs/sec
Received 923501583 of 927695887 (99.5%), 8.3 MBs/sec
Received 923501583 of 927695887 (99.5%), 8.2 MBs/sec
Received 923501583 of 927695887 (99.5%), 8.1 MBs/sec
Received 923501583 of 927695887 (99.5%), 8.1 MBs/sec
Received 923501583 of 927695887 (99.5%), 8.0 MBs/sec
Received 92[350](https://github.com/devinbost/pulsar/actions/runs/4547247024/jobs/8019335994#step:6:351)1583 of 927695887 (99.5%), 7.9 MBs/sec
Received 923501583 of 927695887 (99.5%), 7.8 MBs/sec
Received 923501583 of 927695887 (99.5%), 7.8 MBs/sec
Received 923501583 of 927695887 (99.5%), 7.7 MBs/sec
Warning: Failed to restore: The operation cannot be completed in timeout.
Cache not found for input keys: Linux-m2-dependencies-core-modules-9a40a8425648109ba46c545b035b6c8eaa0d988ecad26f356b8a56f2a992fdaf, Linux-m2-dependencies-core-modules-
##[debug]Save intra-action state CACHE_KEY = Linux-m2-dependencies-core-modules-9a40a8425648109ba46c545b035b6c8eaa0d988ecad26f[356](https://github.com/devinbost/pulsar/actions/runs/4547247024/jobs/8019335994#step:6:357)b8a56f2a992fdaf
Error: The action has timed out.
##[debug]Finishing: Cache Maven dependencies

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by devinbost** [comment]
Also failed on CI - Integration - Transaction for the same reason.

**Comment by devinbost** [comment]
I'm getting this repeatedly upon multiple re-runs of the CI.

**Comment by tisonkun** [comment]
This seems a timeout issue instead of cache miss issue. I'm wondering if personal CI's quota cannot afford Pulsar workflow now.

Maybe we can extend the timeout bound for cache action, 5 minutes is relatively short.

**Comment by lhotari** [comment]
> This seems a timeout issue instead of cache miss issue. I'm wondering if personal CI's quota cannot afford Pulsar workflow now.
> 
> Maybe we can extend the timeout bound for cache action, 5 minutes is relatively short.

It's not a cache miss issue. This is some sort of issue in GitHub Actions. In most cases, the cache download takes less than 20 seconds. Extending the timeout for the action step will just make the problem worse since the job will be consuming resources for longer before it fails.

**Comment by tisonkun** [comment]
OK. Let's close this issue then. We cannot do something from our side but rerun and hope GitHub Actions env be stable.

**Comment by lhotari** [comment]
@tisonkun Makes sense. the problem has been reported as https://github.com/actions/cache/issues/1141 . Sometimes common issues are discussed on https://github.com/orgs/community/discussions/categories/actions .
