### ISSUE TITLE
[Bug] Go Pulsar functions recieves message from only one topic even when provided multiple input  topics

### ISSUE THREAD

**Issue by jdattatr-tibco** [apache/pulsar#19981]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

OS: Ubuntu 20.04(LTS)
Pulsar: 2.10.1

### Minimal reproduce step

Create a pulsar function in golang:

```
package main

import (
	"context"
	"fmt"

	"github.com/apache/pulsar/pulsar-function-go/pf"
)

func HandleResponse(ctx context.Context, in []byte) error {
	fmt.Printf("Processed: %s", string(in))
	return nil
}

func main() {
	pf.Start(HandleResponse)
}
```

Build and pass the file to pulsar-admin:

```
./pulsar-admin functions localrun \
     --go /pulsar/bin/pulsarFuncGolang \
     --inputs persistent://public/default/sourcetopic1,persistent://public/default/sourcetopic2 \
     --tenant public \
     --namespace default \
     --name flogoPulsarFunction
```

Publish message on both the topics, we could only see the function logs of recieved messages on the last topic mentioned (which is sourcetopic2 in the example above)

### What did you expect to see?

Pulsar function should listen to all the topics mentioned

### What did you see instead?

Pulsar function listens to only the last topic mentioned

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jiangpengcheng** [comment]
As far as I know, the GO runtime hasn't yet supported multiple topics, below is the code:

```java
        if (instanceConfig.getFunctionDetails().getSource().getInputSpecsMap() != null) {
            for (String inputTopic : instanceConfig.getFunctionDetails().getSource().getInputSpecsMap().keySet()) {
                goInstanceConfig.setSourceSpecsTopic(inputTopic);
            }
        }
```

We can see that when multiple topics are specified, the last one will overwrite the previous topics.

https://github.com/apache/pulsar/blob/master/pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java#L206-L210

It may take some time to support such a feature, but I will take a look
