### ISSUE TITLE
[improve][doc] Optimize "Get Started" for transactions

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#19996]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

There are some issues in current [txn docs - get started](https://pulsar.apache.org/docs/next/txn-use/#transaction-api):

- Doc structure is not clear.
- Some docs are not "MVP" for a get started. We should give learners minimal info to run it up.
- Some examples are incorrect.

### What is your suggestion?

- Make the doc structure more clear.
- Move some docs to another topic to keep learners focused on the minimal info to get started.
- Remove old examples and add new ones.

@congbobo184 I've recorded my thoughts [here](https://docs.google.com/document/d/1KDCSnYJPC31El5AopqII7VboKFY11MojdvefrhfCZwQ/edit), PTAL, TIA!

cc @Huanli-Meng 

### Any reference?

N/A

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Hi @Anonymitaet! The gdoc link has strict permission setting. Also it's not persisted in public domain. Could you export it to the issue?

**Comment by Anonymitaet** [comment]
@tisonkun Thanks! That gdoc servers as a temporary place that I'll discuss with @congbobo184 this afternoon. I'll make our thoughts public once we reach a consensus on that.

**Comment by Anonymitaet** [comment]
Fix this in https://github.com/apache/pulsar-site/pull/501

**Comment by tisonkun** [comment]
https://github.com/apache/pulsar-site/pull/501 has been merged. Close this issue as resolved.

Thanks for your contributions!
