### ISSUE TITLE
should support IPv4/IPv6 dualstack

### ISSUE THREAD

**Issue by zhangdejin-tom** [apache/pulsar#19997]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

the Pular and broker should support the IPv4/IPv6 dualstack

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
@zhangdejin-tom could you please provide more background and context? Better if you can have a reproduced repo for what's proposed here. One line "request" just does not work.

**Comment by tisonkun** [comment]
Closed as stale.
