### ISSUE TITLE
P99 of write increases largely while Pulsar disk reads increase

### ISSUE THREAD

**Issue by chrisxrepo** [apache/pulsar#20015]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

v2.10.3 journal nvme + ledger hdd

### Minimal reproduce step

1. 生产一段时间数据
2. 开启消费者消费数据
3. 观察监控

### What did you expect to see?

写入耗时无明显变化

### What did you see instead?

 pulsar写入耗时
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/7782939/230062323-488fbdfa-d002-4f0d-a4ab-bbd8889c898c.png">

bookie监控
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/7782939/230062475-0d9467e6-ce3c-4c9e-bcad-6dee69325aac.png">
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/7782939/230062552-35ceae04-6105-42c9-96bb-77d2f8f64176.png">

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
This should be a use-case question. Moved to the Q&A forum.

Also, please translate the content to English for most community members reading your questions.
