### ISSUE TITLE
CI: pulsar does not run tests with httpServer enabled

### ISSUE THREAD

**Issue by dlg99** [apache/pulsar#20071]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Problem found in private tests, hot-fixed https://github.com/apache/pulsar/pull/20070 (which does not add proper tests)

### Solution

some of the e2e integration tests should enable httpServer, possibly other options to provide better coverage

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by MMirelli** [comment]
Please assign this to me.

**Comment by tisonkun** [comment]
@MMirelli assigned. But would you explain your plan and an estimate since this is somehow a release blocker?

**Comment by MMirelli** [comment]
I would:
1. clone an integration test (like [this one](https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/tests/integration/src/test/java/org/apache/pulsar/tests/integration/upgrade/PulsarZKDowngradeTest.java#L44-L43))
2. pass `httpServerEnabled=true` when starting up the server
3. running some smoke test after deployment

WIP: https://github.com/apache/pulsar/compare/master...MMirelli:pulsar:mm-implement-integration-test-with-httpServer-enabled-20071
4. replace [this](https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/tests/integration/src/test/java/org/apache/pulsar/tests/integration/upgrade/PulsarZKDowngradeTest.java#L61-L64)

**Comment by tisonkun** [comment]
Thanks for your update @MMirelli!

After a closer look I find that it's not something wrong with CI settings and not a release blocker but an enhancement to improve test coverage. Go ahead and feel free to ping me as a reviewer once you have a workable patch.
