### ISSUE TITLE
[Bug] can not got apache-pulsar-2.10.4-bin.tar.gz

### ISSUE THREAD

**Issue by chrisxrepo** [apache/pulsar#20153]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

v2.10.4

### Minimal reproduce step

get pulsar v2.10.4 binary from pulsar.apache.org

### What did you expect to see?

url: https://archive.apache.org/dist/pulsar/pulsar-2.10.4/apache-pulsar-2.10.4-bin.tar.gz 
i can not got apache-pulsar-2.10.4-bin.tar.gz, i got 404

### What did you see instead?

return apache-pulsar-2.10.4-bin.tar.gz

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by nicoloboschi** [comment]
Now it's uploaded, please retry
