### ISSUE TITLE
[Doc] Message retention detail explanation

### ISSUE THREAD

**Issue by yaalsn** [apache/pulsar#20167]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

![image](https://user-images.githubusercontent.com/10069311/233829054-eca01855-284d-4e06-a17c-50e6d192a633.png)

The `retention` in the detailed explanation makes me feel confused. I don't know if this means `Always resolved message` or `Always delete message`. If I understand it with `Disable the message retention policy` which means the messages will never be deleted.

### What is your suggestion?

Let's change it to `Disable message retention, which means messages are not reserved (by default).`

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
@yaalsn Thanks for reporting this issue.

Since you tick "I'm willing to submit a PR!" box, I'd like to check if you're going to submit a patch against http://github.com/apache/pulsar-site? If so, feel free to ping me as a reviewer.

**Comment by yaalsn** [comment]
https://github.com/apache/pulsar-site/pull/535 @tisonkun PTAL

**Comment by tisonkun** [comment]
Closed by https://github.com/apache/pulsar-site/pull/535.

@yaalsn FYI - PR closing magic can work cross-repo (I'm not sure if only workable in the same org but pulsar and pulsar-site are in the case).
