### ISSUE TITLE
add maven source plugin

### ISSUE THREAD

**Issue by yonyong** [apache/pulsar#20193]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

The content of the pulsar client source jar package in the Maven repository is empty, resulting in developers being unable to read the code with comments after downloading the source jar.

### Solution

I have submitted a [PR：20192](https://github.com/apache/pulsar/pull/20192)

Also, may I ask if the newly submitted PR will only be merged into the latest version?
For example, our company uses the 2.6.0 version of the jar package. Would it be possible to merge this change into 2.6.0?

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
See https://github.com/apache/pulsar/pull/20192#issuecomment-1526868123.

This is a known and fixed issue. May be delivered at 3.0.
