### ISSUE TITLE
[Bug] While Setting BookieAffinity group, not using the broker config to set the default number of bundles

### ISSUE THREAD

**Issue by syk-coder** [apache/pulsar#20194]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

branch: master
commitId: eedf7026ae60f39bcf74ce67728b47d966fe237f

### Minimal reproduce step

Create a namespace under a tenant
Set bookie-affinity group for the namespace

### What did you expect to see?

Pulsar should read the number of bundles('defaultNumberOfNamespaceBundles') data from the broker config file and use that instead of using a single bundle while creating the affinity group.

### What did you see instead?

Broker is calling the default bundle method in PoliciesUtil and setting the bundle size as 1

**NamespacesBase.java**
getLocalPolicies().setLocalPoliciesWithCreate(namespaceName, oldPolicies -> {
                LocalPolicies localPolicies = oldPolicies.map(
                        policies -> new LocalPolicies(policies.bundles,
                                bookieAffinityGroup,
                                policies.namespaceAntiAffinityGroup))
                        .orElseGet(() -> new LocalPolicies(**defaultBundle()**,
                                bookieAffinityGroup,
                                null));
                log.info("[{}] Successfully updated local-policies configuration: namespace={}, map={}", clientAppId(),
                        namespaceName, localPolicies);

**PoliciesUtil.java**
public static BundlesData defaultBundle() {
        List<String> boundaries = new ArrayList<>();
        boundaries.add(FIRST_BOUNDARY);
        boundaries.add(LAST_BOUNDARY);
        return BundlesData.builder()
                .numBundles(1)
                .boundaries(boundaries)
                .build();
    }

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
Hi @syk-coder , Do we have any updates?
