### ISSUE TITLE
[Doc] Can't find folder when generating the reference doc

### ISSUE THREAD

**Issue by RobertIndie** [apache/pulsar#20214]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

When generating the reference doc according to https://pulsar.apache.org/contribute/release-process/#reference, it raises this error:
```
poetry run bin/reference-doc-generator.py --master-path=/Users/aaronrobert/codebase/pulsar.branch-3.0 --version=3.0.0

Traceback (most recent call last):
  File "/Users/aaronrobert/codebase/pulsar-site/tools/pytools/bin/reference-doc-generator.py", line 61, in <module>
    pulsar_admin_clidoc_generator.execute(master_path, version)
  File "/Users/aaronrobert/codebase/pulsar-site/tools/pytools/lib/execute/pulsar_admin_clidoc_generator.py", line 52, in execute
    with (reference / f'{command}.md').open('w') as f:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/Users/aaronrobert/codebase/pulsar-site/static/reference/3.0.x/pulsar-admin/broker-stats.md'
```

It is trying to find the folder `pulsar-site/static/reference/3.0.x`, but it doesn't exist.

### What is your suggestion?

My workaround is to create that folder manually: `cp -r next 3.0.x`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Thanks for reporting this issue! We should protectively create the parent folder on missing.
