### ISSUE TITLE
[Doc] The latest document should point to 3.x

### ISSUE THREAD

**Issue by nodece** [apache/pulsar#20220]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

1. Open https://pulsar.apache.org/
2. Click [QUICKSTART](https://pulsar.apache.org/docs) button

Then you can see the 2.11 document, this is incorrect, should be 3.x document.

### What is your suggestion?

The Pulsar 3.0.0 has been released, so the document should point to 3.x.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by RobertIndie** [comment]
@tisonkun Is this something that we need to fix in the release process?

**Comment by hpvd** [comment]
search not working yet on 
https://pulsar.apache.org/docs/3.0.x/
see screenshot
-> does the indexing of new doc needs to be triggered manually?
![2023-05-04_10h50_59](https://user-images.githubusercontent.com/5681880/236156812-0863ab0c-2b8f-4caa-9547-b91fb50a9e62.png)

**Comment by tisonkun** [comment]
Algolia Index build periodically every week - IIRC in Tuesday.

**Comment by nodece** [comment]
[LEARN MORE](https://pulsar.apache.org/docs/concepts-overview) is correct, but [QUICKSTART](https://pulsar.apache.org/docs) still is incorrect.

**Comment by tisonkun** [comment]
> [LEARN MORE](https://pulsar.apache.org/docs/concepts-overview) is correct, but [QUICKSTART](https://pulsar.apache.org/docs) still is incorrect.

Cannot reproduce. I suppose it's about browser cache. Maybe you can try in incognito window.
