### ISSUE TITLE
Could you also help change `orElse` to `orElseGet` at line 1713 and 1763

### ISSUE THREAD

**Issue by syk-coder** [apache/pulsar#20278]
Change `orElse` to `orElseGet` at line 1713 and 1763 and also for anti affinity group the default bundle size should be taken from the user-supplied configuration value.

Even at those places and the remaining places where we are creating **new LocalPolicies()** we are not using the bundle size from the configuration. Should I change it to have the bundle size supplied by the user from the configuration? Should we do it in this PR or shall we create another bug and link it and fix them there?

_Originally posted by @syk-coder in https://github.com/apache/pulsar/issues/20250#issuecomment-1539471991_

**Comment by tisonkun** [comment]
Thanks for following up this issue. Would you like to submit https://github.com/syk-coder/pulsar/pull/2 to the upstream?
