### ISSUE TITLE
How to configure pulsar to support ipv6

### ISSUE THREAD

**Issue by chengsir520** [apache/pulsar#20331]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.10.0

### Minimal reproduce step

vim standalone.conf
bindAddress=[:::]

### What did you expect to see?

Verify that pulsar supports ipv6

### What did you see instead?

Caused by: java.net.URISyntaxException: Expected hex digits or IPv4 address at index 12: pulsar://[:::]:6650

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by wangjialing218** [comment]
set `bindAddress=0.0.0.0` and set `-Djava.net.preferIPv4Stack=false` in `bin/pulsar`.

**Comment by tisonkun** [comment]
Closed as answered. If there's any other questions, feel free to ask in the [Q&A forum](https://github.com/apache/pulsar/discussions/categories/q-a).
