### ISSUE TITLE
[Doc] The rendering of REST APIs is wrong

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar#20345]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

For example, see https://pulsar.apache.org/docs/3.0.x/admin-api-schemas/#set-schema-compatibility-check-strategy

The original document is:

```
Send a `GET` request to this endpoint: {@inject: endpoint|GET|/admin/v2/namespaces/:tenant/:namespace|operation/schemaCompatibilityStrategy?version=@pulsar:version_number@}
```

![image](https://github.com/apache/pulsar/assets/18204803/341dbaae-2457-4581-b423-d45ed8224e21)

However, the website only shows `GET|/admin/v2/namespaces/:tenant/:namespace`. The complete URL path should be `GET|/admin/v2/namespaces/:tenant/:namespace/schemaCompatibilityStrategy`.

Besides, the query params are ignored as well but I think they are not important.

### What is your suggestion?

We should parse the REST API after the `@inject` annotation with a correct way.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by shy-share** [comment]
This is indeed a bit strange, obviously the git repository is correct, but it is wrong to display it on the web page

**Comment by tisonkun** [comment]
I don't have too much time to fix it and I postpone it previously for waiting to the website redesign. Now the redesign is landed we can proceed this issue.

It's related about this code snippet when I first take a look at it:

<img width="1728" alt="image" src="https://github.com/apache/pulsar/assets/18818196/9d80580a-55d4-4154-abd8-b4661e213470">

<img width="1728" alt="image" src="https://github.com/apache/pulsar/assets/18818196/bf9def9c-773c-42eb-99ea-ae9a64b1c818">

You can try to propose a solution or I'm hopefully handle it in days.

**Comment by shy-share** [comment]
@tisonkun cc my pr

**Comment by tisonkun** [comment]
Thanks for your contribution @shy-share! Merged.
