### ISSUE TITLE
[Bug] [site] Google/Bing searches return javadoc for version 2.4.2 specifically

### ISSUE THREAD

**Issue by dlg99** [apache/pulsar#20390]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

current as of may 24th 2023

### Minimal reproduce step

<img width="686" alt="image" src="https://github.com/apache/pulsar/assets/8622884/aaed237a-8d86-4e39-88e8-f667beb5d182">

### What did you expect to see?

javadoc from more recent pulsar version (next/dev or 3.0, maybe 2.11)

### What did you see instead?

docs from pulsar 2.4.2

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by shy-share** [comment]
This is indeed a bit weird, but I don't know how to deal with it, it seems to be a problem with Google search engine.
Is it because this version has more clicks?

**Comment by tisonkun** [comment]
When we handle the SEO part in several previous PRs, we don't cover these API docs part.

That is, we add `noIndex` metadata for all pages generated by Docusaurus, but it doesn't work for API docs.

Although, it's possible to add a robots.txt file to manually tell the Google search engine to exclude some page, like what I did for legacy pages: https://github.com/apache/pulsar-site/pull/495

@shy-share You can try to develop such a file and add it under the [static](https://github.com/apache/pulsar-site/tree/main/static) folder, and thus the file will be copied to the root path of the website after deployed.

**Comment by tisonkun** [comment]
cc @momo-jun @Anonymitaet
