### ISSUE TITLE
[Bug] pulsar-all 3.0.0 docker image contains Pulsar 2.11.0

### ISSUE THREAD

**Issue by packageman** [apache/pulsar#20420]
### Version

Ubuntu 20.04, Pulsar 3.0.0

### Minimal reproduce step

<img width="1068" alt="image" src="https://github.com/apache/pulsar/assets/12949466/2e7f1bc2-aeb8-4e72-aae3-73cddc02effd">

### What did you expect to see?

pulsar-related libs in pulsar-all:3.0.0 image should be 3.0.0 also.

### What did you see instead?

pulsar-related libs in pulsar-all:3.0.0 is 2.11.0.

**Comment by tisonkun** [comment]
cc @cbornet @RobertIndie the Release Manager for this version.

**Comment by RobertIndie** [comment]
I think the root cause is that we use `apachepulsar/pulsar:latest` to build the `pulsar-all` image. 
https://github.com/apache/pulsar/blob/ab810f4f59dd7d6c8b5313ceb334873a7d2cde31/docker/pulsar-all/Dockerfile#L29-L31

But at the time of building Pulsar 3.0.0, `apachepulsar/pulsar:latest` was pointing to version 2.11.0(I'm curious why it's not 2.11.1).

We can see that the connectors  and offloaders is pointing to the 3.0.0:
```
docker run apachepulsar/pulsar-all:3.0.0 ls connectors
LICENSE
README
pulsar-io-aerospike-3.0.0.nar
pulsar-io-alluxio-3.0.0.nar
pulsar-io-batch-data-generator-3.0.0.nar
pulsar-io-canal-3.0.0.nar
pulsar-io-cassandra-3.0.0.nar
pulsar-io-data-generator-3.0.0.nar
pulsar-io-debezium-mongodb-3.0.0.nar
pulsar-io-debezium-mssql-3.0.0.nar
pulsar-io-debezium-mysql-3.0.0.nar
pulsar-io-debezium-oracle-3.0.0.nar
pulsar-io-debezium-postgres-3.0.0.nar
pulsar-io-dynamodb-3.0.0.nar
pulsar-io-elastic-search-3.0.0.nar
pulsar-io-file-3.0.0.nar
pulsar-io-flume-3.0.0.nar
pulsar-io-hbase-3.0.0.nar
pulsar-io-hdfs2-3.0.0.nar
pulsar-io-hdfs3-3.0.0.nar
pulsar-io-http-3.0.0.nar
pulsar-io-influxdb-3.0.0.nar
pulsar-io-jdbc-clickhouse-3.0.0.nar
pulsar-io-jdbc-mariadb-3.0.0.nar
pulsar-io-jdbc-openmldb-3.0.0.nar
pulsar-io-jdbc-postgres-3.0.0.nar
pulsar-io-jdbc-sqlite-3.0.0.nar
pulsar-io-kafka-3.0.0.nar
pulsar-io-kafka-connect-adaptor-3.0.0.nar
pulsar-io-kinesis-3.0.0.nar
pulsar-io-mongo-3.0.0.nar
pulsar-io-netty-3.0.0.nar
pulsar-io-nsq-3.0.0.nar
pulsar-io-rabbitmq-3.0.0.nar
pulsar-io-redis-3.0.0.nar
pulsar-io-solr-3.0.0.nar
pulsar-io-twitter-3.0.0.nar
```
But the libraries under lib are not.

If my assumption is correct, then this is a serious problem. 

I'm rebuilding the `pulsar-all` image. And then I will publish it to the docker hub.
We also need to fix this [dockerfile](https://github.com/apache/pulsar/blob/master/docker/pulsar-all/Dockerfile)

**Comment by tisonkun** [comment]
Thanks for your investigation @RobertIndie!

Then this can be of the same reason https://github.com/apache/pulsar/issues/19544#issuecomment-1551881272.

cc @nodece @michaeljmarshall for your information.

**Comment by gaecfov** [comment]
> I think the root cause is that we use `apachepulsar/pulsar:latest` to build the `pulsar-all` image.
> 
> https://github.com/apache/pulsar/blob/ab810f4f59dd7d6c8b5313ceb334873a7d2cde31/docker/pulsar-all/Dockerfile#L29-L31
> 
> But at the time of building Pulsar 3.0.0, `apachepulsar/pulsar:latest` was pointing to version 2.11.0(I'm curious why it's not 2.11.1).
> 
> We can see that the connectors and offloaders are pointing to the 3.0.0:
> 
> ```
> docker run apachepulsar/pulsar-all:3.0.0 ls connectors
> LICENSE
> README
> pulsar-io-aerospike-3.0.0.nar
> pulsar-io-alluxio-3.0.0.nar
> pulsar-io-batch-data-generator-3.0.0.nar
> pulsar-io-canal-3.0.0.nar
> pulsar-io-cassandra-3.0.0.nar
> pulsar-io-data-generator-3.0.0.nar
> pulsar-io-debezium-mongodb-3.0.0.nar
> pulsar-io-debezium-mssql-3.0.0.nar
> pulsar-io-debezium-mysql-3.0.0.nar
> pulsar-io-debezium-oracle-3.0.0.nar
> pulsar-io-debezium-postgres-3.0.0.nar
> pulsar-io-dynamodb-3.0.0.nar
> pulsar-io-elastic-search-3.0.0.nar
> pulsar-io-file-3.0.0.nar
> pulsar-io-flume-3.0.0.nar
> pulsar-io-hbase-3.0.0.nar
> pulsar-io-hdfs2-3.0.0.nar
> pulsar-io-hdfs3-3.0.0.nar
> pulsar-io-http-3.0.0.nar
> pulsar-io-influxdb-3.0.0.nar
> pulsar-io-jdbc-clickhouse-3.0.0.nar
> pulsar-io-jdbc-mariadb-3.0.0.nar
> pulsar-io-jdbc-openmldb-3.0.0.nar
> pulsar-io-jdbc-postgres-3.0.0.nar
> pulsar-io-jdbc-sqlite-3.0.0.nar
> pulsar-io-kafka-3.0.0.nar
> pulsar-io-kafka-connect-adaptor-3.0.0.nar
> pulsar-io-kinesis-3.0.0.nar
> pulsar-io-mongo-3.0.0.nar
> pulsar-io-netty-3.0.0.nar
> pulsar-io-nsq-3.0.0.nar
> pulsar-io-rabbitmq-3.0.0.nar
> pulsar-io-redis-3.0.0.nar
> pulsar-io-solr-3.0.0.nar
> pulsar-io-twitter-3.0.0.nar
> 
> docker run apachepulsar/pulsar-all:3.0.0 ls offloaders
> tiered-storage-file-system-3.0.0.nar
> tiered-storage-jcloud-3.0.0.nar
> ```
> 
> But the libraries under `lib/` are not.
> 
> If my assumption is correct, then this is a serious problem. The `pulsar-all:3.0.0` is actually a version 2.11.0 of Pulsar but with 3.0.0 connectors and offloaders.
> 
> I'm rebuilding the `pulsar-all` image. And then I will publish it to the docker hub. We also need to fix this [dockerfile](https://github.com/apache/pulsar/blob/master/docker/pulsar-all/Dockerfile)

The configuration file also needs to be checked. I encountered a problem of missing 'enableBrokerSideSubscriptionPatternEvaluation' parameter in the broker.conf, but it is correct in pulsar:3.0.0.

**Comment by lhotari** [comment]
> I think the root cause is that we use `apachepulsar/pulsar:latest` to build the `pulsar-all` image.
> 
> https://github.com/apache/pulsar/blob/ab810f4f59dd7d6c8b5313ceb334873a7d2cde31/docker/pulsar-all/Dockerfile#L29-L31
> 
> But at the time of building Pulsar 3.0.0, `apachepulsar/pulsar:latest` was pointing to version 2.11.0(I'm curious why it's not 2.11.1).

@cbornet @RobertIndie 
I don't think that this is the root cause. In the current build, all docker images should be built locally without pulling `apachepulsar/pulsar:latest` from the remote repository. In that case, there's no chance that versions get mixed regardless of the remote versions.

How did the docker images get built and pushed?

We should be updating the release guide if there are problems (which was very common in the past).
I'd rather have the release guide in the GitHub wiki since that would lower the barrier to update the docs if there are issues that need to be addressed.
The current release process is maintained on the website, https://pulsar.apache.org/contribute/release-process/#stage-docker-images . That's fine as long as we continue to maintain it.

**Comment by RobertIndie** [comment]
@lhotari 
When we build the image while preparing the release candidate, we use our own account name as docker hub org name instead of `apachepulsar`.  You can check the release process here: https://pulsar.apache.org/contribute/release-process/#stage-docker-images (But actually, we need to modify this process because we have changed our build script)

Therefore the `apachepulsar/pulsar` is not pointed to the locally built image, which causes the issue.

**Comment by RobertIndie** [comment]
Hi, @gaecfov 

> The configuration file also needs to be checked. I encountered a problem of missing 'enableBrokerSideSubscriptionPatternEvaluation' parameter in the broker.conf, but it is correct in pulsar:3.0.0.

This is the same issue. 'enableBrokerSideSubscriptionPatternEvaluation' only be included in 3.0.0. But currently, `pulsar-all:3.0.0` is actually an image for 2.11.0. This problem will be fixed after I republish the image.
Here is the verification:
```
docker run snzkyang/pulsar-all:3.0.0 cat conf/broker.conf | grep enableBrokerSideSubscriptionPatternEvaluation

enableBrokerSideSubscriptionPatternEvaluation=true
```

**Comment by tisonkun** [comment]
> I'd rather have the release guide in the GitHub wiki since that would lower the barrier to update the docs if there are issues that need to be addressed.

No. GitHub wiki is a half completed Git repo that few people know how to trace its history or collaborate with comment. As a committer you can already update the release process on the site repo without any barrier - what's extra here?

**Comment by lhotari** [comment]
> > I'd rather have the release guide in the GitHub wiki since that would lower the barrier to update the docs if there are issues that need to be addressed.
> 
> No. GitHub wiki is a half completed GitHub repo that few people know how to trace its history or collaborate with comment. As a committer you can already update the release process on the site repo without any barrier - what's extra here?

If the instructions aren't maintained, there might be a barrier. It could be resolved by requesting everyone performing releases to ask for help and/or update the instructions if there are problems.

**Comment by lhotari** [comment]
> I suggest we only use the `apachepulsar/X.Y.Z` image, not the `latest` image, which can avoid this issue.

I don't think that solves the problem. Both images should be built locally and nothing should ever be pulled.

**Comment by cbornet** [comment]
I'm sorry that this happened.
We used the following command to have cross-compilation for ARM:
```
mvn install -DUBUNTU_MIRROR=http://azure.archive.ubuntu.com/ubuntu/ \
        -DskipTests \
        -Pmain,docker -Pdocker-push \
        -Ddocker.platforms=linux/amd64,linux/arm64 \
        -Ddocker.organization=cbornet \
         -pl docker/pulsar,docker/pulsar-all
 ```
 So there's probably something to do better with this command.

**Comment by lhotari** [comment]
> > I'd rather have the release guide in the GitHub wiki since that would lower the barrier to update the docs if there are issues that need to be addressed.
> 
> No. GitHub wiki is a half completed GitHub repo that few people know how to trace its history or collaborate with comment. As a committer you can already update the release process on the site repo without any barrier - what's extra here?

@tisonkun The process isn't up-to-date. I created #20438 to track the outdated release process.

**Comment by packageman** [comment]
> I'm rebuilding the pulsar-all image. And then I will publish it to the docker hub.

@RobertIndie Have you pushed the pulsar-all image to the docker hub? I checked it was still pushed a month ago.

**Comment by RobertIndie** [comment]
@packageman We need a new release 3.0.1 to address this issue. Here is the discussion email about the 3.0.1 release: https://lists.apache.org/list.html?dev@pulsar.apache.org

**Comment by RobertIndie** [comment]
[The Pulsar 3.0.1 has been released](https://lists.apache.org/thread/jwmrv554gpkyqsvcm00ly89kp42lq38q). Please get the new docker image here: https://hub.docker.com/layers/apachepulsar/pulsar-all/3.0.1/images/sha256-40de86dccb1a76f4b6b011be94d7c36e49c18a0a42560363c0b6dd3fd2935d7a?context=explore
