### ISSUE TITLE
[Test] Remove Auth0 service dependency from all unit tests

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#20473]
### Description

Auth0 service dependency in TokenOauth2AuthenticatedProducerConsumerTest was removed in #20465.

It turns out that there is an Auth0 service dependency also in these 2 locations:

https://github.com/apache/pulsar/blob/d565c953a7deab1ea93949bfefa44477e51e417f/pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTlsTestWithAuth.java#L67-L70

https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/pulsar-testclient/src/test/java/org/apache/pulsar/testclient/Oauth2PerformanceTransactionTest.java#L87-L89

These should also be covered. 

An additional detail is that it would be better to change the OAuth2 audience claim `https://dev-kt-aa9ne.us.auth0.com/api/v2/` in TokenOauth2AuthenticatedProducerConsumerTest during this change since that could cause confusion for future maintainers. 

### Implementation hints

It's possible to share test classes via pulsar-broker test-jar dependency:

```
        <dependency>
          <groupId>${project.groupId}</groupId>
          <artifactId>pulsar-broker</artifactId>
          <version>${project.version}</version>
          <scope>test</scope>
          <type>test-jar</type>
        </dependency>
```
This is already specified in `pulsar-proxy/pom.xml` and `pulsar-testclient/pom.xml`

It would be possible to extract some test classes from TokenOauth2AuthenticatedProducerConsumerTest for Wiremocking OAuth and put the classes under some package in pulsar-broker/src/test/java/org/apache/pulsar . This would be a way to reduce code duplication across tests where similar logic is needed.

**Comment by michaeljmarshall** [comment]
Great points @lhotari. I can follow up on this tomorrow.
