### ISSUE TITLE
Return exit code 1 when `pulsar-admin` commands fail

### ISSUE THREAD

**Issue by SpencerC** [apache/pulsar#20485]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Run `bin/pulsar-admin sources create --source-config-file doesnotexist.yaml && echo $?`. The output clearly shows an error, but renders a success return code.

I just spent an hour debugging what turned out to be a spelling error. 😝

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by SpencerC** [comment]
Not at the moment

**Comment by tisonkun** [comment]
Since @SpencerC doesn't tick the " I'm willing to submit a PR!", I believe @JooHyukKim you can continue to work on this ticket.

**Comment by tisonkun** [comment]
> I assumed the checkbox was checked only because it existed

That can be the case sometimes (or often), lol.

**Comment by SpencerC** [comment]
Thanks! I don't know the codebase that well yet, and thought this might be trivially easy for someone who did.
