### ISSUE TITLE
Rewrite BrokerServiceTest#testBrokerStatsTopicLoadFailed

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#20495]
The BrokerServiceTest#testBrokerStatsTopicLoadFailed is disabled by #20494.

> 2. Remove the test case and if the coverage is necessary, file a new ticket to add it back.

_Originally posted by @tisonkun in https://github.com/apache/pulsar/pull/20494#pullrequestreview-1462643509_

The test BrokerServiceTest#testBrokerStatsTopicLoadFailed introduced in #19236 is invalid. 
* It modifies the current shared state and that causes other tests to fail. 
* The test uses Awaitility with a 2 minute timeout. That is too long for unit tests.

**Comment by poorbarcode** [comment]
https://github.com/apache/pulsar/pull/22580 is trying to fix this issue
