### ISSUE TITLE
[Doc] [Debezium connector] how to authenticate database history topics

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#20501]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

Lack of usage info. 
More context see https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1685980377831439

### What is your suggestion?

Add missing info

### Any reference?

N/A

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
Hi @nlu90 can you help answer the following questions? Thank you!

As suggested by @sijie, 

> If you don't set dataabase.history.pulsar.service.url, it will use the the client_auth_plugin and client_auth_params from the connector to connect.

I found that we might need to update the [Debezium source connector doc](https://pulsar.apache.org/docs/3.0.x/io-cdc-debezium/).

1. Does it mean `database.history.pulsar.service.url` is optional? 

2. Should we add a note like below?

<img width="1400" alt="image" src="https://github.com/apache/pulsar/assets/50226895/e06823e8-ba2d-4f56-8a1e-e3fdaf0907ce">

3. As @sijie indicated `I think we fixed the issue but forgot to update the documentation`, can you attach the code PR link (so that I can get more context)?

**Comment by joelsonoda** [comment]
In my opinion, the description that would make the most sense is something like `if database.history.pulsar.service.url is not set, the pulsar client configuration will use the connector's client configuration` or something like that.

**Comment by Anonymitaet** [comment]
Hi @joelsonoda thanks for your suggestion!

What's the meaning of `the pulsar client configuration will use the connector's client configuration`? Can you explain a bit more?

Do `client_auth_plugin` and `client_auth_params` belong to Pulsar client configurations?

If so, how about updating the note like

> If `database.history.pulsar.service.url` is not set, the `client_auth_plugin` and `client_auth_params` (Pulsar client's configurations) will be used to connect.

**Comment by joelsonoda** [comment]
I meant to say that 'if the database.history.pulsar.service.url is not set, the database history pulsar client will use the same client settings as the source connector'. It looks like it will copy more than just the client_auth_plugin and client_auth_params.

**Comment by Anonymitaet** [comment]
@joelsonoda thanks for your explanations! Then how about adding a note like below?

> Note: If `database.history.pulsar.service.url` is not set, then the database history Pulsar client will use the same client settings as those of the source connector, such as `client_auth_plugin` and `client_auth_params`.

**Comment by joelsonoda** [comment]
This seems like a very sensible explanation

**Comment by Anonymitaet** [comment]
@nlu90 can you help answer question 3 in https://github.com/apache/pulsar/issues/20501#issuecomment-1577758724? Thank you!

**Comment by nlu90** [comment]
@Anonymitaet Regarding your questions:

For question 3, pulsar 2.8, 2.9, 2.10, 2.11, and 3.0 all include this fix.

For question 4, the fixing PR link is https://github.com/apache/pulsar/pull/12145.

**Comment by Anonymitaet** [comment]
@joelsonoda @nlu90
Fix in https://github.com/apache/pulsar-site/pull/605, PTAL, thank you!
