### ISSUE TITLE
org.apache.pulsar.client.api.Producer and org.apache.pulsar.client.api.Consumer may need provider it has Closed

### ISSUE THREAD

**Issue by maozhitao12450** [apache/pulsar#20511]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

We want to report client metrics to Prometheus.
Currently, we save a reference to the consumer/producer when it is created, and then we retrieve the metrics from org.apache.pulsar.client.api.Producer#getStats when updating the metrics.
However, in practice, some services use dynamically created and destroyed producers/consumers. Additionally, since the closing of producers and consumers is done during business operations, Pulsar does not provide any interceptors for closing them, and I cannot listen for their close events. Furthermore, pulsar do not provide an interface to check whether they are closed.

### Solution

Could you provide an isClose interface?

### Alternatives

It would be more appropriate to provide an interface that retrieves the current state of the producer/consumer, returning the org.apache.pulsar.client.impl.HandlerState.State of the current instance.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
This is a duplicate of https://github.com/apache/pulsar/discussions/20510.
