### ISSUE TITLE
Factor out integration test utils

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#20664]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Prerequisite for moving out connectors (Pulsar IO) and the trino plugin (Pulsar SQL).

### Solution

The basic shared utils should include testcontainers-based Pulsar testing containers and the test suite setup utils

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
cc @asafm @lhotari I'll try to visit this topic in the following days.

**Comment by dave2wave** [comment]
I'm sure you've found: https://github.com/apache/pulsar/tree/master/docker

**Comment by tisonkun** [comment]
No longer a blocker since we drop all the pulsar-sql code.
