### ISSUE TITLE
[Bug] pulsar-all 3.0.0 docker image contains wrong version

### ISSUE THREAD

**Issue by zzzz465** [apache/pulsar#20670]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

ubuntu 22.04 / 5.10.102.1-WSL amd64

### Minimal reproduce step

1. docker pull apachepulsar/pulsar-all:3.0.0
2. docker run --rm -it apachepulsar/pulsar-all:3.0.0 bash
3. (inside container shell) ./bin/pulsar version

### What did you expect to see?

If I test standard docker image (not full), it prints 3.0.0.

```sh
❯ docker run --rm -it apachepulsar/pulsar:3.0.0 bash
I have no name!@4665ecceea48:/pulsar$ ./bin/pulsar version
Current version of pulsar is: 3.0.0
Git Revision 7636e8989f4d3fc24fce69a356d54e1c550945ed
Git Branch branch-3.0
Built by Christophe Bornet <cbornet@hotmail.com> on cbornet-rmbp16 at 2023-04-12T07:18:48+0200
I have no name!@4665ecceea48:/pulsar$
```

### What did you see instead?

pulsar-all for version 3.0.0 prints 2.11.0 instead of 3.0.0

```sh
❯ docker run --rm -it apachepulsar/pulsar-all:3.0.0 bash
I have no name!@09dfcac03531:/pulsar$ ./bin/pulsar version
Current version of pulsar is: 2.11.0
I have no name!@09dfcac03531:/pulsar$
```

### Anything else?

docker repository: https://hub.docker.com/r/apachepulsar/pulsar-all
tag: 3.0.0
digest (amd64): 19bf90d5404d
digest (arm64): 6f6f4e0563ce

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
Thanks for reporting @zzzz465 . I'll close this one since there's already #20420 about the same issue. I'll rename the title of that one to provide more clarity.
