### ISSUE TITLE
Add "pip" label automatically to a PR when adding file to PIP directory

### ISSUE THREAD

**Issue by asafm** [apache/pulsar#20712]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

When someone creates a new PR for a new PIP, they need to select a number.
Today they search for previous PIPs PRs based on text like "[pip]" but people forget to register that text in their title thus leading to numbering conflicts.

### Solution

There will be a GitHub workflow, which will detect if a PR contains a *new* file matching the pattern "pip*.md" and add the label "pip" to the PR.

Once we add "pip" label to previous PIP PRs, we can modify the search for previous PIPs listed [here](https://github.com/apache/pulsar/blob/master/pip/README.md) to be based on "pip" label, and type: PR.

### Alternatives

Using titles as described in motivation

### Anything else?

No

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by dave2wave** [comment]
You would probably want to enhance - https://github.com/apache/pulsar-test-infra/tree/master/docbot

**Comment by tisonkun** [comment]
@dave2wave I submit a patch - https://github.com/apache/pulsar/pull/20760

docbot is tightly coupled with PR description. It can be refactored to handle all traffic about PR labels later, but I'd prefer to use a mature action for achieving this request now.

**Comment by asafm** [comment]
Brilliant!
@tisonkun Would you be able to backfill the label for the ~8 PIPs PRs the already exists?
Once that's done, I'll submit a PR to modify the place to search for existing PRs (https://github.com/apache/pulsar/blob/master/pip/README.md) so it will be a search by PIP label.
