### ISSUE TITLE
Add support for Key_Shared subscription type in Pulsar Python function 

### ISSUE THREAD

**Issue by yabinmeng** [apache/pulsar#20724]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

When I try to configure a Pulsar Python function with `retainKeyOrdering` configuration, it returns an error message of "Retain Key Orderering not yet supported in python".

Checking the following code ([link](https://github.com/apache/pulsar/blob/ac33311b7dfccdc88d560bbfd33c5cd968881717/pulsar-functions/instance/src/main/python/python_instance.py#L1[…]149](https://github.com/apache/pulsar/blob/ac33311b7dfccdc88d560bbfd33c5cd968881717/pulsar-functions/instance/src/main/python/python_instance.py#L142C8-L149))), it looks like `Key_Shared` subscription type is not supported in Pulsar Python function yet. 

Allowing the user to config subscription types (including `Key_Shared`) for a Pulsar Python function would be beneficial.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yabinmeng** [comment]
Fix is in [PR 20756](https://github.com/apache/pulsar/pull/20756)

**Comment by tisonkun** [comment]
Closed as https://github.com/apache/pulsar/pull/20756 merged.
