### ISSUE TITLE
[Doc] Optimize SEO Strategy | Improve Search Visibility of Pulsar Documentation

### ISSUE THREAD

**Issue by zuobiao-zhou** [apache/pulsar#20732]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

In recent years, the Apache Pulsar community has experienced rapid development, with fast version iterations and rich documentation content, bringing many pleasant experiences to users. Nowadays, an increasing number of users are searching for Pulsar content online, and **the search visibility of official documentation has become increasingly important (higher organic search rankings can enhance the project's visibility and competitiveness)**. Therefore, I would like to enhance the search visibility of Pulsar documentation by optimizing the `SEO` (Search Engine Optimization) strategy.

### What is your suggestion?

Considering that Pulsar users primarily visit the [/docs](https://pulsar.apache.org/docs) page, our first priority will be optimizing documents in version [3.0.x](https://pulsar.apache.org/docs/3.0.x/), which can be partially reused in version [2.11.x](https://pulsar.apache.org/docs/2.11.x/) and [2.10.x](https://pulsar.apache.org/docs/2.10.x/). 

Here are some basic steps:

1. **Check the Structure of Document**: ensure correct usage of H1, H2s, H3s.

2. **Add Metadata**: add `title` and `description` metadata to the documentation.
    In Markdown, we can add `Front Matter` in the beginning of the doc:
    ```yaml
    title: title of the article (under 60 characters)
    description: brief description of the article (under 158 characters)
    ```
    Metadata is shown in SERP (Search Engine Results Pages) to **attract users and encourage them to click through**. A few more **dos** and **don’ts** for writing meta titles and descriptions:
    - Create unique pairs for each page. Don’t duplicate. 
    - Don’t use alphanumeric characters as these may not be displayed properly.
    - Add relevant keywords — one in the title and one in meta description — but don’t overdo. 
    - Provide a title and description relevant to the page content.

3. **Add Alt Labels**: enhance the comprehensibility of images by providing alt labels that describe their content.
    We can add `alt label` for images in Markdown file:
    ```
   ![alt label](image_url)
    ```

I think we can divide the tasks according to chapters:

- [ ] About
- [ ] Get Started
- [ ] Concepts and Architecture
- [ ] Pulsar Schema
- [ ] Pulsar Functions
- [ ] Pulsar IO
- [ ] Pulsar SQL
- [ ] Tiered Storage
- [ ] Transactions
- [ ] Deployment
- [ ] Administration
- [ ] Observability
- [ ] Security
- [ ] Performance
- [ ] Client Libraries
- [ ] Admin API
- [ ] Adaptors
- [ ] Tutorials
- [ ] Development
- [ ] Reference

### Any reference?

https://developers.google.com/search/docs
https://webflow.com/blog/webflow-seo-tips

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zuobiao-zhou** [comment]
cc @Anonymitaet

**Comment by Anonymitaet** [comment]
Hi @zuobiao-zhou 

As stated in [project info | Optimizing the findability of Pulsar documentation with SEO strategies](https://summer-ospp.ac.cn/org/prodetail/23e980570?lang=en&list=pro), can you prioritize the 1st and 2nd tasks as below (especially for the 2nd, it needs more time to implement and take effects than other tasks)? 

1. Provide recommendations and make changes accordingly: perform an audit (criteria + verifications) of the Pulsar documentation and provide recommendations (issues + priorities) for improvement that supports the Pulsar user journey. 

2. Earn featured snippets to set Pulsar documentation “position zero” on Google search results.

References: 
- [Tagging metadata for Pulsar docs for SEO](https://www.notion.so/streamnativeio/Tagging-metadata-for-Pulsar-docs-for-SEO-37a63908960b4bac890c07abc6a45d9d#e26cb2c7a9464e1c805f1a044d1ca863)
- [Tasks | Optimizing Pulsar SEO](https://docs.google.com/document/d/1xGvp7msOYGjh-YDI1JtJ_ORWACEPWnBlhMMkZbylefQ/edit#heading=h.188884qgj6cz)
