### ISSUE TITLE
[doc][feat] use replicationClusters instead of setReplicationClusters

### ISSUE THREAD

**Issue by dgnestsn** [apache/pulsar#20742]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/2.11.x/administration-geo/#selective-replication

setReplicationClusters is not available. I believe the correct command is replicationClusters.

### What is your suggestion?

Update doc to use correct command.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by shy-share** [comment]
@dgnestsn  yes,you are right
