### ISSUE TITLE
[Bug] flink consume multi-partition topic error

### ISSUE THREAD

**Issue by littlecatjianjiao** [apache/pulsar#20754]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

pulsar-server 2.11
flink-connector-pulsar-1.16.0(pulsar-client version: pulsar-client-2.10.1)

### Minimal reproduce step

1.Create a multi-partition topic in pulsar
2.start a flink consumer task,set the parallelism of the task is less than the number of topic partitions, and then check the consumption of the data task detail.

### What did you expect to see?

each subtask can keep the consume rate and consume topic data normally

### What did you see instead?

only the first subtask can obtain topic data 
other subtask failed to consume data

### Anything else?

By opening the debug log, it is found that the above two consumers (normal consumption and abnormal consumption) have different responses when sending http requests through netty, which is mainly reflected in the returned location field

nomal consume thread:
![image](https://github.com/apache/pulsar/assets/52155737/82ab622a-103e-4d45-bfd6-135d823e0928)

error consume thread:
![image](https://github.com/apache/pulsar/assets/52155737/92a8ea7b-e1f3-40a1-a5e2-702d3093ee5a)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by dave2wave** [comment]
@cbornet Please confirm, but I think that this is a limitation in the flink job and it will only consume from pulsar in a single thread because input topic processing is in the job thread and not the task threads.

**Comment by littlecatjianjiao** [comment]
> @cbornet Please confirm, but I think that this is a limitation in the flink job and it will only consume from pulsar in a single thread because input topic processing is in the job thread and not the task threads.
Thank you for your reply. We have resolved this issue by upgrading the Flink version. It appears to be an issue with the pulsarsource provided by Flink, and I will close this issue.
