### ISSUE TITLE
[Bug] Unable to restart the broker properly.

### ISSUE THREAD

**Issue by xyhmnb** [apache/pulsar#20785]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

the cluster has three brokers. version:2.10.3

### Minimal reproduce step

we use the command: pulsar-brokers list use, found had two brokers. but the offline broker`s 6650 and 8080 port was alived.
then, we want to restart this broker, use the command: pulsar-daemon restart broker.
the console show:
"Shutdown is in progress... Please wait...
Shutdown is in progress... Please wait...
Thread dumps are taken for analysis at /usr/local/apache-pulsar-2.10.3/logs/broker.out
WARNNING :  broker is not stopped completely."
now,we found the 8080 port was closed,but the 6650 port was still alived.
we used the command:./pulsar-daemon restart broker --force ,to recover the broker.

### What did you expect to see?

i want to know why the broker cannot restart properly.
what should we do next time. no use --force

### What did you see instead?

[broker.txt](https://github.com/apache/pulsar/files/12023255/broker.txt)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
When closing the broker, many resources need to be closed. In some earlier versions, there may be a deadlock situation here, causing the shutdown to fail. So, when you encounter this situation, just use --force to hit it.

**Comment by xyhmnb** [comment]
> When closing the broker, many resources need to be closed. In some earlier versions, there may be a deadlock situation here, causing the shutdown to fail. So, when you encounter this situation, just use --force to hit it.

emmmok,by the way, the pulsar 2.10.3 is earlier versions?

**Comment by codelipenghui** [comment]
Close the issue since it's inactive.
