### ISSUE TITLE
[Doc] some missing indexs in concepts-overview

### ISSUE THREAD

**Issue by zuobiao-zhou** [apache/pulsar#20784]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

 In https://pulsar.apache.org/docs/3.0.x/concepts-overview/ , The **Contents** section does not include the ‘**Message throttling**’, ‘**Proxy support with SNI routing**’ and ‘**Multiple advertised listeners**’ from the sidebar. Also, the sidebar does not include an index for '**Tiered Storage**' in the contents.

<img width="960" alt="c4c38f376a747f978df9dc1ad841087" src="https://github.com/apache/pulsar/assets/61108539/8e8de081-4f21-496b-aa67-99a963635998">

### What is your suggestion?

fix.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zuobiao-zhou** [comment]
Only the maintained versions need to be fixed, or other legacy versions need to be fixed as well?
cc @Anonymitaet

**Comment by shy-share** [comment]
[Links1](https://pulsar.apache.org/docs/3.0.x/tiered-storage-overview/) and [links2 ](https://pulsar.apache.org/docs/3.0.x/concepts-tiered-storage/)seems that two links can be merged

**Comment by Anonymitaet** [comment]
@zuobiao-zhou 

1. Tiered storage has its independent section, we can update https://pulsar.apache.org/docs/3.0.x/concepts-tiered-storage/ to https://pulsar.apache.org/docs/3.0.x/tiered-storage-overview/
<img width="1366" alt="image" src="https://github.com/apache/pulsar/assets/50226895/c4f8927b-2aec-4f40-8078-fdaeb4eef359">

2. It's a small fix. Please update all occurrences.
> Only the maintained versions need to be fixed, or other legacy versions need to be fixed as well?

**Comment by zuobiao-zhou** [comment]
Hi @Anonymitaet Thanks for your suggestion.
It seems that https://pulsar.apache.org/docs/3.0.x/tiered-storage-overview/ includes the content of https://pulsar.apache.org/docs/3.0.x/concepts-tiered-storage/ and is more comprehensive overall
maybe just need to fix the links here?
<img width="960" alt="图片1" src="https://github.com/apache/pulsar/assets/61108539/c7330a55-dcd1-47f1-b279-64d501bc110a">
