### ISSUE TITLE
[Bug] When bookie-rack is not configured, pulsar-admin bookies get-bookie-rack -b <correct-bookie-address> is throwing 'Bookie address not found' error

### ISSUE THREAD

**Issue by armanjupriya-er** [apache/pulsar#20871]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Pulsar 2.10.3 on K8s container

### Minimal reproduce step

1. Ensure that bookie-rack policy is NOT configured
2. Lis the bookies using "pulsar-admin bookies list-bookies"
3. Get the bookie rack using the address displayed in step 2 (list-bookies command) [pulsar-admin bookies get-bookie-rack -b "proper-bookie-id.:3181"]   . The get-bookie-rack throws error "Bookie address not found: proper-bookie-id.:3181"   

### What did you expect to see?

If the bookie-rack is not set, proper error message should be displayed [ Example : null as bookie as rack]

### What did you see instead?

Bookie address not found: <Bookie Id>.:3181
Example: Bookie address not found: proper-bookie-id.:3181

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
Would you like to try to fix this?

**Comment by 1Jack2** [comment]
> Would you like to try to fix this?

I'd like to help. Here are my thoughts
 


change the following code
https://github.com/apache/pulsar/blob/69298da9f8bd009b72eb5533d31c8c7a696b2a63/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Bookies.java#L108-L121

like this
``` java
                    if (bi.isPresent()) {
                        asyncResponse.resume(bi.get());
                    } else {
                        Set<BookieId> bookieIds = getAllBookieIds();
                        if (bookieIds.contains(BookieId.parse(bookieAddress))) {
                            asyncResponse.resume((BookieInfo) null);
                        } else {
                            asyncResponse.resume(new RestException(Status.NOT_FOUND,
                                    "Bookie address not found: " + bookieAddress));
                        }
                    }

```

The `getAllBookieIds()` method can be implemented by referring to the following methods

https://github.com/apache/pulsar/blob/69298da9f8bd009b72eb5533d31c8c7a696b2a63/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Bookies.java#L78-L97

I think `delete-bookie-rack` api has the same issue

**Comment by Technoboy-** [comment]
> > Would you like to try to fix this?
> 
> I'd like to help. Here are my thoughts
> 
> change the following code
> 
> https://github.com/apache/pulsar/blob/69298da9f8bd009b72eb5533d31c8c7a696b2a63/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Bookies.java#L108-L121
> 
> like this
> 
> ```java
>                     if (bi.isPresent()) {
>                         asyncResponse.resume(bi.get());
>                     } else {
>                         Set<BookieId> bookieIds = getAllBookieIds();
>                         if (bookieIds.contains(BookieId.parse(bookieAddress))) {
>                             asyncResponse.resume((BookieInfo) null);
>                         } else {
>                             asyncResponse.resume(new RestException(Status.NOT_FOUND,
>                                     "Bookie address not found: " + bookieAddress));
>                         }
>                     }
> ```
> 
> The `getAllBookieIds()` method can be implemented by referring to the following methods
> 
> https://github.com/apache/pulsar/blob/69298da9f8bd009b72eb5533d31c8c7a696b2a63/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Bookies.java#L78-L97
> 
> I think `delete-bookie-rack` api has the same issue
> 
> @Technoboy-

Ah, how about simplifying and changing the promote message more clear ?

**Comment by 1Jack2** [comment]
> > > Would you like to try to fix this?
> > 
> > 
> > I'd like to help. Here are my thoughts
> > change the following code
> > https://github.com/apache/pulsar/blob/69298da9f8bd009b72eb5533d31c8c7a696b2a63/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Bookies.java#L108-L121
> > 
> > like this
> > ```java
> >                     if (bi.isPresent()) {
> >                         asyncResponse.resume(bi.get());
> >                     } else {
> >                         Set<BookieId> bookieIds = getAllBookieIds();
> >                         if (bookieIds.contains(BookieId.parse(bookieAddress))) {
> >                             asyncResponse.resume((BookieInfo) null);
> >                         } else {
> >                             asyncResponse.resume(new RestException(Status.NOT_FOUND,
> >                                     "Bookie address not found: " + bookieAddress));
> >                         }
> >                     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The `getAllBookieIds()` method can be implemented by referring to the following methods
> > https://github.com/apache/pulsar/blob/69298da9f8bd009b72eb5533d31c8c7a696b2a63/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Bookies.java#L78-L97
> > 
> > I think `delete-bookie-rack` api has the same issue
> > @Technoboy-
> 
> Ah, how about simplifying and changing the promote message more clear ?

could you explain more clearly?

**Comment by Technoboy-** [comment]
> > > > Would you like to try to fix this?
> > > 
> > > 
> > > I'd like to help. Here are my thoughts
> > > change the following code
> > > https://github.com/apache/pulsar/blob/69298da9f8bd009b72eb5533d31c8c7a696b2a63/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Bookies.java#L108-L121
> > > 
> > > like this
> > > ```java
> > >                     if (bi.isPresent()) {
> > >                         asyncResponse.resume(bi.get());
> > >                     } else {
> > >                         Set<BookieId> bookieIds = getAllBookieIds();
> > >                         if (bookieIds.contains(BookieId.parse(bookieAddress))) {
> > >                             asyncResponse.resume((BookieInfo) null);
> > >                         } else {
> > >                             asyncResponse.resume(new RestException(Status.NOT_FOUND,
> > >                                     "Bookie address not found: " + bookieAddress));
> > >                         }
> > >                     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The `getAllBookieIds()` method can be implemented by referring to the following methods
> > > https://github.com/apache/pulsar/blob/69298da9f8bd009b72eb5533d31c8c7a696b2a63/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Bookies.java#L78-L97
> > > 
> > > I think `delete-bookie-rack` api has the same issue
> > > @Technoboy-
> > 
> > 
> > Ah, how about simplifying and changing the promote message more clear ?
> 
> could you explain more clearly?

Like fixing the promote message "Bookie rack mapping info not found"

**Comment by 1Jack2** [comment]
I've changed it according to your instructions. Could you please review #20949 ? @Technoboy-

**Comment by sindhushreem** [comment]
@Technoboy-  can this be cherrypicked to 2.10 branch
