### ISSUE TITLE
Add getProperties/getPropertiesAsync methods to non-persistent topics

### ISSUE THREAD

**Issue by alexesom** [apache/pulsar#20889]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Currently there is possibility of adding properties while creating an non-partitioned topic.
https://github.com/apache/pulsar/blob/a0372f4b91b4bd6600093cdb52e2db5d6ab8497e/pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java#L552

But unfortunately there is no possibility to read this those properties by the pulsar-admin client as there is no implementation of such mehtod.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lifepuzzlefun** [comment]
please check this pr. https://github.com/apache/pulsar/pull/15944 maybe you need update your admin client and should check the broker version.

**Comment by tisonkun** [comment]
Closed as resolved.

Please check and provide your version if it still doesn't work.
