### ISSUE TITLE
Unify the output format of MessageId and RawMessageId

### ISSUE THREAD

**Issue by crossoverJie** [apache/pulsar#20892]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

When I query data using Pulsar-SQL, the obtained messageId format is as follows:
```
(111,0,0)
```

This output format is inconsistent with the `pulsar-client` implementation.
```
111:0:0
```

### Solution

https://github.com/apache/pulsar/blob/a0372f4b91b4bd6600093cdb52e2db5d6ab8497e/pulsar-common/src/main/java/org/apache/pulsar/common/api/raw/RawMessageIdImpl.java#L31-L41

Modify this `toString()` method.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
@merlimat @eolivelli @BewareMyPower will this change be considered part of public API breaking changes?

**Comment by crossoverJie** [comment]
I checked the code and it looks like only the `pulsar-sql` module uses this `toString()` method.

**Comment by tisonkun** [comment]
No. This is a public stable interface so users outside of modules of this project can use it. The question is whether we should keep compatibility on this representation.

For example, if you were a user of Pulsar, you build a shell script to match `(ledger_id, entry_id, batch_index)`, now we change the pattern to `ledger_id:entry_id:batch_index`, your script (can serve to significant online operation) will break.

**Comment by Shoothzj** [comment]
I think it's not a public API changes. But it's also significant to users. It will change the Ops components behavior like alert, metrics dependens on log.

**Comment by tisonkun** [comment]
@Shoothzj you're right. The issued class is `RawMessageIdImpl`, not `MessageId` or its implementations.

**Comment by BewareMyPower** [comment]
I agree with @Shoothzj. Though it's not a public API change, it could also affect many existing use cases. And I cannot see any benefit by unifying the output format.

**Comment by tisonkun** [comment]
Then I'd suggest we close this one as won't do.
