### ISSUE TITLE
[improve][CodeStyle] Strange code style

### ISSUE THREAD

**Issue by Denovo1998** [apache/pulsar#20967]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

**When I was reading the source code, I found some problems in the code format. Most of this is code from a long time ago, maybe we should add some CheckStyle rules?**

**1.missing spaces**
https://github.com/apache/pulsar/blob/2ab184e49a036a1dd10dc537bef4ab034a5ad5e0/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractReplicator.java#L178-L189
https://github.com/apache/pulsar/blob/2ab184e49a036a1dd10dc537bef4ab034a5ad5e0/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java#L529-L545

**2.Indent of wrong length**
https://github.com/apache/pulsar/blob/2ab184e49a036a1dd10dc537bef4ab034a5ad5e0/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java#L87-L92
https://github.com/apache/pulsar/blob/2ab184e49a036a1dd10dc537bef4ab034a5ad5e0/pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/AbstractCmdConsume.java#L136-L148
https://github.com/apache/pulsar/blob/2ab184e49a036a1dd10dc537bef4ab034a5ad5e0/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java#L738-L757

**I counted a lot of code with these problems:**
<img width="600" alt="Snipaste_2023-08-09_22-38-09" src="https://github.com/apache/pulsar/assets/54846009/b599040a-57c1-4240-a5be-11603fcea495">

### Solution

1.change `WhitespaceAround`
```xml
<module name="WhitespaceAround">
      <!-- Checks that various tokens are surrounded by whitespace.
           This includes most binary operators and keywords followed
           by regular or curly braces.
      -->
      <property name="ignoreEnhancedForColon" value="false" />
      <property name="tokens" value="ASSIGN, BAND, BAND_ASSIGN, BOR,
  BOR_ASSIGN, BSR, BSR_ASSIGN, BXOR, BXOR_ASSIGN, COLON, DIV, DIV_ASSIGN, DO_WHILE,
  EQUAL, GE, GT, LAND, LAMBDA, LE, LITERAL_ASSERT,  LITERAL_CATCH, LITERAL_DO, LITERAL_ELSE,
  LITERAL_FINALLY, LITERAL_FOR, LITERAL_IF, LITERAL_RETURN, LITERAL_SWITCH,
  LITERAL_SYNCHRONIZED, LITERAL_TRY, LITERAL_WHILE, LOR, LT, MINUS,
  MINUS_ASSIGN, MOD, MOD_ASSIGN, NOT_EQUAL, PLUS, PLUS_ASSIGN, QUESTION,
  SL, SLIST, SL_ASSIGN, SR, SR_ASSIGN, STAR, STAR_ASSIGN, TYPE_EXTENSION_AND"/>
      <property name="severity" value="error"/>
  </module>
```
2.add this rule
```xml
<module name="Indentation">
    <property name="throwsIndent" value="8" />
    <property name="lineWrappingIndentation" value="8" />
</module>
```

### Anything else?

Other discussions on code styles:
https://lists.apache.org/thread/qoqg33wpl5099c3dwcb1ry0gn4mr7z4q

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Denovo1998** [comment]
@tisonkun  @codelipenghui PTAL!

**Comment by tisonkun** [comment]
Instead of screenshot, can you share the link to the certain file?

**Comment by Denovo1998** [comment]
> Instead of screenshot, can you share the link to the certain file?

Screenshot of code has been replaced.

**Comment by tisonkun** [comment]
I'm continuting the spotless proposal and fix this issue on the fly. Let's see if we can apply that proposal to all maintained versions.

**Comment by tisonkun** [comment]
FYI - https://github.com/apache/pulsar/pull/20974

**Comment by tisonkun** [comment]
No consensus for using spotless. I may investigate why checkstyle doesn't work here later.

**Comment by tisonkun** [comment]
There is more than 1000+ style violation. I think we just hard to apply these new rules.

Maybe you can start a discussion on mailing list, but I don't think we're on a consensus to apply it as my suggestion to use Spotless was rejected by too much changes.

**Comment by tisonkun** [comment]
<img width="1726" alt="image" src="https://github.com/apache/pulsar/assets/18818196/775fae98-914a-433b-8850-068d0366aebb">

Here is part of the spotted violations. The sum is over 1000+.
