### ISSUE TITLE
[Bug] Installing packages fails

### ISSUE THREAD

**Issue by stefaniecg** [apache/pulsar#20996]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

1.101.0-beta arm64

### Minimal reproduce step

try to install any package, see figures attached, it fails

`Request for package information failed: getaddrinfo ENOTFOUND pulsar-edit.com`

```
Installing “platformio-ide-terminal@2.10.1” failed.Hide output…
Request for package information failed: getaddrinfo ENOTFOUND pulsar-edit.com (ENOTFOUND)
```

### What did you expect to see?

package being installed

### What did you see instead?

error, and no package installation

### Anything else?

no

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
I wonder if you're encountering issue for other "pulsar" project? Your description doesn't seems related to _Apache Pulsar_ which is a message queue and streaming platform.

**Comment by stefaniecg** [comment]
I get it now @tisonkun , so sorry for opening it in the wrong repository.
but at least i discovered apache pulsar :) 
Thanx for the help
