### ISSUE TITLE
[WARN] Can not find org.apache.pulsar.shade.io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath,fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'

### ISSUE THREAD

**Issue by yulin20010422** [apache/pulsar#20994]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

MacOS 13.4 Apple M1
Apache/Pulsar 2.10.0

### Minimal reproduce step

1.Start the springboot project without any VM options,popup exception:`java.lang.IllegalAccessException: class org.apache.pulsar.common.util.netty.DnsResolverUtil cannot access class sun.net.InetAddressCachePolicy (in module java.base) because module java.base does not export sun.net to unnamed module @484970b0
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392) ~[na:na]
`
2.After reading the fix of the issue#15964 [https://github.com/apache/pulsar/pull/15964](url).Configured VMoptions,`--add-opens java.base/sun.net=ALL-UNNAMED`,The exception is gone, replaced by a warning`WARN 3062 --- [           main] .i.n.r.d.DnsServerAddressStreamProviders : Can not find org.apache.pulsar.shade.io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'`.
3.After I add this dependency `io.netty:netty-resolver-dns-native-macos`, the warning will still be reported
4.I tested on win11, there is no such warning.

### What did you expect to see?

1.I hope to be able to remove this warning, because I don't know whether the warning will affect the program.

### What did you see instead?

A warning on macOS.

### Anything else?

If this warning has any effect, I'd like to know what the effect is.
_This is the first time I raise an issue, if there are low-level questions, I hope I can get your understanding._

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Should be answered by https://github.com/apache/pulsar/discussions/17067
