### ISSUE TITLE
[Bug] PulsarService.getLookupServiceAddress returns wrong port if TLS is enabled

### ISSUE THREAD

**Issue by alpreu** [apache/pulsar#21012]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Pulsar 3.1.0 but also broken on master

### Minimal reproduce step

1. Start pulsar standalone with TLS configured using e.g. port 8081 for TLS
2. Run pulsarAdmin.brokers().getActiveBrokers()

### What did you expect to see?

The return value should be `localhost:8081` (using TLS port)

### What did you see instead?

The return value is `localhost:8080` (not using TLS port)

### Anything else?

The value is ultimately retrieved from `PulsarService.getLookupServiceAddress`.
I believe the code below should be the other way around, first checking if a TLS address is available and if not fall back to the non tls one:

https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java#L1740-L1743

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by codelipenghui** [comment]
@alpreu Do you know which PR introduced the break change? I also asked @coderzc and @Technoboy- to take a deep look.

**Comment by alpreu** [comment]
> @alpreu Do you know which PR introduced the break change? I also asked @coderzc and @Technoboy- to take a deep look.

I saw that this part was added in eab2bb5f

**Comment by lhotari** [comment]
> The return value should be `localhost:8081` (using TLS port)

@alpreu Why do you say that it should be the TLS port? 
This value is actually a broker identifier and shouldn't be used for any connections. The PR #21894 makes this explicit.

**Comment by lhotari** [comment]
> > @alpreu Do you know which PR introduced the break change? I also asked @coderzc and @Technoboy- to take a deep look.
> 
> I saw that this part was added in [eab2bb5](https://github.com/apache/pulsar/commit/eab2bb5fe089217d39a71965526729a3d93b74b6)

@alpreu Did that commit introduce a breaking change?
