### ISSUE TITLE
[Bug] The producer pulsar-cluster-1-8-67 can not send message to the topic namespace/tenant/topic-partition-0 within given timeout

### ISSUE THREAD

**Issue by MengXiangDing** [apache/pulsar#21050]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

pulsar server version: 2.9.3, 2.10.3
pulsar client version: 2.11.0

### Minimal reproduce step

We use the internal CDC tool to push the incremental data of mysql binlog to pulsar, and occasionally this error will be reported, and at present, it is necessary to restart the producer to recover.

So in our scenario, it's a sporadic problem.

### What did you expect to see?

I hope the community can give a solution, at least not by restarting the producer. Thanks.

### What did you see instead?

This is the exception information I found from the log.

<img width="1509" alt="image" src="https://github.com/apache/pulsar/assets/73006046/8a9d1472-d3e8-43a4-9a3d-0d5340052427">

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by mattisonchao** [comment]
@MengXiangDing 

Many cases can issue this problem. Could you please share the topic owner broker and the client's full logs?

**Comment by MengXiangDing** [comment]
Hi, @mattisonchao 
Thank you, at around 15 o'clock this afternoon, this problem also appeared. I found some server logs.
<img width="1328" alt="image" src="https://github.com/apache/pulsar/assets/73006046/d64807d1-129f-4c10-83d8-45a750728440">

**Comment by mattisonchao** [comment]
Could you please share the log file of broker&client?

**Comment by MengXiangDing** [comment]
Hi, @mattisonchao 
Thank you again, I changed the version of the pulsar client to 2.10.4, and there is no similar problem so far, and I will share the log when the problem occurs again.

**Comment by mattisonchao** [comment]
@MengXiangDing 
Great! 

I closed this issue. You can reopen it when you meet this issue again. :)
