### ISSUE TITLE
[refactor][cli][PIP-280] Tracker : Refactor byte, time parsing logic using new `pulsar-cli-utils` module

### ISSUE THREAD

**Issue by JooHyukKim** [apache/pulsar#21056]
PIP #20691 
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Since #20782, we have `pulsar-cli-utils` module to refactor  byte, time parsing logic away from `Cmd*` classes (e.g. `CmdTopics`). This issue will serve as a tracker for mutliple PR's that will do the actual refactoring work.

### Solution

Below is tracked PRs. Anyone is welcome to add a PR.

- #20764 
~~- Move some  size conversion to `ByteUnitUtil`, as per [comment](https://github.com/apache/pulsar/pull/20764#discussion_r1328457645)~~
- https://github.com/apache/pulsar/pull/21412

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by nodece** [comment]
PR has been merged.
