### ISSUE TITLE
[Bug][Broker] Message Sequence Problem with Topic Compaction and Async production.

### ISSUE THREAD

**Issue by thetumbled** [apache/pulsar#21055]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

all.

### Minimal reproduce step

1. When we use Producer to send asynchronously, we do not gurantee the message order, right? 
2. Using the compaction mechanism, we compact messages with the same key, and the last message takes effect. Therefore, we do care about the order of the messages. 
As a result, when we use the topic compaction mechanism, we need to send messages synchronously. But in the topic policy and transaction TB modules, all messages production is asynchronous, which may be a big problem as it has a wide range of influence.

I wonder that we should make the message production to compacted topic be synchronous.

### What did you expect to see?

.

### What did you see instead?

.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by thetumbled** [comment]
PTAL, thanks. @codelipenghui @poorbarcode @AnonHxy @lifepuzzlefun

**Comment by mattisonchao** [comment]
Hi, @thetumbled 

>When we use Producer to send asynchronously, we do not gurantee the message order, right?

It depends on how you define the **"message order"**.  Even if the method is async, it will put the request in a queue. which means it will ensure the publishing request order, but some requests may get the exception and jump out of the order.

>Using the compaction mechanism, we compact messages with the same key, and the last message takes effect. Therefore, we do care about the order of the messages.
As a result, when we use the topic compaction mechanism, we need to send messages synchronously. But in the topic policy and transaction TB modules, all messages production is asynchronous, which may be a big problem as it has a wide range of influence.

Well, would you mind giving an example or test to demonstrate this idea? it will help a lot for issue trouble.

**Comment by mattisonchao** [comment]
mark it as the question before we confirm it's a bug.

**Comment by mattisonchao** [comment]
Hi @thetumbled 

If the first message timeout, all of the rest messages will get an exception as well.
