### ISSUE TITLE
[Bug] Building a custom docker image is stuck

### ISSUE THREAD

**Issue by g0715158** [apache/pulsar#21100]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

3.1.0

### Minimal reproduce step

mvn clean install -DskipTests
mvn package -Pdocker,-main -am -pl docker/pulsar-all -DskipTests

### What did you expect to see?

The custom image is successfully created after the command is executed

### What did you see instead?

When I was making a custom image of version 3.1.0, when I was downloading remote resources through http, the user would get stuck every few minutes. I had to stop making the image and rename it again. In this way, I executed many commands repeatedly
![image](https://github.com/apache/pulsar/assets/16098391/eb9027ff-fda0-4d81-a254-438e2bf7a0fa)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by mattisonchao** [comment]
Hi, @g0715158 

You can try to use different mirrors of ubuntu to fix this problem.

**Comment by g0715158** [comment]
> mirrors of ubuntu

ARG UBUNTU_MIRROR=mirror://mirrors.ubuntu.com/mirrors.txt
ARG UBUNTU_SECURITY_MIRROR=http://security.ubuntu.com/ubuntu/

# Install some utilities
RUN sed -i -e "s|http://archive\.ubuntu\.com/ubuntu/|${UBUNTU_MIRROR:-mirror://mirrors.ubuntu.com/mirrors.txt}|g" \
     -e "s|http://security\.ubuntu\.com/ubuntu/|${UBUNTU_SECURITY_MIRROR:-http://security.ubuntu.com/ubuntu/}|g" /etc/apt/sources.list \
     && echo 'Acquire::http::Timeout "30";\nAcquire::ftp::Timeout "30";\nAcquire::Retries "3";' > /etc/apt/apt.conf.d/99timeout_and_retries \
     && apt-get update \
     && apt-get -y dist-upgrade \
     && apt-get -y install --no-install-recommends netcat dnsutils less procps iputils-ping \
                 python3 python3-kazoo python3-pip \
                 curl ca-certificates wget apt-transport-https


@mattisonchao This is the source code, should be replaced by what

**Comment by g0715158** [comment]
I changed the address of Ali cloud still has this problem, is it controlled by which timeout parameter?
![image](https://github.com/apache/pulsar/assets/16098391/cb1e78a8-1b87-4338-9563-97635275bbb9)

**Comment by compuguy** [comment]
This might have been resolved based on #21489 and #21520....

**Comment by compuguy** [comment]
Any updates on this, I think the previous merge requests mentioned in my last comment resolve this issue?

**Comment by lhotari** [comment]
> Any updates on this, I think the previous merge requests mentioned in my last comment resolve this issue?

@compuguy yes, this is fixed.
