### ISSUE TITLE
Pause countdown timer of delayed message or change it's delayed time.

### ISSUE THREAD

**Issue by jaggerwang** [apache/pulsar#21173]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

In our business scenario, the worker need to finish the job assigned to him or her within the specified time, such as 60 minutes, if the worker did not finish the job in this time, the job will be reassigned to another worker. But if the worker paused working, for example, go to lunch, the delayed time should be extended, such as 30 minutes.

### Solution

There are several ways to support this feature:

1. Pause and resume countdown timer of delayed message;
2. Change delayed time of the existing delayed message;
3. Cancel the existing delayed message and create a new one;

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by mattisonchao** [comment]
@jaggerwang 

How about getting the message and then checking if the client can handle it to decide on redelivery or processing?

**Comment by coderzc** [comment]
It seems that the consumer can filter out unnecessary messages after consumption. For a message, it should be immutable.

**Comment by jaggerwang** [comment]
The key point is that the delayed time need to be paused counting down when the worker paused his job and resume counting down when resumed his job. It indeed can be achived by skipp handling the delayed message and resending an new delayed message if the worker ever paused his job, but need the application to handle it.

**Comment by dao-jun** [comment]
It's not MQ's responsibility itself, close as not planned
