### ISSUE TITLE
topics.getPartitionedInternalStats should allow the returned data to not contain publishers or subscriptions information.

### ISSUE THREAD

**Issue by crossoverJie** [apache/pulsar#21200]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

I have a lot of producers in a topic called `admin.topics().getPartitionedStats`, like 3k producers.The response size of `getPartitionedStats` is enormous (400M+) and it responds slowly.

![image](https://github.com/apache/pulsar/assets/15684156/6a8bad02-52de-4b39-bad8-00af5b496b7a)

However, I do not require information about `publishers` and `subscriptions`.

### Solution

So I hope publishers and subscriptions can be optional, we can add new interface like below:

```java
    CompletableFuture<PartitionedTopicStats> getPartitionedStatsAsync(
            String topic, boolean perPartition, boolean getPreciseBacklog, boolean subscriptionBacklogSize,
            boolean getEarliestTimeInBacklog, boolean containPublishers, boolean containSubsriptions,);
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by mattisonchao** [comment]
@crossoverJie 
Could you please draft a PIP for it?  https://github.com/apache/pulsar/blob/master/pip/README.md

**Comment by crossoverJie** [comment]
@mattisonchao OK, I'll try it later.

**Comment by crossoverJie** [comment]
fix by https://github.com/apache/pulsar/pull/21228
