### ISSUE TITLE
[Bug] Docker image did not works

### ISSUE THREAD

**Issue by miton18** [apache/pulsar#21209]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Docker
Pulsar 2.11.2 

### Minimal reproduce step

❯ docker run -it --rm apachepulsar/pulsar:2.11.2 bash
I have no name!@1d44533f0b9e:/pulsar$ bin/pulsar standalone
[0.001s][warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:/pulsar/logs/pulsar_gc_%p.log instead.
Unrecognized VM option 'PrintGCDateStamps'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

### What did you expect to see?

Standalone version started

### What did you see instead?

Error: A fatal exception has occurred. Program will exit.

### Anything else?

how can we remove "PrintGCDateStamps" from the image

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by mattisonchao** [comment]
@miton18 
Could you run `java -version` in your docker container?

**Comment by miton18** [comment]
Sorry I have a too old version of docker
https://github.com/adoptium/containers/issues/215#issuecomment-1142046045
