### ISSUE TITLE
Allow configuring backoff strategy on clients

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#2122]
*Problem*

Currently the backoff strategy on pulsar clients are hardcoded with 100ms backoff. The backoff settings are too aggressive when you have a lot of topics, it would be good to make these settings configurable.

**Comment by ConcurrencyPractitioner** [comment]
@sijie I could take on this isse. :)

**Comment by sijie** [comment]
@ConcurrencyPractitioner ok.

Assigned to @ConcurrencyPractitioner

**Comment by ConcurrencyPractitioner** [comment]
Hi, Just a meta-comment.
The backoff strategy in Pulsar is implemented by a class literally named ```Backoff```. I noticed that this particular class is used in both pulsar-broker and pulsar-client. So I'm curious:  should we only make the backoff in pulsar-client configurable or should the backoff strategy in pulsar-broker also be configurable? Thought it might be related.
