### ISSUE TITLE
Consumer not being notified of new topics - Java and Cli [Bug] 

### ISSUE THREAD

**Issue by thomas-turner** [apache/pulsar#21236]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

OS: Ventura 13.5.2 on M1 Chip
Pulsar: 3.1.0

### Minimal reproduce step

- Create a `docker-compose.yml` and copy in the following:
    - ```yaml
      version: '3.8'

      services:
        pulsar:
          container_name: pulsar
          image: apachepulsar/pulsar:3.1.0
          ports:
            - "6650:6650"
            - "8080:8080"
            - "4181:4181"
          environment:
            - clusterName=local
            - authenticationEnabled=false
            - superUserRoles=admin
            - AWS_ACCESS_KEY_ID=accesskey
            - AWS_SECRET_ACCESS_KEY=secretkey
            - allowAutoTopicCreationType=partitioned
            - defaultNumPartitions=2
            - PULSAR_STANDALONE_USE_ZOOKEEPER=1
            - PULSAR_PREFIX_subscriptionPatternMaxLength=75
          command: >
            /bin/bash -c
            "bin/apply-config-from-env.py conf/standalone.conf
            && exec bin/pulsar standalone"
       ```
- Run `docker compose up --build` in the same folder
- Run `docker exec -it <container id> bash`
- Run `cd bin`
- Run `./pulsar-client consume -s example-sub "public/default/.*" --regex`
- In a new terminal repeat the `docker exec` and `cd bin` steps
- Run `./pulsar-admin topics create-partitioned-topic persistent://public/default/example-topic --partitions 2`
- Run `./pulsar-admin topics subscriptions persistent://public/default/example-topic`

### What did you expect to see?

I expect to see `example-sub` listed on the subscriptions for `example-topic` showing that the consumer has been notified of the new topic.

### What did you see instead?

I see no subscriptions on the topic even after waiting a sufficient amount of time.

### Anything else?

Restarting the consumer results in the topic being discovered.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by thomas-turner** [comment]
> i tried on 3.0.1(latest) and it works fine.

@muni-chada 3.0.1 isn't the latest

**Comment by marksilcox** [comment]
It appears the topic pattern needs to be a full topic url - e.g. this works:
```shell
./pulsar-client consume -s example-sub --regex "persistent://public/default/.*"
```

**Comment by thomas-turner** [comment]
Thanks, @marksilcox . Would be interested if someone can point out where that changed as we never used to have to provide that (same with the `-partition-\d` on the end of the pattern.
