### ISSUE TITLE
[doc] [fix] Links to Broker Load Balancing Use Cases broken

### ISSUE THREAD

**Issue by ble** [apache/pulsar#21306]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

All links to the broker load balancing use cases page are broken: cf. [the second link under the "related topics" heading here](https://pulsar.apache.org/docs/next/concepts-broker-load-balancing-concepts/#related-topics) or [here](https://pulsar.apache.org/docs/3.1.x/concepts-broker-load-balancing-concepts/#related-topics)

### What is your suggestion?

Rename all instances of `concepts-broker-load-balancing-use-case.md` to end `use-cases.md` (just adding an 's') to fix all internal links.

### Any reference?

References given above in the issue.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
https://github.com/apache/pulsar-site/pull/713
