### ISSUE TITLE
[Bug] Can not cleanup heartbeat data if scaling down broker

### ISSUE THREAD

**Issue by TakaHiR07** [apache/pulsar#21324]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

pulsar version: 2.10

### Minimal reproduce step

scaling down broker, by close and remove broker

### What did you expect to see?

scaling down broker can cleanup all resource on broker

### What did you see instead?

heartbeat topic ledger of the scaling-down-broker still exist

### Anything else?

How can we cleanup resource when scaling down broker ? 

I search in code but can not find such method.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
It's a known issue. Unloaded topic could not be deleted

**Comment by TakaHiR07** [comment]
@Technoboy- Is this issue being fixed or has been fixed ?

I think heartbeat namespace and topic is somewhat special. Each broker has its own heartbeat resource. Maybe we can delete heartbeat resource when we close the broker.  What do you think about it ?

**Comment by Technoboy-** [comment]
> @Technoboy- Is this issue being fixed or has been fixed ?
> 
> I think heartbeat namespace and topic is somewhat special. Each broker has its own heartbeat resource. Maybe we can delete heartbeat resource when we close the broker. What do you think about it ?

yes, good idea

**Comment by TakaHiR07** [comment]
issue has fixed. close it
