### ISSUE TITLE
track adobe/s3mock update, since it is not using the latest version of github repo

### ISSUE THREAD

**Issue by zhaijack** [apache/pulsar#2133]
dockerhub adobe/s3mock: https://hub.docker.com/r/adobe/s3mock/
is not using the latest version of github repo: https://github.com/adobe/S3Mock,

And we meet some issue in PR #2065 , such as: https://github.com/adobe/S3Mock/issues/32
We need to track the docker image update to update the followed changes in file: https://github.com/apache/incubator-pulsar/blob/master/tests/integration-tests-topologies/src/main/resources/cube-definitions/single-cluster-2-bookie-1-broker-unstarted-with-s3.yaml

**Comment by sijie** [comment]
since we already have own s3mock image, I don't think we need that one from adobe. closing it for now, if there is a need we can discuss later : https://hub.docker.com/r/apachepulsar/s3mock/
