### ISSUE TITLE
[Bug] BacklogQuota not applied to the namespace

### ISSUE THREAD

**Issue by zzzz465** [apache/pulsar#21337]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

pulasr 3.0.0
pulsar-resources-operator: 0.3.3

### Minimal reproduce step

1. create a namespace
2. manage namespace by CRD

### What did you expect to see?

if the request is invalid it should reject

### What did you see instead?

accepts invalid(?) request and the namespace backlog quota config becomes unmodifiable

### Anything else?

related: https://github.com/streamnative/pulsar-resources-operator/issues/161

this is the requester's problem that not sending valid requests, but still, the pulsar broker should validate and reject before accepting backlog_quota_map

this is a valid request sent using pulsar admin CLI (3.0.0)
![image](https://github.com/apache/pulsar/assets/46273764/2a9d7f81-8f5b-4a43-9dc5-9b5c5803fa32)

this is an invalid request sent from operator (0.3.3)
![image](https://github.com/apache/pulsar/assets/46273764/58370b34-5e51-48fd-a8de-ef27c2e5bfd8)

both logs are caputred from pulsar broker

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
user has fixing this by upgrading pulsar-resources-operator version to 0.4.4
