### ISSUE TITLE
Pulsar site's social media preview image is missing :(

### ISSUE THREAD

**Issue by visortelle** [apache/pulsar#21478]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

There should be some eye-attracting fancy preview image:

<img width="589" alt="Screenshot 2023-10-30 at 11 25 38 PM" src="https://github.com/apache/pulsar/assets/9302460/67c51e41-fb47-4821-bcff-e44dc884a9fa">

### Solution

I'm ready to provide a solution someday in my free time.
If someone wants to fix it, your contribution is very welcome!

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by asafm** [comment]
You mean the logo right?

**Comment by tisonkun** [comment]
Ref - https://github.com/facebook/docusaurus/issues/2968

I suspect that we don't add the metadata in docusarus.config.js for social card. And another question is which picture we should use.

**Comment by tisonkun** [comment]
Ref - https://docusaurus.io/docs/seo

e.g., at least we can something like:

```html
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://tisonkun.org/media/yatennosyo.png">
```

or following https://ogp.me/.

**Comment by visortelle** [comment]
@asafm You mean the logo right?

It may be a logo, logo + project name, or maybe something more colorful. 
It's rather a question to a designer + someone who does SMM.

**Comment by tisonkun** [comment]
Let me give it a try - https://github.com/apache/pulsar-site/pull/723

**Comment by visortelle** [comment]
Another try: https://github.com/apache/pulsar-site/pull/725

<img width="639" alt="Screenshot 2023-11-06 at 2 18 32 PM" src="https://github.com/apache/pulsar/assets/9302460/68299d8b-880c-47c4-847a-7d1aba6bc7a4">

@tisonkun, @asafm, @jak78 what do you think?

**Comment by asafm** [comment]
@visortelle I like it
