### ISSUE TITLE
Offload: track jclouds release update for JCLOUDS-1166 

### ISSUE THREAD

**Issue by zhaijack** [apache/pulsar#2164]
currently we use shaded version of jclouds, because of [gson conflict]( https://issues.apache.org/jira/browse/JCLOUDS-1166), It is undergoing in Jclouds.

Once jclouds have it solved, we could use un-shaded version of jclouds..

In our code, jclouds shaded for gson conflict: https://issues.apache.org/jira/browse/JCLOUDS-1166

This issue could also be used for jclouds new release, because of [JCLOUDS-1389](https://issues.apache.org/jira/browse/JCLOUDS-1389), we will have to use 2.2.0-snapshot currently, and it is in same `pom.xml`. Once we have jclouds 2.1.1 or 2.2.0, we could remove the snapshot.

**Comment by jiazhai** [comment]
asked on twitter, jclouds will have a release 2.1.1 in next week.

**Comment by sijie** [comment]
#2410 already bumped the version to latest jclouds release `2.1.1`
