### ISSUE TITLE
[Bug] all broker FullGC and shutdown when a large number of producers concurrently update schema

### ISSUE THREAD

**Issue by keyboardbobo** [apache/pulsar#21672]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.9.2

### Minimal reproduce step

500 flink tasks start and send message

### What did you expect to see?

Send message normally

### What did you see instead?

too many log like this: 

> 2023-11-29 11:29:16.0673 [main-EventThread] INFO  org.apache.bookkeeper.client.MetadataUpdateLoop - UpdateLoop(ledgerId=82275,loopId=02ae6b89) conflict writing metadata to store, update local value and try again
> 2023-11-29 11:29:16.0674 [main-EventThread] INFO  org.apache.bookkeeper.client.MetadataUpdateLoop - UpdateLoop(ledgerId=82275,loopId=406b81db) conflict writing metadata to store, update local value and try again
> 2023-11-29 11:29:16.0674 [main-EventThread] INFO  org.apache.bookkeeper.client.MetadataUpdateLoop - UpdateLoop(ledgerId=82275,loopId=68cba549) conflict writing metadata to store, update local value and try again

### Anything else?

topN elements of dump file :

> java.util.concurrent.CompletableFuture
> org.apache.bookkeeper.client.LedgerOpenOp$$Lambda$966
> org.apache.bookkeeper.client.LedgerOpenOp
> org.apache.zookeeper.ClientCnxn$Packet
> org.apache.pulsar.broker.service.schema.BookkeeperSchemaStorage$$Lambda$959
> org.apache.bookkeeper.zookeeper.ZooKeeperClient$19$1

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by keyboardbobo** [comment]
@Technoboy- I found that this problem has been indirectly solved by this PR, although not the same problem : https://github.com/apache/pulsar/pull/17283 
Close the ledger '` ledgerHandle.closeAsync()` ' when the schema is written instead of when reading the schema metadata, thus avoiding concurrency.

```
    @NotNull
    private CompletableFuture<SchemaStorageFormat.PositionInfo> addNewSchemaEntryToStore(
        String schemaId,
        List<SchemaStorageFormat.IndexEntry> index,
        byte[] data
    ) {
        SchemaStorageFormat.SchemaEntry schemaEntry = newSchemaEntry(index, data);
        return createLedger(schemaId).thenCompose(ledgerHandle -> {
            final long ledgerId = ledgerHandle.getId();
            return addEntry(ledgerHandle, schemaEntry)
                    .thenApply(entryId -> {
                        ledgerHandle.closeAsync();
                        return Functions.newPositionInfo(ledgerId, entryId);
                    });
        });
    }

```

**Comment by Technoboy-** [comment]
> @Technoboy- I found that this problem has been indirectly solved by this PR, although not the same problem : #17283 Close the ledger '` ledgerHandle.closeAsync()` ' when the schema is written instead of when reading the schema metadata, thus avoiding concurrency.
> 
> ```
>     @NotNull
>     private CompletableFuture<SchemaStorageFormat.PositionInfo> addNewSchemaEntryToStore(
>         String schemaId,
>         List<SchemaStorageFormat.IndexEntry> index,
>         byte[] data
>     ) {
>         SchemaStorageFormat.SchemaEntry schemaEntry = newSchemaEntry(index, data);
>         return createLedger(schemaId).thenCompose(ledgerHandle -> {
>             final long ledgerId = ledgerHandle.getId();
>             return addEntry(ledgerHandle, schemaEntry)
>                     .thenApply(entryId -> {
>                         ledgerHandle.closeAsync();
>                         return Functions.newPositionInfo(ledgerId, entryId);
>                     });
>         });
>     }
> ```

Thanks
