### ISSUE TITLE
[Doc] pulsar v3.0.2 lacks release notes

### ISSUE THREAD

**Issue by StevenLuMT** [apache/pulsar#21685]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

@poorbarcode 
Pulsar v3.0.2 lacks release notes in https://github.com/apache/pulsar/releases 

### What is your suggestion?

@poorbarcode 
Please complete the v3.0.2's release  information in https://github.com/apache/pulsar/releases , thank you

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
Added
