### ISSUE TITLE
[Bug] You are able to add a blank string as a tenant admin

### ISSUE THREAD

**Issue by illegalnumbers** [apache/pulsar#21710]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

At least 3.0.1.6. It looks to be on master

### Minimal reproduce step

Create a tenant admin with a blank string

### What did you expect to see?

This fails to be accepted

### What did you see instead?

You now have a blank tenant admin

### Anything else?

See the `createTenant` method, it does not seem to call validation to the string input in the rest api.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
do you mean ?
```
admin.tenants().createTenant(" ", TenantInfo.builder().allowedClusters(Sets.newHashSet("test")).build());
```
