### ISSUE TITLE
how to use pulsar on windows.[Doc] 

### ISSUE THREAD

**Issue by hi335807829** [apache/pulsar#21750]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

can not find use guide for windows.After cmd file run,service did not work.And can not find useful shell command.

### What is your suggestion?

make doc file for windows,and show shell command guild.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by BewareMyPower** [comment]
The `bin/*.cmd` files are only for clients. Pulsar does not support running server on Windows yet, you have to use Docker to run Pulsar. https://pulsar.apache.org/docs/next/getting-started-docker/

**Comment by ubo-dev** [comment]
> The `bin/*.cmd` files are only for clients. Pulsar does not support running server on Windows yet, you have to use Docker to run Pulsar. https://pulsar.apache.org/docs/next/getting-started-docker/

There is no information about this case, I've added a note under getting started.

**Comment by visortelle** [comment]
The bare metal deployment documentation page states that Pulsar is available for Windows.

I suppose it's also a mistake and the Windows mention should be removed. It makes sense to add a sentence like 'You can run Pulsar on Windows in Docker'.

@ubo-dev are you interested in submitting one more PR?

https://pulsar.apache.org/docs/next/deploy-bare-metal/#requirements
<img width="851" alt="Screenshot 2024-03-02 at 11 40 56 PM" src="https://github.com/apache/pulsar/assets/9302460/5834576b-e1c6-44e6-8625-f7ec7235baa2">

**Comment by ubo-dev** [comment]
@visortelle  Of course, thank you for letting me know!

**Comment by visortelle** [comment]
I believe the issue has been resolved in:
- https://github.com/apache/pulsar-site/pull/756
- https://github.com/apache/pulsar-site/pull/812

Closing.
