### ISSUE TITLE
[Bug] After upgrading to 3.0, some metrics were lost in bk.

### ISSUE THREAD

**Issue by crossoverJie** [apache/pulsar#21766]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

3.0.2

### Minimal reproduce step

![image](https://github.com/apache/pulsar/assets/15684156/8a141d20-7d5c-4085-a1eb-eb42a070796f)
![image](https://github.com/apache/pulsar/assets/15684156/70e1143b-03d6-4e11-832b-fd889c69fdd0)

Details:
- bookkeeper_server_ADD_ENTRY_REQUEST
- bookkeeper_server_ADD_ENTRY_BLOCKED
- bookkeeper_server_READ_ENTRY_BLOCKED
- bookie_journal_JOURNAL_CB_QUEUE_SIZE
- bookie_read_cache_hits_count
- bookie_read_cache_misses_count
- bookie_DELETED_LEDGER_COUNT
- bookie_MAJOR_COMPACTION_COUNT

### What did you expect to see?

The metrics is normal.

### What did you see instead?

Miss some metrics.

### Anything else?

When I downgraded the `bookkeeper` version to 2.11.2, the version of bookkeepe used was `4.15.4`, and everything was normal.

However, when I used BookKeeper `4.16.3` locally with Pulsar 3.x, I could not reproduce the issue.

Whether using source code or Docker: `apache/bookkeeper:4.16.3`, I was unable to reproduce it.

This is my test code:

```java
    @SneakyThrows
    @Test
    public void testBk2() {
        String connectionString = "127.0.0.1:2181"; // For a single-node, local ZooKeeper cluster
        ClientConfiguration config = new ClientConfiguration();
        config.setZkServers(connectionString);
        config.setAddEntryTimeout(2000);
        BookKeeper bookKeeper = new BookKeeper(config);
        byte[] password = "some-password".getBytes();
        bookKeeper.asyncCreateLedger(1, 1,
                1, BookKeeper.DigestType.MAC, password, new AsyncCallback.CreateCallback() {
                    @SneakyThrows
                    @Override
                    public void createComplete(int rc, LedgerHandle lh, Object ctx) {
                        log.info("create complete: {}", rc);

                        for (int i = 0; i < 100000; i++) {
                            lh.asyncAddEntry("some-data".getBytes(), new AsyncCallback.AddCallback() {
                                @Override
                                public void addComplete(int rc, LedgerHandle lh, long entryId, Object ctx) {
                                    log.info("rc: {}, entryId: {}", rc, entryId);
                                }
                            }, null);

                            TimeUnit.SECONDS.sleep(1);
                        }

                    }
                }, null, null);

        TimeUnit.SECONDS.sleep(100);
    }
}
```

![image](https://github.com/apache/pulsar/assets/15684156/8158512e-cdcb-44c9-96fd-193e227ebbef)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by crossoverJie** [comment]
@zymap @hangc0276  Please take a look.

**Comment by hangc0276** [comment]
@crossoverJie Thanks for raising this issue. 
For `bookkeeper_server_ADD_ENTRY_REQUEST` and `bookkeeper_server_READ_ENTRY_REQUEST` metric, please check the 4.16.0 release note.
https://github.com/apache/bookkeeper/releases/tag/release-4.16.0

>bookkeeper_server_ADD_ENTRY_BLOCKED
bookkeeper_server_READ_ENTRY_BLOCKED
bookie_journal_JOURNAL_CB_QUEUE_SIZE
bookie_read_cache_hits_count
bookie_read_cache_misses_count
bookie_DELETED_LEDGER_COUNT
bookie_MAJOR_COMPACTION_COUNT

For the rest metrics, it is not expected. Could you double confirm if they are missed after upgraded the BookKeeper to 4.16.0+?

**Comment by crossoverJie** [comment]
@hangc0276 Thank you for your reply.

> When using V2 protocol, the bookkeeper_server_ADD_ENTRY_REQUEST and bookkeeper_server_READ_ENTRY_REQUEST stats do not work, and you can use bookkeeper_server_ADD_ENTRY and bookkeeper_server_READ_ENTRY instead. https://github.com/apache/bookkeeper/pull/3837

![image](https://github.com/apache/pulsar/assets/15684156/1b87b81d-f980-45ca-8b6c-2c7fac7ee0e0)

But `bookkeeper_server_READ_ENTRY_REQUEST` is still working.




> For the rest metrics, it is not expected. Could you double confirm if they are missed after upgraded the BookKeeper to 4.16.0+?

![image](https://github.com/apache/pulsar/assets/15684156/f551b423-274b-4da0-aae2-a8a06772202e)

Yes, we have already upgraded to `4.16.3`.

**Comment by crossoverJie** [comment]
> bookkeeper_server_ADD_ENTRY_BLOCKED
> bookkeeper_server_READ_ENTRY_BLOCKED
> bookie_journal_JOURNAL_CB_QUEUE_SIZE
> bookie_read_cache_hits_count
> bookie_read_cache_misses_count
> bookie_DELETED_LEDGER_COUNT
> bookie_MAJOR_COMPACTION_COUNT

Update: 

count -> total
bookie_read_cache_hits_count -> bookie_read_cache_hits
bookie_read_cache_misses_count -> bookie_read_cache_misses
and remove `success` label.
