### ISSUE TITLE
[Bug] messageDeduplication.inactiveProducers keeps growing if keep creating and closing producers

### ISSUE THREAD

**Issue by poorbarcode** [apache/pulsar#21763]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

`3.0.2`

### Minimal reproduce step

Keep creating and closing producers.

<img width="1427" alt="Screenshot 2023-12-20 at 11 08 39" src="https://github.com/apache/pulsar/assets/25195800/a9dc306b-fff6-4e4c-8d2c-27fbd158874d">

### What did you expect to see?

We need a mechanism to prevent `PersistentTopic.messageDeduplication.inactiveProducers` keeps growing.

### What did you see instead?

-

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
https://github.com/apache/pulsar/pull/21193
