### ISSUE TITLE
[Bug] When consumers with different topics have the same key, the thread is blocked？

### ISSUE THREAD

**Issue by jinxiaoyi** [apache/pulsar#21774]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version
Java SDK 
pulsar-client  3.1.1
apache-pulsar-3.1.1-bin.tar.gz

### Minimal reproduce step
partition=1
In the Key_Shared type, the producer sends messages to different topics. When the key values are the same, different consumers will be blocked. For example, I have two topics, namely topic1 and topic2. When I use producer1 to send the message <k1, v1> to topic1, and at the same time use producer2 to send the message <k1, v2> to topic2, consumer 1 starts running, and consumer 2 is blocked.

### What did you expect to see?

consumer 1 starts running, and consumer 2 runs simultaneously.

### What did you see instead?

consumer 1 starts running, and consumer 2 is blocked.

### Anything else?

test code  https://github.com/jinxiaoyi/pulsar3.1.1_test.git

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
Test is ok copied from yours
```
docker run -it -p 6650:6650 -p 8080:8080 --mount source=pulsardata,target=/pulsar/data --mount source=pulsarconf,target=/pulsar/conf apachepulsar/pulsar:3.1.1 bin/pulsar standalone
```
```
public static void main(String[] args) throws Exception {
        String serviceUrl = "pulsar://localhost:6650";
        PulsarClient pulsarClient = PulsarClient.builder()
                .serviceUrl(serviceUrl).ioThreads(3) 
                .listenerThreads(20).build();

        String topic1 = "persistent://public/default/topic1";
        String topic2 = "persistent://public/default/topic2";
        Producer<String> producer1 = pulsarClient.newProducer(Schema.STRING)
                .topic(topic1).create();
        Producer<String> producer2 = pulsarClient.newProducer(Schema.STRING)
                .topic(topic2).create();


        Consumer<String> consumer1 = pulsarClient.newConsumer(Schema.STRING)
                .topic(topic1).subscriptionType(SubscriptionType.Key_Shared)
                .subscriptionName("my-subscription1").messageListener((consumer, msg) -> {
                    System.out.println("consumer1 start :" + msg.getValue());
                    try {
                        consumer.acknowledge(msg);
                    } catch (Exception e) {
                        throw new RuntimeException(e);
                    }
                }).ackTimeout(30, TimeUnit.MINUTES)
                .subscribe();
        Consumer<String> consumer2 = pulsarClient.newConsumer(Schema.STRING)
                .topic(topic2).subscriptionType(SubscriptionType.Key_Shared)
                .subscriptionName("my-subscription2").messageListener((consumer, msg) -> {
                    System.out.println("consumer2 start :" + msg.getValue());
                    try {
                        consumer.acknowledge(msg);
                    } catch (Exception e) {
                        throw new RuntimeException(e);
                    }
                }).ackTimeout(30, TimeUnit.MINUTES)
                .subscribe();

        producer1.newMessage().key("key").value("value1").send();
        producer2.newMessage().key("key").value("value1").send();

        CountDownLatch latch= new CountDownLatch(1);
        latch.await();
    }
```

**Comment by jinxiaoyi** [comment]
> Test is ok copied from yours
> 
> ```
> docker run -it -p 6650:6650 -p 8080:8080 --mount source=pulsardata,target=/pulsar/data --mount source=pulsarconf,target=/pulsar/conf apachepulsar/pulsar:3.1.1 bin/pulsar standalone
> ```
> 
> ```
> public static void main(String[] args) throws Exception {
>         String serviceUrl = "pulsar://localhost:6650";
>         PulsarClient pulsarClient = PulsarClient.builder()
>                 .serviceUrl(serviceUrl).ioThreads(3) 
>                 .listenerThreads(20).build();
> 
>         String topic1 = "persistent://public/default/topic1";
>         String topic2 = "persistent://public/default/topic2";
>         Producer<String> producer1 = pulsarClient.newProducer(Schema.STRING)
>                 .topic(topic1).create();
>         Producer<String> producer2 = pulsarClient.newProducer(Schema.STRING)
>                 .topic(topic2).create();
> 
> 
>         Consumer<String> consumer1 = pulsarClient.newConsumer(Schema.STRING)
>                 .topic(topic1).subscriptionType(SubscriptionType.Key_Shared)
>                 .subscriptionName("my-subscription1").messageListener((consumer, msg) -> {
>                     System.out.println("consumer1 start :" + msg.getValue());
>                     try {
>                         consumer.acknowledge(msg);
>                     } catch (Exception e) {
>                         throw new RuntimeException(e);
>                     }
>                 }).ackTimeout(30, TimeUnit.MINUTES)
>                 .subscribe();
>         Consumer<String> consumer2 = pulsarClient.newConsumer(Schema.STRING)
>                 .topic(topic2).subscriptionType(SubscriptionType.Key_Shared)
>                 .subscriptionName("my-subscription2").messageListener((consumer, msg) -> {
>                     System.out.println("consumer2 start :" + msg.getValue());
>                     try {
>                         consumer.acknowledge(msg);
>                     } catch (Exception e) {
>                         throw new RuntimeException(e);
>                     }
>                 }).ackTimeout(30, TimeUnit.MINUTES)
>                 .subscribe();
> 
>         producer1.newMessage().key("key").value("value1").send();
>         producer2.newMessage().key("key").value("value1").send();
> 
>         CountDownLatch latch= new CountDownLatch(1);
>         latch.await();
>     }
> ```


In my test code, the consumer part sleeps for 30 seconds to simulate business logic processing. However, the code you provided does not include this logic. As a result, the log printing speed in the consumer part is very fast without any intervals. It makes it difficult to observe specific issues.

![aaa](https://github.com/apache/pulsar/assets/34831856/98ee8cba-074e-4e8c-81f9-7b5becacd111)

**Comment by Technoboy-** [comment]
> > Test is ok copied from yours
> > ```
> > docker run -it -p 6650:6650 -p 8080:8080 --mount source=pulsardata,target=/pulsar/data --mount source=pulsarconf,target=/pulsar/conf apachepulsar/pulsar:3.1.1 bin/pulsar standalone
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > public static void main(String[] args) throws Exception {
> >         String serviceUrl = "pulsar://localhost:6650";
> >         PulsarClient pulsarClient = PulsarClient.builder()
> >                 .serviceUrl(serviceUrl).ioThreads(3) 
> >                 .listenerThreads(20).build();
> > 
> >         String topic1 = "persistent://public/default/topic1";
> >         String topic2 = "persistent://public/default/topic2";
> >         Producer<String> producer1 = pulsarClient.newProducer(Schema.STRING)
> >                 .topic(topic1).create();
> >         Producer<String> producer2 = pulsarClient.newProducer(Schema.STRING)
> >                 .topic(topic2).create();
> > 
> > 
> >         Consumer<String> consumer1 = pulsarClient.newConsumer(Schema.STRING)
> >                 .topic(topic1).subscriptionType(SubscriptionType.Key_Shared)
> >                 .subscriptionName("my-subscription1").messageListener((consumer, msg) -> {
> >                     System.out.println("consumer1 start :" + msg.getValue());
> >                     try {
> >                         consumer.acknowledge(msg);
> >                     } catch (Exception e) {
> >                         throw new RuntimeException(e);
> >                     }
> >                 }).ackTimeout(30, TimeUnit.MINUTES)
> >                 .subscribe();
> >         Consumer<String> consumer2 = pulsarClient.newConsumer(Schema.STRING)
> >                 .topic(topic2).subscriptionType(SubscriptionType.Key_Shared)
> >                 .subscriptionName("my-subscription2").messageListener((consumer, msg) -> {
> >                     System.out.println("consumer2 start :" + msg.getValue());
> >                     try {
> >                         consumer.acknowledge(msg);
> >                     } catch (Exception e) {
> >                         throw new RuntimeException(e);
> >                     }
> >                 }).ackTimeout(30, TimeUnit.MINUTES)
> >                 .subscribe();
> > 
> >         producer1.newMessage().key("key").value("value1").send();
> >         producer2.newMessage().key("key").value("value1").send();
> > 
> >         CountDownLatch latch= new CountDownLatch(1);
> >         latch.await();
> >     }
> > ```
> 
> In my test code, the consumer part sleeps for 30 seconds to simulate business logic processing. However, the code you provided does not include this logic. As a result, the log printing speed in the consumer part is very fast without any intervals. It makes it difficult to observe specific issues.
> 
> ![aaa](https://private-user-images.githubusercontent.com/34831856/292242481-98ee8cba-074e-4e8c-81f9-7b5becacd111.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1ODMzNzQsIm5iZiI6MTcwMzU4MzA3NCwicGF0aCI6Ii8zNDgzMTg1Ni8yOTIyNDI0ODEtOThlZThjYmEtMDc0ZS00ZThjLTgxZjktN2I1YmVjYWNkMTExLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA5MzExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZjQwZGRkMTQzY2VmYTA5YjQ3YjYwMWQ5N2FjOWNkMTJmMWRlNzVjMzljZDUzMGNjMDA4NmVmM2VjMTIzOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fQBewIDU-Wh6X4sozPyRHIrWrY6REilJFC937Wj5SFQ)

Ah, yes, the message listener is triggered by the external executor provider defined in `pulsarClient`; if the consumer is created by the same `pulsarClient,` the consumers will use the same executor, which may trigger the listener one by one. 
https://github.com/apache/pulsar/blob/c157f0d9b4310a3709e7f1b56a51e754473c015a/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java#L1128-L1130

**Comment by jinxiaoyi** [comment]
> > > Test is ok copied from yours
> > > ```
> > > docker run -it -p 6650:6650 -p 8080:8080 --mount source=pulsardata,target=/pulsar/data --mount source=pulsarconf,target=/pulsar/conf apachepulsar/pulsar:3.1.1 bin/pulsar standalone
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > public static void main(String[] args) throws Exception {
> > >         String serviceUrl = "pulsar://localhost:6650";
> > >         PulsarClient pulsarClient = PulsarClient.builder()
> > >                 .serviceUrl(serviceUrl).ioThreads(3) 
> > >                 .listenerThreads(20).build();
> > > 
> > >         String topic1 = "persistent://public/default/topic1";
> > >         String topic2 = "persistent://public/default/topic2";
> > >         Producer<String> producer1 = pulsarClient.newProducer(Schema.STRING)
> > >                 .topic(topic1).create();
> > >         Producer<String> producer2 = pulsarClient.newProducer(Schema.STRING)
> > >                 .topic(topic2).create();
> > > 
> > > 
> > >         Consumer<String> consumer1 = pulsarClient.newConsumer(Schema.STRING)
> > >                 .topic(topic1).subscriptionType(SubscriptionType.Key_Shared)
> > >                 .subscriptionName("my-subscription1").messageListener((consumer, msg) -> {
> > >                     System.out.println("consumer1 start :" + msg.getValue());
> > >                     try {
> > >                         consumer.acknowledge(msg);
> > >                     } catch (Exception e) {
> > >                         throw new RuntimeException(e);
> > >                     }
> > >                 }).ackTimeout(30, TimeUnit.MINUTES)
> > >                 .subscribe();
> > >         Consumer<String> consumer2 = pulsarClient.newConsumer(Schema.STRING)
> > >                 .topic(topic2).subscriptionType(SubscriptionType.Key_Shared)
> > >                 .subscriptionName("my-subscription2").messageListener((consumer, msg) -> {
> > >                     System.out.println("consumer2 start :" + msg.getValue());
> > >                     try {
> > >                         consumer.acknowledge(msg);
> > >                     } catch (Exception e) {
> > >                         throw new RuntimeException(e);
> > >                     }
> > >                 }).ackTimeout(30, TimeUnit.MINUTES)
> > >                 .subscribe();
> > > 
> > >         producer1.newMessage().key("key").value("value1").send();
> > >         producer2.newMessage().key("key").value("value1").send();
> > > 
> > >         CountDownLatch latch= new CountDownLatch(1);
> > >         latch.await();
> > >     }
> > > ```
> > 
> > 
> > In my test code, the consumer part sleeps for 30 seconds to simulate business logic processing. However, the code you provided does not include this logic. As a result, the log printing speed in the consumer part is very fast without any intervals. It makes it difficult to observe specific issues.
> > ![aaa](https://private-user-images.githubusercontent.com/34831856/292242481-98ee8cba-074e-4e8c-81f9-7b5becacd111.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1ODMzNzQsIm5iZiI6MTcwMzU4MzA3NCwicGF0aCI6Ii8zNDgzMTg1Ni8yOTIyNDI0ODEtOThlZThjYmEtMDc0ZS00ZThjLTgxZjktN2I1YmVjYWNkMTExLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA5MzExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZjQwZGRkMTQzY2VmYTA5YjQ3YjYwMWQ5N2FjOWNkMTJmMWRlNzVjMzljZDUzMGNjMDA4NmVmM2VjMTIzOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fQBewIDU-Wh6X4sozPyRHIrWrY6REilJFC937Wj5SFQ)
> 
> Ah, yes, the message listener is triggered by the external executor provider defined in `pulsarClient`; if the consumer is created by the same `pulsarClient,` the consumers will use the same executor, which may trigger the listener one by one.
> 
> https://github.com/apache/pulsar/blob/c157f0d9b4310a3709e7f1b56a51e754473c015a/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java#L1128-L1130

Usually, in a Java service, a new Pulsar client is created only for different namespaces and tenant IDs. It seems unreasonable to create an additional Pulsar client for key-shared mode. Will this logic be optimized later? After all, creating five Pulsar clients for five key-shard queues seems excessive.

**Comment by Technoboy-** [comment]
> Usually, in a Java service, a new Pulsar client is created only for different namespaces and tenant IDs. It seems unreasonable to create an additional Pulsar client for key-shared mode. Will this logic be optimized later? After all, creating five Pulsar clients for five key-shard queues seems excessive.
> 
> Can the combination of topic and key be used as the key for locking?

You can define your own executor to process the logic
