### ISSUE TITLE
[Bug] [worker]  ProducerFencedException：Topic has an existing exclusive producer 

### ISSUE THREAD

**Issue by wuyanzan** [apache/pulsar#21809]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

3.1.0

### Minimal reproduce step

shutdown broker periodly.

### What did you expect to see?

the cluster worker normally.

### What did you see instead?

[persistent://public/functions/metadata] [172.16.0.185-leader] Failed to create producer:{"errorMsg":"org.apache.pulsar.broker.service.BrokerServiceException$ProducerFencedException:Topic has an existing exclusive producer : 172.16.0.190-leader"}

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
hi, we have fixed this issue by the below prs. you can upgrade to 3.1.2
https://github.com/apache/pulsar/pull/21155
https://github.com/apache/pulsar/pull/21183
https://github.com/apache/pulsar/pull/21220
