### ISSUE TITLE
[Bug] The method PulsarAdmin.topics().getMessageById().getPublishTime() returns wrong timestamp when the timezones between broker and client are different.

### ISSUE THREAD

**Issue by tikafu** [apache/pulsar#21891]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Nothing with. OS and Pulsar version.

### Minimal reproduce step

1. The broker and the admin client use different timezone while the producer and the admin client use the same timezone;
2. Produce one message to pulsar and keep the message id;
3. Invoke PulsarAdmin.topics().getMessageById().getPublishTime() to get the publish time of corresponding message, you may find that it is different with the origin publish time created by producer.

### What did you expect to see?

Get correct publish time through admin client though timezones between client and broker are different.

### What did you see instead?

- There is a  time format operation in org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.java

```
...
if (metadata.hasPublishTime()) {
    responseBuilder.header("X-Pulsar-publish-time", DateFormatter.format(metadata.getPublishTime()));
}
...
```

- There is also a time format operation in org.apache.pulsar.client.admin.internal.TopicsImpl.java

```
...
Object tmp = headers.getFirst(PUBLISH_TIME);
if (tmp != null) {
    messageMetadata.setPublishTime(DateFormatter.parse(tmp.toString()));
}
...
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by lhotari** [comment]
> 2\. Produce one message to pulsar and keep the message id;

@tikafu how did you produce this message? Please provide accurate instructions to reproduce this issue.

**Comment by tikafu** [comment]
> > 2. Produce one message to pulsar and keep the message id;
> 
> @tikafu how did you produce this message? Please provide accurate instructions to reproduce this issue.

@lhotari very simple, just use client sdk to produce one message, nothing special like this:
```
MessageId messageId = producer.newMessage().value("hello".getBytes()).send();
```
By the way, the key point is the different timezones and the process of date formatting rather than the way of producing message.

**Comment by lhotari** [comment]
> ```
> MessageId messageId = producer.newMessage().value("hello".getBytes()).send();
> ```

When using the Java API, there is no time zone information in the `publishTime` field.

https://github.com/apache/pulsar/blob/45037399febdcf7208d8cd88bfd75bd2b1074f07/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L584

> 
> By the way, the key point is the different timezones and the process of date formatting rather than the way of producing message.

How did you determine this?

I tested formatting with a different timezone and parsing with the default time zone (that DateFormatter.parse uses) and couldn't reproduce an issue in the date parsing.

```java
package org.apache.pulsar.common.util;

import static org.testng.Assert.assertEquals;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import org.testng.annotations.Test;

public class DateFormatterTest {

    @Test
    public void differentTimeZoneShouldNotMatterInFormattingAndParsing() {
        Instant now = Instant.now();
        String formatted = DateTimeFormatter.ISO_OFFSET_DATE_TIME
                .withZone(ZoneId.of("America/Los_Angeles")).format(now);
        System.out.println(formatted);
        assertEquals(now.toEpochMilli(), DateFormatter.parse(formatted));
    }

}
```

That's why I think that the root cause could be different. Having full steps and examples of timezones used in different sides (client/broker) could be helpful in reproducing the issue.

**Comment by tikafu** [comment]
Well, I will provide a complete example to illustrate this issue。
1. The publish time is generated by the internal code of SDK as shown in the example you just gave above.
https://github.com/apache/pulsar/blob/45037399febdcf7208d8cd88bfd75bd2b1074f07/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L584
It is a long type numerical value,  an absolute timestamp independent of time zone, there is truly no time zone information in the publishTime field.
2. Then the publish time is sent to pulsar and stored on disk as metadata of the message and it become read only.
3. When you invoke the method PulsarAdmin.topics().getMessageById().getPublishTime() to get the publish time of a special message, the broker will find the entry of this message after receiving request and parse the message's metadata, including its publish time.
https://github.com/apache/pulsar/blob/45037399febdcf7208d8cd88bfd75bd2b1074f07/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L3051
Then the broker formats this long type timestamp, it should be noted that this operation will use the timezone of the current broker.
https://github.com/apache/pulsar/blob/45037399febdcf7208d8cd88bfd75bd2b1074f07/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L3070
4. As so far, the publish time has been formatted as a STRING type value from the absolute timestamp and is added to http headers which will be sent to the admin client.
5. Now let's take a look at how the admin client handle this http header in response.
https://github.com/apache/pulsar/blob/45037399febdcf7208d8cd88bfd75bd2b1074f07/pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java#L1292
https://github.com/apache/pulsar/blob/45037399febdcf7208d8cd88bfd75bd2b1074f07/pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java#L1294 
Obviously, it applies a reverse formatting to this STRING, the publish time was changed back to long type numerical value again, but with the timezone of admin client.
6. Now assuming that the timezones between broker and client are different, will the publish time the admin client get finally be the same as its origin?
@lhotari

**Comment by lhotari** [comment]
> 6\. Now assuming that the timezones between broker and client are different, will the publish time the admin client get finally be the same as its origin?

@tikafu The timezone information isn't preserved, but based on the code, the absolute value of the timestamp will be preserved. Are you expecting the timezone information to be preserved?

Would you be able to provide and example that reproduces your problem. You don't have to show Pulsar code and internals in the reproducer of a bug. :)

**Comment by tikafu** [comment]
> > 6. Now assuming that the timezones between broker and client are different, will the publish time the admin client get finally be the same as its origin?
> 
> @tikafu The timezone information isn't preserved, but based on the code, the absolute value of the timestamp will be preserved. Are you expecting the timezone information to be preserved?
> 
> Would you be able to provide and example that reproduces your problem. You don't have to show Pulsar code and internals in the reproducer of a bug. :)

@lhotari OK.
Step1. Set the timezone to Asia/Shanghai and start broker.
<img width="1358" alt="image" src="https://github.com/apache/pulsar/assets/10616763/b7252a9b-b885-48fc-bbf5-b23c0a773145">

Step2.  Produce a message to broker with java client sdk. Notice that the timezone of the client is Asia/Shanghai, too.
<img width="1438" alt="image" src="https://github.com/apache/pulsar/assets/10616763/ed29fa15-81be-4bfe-b960-532b9fb31692">

Step3. Consume a message print publish time to console.Notice that the timezone of the client is Asia/Shanghai, too.
<img width="1439" alt="image" src="https://github.com/apache/pulsar/assets/10616763/3038e72c-ec71-4806-ab85-8090e0c055c9">
The publish time is 1705369257394.

Step4. Get the publish time of message with admin sdk. Notice that the timezone of the client is Asia/Shanghai, too.
<img width="1439" alt="image" src="https://github.com/apache/pulsar/assets/10616763/0248101c-21d0-4752-890b-1256d921f4eb">
The publish time is 1705369257394. Everything is ok up to now.

Step5. Set the timezone to GMT and restart broker.
<img width="1439" alt="image" src="https://github.com/apache/pulsar/assets/10616763/bf0bf21e-313c-4b12-9269-2384608d0ba8">

Step6. Consume the same message print publish time to console.Notice that the timezone of the client is still Asia/Shanghai.
<img width="1439" alt="image" src="https://github.com/apache/pulsar/assets/10616763/4da262e8-cd34-434e-bbd4-46a1e19b1926">
The publish time is 1705369257394, which is the same as before.

Step7. Get the publish time of message with admin sdk. Notice that the timezone of the client is still Asia/Shanghai.
<img width="1439" alt="image" src="https://github.com/apache/pulsar/assets/10616763/2a3ead63-8748-4820-b2df-1022d35c4c7c">
The publish time is 1705340457394, which has already changed.

I am not expecting the timezone information to be preserved, i am expecting the absolute timestamp when i use admin sdk to get publish time of the message.

**Comment by lhotari** [comment]
@tikafu I found this old JVM bug: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8177021 , https://bugs.openjdk.org/browse/JDK-8177021 . It must have been fixed as part of some other change in Java 8 so most likely a JVM upgrade solves your problem.

**Comment by tikafu** [comment]
> @tikafu Just wondering if this is a JVM bug? You seem to be running the client tests with 1.8.0_201 which was released January 15, 2019, over 5 years ago. Could you test with a recent JVM version? If you are stuck on Java 8, please use a recent version from Eclipse Temurin (or others), https://adoptium.net/temurin/releases/?version=8 .

@lhotari No, I don't think this issue is related JVM bugs. I have seen that there is an issue with it from the code logic.

**Comment by tikafu** [comment]
> I also noticed in your screenshots that you are using Pulsar 2.6.3 . That version contains quite a few severe security vulnerabilities (see https://pulsar.apache.org/security/ for some, in addition I think there's also Log4Shell) and isn't supported or maintained. It's better to upgrade any production systems to supported versions to get security fixes and other bug fixes.

@lhotari Well, I'd like to reproduce this issue with the latest version of pulsar released and jdk-17.0.10.

Step1. Show the version of JVM and pulsar.
<img width="597" alt="image" src="https://github.com/apache/pulsar/assets/10616763/b050b9ae-ec11-47e5-adb0-c95210a497dc">

@Step2. Set the timezone to Asia/Shanghai and start broker.
<img width="1351" alt="image" src="https://github.com/apache/pulsar/assets/10616763/eb6f7fb4-9fc4-4999-a29b-0d0980d105ec">

Step3. Show the JVM version of pulsar client.
<img width="1439" alt="image" src="https://github.com/apache/pulsar/assets/10616763/38c14ca6-1e83-41bd-be1f-26cb0c25e782">

Step4. Produce a message to the broker with java client sdk. Notice that the timezone of the client is Asia/Shanghai, too.
<img width="1439" alt="image" src="https://github.com/apache/pulsar/assets/10616763/a105978f-4334-489a-a277-dee7fba2c410">
The message id is 15:0:-1.

Step5. Consume a message print publish time to console.Notice that the timezone of the client is Asia/Shanghai, too.
<img width="1439" alt="image" src="https://github.com/apache/pulsar/assets/10616763/2b8fc0f6-ed33-485e-a2a9-66bdfe4a5e61">
The publish time is 1705890250190.

Step6. Get the publish time of message with admin sdk. Notice that the timezone of the client is Asia/Shanghai, too.
<img width="1439" alt="image" src="https://github.com/apache/pulsar/assets/10616763/10e97fa2-bb74-4b0d-98d3-4afd731ce1d5">
The publish time is 1705890250190, too. Everything is ok up to now.

Step7. Set the timezone to GMT and restart broker.
<img width="1439" alt="image" src="https://github.com/apache/pulsar/assets/10616763/24e90fb3-f6d9-421e-98c1-c6fbe73a29bf">

Step8. Consume the same message print publish time to console.Notice that the timezone of the client is still Asia/Shanghai.
<img width="1439" alt="image" src="https://github.com/apache/pulsar/assets/10616763/9593d1fb-d75f-4265-96b0-80a827e046c6">
The publish time is 1705890250190, which is the same as before.

Step9. Get the publish time of message with admin sdk. Notice that the timezone of the client is still Asia/Shanghai.






> @tikafu Just wondering if this is a JVM bug? You seem to be running the client tests with 1.8.0_201 which was released January 15, 2019, over 5 years ago. Could you test with a recent JVM version? If you are stuck on Java 8, please use a recent version from Eclipse Temurin (or others), https://adoptium.net/temurin/releases/?version=8 .

@lhotari OK, I will have a test with a recent JVM version and a recent pulsar version.

**Comment by tikafu** [comment]
> @tikafu Just wondering if this is a JVM bug? You seem to be running the client tests with 1.8.0_201 which was released January 15, 2019, over 5 years ago. Could you test with a recent JVM version? If you are stuck on Java 8, please use a recent version from Eclipse Temurin (or others), https://adoptium.net/temurin/releases/?version=8 .

@lhotari OK. I will do more tests with a recent JVM version and a recent pulsar version.

**Comment by tikafu** [comment]
> @tikafu I found this old JVM bug: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8177021 , https://bugs.openjdk.org/browse/JDK-8177021 . It must have been fixed as part of some other change in Java 8 so most likely a JVM upgrade solves your problem.

I will take a good look at this issue, thanks!

**Comment by tikafu** [comment]
> > @tikafu Just wondering if this is a JVM bug? You seem to be running the client tests with 1.8.0_201 which was released January 15, 2019, over 5 years ago. Could you test with a recent JVM version? If you are stuck on Java 8, please use a recent version from Eclipse Temurin (or others), https://adoptium.net/temurin/releases/?version=8 .
> 
> @lhotari OK. I will do more tests with a recent JVM version and a recent pulsar version.

@lhotari It is indeed the bug of JVM that caused this issue, thanks for your help!
