### ISSUE TITLE
Can't start Global Zookeeper in a Multi-cluster setup 

### ISSUE THREAD

**Issue by dsambandam** [apache/pulsar#2195]
#### Expected behavior
Global Zookeeper in a Multi-Cluster Setup doesn't start and fails when started in foreground with Invalid arguments

Tell us what should happen
Global Zookeeper should successfully start on Configured client ports:2184

#### Actual behavior
Pulsar daemon and Pulsar  scripts fails to start with Invalid arguments 
Tell us what happens instead

#### Steps to reproduce
1. Setup Cluster-A ( Deploy 3 local Zookeepers)
2. Setup Cluster-B (Deploy 3 local Zookeepers)
3. Deploy global zookeepers with a quorum of 5 servers ( 3 from Cluster-A and 2 from Cluster-B)
4. Execute the following:
    -   ./bin/pulsar-daemon start global-zookeeper
    -  ./bin/pulsar global-zookeeper
How can we reproduce the issue

#### System configuration
**Pulsar version**: 2.0

Logs:

./bin/pulsar-daemon start global-zookeeper
doing start global-zookeeper ...
starting global-zookeeper, logging to /Opt/Pulsar_install/apache-pulsar-2.0.0-rc1-incubating/logs/pulsar-global-zookeeper-cluster-A-Server-1.log

./bin/pulsar global-zookeeper
[AppClassLoader@26bbad11] info AspectJ Weaver Version 1.8.9 built on Monday Mar 14, 2016 at 21:18:16 GMT
[AppClassLoader@26bbad11] info register classloader sun.misc.Launcher$AppClassLoader@26bbad11
[AppClassLoader@26bbad11] info using configuration file:/Opt/Pulsar_install/apache-pulsar-2.0.0-rc1-incubating/lib/org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar!/META-INF/aop.xml
[AppClassLoader@26bbad11] info using configuration file:/Opt/Pulsar_install/apache-pulsar-2.0.0-rc1-incubating/lib/org.apache.pulsar-pulsar-broker-2.0.0-rc1-incubating.jar!/META-INF/aop.xml
[AppClassLoader@26bbad11] info register aspect org.apache.pulsar.zookeeper.FinalRequestProcessorAspect
[AppClassLoader@26bbad11] info register aspect org.apache.pulsar.zookeeper.ZooKeeperServerAspect
[AppClassLoader@26bbad11] info register aspect org.apache.pulsar.broker.zookeeper.aspectj.ClientCnxnAspect
09:29:29.646 [main] INFO  org.apache.pulsar.zookeeper.ZooKeeperStarter - Starting ZK stats HTTP server at port 8001
09:29:29.669 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @1951ms
09:29:29.736 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.3.11.v20160721
09:29:29.772 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@5a088801{/,null,AVAILABLE}
09:29:29.792 [main] INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@78c78a69{HTTP/1.1,[http/1.1]}{0.0.0.0:8001}
09:29:29.792 [main] INFO  org.eclipse.jetty.server.Server - Started @2075ms
09:29:29.797 [main] INFO  org.apache.zookeeper.server.DatadirCleanupManager - autopurge.snapRetainCount set to 3
09:29:29.797 [main] INFO  org.apache.zookeeper.server.DatadirCleanupManager - autopurge.purgeInterval set to 0
09:29:29.798 [main] INFO  org.apache.zookeeper.server.DatadirCleanupManager - Purge task is not scheduled.
09:29:29.798 [main] WARN  org.apache.zookeeper.server.quorum.QuorumPeerMain - Either no config or no quorum defined in config, running  in standalone mode
09:29:29.847 [main] ERROR org.apache.zookeeper.server.ZooKeeperServerMain - Invalid arguments, **exiting abnormally
java.lang.IllegalArgumentException: Invalid number of arguments:[]**
        at org.apache.zookeeper.server.ServerConfig.parse(ServerConfig.java:56) ~[org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.zookeeper.server.ZooKeeperServerMain.initializeAndRun(ZooKeeperServerMain.java:84) ~[org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.zookeeper.server.ZooKeeperServerMain.main(ZooKeeperServerMain.java:53) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:116) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:78) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.pulsar.zookeeper.ZooKeeperStarter.start(ZooKeeperStarter.java:68) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
        at org.apache.pulsar.zookeeper.ConfigurationStoreStarter.main(ConfigurationStoreStarter.java:26) [org.apache.pulsar-pulsar-zookeeper-2.0.0-rc1-incubating.jar:2.0.0-rc1-incubating]
09:29:29.850 [main] INFO  org.apache.zookeeper.server.ZooKeeperServerMain - Usage: ZooKeeperServerMain configfile | port datadir [ticktime] [maxcnxns]
Usage: ZooKeeperServerMain configfile | port datadir [ticktime] [maxcnxns]

**Comment by dsambandam** [comment]
Also, global zookeeper option isn't supported in the pulsar daemon script and wanted to confirm if running configuration-store does start a zookeeper process on global ports?

root@carocnxoappa8v apache-pulsar-2.0.0-rc1-incubating]# ./bin/pulsar-daemon
Error: no enough arguments provided.
Usage: pulsar-daemon (start|stop) <command> <args...>
where command is one of:
    broker              Run a broker server
    bookie              Run a bookie server
    zookeeper           Run a zookeeper server
    configuration-store Run a configuration-store server
    discovery           Run a discovery server
    websocket           Run a websocket proxy server
    standalone          Run a standalone Pulsar service

**Comment by dsambandam** [comment]
confirmed running  ./bin/pulsar-daemon start configuration-store starts zookeeper on global ports .
Scripts needs update. Please track this is an issue.

**Comment by sijie** [comment]
@dsambandam yes global-zookeeper is renamed to configuration-store since 2.0 release.

**Comment by dsambandam** [comment]
Thanks @sijie  maybe documentation needs to be updated as well as the help. Quick Question - my configuration store in the meta data currently points to local zookeeper and I need to modify to point them to global zookeepers now. Is there a command to do this or do I have to delete the metadata and recreate the same?
Any pointers for the right commands would be very helpful.

**Comment by merlimat** [comment]
@dsambandam We currently don't have a ready-made command to do that. 

The procedure would look like: 
 1. Make sure no updates to policies happens while switching (No new namespaces, permissions updates, etc..) -- I think there was a config switch to ensure that as well.
 2. Copy the `/admin/` subtree into "global-zk" 
 3. Change brokers config to point to "global-zk" 
 4. Do brokers rolling restart
 5. (optional) delete data from local-zk

Though I agree that this needs to be better documented and a tool for the z-nodes copy should be provided.d

**Comment by dsambandam** [comment]
Thanks @merlimat I shall try this out .

**Comment by dsambandam** [comment]
@merlimat - can you please help with the Step#2 above as I don't see "copy" is supported in zookeeper shell..

**Comment by merlimat** [comment]
@dsambandam It should work indeed, even if it would have more z-nodes than actually needed since it's also copying the local metadata.

Another approach would be something like https://github.com/ksprojects/zkcopy . With that you can do: 

```
docker run --rm -it ksprojects/zkcopy --source local-zk:2181/admin --target global-zk:2181/admin
```

I think we should provide something similar to this tool in Pulsar itself.

**Comment by dsambandam** [comment]
15:00:23.240 [NIOServerCxn.Factory:::/0:0:0:0:0:0:0:0:2181] INFO  org.apache.zookeeper.server.ZooKeeperServer - Refusing session request for client /Zk2:44714 as it has seen zxid 0xe00000057 our last zxid is 0x100000000 client must try another server

Any suggestions @sijie @merlimat - This happened after copying over local meta data from Local to Global-Zk

**Comment by sijie** [comment]
@dsambandam it seems that there is inconsistent metadata after you copied the metadata. as the log say it has been a smaller zxid. when you copied the metadata, do you first cleanup the global zk directories?

**Comment by sijie** [comment]
close it due to inactivities, @dsambandam if you need more helps, please reopen it.
