### ISSUE TITLE
[Bug] ASF Privacy Policy Changed and the Website must be fixed

### ISSUE THREAD

**Issue by dave2wave** [apache/pulsar#22068]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Current pulsar website

### Minimal reproduce step

See the ASF's internal report on the compliance of pulsar.apache.org with policy: https://whimsy.apache.org/site/project/pulsar

### What did you expect to see?

All boxes should be green.

### What did you see instead?

The resources box is red. The policy is to avoid use of domains which may track users. This is for GPDR compliance.

There are two different external resource domains being used in three source files:

```
pulsar-site % grep -ni cdn.jsdelivr.net ./static/reference/index.html
17:      href="https://cdn.jsdelivr.net/npm/docsify-themeable@0/dist/css/theme-simple-dark.css"
22:      href="https://cdn.jsdelivr.net/npm/docsify-themeable@0/dist/css/theme-simple.css"
231:    <script src="https://cdn.jsdelivr.net/npm/docsify@4/lib/docsify.min.js"></script>
232:    <script src="https://cdn.jsdelivr.net/npm/docsify-themeable@0/dist/js/docsify-themeable.min.js"></script>
235:    <script src="https://cdn.jsdelivr.net/npm/docsify@4/lib/plugins/search.js"></script>
236:    <script src="https://cdn.jsdelivr.net/npm/docsify@4/lib/plugins/zoom-image.min.js"></script>
241:    <script src="https://cdn.jsdelivr.net/npm/docsify-sidebar-collapse/dist/docsify-sidebar-collapse.min.js"></script>
```

```
pulsar-site % grep -ni cdn.jsdelivr.net ./docusaurus.config.js       
481:      href: "https://cdn.jsdelivr.net/npm/katex@0.13.24/dist/katex.min.css",
```

```
pulsar-site % grep -ni fonts.google ./src/css/typography.css         
1:@import url("https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,400;0,500;0,600;1,400;1,500;1,600&display=swap");
```

### Anything else?

The boxes will be green once these resources are moved to static resources hosted on the `pulsar.apache.org` website

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by visortelle** [comment]
The PR is merged. 
@dave2wave should we somehow trigger the whimsy check?

https://whimsy.apache.org/site/project/pulsar

**Comment by dave2wave** [comment]
AFAIK - The whimsy check is daily. Check again tomorrow.

**Comment by visortelle** [comment]
All the boxes are green.

<img width="1250" alt="Screenshot 2024-02-28 at 2 17 25 AM" src="https://github.com/apache/pulsar/assets/9302460/189f2a62-ae11-47c0-aa3a-40e4db8c7ca2">
