### ISSUE TITLE
[Bug] jvm parameter PerfDisableSharedMem causes jstat to be unavailable

### ISSUE THREAD

**Issue by g0715158** [apache/pulsar#22097]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

3.0.1

### Minimal reproduce step

jstat、jps  Command cannot view the process

### What did you expect to see?

You can run the jps and jstat commands

### What did you see instead?

 cannot view the process

### Anything else?

May I ask if you have considered the inavailability of jps and jstat when adding this parameter? Is it appropriate to delete PerfDisableSharedMem parameter from bookie and broker in the current version?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
The reason why the parameter is typically passed is explained in this blog post: https://www.evanjones.ca/jvm-mmap-pause-finding.html and https://www.evanjones.ca/jvm-mmap-pause.html .

You could always configure Pulsar's JVM parameters to suite your needs.

**Comment by lhotari** [comment]
More details: https://github.com/simonis/mmap-pause

**Comment by g0715158** [comment]
@lhotari Thank you very much for your help

**Comment by Shawyeok** [comment]
IMO, the easiest way to identify a java process (i.e. broker process) is `jps`, especially in environments with multiple JVMs running simultaneously like a Pulsar hybrid deployment.

What I found the best alternative to `jps` is: `pgrep -fa java`.
