### ISSUE TITLE
[Enhancement] Automated site preview deployments for PRs

### ISSUE THREAD

**Issue by visortelle** [apache/pulsar#22128]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Before merging any PR to the site, seeing how site and docs changes look in a browser is useful.

Currently, the reviewer needs to have a local repo copy, a proper Node.js version, switch to the proper branch, install dependencies, and finally run the site using `npm start`.

This process isn't hard for someone who reviews PRs regularly, but for others, this is an additional obstacle that can prevent them from taking a look.

Imagine you made a visual change or worked on some tutorial or blog post. By having automated deployments you'll be able to share this link to the mailing list or Slack and anyone interested will be able to read and review your changes without the need to do any additional actions.

I think it could bring more eyes to the review process and contribute to improving documentation quality over time.

### Solution

Use Vercel for automated deployments.
https://vercel.com/

Taking into account the number of PRs to the apache/pulsar-site repository per month, the free Vercel plan should be enough for the near future. The next paid plan is $20 per month which isn't much.

We currently use this approach for reviewing this PR: https://github.com/apache/pulsar-site/pull/789
The PR branch preview: https://pulsar-site-2024-updates.vercel.app/

I also tried it with a PR by another person's fork here:
https://github.com/visortelle/pulsar-site-2024-updates/pull/1

You can see that the preview deployment has been successfully created:
<img width="920" alt="Screenshot 2024-02-27 at 11 26 58 AM" src="https://github.com/apache/pulsar/assets/9302460/948d22cd-0276-4288-9f6b-059859a1f16d">

https://pulsar-site-2024-updates-8c5d4i9z9-visortelle.vercel.app/books/
<img width="653" alt="Screenshot 2024-02-27 at 11 27 43 AM" src="https://github.com/apache/pulsar/assets/9302460/89ec8f37-d648-4bc0-a547-75b780681b6c">

### Implementation

- No code changes are needed.
- Setup takes 15 minutes.
- The free Vercel plan implies that a single user has access to the Vercel project that connects the GitHub repo to Vercel. I'm going to request access after being sure that it will be approved. **Should I contact anyone in ASF infra beforehand?**
  <img width="791" alt="Screenshot 2024-02-27 at 11 17 46 AM" src="https://github.com/apache/pulsar/assets/9302460/65185fdc-cd7f-4821-8967-aef1ff1182d5">

### Alternatives

- Any other cloud provider than Vercel that simplifies this process.
- Not involve 3rd party services and automate this process using the existing ASF infra resources. It would take more time to implement and additional cost for maintenance.

### Anything else?

- The build time doesn't impact GitHub Actions resources. Vercel uses its own CI.
- The Vercel approach covers most, but not 100% of cases. For example, docs for the previous Pulsar versions won't be published this way. Building all the previous version docs would make CI build time much longer.
- The need for automated feature branch deployments was also mentioned in this comment:
https://github.com/apache/pulsar-site/pull/543#issuecomment-1562151294

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by asafm** [comment]
@lhotari Do we need ASF approval for this?
@visortelle Do you add in github secrets your own user for deployments? How do we keep more than 1 person in that app so if you step away, others can chime in on this?

**Comment by visortelle** [comment]
@asafm I didn’t touch any secrets or env variables. Nor in GitHub forked repository settings nor in Vercel project settings.

How do we keep more than 1 person in that app so if you step away, others can chime in on this?

There are few options:
- The simplest solution is just to ask me to delete the Vercel project and someone else will be able to set it up again 🙂
- Someone from the ASF infra team can remove the GitHub <-> Vercel link without the need to ask me and create a new one.
- We can use a shared GitHub account like `pulsar-service-user` and set up the link on its behalf. Then in the case of the bus :bus: just change the credentials.

**Comment by lhotari** [comment]
> @lhotari Do we need ASF approval for this?
I don't think so, but I could always be wrong. :) @dave2wave knows the right answers.

**Comment by asafm** [comment]
@visortelle Can more than one person be added to this Vercel account in case you are on vacation and we want to fix something?

**Comment by visortelle** [comment]
> Can more than one person be added to this Vercel account
@asafm not in the free plan.

It's doubtful I will be on vacation in a place without Internet access 🚀🌔🏝️

The setup takes a few clicks. Switching to another's person account would take 15 minutes if the approval process is quick.
 
If we try it and find it useful, I can describe the setup process in a markdown document.

**Comment by visortelle** [comment]
I requested the access. Let's see what will happen :)

<img width="754" alt="Screenshot 2024-02-29 at 1 56 46 PM" src="https://github.com/apache/pulsar/assets/9302460/b85ba1cb-6e26-4588-8a12-f320b76f48f4">

**Comment by asafm** [comment]
@visortelle, I think you need to file a JIRA issue to have them approve this pasted above.

Another question - would the mechanism of GitHub pages work for our use case?

**Comment by visortelle** [comment]
@asafm it would, but it needs a bit of bash/whatever code like here:

https://github.com/haskellfoundation/haskellfoundation.github.io/pull/170/files#diff-3ed7460912c35ce883da3c35afc7975ffb28bdeac52bb95569b71b641b9a4300

I'm not sure that anyone wants to support it.
If it's possible to implement without touching the code, I would prefer to go this way.

**Comment by visortelle** [comment]
**HashiCorp** actively uses Vercel for their project site deployments.

You'll find it across most of their projects including Terraform, Consul, and Vault.
  
Forked repository PR deployment example: https://github.com/hashicorp/terraform/pull/34375
  
<img width="909" alt="Screenshot 2024-03-01 at 12 27 09 PM" src="https://github.com/apache/pulsar/assets/9302460/81af2e91-6e10-41b5-bed2-aaffa98cf59f">

**Comment by visortelle** [comment]
Small clarification on how it works in HashiCorp. 

PRs from forked repositories require approval by someone who maintains the site.

<img width="890" alt="Screenshot 2024-03-04 at 6 43 00 PM" src="https://github.com/apache/pulsar/assets/9302460/e5cad6be-d294-49e7-a170-922103ca30b5">

<img width="978" alt="Screenshot 2024-03-04 at 6 42 08 PM" src="https://github.com/apache/pulsar/assets/9302460/447b4566-2af3-4043-a281-52df3acca65b">

**Comment by visortelle** [comment]
The ASF infra team suggested taking a look at [.asf.yaml](https://github.com/apache/infrastructure-asfyaml/blob/main/README.md)

Ref: https://issues.apache.org/jira/browse/INFRA-25567

It supports branch deployment branch deployments, but:
- doesn't support forked repositories PR deployments
- doesn't care about deleted branches
- doesn't automatically add a deployment link to a PR page. Users should manually submit this link as a part of the PR comment, or know how to get this link

Regarding Vercel, the answer is NO
<img width="674" alt="Screenshot 2024-03-04 at 8 40 44 PM" src="https://github.com/apache/pulsar/assets/9302460/e5f4714f-a285-4461-8788-369d1719a08c">

I'll probably experiment with `.asf.yaml` in the future, but closing for now.

**Comment by asafm** [comment]
@visortelle If we assume most contributions will be made a PRs to pulsar-site repo then can get by (1). 
Can you explain about deleted branches. I'm not familiar with GitHub pages mechanism at all.
Do you think ASF infra would be open to improve their GitHub Pages support to add a comment to the PR? Can't we do it if we use gitHub CI workflows?

**Comment by visortelle** [comment]
@asafm 

> Can you explain about deleted branches.
From the first look, it seems like it doesn't care about removing the deployment after the source branch was deleted. I don't know the details.

> I'm not familiar with GitHub pages mechanism at all.

Usually, you just pick the source branch and a root directory where GitHub expects to find index.html or README.md, maybe more pre-defined `index.*` file names for other document types.
Then it serves this directory content on domain like `<user>github.io/<repo>`

<img width="759" alt="Screenshot 2024-03-05 at 12 59 32 AM" src="https://github.com/apache/pulsar/assets/9302460/ccd86a92-403b-43fe-a0c8-6b9581157e20">

I just found an interesting thing that is in **beta**. Probably it solves the task. I will check it.

<img width="834" alt="Screenshot 2024-03-05 at 1 05 19 AM" src="https://github.com/apache/pulsar/assets/9302460/c96cad81-0060-47d1-968b-3c1b5236f90d">

> Do you think ASF infra would be open to improve their GitHub Pages support to add a comment to the PR?

I have no idea :)

> Can't we do it if we use gitHub CI workflows?

Yes, we can call GitHub API in bash/python/js script after the build.
