### ISSUE TITLE
[Bug] Broker memory leak 

### ISSUE THREAD

**Issue by graysonzeng** [apache/pulsar#22157]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

v3.1.1

### Minimal reproduce step

After running for a period of time, the broker memory will gradually increase and eventually lead to a restart.
![企业微信截图_6fc91d9b-5071-41bd-a698-d7c7c8a5b975](https://github.com/apache/pulsar/assets/21187269/74c6be15-bc83-448c-bce3-6f948e0884e6)

After the heap dump, it was found that many ManagedLedgerImpl instances were retained in the memory, and these instances occupied most of the memory.

![企业微信截图_a61faea0-4ef0-4488-905f-c91d5275cf37](https://github.com/apache/pulsar/assets/21187269/cfc71bbc-8593-4565-8b97-bd84be15db1f)

 Common Path To the Accumulation Point：
![image](https://github.com/apache/pulsar/assets/21187269/cae8ad90-e218-430b-b8f0-d57f2a981484)

![image](https://github.com/apache/pulsar/assets/21187269/6cd9c36d-8bba-48dd-89c6-46db03fcb0f2)

- [ ] 

### What did you expect to see?

Normal memory GC

### What did you see instead?

broker restart

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by dao-jun** [comment]
could you please upload the heap dump file？

**Comment by graysonzeng** [comment]
The heap dump has reached 13GB and cannot be uploaded

**Comment by dao-jun** [comment]
> The heap dump has reached 13GB and cannot be uploaded

compress it and upload to cloud driver, such as 百度云? it is very important to locate the root cause

**Comment by lhotari** [comment]
> > The heap dump has reached 13GB and cannot be uploaded
> 
> compress it and upload to cloud driver, such as 百度云? it is very important to locate the root cause

@graysonzeng @dao-jun please notice that the heap dump could contain sensitive data. it should be never shared without encryption because of this.

**Comment by lhotari** [comment]
I'd recommend adding https://github.com/vlsi/mat-calcite-plugin plugin to Eclipse MAT so that you can do SQL queries to the heap dump. Eclipse MAT has OQL support, but that's not so handy as the SQL queries where you can do anything that Calcite supports with SQL.

not useful for this case, but an example of a Calcite query using Eclipse MAT + Calcite plugin:
```
select clientVersion, count(clientVersion) from org.apache.pulsar.broker.service.ServerCnx group by 1 order by 2 desc
```

**Comment by lhotari** [comment]
@graysonzeng related to #13939 ?

**Comment by graysonzeng** [comment]
pulsar version is 3.1.1。It looks like related to #13939 . It looks like maybe removeWaitingCursor is not properly removing the cursor after deactivateCursor() converts the cursor's isActive to false. @lhotari 
https://github.com/apache/pulsar/blob/6ec473ed6458cf30e1fc7062057a50bfefada6cf/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java#L310-L311

**Comment by graysonzeng** [comment]
the waitingCursors is ConcurrentLinkedQueue, this means that the equals and hashcode of the object are compared when deleting. I have a guess, maybe the curosr instance has changed, causing the remove method to fail to delete the curosr reference.

**Comment by lhotari** [comment]
Another possibility is that non-durable cursors and related subscriptions should be cleaned up when a connection dies in an unexpected way. I'm not sure how that is handled in the code base currently.

**Comment by lhotari** [comment]
Or maybe cleaned up after an inactivity period?

**Comment by Technoboy-** [comment]
There is a race condition between the `consumer.close` and `checkForNewEntries`.
When the consumer is closed, the `waitingCursor` is empty.
https://github.com/apache/pulsar/blob/ccc2ea67c192b4771c9af30c6eaf994fe01958e5/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java#L298-L313. 
Then after executing line-311, the cursor was added to `waitingCursor`.

###  Reproduced test

1. Add sleep time for `checkForNewEntries`, like 10s.  https://github.com/apache/pulsar/blob/ccc2ea67c192b4771c9af30c6eaf994fe01958e5/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L983-L989
![image](https://github.com/apache/pulsar/assets/6297296/6fdb69d7-96a0-4190-b8e6-bf8b4bd81f37)

3. Then the below test will reproduce.
```
@Test
    public void testWaitingCursors() throws Exception {
        final String ns = "prop/ns-test";
        admin.namespaces().createNamespace(ns, 2);
        final String topicName = "persistent://prop/ns-test/testWaitingCursors";
        admin.topics().createNonPartitionedTopic(topicName);
        final Consumer<String> consumer = pulsarClient.newConsumer(Schema.STRING).topic(topicName)
                .subscriptionMode(SubscriptionMode.NonDurable)
                .subscriptionType(SubscriptionType.Exclusive)
                .subscriptionName("sub-2").subscribe();
        final Producer<String> producer = pulsarClient.newProducer(Schema.STRING).topic(topicName).create();
        producer.send("test");
        producer.close();
        final String broker = admin.lookups().lookupTopic(topicName);
        final Optional<Topic> topic = pulsar.getBrokerService().getTopic(topicName, false).join();
        assertNotNull(topic.get());
        PersistentTopic persistentTopic = (PersistentTopic) topic.get();
        final PersistentSubscription subscription = persistentTopic.getSubscription("sub-2");
        NonDurableCursorImpl cursor = (NonDurableCursorImpl) subscription.getCursor();
        final Message<String> receive = consumer.receive();
        assertEquals("test", receive.getValue());
        consumer.close();
        while (true) {
            ManagedLedgerImpl ledger = (ManagedLedgerImpl) cursor.getManagedLedger();
            log.info("waitingCursorsCount : {}", ledger.getWaitingCursorsCount());
            Thread.sleep(5 * 1000);
        }
    }
```
