### ISSUE TITLE
function status list json returns strings for counts and timestamp

### ISSUE THREAD

**Issue by cckellogg** [apache/pulsar#2216]
#### Expected behavior

The function status fields numProcessed, numSuccessfullyProcessed, and lastInvocationTime should be longs instead of strings.

#### Actual behavior

{
  "functionStatusList": [
    {
      "running": true,
      "numProcessed": "148770",
      "numSuccessfullyProcessed": "148770",
      "lastInvocationTime": "1532301574265",
      "instanceId": "0",
      "metrics": {
        "metrics": {
          "__total_processed__": {
            "count": 3007.0,
            "sum": 3007.0,
            "max": 3007.0
          },
          "__total_successfully_processed__": {
            "count": 3007.0,
            "sum": 3007.0,
            "max": 3007.0
          },
          "__total_system_exceptions__": {},
          "__total_user_exceptions__": {},
          "__total_serialization_exceptions__": {},
          "__avg_latency_ms__": {}
        }
      },
      "workerId": "c-standalone-fw-localhost-6750"
    }
  ]
}

#### Steps to reproduce

deploy a function then curl

http://localhost:8080/admin/v2/functions/tenant/ns/my-func/status

**Comment by srkukarni** [comment]
We are using JsonFormat class provided in the google protobuf library to convert the an internal protobuf structure to json. According to https://developers.google.com/protocol-buffers/docs/proto3#json int64 translate to string. Is there any way you can interpret them in your client as int64?

**Comment by ivankelly** [comment]
@cckellogg @srkukarni I guess this can be closed as a "won't fix", no?

**Comment by srkukarni** [comment]
Yup, this is not on the horizon any time soon.
