### ISSUE TITLE
[Doc] Wrong spelling of the word Use

### ISSUE THREAD

**Issue by kartikch25** [apache/pulsar#22173]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The word "Use" is spelled as "Usee."

### What is your suggestion?

Change the spelling to **Use**.

### Any reference?

https://pulsar.apache.org/docs/next/client-libraries-node-use/

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by jak78** [comment]
Thank you, @kartikch25, for bringing this to our attention! This issue appears to be still relevant. Could you kindly reopen it? Also, we would greatly appreciate it if you could submit a Pull Request. You can easily do this by clicking the 'edit' button at the bottom of the page. It should only take a couple of minutes. Thank you!
