### ISSUE TITLE
[Doc] pulsar-io-netty-3.2.1.nar appears twice on the download page

### ISSUE THREAD

**Issue by sebbASF** [apache/pulsar#22229]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The artifact pulsar-io-netty-3.2.1.nar appears twice on the download page with different descriptions.

### What is your suggestion?

Combine the entries or remove one

### Any reference?

https://pulsar.apache.org/download/

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jashnGoyl** [comment]
Hey! can I take up this issue?

**Comment by lhotari** [comment]
> Hey! can I take up this issue?

@jashnGoyl Sure, please go ahead. The website is in apache/pulsar-site repository.
