### ISSUE TITLE
[Doc] Add link to Docker Hub images to Pulsar website download page

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#22276]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

Website: the link to Docker Hub images is missing from the download page

### What is your suggestion?

Add link to  https://hub.docker.com/r/apachepulsar/pulsar somewhere on the download page

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by visortelle** [comment]
Resolved: https://github.com/apache/pulsar-site/pull/855
