### ISSUE TITLE
[Doc] REST API examples are incorrect in docs

### ISSUE THREAD

**Issue by visortelle** [apache/pulsar#22289]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

Compare the URLs on these two screenshots:

<img width="858" alt="Screenshot 2024-03-18 at 11 16 57 AM" src="https://github.com/apache/pulsar/assets/9302460/615408d4-dc72-4a52-bbce-5471ff544a05">

---

<img width="1019" alt="Screenshot 2024-03-18 at 11 17 23 AM" src="https://github.com/apache/pulsar/assets/9302460/bf59f8b9-84f3-4ee7-a399-cd67aae10ef0">

The body JSON payload is also different.

The `POST <url>` on the docs page isn’t an endpoint the user can call by `curl`, but a part of a URL to the endpoint section at the REST API reference page.

The source in the site repo: <https://github.com/apache/pulsar-site/blob/8c91e927054dd1ad7aed1b2f6c6cf27902a1d310/docs/admin-api-schemas.md?plain=1#L438>

The original report in Slack: https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1710744420090059

### What is your suggestion?

The docs page doesn’t look auto-generated.

I see the following ways how we can fix that:
- Remove the description and keep just a link to the up-to-date section in REST API docs
- Review all the endpoints manually, which may be very tedious 
- Find a way to render/embed always up-to-date documentation from the OpenAPI definitions

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Samreay** [comment]
Previously raised as https://github.com/apache/pulsar/issues/21573

**Comment by visortelle** [comment]
Closing as duplicate.
