### ISSUE TITLE
IntelliJ checkstyle plugin dropped support for checkstyle 8.x, upgrade checkstyle to newer version

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#22286]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

[IntelliJ checkstyle plugin](https://plugins.jetbrains.com/plugin/1065-checkstyle-idea) dropped support for checkstyle 8.x in the 5.88.0 version update. 

Fails with this error message:
> The Checkstyle rules file could not be parsed. cannot initialize module TreeWalker - cannot initialize module JavadocMethod - Property 'scope' does not exist, please check the documentation The file has been blocked for 60s

### Solution

- Upgrade `buildtools/src/main/resources/pulsar/checkstyle.xml` to support newer checkstyle 10.x version
- Upgrade checkstyle to 10.x

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by nodece** [comment]
What do you think about https://github.com/diffplug/spotless? 

This plugin supports check and format code, I think we can use spotless instead of checkstyle. 

Once we notice that the code has been formatted by spotless on the master branch,  we will be limited when doing cherry-pick operations. If we can double-check by spotless and checkstyle, this will be simpler.

**Comment by lhotari** [comment]
> What do you think about https://github.com/diffplug/spotless?
> 
> This plugin supports check and format code, I think we can use spotless instead of checkstyle.
> 
> Once we notice that the code has been formatted by spotless on the master branch, we will be limited when doing cherry-pick operations. If we can double-check by spotless and checkstyle, this will be simpler.
> 
> We have this discussion thread on the [dev@pulsar.apache.org](mailto:dev@pulsar.apache.org), but I don't know this URL, which title is `[DISCUSS] Consistent code style (esp. ws/indent) and autotools`

@nodece What you are proposing is a completely different thing. I don't think that we want to change the way how code is formatted in Pulsar right now. Such changes cause unnecessary code changes without valuable benefits. 

We should simply upgrade checkstyle to a supported version right now. That requires migrating the configuration file slightly.

**Comment by nodece** [comment]
Upgrading the checkstyle is simpler, I agree with you. 

Right now, the checkstyle is not strict, some places have extra indentation, while others have extra spaces, so I suggest using spotless.

**Comment by lhotari** [comment]
> Upgrading the checkstyle is simpler, I agree with you. PR: https://github.com/apache/pulsar/pull/22291
> 
> Right now, the checkstyle is not strict, some places have extra indentation, while others have extra spaces, so I suggest using spotless.

Making a change to formatting is a broad change that cause more harm than benefit to the Pulsar project currently. We can reconsider after the maintenance strategy has been revisited.
