### ISSUE TITLE
how to unsubscribe pulsar mailing list.

### ISSUE THREAD

**Issue by mykidong** [apache/pulsar#2236]
Sorry, it is not related to pulsar issue, but to pulsar mailing list unsubscription.
Even though I have sent unsubscription emails to users-unsubscribe@pulsar.incubator.apache.org and dev-unsubscribe@pulsar.incubator.apache.org, I am still receiving mails from pulsar.
I have no idea how to unsubscribe pulsar mailing list. 

- Kidong Lee.
P.S: my email address: mykidong@gmail.com

**Comment by sijie** [comment]
@mykidong when you send emails to users-unsubscribe, did you receive any emails from the mailing list confirming you are removed?

**Comment by mykidong** [comment]
No, I have not received any emails of remove confirmation.


2018-07-28 5:38 GMT+09:00 Sijie Guo <notifications@github.com>:
