### ISSUE TITLE
[Bug] Force Delete subscription not working on persistent topics

### ISSUE THREAD

**Issue by alexesom** [apache/pulsar#22404]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

OS: Ubuntu 23.10
Docker Pulsar standalone 3.1.2

### Minimal reproduce step

Using Java client suggesting that `adminClient` is of type `PulsarAdmin`:
invoke `adminClient.topics().deleteSubscription(*topicName*, *subName*, true)` which deletes the subscription forcefully on a persistent topic (on a non-persistent topic it works just fine) and on subscription (same for durable and non-durable) with some active consumers.
It could be connected with #9477 also.

### What did you expect to see?

Expected to delete subscriptions with active consumers.

### What did you see instead?

I get an error:
```org.apache.pulsar.client.admin.PulsarAdminException$PreconditionFailedException: Subscription has active connected consumers```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by dao-jun** [comment]
This issue introduce by https://github.com/apache/pulsar/pull/15347, I'll fix it soon
