### ISSUE TITLE
[Bug] OIDC - Optional alg field being required in Pulsar causes OIDC authentication to fail

### ISSUE THREAD

**Issue by slawrencemd** [apache/pulsar#22419]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

Pulsar v3.1.1

### Minimal reproduce step

Goal is to enable OIDC in a standalone Pulsar instance via Azure App Registrations. 

1. Create an App registration in Azure in preparation for OIDC
2. Bind the necessary args to the standalone.conf file to enable OIDC following official instructions, including admin role binding
3. Start instance 
4. Configure the pulsar admin/shell to use OAuth2 with a credential and make an admin call (ex: tenants list)

### What did you expect to see?

listed tenants

### What did you see instead?

A 401/unauthorized on the client/shell side.
![image](https://github.com/apache/pulsar/assets/151540338/4b4b96fe-16d8-4890-a9f8-7b431f39d9d6)

An error on the Pulsar broker/instance side: Failed to authenticate HTTP request: `Failed to authenticate HTTP request: JWK's alg [null] does not match JWT's alg [RS256]`

![image](https://github.com/apache/pulsar/assets/151540338/da47e952-4e46-4a17-82df-ee52cd38e146)

### Anything else?

The 'alg' header is [optional](https://datatracker.ietf.org/doc/html/rfc7517#page-8), as per the JWK spec:
![image](https://github.com/apache/pulsar/assets/151540338/ead0f329-ea94-45b3-a0ef-f7fc8bb0ec10)

[Azure does not return this as field as part of the well known config](https://github.com/awslabs/aws-jwt-verify/issues/6), but the Pulsar [OIDC implementation](https://github.com/apache/pulsar/blob/cd6f53baee7dbe0651e6581cb9bd3570017348c7/pulsar-broker-auth-oidc/src/main/java/org/apache/pulsar/broker/authentication/oidc/AuthenticationProviderOpenID.java#L307) requires this. This validation is failing and results in the error I saw in the Pulsar instance logs:

![image](https://github.com/apache/pulsar/assets/151540338/651e3bba-1e8f-4dfe-949d-bea06fb55a5c)

It's also possible I've screwed up the OIDC configuration, but my suspicion above seems to make sense... I can share more of my config if needed. 

I'll be glad to do anything I can to help fix this; my guess is this behavior would prevent it from functioning with Azure (if the alg field is missing globally). Short of creating a custom OIDC implementation/authorizer myself, is there anything else I can do in the interim to get around this?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by slawrencemd** [comment]
Screenshot of missing 'alg' field in azure ./well-known config:

![image](https://github.com/apache/pulsar/assets/151540338/30577628-4ebc-42d2-9747-4421c2b2f280)

**Comment by lhotari** [comment]
Thanks for the good issue report @slawrencemd ! Would you like to contribute a fix?

**Comment by lhotari** [comment]
I'm working on a fix.

**Comment by michaeljmarshall** [comment]
Great write up, thanks for surfacing this!

**Comment by slawrencemd** [comment]
You guys are fast! Thank you.

I'm still setting up my environment and getting the build up and running; once I get those first baby steps done and a bit comfier with the codebase/processes, I'll be glad to contribute in other issues/features.

thanks,
-s
