### ISSUE TITLE
[Bug] We are leaving old releases in the ASF distribution area. Please cleanup.

### ISSUE THREAD

**Issue by dave2wave** [apache/pulsar#22486]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

Unsupported versions are found here: https://dist.apache.org/repos/dist/release/pulsar/

### Minimal reproduce step

This is about too many old versions in the release list area.

### What did you expect to see?

I see stale versions should be in the `dist` area. Every release is archived forever here: https://archive.apache.org/dist/pulsar/

### What did you see instead?

I should only see current versions.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
Cleaned up. Please take a look @dave2wave

**Comment by lhotari** [comment]
I cleaned up even more.

**Comment by visortelle** [comment]
@dave2wave, can you please confirm if the issue can be closed?

**Comment by dave2wave** [comment]
You all went too far I’m looking here: https://downloads.apache.org/pulsar/

Where have the ALL of the CURRENT Pulsar releases gone?

Instead of old releases ALL server releases were deleted?! 

Now there are NO official releases of Pulsar.

These MUST BE restored by reverting the svn commit that deleted them and then doing the correct deletion!

**Comment by dave2wave** [comment]
> I cleaned up even more.

You cleaned up current releases with:

**Comment by dave2wave** [comment]
```
cd /tmp
svn co --depth=empty https://dist.apache.org/repos/dist/release/pulsar/
cd pulsar
svn cp ^/release/pulsar/pulsar-3.0.4@68657 .
svn cp ^/release/pulsar/pulsar-3.1.3@68657 .
svn cp ^/release/pulsar/pulsar-3.2.2@68657 .
svn cp ^/release/pulsar/pulsar-adapters-2.11.0@68657 .
svn cp ^/release/pulsar/pulsar-client-cpp-3.5.0@68657 .
svn cp ^/release/pulsar/pulsar-client-go-0.11.1@68657 .
svn cp ^/release/pulsar/pulsar-client-node/pulsar-client-node-1.10.0@68657 .
svn cp ^/release/pulsar/pulsar-client-python-3.5.0@68657 .
svn cp ^/release/pulsar/pulsar-client-reactive-0.5.3@68657 .
svn cp ^/release/pulsar/pulsar-dotpulsar-3.1.2@68657 .
svn cp ^/release/pulsar/pulsar-manager/pulsar-manager-0.3.0@68657 .
# the above took about 17GB
svn commit -m 'Restore current releases.'
Adding         pulsar-3.0.4
Adding         pulsar-3.1.3
Adding         pulsar-3.2.2
Adding         pulsar-adapters-2.11.0
Adding         pulsar-client-cpp-3.5.0
Adding         pulsar-client-go-0.11.1
Adding         pulsar-client-node-1.10.0
Adding         pulsar-client-python-3.5.0
Adding         pulsar-client-reactive-0.5.3
Adding         pulsar-dotpulsar-3.1.2
Adding         pulsar-manager-0.3.0
Committing transaction...
Committed revision 68836.
# the above did not upload as svn already had all the bits.
```
