### ISSUE TITLE
How to manage namespace policies efficiently

### ISSUE THREAD

**Issue by dbsd11** [apache/pulsar#2250]
#### Expected behavior

Doubts about the use and policies of namespace . It's not very intuitive. I think need an admin-ui project to manage namespaces,topics like rocketmq

**Comment by sijie** [comment]
I never try rocketmq UI before. do you have any experiences that you can share with us?

**Comment by sijie** [comment]
@dbsd11 there is a Pulsar Manager (https://github.com/apache/pulsar-manager) now for managing namespaces in web UI.
