### ISSUE TITLE
[improve] Parse the XFF header to get real client IP when behind reverse proxy

### ISSUE THREAD

**Issue by ciiiii** [apache/pulsar#22512]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

When a broker or proxy is deployed behind a reverse proxy, the origin IP of requests will always be IP of the proxy, Therefore the XFF(X-Forwarded-For) request header is often used to preserve the real client IPs, its a de-facto standard. However, the broker and proxy do not currently handle this.

### Solution

Configure [ForwardedRequestCustomizer](https://eclipse.dev/jetty/javadoc/jetty-12/org/eclipse/jetty/server/ForwardedRequestCustomizer.html) for jetty [httpConfiguration](https://github.com/apache/pulsar/blob/20915d1c438783c05778d98a3b77ec485b79d79d/pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java#L105) to handle these headers and support this feature.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by lhotari** [comment]
X-Forwarded-For header isn't sufficient for all use cases. Jetty 12 has support for ["HA proxy protocol"](https://www.haproxy.org/download/2.2/doc/proxy-protocol.txt), explained here: https://eclipse.dev/jetty/documentation/jetty-12/operations-guide/index.html#og-protocols-proxy-protocol

The Pulsar binary protocol already supports "HA proxy protocol" with the `haProxyProtocolEnabled=true` configuration.
