### ISSUE TITLE
[Bug] broker healthcheck ran into loop after decommissioned a cluster of bookies

### ISSUE THREAD

**Issue by wallacepeng** [apache/pulsar#22559]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

puslar 2.10.5

### Minimal reproduce step

1. setup two bookkeeper clusters using helm charts 
   bookkeeper and bookkeeper1
2. make bookkeeper as readonly 
3. decommission bookkeeper till zero replica (as we are using kubernetes, scale down one node, autorecovery replicates the ledgers) 
4. restart brokers. 
5. broker ran into loop on health check 

### What did you expect to see?

broker health check should continue to work

### What did you see instead?

broker health check ran into loop 

<img width="1782" alt="image" src="https://github.com/apache/pulsar/assets/894641/2190991f-996f-4445-9f13-dc4c1e329e2c">

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by wallacepeng** [comment]
<img width="1782" alt="image" src="https://github.com/apache/pulsar/assets/894641/f8879642-e3e2-40b1-b063-308e957e693a">

**Comment by hpvd** [comment]
since 2.10 is not supported anymore, cna you plz check if this also appears in newer versions?
For details see
- supported versions: https://pulsar.apache.org/contribute/release-policy/
- latest pulsar helm chart: https://github.com/apache/pulsar-helm-chart/releases

**Comment by wallacepeng** [comment]
@hpvd we are downgrading the storage so provisioned the bookkeeper cluster. we will upgrade the cluster a bit later. is there any way to clean the healthcheck topic it looks like the ledger cached old bookies ?

**Comment by wallacepeng** [comment]
I finally fixed it . I have to set up another broker cluster, then did some clean up for namespace and managed-ledgers , schemas , then restore the old broker cluster, it fixed the issue .
