### ISSUE TITLE
[Bug] Pulsar concurrent containers has concurrency issues

### ISSUE THREAD

**Issue by dao-jun** [apache/pulsar#22603]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

master branch

### Minimal reproduce step

This issue introduced by https://github.com/apache/pulsar/pull/14497
See: https://github.com/apache/bookkeeper/issues/4318

`ConcurrentLongHashMap`, `ConcurrentLongLongPairHashMap`, `ConcurrentLongPairSet`, `ConcurrentOpenHashMap`, `ConcurrentOpenHashSet` under `org.apache.pulsar.common.util.collections` package are involved.

### What did you expect to see?

NONE

### What did you see instead?

NONE

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by lhotari** [comment]
#18388 is related
