### ISSUE TITLE
Feature of message tracing

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#2280]
Hope pulsar can support feature of message tracing. It very important for any system sensitive to messages.

Support enable or disable message tracing per topic and consumer group.

Client can set the trace info. If client not init set by user client must generate.

Tracing log can be consume for user. can be connect to Elasticsearch by connector. can be query by TraceId.

Point to record tracing
1.produce request
2.produce response
3.fetch request
4.fetch response
5.ack request
6.ack response

**Comment by sijie** [comment]
@codelipenghui : I think this task was partially done by #2476 , are you going to add a tracing interceptor?

**Comment by codelipenghui** [comment]
@sijie Already has a tracing implement base on zipkin in our group, but depends on few private libs, i will rearrange code later.

**Comment by sijie** [comment]
@codelipenghui that would be great!

**Comment by sijie** [comment]
FYI. There is a Skywalking plugin for tracing messages in Pulsar. https://streamnative.io/blog/tech/2019-10-10-use-apache-skywalking-to-trace-apache-pulsar/

**Comment by devinbost** [comment]
Does that plugin allow a message to be traced through functions across namespaces? It looks like it's not quite that sophisticated.

**Comment by sijie** [comment]
@devinbost not. currently the plugin treats Pulsar as a blackbox and only traces messages for producers and consumers. I had a discussion with Skywalking creator about tracing messages flowing through functions. but we haven't done anything yet. If you have any ideas or requirements, feel free to add your thoughts here. We can incorporate your ideas when we start working on the functions tracing.

**Comment by codelipenghui** [comment]
There are several ways to achieve this feature:

1. Integration with OpenTracing https://streamnative.io/blog/tech/2020-06-11-opentracing-instrumentation-for-pulsar
2. Integration with SkyWalking  https://streamnative.io/blog/tech/2019-10-10-use-apache-skywalking-to-trace-apache-pulsar/
3. Leverage on Client interceptor of Pulsar

So close this issue first. Feel free to reopen this issue if needed.
