### ISSUE TITLE
Excessive memory allocation in OTel broker metrics

### ISSUE THREAD

**Issue by asafm** [apache/pulsar#22817]
@dragosvictor @merlimat Please note this contradicts all the work done to eliminate memory allocation. 
The Attributes for each topic should be persisted either in a Map or easier by saving it in the implementation of `Topic` interface you're getting. Then you simply retrieve it by `topic.getTopicOTelAttributes()`.
When you are not doing it, you are creating a memory allocation each time you run collect, for each topic. This is exactly what I was set out to avoid in the whole implementation rework of OpenTelemetry Java SDK memory mode.

_Originally posted by @asafm in https://github.com/apache/pulsar/pull/22467#discussion_r1614798773_

**Comment by asafm** [comment]
@dragosvictor Can you please take a look?
@eolivelli

**Comment by lhotari** [comment]
Fixed by #22837

**Comment by dragosvictor** [comment]
@lhotari Working on the same improvement for the topic stats, can you please reopen this?
