### ISSUE TITLE
[Bug] Offload to S3 triggered manually returns success, while not uploading

### ISSUE THREAD

**Issue by SmnBo** [apache/pulsar#22839]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

Apache Pulsar 3.0.4
Apache Pulsar Helm Chart 3.4.0
Kubernetes v1.27.13

### Minimal reproduce step

Newly installed on Kubernetes using the Helm Chart

Change retention policy:
`curl -vX POST -H 'Content-Type: application/json' http://{ip-address}/admin/v2/namespaces/public/default/retention -d '{"retentionSizeInMB": -1, "retentionTimeInMinutes": -1}'`

Set offload configuration on namespace:
`curl -vX POST  http://{ip-address}/admin/v2/namespaces/public/testing/offloadPolicies -h "Content-Type: application/json" -d '{"s3Driver":true,"managedLedgerOffloadDriver":"S3","offloadersDirectory":"offloaders","s3ManagedLedgerOffloadBucket":"apache-pulsar-offload","s3ManagedLedgerOffloadRegion":"{region}","s3ManagedLedgerOffloadServiceEndpoint":"https://{endpoint}"}'`

Create new topic:
`curl -vX PUT http://{ip-address}/admin/v2/persistent/public/default/test`

Create a new subscription

`curl -vX PUT http://{ip-address}/admin/v2/persistent/public/default/test/subscription/sub`

Write Messages to the topic.

Get ledgerId:

`curl -v http://{ip-address}/admin/v2/persistent/public/default/test/internalStats`

Trigger offload with the following command:

`curl -vX PUT http://{ip-address}/admin/v2/persistent/public/default/test/offload -H 'Content-Type: application/json' -d '{"ledgerId":{ledgerID},"entryId":1,"partitionIndex":-1,"batchIndex":-1,"batchSize":0}'`

Check offload status:
`curl -v http://{ip-address}/admin/v2/persistent/public/default/test/offload`

Answer:
`{"status":"SUCCESS","lastError":"","firstUnoffloadedMessage":{"ledgerId": ledgerID},"entryId":0,"partitionIndex":-1,"batchSize":0,"batchIndex":-1}}`

### What did you expect to see?

Files on the S3-Storage and logs on the brokers describing the course of the operation.

### What did you see instead?

While the answer indicates everything went fine, no files were uploaded to the S3-Storage.

If the logs of two brokers are read the following logs relating the offloading command could be found:
[broker-0.log](https://github.com/user-attachments/files/15556355/broker-0.log)
Broker 2 is the broker responsible for the test topic and the leader broker.
[broker-2.log](https://github.com/user-attachments/files/15556357/broker-2.log)

### Anything else?

The issue is related to this [slack thread](https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1717147743244009).

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by dao-jun** [comment]
![image](https://github.com/apache/pulsar/assets/21362791/8a42d888-93f5-47a3-b60e-a7c57067f974)
The topic has [6, 8, 10, 13] ledgers, and the input position is 6:0

The parameter `messageId` passed to `http://{ip-address}/admin/v2/persistent/public/default/test/offload` is the offload end position, the start position is the first entry of the first ledger. Say, there is [1, 2, 3] ledgers in the topic, `messageId = 3:0`, it will offload [1, 2].

Back to your question, your `messageId` param is wrong. If you want to offload [6, 8], the input param should be 10:0.

**Comment by SmnBo** [comment]
Thank you! That solved my problem!
