### ISSUE TITLE
High GC pause cases high publish latency

### ISSUE THREAD

**Issue by shibd** [apache/pulsar#22866]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

We have observed that using Individual ack frequently results in young generation GC and relatively high GC pauses.

<img width="668" alt="image" src="https://github.com/apache/pulsar/assets/33416836/0a2634a4-39f0-4d4d-b3a1-5e952173f321">

- Resource: k8s cluster
  - broker(1.5CPU)(3CPU 8Gi)
  - bookie(2.5CPU 8Gi) 250Gi gp3 ssd
  - zookeeper(1CPU 4Gi)
- Version: 3.2.2

Performance cmd:
```
bin/pulsar-perf consume test-c 1200 -n 10 -st Shared -t 10
bin/pulsar-perf produce test-p -s 100 -time 1200 -n 10 -t 10 -ml 256M
```

### Solution

The issue should be caused by the large long[] allocated by bitmap. The allocation invoking chain.

<img width="1797" alt="image" src="https://github.com/apache/pulsar/assets/33416836/6d559f3d-e0fa-4725-85ae-21a8bd9083f5">

<img width="1702" alt="image" src="https://github.com/apache/pulsar/assets/33416836/18bda1be-6dd0-4e6f-bfc3-6d17b7b60c8d">

Maybe this is a normal phenomenon and can be solved by increasing the CPU, I would like to share it here to see if there are any similar problems and suggestions in the community.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
Btw. The metric might be wrong. It's not necessarily pause time, but GC time that happens in the background.

**Comment by mattisonchao** [comment]
>Btw. The metric might be wrong. It's not necessarily pause time, but GC time that happens in the background. See https://github.com/apache/pulsar/pull/18891


I think so. But we might need to improve here to avoid allocating a very large `long[]` to give GC pressure. :)

**Comment by lhotari** [comment]
> I think so. But we might need to improve here to avoid allocating a very large `long[]` to give GC pressure. :)


One alternative would be to switch to use https://github.com/lemire/RoaringBitmap/ .
