### ISSUE TITLE
[Bug] [docs] Pulsar 3.3 javadoc is in Chinese

### ISSUE THREAD

**Issue by dlg99** [apache/pulsar#22887]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

3.3

### Minimal reproduce step

open https://pulsar.apache.org/api/client/3.3.x/org/apache/pulsar/client/api/MessageRouter
as linked at https://pulsar.apache.org/docs/3.3.x/concepts-messaging/#routing-modes

### What did you expect to see?

English docs

### What did you see instead?

Chinese docs

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by coderzc** [comment]
This issue been fixed by https://github.com/apache/pulsar-site/pull/912
