### ISSUE TITLE
As a websocket consumer I need to set InitialSubscriptionPosition to earliest

### ISSUE THREAD

**Issue by moinessim** [apache/pulsar#22969]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

As a websocket client, I need to subscribe to a persistent topic that has existing messages.
I need to consume all messages, starting from the first (earliest) one, and keep consuming messages as they become available.
Persistent subscription cursor is needed, hence the use of consumer api.

There is no parameter available for this setting shown in the [documentation](https://pulsar.apache.org/docs/3.3.x/client-libraries-websocket/#query-param-1), or in the [code](https://github.com/apache/pulsar/blob/master/pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ConsumerHandler.java#L133) that creates the subscription.

There is a similar setting [messageId](https://pulsar.apache.org/docs/3.3.x/client-libraries-websocket/#query-param-2) for the Reader endpoint.
But not for the Consumer endpoint.

### Solution

Receive a new url parameter "initialSubscriptionPosition", and add the value to the [consumer builder](https://github.com/apache/pulsar/blob/master/pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ConsumerHandler.java#L133) using the corresponding java api method.

### Alternatives

Use the Reader endpoint: I would really prefer Pulsar to handle the cursor, instead of having to manage that state.

### Anything else?

I would be open to implement this myself, if needed.

Thank you very much for your contributions!

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by lhotari** [comment]
Makes sense to add support for initialSubscriptionPosition
