### ISSUE TITLE
[Security] 3.3.0 has several fixable security vulnerabilities.

### ISSUE THREAD

**Issue by adrian-tarau** [apache/pulsar#23083]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

3.3.0

### Minimal reproduce step

A security scanner will reveal several issues.

### What did you expect to see?

Ideally, no security issues are reported against Pulsal (Uber Jar), or at least nothing Critical or High.

### What did you see instead?

Several Major issues were reported.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by lhotari** [comment]
I'm about to start the release process for Apache Pulsar 3.3.1, so all already fixed issues will be addressed with this release.

A lot of security vulnerability scanner alerts are false positives or don't apply to Apache Pulsar. It would be useful to mention what scanner you are using and what your requirements are ("Several Major issues were reported." isn't addressable).

Apache Pulsar is maintained by volunteers. Active contributions to Apache Pulsar are more than welcome for this type of issues.  Releases are typically made every 1-2 months [for actively supported versions](https://pulsar.apache.org/contribute/release-policy/#supported-versions). 

If you need quicker response to security vulnerabilities, I'd recommend subscribing to a commercial distribution of Apache Pulsar (I work for StreamNative which offers such services).

**Comment by dave2wave** [comment]
Contributions are welcome. Please submit separate PRs for each dependency. Sometimes a dependency update requires extra work depending on changes that may have occurred which may be unrelated to their security fix. (I work for DataStax which also offers such services.)

**Comment by adrian-tarau** [comment]
Indeed, I was looking for #22819 and #22826. I will validate, thanks.

**Comment by adrian-tarau** [comment]
It looks like JARs are not deployed in Maven Central (with rc1 or something similar), so I will have to wait for the official release. However, the POM changes look good; thanks.

**Comment by lhotari** [comment]
> It looks like JARs are not deployed in Maven Central (with rc1 or something similar), so I will have to wait for the official release. However, the POM changes look good; thanks.

The [release vote email](https://lists.apache.org/thread/6o1d37jx8ztcs54d8x120gl4491n4502) contains the URL of the staging repository, it's https://repository.apache.org/content/repositories/orgapachepulsar-1304/ for 3.3.1 release candidate 1. The version is already 3.3.1 in the jars since the staging repository will be published as 3.3.1 version if the release vote passes.

**Comment by lhotari** [comment]
3.3.1 has been released. Closing this issue.
