### ISSUE TITLE
Encryption performance improvement on Java client

### ISSUE THREAD

**Issue by ocadaruma** [apache/pulsar#23121]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

We found that using [encryption](https://pulsar.apache.org/docs/3.3.x/security-encryption/) will add significant performance overhead and could be the bottleneck especially in high-throughput production/consumption.

[The micro benchmark](https://github.com/ocadaruma/pulsar/blob/bc-bench/microbench/src/main/java/org/apache/pulsar/client/impl/crypto/MessageCryptoBcBenchmark.java#L92-L104) shows that `MessageCryptoBc#encrypt` throughput is only around 2k ops/s in below setting:

## Setting
- Pulsar version: 3.4.0-SNAPSHOT (commit: https://github.com/apache/pulsar/commit/f3c177e2243e26a7849feb91dbed9fec4c5723c0)
- JDK version: Temurin JDK21.0.4 x86_64
- CPU: Xeon Silver 4210 2.20GHz
- Payload size: 32KB

## Benchmark result
```
Benchmark                                Mode  Cnt      Score     Error  Units
MessageCryptoBcBenchmark.encryptBc      thrpt   10   1972.095 ±  72.436  ops/s
```

### Solution

`MessageCryptoBc` uses `AES-GCM` for the data encryption.

Hotspot JVM has intrinsics to [use hardware AES instruction](https://bugs.openjdk.org/browse/JDK-7184394) from JDK8 and upwards for SunJCE security provider.
By switching `AES-GCM` cipher to use SunJCE provider instead of BouncyCastle provider, the throughput is improved by x23.

## Benchmark result
```
Benchmark                                Mode  Cnt      Score     Error  Units
MessageCryptoBcBenchmark.encryptBc      thrpt   10   1972.095 ±  72.436  ops/s
MessageCryptoBcBenchmark.encryptSunJCE  thrpt   10  46490.933 ± 762.167  ops/s
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by hpvd** [comment]
awsome finding. Do you also have a direct comparison of "no encryption" vs SunJCE provider?

**Comment by ocadaruma** [comment]
@hpvd below is the pulsar-perf result on standalone pulsar.
```
# No encryption
% bin/pulsar-perf produce persistent://public/default/test-topic -r 2147483647 -time 10
...
Aggregated throughput stats --- 2590389 records sent --- 128708.152 msg/s --- 1005.532 Mbit/s

# Encryption with SunJCE
% bin/pulsar-perf produce persistent://public/default/test-topic -r 2147483647 -time 10 -k test-key -v $PWD/test_ecdsa_pubkey.pem
...
Aggregated throughput stats --- 2368008 records sent --- 117528.344 msg/s --- 918.190 Mbit/s

# Encryption with BouncyCastle
% bin/pulsar-perf produce persistent://public/default/test-topic -r 2147483647 -time 10 -k test-key -v $PWD/test_ecdsa_pubkey.pem
...
Aggregated throughput stats --- 410815 records sent --- 20478.432 msg/s --- 159.988 Mbit/s
```

**Comment by hpvd** [comment]
@ocadaruma many thanks - this looks great! Are there other places in pulsar where this could be relevant?

**Comment by ocadaruma** [comment]
@hpvd decryption performance on consumer-side will be also improved

**Comment by lhotari** [comment]
> [@hpvd](https://github.com/hpvd) decryption performance on consumer-side will be also improved

@ocadaruma This PR contains some improvements to consumer-side decryption performance: #25400. This impacts the case when there are multiple producers and multiple public keys used in the producers. Currently the decryption is very poor in this type of real-world scenario. If the decryption fails, it will retry with the next key that succeeds. CPU will be unnecessarily spent in these attempts. In the Java client implementation, the producer will use the same key for 4 hours before rotating the key. That's why it's useful to cache the decrypted key by producer name.
