### ISSUE TITLE
[Enhancement] Improve error message when sending message to non-existent namespaces

### ISSUE THREAD

**Issue by IPLCGAD** [apache/pulsar#23406]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

Ubuntu 22.04 + JDK17 + Broker version: 3.2.2

### Minimal reproduce step

Send a message to a namespace that does not exist.

### What did you expect to see?

I expected to see a message that the namespace does not exist.

### What did you see instead?

These error logs come from broker:
```
WARN org.apache.pulsar.broker.service.ServerCnx - OriginalRole [...] is not authorized to perform operation [...] on topic [...]
WARN org.apache.pulsar.broker.service.ServerCnx - Client is not authorized to Get Partition Metadata with role [...] on topic [...]
```
Even though messages to other namespaces were being sent out successfully - no authentication problems.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
I don't think that there's a fix for this issue. Due to security reasons, it cannot be exposed to the client that the namespace doesn't exist. There could be a separate feature to allow this so it's possible to change this but this is not a bug, it's currently intentional behavior.

**Comment by IPLCGAD** [comment]
Well, we've just spent a couple of hours barking up the wrong tree, but I see your point.
