### ISSUE TITLE
[Bug] protobuf-java should be an optional dependency for Pulsar Java client libraries

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#23469]
> IMO, making protobuf-java optional is beyond the scope of this PR. It’s something worth discussing separately at a later stage.

It was always meant to be optional. It's already optional in the unshaded module. It was included as required dependency by mistake and this is why it's getting included in the shaded jar. 

It don't think it's beyond the scope to fix the root cause of the issue.

_Originally posted by @merlimat in https://github.com/apache/pulsar/pull/23468#discussion_r1803518970_

**Comment by Shawyeok** [comment]
@lhotari 
I'm working on this issue, please assign this to me.

**Comment by nodece** [comment]
@lhotari @Shawyeok Today, I'm testing the Pulsar 3.0.x, I notice this changes break my test:
```
java.lang.NoClassDefFoundError: com/google/protobuf/MapFieldReflectionAccessor
        at org.apache.pulsar.functions.utils.FunctionConfigUtils.convert(FunctionConfigUtils.java:102)
        at org.apache.pulsar.functions.utils.FunctionConfigUtils.convert(FunctionConfigUtils.java:89)
        at org.apache.pulsar.functions.utils.FunctionConfigUtils.convert(FunctionConfigUtils.java:77)

java.lang.NoClassDefFoundError: com/google/protobuf/MapFieldReflectionAccessor
        at org.apache.pulsar.functions.utils.SourceConfigUtils.convert(SourceConfigUtils.java:97)
```

Is this expected?

**Comment by Shawyeok** [comment]
> @lhotari @Shawyeok Today, I'm testing the Pulsar 3.0.x, I notice this changes break my test:
> 
> ```
> java.lang.NoClassDefFoundError: com/google/protobuf/MapFieldReflectionAccessor
>         at org.apache.pulsar.functions.utils.FunctionConfigUtils.convert(FunctionConfigUtils.java:102)
>         at org.apache.pulsar.functions.utils.FunctionConfigUtils.convert(FunctionConfigUtils.java:89)
>         at org.apache.pulsar.functions.utils.FunctionConfigUtils.convert(FunctionConfigUtils.java:77)
> 
> java.lang.NoClassDefFoundError: com/google/protobuf/MapFieldReflectionAccessor
>         at org.apache.pulsar.functions.utils.SourceConfigUtils.convert(SourceConfigUtils.java:97)
> ```
> 
> Is this expected?

@nodece 
Does your classpath include the `com.google.protobuf:protobuf-java` JAR? If so, which version is it?  

After #23632, users need to explicitly include the `protobuf-java` dependency.

**Comment by nodece** [comment]
@Shawyeok Thank you! These changes may affect some users.

Right now, The `com.google.protobuf:protobuf-java` dependency has been added to my project, and it works fine.
