### ISSUE TITLE
[Enhancement] Disordered messages within DLQ

### ISSUE THREAD

**Issue by ZhaoGuorui666** [apache/pulsar#23557]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

I wrote a test where the order in which messages are stored in the Dead Letter Queue (DLQ) is inconsistent in the case of a single consumer.
![image](https://github.com/user-attachments/assets/45a2f704-0cb1-4074-aa20-3544f0532d4f)

Is it necessary to maintain order within DLQ?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by c4ff3in3** [comment]
Should this be handled by the consumer? 

From the docs:

> The functionality of a dead letter topic is implemented by consumers. You can decide how to handle the messages in the dead letter topic.

Dead letter topics are designed to handle messages that failed processing. Typically, they aren’t reprocessed in the same transactional flow as normal messages, so maintaining order is less relevant.
