### ISSUE TITLE
[Bug] Pulsar build process seems to require Maven > 3.8.1

### ISSUE THREAD

**Issue by frankjkelly** [apache/pulsar#23559]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

```
$ mvn --version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /usr/local/Cellar/maven/3.8.1/libexec
Java version: 17.0.9, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@17/17.0.9/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "14.2.1", arch: "x86_64", family: "mac"
```

### Minimal reproduce step

On the master branch of Pulsar using Maven 3.8.1 I ran

`$ mvn clean install -DskipTests`

it ran successfully without any errors or failures but the binaries locally (in the `./bin` folder) were not updated to todays date (Nov 4th 2024)

```
$ ls -la ./bin/pulsar-client
-rwxr-xr-x  1 xxx  yyy  1075 Dec  1  2022 ./bin/pulsar-client
$  ls -la ./bin/pulsar
-rwxr-xr-x  1 xxx  yyy  17835 Oct 14 09:55 ./bin/pulsar
```

After I updated to Maven 3.9.9 as per https://pulsar.apache.org/contribute/release-process/#preparation
then the binaries were updated.
If this is accurate then someone needs to update the `enforcer-plugin` here https://github.com/apache/pulsar/blob/570cb443eb220135861abf9e9de34ae65e5cdaaa/pom.xml#L2125-L2127

### What did you expect to see?

Binaries in `./bin` updated

### What did you see instead?

Binaries not updated

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
> it ran successfully without any errors or failures but the binaries locally (in the `./bin` folder) were not updated to todays date (Nov 4th 2024)

When you say that the binaries weren't updated, did this happen in the resulting `.tar.gz` distribution?
The [`bin` directory is part of the source repository files](https://github.com/apache/pulsar/tree/master/bin) so I don't see why maven should update the files at all.

**Comment by frankjkelly** [comment]
> > it ran successfully without any errors or failures but the binaries locally (in the `./bin` folder) were not updated to todays date (Nov 4th 2024)
> 
> When you say that the binaries weren't updated, did this happen in the resulting `.tar.gz` distribution? The [`bin` directory is part of the source repository files](https://github.com/apache/pulsar/tree/master/bin) so I don't see why maven should update the files at all to the source directory.

Sorry the binaries in question are in `./bin` directory.
I looked in the `distribution/server/target` folder and although the `.tar.gz` was there the binaries were also not in that gzipped archive file.
Once I updated `mvn` they were then in both locations `./bin` and distribution/server/target` (in the archive)

**Comment by frankjkelly** [comment]
FYI I'm sanity check my report to make sure this is easily reproducible.

**Comment by frankjkelly** [comment]
Very possible that I don't really understand how to recreate the binaries in `./bin`
Using the `mvn` 3.9.9
```
mvn --version
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /Users/fkelly/.sdkman/candidates/maven/3.9.9
Java version: 17.0.9, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@17/17.0.9/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "14.2.1", arch: "x86_64", family: "mac"
```

I deleted `./bin/pulsar` and `./bin/pulsar-client` and then ran

```
$ mvn -q clean install -Dmaven.test.skip=true -Dspotbugs.skip=true -Dlicense.skip=true
```

but the binaries were not created and (probably related) they weren't in the `tar` file either
```
$ tar -tvf apache-pulsar-4.1.0-SNAPSHOT-bin.tar | grep "/bin/pulsar-client"
$
```

**Comment by frankjkelly** [comment]
Yeah so clearly I was not understanding that the files in `./bin` directory were not binaries but scripts and so not generated. Sorry!
