### ISSUE TITLE
[Bug] deadLetterPolicy attribute in the ConsumerConfigurationData class marked as transient

### ISSUE THREAD

**Issue by AnuragReddy2000** [apache/pulsar#23704]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

All Java clients of version v2.8.0 and above

### Minimal reproduce step

Create an instance of `ConsumerConfigurationData` class and set a `deadLetterPolicy` on it. Serialize it and de-serialize it back to get a new instance of the same. The `deadLetterPolicy` previously set will not be present after deserialization.

### What did you expect to see?

Ideally the `deadLetterPolicy` should have been preserved through serialization-deserialization.

### What did you see instead?

null

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by lhotari** [comment]
btw. It would be useful context to explain the issue that you ran into with pulsar-storm. That seems to require serialization support?

**Comment by lhotari** [comment]
Please also explain the context around #9630 which you explained in the GitHub Discussions question.

**Comment by AnuragReddy2000** [comment]
> btw. It would be useful context to explain the issue that you ran into with pulsar-storm. That seems to require serialization support?

Sure. 

We use pulsar-storm adaptor to consume messages in Storm topologies. In a Storm cluster, there is a leader Nimbus node (analogous to a master / controller node) which controls the lifecycle of any topology. 

Whenever a new instance of a topology needs to be created, the topology initialization code executes on the Nimbus. Once the topology components are all initialized, the Nimbus serializes them and sends them to the worker nodes, where the execution continues.

Now the `PulsarSpout` provided by the pulsar-storm adaptor is one such topology component that gets initialized on the Nimbus and later gets transferred to some workers. The `deadLetterPolicy` is one of the many configurations that we provide during the initialization of the `PulsarSpout`. But due to it being marked transient, the resultant instances of the configuration object on the workers do not contain any deadLetterPolicy.
