### ISSUE TITLE
[Doc] Running pulsar using docker compose as documented fails--“Unmatched arguments from index 0”

### ISSUE THREAD

**Issue by yingh0ng** [apache/pulsar#23722]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### problem
Follow the steps in this [https://pulsar.apache.org/docs/4.0.x/getting-started-docker-compose/](url) to start pulsar, and then report an error

![image](https://github.com/user-attachments/assets/6e8339ee-814c-4941-bd25-866eb96d0a84)

### env
system: Debian on wsl
Docker version: 25.03

### reason
The format of the command operation of pulsar-init is wrong and the newline characters cannot be converted correctly.
![image](https://github.com/user-attachments/assets/ffa90d97-56ce-49a4-82ab-dc4080c8f3bb)

### How i fixed
Use Json array on command operation.
![image](https://github.com/user-attachments/assets/d3dd8ed0-b392-4306-a4c6-e48b0afc0af6)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by nodece** [comment]
I submitted https://github.com/apache/pulsar-site/pull/979 to fix this issue.

**Comment by yingh0ng** [comment]
> I submitted [apache/pulsar-site#979](https://github.com/apache/pulsar-site/pull/979) to fix this issue.

It looks good. I'll close this issue.
