### ISSUE TITLE
[Bug] pulsar-client-original 4.0.1 is not debuggable

### ISSUE THREAD

**Issue by Shawyeok** [apache/pulsar#23728]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

4.0.1

### Minimal reproduce step

1. open https://github.com/Shawyeok/348-pulsar-client.git with IDEA
2. add breakpoint for `org/apache/pulsar/client/impl/ConsumerBase.java:864`
3. run `ConsumerInterceptorDemo` with debugger, you'll notice there is a gray cross mark indicate `No executable code found at line 864 in class org.apache.pulsar.client.impl.ConsumerBase`

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/628b9177-6efc-4cce-944f-589ac0a9fff7" />

### What did you expect to see?

`pulsar-client` is a shade jar which is very hard to debug with, `pulsar-client-original` should be debug normally in the IDEA.

### What did you see instead?

`No executable code found at line 864 in class org.apache.pulsar.client.impl.ConsumerBase`

### Anything else?

Here is the output of `javap -l -v -p -c org.apache.pulsar.client.impl.ConsumerBase` for `ConsumerBase#beforeConsume` method in [pulsar-client-original-4.0.1.jar](https://repo1.maven.org/maven2/org/apache/pulsar/pulsar-client-original/4.0.1/)
```
  protected org.apache.pulsar.client.api.Message<T> beforeConsume(org.apache.pulsar.client.api.Message<T>);
    descriptor: (Lorg/apache/pulsar/client/api/Message;)Lorg/apache/pulsar/client/api/Message;
    flags: ACC_PROTECTED
    Code:
      stack=3, locals=2, args_size=2
         0: aload_0
         1: getfield      #158                // Field interceptors:Lorg/apache/pulsar/client/impl/ConsumerInterceptors;
         4: ifnull        17
         7: aload_0
         8: getfield      #158                // Field interceptors:Lorg/apache/pulsar/client/impl/ConsumerInterceptors;
        11: aload_0
        12: aload_1
        13: invokevirtual #763                // Method org/apache/pulsar/client/impl/ConsumerInterceptors.beforeConsume:(Lorg/apache/pulsar/client/api/Consumer;Lorg/apache/pulsar/client/api/Message;)Lorg/apache/pulsar/client/api/Message;
        16: areturn
        17: aload_1
        18: areturn
      LineNumberTable:
        line 862: 0
        line 863: 7
        line 865: 17
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      19     0  this   Lorg/apache/pulsar/client/impl/ConsumerBase;
            0      19     1 message   Lorg/apache/pulsar/client/api/Message;
      LocalVariableTypeTable:
        Start  Length  Slot  Name   Signature
            0      19     0  this   Lorg/apache/pulsar/client/impl/ConsumerBase<TT;>;
            0      19     1 message   Lorg/apache/pulsar/client/api/Message<TT;>;
      StackMapTable: number_of_entries = 1
        frame_type = 17 /* same */
    MethodParameters:
      Name                           Flags
      message
    Signature: #1333                        // (Lorg/apache/pulsar/client/api/Message<TT;>;)Lorg/apache/pulsar/client/api/Message<TT;>;
```

below lines should be highlighted, there is one line missing from the bytecode.
```
      LineNumberTable:
        line 862: 0
        line 863: 7
        line 865: 17
```

https://github.com/apache/pulsar/blob/3ea527bf6b720dcfe074c4476257cce96ebc068a/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java#L862-L868

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Shawyeok** [comment]
Change `pulsar-client` version to `3.0.8`, debug normally with IDEA.

**Comment by lhotari** [comment]
@Shawyeok The example in https://github.com/Shawyeok/348-pulsar-client/blob/main/pom.xml contains a problem. With Spring Boot, you need to set the Pulsar version with `pulsar.version` property instead of using pulsar-bom. 
This has been updated to the Pulsar docs quite recently: https://pulsar.apache.org/docs/4.0.x/client-libraries-java-setup/#pulsar-bom-maven . There's a separate section for Spring Boot: https://pulsar.apache.org/docs/4.0.x/client-libraries-java-setup/#spring-boot

**Comment by lhotari** [comment]
> Thanks for sharing this tips, I've changed the example.
> 
> Btw, any insights on this? This issue could be critical, as debugging with `pulsar-client` nearly impossible. If users cannot debug using the `pulsar-client-original` module, they are forced to debug with the Pulsar source code. This adds significant inconvenience, such as the Pulsar source code potentially lacking the dependencies that their application requires.

@Shawyeok Please test if you can reproduce with the `pulsar.version` property properly set to `4.0.1`. The reason why that was relevant is that Spring Boot would pull in a different version than expected and that could result in the debugging issue since the Pulsar library would be the version whichever is Spring Boot's default. That issue is resolved by setting `pulsar.version` property.

**Comment by Shawyeok** [comment]
> Please test if you can reproduce with the pulsar.version property properly set to 4.0.1. The reason why that was relevant is that Spring Boot would pull in a different version than expected and that could result in the debugging issue since the Pulsar library would be the version whichever is Spring Boot's default. That issue is resolved by setting pulsar.version property.

The [original example](https://github.com/Shawyeok/348-pulsar-client/commit/11731ab9ed307573869388460d437492d9668766) does pull the correct Pulsar version, as confirmed by the jar name with version displayed on the bottom-left of the screenshot (also verified using `mvn dependency:tree`).

The real cause was that the `pulsar-client-original-4.0.1.jar` in my local Maven repository was installed during the Pulsar release verification process (built from the `4.0.1-candidate-1` source), while the `pulsar-client-original-4.0.1-sources.jar` was downloaded separately by IntelliJ IDEA from the Maven repository. These two jars were mismatched, which is expected in such cases. I discovered this by reproducing the issue on another computer.

Thanks for help, I'm going to close this one.
