### ISSUE TITLE
[Bug] getPartitionedTopicMetadata does not work

### ISSUE THREAD

**Issue by dmonopoly** [apache/pulsar#23741]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

Pulsar v3.3.1.8
Mac OS
Java 
openjdk 11.0.22 2024-01-16 LTS
OpenJDK Runtime Environment Corretto-11.0.22.7.1 (build 11.0.22+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.22.7.1 (build 11.0.22+7-LTS, mixed mode)

### Minimal reproduce step

https://stackoverflow.com/questions/79279743/getting-number-of-partitions-of-a-pulsar-topic-could-not-be-parsed-into-a-prope

### What did you expect to see?

Returns partitions count.

### What did you see instead?

Exception in thread "main" org.apache.pulsar.client.admin.PulsarAdminException: java.lang.IllegalArgumentException: pulsar+ssl://mypath.com:1234/admin/v2/persistent/abc/def/myplacev1/partitions could not be parsed into a proper Uri, missing scheme

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by nodece** [comment]
Please use the correct URL.
- Pulsar Admin: `http://mypath.com:1234`. Default to `http://localhost:8080` if you run the pulsar locally.
- Pulsar Client: `http://mypath.com:1234` or `pulsar://mypath.com:6650`. Default to `pulsar://localhost:6650` if you run the pulsar locally.

**Comment by dmonopoly** [comment]
By URL you mean the service URL? Service url we normally use is pulsar+ssl://pc-123abce.ci-abc1.pulsar.mycompany.com:6651 to connect successfully - how would I get the right pulsar admin url from this?

The way the lookup happens is
```
val admin: PulsarAdmin =
                PulsarAdmin
                    .builder()
                    .authentication(authParams)
                    .serviceHttpUrl(serviceUrl)
                    .tlsTrustCertsFilePath(tlsTrustCertsFilePath)
                    .allowTlsInsecureConnection(tlsAllowInsecureConnection)
                    .build()
            
// Error here: can't get number of partitions
println(admin.topics().getPartitionedTopicMetadata(inputTopic))
```

**Comment by nodece** [comment]
It looks you are using the TLS, so I guess the URL is `https://pc-123abce.ci-abc1.pulsar.mycompany.com:8081`.

**Comment by BewareMyPower** [comment]
Generally you can check the port from `webServicePort` config or `webServicePortTls` config if TLS is enabled. The `advertisedAddress` is the hostname.

For example:

```properties
webServicePort=8080
advertisedAddress=myhost
```

then you can use `http://myhost:8080` as the URL for admin APIs.

```properties
webServicePortTls=8081
advertisedAddress=myhost
````

then you can use `https://myhost:8081` as the URL for admin APIs.

**Comment by dmonopoly** [comment]
Where are these configuration files that have the webServicePort config or webServicePortTls config? I see that they can be on my local pulsar install in conf/client.conf, but I would have expected to have these configs somewhere that can be looked up from where the pulsar jobs are typically deployed; StreamNative?

**Comment by visxu** [comment]
> Where are these configuration files that have the webServicePort config or webServicePortTls config? I see that they can be on my local pulsar install in conf/client.conf, but I would have expected to have these configs somewhere that can be looked up from where the pulsar jobs are typically deployed; StreamNative?

You can find these configs in `conf/broker.conf`.
```shell
visxu➜~/pulsar-cluster-3.0.6» grep "webServicePort" pulsar-1/conf/broker.conf                                                                                                                                         [11:22:13]
webServicePort=18080
webServicePortTls=18443
```

**Comment by dmonopoly** [comment]
Ended up side-stepping this issue after seeing the pulsar-flink connector code and finding PulsarClientImpl has a getNumberOfPartitions(topic) which worked.

`(client as PulsarClientImpl).getNumberOfPartitions(topic).get()`
