### ISSUE TITLE
Support for delayed message delivery

### ISSUE THREAD

**Issue by kesavkolla** [apache/pulsar#2375]
Scheduled and delayed message delivery is a good feature to support in pulsar.  Basically individual message can have a header which will be set by publisher and based on the header value the broker should hold message in queue.  Upon the interval is over message should be delivered to subscribers

**Comment by codelipenghui** [comment]
Is any idea to implement this feature?  I'm interest to join the discussion of design and contribute for this feature.

**Comment by skyrocknroll** [comment]
This is an excellent feature we heavily depend on the current messaging system.

**Comment by pouledodue** [comment]
I so wait for this

**Comment by codelipenghui** [comment]
@pmwqld 

> We would like to use such a feature to implement an AUTO Dead Letter Queue (DLQ). Any messages that cannot be processed from the main topic can be sent to the AUTO DLQ topic and only become "visible" after a particular time depending on the retry and backoff algorithm.

I think if all messages with the same delay time in the topic, use Dead Letter Queue can match this scene. otherwise the dispatcher logic in broker and limited by the receive queue will affect the delay result.

**Comment by codelipenghui** [comment]
Delayed message redelivery feature based on expose redelivery count to client. #3030

**Comment by Ah39** [comment]
mark ,the feature have finished ??

**Comment by codelipenghui** [comment]
@Ah39 PR #3033

**Comment by sijie** [comment]
@Ah39 it is not completed yet. there is an ongoing PIP for it.

**Comment by skyrocknroll** [comment]
Getdelivery count does not cover all the use cases. We are pushing the logic to determine whether the delay has expired to the client(Implementing this in all the client languages will be repetitive & some language clients may not even get this feature implemented).  If the broker sends the message to the client after the expiry of the delay then it would be simple and straightforward to remember.

**Comment by skyrocknroll** [comment]
@sijie is there any link to the PIP definition to share?

**Comment by sijie** [comment]
@skyrocknroll : https://lists.apache.org/thread.html/977a8042581819769809f298bd2a2e9fd6b78598792c98069eb691e5@%3Cdev.pulsar.apache.org%3E this is the discussion thread.

**Comment by skyrocknroll** [comment]
Awesome @sijie 👍 💥
