### ISSUE TITLE
[Bug] pulsar v4.0.1 checkStatus interface return 404 error

### ISSUE THREAD

**Issue by Joforde** [apache/pulsar#23778]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

pusar v4.0.1

### Minimal reproduce step

bin/pulsar standalone

curl http://localhost:8080/status.html

### What did you expect to see?

OK

### What did you see instead?

HTTP ERROR 404 Not Found

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by SakaSun** [comment]
Did you solve it?
I'm facing the same issue.

As a workaround I have to:
- disable functions on broker with `functionsWorkerEnabled=false`, restart them.
- unsubscribe the "__compaction" subscription from "persistent://public/functions/metadata"
- reenable the functions with `functionsWorkerEnabled=true` and restart them.

But after a while, the issue comes back again.

**Comment by Joforde** [comment]
Yes, this can currently be resolved through configuration. There is an issue to optimize this: https://github.com/apache/pulsar/issues/23809.

The current solution involves:

Modifying the configuration file to set statusFilePath=/pulsar/data/status.
Creating a file, for example: echo "OK" > /pulsar/data/status.

**Comment by Joforde** [comment]
> Did you solve it? I'm facing the same issue.

@SakaSun Yes, this can currently be resolved through configuration. There is an issue to optimize this: https://github.com/apache/pulsar/issues/23809.

The current solution involves:

Modifying the configuration file to set statusFilePath=/pulsar/data/status.
Creating a file, for example: echo "OK" > /pulsar/data/status.

**Comment by SakaSun** [comment]
Thanks @Joforde for the info.
I'll try to do that.
