### ISSUE TITLE
Document proxy auth data forwarding

### ISSUE THREAD

**Issue by ivankelly** [apache/pulsar#2404]
Added in #1169

Which auth providers does it work for? How does it interact with proxy roles?

Ensure that it is supported in both the binary and http protocols.

Would probably be best if this was picked up by someone who with with Athenz.

**Comment by sijie** [comment]
@rdhabalia @merlimat @maskit since you guys might be more familiar with Athenz, I am wondering if anyone of you can help with task. or even commenting it about how it works :)
