### ISSUE TITLE
Document configuring the proxy without service discovery

### ISSUE THREAD

**Issue by ivankelly** [apache/pulsar#2405]
Feature was added in #1002 

Configuring without service discovery is basically configuring with a broker URL rather than zookeeper. Should mention VIPs and why you would want to do this.

Verify that it works (binary and http protocol, TLS and non-TLS) and add documentation on how to enable in 
http://pulsar.apache.org/docs/en/administration-proxy/

**Comment by sijie** [comment]
This was fixed by #3352
