### ISSUE TITLE
Make sure pulsar configuration files in-sync with the configuration definitions

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#2407]
### Problem

It seems that following settings are missing at `proxy.conf`.

```
brokerServiceURL=pulsar://broker:6650
brokerServiceURLTLS=pulsar+ssl://broker:6651
webServiceURL=http://broker:9101
webServiceURLTLS=https://broker:8443
```

We need to make sure pulsar configuration files are in-sync with the configuration definitions in the code.

**Comment by jiazhai** [comment]
#3169 if for this issue

**Comment by sijie** [comment]
#3169 is just making configuration caught up with current code. However we need a general approach to do so - #3106 #3113 #3117 already added the documentation annotations.
