### ISSUE TITLE
windows server support needed!

### ISSUE THREAD

**Issue by guzuomuse** [apache/pulsar#2461]
for some reason,we must stay windows platform.
 compiling  pulsar-cpp always give errors.
any plan offering support for windows? thanks!

**Comment by sijie** [comment]
@guzuomuse thank you for reporting.  we'd love to support windows, however most of the committers are more familiar with linux/macos. if you can share some of your build errors, we might have some ideas on how to help you better.

**Comment by guzuomuse** [comment]
@sijie ,thanks your reply,here is error log when i compile the c++ client with cmake gui:

`
BUILD_TESTS:  ON
LINK_STATIC:  OFF
USE_LOG4CXX:  OFF
CMAKE_BUILD_TYPE:  
Found ZLIB: F:/en_folder_for_testing/zlib-1.2.11/cmake/Release (found version "1.2.11") 
Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR) 
PYTHON: 3.7.0
DETECTED Python 3
CMake Warning at D:/Program Files/CMake/share/cmake-3.12/Modules/FindBoost.cmake:1723 (message):
  No header defined for python3-mt; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:120 (find_package)


CMake Warning at D:/Program Files/CMake/share/cmake-3.12/Modules/FindBoost.cmake:1723 (message):
  No header defined for python-py37; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:120 (find_package)


CMake Warning at D:/Program Files/CMake/share/cmake-3.12/Modules/FindBoost.cmake:1723 (message):
  No header defined for python37-mt; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:120 (find_package)


Boost version: 1.68.0
Found the following Boost libraries:
  program_options
  filesystem
  regex
  thread
  system
  python37
  chrono
  date_time
  atomic
CMake Error at lib/CMakeLists.txt:42 (set_target_properties):
  set_target_properties called with incorrect number of arguments.


CMake Error at lib/CMakeLists.txt:43 (set_target_properties):
  set_target_properties called with incorrect number of arguments.


CMake Warning (dev) at python/CMakeLists.txt:34 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

Using Boost Python libs: optimized;D:/programs/boost_1_68_0/lib64-msvc-14.1/boost_python37-vc141-mt-x64-1_68.lib;debug;D:/programs/boost_1_68_0/lib64-msvc-14.1/boost_python37-vc141-mt-gd-x64-1_68.lib
clang-tidy not found
clang-format not found
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CURL_LIBRARY_PATH
    linked by target "pulsarStatic" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/lib
    linked by target "pulsarShared" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/lib
    linked by target "perfProducer" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/perf
    linked by target "perfConsumer" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/perf
    linked by target "SampleReaderCApi" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleAsyncProducer" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleConsumerListener" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleConsumer" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleProducer" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleProducerCApi" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleConsumerListenerCApi" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleConsumerCApi" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "main" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/tests
GMOCK_INCLUDE_PATH
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/lib
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/lib
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/perf
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/perf
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/tests
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/python
GMOCK_LIBRARY_PATH
    linked by target "main" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/tests
GTEST_INCLUDE_PATH
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/lib
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/lib
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/perf
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/perf
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/tests
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/python
JSON_INCLUDE_PATH
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/lib
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/lib
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/perf
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/perf
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/tests
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/python
LIB_JSON
    linked by target "pulsarStatic" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/lib
    linked by target "pulsarShared" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/lib
    linked by target "perfProducer" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/perf
    linked by target "perfConsumer" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/perf
    linked by target "SampleReaderCApi" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleAsyncProducer" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleConsumerListener" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleConsumer" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleProducer" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleProducerCApi" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleConsumerListenerCApi" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleConsumerCApi" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "main" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/tests
PROTOBUF_LIBRARIES
    linked by target "pulsarStatic" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/lib
    linked by target "pulsarShared" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/lib
    linked by target "perfProducer" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/perf
    linked by target "perfConsumer" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/perf
    linked by target "SampleReaderCApi" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleAsyncProducer" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleConsumerListener" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleConsumer" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleProducer" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleProducerCApi" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleConsumerListenerCApi" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "SampleConsumerCApi" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
    linked by target "main" in directory F:/en_folder_for_testing/pulsar-client-cpp/source/tests
Protobuf_INCLUDE_DIR (ADVANCED)
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/lib
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/lib
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/perf
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/perf
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/examples
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/tests
   used as include directory in directory F:/en_folder_for_testing/pulsar-client-cpp/source/python

Configuring incomplete, errors occurred!
See also "F:/en_folder_for_testing/pulsar-client-cpp/cmake/CMakeFiles/CMakeOutput.log".
See also "F:/en_folder_for_testing/pulsar-client-cpp/cmake/CMakeFiles/CMakeError.log".
`

**Comment by merlimat** [comment]
@guzuomuse 

You're missing some of the dependencies. For tests, you can disable by passing `-DBUILD_TESTS=OFF` to `cmake`. 

For the rest, you need to install: 
 * Libcurl : https://github.com/curl/curl 
 * JsonCpp : https://github.com/open-source-parsers/jsoncpp
 * Protocol buffer: https://developers.google.com/protocol-buffers/

**Comment by merlimat** [comment]
Anyway, the deps for tests are : 
 * GTest : https://github.com/google/googletest 
 * Google Mock: https://github.com/google/googlemock

**Comment by guzuomuse** [comment]
@merlimat ,thank you very much ,i will try and then give my feedback

**Comment by guzuomuse** [comment]
@merlimat @sijie 
unfortunately. cause too many dependencies drive me crazy.
i will look back.but i have to give up for now.

**Comment by cbornet** [comment]
A conan.io support would make all this much simpler

**Comment by soroshsabz** [comment]
A [vcpkg](https://github.com/Microsoft/vcpkg) support would make all this much simpler :)
