### ISSUE TITLE
HTTP endpoints to consume and produce messages.

### ISSUE THREAD

**Issue by cbornet** [apache/pulsar#2467]
In addition to WebSockets, it would also be nice to be able to consume messages from a simple HTTP streaming endpoint and to publish on a REST API endpoint like is done in [Nakadi](https://nakadi.io/manual.html#/event-types/name/events_get).
HTTP streaming is even more easy and supported in any language/framework than WebSockets and you can use tools such as curl to directly interact with the pulsar cluster (don't even need to install pulsar_client).
You can also document these endpoints in Swagger/OpenAPI.
Supported media-types for the message consumption could be:
* application/stream+json (used by [Spring 5](https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-codecs-streaming))
* `text/event-stream` for [Server Sent Event](https://www.w3.org/TR/eventsource/) clients

**Comment by ruudk** [comment]
:+1: for this. Just tried to produce a single message from PHP and it feels weird to setup an event loop, connect via websockets, wait for it to be connected, then send the message, and wait for a response to come back, and to close the connection. Super verbose in PHP. Sending a simple POST via HTTP would be so much easier.

**Comment by sijie** [comment]
I have raised the PIP for adding HTTP endpoints to existing web server -- https://github.com/apache/pulsar/wiki/PIP-64%3A-Introduce-REST-endpoints-for-producing%2C-consuming-and-reading-messages

**Comment by cbornet** [comment]
@sijie I'm having a look at PIP64.

* For the [subscription endpoint](https://github.com/apache/pulsar/wiki/PIP-64%3A-Introduce-REST-endpoints-for-producing%2C-consuming-and-reading-messages#post-topicsstring-tenant_namestring-namespace_namestring-topic_namesubscriptionstring-subscription), since a subscription can be done on a list of topics, shouldn't this list be passed in the request body and not the path ? The current endpoint allows to subscribe to only one topic.

* The [websocket API](https://pulsar.apache.org/docs/en/client-libraries-websocket/#api-reference) has a lot of parameters to configure the producers/consumers (batching, compression, ...). Should these parameters also be exposed to the REST endpoint ?

**Comment by tisonkun** [comment]
Close as stale. See https://github.com/apache/pulsar/pull/15942#issuecomment-1410768789.

If we have a new proposal to support this functionality, I'd prefer a new issue or discussion.
