### ISSUE TITLE
Function State

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#2489]
This is the master ticket for tracking state related requirements/tasks.

- [ ] Python State Support
- [ ] State lifecycle management (how do we manage the lifecycle of state tables  and how it is related to functions)
- [ ] API for a function to access other state tables or other functions' state
- [ ] AutoSync between a compacted topic and a state table
- [ ] Provide a way to access state table directly without functions

**Comment by srkukarni** [comment]
This is waiting for 4.9 release of bookkeeper

**Comment by ivankelly** [comment]
@srkukarni is the code already in pulsar though?

**Comment by srkukarni** [comment]
No. The prs exists and have been mostly reviewed. They can only be merged once pulsar switches to new bk version

**Comment by pouledodue** [comment]
any news on this? 👍

**Comment by srkukarni** [comment]
2.3.0 added state support for python functions.
also we can access state table directly without functions using just a rest api.
However there is currently no way for a function to access other function's state.
And no autosync between compacted topic and a state table

**Comment by tisonkun** [comment]
Closed as stale.

The development of this initiative seems stalled and this thread doesn't contain too much information. If one wants to revive the proposal, please open a brand new thread.
