### ISSUE TITLE
web rest api

### ISSUE THREAD

**Issue by congbobo184** [apache/pulsar#2520]
The persistent in Rest API connection error。

**Comment by sijie** [comment]
@congbobo184 can you clarify what kind of error are you seeing?

**Comment by congbobo184** [comment]
When you enter the rest api page and click on the interface in the left topic of the persistent topic, then jump to the description of the non-persistent interface

**Comment by sijie** [comment]
@congbobo184 oh I see. that's a bug on loading swagger ui. will investigate how to address the issue.
