### ISSUE TITLE
Wrong zookeeper server names are used in zookeeper helm charts.

### ISSUE THREAD

**Issue by vli02** [apache/pulsar#2522]
#### Expected behavior

By using kubernetes/helm deployment, expect zookeeper to start successfully and the other services can connect to zookeeper correctly.

#### Actual behavior

zookeeper did not config and start successfully:
```
"04:11:45.058 [main] INFO  org.apache.pulsar.zookeeper.ZooKeeperStarter - Starting ZK stats HTTP server at port 8000"
"04:11:45.080 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @1887ms"
"04:11:45.158 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.3.11.v20160721"
"04:11:45.201 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@7ac2e39b{/,null,AVAILABLE}"
"04:11:45.222 [main] INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@1a45193b{HTTP/1.1,[http/1.1]}{0.0.0.0:8000}"
"04:11:45.223 [main] INFO  org.eclipse.jetty.server.Server - Started @2031ms"
"04:11:45.228 [main] INFO  org.apache.zookeeper.server.quorum.QuorumPeerConfig - Reading configuration from: /pulsar/conf/zookeeper.conf"
"04:11:45.230 [main] WARN  org.apache.zookeeper.server.quorum.QuorumPeerConfig - data/zookeeper is relative. Prepend ./ to indicate that you're sure!"
"04:11:45.230 [main] INFO  org.apache.zookeeper.server.quorum.QuorumPeerConfig - clientPortAddress is 0.0.0.0/0.0.0.0:2181"
"04:11:45.230 [main] INFO  org.apache.zookeeper.server.quorum.QuorumPeerConfig - secureClientPort is not set"
"04:11:45.262 [main] ERROR org.apache.zookeeper.server.quorum.QuorumPeerMain - Invalid config, exiting abnormally"
```

#### Steps to reproduce

```
cd deployment/kubernetes/helm
helm package pulsar
<upload chart>
helm install --name pulsar
```

#### System configuration
**Pulsar version**: 2.1 and latest on master

**Comment by vli02** [comment]
The name of zookeeper is deployed as:
```"{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}"```

the use of zookeeper name is:
```{{ printf "%s-%s-%s-%d" $global.Release.Name $global.Chart.Name $global.Values.zookeeper.component $i }}```

They are inconsistent, the template `pulsar.fullname` does not always combine the *release name* and *chart name* together.

I will create a pull request soon.

**Comment by ivankelly** [comment]
@vli02 did you ever create a PR for this?

**Comment by ivankelly** [comment]
Ok, will leave this open and perhaps someone will pick it up at some stage.

**Comment by sijie** [comment]
This change has been fixed in the latest master.
