### ISSUE TITLE
Fail to deploy on Kubernetes cluster

### ISSUE THREAD

**Issue by realwanpengli** [apache/pulsar#2589]
#### Expected behavior
$ alias pulsar-admin='kubectl exec pulsar-admin -it -- bin/pulsar-admin'
$ pulsar-admin properties create prop \
  --admin-roles admin \
  --allowed-clusters us-central

Tell us what should happen
This command will create a property called prop

#### Actual behavior

Tell us what happens instead

Got:

```
Error: Could not find or load main class "
command terminated with exit code 1
```

#### Steps to reproduce

How can we reproduce the issue
Just follow the doc: 
https://pulsar.incubator.apache.org/docs/v2.0.1-incubating/deployment/Kubernetes/#Localcluster-1w5r1b

#### System configuration
**Pulsar version**: 2.0.1

**Comment by srkukarni** [comment]
Did you try with 2.1.0?

**Comment by realwanpengli** [comment]
@srkukarni Yes. I tried. The problem is the same as 2.0.1

**Comment by sijie** [comment]
@realwanpengli I think this is related to #2484 it is fixed and will be released as part of 2.1.1

for a workaround, you can remove this line from the `admin.yml` when you are deploying the admin tool pod.

https://github.com/apache/incubator-pulsar/blob/master/deployment/kubernetes/generic/admin.yaml#L44

**Comment by realwanpengli** [comment]
@sijie But in v2.0.1, the line you mentioned is not existed in pulsar-admin pod.

https://github.com/apache/incubator-pulsar/blob/v2.0.1-incubating/deployment/kubernetes/generic/broker.yaml#L105

**Comment by realwanpengli** [comment]
@sijie Problem solved. Thank you!
