### ISSUE TITLE
Duplicate classes caught by maven-enforcer-plugin

### ISSUE THREAD

**Issue by MarkAddison** [apache/pulsar#2642]
When **maven-enforcer-plugin** is utilised duplicate classes are found for shaded version of Jackson XML classes s e.g. in org.apache.pulsar:pulsar-client:jar and org.apache.pulsar:pulsar-client-schema:jar

Can a modification be made (as a workaround for the present time, these classes have been added for exclusion in *ignoreClasses*)

#### Expected behavior
This is a **maven** build issue.
Tell us what should happen

#### Actual behavior
This is a **maven** build issue.

Tell us what happens instead

#### Steps to reproduce
Use **maven-enforcer-plugin** when building project using maven

How can we reproduce the issue

#### System configuration
**Pulsar version**: x.y
2.1.0-incubating - though probably also expect this affects later versions.

**Comment by jerrypeng** [comment]
@MarkAddison let me look into this

**Comment by jerrypeng** [comment]
The reason this happens if because in Pulsar different modules depend on different version of the same dependencies.  While I think there is a way to fix it, I am not sure how much benefit it will actually bring.  @MarkAddison is this a critical issue for you?

**Comment by MarkAddison** [comment]
It's not ultra critical, as after a little reading it's possible to exclude these classes from detection.

That said I find it perplexing that different versions of the same dependencies would be being utilised!

**Comment by jerrypeng** [comment]
@MarkAddison the multiple version of dependencies has to deal with protobuf 2.0 vs 3.0.  In more recent code we started using protobuf 3.0 because of its integration with GRPC (2.0 does not work very well).  Thus, in some places we are using protobuf 2.0, while in other places we are using 3.0.  Eventually we will probably migrate everything to use protobuf 3 but that hasn't been done yet.

**Comment by tisonkun** [comment]
Closed as stale. Feel free to open a new issue if it's still relevant for maintained versions.
