### ISSUE TITLE
PIP-31: Transactional Streaming

### ISSUE THREAD

**Issue by kuangye098** [apache/pulsar#2664]
This is the master issue for tracking implementing PIP-31: https://docs.google.com/document/d/145VYp09JKTw9jAT-7yNyFU255FptB2_B2Fye100ZXDI/edit#heading=h.40v9f3564x7t

V1: https://github.com/apache/pulsar/issues/8657
V2: https://github.com/apache/pulsar/issues/8633

**Comment by sijie** [comment]
@kuangye098 it is a nice feature request. I am wondering if you are interested in implementing this feature, we can collaborate on this if you are interested in contribution.

> The producer pulls the pre-processing transaction message.

you mean "produce", instead of "pull", right?

**Comment by kuangye098** [comment]
You are right, I may have described it incorrectly.

**Comment by kuangye098** [comment]
@sijie I can try to implement it, because in other projects, I have implemented it.

**Comment by kuangye098** [comment]
@sijie OK，I will read it carefully and then write a PIP to describe the proposal of changes.

**Comment by sijie** [comment]
great thank you @kuangye098

**Comment by ConcurrencyPractitioner** [comment]
@kuangye098 Are you still interested in picking this up? I don't mind if I pick it up.

**Comment by codelipenghui** [comment]
@sijie Is this the same as you mentioned before(Fast Transaction Message)?

**Comment by ConcurrencyPractitioner** [comment]
Hi @sijie  BTW do you know how we create a PIP on Github? For example, do we need permission granted or something first before we create one.

**Comment by ConcurrencyPractitioner** [comment]
Hi @sijie BTW do you know how we create a PIP on Github? For example, do we need permission granted or something first before we create one.

**Comment by sijie** [comment]
@ConcurrencyPractitioner : 

You don't need any permissions to start a PIP, but you do need permissions to post the PIP to Pulsar Github Wiki.
 
So you can just write down a PIP in gist and share it to dev@ mailing list. Any pulsar committer can help you re-post your gist to Pulsar wiki.

**Comment by sijie** [comment]
Here is the PIP for supporting transactions: https://docs.google.com/document/d/145VYp09JKTw9jAT-7yNyFU255FptB2_B2Fye100ZXDI/edit#heading=h.40v9f3564x7t

I will break down this PIP into tasks and update the tasks here. This issue will be used as an anchor for all transaction related tasks.

**Comment by sijie** [comment]
Broke the PIP into tasks and updated them in the description.

**Comment by sijie** [comment]
Marked this as for 2.5.0. since we are close to release 2.4.0 soon.

**Comment by MarvinCai** [comment]
I'm very interesting in this PIP and I could help with some subtasks.

**Comment by sijie** [comment]
@MarvinCai : @tuteng and I start working on the TC part, and @zymap is already working on the TB part. Maybe you can help us in the acknowledgement part. I will try to do the api and protocol and coordinating the work around.

**Comment by sijie** [comment]
Created a separate issue for tracking the remaining tasks at #8633.

The transaction feature will be released as a developer-preview feature as part of 2.7.0.

**Comment by gaoran10** [comment]
# More PRs in Transaction Streaming V1

- [x] transaction buffer
   - [x] transaction buffer refactor https://github.com/apache/pulsar/pull/8347
   - [x] transaction buffer interface adjust https://github.com/apache/pulsar/pull/8291
- [x] transaction message
   - [x] produce batch transaction messages https://github.com/apache/pulsar/pull/8415
   - [x] send tranasction messages to consumer https://github.com/apache/pulsar/pull/8347
- [x] transaction commit
   - [x] commit on topic partition https://github.com/apache/pulsar/pull/7552
   - [x] commit on subscription https://github.com/apache/pulsar/pull/7856
   - [x] abort on topic partition https://github.com/apache/pulsar/pull/7953
   - [x] abort on subscription https://github.com/apache/pulsar/pull/8291
- [x] pending-ack state related
   - [x] pending-ack process https://github.com/apache/pulsar/pull/8426
- [x] cleanup
   - [x] transaction marker clear https://github.com/apache/pulsar/pull/8318
- [x] integration test https://github.com/apache/pulsar/pull/8594

**Comment by codelipenghui** [comment]
Create transaction V1 issue to track the tasks that release at  2.7.0, so move this issue to 2.8.0

**Comment by codelipenghui** [comment]
Close this issue, #8633 is tracking the remaining tasks.
