### ISSUE TITLE
Pass all Apache Project Website Checks

### ISSUE THREAD

**Issue by maskit** [apache/pulsar#2665]
#### Expected behavior

https://whimsy.apache.org/site/project/pulsar
All checks are green.

#### Actual behavior

Some are red.

**Comment by sijie** [comment]
@maskit are you still working on this? I don't think we are able to pass the checks. because the website is now built using React.

**Comment by maskit** [comment]
No, I'm not.

> I don't think we are able to pass the checks. because the website is now built using React.

You mean it's because pages are rendered dynamically with JavaScript and the automated check doesn't find the links even if the pages have them, right? I'd be really surprised if we would not be able to put the links on our website.

I don't think making all the test results green is the real goal. The most important thing is people can access the pages from our website (the dynamically rendered pages have the URLs on there browsers).

Since the expected behavior is "All checks are green", I'm fine with closing this issue with the technical reason above, but I think we are still supposed to provide the links. I'd just edit this issue's goal.

**Comment by sijie** [comment]
> You mean it's because pages are rendered dynamically with JavaScript and the automated check doesn't find the links even if the pages have them, right?

Correct. Currently those links are in a dropdown menu. The dropdown menu only shows up when people clicks it. I am not sure if there are other ways to put the links on our website.

> I don't think making all the test results green is the real goal. The most important thing is people can access the pages from our website (the dynamically rendered pages have the URLs on there browsers).

Agreed. +1 from me. 

> but I think we are still supposed to provide the links.

I think all the links are correctly provided.

**Comment by maskit** [comment]
It seems like the page we have for "^https?://.*apache.org/events/current-event" is the old one.
https://pulsar.apache.org/events/current-event/

I think having "/en/events" for Event page instead of "/events/current-event" is OK, but the two URLs should point to the same page.

**Comment by sijie** [comment]
Closed this issue for now. If we need to work on this, feel free to open a new task.
