### ISSUE TITLE
description mistake in doc

### ISSUE THREAD

**Issue by fenghuasky1991** [apache/pulsar#2672]
#### Expected behavior

In the [Messaging] --> [Subscription modes] --> [Failover] part, the third paragraph
Consumer-C-1 is the master consumer while Consumer-C-2 would be the next in line to receive messages if Consumer-C-1 disconnected.
But the doc says
Consumer-C-1 is the master consumer while Consumer-C-2 would be the next in line to receive messages if Consumer-C-2 disconnected.

#### Actual behavior

It will confuse the readers.

#### Steps to reproduce

Just modify the doc.

#### System configuration
I don't know what the version is. It's just the doc mistake.

**Comment by sijie** [comment]
This has been fixed by #2674
