### ISSUE TITLE
websocket feature parity

### ISSUE THREAD

**Issue by sfescape** [apache/pulsar#2678]
Is there a roadmap that discusses websocket features? It looks like websockets is pretty far behind in feature parity.
I'm considering moving from kafka to pulsar but topics regex consumer is an important feature for me.

**Comment by hpvd** [comment]
feature parity would indeed be pretty awesome and would imho help adoption further

**Comment by hpvd** [comment]
for latest state see: https://github.com/apache/pulsar/wiki/Client-Features-Matrix

**Comment by hpvd** [comment]
imho websocket is for pulsar something like the window to the web world. It enables usage of pulsar for fields like web-tracking,live  chat and many more...
If one see the potential of this community, on should give websocket bugs and features a fair priority in the next releases.
While writing this there are roughly 25 issues regarding websocket topics open.
https://github.com/apache/pulsar/issues?q=is%3Aissue+is%3Aopen+websocket+
3 includes open pull request.

Of course not all fields have the same importance for adoption of pulsar.
But the points
- docs
- security and
- performance
are important for everyone thinking about using pulsar with websocket..
