### ISSUE TITLE
pulsar golang client install failed (on windows)

### ISSUE THREAD

**Issue by templarzq** [apache/pulsar#2680]
![pulsar](https://user-images.githubusercontent.com/18200917/46254590-29e04d80-c4c4-11e8-9fd1-08ca204b9c9a.png)

**Comment by sijie** [comment]
@templarzq pulsar go client is a cgo wrapper over existing cpp client. currently we only provide cpp client for mac and linux. it doesn't support windows yet.

You can check out more details about go client here : http://pulsar.apache.org/docs/en/client-libraries-go/

**Comment by templarzq** [comment]
好的，请问有windows的go client开发计划吗？

**Comment by sijie** [comment]
@templarzq I think we just need to make the c++ client be able to compile on windows. Then you are able to use the go client. However most of the committers don't really use windows here, so it would take a while for us to support windows.
