### ISSUE TITLE
The websocket reader API is not including the specified starting message.

### ISSUE THREAD

**Issue by sfescape** [apache/pulsar#2682]
#### Expected behavior

The websocket reader API should return messages inclusive of the messageId passed in.

#### Actual behavior

The websocket reader API is returning messages exclusive of the messageId passed in.

#### Steps to reproduce

Write a series of message, invoke the reader API passing in the first messageId as the starting message. The first message returned is the second message written.

#### System configuration
**Pulsar version**: 2.1.1 (apachepulsar/pulsar docker image)

**Comment by sfescape** [comment]
Discussed adding inclusive/exclusive option to specific messageId and latest as options.

**Comment by tobgu** [comment]
Having an option like this on a Reader would be enough for me to close #2682.

**Comment by sfescape** [comment]
Is there any update on this feature request? I'll need to add a "marker" message to my writes if this is not coming relatively soon. Right now I just read from the beginning until I see the actual first message... but that is not going to scale at all.

**Comment by hpvd** [comment]
is this related to https://github.com/apache/pulsar/pull/8724 ?

**Comment by tisonkun** [comment]
Closed as stale.

Feel free to open a new issue if it's still relevant to the maintained versions.
