### ISSUE TITLE
Websocket API - Expose ReachedEndOfTopic in Reader/Consumer API

### ISSUE THREAD

**Issue by sfescape** [apache/pulsar#2687]
It would be very helpful if there was an ability to test ReachedEndOfTopic. It's not clear to me when you can stop reading if you're only interested in traversing existing messages for a topic.

**Comment by jerrypeng** [comment]
@sfescape the Reader API does have this functionality:

reader.hasReachedEndOfTopic()

**Comment by sijie** [comment]
@sfescape Currently this feature is not available in websocket. you can check this out for the feature parity between clients: https://github.com/apache/pulsar/wiki/Client-Features-Matrix

**Comment by sfescape** [comment]
Thank you, this feature seems to be "Reader hasMessageAvailable". This project doesn't seem to use JIRA, is there a place I can go look for any roadmap on websocket API features?

**Comment by hpvd** [comment]
nice :-)
with having this, feature matrix shoud be updated: https://github.com/apache/pulsar/wiki/Client-Features-Matrix
