### ISSUE TITLE
Intermittent error in LoadBalancerTest.java

### ISSUE THREAD

**Issue by agarman** [apache/pulsar#269]
#### Expected behavior

```mvn test``` completes successfully in 10-15 minutes.

#### Actual behavior

```
Tests run: 526, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 881.775 sec <<< FAILURE! - in TestSuite
testLoadReportsWrittenOnZK(com.yahoo.pulsar.broker.loadbalance.LoadBalancerTest)  Time elapsed: 0.027 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at com.yahoo.pulsar.broker.loadbalance.LoadBalancerTest.testLoadReportsWrittenOnZK(LoadBalancerTest.java:202)

testResumptionAfterBacklogRelaxed(com.yahoo.pulsar.broker.service.ReplicatorTest)  Time elapsed: 49.376 sec  <<< FAILURE!
com.yahoo.pulsar.client.api.PulsarClientException$TimeoutException: Could not send message to broker within given timeout


Results :

Failed tests: 
  LoadBalancerTest.testLoadReportsWrittenOnZK:202 expected [true] but found [false]
  ReplicatorTest.testResumptionAfterBacklogRelaxed » Timeout Could not send mess...
```

#### Steps to reproduce

Intermittent test failure.

#### System configuration
**Pulsar version**: 17630b9c0386143714a12361d01713f695b4a73c

**Comment by agarman** [comment]
> Tests run: 540, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 863.584 sec <<< FAILURE! - in TestSuite
> testLoadReportsWrittenOnZK(com.yahoo.pulsar.broker.loadbalance.LoadBalancerTest)  Time elapsed: 0.012 sec  <<< FAILURE!
> java.lang.AssertionError: expected [true] but found [false]
> 	at com.yahoo.pulsar.broker.loadbalance.LoadBalancerTest.testLoadReportsWrittenOnZK(LoadBalancerTest.java:202)

Pulsar version: f0fbb4da55d60099af12159f7b7932f9ec4843b3

**Comment by mattisonchao** [comment]
I think this flaky test is Has been fixed.
@lhotari
