### ISSUE TITLE
Provide void java function implementation implementing Consumer Interface

### ISSUE THREAD

**Issue by aahmed-se** [apache/pulsar#2695]
@srkukarni @sijie 

This Example should be using 

https://github.com/apache/pulsar/blob/master/pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/WordCountFunction.java

https://docs.oracle.com/javase/8/docs/api/java/util/function/Consumer.html

**Comment by sijie** [comment]
the discussion is happening at #2698

**Comment by sijie** [comment]
closed the issue as #2698 already concluded that we don't want to implement this feature.
