### ISSUE TITLE
Improve Go/macOS C++ client installation documentation

### ISSUE THREAD

**Issue by grantwwu** [apache/pulsar#2703]
The Go client installation documentation instructs you to install the C++ client as well.  However, it does not note that you need the version to match exactly.

Additionally, the macOS C++ client installation instructions do not provide a way to choose what version you install: https://pulsar.apache.org/docs/en/client-libraries-cpp/#macos

**Comment by merlimat** [comment]
@grantwwu There is a warning at http://pulsar.apache.org/docs/en/client-libraries-go/#note

I think the main issue is that we instruct to get the latest version, eg:

```
$ dep ensure -add github.com/apache/incubator-pulsar/pulsar-client-go/pulsar@v2.1.1-incubating
```

But the MacOS brew recipe is still installing 2.1.0 C++ client. We need to push the brew recipe to homebrew and make sure that gets updated on each release, pointing to new archive.

**Comment by grantwwu** [comment]
I've submitted a PR to improve that warning.  Particularly, it makes it more explicit and puts it up front.  I skipped over that warning because I wasn't using `go get`.

Currently having trouble viewing the changes locally because I can't figure out how to get the local webserver to pickup my changes, discussing in Slack #docs

**Comment by grantwwu** [comment]
> But the MacOS brew recipe is still installing 2.1.0 C++ client. We need to push the brew recipe to homebrew and make sure that gets updated on each release, pointing to new archive.

@merlimat Should I make a new issue for this?
