### ISSUE TITLE
Python messageId serialize is broken

### ISSUE THREAD

**Issue by HaraldGustafsson** [apache/pulsar#2708]
#### Expected behavior
MessageId object serialize method is broken at least in python 3.7 

    pulsar.MessageId.latest.serialize()

Should return a string

#### Actual behavior

    >>> pulsar.MessageId.earliest.serialize()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 1: invalid start byte

#### Steps to reproduce

As above

#### System configuration
pulsar-client 2.1.0 and Python 3.7

**Comment by HaraldGustafsson** [comment]
String function produce a string with the 4 values stringified, but the deserialize function can't understand that. Anyone know a quick workaround until this is fixed?

    >>> str(pulsar.MessageId.latest)
    '(9223372036854775807,9223372036854775807,-1,-1)'

    >>> pulsar.MessageId.deserialize(str(pulsar.MessageId.latest))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/ecshdgn/.virtualenvs/py37_ventri/lib/python3.7/site-packages/pulsar/__init__.py", line 131, in deserialize
        return _pulsar.MessageId.deserialize(message_id_str)
    RuntimeError: unidentifiable C++ exception

**Comment by merlimat** [comment]
I think the might be broken on all python 3.x. With 2.7, the serialize is returning a string with a binary protobuf representation of the message id. Of course that would not be a valid utf-8. 

Doing the `str(pulsar.MessageId.latest)` gives you a human readable version but the de-serialize expects the binary form. 

I cannot think of a quick workaround. The wrapper should be fixed to return it as `bytes` and not `str` type.

**Comment by HaraldGustafsson** [comment]
I wrote a simple protobuf generator based on the MessageId, so that I can serialize them while this is fixed.

    import itertools
    import pulsar
    def pb_varint(value, size):
        value = pow(2,size) + value if value < 0 else value
        s = "{{0:0{}b}}".format(size).format(value)
        b = [int(s[max(0,i-7):i], 2) for i in range(size, 0, -7)]
        b = reversed(list(itertools.dropwhile(lambda x: x == 0, reversed(b))))
        b = list(map(lambda x: x+128, b))
        if not b:
            return b"\x00"
        b[-1] = b[-1] - 128
        return bytes(b)

    def pb_messageid(mid):
        if not isinstance(mid, str):
            mid = str(mid)
        mid = tuple(map(int, mid[1:-1].split(",")))
        b = b""
        for i in range(4):
            b += bytes([(i+1)<<3]) + pb_varint(mid[[0,1,3,2][i]], [64,64,32,32][i])
        return b
