### ISSUE TITLE
Fix various bugs in the Go client doc examples

### ISSUE THREAD

**Issue by grantwwu** [apache/pulsar#2719]
Various parts of the Go client doc examples do not work with the existing API.

For example, https://pulsar.apache.org/docs/en/client-libraries-go/#producers is missing a Context
https://pulsar.apache.org/docs/en/client-libraries-go/#producer-operations more involved example refers to a message ID but the producer does not have that available.

Does anyone know a system that allows typechecking these docs?

I asked around and Rust puts markdown docs in code comments, with embedded code blocks in the markdown.  These get extracted and put into tests.  You can use # to hide boilerplate.

Javascript seems to have https://github.com/eslint/eslint-plugin-markdown

**Comment by sijie** [comment]
@grantwwu are you interested in submitting a PR fixing this?

**Comment by grantwwu** [comment]
Yes, I can fix the immediate bugs.  But I also wanted to solicit thoughts about ways to bring tooling to check these automatically

**Comment by wolfstudy** [comment]
@grantwwu @sijie We can introduce `godoc` in the go client to automatically generate the interface code and related examples we need.

For example: https://godoc.org/github.com/apache/pulsar-client-go

**Comment by wolfstudy** [comment]
But there is a premise, we need to follow the go community related code specifications, I suggest to add the relevant check tool: `gofmt`, `golint`, `goimport` and so on.

**Comment by sijie** [comment]
@wolfstudy any progress on this issue?

**Comment by wolfstudy** [comment]
@grantwwu @sijie According to the go community's processing specification, we should add a `README.md` file to pulsar-client-go and introduce [godoc](https://godoc.org/) to ensure consistency between the document and the interface code. In this way we can completely solve this problem.

**Comment by sijie** [comment]
@wolfstudy can you drive the work to solve the problem?
