### ISSUE TITLE
Add admin command to truncate pulsar topics (partitions)

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#2736]
requirement: set infinite retention on a namespace and then manually truncate the topic.

- truncate the topic by message id
- delete all the messages older than time X

**Comment by foreversunyao** [comment]
@sijie its kinda put an expired tag on one message or lot of message directly?

**Comment by MarvinCai** [comment]
After discussing with @sijie #9514 is not implementing what we want here, we want to able to truncate the topic which is actually delete ledger from BK for given topic. 
Should reopen it.

**Comment by MarvinCai** [comment]
I can work on a solution for it.

**Comment by codelipenghui** [comment]
related to https://github.com/apache/pulsar/issues/9597
