### ISSUE TITLE
Provide example yaml files for pulsar builtin connectors

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#2758]
We should provide example yaml files for pulsar builtin connectors.

**Comment by sijie** [comment]
I think we already have the generator to automatically generate example yaml files from the code. so should just integration the generator as part of website build.

**Comment by Anonymitaet** [comment]
@tuteng as discussed offline, could you please help generate the yaml files automatically?

**Comment by Anonymitaet** [comment]
@tuteng any progress on this issue?

**Comment by tisonkun** [comment]
Closed as stale and vague. Please specify what information is missing on which pages.
