### ISSUE TITLE
support auto.offset.reset on the Pulsar adaptor for Apache Kafka

### ISSUE THREAD

**Issue by macthestack** [apache/pulsar#2792]
auto.offset.reset is currently ignored

**Comment by ivankelly** [comment]
@macthestack could you link some docs on what this option is supposed to do?

**Comment by ConcurrencyPractitioner** [comment]
@skyrocknroll  So are you suggesting that pulsar should allow the user to determine the reset policy for the Kafka consumer?

**Comment by ConcurrencyPractitioner** [comment]
Just a couple of notes in regards to implementation. Looking through Kafka's code for auto.offset.reset, it might require some tweaking with Pulsar's internals as well since it requires knowledge of when an exception occurred for a missing offset and which offset to set it to.

**Comment by MarvinCai** [comment]
I think there's already support for auto.offset.reset , at least earliest and latest are supported, code [reference](https://github.com/apache/pulsar/blob/master/pulsar-client-kafka-compat/pulsar-client-kafka/src/main/java/org/apache/kafka/clients/consumer/PulsarKafkaConsumer.java#L183-L190).

**Comment by sijie** [comment]
This is already supported in latest master.
