### ISSUE TITLE
TLS Hostname verification undefined for C++/python client

### ISSUE THREAD

**Issue by ivankelly** [apache/pulsar#2793]
I've not tested with code, but it looks like TLS hostname verification is a mess for the C++ client (and python by extension).

For binary connections, no hostname verification takes place as far as I can see. For http connections (for lookups) it takes place every time.

I suspect this made it through testing since the tls certs used to test C++ use localhost as the common name. We should expose the ability to add the host verification in the configuration.

**Comment by ivankelly** [comment]
I'm currently adding documentation to security-tls-transport.md for hostname verification, and am stating that it doesn't work for C++. Please update the docs when this is fixed.

**Comment by sijie** [comment]
hostname verification has been added by #1215

**Comment by ivankelly** [comment]
@sijie that change only added the implementation. documentation needs to be updated too.

**Comment by sijie** [comment]
@Jennifer88huang this requires documentation updates.

**Comment by Jennifer88huang** [comment]
Got it.

**Comment by Jennifer88huang** [comment]
hostname verification has been added in #1208

**Comment by Huanli-Meng** [comment]
@ivankelly , the doc is updated, could you please help review it? here is the PR link: https://github.com/apache/pulsar/pull/7162, Thanks.
