### ISSUE TITLE
Documentation error in TLS 

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#2797]
#### Expected behavior

Following the steps described in the documentation should produce a certificate and a private key.

#### Actual behavior

When executing the steps in order, you will get the following error when executing the 

"openssl req -config openssl.cnf -key private/ca.key.pem \
      -new -x509 -days 7300 -sha256 -extensions v3_ca \
      -out certs/ca.cert.pem"
command:

error on line 30 of openssl.cnf
140735608460232:error:0E065068:configuration file routines:STR_COPY:variable has no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.50.2/libressl/crypto/conf/conf_def.c:573:line 30
#### Steps to reproduce

How can we reproduce the issue

Execute the following commands in sequence:

$ mkdir my-ca
$ cd my-ca
$ wget https://github.com/apache/incubator-pulsar/tree/master/site2/website/static/examples/openssl.cnf
$ export CA_HOME=$(pwd)
$ mkdir certs crl newcerts private
$ chmod 700 private/
$ touch index.txt
$ echo 1000 > serial
$ openssl genrsa -aes256 -out private/ca.key.pem 4096
$ chmod 400 private/ca.key.pem
$ openssl req -config openssl.cnf -key private/ca.key.pem \
      -new -x509 -days 7300 -sha256 -extensions v3_ca \
      -out certs/ca.cert.pem

#### System configuration
**Pulsar version**: 2.1.1

**Comment by david-streamlio** [comment]
The associated page is here:  http://pulsar.apache.org/docs/en/security-tls-transport/

**Comment by sijie** [comment]
The documentation has been updated to fetching `openssl.cnf` from github raw content link.
