### ISSUE TITLE
Re-enable PrestoSql test

### ISSUE THREAD

**Issue by srkukarni** [apache/pulsar#2802]
#### Expected behavior

#2752 breaks sql thanks to spaghetti dependencies. This pr will disable the test for now. We need to re-enable it before the next release.
#### Actual behavior

Tell us what happens instead

#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**Pulsar version**: x.y

**Comment by sijie** [comment]
PrestoSQL integration test is renabled already.
