### ISSUE TITLE
pulsar go client static build error

### ISSUE THREAD

**Issue by chowyu08** [apache/pulsar#2842]
#### System configuration
Pulsar version: 2.2.0

dpkg -i apache-pulsar-client*.deb

###build command
go build -ldflags '-extldflags "-static"'

####error
usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libpulsar.a: error adding symbols: Archive has no index; run ranlib to add one
collect2: error: ld returned 1 exit status

**Comment by merlimat** [comment]
@chowyu08 this is a kind of known issue at this point but we have found no fix so far. The libpulsar.a looks ok in the sense that I can link it into a regular C++ binary but not into a Go binary. 

Any hint in how to fix the libpulsar.a linking is welcome. In meantime, the only option is to link dynamically against libpulsar.so

**Comment by sijie** [comment]
removed milestone, since it is a known issue and no fix can be found so far.
