### ISSUE TITLE
What official pulsar helm chart request 15GB memory for bookeeper,zookeeper and broker?

### ISSUE THREAD

**Issue by benjaminhuo** [apache/pulsar#2858]
#### Expected behavior
The memory should be set to a reasonable size
The manifest(bookie.yaml) deploy bookeeper as daemonset, why not statefulset with persistent volume claim?

#### Actual behavior
Official pulsar helm chart request 15GB memory for bookeeper,zookeeper and broker

The manifest(bookie.yaml) deploy bookeeper as daemonset, why not statefulset with persistent volume claim?

![snip20181027_103](https://user-images.githubusercontent.com/18525465/47598862-1cd85080-d9d5-11e8-8201-451d6c377486.png)

![snip20181027_104](https://user-images.githubusercontent.com/18525465/47598863-1cd85080-d9d5-11e8-8728-46d4cb3b6d42.png)

![snip20181027_107](https://user-images.githubusercontent.com/18525465/47598864-1cd85080-d9d5-11e8-89c3-8d8b43343c2b.png)

![snip20181027_108](https://user-images.githubusercontent.com/18525465/47598865-1d70e700-d9d5-11e8-8c26-0f718f609173.png)

#### System configuration
**Pulsar version**: x.y

**Comment by benjaminhuo** [comment]
Thanks for the explanation and suggestion.
I'd like to contribute.

Regards,
Ben

**Comment by benjaminhuo** [comment]
@sijie Another irrelevant question regarding pulsar:
Is the connection to broker per client or per producer?
If I create multiple producers using the same client, there will be multiple connections or just one connection?


PulsarClient client = PulsarClient.builder()
        .serviceUrl("pulsar://localhost:6650")
        .build();
Producer<byte[]> producer = client.newProducer()
        .topic("my-topic")
        .create();

// You can then send messages to the broker and topic you specified:
producer.send("My message".getBytes());

**Comment by sijie** [comment]
@benjaminhuo 

Pulsar is using netty, so the connections will be managed per client.

> If I create multiple producers using the same client, there will be multiple connections or just one connection?

it will be one connection per broker to the brokers that the client will connect to.

**Comment by benjaminhuo** [comment]
Great!
Thanks very much.

Ben

**Comment by sijie** [comment]
Closed this issue since the question was answered
