### ISSUE TITLE
Limit the client reconnect behavior.

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#2876]
## Actual behavior

I got some abnormal metrics in broker stats.

<img width="554" alt="wechatimg101" src="https://user-images.githubusercontent.com/12592133/47623764-115d6480-db50-11e8-90fa-c7c4f31b45d0.png">

When this happened, I checked the network metrics. The network metrics showed network was saturated.

<img width="1279" alt="wechatimg111" src="https://user-images.githubusercontent.com/12592133/47623827-b0825c00-db50-11e8-8573-d45290dd2e43.png">

So, I searched the error log in pulsar cluster, and found some strange logs:

![wechatimg113](https://user-images.githubusercontent.com/12592133/47623893-4ae29f80-db51-11e8-8a85-346644fbbd34.jpeg)

Next, i searched the client logs in kibana:

<img width="1271" alt="wechatimg143" src="https://user-images.githubusercontent.com/12592133/47623928-88dfc380-db51-11e8-8dd4-5661e6d709fe.png">
<img width="895" alt="wechatimg144" src="https://user-images.githubusercontent.com/12592133/47623929-88dfc380-db51-11e8-9490-a30035dface1.png">
<img width="676" alt="wechatimg145" src="https://user-images.githubusercontent.com/12592133/47623930-88dfc380-db51-11e8-9fc4-54ff1f84f349.png">

Regardless the client exception, I am concerned about the client reconnect behavior. I think client reconnect too much and load data from bookie to cause the high network bandwidth usage. And pulsar client exposes updateServiceUrl() to users, it will also trigger reconnect behavior.

So we should add some mechanisms to limit the reconnect to avoid high network bandwidth usage.

**Comment by sijie** [comment]
@codelipenghui are you working on a fix for this?

**Comment by codelipenghui** [comment]
@sijie Yes, i will fix it, We need to decide work on broker or client ?

**Comment by sijie** [comment]
@codelipenghui thank you, what is your thought around? can you describe both approaches and compare pros and cons?

**Comment by codelipenghui** [comment]
I think more secure and unified on broker side, broker already limit the maxConsumersPerTopic and maxConsumersPerSubscription, broker limit the client reconnect(actually limit subscribe) is taken for granted.

If on client side, every client should implement this limiter.

But to identify consumer, on client side is more simple. On broker side, broker can get the consumerId, consumerName, ip address. Is consumerName + consumerId is unique ?

If broker can identify consumer, we just add a subscribe limiter on broker/namespace level. When broker handle subscribe request should check the limiter.

When client got the limit error, client retry again.

Subscribe limiter config in broker.conf. limiter support 2 parameters of resetPeriod and maxSubscribePerConsumer.

On client side, it's necessary to add metrics record the re-connect times.

**Comment by codelipenghui** [comment]
PR #2977

**Comment by sijie** [comment]
This was fixed by #2977
