### ISSUE TITLE
Add integration test for KafkaConnectSource

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#2877]
In PR #2791, @sijie suggested to add an integration test for debezium.
KafkaConnectSource is a little not compatible with current source test framework.
In current existing source test framework, we call produceSourceMessages: Map<String, String> kvs = tester.produceSourceMessages(numMessages) and return expected kvs to verify later, 
But in this KafkaConnectSource, the SourceMessages is created by debezium (convert mysql binlog into KafkaConnectSource), And it seems not easy to save the content as explicit Kvs.
To do this, we may need move some of the methods(such as  `prepareSource` and `validateSourceResult`) from `PulsarFunctionsTest` into `SourceTester` to make the SourceTester do the things more customized. 

This is only an initial thought,  this issue is to track the integration test for KafkaConnectSource

**Comment by sijie** [comment]
@jiazhai any updates on this?

**Comment by jiazhai** [comment]
PR #3154 was for this, and was closed
