### ISSUE TITLE
Expose read and connect timeout in PulsarAdmin

### ISSUE THREAD

**Issue by ivankelly** [apache/pulsar#2891]
When connecting to a pulsar broker endpoint which is not responding, the PulsarAdmin client will hang forever, because this is the default behaviour of the jersey client. We should set the default to something else (60 seconds), and allow the client to tune this down.

**Comment by aahmed-se** [comment]
https://github.com/apache/pulsar/pull/2957

**Comment by aahmed-se** [comment]
Will make it configurable also.

**Comment by sijie** [comment]
This was fixed by #2957
