### ISSUE TITLE
pulsar-perf parameter lack description

### ISSUE THREAD

**Issue by dreamcatchernick** [apache/pulsar#2895]
i am using pulsar-perf to do the performance testing. when i use pulsar-perf produce/consume, it doesn't tell me which parameter is required. And i searched the [document](http://pulsar.apache.org/docs/en/reference-cli-tools.html#pulsar-perf) , it doesn't give me much information. Suggest add "required" flag. 

And also  pulsar-perf produce/consume have the same description in the  [document](http://pulsar.apache.org/docs/en/reference-cli-tools.html#pulsar-perf). Is it a mistake?

**Comment by sijie** [comment]
This was fixed by #3452
