### ISSUE TITLE
pulsar-io/hdfs  Maven compilation failed

### ISSUE THREAD

**Issue by nanguawu** [apache/pulsar#2901]
Version:
https://github.com/apache/pulsar/releases/tag/v2.2.0
HDFS client version:  2.6.0-cdh5.15.0

#cd /opt/soft/tmp/pulsar-2.2.0/pulsar-io/hdfs
#/opt/soft/apache-maven-3.3.9/bin/mvn   install 

[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ pulsar-io-hdfs ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 17 source files to /opt/soft/tmp/pulsar-2.2.0/pulsar-io/hdfs/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /opt/soft/tmp/pulsar-2.2.0/pulsar-io/hdfs/src/main/java/org/apache/pulsar/io/hdfs/SecurityUtil.java:[23,32] package org.apache.commons.lang3 does not exist
[ERROR] /opt/soft/tmp/pulsar-2.2.0/pulsar-io/hdfs/src/main/java/org/apache/pulsar/io/hdfs/sink/HdfsAbstractSink.java:[29,28] cannot find symbol
  symbol:   class FSDataOutputStreamBuilder
  location: package org.apache.hadoop.fs
[ERROR] /opt/soft/tmp/pulsar-2.2.0/pulsar-io/hdfs/src/main/java/org/apache/pulsar/io/hdfs/sink/HdfsAbstractSink.java:[88,21] cannot find symbol
  symbol:   class FSDataOutputStreamBuilder
  location: class org.apache.pulsar.io.hdfs.sink.HdfsAbstractSink<K,V>
[INFO] 3 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

What are the requirements for the hdfs version?

**Comment by nanguawu** [comment]
@sijie   yeah,I manually changed the hdfs client to 2.6.0

**Comment by nanguawu** [comment]
ok thanks a lot.

**Comment by sijie** [comment]
@nanguawu : fyi, @david-streamlio is working on supporting both hdfs 2.x and 3.x. Here is the pr #2966 you can follow the process

**Comment by sijie** [comment]
#2966 is merged and will be released in 2.3.0
