### ISSUE TITLE
Get message by messageId

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#2912]
Is it possible to support a rest api to get message by messageId? For now we can peek the head message but can't query message by messageId.

**Comment by foreversunyao** [comment]
rest api could have bad performance to do this ?

**Comment by codelipenghui** [comment]
@foreversunyao I'm not sure ! Maybe better read from bookie straightforward.

**Comment by sijie** [comment]
I think reading a message by a message-id is the same as peeking messages.
