### ISSUE TITLE
is Authentication available in java client？

### ISSUE THREAD

**Issue by superbaobei** [apache/pulsar#2950]
#### i'm newer for pulsar
today I read pulsar java client in org.apache.pulsar.client.impl.conf.ClientConfigurationData
in class ClientConfigurationData ,there's a field called authentication and type is Authentication.
Authentication is a interface,and I find 5 implements but their‘s start method all empty.no implement in start method ,what i want to know is ,is  authentication feature  can be used now? Maybe I didn't find it, but I really didn't find his implementation.anyone can help me ?thank u

#### System configuration
**Pulsar version**: 2.2.0

**Comment by ivankelly** [comment]
@superbaobei There is a guide to setting up auth with TLS in our documents
http://pulsar.apache.org/docs/en/security-tls-authentication/
