### ISSUE TITLE
[FAQ] How does Pulsar Differ from Pravega

### ISSUE THREAD

**Issue by lgleim** [apache/pulsar#2951]
While there is much documentation on differences between Kafka and Pulsar, no such information exists for Pulsar and Pravega (https://github.com/pravega/pravega) 

C.f Pravega architecture
![image](https://user-images.githubusercontent.com/3898904/48123125-5d5b8800-e279-11e8-8b0d-3880b4e5a293.png)

**Comment by sijie** [comment]
@lgleim 

I am not an expert of Pravega. However I do have known the history of pravega. Here are some of my thoughts. Hope that is helpful to you.

These two projects have very different scopes. Pulsar starts from a Pub/Sub messaging system and evolves into a full-fledged event streaming platform, including unified pub/sub and streaming, infinite streaming storage (via tiered storage) and light-weight computing (via functions). Pravega is designed for a streaming storage only. 

With that being said, Pulsar can be used for traditional queuing workloads and newer streaming workloads. You can use Pulsar to unify your existing legacy messaging and streaming technologies. However Pravega is only for streaming processing. 

Both of systems use bookkeeper. However they are using bookkeeper in a very different way. Pulsar uses bookkeeper as the segment storage and moves the data from bookkeeper to tiered storage when data is aging out. bookkeeper and tiered storage are decoupled. You don't need a tiered storage run Pulsar, but if you want to use tiered storage feature, you can easily turn it on.

However Pravega uses bookkeeper only for WAL and tiered storage as the main storage for storing the data. That says you need both bookkeeper and an additional storage system for running Pravega. 

The differences of using bookkeeper results in performance and efficiency differences. IMO, Pulsar uses bookkeeper in a more efficient way than Pravega.

Besides the main two differences, Pulsar provides Pulsar Functions, Connectors and Schema Management, Geo-Replication for people to easily build reliable messaging and streaming applications. 

Hope this is helpful to you.
