### ISSUE TITLE
acknowledge message from another consumer

### ISSUE THREAD

**Issue by risson** [apache/pulsar#2963]
Is it possible that consumer A receive message 1, but let consumer B acknowledge that message after processing it?

**Comment by merlimat** [comment]
@risson Yes, a consumer instance is able to acknowledge a message that was dispatched to a different consumer. The only thing you need to have is the `MessageId`, which can also be serialized into a `byte[]` and stored somewhere.

**Comment by sijie** [comment]
@risson any thoughts on @merlimat 's comment?

**Comment by sijie** [comment]
Closed this issue since the question was answered
