### ISSUE TITLE
Topic becomes unavailable after being unloaded

### ISSUE THREAD

**Issue by massakam** [apache/pulsar#2967]
In our pulsar cluster, a specific topic became unavailable. The topic returned to normal after restarting the broker, but I would like to know the cause.

The following is the consumer log while the topic was unavailable:
https://gist.github.com/massakam/d2c3dbc1b3ea309b3fbc33f372859783#file-topic_unavailable_consumer-log

The following is log on the broker side at that time:
https://gist.github.com/massakam/d2c3dbc1b3ea309b3fbc33f372859783#file-topic_unavailable_broker-log

Before restarting the broker, we got the topic metadata. The reason is unknown, but the second ledger ID is different in stats-internal (3529617) and info-internal (3558449).
https://gist.github.com/massakam/d2c3dbc1b3ea309b3fbc33f372859783#file-topic_unavailable_stats-sh

This topic was unloaded several times due to heavy load.

```
broker-A
↓ unload (1)
broker-B
↓ unload
:
↓ unload
broker-C
↓ unload (2)
broker-A
```

- At (1), there was no sign of that the `PersistentTopic` instance was normally closed, and [NPE](https://gist.github.com/massakam/d2c3dbc1b3ea309b3fbc33f372859783#file-topic_unavailable_npe-log) occurred instead on broker-A
- The ledger with ID 3529617 was deleted by broker-B at (1)
- This problem occurred right after (2)
- When restarting broker-A, this warning appeared in the broker log
> 13:07:05.050 [shutdown-thread-46-1] WARN  o.a.p.b.s.persistent.PersistentTopic - [persistent://prop/global/ns/dest] Topic is already being closed or deleted

From the above, I think that broker-A had been holding the old `PersistentTopic` instance that was fenced. But I do not know why this happened.

Has anyone experienced a similar phenomenon?

#### System configuration
**Pulsar version**: 2.1.1

**Comment by vicaya** [comment]
We're seeing this (topic unavailable due bundle being unloaded) in 2.4.1:
``
"00:52:30.838 [pulsar-io-24-2] INFO  org.apache.pulsar.broker.lookup.TopicLookupBase - Failed to lookup null for topic persistent://... with error Namespace bundle .../0x00000000_0x40000000 is being unloaded\n"
"00:52:30.838 [pulsar-io-24-2] INFO  org.apache.pulsar.broker.service.ServerCnx - [/10.244.0.50:47136] Subscribing on topic persistent://...\n"
"00:52:30.838 [pulsar-io-24-2] WARN  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://...] Attempting to subscribe to a fenced topic\n"
"00:52:30.838 [pulsar-io-24-2] WARN  org.apache.pulsar.broker.service.ServerCnx - [/10.244.0.50:47136][persistent://...][216569ee-9823-4266-898e-1c54001dfa05] Failed to create consumer: Topic is temporarily unavailable\n"
"java.util.concurrent.CompletionException: org.apache.pulsar.broker.service.BrokerServiceException$TopicFencedException: Topic is temporarily unavailable\n"
"u0009at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326) ~[?:1.8.0_212]\n"
"u0009at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:984) ~[?:1.8.0_212]\n"
"u0009at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_212]\n"
"u0009at org.apache.pulsar.broker.service.ServerCnx.lambda$null$13(ServerCnx.java:680) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]\n"
"u0009at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_212]\n"
"u0009at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[?:1.8.0_212]\n"
``
Which appeared to be causing producer timeouts.
