### ISSUE TITLE
Change default AckTimeout when build consumer instance.

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#2987]
At present, default ackTimeoutMillis in ConsumerConfigurationData is 0. If user forgot set it, in shared model, un-ack message will not be redelivery.  If un-ack message accumulate to maxUnackMessage limit by broker, consumer will be blocked.

In version 2.2.0, support DeadLetterTopic feature. This feature based on message redelivery.

So propose change the default ackTimeoutMillis, such as 30 seconds.

**Comment by sijie** [comment]
@codelipenghui  A better solution might be set `ackTimeoutMillis` to 30 seconds if DLT is set and ackTimeoutMillis is not set yet.

**Comment by codelipenghui** [comment]
👍

**Comment by sijie** [comment]
This was fixed by #3014
