### ISSUE TITLE
schemas feature request

### ISSUE THREAD

**Issue by nha** [apache/pulsar#2992]
Feature request:

schemas ( https://github.com/apache/pulsar/blob/701f3ea7e3541f61f064167043de04e8a2db5c0f/pulsar-client-schema/src/main/java/org/apache/pulsar/client/api/Schema.java  )

If I want to pass arbitrary/dynamic Json schemas that are not POJOs - is there a way to pass something dynamic there?

I would like to create a Json schema that specifies a https://json-schema.org/ , or maybe a `Map<String, String> properties`

All examples I’ve seen are `JSONSchema.of`. Or is possible to describe the new schema over JSON? It seems that yes: https://pulsar.apache.org/docs/en/concepts-schema-registry/#supported-schema-formats but I don’t see any example or they are not exposed.

**Comment by nha** [comment]
After discussion, the way to do what I want is to:

- 1 - create a schemaless topic
- 2 - use the `POST /admin/v2/schemas/:tenant/:namespace/:topic/schema` endpoint to set a schema straight after that ( http://pulsar.apache.org/docs/en/admin-api-schemas/#pulsar-admin )
- 3 - use `AUTO_PRODUCE_BYTES` as mentioned above

**Comment by whisper-bye** [comment]
@nha @merlimat 

sorry for asking.

In my case, I have some raw json string data send to topic and can't hard code pojo class, I want to use the pulsar schema feature to validation the structure. I have a topic "my-topic" and associated with json schema in below, then I try to transmission some message.
```
var producer = client.newProducer(Schema.AUTO_PRODUCE_BYTES();
producer.send("{\"y\": 1}".getBytes()); // here! the value is 1(number) not string.

var reader = client.newReader(Schema.AUTO_CONSUME())
var message = reader.readNext();
I got {"y": 1}
```

my question is how pulsar schema works? The message should be rejected.

```
{
  "version": 1,
  "schemaInfo": {
    "name": "my-topic",
    "schema": {
      "type": "record",
      "name": "Data",
      "namespace": "com.iot.test",
      "fields": [
        {
          "name": "value",
          "type": [
            "null",
            "string"
          ]
        }
      ]
    },
    "type": "JSON",
    "properties": {
      "__alwaysAllowNull": "true"
    }
  }
}
```
