### ISSUE TITLE
documentation request: document presto http endpoint

### ISSUE THREAD

**Issue by nha** [apache/pulsar#3009]
I asked on slack (cc @sijie) if it was possible to use the Java client to make SQL requests.
Apparently there are presto HTTP endpoints that would work as well, but they are not documented at the moment.

This is a request to document them.

**Comment by Jennifer88huang** [comment]
@zymap Let's finalize the PR #5376 this week together.

**Comment by zymap** [comment]
@Jennifer88huang  Sure
