### ISSUE TITLE
Fail to pull the Docker image of apachepulsar/pulsar-standalone

### ISSUE THREAD

**Issue by tonypu** [apache/pulsar#3013]
#### Expected behavior

The info under "Run Pulsar Standalone in Docker"
(https://pulsar.apache.org/docs/en/standalone/) , the command of `docker run -it -p 80:80 -p 8080:8080 -p 6650:6650 apachepulsar/pulsar-standalone` is not working. Either there is no such  `apachepulsar/pulsar-standalone` image available for public, or the info is missing something.
#### Actual behavior

Failed to execute the command "docker run -it -p 80:80 -p 8080:8080 -p 6650:6650 apachepulsar/pulsar-standalone"

#### Steps to reproduce

Follow the "Run Pulsar Standalone in Docker" Docker step of `docker run -it -p 80:80 -p 8080:8080 -p 6650:6650 apachepulsar/pulsar-standalone`

#### System configuration
**Pulsar version**: `2.2`

**Comment by sijie** [comment]
@tonypu : I published the`pulsar-standalone` image: https://hub.docker.com/r/apachepulsar/pulsar-standalone/

and #3016 is the PR for adding `pulsar-standalone` into normal release process.

**Comment by genestack-solomatin** [comment]
Hi, @sijie, I have noticed that [Start a standalone cluster with Docker](https://pulsar.apache.org/docs/en/standalone-docker/) does not reference pulsar-standalone image.
