### ISSUE TITLE
Maven Build Error 2.2.0

### ISSUE THREAD

**Issue by drdrill** [apache/pulsar#3068]
#### Expected behavior

Maven build should work correctly, always, both in Linux and in Windows

#### Actual behavior

In Linux, maven build encounters error when it tries to access non-existing URL:  https://yahoo.bintray.com/maven/org/apache/apache/18/apache-18.pom

[DEBUG] Using transporter WagonTransporter with priority -1.0 for https://yahoo.bintray.com/maven
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://yahoo.bintray.com/maven via proxy.company.com:80 with username=user, password=***
Downloading: https://yahoo.bintray.com/maven/org/apache/apache/18/apache-18.pom
[DEBUG] Writing tracking file /home/user/.m2/repository/org/apache/apache/18/apache-18.pom.lastUpdated
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.apache.pulsar:pulsar:2.2.0: Could not transfer artifact org.apache:apache:pom:18 from/to central (https://repo1.maven.org/maven2): Not authorized by proxy , ReasonPhrase: Proxy Authentication Required. and 'parent.relativePath' points at wrong local POM @ line 27, column 11
 @
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.apache.pulsar:pulsar:2.2.0: Could not transfer artifact org.apache:apache:pom:18 from/to central (https://repo1.maven.org/maven2): Not authorized by proxy , ReasonPhrase: Proxy Authentication Required. and 'parent.relativePath' points at wrong local POM @ line 27, column 11

#### Steps to reproduce

On a clean system, download Pulsar 2.2.0 source, install Java and Maven, and execute the Maven Build

#### System configuration
**Pulsar version**: 2.2.0
Oracle Linux Server release 6.10
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Apache Maven 3.3.3

**Comment by drdrill** [comment]
Resolved: corrected bad password for proxy reference in .m2/settings.xml file

**Comment by drdrill** [comment]
Problems still exist. 
Seems that Apache projects should not be referencing this repository:
    <repository>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>bintray-yahoo-maven</id>
      <name>bintray</name>
      <url>https://yahoo.bintray.com/maven</url>
    </repository>

**Comment by merlimat** [comment]
@drdrill  Actually I was wrong, https://yahoo.bintray.com/maven is still the only place where there jars are being published. 

The questions is that since this is a public repo with not auth required, where is the auth request coming from? Do you have a maven proxy in the middle?

**Comment by drdrill** [comment]
Yes, I do have a proxy in the middle and have corrected the password and the Linux build is now working.
However, the URL reference created by the Pulsar build does not point to a valid directory containing any jars that Pulsar needs or should use: 
Valid Directory:  https://yahoo.bintray.com/maven
Valid Directory:  https://yahoo.bintray.com/maven/org/apache/

Note: there is only an "omid" directory underneath https://yahoo.bintray.com/maven/org/apache/

URL Created by the build points to a non-existent directory and non-existent file:
https://yahoo.bintray.com/maven/org/apache/apache/18/apache-18.pom

**Comment by merlimat** [comment]
All the jars that are on Maven central should be fetched from `repo.apache.org`. Maven should be handling that. It might try on multiple repositories until it succeeds in fetching some artifact.

**Comment by sijie** [comment]
@drdrill does matteo's comment make sense to you?

**Comment by drdrill** [comment]
Yes.  
My only point, stated indirectly, was to suggest removing the references in the Apache-Pulsar pom.xml to bintray to eliminated any ambiguity or unnecessary errors and confusion that Maven may generate.
Specifically, it seems to make sense to remove the following repository reference if it is not needed:
'''xml
<repository>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>bintray-yahoo-maven</id>
      <name>bintray</name>
      <url>https://yahoo.bintray.com/maven</url>
    </repository>
'''

**Comment by sijie** [comment]
Closed this issue since the question was answered
