### ISSUE TITLE
[Question] cluster mode fuctions in Kubernetes cluster

### ISSUE THREAD

**Issue by hiscal2015** [apache/pulsar#3073]
Hi, 

I can't see any documents introduce running pulsar function in cluster mode along side with broker in Kubernetes. But from broker configmap it looks like function is supported. How to use this? Do I need to customize broker image to add my jar file and yaml or something else? Thanks a lot.

![image](https://user-images.githubusercontent.com/15604715/49126796-fd985000-f2ff-11e8-82dd-12f7297b2863.png)

**Comment by hiscal2015** [comment]
@sijie I'm wondering where does pulsar "store" user functions? If I delete broker pods after function created, what will happen? user functions still there?

**Comment by srkukarni** [comment]
Functions are distributed on all broker containers who have function enabled. If you take one or many of these brokers away, they get redistributed to remaining broker containers.

**Comment by hiscal2015** [comment]
@srkukarni Is that mean:

1) If I have 10 pods, I delete 2 of them, after the 2 pods re-created by Kubernetes, functions on the 2 pods will be recovered?
2) if I delete broker deployment in Kubernetes (so all pods will be lost) I have to re-create my functions?

**Comment by srkukarni** [comment]
It depends on how you delete the pods
1a. If you just kill the pods, kubernetes will recreate the pods and the functions will be back on them
1b. If you scale down the number of broker pods from 10 to 8, the killed pods will not be recreated by kubernetes. In that case, functions running on those 2 pods will be redistributed among the remaining 8 pods
2. If all pods are deleted, functions will no longer run. They are not lost, in the sense that the moment some new pod comes up, they will try to come up on that pod. You don;t have to recreate the functions. The meta data for all of this will be in bookkeeper so it wont be lost

**Comment by sijie** [comment]
The documentation about running functions on kubernetes is added in #4263
