### ISSUE TITLE
pulsar-client produce topic -f file in cluster error if you use relative path

### ISSUE THREAD

**Issue by xluckly** [apache/pulsar#3074]
pulsar-client produce topic -f file in cluster error if you use relative path
Solution：

you should use Absolute path

**Comment by Hanqingkuo** [comment]
you should use Absolute path

**Comment by sijie** [comment]
@Hanqingkuo are you interested in contributing a bug fix for this?

**Comment by Hanqingkuo** [comment]
yes

At 2018-11-29 05:37:24, "Sijie Guo" <notifications@github.com> wrote:


@Hanqingkuo are you interested in contributing a bug fix for this?

**Comment by tisonkun** [comment]
Closed as stale. Feel free to open a new issue if it's still relevant for maintained versions.

I noticed that current codebase uses `Paths.get` to resolve paths so it may not be an issue anymore.
