### ISSUE TITLE
Emhancement | NoopLoadManager could have more details for load report

### ISSUE THREAD

**Issue by foreversunyao** [apache/pulsar#3083]
#### Expected behavior

when run pulsar-admin broker-stats load-report, should return load information even run as standalone mode, or return some load empty data instead of null

#### Actual behavior

return "null"

Tell us what happens instead

return the load normal report 

#### Steps to reproduce

1, ./bin/pulsar standalone
2, ./bin/pulsar-admin broker-stats load-report 
null

### Code 
https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/NoopLoadManager.java#L104

#### System configuration
**Pulsar version**:  Current master branch

**Comment by sijie** [comment]
@foreversunyao are you interested in contributing an improvement to this?

**Comment by rdhabalia** [comment]
@merlimat in my opinion, I think we should not use separate `NoopLoadManager` for standalone broker but we should use `ModularLoadManager` everywhere and it should be generic enough to handle all usecases. So, I feel we should remove `NoopLoadManager` and start using ModularLoadManager everywhere.

**Comment by foreversunyao** [comment]
@sijie @rdhabalia @merlimat 

Sure, I'll give it a shot.
Firstly, I need the conclusion for the direction, we will still use NoopLoadManager for some specific cases ?  or we use ModularLoadManager/LoadManager/...  as a unite entry for this function?
Thanks

**Comment by rdhabalia** [comment]
if we not going to use `NoOpLoadManager` then probably we can revert back #2487

**Comment by merlimat** [comment]
The ModularLoadManager has a lot of features that are unnecessary in standalone mode. In fact, with standalone, there is no load to manage.. as there's no way to send it.

As far as the standalone is concerned, we should also remove the embedded ZK as it's not needed.

The motivation for #2487 was to fix the broker restart when the broker Z-node was not cleared. This is a confusing error and unnecessary in standalone mode, since there can be only 1 instance anyway.

**Comment by sijie** [comment]
@merlimat : so fix NoopLoadManager?

**Comment by sijie** [comment]
@rdhabalia @merlimat : can we draw a conclusion here? fix NoopLoadManager or remove it?

**Comment by tisonkun** [comment]
Closed as no consensus. It seems no one else complains while we keep this manner for years.
