### ISSUE TITLE
javadoc doesn't respect the docusaurus versioning

### ISSUE THREAD

**Issue by ivankelly** [apache/pulsar#3087]
http://pulsar.apache.org/docs/en/client-libraries/ points to http://pulsar.apache.org/api/client
http://pulsar.apache.org/docs/en/next/client-libraries/ points to http://pulsar.apache.org/api/client

Of all the things that should be sensitive to version, javadoc is probably number 1.

**Comment by Jennifer88huang** [comment]
I've just checked the two links, they navigate to the right destination now.
@ivankelly Could we close this issue?

**Comment by sijie** [comment]
@Jennifer88huang I don't think they are resolving to the right version of javadoc

**Comment by Jennifer88huang** [comment]
Then who can resolve this issue correctly?

**Comment by sijie** [comment]
I think this has been resolved since @tuteng already introduced versioning for javadoc.
