### ISSUE TITLE
[Question] how to make consumer subscribe only one partition

### ISSUE THREAD

**Issue by huanhuang-wang** [apache/pulsar#3098]
By using custom partitioner we let
all messages of user id 1 to 100 goes to topic A partition 1,
all messages of user id 101 to 200 goes to topic A partition 2,
...

and want to create multiple Failover subscriptions for each partition,
Failover subscription A1 with consumers(A1.x, A1.y) which consumes only message from topic A partition 1,
Failover subscription A2 with consumers(A2.x, A2.y) which consumes only message from topic A partition 2,
...

how to implement this? should I use different topics other than partitions on same topic?

**Comment by merlimat** [comment]
@huanhuang-wang you can either user multiple topics without partitions or a single topic with partitions, there is no mandated solution. 

With partitions, you can use the $TOPIC-partition-N as the topic name to subscribe to a specific subscription

**Comment by huanhuang-wang** [comment]
$TOPIC-partition-N as topic name looks great! didn't know that. thanks!
