### ISSUE TITLE
[Feature request] Make brokers read on closest Bookie

### ISSUE THREAD

**Issue by cbornet** [apache/pulsar#3119]
Rack-aware policy can be used to place bookies on different racks/AZ/regions.
Brokers can be isolated in racks/AZ/regions with a namespace-isolation-policy (#3104). With this cross-dc bandwidth can be minimized between clients and brokers.
Now to minimize cross-dc bandwidth between brokers and bookies, brokers should be aware of their own rack and of the rack location of bookies. Then they can do read requests by first attempting to read on their own rack, then falling back to other racks (with speculative reads ?).

References:
* DistributedLog: https://bookkeeper.apache.org/distributedlog/docs/0.5.0/user_guide/globalreplicatedlog/main.html#cross-region-speculative-reads-1
* Kafka: https://cwiki.apache.org/confluence/display/KAFKA/KIP-392%3A+Allow+consumers+to+fetch+from+closest+replica

**Comment by sijie** [comment]
@cbornet I think it should be already available via configuring `reorderReadSequenceEnabled` in bookkeeper client. https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java#L1130

I need to check whether this is exposed at broker configuration or not.

**Comment by cbornet** [comment]
Also it seems the broker BK client has support for RackawareEnsemblePlacementPolicy but not for RegionAwareEnsemblePlacementPolicy.

**Comment by sijie** [comment]
@cbornet : 

> And it shouldn't be hard to expose. I'll try it and propose a PR if it works.

that would be great!

> how does the bookkeeper client identify which is its preferred rack ?

from bookkeeper client perspective, the ensemble placement policy will use some sort of DNS resolver to resolve a bookie into its network location. the network locations will form a network topology of bookies. it will then use that the compute the shortest network path to find the best bookie to contract to.

in the context of pulsar broker, pulsar provides a REST api for people to update the racks for bookies.

> Also it seems the broker BK client has support for RackawareEnsemblePlacementPolicy but not for RegionAwareEnsemblePlacementPolicy. Wouldn't that be an issue ?

technically you don't have the issue. the existence of RegionAwareEnsemblePlacementPolicy is for the case that you need both region-aware and within a region you also need rack-aware. in a simpler form to think about this is following:

- Rack-Aware is good enough if your network topology only has one level (rack or availability zones)
- Region-Aware is better if your network topology has multiple levels (e.g. /region/rack).

In this way, Rackware is good enough for AWS AZs :)

**Comment by cbornet** [comment]
Actually, reading the code, it seems that the client will already use `selectFromNetworkLocation` which will do `selectRandomFromRack` and fallback to `selectRandom`. So maybe there's nothing to do for racks and the client already reads from its detected rack in priority ?

Also looking at the code, it seems that the client will use the same DNSResolver as the bookies to determine its own rack: https://github.com/apache/bookkeeper/blob/5602c51192483075686746afb84c3449a470a98d/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java#L265
In the case of Pulsar that means I should add rack info for the Broker as if it were a bookie, no ? eg using the `/admin/v2/bookies/racks-info/{bookie}` endpoint ?

**Comment by merlimat** [comment]
> In the case of Pulsar that means I should add rack info for the Broker as if it were a bookie, no ? eg using the /admin/v2/bookies/racks-info/{bookie} endpoint ?

I might work or not. I haven't tried.

In any case we should package that in a better way, by having option to directly configure racks for brokers.

**Comment by cbornet** [comment]
About RegionAwareEnsemblePlacementPolicy  vs RackawareEnsemblePlacementPolicy, it seems the former one will order between regions to match the region of the client whereas the latter will not do the same for racks: https://github.com/apache/bookkeeper/blob/5602c51192483075686746afb84c3449a470a98d/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/RackawareEnsemblePlacementPolicyImpl.java#L957-L967

**Comment by cbornet** [comment]
I did tests with `reorderReadSequenceEnabled=true`  and RackawareEnsemblePlacementPolicy and can confirm the WriteSet is not reordered from a preferred rack.

**Comment by cbornet** [comment]
And on the other hand, RegionAwareEnsemblePlacementPolicy with reorderReadSequenceEnabled works as expected.
Using the following placement
```
bin/pulsar-admin bookies racks-placement                                                              
{
  "default" : {
    "bk1-eu:3181" : {
      "rack" : "eu/1"
    },
    "bk2-eu:3181" : {
      "rack" : "eu/1"
    },
    "bk2-us:3181" : {
      "rack" : "us/1"
    },
    "bk1-us:3181" : {
      "rack" : "us/1"
    },
    "pulsar1-eu:6650" : {
      "rack" : "eu/1"
    },
    "pulsar2-eu:6650" : {
      "rack" : "eu/1"
    },
    "pulsar1-us:6650" : {
      "rack" : "us/1"
    },
    "pulsar2-us:6650" : {
      "rack" : "us/1"
    }
  }
}
```
Consumption from "eu" brokers goes to "eu" bookies as expected

So I propose to add two broker config params:
* `bookkeeperClientRegionawarePolicyEnabled` to activate region aware policy. If set, the value of `bookkeeperClientRackawarePolicyEnabled` will not be used.
* `reorderReadSequenceEnabled`

I'll do the PR if it's OK.

**Comment by cbornet** [comment]
What should be the default value for these options ? Enabled/disabled ?
Should the default policy be rack-aware (current default) or region-aware ?

**Comment by sijie** [comment]
> What should be the default value for these options ? Enabled/disabled ?

better to be "disabled"

> Should the default policy be rack-aware (current default) or region-aware ?

I think default policy should be rack-aware since that would be most of the people is using.
