### ISSUE TITLE
kubernetes fucntion labels are not formatted correctly

### ISSUE THREAD

**Issue by cckellogg** [apache/pulsar#3122]
Kubernetes does not allow "/" in the label or selector values

* spec.selector: Invalid value: "public/default/log": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
* spec.selector: Invalid value: "public/default": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

**Comment by sijie** [comment]
This is fixed by #3123
