### ISSUE TITLE
Function state does not work

### ISSUE THREAD

**Issue by ngjaying** [apache/pulsar#3140]
#### Expected behavior

Function context getState can read the state set by putState

#### Actual behavior

Function context getState does not return the state set by putState

#### Steps to reproduce
Run the following function on the cluster.  The incrCounter/getCounter works fine; but the getState always return empty string.
```
import static java.nio.charset.StandardCharsets.UTF_8;

import java.nio.ByteBuffer;

import org.apache.pulsar.functions.api.Context;
import org.apache.pulsar.functions.api.Function;
import org.slf4j.Logger;

public class StateFunction implements Function<String, Void> {

	private Logger logger;
	@Override
	public Void process(String input, Context context) throws Exception {
		logger = context.getLogger();
		logger.info("received {}", input);
		context.incrCounter("ac", 1);
		long currentCount = context.getCounter("ac");
		logger.info("current count: {}", currentCount);
		
		try {
			ByteBuffer rulesState = context.getState("last");
			if(rulesState != null) {
				logger.info("last: {}", UTF_8.decode(rulesState).toString());
			}
		}catch(Exception e) {
			e.printStackTrace();
		}
		
		context.putState("last", ByteBuffer.wrap(input.getBytes(UTF_8)));
		
		try {
			ByteBuffer rulesState = context.getState("last");
			if(rulesState != null) {
				logger.info("new last: {}", UTF_8.decode(rulesState).toString());
			}
		}catch(Exception e) {
			e.printStackTrace();
		}
		
		return null;
	}

}
```
A sample log produced by this function:
```
09:04:04.921 [public/default/statefunc-0] INFO  function-statefunc - received hello-pulsar-1
09:04:04.929 [public/default/statefunc-0] INFO  function-statefunc - current count: 41
09:04:04.934 [public/default/statefunc-0] INFO  function-statefunc - last: 
09:04:04.942 [public/default/statefunc-0] INFO  function-statefunc - new last: 
```

#### System configuration
**Pulsar version**: 2.2.0

**Comment by ngjaying** [comment]
@sijie Thanks for your reply, but the getState and putState are in the documentation [function-state](https://pulsar.apache.org/docs/en/functions-state/) and it is already exposed in the context. I can't believe it takes no effect.

**Comment by sijie** [comment]
@ngjaying : I need to take a closer look at what happened in 2.2.0. but the feature in 2.2.0 is still a developer preview feature. we have made a lot of changes in bk 4.9.0 and the upcoming 2.3.0 release around state.

**Comment by ngjaying** [comment]
@sijie Thanks. When is the planned release date for 2.3.0?

**Comment by sijie** [comment]
The state is enabled by default in pulsar-standalone
