### ISSUE TITLE
java.lang.IllegalStateException: State is not enabled

### ISSUE THREAD

**Issue by hiscal2015** [apache/pulsar#3153]
bookkeeper version: 4.7.3
Pulsar broker version : 2.2.0

We have a 3 nodes bk cluster on bare metal and 3 brokers on Kubernetes. We followed the guide to create a function, but when our Pulsar function calls "putState" the following exception occurs:
```
java.lang.IllegalStateException: State is not enabled
```
Are there missing steps that we need to take to enable State for functions?
By checking this document:
https://github.com/sijie/incubator-pulsar/blob/55d1701d79ca2e4628f9cc82db01301279589e76/site2/docs/deploy-bare-metal.md
We also added extraServerComponents=org.apache.bookkeeper.stream.server.StreamStorageLifecycleComponent to bk_server.conf

Please help, thanks.

**Comment by sijie** [comment]
@hiscal2015 this is related to #3140

**Comment by yusufaytas** [comment]
I've just downloaded pulsar and running it in standalone mode. I get `java.lang.IllegalStateException: State is not enabled.` when running functions.

**Comment by sijie** [comment]
@yusufaytas for standalone, the state is enabled by default. How did you run the standalone?

**Comment by yusufaytas** [comment]
I've figured this out. I had to set `stateStorageServiceUrl` to make functions work.  Nevertheless, it might be a good idea to supply local BookKeeper URI to functions by default. Thanks for the reply.

**Comment by alohahahaha** [comment]
> I've figured this out. I had to set `stateStorageServiceUrl` to make functions work. Nevertheless, it might be a good idea to supply local BookKeeper URI to functions by default. Thanks for the reply.

 when i debug with localrun mode and use `getCounter()`,I get  `State is not enabled` error too,how to set `stateStorageServiceUrl` ? when i  debug with localrun mode .

**Comment by yusufaytas** [comment]
Simply set it for `LocalRunner`
```
LocalRunner localRunner = LocalRunner.builder()
    .stateStorageServiceUrl("bk://127.0.0.1:4181")
    .functionConfig(functionConfig)
    .build();
```

**Comment by alohahahaha** [comment]
@yusufaytas it works,Thank you very much !
