### ISSUE TITLE
Message ID of sent message should be returned in Go client producer

### ISSUE THREAD

**Issue by tobgu** [apache/pulsar#3161]
#### Expected behavior

Go client library returns the message ID of a message that has been commited to disk. Just like the Java client currently does. Both for async and sync send.

#### Actual behavior

There is no way of getting the message ID of a sent message in the current implementation of the Go client as far as I can tell.

**Comment by merlimat** [comment]
When we defined and reviewed the Go client API, this was one of the discussed points. The idea was to keep the API surface as small as possible. 

Would it be an option to add the message id to the returned `error` ? eg: downcast to a ProducerError interface which will contain an optional message id.
