### ISSUE TITLE
There should be a way to get the last message ID of a topic

### ISSUE THREAD

**Issue by tobgu** [apache/pulsar#3162]
#### Expected behavior

I can either read the last message (through a reader) to get the message ID of that message or get the last commited message ID for a topic in some other way (perhaps the REST API?).

This would be very convinient to be able to instantiate Readers starting from a given position.

Currently you can configure the Reader to start from LastMessageID. This will only give you messages not yet produced though.

**Comment by sijie** [comment]
GetLastMessageId request is already there. However it is not exposed. It should be very straightforward to expose it. @jiazhai or @legendtkl can help with that.

**Comment by ivankelly** [comment]
There was a conversation about whether to expose it when implementing Reader#hasMessageAvailable().
