### ISSUE TITLE
Pulsar Functions ( Python) : Support to submit python modules

### ISSUE THREAD

**Issue by shalinseban** [apache/pulsar#3173]
#### Expected behavior

We should be able to submit a pulsar function as a python module rather than a python file, i.e, ability to pass path to a python module to `py` parameter in `pulsar-admin functions create`. Fitting all the code into a python file makes it difficult to develop and test pulsar functions effectively.

**Comment by srkukarni** [comment]
We already support submitting .whl files. Does that satisfy this requirement?

**Comment by shalinseban** [comment]
Awesome. Yes it does.

**Comment by shalinseban** [comment]
I'm assuming that is for **2.3** release though.

**Comment by srkukarni** [comment]
This is actually for 2.2 release.

**Comment by shalinseban** [comment]
Interesting. Is there documentation updated around submitting `.whl` as pulsar functions. I can't seem to find it. The release notes for 2.2 does not contain any mentions of this either.

**Comment by srkukarni** [comment]
Unfortunately we are a little behind wrt documentation. You can create a wheel file and just submit it using the same --py <wheel file> and things should work fine.

**Comment by shalinseban** [comment]
Got it. Thanks for clarifying that.
