### ISSUE TITLE
Broker should not serve requests until it is ready

### ISSUE THREAD

**Issue by ivankelly** [apache/pulsar#3178]
See discussion on #2942 .

The broker opens port 6650 before it is actually fully initialized, which can cause clients to see weird things (broker bounces and resends all unacknowledged messages). This can happen if there are still ephemerals from the previous instance in zk, so the broker would keep bouncing until session timeout and the client would end up getting a bunch of redeliveries.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
