### ISSUE TITLE
[Feature Request] Control the speed of reading data from bookie

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#3183]
We found from the monitoring that the outflow of high network bandwidth affects the delay of message writing.

![image](https://user-images.githubusercontent.com/12592133/49925062-daba8e00-fef2-11e8-8540-cee4d5c35e6e.png)

Troubleshoot the problem, i think may be caused by the broker reading data from bookie. 

So, If the broker can control the speed of reading data from bookie, message write latency can be better guaranteed

#### System configuration
**Pulsar version**: 2.2.0

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
