### ISSUE TITLE
Can't use jPype on pulsar-client-original.jar

### ISSUE THREAD

**Issue by JevonQ** [apache/pulsar#3186]
Currently, I'm trying to write some test cases in Python to test against Pulsar cluster via Java driver. I download the jar package from offical website. JPype is used to call Java class in Python, the code is like:
`PulsarClient_class = jpype.JClass("org.apache.pulsar.client.api.PulsarClient")`

I got the following error:
`Class PulsarClient is not found.`

Then I realize that jPype might not recognize Java Interface, then I switch to use the Implement class. I wrote the following code:
`PulsarClient_class = jpype.JClass("org.apache.pulsar.client.impl.PulsarClientImpl")`
But it seems jpype can not find impl package. Can anyone help on that?

**Comment by sijie** [comment]
@JevonQ I am wondering why don't you use pulsar python client?

**Comment by JevonQ** [comment]
The producer and consumer are using Java client, we need to guarantee it will be well tested. Unfortunately, our test cases has to be written in Python, so I have to use Jpype to call Java client in the test cases.

**Comment by sijie** [comment]
@JevonQ : I haven't used JPype before. I will have to take a look and try it out.

**Comment by tisonkun** [comment]
Closed as stale. Feel free to open a new issue if it's still relevant for maintained versions.
