### ISSUE TITLE
Can't pip install Pulsar 2.2.0 client for Python 3.6 on MacOS 10.13.

### ISSUE THREAD

**Issue by ewh** [apache/pulsar#3189]
Please refer to these issues:
* https://github.com/apache/pulsar/issues/2568
* https://github.com/apache/pulsar/issues/1926

I'm interested in Pulsar 2.2.0 on Python 3.6 and Python 3.7 on MacOS 10.13 and 10.14. I'm just interested in hearing to what degree these configurations are expected to be supported and available on `pypi`.

**Comment by sijie** [comment]
@ewh you can find the current list of supported platforms here: https://pypi.org/project/pulsar-client/2.2.0/#files

**Comment by ivankelly** [comment]
@ewh does this answer your question?

**Comment by ewh** [comment]
@ivankelly The previous answer _does_ answer which exact configurations are supported for any given version of Python interpreter and OS. However, I was wondering if there might ever be support for Python 3.5 and 3.6 on Mac? It seems as if many Python 3.* versions are supported on Linux, but only Python 3.7 is supported on Mac. There are many users still running Python 3.5 and 3.6 on Mac. I was just wondering if these older Python 3.* versions might ever expect to be supported on Mac.

Thanks!
