### ISSUE TITLE
Is state shared by function instances?

### ISSUE THREAD

**Issue by ngjaying** [apache/pulsar#3208]
Given a function created with --parallelism 2, I wonder if these 2 function instances share the state storage. If not, is it going to be supported in the near future? Thanks.

#### System configuration
**Pulsar version**: 2.2.0

**Comment by srkukarni** [comment]
Yes, the state is shared between the two instances. When you do a put/get inside the Context inside a function the real-key is the fully qualified function name + the key that you specify. This means that the key is visible to not just other instances of the function, but to other functions as well. However the Context api currently doesnt provide any way of accessing some other functions' keys.

**Comment by ngjaying** [comment]
Thank you. Is it thread-safe to use state in parallel function instances?

**Comment by srkukarni** [comment]
When you mean 'thread' safe are you talking about multiple function instances updating/getting state. Yes it is, however note that if two or more instances are updating the same key, the last one will get through.

**Comment by ngjaying** [comment]
OK. I am concerned about the Read-Modify-Write scenario. For below scenario, given the initial value for state.key = "value". If the function has the below logic:
`
String currentValue = context.getState("key"); 
context.putState("key", currentValue + context.getInstanceId);
`
If this function is run with --parallelism 2. Is this read-modify-write run like a database transaction? If not, is there a best practice for such scenario.

**Comment by srkukarni** [comment]
This is not going to be a read-modify-write as in database. In this particular scenario the final value of context.getState("key") is one of (value + "0", value + "1", value + "1" + "0", value + "0" + "1").
The only current server side support for some kind of serialization amongs't update is in form of counters. The Java API(and soon in 2.3 the python api) has support for getCounter/incrCounter methods. Using the example above, if the function logic is context.incrCounter("key", 1), and you have the guarantee that the counter.getCounter after all messages will be equal to the number of messages(assuming no failures). Hope that helps

**Comment by ngjaying** [comment]
The context.incrCounter is excellent for our use case. But the problem is that we want to store some string value in the state instead of integer. Is there any way to do that?

**Comment by srkukarni** [comment]
Unfortunately currently I can't think of a way to accomplish this.
@sijie One thing that might be useful would be a interface like context.putIf("key", "newvalue", "oldvalue") that will do an update of key only if the old value was "oldvalue", otherwise throw an exception. Thoughts?

**Comment by sijie** [comment]
Closed the issue since the question was answered.

**Comment by frank-dkvan** [comment]
> Yes, the state is shared between the two instances. When you do a put/get inside the Context inside a function the real-key is the fully qualified function name + the key that you specify. This means that the key is visible to not just other instances of the function, but to other functions as well. However the Context api currently doesnt provide any way of accessing some other functions' keys.

If I want to read  states from the other functions, which API can help with this?  since context API doesn't support this.

**Comment by kerler** [comment]
> CAS operations should be easy to add.
> 
> We will consider adding a more generic transaction mechanism in future releases.

Any update on CAS or "more generic transaction mechanism in future releases"?
