### ISSUE TITLE
pulsar producer create fail, get error :Received error from server: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Michael-YuSha** [apache/pulsar#3211]
#### Actual behavior

I have create a producer with JSON schema of Person object for topic named /xh/test/demo8, in the code review, we need to update Person to Student, the Student extends Person, so i delete the schema for persistent://xh/test/demo8, then i create the producer by pulsarClient, but the server response the error Received error from server: java.lang.NullPointerException. Then, i delete the topic persistent://xh/test/demo8, and create producer ,i get a same error from server, so that, I use pulsar-admin to upload a new schema by conf file, the server response a 500 bad code for me

#### Steps to reproduce

1、create a producer with Json schema with a pojo object
2、delete the topic schema
3、create producer 

#### System configuration
**Pulsar version**: 2.2.0

**Comment by Michael-YuSha** [comment]
I have create a producer with JSON schema of Person object for topic named /xh/test/demo8, in the code review, we need to update Person to Student, the Student  extends Person, so i delete the schema for persistent://xh/test/demo8, then i create the producer by pulsarClient, but the server response the error Received error from server: java.lang.NullPointerException. Then, i delete the topic persistent://xh/test/demo8,  and create producer ,i get a same error from server, so that, I use pulsar-admin to upload a new schema by conf file, the server response a 500 bad code for me

**Comment by Michael-YuSha** [comment]
this debug have not solved at version v2.2.1

**Comment by sijie** [comment]
Issue #3836 will fix it

**Comment by markmarijnissen** [comment]
Is there a workaround available for Pulsar 2.3.0, other than starting an entirely new topic which doesn't have soft-deleted schema's?

**Comment by tschmidt64-SC** [comment]
I am still getting this issue in 2.3.2

**Comment by Fernandoize** [comment]
i get this issue in 2.4.1
