### ISSUE TITLE
[Feature Request]Tiered storage like Pravega

### ISSUE THREAD

**Issue by yingfeng** [apache/pulsar#3214]
Both Pulsar and [Pravega](https://github.com/pravega/pravega) are streaming storage solution based on BookKeeper. However, Pravega has an extra feature of automatic segment migration for tiered storage(auto tiering)---BookKeeper for streaming and distributed filesystem(HDFS,S3,..,etc) for long term storage.  Given this feature available, Pravega could be a unified storage solution for both streaming and batch processing. On the other hand, Flink would be a unified computation solution for both streaming and batch processing, as a result, Pravega+Flink might be candidates for next generation big data platform which could be defined as Stream Native. The segment store design of Pravega is not complicated, if this feature could be provided by Pulsar, perhaps Pulsar+Flink could be a better choice for NG big data platform.

**Comment by sijie** [comment]
@yingfeng : Pulsar already provided tiered storage since 2.1. http://pulsar.apache.org/docs/en/concepts-tiered-storage/ Please check it out.

@jiazhai and me will be giving a presentation about "Unifying the Batch and Stream Elastic Processing with Apache Pulsar® and Apache Flink®" in Flink Forward China on Dec 20th. If you are attending this conference, feel free to stop by.

https://china-2018.flink-forward.org/conference-program/#unifying-the-batch-and-stream-elastic-processing-with-apache-pulsar%C2%AE-and-apache-flink%C2%AE

**Comment by yingfeng** [comment]
@sijie I've seen the wiki page of tiered storage previously. It's not the same as Pravega:

- It's not an auto-tiering solution. User has to migrate to low tier storage manually through api. An unified storage for both streaming and batching should be able to automatically process these flow for users
- The supporting storage solution is limited, many kinds of storage such as HDFS, Ceph,...,etc are not supported.
- Transaction for entire stream

I don't think implementing features of Pravega to Pulsar is difficult, while providing feature of Pulsar to Pravega is much more difficult. Here's a [slide](https://www.slideshare.net/Hadoop_Summit/an-elastic-batchand-streamprocessing-stack-with-pravega-and-apache-flink)  of having Pravega work together with Flink, which I think it has the same vision with Pulsar.

**Comment by sijie** [comment]
> It's not an auto-tiering solution. User has to migrate to low tier storage manually through api. An unified storage for both streaming and batching should be able to automatically process these flow for users

1) Pulsar has auto-tiering by namespaces. Pulsar is a multi-tenant system, so everything is controlled per tenant/namespace, not per cluster. A user can configure offloading to tiered storage by namespaces. I believe it can configure to auto-offload at size-based policy or interval-based policy. If it is not provided, it should be trivial to add that.
2) Not every user need tiered storage. 

> many kinds of storage such as HDFS, Ceph,...,etc are not supported.

All the mechanism for tiered storages are in places. Everyone can contribute the offloader to offload pulsar to the storage system he/she is using.

HDFS offloader is under development. But if you have more specific requirements, I would suggest you creating specific github issues for them. We can work with you on priotizing them. 

> Transaction for entire stream

Transaction is a separate story that is under discussion and development.

**Comment by yingfeng** [comment]
Thank you. There are some other design features for auto tiering:
1. Retention policy, describes a policy about how much data to retain within a stream. This is similar with what Pulsar has done to let customer configure how data was migrated to low tier storage.
2. Scaling policy, describes if and under what circumstances a stream should `automatically` scale its number of segments. This is a bit more complicated: the controller monitors traffic of stream segment writing requests, if some thresholds have been reached, it will decide how to scale. There are two types of traffic reports that can be received for segments. First type identifies if a segment should be scaled up (split) and second type identifies if a segment should be scaled down. For segments eligible for scale up, controller immediately posts request for segment scale up in the request stream for request event processor to process. However, for scale down, Controller needs to wait for at least two neighboring segments to become eligible for scale down. This auto scaling could be seen [here](https://github.com/pravega/pravega/blob/master/documentation/src/docs/pravega-concepts.md#elastic-streams-auto-scaling) with more detail.
![Uploading 图片.png…](https://raw.githubusercontent.com/pravega/pravega/master/documentation/src/docs/img/segment.split.merge.overtime.new.png)

**Comment by sijie** [comment]
@yingfeng 

> Retention policy, 

it is already supported in Pulsar. I would suggest you taking a closer look at Pulsar and creating individual tasks for the features you would like to see in Pulsar. Pulsar and Pravega are different projects, Pulsar has a broader vision than Pravega. It unifies both messaging (queueing and streaming) and storage. 

> Scaling policy,

Pulsar provides all the mechanisms to scaling up and down partitions. Applications can wire those http endpoints to achieve that. Everyone is welcome to contribute this feature to Pulsar. 

> I notice that Pravega will also be presented at Flink Forward in the same room, just after your presentation, perhaps you could get something more face by face :)

Sure. Happy to chat with them.

**Comment by sijie** [comment]
Created the issues for the features you are interested in:

HDFS/Ceph offloader: https://github.com/apache/pulsar/issues/3216
Auto Scaling: https://github.com/apache/pulsar/issues/3217

**Comment by sijie** [comment]
As discussed above, Pulsar already has tiered storage in place. Closed this issue for now. Feel free to create/follow the issues that you are interested in. Contributions are warmly welcome!
