### ISSUE TITLE
Pulsar client should be able to connect to brokers without DNS

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#3218]
Sometimes people doesn't have DNS for brokers. It might be good for people to specify a list of brokers as bootstrap brokers.

Since ` ServiceUrlProvider` was introduced in #2543 , it should be trivial to add a service url provider implementation that randomly returns a chosen broker.

- [x] java pulsar client support multiple hosts #3249 
- [x] pulsar-admin client support multiple hosts
- [x] support multiple hosts for C++ #5780
- [ ] support multiple hosts for python
- [x] support multiple hosts for go
- [x] document using multiple hosts (in concepts and even a page talking about DNS/vips, etc)
- [x] javadoc for serviceURI in builders

**Comment by ivankelly** [comment]
A subtask for this would be to make it possible to use a list of brokers in the proxy client configuration to allow proxy use without dns

**Comment by sijie** [comment]
@ivankelly added the subtasks. however I removed "metadata format" and "proxy". because there is nothing to do at these two parts. If the pulsar client supports a URI with multiple hosts, both metadata format and proxy will be working. However the current most tricky part is pulsar-admin. still figuring out how to do it in jersey client.

**Comment by ivankelly** [comment]
> however I removed "metadata format" and "proxy" 

We should still test these, to ensure they do work. I would even stay we should only test these with multiple addresses, and not with single addresses, as single address is a special case of multiple.

**Comment by jiazhai** [comment]
add a sub task issue for cpp client

**Comment by freeznet** [comment]
go client now support multiple hosts (ref: https://github.com/apache/pulsar-client-go/pull/484)

**Comment by tisonkun** [comment]
@BewareMyPower @baodi @RobertIndie could you check whether client C++ and Python implement this functionality?

**Comment by BewareMyPower** [comment]
@tisonkun Yes, the multiple hosts feature is supported in the C++ client since https://github.com/apache/pulsar/pull/17162 and https://github.com/apache/pulsar/pull/17410.

**Comment by BewareMyPower** [comment]
The Python client support should be ready since the first 3.0.0 release or the 2.11.0 release.

**Comment by tisonkun** [comment]
OK. Then I'm closing the related issues as completed...

**Comment by tisonkun** [comment]
Closed as all subtasks done.
