### ISSUE TITLE
Pulsar Java admin client should work with URL that points to a load balancer

### ISSUE THREAD

**Issue by michael-card** [apache/pulsar#3220]
#### Expected behavior

When creating an instance of the Java Pulsar administrative client like this:

```
admin = PulsarAdmin.builder().serviceHttpUrl(pulsarAdminUrl).build();
```

it should be possible to supply a URL that references a load balancer e.g.

```
http://emodb-pulsar-databus-pulsar-cluster-1:8080
```

#### Actual behavior

If you do this however the admin client cannot communicate correctly with Pulsar and you will get unexepected end-of-file errors when trying to use the admin client to create topics etc. For example, in some of my code I try to create partitioned topics like this:

```
                try {admin.topics().createPartitionedTopic(FULL_MASTER_QUEUE_TOPIC_NAME, NUM_PARTITIONS); } catch (Throwable t) { _log.error("DefaultDatabus.constructor: caught exception " + t.getClass().getName() + " creating " + FULL_MASTER_QUEUE_TOPIC_NAME + ", message = " + t.getMessage());}
                try {admin.topics().createPartitionedTopic(FULL_RESOLVER_QUEUE_TOPIC_NAME, NUM_PARTITIONS); } catch (Throwable t) { _log.error("DefaultDatabus.constructor: caught exception " + t.getClass().getName() + " creating " + FULL_RESOLVER_QUEUE_TOPIC_NAME + ", message = " + t.getMessage());}
                try {admin.topics().createPartitionedTopic(FULL_RESOLVER_RETRY_QUEUE_TOPIC_NAME, NUM_PARTITIONS); } catch (Throwable t) { _log.error("DefaultDatabus.constructor: caught exception " + t.getClass().getName() + " creating " + FULL_RESOLVER_RETRY_QUEUE_TOPIC_NAME + ", message = " + t.getMessage());}
```

and this results in these errors appearing in the logs:

```
WARN  [2018-12-19 16:21:41,643] org.apache.pulsar.client.admin.internal.BaseResource: [http://emodb-pulsar-databus-pulsar-cluster-1:8080/admin/v2/persistent/public/default/master-queue/partitions] Failed to perform http put request: java.net.SocketException: Unexpected end of file from server
ERROR [2018-12-19 16:21:41,643] com.bazaarvoice.emodb.databus.core.DefaultDatabus: DefaultDatabus.constructor: caught exception org.apache.pulsar.client.admin.PulsarAdminException creating public/default/master-queue, message = java.net.SocketException: Unexpected end of file from server
WARN  [2018-12-19 16:21:41,649] org.apache.pulsar.client.admin.internal.BaseResource: [http://emodb-pulsar-databus-pulsar-cluster-1:8080/admin/v2/persistent/public/default/resolver-queue/partitions] Failed to perform http put request: java.net.SocketException: Unexpected end of file from server
ERROR [2018-12-19 16:21:41,649] com.bazaarvoice.emodb.databus.core.DefaultDatabus: DefaultDatabus.constructor: caught exception org.apache.pulsar.client.admin.PulsarAdminException creating public/default/resolver-queue, message = java.net.SocketException: Unexpected end of file from server
WARN  [2018-12-19 16:21:41,654] org.apache.pulsar.client.admin.internal.BaseResource: [http://emodb-pulsar-databus-pulsar-cluster-1:8080/admin/v2/persistent/public/default/resolver-retry-queue/partitions] Failed to perform http put request: java.net.SocketException: Unexpected end of file from server
ERROR [2018-12-19 16:21:41,654] com.bazaarvoice.emodb.databus.core.DefaultDatabus: DefaultDatabus.constructor: caught exception org.apache.pulsar.client.admin.PulsarAdminException creating public/default/resolver-retry-queue, message = java.net.SocketException: Unexpected end of file from server
```

#### Steps to reproduce

1. Set up a Pulsar cluster in AWS
2. Create an ELB for your Pulsar cluster that listens on ports 6650 and 8080
3. Create a Route53 record set that provides an alias that points to your ELB
4. In some Java code use the URL you set up in Route53 to create an admin client
5. Attempt to perform an admin function like creating a topic using your client, you should see an end-of-file exception propagating up from the call
6. Replace the URL that points to the ELB with a URL containing the IP address of one of the Pulsar cluster's broker nodes and use that to create the admin client
7. Now try to create the topic, it should work without errors

#### System configuration
**Pulsar version**: 2.2.0

**Comment by ivankelly** [comment]
@michael-card Are you load balancing traffic to brokers or to proxies?

**Comment by michael-card** [comment]
Hey Ivan I am load balancing traffic to brokers. The target group for my load balancer is the 3 Pulsar broker instances, see attached grab from EC2
![target group](https://user-images.githubusercontent.com/12663894/50248819-e1894b00-03a1-11e9-8a45-8e6aa707c32a.jpeg)

**Comment by michael-card** [comment]
Hey Ivan I am not sure, I see nothing in EC2 Load Balancer info about L3 or L4. Do specific Pulsar brokers "own" topics? In any case the issue here is not with message sending or receiving but only with administrative tasks using the admin client, which seems to be incompatible with load balancers.

**Comment by lxkaka** [comment]
@michael-card I have similar problem.
```
2018-12-20 19:48:04.103 INFO  ConnectionPool:63 | Created connection for pulsar://pulsar-xxx.elb.cn-north-1.amazonaws.com.cn:6650
2018-12-20 19:52:18.582 INFO  ClientConnection:285 | [172.31.40.156:41068 -> 172.31.62.48:6650] Connected to broker
```
As show above the connection stucks for about 4min.

**Comment by ivankelly** [comment]
Are the broker IPs routable from the machine connecting to the load balancer? And vice versa?

**Comment by lxkaka** [comment]
@ivankelly Thanks for the reply. I have found the problem, broker can not connect to the same broker through aws elb.

**Comment by sijie** [comment]
@lxkaka is the problem addressed at your side?

**Comment by lxkaka** [comment]
@sijie the problem was resolved.
