### ISSUE TITLE
Info shown on Dashboard is not accurate

### ISSUE THREAD

**Issue by xinln** [apache/pulsar#3223]
1、按照官网的集群部署搭建集群。
2、通过该命令向消息队列里面发生数据
  bin/pulsar-client produce \
  persistent://public/default/test \
  -n 1 \
  -m "Hello, Pulsar"
3、再通过该命令消费
bin/pulsar-client consume   persistent://public/default/test -s hei 
4、问题一、通过dashboard 访问http://172.19.36.119/admin/stats/topic/
如下面所示出现很多重复的tipic 

TOPIC
--
persistent://public/default/test
persistent://public/default/test
persistent://public/default/test
persistent://public/default/test
问题二、http://172.19.36.119 通过查看的这个地址
访问看到的租户， namespace topic 不一样

**Comment by MarvinCai** [comment]
Translation: 
1、Follow instruction on official cookbook to deploy pulsar cluster.
2、Use command listed below to produce message to a topic 
bin/pulsar-client produce 
persistent://public/default/test 
-n 1 
-m "Hello, Pulsar"
3、Then consume the message through command listed below:
bin/pulsar-client consume persistent://public/default/test -s hei
4、Issue1, visit dashboard at http://172.19.36.119/admin/stats/topic/
It's showing lots of duplicate topic

TOPIC
persistent://public/default/test
persistent://public/default/test
persistent://public/default/test
persistent://public/default/test

Issue2、tenant, namespace and topic shown at http://172.19.36.119 is different(maybe different than what's shown in admin cli?)

**Comment by tuteng** [comment]
Reference https://github.com/apache/pulsar/issues/3226

**Comment by sijie** [comment]
This has been fixed in master.
