### ISSUE TITLE
expect not  restart application after more partitions created

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#3230]
http://pulsar.apache.org/docs/en/admin-api-partitioned-topics.html#update

Already created partitioned producers and consumers can’t see newly created partitions and it requires to recreate them at application so, newly created producers and consumers can connect to newly added partitions as well. Therefore, it can violate partition ordering at producers until all producers are restarted at application.

---

User may would like to do this in a more friendly way, like not restart app.

**Comment by sijie** [comment]
@foreversunyao if @jiazhai has started the work, feel free to pick it up :-)

**Comment by foreversunyao** [comment]
@sijie , for this issue, what I am considering is using zk temporary node when update any partitions for topic, and if creating succeeded , the watch on this temporary node will tell all producer/consumer reconnect this topic , the current producer/consumer will get from api, what do you think about this ?

**Comment by merlimat** [comment]
@foreversunyao producers/consumers are not directly connected to ZK. We have on the roadmap to add support for "system" topics, to be used to send notifications around events happening in the system (eg: new topics created, policies changes, number of partitions changed...).

In absence of that, I think the best approach is to poll periodically from the client.

**Comment by foreversunyao** [comment]
@merlimat If I am not wrong, your point is in the future , client would subscribe the system topics to get the these updates, and each type of update could have its own topic ? and the client could be producer, consumer, and any admin tools.  and only brokers would connect to zk only and get some changes and push to the "system" topics ?

**Comment by merlimat** [comment]
Correct, that will be a general solution for a variety of problems

**Comment by JevonQ** [comment]
> @foreversunyao producers/consumers are not directly connected to ZK.
> 
> We have on the roadmap to add support for "system" topics, to be used to send notifications around events happening in the system (eg: new topics created, policies changes, number of partitions changed...).
> 

@merlimat Is there any schedule for this?

> In absence of that, I think the best approach is to poll periodically from the client.

**Comment by jiazhai** [comment]
@foreversunyao Thanks for looking into this issue. Do you still want to do this?

**Comment by jiazhai** [comment]
Yes, as @sijie mentioned, I am preparing a PR for this. @foreversunyao 
And current approach is to poll periodically from the client.

**Comment by foreversunyao** [comment]
@jiazhai , I don't work on this yet, please go ahead, thanks.
