### ISSUE TITLE
Discuss whether remove JsonRow SerializationSchema and DeserializationSchema

### ISSUE THREAD

**Issue by ambition119** [apache/pulsar#3232]
#### Expected behavior

while I commit PulsarAvroTableSink class found , streaming.connectors.pulsar.serde we can use the native SerializationSchema and DeserializationSchema classes provided by Flink directly. directly use flink-json model classes, maintain consistency and synchronization with Flink.

#### Actual behavior

We rewrote JsonRow SerializationSchema and DeserializationSchema classes ourselves，I think that unnecessary.

If everyone thinks so,  fix this.

tks

**Comment by sijie** [comment]
@ambition119 : 

> directly use flink-json model classes, maintain consistency and synchronization with Flink.

if flink-json supports json schema, that is probably goodl

however I think a better approach is to integrate with pulsar schema directly.

**Comment by ambition119** [comment]
> @ambition119 :
> 
> > directly use flink-json model classes, maintain consistency and synchronization with Flink.
> 
> if flink-json supports json schema, that is probably goodl
> 
> however I think a better approach is to integrate with pulsar schema directly.

flink-json support JsonRowSerializationSchema.java and JsonRowDeserializationSchema.java, integrate with pulsar schema directly [PR #3234 ](https://github.com/apache/pulsar/pull/3234)
