### ISSUE TITLE
Document new rest api - getLastMessageId

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#3233]
We introduced a new rest endpoint `getLastMessageId` at #3196. We should also update the website about this new api

**Comment by sijie** [comment]
we need to add the documentation to http://pulsar.apache.org/docs/en/admin-api-persistent-topics/

**Comment by legendtkl** [comment]
I will do that later.

**Comment by legendtkl** [comment]
refer https://github.com/apache/pulsar/pull/3243
