### ISSUE TITLE
Build error on linux if userid is an huge number

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#3247]
#### Expected behavior

Tell us what should happen

The build passes

#### Actual behavior

ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (package) on project pulsar-presto-connector: Execution package of goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single failed: group id '949000222' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit -> [Help 1]
[ERROR] 

#### Steps to reproduce

On Linux with an user with an huge UID run
`mvn clean install -DskipTests`

#### System configuration
Current master (git sha c3a7d6a89eaf6c7cb1ff226ffc9b7c67bc418bc4)
Linux Fedora 27

**Comment by sijie** [comment]
This is fixed by #3248

**Comment by eolivelli** [comment]
Thank you @sijie

I hope to be able to complete my prototype soon. I am going to replace Kafka :)
