### ISSUE TITLE
can Online Upgraded Version

### ISSUE THREAD

**Issue by hlouf** [apache/pulsar#3254]
#### Expected behavior
i install pulsar2.1.0 ,now i want to online upgraded pulsar2.2.0,how do i do it?
Tell us what should happen

#### Actual behavior

Tell us what happens instead

#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**Pulsar version**: x.y

**Comment by hlouf** [comment]
thanks !!

**Comment by sijie** [comment]
Pulsar maintains backward compatibilities between versions. so it is trivial to upgrade between versions. A typical sequence would be:

- upgrade bookies, probably one by one.
- upgrade brokers

I have an outstanding task on documenting the upgrade sequence. you can check out as an example : https://github.com/apache/pulsar/blob/a8a1453486de6e94a76284503f80c3148bf819c3/site/docs/latest/admin/Upgrade.md

**Comment by hlouf** [comment]
yes ,i test upgrade bookies, one by one.It has now been settled.

**Comment by sijie** [comment]
@hlouf awesome, glad that you figured it out.
