### ISSUE TITLE
[Feature Request] Control the network bandwidth of the broker

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#3280]
#### Network bandwidth in of broker

1. Client send message to broker
2. Read entries from bookie

#### Network bandwidth out of broker

1. Dispatch message to consumer
2. Write entries to bookie

Broker will be the network convergence point. 

User send messages to pulsar will cause broker write entries to bookie, if broker dispatch messages use the high network bandwidth, latency of produce message will becomes higher.

When user consume the cold message(messages is already evict in cache), broker network bandwidth will becomes higher to read entries from bookie, latency of produce message will becomes higher.

So, if we can config dispatch rate in bytes and bookie read rate in bytes limit guarantee that the broker has a certain bandwidth for writing messages.

#### System configuration
**Pulsar version**: 2.2.0

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
