### ISSUE TITLE
[feature request] allow consumers joining in standby state in failover subscription

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#3288]
#### Feature

In streaming applications, when a subscription scales up the consumer group, the new consumers joining the consumer group might be doing expensive operations (e.g. like replaying db or state). In this case, it might be great to let consumer connect in a standby state, when the consumer finishes its application logic, it can then be converted to an normal state and get ready for being elected as an owner for some partitions.

This is a very useful feature for developing stateful streaming applications (e.g. supporting kstreams like application).

**Comment by zwalsh-toast** [comment]
See https://github.com/apache/pulsar/pull/11974

**Comment by tisonkun** [comment]
Closed as stale. May be fixed by #11974.
