### ISSUE TITLE
Connectors and offloaders are not available in download pages

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#3292]
#### Expected behavior

Connectors and offloaders should be available to be downloaded in download page

#### Actual behavior

There is no simple way to find the connectors and offloaders packages.

http://pulsar.apache.org/en/download/

**Comment by legendtkl** [comment]
I can help with this.

@sijie , do you mean the connector and offloader in the path: https://archive.apache.org/dist/pulsar/pulsar-2.2.0/ , ie apache-pulsar-io-connectors-2.2.0-bin.tar.gz   and apache-pulsar-offloaders-2.2.0-bin.tar.gz

**Comment by sijie** [comment]
@legendtkl sorry for late response. Yes, I mean adding connector and offloader to the pulsar's download page.

**Comment by sijie** [comment]
This has been fixed.
