### ISSUE TITLE
Could Subscription filter message for consumer 

### ISSUE THREAD

**Issue by vincent-pli** [apache/pulsar#3302]
#### Expected behavior
Subscription could filter message for consumer
Tell us what should happen
For example, certain user only care about message for himself, then he want filter all message and only get message specific for him based on one properties in the message, guess it's "user_id".
#### Actual behavior
Seems not support

#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**Pulsar version**: x.y

**Comment by sijie** [comment]
@vincent-pli : currently it is not supported yet. One solution is to use pulsar functions. You can write a pulsar function to filter the messages by user_id and route the messages to user's own topic.

**Comment by vincent-pli** [comment]
Thanks for your reply, I want to know if creating/delete topic in run time is expensive or not.
If it's cheap, I can adopt the pulsar function, thanks

**Comment by sijie** [comment]
> I want to know if creating/delete topic in run time is expensive or not.

Creating and deleting topics should be relatively cheap. However one thing to be kept in mind is that the number of topics that a single Pulsar cluster can support is bounded by how much metadata your zookeeper cluster can store for Pulsar. If you are going down into this approach, you might need to do a capacity plan to figure out how many of per-user-id topics you need.

**Comment by vincent-pli** [comment]
Got it, many thanks
