### ISSUE TITLE
[Question] A few questions on using Pulsar in different scenarios

### ISSUE THREAD

**Issue by JevonQ** [apache/pulsar#3303]
1. How to configure the pulsar protocol url for a pulsar instance?
Suppose I have a pulsar instance which consists of 3 pulsar clusters(C1, C2, C3), each cluster has one broker(B1, B2, B3), each broker manages one topic (T1, T2, T3). If I use DNS as service discovery method, how should I set the pulsar protocol url in order to allow pulsar client to create subscriptions on T1, T2 and T3? Per my understanding, the url should not point to one of the broker(B1, B2, B3), right? It must point to a service that has access to the metadata in pulsar instance level. But I cannot figure out what it is.

2. For a single cluster environment, if I use the built-in discovery service, what address should I use for web-service-url and broker-service-url while executing initialize-cluster-metadata?

**Comment by sijie** [comment]
@JevonQ 

If you have a DNS for your brokers, your pulsar service url would be:

- web service url : http://<dns>:8080/
- broker service url: pulsar://<dns>:8080/

**Comment by JevonQ** [comment]
@sijie Thanks for your reply, but I'm still not clear. 

For the multi-clusters environment like I given in my previous question, suppose I have a domain name named pulsar.east-china.com which is provided for pulsar client to use, so how should I set the A record in DNS server for pulsar.east-china.com? I don't think it can work if I config DNS as follows:
pulsar.east-china.com    IN  A  B1-ip-address
pulsar.east-china.com    IN  A  B2-ip-address
pulsar.east-china.com    IN  A  B3-ip-address

That's because none of brokers has the instance-wide metadata. Let's think of this case, if a pulsar client is created with pulsar.east-china.com and the DNS server return B2-ip-address to the client, then it will make a connection with B2. If the client continue to create a Consumer on T3 which is owned by B3, B2 will not find the topic and return an error?

For a single cluster environment, if I use the built-in discovery service, what address should I use for web-service-url and broker-service-url while executing initialize-cluster-metadata?

**Comment by sijie** [comment]
oh sorry, I misunderstood your question.

* for multiple cluster case:

> Suppose I have a pulsar instance which consists of 3 pulsar clusters(C1, C2, C3), each cluster has one broker(B1, B2, B3), each broker manages one topic (T1, T2, T3). 

I am not sure what do you want to achieve here. can you describe a bit more your use case?
Are you going to create a *global* cluster of C1, C2, C3? or do you want to ensure data is replicated across multiple clusters?

* for simple cluster environment

technically, the web-service-url and broker-service-url in a single cluster is not really used. those service urls are needed when you have more clusters and want to do geo-replication between clusters. You need to tell what are the service urls for each cluster. So in that sense, people are using DNS of the brokers for the web-service-url and broker-service-url.

**Comment by JevonQ** [comment]
> * for multiple cluster case:
> 
> > Suppose I have a pulsar instance which consists of 3 pulsar clusters(C1, C2, C3), each cluster has one broker(B1, B2, B3), each broker manages one topic (T1, T2, T3).
> 
> I am not sure what do you want to achieve here. can you describe a bit more on your use case?
> Are you going to create a _global_ cluster of C1, C2, C3? or do you want to ensure data is replicated across multiple clusters?
> 
Yes, I want to create a multi-cluster instance without replication among themselves and allow users to access the topic within each cluster. I cannot figure out a way to achieve this.

> * for simple cluster environment
> 
> technically, the web-service-url and broker-service-url in a single cluster is not really used. those service urls are needed when you have more clusters and want to do geo-replication between clusters. You need to tell what are the service urls for each cluster. So in that sense, people are using DNS of the brokers for the web-service-url and broker-service-url.
But pulsar client also use service url to establish a connection and do the topic lookup, does that mean I need to set the url address to the node ip where the pulsar discovery process run? Also, if I need the fault tolerance on the discovery, I need to run several discovery processes and provide an single ip like vip over them. What is the best practice for that?

**Comment by sijie** [comment]
> Yes, I want to create a multi-cluster instance without replication among themselves and allow users to access the topic within each cluster. I cannot figure out a way to achieve this.

if it is "multi-cluster" instance without replication, then each cluster is a separate cluster. You have to manage which topic in which cluster.

Alternatively, you can setup a "global" instance, which requires a "global" zookeeper that spreads across multiple physical locations. In this way, pulsar will be acting as a "whole" system and managing the topic assignments. 

> does that mean I need to set the url address to the node ip where the pulsar discovery process run? 

If you want to setup additional discovery service, then the service urls are the DNS of the discovery service nodes and you have to run several processes for fault tolerance.

However you don't have to do so, broker already offers discovery. If you have DNS or load balancer for your brokers, you can just use that DNS in the service urls.

**Comment by JevonQ** [comment]
> > Yes, I want to create a multi-cluster instance without replication among themselves and allow users to access the topic within each cluster. I cannot figure out a way to achieve this.
> 
> if it is "multi-cluster" instance without replication, then each cluster is a separate cluster. You have to manage which topic in which cluster.
> 
> Alternatively, you can setup a "global" instance, which requires a "global" zookeeper that spreads across multiple physical locations. In this way, pulsar will be acting as a "whole" system and managing the topic assignments.

The global zookeeper has the global view of all topic assignments, every broker will have the view cached locally? Does that mean the pulsar client can get find which broker hosts the topic via every broker?

BTW, for the zookeeper pulsar uses, is it the official versioned zookeeper or a modified versioned zookeeper? I mean if we already have a zookeeper available, can we just use it as the local zookeeper or global zookeeper for pulsar?
> 
> > does that mean I need to set the url address to the node ip where the pulsar discovery process run?
> 
> If you want to setup additional discovery service, then the service urls are the DNS of the discovery service nodes and you have to run several processes for fault tolerance.
> 
> However you don't have to do so, broker already offers discovery. If you have DNS or load balancer for your brokers, you can just use that DNS in the service urls.

**Comment by sijie** [comment]
>  Does that mean the pulsar client can find which broker hosts the topic via any broker?

yes.

all the brokers registered under same zookeeper instance will learn how topics are assigned to the broker. so when pulsar client connects to any broker, it will discover the right owner broker of the topic and then establish the connection with owner broker.

>  is it the official versioned zookeeper or a modified versioned zookeeper?

yes you can use your own zookeeper.

**Comment by JevonQ** [comment]
@sijie Appreciate you for all the replies, you help me a lot.
