### ISSUE TITLE
tlsEnabled not respected in broker or proxy

### ISSUE THREAD

**Issue by ivankelly** [apache/pulsar#3330]
#2988 added a change that deprecated tlsEnabled, so now tls can only be enabled via setting webServicePortTls and brokerServicePortTls. 

Deprecation shouldn't mean break though. It should mean, we will break this in the future. If tlsEnabled is set, we should set webServicePortTls and brokerServicePortTls to the default values.

**Comment by ivankelly** [comment]
cc @jai1

**Comment by ivankelly** [comment]
Also, this change breaks the documentation

**Comment by sijie** [comment]
@ivankelly is there anything we can do here? Or shall we just close the issue?

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant in maintained versions.
