### ISSUE TITLE
namespaces grant-permission should accept comma separated roles

### ISSUE THREAD

**Issue by ivankelly** [apache/pulsar#3331]
```
bin/pulsar-admin namespaces grant-permission --role user1,proxy --actions produce,consume my-tenant/ns1
```
should grant permissions to user1 & proxy, no a non-existant user 'user1,proxy'.

**Comment by sijie** [comment]
This feature has been implemented in the golang CLI pulsarctl - https://github.com/streamnative/pulsarctl
