### ISSUE TITLE
Proxy shouldn't require both brokerWebServiceURL & brokerServiceURL if http is being used for lookup

### ISSUE THREAD

**Issue by ivankelly** [apache/pulsar#3343]
This is in the context of configuring a proxy to not use ZK. Rather than requiring that the use specify the brokerServiceURL, if there is a brokerWebServiceURL specified, we should fallback to that and do http lookup.

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.
