### ISSUE TITLE
brokerWebServiceURL should not be required in proxy conf

### ISSUE THREAD

**Issue by ivankelly** [apache/pulsar#3351]
It's a perfectly valid usecase to only want the proxy to be used for produce and consume traffic, and to only allow admin requests from inside the pulsar cluster. However, currently if URL based configuration is being used (i.e. zk is not configured), then brokerWebServiceURL is required. 

Update docs(http://pulsar.apache.org/docs/en/administration-proxy/) when this is fixed to note that not all URLs need to be configured.

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.
