### ISSUE TITLE
Kafka configure properties are not included subscription type and subscription mode

### ISSUE THREAD

**Issue by sautran** [apache/pulsar#3361]
I am trying to use the latest pulsar release to migrate current kafka client to pulsar and try to use the kafka pulsar wrapper.

I am using non-persistent topic,
in the kafka pulsar client config, Following is the default
"subscriptionTopicsMode" : "PERSISTENT", 
 "subscriptionType" : "Failover",

Is there anyway to set subscriptionTopicsMode and subscriptionType through the kafka configuration properties map?

**Comment by merlimat** [comment]
I agree that `subscriptionTopicsMode` should be configurable. Though I believe `subscriptionType` can only be `Failover`, since Kafka API has no option to do individual acknowledge of messages.

**Comment by sautran** [comment]
For the subscriptionType, right now our kafka application have a few consumers using the same group.id on a partitioned topic.  Each consumer reads some partitions. My question is in Pulsar,  if one consumer die, are other consumers taking those partitions over?

**Comment by sautran** [comment]
Thanks, Guys.
