### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal base64 character 2d

### ISSUE THREAD

**Issue by sautran** [apache/pulsar#3362]
I am using kafka api, the topic is persistent and partitioned topic, in the java consumer, the consumer.poll method  throws the following exception
java.lang.IllegalArgumentException: Illegal base64 character 2d
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at org.apache.kafka.clients.consumer.KafkaConsumer.getKey(KafkaConsumer.java:364)

In the producer, the key is "tenant-4",
 final ProducerRecord<String, byte[]> data = new ProducerRecord<>(
                    "persistent://public/default/abc", "tenant-4", outStream.toByteArray());

In the pulsar admin api  /pulsar-client consume,  the message is displayed.

**Comment by merlimat** [comment]
@sautran The code there should be like : 

```java
 private K getKey(String topic, Message<byte[]> msg) {
        if (!msg.hasKey()) {
            return null;
        }

        if (keyDeserializer instanceof StringDeserializer) {
            return (K) msg.getKey();
        } else {
            // Assume base64 encoding
            byte[] data = Base64.getDecoder().decode(msg.getKey());
            return keyDeserializer.deserialize(topic, data);
        }
    }
```

Did you set the `StringDeserializer` for the key?

**Comment by merlimat** [comment]
(Above code was taken from https://github.com/apache/pulsar/blob/ef82f045257ae839c0208c75b1b31ba0ad6693aa/pulsar-client-kafka-compat/pulsar-client-kafka/src/main/java/org/apache/kafka/clients/consumer/PulsarKafkaConsumer.java#L382 )

**Comment by sautran** [comment]
@merlimat , yes, I set the key as StringSerializer
props.put("key.serializer", 
                StringSerializer.class.getName());

**Comment by merlimat** [comment]
This error is coming from consumer, so it should be the `StringDeserializer` there

**Comment by sautran** [comment]
Ok. I set the consumer 
     props.put(KafkaKeys.VALUE_DESERIALIZER, 
                ByteArrayDeserializer.class.getName());
        props.put(KafkaKeys.KEY_DESERIALIZER, 
                StringDeserializer.class.getName());
in producer, I have the same setting but it is the serializer.

now I am getting the following error in the pulsar server:
14:16:27.791 [pulsar-io-49-12] WARN  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:51545] Got exception IndexOutOfBoundsException : writerIndex: 1179652 (expected: readerIndex(4) <= writerIndex <= capacity(20))
java.lang.IndexOutOfBoundsException: writerIndex: 1179652 (expected: readerIndex(4) <= writerIndex <= capacity(20))
	at io.netty.buffer.AbstractByteBuf.writerIndex(AbstractByteBuf.java:118) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at org.apache.pulsar.common.api.PulsarDecoder.channelRead(PulsarDecoder.java:83) ~[org.apache.pulsar-pulsar-common-2.2.1.jar:2.2.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:649) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:584) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by merlimat** [comment]
This seems like it's trying to connect the Pulsar service using HTTP?  What service url did you specify?

**Comment by sautran** [comment]
I set bootstrap.servers  pulsar://localhost:6650 in the properties

**Comment by merlimat** [comment]
Ok, that's strange. Can you also include the client logs?

**Comment by sautran** [comment]
Consumer log:


20190111.142908.328 INFO  [org.apache.kafka.clients.consumer.ConsumerConfig] ConsumerConfig values: 
	auto.commit.interval.ms = 5000
	auto.offset.reset = latest
	bootstrap.servers = [pulsar://localhost:6650]
	check.crcs = true
	client.id = 
	connections.max.idle.ms = 540000
	enable.auto.commit = false
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = 222
	heartbeat.interval.ms = 3000
	interceptor.classes = null
	key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.ms = 50
	request.timeout.ms = 305000
	retry.backoff.ms = 100
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
 - 
20190111.142908.474 WARN  [org.apache.kafka.clients.consumer.ConsumerConfig] The configuration 'AAA' was supplied but isn't a known config. - 
20190111.142908.475 WARN  [org.apache.kafka.clients.consumer.ConsumerConfig] The configuration 'BBB' was supplied but isn't a known config. - 
20190111.142908.475 WARN  [org.apache.kafka.clients.consumer.ConsumerConfig] The configuration 'thread_number' was supplied but isn't a known config. - 
20190111.142908.475 WARN  [org.apache.kafka.clients.consumer.ConsumerConfig] The configuration 'socket.timeout.ms' was supplied but isn't a known config. - 
20190111.142908.477 INFO  [org.apache.kafka.common.utils.AppInfoParser] Kafka version : 0.10.2.1 - 
20190111.142908.477 INFO  [org.apache.kafka.common.utils.AppInfoParser] Kafka commitId : e89bffd6b2eff799 - 
20190111.143140.410 INFO  [org.apache.kafka.clients.consumer.ConsumerConfig] ConsumerConfig values: 
	auto.commit.interval.ms = 5000
	auto.offset.reset = latest
	bootstrap.servers = [pulsar://localhost:6650]
	check.crcs = true
	client.id = 
	connections.max.idle.ms = 540000
	enable.auto.commit = false
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = 222
	heartbeat.interval.ms = 3000
	interceptor.classes = null
	key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.ms = 50
	request.timeout.ms = 305000
	retry.backoff.ms = 100
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
 - 
20190111.143140.575 WARN  [org.apache.kafka.clients.consumer.ConsumerConfig] The configuration 'AAA' was supplied but isn't a known config. - 
20190111.143140.575 WARN  [org.apache.kafka.clients.consumer.ConsumerConfig] The configuration 'BBB' was supplied but isn't a known config. - 
20190111.143140.575 WARN  [org.apache.kafka.clients.consumer.ConsumerConfig] The configuration 'thread_number' was supplied but isn't a known config. - 
20190111.143140.575 WARN  [org.apache.kafka.clients.consumer.ConsumerConfig] The configuration 'socket.timeout.ms' was supplied but isn't a known config. - 
20190111.143140.578 INFO  [org.apache.kafka.common.utils.AppInfoParser] Kafka version : 0.10.2.1 - 
20190111.143140.582 INFO  [org.apache.kafka.common.utils.AppInfoParser] Kafka commitId : e89bffd6b2eff799 - 

Producer log:

20190111.142849.112 INFO  [org.apache.kafka.clients.producer.ProducerConfig] ProducerConfig values: 
	acks = 1
	batch.size = 16384
	block.on.buffer.full = false
	bootstrap.servers = [pulsar://localhost:6650]
	buffer.memory = 33554432
	client.id = 
	compression.type = lz4
	connections.max.idle.ms = 540000
	interceptor.classes = null
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	linger.ms = 0
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.fetch.timeout.ms = 60000
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 0
	retry.backoff.ms = 100
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	timeout.ms = 30000
	value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
 - 
20190111.142849.263 INFO  [org.apache.kafka.common.utils.AppInfoParser] Kafka version : 0.10.2.1 - 
20190111.142849.263 INFO  [org.apache.kafka.common.utils.AppInfoParser] Kafka commitId : e89bffd6b2eff799 -

**Comment by sautran** [comment]
i am running local standalone mode. I already removed the data and logs directory, server still kept throwing this error. What files/directory do I need to delete to do the fresh restart.?

**Comment by jiazhai** [comment]
As @murong00 point out this is a dup to #3369, @sautran  will close this issue for the dup.

**Comment by jiazhai** [comment]
Seems another user reported a similar issue of `java.lang.IllegalArgumentException: Illegal base64 character 2d`.

This looks more like a convert issue between protobuf string (optional string partition_key   = 6) to bytes.

**Comment by sijie** [comment]
@jiazhai can you start a PIP discussion? I am in favor of making the partition key to bytes. but we need to think about the backward compatibility issue.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
