### ISSUE TITLE
Dashboard docker shows no data

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#3367]
**Describe the bug**
Some user reported that Dashboard docker  shows no data by following instruction of [dashboard](http://pulsar.apache.org/docs/en/administration-dashboard.html#docsNav)

**To Reproduce**
1. following instruction of [dashboard](http://pulsar.apache.org/docs/en/administration-dashboard.html#docsNav) to start docker.

**Expected behavior**
dashboard could show data

**Screenshots**
![image](https://user-images.githubusercontent.com/6348208/51119765-a4a05f00-184e-11e9-87da-a501ea007ea9.png)
![image](https://user-images.githubusercontent.com/6348208/51119774-ab2ed680-184e-11e9-9d67-ab51323265ae.png)
![image](https://user-images.githubusercontent.com/6348208/51119777-ae29c700-184e-11e9-9c8e-a3d04a61bd6f.png)

**Desktop (please complete the following information):**

**Comment by foreversunyao** [comment]
@jiazhai could show after have some prouder or consumer ran for the topics ? looks like the data comes from the stats api

**Comment by jiazhai** [comment]
@foreversunyao  asked one usr that reported a similar issue, this could be fixed by setting advertisedAddress for both `broker.conf` and `bookkeeper.conf`.
```
# Hostname or IP address the service advertises to the outside world. If not set, the value of InetAddress.getLocalHost().getHostName() is used.
advertisedAddress=
```

**Comment by sijie** [comment]
@jiazhai is this resolved by setting `advertisedAddress`?

**Comment by sijie** [comment]
Closed it since it is related to advertisedAddress.
