### ISSUE TITLE
What's purpose of ackId when publishing to a topic ? 

### ISSUE THREAD

**Issue by kamal-brill** [apache/pulsar#3382]
**Describe the bug**
When we publish the message to a topic, it returns an `ackId`. What's the purpose of that `ackId` ? Can we use it to retrieve the particular message using any REST or WebSocket API ?

**To Reproduce**
1. Go to WebSocket API Documentation page.
2. Run the Node.js Producer and Reader examples.
3. Send message from producer, it returns an unique "ackId" for each message that's published.

**Expected behavior**
There should be an REST API or WebSocket API available for retrieving the message and it's metadata.

**Desktop (please complete the following information):**
 - OS: Docker

**Comment by sijie** [comment]
@kamal-brill ackId (aka message id) is used for consumer to acknowledge it has received and processed the message. once a message is acknowledged, the message will not be delivered again. You can read the documentation here: http://pulsar.apache.org/docs/en/concepts-messaging/#acknowledgement
