### ISSUE TITLE
[Go Client] - Add ability to send an atomic batch

### ISSUE THREAD

**Issue by imaramos** [apache/pulsar#3388]
**Is your feature request related to a problem? Please describe.**
In this moment we can't produce/send an atomic batch throught de client. 
Currently the producer batching is a buffer that is flushed according with batching configs. The problem is that we can loose the messages order, if some fails.

**Describe the solution you'd like**
I would like to have  a method to send an atomic batch.

**Describe alternatives you've considered**
An alternative could be adding a flush method that gives more control to the client, having the ability to flush the buffer when desired. I dont know if it solves the problem since in concurrent requests, one could flush the messages from the other.

**Comment by imaramos** [comment]
@tuan6956 I didnt understand, can you detail please?

**Comment by tuan6956** [comment]
it mean that can i batch acknowledge message?
Ex: acknowledge message 1 ->10 in one time

**Comment by imaramos** [comment]
@tuan6956 Sorry I thought you were giving a suggestion to my problem. You can achieve that with cumulative ack I assume, at least in the exclusive subscription.
