### ISSUE TITLE
pulsar-daemon start broker without setting mandatory parameter failed without any errors

### ISSUE THREAD

**Issue by foreversunyao** [apache/pulsar#3390]
**Describe the bug**
for the **./pulsar-daemon start broker** command, the mandatory configuration like **zookeeperServers**, **configurationStoreServers** and **clusterName** are not check in the code .

**To Reproduce**
1.  remove the **zookeeperServers** or **configurationStoreServers** or **clusterName** in broker.conf
2. ./pulsar-daemon start broker
3. broker start failed without any errors

**Expected behavior**
pulsar broker start failed with errors like," no configuration for **zookeeperServers** or **configurationStoreServers** or **clusterName**, start failed"

**Screenshots**
no
**Desktop (please complete the following information):**
pulsar version 2.2.1

**Additional context**

**Comment by foreversunyao** [comment]
looks like https://github.com/apache/pulsar/blob/master/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java#L104 , **brokerServicePort** has no "required" attributes, so it will prompt an **java.lang.NullPointerException** exception, and don't do any check further .

**Comment by murong00** [comment]
@foreversunyao In fact, the parameters have been checked but the error log is not printed as expected (see https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/PulsarBrokerStarter.java#L277). I replaced this line by following:
`System.out.println(">>>" + String.format("Uncaught exception in thread %s: %s", thread.getName(), exception.getMessage()));`
it printed the log as expected in pulsar-broker-$broker.out as below:
`>>>Uncaught exception in thread main: Required zookeeperServers is null,Required clusterName is null`

**Comment by murong00** [comment]
@sijie How do you think about this, should we print the exception in stack trace?

**Comment by foreversunyao** [comment]
@murong00 ,you mean even it failed at here, it will continue the for loop , https://github.com/apache/pulsar/blob/master/pulsar-broker-common/src/main/java/org/apache/pulsar/common/configuration/PulsarConfigurationLoader.java#L133 . ?

**Comment by murong00** [comment]
@foreversunyao yeah, it continues the for loop and appends all required fields error then throws it .

**Comment by foreversunyao** [comment]
@murong00 I could be wrong, but what I tested is **loop** would break when it met the first error , anything I could miss ?

**Comment by foreversunyao** [comment]
found another two places would have same issues like **PulsarBrokerStarter.java**, 
shall I update them in the same time with a new issue for all of them ?

- 1, https://github.com/apache/pulsar/blob/master/pulsar-discovery-service/src/main/java/org/apache/pulsar/discovery/service/server/DiscoveryServiceStarter.java#L53

- 2, https://github.com/apache/pulsar/blob/master/pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyServiceStarter.java#L71

**Comment by sijie** [comment]
@foreversunyao I think if you can fix them at the same pull request, that would be great!
