### ISSUE TITLE
Add missing methods to SinkContext & SourceContext interfaces

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#3396]
**Is your feature request related to a problem? Please describe.**
I would like it if the Context objects for Pulsar Sinks & Sources had the same methods defined as the Context object for Pulsar functions, 
https://github.com/apache/pulsar/blob/master/pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Context.java

**Describe the solution you'd like**
Make the following context objects interface definitions as close as practical to the functions context interface to provide some level of consistency when developing them

https://github.com/apache/pulsar/blob/master/pulsar-io/core/src/main/java/org/apache/pulsar/io/core/SinkContext.java &

https://github.com/apache/pulsar/blob/master/pulsar-io/core/src/main/java/org/apache/pulsar/io/core/SourceContext.java interfaces

 e.g. Logger getLogger(); is missing from Sink & Source

**Comment by jerrypeng** [comment]
@david-streamlio we can add some the methods from Function Context to Sink/Source Context.  However, there is a major difference between Function Context and Sink/Source Context.  Function Context is meant context for the message currently being processed while Sink/Source Context provide general context for the Sink and Source in general.

**Comment by david-streamlio** [comment]
That's fine, just add a subset that makes sense, which would include the getLogger() method

**Comment by sijie** [comment]
This is fixed by #3397
