### ISSUE TITLE
Documentation: Pulsar functions difference between thread and process mode

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#3400]
**Describe the bug**
Document: pulsar functions lack of introduction for the difference between thread mode and process mode

**To Reproduce**
No introduce of these in docs of functions:
http://pulsar.apache.org/docs/en/functions-overview.html#docsNav

**Additional context**
thread mode: one function is running in thread mode, and running on same jvm with function worker;
process mode: one function is running in process mode, and running on same machine that function worker runs;

**Comment by Jennifer88huang** [comment]
@sijie @jiazhai I have two questions on this:
1. Is it OK to refine the description as follows?
- Thread mode: when a function runs in thread mode, it runs on the same Java virtual machine (JVM) with Functions worker.
- Process mode: when a function runs in process mode, it runs on the same machine that Functions worker runs.

2. What's the most proper place to add the content in "overview"? Shall we add a new section? It seems that the content is a little too simple for a new section.

**Comment by sijie** [comment]
@Jennifer88huang 

You description for question 1 is correct. 

For your second question, add a section for runtime. You can collect the information from runtime page and add clarifications.

**Comment by Jennifer88huang** [comment]
@sijie Thank you very much for your advice.
Maybe it's good idea to add the differences in [Configure Functions runtime](http://pulsar.apache.org/docs/en/functions-runtime/).
![image](https://user-images.githubusercontent.com/47805623/62001810-2ab92e80-b12b-11e9-8895-385294d16613.png)

**Comment by sijie** [comment]
sgtm

**Comment by Jennifer88huang** [comment]
Update those two PRs.
