### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by bputt** [apache/pulsar#3404]
**Is your feature request related to a problem? Please describe.**
We're looking to use pulsar and are having issues which should be addressed in a newer release (2.3) and would really like to download a nightly build so we can develop towards that

**Describe the solution you'd like**
A nightly build that we can download

**Describe alternatives you've considered**
I've attempted to use your build/docker and it fails, seems to be an issue with one of the curl commands inside the Dockerfile. I can certainly build it outside of docker, but a nightly build would be more efficient ;)

**Additional context**
Just looking to try out the latest code to help fix current issues while we wait for official releases

**Comment by sijie** [comment]
@bputt we published the nightly build to maven artifacts - (apache snapshot repository) 

https://repository.apache.org/content/repositories/snapshots/org/apache/pulsar/

are you looking for a client fix or a broker side fix?

**Comment by bputt** [comment]
broker side, more or less, when downloading the tar.gz from pulsar's website

**Comment by sijie** [comment]
Question is answered. So closed this issue.
