### ISSUE TITLE
pulsar golang error

### ISSUE THREAD

**Issue by chowyu08** [apache/pulsar#3408]
when client connect pulsar broker:
**Describe the bug**
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_function_call> >'
  what():  call to empty boost::function
```

 - OS: ubuntu16.04
- golang: 1.11

**Comment by merlimat** [comment]
@chowyu08 This looks like an empty callback object being passed. Can you describe a bit more how to reproduce this error? 

Also, can you get a stack trace from gdb? That would be helpful.

**Comment by sijie** [comment]
@chowyu08 any more context about this issue?
