### ISSUE TITLE
some thoughts about [pulsar-client-go]

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar#3417]
1. The go community provides some good libraries, which can help us save a lot of development work, as follows:

- log: [logrus](https://github.com/Sirupsen/logrus)
- error: [error](https://github.com/juju/errors)
- test: [test](https://github.com/stretchr/testify)
- so on

2. We can encapsulate a `check.sh` script to help us check some of Go's naming conventions, annotation specifications, etc. I recommend using [gometalinter](https://github.com/alecthomas/gometalinter).

3. When we introduce the external package required by the project, we can use the go official package management tool `dep` or `go mod` to help us.

**Comment by merlimat** [comment]
@wolfstudy All good points. Do you plan to get started on these tasks?

**Comment by wolfstudy** [comment]
yes, if it is possible, I will implement the above ideas in the next time.
