### ISSUE TITLE
Pulsar 2.2.1 compile fails

### ISSUE THREAD

**Issue by ambud** [apache/pulsar#3420]
**Describe the bug**
Pulsar compile from source is failing with jcloud issues `org.jclouds does not exist`
`Apache Pulsar :: Tiered Storage :: JCloud .......... FAILURE`

Please note that specific project build like `mvn clean compile -pl pulsar-broker` succeeds.

**To Reproduce**
```
git clone https://github.com/apache/pulsar.git
cd pulsar
git checkout v2.2.1
mvn clean compile
```

**Expected behavior**
Compile should succeed without any failures.

**Screenshots**
- 

**Desktop (please complete the following information):**
 - osx-x86_64 10.14.2
 - Java 1.8_181
 - Maven: 3.5.4

**Comment by merlimat** [comment]
that should work with `mvn install -DskipTests`. There are some of the dependencies between modules that fail in maven when not installing the artifacts
