### ISSUE TITLE
GKE unschedulable pods error

### ISSUE THREAD

**Issue by shrikant-pa** [apache/pulsar#3421]
I tried to deploy pulsar on google kubernetes engine. Everything is running except bookkeeper and prometheus. It is giving Your cluster has 2 unschedulable pods error. 

pod has unbound PersistentVolumeClaims (repeated 3 times) for both bookkeeper an prometheus. 

#### Steps to reproduce
1. Setup GKE 
2. Select n1-standard-8
3. Local SSD 2
4. Download Pulsar version 2.2.1 src 
5. Deploy from google-kubernetes folder

**Comment by aahmed-se** [comment]
how many nodes is the cluster have you tried the pulsar helm ?

**Comment by shrikant-pa** [comment]
3 nodes with auto scaling enabled unto 6.

**Comment by shrikant-pa** [comment]
Below are the details through screenshots. 

![gke](https://user-images.githubusercontent.com/43746656/51701579-ba94e900-1fdf-11e9-948d-40cadb8f2366.jpg)

![image](https://user-images.githubusercontent.com/43746656/51701452-7a356b00-1fdf-11e9-893c-efc13b4606ee.jpg)

**Comment by sijie** [comment]
@shrikant-pa "unscheduled pod" typically due to lack of resources. I would suggest you double-checking if you have enough resources.

**Comment by shrikant-pa** [comment]
So i was able to resolve both the issues. Below are the details. 

Error 1: 
`Warning  ProvisioningFailed  4m (x382 over 1h)  persistentvolume-controller  Failed to provision volume with StorageClass "bookie-ssd": kubernetes does not have a node in zone "us-east1-b"`

Solution: 
Modify the bookie.yaml file in google kubernetes folder. Comment the `zones: us-east1-b ` as it is hard coded and my cluster was created in different zone  and change ` cluster: us-east` to ` cluster: pulsar-gke`

Error 2: 
`Warning  ProvisioningFailed  3m (x382 over 1h)  persistentvolume-controller  storageclass.storage.k8s.io "ssd" not found`

Solution: 
Modify monitoring.yaml change `storageClassName: ssd` to available storage class.
