### ISSUE TITLE
Add configuration properties to limit the automatic creation of topics.

### ISSUE THREAD

**Issue by bilahepan** [apache/pulsar#3436]
**Describe**
When Pulsar client creates a producer or consumer, it first gets partition-metadata.
If partition-metadata is not queried, and the topic does not exist, the broker will automatically create a non-partition topic.

**Describe the solution you'd like**
 Add configuration parameters which can limit the broker to automatically create a non-partition topic.

#issue-number

**Comment by bilahepan** [comment]
#3430  is related

**Comment by ConcurrencyPractitioner** [comment]
Ok, I have a pretty good idea on how to add these configuration parameters. I would be able to submit a PR pretty soon. :)

**Comment by sijie** [comment]
This is fixed by #3450
