### ISSUE TITLE
Support Time Index to support seeking based on time in reader interface. 

### ISSUE THREAD

**Issue by skyrocknroll** [apache/pulsar#3446]
**Is your feature request related to a problem? Please describe.**
Right now we can seek to earliest or latest. But we are not able seek based on time in the reader interface. 

**Describe the solution you'd like**
In the reader interface, we can support time-based seek along with earliest and latest?

**Describe alternatives you've considered**
We are thinking of randomly picking a message id and trying to go to the nearest specified time by incrementing the ID.

**Comment by jiazhai** [comment]
Thanks for point out, this is a good feature to have.

**Comment by ivankelly** [comment]
One problem here would be that timestamps on messages aren't necessarily monotonically increasing, but there is a plan to fix that.
