### ISSUE TITLE
Tag Pulsar ledgers in order to distinguish from other ledgers in the same Bookkeeper cluster

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#3458]
**Is your feature request related to a problem? Please describe.**
I need a way to distinguish Pulsar ledgers from ledgers created by other applications.

**Describe the solution you'd like**
An idea to solve the problem in the short term is to add some "custom metadata" on every ledger created by Pulsar.
It would be good to add metadata to link the ledger to the owner component in Pulsar (topic...)

**Describe alternatives you've considered**
We can start on BookKeeper a new feature to add a (optional) "Application Type" client configuration which would be written to Ledgers metadata.
This can be a better solution in the mid term but it requires more coordination with BookKeeper community and it can happen before BookKeeper 4.10.
My need is to have such tags for Pulsar + BookKeeper 4.9.

**Comment by eolivelli** [comment]
@merlimat  @sijie  @ivankelly  how does this sounds to you ?

**Comment by jiazhai** [comment]
@eolivelli Would you mind share a little about How the tag will be used?

**Comment by ivankelly** [comment]
While you're at it, you could change managed ledger to use WriteHandle. It already uses ReadHandle in the read path.

**Comment by eolivelli** [comment]
@jiazhai  @ivankelly these tags in my case are only for debug/ops.

When an operator (using an automatic tool) looks at the contents of BookKeeper he must be able to understand which application/sub-system created the ledger.
Especially the case is for orphan ledgers, the application creates the ledger then it crashes and so there is no track of that ledger, it will remain forever on metadata.

**Comment by eolivelli** [comment]
@ivankelly 

> While you're at it, you could change managed ledger to use WriteHandle. It already uses ReadHandle in the read path.

I can do this change but I guess it will be a different patch, I did not look at Pulsar write path yet but if it is using the old API it will be using callbacks and not CompletableFuture.
I will be happy to contribute a patch

**Comment by eolivelli** [comment]
@jiazhai @ivankelly  Am I in time to send a patch at least for the new custom metadata and have it in the new release of Pulsar ?
I am asking just to know if I have to work on this as soon as possible or I will eventually see mu change within months.
AFAIK the new Pulsar release is just waiting for BK 4.9 and this will happen very soon (hopefully)


thanks

**Comment by sijie** [comment]
Enrico, yes, you are still in time for a patch for adding tags for ledger metadata. Agreed that changing to WriteHandle should be in a separate patch. It would be great if you can create a GitHub issue, so that people in the community can pick it up at their convinience.

**Comment by eolivelli** [comment]
Another question: 
Should I add a flag?
Custom metadata are there aince bk 4.5, so there should not be a real compatibility issue

**Comment by eolivelli** [comment]
Great, it is time to write code now!

**Comment by eolivelli** [comment]
@merlimat  @ivankelly I am not sure how to work in BookkeeperSchemaStorage, any hint ?

**Comment by ivankelly** [comment]
How do you mean? I would just change the component to "schema", everything else should be similar.

**Comment by eolivelli** [comment]
@ivankelly 
I am not sure how to get the 'schema name' from the objects I have around createLedger

**Comment by ivankelly** [comment]
Just pass in SchemaId from the calling methods to BookkeeperSchemaStorage#addNewSchemaEntryToStore

**Comment by eolivelli** [comment]
@ivankelly  thank you.
I am totally new to Pulsar internals !

**Comment by eolivelli** [comment]
@ivankelly  this is my workbench #3525
