### ISSUE TITLE
Broker stop produces a consumer reset

### ISSUE THREAD

**Issue by sschepens** [apache/pulsar#346]
I've been stopping some brokers and found that probably all consumers handled by that broker were reset to a previous position.
This should not be happening as we're mark-deleting 10 times per second.
I've been checking logs but found nothing useful, it would seem that the metadata stored in zookeeper is just old.
Do you know what could be happening @merlimat @rdhabalia ?

Here are the logs for all brokers when the stopped:
[broker-logs.txt](https://github.com/yahoo/pulsar/files/914757/broker-logs.txt)

**Comment by sschepens** [comment]
I add some more info, I grabbed a random consumer from a random topic which is currently active and find the following cursor info:
```
cursor info: cursorsLedgerId: 1085466
markDeleteLedgerId: 1009812
markDeleteEntryId: 6153
individualDeletedMessages {
  lowerEndpoint {
    ledgerId: 1009812
    entryId: 6154
  }
  upperEndpoint {
    ledgerId: 1083923
    entryId: 44490
  }
}
individualDeletedMessages {
  lowerEndpoint {
    ledgerId: 1083923
    entryId: 44491
  }
  upperEndpoint {
    ledgerId: 1083923
    entryId: 44495
  }
}
```

What about this is that ledger 1085466 is closed:
```
ledgerID: 1085466
BookieMetadataFormatVersion	2
quorumSize: 3
ensembleSize: 3
length: 50
lastEntryId: 0
state: CLOSED
segment {
  ensembleMember: "10.64.102.126:3181"
  ensembleMember: "10.64.103.151:3181"
  ensembleMember: "10.64.103.68:3181"
  firstEntryId: 0
}
segment {
  ensembleMember: "10.64.102.126:3181"
  ensembleMember: "10.64.103.151:3181"
  ensembleMember: "10.64.102.214:3181"
  firstEntryId: 1
}
digestType: CRC32
password: ""
ackQuorumSize: 3
```

Now, if I get the internal-stats for that topic and consumer I get the following information:
```
    {
      "markDeletePosition" : "1218534:48417",
      "readPosition" : "1352213:18774",
      "waitingReadOp" : true,
      "pendingReadOps" : 0,
      "messagesConsumedCounter" : 35121719,
      "cursorLedger" : 1085466,
      "cursorLedgerLastEntry" : 0,
      "individuallyDeletedMessages" : "[(1218534:48418‥1333786:41094], (1333786:41095‥1352213:18164], (1352213:18165‥1352213:18248], (1352213:18249‥1352213:18272], (1352213:18273‥1352213:18315], (1352213:18316‥1352213:18336], (1352213:18337‥1352213:18350], (1352213:18351‥1352213:18548], (1352213:18549‥1352213:18593], (1352213:18594‥1352213:18610], (1352213:18611‥1352213:18636], (1352213:18637‥1352213:18760], (1352213:18761‥1352213:18773]]",
      "lastLedgerSwitchTimestamp" : "2017-04-01 06:17:54.742",
      "state" : "NoLedger"
    }
```

It would seem that the consumer somehow failed to open a new ledger but is never retrying or something of the sort.
What's also strange is that there are no logs of the sort, and it seems that the broker is allowing markDeletes on the consumer but never persisting them.

**Comment by sschepens** [comment]
By the way, @merlimat @rdhabalia is there any other communication channel you handle to contact you more quickly? this is rather critical

**Comment by merlimat** [comment]
@sschepens The `NoLedger` state is the normal state after the cursor has been recovered, and before any new mark-delete has been issued.

The idea there is to defer the ZK writes for creating a new ledger and updating the cursor z-node until is needed.

In the log that you posted before, can you give the topic/subscription name for which you have added the internal stats?

**Comment by sschepens** [comment]
@merlimat the subscription is `8caa83e304674002a34f441f34f73f63-shipping-feed-orders` and the topic is `persistent://fury/global/cbead41f2a5849b5a5be64df0f3521d2-orders-orders/cbead41f2a5849b5a5be64df0f3521d2-orders-orders`, the information provided is specifically for partition 0 (`persistent://fury/global/cbead41f2a5849b5a5be64df0f3521d2-orders-orders/cbead41f2a5849b5a5be64df0f3521d2-orders-orders-partition-0`).

> @sschepens The NoLedger state is the normal state after the cursor has been recovered, and before any new mark-delete has been issued.

I understand that and I have read the code, but the state is still NoLedger and it has not changed, by the stats-internal it was last changed 11 days ago.

**Comment by sschepens** [comment]
Adding some more info:
That consumer is apparently stuck on message `1218534:48418` and not acknowledging it, though that message was published `2017-04-06 23:00:29.200`, so the consumer should have already acknowledged messages between the ledger was last switched and message `1218534:48418`.
Also, we have a message expiration of 7 days.

**Comment by merlimat** [comment]
In the log you attached I can only see `partition-2` of that topic. Can you reattach the log for `partition-0`?

Any hints in logs why the TTL is failing to be enforced? There should be a log line printed every ~5min like : 
```java
log.info("[{}][{}] Starting message expiry check, ttl= {} seconds", topicName, subName,
                    messageTTLInSeconds);
```

In addition if the suspicion of the issue is there,  can you enable debug level logs on `com.yahoo.pulsar.broker.service.persistent.PersistentMessageExpiryMonitor` ?

**Comment by sschepens** [comment]
@merlimat probably `partition-0` was not affected when I restarted those brokers, which is why the issue is currently present in it, I will check the stats for `partition-2`

> Any hints in logs why the TTL is failing to be enforced?

The logs are being printend and there doesn't seem to be any failures, it just seems that in that period of time i took the logs there weren't any from PersistentMessageExpiryMonitor.

**Comment by sschepens** [comment]
Over the past 7 days, there seem to have been just a few warning of message expiry fails, for example:
`2017-04-06 07:47:41,310 - WARN  - [BookKeeperClientWorker-18-1:PersistentMessageExpiryMonitor$1@106] - [persistent://fury/global/cbead41f2a5849b5a5be64df0f3521d2-orders-orders/cbead41f2a5849b5a5be64df0f3521d2-orders-orders-partition-7][cbead41f2a5849b5a5be64df0f3521d2-orders-buyingflow_notifications] Message expiry failed - mark delete failed`

Though none seem to have been from this consumer

**Comment by sschepens** [comment]
@merlimat effectively, `partition-2` which was affected by the broker restart was 'fixed' and now contains an Open ledger.
But `partition-0` which wasn't affected has the issue of NoLedger state.

**Comment by merlimat** [comment]
So, `partition-0` is still running on the "old" broker without restart, correct?

Can you post the logs for that partition? 

Also, the info log with the `Starting message expiry check .. ` message should be printed any way every 5min. Is that happening?

**Comment by merlimat** [comment]
The other question is. Can you try to do the manual expiry operation on that partition/subscription ? 

```shell
# for 1h expiry:
$ bin/pulsar-admin persistent expire-messages $TOPIC --subscription $MY_SUB --expireTime 3600
```

And if this fails, it should be printing some error.

**Comment by sschepens** [comment]
> So, partition-0 is still running on the "old" broker without restart, correct?

Correct.

Also, the info log with the Starting message expiry check .. message should be printed any way every 5min. Is that happening?

Yes, the logs are being printed and expiry is not failing.

I don't believe expiry is the issue here, when a Cursor is in a NoLedger state and a asyncDelete comes in, it should recreate the ledger, but that's not happening.

**Comment by merlimat** [comment]
> I don't believe expiry is the issue here, when a Cursor is in a NoLedger state and a asyncDelete comes in, it should recreate the ledger, but that's not happening.

That's correct and that's irrespective of any throttling, since the 1st request should anyway go through.

Which version of the code the `partition-0` broker is using? In the 1.17 code, https://github.com/yahoo/pulsar/blob/f572241537b958a8afda48b8af13ea768a7230f7/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L1494 the async delete should trigger the persistence of mark-delete even if there are unacked messages. Any chance to enable debug logs on `ManagedCursorImpl` for that broker? Or also a heap-dump might be helpful.

Did you get to see any error line in log like `Metadata ledger creation failed` ?

**Comment by sijie** [comment]
close it due to inactivities in this thread. feel free to reopen it if it reoccurs
