### ISSUE TITLE
Unable to delete a namespace using pulsar-admin CLI

### ISSUE THREAD

**Issue by shrikant-pa** [apache/pulsar#3463]
**Expected behavior**
Delete a namespace created in tenant/namespace format after running namespaces command using pulsar-admin CLI. 

**Actual behavior**
I can only delete namespace created in tenant/cluster/namespace format. 

Returns below error when deleting namespace created with tenant/namespace format.

```
null
Reason: javax.ws.rs.ProcessingException: java.net.ProtocolException: Server redirected too many  times (20)
command terminated with exit code 1
```

**Steps to reproduce** 
1. pulsar-admin tenants create sample --admin-roles admin
2. pulsar-admin namespaces create sample/ns
3. pulsar-admin namespaces set-clusters sample/ns --clusters us-central
4. pulsar-admin namespaces delete sample/ns

**System configuration**
apache-pulsar-2.2.1 on google kubernetes cluster. Pulsar cluster name us-central.

**Comment by liketic** [comment]
I can't reproduce this bug on master branch. @jiazhai , do you have any suggestions ?

**Comment by shrikant-pa** [comment]
So this feels like GKE deployment issue. The source code YAML files have pulsar-gke as local cluster name but metadata has us-central as cluster name. While creating namespaces it was causing issue and had to set the replication cluster for each namespace and cluster names were different. 

I redeployed GKE cluster and changed cluster name in metadata to pulsar-gke as this value is provided in other yaml files. After this i did not encounter this issue.

**Comment by sijie** [comment]
Closed this issue since it seems to be related GKE issue.
