### ISSUE TITLE
Feature: Allows multiple topics consumer to be able to listen to the earliest message in topics discovered.

### ISSUE THREAD

**Issue by lelabo-marc** [apache/pulsar#3494]
**Is your feature request related to a problem? Please describe.**
I am working with the python client and a MultiTopicsConsumer in order to listen to events in streams following a specific pattern. I then archive any new events based on the incoming topics.
It allows us to split the routing and the archiving process into two different micro-services.

**Describe the solution you'd like**
I'd like to be able to create a consumer that start listening to topics from the start. The current behavior only allows me to listen to new messages.
The auto-discovery feature can take some time to discover a new topic and therefore, I am missing a few messages each time.

I'd like the MultiTopicsConsumer to be able to support seek() or to be able to pass to Client.subscribe() a parameter that create a consumer that will listen to the earliest message in the topic discovered.

**Describe alternatives you've considered**
I took a look to reader interface but it does not allow to multiple topics subscription.
We will be forced to channel every message to the same channel to use a normal consumer and do the routing just before the archive. It will be an important overload to our archiving process.

For the moment, I am running in the following exception that I found in the CPP library (see link):

[Exception: Pulsar error: OperationNotSupported](https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/lib/MultiTopicsConsumerImpl.cc)

**Comment by merlimat** [comment]
I think the problem is that https://pulsar.apache.org/api/client/org/apache/pulsar/client/api/ConsumerBuilder.html#subscriptionInitialPosition-org.apache.pulsar.client.api.SubscriptionInitialPosition- is not exposed in C++ client (and Python/Go)
