### ISSUE TITLE
Could we follow message in realtime in the browser as pusher or pubnub does?

### ISSUE THREAD

**Issue by lanlin** [apache/pulsar#3500]
I notice that pulsar all implemented clients are the server side.

So, Could I follow message in realtime in the browser as pusher or pubnub does?

**Comment by sijie** [comment]
@lanlin can you explain more about your feature request? if possible, can you show a few examples of your feature request?

**Comment by lanlin** [comment]
I want to subscribe to a topic(channel) from the browser(consumer), the server side(backend) as the producer. 

So that I can replace [Pusher](https://pusher.com/) or [Pubnub](https://www.pubnub.com/) with the pulsar. 

Not server to server, but server to the browser.

**Comment by sijie** [comment]
@lanlin you can check websocket proxy in pulsar. http://pulsar.apache.org/docs/en/client-libraries-websocket.html#docsNav

**Comment by lanlin** [comment]
@sijie thanks.
But I can't use TLS to identify the browser client as the server side do.
Is there any way to dynamically generate a token with an expiration time?

**Comment by sijie** [comment]
@lanlin there is a token-based authentication mechanism introduced in 2.3.0. You can checkout the details here : http://pulsar.apache.org/docs/en/next/security-token-admin/

2.3.0 will be released in 1 week or so.

**Comment by lanlin** [comment]
@sijie that's what we need! thank you very much!
