### ISSUE TITLE
Failover mode consumer has inconsistent behaviour

### ISSUE THREAD

**Issue by narkedboy** [apache/pulsar#3504]
When using failover subscription mode with multiple Pulsar consumers, with partitioned topics, it is possible to have multiple consumers reading from the same partition.

**Steps to reproduce the behavior:**
Set up 3 consumers, pulling from the same topic and partition with the same subscription name, all in Failover mode, all with different consumer names, A, B, C.

E.g. (I added a consumer-name parameter to the client tool to demo this)
pulsar-client consume persistent://public/default/topicXYZ-partition-0 --subscription-name sub1 --num-messages 0 --subscription-type Failover --rate 1 --consumer-name [A|B|C]

Start consumer A first, then C, then B... let A run for a while, B and C will be suspended, then kill A, B takes over, C stays suspended...kill B, C takes over.... all good.
Start consumer B first, then A... B starts consuming, but A does also!!

This defeats the point of Failover mode, which should ensure ordering of a partition is retained. It appears to have reverted back to Shared mode.

**Expected behavior**
I would expect to start consumer B first, then A, then C... B starts consuming, A and C will be suspended, then kill B, A takes over, C stays suspended.... kill A, C takes over.

This would ensure only one consumer was ever reading from that partition.

**Additional context**
We have an extremely high throughput partitioned topic. It is being read by consumers split across 3 machines. We need to retain ordering of the topic within a partition and have failover. This is not straightforward to configure (compared to Kafka).

Thanks

**Comment by merlimat** [comment]
@narkedboy with a failover subscription, having a unique active consumer on a given partition, is guaranteed at the broker level and I am not aware of any issues in that mechanism. 

What you also might be seeing is that some the failover is being triggered when you start the consumer as the assignments are re-balanced. 

When the rebalance/failover occurs, the broker will switch the active consumer and will re-send all the unacknowledged messages to the new active consumer.

**Comment by narkedboy** [comment]
@merlimat have you tried to reproduce this issue?

It's pretty easy to do so. With two consumers, start one with consumer name B and 10 seconds later one with consumer name A. Both attached to the same partition.

Both consumers will read from the partition simultaneously. B is not suspended when A starts.

**Comment by narkedboy** [comment]
@merlimat Yes that seems to be the case, if you let both consumers run for long enough, eventually the one with the lexically higher consumer name does stop. So it must just be the buffering that is causing both consumers to run simultaneously.

**Comment by duyhieuvo** [comment]
Hi @merlimat. I think this behavior can be problematic. Please correct me if I don't understand it correctly. Assuming an application reads messages from Pulsar, processes and produces results back to another Pulsar topic. 
If there are still some unacknowledged messages buffering on the disconnected consumer and these messages are re-sent to the failover consumer, these messages can be concurrently processed in two different processes. This can lead to duplication or out-of-order results on the output topic. 
Does Pulsar provide any fence-off mechanism to prevent application with disconnected consumer from continuing to produce results to Pulsar? For example, in case of Apache Kafka, they use a new epoch number for the producer on the failover instance to detect and drop any message produced by the instance with disconnected consumer.
