### ISSUE TITLE
Functions missing from REST api docs

### ISSUE THREAD

**Issue by ivankelly** [apache/pulsar#3506]
http://pulsar.apache.org/en/admin-rest-api/

There's no mention of the functions endpoints.

**Comment by ivankelly** [comment]
Swagger was failing because the function endpoint was returning some protobuf. This protobuf needs to be refactored out of the API, and then swagger should work.

**Comment by sijie** [comment]
The docs of functions, sinks and sources are all added.

**Comment by sijie** [comment]
The docs of functions, sinks and sources are all added.
