### ISSUE TITLE
Tiered Storage Offloaders download link is dead in the Docs

### ISSUE THREAD

**Issue by digi691** [apache/pulsar#3510]
**Describe the bug**
When trying to download the Pulsar Tiered Storage Offloaders 2.2.1 release, the download link appears to be dead.  In the browser it's giving a Not Found Error page, wget produces a 404.

**To Reproduce**
1. Go to http://pulsar.apache.org/docs/en/standalone.html#installing-tiered-storage-offloaders-optional
2. Try downloading the release from the web page with the link: https://archive.apache.org/dist/pulsar/pulsar-2.2.1/apache-pulsar-offloaders-2.2.1-bin.tar.gz
3. Or use wget
`wget https://archive.apache.org/dist/pulsar/pulsar-2.2.1/apache-pulsar-offloaders-2.2.1-bin.tar.gz`

**Expected behavior**
tarball should begin download

**Desktop (please complete the following information):**
 - OS: [Archlinux]

**Comment by sijie** [comment]
@merlimat I think offloader distribution was not generated for release 2.2.1.

**Comment by sijie** [comment]
since 2.2.2 was released, close this issue.
