### ISSUE TITLE
Please add option to start reader / consumer cursor by timestamp or time delta

### ISSUE THREAD

**Issue by matansh** [apache/pulsar#3565]
**Is your feature request related to a problem? Please describe.**
problem: currently a reader can take a message id and start from it, but knowing what message id to start from is not always possible.

**Describe the solution you'd like**
If readers (or consumers) could be initialised using a time based interface it would be very easy to develop services that need to aggregate statistics or execute some batch job like archiving / persisting.
For example, passing a epoch timestamp / time delta like -7d to the reader interface to tell it where to start our cursor 

**Describe alternatives you've considered**
A current work around is starting a new reader / consumer and using the admin api's reset-cursor command to move our cursor back.
A less intuitive solution that is hard to find.

**Additional context**
NA?, if anything extra is needed please let me know :)

**Comment by merlimat** [comment]
@matansh This is easily doable, as you also seen that reset to a timestamp is already there. Marking this for 2.4

**Comment by wolfstudy** [comment]
hello @matansh @merlimat I am paying attention to this issue and will implement this function as soon as possible.

**Comment by skyrocknroll** [comment]
https://github.com/apache/pulsar/issues/3446

**Comment by sijie** [comment]
this  has been fixed by #3622
