### ISSUE TITLE
Improve pulsar docker image distribution

### ISSUE THREAD

**Issue by aahmed-se** [apache/pulsar#3611]
Currently the pulsar docker image  is large and is getting difficult to distribute.

Suggested list of improvements

* use multi-stage build to reduce layers
   ex : https://github.com/aahmed-se/pulsar-docker-slim-test
* switch base image to open jre slim, add jstack as addon utility (100 kb)
* Remove connectors from base image, (possibly make another image for each container bundle or link to a registry)
* reduce python artifacts 
  - pip may be removed (this may affect functions with external dependencies)
  - switch to python 3.7 as default
* (Longer term) move to modular jdk-11 base image

**Comment by sijie** [comment]
This fixed by #4184
