### ISSUE TITLE
Provide a NAR way to load customized implemented of class in broker config

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#3614]
**Is your feature request related to a problem? Please describe.**
Some user is asking Provide a NAR way to load customized implemented of class in broker config.
e.g. 
loadManagerClassName
authorizationProvider
schemaRegistryStorageClassName

**Comment by tisonkun** [comment]
Closed as stale.

The development of this initiative seems stalled and this thread doesn't contain too much information. If one wants to revive the proposal, please open a brand new thread.

IIRC we release connectors in NAR format, not sure whether it's supported already.
