### ISSUE TITLE
Pulsar C++/Python consumer performance issue, if producing message in batch mode, consuming ACK in single mode

### ISSUE THREAD

**Issue by easyfan** [apache/pulsar#3623]
#### Expected behavior
Pulsar C++/Python client consuming  performance should keep at a stable level;

#### Actual behavior

 Pulsar C++/Python client consuming  performance  downgrade obviously;

#### Steps to reproduce
1. Producing messages in batch mode (locally with batch count as 1000);
2. Consuming messages with ACK in single mode (as appose to the cumulative mode) with C++ or Python clients;
3. Keep the consuming process running for a while (say, with producing message 5000-8000 per second, run at least 15 minutes) and see the consuming messages per seconds, it downgrades very obviously; At the same time, the Pulsar Java client consuming performance could keep in a stable level.
See the attached monitor screen below:
![image](https://user-images.githubusercontent.com/7017849/53001501-bd132300-3465-11e9-9dff-7d382030284a.png)

#### System configuration
org.apache.pulsar:pulsar-client-cpp: 2.2.0

**Comment by easyfan** [comment]
This issue is led by a mistake in pulsar-client-cpp/BatchAcknowledgementTracker.cc.

**Comment by merlimat** [comment]
This is fixed in master https://github.com/apache/pulsar/pull/3618

**Comment by sijie** [comment]
closed the issue as #3618 fixed it.

@easyfan #3618 would be released as part of 2.3.1 and 2.4.0. you can check it out when 2.3.1 is release. if it happens again, please reopen the issue or create a new one.
