### ISSUE TITLE
No documentation on how to get connector logs

### ISSUE THREAD

**Issue by ivankelly** [apache/pulsar#3624]
**Describe the bug**

Lets say you start a connector. It isn't working for some reason. How do you get detailed logging of what is happening? Same goes for functions. There are files on the filesystem, but you have to look at the running process to see what they are. With k8s this is probably even harder.

**Comment by Anonymitaet** [comment]
@tuteng  as discussed offline, could you please write a *how to debug Pulsar connector* guide (includes getting connector logs)?

You can take Pulsar Function Debug Guide for reference:

* https://pulsar.apache.org/docs/en/next/functions-debug/

* https://mp.weixin.qq.com/s/3Iz5_GF8V_4gsvVRduophQ

**Comment by Anonymitaet** [comment]
@tuteng Just a soft reminder: you are working on writing the **How to Debug Pulsar Connector Guide** these days, could you please add **how to get connector logs** to the guide? Thank you

**Comment by Anonymitaet** [comment]
@ivankelly @tuteng @sijie 

Done in https://github.com/apache/pulsar/pull/5041, so we can close this issue.
