### ISSUE TITLE
Schema in JSON 

### ISSUE THREAD

**Issue by congbobo184** [apache/pulsar#3631]
**Describe the bug**
this is the first time schema
![image](https://user-images.githubusercontent.com/39078850/53084016-f6699280-353a-11e9-930b-8e0d088fb707.png)
this is the second time schema
![image](https://user-images.githubusercontent.com/39078850/53084084-16995180-353b-11e9-804e-5a0290368f90.png)
but it report an error
![image](https://user-images.githubusercontent.com/39078850/53084158-37fa3d80-353b-11e9-892c-a78667c617f9.png)
when I revise the ddd field to String type,it can create producer and send message

**Comment by aahmed-se** [comment]
are you saying to can't add a int field ?

**Comment by congbobo184** [comment]
> are you saying to can't add a int field ?

it can't add primitive types but it can add boxing field

because it can judge  whether or not the field’s null
