### ISSUE TITLE
go static build error

### ISSUE THREAD

**Issue by Tevic** [apache/pulsar#3680]
**Describe the bug**
Pulsar version: 2.3.0
dpkg -i apache-pulsar-client*.deb

**To Reproduce**
go build -a -ldflags '-extldflags "-static"' .

**Expected behavior**
build success

**Desktop (please complete the following information):**
go version go1.11.5 linux/amd64
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

**Additional context**
Some error output:(error log is long,i will upload if needed.)
````
# command-line-arguments
/home/tevic/WorkSpace/RunTime/Go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-849858481/000024.o: In function `_cgo_18049202ccd9_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:49: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libpulsar.a(ExecutorService.cc.o): In function `void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) [clone .isra.150]':
/usr/include/c++/6/bits/basic_string.tcc:212: undefined reference to `std::__throw_logic_error(char const*)'
/usr/include/c++/6/bits/basic_string.tcc:219: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libpulsar.a(ExecutorService.cc.o): In function `pulsar::ExecutorService::close()':
/usr/include/c++/6/bits/unique_ptr.h:76: undefined reference to `operator delete(void*)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libpulsar.a(ExecutorService.cc.o): In function `pulsar::ExecutorService::~ExecutorService()':
/usr/include/c++/6/bits/unique_ptr.h:76: undefined reference to `operator delete(void*)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libpulsar.a(ExecutorService.cc.o): In function `pulsar::ExecutorService::~ExecutorService()':
/usr/local/include/boost/asio/impl/io_service.ipp:53: undefined reference to `operator delete(void*)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libpulsar.a(ExecutorService.cc.o): In function `pulsar::ExecutorServiceProvider::ExecutorServiceProvider(int)':
/usr/include/c++/6/ext/new_allocator.h:104: undefined reference to `operator new(unsigned long)'
/usr/include/c++/6/ext/new_allocator.h:102: undefined reference to `std::__throw_bad_alloc()'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libpulsar.a(ExecutorService.cc.o): In function `pulsar::ExecutorService::ExecutorService()':
/usr/local/include/boost/asio/impl/io_service.ipp:39: undefined reference to `operator new(unsigned long)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libpulsar.a(ExecutorService.cc.o): In function `pulsar::ExecutorService::ExecutorService()':
````

**Comment by Tevic** [comment]
I've figure out a workaround:
1.install the requirements for build cpp client
2.build cpp client, finally make install
3.download curl source build and install, with specific build flags:
```
./configure --disable-shared --enable-static --disable-ldap --disable-sspi
make
make install
```
4.build your go code use command like this:
```
CGO_CPPFLAGS="-I/usr/local/include -I/usr/include" CGO_LDFLAGS="-L/usr/local/lib -L/usr/lib -lcurl -lssl -lcrypto -lcrypto -lz -lpulsar -lstdc++ -lboost_system -lboost_regex -lprotobuf -ldl" go build -tags netgo -ldflags '-extldflags "-static"' hello.go

```

**Comment by wolfstudy** [comment]
Currently `pulsar-client-go` is encapsulated using cgo. All code logic is implemented in `pulsar-client-cpp`. The execution of `pulsar-client-go` depends on `pulsar-client-cpp`. In principle, you only need to build `pulsar-client-cpp` locally, `pulsar-client-go` can be used.

**Comment by wolfstudy** [comment]
> 4.build your go code use command like this:
> 
> ```
> CGO_CPPFLAGS="-I/usr/local/include -I/usr/include" CGO_LDFLAGS="-L/usr/local/lib -L/usr/lib -lcurl -lssl -lcrypto -lcrypto -lz -lpulsar -lstdc++ -lboost_system -lboost_regex -lprotobuf -ldl" go build -ldflags '-extldflags "-static"' hello.go
> ```
> It is quite complex and is there any simple method?

In my local area, I only need to build cpp-client, I have not run this step, and it can also run normally.

**Comment by Tevic** [comment]
> > 4.build your go code use command like this:
> > ```
> > CGO_CPPFLAGS="-I/usr/local/include -I/usr/include" CGO_LDFLAGS="-L/usr/local/lib -L/usr/lib -lcurl -lssl -lcrypto -lcrypto -lz -lpulsar -lstdc++ -lboost_system -lboost_regex -lprotobuf -ldl" go build -ldflags '-extldflags "-static"' hello.go
> > ```
> > It is quite complex and is there any simple method?
> 
> In my local area, I only need to build cpp-client, I have not run this step, and go-client can also run normally.

If you only use `go build xxx.go` without any arguments, go will use dynamiclly build your program which runs rely on libpulsar.so, which means you need to copy libpulsar.so to every machine you run this program. But in my way, all dependencies will in one binary.

**Comment by tisonkun** [comment]
Closed as stale. The new client-go is implemented in pure go and is located at https://github.com/apache/pulsar-client-go.

Feel free to create an issue there if more issues found.
