### ISSUE TITLE
Via the python client I am unable to consume messages with a multi-topic regex consumer

### ISSUE THREAD

**Issue by matansh** [apache/pulsar#3681]
**Describe the bug**
Via the python client I am unable to consume messages with a multi-topic regex consumer

**To Reproduce**
1. bring up pulsar standalone instance via docker 
```
docker run -it -p 80:80 -p 8080:8080 -p 6650:6650 apachepulsar/pulsar-standalone
```
2. init python client
```python
pulsar_client = pulsar.Client('pulsar://localhost:6650')
```
3. create subscriber 
```python
consumer = pulsar_client.subscribe(re.compile('test_.*'), 'sub1')
```
4. create producer 
```python
producer = pulsar_client.create_producer('test_1')
```
5. via 2 different python instances / threads / processes attempt to send + read
```python
while Ture:
    producer.send(b'test')
```
```python
consumer.receive()
```
6. ERROR: consumer never received any messages 

**Expected behavior**
topic `test_1` should be read by subscription `test_.*`

**Desktop (please complete the following information):**
 - OS: mac OS (pulsar running in docker)
 - pulsar version: latest master from docker (should be 2.2.0?)
 - python version: 3.7
 - pulsar-client (pip lib) version: 2.3.0.post1 (latest)

**Comment by matansh** [comment]
update: 
just found a workaround!
if i change my code to contain the full topic path it works.
```python
consumer = pulsar_client.subscribe(re.compile('persistent://public/default/test_.*'), 'sub1')
producer = pulsar_client.create_producer('persistent://public/default/test_1')
```

I guess the doc's should at least reflect this, or even better fixing the "shorter" syntax

**Comment by grantwwu** [comment]
We just ran into this as well :(

**Comment by Jennifer88huang** [comment]
@matansh @grantwwu We're fixing the issue in #6050. You can check the update in #6050. If there is any issue with it, feel free to comment.

**Comment by grantwwu** [comment]
Unfortunately, I have moved on from my employer which uses Pulsar.  But thanks, anyways, for the fix!

**Comment by Jennifer88huang** [comment]
@grantwwu that's OK. Thanks for reporting the issue.
