### ISSUE TITLE
build failed without lombok 

### ISSUE THREAD

**Issue by hwind001** [apache/pulsar#3699]
why use lombok plugin ?

this plugin cause source build failed , not friendly to read source. 

very very not friendly ~~ 

trash

**Comment by sijie** [comment]
@hwind001 

- if you are using `maven` build the source, it should be working.
- if you are using an ide like intellij, intellij will handle for you.

I would suggest you checkout pulsar docs or ask questions at mailing list or slack channel if you encounter any issue.
