### ISSUE TITLE
Documentation generation issues

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#3725]
**Describe the bug**
Hi, the documentation of v2.2.1 normally available right there: https://pulsar.apache.org/docs/en/2.2.1/standalone/ has content of v2.3.0. More, how to choose the javadoc from pulsar version? What is the version of: https://pulsar.apache.org/api/client/?

**Comment by Jennifer88huang** [comment]
When I navigate to the link https://pulsar.apache.org/docs/en/2.2.1/standalone/ , it shows content of v2.2.1. So has this issue been fixed?

**Comment by KannarFr** [comment]
Probably yes.

**Comment by Jennifer88huang** [comment]
@KannarFr  Thanks for your confirmation.
