### ISSUE TITLE
functions cli received HTTP 404 when trying to inspect a build-in I/O connector

### ISSUE THREAD

**Issue by murong00** [apache/pulsar#3726]
**Describe the bug**

When trying to use `pulsar-admin functions` CLI (e.g. `getstatus`) for inspecting a submitted build-in I/O sink connector by following the tutorial for Pulsar IO, someone will receive HTTP 404 like follows:
```
$ bin/pulsar-admin functions getstatus \
>     --tenant public \
>     --namespace default \
>     --name test-sink
HTTP 404 Not Found

Reason: Function test-sink doesn't exist
```
However, use `pulsar-admin sink` CLI can get the correct result.

**Comment by murong00** [comment]
This is probably due to:
https://github.com/apache/pulsar/blob/master/pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java#L922
the method `calculateSubjectType` returns the actual component Type `SINK`, but the variable `componentType` initialized by `Utils.ComponentType.FUNCTION` via constructor `FunctionsImpl` in `FunctionsBase.functions`.

**Comment by srkukarni** [comment]
This is the right behaviour. In 2.3, functions/sources/sinks are treated seperately. Thus submitting a source via source create and doing functions getstatus, etc will not work. You will need to use source commands to interact with sources

**Comment by murong00** [comment]
@srkukarni Thanks for point it out. As the functions/sources/sinks are treated seperately, I think we should update the [Tutorial](https://github.com/apache/pulsar/blob/master/site2/docs/io-quickstart.md) to guide the novices.
