### ISSUE TITLE
Need to catchup doc for IO Connectors.

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#3728]
**Describe the bug**
some of the connectors are not documented in this link:
http://pulsar.apache.org/docs/en/io-connectors.html#docsNav
such as：
- [x] canal #3664 
- [ ] elastic
- [ ] file
- [ ] hdfs2/3
- [ ] mongo

we need catch up the work.

**Comment by tuteng** [comment]
Document of canal has been updated here https://github.com/apache/pulsar/pull/3664.

**Comment by jiazhai** [comment]
Thanks @tuteng  for point it out
