### ISSUE TITLE
[pulsar-broker: message-dispatching] Slow message redelivery for subscription with large backlog and random unack messages.

### ISSUE THREAD

**Issue by rdhabalia** [apache/pulsar#3731]
### Issue
**Slow message redelivery for subscription with large backlog and random unack messages.**

Many times consumers don't ack messages properly which leads large number of unack-message list for that consumer and it also leads to huge backlog because `markDeletePosition` can't be advanced due to large number of ack-holes in acked-messages list at the broker.

Because of that broker ends up owning large number of unacked messages in the list and broker tries redeliver all those messages when redelivery triggers. Right now, broker tries to read random messages from the large number of unack-message list which also makes bookie to perform random read across many ledgers. Therefore, message dispatch rate becomes slow and it directly impacts consumer's delivery rate which many times become a bottleneck to drain the huge backlog.

### Solution
We need to optimize message-replay for redelivery message in such a way that broker does less number of random reads or at least try to read from the same ledger that can help to utilize bookie-read-cache.

**Comment by codelipenghui** [comment]
Since #3732 is already fixed, close this issue.
