### ISSUE TITLE
Pulsar Function Authorization

### ISSUE THREAD

**Issue by jerrypeng** [apache/pulsar#3763]
After Pulsar Function Authentication is implemented, we also need to implement the authorization model for functions.

I propose we add the following methods to the AuthorizationProvider (https://github.com/apache/pulsar/blob/master/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationProvider.java) interface:

```
/**
* Allow all function operations with in this namespace
* @param namespaceName The namespace that the function operations can be executed in
* @param role The role to check
* @param authenticationData authentication data related to the role
* @return a boolean to determine whether authorized or not
*/
CompletableFuture<Boolean> allowFunctionOps(NamespaceName namespaceName, String role,
                                           AuthenticationDataSource authenticationData);

```
We should also add an action to AuthAction for functions:

```
public enum AuthAction {
   /** Permission to produce/publish messages */
   produce,

   /** Permission to consume messages */
   consume,
  
   /** Permissions for functions ops **/
   functions,
}
```

And admins and tenant admins can grant the permission “functions” to users for a namespace and they can perform all function operations(create, update, delete, get)  within that namespace.  

I also think if a user has the permissions to perform all function operations within a namespace, he or she should also be able to consume and produce to a any topic within that namespace

**Comment by jerrypeng** [comment]
@srkukarni @sijie @merlimat what do you think?

**Comment by rdhabalia** [comment]
Do we really need separate `AuthAction` for function? function is going to produce/consume from a specific topic so, can't we authorize function's principal-identity for produce/consume action?

**Comment by jerrypeng** [comment]
@rdhabalia but is there a situation in which I want to user to be able to consume/produce in a namespace but not be able to create functions in that namespace?

**Comment by rdhabalia** [comment]
so, do we have plan to store function-authorization metadata into same global/metastore zk?
so far we are able to keep function metadata separate from broker's cluster metadata by storing them into function itself. So, can't we do the same for function auth data?

**Comment by jerrypeng** [comment]
@rdhabalia would there be a problem storing the function authorization data in zk?  It will be basically the same as the other authorization data right?  I would rather not complicate the implementation and store the function specific authorization data somewhere else.

**Comment by sijie** [comment]
@jerrypeng 

If I understand this correctly, there are two parts in this proposal?

One part is authorization for end-users, where a user has permissions to create/delete/update functions?

The one part is for a function, where a function can produce, consume messages?

Is that correct?  Or is it just about the first part?

**Comment by jerrypeng** [comment]
@sijie I propose that if a user has the permissions to CRUD functions in a namespace, he or she should automatically also be able to consume and produce messages to any topic in that namespace as well.

**Comment by sijie** [comment]
> I propose that if a user has the permissions to CRUD functions in a namespace, he or she should automatically also be able to consume and produce messages to any topic in that namespace as well.

I don't have any problems with that.

**Comment by merlimat** [comment]
> so far we are able to keep function metadata separate from broker's cluster metadata by storing them into function itself. So, can't we do the same for function auth data?

The important part here is to have consistent way to declare and enforce authorization across topics and functions.

The authorization is already abstracted and pluggable through the `AuthorizationProvider`. This is to add the "function operations" action as one of the possible actions one can do in the system (other than "produce" and "consume"). 

Where the authorization is stored depends on the authz plugin and by default will be on configuration store (global zk). There isn't any change in the volume of data or frequency of updates.
