### ISSUE TITLE
Pulsar Functions should support disabling AllowNull

### ISSUE THREAD

**Issue by congbobo184** [apache/pulsar#3765]
### Describe the bug

Currently AvroSchema makes all fields default allowNull

### Expected behavior

Need to fix the default allowNull becomes optional

### Additional context

N/A

**Comment by codelipenghui** [comment]
#3752 This PR is fix pulsar avro schema aways make fields allow null. 
@jerrypeng May need to make some changes on the function side.

**Comment by sijie** [comment]
This has been fixed in the recent change to allow configuring schema properties.
