### ISSUE TITLE
[go functions] support go pulsar function

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar#3767]
The pulsar function is a very eye-catching feature, but there is currently no support for the go language. I am developing functions related to go functions. The related PIP documentation will be updated later.

**Comment by wolfstudy** [comment]
[PIP-32: Support Go Function - API, Instance and LocalRun](https://gist.github.com/wolfstudy/773871ee0d24643f8111ccfa055b2f26)

**Comment by merlimat** [comment]
@wolfstudy Added to the wiki at https://github.com/apache/pulsar/wiki/PIP-32%3A-Go-Function-API%2C-Instance-and-LocalRun
Please send email to dev@ list to start discussion

**Comment by wolfstudy** [comment]
@merlimat Thanks for your reply, I have sent the corresponding email to dev@ list.
