### ISSUE TITLE
Documentation: change download link from archive.apache.org to dyn/mirrors

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#3778]
In current website, some download like from apache, is linked to: `https://archive.apache.org/dist/pulsar`
It would be better to change to  [dyn/mirrors](https://www.apache.org/dyn/mirrors/mirrors.cgi?action=download&filename=pulsar) to get a faster download experience for user

**Comment by merlimat** [comment]
@jiazhai Which ones are you referring to? Some of the link need to be on archive (eg: old versions and signatures)

**Comment by jiazhai** [comment]
@merlimat Thanks for the reminder.  I see, will close this issue.
