### ISSUE TITLE
[java client] main class location problem with pulsar-client-admin 2.3.0

### ISSUE THREAD

**Issue by evgmitskevich** [apache/pulsar#3799]
**Description:**
In gradle project having these two files 
```
package examplepackage;

public class Launcher {
    public static void main(String[] args) {}
}
```
```
repositories {
    mavenCentral()
}

dependencies {
    compile group: 'org.apache.pulsar', name: 'pulsar-client-admin', version: '2.3.0'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
```
there is problem after building jar: `java -cp jar-with-dependencies.jar examplepackage.Launcher` results in `Error: Could not find or load main class examplepackage.Launcher`. 

I guess the reason is in transitive `org.bouncycastle` dependency, because excluding it eliminates the problem.

**Desktop:**
 - OS: Mac OS & Ubuntu
 - pulsar-client-admin version: 2.3.0

**Comment by sijie** [comment]
@evgmitskevich it seems you already find a solution to fix the issue. what else we can do for this issue here?

**Comment by sijie** [comment]
Closed this issue since the problem was found.
