### ISSUE TITLE
cmake config are not valid for windows

### ISSUE THREAD

**Issue by aahmed-se** [apache/pulsar#3800]
Current Cmake config doesn't not work for non gcc compilers in windows

```
if (NOT APPLE)
    # we don't set options below to build _pulsar.so
    set(CMAKE_CXX_FLAGS_PYTHON "${CMAKE_CXX_FLAGS}")
    # Hide all non-exported symbols to avoid conflicts
    set(CMAKE_CXX_FLAGS " -fvisibility=hidden -Wl,--exclude-libs,ALL ${CMAKE_CXX_FLAGS}")
endif ()
```

**Comment by aahmed-se** [comment]
```
"C:\Users\test\pulsar\pulsar-client-cpp\pulsar-cpp.sln" (pulsarShared target) (1) ->
"C:\Users\test\pulsar\pulsar-client-cpp\lib\pulsarShared.vcxproj.metaproj" (default target) (2) ->
"C:\Users\test\pulsar\pulsar-client-cpp\lib\pulsarShared.vcxproj" (default target) (4) ->
(ClCompile target) ->
  cl : Command line error D8021: invalid numeric argument '/Wl,--exclude-libs,ALL' [C:\Users\test\pulsar\pulsar-client-cpp\lib\pulsarShared.vcxproj]

    0 Warning(s)
    1 Error(s)
```

**Comment by aahmed-se** [comment]
"C:\Users\test\pulsar\pulsar-client-cpp\pulsar-cpp.sln" (pulsarShared target) (1) ->
"C:\Users\test\pulsar\pulsar-client-cpp\lib\pulsarShared.vcxproj.metaproj" (default target) (2) ->
"C:\Users\test\pulsar\pulsar-client-cpp\lib\pulsarShared.vcxproj" (default target) (4) ->
(ClCompile target) ->
  cl : Command line error D8021: invalid numeric argument '/Werror=switch' [C:\Users\test\pulsar\pulsar-client-cpp\lib\pulsarShared.vcxproj]

**Comment by aahmed-se** [comment]
Build FAILED.

"C:\Users\test\pulsar\pulsar-client-cpp\pulsar-cpp.sln" (pulsarShared target) (1) ->
"C:\Users\test\pulsar\pulsar-client-cpp\lib\pulsarShared.vcxproj.metaproj" (default target) (2) ->
"C:\Users\test\pulsar\pulsar-client-cpp\lib\pulsarShared.vcxproj" (default target) (4) ->
(ClCompile target) ->
  cl : Command line error D8021: invalid numeric argument '/Wno-deprecated-declarations' [C:\Users\test\pulsar\pulsar-client-cpp\lib\pulsarShared.vcxproj]

    0 Warning(s)
    1 Error(s)

**Comment by tisonkun** [comment]
Closed as stale. The development of C++ client has been permanently moved to https://github.com/apache/pulsar-client-cpp. If there are still some issues, please open again that repo.
