### ISSUE TITLE
Source jars do not contain any source code

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#3809]
**Describe the bug**
The source jar published to http://central.maven.org/maven2/org/apache/pulsar/pulsar-client-admin/2.3.0/pulsar-client-admin-2.3.0-sources.jar, does not contain any source code

**To Reproduce**
1. Go to 'http://central.maven.org/maven2/org/apache/pulsar/pulsar-client-admin/2.3.0/'
2. Click on 'pulsar-client-admin-2.3.0-sources.jar' to download the jar
3. List the jar contents, 'jar -tvf ~/Downloads/pulsar-client-admin-2.3.0-sources.jar`

jar -tvf ~/Downloads/pulsar-client-admin-2.3.0-sources.jar 
   126 Thu Feb 14 22:41:24 PST 2019 META-INF/MANIFEST.MF
     0 Thu Feb 14 22:41:24 PST 2019 META-INF/
     0 Thu Feb 14 22:41:24 PST 2019 META-INF/maven/
     0 Thu Feb 14 22:41:24 PST 2019 META-INF/maven/org.apache.pulsar/
     0 Thu Feb 14 22:41:24 PST 2019 META-INF/maven/org.apache.pulsar/pulsar-client-admin/
 11358 Thu Feb 14 22:41:24 PST 2019 META-INF/LICENSE
 21319 Thu Feb 14 22:41:24 PST 2019 META-INF/DEPENDENCIES
   132 Thu Feb 14 22:12:12 PST 2019 META-INF/maven/org.apache.pulsar/pulsar-client-admin/pom.properties
   172 Thu Feb 14 22:41:24 PST 2019 META-INF/NOTICE
 10627 Thu Feb 14 22:06:46 PST 2019 META-INF/maven/org.apache.pulsar/pulsar-client-admin/pom.xml

**Expected behavior**
The jar file should contain the source code for the pulsar client

**Comment by sijie** [comment]
pulsar-client and pulsar-client-admin are shaded jars. so I don't think it is trivial to support source jar for shade jars.

**Comment by jiazhai** [comment]
would like to close this issue. feel free to reopen it. @david-streamlio
