### ISSUE TITLE
[go client] Pointers vs. values in parameters 

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar#3813]
In pulsar-client-go, all of the structures we define are passed using values, but if the structure itself is large, using value passing sometimes causes a lot of memory copies.

eg:

```
producer, err := client.CreateProducer(ProducerOptions{
		Topic: topic,
	})

	assert.Nil(t, err)
	defer producer.Close()

	consumer, err := client.Subscribe(ConsumerOptions{
		Topic:             topic,
		SubscriptionName:  "my-sub",
		AckTimeout:        1 * time.Minute,
		Name:              "my-consumer-name",
		ReceiverQueueSize: 100,
		MaxTotalReceiverQueueSizeAcrossPartitions: 10000,
		Type: Shared,
	})
```
If we use pointers to pass, we will save a lot of resources.

**Comment by wolfstudy** [comment]
[https://golang.org/doc/faq#methods_on_values_or_pointers](https://golang.org/doc/faq#methods_on_values_or_pointers)

**Comment by Tevic** [comment]
In my opinion what you list it is a one-time costs,not the point. What‘s the point is that ProducerMessage struct used in producer.Send, copy occurs every time when produce. But if you refractor the code, sdk will not be forward compatible.

**Comment by wolfstudy** [comment]
> In my opinion what you list it is a one-time costs,not the point. What‘s the point is that ProducerMessage struct used in producer.Send, copy occurs every time when produce. But if you refractor the code, sdk will not be forward compatible.

Yes, this is also a point I am struggling with. As you have described, if there are some places where we can replace the value with point, I think this is a good idea. How to implement it, we can listen to the view of @merlimat .

**Comment by sijie** [comment]
@wolfstudy did we address the problem in native client implementation?

**Comment by wolfstudy** [comment]
> @wolfstudy did we address the problem in native client implementation?

No, in the native go client, we still have this problem. [pr:69](https://github.com/apache/pulsar-client-go/pull/69) is a better way to solve this problem.

In cgo client, maybe we can ignore this the problem, make sure sdk is forward compatible.

**Comment by codelipenghui** [comment]
@wolfstudy Any update for this issue? I noticed https://github.com/apache/pulsar-client-go/pull/69 was close. Is the issue resolved or shall we need to continue to fix this issue?

**Comment by wolfstudy** [comment]
@codelipenghui This question is raised for the cgo client. In the native go client, we have used this recommended method. Given that we are temporarily giving up maintaining the cgo client, I think we can close this issue.
