### ISSUE TITLE
Broker LoadFactor CPU NaN

### ISSUE THREAD

**Issue by sschepens** [apache/pulsar#382]
We've found that brokers are saving loadFactorCPU as `NaN` in zookeeper path `/loadbalance/settings/load_factor_cpu`, and think this is probably messing load balancing.
`{"loadFactorCPU":"NaN"}`
How can this end up being `NaN`? What consecuences can this bring?

PS: I've also seen some other fields in `/loadbalance/brokers/*` with NaN, such as `allocatedCPU` and `preAllocatedCPU`

**Comment by aahmed-se** [comment]
https://github.com/apache/incubator-pulsar/pull/2618

**Comment by aahmed-se** [comment]
this should be resolved in the next realease

**Comment by sijie** [comment]
This is fixed by #2618
