### ISSUE TITLE
Add a sink connector to export stream data to Alluxio

### ISSUE THREAD

**Issue by murong00** [apache/pulsar#3822]
[Alluxio](https://www.alluxio.org/) is an open-source virtual distributed file system that provides a unified data access layer for hybrid and multi cloud deployments. For some application cases, someone may expect to provide a sink connector to export pulsar messages to Alluxio.

**Comment by mingfang** [comment]
I think having an Alluxio Source would be great too.

**Comment by codelipenghui** [comment]
@murong00 Are you interested in implement this feature?

**Comment by murong00** [comment]
@codelipenghui This feature is already supported based on version 1.8.1, you can refer to #3823 for some detail, I have addressed sijie's comment, you can help to review it again.
