### ISSUE TITLE
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 5242880: 369295620 - discarded

### ISSUE THREAD

**Issue by tcbuzor** [apache/pulsar#3832]
**Describe the bug**
I installed Apache pulsar 2.3.0 and set up TLS by following the steps described in https://pulsar.apache.org/docs/en/security-tls-transport/ 
When I use the client in the pulsar distribution, I get the TooLonFrameException

11:36:56.866 [pulsar-io-49-3] INFO  org.apache.bookkeeper.mledger.impl.ManagedCursorImpl - [public/functions/persistent/coordinate-participants] Rewind from 120:0 to 120:0
11:37:01.309 [pulsar-io-49-4] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from /10.107.48.30:43 
11:37:01.329 [pulsar-io-49-4] WARN  org.apache.pulsar.broker.service.ServerCnx - [IP Address:43754] Got exception TooLongFrameException : Adjusted frame length exceeds 5242880: 369295620 - discarded
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 5242880: 369295620 - discarded
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
  
 11:37:01.334 [pulsar-io-49-4] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /10.107.48.30:43754 

**To Reproduce**
1. Download the Apache pulsar binary from https://pulsar.apache.org/en/download/
    Current version (Stable) 2.3.0
2. Unzip the binary and follow the steps for setting up TLS with self signed certificate
3. launch pulsar in standalone mode - ./pulsar standalone
4. start pulsar consumer ./pulsar-client -n 0 -s "TEST" TEST_TOPIC

**Expected behavior**
I expect the consumer to start listening for messages on TEST_TOPIC and the producer should be able to send messages to the TEST_TOPIC

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux 7

**Additional context**

**Comment by merlimat** [comment]
@tcbuzor this looks like a mismatch between client and server on whether TLS is enabled (eg: connecting with TLS on a non-TLS port or vice-versa)

the regular client command (`pulsar-client -n 0 -s "TEST" TEST_TOPIC`) will connector to `pulsar://localhost:6650` without TLS.

Use `pulsar-client --url pulsar+ssl://localhost:6651 ... ` to have the client use TLS when connecting.

**Comment by tcbuzor** [comment]
I got the same exception with the url option. B/W, I already added the following to the CLI:
webServiceUrl=https://broker.example.com:8443/
brokerServiceUrl=pulsar+ssl://broker.example.com:6651/
useTls=true
tlsAllowInsecureConnection=false
tlsTrustCertsFilePath=/path/to/ca.cert.pem
tlsEnableHostnameVerification=false

**Comment by sijie** [comment]
@tcbuzor does this happen constantly?

**Comment by youurayy** [comment]
This happens when you try to connect with `pulsar+ssl://` to a `https://` pulsar API endpoint.

The currently thrown exception is confusing.

**Comment by sijie** [comment]
@youurayy I think similar exceptions will be thrown if you connect to a port using a wrong protocol. it is a bit difficult to throw a better exception.

**Comment by codelipenghui** [comment]
Thanks, @sijie you made a clear explanation. So I will close this issue first.
