### ISSUE TITLE
Provide an option to delete schema when deleting a topic

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#3837]
**Is your feature request related to a problem? Please describe.**

Currently the lifecycle of schema is not tied to the lifecycle of a topic. So when a topic is deleted, the schema might still be there. This will result in an unexpected behavior when people try to delete a topic to resolve schema incompatibility issue. See description at issue #2786 

**Describe the solution you'd like**

Either we delete the schema along with deleting the topic. Or providing an option to delete schema when deleting a topic.

**Additional context**

N/A

**Comment by chrismiller** [comment]
One use case for this is during development, when the schema is still in a state of flux. Currently for every incompatible schema change a new topic has to be created (e.g. MyTopic_v1, MyTopic_v2, ...). This makes testing and releasing (with the desired production topic name) more difficult than it should be.

**Comment by liketic** [comment]
Hi @sijie , I'm happy to work on this. From what I understand, we need to add an argument which may be called ```deleteSchema``` in the ```delete``` API of ```Topic```. Am I right?

**Comment by tuteng** [comment]
@liketic I just submitted this https://github.com/apache/pulsar/pull/3941
