### ISSUE TITLE
Functions/Source/Sink REST API page can't be loaded

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#3901]
**Describe the bug**

http://pulsar.apache.org/functions-rest-api/ isn't loaded.

**Screenshots**
<img width="1666" alt="Screen Shot 2019-03-25 at 10 39 18 PM" src="https://user-images.githubusercontent.com/1217863/54973883-1a136480-4f4f-11e9-8cfd-d3757e6cc8e6.png">

**Context**

It might be related to #3871 

See comment at https://github.com/apache/pulsar/pull/3871#pullrequestreview-217072136

**Comment by sijie** [comment]
@srkukarni ^

**Comment by srkukarni** [comment]
That's wierd. Its interesting because this works on the laptop. I will send out a pr to revert it but any chance we can test it to make sure it works on apache infra?

**Comment by sijie** [comment]
thank you @srkukarni

**Comment by sijie** [comment]
This has been fixed by #4024
