### ISSUE TITLE
link failure

### ISSUE THREAD

**Issue by Xlingxiao** [apache/pulsar#3903]
An error occurred while installing the Pulsar-connectors

$ wget https://archive.apache.org/dist/pulsar/pulsar-2.3.0/apache-pulsar-io-connectors-2.3.0-bin.tar.gz

HTTP Code is 404

**Comment by liangyuanpeng** [comment]
repeated  #3292

**Comment by ambition119** [comment]
this issue PR #3793

**Comment by Xlingxiao** [comment]
> this issue PR #3793 .
> @Xlingxiao you can access https://archive.apache.org/dist/pulsar/pulsar-2.3.0/connectors/ chose you want connector. thanks

Please tell me which connector I should download if I need to use Pulsar SQL

**Comment by ambition119** [comment]
> > this issue PR #3793 .
> > @Xlingxiao you can access https://archive.apache.org/dist/pulsar/pulsar-2.3.0/connectors/ chose you want connector. thanks
> 
> Please tell me which connector I should download if I need to use Pulsar SQL

just use sql function not necessary connector, doc info:
http://pulsar.apache.org/docs/en/sql-getting-started/

**Comment by Xlingxiao** [comment]
> > > this issue PR #3793 .
> > > @Xlingxiao you can access https://archive.apache.org/dist/pulsar/pulsar-2.3.0/connectors/ chose you want connector. thanks
> > 
> > 
> > Please tell me which connector I should download if I need to use Pulsar SQL
> 
> just use sql function not necessary connector, doc info:
> http://pulsar.apache.org/docs/en/sql-getting-started/

Many thanks

**Comment by ambition119** [comment]
> > > > this issue PR #3793 .
> > > > @Xlingxiao you can access https://archive.apache.org/dist/pulsar/pulsar-2.3.0/connectors/ chose you want connector. thanks
> > > 
> > > 
> > > Please tell me which connector I should download if I need to use Pulsar SQL
> > 
> > 
> > just use sql function not necessary connector, doc info:
> > http://pulsar.apache.org/docs/en/sql-getting-started/
> 
> Many thanks ，I am a beginner，sorry

You are welcome, welcome to use and ask questions or create issue.

**Comment by sijie** [comment]
#3793 was fixed.
