### ISSUE TITLE
Pulsar source/sink creation fails when using JSON config values

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#3908]
**Description**
When executing `pulsar-admin source create` or `pulsar-admin sink create`, the created source/sink fails to operate as expected when config values are specified via JSON rather than via a config file. 
Being able to create sources and sinks with inline JSON is particularly important for our CI/CD automation because it gets complicated if we need to track a lot of config files

**To Reproduce**
Execute a command like this:

```
bin/pulsar-admin source create \
          --source-type 'kafka' \
          --destinationTopicName  exampleTopic \
          --sourceConfig '{"bootstrapServers": "kafka01.FQDN.com:9092,kafka02.FQDN.com:9092,kafka03.FQDN.com:9092", "consumerConfigProperties.auto.offset.reset": "earliest", "consumerConfigProperties.sasl.jaas.config": "com.sun.security.auth.module.Krb5LoginModule required doNotPrompt=true useTicketCache=false serviceName=\"kafka\" principal=\"pulsar_runtime@FQDN.COM\" useKeyTab=true keyTab=\"/pulsar/conf/auth/pulsar_runtime_test.keytab\" client=true; ", "consumerConfigProperties.sasl.kerberos.service.name": "kafka", "consumerConfigProperties.security.protocol": "SASL_PLAINTEXT", "groupId": "abandoned-site-group", "topic": " exampleTopic"}' \
          --source-type 'kafka' \
          --namespace  exampleNamespace \
          --name campaign-kafka-source \
          --tenant osp
```

The command will report that the source was created successfully; however, the source will not operate as desired. However, the source will operate as desired if the config-file approach is used, like this:

```
bin/pulsar-admin source create \
          --source-type 'kafka' \
          --destinationTopicName  exampleTopic \
          --sourceConfigFile /path/to/file.yml  \
          --source-type 'kafka' \
          --namespace  exampleNamespace \
          --name campaign-kafka-source \
          --tenant osp
```
where the config file is like this:

```bootstrapServers: "kafka01.FQDN.com:9092,kafka02.FQDN.com:9092,kafka03.FQDN.com:9092"
groupId: "abandoned-site-group"
topic: " exampleTopic"
consumerConfigProperties:
    security.protocol: "SASL_PLAINTEXT"
    sasl.kerberos.service.name: "kafka"
    auto.offset.reset: "earliest"
    sasl.jaas.config: "com.sun.security.auth.module.Krb5LoginModule required doNotPrompt=true useTicketCache=false serviceName=\"kafka\" principal=\"pulsar_runtime@FQDN.COM\" useKeyTab=true keyTab=\"/pulsar/conf/auth/pulsar_runtime_test.keytab\" client=true; "
```

Notice that the JSON is flattened in comparison to the config file. We initially tried having the JSON match the hierarchy in the YAML, but we got errors. So, we flattened it by combining `consumerConfigProperties` with the properties under it like: `security.protocol` to produce properties like `consumerConfigProperties.security.protocol`, which match the "key/value" requirements specified in Pulsar documentation. 

**Expected behavior**
The source should function correctly when executing a command with inline JSON.

**Desktop (please complete the following information):**
 - OS: https://github.com/apache/pulsar/tree/branch-2.3/docker/pulsar-all
(Docker using `pulsar-all` container with release `2.3.0`

**Additional context**
We're running Pulsar in a cluster.

**Comment by tuteng** [comment]
@devinbost Is there a problem with startup in mode standalone? Can you provide some log information?

**Comment by murong00** [comment]
@tuteng @devinbost I think the PR #3432 may occur this error when using `load(Map<String, Object> map)` which added a variable `Map<String, Object>` for properties.

**Comment by murong00** [comment]
@sijie @jiazhai How do you think about this? I guess we should use a `CustomMapDeserializer` on this field to deseralize the config Map to the specific class. If so, I will work on this.

**Comment by murong00** [comment]
@devinbost @tuteng The current implementation occurs the following error when using config such as`{"bootstrapServers":"localhost:6667","acks":"1","producerConfigProperties":{"sasl.kerberos.service.name":"kafka","client.id":"kobe.bryant"},"topic":"topic_2"}`:
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 104 path $.
```
