### ISSUE TITLE
Allow client authentication from pulsar-flink package

### ISSUE THREAD

**Issue by shiv4289** [apache/pulsar#3939]
**Is your feature request related to a problem? Please describe.**
We recently enabled JWT based authentication on our brokers. Though the native pulsar client allows setting tokens in the client builder, the pulsar-flink connector does not provide a way to provide authentication token to the pulsar client used internally.

**Describe the solution you'd like**
Pulsar-flink module should accept auth token / provider. Further when building the pulsar client:
1. Pulsar-flink should check if auth is enabled.
2. If yes. set the same when building pulsar-client instance.

**Describe alternatives you've considered**
There is no alternative. It is not possible to provide auth info to pulsar-flink.

**Additional context**
Here is how the the pulsar-flink module builds pulsar-client:
`PulsarClient client = PulsarClient.builder().serviceUrl(serviceUrl).build();`

**Comment by ambition119** [comment]
Add org.apache.pulsar.client.impl.auth.AuthenticationJwt to solve JWT authorization. I will try to develop if everyone agrees with this way.

**Comment by shiv4289** [comment]
Hello,

I submitted a PR at https://github.com/apache/pulsar/pull/3949
Please have a look and let me know your feedback.

Regards,
Shivji Kumar Jha
http://www.shivjijha.com/
+91 8884075512
