### ISSUE TITLE
[pulsar-flink] Use an extensible client conf to forward to pulsar native client configs

### ISSUE THREAD

**Issue by shiv4289** [apache/pulsar#3954]
**Is your feature request related to a problem? Please describe.**
The current implementation of pulsar-flink takes serviceUrl and topic as params and initialises pulsar client from these params. It is not possible to pass other pulsar client params to pulsar-flink connector.

**Describe the solution you'd like**
pulsar-flink should accept all the params pulsar-client accepts. This should also be extensible so future pulsar-client params can be sent without any modifications to the pulsar-flink module. The idea is to accept pulsar-client params as Map<String, Object> and pass this map to the pulsar-client builder.

This would sit well with the future additions in pulsar-client in future too.

**Comment by shiv4289** [comment]
The issue was re-oponed as a result of this chat on slack:

> @sijieg Can you please re-open this https://github.com/apache/pulsar/issues/3954
> I would like to add Map<String, Object> to other places in flink connector.
> https://github.com/apache/pulsar/pull/3955 actually only handled streaming and producer use case. We need consumer at least.. I can contribute that PR in a couple of days to add Map everywhere (streaming + batch, producer + consumer etc)! (edited)

**Comment by sijie** [comment]
This has been fixed.
