### ISSUE TITLE
Can`t get pulsar-client-go lib

### ISSUE THREAD

**Issue by xrayid** [apache/pulsar#3968]
Hello!
Centos 7
go version go1.12.1 linux/amd64

Reproduce:
```
yum install apache-pulsar-client-2.3.0-1.x86_64.rpm
yum install apache-pulsar-client-devel-2.3.0-1.x86_64.rpm
go get github.com/apache/pulsar/pulsar-client-go/pulsar
```

Result:
```
Error:
# github.com/apache/pulsar/pulsar-client-go/pulsar
src/github.com/apache/pulsar/pulsar-client-go/pulsar/c_consumer.go:101:3: could not determine kind of name for C.pulsar_configure_set_negative_ack_redelivery_delay_ms
src/github.com/apache/pulsar/pulsar-client-go/pulsar/c_consumer.go:263:2: could not determine kind of name for C.pulsar_consumer_negative_acknowledge
src/github.com/apache/pulsar/pulsar-client-go/pulsar/c_consumer.go:268:2: could not determine kind of name for C.pulsar_consumer_negative_acknowledge_id
```

How to fix it?

**Comment by grantwwu** [comment]
This looks like a version mismatch between the Go client and the installed C++ library.

**Comment by xrayid** [comment]
> This looks like a version mismatch between the Go client and the installed C++ library.

Fixed! Thx

**Comment by StartFeng** [comment]
@xrayid How fixed it?

**Comment by xrayid** [comment]
I installed go library using go dep (package version v2.3.0)

**Comment by gurgen2727** [comment]
Doesn't work at all:

pip3 install pulsar-client
Collecting pulsar-client
ERROR: Could not find a version that satisfies the requirement pulsar-client (from versions: none)
ERROR: No matching distribution found for pulsar-client

pip3 install pulsar-client==2.4.0
Collecting pulsar-client==2.4.0
ERROR: Could not find a version that satisfies the requirement pulsar-client==2.4.0 (from versions: none)
ERROR: No matching distribution found for pulsar-client==2.4.0

I am on Windows 10, python 3 version.

**Comment by grantwwu** [comment]
That's because the pulsar-client packages for after 2.3.1 aren't available outside linux because CI is broken

**Comment by gurgen2727** [comment]
makes sense, thank you, though it wasn't written anywhere in the documentation.
managed to install in Ubuntu 18.04.2 LTS (Bionic Beaver) running in VirtualBox under Windows 10 for python version 2

But even simple got doesn't work for me:
     import pulsar
     client = pulsar.Client('pulsar://localhost:6650')
     producer = client.create_producer('my-topic')
     producer.send("testing")
     client.close()
 
2019-07-16 18:19:47.192 INFO  ConnectionPool:72 | Created connection for pulsar://localhost:6650
2019-07-16 18:19:47.193 ERROR ClientConnection:360 | [<none> -> pulsar://localhost:6650] Failed to establish connection: Connection refused
2019-07-16 18:19:47.193 INFO  ClientConnection:1297 | [<none> -> pulsar://localhost:6650] Connection closed
2019-07-16 18:19:47.193 ERROR ClientImpl:182 | Error Checking/Getting Partition Metadata while creating producer on persistent://public/default/my-topic -- 5
2019-07-16 18:19:47.193 INFO  ClientImpl:482 | Closing Pulsar client
Traceback (most recent call last):
  File "flask_server.py", line 70, in <module>
    pulsar_producer()
  File "flask_server.py", line 59, in pulsar_producer
    producer = client.create_producer('my-topic')
  File "/usr/local/lib/python2.7/dist-packages/pulsar/__init__.py", line 476, in create_producer
    p._producer = self._client.create_producer(topic, conf)
Exception: Pulsar error: ConnectError
2019-07-16 18:19:47.200 INFO  ClientConnection:222 | [<none> -> pulsar://localhost:6650] Destroyed connection


changing 'pulsar://localhost:6650' -> 'http://<local_ip>6650' doesn't work either.
I am really confused with this library.

**Comment by grantwwu** [comment]
Did you manually create `ns1`?   The only namespace that exists by default is named `default`.

**Comment by gurgen2727** [comment]
Hi

I found it here: https://github.com/streamlio/pulsar-python-tutorial
this tutorial are just horrible, do you have normal uptodate version link please ?

BTW I have tried as you suggested, it's the same error.

python pulsar_consumer.py 
2019-07-16 19:49:24.587 INFO  Client:88 | Subscribing on Topic :persistent://public/default/my-topic
2019-07-16 19:49:24.587 INFO  ConnectionPool:72 | Created connection for pulsar://localhost:6650
2019-07-16 19:49:24.588 ERROR ClientConnection:360 | [<none> -> pulsar://localhost:6650] Failed to establish connection: Connection refused

Gurgen

**Comment by grantwwu** [comment]
That other tutorial is very old.

Do you see any logs from pulsar standalone at all?

**Comment by gurgen2727** [comment]
thank you very much. Just your comment helped me :-D 

I tried to install standalone from scratch as it is mentioned here for version 2.4.0
https://pulsar.apache.org/docs/en/standalone/

now standalone runs fine (bin/pulsar standalone)
and I managed to send & receive messages.

**Comment by gurgen2727** [comment]
Hi

I have another question :)
The following schema doesn't work at all during create_producer, I want to pass array of maps (list of dictionaries), why it doesn't work ? please ?

class MySchema(Record):
    a1 = String()
    b1 = Long()
    # array of dict, json data
    data = Array(Map(String()))

this crashes during instance creation, even I didn't reach to send.
producer = client.create_producer(topic='mytopic15', schema=AvroSchema(MySchema))

Gurgen

**Comment by grantwwu** [comment]
@gurgen2727 Have you tried joining the Pulsar Slack? I think that might be a more appropriate forum for these questions than an unrelated bug thread.

**Comment by gurgen2727** [comment]
@grantwwu because nobody knows the answer and nobody answers for days there, you are the only person who responded to my question, also if you are concerned about ticket, don't worry I will remove all my comments as soon as I finish my projects, so your ticket will be clean. 
Thanks
Gurgen

**Comment by grantwwu** [comment]
...Please don't delete your comments...

I'm in the Slack as well.  It really depends on whether I (and other people) are free and whether or not we're capable of answering the question.  For example I recently saw your Avro schema question and didn't answer it because I've never worked with it.

**Comment by abrahamsangha** [comment]
@gurgen2727 how did you solve this issue?

**Comment by gurgen2727** [comment]
> @gurgen2727 how did you solve this issue?

just run server correctly before running client, was stupid question from my side, easy solvable.
