### ISSUE TITLE
In Pulsar 2.3,` pulsar-admin topics list` will report read timed out

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#3970]
**Describe the bug**
user reported error while using `pulsar-admin topics list`, in cluster deploy.
![image](https://user-images.githubusercontent.com/6348208/55448017-bfd26d80-55f8-11e9-8dec-0b5797942b6e.png)

namespaces/tenants list works well
![image](https://user-images.githubusercontent.com/6348208/55448042-d4166a80-55f8-11e9-9c0a-acc1554a0d50.png)

**Comment by merlimat** [comment]
This seems to be the same issue that was already fixed in #3776
