### ISSUE TITLE
[Question] Geo Replication docs out of date?

### ISSUE THREAD

**Issue by wmccarley** [apache/pulsar#3989]
The documentation on [Geo Replication](https://pulsar.apache.org/docs/latest/admin/GeoReplication/#creating-global-namespaces) mentions: 

> Replication must be used with global topics, meaning topics that belong to a global namespace and are thus not tied to any particular cluster... **Global namespaces need to be created in the global virtual cluster.**

Is this part of documentation still valid? It seems I can create namespaces that replicate between two clusters (i.e. creating a namespace for a given tenant and then using set-clusters to set both ) without having to use the virtual cluster notation mentioned on this page.. Replication seems to work fine.

**Comment by merlimat** [comment]
@wmccarley Thanks for pointing out. the doc is indeed out of date. That was the behavior with Pulsar 1.x but we corrected the naming and simplified the namespaces in 2.0
