### ISSUE TITLE
Improve read performance for tiered-storage segment readout

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#4025]
As discussed in slack channel with @chairmank , Steve suggested that we could do a read-ahead to improve the read performance:

>I looked at `BlobStoreBackedInputStreamImpl` and `BlobStoreBackedReadHandleImpl` to understand how performance could be improved. I think that reads from blob store would be faster with speculative read-ahead, so that `refillBufferIfNeeded` can swap an already-populated buffer instead of blocking on a call to `blobStore.getBlob`.

**Comment by chairmank** [comment]
possibly related: https://github.com/apache/pulsar/issues/3804

**Comment by sijie** [comment]
Closed this since it is a duplicate of #3804
