### ISSUE TITLE
For functions, allow users to configure whether the output should inherit the key of the input

### ISSUE THREAD

**Issue by jerrypeng** [apache/pulsar#4041]
**Is your feature request related to a problem? Please describe.**

Currently, for Java functions, if the input message has a key associated with it, it is automatically inherit onto by the output message.

This might not be the desirable behavior for all scenarios.

In Python functions, the keys of input messages are not inherited by output messages.

**Describe the solution you'd like**

Allow users to configure that behavior.  Make behavior of Python and Java functions consistent

**Comment by sijie** [comment]
This issue has been implemented with the flag `forward message properties`.
