### ISSUE TITLE
Need to catch up docs for functions/sink/source in Admin CLI

### ISSUE THREAD

**Issue by murong00** [apache/pulsar#4047]
**Describe the bug**
Some of the subcommands of functions/sink/source are not documented in [Pulsar admin CLI](http://pulsar.apache.org/docs/en/pulsar-admin/), such as `sink/source status`. We need update the doc to catch up the work.

**Comment by jerrypeng** [comment]
@murong00 thanks for submitting this issue.  This is something that needs work.  Are you going to add the needed documentation?
