### ISSUE TITLE
Download lastest version in old version page

### ISSUE THREAD

**Issue by k2la** [apache/pulsar#4053]
https://pulsar.apache.org/docs/en/2.2.0/client-libraries-cpp/
When I clicked `deb cpp client` link in old version page,  I downloaded latest version of client.
Is that mistake?

**Comment by tuteng** [comment]
You can try to download from [here](https://archive.apache.org/dist/pulsar/), we will fix the old version address of the download.

**Comment by tuteng** [comment]
@Jennifer88huang @Anonymitaet Can you fix this problem?
Replace download link of the document to correct link https://archive.apache.org/dist/pulsar/

**Comment by Anonymitaet** [comment]
@tuteng glad to help

**Comment by Jennifer88huang** [comment]
@Anonymitaet would you like to fix it?

**Comment by Anonymitaet** [comment]
@Jennifer88huang sure

**Comment by Jennifer88huang** [comment]
It's was fixed in #5865
