### ISSUE TITLE
Exposing `MaxMessageSize` to user configuration

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar#4054]
**Is your feature request related to a problem? Please describe.**

Now, I want to send a larger message to pulsar, but pulsar's `MaxMessageSize` is in the form of hardcode. If the size of the message > 5MB, the pulsar client will fail.

code as follows:

```
    // Max message size is limited by max BookKeeper entry size which is 5MB, and we need to account
    // for headers as well.
    public final static int MaxMessageSize = (5 * 1024 * 1024 - (10 * 1024));
    public final static int MaxFrameSize = 5 * 1024 * 1024;
```

**Describe the solution you'd like**

In kafka, `MaxMessageSize` is a configurable option. We can also consider exposing it to the user as a configurable option. Of course, we may need to modify the size of the bookkeeper for the size of the message.

```
# The maximum netty frame size in bytes. Any message received larger than this will be rejeted. Default value is 5MB.
# nettyMaxFrameSizeBytes=5242880
```

**Comment by merlimat** [comment]
Yes, the limit was very arbitrarily picked. It would be nice to have config options in brokers/clients

**Comment by ambition119** [comment]
I'm interested in trying to solve this issue, tks

**Comment by hellozepp** [comment]
Hi~ @zymap , What is the progress now?

**Comment by zymap** [comment]
@hellozepp  It's already implement. https://github.com/apache/pulsar/pull/4247

**Comment by xianhua** [comment]
I am using 2.7.0 and I tried to set the maxMessageSize to 10M. I still got error complaining about max size allowed is 5M when published message > 5M. I wonder if I missed any other config and need to do something on client side. I am using java API for pulsar v2.7.0.  Thanks.

**Comment by zymap** [comment]
You need to set `maxMessageSize` in broker.conf and set `nettyMaxFrameSizeBytes` in bookkeeper.conf.
