### ISSUE TITLE
could not determine kind of name for C.pulsar_configure_set_negative_ack_redelivery_delay_ms

### ISSUE THREAD

**Issue by chrislearn** [apache/pulsar#4055]
**Describe the bug**
When I upgrade my app to use the latest pulsar 2.3.1, compile report this error:
/home/chris/.gvm/pkgsets/go1.12.1/global/pkg/mod/github.com/apache/pulsar/pulsar-client-go@v0.0.0-20190416000109-76aacd3c3477/pulsar/c_consumer.go:101:3: could not determine kind of name for C.pulsar_conf
igure_set_negative_ack_redelivery_delay_ms
/home/chris/.gvm/pkgsets/go1.12.1/global/pkg/mod/github.com/apache/pulsar/pulsar-client-go@v0.0.0-20190416000109-76aacd3c3477/pulsar/c_consumer.go:263:2: could not determine kind of name for C.pulsar_cons
umer_negative_acknowledge
/home/chris/.gvm/pkgsets/go1.12.1/global/pkg/mod/github.com/apache/pulsar/pulsar-client-go@v0.0.0-20190416000109-76aacd3c3477/pulsar/c_consumer.go:268:2: could not determine kind of name for C.pulsar_cons
umer_negative_acknowledge_id

**Screenshots**
![image](https://user-images.githubusercontent.com/5874864/56188611-8cf89280-6058-11e9-951e-725408b1cbc5.png)

**Desktop (please complete the following information):**
 - MacOS
 - Ubuntu

**Comment by merlimat** [comment]
@chrislearn Which tag are you pulling of the Go code? and which version of `libpulsar` C++ library do you have installed? 

It looks like this is the code from master, though the `libpulsar` library is 2.3.1.

**Comment by chrislearn** [comment]
I use latest libpulsar C++ library, 2.3.1
I use go module to install go client, but when I try to use `go get github.com/apache/pulsar/pulsar-client-go@v2.3.1` to install v2.3.1, it will report error:
`
go get github.com/apache/pulsar/pulsar-client-go@v2.3.1: unknown revision pulsar-client-go/v2.3.1
`
So I use this command to install go client from master: 
`
go get github.com/apache/pulsar/pulsar-client-go
`

**Comment by merlimat** [comment]
The tag is there though.. https://github.com/apache/pulsar/tree/v2.3.1/pulsar-client-go

you can work around by doing:
```
cd ~/go/src/github.com/apache/pulsar/pulsar-client-go/
git co v2.3.1
```

**Comment by chrislearn** [comment]
@merlimat You mean I need to checkout it manually. It is not supports go module?

**Comment by merlimat** [comment]
I think the problem is you’re trying to fetch a specific tad with go get which I’m not sure it supported (by Go get). 

Have you tried to use

```
$ dep ensure -add github.com/apache/pulsar/pulsar-client-go/pulsar@v2.3.1
```

Like explained on https://pulsar.apache.org/docs/en/client-libraries-go/

**Comment by chrislearn** [comment]
@merlimat go supports version tag in go get.
https://github.com/golang/go/wiki/Modules
My project use go module and I want to change it to use dep.

**Comment by NotBad4U** [comment]
I encounter the same errors with the `client-cpp 2.3.1`.
Fixing the pulsar-client-go version with `require github.com/apache/pulsar/pulsar-client-go v2.3.1` in the `go.mod` throw me the same error:
```
go: errors parsing go.mod:
/home/alessio/Projects/go/src/stream-dns/go.mod:5: invalid module version "v2.3.1": unknown revision pulsar-client-go/v2.3.1
```

Desktop:
- Linux
- arch and ubuntu

**Comment by simonliangnarvar** [comment]
@chrislearn @merlimat Do you have any idea how to solve `go mod` issue mentioned by @NotBad4U ? From [official documentation](http://pulsar.apache.org/docs/en/client-libraries-go/), it never mentions about it, but instead only `go get` and `dep`.

**Comment by simonliangnarvar** [comment]
Hi @chrislearn @merlimat @NotBad4U 
Any update one this issues? We meet the similar problem, especially unknown go modules for Pulsar 2.3.1.
Does anyone use go mod to successfully download/install Pulsar go client?
Thanks very much!

**Comment by chrislearn** [comment]
@simonliangnarvar
If the library's version is v1.x.x, I think add a version tag v1.x.x in git repository can let it supports go module.
But if the library's version is v2 or higher, according official documention, we need to change major branch or use subdirectory.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher
https://github.com/golang/go/wiki/Modules#semantic-import-versioning
https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning

**Comment by Jim-Lambert-Bose** [comment]
I got it work via...
```
# latest commit in the branch 2.3 branch
# https://github.com/apache/pulsar/commits/branch-2.3 
# which is: 1f4a836a46483db408e0bf39903215974262d946

# install 2.3.1
 brew install libpulsar  

# get the go-client module
go get github.com/apache/pulsar/pulsar-client-go@1f4a836a46483db408e0bf39903215974262d946

$ go run main.go
2019/05/16 13:21:59.388 c_client.go:68: [info] INFO  | ClientImpl:492 | Closing Pulsar client
```

**Comment by NotBad4U** [comment]
Hi :smile: 
any update one this issues?

**Comment by whisper-bye** [comment]
+1

**Comment by laurent75019** [comment]
I solved the problem by removing "HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH         = C.SDL_HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH         // specifies a variable to control whether mouse and touch events are to be treated together or separately" in the file :
C:\Users\lbaha\go\src\github.com\veandco\go-sdl2\sdl\hint.go

**Comment by NotBad4U** [comment]
Can you explain the link between `HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH` and the compilation errors: `could not determine kind of name for C.pulsar_...` @laurent75019 ? :thinking:

**Comment by NotBad4U** [comment]
Hello ! Any update on this one ?

**Comment by wolfstudy** [comment]
@NotBad4U can you provide more info for the issue, e.g:

- OS: Mac OS or Linux
- CPP Client Version: 
- CGO client version:
- Go Version:
- so on..

This information can help me reproduce the problem better, thanks.

**Comment by codelipenghui** [comment]
@NotBad4U Any update on this issue?
