### ISSUE TITLE
Migrate ledgers,admin,bookies,managed-ledgers,namespace Zookeeper directories to pulsar

### ISSUE THREAD

**Issue by RedBlackTreei** [apache/pulsar#4078]
**Situation:**
This problem occurred when I tried to delete the metadata in Zookeeper. I found that Pulsar store the metadata in the root directory, such as `ledgers、admin、bookies、managed-ledgers、namespace`, this may lead to conflict with other middlewares and cause inappropriate operations, I think it is very dangerous.
Besides, it is also very difficult to delete those metadata.

**Expectation:**

- Migrate those directories to `pulsar`
- Provide a tool to delete metadata, it is very useful when deploying a cluster for a green hand.

**Consideration:**
Of course, a new zookeeper a cluster can avoid this problem, but it also means more costs, not every company is willing to accept.

**Comment by merlimat** [comment]
zookeeper has a way to define a base directory in the connection string. Eg: `zk1:2181/my-prefix`. You just need to use that in your zk  connection string

**Comment by RedBlackTreei** [comment]
> zookeeper has a way to define a base directory in the connection string. Eg: `zk1:2181/my-prefix`. You just need to use that in your zk connection string

Thanks, great!
Add to document, may be better!

**Comment by sijie** [comment]
This has been documented in the website.
