### ISSUE TITLE
Tag v2.3.1 as latest

### ISSUE THREAD

**Issue by ruudk** [apache/pulsar#4085]
Better, don't use the `latest` flag in Github :)

<img width="537" alt="Screenshot 2019-04-19 at 19 20 46" src="https://user-images.githubusercontent.com/104180/56435294-4022ef00-62d8-11e9-922b-2fc0e0e0ce8e.png">

**Comment by merlimat** [comment]
Thanks for reporting! We forgot to publish the release on github last time. Done now and added to the release process instructions for next releases.

https://github.com/apache/pulsar/releases/tag/v2.3.1
