### ISSUE TITLE
2.3+ python client depends on bookkeeper client

### ISSUE THREAD

**Issue by vicaya** [apache/pulsar#4089]
**Describe the bug**
2.3+ python client pip install doesn't work on python slim images, as it pulls in bookkeeper client, which requires gcc to compile a source only dependency (mmh3). This breaks existing build systems that rely on python slim images.

**To Reproduce**
Use this Dockerfile
```
FROM python:3.6-slim
RUN pip install pulsar-client
```

**Expected behavior**
Before 2.3 the above Dockerfile works fine

**Additional context**
It appears that the bookkeeper client got pulled into pulsar-client to support pulsar-function writing, which is a new feature. I suggest that we create a separate pulsar-function-client package that depends on the lighter weight pulsar-client.

In some cases, the workaround is to use the full python image (928MB vs 138MB), which may not be possible in other cases.

**Comment by merlimat** [comment]
We'll try to get this fixed in BookKeeper-4.9.2 to include in Pulsar-2.3.2

**Comment by merlimat** [comment]
Created fix in https://github.com/apache/bookkeeper/pull/2069

**Comment by merlimat** [comment]
Fixed in BookKeeper 4.9.2.

`pip install apache-bookkeeper-client==4.9.2` Should let install the pulsar-client now.

**Comment by gurgen2727** [comment]
Doesn't work at all:
pip3 install  pulsar-client
Collecting pulsar-client
  ERROR: Could not find a version that satisfies the requirement pulsar-client (from versions: none)
ERROR: No matching distribution found for pulsar-client


I am on Windows 10, python 3 version.
