### ISSUE TITLE
[WIP][Pulsar Pipeline Plugin] add Pipeline plugin feature to pulsar

### ISSUE THREAD

**Issue by foreversunyao** [apache/pulsar#4094]
**Is your feature request related to a problem? Please describe.**

Currently we already have pulsar-io framework to let us make source/sink easily. And it would be better if we can have **pipeline plugin system** to **combine** multiple source/sink and make them work together like a data pipeline , and also it could make everyone to implement pulsar pipeline easier(like just make a config file). 

**Describe the solution you'd like**
Probably rely on pulsar-io framework.
**Config** could be:
```
## config
{
   "Source": {
       "Package": "pulsar-io-source-xxx",
       "Parameters": {"conn":"","threads":2},
       "Name": "pulsar-io-source-xxx_1"
   },
   "Plugins": [
       {
           "Package": "plugin/wordcount",             --- simple process and send result back to pulsar directly by default
           "Name":"wordcount_1"
           "Parameters": {}
       },
       {
           "Package": "plugin/cassandrasink",        --- a sink io and send result back to pulsar directly by default

           "Name": "pulsar-io-cassandrasink",
           "Parameters": {}
       },
       {
           "Package": "plugin/kafka",                --- a sink io and send result back to pulsar directly by default

           "Name": "kafka_1",
           "Parameters": {}
       }
   ],
   "NumRetry": 3,
   "NumWorkers":20,
   "HttpPort": 6666, ---admin port for getting pipeline metrics 
   "FailureResovling": "exit"
}

```

**Design**
https://docs.google.com/document/d/1Hy7NSzZT-5oo2UvuhjrCM0SSl8n9ySiWdHBZ__qMFjc/edit

**Additional context**

**Comment by foreversunyao** [comment]
@sijie , I updated the design document, could be ready to start a discussion for more details.

**Comment by sijie** [comment]
@foreversunyao sorry that I forgot to review this. I am wondering if you would like to send this out as a PIP, so that more people in the community can help review it.

**Comment by tisonkun** [comment]
Closed as stale. As sijie suggested above, you can submit a PIP to the dev@ mailing list to see if there's a consensus.
