### ISSUE TITLE
Closed consumers remain in websocket proxy

### ISSUE THREAD

**Issue by k2la** [apache/pulsar#4098]
#### Expected behavior
 
After websocket clients are closed, consumers connected with them in websocket proxy should be closed and removed.
 
#### Actual behavior
 
After the clients are closed, some consumers remain in websocket proxy.
The consumers remain until websocket proxies restart.
 
#### Findings of research
- According to heap dump, their reference from `ConsumerHandler` is removed but they exist in `consumers (properties of ClientCnx`).
- `closeAsync()` of the consumers seems to finish properly since error messages like `Failed to close consumer` are not in logs. 
 
#### Steps to reproduce
 
We tried but haven't reproduced yet.
That occurred with two topics.
 
- Situation
  - Clients connect with websocket proxies again every time recieve messages.
  - SubscriptionType: `Shared`.
 
#### System configuration
 
**Pulsar version**: 2.2.1
**Java version:** 1.8
**OS:** Linux

**Comment by tisonkun** [comment]
Closed as stale for a long time, and no one works on it.
