### ISSUE TITLE
DeadLetterTopic is not working for FailOver subscription type

### ISSUE THREAD

**Issue by lakarchitect** [apache/pulsar#4100]
**Describe the bug**
DeadLetterTopic is not working for FailOver subscription type

**To Reproduce**
Create a subscription with type  FailOver, with maxRedeliverCount say 3, Do not ack the receipt of a message in the test code. After 3 retries, the message is supposed to be delivered to DeadLetterTopic, but it's continuously retrying without upper bound. The redeliverCount is increasing in Shared subscription but in Failover subscription redeliverCount is not increasing.

Note:This is working fine in Shared Subscription type

**Expected behavior**
After 3 retries, the message is supposed to be delivered to DeadLetterTopic, but it's continuously retrying without upper bound.

**Comment by codelipenghui** [comment]
DeadLetterTopic feature is disabled for `FailOver` and `Exclusive` subscription at broker side.

**Comment by lakarchitect** [comment]
May i know more details on why? Also what are the alternatives suggested, does it mean cursor will not move until the message is processed and acked ?

**Comment by codelipenghui** [comment]
> May i know more details on why? 

For `FailOver` and `Exclusive` subscription mode, pulsar do not track the ack status for each message. When message redelivery happens in  `FailOver` or `Exclusive` mode,  broker just rewind the cursor(Currently, no sign for ack timeout message).  So we originally supported this feature in `Shared` mode.

This is possible to support this feature in  `FailOver` or `Exclusive` mode. Like in `Shared` mode, we need a `RedeliveryTracker` to track each ack timeout message, there are some differences between `Shared` mode, we need a ordered structure to maintain position. 

> Also what are the alternatives suggested, does it mean cursor will not move until the message is processed and acked ?

As far as I know there is no alternative currently, If message cannot be successfully acked, cursor will not move.

By the way, can I know your usage scenario?

**Comment by sijie** [comment]
changed this issue from a bug to a feature. because originally we were planning to support deadletter topic for shared subscription only. If we are going to support it for exclusive and failover, it is a feature request here.

**Comment by jkolash** [comment]
I'm curious if there Is there any timeline on when this would be implemented? We are using the Failover mode and would like to have this just work if possible.

**Comment by codelipenghui** [comment]
@jkolash Could you please share your use case? The DLQ essentially makes the messages out of order. This violates the semantics of failover subscription

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.

Now, you can ask questions in https://github.com/apache/pulsar/discussions/categories/q-a instead, or send feature request which you don't have idea to implement in https://github.com/apache/pulsar/discussions/categories/general, since we almost use issues to track actionable tasks.
