### ISSUE TITLE
[Websockets] Support server-side schema validation

### ISSUE THREAD

**Issue by ruudk** [apache/pulsar#4109]
**Is your feature request related to a problem? Please describe.**
I'm using Websockets and want to use server-side Schema validation. Currently, this is not supported for Websockets.

**Additional context**
See [chat transcript](https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1556043593312000) on Pulsar Slack channel.

**Comment by tisonkun** [comment]
Closed as stale for a long time, and no one works on it.
