### ISSUE TITLE
Documentation for Dead letter topic

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#4119]
This is a task to track documentation of dead letter topic.

**Comment by sijie** [comment]
@codelipenghui wondering if you have time to provide the content for dead letter topic. @Jennifer88huang or @Anonymitaet can help with writing the documentation.

**Comment by Jennifer88huang** [comment]
Sure. When the doc related material is ready, feel free to contact us.

**Comment by Anonymitaet** [comment]
Glad to help @codelipenghui
