### ISSUE TITLE
Policies not found && ServiceNotReady

### ISSUE THREAD

**Issue by LvBay** [apache/pulsar#4128]
**Describe the bug**

pulsar 2.3.0

1. When i produce or consumer the topic named `persistent://tenant/namespace1/topic1`,
pulsar returns the error `Policies not found for tenant/namespace1 namespace`. If the topic named `persistent://tenant/namespace1/ns/topic1`, it is fine.

2. When I produce a message to a new topic(`persistent://tenant/namespace1/ns/topic1`), I must subscribe to this topic first. Otherwise I will get this error: ServiceNotReady: `Namespace bundle for topic (persistent://tenant/namespace1/ns/topic1) not served by this instance. Please redo the lookup. Request is denied: namespace=tenant/namespace1/ns`

**Expected behavior**
1.  The naming convention for topic, consistent with the document [doc](https://pulsar.apache.org/docs/zh-CN/next/concepts-messaging/#topics)

2. If the client attempts to write or accept a message from a topic that does not yet exist, pulsar will automatically create

**Comment by sijie** [comment]
@LvBay 

A couple questions to help with your problem:

- how do you setup pulsar? standalone or in a cluster.
- what was the commands you used for creating tenants and namespaces?

**Comment by LvBay** [comment]
@sijie 
1. standalone, use pulsar/docker-compose/standalone-dashboard/docker-compose.yml
2. Sorry, I found that the second problem may be caused by my client. When I use ./bin/pulsar-client produce, everything is normal. But when I use go-client to send a message to a new tenant or topic under namespace, I have to initialize a consumer before I can generate a message.

**Comment by LvBay** [comment]
@sijie 
About the second, i got it. I should send LookupTopic command before generating a message for a new topic.

Is there a progress in the first question?

**Comment by sijie** [comment]
@LvBay 

Sorry for late response. I missed your reply 3 days ago. 

It seems that you created a namespace `namespace1/ns`. Is that the case? 

Pulsar doesn't allow using "/". Because it will confuses Pulsar whether it is a v1 topic or v2 topic.
