### ISSUE TITLE
Warning: Nashorn engine is planned to be removed from a future JDK release

### ISSUE THREAD

**Issue by ruudk** [apache/pulsar#4131]
When using the latest `pulsar-admin` commands I get this message every time:
```
Warning: Nashorn engine is planned to be removed from a future JDK release
```

Can it be removed / ignored?

**Comment by sijie** [comment]
@ruudk can you provide more information on the jdk you are using?

**Comment by rosenk** [comment]
$ java --version
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)

**Comment by sijie** [comment]
https://openjdk.java.net/jeps/335 the warning is coming from JDK itself. you can ignore the warning message.

**Comment by sijie** [comment]
Since the warning message is from the JDK itself, there is nothing we can do from Pulsar side. Closed this issue.
