### ISSUE TITLE
Featuring pulsar in Docusaurus

### ISSUE THREAD

**Issue by NishealJ** [apache/pulsar#4163]
Hello, we would like to feature your project to the Docusaurus users page.
Would that be ok? Also can you provide your logo?

More info about this [here](https://github.com/facebook/Docusaurus/issues/1080)

**Comment by sijie** [comment]
@NishealJ yes. there is no problem about that.

You can find Pulsar's logo under https://github.com/apache/pulsar/blob/master/site2/website/static/img/pulsar.svg

**Comment by NishealJ** [comment]
Hi,
Has been added Thanks :) !

**Comment by sijie** [comment]
Awesome @NishealJ !
