### ISSUE TITLE
The superuser cannot obtain lastMessageId

### ISSUE THREAD

**Issue by Xlingxiao** [apache/pulsar#4164]
partition-0 get lastMessageId `401 Authentication required`
![image](https://user-images.githubusercontent.com/34467450/56876049-456dff80-6a77-11e9-8df7-f49a88a5e4e6.png)

partition-1 get lastMessageId is ok
![image](https://user-images.githubusercontent.com/34467450/56876036-30916c00-6a77-11e9-9f82-807362b2e35b.png)

**Comment by Xlingxiao** [comment]
The number of partitions for topic is 4.in java client  parition-0 and partition-3  is ok ,but partition-1 and partition-2 like this `401 Authentication required`

**Comment by sijie** [comment]
@Xlingxiao are you using JWT authentication? 

Which version of pulsar are you using?

**Comment by Xlingxiao** [comment]
@sijie Im using JWT authentication。Pulsar version is `pulsar-2.3.1`

**Comment by Xlingxiao** [comment]
Can I use Chinese ？

this is new problem：
这里又有新的问题出现了：

```
[zx@slave107 ~]$ pulsar-admin clusters list
lx_cluster_1
[zx@slave107 ~]$ pulsar-admin clusters get lx_cluster_1
Cluster does not exist

Reason: Cluster does not exist
[zx@slave107 ~]$ 
```

**Comment by sijie** [comment]
@Xlingxiao :

>  Im using JWT authentication。Pulsar version is pulsar-2.3.1

I looked at your screenshots - it seems that you are issuing the `lastMessageId` directly to the admin endpoint. it seems your JWT authentication is lost when the http request is redirected. There is a similar issue in java admin client : https://github.com/apache/pulsar/pull/3869 . 

I would suggest you using admin cli or the java admin api. It handles the authentication header during redirections happen.

> Can I use Chinese ？

I would suggest using English if possible. If you are interested in talking to Chinese contributors, there is a slack channel #china in Pulsar's slack, where people chat in Chinese though.

>  pulsar-admin clusters list

Interesting. It looks like the second command talks to a broker whose didn't find the metadata. How do you setup you the clusters? Can you describe a bit more about your setup?

**Comment by Xlingxiao** [comment]
@sijie 
> using admin cli or the java admin api.
Yesterday I also made errors using Java cli，but today I deleted the topic and used the new topic. Now there is no problem with Java cli
>  Can you describe a bit more about your setup?
What configuration do you need to see ?
> and this problem 
```
[zx@slave107 pulsar-2.3.1]$ pulsar-admin namespaces list lx
lx/java
lx/java2
[zx@slave107 pulsar-2.3.1]$ pulsar-admin persistent list lx/java
HTTP 500 Internal Server Error

Reason: HTTP 500 Internal Server Error
[zx@slave107 pulsar-2.3.1]$ bin/pulsar-admin topics list lx/java
HTTP 500 Internal Server Error

Reason: HTTP 500 Internal Server Error
```
![image](https://user-images.githubusercontent.com/34467450/56948321-59daf680-6b62-11e9-80bd-75ff98acbe75.png)

**Comment by sijie** [comment]
Talked with @Xlingxiao offline. The issue that cluster doesn't show up was due to a misconfiguration in zookeeper. It was gone after fixing the zookeeper setup.

The Authentication error seems to still happen. I guess it is related to the redirection problem similar to   #3869 . will keep working on this. @merlimat if you have any quick idea, please comment to help.

**Comment by sijie** [comment]
@Xlingxiao any luck about this issue?

**Comment by Xlingxiao** [comment]
sorry,no
