### ISSUE TITLE
[pulsar function] refactor function runtime

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar#4176]
**Is your feature request related to a problem? Please describe.**

When writing the go function, I realized that the function runtime has some places that are not very reasonable, for example:

What does the runtime mean? 

- Is java python or golang? 
- or thread process or k8s?

I think the runtime itself wants to mean something like: thread, process and k8s and other different runtime environments.

but in function runtime code: 

```
Function.FunctionDetails.Runtime.JAVA

Function.FunctionDetails.Runtime.PYTHON

Function.FunctionDetails.Runtime.GO
```

We can see usages like the above, which can easily cause ambiguity.

Another problem is that when we add a new language function, the intrusion of the runtime is too large, and whether we can give a reasonable abstraction way makes it easier for contributors to support the function of the new language.

As @sijie  said in [pull:4174](https://github.com/apache/pulsar/pull/4174#discussion_r279606586):

>Nit: I think we are beginning having more and more branches in the pulsar runtime. I guess it might be the time to do a refactor to make the language runtime pluggable in Pulsar Function. So that we don't need to touch the runtime each time we introduce a new language. You don't need to do it right now. but It might be worth creating a task to track that.

@srkukarni @jerrypeng @merlimat about this, do you have any good suggestions or opinions?

**Comment by jerrypeng** [comment]
Yup I agree some refactoring can and should be done to make runtimes more modular and that the code between all of these runtimes is not sprinkled everywhere in the code.

I can definitely seen the confusion here with the overloaded term "runtime".  We have a interface call Runtime and we have an enum called Runtime but they refer to different things.  The former refers more to a Runtime Environment and the later refers to a Runtime language.  We can discuss how we can rename to eliminate this confusion.  Maybe we can just change the Runtime interface to be called something like RuntimeEnv

**Comment by jerrypeng** [comment]
We should also make the setting of the Runtime/RuntimeFactory to be actually pluggable in the WorkerConfig.  Currently its not.  Ideally in the work config we should see something like:

RuntimeFactory: "org.apache.pulsar.functions.runtime.ProcessRuntimeFactory"
RuntimeFactoryConfigs:
  ...

**Comment by srkukarni** [comment]
One simple fix to avoid the runtime overload confusion might be to just rename the RunTime enum to a Language enum. i believe that should be backwards compatible.

**Comment by jerrypeng** [comment]
This is done:

apache#5463
