### ISSUE TITLE
Delete Inactive Topic should also clean up the schema

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#4180]
Similar as #3941, we should also clean up schema when deleting inactive topic. Otherwise the schema information would be just left there :(

**Comment by hellozepp** [comment]
Hi~ @sijie 
I have reviewed CmdTopics.Java, is not the feature you mentioned the following code?
```
 @Parameters(commandDescription = "Delete a topic. \n"
            + "\t\tThe topic cannot be deleted if there's any active subscription or producers connected to it.")
...
  if (deleteSchema) {
                admin.schemas().deleteSchema(topic);
            }
```

**Comment by sijie** [comment]
@hellozepp 

Sorry for late response. the code snippet you pasted is the feature I mentioned in #3941 

However the feature here is about doing the same thing when pulsar broker deleteInactiveTopic. In #3941 , users delete topic explicitly using pulsar-admin. In this issue, it is broker itself deleting the topics when they are inactive. Hope this give you the idea about what this issue for.

**Comment by liketic** [comment]
hi @sijie , I opened #4262 , happy to hear your thoughts. :)
