### ISSUE TITLE
trigger a function through a HTTP API

### ISSUE THREAD

**Issue by pouledodue** [apache/pulsar#4201]
Capability to trigger a function through a HTTP API 
Without using `pulsar-admin`.
Goal is to get the output fast and be able to handle high number of calls.
Like AWS Lambda where you can serve website content directly from function output

**Comment by merlimat** [comment]
The CLI tool is always using the HTTP API. 
The endpoint is https://pulsar.apache.org/functions-rest-api/#operation/triggerFunction 

Setting up the content might be a bit involved though :/ since it requires a multi-part body a so on.

**Comment by pouledodue** [comment]
it works thanks

**Comment by pouledodue** [comment]
do you know if it can handle a lot of hits?

**Comment by srkukarni** [comment]
It creates a producer for each http request. Meant for debugging rather than a fast data path.

**Comment by pouledodue** [comment]
@srkukarni would it be possible to add scalability, the goal would be direct content serve client->api gateway->http_api->function

**Comment by srkukarni** [comment]
It should't be too hard. Please open an issue. 
We love contributions as well :) I could guide you with this.

**Comment by pouledodue** [comment]
I read the PRs regularly and not sure I have the Java skills to contribute at this time.
Maybe later
