### ISSUE TITLE
State as first-class citizen

### ISSUE THREAD

**Issue by ghost** [apache/pulsar#4202]
Goal is to have capability equivalent to DynamoDB so I can rely less on external databases
Implement more capabilities of RocksDB: Get, Put, Range, Multiget
Access all those capabilities by Rest API, Python, Java
State less tied to Function like asked in #2489

**Comment by tisonkun** [comment]
Closed as stale.

The development of #2489 seems stalled and this thread doesn't contain too much information. If one wants to revive the proposal, please open a brand new thread.
