### ISSUE TITLE
Download links for 2.3.1 rpm packages are broken

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#4206]
![image (2)](https://user-images.githubusercontent.com/1217863/57190693-f977fa80-6f4f-11e9-8b20-2fffd580bf50.png)
![image (1)](https://user-images.githubusercontent.com/1217863/57190694-fa109100-6f4f-11e9-92f5-dc7d4bca8ade.png)

**Comment by ambition119** [comment]
client and client-debuginfo link to https://www.apache.org/dyn/mirrors/mirrors.cgi?, but client-devel, asc, sha512 link to  https://archive.apache.org/dist/pulsar occur error.
