### ISSUE TITLE
HTTP lookup doesn't work through proxy

### ISSUE THREAD

**Issue by ivankelly** [apache/pulsar#4215]
**Describe the bug**
When configuring a client, connecting directly to brokers you can specify that it uses http for lookup by configuring the HTTP url as the service URL. This works fine.

However, if you are connecting to the service through a proxy, specifying the HTTP url doesn't work, as the client doesn't know if it should connect to the returned endpoint via a proxy node, or directly.

**To Reproduce**
1. Set up a cluster with a proxy.
2. Try to connect to the proxy and publish messages with the java, c++ or python clients.

**Expected behavior**
Should work.

**Comment by tisonkun** [comment]
Closed as stale.

Feel free to open a new issue if it's still relevant to the maintained versions.
