### ISSUE TITLE
Is there any plan to add rust client?

### ISSUE THREAD

**Issue by chrislearn** [apache/pulsar#4225]
Rust is a good language, Is there any plan to add rust client?

**Comment by merlimat** [comment]
There are people working on https://github.com/wyyerd/pulsar-rs

**Comment by aahmed-se** [comment]
you can also use the rust via websocket
https://github.com/quiye/pulsar-rust-websocket-client

**Comment by sijie** [comment]
Closed this issue since the question has been answered.
