### ISSUE TITLE
Close blocks if called twice in Go Client

### ISSUE THREAD

**Issue by bruth** [apache/pulsar#4231]
**Describe the bug**
Calling `Client.Close()` twice blocks due to the presumably since the underlying [`CloseAsync`](https://github.com/apache/pulsar/blob/master/pulsar-client-go/pulsar/c_producer.go#L287-L291) blocks.

**To Reproduce**
Initialize a client and call `Close` twice successively. The second call will block indefinitely.

**Expected behavior**
Subsequent calls to `Close` should be a no-op or at least an error statement the client is already closed.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - macOS when using the Go client
 - Linux (the apachepulsar/pulsar Docker image) for the Pulsar server

**Additional context**
n/a

**Comment by bruth** [comment]
This appears to be the case for producers as well (and I would presume consumers).

**Comment by williamhammond** [comment]
I'd like to take a shot at fixing this

**Comment by tisonkun** [comment]
Closed as stale.

The development of the (reimplemented pure) Go client has been permanently moved to https://github.com/apache/pulsar-client-go.
