### ISSUE TITLE
Function worker can't start when setting up a geo-replicated cluster

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#4233]
**Describe the bug**

When setting up two geo-replicated clusters with functions-worker enabled, one cluster will fail to start functions worker because the cluster is not in the cluster list of `public/functions`.

**To Reproduce**

1. Setup cluster A
2. Setup cluster B. B shares the same configuration store with A.

**Expected behavior**

Cluster should start function worker as expected.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
