### ISSUE TITLE
Make client logging configurable

### ISSUE THREAD

**Issue by grantwwu** [apache/pulsar#4234]
**Is your feature request related to a problem? Please describe.**
The Python and Go client libraries log - a lot.  It's annoying especially if you're trying to use a form of structured logging, or just debug something you know is unrelated to Pulsar.

**Describe the solution you'd like**
At bare minimum, there should be a way to just turn it off.

A more complete solution would allow configuring the logger in a way idiomatic to each language.  For example, integrating with Python `logging`.  I'm not 100% sure how.

Another option would be to allow redirecting the logs to a file instead of polluting stderr.

**Describe alternatives you've considered**
Not sure if there's a good alternative.

**Comment by merlimat** [comment]
@grantwwu In Go it's already possible to configure. Take a look at the `Logger` in `ClientOptions`:
https://godoc.org/github.com/apache/pulsar/pulsar-client-go/pulsar#ClientOptions 

We should do something similar for Python as well and probably move the logger to Py `logging` by default.

**Comment by merlimat** [comment]
C++ lib has a `setLogger()` method that we'd need to hook up in the Python bindings: https://pulsar.apache.org/api/cpp/classpulsar_1_1_client_configuration.html#aa0dc0968fea7621352aae5a82bda7222

**Comment by grantwwu** [comment]
Good to know for Go.  Definitely would love this in Python as well.

**Comment by chairmank** [comment]
The `logging` module in the Python standard library is implemented in Python. It is not a built-in implemented in C.

I think that we could implement a log4cxx appender that uses `boost::python::exec` to call methods on a Python standard library `Logger` instance, with arguments passed as `locals`.

**Comment by tiwansh** [comment]
The client logging in python still seems non-configurable even after providing the log4cxx config file. Is it possible to configure to stop logging to stdout ?

**Comment by rosejn** [comment]
It seems maybe this got held up due to the potential difficulty of sending log data from C++ up to python.  How about just providing options to silence logging, and/or set the log level in the meantime?
