### ISSUE TITLE
c++ client too many files opens

### ISSUE THREAD

**Issue by 18852996112** [apache/pulsar#4240]
**Describe the bug**
open too many files.

**To Reproduce**
1. create client&consumer, subscribe, close and destroy client.   
2. do `Step1` in a loop for many times
3. use `netstat` i find that the number of opened socket is increasing.
4. See error,  too many files open, when create client  

**Expected behavior**
nothing.

**Comment by merlimat** [comment]
@18852996112 A client instance should be reused in a process. 

> use netstat i find that the number of opened socket is increasing.

What's the state of this sockets? OS will keep the ports busy for some time after closing the sockets. Once the limit is reached, the process will fail to create new sockets.

**Comment by 18852996112** [comment]
All  states are ESTABLISHED.

**Comment by 18852996112** [comment]
> @18852996112 A client instance should be reused in a process.
> 
> > use netstat i find that the number of opened socket is increasing.
> 
> What's the state of this sockets? OS will keep the ports busy for some time after closing the sockets. Once the limit is reached, the process will fail to create new sockets.

 ESTABLISHED

**Comment by merlimat** [comment]
@18852996112 Can you share your test code to reproduce the issue?

**Comment by merlimat** [comment]
Error does not reproduce on MacOS with

```java
for (int i = 0; i < 100; i++) {
    PulsarClient client = PulsarClient.builder()
            .serviceUrl("pulsar://localhost:6650")
            .build();

    Consumer<byte[]> consumer = client.newConsumer()
           .topic("my-topic")
           .subscriptionName("test")
           .subscribe();

    client.close();
}
```

**Comment by 18852996112** [comment]
> Error does not reproduce on MacOS with
> 
> ```java
> for (int i = 0; i < 100; i++) {
>     PulsarClient client = PulsarClient.builder()
>             .serviceUrl("pulsar://localhost:6650")
>             .build();
> 
>     Consumer<byte[]> consumer = client.newConsumer()
>            .topic("my-topic")
>            .subscriptionName("test")
>            .subscribe();
> 
>     client.close();
> }
> ```

In my last testing, i create connection and destroy the connection further slowly. Then  there's no that problem.  I think the season is OS keep the connection for some time.
thanks.

**Comment by merlimat** [comment]
@18852996112 I actually mistakenly assumed this was with Java client. I haven checked with C++ client...
