### ISSUE TITLE
pulsar bookie establish a tcp link with a port lower than 20,000, which is easy to occupy the port

### ISSUE THREAD

**Issue by Lsxk** [apache/pulsar#4244]
#### Expected behavior
![image](https://user-images.githubusercontent.com/12078538/57438481-9f8c7300-7276-11e9-8229-1da7beebd97c.png)

Tell us what should happen

#### Actual behavior

Tell us what happens instead

#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**Pulsar version**: x.y

**Comment by Lsxk** [comment]
![image](https://user-images.githubusercontent.com/12078538/57438838-61dc1a00-7277-11e9-9734-bd94bab9485a.png)

**Comment by sijie** [comment]
@Lsxk Can you explain a bit more about the screenshots?

**Comment by sijie** [comment]
Closed this issue since there are no detailed information provided.
