### ISSUE TITLE
Scalable HTTP API for Function triggering 

### ISSUE THREAD

**Issue by ghost** [apache/pulsar#4249]
Goal is to serve content to end user using Functions.

```
http_user_agent -> my_api_gateway -> scalable_pulsar_http_api -> pulsar_function
```
like aws is doing with their combo apigateway+lambda where their ApiGateway can return content to user (json/html..) while also calling a Lambda function

The goal here is scalability to handle many user requests coming from the `my_api_gateway`

related to #4201

**Comment by pouledodue** [comment]
any news on this missing part?
[X] Pulsar <s>Kinesis + SQS</s>
[X] Bookkeeper <s>DynamoDB</s>
[ ] Pulsar API Gateway <s>AWS APi Gateway</s>

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
