### ISSUE TITLE
Not exist default tenants `public` and namespace `default`

### ISSUE THREAD

**Issue by zymap** [apache/pulsar#4260]
**Describe the bug**
When I start a broker there is not exist default tenants and namespace:

**To Reproduce**
1. Start a zookeeper
2. Start a broker `bin/pulsar broker`

**Expected behavior**
start a broker successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/24502569/57524219-c1125b00-7359-11e9-8e3f-cccd5230d315.png)

**Desktop (please complete the following information):**
 - OS: [macOS]

**Comment by rshermanTHG** [comment]
The public tenant and public/default namespace are only created automatically when you start a standalone broker

`bin/pulsar standalone`

**Comment by zymap** [comment]
ok, thank you

**Comment by mingfang** [comment]
What is the downside to automatically create public/default when not running standalone mode?
Many of the online tutorials/samples request the default namespace and not having it creates a bad first experience.
