### ISSUE TITLE
Pulsar Avro Schema Enum improvement request

### ISSUE THREAD

**Issue by moonboots300** [apache/pulsar#4271]
**Is your feature request related to a problem? Please describe.**
The pulsar API is not granular enough around Avro Schemas and Enums. There are currently 2 problems with the Pulsar Avro Schema resolution: 

1.  Not able to set required=True for Enum types in python for an enum. 
```
class Event(Enum):
    OPEN=0
    CLOSE=1

class Test:
     event = Event #### NO way to pass in 'required=True' for enum.
```

Desired Schema (with required enum):
```
{
    "type": "record",
    "name": "Test",
    "namespace": "com.test",
    "fields": [ {
	     "name": "event",
		"type": {
				"type": "enum",
				"name": "Event",
				"symbols": ["OPEN", "CLOSE"]
			}
             }
    ]
}
```
Actual Schema - generated by AvroSchema(Test)
```
{
    "type": "record",
    "name": "Test",
    "namespace": "com.test",
    "fields": [ {
            "name": "event",
            "type": **["null", {**
                    "type": "enum",
                    "name": "Event",
                    "symbols": ["OPEN", "CLOSE"]
                }
            ]
        }
    ]
}

```
required=True, was implemented for all Python types except for Enum in https://github.com/apache/pulsar/pull/3526

Was the functionality missed for Enums?

2. In java, Building a Schema with Enums and withAlwaysAllowNull(false) is too restrictive. Suppose I have an AvroSchema that is defined by a java Class with two Enums, one that is required and one that is not required. 
```
public class Payload{
     private Event event;
     private Direction direction;
.....
     public enum Event { OPEN, CLOSE }
     public enum Direction { UP, DOWN }
}
```

Create an AvroSchema<Payload> - Neither of the following will give the desired Schema 
```
AvroSchema<Payload> avroSchema = AvroSchema.of(SchemaDefinition.<Payload>builder().withPojo(Payload.class).**withAlwaysAllowNull(false)**.build());
//OR 
AvroSchema<Payload> avroSchema = AvroSchema.of(SchemaDefinition.<Payload>builder().withPojo(Payload.class).**withAlwaysAllowNull(true)**.build());
//OR 
AvroSchema<Payload> avroSchema = AvroSchema.of(SchemaDefinition.<Payload>builder().withPojo(Payload.class).build());
```
**Desired Schema:** (One Nullable - event, and One Required - direction enum symbols)
```
{
    "type": "record",
    "name": "Payload",
    "namespace": "com.test",
    "fields": [ {
	     "name": "event",
		"type": {
				"type": "enum",
				"name": "Event",
				"symbols": ["OPEN", "CLOSE"]
			}
             },
             {
	     "name": "direction",
		"type": ["null",{
				"type": "enum",
				"name": "Direction",
				"symbols": ["UP", "DOWN"]
			}]
             }
    ]
}
```

**Describe the solution you'd like**
Allow the schema to be built from a String definition of the Schema in Java and Python. OR implement some method to identify each field as required or not. Python already has this, except it does **not** exist for enums. The Java implementation is too restrictive, requiring all of the Class fields to be non-null or allowing all fields to be null. There is no in-between (for there to be one Enum as Required and another as Nullable).

**Describe alternatives you've considered**
Using avro library instead of the wrapped pulsar functionality since it works for these cases.

**Additional context**

**Comment by merlimat** [comment]
> Allow the schema to be built from a String definition of the Schema in Java and Python

Yes, this is something we definitely need to do

> OR implement some method to identify each field as required or not. Python already has this, except it does not exist for enums.

How do you suggest the declaration for enums with "annotations" should look like in Python?

**Comment by moonboots300** [comment]
so for #2. (java) I found that setting .withAlwaysAllowNull(false) and marking fields as @Nullable (org.apache.avro.reflect.Nullable) as a workaround works. Still not perfect, but slightly better than originally mentioned. 

> How do you suggest the declaration for enums with "annotations" should look like in Python?

I suggest that there be a similar method to mark an Enum as required. It should look like this when I define a class that extends Record (to create a schema). I am not as familiar with Python Enums, so I may be missing something. I suppose there is some rule that prevents passing "required=True" to an enum?

class MyObject(Record):
      a = String()
      b = Integer(required=True)
      c = **MyEnum(required=True)**

**Comment by merlimat** [comment]
the problem here is that `MyEnum` is really of Python type `Enum`. That enum might be defined elsewhere in the application (or might be coming from a library), therefore we cannot count on passing `required=True` there. 

We would have to add a `c = pulsar.schema.Enum(MyEnum, required=True)`

**Comment by moonboots300** [comment]
That would solve the issue I am currently facing. Would really appreciate this in an upcoming release!

**Comment by moonboots300** [comment]
One last thing. The issue with java Enums still exists as I stated in the original post. I revisited and realized it was not working as I thought. See below: 

In java, Building a Schema with Enums and withAlwaysAllowNull(false) is too restrictive. Suppose I have an AvroSchema that is defined by a java Class with two Enums, one that is required and one that is not required. I can only choose: withAlwaysAllowNull(true) -> Both are marked null **or** withAlwaysAllowNull(false) -> Both are marked as required

```
public class Payload{
     private Event event;
     private Direction direction;
.....
     public enum Event { OPEN, CLOSE }
     public enum Direction { UP, DOWN }
}

```
Create an AvroSchema - Neither of the following will give the desired Schema

```
AvroSchema<Payload> avroSchema = AvroSchema.of(SchemaDefinition.<Payload>builder().withPojo(Payload.class).**withAlwaysAllowNull(false)**.build());
//OR 
AvroSchema<Payload> avroSchema = AvroSchema.of(SchemaDefinition.<Payload>builder().withPojo(Payload.class).**withAlwaysAllowNull(true)**.build());
//OR 
AvroSchema<Payload> avroSchema = AvroSchema.of(SchemaDefinition.<Payload>builder().withPojo(Payload.class).build());

```
Desired Schema: (One Nullable - event, and One Required - direction enum symbols)
```
{
    "type": "record",
    "name": "Payload",
    "namespace": "com.test",
    "fields": [ {
	     "name": "event",
		"type": {
				"type": "enum",
				"name": "Event",
				"symbols": ["OPEN", "CLOSE"]
			}
             },
             {
	     "name": "direction",
		"type": ["null",{
				"type": "enum",
				"name": "Direction",
				"symbols": ["UP", "DOWN"]
			}]
             }
    ]
}
```

**Comment by codelipenghui** [comment]
@moonboots300 I think you can add annotation `org.apache.avro.reflect.Nullable` for enum which you want it allow null. withAlwaysAllowNull(true) equivalent to `org.apache.avro.reflect.Nullable` for every field.

**Comment by moonboots300** [comment]
@codelipenghui, @merlimat  - That is another problem that I would like to highlight. Suppose I have a schema that we are currently using that has the following Avro Enum field:
```
{
    "name": "exampleEnum",
     "type": ["null", {
		"type": "enum",
		"name": "ExampleEnum",
		"symbols": ["YES", "NO"]
		}
	]
}
```
If I do AvroSchema.of( <Classname of Pojo> ). I get the following Enum field in my definition (which is not backwards compatible - with the **,"default": Null** added at the end): 

```
{
    "name": "exampleEnum",
     "type": ["null", {
		"type": "enum",
		"name": "ExampleEnum",
		"symbols": ["YES", "NO"]
		}
	],
	"default": null
}
```
The use case I have for this one is that I am trying to implement a current production Use Case with Pulsar Functions - 1. I use AvroSchema.of() to generate the schema and 2. I use schema.encode(OBJECT) to Serialize before publishing to a pulsar topic.

If I use the avro-tools jar, following the directions here along with the Avro java library and I can Serialize / Deserialize messages With the Schema definition text file and my POJO that was generated from avro-tools jar. Using this workaround along with Pulsar Functions works but it is not utilizing the schema.encode() and AvroSchema.of() which is how we should be using Avro Schema's with Pulsar.

**Comment by codelipenghui** [comment]
@moonboots300 Sorry, I didn't fully understand your question. I wrote a test, hope can help you.
```java
package org.apache.pulsar;

import org.apache.avro.reflect.Nullable;
import org.apache.pulsar.broker.service.schema.AvroSchemaCompatibilityCheck;
import org.apache.pulsar.broker.service.schema.SchemaCompatibilityCheck;
import org.apache.pulsar.broker.service.schema.SchemaCompatibilityStrategy;
import org.apache.pulsar.client.api.schema.SchemaDefinition;
import org.apache.pulsar.client.impl.schema.AvroSchema;
import org.apache.pulsar.common.schema.SchemaData;
import org.apache.pulsar.common.schema.SchemaType;
import org.testng.Assert;
import org.testng.annotations.Test;

import java.util.Objects;

public class AvroTest {

    private SchemaCompatibilityCheck checker = new AvroSchemaCompatibilityCheck();

    @Test
    public void test() {

        // generic schema via pojo
        AvroSchema<Example> schema1 = AvroSchema.of(SchemaDefinition.<Example>builder().withPojo(Example.class)
                .withAlwaysAllowNull(false).build());

        // generic schema one field nullable
        AvroSchema<Example> schema2 = AvroSchema.of(SchemaDefinition.<Example>builder().withJsonDef("{\"type\":\"record\",\"name\":\"Example\",\"namespace\":\"org.apache.pulsar.AvroTest$\",\"fields\":[{\"name\":\"enumA\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"ExampleEnumA\",\"symbols\":[\"YES\",\"NO\"]}],\"default\":null},{\"name\":\"enumB\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"ExampleEnumB\",\"symbols\":[\"UP\",\"DOWN\"]}]}]}").withAlwaysAllowNull(false).build());

        Example example = new Example();

        byte[] bytes = schema2.encode(example);
        Example decoded = schema2.decode(bytes);
        Assert.assertEquals(example, decoded);

        example.setEnumA(ExampleEnumA.NO);
        bytes = schema1.encode(example);
        decoded = schema1.decode(bytes);
        Assert.assertEquals(example, decoded);

        Assert.assertTrue(checker.isCompatible(
                getSchemaData(new String(schema1.getSchemaInfo().getSchema())),
                getSchemaData(new String(schema2.getSchemaInfo().getSchema())),
                SchemaCompatibilityStrategy.BACKWARD)
        );
    }

    static class Example {

        private ExampleEnumA enumA;

        @Nullable
        private ExampleEnumB enumB;

        public ExampleEnumA getEnumA() {
            return enumA;
        }

        public void setEnumA(ExampleEnumA enumA) {
            this.enumA = enumA;
        }

        public ExampleEnumB getEnumB() {
            return enumB;
        }

        public void setEnumB(ExampleEnumB enumB) {
            this.enumB = enumB;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Example example = (Example) o;
            return enumA == example.enumA &&
                    enumB == example.enumB;
        }

        @Override
        public int hashCode() {
            return Objects.hash(enumA, enumB);
        }
    }

    enum  ExampleEnumA {
        YES,
        NO
    }

    enum  ExampleEnumB {
        UP,
        DOWN
    }

    private static SchemaData getSchemaData(String schemaJson) {
        return SchemaData.builder().data(schemaJson.getBytes()).type(SchemaType.AVRO).build();
    }
}

```

**Comment by moonboots300** [comment]
@codelipenghui  Thanks! That will work and answers my question around java.

**Comment by sijie** [comment]
@moonboots300 

To summarize the problems here, 

a) in Java, you can use `withJsonDef` in SchemaDefinitionBuilder to enforce the avro schema. Hence I think your question in Java is answered, correct?

b) in Python, does python schema provides similar `withJsonDef` work for you as well?

**Comment by moonboots300** [comment]
@sijie 

a. Yes, originally I was not aware, @codelipenghui  pointed this out for me
b. No Python does not have a similar withJsonDef method. I think there is room for improvement around Avro in python.

**Comment by bry00** [comment]
> the problem here is that `MyEnum` is really of Python type `Enum`. That enum might be defined elsewhere in the application (or might be coming from a library), therefore we cannot count on passing `required=True` there.
> 
> We would have to add a `c = pulsar.schema.Enum(MyEnum, required=True)`

Is there any chance to add Enum field supporting properly `required` and `default` parameters?
