### ISSUE TITLE
some ZK path for Pulsar metadata is not configurable

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#4279]
some ZK path for Pulsar metadata is hard coded and not configurable, It would be great to make them configurable, so user could leverage their existing zk cluster, and put all pulsar related data in user configured place.

**Comment by sijie** [comment]
@jiazhai you can use zookeeper chroot to configure the root path for pulsar metadata. 

e.g. "zk:2181/newroot"

So I don't think we need a code change for this.
