### ISSUE TITLE
Pulsar Functions as a library

### ISSUE THREAD

**Issue by cbornet** [apache/pulsar#4285]
**Is your feature request related to a problem? Please describe.**
Currently, Pulsar Functions need to be packaged and launched by pulsar-admin or loaded into a broker.
This has the disadvantage of being hard to debug and slow to REPL. And you can't use your favorite framework to integrate into your existing infrastructure (eg. Spring-Boot, Spring-Cloud, ...)

**Describe the solution you'd like**
Kafka has a different approach where Kafka-Streams is just a library that you add on top of any Java app and doesn't impose a "runtime context". It would be great to have the same for Pulsar.

cc @srkukarni

**Comment by sijie** [comment]
@cbornet I think we have already provided a runner library to run the functions. This should have achieved the same purpose. I will create an issue #6044 to follow up on the documentation for running functions in library.

**Comment by sijie** [comment]
@cbornet does this meet your requirements?

**Comment by cbornet** [comment]
Yes LocalRunner seems to fill that gap.
