### ISSUE TITLE
Is this code reasonable in GenericJsonSchema.java ?

### ISSUE THREAD

**Issue by ppgoml** [apache/pulsar#4294]
/pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/GenericJsonSchema.java

 public byte[] encode(GenericRecord message) {
        checkArgument(message instanceof GenericAvroRecord);
        GenericJsonRecord gjr = (GenericJsonRecord) message;
        try {
            return objectMapper.writeValueAsBytes(gjr.getJsonNode().toString());
        } catch (IOException ioe) {
            throw new SchemaSerializationException(ioe);
        }
    }

I don't understand why there is a GenericAvroRecord check here in Json schema.

**Comment by sijie** [comment]
@ppgoml I think this was an issue that was fixed in master.
