### ISSUE TITLE
Go client blocks forever if tenant/namespace missing.

### ISSUE THREAD

**Issue by Jim-Lambert-Bose** [apache/pulsar#4302]
**Describe the bug**
If a tentant/namespace is missing, and you create a producer, the Go client hangs forever

**To Reproduce**
```
client, err := pulsar.NewClient(pulsar.ClientOptions{
			URL:                        "pulsar://localhost:6650",
			TLSAllowInsecureConnection: true,
			IOThreads:                  10,
			OperationTimeoutSeconds:    5,
		})
if err != nil {
	return err
}
// Get the topic configuration
producer, err := client.CreateProducer(pulsar.ProducerOptions{
	Topic:"persistent://identity/users/new-bose-person-id",
})
```
```
### hangs here forever.
2019/05/17 17:39:09.537 c_client.go:68: [info] INFO  | ConnectionPool:72 | Created connection for pulsar://localhost:6650
```
**Expected behavior**
I think this should timeout after 5 seconds.

**Desktop (please complete the following information):**
macOS Mojave v10.14.4

**Additional context**
pulsar v2.3.1 go client and libpulsar

**Comment by Jim-Lambert-Bose** [comment]
More information...  It appears there's some sort of "environment issue".  I've stripped my puslar code down to the example:
`
package main

import (
	"context"
	"fmt"

	log "github.com/apache/pulsar/pulsar-client-go/logutil"
	"github.com/apache/pulsar/pulsar-client-go/pulsar"
)

func Foo() {
	fmt.Println("starting Foo...")
	client, err := pulsar.NewClient(pulsar.ClientOptions{
		URL:       "pulsar://localhost:6650",
		IOThreads: 5,
	})

	if err != nil {
		log.Fatal(err)
	}

	defer client.Close()

	fmt.Println("trying...")

	producer, err := client.CreateProducer(pulsar.ProducerOptions{
		Topic: "my-topic",
	})
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("created...")
	defer producer.Close()

	ctx := context.Background()

	for i := 0; i < 10; i++ {
		if err := producer.Send(ctx, pulsar.ProducerMessage{
			Payload: []byte(fmt.Sprintf("hello-%d", i)),
		}); err != nil {
			log.Fatal(err)
		}
	}
`

**Comment by Jim-Lambert-Bose** [comment]
This runs when it's in a stand-alone executable with the following broker logs
```
11:20:50.950 [pulsar-io-49-8] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from /172.17.0.1:46852
11:20:50.970 [pulsar-io-49-1] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from /172.17.0.1:46854
11:20:50.973 [pulsar-io-49-1] INFO  org.apache.pulsar.broker.service.ServerCnx - [/172.17.0.1:46854][persistent://public/default/my-topic] Creating producer. producerId=0
11:20:50.975 [ForkJoinPool.commonPool-worker-2] INFO  org.apache.pulsar.broker.service.ServerCnx - [/172.17.0.1:46854] Created new producer: Producer{topic=PersistentTopic{topic=persistent://public/default/my-topic}, client=/172.17.0.1:46854, producerName=standalone-5-4, producerId=0}
11:20:51.133 [pulsar-io-49-1] INFO  org.apache.pulsar.broker.service.ServerCnx - [PersistentTopic{topic=persistent://public/default/my-topic}][standalone-5-4] Closing producer on cnx /172.17.0.1:46854
11:20:51.134 [pulsar-io-49-1] INFO  org.apache.pulsar.broker.service.ServerCnx - [PersistentTopic{topic=persistent://public/default/my-topic}][standalone-5-4] Closed producer on cnx /172.17.0.1:46854
11:20:51.138 [pulsar-io-49-8] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /172.17.0.1:46852
11:20:51.139 [pulsar-io-49-1] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /172.17.0.1:46854
11:20:53.610 [SessionTracker] INFO  org.apache.zookeeper.server.ZooKeeperServer - Expiring session 0x100039f8a97000b, timeout of 30000ms exceeded
11:20:53.611 [ProcessThread(sid:0 cport:2181):] INFO  org.apache.zookeeper.server.PrepRequestProcessor - Processed session termination for sessionid: 0x100039f8a97000b
```
But when I pull it into my larger project it just hands with the following broker logs:
```
11:22:54.293 [pulsar-io-49-3] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from /172.17.0.1:47080
11:23:07.940 [pulsar-web-55-3] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [19/May/2019:11:23:07 +0000] "GET /admin/v2/persistent/public/functions/coordinate/stats HTTP/1.1" 200 776 "-" "Pulsar-Java-v2.3.1" 2
11:23:24.293 [pulsar-io-49-3] WARN  org.apache.pulsar.common.api.PulsarHandler - [[id: 0x08270021, L:/172.17.0.2:6650 - R:/172.17.0.1:47080]] Pulsar Handshake was not completed within timeout, closing connection
11:23:24.294 [pulsar-io-49-3] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /172.17.0.1:47080
```
Both of working test and the failed test projects have the same go module graphs for puslar:
```
$ go mod graph | grep pulsar | sort 
github.com/apache/pulsar/pulsar-client-go@v0.0.0-20190507044647-1f4a836a4648
github.com/apache/pulsar/pulsar-client-go@v0.0.0-20190507044647-1f4a836a4648 github.com/BurntSushi/toml@v0.3.1
github.com/apache/pulsar/pulsar-client-go@v0.0.0-20190507044647-1f4a836a4648 github.com/sirupsen/logrus@v1.3.0
github.com/apache/pulsar/pulsar-client-go@v0.0.0-20190507044647-1f4a836a4648 github.com/stretchr/testify@v1.3.0
github.com/apache/pulsar/pulsar-client-go@v0.0.0-20190507044647-1f4a836a4648 gopkg.in/natefinch/lumberjack.v2@v2.0.0
github.com/apache/pulsar/pulsar-client-go@v0.0.0-20190507044647-1f4a836a4648 gopkg.in/yaml.v2@v2.2.2
```

**Comment by Jim-Lambert-Bose** [comment]
Ah Ha!!!! I figured it out.  I was creating a producer in an init() function and apparently that just hangs forever.

**Comment by Jim-Lambert-Bose** [comment]
I think, this issue has to do with CreateProducer() depending on multiple goroutines executing so it can write/read to a channel:
https://github.com/apache/pulsar/blob/6485ccf75d96f282c2c61e1dd87b85e42de64102/pulsar-client-go/pulsar/c_client.go#L207

But all Go init() functions execute in a single goroutine: https://golang.org/ref/mem#tmp_4

**Comment by sijie** [comment]
@wolfstudy can you help with the question here?

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Go client has been permanently moved to https://github.com/apache/pulsar-client-go. If it's still relevant, please open an issue there.
