### ISSUE TITLE
Number of placeholder and arguments mismatch in log message

### ISSUE THREAD

**Issue by liketic** [apache/pulsar#4304]
**Describe the bug**
We have some log like:
```
log.debug("[{}] Redirecting the rest call to {}: cluster={}", redirect, peerClusterData);
```
The number of ```{}``` is different to arguments count.  And for exception logging:
```
log.warn("Failed to offload: {}", e.getCause());
```
The last argument type is ```Throwable``` , here is last argument will not be treated as a format argument even there is a placeholder.

**Comment by sijie** [comment]
This was fixed by #4436
