### ISSUE TITLE
OperationsTimeout in pulsar go client pulsar.ClientOptions is a time.Duration but it's treated as Seconds

### ISSUE THREAD

**Issue by Jim-Lambert-Bose** [apache/pulsar#4307]
**Describe the bug**
OperationTimeoutSeconds is defined as type time.Duration (https://golang.org/pkg/time/#Duration), which leads the developer to believe they should set it to a time.Duration which for 5s would be 5000000000, since time.Duration is in nanoseconds.  Unfortunately, it's treated an integer representing seconds and it expects 5s to be represented as 5.

**Expected behavior**
If you're using time.Duration, then it should expect and deal with any valid time.Duration which is in nanoseconds not seconds.  If the pulsar only supports a timeout in seconds, then the client should define OperationTimeoutSeconds as an int

Thanks.

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Go client has been permanently moved to https://github.com/apache/pulsar-client-go. If it's still relevant, please open an issue there.
