### ISSUE TITLE
Go client: consumer.Unsubscribe() places topic in unusable state.

### ISSUE THREAD

**Issue by Jim-Lambert-Bose** [apache/pulsar#4324]
**Describe the bug**
My unit tests use a static subscription name and topic name.  My test does a: create, publish, consume messages and then unsubscribe at the end.  This works the first time with no problem, but subsequent runs fail and the subscription is in an odd state.   I am able to clear the issue be running: `pulsar-client consume --subscription-name my-sub  --num-messages 0 my-topic` 
Then the next iteration of my test succeeds... and we repeat the process all over again.

If you don't Unsubscribe() then the test always succeeds.
If you create a new subscription name every time, the test always succeed. 

**To Reproduce**

I created a repo with my Go tests: https://github.com/Jim-Lambert-Bose/go-test-pulsar-consumer
To recreate:
1. clone repo
2. run `go test -v` multiple times.

**Expected behavior**

I believe that you should be able to subscribe/unsubscribe as many times as you wish from the same static subscription name.  As long as you create a new subscriber, it should just work.

**Desktop (please complete the following information):**
 - OS: macOS Mojave v10.14.4

**Comment by sijie** [comment]
It seems like a question than a bug. @wolfstudy can you help check the issue here?

**Comment by wolfstudy** [comment]
You can comment out the operation of [seek()](https://github.com/Jim-Lambert-Bose/go-test-pulsar-consumer/blob/master/consumer_test.go#L83) and continue to execute it.

```
	err = consumer.Seek(pulsar.EarliestMessage)
	assert.Nil(t, err)
```

**Comment by sijie** [comment]
It seems that the question has been answered. Closed the issue now. If there are any other questions, please create a new issue.
