### ISSUE TITLE
support create one partition partitioned-topic by pulsar-admin  create-partitioned-topic command 

### ISSUE THREAD

**Issue by yangl** [apache/pulsar#4333]
**Is your feature request related to a problem? Please describe**
```sh
./bin/pulsar-admin topics  create-partitioned-topic  persistent://my-tenant/my-namespace/my-topic-test -p 20
```
above command parameter  **-p** the number of partitions should be more than 1

**Describe the solution you'd like**
use "./bin/pulsar-admin topics  create-partitioned-topic"  command  create **1 partition** partitioned-topic instead the none partitioned topic , because the none partitioned topic can't become partitioned topic.

**Comment by jiazhai** [comment]
#4764  fix this issue.
