### ISSUE TITLE
Duplicate metrics Prometheus

### ISSUE THREAD

**Issue by rcastagnet** [apache/pulsar#4337]
**Describe the bug**
The default metrics stay present even though there is an other metrics with more information.
Prometheus only processes this default metric.

**To Reproduce**
* Produce and consumer on your cluster
* Do a curl on metrics url : 
```
curl -s server01:8080/metrics/ | grep -e pulsar_consumers_count
```
* The result :
```
pulsar_consumers_count{cluster="pulsar_bdx"} 0 1558518241858
pulsar_consumers_count{cluster="pulsar_bdx",namespace="ns/global",topic="persistent://ns/global/queue"} 1.0 1558518241859
```
* Next, in prometheus you find only :
```
pulsar_consumers_count{cluster="pulsar_bdx",instance="server01:8080",job="Pulsar-broker-exporter"} 0
```

**Expected behavior**

* In Prometheus, you should find :
```
pulsar_consumers_count{cluster="pulsar_bdx",instance="server01:8080",job="Pulsar-broker-exporter",namespace="ns/global",topic="persistent://ns/global/queue1"} 1
```

**Additional context**

In my test, I solved this problem by commenting on the next line of the file "pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java" :
```
// printDefaultBrokerStats(stream, cluster);
```
An other solution should be the next line :
```
if (pulsar.getBrokerService().getMultiLayerTopicMap().isEmpty()) {
    printDefaultBrokerStats(stream, cluster);
}
```

Why do these metrics remain constantly instead of being overrided by new values?

**Comment by sijie** [comment]
@rcastagnet which version are you using? there were bunch of prometheus related changes merged in master.

**Comment by rcastagnet** [comment]
@sijie I installed prom/prometheus:v2.4.0 on AKS.
I'll try with v2.10.0.

**Comment by rcastagnet** [comment]
v2.10.0 prometheus version fix this problem, thank you
