### ISSUE TITLE
[Doc] Fix output after #4318 is merged

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#4344]
I'll handle this.

https://github.com/apache/pulsar/pull/4318

https://github.com/apache/pulsar/pull/4338

**Comment by sijie** [comment]
@Anonymitaet - #4338 is merged. fyi

**Comment by Anonymitaet** [comment]
@sijie Thanks.

**Comment by Anonymitaet** [comment]
I've created a PR (https://github.com/apache/pulsar/pull/4531) to fix this.
