### ISSUE TITLE
Proxy doesn't start on machines with <= 2 CPUs with default proxy.conf

### ISSUE THREAD

**Issue by davidtinker** [apache/pulsar#4359]
**Describe the bug**
The proxy fails to start with 'Uncaught exception in thread main: Failed to start HTTP server on ports [8082]' with default proxy.conf (httpNumThreads=) on machines with <= 2 CPUs.

**To Reproduce**
Set 'httpNumThreads=' (default) and start the proxy on a machine with <= 2 CPUs.

**Expected behavior**
The proxy should start with the default httpNumThreads setting in proxy.conf.

**Additional context**
Work around is simple: Set httpNumThreads=8. But this will catch people out testing Pulsar on small cloud servers.

**Comment by sijie** [comment]
@davidtinker #4375 for the fix
