### ISSUE TITLE
Authentication provider getAuthData called before initialization

### ISSUE THREAD

**Issue by sleungtoast** [apache/pulsar#4365]
**Describe the bug**
When I wrote a custom authentication provider, I expected `.getAuthData()` to not be called before `.start()` was called. When I turned on TLS, it hit a codepath where that happened.

**To Reproduce**
1. Add an Authentication provider that throws an exception if `start()` has not been called.
2. Use a TLS broker url
3. Create a consumer
4. On consumer `build()`, the Authentication provider will throw the exception.

**Expected behavior**
Do not call `Authentication.getAuthData()` before `Authentication.start()` so the consumer starts up successfully.

**Additional context**
In a `PulsarClientImpl` constructor, a new `ConnectionPool` is created, then a new `PulsarChannelInitializer` is created, which has the following code that doesn't use my auth data anyway.
```
if (conf.isUseTls()) {
    // Set client certificate if available
    AuthenticationDataProvider authData = conf.getAuthentication().getAuthData();
    if (authData.hasDataForTls()) {
        this.sslCtx = SecurityUtility.createNettySslContextForClient(conf.isTlsAllowInsecureConnection(),
                conf.getTlsTrustCertsFilePath(), (X509Certificate[]) authData.getTlsCertificates(),
                authData.getTlsPrivateKey());
    } else {
        this.sslCtx = SecurityUtility.createNettySslContextForClient(conf.isTlsAllowInsecureConnection(),
                conf.getTlsTrustCertsFilePath());
    }
} else {
    this.sslCtx = null;
}
```

**Comment by merlimat** [comment]
@sleungtoast Can you past the stack trace for the initialization sequence?

**Comment by sleungtoast** [comment]
Sure thing
```
Hit NPE in our CustomPulsarAuthentication.getAuthData()
! at org.apache.pulsar.client.impl.PulsarChannelInitializer.<init>(PulsarChannelInitializer.java:48)
! at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:80)
! at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:62)
! at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:105)
! at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:101)
! at org.apache.pulsar.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:61)
```

**Comment by jiazhai** [comment]
seems the code is added in PR #3550, indeed called getAuthData before start
<img width="733" alt="WeChat23843512bff02c5c74b20d4a40daedf1" src="https://user-images.githubusercontent.com/6348208/58364317-59294c00-7ee5-11e9-8bae-54815eb6b7ca.png">
