### ISSUE TITLE
Implement Flume Source with Event driven source instead 

### ISSUE THREAD

**Issue by liketic** [apache/pulsar#4370]
Currently, we implemented a Flume source which is also a Pulsar connector, the base class ```SourceOfFlume``` extends Flume's ```AbstractPollableSource```, which will be called in a poll interval by an external driver. In this way, the results consumed from Pulsar will be stored in a queue as the consuming logic maybe independent absolutely. 

In the other hand, Flume also support Event Driven source mode. Which will not be polled by other driver. The benefits for us, is we don't need the buffer queue any more. And for any records we got from Pulsar, we can push it to Flume channel immediately. 

See https://flume.apache.org/releases/content/1.9.0/apidocs/org/apache/flume/EventDrivenSource.html for more details. 

Happy to know yours thoughts.

**Comment by sijie** [comment]
@tuteng can you chime in with your thoughts?

**Comment by tuteng** [comment]
Using event-driven is a better way.
However, in the current environment, sink of pulsar is a wrapper for the consumer. In the interface sink, the write method does not return a value and needs a place to temporarily store the received message. Therefore, a buffer queue-like component is needed here.
I think it is simpler to use consumer components directly, similar to the following code:

```
private Event extractEvent() {
  ...
  while (!doneReading) {
    Message msg = consumer.receive();
  }
  e = EventBuilder.withBody(msg.toByteArray(), headers);
  return e;
}

  @Override
  public void messageReceived(ChannelHandlerContext ctx, MessageEvent mEvent) {
    Event e = extractEvent();
    getChannelProcessor().processEvent(e);
    counterGroup.incrementAndGet("events.success");
}
```

**Comment by liketic** [comment]
@tuteng I'm not sure if that's possible, I guess there are some differences between a pulsar sink and Flume source. Maybe need future work to figure what we can do.
