### ISSUE TITLE
Why pulsar java client doesn't support batch message consuming?

### ISSUE THREAD

**Issue by kevinclcn** [apache/pulsar#4405]
I am a Kafka user and attracted here by some Pulsar impressive features. However, I find Pulsar lacks one feature that Kafka has - the batching message consuming support.

In Kafka, we can fetch a list of message records in each poll invoking, while in Pulsar, we can [only get one message](https://github.com/apache/pulsar/blob/e3ece349d060b7ce0fd40e37e3a6d197036274c9/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java#L110). I do need the batch consuming feature in some cases, are there any concerns that Pulsar does not have this feature?

**Comment by merlimat** [comment]
If the concern is around efficiency, internally, messages are transported in batches. With that, there’s not a real difference between getting a list of messages or getting them one by one

**Comment by kevinclcn** [comment]
Yep, I agree the efficiency is not much different. But what I need to do is to get a batch list of messages and do a batch thing with them, such as batch insert, etc. In the current consumer API, I have to buffer the messages into memory myself, which is not convenient.

**Comment by sijie** [comment]
@codelipenghui is working on adding the feature in #4621

**Comment by sijie** [comment]
This has been supported in #4621
