### ISSUE TITLE
Consumer subscribe memory leak when server not reachable

### ISSUE THREAD

**Issue by sleungtoast** [apache/pulsar#4413]
**Describe the bug**
If you continually create new Consumers that fail to subscribe due to an unresponsive host, a memory leak in some resource inside ClientCnx happens. I'd assume something similar can happen for other clients. Let me know if I should upload a heap dump somewhere. Possibly related to https://github.com/apache/pulsar/pull/3422 

**To Reproduce**
Run a loop like
```
    @Test
    fun consumerStartupFailMemoryLeak() {
        val client = PulsarClient.builder()
            .serviceUrl("pulsar://localhost:9999")
            .build()

        var i = 0
        while (true) {
            try {
                client.newConsumer()
                    .topic("topic")
                    .subscriptionName("subscription")
                    .subscribe()
            } catch (ignored: Exception) {}

            if (i % 1000 == 0) {
                val r = Runtime.getRuntime()
                val heapused = r.totalMemory() - r.freeMemory()
                LOG.info("Heap used: ${heapused/1024/1024}MB")
            }
            i++
        }
    }
```
Within minutes the heap used will balloon
```
15:26:32.609 [main] INFO   Heap used: 107MB
15:26:40.164 [main] INFO   Heap used: 194MB
15:26:48.272 [main] INFO   Heap used: 378MB
15:26:56.301 [main] INFO   Heap used: 573MB
15:27:04.759 [main] INFO   Heap used: 726MB
15:27:12.703 [main] INFO   Heap used: 917MB
15:27:20.848 [main] INFO   Heap used: 1065MB
```

**Expected behavior**
Consumer subscribe should be able to retry basically forever without hitting memory problems.

**Comment by sleungtoast** [comment]
I noticed this problem doesn't exist if you point to something like "pulsar://unreachable:9999" if that helps narrow the scope.

**Comment by merlimat** [comment]
@sleungtoast Nice catch! The leak is there because the `ClientCnx` object is created but since the connection fails to get established, it will never call the `connectionInactive()` handler. 

The leaked memory though is smaller than the above reported (eg: I did put a `System.gc()` in between because `Runtime.freeMemory()` is not accounting for non-referenced objects).
