### ISSUE TITLE
Bookie can't start in the background by pulsar-daemon when passing extra opts

### ISSUE THREAD

**Issue by murong00** [apache/pulsar#4422]
When trying to pass extra settings via `bkenv.sh` (e.g. set `BOOKIE_EXTRA_OPTS` when enable kerberos) and starting in the background via `bin/pulsar-daemon start bookie`, it failed to get the corresponding settings since `bin/pulsar-daemon` i.e. `bin/pulsar` use `pulsar_env.sh` by default. 

One way is to start the bookie in the foreground via `bin/bookkeeper bookie`, or as a workaround, you can just source the `bkenv.sh` and pass the `BOOKIE_EXTRA_OPTS` to `OPTS` in the shell `bin/pulsar` when command is `bookie`.

It would be better to support `pulsar-daemon` which seems more popular to start bookie in the background when passing extra opt.

**Comment by sijie** [comment]
@murong00 I saw you fixed this by updating the documentation. do you think we still need to make the improvement here?

**Comment by murong00** [comment]
In practice most users prefer to start bookie in the background especially in production environments, so it would be better to support this. However, as discussed with @jiazhai , the original intention of `bin/pulsar` is to use `pulsar_env.sh`, therefore I'm not sure it's appropriate to pass the `BOOKIE_EXTRA_OPTS` in `bin/pulsar`. If this way can be accepted I can make a PR trying to address this.

**Comment by sijie** [comment]
>  I'm not sure it's appropriate to pass the BOOKIE_EXTRA_OPTS in bin/pulsar

I think it would be great to have ability  to configure BOOKIE_EXTRA_OPTS in pulsar_env.sh. So that all pulsar scripts can work seamless with bookkeeper.

**Comment by murong00** [comment]
@sijie Nice suggestion. I made a pull request trying to address this, please take a look.
