### ISSUE TITLE
Like PulsarClient.buiilder, ClientConfigurationData.java should enable tls if  pulsar+ssl 

### ISSUE THREAD

**Issue by shiv4289** [apache/pulsar#4441]
**Describe the bug**
There are two ways of instantiating a java client and both should behave in similar ways. As of now, PulsarClient.builder assumes tls enabled if the pulsar+ssl or https is used in the service url. In fact, the builder marks enableTls() as deprecated.

ClientConfigurationData.java lags a bit that way. It does not enable tls if pulsar+ssl or https is used in service url.

**To Reproduce**
1. Initialise PULSAR_BROKER_URL as pulsar+ssl:// *
2. Instantiate the pulsar client with client config POJO.

>             ClientConfigurationData clientConfig = new ClientConfigurationData();
>             clientConfig.setServiceUrl(PULSAR_BROKER_URL);
>             clientConfig.setTlsTrustCertsFilePath(PULSAR_CA_CERT_PATH);
> 
>             client = new PulsarClientImpl(clientConfig);

**Expected behavior**
Client should use tls if service url is pulsar+ssl://* or https://*

**Comment by sijie** [comment]
@shiv4289 are you interested in sending the pull request to pulsar?

**Comment by shiv4289** [comment]
This was fixed by https://github.com/apache/pulsar/pull/4451
