### ISSUE TITLE
Upgrade ZooKeeper to 3.5.5 (stable)

### ISSUE THREAD

**Issue by sleungtoast** [apache/pulsar#4448]
**Is your feature request related to a problem? Please describe.**
This is just a nice to have. The new version of ZooKeeper has many features such as dynamic membership reconfiguration. Hopefully this can also take out the need for some workarounds to maintain ZK version compatibility with BK as well.

**Additional context**
Release 3.5.5 is now stable https://zookeeper.apache.org/releases.html

**Comment by merlimat** [comment]
We already did the exercise of upgrading to 3.5.4-beta (and then rolled back because of the perceived instability of `-beta`...). 

There are few breaking things in the on-disk format for zk 3.5, though we are already handling these (though AspectJ) in order to allow a rollback to 3.4.
