### ISSUE TITLE
Build fails with boost 1.70.0

### ISSUE THREAD

**Issue by scpeters** [apache/pulsar#4449]
**Describe the bug**
This package fails to compile with boost 1.70.0. I noticed this in the test logs of boost 1.70.0 in homebrew-core:

* https://github.com/Homebrew/homebrew-core/pull/38890
* https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/43080/version=sierra/testReport/junit/brew-test-bot/sierra/install___build_bottle_libpulsar/

**To Reproduce**
1. Using macOS 10.12, 10.13, or 10.14 with homebrew
2. `brew pull 38890`
3. `brew install libpulsar`
4. Build fails: https://gist.github.com/scpeters/d7c04bf3e531c994284c89135bf1147f

~~~
lib/ExecutorService.cc:37:17:
 note: in instantiation of function template specialization
 'std::__1::make_shared<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, std::__1::reference_wrapper<boost::asio::io_context> >' requested here
    return std::make_shared<boost::asio::ip::tcp::socket>(std::ref(io_service_));
                ^
~~~

**Expected behavior**
Successful compilation.

**Desktop (please complete the following information):**
 - OS: macOS 10.12, 10.13, 10.14

**Additional context**
Several other packages have had similar build failures with boost 1.70. The most relevant one to me seems to be websocketpp, which also has a problem with using `std::make_shared`. There is an open pull request changing from `make_shared` to `new`: https://github.com/zaphoyd/websocketpp/pull/814

**Comment by merlimat** [comment]
@scpeters Thanks for reporting this and for giving the pointer to the workaround solution. We'll apply the same change here.
