### ISSUE TITLE
token auth not work well for non-persistent topic get

### ISSUE THREAD

**Issue by zhaijack** [apache/pulsar#4466]
**Describe the bug**
This happens in 2.3.2
user report token auth not worked well for non-persistent topic get

when token auth configured, get tentant and get namespace both worked well, but get non-persistent topic failed: 
![WechatIMG175](https://user-images.githubusercontent.com/26834121/58881190-40523f00-870c-11e9-89eb-362ec97ccb47.png)

![WechatIMG172](https://user-images.githubusercontent.com/26834121/58881137-1ef15300-870c-11e9-86b1-3d4e36d482a4.png)

**Comment by jiazhai** [comment]
dup with #4560 will close this one
