### ISSUE TITLE
Lists all Functions deployed in a given namespace using API does not work

### ISSUE THREAD

**Issue by bbonnin** [apache/pulsar#4467]
**Describe the bug**
Context: the function workers are not in the brokers.
When invoking the service URL of a function worker to get the list of deployed functions in a given namespace, the response is 404 Not Found (while there are functions deployed). 

**To Reproduce**
1. Run a function worker
2. Deploy a function using the admin url of the function worker
3. Get the list of currently deployed functions in a namespace (`pulsar-admin --admin-url http://my-host:6750 functions list --namespace my-namespace --tenant my-tenant`)
4. The response is `HTTP 404 Not Found`

Also test with curl, same result. 
If the worker run in a broker, the response is correct.
The other pulsar-admin commands such as `functions create` are working.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
- Pulsar Version: 2.3.2
- Java Version: 1.8.0_202

**Comment by sijie** [comment]
@bbonnin Have you tried the latest Pulsar version?

**Comment by brunobonnin** [comment]
Hi, with Pulsar 2.5.2, now I can see all the functions. :)

**Comment by bbonnin** [comment]
Hi, with Pulsar 2.5.2, now, I can list the functions. :)
