### ISSUE TITLE
Logging Spew

### ISSUE THREAD

**Issue by tschmidt64-SC** [apache/pulsar#4472]
**Is your feature request related to a problem? Please describe.**
As far as I can tell the Java client's logging is not configurable. This results in constant spew of DEBUG level logs:
```
16:25:08.359 [pulsar-timer-4-1] DEBUG o.a.pulsar.client.impl.ProducerImpl - [persistent://public/default/my-ns/my-topic] [standalone-11-36] Batching the messages from the batch container with 0 messages 
16:25:08.360 [pulsar-timer-4-1] DEBUG o.a.pulsar.client.impl.ProducerImpl - [persistent://public/default/my-ns/my-topic] [standalone-11-36] Batching the messages from the batch container from timer thread
```

**Describe the solution you'd like**
Would be great for the Log level to be configurable at least.

**Comment by merlimat** [comment]
@tschmidt64-SC Pulsar client library uses SLF4J for logging. The logging configuration will depend on your logger implementation (eg. Log4J, Logback, etc...).

**Comment by sijie** [comment]
The issue has been fixed.

**Comment by dlmutart** [comment]
@sijie was there a code fix because I can't find the related pull request or was @mirlimat answer the right resolution?
