### ISSUE TITLE
Expect perf producer to publish non-empty buffer and use load from a multi-lines file

### ISSUE THREAD

**Issue by ayolivia** [apache/pulsar#4478]
Currently, perf producer publishes empty buffer of certain size, it may confuse someone using `pulsar-client consume` like below:

```
----- got message -----

----- got message -----

```
Furthermore, it uses the whole payload in a file which has multiple lines. It would be better to publish non-empty buffer and use load from a multi-lines file.

**Comment by jiazhai** [comment]
Thanks @murong00 for help on this
