### ISSUE TITLE
a little change needed of pulsar cli

### ISSUE THREAD

**Issue by sxcooler** [apache/pulsar#4481]
**Is your feature request related to a problem? Please describe.**
When I tried to use pulsar cli to test my code, send a json string to a topic, like this:
```
./pulsar-client produce my-topic --messages '{"appId":"test","userId":38,"phone":"13800138000","score":664}'
```
But the default behavior of pulsar-client produce is use comma as separator to divide messages, so my json divided into several messages which I didn't want to, like this:
```
19:06:03.742 [main] INFO  org.apache.pulsar.client.cli.PulsarClientTool - 4 messages successfully produced
```
And I couldn't find any way to escape the comma(backslash / double backslash did not work).
And after that I try to put the json into a file and use -f option, like:
```
./pulsar-client produce my-topic -f ./test.json
```
And I got 
```
java.nio.file.NoSuchFileException: ./test.json
```
So I had to use the full path.

**Describe the solution you'd like**
* Do not use comma as default separator in cli, or at least tell users how to escape it in the command line help.
* Support relative path in cli as other clis.

**Describe alternatives you've considered**
I can't imagine.

**Additional context**
none.

**Comment by liketic** [comment]
I think there are two things we can do for this:
1. split messages with another separator line \n.
2. add support for loading messages from file.

@jiazhai Which one do your prefer? Or both.

**Comment by sijie** [comment]
2 sounds a good option to start. because 1 will change some default behaviors which can involve backward compatibility discussion.

**Comment by liketic** [comment]
@sxcooler Which version are you using? I didn't reproduce this bug on master branch.

**Comment by sxcooler** [comment]
> @sxcooler Which version are you using? I didn't reproduce this bug on master branch.

I was using 2.3.2 on Mac.

**Comment by liketic** [comment]
@sxcooler 2.4.0 is on the way. I would like to suggest you try 2.4.0 once it's released.

**Comment by sxcooler** [comment]
> @sxcooler 2.4.0 is on the way. I would like to suggest you try 2.4.0 once it's released.

Thanks a lot!

**Comment by dmi-kov** [comment]
hey @liketic, I've got the same issue on the latest (2.5.0) version of Pulsar.

**Comment by eladchen** [comment]
Hi, 

This still appears to be broken (using version 2.5.0)
