### ISSUE TITLE
[Schema][AVRO] Unable to read fields of java built-in types defined in POJO class

### ISSUE THREAD

**Issue by yjshen** [apache/pulsar#4488]
**Describe the bug**
`AvroSchema` and `GenericAvroSchema` cannot read POJO field's of java built-in types, `GenericAvroSchema` lose all java built-in fields' value when read, and `AvroSchema` will lose part of them,  `BitSet` for example.

**To Reproduce**
``` java
class Foo {
   boolean b;
   java.util.Date dt;
   java.util.BitSet bs;
}

Schema sa = Schema.AVRO(Foo.class);
Schema sb = Schema.getSchema(a.getSchemaInfo());

Consumer ca = client.newConsumer(sa)....subscribe();
Consumer cb = client.newConsumer(sb)....subscribe();
```
For `ca`, `dt` can be read, `bs` is empty
For `cb`, both `dt` and `bs` is empty

**Comment by tisonkun** [comment]
Closed as stale and no one showed interest. Please open a new issue if it's still relevant to the maintained versions.
