### ISSUE TITLE
Security: Always fetch latest curl and OpenSSL releases for client lib

### ISSUE THREAD

**Issue by benstadin** [apache/pulsar#4497]
The client cpp Docker build currently downloads a fixed version of curl and OpenSSL. I propose to use the always latest versions when building the fat client lib.

The latest curl release is available on the developer homepage (I did not find a way without bas scripts to download the latest version easily from Github):
https://curl.haxx.se/metalink.cgi?curl=tar.gz

For OpenSSL there is a OpenSSL_1_1_0-stable branch for the currently used 1.1.x version.

**Comment by sijie** [comment]
@benstadin Could using latest version introduce instability to the build system?

**Comment by benstadin** [comment]
I think it is, but I've found other security related issues as well in other libraries. I think the best way would be to build from the maintained package source, and just add -fPIC to the build environment:

https://www.cmiss.org/cmgui/wiki/BuildingUbuntuPackagesFromSource

I also tried to update the Dockerfile in the pulsar-client-cpp/docker folder manually. But it fails early:

```
Step 8/32 : RUN ln -s /opt/python/${PYTHON_SPEC}/include/python${PYTHON_VERSION}m /opt/python/${PYTHON_SPEC}/include/python${PYTHON_VERSION}
 ---> Running in 77f069106b7f
ln: creating symbolic link `/opt/python//include/python' to `/opt/python//include/pythonm': No such file or directory
The command '/bin/sh -c ln -s /opt/python/${PYTHON_SPEC}/include/python${PYTHON_VERSION}m /opt/python/${PYTHON_SPEC}/include/python${PYTHON_VERSION}' returned a non-zero code: 1

```

**Comment by sijie** [comment]
@benstadin We have fixed the issue by introducing different variants of client libraries. You can use the library that is not linked with SSL. For details, please check: http://pulsar.apache.org/docs/en/client-libraries-cpp/#linux
