### ISSUE TITLE
Seperate name of namespaces, topics from its parent

### ISSUE THREAD

**Issue by hungndiam** [apache/pulsar#4498]
I'm on a frond-end project to manage Pulsar by Angular.
When I call API, received Namespace is: _**public/default**_ : _**public**_ is tenant, but the name actually is **_default_**. Or with Topic _**persistent://public/functions/assignments**_: topic is _**assignments**_

#### Expected behavior 

I want to have APIs to get topics, namespaces with their properties like

> [
  {
    "name": "metadata",
    "tenant": "public",
    "namespace": "functions",
    "type": "persistent",
    "link": "persistent://public/functions/metadata"
  },
  {
    "name": "assignments",
    "tenant": "public",
    "namespace": "functions",
    "type": "persistent",
    "link": "persistent://public/functions/assignments"
  }
]

#### Actual behavior

Now what I get is:

> [
"persistent://public/functions/metadata", 
"persistent://public/functions/assignments", 
"persistent://public/functions/coordinate"
]

#### Steps to reproduce

Add new APIs.

**Comment by tisonkun** [comment]
Closed as stale and no one works on it. Please create a new issue if it's still relevant to the maintained versions.

API changes should be go through a PIP process and I suggest you to throw the proposal on the dev@ mailing list.
