### ISSUE TITLE
Compressed batch payload size reported incorrectly in Java client

### ISSUE THREAD

**Issue by sleungtoast** [apache/pulsar#4506]
**Describe the bug**
In a batch and compression enabled producer, the uncompressed size of each message remains in the OpSendMsg, (`op.setBatchSizeByte(batchMessageContainer.currentBatchSizeBytes);`)
instead of the compressed size, which is correctly set for non-batch messages (`op.setBatchSizeByte(encryptedPayload.readableBytes());`). These are inside `ProducerImpl.java`.

Consumer stats also reports the uncompressed size, but I'm less concerned about that.

Also the max batch size is split according to the uncompressed size - that is intentional, correct?

**To Reproduce**
1. Send batch message with and without compression
2. Print `org.apache.pulsar.client.api.ProducerStats#getTotalBytesSent`
3. Message size is always the same though the compressed one should be different

**Expected behavior**
Message size in producer stats should reflect the compressed size

**Additional context**
Low impact since I expect the broker stats to reflect the compressed size.

**Comment by sijie** [comment]
@sleungtoast maybe we can have two different metrics, one for compressed, the other for the raw bytes?

**Comment by sleungtoast** [comment]
That sounds reasonable.

**Comment by tisonkun** [comment]
We're using `op.setBatchSizeByte(encryptedPayload.readableBytes());` for batch payload now.

Closed. Please open a new issue if it's still relevant.
