### ISSUE TITLE
2.3.2 website content is not aligned with code

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#4508]
the content of 2.3.2 website is not aligned with code. 
like [`negative acknowledgement `](https://pulsar.apache.org/docs/en/concepts-messaging/#acknowledgement-timeout) is not in 2.3.2 code, but is in the documentation.
The main reason is that the website is always cut from master. It should cut 2.3.2 base on 2.3.1 instead of master.

**Comment by sijie** [comment]
I think this is a problem related to the framework. We need to think about how to improve it.

**Comment by sijie** [comment]
Can we manually fix the 2.3.2 issue?

**Comment by sijie** [comment]
Closed this issue since we are providing scripts for cutting documentation for minor releases.
