### ISSUE TITLE
[Documentation][Client Lib Configuration] A full list configuration for Producer/Consumer/Client on website

### ISSUE THREAD

**Issue by yjshen** [apache/pulsar#4509]
**Is your feature request related to a problem? Please describe.**
Currently, when I am building a Java consumer, and want to check all available configurations. I am asked to `see the Javadoc for the ProducerBuilder class`. However, when I have checked that doc, I still need to know what kind of configuration should I pass to `loadConf(Map<String,Object> config)`. It's really frustrate.

**Describe the solution you'd like**
A full list of all available configuration option for consumer/producer/client somewhere on the website,  just like what we have for cluster configuration at `https://pulsar.apache.org/docs/en/reference-configuration/`

**Comment by Anonymitaet** [comment]
@yjshen As discussed offline, could you please provide raw materials? Many thanks

**Comment by Anonymitaet** [comment]
@yjshen any progress on this issue?

**Comment by Anonymitaet** [comment]
Done in several PRs:

* https://github.com/apache/pulsar/pull/5087/files
* TO DO

**Comment by yjshen** [comment]
Close this issue since all PRs has been merged.

**Comment by Anonymitaet** [comment]
@yjshen thanks for your guidance and help.

**Comment by yjshen** [comment]
> @yjshen thanks for your guidance and help.

Glad to help~
