### ISSUE TITLE
Offload if retention is expired

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#4515]
**Describe the solution you'd like**
Do you think it's possible to trigger offload depending on retention (or maybe other word)? 

Currently we can auto-offload only on storage size, but retention means storage size and/or duration, so I looking to offload on these two conditions or one of them.

WDYT?

**Comment by sijie** [comment]
@KannarFr can you explain more on the requirements?

**Comment by KannarFr** [comment]
@sijie offloading depends on size only can it depends on size + duration?

**Comment by KannarFr** [comment]
@sijie poke.

Another question, tiered storage is never clean. Currently, there is no retentionpolicies for tieredstorage right? What do you think about have offloadpolicies that define when a message should be offloaded and when an offloaded message should be removed? Both should have duration and size conditions.

**Comment by KannarFr** [comment]
@sijie @jiazhai poke

**Comment by sijie** [comment]
> @sijie offloading depends on size only yet, can it depends on size + duration?

Currently it doesn't support time based offloading. We can look into adding it. Although there is some tricks need to be taken care. The offload happens on a segment / ledger basis. So a segment can only be offloaded when it is sealed. A segment is only sealed when a new ledger is rolled over, which mean it also depends on the ledger rollover settings.

> What do you think about have offloadpolicies that define when a message should be offloaded and when an offloaded message should be removed? Both should have duration and size conditions.

+1 that sounds a good idea
