### ISSUE TITLE
Strange HTTP verbs on admin API

### ISSUE THREAD

**Issue by miton18** [apache/pulsar#4516]
**Describe the bug**
I often use rest APIs and there is something disappointing in Pulsar admin one.

When you want to [create a tenant](https://github.com/apache/pulsar/blob/8b2929b3e5403fb44653976dc74be287666f7b96/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java#L83):
`PUT /admin/v2/tenants/{tenant}`

And when you want to [update](https://github.com/apache/pulsar/blob/8b2929b3e5403fb44653976dc74be287666f7b96/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java#L110) admin roles and allowed cluster on an existing tenant:
`POST /admin/v2/tenants/{tenant}`

**To Reproduce**
--

**Expected behavior**
A POST to create a tenant and a PUT to update it

**Screenshots**
--

**Desktop (please complete the following information):**
--

**Additional context**
Pulsar version: v2.3.1 
[Tenants doc section](https://pulsar.apache.org/admin-rest-api/#operation/createTenant)

**Comment by sijie** [comment]
@miton18 thank you for raising this up. we can consider bumping the api version and changing the behavior following the rest world. Are you interested in contributing a change for it?

**Comment by tisonkun** [comment]
I agree that this can be less than awesome. But it should require a version bump (and breaking changes).

Please come up with a concrete proposal on the dev@ mailing list.

Closed as stale.
