### ISSUE TITLE
Go client: Missing ability to retrieve MessageID from pulsar.ProducerMessage

### ISSUE THREAD

**Issue by Jim-Lambert-Bose** [apache/pulsar#4537]
**Describe the bug**
There's no way to get the MessageID after publishing a pulsar.ProducerMessage.
This should be available and is documented here: https://pulsar.apache.org/docs/en/client-libraries-go/#producer-operations
```
 // Attempt to send the message asynchronously and handle the response
        producer.SendAsync(ctx, asyncMsg, func(msg pulsar.ProducerMessage, err error) {
            if err != nil { log.Fatal(err) }

            fmt.Printf("Message %s succesfully published", msg.ID())
        })
```
**Expected behavior**
I think, this is a defect and is available in other clients that wrap the C++ library

**Additional context**
pulsar v2.3.1 go client and libpulsar

**Comment by wolfstudy** [comment]
Thank you for pointing this out. The documentation here is incorrect. The `MessageID` field needs to be obtained after the consumer receives the message. You can try the following way:

```
for i := 0; i < 10; i++ {
	msg, err := consumer.Receive(ctx)
	if err != nil {
		log.Fatal(err)
	}
	err = consumer.Ack(msg)
	assert.Nil(t, err)
        fmt.Printf("Message %s succesfully received", msg.ID())
}
```

**Comment by wolfstudy** [comment]
@Jim-Lambert-Bose This problem will be solved in this [pull:4571](https://github.com/apache/pulsar/pull/4571).

PTAL thanks.

**Comment by Jim-Lambert-Bose** [comment]
While I agree that fixing the docs is the expedient way to resolve the issue, it doesn't fix the problem: there's no way to get the `msgID()` after publishing a message.  Without this `ID` there's no way to trace a message from producer to consumer (think distributed tracing).  I'm guessing that the `ID` has to be attached to the message as it's published, so Pulsar just needs to return it to the publishing client.

**Comment by grantwwu** [comment]
Can we reopen this?

**Comment by sijie** [comment]
#4811 is fixing the issue.
