### ISSUE TITLE
offloaded: outbound traffic >>> inbound traffic

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#4545]
Hi, how works consumption of offloaded messages and how "healthchecks" offloaded works?

The reason of this questions is: I've got big traffic outbound traffic 165GB for 2GB inbound traffic, I think it's quite normal as pulsar checks its offloaded storage when a consumer is on the corresponding topic. But I would like to know how it works with a schema or something or a quote/location of related code.

**Comment by sijie** [comment]
@KannarFr pulsar broker will to read the messages from offloaded segments when a topic consumer wants the messages. so it will consume inbound bandwidth to load the messages from S3 to brokers.

**Comment by KannarFr** [comment]
@sijie You mean outbound?

**Comment by sijie** [comment]
@KannarFr 

I mean it consumes both inbound and outbound. 

the inbound bandwidth for loading the messages from S3 to broker.
the outbound bandwidth for dispatching the messages from brokers to consumers.

**Comment by KannarFr** [comment]
Oh, but I was talking about bandwidth on bucket not on broker.

**Comment by KannarFr** [comment]
Anyway, same idea.

**Comment by KannarFr** [comment]
But huge consumption of bucket outbound.

**Comment by sijie** [comment]
@KannarFr 

yes it is outbound bandwidth of buckets. but if you are going to read data from offloaded segments, don't you need to read those buckets and once you are reading those buckets, it is going to consume the outbound bandwidth, no? Is there any other approach to avoid outbound bandwidth on the buckets?

**Comment by KannarFr** [comment]
Ok, it was to be sure. You are right.
