### ISSUE TITLE
set offload bucket per topic and per tenant/namespace

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#4547]
**Describe the solution you'd like**
Do you think it's easy to set s3 bucket for offload to topic level and tenant/namespace instead of cluster level? (i.e. be able to configure one bucket per topic, and one bucket per tenant/namespace).

**Comment by KannarFr** [comment]
I think the best should have a default bucket which is defined in `broker.conf` and be able to configure one bucket per tenant and/or tenant/namespace and/or tenant/namespace/topic. Then when offload is threw, it will take the more specified defined. WDYT?

**Comment by KannarFr** [comment]
@sijie I started to dev this feature. Where do we store the offload configuration per tenant/namespace? On BK as it's done for schemas? Or in ZK?

**Comment by KannarFr** [comment]
(I started an implementation copied from Schemas usages).

**Comment by sijie** [comment]
@KannarFr I think it should be part of namespace policies. Please check this class : https://github.com/apache/pulsar/blob/master/pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/Policies.java

**Comment by KannarFr** [comment]
Ok.

**Comment by shiv4289** [comment]
Really looking forward to this feature. The following can be implemented once the directory structure for tenant, namespace and topic is there: https://github.com/apache/pulsar/issues/5978
