### ISSUE TITLE
Dashboard shows data only after running pulsar-admin command (docker, standalone)

### ISSUE THREAD

**Issue by langep** [apache/pulsar#4550]
**Describe the bug**
I am using docker-compose to run pulsar in standalone mode together with dashboard. However, my dashboard stays empty until I run `bin/pulsar-admin clusters list` inside the pulsar container.

**To Reproduce**
1. Create docker-compose.yaml
```
# docker-compose.yaml
version: "3.7"
services:
  apache-pulsar:
    hostname: apache-pulsar
    image: apachepulsar/pulsar:2.3.2
    command: ["bin/pulsar", "standalone"]
    ports:
      - "6650:6650"
      - "8080:8080"
  apache-pulsar-dashboard:
    hostname: apache-pulsar-dashboard
    image: apachepulsar/pulsar-dashboard
    ports:
      - "80:80"
    environment:
      - SERVICE_URL=http://apache-pulsar:8080
```

2. Run `docker-compose up`
3. Go to `http://locahost` and check the dashboard. It does not show data.
4. Run `docker exec apache-pulsar /bin/bash`
5. Run `bin/pulsar-admin cluster list` inside the container
6. The dashboard now shows data (might need a refresh).

**Expected behavior**
Have the dashboard show data without running a command in the container.

**Desktop (please complete the following information):**
 - OS: macOS but running in docker containers

**Additional context**
Might be related to #3367

**Comment by sijie** [comment]
@langep the current dashboard is using stats for displaying the resources. so when you run some operations on the cluster, the stats will be showing up and the dashboard will be able to collect stats and display the dashboard correctly.

**Comment by skyrocknroll** [comment]
@sijie When we restart all the brokers we don't see any topics or namespace in the dashboard. Only after producing and consuming the topic the topics appear in the dashboard. is it expected or bug  ?

**Comment by langep** [comment]
@sijie I see. I wasn't sure if this is the default behavior. I definitely saw resources showing up when they got used.

**Comment by sijie** [comment]
@skyrocknroll @langep this is the current implementation as it is using stats for the dashboard. to change this behavior, it might require a rewrite of the dashboard. I know there are teams looking into implementing a new dashboard. for example, [pulsar-express](https://github.com/bbonnin/pulsar-express) is one of the efforts. although I haven't looked deeply how it was implemented yet.

**Comment by sijie** [comment]
Pulsar dashboard is deprecated in favor of using Pulsar Manager. http://pulsar.apache.org/docs/en/administration-pulsar-manager/ 

So close this now. If you have any questions, please re-open it.
