### ISSUE TITLE
Add warning : Apache Pulsar Configuration / Bookie / minorCompactionInterval property

### ISSUE THREAD

**Issue by guillaume-braibant** [apache/pulsar#4558]
**Problem**

minorCompactionInterval value must be greater than gcWaitTime. If it is not the case, bookie will crash at startup. This is not indicated either in Bookkeeper Documentation nor in Apache Pulsar Configuration documentation. A warning for this in the minorCompactionInterval  description section would be welcome.

**Source of the problem**

https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java#L196

Lines 196 to 198

**Solution**

Put a clear warning about how minorCompactionInterval value should be set in regard to the gcWaitTime value (minorCompactionInterval in milliseconds must be greater than gcWaitTime).

**Comment by codelipenghui** [comment]
Thank you for your feedback, more instructions should be added to the bookie configuration file.

**Comment by sijie** [comment]
@codelipenghui @guillaume-braibant can you guys help create an issue at apache/bookkeeper project? 

it seems to be a simple change. Are you guys interested in contributing code to apache/bookkeeper?

**Comment by codelipenghui** [comment]
@sijie I have added related issue in bookkeeper.
