### ISSUE TITLE
C++ client producer sendAsync() method will be blocked forever, if enough batched messages sent timeout.

### ISSUE THREAD

**Issue by easyfan** [apache/pulsar#4569]
**Describe the bug**
C++ client producer sendAsync() method will be blocked forever, if enough batched messages sent timeout.
**To Reproduce**

1. Using the following producer configures: 
setBatchingEnabled(true)
setBlockIfQueueFull(true)
setSendTimeout(100) (shorter timeout interval would help reproduce the issue)
2. Producing huge plant of messages (better in a pressure test env.);
3. Try to made some producer timeout happens (with shorter timeout interval for example)
4. After accumulating enough timeout captured, the pulsar::Producer::sendAsync method will be blocked and will nerver turned back to available.

**Expected behavior**
The method pulsar::Producer::sendAsync(...) might be blocked for a while, if the pending messages reached the max value, but it shall be returned back available if previous pending messages acked or reaching timeout point.

**Desktop (please complete the following information):**
 - OS: Centos

**Comment by easyfan** [comment]
Root cause: a simple mistake in pulsar/pulsar-client-cpp/lib/ProducerImpl.cc:

The reserved spots for all individual messages in a batch message (just reserved, not occupied by pushing in) did not be released in the case of batching message sent failure (sent timeout or any other failure cases), which was processed by `ProducerImpl::failPendingMessages(...)`

**Comment by sijie** [comment]
@easyfan are you interested in sending a pull request for it?

**Comment by easyfan** [comment]
OK. I will send pull request later today.

**Comment by sijie** [comment]
Awesome @easyfan !

**Comment by easyfan** [comment]
@sijie BTW, I found another timeout check arbitrary issue inside C++ client. And the solution also in the exact same file pulsar/pulsar-client-cpp/lib/ProducerImpl.cc. So shall I open another issue for it, or just add some comments inside this one?

**Comment by easyfan** [comment]
@sijie  Seems the solution of said timeout check issue I mentioned before need a discussion about the performance, I open another issue for recording: https://github.com/apache/pulsar/issues/4656

**Comment by sijie** [comment]
@easyfan let's have a separated discussion in #4656

**Comment by easyfan** [comment]
A weird Unit test issue encountered...
======================================================================
FAIL: test_publish_compact_and_consume (__main__.PulsarTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pulsar_test.py", line 641, in test_publish_compact_and_consume
    self.assertEqual(msg0.data(), b'hello-1')
AssertionError: 'hello-0' != 'hello-1'

----------------------------------------------------------------------

From the code, seems the case is something about the consumer configuration: "reading compact".
Very strange.
