### ISSUE TITLE
[spark streaming] Support spark direct stream

### ISSUE THREAD

**Issue by liketic** [apache/pulsar#4584]
Currently, we only support receiver stream. See https://spark.apache.org/docs/2.2.0/streaming-kafka-0-8-integration.html#approach-2-direct-approach-no-receivers

**Comment by sijie** [comment]
See comment at https://github.com/apache/pulsar/issues/4585#issuecomment-504836970

**Comment by sijie** [comment]
@liketic I have to take my previous back. It seems that you were asking for a feature on spark streaming. The one I commented in #4585 is about Spark SQL and Spark Structured Streaming. I don't think anyone is working on a direct stream implementation. If you are interested in contributing, feel free to contribute.

**Comment by liketic** [comment]
@sijie OK. I'll take a look.

**Comment by sijie** [comment]
Close this issue since there is already a pulsar-spark connector for structured streaming. https://github.com/streamnative/pulsar-spark

**Comment by maneeshbhunwal123** [comment]
@sijie is this connector https://github.com/streamnative/pulsar-spark based on direct approach or reciever based approach?
I have asked same question [here](https://stackoverflow.com/questions/74384351/apache-pulsar-direct-approach-with-apache-spark) can you please help me understand what use cases both the adaptors are solving?
