### ISSUE TITLE
pulsar connector for clickhouse

### ISSUE THREAD

**Issue by liketic** [apache/pulsar#4601]
ClickHouse is an open source column-oriented database management system capable of real time generation of analytical data reports using SQL queries. It's would be great if we can sink data from pulsar to clickhouse.

**Comment by aahmed-se** [comment]
A basic with jdbc will be very simple a tighter integration will be harder , what level of capability do you need ?

**Comment by sijie** [comment]
@kuangye098 ^^

**Comment by vzhikserg** [comment]
@sijie  #6835 should close this feature request.

**Comment by sijie** [comment]
Not sure why it didn't close the issue here. Closing it now.

**Comment by sijie** [comment]
This issue has been fixed by #6835
