### ISSUE TITLE
[doc] Refine the framework and implement language-specific code tabs

### ISSUE THREAD

**Issue by Jennifer88huang** [apache/pulsar#4606]
**Is your feature request related to a problem? Please describe.**
We will adopt new structure for Pulsar Functions, as proposed in #4554, so we need new framework and implement language-specific code tabs for Java, Go, and Python languages.

**Describe the solution you'd like**
We can refine the framework, refer to https://docusaurus.io/docs/en/doc-markdown

**Comment by Jennifer88huang** [comment]
@tuteng Could you please help refine the framework? Thank you very much.

**Comment by tuteng** [comment]
> @tuteng Could you please help refine the framework? Thank you very much.

Ok, I will try to upgrade docusaurus to 1.11.1 later

**Comment by Jennifer88huang** [comment]
thank you very much.

**Comment by Jennifer88huang** [comment]
Great, we can adopt the language-specific tab now. Thank you very much for your help.
