### ISSUE TITLE
pulsar-admin cli: pulsar functions api issues after changing function parallelism > 1

### ISSUE THREAD

**Issue by one70six** [apache/pulsar#4610]
**Describe the bug**
Pulsar v2.3.2

Commands such as the following work as long as your function has a parallelism of 1...
`$PULSAR_HOME/bin/pulsar-admin functions getstatus --tenant public --namespace default --name exclamation`

The results on the functions worker logs show a good return of:
`"GET /admin/v3/functions/public/default/exclamation/status HTTP/1.1" 200 354 "-" "Pulsar-Java-v2.3.2" 14`

`{
  "numInstances" : 1,
  "numRunning" : 1,
  "instances" : [ {
    "instanceId" : 0,
    "status" : {
      "running" : true,
      "error" : "",
      "numRestarts" : 0,
      "numReceived" : 0,
      "numSuccessfullyProcessed" : 0,
      "numUserExceptions" : 0,
      "latestUserExceptions" : [ ],
      "numSystemExceptions" : 0,
      "latestSystemExceptions" : [ ],
      "averageLatency" : 0.0,
      "lastInvocationTime" : 0,
      "workerId" : "localhost-6750"
    }
  } ]
}
`

Changing the parallelism to >1 results in a bad return and the following output in the logs:
`"GET /admin/v3/functions/public/default/exclamation/0/status HTTP/1.1" 500 110 "-" "Pulsar-Java-v2.3.2" 57`

`org.apache.pulsar.client.admin.PulsarAdminException$NotAuthorizedException: HTTP 401 Unauthorized
Reason: HTTP 500 Internal Server Error`

It looks like the API is not able to pickup the numbers that are being appended to the URL when you add the parallelism, i.e.

`GET /admin/v3/functions/public/default/exclamation/0/status`
`GET /admin/v3/functions/public/default/exclamation/1/status`
`GET /admin/v3/functions/public/default/exclamation/2/status`

**To Reproduce**
1. Create the exclamation function:
`$PULSAR_HOME/bin/pulsar-admin \
functions create \
  --jar examples/api-examples.jar \
  --classname org.apache.pulsar.functions.api.examples.ExclamationFunction \
  --inputs persistent://public/default/exclamation-input \
  --output persistent://public/default/exclamation-output \
  --name exclamation`
2. Run the following to see good output
`$PULSAR_HOME/bin/pulsar-admin functions getstatus --tenant public --namespace default --name exclamation`
3. Change the parallelism to >1
`$PULSAR_HOME/bin/pulsar-admin \
functions update \
  --jar examples/api-examples.jar \
  --classname org.apache.pulsar.functions.api.examples.ExclamationFunction \
  --inputs persistent://public/default/exclamation-input \
  --output persistent://public/default/exclamation-output \
  --tenant public \
  --namespace default \
  --name exclamation \
  --parallelism 3 \`
4. Rerun the command from step 2
``$PULSAR_HOME/bin/pulsar-admin functions getstatus --tenant public --namespace default --name exclamation`

**Expected behavior**
Should respond with a 200 and a result

**Comment by tuteng** [comment]
I tested in the latest version and version 2.3.2, but I didn't find this problem. I don't know what else the broker reported wrong

**Comment by one70six** [comment]
It's like it can't route do to the URL adding the /0 or /1 etc. If that is not there, it works fine. I rebuilt the cluster from scratch and it still has this issue in 2.3.2. Not sure why it would not happen to your cluster. Is your conf file different than mine?

**Comment by tuteng** [comment]
I used this [image](https://hub.docker.com/r/apachepulsar/pulsar/tags) of 2.3.2 version to test, you can see what is different from your configuration.

**Comment by jerrypeng** [comment]
@one70six what is your cluster setup? Single node standalone or multi node cluster?  Running function worker with broker or alone?

**Comment by one70six** [comment]
@jerrypeng It's a multi node cluster

- 6 brokers
- 6 bookies
- 6 Zookeepers
- 6 Functions Workers (outside brokers)

**Comment by sijie** [comment]
@one70six Does the problem still exist in your cluster?

**Comment by tisonkun** [comment]
Closed as stale and no response. Please open a new issue if it's still relevant to the maintained versions.
