### ISSUE TITLE
Return empty object of Namespace Isolation Policies instead of PulsarAdminException$NotFoundException

### ISSUE THREAD

**Issue by hungndiam** [apache/pulsar#4618]
**Describe the bug**

API: _**/admin/v2/clusters/{cluster}/namespaceIsolationPolicies**_ returns _**PulsarAdminException$NotFoundException**_ after creating new cluster
This is not an exception while cluster is just created.

**Expected behavior**

Return `{}` if not exist.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
