### ISSUE TITLE
[pulsar-dashboard]Dashboard report MultipleObjectsReturned

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar#4622]
**Describe the bug**
If cross-regional replication is turned on, the same Topic will appear, Django uses get_object_or_404  will throw  an exception MultipleObjectsReturned

**To Reproduce**

**Expected behavior**
In case of duplicate data, the information will be displayed normally.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

Fix
Use  get_list_or_404 instead of get_object_or_404, but check the logic elsewhere to prevent similar errors.

**Comment by se7enkings** [comment]
**Screenshots**
```
Environment:

Request Method: GET
Request URL: http://{dashboard}:8780/stats/topic/persistent/test-signal/test-replication/msgsync-partition-14/

Django Version: 1.11.20
Python Version: 2.7.16
Installed Applications:
['stats.apps.StatsConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "./stats/views.py" in topic
  132.         topic = get_object_or_404(Topic, name=topic_name, timestamp=timestamp)

File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py" in get_object_or_404
  85.         return queryset.get(*args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py" in get
  384.             (self.model._meta.object_name, num)

Exception Type: MultipleObjectsReturned at /stats/topic/persistent/online-signal/signal-replication/msgsync-partition-14/
Exception Value: get() returned more than one Topic -- it returned 2!
```
- If we change the line 132 to "topic = get_list_or_404(Topic, name=topic_name, timestamp=timestamp)",  the value of "topic" will be :
`[<Topic: persistent://test-signal/test-replication/msgsync-partition-14>, <Topic: persistent://test-signal/test-replication/msgsync-partition-14>]`

**Comment by sijie** [comment]
@tuteng @se7enkings have you guys sent out the fix?

**Comment by tuteng** [comment]
I have to consider how to repair this one. In the case of multiple clusters, for example, cross-regional replication, there may be exactly the same topic, tenant, namespace, and topic are exactly the same. The current dashboard does not consider this situation. The repair of this one may need to modify the front end.

**Comment by sijie** [comment]
Closed this issue since pulsar-dashboard has been deprecated.
