### ISSUE TITLE
Python Pulsar client producer send should return messageId

### ISSUE THREAD

**Issue by grantwwu** [apache/pulsar#4626]
**Is your feature request related to a problem? Please describe.**
The Python client does not return a Message ID for `send` on producers.  `send_async` also seems to return a bogus message ID.

**Describe the solution you'd like**
Match the behavior of the Java Pulsar client, which is documented to return a message ID.

**Describe alternatives you've considered**
Outside of horrendous hacks involving creating a consumer at the same time and getting messages that way, I can't think of any.

**Additional context**
https://pulsar.apache.org/api/python/#pulsar.Producer.send
https://pulsar.apache.org/api/client/org/apache/pulsar/client/api/Producer.html#send-T-

**Comment by Jim-Lambert-Bose** [comment]
Can we get this fixed for the Go client as well?  I opened an issue about it which was closed: https://github.com/apache/pulsar/issues/4537

I'd be happy if a fix was just included in the new Go client under dev.

**Comment by yittg** [comment]
@sijie Anyone is working on this? otherwise i would like to take it.

**Comment by sijie** [comment]
@yittg : #4811 is fixing the issue in C++ client and CGo client. For the python fix, it has to wait for #4811 to be merged.

**Comment by jiazhai** [comment]
since 4811 is marked as 2.5.0, would like to make this 2.5.0

**Comment by sijie** [comment]
This is fixed by #4811
