### ISSUE TITLE
Netty Connector chunks request bodies into separate messages 

### ISSUE THREAD

**Issue by Mrdigs** [apache/pulsar#4630]
When the Netty connector is configured in HTTP mode, messages longer than 1024 bytes are produced as separate messages.

I've double checked with ngrep: one HTTP POST results in multiple messages. I'm using a topic with a JSON schema and it errors when trying to consume a message because the message content is not a fully formed JSON message as it is cut off, with the remainder of the JSON string in the next message.

In my opinion, this should be a high priority issue because it makes the Netty connector unusable in real world scenarios.

**Comment by tisonkun** [comment]
Closed as stale and no one works on it. Please create a new issue if it's still relevant to the maintained versions.
