### ISSUE TITLE
HTTP request headers and URL parameters in Netty connector message properties

### ISSUE THREAD

**Issue by Mrdigs** [apache/pulsar#4631]
I need to be able to at least access the values of certain HTTP headers of requests POSTed to the Netty connector to provide some context to drive how the message should be routed or interpreted in my particular use case whereby the external system sends meta data in the HTTP headers.

Although it's not necessary in my case,  I can imagine it would also be very useful to be able to access the URL parameters of a message, and potentially the path.

For example. any given connector must publish messages to a configured topic, meaning that if the ability to publish to several topics via HTTP is required, a connector per topic needs to be created.

If the context of the request rather than just the body forms part of the message, then a single connector could provide routing information. For example, I could create a single connector which publishes on a given topic, and a single consumer that re-publishes the message on another topic depending on the request headers, path or parameters.

Consider the following potential scenario in the context of a consumer:

final Message<String> message = consumer.receive();
producers.get(message.getProperty("http.parameters.topic")) .send(message.getValue());

Which would allow a single HTTP connector to receive messages destined for an unlimited number of topics, rather than creating a connector for each potential topic.

The usefulness of the Netty connector in HTTP mode would be massively increased by this functionality.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
