### ISSUE TITLE
Ho to integrate the existing premetheus in k8s cluster?

### ISSUE THREAD

**Issue by Kiddinglife** [apache/pulsar#4633]
Hi folks,
I alreasy had premetheus stack deployed on my k8s cluster.
I am expecting some tips about how to add pulsa metrics to my existing premetheus stack?
Thanks.

**Comment by tuteng** [comment]
You can refer to this [repositories](https://github.com/streamnative/apache-pulsar-grafana-dashboard) to add some related metrics.

**Comment by sijie** [comment]
The question has been answered
