### ISSUE TITLE
The project does not build with JDK 12. 

### ISSUE THREAD

**Issue by annubiz** [apache/pulsar#4641]
**Is your feature request related to a problem? Please describe.**
Pulsar does not build with JDK 12.    It requires JDK 1.8.
JDK 1.8 will end of life in Dec 2020.  That is a year and a half away, but conversion may take a while.

**Describe the solution you'd like**
Please start an effort (branch) to support JDK 12

**Describe alternatives you've considered**
OpenJDK

**Additional context**
Many many many systems still use 1.8 and will for potentially yrs.  It can be very difficult to support a mission critical system that uses several different jre versions.  You may need to start to support 12 soon and continue to support 8 and 12 for several years.

**Comment by merlimat** [comment]
@annubiz We do support JDK 11, (even though the unit tests are not completely passing, mostly due to Mockito and Powermock issues), though we haven't started to check with JDK 12. 

It would be good to have a Jenkins pipeline with JDK setup for 2.5 release

**Comment by leonidv** [comment]
I've run Apache Pulsar 2.4.1 in standalone mode on open-jdk-13:

`
 07:28:28.461 [main] INFO  org.apache.zookeeper.server.ZooKeeperServer - Server environment:host.name=lv-linux
07:28:28.461 [main] INFO  org.apache.zookeeper.server.ZooKeeperServer - Server environment:java.version=13
07:28:28.461 [main] INFO  org.apache.zookeeper.server.ZooKeeperServer - Server environment:java.vendor=N/A
07:28:28.461 [main] INFO  org.apache.zookeeper.server.ZooKeeperServer - Server environment:java.home=/usr/lib/jvm/java-13-openjdk
`

I've remove -XX:+AggressiveOpts from PULSAR_GC

**Comment by codelipenghui** [comment]
@annubiz Is @leonidv's comment can help? Move it to 2.7.0 first, feel free to move it back if it needs to onboard 2.6.0 release.
