### ISSUE TITLE
[Build] erroneous aspectj weaving processing on 

### ISSUE THREAD

**Issue by willome** [apache/pulsar#4652]
While building the project, I see this error  in *pulsar-zookeeper-utils*  module :  

```bad version number found in /root/.m2/repository/org/aspectj/aspectjrt/1.9.2/aspectjrt-1.9.2.jar expected 1.9.1 found 1.9.2```

and

```
You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
Your processor is: org.aspectj.org.eclipse.jdt.internal.compiler.apt.dispatch.BatchProcessingEnvImpl
Lombok supports: sun/apple javac 1.6, ECJ
    <unknown source file>:<no line information>
```

This probably means that the weaving is not working as expected on this module.

**Comment by merlimat** [comment]
> This probably means that the weaving is not working as expected on this module.

That is correct, Lombok and AspectJ don't play nice together. This is why we cannot use Lombok in the `pulsar-zookeeper-utils` module. The warning here should be not a problem.

**Comment by sijie** [comment]
The question was answered.
