### ISSUE TITLE
Build fails including Logger.h

### ISSUE THREAD

**Issue by benstadin** [apache/pulsar#4655]
Using Xcode / clang, the build fails when including Logger.h, because there is a log level named DEBUG (build error is "Expected identifier" because XCode defines a DEBUG macro per default for the debug target). Renaming it to e.g. TDEBUG fixes the issue:

enum Level
    {
        TDEBUG = 0,
        INFO = 1,
        WARN = 2,
        ERROR = 3
    };

IMHO, the best would be to avoid DEBUG and rename the enums to something like LOG_DEBUG, LOG_INFO etc. Even though it will mean a breaking change in some code.

**Comment by merlimat** [comment]
@benstadin I think it would indeed be fine to update these enum names
