### ISSUE TITLE
C++ client producer sendAsync() timeout check method seems too arbitrary

### ISSUE THREAD

**Issue by easyfan** [apache/pulsar#4656]
**C++ client producer sendAsync() timeout check method seems too arbitrary**

**Analysis**
In general, the c++ client producer timeout check was implemented in pulsar/pulsar-client-cpp/lib/ProducerImpl.cc, `ProducerImpl::handleSendTimeout(...)`, which is registered as a handler of `ProducerImpl::sendTimer_`;
In any performing phase of `ProducerImpl::sendTimer_`, the very first `pulsar::OpSendMsg` element inside `ProducerImpl::pendingMessagesQueue_` will be picked up and compare the  OpSendMsg::timeout_ with current tick. If the time diff is less than 0, there is a sending timeout happens. 

So far so good.

But then, it invokes the method `ProducerImpl::failPendingMessages(...)` for dealing the message failure stuff. Definitely, it works, but not only on the message it already checked as we hoped, but just all the messages inside `ProducerImpl::pendingMessagesQueue_`.

Result: Inside a sending timeout check, if the very oldest message inside the pending queue timeout, will lead all the messages inside the pending queue to be processed as a timeout

**Expected behavior**
A more specifical check on every message timeout. 

**Desktop (please complete the following information):**
 - OS: centOS

**About the performance**
As there are much more performing of check and compare than it was, the performance will downgrade undoubtedly. We may have a discussion of it, and make a decision then.

**Comment by merlimat** [comment]
> But then, it invokes the method ProducerImpl::failPendingMessages(...) for dealing the message failure stuff. Definitely, it works, but not only on the message it already checked as we hoped, but just all the messages inside ProducerImpl::pendingMessagesQueue_.

The reason for erroring out all the messages in the queue after the 1st message times out is to give chance to the application to preserve ordering. 

If you're publishing m1, m2 and m3. If m2 times out, a consumer might see m1 followed by m3. By clearing the queue, application can decides to resend m2 & m3 in same order (or just failed both upstream operations). 

Another consideration, is that typically the timeout is set to a value which is order of magnitudes bigger than the normal publish latency (eg: 30sec vs 5millis). This means that when one message times out, it will be very likely that some bigger issue is involved and that most of the messages will anyway hit the timeout threshold.

**Comment by easyfan** [comment]
@merlimat  Yes, your word sounds reasonable. Thanks for the response.
I will close this issue then.
