### ISSUE TITLE
Broken link on the "Develop Connectors" page

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#4661]
**Describe the bug**
On the following page, https://pulsar.apache.org/docs/en/io-develop/ , the link pointing to the KafkaSource as a good example to follow takes us to a 404 => https://github.com/apache/pulsar/tree/master/master/pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaAbstractSource.java

**To Reproduce**
1. Go to  https://pulsar.apache.org/docs/en/io-develop/
2. Click on "Source Connector" link
3. See error

**Expected behavior**
We expect to be taken to the https://github.com/apache/pulsar/blob/master/pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaStringSource.java page

**Screenshots**

<img width="880" alt="Screen Shot 2019-07-02 at 8 48 59 AM" src="https://user-images.githubusercontent.com/35466513/60527045-5b31b800-9ca6-11e9-8366-c961bec92493.png">

**Comment by sijie** [comment]
This is fixed by #4674
