### ISSUE TITLE
Document for delayed message delivery.

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#4675]
Need document for delayed message delivery to describe how to send a delayed message by pulsar producer and introduce architecture of delayed message delivery in pulsar.

**Comment by xujianhai666** [comment]
can I  do it ?

**Comment by codelipenghui** [comment]
@xujianhai666 welcome!

**Comment by Jennifer88huang** [comment]
@xujianhai666 could you please pull request to https://github.com/apache/pulsar/pulls

**Comment by jiazhai** [comment]
Seems this already fixed in https://github.com/apache/pulsar/pull/5293
