### ISSUE TITLE
Search box on website stopped working

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#4695]
After the update of Docusaurus to 1.11 in #4682, the search box stopped working.

@tuteng @sijie

**Comment by tuteng** [comment]
This seems to be related to the crawling of the algolia. The content of the old version can be searched normally, and the content of version 2.4.0 does not seem to have been included in algolia yet.

**Comment by sijie** [comment]
@tuteng Can you file an issue to check with algolia docsearch team? https://github.com/algolia/docsearch-configs

**Comment by tuteng** [comment]
This issue has been addressed, the search is already working properly. @merlimat

**Comment by merlimat** [comment]
👍 Nice!
