### ISSUE TITLE
authentication with a valid client mTLS certificate is rejected

### ISSUE THREAD

**Issue by Jim-Lambert-Bose** [apache/pulsar#4696]
**Describe the bug**
Pulsar fails mTLS when the client presents a cert with SANs and no CN in the x509 Subject.

As per RFC 6125 (published in '2011) the validator must check SAN first, and if SAN exists, then CN should not be checked.    https://tools.ietf.org/html/rfc6125#section-6.4.4

Pulsar is not checking the SANs and appears to only validate a client cert using the CN within the Subject.

**To Reproduce**
Create a client cert with no CN and a SAN and try to authenticate via mTLS

I have a repo setup for this testing: https://github.com/Jim-Lambert-Bose/test-standalone-pulsar-with-tls

To reproduce: 

- uncomment https://github.com/Jim-Lambert-Bose/test-standalone-pulsar-with-tls/blob/a9a162cc10d2666e8ffb8509c722452bd03c31a8/Dockerfile#L37
- which will create an admin cert with a SAN and no CN during the docker build
- build/run the container: ./build.sh && ./run.sh
- run: standalone-exec-bash: to exec into the standalone container
- from within container: pulsar-admin tenants list

You'll get a 401

**Expected behavior**
Pulsar's mTLS authentication should follow RFC 6125 and support client certs with SANs and no CN in the Subject.

**Comment by zymap** [comment]
@sijie  It' s looks like an enhancement of the Pulsar security.  

@Jim-Lambert-Bose Would you like to add it to the Pulsar? I'm afraid I haven't time to do this because I'm focused on the transaction-related works.

**Comment by tisonkun** [comment]
Closed as stale and no one shows interest. Please open a new issue if it's still relevant to the maintained versions.
