### ISSUE TITLE
Memory leak in Pulsar 2.3.1

### ISSUE THREAD

**Issue by ArtemShaban** [apache/pulsar#4697]
Not far ago we tried update our production to Pulsar 2.3.1 from 2.2.1 version. But after one-two days working we noticed big CPU and memory consumption.
We did memory dumps and found suspicious objects.

In all dumps of brokers there are huge count of org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl and a lot of big objects of java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue

https://www.dropbox.com/s/jde4h7yesu4i0a5/Screenshot%202019-07-09%2019.45.25.png?dl=0
https://www.dropbox.com/s/pcewv24p4mx73dj/Screenshot%202019-07-09%2019.46.05.png?dl=0

and this 2 types of objects occupy most part of heap:
https://www.dropbox.com/s/kx213bfvwgbgjhk/Screenshot%202019-07-09%2019.49.12.png?dl=0

```Problem Suspect 1

29 instances of "java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue", loaded by "<system class loader>" occupy 3,834,885,672 (69.63%) bytes.

Biggest instances:
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue @ 0x5c19ba9c0 - 486,434,080 (8.83%) bytes.
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue @ 0x5c19bc680 - 480,259,160 (8.72%) bytes.
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue @ 0x5c19bcb40 - 479,897,832 (8.71%) bytes.
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue @ 0x5c19ba768 - 479,323,032 (8.70%) bytes.
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue @ 0x5c19bcd88 - 479,216,656 (8.70%) bytes.
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue @ 0x5c19ba2c8 - 478,129,544 (8.68%) bytes.
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue @ 0x5c19ba510 - 477,094,040 (8.66%) bytes.
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue @ 0x5c19bc8e8 - 474,507,096 (8.62%) bytes.


78,804 instances of "org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl", loaded by "sun.misc.Launcher$AppClassLoader @ 0x5c1401cd0" occupy 1,139,905,784 (20.70%) bytes. 

Keywords
org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl
sun.misc.Launcher$AppClassLoader @ 0x5c14

```

Also I compared memory dumps of 2.3.1 and 2.2.1 - and 2.2.1 has no such problems.
I know and there is new updates of Pulsar, and I did't found any notions about such case.

We tried reproduce this case in test environment - unsuccessfully.

In our production case we create/delete a lot of topics (probably this note will be helpful).

**Comment by merlimat** [comment]
@ArtemShaban the memory usage is due to the managed ledger write timeout that was introduced in 2.3. This has been disabled already by default in 2.4 release, along with a much more efficient implementation.

The recommendation, with many topics, in 2.3 release would be to turn that off: 

```
# Add entry timeout when broker tries to publish message to bookkeeper (0 to disable it).
managedLedgerAddEntryTimeoutSeconds=0
```

**Comment by ArtemShaban** [comment]
Thanks for clarifying)
