### ISSUE TITLE
Modify kubernetes generic deployment scripts in order to create services before any StatefulSet/Deployment/DaemonSet/Pod (follow K8S Recommandation)

### ISSUE THREAD

**Issue by guillaume-braibant** [apache/pulsar#4699]
**Problem and motivation**

Kubernetes recommends that, in multi-resources .yaml files, services bound to StatefulSet/Deployment/DaemonSet/Pods objects should be created first.

**Proposed solution**

In each .yaml file, declare the service before the Deployment/StatefulSet/DaemonSet/Pod object the service is bound to.

**Sources**

https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/#organizing-resource-configurations

> The resources will be created in the order they appear in the file. Therefore, it’s best to specify the service first, since that will ensure the scheduler can spread the pods associated with the service as they are created by the controller(s), such as Deployment.

**Comment by guillaume-braibant** [comment]
Pull request submitted : https://github.com/apache/pulsar/pull/4700

**Comment by sijie** [comment]
This is fixed by #4700
