### ISSUE TITLE
Add documentation for HDFS offloader

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#4704]
We need to add documentation for hdfs offloader before releasing 2.5.0

**Comment by sijie** [comment]
@congbobo184 can you help provide the documentation for HDFS offloader?

**Comment by sijie** [comment]
@Jennifer88huang please work with @congbobo184 adding the documentation for HDFS offloader. it is a blocker for 2.5.0.

**Comment by Jennifer88huang** [comment]
@sijie Got it, I've contacted with @congbobo184 on this issue last week, and @Anonymitaet is dealing with this issue this week.

**Comment by Anonymitaet** [comment]
@congbobo184 could you please provide technical inputs? Then I can review from the perspective of technical writing, thank you

**Comment by Anonymitaet** [comment]
Fixed in https://github.com/apache/pulsar/pull/5762.
