### ISSUE TITLE
Search bar on 2.4.0 documentation page doesn't work

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#4706]
**Describe the bug**
Search bar on 2.4.0 documentation page doesn't work

**To Reproduce**
1. Go to http://pulsar.apache.org/docs/en/standalone/
2. Enter a search term in the search box in the upper right hand corner
3. Hit enter, click on search icon
4. See no search results

**Expected behavior**
Expect a search box to pop up with search results

**Screenshots**

![Screen Shot 2019-07-10 at 2 19 39 PM](https://user-images.githubusercontent.com/35466513/61004345-a7ba6a80-a31a-11e9-8e9a-891045db4258.png)

**Comment by merlimat** [comment]
Dups of #4695
