### ISSUE TITLE
[Doc]Documentation on upgrading Pulsar is missing

### ISSUE THREAD

**Issue by yjshen** [apache/pulsar#4711]
Upgrading guide is missing, these are two items related to cluster upgrading:
-  https://github.com/apache/pulsar/commit/197e22c50ed4c09a550705259ddbb3e8eed10894
- https://github.com/apache/pulsar/blob/master/faq.md#is-there-any-sort-of-order-of-operations-or-best-practices-on-the-upgrade-procedure-for-a-geo-replicated-pulsar-cluster

Any plans on merging these two and update in the doc?

cc @sijie @Anonymitaet

**Comment by Anonymitaet** [comment]
@sijie  could we merge the PR (or do you need a review?)

**Comment by sijie** [comment]
@yjshen I will get my change move forward.

**Comment by yjshen** [comment]
https://ci.apache.org/projects/flink/flink-docs-master/ops/upgrading.html might be a reference as well.
