### ISSUE TITLE
Plusar Docker standalone on Mac idling at ~80% CPU core

### ISSUE THREAD

**Issue by youurayy** [apache/pulsar#4722]
**Describe the bug**
Pulsar 2.4 standalone in Docker uses very high CPU when not being used.

**To Reproduce**
Run the docker image as per the online instructions:
```
cd mydir
mkdir data
docker run -it \
  -p 6650:6650 \
  -p 8080:8080 \
  -v $PWD/data:/pulsar/data \
  apachepulsar/pulsar:2.4.0 \
  bin/pulsar standalone
```

**Expected behavior**
Pulsar should be idling at much lower CPU values.

**Screenshots**
![image](https://user-images.githubusercontent.com/588573/61178247-a9718000-a5f1-11e9-8c4d-19c221ffce91.png)

**Desktop (please complete the following information):**
 - OS: OS X High Sierra on 2.2 GHz Intel Core i7

**Additional context**
Docker Desktop 2.0.0.3 (31259) Engine: 18.09.2

**Comment by youurayy** [comment]
Running standalone from `apache-pulsar-2.4.0-bin.tar.gz` (without Docker), the java process is idling at ~21% CPU core.

**Comment by sijie** [comment]
@youurayy what is the memory and cpu you allocated to your Docker Machine?

**Comment by youurayy** [comment]
Hi sijie, 4 CPU and 2 GiB of RAM.

Increasing the RAM to 6 GiB, the Docker is at 55% of CPU core, Pulsar idling.

**Comment by sijie** [comment]
@youurayy yes the default `PULSAR_MEM` setting is `PULSAR_MEM=${PULSAR_MEM:-"-Xms2g -Xmx2g -XX:MaxDirectMemorySize=4g"}`. so when you need to make sure your docker machine is more than the JVM memory. Otherwise CPU might be used by the docker itself not by pulsar.

**Comment by youurayy** [comment]
Maybe this could be added to the page which describes how to run Pulsar in Docker.

Also, a lower idle than 21% (w/o Docker) and 55% (w/ Docker) CPU core would be really nice for laptops.

That said, it's a server-tier software w/ elements this project probably doesn't have control of (Zookeeper, Bookkeeper), so Idk about the priorities here.

**Comment by hpvd** [comment]
Would be nice to have some hardware recommodations / name the reqirements also for dev setups
- standalone Pulsar locally https://pulsar.apache.org/docs/en/standalone/
- standalone Pulsar in Docker  https://pulsar.apache.org/docs/en/standalone-docker/
- Pulsar with Helm on Kubernetes https://pulsar.apache.org/docs/en/kubernetes-helm/

for production there are already some startingpoints regarding AWS: 3x t2.small + 3x i3.4xlarge
https://pulsar.apache.org/docs/en/deploy-bare-metal/

**Comment by RobertLowe** [comment]
![Screen Shot 2021-08-03 at 12 18 26 AM](https://user-images.githubusercontent.com/601141/127957074-ae3d847e-9380-423b-816b-4c7948bf63af.png)

Idle's at 12%-15% for me. Acceptable. However, other containers idle at 0-2%. 

Purely curious, what is pulsar doing? Polling something? Loops? JVM stuff?

**Comment by hpvd** [comment]
yes this would be indeed interesting to know what is happening. It's not only about idle load and power consumption, but may be something like an additional load off set which would free some resources when possible to minimize...

@RobertLowe which version are you using?

**Comment by RobertLowe** [comment]
@hpvd latest docker `apachepulsar/pulsar`, so 2.8.0

**Comment by lhotari** [comment]
https://github.com/apache/pulsar/issues/9958#issuecomment-802616057 contains some explanation for high CPU usage while idling.

**Comment by tisonkun** [comment]
Closed as information delivered.
