### ISSUE TITLE
Pulsar SQL incompatible with Open JDK

### ISSUE THREAD

**Issue by helicopter18** [apache/pulsar#4723]
**Describe the bug**
Pulsar SQL incompatible with open JDK

**To Reproduce**

1. java -version openjdk version "1.8.0_202"

2. bin/pulsar sql-worker run

3. ERROR: ld.so: object '/usr/local/brokers-2.4/lib/presto/bin/procname/Linux-x86_64/libprocname.so' from LD_PRELOAD cannot be preloaded: ignored.
Presto requires an Oracle or OpenJDK JVM (found Azul Systems, Inc.)

**Comment by helicopter18** [comment]
**Describe the bug**
Pulsar SQL incompatible with open  JDK

**To Reproduce**

1. java -version openjdk version "1.8.0_202"

2. bin/pulsar sql-worker run

3. ERROR: ld.so: object '/usr/local/brokers-2.4/lib/presto/bin/procname/Linux-x86_64/libprocname.so' from LD_PRELOAD cannot be preloaded: ignored.
Presto requires an Oracle or OpenJDK JVM (found Azul Systems, Inc.)

**Comment by rfuerst87** [comment]
Looks like you are running pulsar using a JDK from Azul Systems rather than OpenJDK. Pulsar definitely works with OpenJDK. See docker images for example.

**Comment by sijie** [comment]
@helicopter18 are you using a 32-bit JVM? If so, can you change to use a 64-bit JVM?

See prestodb/presto#2807

**Comment by helicopter18** [comment]
@sijie   
**system infomation** 

- CentOS Linux release 7.6.1810 (Core)    Linux version 3.10.0-957.10.1.el7.x86_64

**java version**

openjdk version "1.8.0_202"
OpenJDK Runtime Environment (Zulu 8.36.0.1-CA-linux64) (build 1.8.0_202-b05)
OpenJDK 64-Bit Server VM (Zulu 8.36.0.1-CA-linux64) (build 25.202-b05, mixed mode)

bin/pulsar sql-worker run
ERROR: ld.so: object '/usr/local/brokers-2.4/lib/presto/bin/procname/Linux-x86_64/libprocname.so' from LD_PRELOAD cannot be preloaded: ignored.
Presto requires an Oracle or OpenJDK JVM (found Azul Systems, Inc.)

**Comment by sijie** [comment]
@helicopter18 is it possible for you to install a OpenJDK JVM and try it again?
