### ISSUE TITLE
New schemas should overwrite deleted schemas

### ISSUE THREAD

**Issue by rfuerst87** [apache/pulsar#4724]
**Describe the bug**
For what I observed deleting schemas currently just marks a schema deleted rather than actually delete it. Now for some reason schemas are simply ignored writing to a once-existing-but-now-deleted topic. Querying a schema for such a topic always returns a 404. The only workaround I found so far is to manually delete the schema in zookeeper. 

**To Reproduce**
1. Write some messages to topic `tenant/ns/topic` using an AvroSchema for example
2. Query schema: `pulsar-admin schemas get persistent://tenant/ns/topic` -> Result ok
3. Delete topic including schema: `pulsar-admin topics delete persistent://tenant/ns/topic -d`
4. Again write messages to `tenant/ns/topic` with same AvroSchema as above
5.  Query schema: `pulsar-admin schemas get persistent://tenant/ns/topic` -> Error 404 Not Found 

**Expected behavior**
Deleted schemas should be overwritten by new schemas.

**Desktop (please complete the following information):**
 - Pulsar version 2.4.0

**Additional context**
The same behavior can be observed when a topic is deleted automatically due to inactivity.

**Comment by congbobo184** [comment]
I hava already started to fix this bug :)
