### ISSUE TITLE
pulsar-function-go/log is not exist

### ISSUE THREAD

**Issue by freeznet** [apache/pulsar#4726]
**Describe the bug**
`pulsar-function-go/log` is not exist, trying to compile example failed.

**To Reproduce**
create a new pulsar go function and compile
```
go build -o examplepulsar helloFunc.go
```

get the error:

```
$ go build -o examplepulsar helloFunc.go
go: finding github.com/apache/pulsar/pulsar-function-go/log latest
go: finding github.com/apache/pulsar/pulsar-function-go latest
build command-line-arguments: cannot load github.com/apache/pulsar/pulsar-function-go/log: cannot find module providing package github.com/apache/pulsar/pulsar-function-go/log
```

**Comment by wolfstudy** [comment]
The `logtopic` use case as follows:

```
package main

import (
	"github.com/apache/pulsar/pulsar-function-go/log"
	"github.com/apache/pulsar/pulsar-function-go/pf"
)

func hello() {
	log.Info("hello.")
}

func main() {
	pf.Start(hello)
}
```

Two places to note:

-  `pulsar-function-go` depends on `pulsar-client-go` of `cgo` version, so make sure you have successfully built `pulsar-client-cpp` locally.
-  Please make sure your go version is greater than `go1.11`. 


The problem with your above is that you are manipulating the `go mod` error, you can re-import the project, and run `go mod download`.

**Comment by freeznet** [comment]
@wolfstudy thanks but i am still confusing.

- `pulsar-client-cpp` with version 2.4.0 was installed from deb release
- golang version is `go1.12.6`

following are my test files

- go.mod
```
module test-functions

go 1.12

require github.com/apache/pulsar/pulsar-function-go v0.0.0-20190713045844-6ff1bbae0fe2
```

- helloFunc.go

```
package main

import (
    "context"

    "github.com/apache/pulsar/pulsar-function-go/pf"
)

func HandleResponse(ctx context.Context, in []byte) ([]byte, error) {
    res := append(in, 110)
    return res, nil
}

func main() {
    pf.Start(HandleResponse)
}
```

after `go mod download` without any error, i ran `go build -o examplepulsar helloFunc.go` to build the pulsar function, and got error 

```
go: finding github.com/apache/pulsar/pulsar-function-go/log latest
go: finding github.com/apache/pulsar/pulsar-function-go latest
build command-line-arguments: cannot load github.com/apache/pulsar/pulsar-function-go/log: cannot find module providing package github.com/apache/pulsar/pulsar-function-go/log
```
which shows github.com/apache/pulsar/pulsar-function-go/log is not exist. you can check github's pulsar-function-go/log, also not exist.

To my understanding, i think `pulsar-function-go/log` is ignored by .gitignore.

**Comment by wolfstudy** [comment]
Specific issues can be viewed: [cmd/go: 'cannot find module for path' when importing from subdirectories
](https://github.com/golang/go/issues/26645)

The general reason is because you have problems executing `go mod init`

**Comment by freeznet** [comment]
@wolfstudy  i dont think this is a "cannot find module for path" issue. It is `pulsar-function-go/log` package not uploaded to git issue. if as you said, it is a problem i am executing `go mod init`,  then `pulsar-function-go/pf` package should also in the error message.

you can check this file list of `pulsar-function-go`, no `log` package here, i think this is why `cannot load github.com/apache/pulsar/pulsar-function-go/log`

```
rui at localhost in ~/playground/pulsar/pulsar-function-go (eb7ef89ca●)
$ ls -l
total 16
drwxr-xr-x   4 rui  staff   128  7 15 14:50 conf
drwxr-xr-x   7 rui  staff   224  7 15 14:50 examples
-rw-------   1 rui  staff   314  7 15 15:16 go.mod
-rw-r--r--   1 rui  staff  3448  7 15 14:50 go.sum
drwxr-xr-x   7 rui  staff   224  7 15 14:50 pb
drwxr-xr-x  12 rui  staff   384  7 15 14:50 pf
```

**Comment by freeznet** [comment]
https://github.com/apache/pulsar/blob/master/.gitignore#L37

the package name of `github.com/apache/pulsar/pulsar-function-go/log` just hit this .gitignore rule, by default the `log` package will be ignored and not commit to git.

**Comment by wolfstudy** [comment]
yes, you are right. `.gitignore` filtered this file, will fix it, thanks.
