### ISSUE TITLE
Can't get schema info with topic partition

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#4730]
**Describe the bug**

If topic is a partitioned topic, use topic name can get schema info correct. But if use topic partition (e.g. persistent://my-tenant/my-namespace/my-topic-partitiion-0), can't get a schema info.

**To Reproduce**
1.create a new partitioned topic
2.create producer with schema
3.use pulsar admin to get schema info with topic partition

**Expected behavior**

If use topic partition to get schema info should return the partitioned topic schema info.

**Comment by codelipenghui** [comment]
@congbobo184 please take a look this issue.

**Comment by sijie** [comment]
@codelipenghui nice catch!
