### ISSUE TITLE
Support for other schema name separators in pulsar SQL

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#4732]
Pulsar sql table schema using the same naming policy as pulsar namespace, but "/" will cause some problem with presto connection string.

Here is a snapshot of superset use pulsar sql as datasource
![image](https://user-images.githubusercontent.com/12592133/61216306-8d7bf480-a73f-11e9-9bf4-77fbfe0cec66.png)

>Note: Can be replace with presto://172.30.91.40:8081/pulsar?schema=public/default

Get table schema error in superset use pulsar sql as datasource
![image](https://user-images.githubusercontent.com/12592133/61216599-4f330500-a740-11e9-945f-9ec84b6bd027.png)

So i would like to suggest pulsar SQL table schema can support other named separators like "-" or "|"  will bring convenience to users.

I'm interested to add this feature.

**Comment by jerrypeng** [comment]
I have encountered this problem with Superset before but its because Superset doesn't escape quotes correctly.  Other SQL tools such as Tableau doesn't have this issue.
