### ISSUE TITLE
backlog retention policy doesn't work without subscriptions

### ISSUE THREAD

**Issue by freeart** [apache/pulsar#4740]
**Describe the bug**
When persistent topic never had subscriptions the published messages will deleted after few minutes with no reason

**To Reproduce**
1. publish to a new topic "persistent://public/default/my-topic" the message "test"
2. create reader from "persistent://public/default/my-topic"
3. get the message "test"
4. wait about 1 min
5. create reader from "persistent://public/default/my-topic"
6. topic is empty

**Expected behavior**
persistent topic should store messages in backlog by backlog retention policy
In my case is 
```bash
bin/pulsar-admin namespaces get-backlog-quotas public/default
```
```json
{
  "destination_storage" : {
    "limit" : 10737418240,
    "policy" : "producer_request_hold"
  }
}
```
**Desktop (please complete the following information):**
 - OS: Official docker from ```apachepulsar/pulsar:2.4.0```

**Comment by codelipenghui** [comment]
Backlog retention policy can affect the subscriber's backlog data retention. If you want to save data  whether or not you have a subscription, you can use:
```shell
bin/pulsar-admin namespace set-retention
```
Hope can help you.

**Comment by freeart** [comment]
@codelipenghui  Yes, I did. It doesn't work.
```bash
bin/pulsar-admin namespaces get-retention public/default
```
```json
{
  "retentionTimeInMinutes" : 0,
  "retentionSizeInMB" : 0
}
```

**Comment by freeart** [comment]
@codelipenghui thanks!
