### ISSUE TITLE
[docs] Add documentation for Functions develop: encryption

### ISSUE THREAD

**Issue by Jennifer88huang** [apache/pulsar#4753]
**Is your feature request related to a problem? Please describe.**
The encryption section in the Functions develop chapter is missing.

**Describe the solution you'd like**
Add encryption section, and complete the content in https://github.com/apache/pulsar/pull/4725

**Comment by sijie** [comment]
@Jennifer88huang @wolfstudy can you add the functions documentation for 2.5.0? It is better to make documentation as completed as possible in 2.5.0.

**Comment by Jennifer88huang** [comment]
Got it.

**Comment by wolfstudy** [comment]
> can you add the functions documentation for 2.5.0? It is better to make documentation as completed as possible in 2.5.0.

Sure, will add it.
