### ISSUE TITLE
get the list of schema should return non-deleted schemas

### ISSUE THREAD

**Issue by congbobo184** [apache/pulsar#4763]
#### Describe the bug

get schema list is all schema is last version schema

#### To Reproduce
https://github.com/apache/pulsar/blob/cc5f25bf1a97609ad065908b9a60866c382ee2e0/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java#L142

**Comment by congbobo184** [comment]
#4731 fixed it.

**Comment by sijie** [comment]
This is fixed by #4731
