### ISSUE TITLE
pulsar-io/file compile error: Cannot resolve method 'getNumWorkers()'

### ISSUE THREAD

**Issue by HeChuanXUPT** [apache/pulsar#4769]
**Describe the bug**
Cannot resolve method 'getNumWorkers()'

**Screenshots**
![image](https://user-images.githubusercontent.com/5425689/61588572-8b4ae780-abd0-11e9-8cea-fa1bf6fd1e73.png)

**Comment by sijie** [comment]
@HeChuanXUPT you need to configure lombok pluin in your IDE. See instructions at https://github.com/apache/pulsar#setting-up-your-ide

**Comment by HeChuanXUPT** [comment]
thanks
