### ISSUE TITLE
Rename the --destination-topic-name switch to --output for the Pulsar Admin CLI create source command

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#4772]
**Is your feature request related to a problem? Please describe.**
The sink create command has a --input switch, so this feature would bring consistency between the two commands in terms of specifying the topics.

**Describe the solution you'd like**
Rename the --destination-topic-name switch to --output switch for the Pulsar Admin CLI create source command 

**Describe alternatives you've considered**
N/A

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
