### ISSUE TITLE
[SQL] Optimize handling date related types in presto handler

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#4775]
**Is your feature request related to a problem? Please describe.**

Currently Presto is using `Schema` implementation to serialize and deserialize types. Schema stores `Date`, `Timestamp` and `Time` as epoch timestamp in the same way. So presto has to deserialize the serialized message back to java util `Date`, `Timestamp` and `Time`. There can be performance penalty due to object allocations. If it happens to be a bottleneck, we need to seek a solution to optimize it.

See discussions at : https://github.com/apache/pulsar/pull/4728#discussion_r305015611

**Comment by tisonkun** [comment]
Closed as stale.

The development of this initiative seems stalled and this thread doesn't contain too much information. If one wants to revive the proposal, please open a brand new thread.
