### ISSUE TITLE
[presto] pulsar presto connector doesn't have to configure zookeeper manually

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#4784]
**Is your feature request related to a problem? Please describe.**

Currently pulsar configures presto-worker by setting `pulsar.zookeeper-uri` in `conf/presto/catalog/pulsar.properties`. It would be great to deprecate this setting. Because the internal cluster configuration can be fetched from broker restful endpoint.

**Comment by jerrypeng** [comment]
@sijie I suggest keeping this setting as the url to the zookeeper cluster from the presto cluster might be different than the one brokers use to go the zookeeper.  I would suggest that by default if this config is not set, then we just fetch the zookeeper url from the brokers

**Comment by sijie** [comment]
Isn’t that a much bigger problem if broker is using a different zookeeper than bookies?

**Comment by jerrypeng** [comment]
Its the same zookeeper cluster but the url path to the zookeeper cluster might be different since users can run a presto cluster separately from the pulsar cluster

**Comment by jerrypeng** [comment]
The routing paths / urls can be set differently for different clusters for one reason or another, we should allow users to override if necessary

**Comment by sijie** [comment]
Can you use an example for this? 

If a different url or path (or just a different zk connect string) is used, that means the data is stored in a different bookkeeper cluster. And the only component writes data to it is the brokers. So you should be able to connect to brokers to fetch the connect string for accessing the bookkeeper cluster.

I can’t think of a case you need to override this setting. Can you please share an example?

I have a concern about this because it leads to inconsistency between data and metadata when you are asking people to configure two parts. You ask users to configure a broker url for accessing metadata such as schemas and partitions; but asking people to configure a zookeeper url for accessing the managed ledgers (the data part).

**Comment by jerrypeng** [comment]
@sijie for example if you have a pulsar cluster ( brokers, bookies, and zk) running inside a kubernetes cluster in AWS or anywhere, the internal hostname that brokers use for ZK can just be "zookeeper".  However, if my presto cluster is not within the kubernetes cluster, I will need an external ip or hostname to use to access both brokers and zk e.g., "a852ba4daae6b6598-1362313856.us-west-2.elb.amazonaws.com", given that they are exposed.  If we just use the hostname for zk provided by the broker, it will be wrong.

**Comment by jerrypeng** [comment]
@sijie I am thinking of a use case where you have a pulsar cluster ( brokers, bookies, and zk) running inside a kubernetes cluster, the internal hostname that brokers use for ZK and BK can just be "zk" or "bk.  However, if my presto cluster is not within the kubernetes cluster, I will need an external ip or hostname to access brokers, zk, and bookies.  Though I wonder if that is achievable since zk is used for service discovery for the bookies.

**Comment by sijie** [comment]
That's not achievable at this moment. because bk only has one advertised address for now. Unless we support bk having multiple advertised address, it is not feasible.

**Comment by jiazhai** [comment]
BP-38 has already implement part of the work, and included in latest bookkeeper release: 4.11
https://bookkeeper.apache.org/bps/BP-38-bookie-endpoint-discovery/

**Comment by tisonkun** [comment]
> Isn't that a much bigger problem if broker is using a different zookeeper than bookies?

I learned yesterday from a use case that the SQL worker will read from both `/ledgers` and `/managed-ledgers` on ZK namespace. And `ServiceConfiguration` has a `getBookkeeperMetadataStoreUrl` method to support separated configured `bookkeeperMetadataStoreUrl`, while Pulsar SQL still has only `zookeeper-uri` config (I extend it to `metadataUrl` in #18210).

This is another direction that we may introduce even a new configure as `ServiceConfiguration`'s `bookkeeperMetadataStoreUrl ` to handle the case.

**Comment by tisonkun** [comment]
Closed as stale. I'll open a new issue for any further proposals.
