### ISSUE TITLE
[pulsar-sql] export partitioned topic name

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#4785]
**Is your feature request related to a problem? Please describe.**
Currently, use pulsar sql to show tables list will return all topic partition names, integration with some UI tools can't select the partitioned topic, so suggest to add the partitioned topic to pulsar sql table list.

**Describe the solution you'd like**
Add the partitioned topic to pulsar sql table list while get table list.

**Comment by codelipenghui** [comment]
@sijie @jerrypeng 
We've been using pulsar SQL recently, will return a large table lists when users have a lot of partitions. Can we regard partition as a internal column and just return the partition topic name, while user query by partition can use like following:
```
SELECT * FROM "my-table" WHERE "__partition__" = 0
```
And Pulsar SQL push down the `"__partition__"`.

**Comment by jerrypeng** [comment]
+1 it also makes it easier for the user query every partition without specifying multiple topics

**Comment by sijie** [comment]
+1
