### ISSUE TITLE
[Doc] Add Schema Chapter

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#4789]
I plan to add Schema Chapter and several sections under it, the structure looks like this:

![Schema](https://user-images.githubusercontent.com/50226895/62191329-e38aa200-b3a5-11e9-9bda-db59981ca301.png)

Any thoughts?  @sijie @tuteng 

Welcome any comments.

**Comment by sijie** [comment]
^ @codelipenghui @congbobo184 does the proposed schema documentation structure looks good to you?

**Comment by Anonymitaet** [comment]
I've created the following PRs based on this structure:

Get Started Section: https://github.com/apache/pulsar/pull/4786

Understand Schema Section: https://github.com/apache/pulsar/pull/4759

**Comment by Anonymitaet** [comment]
All schema related PRs have been merged.
