### ISSUE TITLE
[documentation] Add documentation for replicated subscription

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#4793]
The replicated subscription documentation is missing.

**Comment by Huanli-Meng** [comment]
@sijie , some replicated subscription contents have been added to Pulsar docs (for releases from master to 2.5.0). What the missing documentation for replicated subscription here? a Tutorial or something else? 
![image](https://user-images.githubusercontent.com/48120384/84096342-4fad4c00-aa34-11ea-8311-947f0e620cd8.png)

**Comment by sijie** [comment]
We can close this issue now.
