### ISSUE TITLE
Expose schema in Pulsar source

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#4802]
**Is your feature request related to a problem? Please describe.**

When moving messages from Kafka (with schema registry) to Pulsar, we also need to carry the schema from source and store the schema to Pulsar. 

This issue serves as a master issue for exploring a solution to expose schema in Pulsar source and Pulsar Functions framework should leverage the schema information and handle schema evolution as well.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.

FYI @BewareMyPower this can be a valuable input to work Pulsar with Kafka.
