### ISSUE TITLE
A Pulsar producer should be able to produce messages of different schemas

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#4806]
**Is your feature request related to a problem? Please describe.**

When replicating data from Kafka (with schema registry) to Pulsar, it involves both uploading schemas and producing data to Pulsar. Also All the messages should also be replicated in order and there are no duplicates. The later requirement means we can only use one producer for replicating one Kafka partition to one Pulsar partition. However current Pulsar producer can only supports producing messages of one type of schema.

**Comment by yittg** [comment]
@sijie i have a similar scenario, a producer with AUTO_PRODUCE_BYTES schema(AVRO inner schema in schema registry) to send bytes encoded with AVRO.
After updating a new compatible schema, 
the producer will use older schema when sending bytes, even if they are encoded with newer schema,
on the contrary, a new producer will use newer schema when sending bytes encoded with older schema.

Is there any plan or design in progress?
Maybe we can drop the ability to control the schema version to the message level.
The producer would check the schema version of message and load it from the registry if it is different from the current producer.

**Comment by yittg** [comment]
@sijie i drafted a solution, would you have a look whether it make sense, thanks.

**Comment by yittg** [comment]
@sijie here i drafted a PIP for this feature, https://gist.github.com/yittg/56c6dedf7509f634ec7effc4f6f3631d#file-pip-md
@jiazhai @codelipenghui please help to review before sending it to the mailing list, thanks.

**Comment by yittg** [comment]
ping, any suggestions?

**Comment by codelipenghui** [comment]
@yittg  Great work!

Left few comments:
1. I think use `CommandGetOrCreateSchema` and `CommandGetOrCreateSchemaResponse`  is more accurate.
2. Similar to the reader cache, the writer cache can be handled in the same way.
3. Need to consider the batch message, messages of different schema versions cannot be contained in a batch.

**Comment by yittg** [comment]
@codelipenghui thanks for your comments.

> 1. I think use `CommandGetOrCreateSchema` and `CommandGetOrCreateSchemaResponse`  is more suitable.

it's ok to use a more direct and clear name;

> 2. Similar to the reader cache, the writer cache can be handled in the same way.

seems we do not need a writer cache like reader cache, we already have the schema itself;

> 3. Need to consider the batch message, messages of different schema versions cannot be contained in a batch.

you just knocked me, i missed it.

thanks  again.

**Comment by yittg** [comment]
@codelipenghui comments 1 & 3 fixed.

**Comment by sijie** [comment]
@yittg the proposal looks good to me. do you mind sending an email to dev@pulsar.apache.org mailing list to start a discussion thread to see if there are more comments from other people in the community?

**Comment by yittg** [comment]
@sijie sure.

**Comment by yittg** [comment]
@sijie This feature addressed in PIP-43 #5141  has been completed, pls close this issue.

**Comment by sijie** [comment]
This feature is implemented in PIP-43 (#5141).
