### ISSUE TITLE
Pulsar schema service should retry on concurrent schema updates

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#4807]
**Describe the bug**

Currently Pulsar doesn't retry on exceptions thrown when concurrently updating same schema. So the exception is propagated to Pulsar client directly. This is not a good experience for clients.

We should consider handling errors and retry it again.

Example exceptions are:

```
org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:297) ~[pulsar-client-api-2.5.0-2cc34afc0.jar:2.5.0-2cc34afc0]
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:88) ~[pulsar-client-all-2.5.0-2cc34afc0.jar:2.5.0-2cc34afc0]
```

**Comment by areebahmed04** [comment]
@sijie I'd like to work on this. How should I proceed?

**Comment by TC-oKozlov** [comment]
Hi, what's the recommended work around ? I'm getting this intermittently while trying to a 16-thread producer on 16-core machine, 1 time out of 2-3 runs

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
