### ISSUE TITLE
TYPO in C++ client producer method for processing failure case

### ISSUE THREAD

**Issue by easyfan** [apache/pulsar#4808]
**Describe the bug**
Inside file pulsar/pulsar-client-cpp/lib/ProducerImpl.cc, the method:
`void ProducerImpl::failPendingMessages(Result result) `
is designed for processing all the failure cases on publishing messages. As the exact result is given by parameter, so every registered message callback should be invoked with exactly the same result. But actually, In the final line of this method, the given code like this:
`    BatchMessageContainer::batchMessageCallBack(ResultTimeout, messageContainerListPtr, NULL);
`
Definitely, this a typo, as the method should report the callback with the GIVEN result stat, but not a CERTAIN result stat.

**Comment by easyfan** [comment]
I may submit my PR later if no any doubt.

**Comment by sijie** [comment]
This has been fixed by 4873
