### ISSUE TITLE
provide a convenient method for C++ client producer batch container

### ISSUE THREAD

**Issue by easyfan** [apache/pulsar#4809]
**Describe the bug**
Inside file: there is an inner structure `pulsar::BatchMessageContainer::MessageContainer,` which designed for some bridge purpose from an all-in-one message and each separated message callback. But so strange is that there is no convenient method for the structure to callback any given result directly. 

**Expected behavior**
Hope there is a convenient method for callbacking.

**Comment by easyfan** [comment]
I will submit PR later.

**Comment by jiazhai** [comment]
merged by #4885
