### ISSUE TITLE
Pulsar functions context potential OOM 

### ISSUE THREAD

**Issue by zubchenok** [apache/pulsar#4816]
Pulsar functions ContextImpl getProducer method caches created producers in a private hash map publishProducers and never voids any of them. Once producer goes to the map, it stays there forever.

If you start a function and it will publish to unbounded set of random topics, you'll finally get OOM.

It would be great to clean up the map based on the last producer access timestamp. Like 1 or 10 minutes after the last access. (I cannot offer a reasonable timeout, cause I don't know how expensive a producer and its creation in the context of function)

Applicable to Pulsar 2.4.0 and earlier.

**Comment by jerrypeng** [comment]
@zubchenok is there a reason why you are publishing to an unbounded set of random topics from a function?  That is not a typical use case.  We can perhaps add the capability to set a maximum number of topics any function publish to.

**Comment by zubchenok** [comment]
We use hundred thousands topics per day (topic per user session). I've already explained in detail our case in Pulsar community earlier.

I don't think this is reasonable to set such limit, because you can implement a smart cache or improve the functions API to publish messages without explicit creation a publisher per topic.

**Comment by jerrypeng** [comment]
> you can implement a smart cache

We can implement a cache for producers.  That closes "old" producers automatically

> improve the functions API to publish messages without explicit creation a publisher per topic.

This cannot be done in Pulsar in general.  With the current producer API, it one producer per topic

**Comment by jiazhai** [comment]
Add label `help wanted` for the contributor that want to contribute to this feature.
as above comments: "We can implement a cache for producers. That closes "old" producers automatically"

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
