### ISSUE TITLE
Pulsar schema api should respect to namespace level compatibility

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#4821]
**Describe the bug**
Currently the schema restful api is using `SchemaCompatibilityStrategy.FULL`

https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/SchemasResource.java#L268

It should use the compatibility strategy configured at namespace level.

**Comment by codelipenghui** [comment]
@congbobo184 please take a look this issue
