### ISSUE TITLE
Allow using a different identifier for message de-duplication

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#4833]
**Is your feature request related to a problem? Please describe.**

Currently the deduplication is based on producer name. The producer name is associated with a connection. Pulsar doesn't allow two concurrent connections with same producer name. In most of the cases, that is good enough.

However in connector use case, copying a Kafka partition to a Pulsar partition. We can use Kafka offset as the sequence id and the Kafka partition name as the unifier identifier. It is more convenient  if a producer can be allowed to use a customer id to configure, so we don't need to tied to a producer name.

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.
