### ISSUE TITLE
Acknowledged messages get redelivered after broker failure

### ISSUE THREAD

**Issue by Lanayx** [apache/pulsar#4849]
**Describe the bug**
I'm expecting redelivery of  the old acknowleged messages after one broker failure on default minikube helm installation with 2 brokers and 2 bookkeepers instead of 3 (to reduce resource usage).

**To Reproduce**
I'm testing basic pub/sub pulsar functionality in minikube. There is topic "public/default/test" with default settings. I'm using the same exclusive subscription "test-subscription" all them time. I register producer which produces 100 messages and consumer which consumes them and acks all messages one by one as they arrive, they run concurrently. I can run this many times and it works ok all the times. Then I want to test broker failure, I have 2 of them in local cluster and 1 proxy.

1. Run test before shutting down broker - everything works correctly, all messages produced and acknowledged
2. Shutdown one of brokers
3. Run the test again
4. After some reconnects are done internally - I get some random number of last messages from step1

**Expected behavior**
I expect that after messages are acknowledged successfully they never get into the same subscription again.

**Screenshots**
Here is a screenshot of messages from the 1st step that were received on 4th step
![image](https://user-images.githubusercontent.com/3329606/62114062-80721000-b2be-11e9-8fbd-65e19cfbff58.png)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Environment: minikube
 - Pulsar version: 2.4.0

**Additional context**

**Comment by sijie** [comment]
@Lanayx  this is a known behavior. see the discussion at #4118. #4118 is already created for tracking an improvement for this.

**Comment by Lanayx** [comment]
@sijie Hi, looks like this issue is not directly connected, since I see the same behavior with _Shared_ subscription configured as well

**Comment by sijie** [comment]
@Lanayx currently there is no acknowledges on "acks". so it is no guaranteed that the ack received by broker. If a broker crashes before it receives acks, broker will redeliver unacked messages. 

The behavior will be improved with "acknowledges" on "acks" with the development of transaction support.

**Comment by Lanayx** [comment]
@sijie In my case I write a .NET client and I explicitly ensure that each ack is received by proxy (since I'm testing in local kubernetes environment). Might it be that proxy didn't send acks immediately to broker?

**Comment by dao-jun** [comment]
closing due to stable
