### ISSUE TITLE
Generate publish time of message at broker side

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#4850]
**Is your feature request related to a problem? Please describe.**

Currently, publish time of message is generate at client side, while multiple client send messages to broker, we can't guarantee that the order of the messages is incremented by the publish time of the message.

Since Pulsar SQL can push down the "__publish_time__" predicate and use binary search to trim data, this may result in inaccurate data being trimmed.

So, if can support the generation of publish time on the broker side will bring benefits in this scene. Although topic owner(broker) can change, ledger id still can help guarantee that the trimmed data no data loss.

**Describe the solution you'd like**

Add support for generate publish time at broker side and add options to enable or disable this feature.

This issue is relate to #4823

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.
