### ISSUE TITLE
Cannot get a schema version

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#4854]
Schema version cannot be retrieved using the `pulsar-admin` CLI as below:

```
$ ./pulsar-admin schemas get testschematopic
{
  "name": "testschematopic",
  "schema": "",
  "type": "STRING",
  "properties": {
    "key1": "value1"
  }
}
```

@sijie could you please help?

**Comment by sijie** [comment]
@congbobo184 since you are working on the schema restful api, can you help with this issue? Currently we don't return schema version on get schema response. Hence the users don't know what is the schema version for this schema.

**Comment by congbobo184** [comment]
> @congbobo184 since you are working on the schema restful api, can you help with this issue? Currently we don't return schema version on get schema response. Hence the users don't know what is the schema version for this schema.

OK, I will take a look and fix this issues

**Comment by Anonymitaet** [comment]
@sijie @congbobo184 thank you
