### ISSUE TITLE
Uploading a Pulsar Function with pulsar-admin 2.2.1 to a 2.4.0 broker causes validation failure

### ISSUE THREAD

**Issue by grantwwu** [apache/pulsar#4855]
**Describe the bug**
If you use the pulsar-admin client bundled with the 2.2.1 client download with a 2.4.0 broker, uploading functions in a way that works with a 2.2.1 broker fails.

**To Reproduce**
Attempt to upload a function to a 2.4.0 broker with a 2.2.1 client.

Here's an example `function-config.yaml`:
```
tenant: "public"
namespace: "default"
inputs:
  - "persistent://public/default/public-fooBar"
name: "fooBar"
py: "/Users/grant.wu/fooBar.py"
className: "fooBar.FooBar"
autoAck: true
parallelism: 1
processing-guarantees: AT_LEAST_ONCE
```

Command used for upload looks like this:

```
$PULSAR_DIR/bin/pulsar-admin functions create --functionConfigFile "$(realpath function-config.yaml)"
```
where `$PULSAR_DIR` is the location of the extracted client tarball.

**Expected behavior**
Completes as normal, or some sort of incompatibility message is presented.

**Actual behavior**
Throws this error message:

```
The cpu allocation for the function must be positive
```

**Desktop (please complete the following information):**
 - OS: Reproduced on macOS Mojave (10.14.5).  Originally discovered on a Kubernetes (Linux) cluster.

**Additional context**
it seems strange to me that it would behave like this, especially because the documentation implies that CPU is irrelevant for non-docker runtimes.

I have noticed within the Pulsar broker logs that with a 2.4.0 client, the `cpu` field seems to be defaulted to `1.0`.

**Comment by sijie** [comment]
@grantwwu I think there are bunch of fields added to function config since 2.2.1. Hence 2.2.1 doesn't fill in those settings and 2.4.0 broker verifies those settings and it causes the issue as you described here. 

@jerrypeng can help you with this part.

**Comment by jerrypeng** [comment]
@grantwwu that is weird because I can submit a function via REST API:

```
curl  --request POST  -H "Content-Type: multipart/form-data" -F functionConfig='{"tenant":"public","namespace":"default","name":"test","className":"com.streamlio.datagen.DataGeneratorFunction","inputs":["input"], "output": "output", "parallelism":1, "runtime": "JAVA"};type=application/json' -F url='https://jerry-pulsar-test.s3-us-west-2.amazonaws.com/pulsar-functions-demos-data-gen-function-1.0-SNAPSHOT.jar;type=application/text' http://localhost:8080/admin/v3/functions/public/default/test
```

I didn't specify CPU and the default of "1" core is used.

I can try with a 2.2.1 client to see if there is some weird interaction

**Comment by jerrypeng** [comment]
@grantwwu I was able to reproduce the issue with 2.2.1 client.  I know what is going on.  I will create a patch

**Comment by grantwwu** [comment]
Additionally, using a 2.4.0 client seems to result in an HTTP 404 with a 2.2.1 broker.  Is there a written deprecation/compatibility policy anywhere?  Should I file a new bug for this?

**Comment by jerrypeng** [comment]
@grantwwu what command we you trying to issue for that?

**Comment by grantwwu** [comment]
Same command as listed, but with a 2.4.0 client and a 2.2.1 broker.

**Comment by tisonkun** [comment]
Since 2.1 ~ 2.4 has been end of life for a while, it's possible that the default value and null cases are handled properly.

Closed.

If it's still relevant to the maintained versions, we can always take this patch back for a fix.
