### ISSUE TITLE
Admin REST API resetCursorOnPosition endpoint missing position parameter in docs

### ISSUE THREAD

**Issue by grantwwu** [apache/pulsar#4856]
**Describe the bug**
http://pulsar.apache.org/en/admin-rest-api/#operation/resetCursorOnPosition does not describe how to actually supply the position.

**Additional context**

**Comment by congbobo184** [comment]
@grantwwu The document has now been added. Does this problem still exist? If there are no problems, we will close this issue.

**Comment by Huanli-Meng** [comment]
@congbobo184 could you please help provide the link/PR for the added document? Thanks.

**Comment by Anonymitaet** [comment]
@congbobo184 do you refer to this doc (https://pulsar.apache.org/admin-rest-api/?version=2.8.0&apiversion=v2#operation/resetCursor) ?

**Comment by congbobo184** [comment]
https://pulsar.apache.org/admin-rest-api/?version=2.8.0&apiversion=v2#operation/resetCursorOnPosition  this is right
