### ISSUE TITLE
Error: "Trying to subscribe with incompatible schema" even though isSchemaValidationEnforced=false 

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#4857]
**Describe the bug**

We are getting the error: `Trying to subscribe with incompatible schema`
even though:
`isSchemaValidationEnforced=false `
is set on the broker after deploying a new Pulsar Source and simple passthrough Pulsar Function. Here is the more detailed exception:

> java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$IncompatibleSchemaException: Trying to subscribe with incompatible schema
> 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_212]
> 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_212]
> 	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:700) ~[?:1.8.0_212]
> 	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) ~[?:1.8.0_212]
> 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_212]
> 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_212]
> 	at org.apache.pulsar.client.impl.ClientCnx.handleError(ClientCnx.java:582) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.common.api.PulsarDecoder.channelRead(PulsarDecoder.java:159) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at org.apache.pulsar.functions.runtime.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[java-instance.jar:2.4.0-streamlio-24]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
> Caused by: org.apache.pulsar.client.api.PulsarClientException$IncompatibleSchemaException: Trying to subscribe with incompatible schema
> 	at org.apache.pulsar.client.impl.ClientCnx.getPulsarClientException(ClientCnx.java:890) ~[java-instance.jar:2.4.0-streamlio-24]
> 	... 22 more

**To Reproduce**

1. Ensure that the schemas from the input topics and output topics have been deleted.
2. Ensure that the source and function with the information below have been deleted.
3. Deploy the Pulsar Source with the below configs:
```
{  "type": "source",
    "sourceType": "kafka",
    "runtimeFlags":"-Djava.security.krb5.conf=/pulsar/conf/krb5-dev.conf",
    "destinationTopicName": "persistent://example-tenant/ingest/example-kafka-topic",
    "configs": {
		"bootstrapServers": "kafka06.example.domain.com:9092,kafka07.example.domain.com:9092,kafka08.example.domain.com:9092",
		"consumerConfigProperties": {
			"auto.offset.reset": "latest",
			"sasl.jaas.config": "com.sun.security.auth.module.Krb5LoginModule required doNotPrompt=true\nuseTicketCache=false serviceName=\"kafka\" principal=\"pulsar_runtime@EXAMPLE.DOMAIN.COM\"\nuseKeyTab=true keyTab=\"/pulsar/conf/auth/pulsar_runtime_dev.keytab\" client=true;",
			"sasl.kerberos.service.name": "kafka",
			"security.protocol": "SASL_PLAINTEXT"
		},
		"groupId": "pulsar-example-tenant-example-kafka-topic-group",
		"topic": "example-kafka-topic"
	},
    "namespace": "ingest",
    "name": "kafka-example-kafka-topic-source",
    "tenant": "example-tenant"
}
```
4. Deploy the Pulsar function with the configs below:
```
{
    "type": "function",
    "tenant": "example-tenant",
    "namespace": "ingest",
    "name": "example-kafka-topic-SimplePassthroughFunction",
    "artifactPathOrUrl": "http://repository.domain.com/path/to/jar-build-129875312.jar",
    "className": "com.path.to.pulsar.functions.SimplePassthroughFunction",
    "inputs": [
        "persistent://example-tenant/ingest/example-kafka-topic"
    ],
    "output": "persistent://feeds/example-namespace/example-kafka-topic",
    "logTopic": "persistent://example-tenant/ingest/function-logs"
}
```

The same problem occurs if the tenant and namespace are all set to public/default.

All of our functions and sources just take a string and return a string, so there's nothing complex in terms of the schemas.

**Expected behavior**
We expect the Pulsar Source to collect data from our Kafka topic without error. We also expect the function to process data from our Pulsar Source without error.

**Screenshots**

We've noticed that when we deploy the passthrough function and start querying its status, we initially notice an error that states "UNAVAILABLE: io exception," like this:

```
$ pulsar-admin functions status --fqfn public/default/example-kafka-topic-SimplePassthroughFunction
{
  "numInstances" : 1,
  "numRunning" : 1,
  "instances" : [ {
    "instanceId" : 0,
    "status" : {
      "running" : true,
      "error" : "",
      "numRestarts" : 0,
      "numReceived" : 0,
      "numSuccessfullyProcessed" : 0,
      "numUserExceptions" : 0,
      "latestUserExceptions" : [ ],
      "numSystemExceptions" : 0,
      "latestSystemExceptions" : [ ],
      "averageLatency" : 0.0,
      "lastInvocationTime" : 0,
      "workerId" : "c-pulsar-example.cluster.com-8080"
    }
  } ]
}
$ pulsar-admin functions status --fqfn public/default/example-kafka-topic-SimplePassthroughFunction
{
  "numInstances" : 1,
  "numRunning" : 0,
  "instances" : [ {
    "instanceId" : 0,
    "status" : {
      "running" : false,
      "error" : "UNAVAILABLE: io exception",
      "numRestarts" : 0,
      "numReceived" : 0,
      "numSuccessfullyProcessed" : 0,
      "numUserExceptions" : 0,
      "latestUserExceptions" : [ ],
      "numSystemExceptions" : 0,
      "latestSystemExceptions" : [ ],
      "averageLatency" : 0.0,
      "lastInvocationTime" : 0,
      "workerId" : "c-pulsar-example.cluster.com-8080"
    }
  } ]
}
$ pulsar-admin functions status --fqfn public/default/example-kafka-topic-SimplePassthroughFunction
{
  "numInstances" : 1,
  "numRunning" : 0,
  "instances" : [ {
    "instanceId" : 0,
    "status" : {
      "running" : false,
      "error" : "",
      "numRestarts" : 1,
      "numReceived" : 0,
      "numSuccessfullyProcessed" : 0,
      "numUserExceptions" : 0,
      "latestUserExceptions" : [ ],
      "numSystemExceptions" : 0,
      "latestSystemExceptions" : [ ],
      "averageLatency" : 0.0,
      "lastInvocationTime" : 0,
      "workerId" : "c-pulsar-example.cluster.com-8080"
    }
  } ]
}
```

**Environment:**
 - OS: `docker standalone run -it --net=host -v /etc/pulsar:/pulsar/conf -v /data/provisioning:/pulsar/data  apachepulsar/pulsar-all:2.3.2 /bin/bash`
- Pulsar version: Using Pulsar 2.3.2.

**Additional context**
We experienced this error also with a sink.

**Comment by sijie** [comment]
@devinbost 

I think `isSchemaValidationEnforced` is only applied for producers without schema connecting to a topic with schema. We introduced this setting to allow non-java clients (without schema support) still being able to produce messages to the topic.

The error you described is a subscription error. It means a consumer with schema attempts to consume messages from a topic without schema.

In your case,

- the Kafka source is transferring bytes from a Kafka topic to a Pulsar topic. It will create a pulsar topic `persistent://example-tenant/ingest/example-kafka-topic` without schema.
- The function is consuming from the Pulsar topic `persistent://example-tenant/ingest/example-kafka-topic` with a string schema. (because the schema is inferred from the function input type).

Hence the function will fail to start because the function attempts to consume `persistent://example-tenant/ingest/example-kafka-topic` with a string schema.

---

There are a few workarounds:

1) you can precreate the topic with `String` schema. so that Kafka source is able to produce with `isSchemaValidationEnforced` setting to true.

2) you can disable schema compatibility check by setting the namespace's schema compatibility check policy to `None`: `bin/pulsar-admin namespaces set-schema-autoupdate-strategy -d tenant/namespace`.

---

We can also consider extending `isSchemaValidationEnforced` for disabling schema validation completely.

**Comment by devinbost** [comment]
@sijie Thanks for the information. We will first try pre-creating the topic with a String schema to work around the issue. I'll update this issue if we run into further problems.

**Comment by devinbost** [comment]
@sijie We got the same error after trying both workarounds.

**Comment by sijie** [comment]
@devinbost interesting. there was a similar issue raised in #4864 . the folk got around this issue by precreating the topic with String schema.

**Comment by sijie** [comment]
@devinbost what version are you using? 2.3.2? I am wondering if this is related to this issue #4669. 

Have you tried pre-creating a new topic with String schema?

**Comment by devinbost** [comment]
@sijie We created the String schemas. Do we also need to do something to create the topics?

**Comment by sijie** [comment]
@devinbost no. did you create the String schema on a brand new topic? or an existing topic (with deleted schemas)?

**Comment by sijie** [comment]
@devinbost I wrote a test to produce your issue. 

https://gist.github.com/sijie/297e3de42f8184350e651f11db91408b

The test basically does followings:

"Kafka Topic" -> Kafka Source -> "Pulsar Topic" -> Exclamation Function -> "Pulsar Output Topic".

1. It creates a Kafka topic
2. It creates a Pulsar output topic as the output topic for Exclamation Function
3. *It registers a STRING schema for "Pulsar Topic"*
4. It creates a Kafka source and wait until it is running
5. It creates a Exclamation function  and wait until it is running
6. Produce messages to "Kafka Topic"
7. Receive messages from "Pulsar Output Topic".

If I don't do step 3, the Exclamation Function will fail due to "Subscribe with Incompatible Schema".

If I do step 3, the whole pipeline is working.

Hence I think if you register the `Schema.STRING` for the input topic for your function, it should get around the issue.

**Comment by devinbost** [comment]
@sijie Is there a way to create the topic from the CLI? When we run these commands:

$ docker standalone run -it --net=host -v /etc/pulsar:/pulsar/conf -v /data/provisioning:/pulsar/data apachepulsar/pulsar-all:2.3.2 /bin/bash

$bin/pulsar-admin topics create persistent://example-tenant/ingest/example-kafka-topic

We get this error:

> Expected a command, got create
> 
> Exception in thread "main" com.beust.jcommander.ParameterException: Asking description for unknown command: null
> 	at com.beust.jcommander.JCommander.getCommandDescription(JCommander.java:1003)
> 	at com.beust.jcommander.JCommander.usage(JCommander.java:988)
> 	at com.beust.jcommander.JCommander.usage(JCommander.java:980)
> 	at com.beust.jcommander.JCommander.usage(JCommander.java:972)
> 	at org.apache.pulsar.admin.cli.CmdBase.run(CmdBase.java:49)
> 	at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:189)
> 	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:231)

**Comment by devinbost** [comment]
We then get this:

`$ bin/pulsar-admin schemas upload  persistent://example-tenant/ingest/example-kafka-topic --filename /pulsar/data/path/to/schema-file.json `

`$ bin/pulsar-admin schemas get persistent://example-tenant/ingest/example-kafka-topic`

> HTTP 404 Not Found
> 
> Reason: HTTP 404 Not Found

**Comment by david-streamlio** [comment]
@devinbost Were you able to run the test provided by @sijie to confirm that it works?

I think the create topic command below, fails because the tenant and namespace weren't created first. 
`$ bin/pulsar-admin topics create persistent://example-tenant/ingest/example-kafka-topic`

**Comment by sijie** [comment]
@devinbost 

`topics create` is only available since 2.4.0. 

in your example, you don't need to create the topic since it is a non-partitioned topic. A non-partitioned topic will be create automatically when producer or consumer connects.

you can do this:

1. bin/pulsar-admin tenants create example-tenant
2. bin/pulsar-admin namespaces create example-tenant/ingest
3. bin/pulsar-admin schemas upload 

Can you share the content of `persistent://example-tenant/ingest/example-kafka-topic`?

**Comment by sijie** [comment]
regarding uploading schema, I have the steps as the followings for your reference:

```
$ cat schema.json
{
    "type": "STRING",
    "schema": "",
    "properties": {}
}
$ bin/pulsar-admin schemas upload -f schema.json test-string-schema
$ bin/pulsar-admin schemas get test-string-schema
{
  "name": "test-string-schema",
  "schema": "",
  "type": "STRING",
  "properties": {}
}
```

**Comment by sijie** [comment]
@devinbost any luck?

**Comment by devinbost** [comment]
> @devinbost Were you able to run the test provided by @sijie to confirm that it works?
> 
> I think the create topic command below, fails because the tenant and namespace weren't created first.
> `$ bin/pulsar-admin topics create persistent://example-tenant/ingest/example-kafka-topic`

We actually did create the tenant and namespace already, so that's not the issue. 

We will keep you guys posted.

**Comment by devinbost** [comment]
I think that's appropriate. I'll post another update if we experience this issue again.

**Comment by FFC-SystemAdmin** [comment]
Hello, I have the same problem with 2.4.2

I am writing a function to listen for input on a topic set with a schema:
`"schemaInfo": {
    "name": "ffc-liveoccupancydata",
    "schema": {
      "type": "record",
      "name": "LIVEOCCUPANCYDATA",
      "namespace": "public.default",
      "fields": [
        {
          "name": "DataID",
          "type": "long"
        },
        {
          "name": "CameraSerial",
          "type": [
            "null",
            "string"
          ]
        },
        {
          "name": "Timestamp",
          "type": "long"
        },
        {
          "name": "OutValue",
          "type": "long"
        },
        {
          "name": "Create_at",
          "type": [
            "null",
            "string"
          ]
        },
        {
          "name": "BranchCode",
          "type": [
            "null",
            "string"
          ]
        },
        {
          "name": "UploadedLocalDateTime",
          "type": [
            "null",
            "string"
          ]
        },
        {
          "name": "UploadedUTCDateTime",
          "type": [
            "null",
            "string"
          ]
        },
        {
          "name": "UtcDateTime",
          "type": [
            "null",
            "string"
          ]
        },
        {
          "name": "InValue",
          "type": "long"
        },
        {
          "name": "Serial",
          "type": [
            "null",
            "string"
          ]
        }
      ]
    },
    "type": "JSON",
    "properties": {}
  }
`

Please advice, thanks.

**Comment by devinbost** [comment]
@FFC-SystemAdmin 
We've noticed that it seems like this issue may occur depending on the order in which subscriptions are made (e.g. from sink to source vs source to sink.) We've had more success going from sink to source (meaning connecting the sink to the upstream function, then connecting that function to the function upstream from it . . . until you connect an upstream function to the source.) 
I don't know what your flow looks like though.
