### ISSUE TITLE
MacOS clang/llvm compiler imcompatible code in Unit test case BasicEndToEndTest.cc

### ISSUE THREAD

**Issue by easyfan** [apache/pulsar#4871]
**Describe the bug**
There are 2 compiler errors while compiling BasicEndToEndTest.cc under MacOS with clang/LLVM:
"variable length array of non-POD element type of Consumer"

Basically, this is introduced by announcing an array of elements, with a variable length.

**To Reproduce**
1. Try build BasicEndToEndTest.cc under clang/llvm

**Expected behavior**
build BasicEndToEndTest.cc pass under clang/llvm, with no error report.

**Comment by easyfan** [comment]
Assign to me please, will commit later.

**Comment by easyfan** [comment]
Here is the official announcement of this incompatible issue: http://clang.llvm.org/compatibility.html#vla

**Comment by sijie** [comment]
@easyfan can you submit a pull request for that?

**Comment by easyfan** [comment]
@sijie already done. See https://github.com/apache/pulsar/pull/4878 please
