### ISSUE TITLE
Not matching schema while using subrecords for Python client

### ISSUE THREAD

**Issue by chariot1498** [apache/pulsar#4874]
In this piece of code when I print schema of Example it shows the type of sub without null but when I do producer send or encode it throws value error 

ValueError: <__main__.test_complex.<locals>.MySubRecord object at 0x1022fc790> (type <class '__main__.test_complex.<locals>.MySubRecord'>) do not match ['null', {'type': 'record', 'name': 'MySubRecord', 'fields': [{'name': 'a', 'type': 'string'}]}]

I thought doing required = True should have solved it but though in example schema it disappears but while doing producer send it still gives error 

class MySubRecord(Record):
    a = String(required = True)

class Example(Record):
    x = String(required=True)
    sub = MySubRecord(required=True)

#Connect to pulsar
client = pulsar.Client('pulsar://localhost:6650')
producer = client.create_producer(
                    topic='tes',
                    schema=AvroSchema(Example) )

**Comment by Choqs** [comment]
Same issue here, producer send produce the bellow error, while everything seems to be ok:

`exception=ValueError("<micro_service.schema.ProcedureSchema object at 0x7f0e060a8cf8> (type <class 'micro_service.schema.ProcedureSchema'>) do not match ['null', {'type': 'record', 'name': 'ProcedureSchema', 'fields': [{'name': 'procedure_id', 'type': ['null', 'string']}, {'name': 'user_id', 'type': ['null', 'string']}]}]",)>)`

where ProcedureSchema is a sub record. Any idea ?

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Python client has been permanently moved to https://github.com/apache/pulsar-client-python. If it's still relevant, please open an issue there.
