### ISSUE TITLE
Delayed messages support any time?

### ISSUE THREAD

**Issue by hadoop835** [apache/pulsar#4876]
Delayed messages support any time?

**Comment by sijie** [comment]
@hadoop835 in theory the current implementation supports arbitrary time. However it is limited by the memory. Here is a proposed hash-wheel based implementation which can support this well. See details at https://github.com/apache/pulsar/wiki/PIP-26%3A-Delayed-Message-Delivery

**Comment by sijie** [comment]
Close this issue since it was answered.
