### ISSUE TITLE
Update Functions state documentation for Python

### ISSUE THREAD

**Issue by jonb-streamlio** [apache/pulsar#4898]
Pulsar Functions documentation at http://pulsar.apache.org/docs/en/functions-state/ needs to be updated to note that Python functions support state, and to provide examples of how to use state with Python.

**Comment by Jennifer88huang** [comment]
@jonb-streamlio Thank you very much for reporting the issue. We've update the docs accordingly, see http://pulsar.apache.org/docs/en/next/functions-develop/#state-storage
Could you please help confirm? If it fixes this issue, we can close it. Any issue, feel free to comment.

**Comment by Jennifer88huang** [comment]
I think we can close the issue now. @jonb-streamlio If you have any further issue on this, feel free to contact us.
