### ISSUE TITLE
Dispatch throttling might prevent consumers from receiving messages

### ISSUE THREAD

**Issue by massakam** [apache/pulsar#4900]
The other day, a problem that backlog messages of a specific partitioned topic were not reduced occured in our Pulsar cluster. When we checked the stats of that topic, delivery of messages to the consumers was stopping on three partitions owned by a particular broker.

The following files are the stats of the partitions in problem. The subscription for which message delivery was stopping is `90cluster1`.

- partition-1
  - [stats-1.txt](https://github.com/apache/pulsar/files/3470850/stats-1.txt)
  - [stats-internal-1.txt](https://github.com/apache/pulsar/files/3470851/stats-internal-1.txt)
  - [info-internal-1.txt](https://github.com/apache/pulsar/files/3470852/info-internal-1.txt)
- partition-5
  - [stats-5.txt](https://github.com/apache/pulsar/files/3470853/stats-5.txt)
  - [stats-internal-5.txt](https://github.com/apache/pulsar/files/3470857/stats-internal-5.txt)
  - [info-internal-5.txt](https://github.com/apache/pulsar/files/3470864/info-internal-5.txt)
- partition-9
  - [stats-9.txt](https://github.com/apache/pulsar/files/3470868/stats-9.txt)
  - [stats-internal-9.txt](https://github.com/apache/pulsar/files/3470869/stats-internal-9.txt)
  - [info-internal-9.txt](https://github.com/apache/pulsar/files/3470871/info-internal-9.txt)

Here is the broker thread dump: [threaddump.txt](https://github.com/apache/pulsar/files/3470872/threaddump.txt)

When we changed the broker log level to DEBUG, the following messages were continuously logged:
```
11:11:18.652 [pulsar-io-21-57] DEBUG o.a.p.b.s.p.PersistentDispatcherSingleActiveConsumer - [persistent://tenant/global/ns/partitioned-topic-partition-9 / 90cluster1] message-read exceeded subscription message-rate 15000/15360000, schedule after a 1000
11:11:18.652 [pulsar-io-21-59] DEBUG o.a.p.b.s.p.PersistentDispatcherSingleActiveConsumer - [persistent://tenant/global/ns/partitioned-topic-partition-1 / 90cluster1] message-read exceeded subscription message-rate 15000/15360000, schedule after a 1000
11:11:18.652 [pulsar-io-21-58] DEBUG o.a.p.b.s.p.PersistentDispatcherSingleActiveConsumer - [persistent://tenant/global/ns/partitioned-topic-partition-5 / 90cluster1] message-read exceeded subscription message-rate 15000/15360000, schedule after a 1000
11:11:19.652 [pulsar-io-21-60] DEBUG o.a.p.b.s.p.PersistentDispatcherSingleActiveConsumer - [persistent://tenant/global/ns/partitioned-topic-partition-9 / 90cluster1] message-read exceeded subscription message-rate 15000/15360000, schedule after a 1000
11:11:19.652 [pulsar-io-21-61] DEBUG o.a.p.b.s.p.PersistentDispatcherSingleActiveConsumer - [persistent://tenant/global/ns/partitioned-topic-partition-5 / 90cluster1] message-read exceeded subscription message-rate 15000/15360000, schedule after a 1000
11:11:19.652 [pulsar-io-21-62] DEBUG o.a.p.b.s.p.PersistentDispatcherSingleActiveConsumer - [persistent://tenant/global/ns/partitioned-topic-partition-1 / 90cluster1] message-read exceeded subscription message-rate 15000/15360000, schedule after a 1000
```

This means that the delivery rate for `90cluster1` exceeded the threshold of dispatch throttling (15000msg/s or 15360000bytes/s). But the actual delivery rate was 0.

This problem was resolved by restarting the broker. This might be a bug of dispatch throttling.

**Pulsar version:** 2.2.1

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
