### ISSUE TITLE
[Dashboard] Enable communication to broker over https, add ca-cert verify

### ISSUE THREAD

**Issue by shiv4289** [apache/pulsar#4906]
**Is your feature request related to a problem? Please describe.**
Dashboard should be able to talk to broker over https. Currently, collector in the dashboard does not accept verify param in requests.

**Describe the solution you'd like**
Allow to mount cert to a path in docker container at a specific location, then use the path in verify cert param in python request of collector

**Describe alternatives you've considered**
No alternative

**Additional context**
Collector.py

> def get(base_url, path):
>     if base_url.endswith('/'): path = path[1:]
>     return requests.get(base_url + path,
>                         headers=http_headers,
>                         proxies=http_proxyes,
>                         ).json()

**Comment by dockerzhang** [comment]
Is there any plan for this issue recently?

**Comment by shiv4289** [comment]
@dockerzhang I have started using pulsar-manager. So this is not planned. Sorry for the delayed response.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant in maintained versions.
