### ISSUE TITLE
admin.topics.createNonPartitionedTopic issue when disable allowAutoTopicCreation

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#4908]
User can set `allowAutoTopicCreation` to disable topic auto create,  at this time, user use admin client admin.topics.createNonPartitionedTopic to create each partition. 
In method [`internalCreateNonPartitionedTopic`](
https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L397),
It firstly call `validateTopicOwnership(topicName, authoritative)`, then do topic create.
If validate ownership failed(because of admin connect to a non-topic-owner broker), this command will fail, and user not able to create the wanted topic. 

We should add the lookup logic in command `createNonPartitionedTopic`, to make sure topic creation success.

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.
