### ISSUE TITLE
The requested URL /api/admin/org/apache/pulsar/client/admin/ClientConfiguration was not found on this server.

### ISSUE THREAD

**Issue by huangdx0726** [apache/pulsar#4914]
1. Go to 'http://pulsar.apache.org/docs/en/admin-api-overview'
2. Scroll down to 'Java admin client' and click ClientConfiguration link
3. 404 not found error is displayed "The requested URL /api/admin/org/apache/pulsar/client/admin/ClientConfiguration was not found on this server."

**Comment by Jennifer88huang** [comment]
@huangdx0726  Thank you very much for raising the issue. 
I've checked and found the link is indeed invalid. 
![image](https://user-images.githubusercontent.com/47805623/62687989-735dcb00-b9fa-11e9-80de-9839db8534d2.png)
I can trace the link to `http://pulsar.apache.org/api/admin/`, and find the `org.apache.pulsar.client.admin` package, yet not the `ClientConfiguration`
![image](https://user-images.githubusercontent.com/47805623/62688049-9b4d2e80-b9fa-11e9-8b06-2e92c21c98e8.png)

@sijie @jiazhai Could you give some help on this?

**Comment by huangdx0726** [comment]
@Jennifer88huang   and copied the example is not working yet. it's displayed no class ClientConfiguration and no Constructor PulsarAdmin(java.net.URL,ClientConfiguration). it's the same error of 2.4 or 2.3.2.is it woring on the early version?

**Comment by huangdx0726** [comment]
i see this Pulsar client admin API and fix the example, like this:
String url = "http://localhost:8080";
// Pass auth-plugin class fully-qualified name if Pulsar-security enabled
        String authPluginClassName = "com.org.MyAuthPluginClass";
// Pass auth-param if auth-plugin class requires it
        String authParams = "param1=value1";
        boolean useTls = false;
        boolean tlsAllowInsecureConnection = false;
        String tlsTrustCertsFilePath = null;
        ClientConfigurationData config = new ClientConfigurationData();
        config.setAuthPluginClassName(authPluginClassName);
        config.setUseTls(useTls);
        config.setTlsAllowInsecureConnection(tlsAllowInsecureConnection);
        config.setTlsTrustCertsFilePath(tlsTrustCertsFilePath);
        PulsarAdmin admin = new PulsarAdmin(url, config);

OR 

String url = "http://localhost:8080";
// Pass auth-plugin class fully-qualified name if Pulsar-security enabled
        String authPluginClassName = "com.org.MyAuthPluginClass";
// Pass auth-param if auth-plugin class requires it
        String authParams = "param1=value1";
        boolean useTls = false;
        boolean tlsAllowInsecureConnection = false;
        String tlsTrustCertsFilePath = null;
        PulsarAdmin admin = new PulsarAdminBuilderImpl()
                .authentication(authPluginClassName,authParams)
                .serviceHttpUrl(url)
                .tlsTrustCertsFilePath(tlsTrustCertsFilePath)
                .allowTlsInsecureConnection(tlsAllowInsecureConnection)
                .build();
it's working.
@Jennifer88huang @sijie @jiazhai

**Comment by Jennifer88huang** [comment]
@huangdx0726 Thank you very much for your information. 
I've checked the `http://pulsar.apache.org/api/admin/org/apache/pulsar/client/admin/PulsarAdmin.html`, and found what you have fixed is correct. Yes, currently, it seems that the `ClientConfigurationData` string is adopted, while `ClientConfiguration` string is not defined anywhere.

So the solution is to replace `ClientConfiguration` with `ClientConfigurationData` in the doc description and two examples.

@sijie Could you please help confirm whether I've understood it correctly? If yes, we can update the doc accordingly.

**Comment by sijie** [comment]
@Jennifer88huang @huangdx0726 

We should change the example to the later form that @huangdx0726 commented, but use "PulsarAdmin.builder()". The link to ClientConfiguration should be changed to PulsarAdminBuilder.

@Jennifer88huang when we are fixing the issue, we might consider fixing all the similar examples in the documentation.

```
String url = "http://localhost:8080";
// Pass auth-plugin class fully-qualified name if Pulsar-security enabled
String authPluginClassName = "com.org.MyAuthPluginClass";
// Pass auth-param if auth-plugin class requires it
String authParams = "param1=value1";
boolean useTls = false;
boolean tlsAllowInsecureConnection = false;
String tlsTrustCertsFilePath = null;
PulsarAdmin admin = PulsarAdmin.builder()
.authentication(authPluginClassName,authParams)
.serviceHttpUrl(url)
.tlsTrustCertsFilePath(tlsTrustCertsFilePath)
.allowTlsInsecureConnection(tlsAllowInsecureConnection)
.build();
```

**Comment by Jennifer88huang** [comment]
@sijie Sure, got it, thanks for your confirmation.
@huangdx0726 Would you like to try?

**Comment by huangdx0726** [comment]
my pleasure。
