### ISSUE TITLE
Add more config for auto-topic-creation

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#4926]
**Is your feature request related to a problem? Please describe.**
Curently the partitioned-topic and non-partitioned topic is a little confuse for users. in PR #3450 we add config for auto-topic-creation.
We could leverage this config to provide some more config for auto-topic-creation:
e.g.
- auto create what type of topic: partitioned/non-partitioned.
- if auto create partitioned topic, what is the default partition number.

With PR #4764 and #4883, we could create partitioned topic with 1 partition number, it would be good to make partitioned topic as default topic, it would be easy for user to understand and use.

**Comment by sijie** [comment]
This will be fixed by #4963

**Comment by addisonj** [comment]
This looks to be all fixed now? Seems like this should be closed

**Comment by sijie** [comment]
Fixed by #4963
