### ISSUE TITLE
define subscription expiration on consumer creation

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#4929]
**Describe the solution you'd like**
It could be very interesting to configure:

```
# How long to delete inactive subscriptions from last consuming
# When it is 0, inactive subscriptions are not deleted automatically
subscriptionExpirationTimeMinutes=0

# Enable subscription message redelivery tracker to send redelivery count to consumer (default is enabled)
subscriptionRedeliveryTrackerEnabled=true

# How frequently to proactively check and purge expired subscription
subscriptionExpiryCheckIntervalInMinutes=
```

as consumer configuration on its creation.

**Comment by tisonkun** [comment]
Closed as stale and no one works on it. Please create a new issue if it's still relevant to the maintained versions.

I think this proposal is better to go to the dev@ mailing list with a technical design.
