### ISSUE TITLE
Retrieve schema instance from schema info for type 'NONE' 

### ISSUE THREAD

**Issue by pouledodue** [apache/pulsar#4937]
```
pulsar-admin functions trigger --fqfn test/app/func1 --trigger-value yoshi

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException:
 Retrieve schema instance from schema info for type 'NONE' is not supported yet

Reason: HTTP 500 Internal Server Error
```

What am I doing wrong?

**Comment by sijie** [comment]
@pouledodue interesting. Can you describe more about this case?

- what is the function?
- does the topic `test/app/func` exist?

**Comment by devinbost** [comment]
@pouledodue What was the resolution on this?

**Comment by gh777777** [comment]
> @pouledodue What was the resolution on this?
Me too! So what was the resolution on this? The issue still exists in pulsar v2.5.1. After deplying a 3-node pulsar cluster, I tried several times to create, trigger and delete the example python function (examples/python_examples/exclamation_function.py). Then this error ocurred and I can not run the function any more, even by recreating the function.

**Comment by sijie** [comment]
@gh777777 what version of python function are you using?

**Comment by devinbost** [comment]
At a glance, I wonder if this issue is related to this other one: https://github.com/apache/pulsar/issues/4857#issuecomment-517065570

**Comment by gh777777** [comment]
> @gh777777 what version of python function are you using?

Sorry to reply so late. I use python 3.8.2. Now the issue has gone.

I suspect the problem has to do with python environment. I found that pulsar functions are running in my bash environment, so I put python (3.8.2) in front of my $PATH. This seems to work, but i'm not very sure.
