### ISSUE TITLE
Python 3.7 in Docker

### ISSUE THREAD

**Issue by ghost** [apache/pulsar#4944]
**Is your feature request related to a problem? Please describe.**
pulsar docker contains python 3.5 so python functions fail on things like f-strings and type hints

**Describe the solution you'd like**
use python 3.7 instead

**Comment by aahmed-se** [comment]
We are just using the default python provided by the debian, if 3.7 is needed best fork to build a custom image.

**Comment by pouledodue** [comment]
debian 10 uses 3.7 as default

**Comment by aahmed-se** [comment]
debian 10 can be considered for 2.5 , that will be later in the year.

**Comment by aahmed-se** [comment]
debian 10 has open jdk 11 as default , we will decide to move that as default jvm also as part of the move.

**Comment by jiazhai** [comment]
This issue should already be fixed, and will be included in 2.7.0.   would like to close this issue.
