### ISSUE TITLE
[function]Does  the pulsar support connecting to the database in function?

### ISSUE THREAD

**Issue by LeisureChou** [apache/pulsar#4947]
Does  the pulsar support connecting to the database in function?

**Comment by LeisureChou** [comment]
or  can the state in function  save into db

**Comment by sijie** [comment]
@LeisureChou in theory you can just open a connection to a data in the constructor of the function, so that you can use the db connection in the function method.

Is that what you are looking for? Or can you describe more about what you are looking for?

**Comment by LeisureChou** [comment]
The state in function is saved into  local memory or bookeeper memory  or bookeeper disk

**Comment by sijie** [comment]
> The state in function is saved into local memory or bookeeper memory or bookeeper disk

in bookkeeper. stored and replicated on disks.

**Comment by LeisureChou** [comment]
import lombok.*;
import lombok.experimental.Accessors;

@Data
@Setter
@Getter
@Accessors(chain = true)
@ToString
public class WindowConfig {

    public static final String WINDOW_CONFIG_KEY = "__WINDOWCONFIGS__";
    /*The number of messages per window*/
    private Integer windowLengthCount;
    /*The time duration of the window in milliseconds*/
    private Long windowLengthDurationMs;
   /*The number of messages after which the window slides*/
    private Integer slidingIntervalCount;
    /*The time duration after which the window slides*/
    private Long slidingIntervalDurationMs;

    private String lateDataTopic;

    private Long maxLagMs;

    private Long watermarkEmitIntervalMs;

    private String timestampExtractorClassName;

    private String actualWindowFunctionClassName;
}
Can  I  customize my 'timestampExtractorClassName' ? How can I customize it?

**Comment by sijie** [comment]
Close this issue since the original question is answered. If there are more questions, please open a new issue.
