### ISSUE TITLE
gen-yml-from-env.py is broken in 2.4.0

### ISSUE THREAD

**Issue by mingfang** [apache/pulsar#4956]
```sh
docker run apachepulsar/pulsar-all:2.4.0 sh -c "\
export configurationStoreServers=foo
env|grep foo
/pulsar/bin/gen-yml-from-env.py /pulsar/conf/functions_worker.yml
grep configurationStoreServers /pulsar/conf/functions_worker.yml"
```
configurationStoreServers=foo
/pulsar/bin/gen-yml-from-env.py:49: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  conf = yaml.load(open(conf_filename))
configurationStoreServers: localhost:2181

**Comment by tuteng** [comment]
This is a warning and will not affect the normal operation. Fix has been made here https://github.com/apache/pulsar/pull/4974

**Comment by mingfang** [comment]
My function_worker.yml file does not seem to pick up the env.
I thought it was because of this problem.

**Comment by mingfang** [comment]
ok, nvm
I looked at the script. The env needs PF_ prefix.

**Comment by tuteng** [comment]
> ok, nvm
> I looked at the script. The env needs PF_ prefix.

Yes, PF_ prefix is required for parameters customized in environment variables
