### ISSUE TITLE
docker image should have C++ client installed

### ISSUE THREAD

**Issue by freeznet** [apache/pulsar#4971]
**Describe the bug**
pulsar standalone v2.4.0 docker image do not have C++ client installed, we have to manually install C++ client from deb package from https://pulsar.apache.org/docs/en/client-libraries-cpp/#deb. The lack of C++ client caused go function cannot be executed. following logs shown that the elf do not have required lib `libpulsar.so.2.4.0`.

```
ldd steady-voltage-handler
	linux-vdso.so.1 (0x00007ffe4b5fe000)
	libpulsar.so.2.4.0 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1631147000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1630da8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1631364000)
```

**Comment by sijie** [comment]
@freeznet I believe the docker image should have C++ client installed. otherwise python client is unable to be used and python functions can not be run.

@wolfstudy can you work with @freeznet to see why he can't run go function?

**Comment by freeznet** [comment]
@sijie @wolfstudy i have located the problem. python version has a shortcut to solve the dependency problem by copy a compiled dynamic lib file called `_pulsar.so` to python's `site-packages`.

https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/python/setup.py#L50

for golang function, ELF will not search dynamic lib within python's site path.
