### ISSUE TITLE
[Doc] update config docs

### ISSUE THREAD

**Issue by ghost** [apache/pulsar#4981]
[Docs](https://pulsar.apache.org/docs/en/reference-configuration/#broker) not up-to-date with [conf](https://github.com/apache/pulsar/blob/branch-2.4/conf/broker.conf)

for example `isSchemaValidationEnforced=false` is not there

**Comment by BGRichi** [comment]
marked, I will take care of this issue, and get back if any news.

**Comment by Jennifer88huang** [comment]
@pouledodue Thanks for raising the issue.
We've updated the docs to sync with code changes for this files in multiple PRs.

To make sure to sync doc with code changes, we'd like to  fix it with a auto generator in https://github.com/apache/pulsar/issues/7412
If you can contribute such script, that would be great.

**Comment by sijie** [comment]
Close this issue since it has been fixed.
