### ISSUE TITLE
[cgo client] The function Send(ctx, msg) performance is not good

### ISSUE THREAD

**Issue by banishee** [apache/pulsar#4983]
#### Expected behavior

I want to send a quantity of messages using [pulsar-client-go](https://github.com/apache/pulsar-client-go) (not cgo), and I hope it can be done in less than 1 second

#### Actual behavior

I call Send(ctx,msg) about 2000 times in a loop, it costs me 6 seconds to finish totally.
One message's capacity is 60 Bytes or so.

#### Steps to reproduce

```
       for i:=0; i<2000; i++ {		
                        ..........
		msg, err := proto.Marshal(&xxx)
		if err != nil {
			fmt.Println(err)
			return
		}

		if err := producer.Send(context.Background(), &pulsar.ProducerMessage{Payload: msg}); err != nil {
			fmt.Println(err)
		} else {
			//fmt.Printf("[%d]success\n", i)
		}
	}
```

#### System configuration
OS: macOS 10.14
docker in localhost: apachepulsar/pulsar-standalone:2.3.1 bin/pulsar standalone

**Comment by wolfstudy** [comment]
Now, the go client depends on the cpp client. When we send the message every time, we will call the send of the cpp client to implement the real send function. In this process, a system call from go to c will occur, so there will be a certain performance issues.

Currently we use native go to rewrite pulsar's go client, the interface is consistent with the cgo client, the project address: https://github.com/apache/pulsar-client-go/, you can try to use this client to see if it can meet your performance requirements.
