### ISSUE TITLE
Non-partitioned topic with '-partition-[number]' suffix conflicts with partitioned topic

### ISSUE THREAD

**Issue by fxbing** [apache/pulsar#4994]
**Is your feature request related to a problem? Please describe.**

First, create a non-partitioned topic with the '-partition-[number]' suffix, such as  'topic-name-partition-0'.
And then, create a partitioned topic which name is 'topic-name' by cli.
The result is that the non-partitioned topic that was originally created will be overwritten.
**The consumer that previously planned to consume the non-partitioned topic will also consume the message published by the producer of the partitioned topic.**

**Describe the solution you'd like**

If the user created a partitioned topic  with the same name after creating a non-partitioned topic with a '-partition-[number]' suffix, throw exception and prohibit creation.

**Describe alternatives you've considered**

If we think that it is a consensus to not be able to create a topic like this
Only tell the user through the documentation not to use this way

**Comment by sijie** [comment]
> If the user created a partitioned topic with the same name after creating a non-partitioned topic with a '-partition-[number]' suffix, throw exception and prohibit creation.

+1 Pulsar should prohibit the creation of a partitioned topic with the same name if there is already a non-partitioned topic already exists.
