### ISSUE TITLE
[BUILD FAILURE] pulsar-broker-auth-athenz of 2.5.0-SNAPSHOT[master], due to wrong maven repository

### ISSUE THREAD

**Issue by frank-dkvan** [apache/pulsar#4998]
**Describe the bug**
don't have jar in the maven repository: http://repo1.maven.org/maven2/com/yahoo/

the building error info below for reference: 

[ERROR] Failed to execute goal on project pulsar-broker-auth-athenz: Could not resolve dependencies for project org.apache.pulsar:pulsar-broker-auth-athenz:jar:2.5.0-SNAPSHOT: Failed to collect dependencies at com.yahoo.athenz:athenz-zpe-java-client:jar:1.8.17: Failed to read artifact descriptor for com.yahoo.athenz:athenz-zpe-java-client:jar:1.8.17: Failure to find com.yahoo.athenz:athenz:pom:1.8.17 in http://repo1.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of Central has elapsed or updates are forced -> [Help 1]

**To Reproduce**
git clone latest master code, just build...then...failure

**Expected behavior**
![image](https://user-images.githubusercontent.com/17067653/63420436-3bfb0f80-c439-11e9-9481-d66ab798ce9e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/17067653/63420491-5af9a180-c439-11e9-811f-12496375e1a8.png)

**Additional context**
may need change to right maven repository

**Comment by sijie** [comment]
@frank-dkvan can you provide more details about what command you are running?

**Comment by sijie** [comment]
@frank-dkvan just FYI. I don't have any problems building the master and also all the jenkins CI jobs can build master as well.

**Comment by frank-dkvan** [comment]
@sijie Hi, I just clone master code from github to local directory, then execute command in my MAC as follow, consequently failure occured:    
mvn install -DskipTests

**Comment by sijie** [comment]
@frank-dkvan 

The athenz dependencies are in yahoo's maven repo. 

The yahoo's maven repo is already defined in pulsar's root pom file. so please make sure you are able to access the maven repo.

```
  <repositories>
    <repository>
      <id>central</id>
      <layout>default</layout>
      <url>https://repo1.maven.org/maven2</url>
    </repository>
    <repository>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>bintray-yahoo-maven</id>
      <name>bintray</name>
      <url>https://yahoo.bintray.com/maven</url>
    </repository>
  </repositories>
```

**Comment by frank-dkvan** [comment]
@sijie it works! great, thanks!
I just paste this repository into sub-project "pulsar-broker-auth-athenz" POM file.

**Comment by frank-dkvan** [comment]
I think this thread can be closed.
