### ISSUE TITLE
RedeliverUnacknowledgedMessages by ids returns more messages than requested

### ISSUE THREAD

**Issue by Lanayx** [apache/pulsar#5004]
**Describe the bug**
I'm writing a [.net client](https://github.com/fsharplang-ru/pulsar-client-dotnet) and got an issues while implementing _AckTimeout_ logic. When ack is not received [RedeliverUnacknowledgedMessages ](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L1266)function is called. 
Let's say 100 messages where produced (without any batching) and 90 messages where acknowledged individually. After _AckTimeout_ I make RedeliverUnacknowledgedMessages call for messages 91-95 and expect only them to be redelivered. But what I see is messages 91-100 get redelived.

**To Reproduce**
Unfortunately I was unable to run Java source code to confirm this, so [this is](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/tests/IntegrationTests/Tests.fs#L241-L293) integration test for .NET at least for some reference. It works fine most of the times, because all 10 messages get in one [timePartition ](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/UnAckedMessageTracker.java#L115) but otherwise I see the warning in logs which clearly show that all messages were redelivered, not only requested ones

**Expected behavior**
Only requested messages get redelivered

**Screenshots**
not applicable

**Desktop (please complete the following information):**
 - Windows 10
 - minikube (2 bookees, 2 brokers, 1 proxy) 

**Additional context**
Pulsar version 2.4.0 (installed from helm chart)

**Comment by sijie** [comment]
@Lanayx what is the subscription mode?

**Comment by Lanayx** [comment]
@sijie Subscription mode is default - exclusive

**Comment by sijie** [comment]
@Lanayx : If it is exclusive or failover, it is the expected current behavior. There is an issue following up improving the behavior. See #4118

**Comment by Lanayx** [comment]
Thank you, I've checked that with shared mode is works as expected. Closing the issue.
