### ISSUE TITLE
pulsar-proxy serves pulsar sql worker?

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#5017]
I checked the proxy.conf and there is no mention about pulsar sql-worker support.

Does the pulsar-proxy support redirect presto://<proxy-url> to pulsar sql workers?

**Comment by KannarFr** [comment]
And if it doesn't, does pulsar sql worker supports SslContextAutoRefreshBuilder?

**Comment by sijie** [comment]
@KannarFr You can use `httpReverseProxyConfigs`for making pulsar proxy as a reverse proxy. https://github.com/apache/pulsar/blob/master/conf/proxy.conf#L173
