### ISSUE TITLE
Create ZooKeeper znodes under a dedicated parent

### ISSUE THREAD

**Issue by vontikov** [apache/pulsar#5026]
Apache Pulsar related znodes are placed under ZooKeeper root:
_[admin, bookies, counters, ledgers, loadbalance, managed-ledgers, namespace, schemas, stream]_
Placing them under a dedicated parent (someting like "/apache-pulsar") would simplify support in case of sharing ZooKeeper cluster between different apps

**Comment by skyrocknroll** [comment]
You can use zookeeper chroot to achieve the same

**Comment by vontikov** [comment]
Thanks!
