### ISSUE TITLE
[Doc] 'JSON Web Token Authentication' is not documented in the Security chapter of Pulsar document

### ISSUE THREAD

**Issue by Monica-zy** [apache/pulsar#5050]
Need to add the corresponded reference content of 'JSON Web Token Authentication' link in the Security chapter of Pulsar document. Its descriptive md. file is not added at present.

![image](https://user-images.githubusercontent.com/44013755/63753636-02694f00-c8e6-11e9-9101-a203c06640b3.png)

**Comment by Jennifer88huang** [comment]
@sijie From the engineer part, who is familiar with "JSON Web Token Authentication"? We need some support to write this topic.

**Comment by sijie** [comment]
@Jennifer88huang @Monica-zy : 

It is already documented: http://pulsar.apache.org/docs/en/security-token-client/ and http://pulsar.apache.org/docs/en/security-token-admin/

**Comment by Jennifer88huang** [comment]
@Monica-zy Try to investigate the issue. If needed, you can come up with a solution with new structure.

**Comment by Monica-zy** [comment]
Here is my suggested solution: Merge and rewrite the original two file security-token-client.md and security-token-admin.md into a new security-jwt.md which links to the list item "JSON Web Token Authentication" in the file security-overview.md; adjust the related content in security-overview and unify the sidebar title into a similar format as much as possible.
Changes in security-overview.md:
![屏幕快照 2019-09-11 上午11 42 00](https://user-images.githubusercontent.com/44013755/64666613-7892b780-d489-11e9-9e63-5d6848aaec78.png)
Changes in sidebar:
![屏幕快照 2019-09-11 上午11 46 21](https://user-images.githubusercontent.com/44013755/64666764-ffe02b00-d489-11e9-8131-0079b2b6f58d.png)
and welcome better suggestions and opinions to discuss here~

**Comment by Jennifer88huang** [comment]
@Monica-zy In the TLS transport topic and other topics, make the heading consistent. The following is an example.
![image](https://user-images.githubusercontent.com/47805623/64754408-cf67c200-d559-11e9-914a-62c82502dc03.png)
When you update this, make sure that 
1. Update all similar cases in the Security and Deployment chapters;
2. Check links related to those headings;
3. Add related lead-in sentences.

For the overall structure, I'll sync with you later.
