### ISSUE TITLE
deliverAfter(...).sendAsync() -> CompletableFuture returning immediately

### ISSUE THREAD

**Issue by lorraine1** [apache/pulsar#5061]
**Describe the bug**
The delayed publishing feature deliverAfter(...) is working good and well with sendAsync().  However, the CompletableFuture return of the sendAsync() is getting a completion immediately.  Expected is that it will return only after the delayed publishing is actually done.  Or is my understanding wrong?...

**To Reproduce**
`producer.newMessage().keyBytes(key).value(value).deliverAfter(10_000, MILLISECONDS).sendAsync().thenAccept(messageId -> log.info("done"));`

"done" is getting printed immediately.

**Expected behavior**
Expected is that the CompletableFuture will only return/get accepted after the delayed publishing is actually done, in the example after 10 seconds.

version 2.4.0

**Comment by sijie** [comment]
> Expected is that it will return only after the delayed publishing is actually done. Or is my understanding wrong?...

@lorraine1 the delay applies to delivering message to the consumer. it doesn't 'delay' at producing.
