### ISSUE TITLE
can't update JSON Schema to AVRO with pulsar-admin

### ISSUE THREAD

**Issue by pouledodue** [apache/pulsar#5088]
**Describe the bug**
Changing just the type of schema does not work

**To Reproduce**
1. create a file `/tmp/yoshi` containing:
```
{
    "type": "JSON",
    "schema": "{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"com.foo\",\"fields\":[{\"name\":\"file1\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"file2\",\"type\":\"string\",\"default\":null},{\"name\":\"file3\",\"type\":[\"null\",\"string\"],\"default\":\"dfdf\"}]}",
    "properties": {}
}
```
2. now type `pulsar-admin schemas upload -f /tmp/yoshi persistent://public/default/yoshi` to upload the schema
3. now type `pulsar-admin schemas get persistent://public/default/yoshi`
the result will say:
```
...
 "type": "JSON",
...
``` 
which is ok
4. edit `/tmp/yoshi` and change
```
...
  "type": "AVRO",
...
```
5. now type `pulsar-admin schemas upload -f /tmp/yoshi persistent://public/default/yoshi` to upload the schema
6. now type `pulsar-admin schemas get persistent://public/default/yoshi`
the result will say:
```
...
 "type": "JSON",
...
``` 
it should say instead 'AVRO'

**Desktop (please complete the following information):**
 - macos, pulsar-all docker image 2.4.0 standalone

**Comment by sijie** [comment]
@pouledodue I don't think we allow changing the schema type at this moment. In your case, you are changing the schema type from AVRO to JSON

**Comment by stupidusername** [comment]
Have you tried deleting the schema before changing its type?

```
$ pulsar-admin schemas delete persistent://public/default/yoshi
```

And then upload the new schema.

**Comment by pouledodue** [comment]
yes it's ok when I delete it before
