### ISSUE TITLE
[doc] Admin Rest Api page do not show

### ISSUE THREAD

**Issue by pouledodue** [apache/pulsar#5089]
**To Reproduce**
1. Go to`http://pulsar.apache.org/admin-rest-api/`
2. Stare at a blank page for 5 minutes
3. go make coffee
4. Page is still blank
5. cry

**Desktop (please complete the following information):**
 - macos, safari, chrome

**Comment by tuteng** [comment]
Thank you very much, this [pr](https://github.com/apache/pulsar/pull/5076) is being fixed.

**Comment by sijie** [comment]
waiting #5107 to  be merged
