### ISSUE TITLE
Error while producing messages

### ISSUE THREAD

**Issue by ShadowDAssange** [apache/pulsar#5095]
I use pulsar-client to produce msg.

It returns "ERROR org.apache.pulsar.client.cli.PulsarClientTool - Error while producing messages
ERROR org.apache.pulsar.client.cli.PulsarClientTool - Could not send message to broker within given timeout
"
![Capture](https://user-images.githubusercontent.com/30060632/64139351-20c5d200-ce33-11e9-9bd8-3b54e7a87da9.PNG)

**Comment by ShadowDAssange** [comment]
And I use pulsar-client to consume

![Capture](https://user-images.githubusercontent.com/30060632/64139697-57501c80-ce34-11e9-93b9-612b6fcf85ee.PNG)

**Comment by sijie** [comment]
@ShadowDAssange Can you describe more about  how do you set up a Pulsar cluster, how do you configure your Pulsar client?

**Comment by sijie** [comment]
@ShadowDAssange Can you provide more information about this issue?

**Comment by ShadowDAssange** [comment]
Sorry,I have solved

**Comment by zhoudayu123** [comment]
@InasaXia   Hi, i meet the same error, may i know how do you solved it? Thanks

**Comment by zhoudayu123** [comment]
@sijie  Hi, can you help me to look at this issue?
