### ISSUE TITLE
Add documentation of pulsar-client-node to website

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#5101]
Pulsar community just release the first version of pulsar-client-node. We should add the documentation for this client.

**Comment by Jennifer88huang** [comment]
The project is at https://github.com/apache/pulsar-client-node
For writing documentation, refer to different `Client libraries` at https://github.com/apache/pulsar-client-node

**Comment by nkurihar** [comment]
https://github.com/apache/pulsar/pull/5212

**Comment by Jennifer88huang** [comment]
Fixed in #5212 , so close this issue.
