### ISSUE TITLE
How to Date type -> AVRO -> Presto

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#5112]
Hi,

I checked https://github.com/apache/pulsar/blob/master/pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/AvroSchemaTest.java#L80.

First question, `java.time.LocalDateTime` is supported?

Second about this issue:

I've got a schema with timestamp value, I tried to encode it using the example provided via Joda. Here is the schema for this attribute:

```
      {
        "name": "timestamp",
        "type": {
          "type": "record",
          "name": "DateTime",
          "namespace": "org.joda.time",
          "fields": [
            {
              "name": "iMillis",
              "type": "long"
            },
            {
              "name": "iChronology",
              "type": {
                "type": "record",
                "name": "Chronology",
                "fields": []
              }
            }
          ]
        }
      },
```

How get a generic date type, not jvm one, to output it as timestamp type in presto?

For this I've got presto typed as  `timestamp.imillis    | bigint    |       | `.

**Comment by KannarFr** [comment]
@jerrypeng

**Comment by sijie** [comment]
@codelipenghui @congbobo184 can any of you help @KannarFr with his question? Also if the documentation is missing, it might be worth improving the documentation about this part.

**Comment by KannarFr** [comment]
poke @codelipenghui @congbobo184

**Comment by congbobo184** [comment]
@KannarFr First, AvroSchema only support org.joda.time. The second, you should use Avro logicalType like ``        @org.apache.avro.reflect.AvroSchema("{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}")
        DateTime timestampMillis;``

**Comment by KannarFr** [comment]
@congbobo184 I tried this but in presto side it's a bigint, not a timestamp.

**Comment by KannarFr** [comment]
Yes I saw this in AvroSchemaTest.java or something related but still the presto type issue.

**Comment by KannarFr** [comment]
(The second part of the issue described on top of this thread).

**Comment by codelipenghui** [comment]
@KannarFr Are you using the master branch to build a snapshot version?  I test with master branch, it seems worked:

**Comment by KannarFr** [comment]
Ok, will try maybe I probably did something wrong. Thanks for your time, keep you updated.

**Comment by KannarFr** [comment]
@codelipenghui and about List[String] to presto array, do you have an example?

**Comment by codelipenghui** [comment]
@KannarFr Currently can not work well with list, i think we need add support for presto ARRAY type in pulsar SQL.

**Comment by KannarFr** [comment]
@congbobo184 @codelipenghui 

I used joda, with the logical schema type. like 

```java
@AvroSchema("{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}")
public DateTime timestamp;
```

The output of `show columns from topic`

```sql
 timestamp.imillis    | bigint    |       |
```

When I select this particular field I've got `Column 'timestamp.imillis' cannot be resolved` other fields (text, int) work well.

The `select *` works and outputs 

```sql
| timestamp.imillis |                  ownerid                  |
+-------------------+-------------------------------------------+
|     1568128483098 | orga_858600a8-74f4-4d75-a8a3-f5b368be093c |
|     1568128480098 | orga_858600a8-74f4-4d75-a8a3-f5b368be093c |
|     1568128481098 | orga_858600a8-74f4-4d75-a8a3-f5b368be093c |
|     1568128482098 | orga_858600a8-74f4-4d75-a8a3-f5b368be093c |
```

**Comment by codelipenghui** [comment]
@KannarFr I see something different.

**Comment by KannarFr** [comment]
@codelipenghui I deliberately trim, the metadata columns are here and publishtime is typed timestamp.

For your example what is the schema if you schemas get on topic for field timestamp?

**Comment by KannarFr** [comment]
(I described mine un top of this thread.)

**Comment by codelipenghui** [comment]
@KannarFr This is my schema info(use pulsar-admin schemas get):

**Comment by sijie** [comment]
@KannarFr is your question answered?
