### ISSUE TITLE
Bookie : provide option to skip adding entry to journal 

### ISSUE THREAD

**Issue by rdhabalia** [apache/pulsar#5128]
### Motivation
Right now, bookie serves WAL and provides durability by writing entry to journal before acking the message and it persist the entry to entry log file. bookie also provides below options to improve throughput
- to persist entry with fsync disable 
- writing entry to separate devices for journal and ledger. 

So, persisting entry to journal before acking gives durability but sometimes it becomes bottleneck (mostly due to number of io ops) when user wants to achieve higher throughput in system.

Few users have usecase to achieve high throughput with low publish latency, can compromise with durability and mostly reads from the cache. In that case, if we skip adding entry to journal and acks the message as soon as it's added to ledger cache then user can achieve comparatively very high writes in bookie. and it also helps in pulsar to reduce footprints of bookie while serving such usecases.

So, we want to add option to skip adding entry to journal. We also want to make sure that bookie should be able to handle change in this configuration and should come back gracefully whenever this configuration has been changed.

### Changes
Provide option `journalSkipEntryEnable` using which bookie can skip adding entry to journal while serving addEntry request.

@merlimat

**Comment by rdhabalia** [comment]
created PR at: https://github.com/apache/bookkeeper/pull/2157

**Comment by tisonkun** [comment]
IIRC this functionality is supported by BookKeeper now.

Closed as stale. Please open a new issue if it's still relevant in maintained versions.
