### ISSUE TITLE
Pip can't find pulsar-client 2.4.1 for Python 3.7

### ISSUE THREAD

**Issue by RAbraham** [apache/pulsar#5129]
**Describe the bug**
Hi,
I'm on python 3.7.4 and when I do a `pip install pulsar-client==2.4.1` according to the [docs](https://pulsar.apache.org/docs/en/client-libraries-python/#installation-using-pip), I get the following error.

```bash
(venv) ➜   python --version
Python 3.7.4
(venv) ➜   pip install pulsar-client==2.4.1
Collecting pulsar-client==2.4.1
  ERROR: Could not find a version that satisfies the requirement pulsar-client==2.4.1 (from versions: 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.3.0, 2.3.0.post1, 2.3.1, 2.3.2, 2.4.0)
ERROR: No matching distribution found for pulsar-client==2.4.1
```

**Desktop (please complete the following information):**
 - OS: MacOS Mojave

**Additional context**
I'm using `pyenv`

**Comment by aahmed-se** [comment]
mac os artifacts have not been published yet.

**Comment by RAbraham** [comment]
great, thanks
