### ISSUE TITLE
[Documentation] Add Geo Replicated subscriptions documentation in website

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#5134]
In [PIP-33](https://github.com/apache/pulsar/wiki/PIP-33%3A-Replicated-subscriptions), Geo Replicated subscriptions, feature is added, but documentation is not updated.
related PRs: #4396 #4299 #4340 #4354

This issue tries to track the documentation work.

**Comment by sijie** [comment]
@Jennifer88huang can you add this to the backlog? It is good to have this documentation added before 2.5.0 release.

**Comment by Jennifer88huang** [comment]
Sure, got it.

**Comment by Jennifer88huang** [comment]
After reading PIP-33, and discussing with @zymap, we come to the conclusion that snapshot belongs to internal implementation, and users need not know it. If so, I'll not document how snapshot works in the user docs. If there is any misunderstanding, feel free to tell me.
Thing to be confirmed (@jiazhai @tuteng @zymap @merlimat) :   
- "The snapshots are taken periodically. Proposed default is every 1 second." "The frequency of this snapshot will be configurable in `broker.conf`" Is the snapshot set by default? Should we tell users the limitations?
- Is "replicated subscription" enabled by default? or Is the default value of `.replicateSubscriptionState` true or false?
