### ISSUE TITLE
[Go Function API] Ability to do content-based routing

### ISSUE THREAD

**Issue by mrijkeboer** [apache/pulsar#5137]
In the Java Function API there's the option to do routing based on content ([fruit and vegetable example](https://pulsar.apache.org/docs/en/functions-overview/)) by using the `publish` method of the `context`. It would be useful if this functionality would be available in Go as well.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
