### ISSUE TITLE
PIP-43: Producer Send Message with Different Schema

### ISSUE THREAD

**Issue by yittg** [apache/pulsar#5141]
This is a master issue for tracking the work to implement [PIP-43](https://github.com/apache/pulsar/wiki/PIP-43%3A-producer-send-message-with-different-schema).

* [x] core implementation.
* [x] expose `newMessage` to interface with different parameterized type.
* [x] move general `SchemaHash` to pulsar-common module.

**Comment by yittg** [comment]
cc @sijie. BTW, would you help to update the PIP wiki, some typos fixed and header supplemented.

**Comment by sijie** [comment]
@yittg done

**Comment by yittg** [comment]
@sijie, PIP-43 has been fully implemented, may we close this issue?

**Comment by sijie** [comment]
@yittg yes. closing it now and will update the status of the PIP.

**Comment by sijie** [comment]
@yittg well done!
