### ISSUE TITLE
[docs] Managing partitioned topics page has odd "Nonpartitioned topics resources" section

### ISSUE THREAD

**Issue by rocketraman** [apache/pulsar#5142]
**Describe the bug**

The docs about managing partitioned topics has an odd sub-heading "Nonpartitioned topics resources". However, everything under that sub-heading except the first "Create" sub-heading seems to be related to partitioned topics (as one would expect for this page). The "Nonpartitioned topics resources" and the "Create" subheading under that seem to be a copy/paste error or something.

![image](https://user-images.githubusercontent.com/53049/64441829-9d0f1e00-d09c-11e9-867b-d03e7a78165b.png)

**Comment by sijie** [comment]
@Jennifer88huang can you help check the issue?

**Comment by Jennifer88huang** [comment]
Sure.

**Comment by Jennifer88huang** [comment]
While I pull request on the modification today, I notice that @rocketraman has already pulled request for this issue, see https://github.com/apache/pulsar/pull/5143
While investigating the issue, I come up with the following structure:
## Partitioned topic resources
### Create
### Get metadata
### Update
### Delete
### List
### Stats (not sure whether the content is same for partitioned and non-partitioned topics)
### Internal stats (not sure whether the content is same for partitioned and non-partitioned topics)

## Nonpartitioned topic resources
### Create
### Delete (need info)
### List (need info)

**Comment by rocketraman** [comment]
@Jennifer88huang Note the title of the page is "Managing Partitioned Topics". I think a different page "Managing Non-Partitioned Topics" needs to be created, as such a page does not currently appear to exist. If so, I can add this to my pull request.

**Comment by rocketraman** [comment]
I have added a new page "Managing non-partitioned topics", for review, to pull request #5143 .

**Comment by Jennifer88huang** [comment]
Great, I'll check the added content in #5143. Thanks for doing so.
