### ISSUE TITLE
[docs] How does --processing-guarantees affect source connectors?

### ISSUE THREAD

**Issue by stupidusername** [apache/pulsar#5157]
The command `sources create` accepts a `--processing-guarantees` option. I tried to find out what's the difference between the accepted options but I could not find an answer in the docs.

Did I miss something or does the documentation need a little improvement?

Thank you!

**Comment by jiazhai** [comment]
http://pulsar.apache.org/docs/en/functions-overview/#processing-guarantees
Does this link contain the info you want?

**Comment by stupidusername** [comment]
Thank you but that document does not explains how the `--processing-guarantees` option affects source connectors.

For sink connectors using a value of `EFFECTIVELY_ONCE` changes the subscription mode to fail over, thus enabling the connector to retain message order. But I do not understand why is this an option for source connectors. I tried reading the source code without luck. Maybe the option is just there so developers can use it in source connectors if they need it.

**Comment by sijie** [comment]
@stupidusername 

> But I do not understand why is this an option for source connectors.

A source connect receives messages from external system and writes them to a Pulsar topic. The "--processing-guarantees" is use for ensuring the processing guarantees for writing messages to the Pulsar topic.

@jiazhai @tuteng @Anonymitaet Can you work on clarifying the meanings for this flag?

**Comment by stupidusername** [comment]
Thank you.

I think that for sink connectors the functionality is clear enough:

- `ATMOST_ONCE`: Shared subscription - Does not retry on unknown delivery status.
- `ATLEAST_ONCE`: Shared subscription - Retries on unknown delivery status.
- `EFFECTIVELY_ONCE`: Failover subscription - Retries on unknown delivery status.

A technical explanation on how this option is implemented on source connectors is going to be useful for developers that need to determine the delivery guarantees of their systems.

**Comment by sijie** [comment]
@stupidusername :

Actually I think you had a wrong impression here. 

the processing guarantees are used for determining the subscription type that Pulsar uses for reading messages from a Pulsar topic and the error handling for Pulsar writing messages to a Pulsar topic.

So the actual processing guarantee for connectors is not just relied on Pulsar guarantee but also on the implementation of source and sink.

For source connectors, the processing guarantees is much clear. Because Pulsar ensures writing messages to a Pulsar topic to be respecting to processing guarantee. It is within Pulsar's control.

For sink connectors, the processing guarantees replies on the sink implementation. If the sink implementation doesn't handle retries in the idempotent way,  the sink will not respect to the processing guarantees.

**Comment by stupidusername** [comment]
I do understand that the processing guarantees are also determined by the implementation of the connectors.

I'm going to try to make some free time to further explore this topic and make a PR to update the docs if I see it necessary.

I appreciate you taking the time to clarify my doubts.

**Comment by sijie** [comment]
@stupidusername you are welcome. looking forward to your contributions.

**Comment by codelipenghui** [comment]
@stupidusername Are your working on this issue?

**Comment by stupidusername** [comment]
This has been sitting in my backlog for ages. I promise to submit a PR this week.

![image](https://user-images.githubusercontent.com/3828886/82345801-13a24080-99cc-11ea-861c-faf2cd8c34c0.png)

**Comment by codelipenghui** [comment]
Thanks a lot. Don't worry, take your time.

**Comment by stupidusername** [comment]
I've been doing some tests using this source connector: [sequence_source](https://github.com/Antti-Kaikkonen/PulsarSequenceSource).

I tested different combinations of `--processing-guarantees` and `--parallelism` and consumed the published messages.

- Using `EFFECTIVELY_ONCE` and `--parallelism` set to `1` I got one sequence of ordered numbers.
- Using `ATLEAST_ONCE` and `--parallelism` set to `1` I got one sequence of ordered numbers.
- Using `EFFECTIVELY_ONCE` and `--parallelism` set to `4` I got one sequence of ordered numbers.
- Using `ATLEAST_ONCE` and `--parallelism` set to `4` I got what it looks to be four sequences of numbers, each one of them starting from 0.
- Using `EFFECTIVELY_ONCE` and `--parallelism` set to `4` with a modified version of the source connector that uses a different `partitionId` for each instance of the connector I also got four sequences of numbers.

The tests were conducted on a standalone instance of Pulsar. Deduplication was not set.

So It looks like when ussing `EFFECTIVELY_ONCE` duplicated messages are beign removed even though deduplication is not set on a namespace level. Is this observation correct?

Also, I would like to know if each instance of the source connector has the guarantee of writing its messages in order to the topic. If that's true: How is it achieved?

Thanks!

**Comment by Jennifer88huang** [comment]
@stupidusername thanks for raising the issue. Could you please check the update in https://github.com/apache/pulsar/pull/7767. Any issue, feel free to contact me. Thank you.

**Comment by stupidusername** [comment]
@Jennifer88huang thanks for submitting the PR. The CLI documentation looks better with those changes IMO.

It's still difficult for me to understand how is the `EFFECTIVELY_ONCE` guarantee achieved. I ran some tests and also read the source code. My conclusion was that the `partitionId` and the `recordSequence` are used to determine the uniqueness of a message.

I wouldn't mind adding this information to the docs myself but I am not quite sure if my observations are correct.

**Comment by stupidusername** [comment]
The doubt I mentioned in my last comment was clarified on #5181. Thanks to all the people involved in making the documentation better!

**Comment by Jennifer88huang** [comment]
@stupidusername thanks for your contributions. And looking forward to your update later.
