### ISSUE TITLE
function querystate command causes the number of broker threads to increase

### ISSUE THREAD

**Issue by JoyJava** [apache/pulsar#5177]
**Describe the bug**
`bin/pulsar-admin function querystate --name xxx --tenant public --namespace default --key SumFunction -w`
Resulting in a surge in the number of pulse broker server threads, eventually OOM

**To Reproduce**
1. bin/pulsar-admin function querystate --name xxx --tenant public --namespace default --key SumFunction -w
2. run the command on broker server `jstack `sudo jps|grep Pul|awk '{print $1}'`|grep tid |awk '{print $1 }'|sort|unqi -c`

**Expected behavior**
xxx-OrderedScheduler The number of threads is gradually increasing

**Screenshots**
![image](https://user-images.githubusercontent.com/2907737/64678007-42fec600-d4ab-11e9-8778-8c8b8b4aba1d.png)

**Desktop (please complete the following information):**
 - OS: 16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- version：apache-pulsar-2.4.0

**Comment by jiazhai** [comment]
@wolfstudy to take a look

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
