### ISSUE TITLE
A placeholder for function security doc of brokerClientAuthenticationPlugin

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#5179]
This is a placeholder for function security doc of brokerClientAuthenticationPlugin
In #5153, we add some configuration doc for brokerClientAuthenticationPlugin, 
In Function worker security, this brokerClientAuthenticationPlugin also need to be taken care. 
reference #4560 for more details.

**Comment by jiazhai** [comment]
@wolfstudy

**Comment by Anonymitaet** [comment]
@wolfstudy since u r working on function security doc, could u pls take this issue into consideration? thanks
