### ISSUE TITLE
Multiple LAN clusters configure multi-cluster

### ISSUE THREAD

**Issue by efynn** [apache/pulsar#5182]
In multiple lans, multiple clusters and each cluster network is not connected, how should the configuration storage be deployed?
Is it necessary to set up another DNS server?

Not found in the documentation:  http://pulsar.apache.org/docs/en/deploy-bare-metal-multi-cluster/

**Comment by sijie** [comment]
the configuration storage should be stored in locations that are accessible by all the brokers in different clusters.

**Comment by efynn** [comment]
Thank you for your reply
