### ISSUE TITLE
2.4.1 - Pulsar standalone + debezium mysql do not work

### ISSUE THREAD

**Issue by SirBigoo** [apache/pulsar#5189]
Hello !

**Describe the bug**
I tried to connect pulsar with CDC debezium on MySQL database. So, I'm following this tutorial : https://pulsar.apache.org/docs/en/io-cdc-debezium/

But, when I start my local run with my source file, it crashes. 

Logs on pulsar standalone : 
```
0:16:53.687 [ForkJoinPool.commonPool-worker-6] ERROR org.apache.pulsar.broker.web.PulsarWebResource - Policies not found for pubilc/default namespace
10:16:53.687 [ForkJoinPool.commonPool-worker-6] WARN  org.apache.pulsar.broker.service.ServerCnx - Failed to get Partitioned Metadata [/127.0.0.1:53926] persistent://pubilc/default/dbserver1.inventory.products_on_hand: Policies not found for pubilc/default namespace
org.apache.pulsar.broker.web.RestException: Policies not found for pubilc/default namespace
```

Logs on source loading : 
```
10:15:38.186 [pulsar-client-io-1-1] WARN  org.apache.pulsar.client.impl.BinaryProtoLookupService - [persistent://pubilc/default/dbserver1.inventory.products_on_hand] failed to get Partitioned metadata : Policies not found for pubilc/default namespace
...
10:15:38.205 [main] INFO  org.apache.pulsar.functions.LocalRunner - RuntimeSpawner quit because of
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: Sink Error
```

**To Reproduce**
Steps to reproduce the behavior (all config in tutorial link) :
1. Download pulsar 2.4.1
2. Download debezium mysql connector 2.4.1
3. Install connector by creating connectors folder on pulsar install dir
4. Create configuration file 
5. Run mysql docker
6. Run pulsar standalone : `bin/pulsar standalone`
7. Run configuration : `bin/pulsar-admin source localrun  --sourceConfigFile debezium-mysql-source-config.yaml`

**Expected behavior**
Topics are created and database events are loaded to topics.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

Thanks !

**Comment by tuteng** [comment]
It seems that the tenant's name is wrong, please use `public`, I have fixed it here https://github.com/apache/pulsar/pull/5190.
