### ISSUE TITLE
Schema modification question

### ISSUE THREAD

**Issue by pouledodue** [apache/pulsar#5208]
I delete a schema:
`pulsar-admin schemas delete  persistent://a/b/c`

I verify it is deleted:
`pulsar-admin schemas get persistent://a/b/c`
`> HTTP 404 Not Found`

I verify it is deleted with the `version`
`pulsar-admin schemas get --version 0 persistent://a/b/c`
```
{
  "name": "c",
  "schema": {
    "name": "YoshiSchema",
    "type": "record",
    "fields": [
      {
        "name": "comment",
        "type": "string"
      }
    ]
  },
  "type": "AVRO",
  "properties": {
    "key1": "value1"
  }
}
```

oops it is still there why?
Should it have a prop `deleted = true` ?

**Comment by stupidusername** [comment]
I don't think `deleted` it's the right field name to indicate that the schema is no longer in use. Messages created before the schema was deleted will still use it. But I do think that adding two fields to the reponse of the `schemas get` command would be useful:

- `version`: to indicate the version number of the schema (useful if you do not specify the `--version` option).

- `active`: to indicate that is used to tag new messages.

**Comment by pouledodue** [comment]
great

**Comment by sijie** [comment]
`version` is already added in master and will be released in 2.5.0.

If a topic or a schema is deleted, the schema is not used anymore because all the messages using that schema are gone. However the old versions of schema will be still there until they are compacted. We can improve the broker to return 404 if an admin client attempts to retrieve a deleted version. /cc @codelipenghui @congbobo184

**Comment by stupidusername** [comment]
@sijie 

> If a topic or a schema is deleted, the schema is not used anymore because all the messages using that schema are gone.

What do you mean by gone?

Let's say you have unacked messages that use an schema, and you delete that schema. What happens then?

I thought that messages would still reference the deleted schema.

From the schema version docs:

> Messages produced with a given `SchemaInfo` is tagged with a schema version, so when a message is consumed by a Pulsar client, the Pulsar client can use the schema version to retrieve the corresponding `SchemaInfo` and then use the `SchemaInfo` to deserialize data.

**Comment by sijie** [comment]
I meant if the schema was deleted when a topic is deleted.

In the case you described above, yes it will still referencing the old schemas.
