### ISSUE TITLE
HTTP 500 on pulsar-admin schemas delete

### ISSUE THREAD

**Issue by ghost** [apache/pulsar#5209]
when there is no schema to delete the command
`pulsar-admin schemas delete  persistent://a/b/c`

gives:
HTTP 500 Internal Server Error

Should probably be a different http code

There is nothing particular in the logs

**Comment by merlimat** [comment]
500 is typically associated with an exception stack trace on broker side. Can you paste that as well?

**Comment by pouledodue** [comment]
no stack trace with `docker logs` and no stack trace in `logs/pulsar-standalone.log` is there a log file I missed?

**Comment by pouledodue** [comment]
only the INFO:
```
02:27:53.015 [BookKeeperClientWorker-OrderedExecutor-0-0] INFO 

org.eclipse.jetty.server.RequestLog - 172.17.0.1 - - [18/Sep/2019:02:27:53 +0000] "DELETE 

/admin/v2/schemas/a/b/c/schema HTTP/1.1" 500 0 "-" "Pulsar-Java-v2.4.1" 15
```

**Comment by sijie** [comment]
@pouledodue does the topic exist or not? or was the topic deleted before?

**Comment by pouledodue** [comment]
yes it's when the topic does not exist:
```
pulsar-admin tenants create r
pulsar-admin namespaces create r/t
pulsar-admin schemas delete persistent://r/t/e
```

**Comment by xujianhai666** [comment]
@sijie on my opinion, if the topic dost not exist or has been deleted, the response should be text clear instead of 500 error.

**Comment by devinbost** [comment]
I've seen this issue as well. 
@merlimat For what it counts, on other issues, I've seen intermittent 500's appear without stack traces appearing in the broker logs. Perhaps the errors are getting suppressed somewhere.

**Comment by tisonkun** [comment]
Now it doesn't return 500.

Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
