### ISSUE TITLE
Support Postgres as a JDBC source/sink

### ISSUE THREAD

**Issue by JamieCressey** [apache/pulsar#5215]
Having ran a custom build of Pulsar 2.4 with the PostgreSQL client built in for a number of days now, I have not come across any problems using the PSQL driver as a JDBC sink at load.

I note the JDBC tests are all performed against an embedded SQL instance, are there any other tests that should be ran before I create a PR to support Postgres?

**Comment by sijie** [comment]
@JamieCressey the JDBC connectors are using JDBC for talking to different database instances. It doesn't depend on any other database implementation specific logic. So ideally whether it is using an embedded SQL instance or an external one, it should work as the same.

From CI perspective, I don't think we can support running the JDBC connectors against all different type of databases. 

However it is also great to add some coverage to popular databases like MySQL or Postgres. So if you are interested in contributing test changes, you are welcome to do so.

**Comment by makkus** [comment]
@JamieCressey would you linking your custom build? I'd like to try out a Postgres sink and if I don't have to figure out how to rebuild Pulsar myself I wouldn't mind...
