### ISSUE TITLE
Python pulsar-client==2.4.0 segfaults on macOS Catalina beta 8 (19A558d)

### ISSUE THREAD

**Issue by pouledodue** [apache/pulsar#5217]
**Describe the bug**
```
➜ ~ python
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulsar
[1]    28547 segmentation fault  python
```

**To Reproduce**
1. Install macOS Catalina beta 8
2. install python3.7
3. `pip install pulsar-client==2.4.0`
4. execute in Terminal `python -c 'from pulsar.schema import Record'`

**Expected behavior**
no segfault message

**Desktop (please complete the following information):**
 - macOS Catalina beta 8 (19A558d)

**Additional context**

**Comment by aahmed-se** [comment]
hopefully we can find hosted mac os env to make build and deploy soon https://github.com/microsoft/azure-pipelines-image-generation/issues/1243

**Comment by pouledodue** [comment]
@aahmed-se is it the correct way to build the wheel on my mac: 
```
git checkout <the 2.4 branch>
cd pulsar-client-cpp
cmake .
make
cd python
python3 setup.py bdist_wheel
pip uninstall pulsar-client
pip install ./dist/pulsar_client-2.4.1-cp37-cp37m-macosx_10_9_x86_64.whl
```

because it gives me err when importing pulsar so my procedure is probably not correct to build wheel :

```
➜ ~ python -c "import pulsar"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulsar/__init__.py", line 274, in <module>
    class Client:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulsar/__init__.py", line 372, in Client
    schema=schema.BytesSchema(),
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulsar/schema/schema.py", line 53, in __init__
    super(BytesSchema, self).__init__(bytes, _pulsar.SchemaType.BYTES, None, 'BYTES')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulsar/schema/schema.py", line 32, in __init__
    json.dumps(schema_definition, indent=True))
TypeError: __init__() should return None, not 'NoneType'
```

**Comment by pouledodue** [comment]
ok I found why

**Comment by pouledodue** [comment]
`cmake -DPYTHON_LIBRARY="/Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7.dylib" .`

**Comment by pouledodue** [comment]
hmm not sure it's the correct way because in `pipenv` virtualenv it outputs me the same err
but in non-virtualenv it works

**Comment by pouledodue** [comment]
ok recreated the `pipenv` virtualenv from scratch and seems to work in pipenv virtualenv too

**Comment by aahmed-se** [comment]
will consider this solved
