### ISSUE TITLE
Enabling Deduplication may drop messages

### ISSUE THREAD

**Issue by sleungtoast** [apache/pulsar#5218]
**Describe the bug**
Since deduplication drops messages based on the the largest sequence id recorded pre-persist, if there’s an error persisting to BK, a retry attempt will just be “deduplicated” with no message ever getting persisted.
<img width="801" alt="dedupe_fail_case" src="https://user-images.githubusercontent.com/7429691/65181039-2a068f80-da2c-11e9-9d24-550ab3c0a220.png">

**To Reproduce**
1. Client connects successfully, producer send retry enabled (i.e. sendTimeoutMs at default of 30s)
2. Produce messages at something like 1msg/s and consume them, verifying messages were not lost.
3. Cause some BK failures by shut down of some nodes or a rolling restart
4. While that happens, Client reports `Received send error from server` (note it's send error, not just a normal connection error). One example of the several resulting errors are `PersistenceError : org.apache.bookkeeper.mledger.ManagedLedgerException: Waiting for new ledger creation to complete`
5. Looking at broker logs, will see `Message has been dropped for non-persistent topic producer-id ...` even though the first attempt was unsuccessful
6. Message was lost due to dedupe logic counting 2nd retry attempt as duplicate.

**Expected behavior**
Messages should not be dropped

**Desktop (please complete the following information):**
 - OS: OSX, AWS Linux

**Additional context**
Instructions for dedupe at this link, but the same problem can occur with those settings. Also, does setting sendTimeoutMs to 0 make it try forever, or does it drop the message on first fail? https://pulsar.apache.org/docs/en/cookbooks-deduplication/#message-deduplication-and-pulsar-clients-clients
Logic for dedupe in `MessageDeduplication.java`

**Comment by merlimat** [comment]
@sleungtoast Thanks for reporting. We also discovered this issue and had already a plan for fixing it. @jerrypeng is working on that. 

The fix is two-fold: 
 * Double check the pending messages and return error to producer when the dup status is uncertain (eg. message is still pending)
 * Sync back the lastPushed map with the lastStored map after the failures

**Comment by merlimat** [comment]
To clarify one additional aspect: with the default config, this error can only happen if the BK cluster is completely unavailable for writes.

**Comment by sleungtoast** [comment]
Thanks @merlimat. One other thing that we found was when turning off dedupe on the broker config (and doing a restart) instead of dynamically through the API, the dedupe topic was not cleaned up.

**Comment by merlimat** [comment]
You mean the dedup cursor?

**Comment by sleungtoast** [comment]
Yes, sorry that's what I meant.
