### ISSUE TITLE
2.4.1 pulsar-admin should have 8 schema compatibility check strategies

### ISSUE THREAD

**Issue by pouledodue** [apache/pulsar#5222]
**Describe the bug**
2.4.1 `pulsar-admin` should have 8 schema compat check strategy, it only has 3.

**To Reproduce**
```
wget -c https://archive.apache.org/dist/pulsar/pulsar-2.4.1/apache-pulsar-2.4.1-bin.tar.gz
tar mxvfz apache-pulsar-2.4.1-bin.tar.gz
./apache-pulsar-2.4.1/bin/pulsar-admin tenants create a
./apache-pulsar-2.4.1/bin/pulsar-admin namespaces create a/b
./apache-pulsar-2.4.1/bin/pulsar-admin namespaces set-schema-autoupdate-strategy --compatibility always_compatible  a/b
```
gives:
```
null

Reason: Either --compatibility or --disabled must be specified
```
**Expected behavior**
A change of strategy

**Screenshots**

**Desktop (please complete the following information):**
 - OS: catalina

**Comment by sijie** [comment]
@pouledodue : you can use `NONE` for `always_compatible` check policy. The other 3 transitive policies are added recently. It seems that the pulsar-admin is not updated to include them.

@codelipenghui @congbobo184 can you help with this issue?

**Comment by congbobo184** [comment]
@pouledodue now pulsar-admin only support four compatibility strategy, here will have an update. 
you can see [PIP-44](https://github.com/apache/pulsar/wiki/PIP-44%3A-Separate-schema-compatibility-checker-for-producer-and-consumer), auto update schema and compatibility strategy will be separated, #5227

**Comment by sijie** [comment]
@congbobo184 Can you please update the documentation for #5227 ?

**Comment by congbobo184** [comment]
I will update documentation soon.

**Comment by congbobo184** [comment]
#5227 has fixed it.
