### ISSUE TITLE
Segmentation Fault: Mac OS Mojave

### ISSUE THREAD

**Issue by RAbraham** [apache/pulsar#5248]
```bash
➜ fifteenrock-connector> pyenv local 3.7.4
➜  fifteenrock-connector> python
Python 3.7.4 (default, Sep  5 2019, 18:48:02)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
➜  fifteenrock-connector> python -m venv venv
➜  fifteenrock-connector> source venv/bin/activate
(venv) ➜  fifteenrock-connector> pip install pulsar-client  --no-cache-dir
Collecting pulsar-client
  Downloading https://files.pythonhosted.org/packages/76/96/41ec33004a99f2a4eb8b7a0577a5c3e69c7400e139a8753724fde7ae03cb/pulsar_client-2.4.0-cp37-cp37m-macosx_10_14_x86_64.whl (15.5MB)
.....
You are using pip version 19.0.3, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(venv) ➜  fifteenrock-connector> python
Python 3.7.4 (default, Sep  5 2019, 18:48:02)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulsar
[1]    3856 segmentation fault  python

```

Note: I was trying to install from source earlier if that made any difference. I did `brew uninstall libpulsar` before doing the above

**Comment by aahmed-se** [comment]
looks fine to me on mojave

```
 python
Python 2.7.16 (default, Sep  2 2019, 11:59:44) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulsar
>>> 
```

**Comment by pouledodue** [comment]
that wheel was working for me on Mojave.
if you do not find the solution you can build a wheel direct on your mac:
```
git clone https://github.com/apache/pulsar.git
cd pulsar
git checkout branch-2.4
cd pulsar-client-cpp
cmake DPYTHON_LIBRARY="<path_to_libpython3.7.dylib_for_your_installed_python_version>" .
make
cd python
python3 setup.py bdist_wheel
pip uninstall pulsar-client
pip install ./dist/pulsar_client-*.whl
python -c "import pulsar"
```

**Comment by RAbraham** [comment]
@aahmed-se @pouledodue  could you try python3.7? I just tried on python2.7 and python3.6 and it worked for me but not python3.7.4. @pouledodue I'll also try your solution but still wanted to raise the issue, just in case something went wrong with the python3.7 binaries.

**Comment by RAbraham** [comment]
@pouledodue. I see you had the same issue https://github.com/apache/pulsar/issues/5217. Was your resolution, the one above?

**Comment by pouledodue** [comment]
does it work with 3.7.0 or 3.7.3

**Comment by pouledodue** [comment]
my issue #5127 is with Catalina, not Mojave.

**Comment by RAbraham** [comment]
Fails on both 3.7.0 and 3.7.3. To check if my 3.7 binaries are ok, I installed `numpy`(because it may have c extensions like Pulsar)  and `numpy` worked.

**Comment by pouledodue** [comment]
I used successfully 3.7.0 and 3.7.3 in the past with Mojave

**Comment by pouledodue** [comment]
did you try outside pyenv

**Comment by RAbraham** [comment]
@pouledodue I'l try but the python 3.6.8 version I tried it with and worked was using `pyenv`.

**Comment by RAbraham** [comment]
@pouledodue  It worked in 3.7.4 in a non pyenv environment. Thanks for that tip. However, I'm a bit confused as it worked for python 3.6.8 in a pyenv environment and  pyenv is such a blessing when it comes to managing multiple python environments for many projects.
