### ISSUE TITLE
pulsar SQL (Presto) can only query data less than 100000 

### ISSUE THREAD

**Issue by zinohome** [apache/pulsar#5262]
**Describe the bug**
I create a persistent topic named "persistent://public/default/tusr1", use a nifi workflow to read user data from https://randomuser.me/ and push the userdata in to "persistent://public/default/tusr1", then I use pulsar sql to get the message count.
the sql is simply: [ SELECT COUNT(ssn) FROM pulsar."public/default"."tusr1"; ]
I Expected the return value is the message count saved in the bookkeeper ;
but when the messages count up to 100000+, the sql will return 50000+

**To Reproduce**
1. push messages to a persistent topic
2. keep querying "select count(*) from topic name " in presto
3. wait the messages count up to 100000+
4. the "select count(*) from topic name " result will back to 50000+

**Expected behavior**
I expected the query will return the right message count with the "pulsar-admin persistent stats-internal" command

**Screenshots**
I use "pulsar-admin persistent stats-internal persistent://public/default/tusr1" to get the internal stats , got below :
{
"entriesAddedCounter" : 149000,
"numberOfEntries" : 11999,
"totalSize" : 1670626,
"currentLedgerEntries" : 2999,
"currentLedgerSize" : 417685,
"lastLedgerCreatedTimestamp" : "2019-09-23T00:16:38.965Z",
"waitingCursorsCount" : 0,
"pendingAddEntriesCount" : 0,
"lastConfirmedEntry" : "8088:2998",
"state" : "LedgerOpened",
"ledgers" : [ {
"ledgerId" : 5638,
"entries" : 9000,
"size" : 1252941,
"offloaded" : false
}, {
"ledgerId" : 8088,
"entries" : 0,
"size" : 0,
"offloaded" : false
} ],
"cursors" : { }
}

but "SELECT COUNT(ssn) FROM pulsar."public/default"."tusr1";" return 50000+

**Desktop (please complete the following information):**
 - OS: [linux]  pulsar 2.4.1 presto pulsar edition with 2.4.1

**Additional context**
I guess the messages all stored in bookkeeper, but presto only can query 2 segment? is that right ?

anyone can help me to explain this ? and how chan I query all of the messages?

thank you very much

**Comment by liangyuanpeng** [comment]
There are may be other reasons.

I can query 100000+ data

``pulsar-admin persistent stats-internal``  result

```
[root@localhost apache-pulsar-2.4.1-normal]# bin/pulsar-admin persistent stats-internal persistent://public/default/topic-3

{
  "entriesAddedCounter" : 102062,
  "numberOfEntries" : 102062,
  "totalSize" : 7623081,
  "currentLedgerEntries" : 102062,
  "currentLedgerSize" : 7623081,
  "lastLedgerCreatedTimestamp" : "2019-10-11T04:23:27.017+08:00",
  "waitingCursorsCount" : 0,
  "pendingAddEntriesCount" : 0,
  "lastConfirmedEntry" : "6:102061",
  "state" : "LedgerOpened",
  "ledgers" : [ {
    "ledgerId" : 6,
    "entries" : 0,
    "size" : 0,
    "offloaded" : false
  } ],
  "cursors" : { }
}
```

``sql run`` result

```
presto> SELECT COUNT(1) FROM pulsar."public/default"."topic-3";
 _col0  
--------
 102307 
(1 row)

Query 20191010_202608_00012_zu36h, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
1:10 [102K rows, 7.26MB] [1.47K rows/s, 107KB/s]
```

and my test code

```
Producer<byte[]> producer = client.newProducer().topic("persistent://public/default/topic-3").create();

        producer.sendAsync("My message".getBytes());

        ExecutorService executorService = Executors.newFixedThreadPool(100);

        int count = 102400;
        for(int i=0;i<count;i++){
            executorService.execute(new Runnable() {
                @Override
                public void run() {
                    String msg = ("My message"+System.currentTimeMillis()+ RandomUtils.nextInt(1,10000));
                    System.out.println(msg);
                    try {
                        producer.send(msg.getBytes());
                    } catch (PulsarClientException e) {
                        System.out.println(e.getMessage());
                    }
                }
            });
        }
```


pulsar 2.4.1

**Comment by sijie** [comment]
@JointHero 

what is the retention for your topic? did you set the data retention to long enough so that the data will be kept in Pulsar?

**Comment by tisonkun** [comment]
Closed as no response.
