### ISSUE TITLE
It takes too long for the client to reconnect to the broker server

### ISSUE THREAD

**Issue by JoyJava** [apache/pulsar#5264]
**Description error**

producer.serviceUrl("server1:6650,server2:6650,server3:6650")
If the producer connection to server1, kill -9 server1, will cause the producer to reconnect continuously within 2-5 minutes.

This time too long.

**Reproduced**
1. producer.serviceUrl("server1:6650,server2:6650,server3:6650")
2. If the producer is connected to server1
3. kill -9 server1
4. will cause the producer to reconnect continuously within 2-5 minutes.

**Expected behavior**
I hope that pulsar will provide the number of retries and retry time configurations to the user.

**Desktop (please fill in the information below):**
- system: linux, pulsar-2.4

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
