### ISSUE TITLE
presto connector - how to specify cluster (multi broker/zk) connection

### ISSUE THREAD

**Issue by tooptoop4** [apache/pulsar#5287]
**Describe the bug**
Trying to connect existing presto (not part of pulsar distro) to pulsar (multi host cluster)

**To Reproduce**

catalog/pulsar.properties in presto has

```
connector.name=pulsar
# the url of Pulsar broker service
pulsar.broker-service-url=http://yy:8080;xx:8080
# URI of Zookeeper cluster
pulsar.zookeeper-uri=yy,xx:2181
# minimum number of entries to read at a single time
#pulsar.entry-read-batch-size=100
# default number of splits to use per query
pulsar.target-num-splits=4
```

major (1st issue)
```
presto> select * from pulsar."public/functions".assignments;
Query 20190927_164934_00002_q7acj failed: Failed to get topics in schema public/functions: For input string: "8080;xx:8080"
```

There is no documentation about how to provide multi hosts for brokers or zk

minor (2nd issue)
`pulsar.entry-read-batch-size=100 --> this config causes error`

**Expected behavior**
presto can connect to pulsar/zk cluster (multi hosts)

env: using presto .220 and pulsar 2.41

**Comment by sijie** [comment]
@zymap can you please help with this question? If this is not documented, can you work with @Jennifer88huang or @Anonymitaet to add it?

**Comment by zymap** [comment]
@tooptoop4 Sorry for the late response.

If you want to use multi hosts you should use `,` to connect each broker host, not `;`.

@sijie Will add. Thanks for your reminder.
