### ISSUE TITLE
Getting errors when creating JWT

### ISSUE THREAD

**Issue by Loghijiaha** [apache/pulsar#5294]
**Describe the bug**
I created private/public key pairs using :

`$ bin/pulsar tokens create-key-pair --output-private-key my-private.key --output-public-key my-public.key`

And I couldn't create a token using the secretkey 👎 

`bin/pulsar tokens create --private-key file:///path/to/my-private.key \
            --subject test-user`

**To Reproduce**
1. `$ bin/pulsar tokens create-key-pair --output-private-key my-private.key --output-public-key my-public.key`

2.`bin/pulsar tokens create --private-key file:///path/to/my-private.key \
            --subject test-user`

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by tuteng** [comment]
Can you write more detailed information, such as the version of the pulsar, whether there are exceptions thrown, and if so, what are the exceptions? @Loghijiaha 

Note: path needs to be replaced by your real path

**Comment by sijie** [comment]
@Loghijiaha Can you provide the error messages you encountered when you ran the commands?

**Comment by sijie** [comment]
Since there are no more details to look into this issue, close it for now.
