### ISSUE TITLE
Loading certificates from classpath rather from filesystem

### ISSUE THREAD

**Issue by vl185050** [apache/pulsar#5304]
**Is your feature request related to a problem? Please describe.**
running pulsar consumer program as java -jar target\xyz.jar .
For authentication, it could NOT load certificates file from classpath under the resource folder and throws file not found an exception.

**Describe the solution you'd like**
It should also be able to load the certificates from the classpath folder and from file system

**Describe alternatives you've considered**

**Additional context**

**Comment by sijie** [comment]
@vl185050 can you provide more information about how do you configure the certificates file?

**Comment by tisonkun** [comment]
Closed as stale. If the issue is still valid in the maintained versions, you can open a new issue with repros.
