### ISSUE TITLE
[docs] Clarify wording around retention policies

### ISSUE THREAD

**Issue by rocketraman** [apache/pulsar#5309]
In section https://pulsar.apache.org/docs/en/cookbooks-retention-expiry/#retention-policies, this text appears:

> When you set a size limit of, say, 10 gigabytes, then messages in all topics in the namespace, even acknowledged messages, will be retained until the size limit for the topic is reached; if you set a time limit of, say, 1 day, then messages for all topics in the namespace will be retained for 24 hours.

The "**even** acknowledged messages" seems to imply the settings apply to all messages, both unacked and acked.

As I understand the retention settings, these apply *only* to acknowledged messages, which implies that unacked messages are retained indefinitely (or actually as per the backlog quota size and retention policy). So I think this wording would be clearer if it said something like this:

> When you set a size limit of, say, 10 gigabytes, then acknowledged messages in all topics in the namespace will be retained until the size limit for the topic is reached; if you set a time limit of, say, 1 day, then acknowledged messages for all topics in the namespace will be retained for 24 hours. The retention settings do not affect unacknowledged messages -- these are instead controlled by the backlog quota and retention policy.

Let me know if this is correct, and if so, I would be happy to submit a pull request.

**Comment by rocketraman** [comment]
Never mind, I was confused.

**Comment by sijie** [comment]
@rocketraman your understanding is correct. Can you submit a pull request for it?

**Comment by rocketraman** [comment]
Pull request submitted.
