### ISSUE TITLE
Mysterious random errorless failures of functions and sinks - only resolved by restarting brokers

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#5311]
**Describe the bug**
This incident has been occurring approximately once every 2 weeks or so. In the most recent case, two of our functions mysteriously stopped working. 
No user or system exceptions were being thrown on the functions. The only way we determined that there was a problem was due to accumulating backlog. Restarting the functions had no effect. There were no errors in their function logs.
I checked the broker logs on a node that was running one of the function instances and found this exception occurring approximately once every 30 seconds:

> 05:00:33.974 [ForkJoinPool.commonPool-worker-29] WARN  org.apache.pulsar.broker.service.ServerCnx - [/10.20.69.19:50624][persistent://product-infrastructure/ingest/example-topic][product-infrastructure/ingest/example-function-Transformer] Failed to create consumer: Trying to subscribe with incompatible schema
> java.util.concurrent.CompletionException: org.apache.pulsar.broker.service.schema.IncompatibleSchemaException: Trying to subscribe with incompatible schema
>     at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326) ~[?:1.8.0_212]
>     at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338) ~[?:1.8.0_212]
>     at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911) ~[?:1.8.0_212]
>     at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:953) ~[?:1.8.0_212]
>     at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_212]
>     at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_212]
>     at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[?:1.8.0_212]
>     at org.apache.pulsar.broker.service.schema.BookkeeperSchemaStorage.lambda$null$2(BookkeeperSchemaStorage.java:157) ~[org.apache.pulsar-pulsar-broker-2.4.0-streamlio-24.jar:2.4.0-streamlio-24]
>     at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822) [?:1.8.0_212]
>     at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797) [?:1.8.0_212]
>     at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) [?:1.8.0_212]
>     at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212]
>     at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212]
>     at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212]
>     at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212]
> Caused by: org.apache.pulsar.broker.service.schema.IncompatibleSchemaException: Trying to subscribe with incompatible schema
>     at org.apache.pulsar.broker.service.ServerCnx.lambda$null$9(ServerCnx.java:688) ~[org.apache.pulsar-pulsar-broker-2.4.0-streamlio-24.jar:2.4.0-streamlio-24]
>     at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_212]
>     ... 11 more

Due to the schema error, I checked the input and output topic schemas for the functions and discovered that Pulsar mysteriously lost the schemas of both the input and output topics of the first function and the output topic of the second function:

e.g. For the second function:

> [(prod) root@example.domain.com ~]# pulsar-admin schemas get persistent://graph/exampleNamespace/output-topic
> Not Found
> 
> Reason: Not Found
> [(prod) root@example.domain.com ~]# pulsar-admin schemas get persistent://graph/exampleNamespace/input-topic
> {
>   "name" : "input-topic",
>   "schema" : "",
>   "type" : "STRING",
>   "properties" : { }
> }

All of the functions are just using the same basic STRING schema for input and output topics.

I uploaded new schemas for the input topic and output topic for the first function and was able to get the uploaded schemas back from those topics when I ran a `get` on them.
However, after doing this, the missing schema for the second function mysteriously returned, even though I never uploaded a new schema for it. There is no clear explanation for why this happened. 
Despite these changes, the backlogs did not start dropping.

In some of the other broker logs, I found these errors:

>     02:31:12.941 [bookkeeper-ml-scheduler-OrderedScheduler-3-0] ERROR org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Failed to add entry for ledger -1 in time-out 120 sec
>     02:35:04.608 [bookkeeper-ml-scheduler-OrderedScheduler-6-0] ERROR org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Failed to add entry for ledger -1 in time-out 120 sec
>     02:40:07.090 [bookkeeper-ml-scheduler-OrderedScheduler-5-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught
>     02:40:07.262 [bookkeeper-ml-scheduler-OrderedScheduler-5-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught
>     02:40:07.361 [bookkeeper-ml-scheduler-OrderedScheduler-5-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught
> . . . 
>     04:26:59.713 [bookkeeper-ml-scheduler-OrderedScheduler-4-0] ERROR org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Failed to add entry for ledger -1 in time-out 120 sec
>     04:32:57.172 [bookkeeper-ml-scheduler-OrderedScheduler-1-0] ERROR org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Failed to add entry for ledger -1 in time-out 120 sec
>     04:32:59.712 [bookkeeper-ml-scheduler-OrderedScheduler-4-0] ERROR org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Failed to add entry for ledger -1 in time-out 120 sec
>     04:34:59.713 [bookkeeper-ml-scheduler-OrderedScheduler-4-0] ERROR org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Failed to add entry for ledger -1 in time-out 120 sec
>     04:50:59.713 [bookkeeper-ml-scheduler-OrderedScheduler-4-0] ERROR org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Failed to add entry for ledger -1 in time-out 120 sec
>     04:58:59.713 [bookkeeper-ml-scheduler-OrderedScheduler-4-0] ERROR org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Failed to add entry for ledger -1 in time-out 120 sec
>     05:44:59.713 [bookkeeper-ml-scheduler-OrderedScheduler-4-0] ERROR org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Failed to add entry for ledger -1 in time-out 120 sec
> . . . 

So, I checked the bookie logs and found this on one of the bookies:

> I found this in one of the bookie logs:
> 03:14:51.117 [ZKC-connect-executor-0-EventThread] ERROR org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client connection to the ZooKeeper server has expired!
>     03:30:18.128 [ZKC-connect-executor-0-EventThread] ERROR org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client connection to the ZooKeeper server has expired!
>     04:16:27.973 [ZKC-connect-executor-0-EventThread] ERROR org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client connection to the ZooKeeper server has expired!
>     04:30:27.767 [ZKC-connect-executor-0-EventThread] ERROR org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client connection to the ZooKeeper server has expired!
>     04:45:27.611 [ZKC-connect-executor-0-EventThread] ERROR org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client connection to the ZooKeeper server has expired!
>     05:01:11.128 [ZKC-connect-executor-0-EventThread] ERROR org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client connection to the ZooKeeper server has expired!
>     05:16:06.869 [ZKC-connect-executor-0-EventThread] ERROR org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client connection to the ZooKeeper server has expired!
>     05:44:17.705 [ZKC-connect-executor-0-EventThread] ERROR org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client connection to the ZooKeeper server has expired!

I found this on one of the other bookies:

> 02:18:26.078 [ZKC-connect-executor-0-EventThread] ERROR org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client connection to the ZooKeeper server has expired!
>     02:19:13.031 [DLM-/stream/storage-OrderedScheduler-22-0] ERROR org.apache.distributedlog.BKAbstractLogWriter - Completing Log segments encountered exception
>     02:19:43.502 [io-checkpoint-scheduler-OrderedScheduler-1-0] ERROR org.apache.bookkeeper.statelib.impl.rocksdb.checkpoint.RocksdbCheckpointTask - Failed to checkpoint db 000000000000000000/000000000000000001/000000000000000000 to dir /pulsar/data/bookkeeper/ranges/ranges/000000000000000000/000000000000000001/000000000000000000/checkpoints/d0ee2a6b-33e8-4148-a6bd-cc027c97e200
>     02:19:43.504 [io-checkpoint-scheduler-OrderedScheduler-1-0] ERROR org.apache.bookkeeper.statelib.impl.kv.RocksdbKVStore - Failed to checkpoint state store 000000000000000000/000000000000000001/000000000000000000 at revision 0
>     03:35:11.163 [ZKC-connect-executor-0-EventThread] ERROR org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client connection to the ZooKeeper server has expired!
>     04:15:14.241 [ZKC-connect-executor-0-EventThread] ERROR org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client connection to the ZooKeeper server has expired!

So, I checked the Zookeeper logs for clues but didn't find much information. Here's what I found:

> 06:01:31.436 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] INFO  org.apache.zookeeper.server.NIOServerCnxnFactory - Accepted socket connection from /10.20.17.42:54387
>     06:01:31.436 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] WARN  org.apache.zookeeper.server.NIOServerCnxn - Unable to read additional data from client sessionid 0x0, likely client has closed socket
>     06:01:31.436 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] INFO  org.apache.zookeeper.server.NIOServerCnxn - Closed socket connection for client /10.20.17.42:54387 (no session established for client)
>     06:01:37.795 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] INFO  org.apache.zookeeper.server.NIOServerCnxnFactory - Accepted socket connection from /10.20.17.40:59796
>     06:01:37.796 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] WARN  org.apache.zookeeper.server.NIOServerCnxn - Unable to read additional data from client sessionid 0x0, likely client has closed socket
>     06:01:37.796 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] INFO  org.apache.zookeeper.server.NIOServerCnxn - Closed socket connection for client /10.20.17.40:59796 (no session established for client)
>     06:01:41.436 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] INFO  org.apache.zookeeper.server.NIOServerCnxnFactory - Accepted socket connection from /10.20.17.42:54388
>     06:01:41.436 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] WARN  org.apache.zookeeper.server.NIOServerCnxn - Unable to read additional data from client sessionid 0x0, likely client has closed socket
>     06:01:41.436 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] INFO  org.apache.zookeeper.server.NIOServerCnxn - Closed socket connection for client /10.20.17.42:54388 (no session established for client)
>     06:01:42.365 [CommitProcessor:1] INFO  org.apache.zookeeper.server.NIOServerCnxn - Closed socket connection for client /10.20.69.16:54722 which had sessionid 0x103ee5b2be70065

I also found this in one of the Zookeeper logs:

> 06:02:18.885 [ProcessThread(sid:3 cport:-1):] INFO  org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x203ee709048001c type:delete cxid:0xef2875 zxid:0x1a10394f80d txntype:-1 reqpath:n/a Error Path:/ledgers/05/9481 Error:KeeperErrorCode = Directory not empty for /ledgers/05/9481
>     06:02:18.899 [ProcessThread(sid:3 cport:-1):] INFO  org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x203ee709048001d type:delete cxid:0x9b7ab8 zxid:0x1a10394f814 txntype:-1 reqpath:n/a Error Path:/ledgers/05/9481 Error:KeeperErrorCode = Directory not empty for /ledgers/05/9481
>     06:02:18.899 [ProcessThread(sid:3 cport:-1):] INFO  org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x203ee709048001d type:delete cxid:0x9b7ab9 zxid:0x1a10394f815 txntype:-1 reqpath:n/a Error Path:/ledgers/05/9481 Error:KeeperErrorCode = Directory not empty for /ledgers/05/9481
>     06:02:18.899 [ProcessThread(sid:3 cport:-1):] INFO  org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x203ee709048001d type:delete cxid:0x9b7aba zxid:0x1a10394f816 txntype:-1 reqpath:n/a Error Path:/ledgers/05/9481 Error:KeeperErrorCode = Directory not empty for /ledgers/05/9481
>     06:02:18.899 [ProcessThread(sid:3 cport:-1):] INFO  org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x203ee709048001d type:delete cxid:0x9b7abb zxid:0x1a10394f817 txntype:-1 reqpath:n/a Error Path:/ledgers/05/9481 Error:KeeperErrorCode = Directory not empty for /ledgers/05/9481
>     06:02:18.921 [ProcessThread(sid:3 cport:-1):] INFO  org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x103ee5b2be7001c type:delete cxid:0x7ecbe2 zxid:0x1a10394f828 txntype:-1 reqpath:n/a Error Path:/ledgers/05/9481 Error:KeeperErrorCode = Directory not empty for /ledgers/05/9481
>     06:02:18.922 [ProcessThread(sid:3 cport:-1):] INFO  org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x203ee7090480018 type:delete cxid:0x9aa6cb zxid:0x1a10394f829 txntype:-1 reqpath:n/a Error Path:/ledgers/05/9481 Error:KeeperErrorCode = Directory not empty for /ledgers/05/9481
>     06:02:18.922 [ProcessThread(sid:3 cport:-1):] INFO  org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x103ee5b2be7001c type:delete cxid:0x7ecbe3 zxid:0x1a10394f82a txntype:-1 reqpath:n/a Error Path:/ledgers/05/9481 Error:KeeperErrorCode = Directory not empty for /ledgers/05/9481
>     06:02:19.052 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] INFO  org.apache.zookeeper.server.NIOServerCnxnFactory - Accepted socket connection from /10.20.17.42:22997
>     06:02:19.053 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] WARN  org.apache.zookeeper.server.NIOServerCnxn - Unable to read additional data from client sessionid 0x0, likely client has closed socket
>     06:02:19.053 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] INFO  org.apache.zookeeper.server.NIOServerCnxn - Closed socket connection for client /10.20.17.42:22997 (no session established for client)

It seems unlikely (though possible) that the issue is being caused by resource contention on the Zookeeper nodes because those nodes are only running Zookeeper. 

The only other changes we made prior to the incident were that approximately 12 hours prior to the incident, several Jars were updated for functions and sinks in the cluster. 

This problem is ONLY resolved once we perform a rolling restart of all of the brokers in the cluster. 

**To Reproduce**
We do not yet know how to reproduce the issue. 

**Expected behavior**
The functions should not be unhealthy and failing to process messages without any errors being reported.

**Environment:**
We're running the dockerized Apache Pulsar 2.4.0 in a cluster with dedicated Zookeeper nodes. The brokers are currently running without dedicated function worker nodes. (The broker nodes are the function worker nodes.) The bookies are distributed throughout the cluster. 
Pulsar is running most of the configurations with default settings. We're using token authentication and running Pulsar functions in process mode. 

Our bookies are still running Pulsar 2.3.0.

We have occasionally noticed that our Prometheus metrics will cause a significant spike in IOPS on the cluster right around the time that the functions die. We do not yet know the cause of this spike. 

Here is a picture that shows the random spikes in IOPS:
![image](https://user-images.githubusercontent.com/7418031/66168831-9b813900-e5fb-11e9-914a-bf0144e4e958.png)

Here's another picture that shows the spike in IOPS:
![image](https://user-images.githubusercontent.com/7418031/66169123-907ad880-e5fc-11e9-861e-b0878a0bdb23.png)

We also captured more log content on a couple of the broker nodes, so we can provide that upon request.

**Comment by sijie** [comment]
@codelipenghui @wolfstudy can you help with this issue?

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.

I can see several PRs are against this issue.
