### ISSUE TITLE
Function REST API documentation is insufficient for Create POST action

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#5312]
**Describe the bug**

I’m attempting to create a function through the REST API, and I’m getting a 415 Unsupported Media Type response. I had this same issue when creating a PUT to create a new tenant through the REST API, but I resolved that issue by setting the content type to "application/json; charset=utf-8". However, with the POST of the function, I’m still getting this issue. 

**To Reproduce**

In the docs (https://pulsar.apache.org/functions-rest-api/?version=2.4.1#operation/registerFunction), the example of the expected POST body is this:
```
{
  "inputs": persistent://public/default/input-topic,
  "parallelism": 4
  "output": persistent://public/default/output-topic
  "log-topic": persistent://public/default/log-topic
  "classname": org.example.test.ExclamationFunction
  "jar": java-function-1.0-SNAPSHOT.jar
}
```

I’ve checked the POST body that I'm sending via Wireshark, and the content is valid JSON.
This is my post body:
`{"namespace":"exampleNamespace","tenant":"exampleTenant","name":"exampleFunction","jar":"http://repository.domain.com/example-jar-1.0.1-20191001.001216-48-jar-with-dependencies.jar","className":"com.overstock.path.to.class","output":"persistent://exampleTenant/exampleNamespace/exampleOutputTopic","logTopic":"persistent://exampleTenant/exampleNamespace/exampleLogTopic","inputs":["persistent://exampleTenant/exampleNamespace/exampleInputTopic"],"userConfig":{"hostname":"endpoint.domain.com","port":"9082"}}`

The method I'm using to send this JSON string is this (written in Golang):

```
func createPost(serviceURL string, messageBody string) *http.Response {
    var netClient = &http.Client{
        Timeout: time.Second * 10,
    }
    log.Println("This is the body of our POST:")
    log.Println(messageBody)
    //msgBodyMarshalled, _ := json.Marshal(messageBody)
    msgBodyMarshalled := []byte(messageBody)
    resp, err := netClient.Post(serviceURL, "application/json; charset=utf-8", bytes.NewBuffer(msgBodyMarshalled))
    if err != nil {
        log.Fatalln(err)
    }
    defer resp.Body.Close()

    body, err := ioutil.ReadAll(resp.Body)
    if err != nil {
        log.Fatalln(err)
    }
    log.Println(string(body))
    return resp
}
```

In the source code for the endpoint, it’s not clear how the post body is translated to the endpoint because the expected parameters do not match the docs cited above (https://pulsar.apache.org/functions-rest-api/?version=2.4.1#operation/registerFunction):

```
public FunctionsApiV3Resource() {
        this.functions = new FunctionsImpl(this);
    }

    @POST
    @Path("/{tenant}/{namespace}/{functionName}")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    public void registerFunction(final @PathParam("tenant") String tenant,
                                 final @PathParam("namespace") String namespace,
                                 final @PathParam("functionName") String functionName,
                                 final @FormDataParam("data") InputStream uploadedInputStream,
                                 final @FormDataParam("data") FormDataContentDisposition fileDetail,
                                 final @FormDataParam("url") String functionPkgUrl,
                                 final @FormDataParam("functionConfig") FunctionConfig functionConfig) {

        functions.registerFunction(tenant, namespace, functionName, uploadedInputStream, fileDetail,
                functionPkgUrl, functionConfig, clientAppId(), clientAuthData());
    }
```

From the Glassfish docs on @FormDataParam, it appears that the expected content type is actually `multipart/form-data`, not `application/json`. To investigate this, I created a Wireshark capture of a Functions Create message being sent from the Pulsar Admin CLI. Sure enough, the content of the message is `multipart/form-data`, not `application/json`. 

**Expected behavior**
The Pulsar docs should provide a clearer example of what is expected as the body for a POST for Functions Create. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7418031/66170969-b9eb3280-e603-11e9-860d-c52b7c4d9b57.png)

**Comment by Guchman** [comment]
I think expected behaviour is to support application/json:)

**Comment by devinbost** [comment]
Here's additional detail that I get from Wireshark on the content of the `multipart/form-data` message:

```
POST /admin/v3/functions/public/default/exampleFunction HTTP/1.1
Accept: application/json
Content-Type: multipart/form-data;boundary=Boundary_1_624637962_1570145452774
MIME-Version: 1.0
content-length: 623
host: localhost:8080
user-agent: Pulsar-Java-v2.4.0

--Boundary_1_624637962_1570145452774
Content-Type: text/plain
Content-Disposition: form-data; name="url"

http://example.com/1.0.1-20191001.001216-48-jar-with-dependencies.jar
--Boundary_1_624637962_1570145452774
Content-Type: application/json
Content-Disposition: form-data; name="functionConfig"

{"tenant":"public","namespace":"default","name":"exampleFunction","className":"com.path.to.class","inputs":["persistent://public/default/exampleInputTopic"],"outputSchemaType":"","userConfig":{},"jar":"http://example.com/1.0.1-20191001.001216-48-jar-with-dependencies.jar"}
--Boundary_1_624637962_1570145452774--
```

**Comment by devinbost** [comment]
Also, I found the code for the CLI in org.apache.pulsar.client.admin.internal.FunctionsImpl.java, which contains:

```
    @Override
    public void updateFunctionWithUrl(FunctionConfig functionConfig, String pkgUrl, UpdateOptions updateOptions) throws PulsarAdminException {
        try {
            final FormDataMultiPart mp = new FormDataMultiPart();

            mp.bodyPart(new FormDataBodyPart("url", pkgUrl, MediaType.TEXT_PLAIN_TYPE));

            mp.bodyPart(new FormDataBodyPart(
                    "functionConfig",
                    ObjectMapperFactory.getThreadLocal().writeValueAsString(functionConfig),
                    MediaType.APPLICATION_JSON_TYPE));

            if (updateOptions != null) {
                mp.bodyPart(new FormDataBodyPart(
                        "updateOptions",
                        ObjectMapperFactory.getThreadLocal().writeValueAsString(updateOptions),
                        MediaType.APPLICATION_JSON_TYPE));
            }

            request(functions.path(functionConfig.getTenant()).path(functionConfig.getNamespace())
                    .path(functionConfig.getName())).put(Entity.entity(mp, MediaType.MULTIPART_FORM_DATA),
                    ErrorData.class);
        } catch (Exception e) {
            throw getApiException(e);
        }
    }
```

**Comment by devinbost** [comment]
> I think expected behaviour is to support application/json:)

I think the issue is that when uploading a Jar from a local path, it needs to be uploaded as a binary object. So, I think that's why they're using `multipart/form-data`, rather than `application/json`.

**Comment by Guchman** [comment]
> > I think expected behaviour is to support application/json:)
> 
> I think the issue is that when uploading a Jar from a local path, it needs to be uploaded as a binary object. So, I think that's why they're using `multipart/form-data`, rather than `application/json`.

But when you send not jar file, but http link to file I'll be more clear to use application/json. Probably it must be different options

**Comment by wolfstudy** [comment]
@devinbost Sorry, I missed this message.

The REST API for create function should be correct. In [pulsarctl](https://github.com/streamnative/pulsarctl/blob/master/pkg/pulsar/functions.go#L142), I also called this REST API and successfully created the function.

Copy the code from pulsarctl:

```
func (f *functions) createStringFromField(w *multipart.Writer, value string) (io.Writer, error) {
	h := make(textproto.MIMEHeader)
	h.Set("Content-Disposition", fmt.Sprintf(`form-data; name="%s" `, value))
	h.Set("Content-Type", "application/json")
	return w.CreatePart(h)
}

func (f *functions) CreateFunc(funcConf *utils.FunctionConfig, fileName string) error {
	endpoint := f.client.endpoint(f.basePath, funcConf.Tenant, funcConf.Namespace, funcConf.Name)

	// buffer to store our request as bytes
	bodyBuf := bytes.NewBufferString("")

	multiPartWriter := multipart.NewWriter(bodyBuf)

	jsonData, err := json.Marshal(funcConf)
	if err != nil {
		return err
	}

	stringWriter, err := f.createStringFromField(multiPartWriter, "functionConfig")
	if err != nil {
		return err
	}

	_, err = stringWriter.Write(jsonData)
	if err != nil {
		return err
	}

	if fileName != "" && !strings.HasPrefix(fileName, "builtin://") {
		// If the function code is built in, we don't need to submit here
		file, err := os.Open(fileName)
		if err != nil {
			return err
		}
		defer file.Close()

		part, err := multiPartWriter.CreateFormFile("data", filepath.Base(file.Name()))

		if err != nil {
			return err
		}

		// copy the actual file content to the filed's writer
		_, err = io.Copy(part, file)
		if err != nil {
			return err
		}
	}

	// In here, we completed adding the file and the fields, let's close the multipart writer
	// So it writes the ending boundary
	if err = multiPartWriter.Close(); err != nil {
		return err
	}

	contentType := multiPartWriter.FormDataContentType()
	err = f.client.postWithMultiPart(endpoint, nil, bodyBuf, contentType)
	if err != nil {
		return err
	}

	return nil
}
```

**Comment by wolfstudy** [comment]
@devinbost I will close this pull request first. If you have any issues, please let me know, thanks.

**Comment by oginskis** [comment]
Does anybody have a `curl` example that POSTs the function directly using the API?

**Comment by odmarkj** [comment]
This shouldn't have been closed. The API documentation is incorrect at the very least.

**Comment by devinbost** [comment]
@odmarkj Could you please provide some additional information on what is incorrect in the current documentation? If you can do that, I'm sure we can re-open this issue.

**Comment by odmarkj** [comment]
Your comments on this thread were pretty verbose in explaining the issue.

https://pulsar.apache.org/functions-rest-api/?version=2.7.1&apiversion=v3#operation/registerFunction

This documentation does not work as described.

It has to be formatted like you mentioned, as two parts with their own content type:

--Boundary_1_624637962_1570145452774
Content-Type: text/plain
Content-Disposition: form-data; name="url"

http://example.com/1.0.1-20191001.001216-48-jar-with-dependencies.jar
--Boundary_1_624637962_1570145452774
Content-Type: application/json
Content-Disposition: form-data; name="functionConfig"

{"tenant":"public","namespace":"default","name":"exampleFunction","className":"com.path.to.class","inputs":["persistent://public/default/exampleInputTopic"],"outputSchemaType":"","userConfig":{},"jar":"http://example.com/1.0.1-20191001.001216-48-jar-with-dependencies.jar"}
--Boundary_1_624637962_1570145452774--

**Comment by devinbost** [comment]
@wolfstudy Could you please take another look at this?

**Comment by odmarkj** [comment]
Also, for others coming to this thread, this Python code works:

```
import requests
from requests_toolbelt.multipart.encoder import MultipartEncoder

url = 'http://localhost:8080/admin/v3/functions/public/default/exampleFunction3232'

mp_encoder = MultipartEncoder(
    fields={
        'functionConfig': ('functionConfig', '{"runtime":"PYTHON","name":"exampleFunction3232","parallelism":1,"tenant":"public","namespace":"default","className":"csv_test.src.wrapper.Wrapper","inputs":["non-persistent://public/default/in"]}', 'application/json'),
        'data': ('688b4a39f351fd4725edc2ba1d6a5937.zip', open('/tmp/688b4a39f351fd4725edc2ba1d6a5937.zip', 'rb'), 'application/octet-stream')
    }
)

r = requests.post(
    url,
    data=mp_encoder,
    headers={'Content-Type': mp_encoder.content_type}
)
```

**Comment by Kelly-ZH** [comment]
@devinbost hello, do you have a curl example that POSTs the function directly using the API? Thank you very much.

**Comment by kingdom998** [comment]
> 
I solved it with curl expression below in my env.
curl --location --request POST 'http://127.0.0.1:8080/admin/v3/functions/sample/ns1/toupper' \
--header 'Content-Disposition;' \
--form 'data=@"/Users/zy/01_prj/pulsar/func/uppercase.py"' \
--form 'functionConfig=@"/Users/zy/01_prj/pulsar/func/upper.json"'
