### ISSUE TITLE
pulsar released package missing configuraion for ranges from bookkie

### ISSUE THREAD

**Issue by hanbo1990** [apache/pulsar#5326]
**Describe the bug**
Standalone pulsar's bookie creates data/ranges folder even bookkeeper's data path is changed to another folder. This data/ranges folder is used by data.bookkeeper.ranges, which can be configured in the bookkeeper package downloaded from apache bookkeeper but not pulsar.

**To Reproduce**
1. Go to the conf folder and change all data paths of the bookie. Don't use any path containing `data/`
2. Execute standalone with `--bookkeeper-dir` pointing to other locations outside PULSAR_HOME for some time.

**Expected behavior**
No data/ranges should exist because bookkeeper's data folder is changed to another location, but I can still see it.

**Comment by sijie** [comment]
@hanbo1990 yeah, this should be simple fix. do you want to try to make a contribution to this?

**Comment by hanbo1990** [comment]
Sure, I will do it.

**Comment by hanbo1990** [comment]
I am going to create a config interface in pulsar's bookie.conf  `# local storage directories for storing table ranges data (e.g.  sst files)
storage.range.store.dirs=data/bookkeeper/ranges   

# whether the storage server capable of serving readonly tables. default is false.
storage.serve.readonly.tables=false

# the cluster controller schedule interval, in milliseconds. default is 30 seconds.
storage.cluster.controller.schedule.interval.ms=30000`  Is that fine?
