### ISSUE TITLE
[Doc] Fix doc issues related to BookKeeper, Python Client, and so on

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#5345]
Fix some issues reported by @candlerb (b.candler@pobox.com):

![image](https://user-images.githubusercontent.com/50226895/66488067-f0332100-eadf-11e9-9c4b-4a8c2bdf19c2.png)

**Comment by sijie** [comment]
@Anonymitaet was this fixed?

**Comment by Anonymitaet** [comment]
@sijie Not yet, I'll fix it.

**Comment by Anonymitaet** [comment]
* Inconsistent and incorrect issues have been fixed in 

* Broken links issues have been fixed in 

* For Python API doc, as discussed with @tuteng, the correct information on http://pulsar.apache.org/api/python/ should be:

![image](https://user-images.githubusercontent.com/50226895/67918188-3ad32500-fbd6-11e9-8e2c-4944f5148de5.png)

This website is automatically generated and cannot be modified from my side.

We've reported this issue to ASF, waiting for the response.

**Comment by candlerb** [comment]
The python version message is from [`pulsar-client-cpp/python/pulsar/__init__.py`](https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/python/pulsar/__init__.py#L24)

Therefore I think it should be sufficient to update it there, and then somehow republish the API docs (maybe this won't happen until a new version of the package is pushed into pip?)

**Comment by Anonymitaet** [comment]
@tuteng, any thoughts on the @candlerb's comment?

**Comment by tuteng** [comment]
@candlerb you are right, we need to update file https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/python/pulsar/__init__.py#L24

**Comment by Anonymitaet** [comment]
@tuteng @candlerb I've updated the file https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/python/pulsar/__init__.py#L24 in https://github.com/apache/pulsar/pull/5649
