### ISSUE TITLE
bin/pulsar standalone --zookeeper-port 2183 does not work with version 2.4.1

### ISSUE THREAD

**Issue by ccronemberger** [apache/pulsar#5346]
I need to run Zookeeper in a different port number, so I specify "--zookeeper-port 2183" in the command line, but it is still using default port 2181 in the BookieServer configuration. As you can see in the attached log.

**To Reproduce**
1. Go to Pulsar installation directory
2. Run the command "bin/pulsar standalone --zookeeper-port 2183"
3. Search for 2181 in the logs
4. You will find it in the zookeeperServers property in the log generate for org.apache.bookkeeper.proto.BookieServer.

**Expected behavior**
It should use the specified port in all places. I even tried to change the configuration in the bookkeeper.conf file, but it didn't help.

**Desktop :**
 - OS: uname -a
Linux GFT_BTB 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

[output.log](https://github.com/apache/pulsar/files/3707871/output.log)

**Comment by sijie** [comment]
@ccronemberger did you change standalone.conf (which is the right conf used by pulsar standalone)?

**Comment by ccronemberger** [comment]
Hi,
Yes, I have changed all places were I found port 2181. I will double check anyway.
Regards,    Constantino

Enviado do Yahoo Mail no Android 
 
  <div>Em dom, 27 27e out 27e 2019 às 13:51, Sijie Guo</div><div><notifications@github.com> escreveu:</div>   
@ccronemberger did you change standalone.conf (which is the right conf used by pulsar standalone)?
