### ISSUE TITLE
UnAckedMessageTracker: 3600 messages have timed-out... but they haven't?

### ISSUE THREAD

**Issue by rocketraman** [apache/pulsar#5349]
**Describe the bug**
~I've deployed a topic into Pulsar 2.4.1 with default configuration for message TTL, which as I understand it should mean that unacked messages should be retained forever.~ 

UPDATE: I've realized the UnAckedMessageTracker does something different than I thought it did. The behavior is still unexplained though.

I've deployed a topic into Pulsar and my consumers are configured with ackTimeout = 60 minutes. However, my consumers always either negative ack or ack messages. There may be rare situations in which neither of these happen (application crash or network problem), but for some reason my consumers consistently and periodically report:

```
org.apa.pul.cli.imp.UnAckedMessageTracker : [ConsumerBase{subscription='my-sub', consumerName='my-consumer', topic='persistent://dev/my-ns/q'}] 3600 messages have timed-out
```

I've seen this on 3 separate environments, starting the topic and associated subscriptions from scratch. Subscriptions are Shared, and configured to start at position "earliest".

The value is always 3600. In all 3 environments, which have vastly different numbers of messages in the topic, the number is always 3600. In some environments I don't believe 3600 messages were even placed into the topic, so it shouldn't be possible for there to be 3600 unacked messages.

This doesn't actually appear to cause any problems -- everything seems to be working normally. Its just an annoying message to see.

**To Reproduce**
1. Create a topic with default settings, change retention size to -1 and retention period to 1 hour (I can't see how these settings would be relevant, but that's what my topics have).
2. Produce and consume some messages from the topic, ensure they are all acked or nacked.
3. Wait until the warning is reported.

**Expected behavior**
No warning.

**Comment by Jesse-Zhang-Bose** [comment]
I have seen the same.

**Comment by jiazhai** [comment]
will look into it.
