### ISSUE TITLE
[website] Some company logos are not displayed well on poweredby website

### ISSUE THREAD

**Issue by Jennifer88huang** [apache/pulsar#5362]
**Describe the bug**
Some company logos are not displayed well on website http://pulsar.apache.org/powered-by/

![image](https://user-images.githubusercontent.com/47805623/66643570-9488a500-ec51-11e9-978a-aa3aad9e8547.png)
![image](https://user-images.githubusercontent.com/47805623/66643578-9ce0e000-ec51-11e9-842e-f6fbd9362a99.png)
![image](https://user-images.githubusercontent.com/47805623/66643597-a407ee00-ec51-11e9-9a04-68b3ed0d9bcd.png)

**Comment by liangyuanpeng** [comment]
Actually, five

**Comment by Jennifer88huang** [comment]
What's the other one?

**Comment by liangyuanpeng** [comment]
![image](https://user-images.githubusercontent.com/28711504/66660814-75e9d480-ec78-11e9-8133-22b84ca5c919.png)

...

**Comment by merlimat** [comment]
That's because the logo img url is HTTP and we're serving the page with HTTPS.

**Comment by Jennifer88huang** [comment]
@liangyuanpeng I see, there are some differences in display on our PC. "Giggso" and "Onde" display well on my PC.
@merlimat Is there a solution for this?

**Comment by tuteng** [comment]
It seems that the links to some images are incorrect.

**Comment by liangyuanpeng** [comment]
![image](https://user-images.githubusercontent.com/28711504/66693561-d1e64480-ecdc-11e9-8fc5-af63e9d61181.png)


This is what I saw in firefox

**Comment by Jennifer88huang** [comment]
I've just fixed the issue in https://github.com/apache/pulsar/pull/5374, and build it locally, now all of them display well on website now.
The following image comes from my local update.
![image](https://user-images.githubusercontent.com/47805623/66693763-415d3380-ecdf-11e9-9ac1-1c28985a2e28.png)
