### ISSUE TITLE
[docs] Contradictory information about what versions of python are supported

### ISSUE THREAD

**Issue by Jennifer88huang** [apache/pulsar#5368]
**Describe the bug**
There is contradictory information about what versions of python are supported.  
1. It says that versions 3.4-3.7 are supported at http://pulsar.apache.org/docs/en/client-libraries-python/ 
2. It says that only version 2.7 is supported at http://pulsar.apache.org/api/python/ 
The info is out-of-date and needs regenerating.
3. python3 now being supported, there is other new functionality
which is not shown: e.g.

- Client.create_producer and Client.create_reader can take a "schema"
argument
- Message.value()   contains the object deserialized via schema

Note: The issue is found and reported by Brian (b.candler@pobox.com). Thank Brian for his contribution.

**Comment by Jennifer88huang** [comment]
@merlimat @jerrypeng @sijie The generated API files are not copied to the right path, could you please help to resolve the issue?
![image](https://user-images.githubusercontent.com/47805623/66693229-6058c700-ecd9-11e9-985d-f033532f40b9.png)

**Comment by sijie** [comment]
@Jennifer88huang I think @tuteng was looking into fixing the API generation. Can you work with him on this?

**Comment by Jennifer88huang** [comment]
@sijie Sure.

**Comment by Anonymitaet** [comment]
#1 and #2 are tracked (and fixed) in https://github.com/apache/pulsar/issues/5345

**Comment by Anonymitaet** [comment]
#3 has been fixed, here is the [latest doc](http://pulsar.apache.org/api/python/2.5.0-SNAPSHOT/).

* `client.create_producer` and `client.create_reader` can take a "schema"
argument
![image](https://user-images.githubusercontent.com/50226895/68753334-ca99ba00-063f-11ea-8ef5-3128b33e27e2.png)

![image](https://user-images.githubusercontent.com/50226895/68753392-ea30e280-063f-11ea-8458-1d29865aa99d.png)

* Message.value() contains the object deserialized via schema
![image](https://user-images.githubusercontent.com/50226895/68753816-95419c00-0640-11ea-9a06-14c3047b469f.png)

**Comment by Anonymitaet** [comment]
@Jennifer88huang all issues have been fixed, could you please close this issue?

**Comment by Jennifer88huang** [comment]
@Anonymitaet When you fix an issue, you can follow the template in PR, and write "Fixes #xxx". When the PR is merge, the related issue is closed automatically.
