### ISSUE TITLE
Kafka Wrapper can NOT support new Kafka version, >=0.11+, 1.0+ and 2.0+ 

### ISSUE THREAD

**Issue by frank-dkvan** [apache/pulsar#5379]
**Describe the bug**
Error: Failed to sample data: java.lang.UnsupportedOperationException

look like currently it only supports Kafka version <=0.10? 

**Screenshots**
![image](https://user-images.githubusercontent.com/17067653/66702857-c0358900-ed3e-11e9-9e2e-2fe3c17bfe96.png)

**Comment by sijie** [comment]
We have just released a Kafka protocol handler for Pulsar. It supports Kafka protocol 2.0+. So you can use vanilla Kafka clients with Pulsar brokers now. Please try this out: https://github.com/streamnative/kop
