### ISSUE TITLE
Support service mesh for pulsar

### ISSUE THREAD

**Issue by xujianhai666** [apache/pulsar#5393]
**Is your feature request related to a problem? Please describe.**
service mesh save lots of devops time.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pouledodue** [comment]
i'm just a user, can you give more info

**Comment by sijie** [comment]
@xujianhai666 Can you provide more information?

**Comment by xujianhai666** [comment]
> @xujianhai666 Can you provide more information?

@sijie same work for kafka: https://github.com/envoyproxy/envoy/pull/8188/files.  This is just layer 4 impl, layer 7 is working. I think this feature for pulsar is beyond my effort.

**Comment by sijie** [comment]
@xujianhai666 I see. so it seems like a feature request adding Pulsar filter in envoy. The work seems to have be done at Envoy side though.

**Comment by xujianhai666** [comment]
> @xujianhai666 I see. so it seems like a feature request adding Pulsar filter in envoy. The work seems to have be done at Envoy side though.

@sijie okay, I got it.

**Comment by hpvd** [comment]
just raised a new detailed issue for the topic "benefiting from service mesh?":
check possibilities to benefit from Linkerd #8986
