### ISSUE TITLE
Enable/disable allowAutoTopicCreation per namespace

### ISSUE THREAD

**Issue by sleungtoast** [apache/pulsar#5395]
**Is your feature request related to a problem? Please describe.**
Currently, `allowAutoTopicCreation` is set as a broker configuration. Generally in my cluster, I want to set that to false to lock down auto topic creation. However, there are still some use cases where topics change a lot and dynamic topic creation would be easier.

**Describe the solution you'd like**
I want to be able to turn on/off `allowAutoTopicCreation` in certain namespaces.

**Describe alternatives you've considered**
- Add the creation of new topics to our terraform definition and run that tool, but we keep that config in source control and it would be complex and frequently updated (many times a day) in order to create all the topics we need.

**Comment by huangdx0726** [comment]
@sleungtoast  You maybe try  admin.brokers().updateDynamicConfiguration(“allowAutoTopicCreation”, false);

**Comment by sleungtoast** [comment]
@huangdx0726 Hmm that could work, but if my app had admin privileges already, I could just have it create topics as an admin before using them, and I wouldn't have to temporarily turn on auto topic creation just so this single app can do so. 
What I need is for a single non-admin user be able to create topics on a namespace, but nobody else can.

**Comment by wmccarley** [comment]
@sleungtoast I am in a similar situation as you I would love to control this behavior at namespace level. For most of my clients I want allowAutoTopicCreation = false so I can funnel topic creation through a workflow and have an admin review the request etc.. However I have one client that uses only non-persistent topics and needs allowAutoTopicCreation = true. The way I have accomplished this is using namespace isolation policies to force that one client's namespaces to different brokers with different configurations. Not the best solution IMO but it will allow you to accommodate both use cases in one cluster.

**Comment by klevy-toast** [comment]
We would like to implement this. It looks like it can be done with configs similar to how deduplication can be enabled on a namespace basis: https://pulsar.apache.org/docs/en/pulsar-admin/#namespace-set-deduplication. Would there be any objections to doing this?
