### ISSUE TITLE
[doc]missing coding guide

### ISSUE THREAD

**Issue by kevenYLi** [apache/pulsar#5402]
#### Expected behavior

The coding guild should be there.

#### Actual behavior

404 Not Found

#### Steps to reproduce

* open [pulsar's home page](https://pulsar.apache.org), choose "Community -> Contributing" on the top navigation bar.
* scroll to the module- Code
* click the [Coding Guide](https://pulsar.apache.org/en/coding_guide)

**Comment by sijie** [comment]
@Anonymitaet @Jennifer88huang please help with this issue.

**Comment by Jennifer88huang** [comment]
Duplicate with https://github.com/apache/pulsar/issues/5425.
A contributor named `gm7y8` is fixing it.

**Comment by Jennifer88huang** [comment]
@kevenYLi Thank you very much for raising the issue, @gm7y8 is fixing it in #5425.
So I'll close this issue currently.
