### ISSUE TITLE
pulsar-client should support JSON in authparams

### ISSUE THREAD

**Issue by tsasaki609** [apache/pulsar#5407]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when using pulsar-client of Pulsar CLI tools.
This is because it is easy to misunderstand that JSON can be set as auth-params.

> for example "key1:val1,key2:val2" or "{"key1":"val1","key2":"val2"}"

https://pulsar.apache.org/docs/en/reference-cli-tools/#pulsar-client

Since it is written like this, it seems that JSON can be set at first glance.
However, tabs, indents and line breaks are not allowed.

The implementation is this code, as I looked up.
https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/AuthenticationUtil.java#L47-L52

**Describe the solution you'd like**
Tabs, indents, and line breaks should be allowed. Or is there any reason why you can't do that?

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.

IIRC this is somehow implemented as `AuthenticationUtil#configureFromJsonString`.
