### ISSUE TITLE
website page `coding_guide` return 404

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#5425]
As @Retardust reported on slack, when you click the link to "coding guide" at  http://pulsar.apache.org/en/contributing/#code, it returns `404`. 
Actually, the link to http://pulsar.apache.org/en/coding_guide does not work.

**Comment by gm7y8** [comment]
@jiazhai can i pick this up?

**Comment by jiazhai** [comment]
@gm7y8 sure you could do it, please feel free for it. It is very appreciate for your help.
This may need a check when the `coding_guide` is removed and un-linked.

Besides this, I checked use a tool: https://www.drlinkcheck.com/, 
and it showed there are a lot of links with issue, It would be great if you could help on them.
![image](https://user-images.githubusercontent.com/6348208/67557450-b0a73e80-f747-11e9-8f6b-7a022a8d896e.png)

**Comment by jiazhai** [comment]
@gm7y8, since it's some kind of urgent, @Jennifer88huang is handling this issue.
