### ISSUE TITLE
Flink connector sink doesn't work on blink SQL context

### ISSUE THREAD

**Issue by fhalim** [apache/pulsar#5430]
**Describe the bug**

**To Reproduce**
1. Create a Flink SQL application in Flink 1.9.0, using the blink optimizer, and register a PulsarJsonTableSink (for instance as described in https://flink.apache.org/2019/05/03/pulsar-flink.html).
2. Run the application.

**Expected behavior**
Sink should be available for writing.

**Actual output**
```

Exception in thread "main" org.apache.flink.table.api.TableException: The StreamTableSink#consumeDataStream(DataStream) must be implemented and return the sink transformation DataStreamSink.
```

**Comment by sijie** [comment]
@fhalim for the integration with Flink 1.9, you might checkout this out : https://github.com/streamnative/pulsar-flink

We are working with Flink community at pushing this new connector back to upstream Flink repo. There is a FLIP for it : https://cwiki.apache.org/confluence/display/FLINK/FLIP-72%3A+Introduce+Pulsar+Connector

**Comment by fhalim** [comment]
@sijie thanks so much for the information. I did not see any artifacts for `pulsar-flink-connector` at https://dl.bintray.com/streamnative/maven/io/streamnative/connectors/, so incorrectly assumed that the project was not actively developed. I'll build the library locally and use it for now. I'll close this issue as `pulsar-flink-connector` is the future.

**Comment by sijie** [comment]
@fhalim ah, I don't think we have ever uploaded the artifacts to our maven repo. The plan is to push the connector to upstream Flink repo. So both Flink and Pulsar communities can work together to provide the best connector for the users who use Pulsar and Flink. For now, if you are interested in trying out the Pulsar-Flink connector, you can clone the repo and build the connector yourself.
