### ISSUE TITLE
Implementing a Sink to a non thread-safe destination

### ISSUE THREAD

**Issue by wmccarley** [apache/pulsar#5433]
I am implementing a Sink to a proprietary socket-based system. The API provided by the destination system does not supply thread-safe classes and write methods.

Is the write method of a class implementing the Pulsar Sink interface expected to be thread safe?

If yes, can someone explain the lifecycle of a Sink within a given JVM?
- When exactly is open/close called?
- Can multiple instances of the same Sink class be instantiated in one JVM?
- What happens when I trigger a sink "update" command.

The developer of the destination system suggested just use a ThreadLocal instance of the socket thingy. That _might be possible_ contingent upon the answers to the questions above but I don't like it. I am worried about leaking the socket thingys if I stop/start sinks etc.

**Comment by sijie** [comment]
> Is the write method of a class implementing the Pulsar Sink interface expected to be thread safe?

yes.

> When exactly is open/close called?

open is called once when an instance of sink connector is initialized.

close is called when an instance of sink connector is closed. the instance is closed when the instance is moving from one function worker to another function worker, or a function worker running the instance is shutting down.

> Can multiple instances of the same Sink class be instantiated in one JVM?

That's possible. If you configure the parallelism to be more than the number of function workers.

Hope this provides the information you need.
