### ISSUE TITLE
Test errors in BrokerServiceLookupTest.testMultipleBrokerDifferentClusterLookup

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#5437]
The test seems to be failing by getting stuck in the consumer creation at:

https://github.com/apache/pulsar/blob/88c854473346507563305d6b65d7a094f7531964/pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java#L261

The problem is that client gets redirected between the 2 brokers in a loop.

cc/ @rdhabalia

**Comment by tisonkun** [comment]
Closed as stale and no recent reports.

Feel free to open a new issue if it's still relevant to the maintained versions.
