### ISSUE TITLE
Some functional requirements about pulsar sql

### ISSUE THREAD

**Issue by apacheBright** [apache/pulsar#5450]
**Is your feature request related to a problem? Please describe.**
       There is currently a need to manage and display pulsar's unconsumed metadata. But currently pulsar SQL will display the consumed data.

**Describe the solution you'd like**
       According to the cursor to get the largest markDeletePosition, which is the location of the last spent cursor, and then reassemble the messageId, like this __message_id__ > '(850,0,0)'. Data pagination can then be paged according to __publish_time__, like this: __publish_time__ > timestamp'2019-10-23 21:32:00' LIMIT 100.If it is a partition theme, filter the corresponding data according to the partition.

**Describe alternatives you've considered**
       #Use the consumer to get the data directly, but not ack, do this to the data display.
       # If pulsar is logically deleted, it should have a logo, which can consume the consumed data according to that identifier.

 Finally thank all the staff of pulsar.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
