### ISSUE TITLE
SchemaUpdateStrategyTest is broken and not run

### ISSUE THREAD

**Issue by jerrypeng** [apache/pulsar#5451]
**Describe the bug**
Schema integration tests in SchemaUpdateStrategyTest are not run because they are not added in https://github.com/apache/pulsar/blob/master/tests/integration/src/test/resources/pulsar.xml.

Some of the tests also appear to be broken

**Comment by codelipenghui** [comment]
@congbobo184 Can you  help take a look this issue?

**Comment by huangdx0726** [comment]
<classes>
            <class name="org.apache.pulsar.tests.integration.cli.CLITest" />
            <class name="org.apache.pulsar.tests.integration.cli.HealthCheckTest" />
            <class name="org.apache.pulsar.tests.integration.compaction.TestCompaction" />
            <class name="org.apache.pulsar.tests.integration.cli.AdminMultiHostTest"/>
            <class name="org.apache.pulsar.tests.integration.cli.FunctionsCLITest"/>
            <class name="org.apache.pulsar.tests.integration.cli.SchemaUpdateStrategyTest"/>
        </classes>
like this？

**Comment by huangdx0726** [comment]
``` xml
 <classes>  
            <class name="org.apache.pulsar.tests.integration.cli.CLITest" />

            <class name="org.apache.pulsar.tests.integration.cli.HealthCheckTest" />

            <class name="org.apache.pulsar.tests.integration.compaction.TestCompaction" />

            <class name="org.apache.pulsar.tests.integration.cli.AdminMultiHostTest"/>

            <class name="org.apache.pulsar.tests.integration.cli.FunctionsCLITest"/>

            <class name="org.apache.pulsar.tests.integration.cli.SchemaUpdateStrategyTest"/>

        </classes>
```

**Comment by jiazhai** [comment]
seems the current test is running well in current ci. would like to close this issue
