### ISSUE TITLE
PersistentTopicMessagingTest and NonPersistentTopicMessagingTest broken and not running

### ISSUE THREAD

**Issue by jerrypeng** [apache/pulsar#5452]
Describe the bug
Topic integration tests in PersistentTopicMessagingTest and NonPersistentTopicMessagingTest are not run because they are not added in https://github.com/apache/pulsar/blob/master/tests/integration/src/test/resources/pulsar.xml.

Some of the tests also appear to be broken

**Comment by sijie** [comment]
this is fixed by #5456
