### ISSUE TITLE
Support CDC Connector for MongoDB

### ISSUE THREAD

**Issue by limadelrey** [apache/pulsar#5474]
At this moment, Apache Pulsar's [documentation](https://pulsar.apache.org/docs/en/io-cdc/) on CDC Connectors states the following information:  

> "The CDC Source connector is used to capture change log of existing databases like MySQL, MongoDB, PostgreSQL into Pulsar".

However, there isn't any available option to capture change logs on MongoDB instances. 

Is it on Apache Pulsar's roadmap? If so, [Debezium's Connector for MongoDB](https://debezium.io/documentation/reference/1.0/connectors/mongodb.html) could be supported.

**Comment by tuteng** [comment]
Yes, Debezium has already supported MongoDB. That should be easy to add support to Mongo in pulsar-io, you can refer to https://github.com/apache/pulsar/blob/master/pulsar-io/debezium/postgres/src/main/java/org/apache/pulsar/io/debezium/postgres/DebeziumPostgresSource.java
```
package org.apache.pulsar.io.debezium.postgres;

import java.util.Map;

import org.apache.kafka.connect.runtime.TaskConfig;
import org.apache.pulsar.io.debezium.DebeziumSource;


/**
 * A pulsar source that runs debezium postgres source
 */
public class DebeziumPostgresSource extends DebeziumSource {
    static private final String DEFAULT_TASK = "io.debezium.connector.postgresql.PostgresConnectorTask";

    @Override
    public void setDbConnectorTask(Map<String, Object> config) throws Exception {
        throwExceptionIfConfigNotMatch(config, TaskConfig.TASK_CLASS_CONFIG, DEFAULT_TASK);
    }
}
```
, but we haven't had time to add this recently, if you are interested, you can try it.

**Comment by Jennifer88huang** [comment]
@tuteng Shall we add this to code only, or add it to both code and doc?

**Comment by huangdx0726** [comment]
@tuteng May i try it？

**Comment by Jennifer88huang** [comment]
@huangdx0726 Sure, thank you very much for your contribution.

**Comment by huangdx0726** [comment]
ok ，i got it

**Comment by tuteng** [comment]
Mongodb's connector is ready for use https://github.com/apache/pulsar/pull/5590.
