### ISSUE TITLE
CDC Debezium Connector isn't allowing to specify replication slot name

### ISSUE THREAD

**Issue by limadelrey** [apache/pulsar#5481]
I think that it's safe to say that Apache Pulsar has multi-tenancy as a first-class citizen. However, when using it with CDC PostgreSQL Debezium Connector we actually have a issue that isn't allowing to separate data from different tenants.

Most companies use a schema-per-tenant approach when it comes to multi-tenancy so it is desirable to have a source connector for each schema. However, when using a standard configuration for PostgreSQL CDC Source Connector it creates a replication slot with the name "debezium" on PostgreSQL database. If we try to specify "slot.name" property it simply replies with "IO Exception". 

**It would be desirable to allow to specify the pg_replication_slot's name (possibly with the tenant's name) and this could be fixed by allowing to use Debezium's "slot.name" property.**

**Comment by Jennifer88huang** [comment]
@limadelrey Thank you for raising the issue. 
@jiazhai @tuteng Is it possible to use `slot.name` property?

**Comment by codelipenghui** [comment]
ping @tuteng Could you please help take a look at this issue?

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.

**Comment by RobertIndie** [comment]
I believe that it’s already supported. We can set slot.name directly in the connector configuration. Just like how we set `database.hostname` , `database.dbname` .
The debezium connector is based on the kafka debezium connector. For debezium-postgres-connecotor, it’s using PostgresConnectorTask .
So we can use the settings inherited from the kafka connector. Here is the documentation for `slot.name` :https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-slot-name
