### ISSUE TITLE
NPE occur when get partitioned topic stats

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#5505]
**Describe the bug**
![image](https://user-images.githubusercontent.com/12592133/67863080-2eab8100-fb5e-11e9-8621-0c07c388757d.png)

**Pulsar version**
2.4.1

**Comment by Jennifer88huang** [comment]
@codelipenghui Thank you for raising the issue. Do you know the reason of this issue, and could you fix it?

**Comment by codelipenghui** [comment]
@Jennifer88huang I will take a look this issue later

**Comment by Jennifer88huang** [comment]
@codelipenghui Thank you.

**Comment by yjshen** [comment]
@codelipenghui does this bug still exists? how could I reproduce it?

**Comment by codelipenghui** [comment]
@yjshen Yes, i think it have not fixed and i have not reproduce it yet.

**Comment by sijie** [comment]
@codelipenghui I am closing this issue for now. if you have reproduced the behavior, please re-open the task.
