### ISSUE TITLE
Similar to issue #5129.  Unable to install pulsar-client 2.4.1 on Windows

### ISSUE THREAD

**Issue by rebootmoishe** [apache/pulsar#5509]
**Describe the bug**
Unable to pip install pulsar-client 2.4.1 on Windows

**To Reproduce**

C:\Users\name>python --version
Python 3.7.5

C:\Users\name>pip install pulsar-client==2.4.1
ERROR: Could not find a version that satisfies the requirement pulsar-client==2.4.1 (from versions: none)
ERROR: No matching distribution found for pulsar-client==2.4.1

**Expected behavior**
client installs.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by aahmed-se** [comment]
we don't publish python packages for windows currently.

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Python client has been permanently moved to https://github.com/apache/pulsar-client-python. If it's still relevant, please open an issue there.
