### ISSUE TITLE
use pulsar get error in mac os

### ISSUE THREAD

**Issue by nathan-zhu** [apache/pulsar#5514]
#### Expected behavior
hi, i use docker to start pulsar, use simple code to test connect pulsar server. the code like below:
```
import pulsar
client = pulsar.Client('pulsar://localhost:6650')
producer = client.create_producer('my-topic')
for i in range(10):
   producer.send(('hello-pulsar-%d' % i).encode('utf-8'))
client.close()
```
#### Actual behavior
```
Traceback (most recent call last):
  File "pulsar.py", line 1, in <module>
    import pulsar
  File "/Users/python/Pulsar/pulsar.py", line 2, in <module>
    client = pulsar.Client('pulsar://localhost:6650')
AttributeError: module 'pulsar' has no attribute 'Client'
```
#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**Pulsar version**: 2.4.1
**python**: 3.7.1

**Comment by aahmed-se** [comment]
@nathan-zhu you are naming your file pulsar.py it's confusing python

**Comment by nathan-zhu** [comment]
i already change file name to others but still get same error.
```
Traceback (most recent call last):
  File "testpulsar.py", line 2, in <module>
    client = pulsar.Client('pulsar://localhost:6650')
AttributeError: module 'pulsar' has no attribute 'Client'
```

**Comment by tuteng** [comment]
Please send command about how to install pulsar-client?
You can try 
```
dir(pulsar)
```

**Comment by aahmed-se** [comment]
@nathan-zhu you have python cache files still interfering with the execution remove all *.pyc files.

**Comment by nathan-zhu** [comment]
> Please send command about how to install pulsar-client?
> You can try
> 
> ```
> dir(pulsar)
> ```

Hi,  i use pip to install client.

`pip install pulsar-client==2.4.1`

i can't use dir(pulsar) command,  is there missing something?
![image](https://user-images.githubusercontent.com/1650457/68096447-b8a37300-feeb-11e9-8acb-595b2a9cbc74.png)

**Comment by nathan-zhu** [comment]
> @nathan-zhu you have python cache files still interfering with the execution remove all *.pyc files.

thanks, but there no pulsar.pyc for my file.

**Comment by tuteng** [comment]
You can try:

```
root@b719364a53f1:/pulsar# python
Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulsar
>>> dir(pulsar)
['Authentication', 'AuthenticationAthenz', 'AuthenticationTLS', 'AuthenticationToken', 'Client', 'CompressionType', 'Consumer', 'ConsumerType', 'Context', 'Function', 'IdentitySerDe', 'InitialPosition', 'Message', 'MessageId', 'PartitionsRoutingMode', 'PickleSerDe', 'Producer', 'Reader', 'Result', 'SerDe', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '_check_type', '_check_type_or_none', '_listener_wrapper', '_pulsar', '_retype', '_schema', 'certifi', 'functions', 're', 'schema']
>>> pulsar.__path__
['/usr/local/lib/python2.7/dist-packages/pulsar']
>>>
```

**Comment by nathan-zhu** [comment]
> You can try:
> 
> ```
> root@b719364a53f1:/pulsar# python
> Python 2.7.13 (default, Sep 26 2018, 18:42:22)
> [GCC 6.3.0 20170516] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pulsar
> >>> dir(pulsar)
> ['Authentication', 'AuthenticationAthenz', 'AuthenticationTLS', 'AuthenticationToken', 'Client', 'CompressionType', 'Consumer', 'ConsumerType', 'Context', 'Function', 'IdentitySerDe', 'InitialPosition', 'Message', 'MessageId', 'PartitionsRoutingMode', 'PickleSerDe', 'Producer', 'Reader', 'Result', 'SerDe', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '_check_type', '_check_type_or_none', '_listener_wrapper', '_pulsar', '_retype', '_schema', 'certifi', 'functions', 're', 'schema']
> >>> pulsar.__path__
> ['/usr/local/lib/python2.7/dist-packages/pulsar']
> >>>
> ```

HI, tuteng. here is my dir(pulsar) information
```
~ ❯❯❯ python
Python 3.7.1 (default, Dec 14 2018, 13:28:58)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulsar
>>> dir(pulsar)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> pulsar.__path__
_NamespacePath(['/Users/lidongzhu/miniconda/lib/python3.7/site-packages/pulsar'])
>>>
```

**Comment by tuteng** [comment]
Please try command:

```
brew install boost-python3
cd pulsar-client-cpp
cmake .
make -j4 && make install 
cd python
python setup.py install

# python
Python 3.7.3 (default, Mar 27 2019, 09:23:32)
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulsar
>>> dir(pulsar)
['Authentication', 'AuthenticationAthenz', 'AuthenticationTLS', 'AuthenticationToken', 'Client', 'CompressionType', 'Consumer', 'ConsumerType', 'Context', 'Function', 'IdentitySerDe', 'InitialPosition', 'Message', 'MessageBatch', 'MessageId', 'PartitionsRoutingMode', 'PickleSerDe', 'Producer', 'Reader', 'Result', 'SerDe', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_check_type', '_check_type_or_none', '_listener_wrapper', '_pulsar', '_retype', '_schema', 'certifi', 'functions', 're', 'schema']
>>>
```

**Comment by nathan-zhu** [comment]
> pulsar-client-cpp
Hi, tuteng, thanks for help. i follow your step to reinstall python3, but still get error, like below. 

```

-- BUILD_TESTS:  ON
-- BUILD_PYTHON_WRAPPER:  ON
-- LINK_STATIC:  OFF
-- USE_LOG4CXX:  OFF
-- CMAKE_BUILD_TYPE:  RelWithDebInfo
-- PYTHON: 2.7.10
CMake Warning at /usr/local/Cellar/cmake/3.15.4/share/cmake/Modules/FindBoost.cmake:2003 (message):
  No header defined for python-mt; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:143 (find_package)

CMake Warning at /usr/local/Cellar/cmake/3.15.4/share/cmake/Modules/FindBoost.cmake:2003 (message):
  No header defined for python-py27; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:143 (find_package)

CMake Warning at /usr/local/Cellar/cmake/3.15.4/share/cmake/Modules/FindBoost.cmake:2003 (message):
  No header defined for python27-mt; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:143 (find_package)

CMake Error at CMakeLists.txt:151 (MESSAGE):
  Could not find Boost Python library

-- Configuring incomplete, errors occurred!
See also "/Users/lidongzhu/python/Pulsar/pulsar-branch-2.4/pulsar-client-cpp/CMakeFiles/CMakeOutput.log".
```
i use pip3 install pulsar-client==2.4.1 get successfully
![image](https://user-images.githubusercontent.com/1650457/68373650-45fdf600-017e-11ea-8e60-a7aa1f645df7.png)

but get new error at below.

```
ython 3.7.5 (default, Nov  1 2019, 02:16:32)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulsar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pulsar/__init__.py", line 102, in <module>
    import _pulsar
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/_pulsar.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf-lite.20.dylib
  Referenced from: /usr/local/lib/python3.7/site-packages/_pulsar.cpython-37m-darwin.so
  Reason: image not found
```

**Comment by tuteng** [comment]
There seems to be a lack of package boost-python3, if you try to install with source code, don't install with pip anymore.

The following command is installed based on source code:
```
git clone https://github.com/apache/pulsar
cd pulsar
git checkout branch-2.4
brew install boost-python3
cd pulsar-client-cpp
cmake .
make -j4 && make install 
cd python
python setup.py install
# python
Python 3.7.3 (default, Mar 27 2019, 09:23:32)
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulsar
>>> dir(pulsar)
['Authentication', 'AuthenticationAthenz', 'AuthenticationTLS', 'AuthenticationToken', 'Client', 'CompressionType', 'Consumer', 'ConsumerType', 'Context', 'Function', 'IdentitySerDe', 'InitialPosition', 'Message', 'MessageBatch', 'MessageId', 'PartitionsRoutingMode', 'PickleSerDe', 'Producer', 'Reader', 'Result', 'SerDe', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_check_type', '_check_type_or_none', '_listener_wrapper', '_pulsar', '_retype', '_schema', 'certifi', 'functions', 're', 'schema']
>>>
```

**Comment by aahmed-se** [comment]
@nathan-zhu try this
```pip3 install pulsar-client==2.4.1.post1```

**Comment by nathan-zhu** [comment]
> There seems to be a lack of package boost-python3, if you try to install with source code, don't install with pip anymore. Python3 is no problem, you don't need to reinstall it.
> 
> The following command is installed based on source code:
> 
> ```
> git clone https://github.com/apache/pulsar
> cd pulsar
> git checkout branch-2.4
> brew install boost-python3
> cd pulsar-client-cpp
> cmake .
> make -j4 && make install 
> cd python
> python setup.py install
> # python
> Python 3.7.3 (default, Mar 27 2019, 09:23:32)
> [Clang 9.0.0 (clang-900.0.39.2)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pulsar
> >>> dir(pulsar)
> ['Authentication', 'AuthenticationAthenz', 'AuthenticationTLS', 'AuthenticationToken', 'Client', 'CompressionType', 'Consumer', 'ConsumerType', 'Context', 'Function', 'IdentitySerDe', 'InitialPosition', 'Message', 'MessageBatch', 'MessageId', 'PartitionsRoutingMode', 'PickleSerDe', 'Producer', 'Reader', 'Result', 'SerDe', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_check_type', '_check_type_or_none', '_listener_wrapper', '_pulsar', '_retype', '_schema', 'certifi', 'functions', 're', 'schema']
> >>>
> ```
Thanks , tuteng. follow your step to do, currently get another error during cmake . like below: 

```
-- Found Boost: /usr/local/include (found version "1.71.0") found components:  python37-mt
-- HAS_ZSTD: 1
-- HAS_SNAPPY: 1
-- Using Boost Python libs: /usr/local/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib;/usr/local/lib/libboost_python37-mt.dylib
clang-tidy not found
clang-format not found
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GMOCK_INCLUDE_PATH
   used as include directory in directory /Users/lidongzhu/python/Pulsar/pulsar/pulsar-client-cpp
   used as include directory in directory /Users/lidongzhu/python/Pulsar/pulsar/pulsar-client-cpp
   used as include directory in directory /Users/lidongzhu/python/Pulsar/pulsar/pulsar-client-cpp
   used as include directory in directory /Users/lidongzhu/python/Pulsar/pulsar/pulsar-client-cpp
   used as include directory in directory /Users/lidongzhu/python/Pulsar/pulsar/pulsar-client-cpp
```
here is CMakeOutput.log file.
[CMakeOutput.log](https://github.com/apache/pulsar/files/3823548/CMakeOutput.log)

**Comment by nathan-zhu** [comment]
> @nathan-zhu try this
> `pip3 install pulsar-client==2.4.1.post1`

thanks,  aahmed-se. now it works on my mac. thanks all people to help me on it.
