### ISSUE TITLE
Missing documentation for window functions

### ISSUE THREAD

**Issue by candlerb** [apache/pulsar#5520]
**Describe the bug**
There is no documentation for window functions, and no python examples for window functions.

**To Reproduce**
Search for "window" in the docs (site2).

It's mentioned in passing:

> A Java function listens for the sanitized-sentences topic, counts the number of times each word appears **within a specified time window**, and publishes the results to a results topic

(my emphasis)

In some CLI flags:

```
./docs/functions-cli.md:sliding-interval-count | The number of messages after which the window slides. |  |
./docs/functions-cli.md:sliding-interval-duration-ms | The time duration after which the window slides. |  |
./docs/functions-cli.md:window-length-count | The number of messages per window. |  |
./docs/functions-cli.md:window-length-duration-ms | The time duration of the window in milliseconds. | |
```

And in a reference to release notes:

> * Add Windowfunction interface to functions api [#3324](https://github.com/apache/pulsar/pull/3324)

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
This functionality is really interesting to me, and I'd like to know (a) what it can do, and (b) if I can use it from python.

I'm particularly interested if it's possible to do e.g. a ten-minute rolling window, where I can add 1 to an internal counter for an event which enters the window, and remove 1 from a count when that event leaves the window, thus maintaining a running count.

It could be done without external support, but would require in-RAM buffering for all events over than 10 minute window - but buffering is what pulsar is for :-)

Externally I could maintain two readers: one at the current location and one at T-10 mins.  But that wouldn't work as a pulsar function AFAICS.

**Comment by candlerb** [comment]
I got part of the answer from pulsar:

```
$ apache-pulsar-2.4.1/bin/pulsar-admin functions update --name womble --window-length-count 5 --sliding-interval-count 3
There is currently no support windowing in python

Reason: There is currently no support windowing in python
```

But I'd still like to see documentation for what windowing is supposed to do :-)

**Comment by Jennifer88huang** [comment]
@candlerb Thank you very much for raising the issue. I'll look into the issue, and provide related docs soon.

**Comment by wolfstudy** [comment]
> But I'd still like to see documentation for what windowing is supposed to do :-)

Sorry, I missed this message.

@candlerb Currently, does not support `window function` in Python Function. 

```
private static void doPythonChecks(FunctionConfig functionConfig) {
        if (functionConfig.getProcessingGuarantees() == FunctionConfig.ProcessingGuarantees.EFFECTIVELY_ONCE) {
            throw new RuntimeException("Effectively-once processing guarantees not yet supported in Python");
        }

        if (functionConfig.getWindowConfig() != null) {
            throw new IllegalArgumentException("There is currently no support windowing in python");
        }

        if (functionConfig.getMaxMessageRetries() != null && functionConfig.getMaxMessageRetries() >= 0) {
            throw new IllegalArgumentException("Message retries not yet supported in python");
        }
    }
```

**Comment by Jennifer88huang** [comment]
@candlerb Currently, window function is supported in Java, not in Python.

**Comment by candlerb** [comment]
Yep, I got that.  But I don't see any documentation for how it would work for a *Java* Pulsar Function either.

**Comment by Jennifer88huang** [comment]
@srkukarni could you help add the related documentation?
