### ISSUE TITLE
Pulsar function to read compacted topics

### ISSUE THREAD

**Issue by candlerb** [apache/pulsar#5538]
**Is your feature request related to a problem? Please describe.**
Pulsar functions cannot currently be configured to read the compacted version of a topic.

**Describe the solution you'd like**
An option to `pulsar-admin functions create/update`, and/or setting in `--function-config-file`, to request subscribing to the compacted version of a topic.

Note: a function can have multiple topics as inputs.  There are already other options which are on a per-input basis (e.g. `custom-schema-inputs`, `custom-serde-inputs`) so it ought to work like those.

**Describe alternatives you've considered**
It occurred to me that subscription options could be part of the topic URI, e.g.

```
persistent://public/default/my-topic?compacted=yes
```

... but that would be a major change if deployed everywhere that subscriptions are used.

**Additional context**
A similar option might be required for sinks.

PR #5532 adds a similar feature to start a sink from "earliest" rather than "latest" message.  If that's just for sinks then it would be useful for functions too.

Hence there seems to be a more general case use around setting initial subscription options for both functions and sinks.

**Comment by 315157973** [comment]
Please assign it to me @codelipenghui
