### ISSUE TITLE
Bulk admin operations for function state

### ISSUE THREAD

**Issue by candlerb** [apache/pulsar#5539]
**Is your feature request related to a problem? Please describe.**
At the moment you can only `querystate` if you know in advance the name of the key you're looking for.

So I would like to be able to:
* List / iterate over all stored state belonging to a function
* Delete all stored state belonging to a function

It is apparently possible via bk interfaces.

**Describe the solution you'd like**
Add commands to pulsar-admin / REST API

* list all keys/values (which could be millions of keys; would need some sort of paging mechanism in the API)

    I noticed[^1] that `GET /admin/v3/functions/public/default/<functionname>/state` (without a key) currently returns a 404 - maybe it could be used to return the first N key/value pairs

* Delete all state for a given function

    Note: whilst the Pulsar functions context object has `deleteState`, there is currently no way from the CLI to delete even a single key, so that ought to be rectified too.

**Describe alternatives you've considered**
Document the bk way of doing this, with examples.

-----

[^1] Found using pulsarctl:

```
./pulsarctl functions querystate --name womble
error: Unknown pulsar error
```

and tcpdump:

```
GET /admin/v3/functions/public/default/womble/state HTTP/1.1
Host: localhost:8080
User-Agent: Pulsarctl-Go-v0.1.0
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

HTTP/1.1 404 Not Found
Date: Sat, 02 Nov 2019 08:27:18 GMT
Cache-Control: must-revalidate,no-cache,no-store
Content-Length: 0
Server: Jetty(9.4.12.v20180830)
```

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
