### ISSUE TITLE
reset-cursor to absolute time

### ISSUE THREAD

**Issue by candlerb** [apache/pulsar#5540]
**Is your feature request related to a problem? Please describe.**
It would be handy to be able to [reset-cursor](https://pulsar.apache.org/docs/en/next/pulsar-admin/#reset-cursor) to an absolute time, e.g. "start consuming from midnight".  Otherwise you have to calculate the time offset, and stuff it into the command immediately.

There is a [mention](https://pulsar.apache.org/docs/en/next/admin-api-persistent-topics/#reset-cursor) of the corresponding REST API call which appears to have a `:timestamp` parameter - if that's an absolute time, then this is just an issue with the CLI.

**Describe the solution you'd like**
[ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Durations) includes unambiguous ways of representing absolute and relative times.

* `PT30M` - 30 minutes (relative offset)
* `P1D` - one day (relative offset)
* `1981-04-05T12:00` - absolute date/time (extended format)
* `19810405T1200` - absolute date/time (basic format)

It should be straightforward to parse and distinguish these cases, whilst falling back to existing behaviour (`10` = 10 minute offset, `2h` = 2 hour offset etc)

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
