### ISSUE TITLE
Python API: seek(eventtime)

### ISSUE THREAD

**Issue by candlerb** [apache/pulsar#5541]
**Is your feature request related to a problem? Please describe.**
Feature-parity between APIs: Java Consumer and Reader have [`seek(messageId)`](https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java#L319) and [`seek(timestamp)`](https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java#L327), but Python has only [`seek(messageId)`](https://pulsar.apache.org/api/python/#pulsar.Consumer.seek) in Consumer, and nothing in Reader.

**Describe the solution you'd like**
Add a new method to Consumer and Reader to seek by timestamp.  Or it could test the type of the value passed, or have different named arguments.

**Describe alternatives you've considered**
N/A

**Additional context**
Use cases are given in #5537 - e.g. rewind a reader to start at a given time.

**Comment by candlerb** [comment]
On further investigation I think some work on C++ API would be needed as well.

1. C++ API has seek in Consumer but not in Reader (which is where I want it)
2. `Consumer::seek` accepts only `MessageId` as its argument - although I see no reason why it can't be overloaded like its Java counterpart

In terms of the wire protocol, it would need to copy whatever the Java client [does](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L1386) for `seek(timestamp)` - the command is built [here](https://github.com/apache/pulsar/blob/master//pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java#L563).

**Comment by aahmed-se** [comment]
https://github.com/apache/pulsar/pull/5542
