### ISSUE TITLE
Is this normal？The "msgBacklog" is "-2".

### ISSUE THREAD

**Issue by l786170309** [apache/pulsar#5543]
**Describe the bug**
I use the exclusive consumer to receive messages and ack them, but I found some message lost. So I check the stats of the topic, and I found "msgBacklog" is "-2". I do not konw how this happened.  Is there any reason to explain it?

**To Reproduce**
I do not how to reproduce the behavio.

**Screenshots**
![96661a0accf3c50aa6e7d4a1b4ae31f](https://user-images.githubusercontent.com/24506890/68073691-a6cbae00-fdcd-11e9-9b53-9abcd4e51e44.png)

\

**Comment by sijie** [comment]
@l786170309 it seems like a calculation problem. we will take a look at it.

**Comment by l786170309** [comment]
OK，got it
