### ISSUE TITLE
Could pulsar support UUID as sequence id?

### ISSUE THREAD

**Issue by l786170309** [apache/pulsar#5548]
**Is your feature request related to a problem? Please describe.**
My data use UUID as sequence id in database, so i want to use UUID as sequence id in pulsar to avoid message duplicate. Would pulsar support it in the future?

**Comment by merlimat** [comment]
You can add your UUID as a property of the message and use that to dedup at the database level.

**Comment by tisonkun** [comment]
Closed as information delievered.
