### ISSUE TITLE
[Pulsar Functions] Allowed to subscribe from an arbitrary point in time 

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar#5552]
**Is your feature request related to a problem? Please describe.**

In some times, user wants a specific subscription-position for input-topic consumer in Pulsar Functions.

**Describe the solution you'd like**

- Add `SubscriptionInitialPosition` param in create consumer for input topics.

**Comment by Jennifer88huang** [comment]
@wolfstudy will add feature and docs requested from @candlerb .
