### ISSUE TITLE
Compacted topics can't be deleted - 500 Internal Server Error

### ISSUE THREAD

**Issue by candlerb** [apache/pulsar#5555]
**Describe the bug**
500 Internal Server error when trying to delete compacted topic.

**To Reproduce**
Run python test suite.

After running the test suite several times, I'm left with a bunch of topics which can't be deleted:

```
$ ../../bin/pulsar-admin topics list public/default
"persistent://public/default/compaction_7011c5e5-8f4a-4388-83bf-a0f6407262a1"
"persistent://public/default/compaction_81a36b03-54bd-4019-9189-4c5de65ecb14"
"persistent://public/default/compaction_cef2af19-6fad-4e91-b1d2-7c98c7119650"
"persistent://public/default/compaction_e748f6fc-5104-4fd2-af65-d316f83079b7"
"persistent://public/default/compaction_49594c8d-9dc3-42cf-bfd0-330ac4a083e8"
"persistent://public/default/compaction_56e01255-80ac-4390-a34a-3bb81ecc17a4"
"persistent://public/default/compaction_dd7c85e6-807a-4444-aa77-815a41f4bdf4"
"persistent://public/default/compaction_439d22a6-9e75-4e03-9a28-2ee849b04104"
"persistent://public/default/compaction_48f1ac1e-24dd-411d-ad63-ac99c549ded6"

$ ../../bin/pulsar-admin topics delete "persistent://public/default/compaction_7011c5e5-8f4a-4388-83bf-a0f6407262a1"
10:39:48.073 [AsyncHttpClient-5-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://localhost:8080/admin/v2/persistent/public/default/compaction_7011c5e5-8f4a-4388-83bf-a0f6407262a1?force=false] Failed to perform http delete request: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
HTTP 500 Internal Server Error

Reason: HTTP 500 Internal Server Error

$ ../../bin/pulsar-admin topics delete -f "persistent://public/default/compaction_7011c5e5-8f4a-4388-83bf-a0f6407262a1"
10:41:54.772 [AsyncHttpClient-5-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://localhost:8080/admin/v2/persistent/public/default/compaction_7011c5e5-8f4a-4388-83bf-a0f6407262a1?force=true] Failed to perform http delete request: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
HTTP 500 Internal Server Error

Reason: HTTP 500 Internal Server Error
```

**Expected behavior**
* Topic to be deleted, or:
* a sensible error message returned explaining why the deletion cannot be done

**Comment by zymap** [comment]
Hi @candlerb, I am trying to reproduce this issue. Which python test suite you were running?  How did you run the test suite? With local clusters?

**Comment by candlerb** [comment]
A ran the `python/pulsar_test.py` suite as per `pulsar-client-cpp/run-unit-tests.sh` - this starts a cluster in standalone mode (note how it calls `./pulsar-test-service-start.sh` to do this)

**Comment by zymap** [comment]
My reproduce steps:
```
cd pulsar-client-cpp
./pulsar-test-service-start.sh
cd python 
python3 pulsar_test.py
```

After run the python file several times, I will left some compaction topics:
```
"persistent://public/default/compaction_4542aece-8e7a-45c7-b7fb-e0a405edad97"
"persistent://public/default/compaction_28be4f9d-8238-4cb9-a7aa-2c4e09475ebc"
"persistent://public/default/compaction_2b050724-cc32-4f4c-b1f0-6d7d8762717c"
"persistent://public/default/compaction_2a137ceb-f40e-4539-969a-34f828f1e517"
"persistent://public/default/compaction_7989dd39-4e00-486e-81ad-29b71a818b1d"
"persistent://public/default/compaction_3902a6d5-2a2b-46bf-a6bb-e514b4d4ee7f"
"persistent://public/default/compaction_d7a21d96-ed89-44f7-a3c4-609a9d2bf915"
"persistent://public/default/compaction_3acbfdde-902a-44d9-ae3a-95be2fecf4d0"
"persistent://public/default/compaction_6d8fb9ce-dc72-4d67-9b3a-9b0db0e9f951"
"persistent://public/default/compaction_cce799ee-64ab-4a54-b3d4-98e621138a90"
"persistent://public/default/compaction_8519946b-de0b-4460-a586-075a9f8ca6b8"
"persistent://public/default/compaction_7b35c6f7-0dfc-47d7-b226-e7e3fddae9b0"
"persistent://public/default/compaction_d6465e80-ccf7-4cb9-ac41-b808015b59f0"
"persistent://public/default/compaction_e18b20bf-eb89-4d67-9b9e-2fb5e2cb4bf5"
```

Delete them one by one
```
bin/pulsar-admin topics delete compaction_xxxx
```

The delete operation is executed successfully.

Hi @candlerb, I try to reproduce this issue. I am using the master code to reproduce this issue,  but it seems can not reproduce on my laptop(macOs Catalina 10.15.2).  

Can you reproduce this issue now? 
Do you have some other information about this issue?
Do you have the error log in the broker?

**Comment by candlerb** [comment]
I was using 2.4.1.  I will need to re-test with 2.4.2

**Comment by stevenarvar** [comment]
I ran in the the same issue in 2.4.2:

pulsar-admin topics delete-partitioned-topic persistent://qa04/messaging/topic-a
05:12:04.404 [AsyncHttpClient-5-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://pulsar.narvar.internal:8080/admin/v2/persistent/qa04/messaging/topic-a/partitions?force=false] Failed to perform http delete request: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
HTTP 500 Internal Server Error

Reason: HTTP 500 Internal Server Error

I used --force and that seems to work for me.

**Comment by devinbost** [comment]
Is this issue intermittent or continuous?

**Comment by zymap** [comment]
Hi @stevenarvar, Does this issue still can reproduce in your environment? If it does, could you please write some steps about how to help me to reproduce this problem? 
And is there any error log in the broker?

**Comment by stevenarvar** [comment]
The steps I used came out of my experiment with geo replication:
1.) pulsar-admin clusters create ...
2.) pulsar-admin tenants update ... --allowed-clusters a b
3.) pulsar-admin namespaces set-clusters ... --clusters a b
Above steps are done on both cluster a and b
4.) Send traffic to topic x
5.) Unsubscribe from topic x
6.) Delete topic x's namespace
7.) Convert topic x to a partitioned topic
8.) Send traffic to topic x

I attempted to undo everything such as delete subscriptions, delete partitioned topics, unset tenants, unset namespaces, delete cluster, and recreate clusters.  So it is hard to say what trigger the problem.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
