### ISSUE TITLE
Add the doc for new schema compatibility  strategy.

### ISSUE THREAD

**Issue by congbobo184** [apache/pulsar#5562]
link #5227 , add the new schema compatibility strategy doc for 2.5.0 version in pulsar.

**Comment by Jennifer88huang** [comment]
When you add docs for this feature, feel free to ping us.

**Comment by sijie** [comment]
@Jennifer88huang @congbobo184 can you please add the documentation for 2.5.0 features. It is a blocker for 2.5.0 release.

**Comment by Jennifer88huang** [comment]
Got it.

**Comment by Anonymitaet** [comment]
I'm handling this task and @congbobo184 will provide technical inputs.
