### ISSUE TITLE
Zookeeper znodes not created for partitioned topics if allowAutoTopicCreation=false

### ISSUE THREAD

**Issue by verdaster** [apache/pulsar#5565]
I've come into an issue when allowAutoTopicCreation is set to false and partitioned topic is created, then pulsar will not create znodes for partitions in managed ledgers and then subscriptions fails with error org.apache.pulsar.client.api.PulsarClientException: No value present

**To Reproduce**
1. set allowAutoTopicCreation to false in broker.conf
2. create partitioned topic
3. subscribe to created topic

**Expected behavior**
Pulsar should create znodes in managed-ledgers.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by codelipenghui** [comment]
Thanks for the feedback, will take a look soon
