### ISSUE TITLE
dashboard is unable to connect with borker cluster

### ISSUE THREAD

**Issue by rvashishth** [apache/pulsar#5567]
**Describe the bug**
Pulsar dashboard is unable to connect with broker cluster

**To Reproduce**
i followed the steps mentioned in the pulsar doc. 1st [started a pulsar standalone cluster using docker](https://pulsar.apache.org/docs/en/standalone-docker/), and then [pulsar dashboard using docker](https://pulsar.apache.org/docs/en/administration-dashboard/). but the dashboard is unable to connect with the cluster.  I have tried to start cluster usign `--advertised-address 1.2.3.4` but that too failed with zookeeper cluster error. 

**Expected behavior**
Dashboard should scrp data from broker as explained in docs

**Desktop (please complete the following information):**
 - OS: iOS

**Additional context**
[pulsar-express](https://github.com/bbonnin/pulsar-express) is working fine and showing the data as expected

**Comment by sijie** [comment]
Can you share the command you used for starting the dashboard container?

**Comment by rvashishth** [comment]
i am using mac. Below is the first command to run [doc - docker standalone](https://pulsar.apache.org/docs/en/standalone-docker/)

`docker run -it -p 6650:6650 -p 8080:8080 -v $PWD/data:/pulsar/data apachepulsar/pulsar:2.4.1 bin/pulsar standalone`

This will start the pulsar cluster, accessible at localhost:8080, on mac the same will also be accessible on <http://docker.for.mac.localhost:8080/>

Later i started with following command 
`SERVICE_URL=http://docker.for.mac.localhost:8080/`
`docker run -p 80:80 -e SERVICE_URL=$SERVICE_URL apachepulsar/pulsar-dashboard:2.4.1`

I also tried to use `--advertised-address` but, broker standalone cluster didn't start with advertise address.  But starting docker standalone with this command didn't workout.

` docker run -it -p 6650:6650 -p 8080:8080 -v $PWD/data:/pulsar/data apachepulsar/pulsar:2.4.1 bin/pulsar standalone --advertised-address=10.192.31.2`

Here the ip is my localhost ip.

**Comment by tisonkun** [comment]
Pulsar Dashboard has been deprecated and removed. Please try out https://github.com/apache/pulsar-manager.
