### ISSUE TITLE
fix the typo error

### ISSUE THREAD

**Issue by chenyuyun-emc** [apache/pulsar#5575]
I read the code, I found there is typo error in org.apache.pulsar.broker.admin.impl.BrokersBase.java

![image](https://user-images.githubusercontent.com/16811354/68302625-5ca04080-00dd-11ea-8d3a-877842452f52.png)

this should be getOwnedNamespaces

**Comment by sijie** [comment]
@chenyuyun-emc are you interested in sending a pull request to fix this typo?

**Comment by huangdx0726** [comment]
shall i try to fix this issue?

**Comment by Jennifer88huang** [comment]
@huangdx0726 Sure, please go ahead, and thanks for your contribution.
