### ISSUE TITLE
Rate limiting or priority control to restrict the resource consumption while restart the whole pulsar cluster

### ISSUE THREAD

**Issue by f7753** [apache/pulsar#5583]
Suppose on some corner-cases, the operators need to restart the whole cluster while the consumers and the producers are still working.  Can I set come configs to prevent loading all the topics that may take a big bite of the resource pool and also do the harms to the most important service that should be restart asap?

It might potentially be useful that add a mechanism which could limit the rate of the topics in the loading stage, and a priority queue to guarantee the most import topics to be loaded as fast as there is enough resource.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
