### ISSUE TITLE
[DISCUSS] Sticky consumer reset cursor

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#5586]
**Is your feature request related to a problem? Please describe.**
Sticky consumer consume messages with distributed to a fixed hash key range, also like a logical partition or a virtual partition. PR https://github.com/apache/pulsar/pull/5388 is added support for sticky consumer.

However, we need to rethink the reset cursor of sticky consumer. Currently, if one sticky consumer reset cursor to a historical point, other sticky consumers cursor also be set. So it's better to explore a new approach for sticky consumer reset cursor which can avoid effect between sticky consumers.

Added issue to track the approach of sticky consumer reset cursor, if anyone has ideas please add comments here.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant in maintained versions.

Open-ended discussions can be posted at the Discussions forum.
