### ISSUE TITLE
[Doc] Document that --py can be a zipfile

### ISSUE THREAD

**Issue by candlerb** [apache/pulsar#5608]
It's possible to provide a zipfile for the `--py` argument to pulsar-admin functions create/update, but this doesn't appear to be documented.

It would be good to note that this can be done, and also give an example (e.g. how it interacts with `--className`)

Current:

```
$ grep -R -- --py site2/docs
site2/docs/functions-develop.md:  --py my_function.py \
site2/docs/functions-develop.md:  --py logging_function.py \
site2/docs/functions-deploying.md:  --py myfunc.py \
site2/docs/functions-deploying.md:  --py myfunc.py \
site2/docs/functions-deploying.md:  --py myfunc.py \
site2/docs/functions-deploying.md:  --py myfunc.py \
site2/docs/functions-deploy.md:  --py myfunc.py \
site2/docs/functions-deploy.md:  --py myfunc.py \
site2/docs/functions-deploy.md:  --py myfunc.py \
site2/docs/functions-deploy.md:  --py myfunc.py \
site2/docs/reference-pulsar-admin.md:|`--py`|Path to the main Python file/Python Wheel file for the function (if the function is written in Python)||
site2/docs/reference-pulsar-admin.md:|`--py`|Path to the main Python file/Python Wheel file for the function (if the function is written in Python)||
site2/docs/reference-pulsar-admin.md:|`--py`|Path to the main Python file/Python Wheel file for the function (if the function is written in Python)||
site2/docs/functions-overview.md:  --py ~/router.py \
```

**Comment by Anonymitaet** [comment]
@candlerb `--py` has been documented in [pulsar-admin functions create](http://pulsar.apache.org/tools/pulsar-admin/2.7.0-SNAPSHOT/#-em-create-em--2) and [pulsar-admin functions update](http://pulsar.apache.org/tools/pulsar-admin/2.7.0-SNAPSHOT/#-em-update-em--4).

**Comment by candlerb** [comment]
I don't see any mention of zip files at those links - is this awaiting docs to be republished?  I can't tell, because there's no link to the relevant git commit either.

**Comment by Anonymitaet** [comment]
@wolfstudy could u pls help explain the `zip file`? Many thanks.

**Comment by wolfstudy** [comment]
> I don't see any mention of zip files at those links - is this awaiting docs to be republished? I can't tell, because there's no link to the relevant git commit either.

Hello @candlerb When we want to submit a python function, we can use --py to specify that we are about to submit a python function. --py specifies the user python function, which is an executable file, not a zip file, so what do you mean by zip file?

**Comment by candlerb** [comment]
I mean exactly that: `--py mybundle.zip` is how you deploy a bundle containing multiple python files.  At least, it worked the last time I tested it (I haven't been using pulsar for a while).

This is [PEP-273](https://www.python.org/dev/peps/pep-0273/) behaviour.

It's very useful otherwise you have no way to deploy a function with its dependent libraries, other than installing the libraries on every host where the function might run.
