### ISSUE TITLE
Fluentd connector for Apache Pulsar

### ISSUE THREAD

**Issue by pradeep-mishra** [apache/pulsar#5610]
Currently we are using Kafka + Fluentd + (Elasticsearch + MongoDB) for log processing
I am looking into replacing Kafka with Pulsar, but for that, we need Fluentd connector for Pulsar.

**Comment by candlerb** [comment]
Fluentd writing messages to pulsar, or consuming messages from pulsar?

It's not exactly what you're asking for, but I just made a plugin for rsyslog to write to pulsar [here](https://github.com/candlerb/rsyslog-omprog-pulsar).

**Comment by pradeep-mishra** [comment]
@candlerb I'll look into it, but I need solution which can be deployable on production.

**Comment by jiazhai** [comment]
Thanks for the help @pradeep-mishra

**Comment by zwzch** [comment]
I made a [plugin](https://github.com/zwzch/fluent-plugin-pulsar) for this

**Comment by pradeep-mishra** [comment]
@zwzch  thanks, i ll look into it. :)

**Comment by jijikarikkad** [comment]
@zwzch  Fluentd is restarting , because of the unhandled exception while socket connection reading bytes of data on PulsarClient.rb #1
https://github.com/zwzch/fluent-plugin-pulsar/issues/1

**Comment by sijie** [comment]
Closing this issue since there are multiple efforts building fluentd plugins.
