### ISSUE TITLE
[Doc] unlinked pages

### ISSUE THREAD

**Issue by candlerb** [apache/pulsar#5611]
The following pages appear to be completely unlinked, both from other pages and from `website/sidebars.json`

* developing-load-manager.md
* functions-guarantees.md
* io-cassandra.md
* security-token-admin.md

io-cassandra.md appears to have been superceded by io-cassandra-sink.md.

security-token-admin.md appears to have been superceded by security-jwt.md

functions-guarantees.md content is already at the end of functions-overview.md

So I think those three files can simply be deleted; but I don't know about developing-load-manager.md.  Maybe it needs a link adding, or else its content needs to be merged somewhere else before deleting it.

**Comment by Jennifer88huang** [comment]
@candlerb Thank you very much for raising the issue. 
Except io-cassandra.md, functions-guarantees.md, security-token-admin.md, there are more deprecated files that should be removed from `master`. Before removing them from `master`, we need to fix links to those files in the older version. @tuteng is checking the process.

For developing-load-manager.md, somebody updates the name as "develop-load-manager.md", and add this file in the sidebar.json file.
I'll check and fix this issue asap.

**Comment by Jennifer88huang** [comment]
@candlerb The id of the `developing-load-manager.md` file is `develop-load-manager`, and in the sidebar.json file, the id used is `develop-load-manager`. I found many similar cases in the `docs` folder, namely, the file names and their ids are not consistent. As long as the id in the sidebar.json file is correct, it does not influence the link.

If we can keep the file name and its id consistent, that's best. After @tuteng fixes the links for the deprecated files, we can try to keep all file names and their ids consistent in the `docs` folder.

**Comment by sijie** [comment]
@Jennifer88huang I don't think we can delete unlinked pages because those pages are required for old versions. It is a limitation of our current documentation framework. I am closing this issue for now. If we have a better framework, we can revisit this issue again.

**Comment by Jennifer88huang** [comment]
That's ok.
