### ISSUE TITLE
  Update Deprecated classes for MongoSink 

### ISSUE THREAD

**Issue by huangdx0726** [apache/pulsar#5612]
Some Classes have Deprecated in ”com.mongodb.async.client” package ，LIke MongoClient、MongoClients。

should we replace ”com.mongodb.async.client” package with ”com.mongodb.reactivestreams.client.”

**Comment by jiazhai** [comment]
@huangdx0726 Would you like to contribute to it?

**Comment by huangdx0726** [comment]
OK，I’ll&nbsp; try



---Original---
