### ISSUE TITLE
Is there an alternate address we can provide for the fields while setting up cluster metadata in case we do not have a DNS?

### ISSUE THREAD

**Issue by vishalananth07** [apache/pulsar#5619]
When running the command `bin/pulsar initialize-cluster-metadata` I do not have a DNS name set up for the cluster to give **web-service-url** and **broker-service-url** fields. Is there an alternate way to set up a single cluster with 3 Bookies/Brokers? or can you help us with how to set up the required DNS?

I saw a similar issue at [https://github.com/apache/pulsar/pull/3249](https://github.com/apache/pulsar/pull/3249) but was not able to understand the workaround provided.

I am a college student and relatively new to this field. I am trying to use Pulsar for our project work and following the instructions given at [https://pulsar.apache.org/docs/en/deploy-bare-metal/](https://pulsar.apache.org/docs/en/deploy-bare-metal/), but it will be of great help if you can provide a person whom I can contact if I am having major issues with setting up and using Pulsar. Thanks :)

**Comment by sijie** [comment]
@vishalananth07 you can put your brokers in the service url. for example: `pulsar://broker1:6650,broker2:6650` or `http://broker1:8080,broker2:8080`.

**Comment by vishalananth07** [comment]
Thanks for the response, also how do we refer to this cluster from the client program since we are not having a dns name?

**Comment by sijie** [comment]
@vishalananth07 I just showed you the service url.

**Comment by vishalananth07** [comment]
Thanks sijie for the quick response!
