### ISSUE TITLE
Enable or disable topic auto creation for non-persistent topic.

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#5631]
**Is your feature request related to a problem? Please describe.**
Currently, we can disable the topic auto creation at broker side, but for non-persistent topic, disable topic auto creation isn't works well.

Unlike persistent topic, we need to create mledger znode in zookeeper, non-persistent topic only maintained in broker, so must allow topic auto creation for non-persistent topic now.

But we also need to disable the non-persistent topic auto creation for topic management.

**Describe the solution you'd like**
Add support for disable non-persistent topic auto creation.

**Describe alternatives you've considered**
Since we just need to store the created non-persistent topics, i'd like to use a system topic to store the non-persistent topic create or delete log and the broker cache the non-persistent topics which is belongs to owned bundles.

**Comment by codelipenghui** [comment]
relate to #5572

**Comment by tisonkun** [comment]
Closed as stale and no one works on it. Please create a new issue if it's still relevant to the maintained versions.

**Comment by zzzming** [comment]
Non-persistent topic auto creation is needed. This is a scenario.
1. when a broker restarts, the topic is unloaded that can no longer to be recreated.
2. the connected consumer/producers try to reconnect but broker reports the topic not found

**Comment by dave2wave** [comment]
I re-opened this so that we can discuss it in the context of the example from @zzzming

**Comment by nicoloboschi** [comment]
IIUC currently the auto topic creation for non persistent topics is managed by `allowAutoTopicCreation` (like for the persistent topics). 

I think @zzzming is assuming that in his scenario allowAutoTopicCreation is set to false.

Probably we should have two different flags in order to manage them independently.

**Comment by michaeljmarshall** [comment]
If `enableNonPersistentTopics=true`, it seems like perhaps we should allow for auto topic creation of non persistent topics, since the feature doesn't really work without it enabled. What do you think @nicoloboschi?
