### ISSUE TITLE
Is there any plan for a pure golang client?

### ISSUE THREAD

**Issue by jinxfei** [apache/pulsar#5637]
**Is your feature request related to a problem? Please describe.**
I want to write a tool that will install on lot's of  hosts, some of the hosts run windows and others with linux. I'am familiar with java but if I write the tool in java, the installation package can't be very small. So go is a proper choice, but use pulsar from go needs install C++ client first, which make the installation complex(especially when there are hundreds of hosts).

**Describe the solution you'd like**
So I really appreciate a pure go client for pulsar.

**Describe alternatives you've considered**
IMy alternative solution include:
1. Use redis pub/sub for communication, but it's unreliable.
2. Use kafka. But I really like pulsar and kafka can't handle large amount of topic very well(Benchmark shows performance will downgrade when partition/topic increase).
3. Write the tool in java.

**Comment by jiazhai** [comment]
https://github.com/apache/pulsar-client-go @jinxfei

**Comment by jiazhai** [comment]
would like to close this issue. @jinxfei please feel free to reopen it.

**Comment by jinxfei** [comment]
> would like to close this issue. @jinxfei please feel free to reopen it.

Thank you for the information!
