### ISSUE TITLE
Python Pypi installation of pulsar-client broken because 2.4.1.post1 doesn't have Linux files

### ISSUE THREAD

**Issue by dtwright** [apache/pulsar#5654]
**Describe the bug**
Trying to install pulsar-client on anything other than MacOS fails, because the 2.4.1.post1 published to Pypi only has MacOS files included. This means installing any package with Pipenv that declares a dependency on pulsar-client will result in strange failures, because Pypi says 2.4.1.post1 is available, but the the matching files for my arch (Linux) don't actually exist in the repo.

It is possible to work around this by explicitly installing 2.4.1, but this is not desirable for automatically tracking new versions.

**To Reproduce**
1. `Pipenv install pulsar-client` on any non MacOS system
2. Observe installation failure

**Expected behavior**
Successful package installation

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04

**Comment by aahmed-se** [comment]
try ```pip install pulsar-client==2.4.1```

**Comment by merlimat** [comment]
We should probably publish the `.post1` also for Linux

**Comment by dtwright** [comment]
@aahmed-se that does work (as noted above), but is not ideal because then my `Pipfile` is stuck on a particular version instead of tracking the latest when I update.

@merlimat that would be great, it would take care of the issue.

**Comment by sijie** [comment]
Close this issue since 2.4.2 release is already published.
