### ISSUE TITLE
[CLIENT SDK] The KeyShared is only supported in java SDK and not in python

### ISSUE THREAD

**Issue by HarishAtGitHub** [apache/pulsar#5656]
**Describe the bug**
There is feature to have KeyShared implementation in apache pulsar. and it works as expected. but there is no equivalent implementation in python. Can you please add ?
Can you also check and guarantee that c++ client also supports it ?

**To Reproduce**
![image](https://user-images.githubusercontent.com/5524260/68810298-ac719100-0622-11ea-98f9-71ee0e218dea.png)

**Expected behavior**
The KeyShared should be supported in python  and c++

**Screenshots**
![image](https://user-images.githubusercontent.com/5524260/68810298-ac719100-0622-11ea-98f9-71ee0e218dea.png)

**Desktop (please complete the following information):**
 - OS: linux

**Additional context**
I was not able to use KeyShared in python because of the lack of support.

**Comment by jerrypeng** [comment]
@HarishAtGitHub this feature is actually already added to the python client but haven't be officially been released yet.

**Comment by jiazhai** [comment]
@jerrypeng @HarishAtGitHub Could we close this issue, since it is already in master?
