### ISSUE TITLE
[CLIENT SDK] Absense of MessageRouter support in python

### ISSUE THREAD

**Issue by HarishAtGitHub** [apache/pulsar#5657]
**Describe the bug**
the message router explained here is supported only in java, but i cannot find an equivalent in python. can you help us by supporting the python equivalent ?

**To Reproduce**
1. Go to link : https://pulsar.apache.org/docs/en/cookbooks-partitioned/
2. see the java implementation
3) but i cannot see way to send custom message router in python

**Expected behavior**
the message router sending way should be supported in python and c++

**Screenshots**
![image](https://user-images.githubusercontent.com/5524260/68810699-ac25c580-0623-11ea-95c1-333853e18635.png)

**Desktop (please complete the following information):**
 - All

**Comment by jiazhai** [comment]
It is named as `MessageRoutingPolicy` in Cpp.
and in python is used as: `                      message_routing_mode=PartitionsRoutingMode.RoundRobinDistribution,`

**Comment by jiazhai** [comment]
Here is a detailed define in python:
```
   def create_producer(self, topic,
                        producer_name=None,
                        schema=schema.BytesSchema(),
                        initial_sequence_id=None,
                        send_timeout_millis=30000,
                        compression_type=CompressionType.NONE,
                        max_pending_messages=1000,
                        max_pending_messages_across_partitions=50000,
                        block_if_queue_full=False,
                        batching_enabled=False,
                        batching_max_messages=1000,
                        batching_max_allowed_size_in_bytes=128*1024,
                        batching_max_publish_delay_ms=10,
                        message_routing_mode=PartitionsRoutingMode.RoundRobinDistribution,   < ===
                        properties=None,
                        ):
```

**Comment by jiazhai** [comment]
Hi @HarishAtGitHub I would like to close this issue. If is not solved, please open it again.

**Comment by merlimat** [comment]
The point here is that it’s not possible to specify a message router in python

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant in maintained versions.

The development of the Python client is permanently moved to https://github.com/apache/pulsar-client-python.
