### ISSUE TITLE
typo error

### ISSUE THREAD

**Issue by huangdx0726** [apache/pulsar#5661]
**Describe the bug**
A typo error of this website of pulsar

**To Reproduce**
1. Go to http://pulsar.apache.org/docs/en/standalone
2. Click on 'Deployment > bare-metal-multi-cluster '
3. Scroll down to 'Provisioning new tenants'
```
$ bin/pulsar-admin tenants create test-tentant \
  --allowed-clusters us-west \
  --admin-roles test-admin-role
```
the test-tentant maybe typo test-tenant.  if we can't fix it，it can run normal .

**Comment by Jennifer88huang** [comment]
@huangdx0726 would you like to fix it?

**Comment by huangdx0726** [comment]
em，I'll try.

**Comment by Jennifer88huang** [comment]
Thanks for your contribution~
