### ISSUE TITLE
[doc] API documentation doesn't describe behaviour of async callbacks

### ISSUE THREAD

**Issue by candlerb** [apache/pulsar#5662]
**Is your feature request related to a problem? Please describe.**
The various APIs include asynchronous operations with callbacks on completion - for example the [Python API](https://pulsar.apache.org/docs/en/client-libraries-python) has [send_async](https://pulsar.apache.org/api/python/#pulsar.Producer.send_async).

However, I cannot see it documented anywhere whether the callbacks occur in a different thread (and hence could occur at any instant) or in the same thread (and won't occur until you next call some other pulsar API method)

This has a big impact on how you use the API.  If it's in a different thread: then you have to protect all data structures that the callback may touch using mutexes.  If it's in the same thread: then you have to make sure your application calls an pulsar API method periodically to avoid starvation.

I ended up having to test the behaviour.

```
import pulsar
import threading
import time

client = pulsar.Client('pulsar://localhost:6650')

producer = client.create_producer('temp', producer_name='fred')

def ack(*args, **kwargs):
    print("Got ack: %r %r in thread %r" % (args, kwargs, threading.get_ident()))

print("Main thread %r" % threading.get_ident())
producer.send_async(b"Hello 1", callback=ack)
print("Sleeping...")
time.sleep(1)
producer.send_async(b"Hello 2", callback=ack)
print("Sleeping...")
time.sleep(1)

producer.close()
client.close()
```

Result:

```
Main thread 140330719487808
Sleeping...
Got ack: (_pulsar.Result.Ok, <_pulsar.Message object at 0x7fa14931f190>) {} in thread 140330630002432
Sleeping...
Got ack: (_pulsar.Result.Ok, <_pulsar.Message object at 0x7fa14931f190>) {} in thread 140330630002432
```

This shows that acks are delivered in a different thread.  I think such important semantics should be documented.

Aside: there *is* a test for send_async in [pulsar_test.py](https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/python/pulsar_test.py#L104), which could only work if callbacks are invoked in a different thread.

**Comment by jiazhai** [comment]
@candlerb This is related to the thread that user setting in client config?
```
struct ClientConfigurationImpl {
    AuthenticationPtr authenticationPtr;
    int ioThreads;   < ===
    int operationTimeoutSeconds;
    int messageListenerThreads;  < ===
    int concurrentLookupRequest;
    std::string logConfFilePath;
    bool useTls;
    std::string tlsTrustCertsFilePath;
    bool tlsAllowInsecureConnection;
    unsigned int statsIntervalInSeconds;
    LoggerFactoryPtr loggerFactory;
    bool validateHostName;

    ClientConfigurationImpl()
        : authenticationPtr(AuthFactory::Disabled()),
          ioThreads(1),
          operationTimeoutSeconds(30),
          messageListenerThreads(1),
          concurrentLookupRequest(50000),
          logConfFilePath(),
          useTls(false),
          tlsAllowInsecureConnection(false),
          statsIntervalInSeconds(600),  // 10 minutes
          loggerFactory(),
          validateHostName(false) {}
};
```

**Comment by candlerb** [comment]
I've no idea.  I'm approaching this as a Python API user, and that setting is not something I can control.

**Comment by tisonkun** [comment]
cc @BewareMyPower @shibd @RobertIndie what's the current status of this feature?

**Comment by BewareMyPower** [comment]
@tisonkun The behavior is expected. The behavior is similar in Java client. The callback is executed by the internal executor of the pulsar-client library. The thread is different from the main thread.

```java
        @Cleanup final var client = PulsarClient.builder().serviceUrl(Config.BROKER_URL).build();
        System.out.println(Thread.currentThread().getName());
        client.newProducer(Schema.STRING)
                .topic("my-topic")
                .create()
                .sendAsync("hello")
                .thenAccept(id -> System.out.println(Thread.currentThread().getName() + " " + id))
                .get();
```

Outputs:

```
main
pulsar-client-io-1-1 16:0:-1:0
```

> I cannot see it documented anywhere whether the callbacks occur in a different thread

I'm not sure if it's worth documenting. Should we assume the callback is executed in the caller's thread without any explicit explanation?

**Comment by tisonkun** [comment]
@BewareMyPower Thanks for your answer. Closed as answered.

I think it's somehow a technical internal and users should not care about it. If they do, they can read the code or find this thread.
