### ISSUE TITLE
all-messages-shared subscription mode

### ISSUE THREAD

**Issue by ssrkr** [apache/pulsar#5678]
**Is your feature request related to a problem? Please describe.**

We are trying to use pulsar in a scenario where there is many-to-many relation with producers and consumers. Specifically we would like to have **n producers** producing messages  on same topic for **m** **consumers** and importantly, every single message is copied to all consumers. That way all consumers can work independently with the same input stream. At present 'shared' mode  works in round-robin mode which means one message goes to a one consumer alone. 

**Describe the solution you'd like**
We are building a service where we need multiple consumers to receive same messages in ordered fashion. We realised that none of the existing subscription mode offers this service.
It would be great if there is a special **shared** mode of subscription, which consumers can choose  for a certain topic and all messages produced under this topic are shared with every consumers. So in effect it is multicast message from one producer to many consumers.

**Describe alternatives you've considered**
We are still evaluating alternatives. If there is any clear scheme on how we can achieve the same result in any other way, we would highly appreciate.

**Comment by codelipenghui** [comment]
I think you can use different subscription name for each consumers, pulsar use subscription to multicast messages

**Comment by ssrkr** [comment]
Could you elaborate on what you mean by subscription name? In our scenario, all consumers have to subscribe to a topic and subscription is based on a specific topic, as per pulsar document. Are you saying there is another control like subscription name?

**Comment by jiazhai** [comment]
@ssrkr you are right. use a new `subscriptionName ` for each consumer could achieve the fan-out use case.

**Comment by jiazhai** [comment]
I would like to close this issue. welcome to open other issue when meet new problem.
