### ISSUE TITLE
[Pulsar dashboard] dashboard docker image installs incorrect version of postgres

### ISSUE THREAD

**Issue by frejonb** [apache/pulsar#5688]
**Describe the bug**
Docker image install postgres 11 instead of 9.6. This results in
```
Starting Pulsar dasboard
+ /pulsar/init-postgres.sh
+ rm -rf '/data/*'
+ chown -R postgres: /data
+ chmod 700 /data
+ sudo -u postgres /usr/lib/postgresql/9.6/bin/initdb /data/
sudo: /usr/lib/postgresql/9.6/bin/initdb: command not found
```

**To Reproduce**
1. Build dashboard docker image from master
1. Run image

**Expected behavior**
Dashboard running

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker

**Additional context**

**Comment by Javac7** [comment]
Same problem here, running in docker.

**Comment by frejonb** [comment]
@Javac7 it's fixed in the PR #5689

**Comment by Javac7** [comment]
@frejonb I was pulling from apachepulsar/pulsar-dashboard image that was updated 9 days ago but no success.

**Comment by frejonb** [comment]
@Javac7 ok you'd have to ask the maintainers. I guess you can build the docker image yourself for now.

**Comment by Javac7** [comment]
Thank you @frejonb
