### ISSUE TITLE
[documentation] Clarify the messages(data) be invisible

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#5693]
**Is your feature request related to a problem? Please describe.**
If all subscriptions mark delete at a position, the messages before that position will be delete. Always, users understand the mechanism like send a message to the topic, and a new consumer A create a new subscription SUB-A with the earliest position and acknowledge the message, then a new consumer B also create a new subscription SUB-B with the earliest position, since consumer A already acknowledge the message, and at that time topic only have SUB-A subscription, so consumer B should not receive that message.

But, actually the consumer B also can receive that message, because broker will not delete the current active ledger in the topic, data will be invisible to the user until the ledger rollover happens.

So, here add an issue to track the documentation of how messages be invisible works.

**Comment by Anonymitaet** [comment]
@codelipenghui could you please provide technical inputs (docs/PR) for this issue? Then I'm glad to review it from a technical writer's perspective.

Thank you

**Comment by tisonkun** [comment]
Closed as stale - it seems no interest for a long time. If this is still relevant, please open an issue there.
