### ISSUE TITLE
Support multiple topic subscriptions across multiple namespace

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar#5709]
Currently, multiple topic subscriptions are supported in the same namespace. Some users want to support multi-topic subscriptions across multiple namespaces. The main consideration is authentication and authorization under multiple namespaces and multiple topics.

First:

MultiTopicsConsumerImpl.java => topicNamesValid
Remove check logic

Second:
Check the content related to permissions, mainly for verification logic under multi-namespace and multi-topic, such as creating consumer, calling schema, authorizing, canceling permissions, etc

**Comment by jiazhai** [comment]
Seems this not need to much change, maybe remove the namespace checking, and check if all the the tests passed.
