### ISSUE TITLE
Don't depend on ZooKeeper for coordination

### ISSUE THREAD

**Issue by thedrow** [apache/pulsar#572]
#### Expected behavior

Pulsar should be able to function without ZooKeeper or provide other backends for Etcd and Consul

#### Actual behavior

ZooKeeper is required for Pulsar's operation.
One of the major hurdles of using Kafka in production is ZooKeeper. The component is a source for many operational problems and thus not suitable for use in small startups/shops.
If this project wants to succeed it should provide us with a way to replace this dependency with another one or implement all coordination on it's own (as Mesos is working on now)

**Comment by dave2wave** [comment]
Are you in an environment that is virtualized? When ZK gets confused are you having migrations? I've seen a case where Solr 5.5 clusters which also use ZK got confused in those scenarios especially when logging was configured off host. The solution required 5 ZK nodes to 3 Solr nodes. along with not using mounted disks for Jetty logs in front of the Solr nodes.

Also I think that the ZK dependency in Pulsar is due to the use of BookKeeper...

**Comment by youurayy** [comment]
Bookkeeper seems to be Etcd ready: https://github.com/apache/bookkeeper/issues/1639
Kafka also already supports etcd.

Is it time for Pulsar to be reassessed for adding etcd support?

**Comment by mingfang** [comment]
Pulsar is an amazing technology, and zookeeper is not.
Please remove the zookeeper dependency.

**Comment by atombender** [comment]
I'd like this, too. We use Etcd.

How solid is zetcd? It's not been updated since January, the last pre-release was 16 months ago, and the last release was 2 years ago. Readme doesn't have any information on whether it's production-ready. Not too promising.

**Comment by adamfeldman** [comment]
@mingfang thank you for sharing that you're using zetcd! How has your experience been?

(pardon me for potentially hijacking this issue -- it is very difficult to find information on zetcd in production...)

**Comment by mingfang** [comment]
Unfortunately zetcd didn't work very well so I stopped using reverted back to using zookeeper.

The problem was it intercepts the four letter health check command (srvr) so there was no way of knowing if the backend fails.  Also the project seems abandoned.

**Comment by IsNull** [comment]
When I stumbled upon Plusar I died twice. First I read the description and, coming from a Kafka / Kubernetes background, I thought man these guys really tick everything I could wish for. After that, I clicked the Docs page and when I discovered those nasty ZK boxes in the diagram the dream died as fast as it was emerging.

I can understand the argument of not repeating yourself and it may look like a good idea to have that complicated quorum stuff sorted out with a separate microservice (ZK). However, If you produce the situation that the state of multiple services are interconnected and can desynchronize, its an operational nightmare. At least in a containerised and managed environment like Kubernetes.

Kafka has (finally) accepted this reality and is moving away from an external solution to embed quorum ([KIP-500](https://cwiki.apache.org/confluence/display/KAFKA/KIP-500%3A+Replace+ZooKeeper+with+a+Self-Managed+Metadata+Quorum)). By having the Quorum State and Broker Data state in the same location, desynchronisation are no longer possible and operations are very much simplified.

So my two cents would be to not make ZK replaceable by something other but remove the need for an external solution altogether.

**Comment by kjaggann** [comment]
My understanding zookeeper has an issue in terms of "quorum" and "split Brain"
my finding correct me if I am wrong lets take we have 5 servers. The voting to elect the leader is based on the majority of the servers. the number of servers must accept specific server to become the leader, the other becomes the followers
So there is this bad thing that may happen called "split brain". A split brain is simply this, as far as I understand: The cluster of 5 servers splits into two parts, or let's call it "server teams", with maybe one part of 2 and the other of 3 servers. This is really a bad situation as if both "server teams" must execute a specific order how would you decide which team should be preferred? So it is really important to know what "server team" is still relevant and which one can/should be ignored.

 When one server in {3,4,5} realizes the leader is gone, it triggers an election. Once a new leader is elected, it starts serving client requests normally. The other partitioned cluster {1,2} won't serve any client request and will be stuck in the election until the partition is resolved. So it waits till the issue resolved and the cluster runs normal again.

Currently, pulsar uses  Apache zookeeper to store its metadata. Data such as the location of partitions and the configuration of topics are stored outside of Kafka itself, in a separate Zookeeper cluster. so is there a plan to break this dependency and bring metadata management into Pulsar itself.

**Comment by SleeperSmith** [comment]
@kjaggann split brain is a situation where the minority "server team" accepts write/read command and leads to a situation where the two clusters becomes inconsistent (in terms of data). It does not occur trivially from just 2 servers being cut off (say AWS AZ connection outage) from the rest of the cluster. That's a clear cut case of minority / not holding the quorum. One potential scenario is when servers have partial connections to rest of the cluster. Say servers of ABCDE. C can talk to the whole cluster, but AB can't talk to DE. AB and DE then both elect a leader amongst themselves and function independently thinking they both have majority with C.

Even the above scenario does not cause split brain with ZK. ZK is a very robust and well tested software. Those nuances are already well tested and handled.

Have a read of this https://aphyr.com/posts/291-jepsen-zookeeper and other related posts to understand more about consistency / quorum. You'll also see why managing all that stuff inside Pulsar ..... might not be the best idea. You are just reinventing the wheel twice, and it's a pretty fucking complex wheel.

**Comment by asafm** [comment]
Also bear in mind you still have to maintain 3 separate machines with a special role that function just for raft, so it’s not that different. Kafka specifically adapted Raft to match their needs. IMO it just makes more difficult to fix issues.

**Comment by josephlim75** [comment]
I hope Pulsar and BookKeeper will ditch Zookeeper and come out with their internal built-in cluster coordination like Raft, what new Kafka 2.8 has developed `KIP-500` and also how Docker Swarm cluster coordinate with each other without using any external system like Etcd, Consul or Zookeeper.

**Comment by tomdavidson** [comment]
> hope Pulsar devs don't make the same mistake Kafka did

I thought thats what Pulsar is :D 

100% in agreement with @SleeperSmith ectd/consul/zk as plugable options seems consistent with the Pulsar's architecture. This would not only avoid the concern shared about kafka, but let operators choice the the tech they are most competent in .... isn't that the whole concern about zk, that some (including me) lack the ability to operate and fix it where as other options have bigger communities, more engineers that are familiar, and various commercial support options?  The way zk is used in Pulsar isnt necessarily a technical problem right?

**Comment by josephlim75** [comment]
The only reason I'm saying to get away from the external coordination tool is that the additional maintenance, monitoring, management, and infrastructure cost to host the tools.  I don't think Kafka made a mistake in ditching away Zookeeper.  I'm sure the architect team has gone through a deep discussion and thought process about it.   
Etcd and Consul themselves internally are using Raft consensus for writing by the way.  Hashicorp Vault Integrated Storage is also using Raft internally.  Not to mention Yugabyte and Google spanner.   I'm not trying to argue, and I'm 100% agreeing of using those tools will provide benefits, but I do see the benefits of having a product that has fewer moving parts to maintain.

**Comment by lhotari** [comment]
FYI there's https://github.com/apache/pulsar/wiki/PIP-45%3A-Pluggable-metadata-interface which will later give the choice of choosing between multiple options.

**Comment by josephlim75** [comment]
@lhotari  is great to hear that Pulsar team is working towards a solution.  That is a good start though.  Having a choice to select is always better than none.  Kudos to you guys.  Really hope that the team from Apache BookKeeper will have the same plan going forward.

**Comment by lhotari** [comment]
> @lhotari is great to hear that Pulsar team is working towards a solution. That is a good start though. Having a choice to select is always better than none. Kudos to you guys.

Yes, Bookkeeper already supports a pluggable metadata store.

**Comment by thedrow** [comment]
> > @lhotari is great to hear that Pulsar team is working towards a solution. That is a good start though. Having a choice to select is always better than none. Kudos to you guys.
> 
> Yes, Bookkeeper already supports a pluggable metadata store. https://bookkeeper.apache.org/bps/BP-29-metadata-store-api-module/

That is wonderful! Can we use that in Pulsar?
Do we just need the documentation for it?

**Comment by kant777** [comment]
kafka got rid of ZK and doesnt depend on etcd or consul either(way to go).

**Comment by truong-hua** [comment]
We love etcd too due to it simplification in deployment and easier to maintain than Zookeeper. We are using both and etcd is definitely take us less time to control and maintain it.

**Comment by tisonkun** [comment]
I believe this issue can be resolved by [PIP-45](https://github.com/apache/pulsar/wiki/PIP-45:-Pluggable-metadata-interface) delivered and we implemented etcd as the metadata store backend.
