### ISSUE TITLE
[pulsar-broker]Support batch authorization of partitioned topic

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar#5724]
At present, if a topic is a partitioned topic, the sub-partition topic below it is not authorized when grant it, resulting in an error in connection creation. So if the topic is found to be a partitioned topic when authorizing or canceling permissions, all partitioned topics should be authorized or revoke permissions.

Implement similar `pulsar-admin topics skip` https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L935

1. Check topic type by `getPartitionedTopicMetadata`
2. Non partitioned topic, the current logic remains unchanged.
3. Partitioned topic, authorize each topic through the for a loop.
4. Add unit test

**Comment by zhaohaidao** [comment]
Is there someone working on it?
If not, I want to have a try.

**Comment by jiazhai** [comment]
@zhaohaidao You are welcome to do it. Please go ahead. Feel free to ping @tuteng if you meet problem

**Comment by tuteng** [comment]
Welcome, if you have any questions, you can ping me at any time. @zhaohaidao
