### ISSUE TITLE
[doc] Missing right Parentheses

### ISSUE THREAD

**Issue by huangdx0726** [apache/pulsar#5728]
**Describe the bug**
Missing right Parentheses 

**To Reproduce**
1. Go to 'http://pulsar.apache.org/docs/en/concepts-messaging/'
2. Click on 'Messaging'
3. Scroll down to 'Producers>Send modes'
![图片](https://user-images.githubusercontent.com/29513837/69471843-f571d400-0dde-11ea-932b-cefdd98d2f91.png)

**Comment by huangdx0726** [comment]
The right parentheses should be added after the word of 'the right Parentheses should be added after the word of 'web'. Is right？

**Comment by Jennifer88huang** [comment]
@huangdx0726 @atlantic2099 Thank you very much for your contribution.
