### ISSUE TITLE
[doc] Picture and text are not match 

### ISSUE THREAD

**Issue by huangdx0726** [apache/pulsar#5729]
**Describe the bug**
Picture and text are not match.

**To Reproduce**
1. Go to 'http://pulsar.apache.org/docs/en/concepts-messaging/'
2. Click on 'Messaging'
3. Scroll down to 'Subscription modes > Exclusive'

**Expected behavior**

May be the Consumer-A  should be Consumer A-0.

**Screenshots**
![图片](https://user-images.githubusercontent.com/29513837/69472688-40441980-0de8-11ea-8d0c-0a8d98de4d36.png)

**Comment by jiazhai** [comment]
@huangdx0726 Would you like to provide a fix for this?
