### ISSUE TITLE
Provide raw counters metrics

### ISSUE THREAD

**Issue by PierreZ** [apache/pulsar#5735]
**Is your feature request related to a problem? Please describe.**
Pulsar is offering many [built-in metrics](https://pulsar.apache.org/docs/en/reference-metrics/), which is pretty awesome. You can find metrics on any layer, from the pulsar-proxy to Bookkeeper. There are easy to plot within Grafana as most of the rate are already computed, for example `pulsar_throughput_in` is directly offering **the total throughput of the namespace coming into this broker in bytes/second.**

However, for some usages, metrics based on rate are not enough. For example, to bill users according to messages produced, you cannot rely on a rate, you need the `raw counter` associated.

**Describe the solution you'd like**
I would like to add a new boolean to the configuration `exposeTopicLevelMetricsAsCounterInPrometheus`, which default is false. By setting it to true, **broker will expose new counter metrics**, which will be the **raw counters** used to compute the rates internally. The new metrics could be suffixed by _counter, for example:

* pulsar_throughput_in_counter
* pulsar_in_counter

and so on. We could also do the same work for any metrics which are a rate, but I think we should start with the `topic metrics`.

**Describe alternatives you've considered**
Using the rate to compute the counter is not offering enough precision.

What do you think about it? We can discuss on the name of the parameter and the naming schemas.

**Comment by jiazhai** [comment]
Thanks @PierreZ for working on this. it sounds good to me.  Add @sijie @merlimat, to see if they have more suggestions.

**Comment by sijie** [comment]
@PierreZ +1 

Can I suggest using names like "pulsar_in_bytes_total" or "pulsar_in_bytes_counter", "pulsar_in_messages_total" or "pulsar_in_messages_counter"?

**Comment by PierreZ** [comment]
I like `pulsar_in_bytes_total`!

**Comment by PierreZ** [comment]
I started working on it. From what I see, the rate is computed through [Rate](https://github.com/apache/pulsar/blob/master/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/Rate.java), which seems to be hold by [Producer](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java) which `Represents a currently connected producer`. The rate is [polled frequently](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L383-L386). As the classes are representing by **connected** {Producer, Consumer} and the fact the update is async, we can miss events between two polls if a {Producer, Consumer} disconnects.

I'm wondering if the metrics can be generated from a place less volatile, maybe at the opening of the managed ledger? What do you think?

**Comment by PierreZ** [comment]
Found a naive solution, by creating a [Counter directly on the AbstractTopic class](https://github.com/apache/pulsar/commit/8625db717c021318d65f70b9b19b0c181ebbc64b). I am not sure if this is recommend though. What do you think @sijie?

**Comment by sijie** [comment]
I don't think we have used Prometheus counter directly.

I would suggest:

- use LongAdder in AbstractTopic for counting only.
- expose those counters in PersistentInternalTopicStats or TopicStats
- update NamespaceStatsAggregator to expose those counters to prometheus servlet.

**Comment by PierreZ** [comment]
Thanks, I will do this 👍
