### ISSUE TITLE
Add test check in branch

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar#5736]
**Is your feature request related to a problem? Please describe.**

Currently, the test check of branch not work, there are two main problems:

- the java8 tests missing
- the cpp tests not work

**Describe the solution you'd like**

Add test check in branch.

**Additional context**

#5733 
![image](https://user-images.githubusercontent.com/20965307/69527615-a6c36600-0fa7-11ea-91da-4a51eaa7a031.png)

**Comment by vzhikserg** [comment]
@wolfstudy @sijie @jiazhai Is this issue still relevant for the Gitlab Actions?

**Comment by sijie** [comment]
@vzhikserg I think it is still relevant. We should add workflows in GitHub Actions to test branches. It is to ensure any cherry-picks to the branch doesn't break the build. Are you interested in contributing a change to it?

**Comment by vzhikserg** [comment]
@sijie Do you want to run the same checks as for a normal pull requests, but in "branch-*"?
I think it should be easy to achieve with the following additional block in all CI workflows
```
on:
  push:
    branches:    
      - branch-*
```
If this is the case, I can work on it
