### ISSUE TITLE
Use message bytes instead of message number for producer pending messages

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#5739]
In PR #5045 we introduce use bytes instead of message number to limit a batch message.  It would be good to following the same way to use bytes instead of message number for  the `maxPendingMessages` and `maxPendingMessagesAcrossPartitions`

**Comment by zhaohaidao** [comment]
Is there someone working on it?
If not, I want to have a try.

**Comment by codelipenghui** [comment]
welcome @zhaohaidao and looking forward to your contribution.

**Comment by Renkai** [comment]
I will try to work on this.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
