### ISSUE TITLE
handle broker shutdown when no zk session

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#5740]
currently, when no zk session, broker is shutdown.
In issue https://github.com/apache/pulsar/issues/308
It mentioned how to handle no zk session for broker, this is to tracking that work. 

>We have already been discussing a bit on improving this behavior by having a "degraded" mode in which brokers with no ZK session can continue sending and delivering messages without attempting to do any metadata operations (no new topics, no ledger rollovers..). The design is still up in the air, but it's an area that we surely are going to improve.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant in maintained versions.
