### ISSUE TITLE
[Doc] link for  TLS Authentication on Proxies is dead

### ISSUE THREAD

**Issue by wangyunpeng666** [apache/pulsar#5753]
Expected behavior
Show a page / Enabling TLS Authentication on Proxies 
Actual behavior
404
Steps to reproduce
1、Open https://pulsar.apache.org/docs/zh-CN/security-authorization/
2、Click a link for  Enabling TLS Authentication on Proxies

**Comment by wangyunpeng666** [comment]
@Anonymitaet Thank you for solving my problem

**Comment by Jennifer88huang** [comment]
@Anonymitaet @wangyunpeng666 Have you solved the issue?

**Comment by Anonymitaet** [comment]
@Jennifer88huang not yet, I'll fix when I'm available.

**Comment by Anonymitaet** [comment]
@Jennifer88huang could you please help tag `help-wanted`?

**Comment by Jennifer88huang** [comment]
@Anonymitaet We can add `help-wanted` tag. If the link affects user experience, and no contributors fix it within two days, we need to fix it promptly.

**Comment by belinda-wong** [comment]
what is the target page for "Enabling TLS Authentication on Proxies"？ can you give the target link?

**Comment by belinda-wong** [comment]
@wangyunpeng666  what is the target page for "Enabling TLS Authentication on Proxies"？ can you give the target link?

**Comment by wangyunpeng666** [comment]
> @wangyunpeng666 what is the target page for "Enabling TLS Authentication on Proxies"？ can you give the target link?
> I am a technical writer and try to fix the doc issue.

[https://pulsar.apache.org/docs/zh-CN/security-authorization/security-tls-authentication#on-proxies](url)

**Comment by wangyunpeng666** [comment]
> @wangyunpeng666 what is the target page for "Enabling TLS Authentication on Proxies"？ can you give the target link?
> I am a technical writer and try to fix the doc issue.

[https://pulsar.apache.org/docs/zh-CN/security-authorization/security-tls-authentication#on-proxies](url)

**Comment by Jennifer88huang** [comment]
@belinda-wong The following image will help you to resolve the issue.
![image](https://user-images.githubusercontent.com/47805623/69815498-670faf00-1231-11ea-8092-61e93692594e.png)
You need to update it as "see ["Enable TLS Authentication on Proxies"](security-tls-authentication.md#enable-tls-authentication-on-proxies)". After you update, you can run website locally and verify the change.
