### ISSUE TITLE
Inactive non-persistent subscriptions not purged

### ISSUE THREAD

**Issue by wmccarley** [apache/pulsar#5759]
**Describe the bug**

I have set up a cluster with brokers that only serve non-persistent topics. Furthermore, I have set the topic/subscription purge intervals/frequencies to low values to satisfy the use case I am focused on. However I am not seeing topics get cleaned up due to inactivity.

In the original pull request (1352) by @yush1ga  that implemented the inactive subscription purge feature the checkInactiveSubscriptions method was not implemented for NonPersistent topics:
https://github.com/apache/pulsar/pull/1352/files#diff-48abd445bf0d38e83cc8966f765f6615

Isn't the side effect of this that unused subscriptions will never be cleared on non-persistent topics? In turn this prevents the broker from purging the topic as inactive if there are also no producers?

Is this correct?

My concern is that in an environment where I need lots of short-lived (read: ephemeral) non-persistent topics I will accumulate topic metadata as older topics are abandoned but never fully cleaned up...

**Expected behavior**

I would expect that the subscription inactivity and topic inactivity settings would apply to non-persistent topics as well.

**Comment by jiazhai** [comment]
Thanks for the detailed reports @wmccarley . This is a feature that need to fix for non-persistent topics. This should be a direct fix that need following #1352 have done, mark this as help wanted.

**Comment by 315157973** [comment]
I will work on it
