### ISSUE TITLE
Python API Docs are not updated

### ISSUE THREAD

**Issue by acedrew** [apache/pulsar#5778]
**Describe the bug**
Python API docs do not represent the 2.4.1 code that the rest of the site is based on.
Specifically, the Client.subscribe method now takes an initial_position argument that is missing from the documentation. It appears that the doc generation pipeline is still broken from #5368 

**To Reproduce**
https://pulsar.apache.org/api/python/

**Expected behavior**
The Python API documentation would show code and examples congruent with the rest of the documentation

**Comment by tuteng** [comment]
Please try http://pulsar.apache.org/api/python/2.5.0-SNAPSHOT/

**Comment by acedrew** [comment]
@tuteng Thanks, yes I was able to find the docs and just look at the source to answer my question, but it was confusing to follow the link from the 2.4.1 docs to find a completely different version of the API 

![image](https://user-images.githubusercontent.com/977415/69930691-5d38b680-1492-11ea-8dc5-7b601add84ff.png)

**Comment by tuteng** [comment]
We have an e-mail to discuss this matter https://lists.apache.org/thread.html/a6a91990907cf8d2458ff8b7e1e916a9bfb17ec0cd216d57c66ab96c@%3Cdev.pulsar.apache.org%3E. We are doing this, this is a pr https://github.com/apache/pulsar/pull/5660. After adding the old version of API documents, we will consider replacing the jump links in the documents. @acedrew

**Comment by tuteng** [comment]
Now that python's old version of the document has been generated, please check here.
python:
http://pulsar.apache.org/api/python/2.2.0/
http://pulsar.apache.org/api/python/2.2.1/
http://pulsar.apache.org/api/python/2.3.0/
http://pulsar.apache.org/api/python/2.3.1/
http://pulsar.apache.org/api/python/2.3.2/
http://pulsar.apache.org/api/python/2.4.0/
http://pulsar.apache.org/api/python/2.4.1/
http://pulsar.apache.org/api/python/2.4.2/

and then we will gradually fix the wrong links in the document.

**Comment by sijie** [comment]
This has been fixed in the latest website.
