### ISSUE TITLE
[docs] Reorganize "Tiered storage" content

### ISSUE THREAD

**Issue by Jennifer88huang** [apache/pulsar#5779]
**Describe the bug**
There are two sections about "tiered storage" under "Concepts and Architecture" and "Cookbooks", the information splits. It's better to reorganize the the content for "tierage storage" after merging https://github.com/apache/pulsar/pull/5762

**Comment by Anonymitaet** [comment]
@Jennifer88huang FYI:

Suggestions from @sijie:

- Keep tiered storage in the "Concepts and Architecture" chapter to let users know we have this feature.
- Tiered storage is one of the most important features in Pulsar. Same as we did for functions, connector, and schema, we can create an independent chapter for tiered storage and add sections to explain principles of offloaders, how to use offloaders, how to manage offloaders (admin API), and so on.

**Comment by atlantic2099** [comment]
Reorganized and proofread "Tiered Storage" section per your comments. See details from https://github.com/atlantic2099/pulsar/commit/b7fb118800bf170ee34ddba78244c98db18360cd

**Comment by Anonymitaet** [comment]
Done in https://github.com/apache/pulsar/pull/7393
