### ISSUE TITLE
deploy-kubernetes in minikube tutorial doc seems not work

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#5787]
**Describe the bug**
In Pulsar website: http://pulsar.apache.org/docs/en/deploy-kubernetes/#minikube
It is suggested use this command:
> minikube start --memory=8192 --cpus=4 \
>    --kubernetes-version=v1.10.5

but this will report error in macos 10.14.2
![image](https://user-images.githubusercontent.com/6348208/69974222-ca664d80-155f-11ea-99eb-f604d09ccec0.png)

**To Reproduce**
1. follow instructions  in above like to install the latest minikube
2. run 'minikube start --memory=8192 --cpus=4 \
    --kubernetes-version=v1.10.5'
3. See error

**Expected behavior**
No error happens

**Comment by jiazhai** [comment]
add @wolfstudy  to take a look

**Comment by jiazhai** [comment]
![image](https://user-images.githubusercontent.com/6348208/70020290-1e584d00-15c7-11ea-9d06-7165459b6628.png)
minikube verison 1.5.2

**Comment by wolfstudy** [comment]
@jiazhai On `v1.4.0`, it can work normally.

```
minikube version: v1.4.0
commit: 7969c25a98a018b94ea87d949350f3271e9d64b6
```

Output as follows:

```
😄  minikube v1.4.0 on Darwin 10.14.5
🔥  Creating virtualbox VM (CPUs=4, Memory=8192MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.10.5 on Docker 18.09.9 ...
💾  Downloading kubelet v1.10.5
💾  Downloading kubeadm v1.10.5
🚜  拉取镜像 ...
❌  Unable to pull images, which may be OK: pull command is not supported by kubeadm v1.10.5
🚀  正在启动 Kubernetes ...
⌛  Waiting for: apiserver proxy etcd scheduler controller dns
🏄  Done! kubectl is now configured to use "minikube"
```
