### ISSUE TITLE
Using the latest release version of pulsar-client-go module from pulsar-function-go

### ISSUE THREAD

**Issue by Sunkwan-Kwon** [apache/pulsar#5799]
**Describe the bug**

Is it possible to use the latest released version of `pulsar-client-go` module from `pulsar-function-go`?

The current version of `pulsar-function-go` uses `v0.0.0-20190320194916-f03971cb5b4f` of `pulsar-client-go` module like below.
https://github.com/apache/pulsar/blob/180e28aceb39d1683df034c8c2234595d23ab935/pulsar-function-go/go.mod#L4

Actually, I faced a worker process hanging issue during a long-running test, but It seems that the related patch already has been merged to `pulsar-client-go`. (https://github.com/apache/pulsar/issues/5324)

To avoid the hanging issue, I've manually modified the downloaded `pulsar-client-go` file under the local go module path by following the patch(https://github.com/apache/pulsar/pull/5336)  and the problem has been resolved. But it is just a temporal workaround.

So that I suggest using the latest release version of `pulsar-client-go` module from `pulsar-function-go` to apply recently applied patch set.

It will be great if you can consider my suggestion.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by wolfstudy** [comment]
Thanks @Sunkwan-Kwon, this is a good proposal, when the 2.5.0 is released, we can replace the latest version of `pulsar-client-go` in `pulsar-function-go`.

**Comment by jiazhai** [comment]
@wolfstudy Thanks for the help. Since you are releasing 2.4.2, Is it easy to update it with 2.4.2?

**Comment by wolfstudy** [comment]
> @wolfstudy Thanks for the help. Since you are releasing 2.4.2, Is it easy to update it with 2.4.2?

The #5324 and #5336 will be released in 2.5.0.

**Comment by Sunkwan-Kwon** [comment]
@wolfstudy Thank you for considering.

By the way, I have a question.
There is another git repository `https://github.com/apache/pulsar-client-go`.
What is the difference between that and `https://github.com/apache/pulsar/pulsar-client-go`?
And what would you recommend using for go application?

**Comment by wolfstudy** [comment]
> What is the difference between that and `https://github.com/apache/pulsar/pulsar-client-go`?

@Sunkwan-Kwon 

This is a native go client(https://github.com/apache/pulsar-client-go).

This is a cgo client(https://github.com/apache/pulsar/tree/master/pulsar-client-go)

Once feature parity and stability are reached, this will supersede the current CGo based library.
