### ISSUE TITLE
C API 'pulsar_message_id_t' couples to C++ 'class pulsar::MessageId'

### ISSUE THREAD

**Issue by AllenChien** [apache/pulsar#5800]
**Describe the bug**

The C API prototype defined in message_id.h, such as:

> PULSAR_PUBLIC const pulsar_message_id_t *pulsar_message_id_earliest();
> PULSAR_PUBLIC const pulsar_message_id_t *pulsar_message_id_latest();

the return type is pulsar_message_id_t, which is defined as:

> struct _pulsar_message_id {
> pulsar::MessageId messageId;
> };

where the pulsar::MessageId is a C++ class. Thus this kind of APIs can't work smoothly in pure C env. 

**To Reproduce**
1. Go to source file 'message_id.h'
2. Check its definition

**Expected behavior**
C API should not couple to C++ class definition.

**Comment by jiazhai** [comment]
@AllenChien , Thanks for the reporting.  Currently Pulsar provided a native Cpp client, and the c client is a wrapper for Cpp client. And seems this is the reason that `struct _pulsar_message_id` exists. 
Would you please help provide a detailed error information that you have meet?

**Comment by tisonkun** [comment]
Closed as stale.

The development of the C++ client has been permanently moved to https://github.com/apache/pulsar-client-cpp. If it's still relevant, please open an issue there.
