### ISSUE TITLE
When CryptoFailureAction is FAIL, after a number of redeliver a message, the message is not move to deadletter topic

### ISSUE THREAD

**Issue by bigbang489** [apache/pulsar#5807]
**Describe the bug**
The decypt action fail should be treated as a Unack message, therefore it should be moved to the deadletter topic if Dead Letter Topic is enabled

**To Reproduce**
1. At comsumer: Set the decryption keys to an incorrect key 
2. Enable dead letter policy 
3. At producer: Sent a encrypted message to the topic (End to End Encryption)

**Expected behavior**
After a number of redelivery times of the message, it should be moved to the Dead Letter topic

**Actual behavior**
The message it redelivered to consumer forever

**Comment by jiazhai** [comment]
@bigbang489 Thanks for reporting this issue. 
usually a countable deliver message is the one that get a success receive() in consumer. For this case, if decryption keys is incorrect, the receive() should be failed?
From my point of view, If this is the case, user should handle this kind of receive error manually. And of cause, user could choose to  put the error message into a dead-letter-topic in the handling.

**Comment by jiazhai** [comment]
@bigbang489 There is action for user to choose:
```
        switch (conf.getCryptoFailureAction()) {
            case CONSUME:
                // Note, batch message will fail to consume even if config is set to consume
                log.warn("[{}][{}][{}][{}] Decryption failed. Consuming encrypted message since config is set to consume.",
                        topic, subscription, consumerName, messageId);
                return payload.retain();
            case DISCARD:
                log.warn("[{}][{}][{}][{}] Discarding message since decryption failed and config is set to discard", topic,
                        subscription, consumerName, messageId);
                discardMessage(messageId, currentCnx, ValidationError.DecryptionError);
                return null;
            case FAIL:
                MessageId m = new MessageIdImpl(messageId.getLedgerId(), messageId.getEntryId(), partitionIndex);
                log.error(
                        "[{}][{}][{}][{}] Message delivery failed since unable to decrypt incoming message",
                         topic, subscription, consumerName, m);
                unAckedMessageTracker.add(m);
                return null;
        }
```

**Comment by jiazhai** [comment]
The default CryptoFailureAction is `FAIL`, so it will add to unAckedMessageTracker and get redeliver.
`DISCARD` will auto `ack` the message, and it will not get redelivered.
`CONSUME` will need the consumer to choose and handle it.

**Comment by bigbang489** [comment]
In the case of CONSUME, I don’t know If The payload I received is decryptEd successfully or not. How can I get that information?

**Comment by jiazhai** [comment]
@bigbang489 , how do you consume the successfully received messages? will you meet error when you read the failed-decypted message?

**Comment by bigbang489** [comment]
I used MessageListener interface as below:
builder.messageListener(new MessageListener<byte[]>() {
					private static final long serialVersionUID = 1L;
					@Override
					public void received(Consumer<byte[]> consumer, Message<byte[]> msg) {
						try {
							if(logger.isDebugEnabled()) {
								logger.debug("Received msgId: " + BinaryUtil.bytesToHex(msg.getMessageId().toByteArray())+ ", topic: " + msg.getTopicName());
							}
							msgHandler.processMessage(resultConvertor.convert(msg));
						} catch (Exception e) {
							logger.error(ThrowableUtil.trace(e));
						}
					}
				});

All the decrypted and undecrypted messages are processed in the same way with no error

**Comment by jiazhai** [comment]
I see. Seems we need a way to let user know that the decrypt failed in CONSUME mode?

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
