### ISSUE TITLE
[docs] The example code does not display correctly

### ISSUE THREAD

**Issue by huangdx0726** [apache/pulsar#5808]
**Describe the bug**
Ununderstood example code .
**To Reproduce**
1. Go to 'http://pulsar.apache.org/docs/en/schema-understand'
2. Click on 'Understand schema'
3. Scroll down to 'Complex type>Example'

**Expected behavior**
this  example code is for java or other?
**Screenshots**
![图片](https://user-images.githubusercontent.com/29513837/70309120-bebca480-1847-11ea-89ed-badf4ca9c5e2.png)

**Additional context**
For JAVA , ``` Schema> ```  means ``` Schema<KeyValue<Integer, String>>```,right?

**Comment by sijie** [comment]
@huangdx0726 the example is written in Java. I guess there are typos when we put up the documentation.

**Comment by jiazhai** [comment]
Thanks @huangdx0726 for the help
