### ISSUE TITLE
2.4.2 on Kubernetes, can't start Brokers, functions.worker.WorkerService

### ISSUE THREAD

**Issue by youurayy** [apache/pulsar#5818]
**Describe the bug**
Starting image 2.4.2 on Kubernetes config where 2.4.1 worked, puts the brokers into `CrashLoopBackOff`.

**To Reproduce**
1. in your k8s yamls, change your pulsar image ref from 2.4.1 to 2.4.2 and clean-deploy
2. observe the pod initialization

**Expected behavior**
Pulsar should start normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/588573/70395931-9af68b80-1a0c-11ea-905a-fcd5b5222715.png)

**Additional context**
n/a

**Comment by jiazhai** [comment]
@wolfstudy,  @yjshen Is it a known issue?

**Comment by youurayy** [comment]
Adding `functionsWorkerEnabled: "false"` to the Broker config works as a temporary workaround - the Brokers start normally.

**Comment by youurayy** [comment]
Might have something to do with the Broker seeing no initialized Bookie:

![image](https://user-images.githubusercontent.com/588573/71207749-41b21600-22b0-11ea-95a6-d8bdee659e1d.png)

The Bookies in my cluster eventually initialize fine, so this is probably a init race issue.
The Brokers also recover after a few restarts (they are hitting an error where they discover their ZK node entry from the previous run and bail out, so that has to time out first, or something.)

![image](https://user-images.githubusercontent.com/588573/71207903-92297380-22b0-11ea-92bc-9531a6b02c55.png)

**Comment by wolfstudy** [comment]
> The Bookies in my cluster eventually initialize fine, so this is probably a init race issue.

yes, thanks @youurayy work for this, will fix the issue.
