### ISSUE TITLE
[doc] Add a section to document function types and schema

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#5831]
#### Problem

This task is used for tracking adding a section in functions documentation about the function argument types and schema.

**Comment by momo-jun** [comment]
Hi @sijie, can you pls provide more context regarding the argument types and schema you mentioned?
We are revisiting backlog doc issues for functions and trying to resolve them with engineering support (@freeznet ).

**Comment by D-2-Ed** [comment]
@david-streamlio Can you help @momo-jun with documenting the function argument types and schema?

**Comment by tisonkun** [comment]
Closing for now...

We need more context to proceed with this task. Please open a new issue with what should be documented and basic usage or source of truth.
