### ISSUE TITLE
[Doc] Variable issues in website download links

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#5839]
### Issue

Currently, for different contents, we use the same variables in multiple versions.

### Incorrect example 1

When I resolve https://github.com/apache/pulsar/issues/4053, I find that:

**From `2.1.0-incubating` to `2.4.2`, the download links for the contents in the red box are redirected to **2.4.1 links****, which are the **latest version of docs** now (2.4.2 is released, but the docs are not shown on Pulsar website now, so 2.4.1 is the latest).

![image](https://user-images.githubusercontent.com/50226895/70599960-775c5c80-1c29-11ea-94ea-95de1c52078e.png)

Then I open the original file (that is `client-libraries-cpp.md`) and find that all version docs are using the same variables:

![image](https://user-images.githubusercontent.com/50226895/70606263-0de34a80-1c37-11ea-8a90-3f0b3e6c2e26.png)

P.S. I search `{{pulsar:rpm:client}}` in Pulsar project, except in `.md` and `html` files, it appears in the`site2/website/scripts/replace.js` file, which contains many variables:

![image](https://user-images.githubusercontent.com/50226895/70600541-e25a6300-1c2a-11ea-9115-1179b39d1806.png)

### Incorrect example 2

Taking 2.3.1 as an example, as same to other version docs, it uses a general variable so that it is shown and redirected to 2.4.1:

![image](https://user-images.githubusercontent.com/50226895/70605953-6bc36280-1c36-11ea-9c8f-a1f72b750526.png)

### Summary

For different contents, we can not use the same variables in multiple versions, because each version should have its own specific links.

But I do not know how to change it (seems it needs coding updates?), anyone can help?

**Comment by jiazhai** [comment]
@tuteng could be able to help on this issue.

**Comment by Anonymitaet** [comment]
@tuteng seems that this issue is not resolved.

### Incorrect example 1

After clicking the contents in the red boxes (https://pulsar.apache.org/docs/en/2.3.2/client-libraries-cpp/), I got a `404 Not Found` error.

![image](https://user-images.githubusercontent.com/50226895/72576313-506d0680-390a-11ea-8242-44889b055e4a.png)

### Incorrect example 2

After clicking `downloads page`, I got a `404 Not Found` error.

![image](https://user-images.githubusercontent.com/50226895/72578078-e9525080-390f-11ea-8487-8c0d7118ee51.png)

It seems that the variable `pulsar:download_page_ur` should be reset to redirect to a correct destination.

![image](https://user-images.githubusercontent.com/50226895/72578038-cfb10900-390f-11ea-8586-eef0aac8e502.png)

Could you please help? Thanks

**Comment by Anonymitaet** [comment]
Related PR:
https://github.com/apache/pulsar/pull/5865
https://github.com/apache/pulsar/issues/4053

**Comment by sijie** [comment]
@Anonymitaet I think the website has been fixed by #5865. Please double check if the problem exists.

**Comment by Anonymitaet** [comment]
I've checked related links in all releases, they are redirected correctly.
