### ISSUE TITLE
Subscription mode Key_Shared not working as expected

### ISSUE THREAD

**Issue by patronovski** [apache/pulsar#5840]
#### Expected behavior

When running two instances of my app, i expect that pulsar should loadbalance between the two instances. Also, messages with the same key should always go to the same instance. 

#### Actual behavior

However, all messages are handled by instance 1. Instance 2 only receive messages when instance 1 is down.

#### Steps to reproduce
Create a SpringBoot app with a single Pulsar Consumer Bean:

```
@Slf4j
@Component
public class CustomerCommandHandler {

  @Autowired
  private PulsarClient pulsarClient;

  @Bean
  public Consumer<Customer> consumer() throws PulsarClientException {
    return pulsarClient.newConsumer(Schema.JSON(Customer.class))
        .topic("eu-west/app1/customers-topic")
        .subscriptionType(SubscriptionType.Key_Shared)
        .subscriptionName("my-subscription")
        .messageListener((MessageListener<Customer>) (consumer, message) -> {
          try {
            log.info("Message received: {}", message.getValue());
            consumer.acknowledge(message);
          } catch (Exception e) {
            consumer.negativeAcknowledge(message);
            e.printStackTrace();
          }
        })
        .subscribe();
  }
}`
```
Run two instances of this app and puplish messages to the customers-topic.

#### System configuration
Pulsar version: 2.4.1 and 2.4.2

**Comment by jiazhai** [comment]
@patronovski what does the code of producer side looks like? What is the key for each message?

**Comment by alikelleci** [comment]
Hi, below is the code for the producer:

`@Slf4j
@RestController
@RequestMapping(value = "/customers")
public class CustomerController {

  @Autowired
  private Producer<Customer> producer;

  @GetMapping(value = "/create/{id}")
  public void create(@PathVariable String id) throws PulsarClientException {
    Faker faker = new Faker();
    producer.newMessage()
        .key(id)
        .value(Customer.builder()
            .id(id)
            .firstName(faker.name().firstName())
            .lastName(faker.name().lastName())
            .address(faker.address().streetAddress())
            .postal(faker.address().zipCode())
            .city(faker.address().city())
            .country(faker.address().country())
            .credit(100)
            .build())
        .send();
  }
}`

**Comment by alikelleci** [comment]
> @patronovski what does the code of producer side looks like? What is the key for each message?

Hi, below is the code for the producer:

`@Slf4j
@RestController
@RequestMapping(value = "/customers")
public class CustomerController {

  @Autowired
  private Producer<Customer> producer;
  
  @GetMapping(value = "/create/{id}")
  public void create(@PathVariable String id) throws PulsarClientException {
    Faker faker = new Faker();
    producer.newMessage()
        .key(id)
        .value(Customer.builder()
            .id(id)
            .firstName(faker.name().firstName())
            .lastName(faker.name().lastName())
            .address(faker.address().streetAddress())
            .postal(faker.address().zipCode())
            .city(faker.address().city())
            .country(faker.address().country())
            .credit(100)
            .build())
        .send();
  }
}`

**Comment by patronovski** [comment]
> @patronovski what does the code of producer side looks like? What is the key for each message?

Hi, below is the code for the producer:

`@Slf4j
@RestController
@RequestMapping(value = "/customers")
public class CustomerController {

  @Autowired
  private Producer<Customer> producer;
  
  @GetMapping(value = "/create/{id}")
  public void create(@PathVariable String id) throws PulsarClientException {
    Faker faker = new Faker();
    producer.newMessage()
        .key(id)
        .value(Customer.builder()
            .id(id)
            .firstName(faker.name().firstName())
            .lastName(faker.name().lastName())
            .address(faker.address().streetAddress())
            .postal(faker.address().zipCode())
            .city(faker.address().city())
            .country(faker.address().country())
            .credit(100)
            .build())
        .send();
  }

}`

**Comment by zhouyangang** [comment]
i have met this problem also....
finally, i find when use Key_Shared subscrition mode, the producer must set  enableBatching(false), like this:
`client.newProducer(Schema.JSON(User.class))
                    .topic(topic)
                    **.enableBatching(false)**
                    .messageRoutingMode(MessageRoutingMode.RoundRobinPartition)
                    .hashingScheme(HashingScheme.Murmur3_32Hash)
                    .create();`
but i don't know why need this special set

**Comment by patronovski** [comment]
> i have met this problem also....
> finally, i find when use Key_Shared subscription mode, the producer must set like this:
> ` private Producer<Integer> createProducer(String topic, boolean enableBatch) throws PulsarClientException { Producer<Integer> producer = null; if (enableBatch) { producer = pulsarClient.newProducer(Schema.INT32) .topic(topic) .enableBatching(true) .batcherBuilder(BatcherBuilder.KEY_BASED) .create(); } else { producer = pulsarClient.newProducer(Schema.INT32) .topic(topic) .enableBatching(false) .create(); } return producer; }`
> because producer enable batching by default, so you must set batcherBuilder(BatcherBuilder.KEY_BASED) when use Key_Shared mode.

Thank you, this solves my problem.
