### ISSUE TITLE
pip can't find pulsar-client 2.4.2 for Python 3.8

### ISSUE THREAD

**Issue by bry00** [apache/pulsar#5842]
**Describe the bug**
Cannot install [`pulsar-client==2.4.2`](https://pulsar.apache.org/docs/en/client-libraries-python/#installation-using-pip) on Python 3.8.0, receiving error: `No matching distribution found for pulsar-client`.

**To Reproduce**
1. Try to install pulsar-client in the Python 3.8.0 environment:

```Python
(.venv) # python -V
Python 3.8.0
(.venv) # pip install pulsar-client
ERROR: Could not find a version that satisfies the requirement pulsar-client (from versions: none)
ERROR: No matching distribution found for pulsar-client
```

2. See error

**Expected behavior**
The python-client should be installed.

**Desktop (please complete the following information):**
 - OS: macOS Catalina (v. 10.15.2)

**Comment by sijie** [comment]
@bry00 this is related to #5846

**Comment by jiazhai** [comment]
would like to close this issue and dup this to #5846
