### ISSUE TITLE
log4j2-appender producer name should be configurable

### ISSUE THREAD

**Issue by tkram01** [apache/pulsar#5845]
When using the log4j2-appender it always gives a producer name of "pulsar-log4j2-appender-" + topic which means you can only send logs from one process to that topic at a time. When there are multiple instances of an application I think it makes sense to be able to consolidate them into a single topic.

**Comment by jiazhai** [comment]
Thanks @tkram01 for report this requirements.
> I think it makes sense to be able to consolidate them into a single topic
The 'topic' in log4j2 appender is configurable,
If user want to append all logs into a single topic, only need to set the same `topic` name. 
If want to append to different topic, user also could set the different `topic` name. 
I may not understand it well, Would you please provide an example for the requirement?

**Comment by sijie** [comment]
@jiazhai we might consider adding documentation for this.

**Comment by Jennifer88huang** [comment]
I add the following note in "reference-configure/log4j". If we need more info, please provide, and I'll improve it further in [PR-7297](https://github.com/apache/pulsar/pull/7297)
> 'topic' in log4j2.appender is configurable. 
> - If you want to append all logs to a single topic, set the same topic name.
> - If you want to append logs to different topics, you can set different topic names.
