### ISSUE TITLE
Error at starting apachepulsar/pulsar-dashboard docker container within Kubernetes

### ISSUE THREAD

**Issue by julio666** [apache/pulsar#5847]
Hi there!

**Issue**
I've used the helm chart available in the 2.4.2 Apache Pulsar project. Every pod is created and running correctly except `pulsar-dashboard` which has the `CrashLoopBackOff` status.

It looks like the initdb file from postgresql does not exist. Here what the logs are saying :

```
Starting Pulsar dasboard
+ /pulsar/init-postgres.sh
+ rm -rf '/data/*'
+ chown -R postgres: /data
+ chmod 700 /data
+ sudo -u postgres /usr/lib/postgresql/9.6/bin/initdb /data/
sudo: /usr/lib/postgresql/9.6/bin/initdb: command not found
```

**To Reproduce**
Simply install the helm chart with values-mini.yaml and look at the pods in the pulsar namespace. To be sure, I've tried to run the container alone on my machine and I get the same error.

**Expected behavior**
I would expect Pulsar Dashboard to run properly :)

**Cluster Kubernetes:**
 - Server version 1.12 on linux/amd64 platform

**Comment by julio666** [comment]
It looks like the installed version of postgresql is now 11 and no more 9.6.

**Comment by tshh** [comment]
running into same problem too.
use “kubectl set image deployment”
set image to
pulsar-dashboard:2.3.0 
is ok.

**Comment by jiazhai** [comment]
Thanks @julio666 , Seems you already found the version issue . Would you like to provide a PR to fix it?

**Comment by jiazhai** [comment]
And also in master pulsar-manager is added in helm, you could try pulsar-manager instead of dashboard.

**Comment by Javac7** [comment]
I'm looking for a working docker-compose for local standalone pulsar with dashboard, someone already made it?

**Comment by julio666** [comment]
@jiazhai no problem, I'll do it. Thanks for the tip about pulsar-manager.

**Comment by dockerzhang** [comment]
there is a bug in apachepulsar/pulsar-dashboard:2.4.2 docker image, 
/usr/lib/postgresql/9.6/bin/initdb  - > /usr/lib/postgresql/11/bin/initdb  for /pulsar/init-postgres.sh
or you can set image tag to other version, apachepulsar/pulsar-dashboard:2.4.1 works fine for me.

**Comment by nirodg** [comment]
> there is a bug in apachepulsar/pulsar-dashboard:2.4.2 docker image,
> /usr/lib/postgresql/9.6/bin/initdb - > /usr/lib/postgresql/11/bin/initdb for /pulsar/init-postgres.sh
> perhaps you can set image tag to other version, apachepulsar/pulsar-dashboard:2.4.1 works fine for me.

Same issue here, downgraded to `2.4.1` and now it's up and running!

**Comment by Javac7** [comment]
I made a build from version 2.4.2 you can pull here: docker pull javac7/apachepulsar-dashboard
or can get the docker-compose from my "docker-composes" repository.

**Comment by jiazhai** [comment]
@tuteng also has already pushed the 2.4.2 version into apachepulsar 's dockerhub, @julio666 Could we close this issue?

**Comment by julio666** [comment]
@jiazhai yes, I close it !

**Comment by complex64** [comment]
Running into this issue with the image `apachepulsar/pulsar-dashboard:2.5.1` and the following error:

```
Starting Pulsar dasboard
+ /pulsar/init-postgres.sh
+ rm -rf '/data/*'
+ chown -R postgres: /data
+ chmod 700 /data
+ sudo -u postgres /usr/lib/postgresql/11/bin/initdb /data/
sudo: /usr/lib/postgresql/11/bin/initdb: command not found
```

**Comment by tuteng** [comment]
You can try http://pulsar.apache.org/docs/en/administration-pulsar-manager/ first. https://github.com/apache/pulsar-manager is a better management tool. Let's take a look at this problem next. @complex64

**Comment by complex64** [comment]
> You can try http://pulsar.apache.org/docs/en/administration-pulsar-manager/ first. https://github.com/apache/pulsar-manager is a better management tool. Let's take a look at this problem next. @complex64

Thanks for the pointer to the manager, we'll give that project a try :+1:
