### ISSUE TITLE
pulsar-admin get HTTP 403 Forbidden return with kubernetes

### ISSUE THREAD

**Issue by tshh** [apache/pulsar#5849]
**Describe the bug**
$pulsar-admin tenants list
HTTP 403 Forbidden

Reason: HTTP 403 Forbidden

**To Reproduce**
1. my kubernetes is up and fine
$ kubectl get nodes
NAME             STATUS   ROLES    AGE    VERSION
k8s-node-141     Ready    <none>   2d3h   v1.13.2
k8s-node-142     Ready    <none>   2d1h   v1.13.2
k8s-node-143     Ready    <none>   22h    v1.13.2
k8s-server-140   Ready    master   2d4h   v1.13.2

2. pulsar deployment is up and running
$kubectl get pods
NAME                                 READY   STATUS      RESTARTS   AGE
bookie-86nzz                         1/1     Running     1          102m
bookie-vvqsn                         1/1     Running     1          102m
bookie-wh6dv                         1/1     Running     1          102m
broker-55958769bd-bjfg2              1/1     Running     2          113m
broker-55958769bd-hpbwz              1/1     Running     2          113m
broker-55958769bd-qrrxh              1/1     Running     2          113m
grafana-6c6b796879-lqbvq             1/1     Running     2          2d3h
prometheus-7548d7d545-b8hrp          1/1     Running     2          2d3h
proxy-ff85bffd-8pdgs                 1/1     Running     2          2d3h
proxy-ff85bffd-jtggr                 1/1     Running     2          2d3h
pulsar-admin                         1/1     Running     1          130m
pulsar-cluster-metadata-init-68zmm   0/1     Completed   0          2d3h
pulsar-dashboard-74b788ddd-7fntt     1/1     Running     1          27h
zk-0                                 1/1     Running     2          2d3h
zk-1                                 1/1     Running     2          2d3h
zk-2                                 1/1     Running     2          2d3h

3. alias made
$alias pulsar-admin='kubectl exec pulsar-admin -it -- bin/pulsar-admin'
4. changed pulsar-dashboard image to 2.3.0 because latest does't running.
5. pulsar-admin will not work at all:
$pulsar-admin tenants list
HTTP 403 Forbidden

Reason: HTTP 403 Forbidden
command terminated with exit code 1

**Expected behavior**
pulsar-admin work.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jiazhai** [comment]
@tshh `HTTP 403 Forbidden` usually means not have the right permission.  Is there any other additional change?

**Comment by tshh** [comment]
> @tshh `HTTP 403 Forbidden` usually means not have the right permission. Is there any other additional change?

no further change.
just following the guide:
http://pulsar.apache.org/docs/en/deploy-kubernetes/#minikube

by the way:
pulsar 2.4.2 deployment failed on k8s v1.6
I'm using k8s v1.3.2

**Comment by tshh** [comment]
tear pulsar deployment down and re deploy again.
pulsar-admin success.
