### ISSUE TITLE
Prometheus - Add Metrics Around Message Storage

### ISSUE THREAD

**Issue by one70six** [apache/pulsar#5854]
Currently you can visualize message backlog via Prometheus/Grafana by observing the **pulsar_msg_backlog** metric.  Since Pulsar allows for TTL and Retention to be set on a namespace, it would be very nice if we could somehow visualize if the messages are in TTL phase or in Retention phase. Pulsar does a great job of abstracting storage from the consumer by design, but developers ask all the time how they know if there is still data in the topic or not.
- Did we consume it all?
- I thought there was a retention?
- etc.

### Enhancement 
Please add the following metrics for better visualizing what phase the messages are in.
- Add pulsar_msg_ttl metric
- Add pulsar_msg_retention metric

Thanks!

**Comment by jiazhai** [comment]
Thanks @one70six for reporting this issue.  This should be an independent task, mark it as help wanted. 
Would you please provide more details of the requirements?
pulsar_msg_ttl:  the number of messages that will not be in backlog after a TTL?
pulsar_msg_retention:  for [retention](https://pulsar.apache.org/docs/en/2.4.1/cookbooks-retention-expiry/#__docusaurus), it is independent from pulsar_msg_backlog. This aimed to show the messages  in retention?

**Comment by one70six** [comment]
@jiazhai thanks for the response! I would think:

- pulsar_msg_ttl: Yes, the number of messages that will not be in backlog after a TTL. Or maybe you could calculate a histogram of the avg. TTL for 1m, 5m, 30m, 1h, etc. so that you can visualize how the messages are being affected by TTL.

- pulsar_msg_retention: Yes, this aimed to show the messages in retention. After the TTL expires, the messages should show up here. You could also do a histogram here as well to visualize how the messages are being removed from Pulsar completely.

Thanks!

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
