### ISSUE TITLE
Helm chart does not allow ingress TLS to be enabled without a secretName

### ISSUE THREAD

**Issue by juliohm1978** [apache/pulsar#5858]
**Describe the bug**
The provided helm chart can create an Ingress with TLS, but it requires a `secretName` to be added. This is not an Ingress requirement and, in some cases, the ingress controller can provide a default certificate when the Ingress object does not declare one.

**To Reproduce**
Deploy the helm chart with an Ingress enabled and an empty tls `secretName`.

**Expected behavior**
I expect to be able to configure the Ingress TLS without the need to give it a `secretName`. My Ingress controller will use a default certificate.

**Comment by jiazhai** [comment]
Thanks @juliohm1978 for working on this issue
