### ISSUE TITLE
Flink event time based windowing functions not working with pulsar

### ISSUE THREAD

**Issue by subbu107** [apache/pulsar#5866]
We are using Event time based windowing functions in Flink. The source is a partitioned Pulsar topic . The timestamp field is decided by the processing function in flink.
The event time is extracted from the message by attaching a TimeStampExtractor to the stream which extracts time from the message 

#### Expected behavior

The window should get triggered once the watermark is crossed.

#### Actual behavior

We noticed that the window does not triggered though the watermark is crossed.

#### Steps to reproduce

Attaching the sample code. 
[pulsar-flink-preload-new.zip](https://github.com/apache/pulsar/files/3968426/pulsar-flink-preload-new.zip)

#### System configuration
**Pulsar version**: 2.4.2
Flink version : 1.8.2

**Comment by jiazhai** [comment]
@yjshen to take a look

**Comment by jiazhai** [comment]
Seems @yjshen not able to reproduce, because lack of table info.

**Comment by yjshen** [comment]
Hi @subbu107 , I saw you were logging in trigger as well as window function, could you please provide the log file of the program?

**Comment by yjshen** [comment]
Or could you simply remove `.trigger(new MovingAverageTrigger(timeField,0L,(long)windowSize))` and use the default trigger to see what's happening?

BTW I think this issue is off-topic since the watermark generation and window trigger / proceessing are all constructed in the program instead of inside pulsar-flink connector.

**Comment by subbu107** [comment]
Hi @yjshen , I did also try with default trigger, it still didn't work.

Basically it can be simulated in the following way :
 - set flink env parallelism to 4 
 - set consumerConfigurationData.setSubscriptionType(SubscriptionType.Failover); .
 - number of partitions of source/ sink topics = 2
 - If I increase the number of partitions on  my source and sink topics to 4, it works. Basically if I have fewer partitions than the parallelism that I have set in flink, it stops working.
 
 
 - when I set 
 consumerConfigurationData.setSubscriptionType(SubscriptionType.Shared);, it always works.
However, since we want to maintain processing order, we want to use SubscriptionType.Failover


I will attach the logs shortly

**Comment by subbu107** [comment]
Attaching log after streaming 30 messages in the following format 

message 1:{"source":"test","host":"btpvm0933.hpeswlab.net","diskValue":"300","datatype":"metric_streaming","metricClass":"DISK","metricName":"DISK_UTIL","sampleValue":"0.8727556612521685","timeMeasured":"1577252926318"}

message 30:{"source":"test","host":"btpvm0933.hpeswlab.net","diskValue":"300","datatype":"metric_streaming","metricClass":"DISK","metricName":"DISK_UTIL","sampleValue":"0.4051540996367392","timeMeasured":"1577252962314"}

[flink-root-taskexecutor-0-btpvm3362.hpeswlab.net.log](https://github.com/apache/pulsar/files/3999714/flink-root-taskexecutor-0-btpvm3362.hpeswlab.net.log)

**Comment by yjshen** [comment]
Hi @subbu107 , thanks for the log. Regarding the log, your watermark seems to be Long.minvalue and never changes, I think this could be the reason:

```
2019-12-25 11:23:37,311 INFO  com.microfocus.sample.flink.window.MovingAverageTrigger       - ONELEMENT: [TimeWindow: Mon Dec 16 10:44:40 IST 2019 - Mon Dec 16 10:44:50 IST 2019] , [Watermark: -9223372036854775808 , date: "1576473289344"], Element: "btpvm0933.hpeswlab.net"_1576473289999, window MaxTimestamp: {}
2019-12-25 11:23:37,311 INFO  com.microfocus.sample.flink.window.MovingAverageTrigger       - [windowDeadline : 1577253227295, (Wed Dec 25 11:23:47 IST 2019) ]
2019-12-25 11:23:37,311 INFO  com.microfocus.sample.flink.window.MovingAverageTrigger       - Time field value Mon Dec 16 10:44:49 IST 2019
2019-12-25 11:23:37,311 INFO  com.microfocus.sample.flink.window.MovingAverageTrigger       - current watermark Sun Dec 02 22:17:04 IST 292269055
2019-12-25 11:23:37,311 INFO  com.microfocus.sample.flink.window.MovingAverageTrigger       - ------Time field value is greater than current watermark-----
```

and your code path never when to `FIRE_AND_PURGE` branch, therefore window never fired

**Comment by subbu107** [comment]
This is the log with a different topic -- this topics have multiple partitions. No code change !
But as you can see here the window is triggering here.

Usage:
./bin/flink run preloadjob-1.0-SNAPSHOT-jar-with-dependencies.jar  --props /root/flink-1.8.2/config.properties --brokerType pulsar --source moving_average_partitioned_source_1 --sink moving_average_partitioned_sink_1 --keyFields host,metricName --timeField timeMeasured --movingAvgFields sampleValue --window.size 10000 --slide.size 5000 --parallellism 2


[flink-root-taskexecutor-0-btpvm3362.hpeswlab.net.log](https://github.com/apache/pulsar/files/4000533/flink-root-taskexecutor-0-btpvm3362.hpeswlab.net.log)

**Comment by yjshen** [comment]
1. since you are using `MovingAvgTimestampExtractor` which is an implement of `AssignerWithPeriodicWatermarks`, you should set `env.setAutoWatermarkInterval()` to make flink emit watermarks periodically in your `FlinkWindowApp`.

2. The definition of `MovingAverageTrigger` is vague here. Since you are doing watermark based window computation, check `EventTimeTrigger` which is the default trigger for `SlidingEventTimeWindows` if you really need to overwrite its behavior.

3. If you want to read a partitioned topic in parallel (the max parallelism you could achieve currently equals to the number of the partition), you need to create a pulsar source for each partition and create datastream for each of them:

```
DataStream<String> stream0 = env.addSource(consumer read partition 0).setParallelism(1);
DataStream<String> stream1 = env.addSource(consumer read partition 1).setParallelism(1);
DataStream<String> streamn = env.addSource(consumer read partition n).setParallelism(1);

DataStream<String> finalStream = stream0.union(stream1, stream2, ... , stream n);
```
 and use finalStream as your return value for `addSourceTopics`.

**Comment by subbu107** [comment]
Attaching the logs with 2 changes : 
- default trigger
-  env.getConfig().setAutoWatermarkInterval(1000L);

[flink-root-taskexecutor-0-btpvm3362.hpeswlab.net.log](https://github.com/apache/pulsar/files/4001622/flink-root-taskexecutor-0-btpvm3362.hpeswlab.net.log)

I still don't get the result data in the sink topic with this change.

We were using Kafka earlier, we did not have to create separate pulsar source for each partition with kafka -- the same code worked with partitioned kafka topic; hence was wondering. 

So is the only solution to create source for each partition?

**Comment by jiazhai** [comment]
@yjshen Would you please help answer above question？

**Comment by yjshen** [comment]
Hi @subbu107, I've created a repo for you to enable IDE-based flink program debugging,  using JUnit, you could find it here https://github.com/yjshen/flink-pulsar-playground. Please make your program as a test case and check what happens by debugging it. :)

**Comment by subbu107** [comment]
hi yjshen,
Sorry I was away on vacation and could not try this yet.
Were you able to try out the sample code, to reproduce the issue on standalone pulsar? 
Do you see any issues with the sample code?

**Comment by subbu107** [comment]
Hi @yjshen ,
I've added the program but haven't been able to run it as yet since I'm having a few issues running it on the local docker environment. 
Attaching the code in case you could  run it.
[flink-pulsar-playground-flinkwindow.zip](https://github.com/apache/pulsar/files/4107618/flink-pulsar-playground-flinkwindow.zip)

**Comment by tisonkun** [comment]
Closed as stale. I suggest you report pulsar-flink related issues at https://github.com/streamnative/flink or https://issues.apache.org/jira/projects/FLINK/issues.
