### ISSUE TITLE
JDBC Sink Leaks DB Credentials

### ISSUE THREAD

**Issue by jeloba** [apache/pulsar#5868]
**Describe the bug**
The JDBC sink leaks db credentials (the in contents of 'configs') into logs and API results. 

**To Reproduce**
0. Start Pulsar standalone
1. Register a JDBC sink
2. Observe the log output on a standalone pulsar instance
3. It contains the credentials in a line starting with 'ProcessBuilder starting the process with' in a JSON object called '--function_details'
4. Fetch the sink details using 'bin/pulsar-admin sinks get'
5. Observe that the result also contains the credentials

**Expected behavior**
Secrets should not be logged or returned by the API.

**Comment by jiazhai** [comment]
@tuteng Would you please help on this issue?

**Comment by tuteng** [comment]
Thank you for reporting this problem. The current configuration is printed in function_worker. We may need to plan how to replace this sensitive information. Please let us know if you have any good suggestions. @jeloba

**Comment by jeloba** [comment]
Maybe storing the password in the 'secrets' map instead of 'configs' would be an option?

**Comment by sijie** [comment]
+1 we should pass in the credentials through secrets map.

**Comment by tisonkun** [comment]
cc @nicoloboschi as you recently touch JDBC sink component, do you think this issue is still relevant and we should pick it up?

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
