### ISSUE TITLE
run bin/pulsar-admin namespaces list public with 404 return

### ISSUE THREAD

**Issue by superbaobei** [apache/pulsar#5880]
**Describe the bug**
when I start pulsar in standalone model,I change conf *webServicePort* in file *conf/standalone.conf* from 8080 to 8081.
I want to take a look at namespace list,when I run *bin/pulsar-admin namespaces list public*,pulsar gave me a reqponse with 404

**To Reproduce**
cd {pulsar_home}/
bin/pulsar-admin namespaces list public
return:
```
[resin@localhost apache-pulsar-2.4.2]$ bin/pulsar-admin namespaces list public
HTTP 404 Not Found

Reason: HTTP 404 Not Found 
```

**Desktop (please complete the following information):**
 - OS: centos 

**Additional context**
I also change conf in *pulsar_env.sh* from *PULSAR_MEM=${PULSAR_MEM:-"-Xms2g -Xmx2g -XX:MaxDirectMemorySize=4g"}* to *PULSAR_MEM=${PULSAR_MEM:-"-Xms1g -Xmx1g -XX:MaxDirectMemorySize=4g"}*,but I think this won't cause this 404

Thanks!

**Comment by codelipenghui** [comment]
You can try to use:
```
$ bin/pulsar-admin --admin-url http://127.0.0.1:8081 namespaces list public
```

**Comment by superbaobei** [comment]
> You can try to use:
> 
> ```
> $ bin/pulsar-admin --admin-url http://127.0.0.1:8081 namespaces list public
> ```

Ok.When I specified *--admin-url* ,pulsar executed correctly.
thanks！

**Comment by jiazhai** [comment]
@superbaobei you could also set config/client.conf to do it.
Thanks @codelipenghui for help on this issue. would like to close it.
