### ISSUE TITLE
[Docs]Old version download link error

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar#5887]
**Describe the bug**

http://pulsar.apache.org/docs/en/2.3.0/standalone/

![image](https://user-images.githubusercontent.com/1907867/71054469-1387e580-218d-11ea-9c08-289f509c8970.png)

The old version has been removed https://archive.apache.org/dist/pulsar/. Only the latest two versions are kept here in https://www-eu.apache.org/dist/pulsar/.

**To Reproduce**

**Expected behavior**
Displays the correct download link

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
We should fix this script https://github.com/apache/pulsar/blob/master/site2/website/scripts/replace.js to solve this problem.

Test

```
git clone https://github.com/apache/pulsar.git
cd pulsar/site2/website
yarn install
rm -rf build
yarn build
node scripts/replace.js
```

Check file build/pulsar/docs/en/2.3.0/standalone/index.html, search key `downloads page`:

```
<li><p>from the Pulsar <a href="/download">downloads page</a></p></li>
```

**Comment by huangdx0726** [comment]
It means download  the latest two versions  from https://www-eu.apache.org/dist/pulsar/, others from https://archive.apache.org/dist/pulsar?  Or, all of them from https://archive.apache.org/dist/pulsar/.

**Comment by tuteng** [comment]
I think both methods are ok, our goal is to let users to download the package correctly.
