### ISSUE TITLE
Cannot import Python pulsar-client==2.4.2 on Mac Os Catalina 10.15.2

### ISSUE THREAD

**Issue by bry00** [apache/pulsar#5899]
**Describe the bug**
With correctly installed `libpulsar` and `protobuf` and pulsar-client 2.4.2 cannot import pulsar on Python 3.7.5. An attempt to import raises ```ImportError: dlopen(/tmp/check/.venv/lib/python3.7/site-packages/_pulsar.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/protobuf@2.6/lib/libprotobuf-lite.9.dylib```

**To Reproduce**
1. Run:
```
# python3 -V
Python 3.7.5
# python3
Python 3.7.5 (default, Dec 12 2019, 09:41:03)
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulsar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/check/.venv/lib/python3.7/site-packages/pulsar/__init__.py", line 102, in <module>
    import _pulsar
ImportError: dlopen(/tmp/check/.venv/lib/python3.7/site-packages/_pulsar.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/protobuf@2.6/lib/libprotobuf-lite.9.dylib
  Referenced from: /tmp/check/.venv/lib/python3.7/site-packages/_pulsar.cpython-37m-darwin.so
  Reason: image not found
```

2. See the error

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.2

**Comment by jiazhai** [comment]
@sijie is helping on this 2.4.2 version.

**Comment by sijie** [comment]
I don't think we publish the client for 10.15. we only have vagrant images to build 10.12, 10.13 and 10.14. We will have to figure out a plan for 10.15.

**Comment by sijie** [comment]
@bry00 we have just published 2.4.2 python client for osx 10.15. Can you try it again?

**Comment by bry00** [comment]
> @bry00 we have just published 2.4.2 python client for osx 10.15. Can you try it again?

It does not work yet:
```bash
# python3
Python 3.7.5 (default, Dec 12 2019, 09:41:03)
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulsar
Segmentation fault: 11
```

**Comment by sijie** [comment]
@bry00 can you try install `protobuf` and `zstd`?

```bash
brew install zstd protobuf
```

**Comment by bry00** [comment]
> @bry00 can you try install `protobuf` and `zstd`?
> 
> ```shell
> brew install zstd protobuf
> ```

```bash
(venv) # brew install zstd protobuf
(...)
Warning: zstd 1.4.4 is already installed and up-to-date
To reinstall 1.4.4, run `brew reinstall zstd`
Warning: protobuf 3.11.2 is already installed and up-to-date
To reinstall 3.11.2, run `brew reinstall protobuf`
(venv) # python3 -V
Python 3.7.5
(venv) # pip install pulsar-client --upgrade
(...)
Collecting pulsar-client
  Downloading Installing collected packages: pulsar-client
  Found existing installation: pulsar-client 2.4.2
    Uninstalling pulsar-client-2.4.2:
      Successfully uninstalled pulsar-client-2.4.2
Successfully installed pulsar-client-2.5.0
(venv) # python3
Python 3.7.5 (default, Dec 12 2019, 09:41:03)
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulsar
Segmentation fault: 11
(venv) #
```

**Comment by bry00** [comment]
I've succeed with installing and using `pulsar-client==2.5.0` using regular (brew not pyenv) Python 3.7.6 installation.
It seems, that this segmentation fault is caused by some incompatibility of` pulsar-client` with pyenv, but it would be another issue.
I close this issue.

**Comment by Dcep** [comment]
> @bry00 can you try install `protobuf` and `zstd`?
> 
> ```shell
> brew install zstd protobuf
> ```

Fixed my issue with same error with pulsar-client==2.5.0 & OSX 10.13.6
