### ISSUE TITLE
[pulsar-broker][REST API] Support `terminate` all partitions of a partitioned topic

### ISSUE THREAD

**Issue by zymap** [apache/pulsar#5905]
**Is your feature request related to a problem? Please describe.**

Pulsar supports `terminate` a non-partitioned-topic or a partition of a partitioned topic. If there has a partitioned topic with too many partitions, users need to get all partitions and `terminate` them one by one. We need to support `terminate` all partition of a partitioned topic.

**Describe the solution you'd like**

Support `terminate` all partition of a partitioned topic.

The implementation is similar to this: https://github.com/apache/pulsar/blob/bdb1f4cb3d1df27957a1472e02d7a22f229aaef8/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L890
We need to get all partition of a partitioned topic if the topic is a partitioned topic and send `terminate` requests and waiting for them back.

**Additional context**

We need to add an integration test or unit test for verifying this change.

There has a similar unit test about REST API: https://github.com/apache/pulsar/blob/bdb1f4cb3d1df27957a1472e02d7a22f229aaef8/pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java#L136

**Comment by Loghijiaha** [comment]
I am quite experienced in pulsar and also interested in this ticket.

**Comment by zymap** [comment]
@Loghijiaha Sorry for the late response. 

You can pick up this and feel free to let me know if you have any problems.

Thanks.

**Comment by antimpatel** [comment]
Hey, I want to go ahead with this, 
after initial investigation what I have understood is that We can implement a new method similar to the one you mentioned, in TopicImpl .java class and make a post-call to the path for all partitioned topic and return. 
let me know if I am missing something here?

**Comment by zymap** [comment]
Hi, @antimpatel 

Maybe we can implement this on the original method.
Currently, we have already support terminate a non-partitioned topic or a partition of a partitioned topic. So we just add some codes to delete them one by one if the topic is partitioned topic.

**Comment by antimpatel** [comment]
@zymap 
Since terminate Api returns the messageId, so To accommodate the above changes we also need to change the response of the API if we want to implement this in the same method.
Why it's not recommended by you to create a new method in API and in TopicBase to accommodate this change?
I believe it's better to have two separate API method, one for a single topic and other for the partitioned topic, because it's more readable and abstracted out as per API description.

**Comment by zymap** [comment]
@antimpatel  Oh. I missed the response. You are right.
