### ISSUE TITLE
Add ability to change server log level for prebuilt images

### ISSUE THREAD

**Issue by Lanayx** [apache/pulsar#5917]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to provide debug-level broker logs to resolve the issue (like https://github.com/apache/pulsar/issues/5877). With current helm chart I don't see a way to do this

**Describe the solution you'd like**
Expose log level as helm chart value for brokers. I think it will be helpful for other components as well: proxy, bookeeper, zookeeper.

**Describe alternatives you've considered**
I don't know any alternatives

**Additional context**
Looks like the issue is present with regular docker deployment as well.

**Comment by jiazhai** [comment]
Thanks @Lanayx for reporting this issue. also put this into help wanted.

**Comment by jiazhai** [comment]
@wolfstudy we may need to export log4j configs out to yaml

**Comment by sijie** [comment]
@Lanayx : 

I think you can configure the log level through the system environments provided in `bin/pulsar`. You can add `PULSAR_LOG_LEVEL` and `PULSAR_LOG_ROOT_LEVEL` to the corresponding configmap.

```
PULSAR_LOG_DIR=${PULSAR_LOG_DIR:-"$PULSAR_HOME/logs"}
PULSAR_LOG_APPENDER=${PULSAR_LOG_APPENDER:-"RoutingAppender"}
PULSAR_LOG_ROOT_LEVEL=${PULSAR_LOG_ROOT_LEVEL:-"info"}
PULSAR_LOG_LEVEL=${PULSAR_LOG_LEVEL:-"info"}
PULSAR_ROUTING_APPENDER_DEFAULT=${PULSAR_ROUTING_APPENDER_DEFAULT:-"Console"}
```
