### ISSUE TITLE
pop up "Templating init failed " when querying topics on grafana dashboard

### ISSUE THREAD

**Issue by dockerzhang** [apache/pulsar#5918]
**Describe the bug**
version: 2.4.2
bug: pop up "Templating init failed " when querying topics on grafana dashboard, deployed by kubernetes.

**To Reproduce**
1. Go to 'http://k8s_node_ip:grafana_node_port/dashboard/file/topic.json?refresh=5s&orgId=1'
2. See error
![image](https://user-images.githubusercontent.com/18047329/71344796-71a63580-259e-11ea-9952-0c6f950d447c.png)

**Comment by jiazhai** [comment]
@dockerzhang Which yaml file were you using, and was there any changes?

**Comment by jiazhai** [comment]
@tuteng  @wolfstudy  to take a look

**Comment by wolfstudy** [comment]
@dockerzhang i can't reproduce your issue.

My step of reproduce:

- cd deployment/kubernetes/helm
- helm install test-pulsar --values ./pulsar/values-mini.yaml ./pulsar
- kubectl exec -it test-pulsar-grafana-5b6db946f9-dprkg -n pulsar  /bin/bash
- curl -v http://127.0.0.1:3000/dashboard/file/topic.json?refresh=5s&orgId=1

the output as follows:

```
root@test-pulsar-grafana-5b6db946f9-dprkg:/# curl -v http://127.0.0.1:3000/dashboard/file/topic.json?refresh=5s&orgId=1
[1] 44
root@test-pulsar-grafana-5b6db946f9-dprkg:/# * Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> GET /dashboard/file/topic.json?refresh=5s HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 127.0.0.1:3000
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=UTF-8
< Set-Cookie: grafana_sess=b35b59c93ab33f25; Path=/; HttpOnly
< Date: Fri, 03 Jan 2020 09:31:48 GMT
< Transfer-Encoding: chunked

....
```

- helm version

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

@dockerzhang please provide more info for this.

**Comment by dockerzhang** [comment]
@wolfstudy I deployed pulsar referring to
[deploy-kubernetes](http://pulsar.apache.org/docs/en/deploy-kubernetes/), i didn't use helm.
There is only one different step, pulsar-dashboard is deployed with 2.4.1 tag because of [5847](https://github.com/apache/pulsar/issues/5847).

**Comment by sijie** [comment]
@dockerzhang 

the yaml files are pretty out-of-dated. It is hard for us to maintain individual yaml files for different platforms. we have decided to remove those yaml files.

Please consider using the latest helm chart for deploying Pulsar on Kubernetes. The Helm chart is now protected and verified using the Helm chart testing framework and it is the official support Helm chart by the Pulsar PMC.

follow the instructions (http://pulsar.apache.org/docs/en/kubernetes-helm/) to get started
follow the instructions to configure (http://pulsar.apache.org/docs/en/helm-deploy/) the helm chart to install a production setup
