### ISSUE TITLE
Where can I find the logs for the deployed helm installation?

### ISSUE THREAD

**Issue by davdes44** [apache/pulsar#5921]
#### Expected behavior
When running pulsar standalone, I can see the server logs in stdout and also logs in the pulsar directory for functions and etc.

#### Actual behavior

 In my deployed helm install, I cannot figure out where these logs are in the pods. When I exec into the pods and look in /pulsar/logs/ the log files are empty.

#### Steps to reproduce

Deploy pulsar through its helm chart

#### System configuration
**Pulsar version**: 2.4.1

**Comment by cckellogg** [comment]
I think logs only go to standard out when running in kubernetes. Can you see the logs if you run `kubectl logs -f <a-pulsar-pod>`

**Comment by davdes44** [comment]
Yes, I guess what I'm looking for is logs for my function I created, or even the "server" logs. Do the fall under the broker pods?

**Comment by cckellogg** [comment]
What kind of runtime are you using for functions? If you run them using the kubernetes runtime the logs will run as separate pods and the logs will go to standard out. If you are running them in process or thread mode the logs should be where the worker is running. This could be with the broker or in a separate worker pod depending on how the chart was deployed.

**Comment by davdes44** [comment]
Currently using the kubernetes runtime, not too familiar with process or thread mode

**Comment by cckellogg** [comment]
If you run `kubectl logs -f <a-function-pod>` are you able to see the logs?

**Comment by davdes44** [comment]
So when I say function, i'm specifically referring to pulsar functions ie: https://pulsar.apache.org/docs/en/functions-overview/ 
I don't think there is a pod for a pulsar function.
