### ISSUE TITLE
On the dependencies in the pom.xml files.

### ISSUE THREAD

**Issue by lihanhui** [apache/pulsar#5922]
**Describe the bug**
Most of pom.xml files, in which some dependencies on the pulsar itself are written as following:
    ......
    \<dependency>
      \<groupId>org.apache.pulsar\</groupId> // **THIS LINE**
      \<artifactId>pulsar------\</artifactId>
      \<version>${project.version}\</version>
    \</dependency>
    ......
But most of them are like this:
\<dependency>
      \<groupId>${project.groupId}\</groupId> // **THIS LINE**
      \<artifactId>pulsar------\</artifactId>
      \<version>${project.version}\</version>
    \</dependency>

**Although both of them work, why not use JUST one of them (e.g.  \<groupId>${project.groupId}\</groupId>)**. 
![pulsar-pom](https://user-images.githubusercontent.com/4320310/71367272-848d2a00-25df-11ea-92e2-92c2635d08df.png)

**Comment by jiazhai** [comment]
@lihanhui `<groupId>${project.groupId}</groupId>` Thanks for the checking. Would you like to contribute to make them unify?

**Comment by lihanhui** [comment]
OK

**Comment by vcottagiri** [comment]
@jiazhai - Can I look into this? If so please assign this to me, thx

**Comment by sijie** [comment]
@vcottagiri you are welcome to make the contribution! Assigned to you.
