### ISSUE TITLE
Is georeplication docs outdated since PIP-33 was released?

### ISSUE THREAD

**Issue by ograycode** [apache/pulsar#5924]
The [site](https://github.com/apache/pulsar/blob/master/site2/docs/administration-geo.md#subscriptions-are-local-to-a-cluster) says:

> Subscriptions are local to a cluster
> While producers and consumers can publish to and consume from any cluster in a Pulsar instance, subscriptions are local to the clusters in which the subscriptions are created and cannot be transferred between clusters. If you do need to transfer a subscription, you need to create a new subscription in the desired cluster.

Should this be updated since [PIP-33](https://github.com/apache/pulsar/wiki/PIP-33%3A-Replicated-subscriptions) was released in 2.4.0?

My understanding is since PIP-33 was released then subscriptions are replicated so a consumer can fail over?

**Comment by sijie** [comment]
@ograycode yes we need to update the document.

after PIP-33, user can configure a subscription to be replicated. hence it supports both local subscription and replicated subscription.
