### ISSUE TITLE
Ftr:pulsar-proxy should support WebSocket && Use Pulsar's WebSocket API to Extend Authentication and Authorization

### ISSUE THREAD

**Issue by pantianying** [apache/pulsar#5925]
**Is your feature request related to a problem? Please describe.**
pulsar WebSocket Client libraries not support Authentication and Authorization which I really want to. And this should add to pulsar-proxy
**Describe the solution you'd like**

Websocket is a good cross language tool, but the lack of this function makes me headache. We have customers who use the Java version of the lower version (1.7) and cannot use the official client. So we want to use the websocket protocol. But the lack of permission management makes the project unable to proceed

**Describe alternatives you've considered**
pulsar-proxy should support WebSocket to forward to broker and finish Authentication and Authorization

**Additional context**

**Comment by hpvd** [comment]
client feature matrix shows auth support for websocket (version 2.5.0) 
https://github.com/apache/pulsar/wiki/Client-Features-Matrix

**Comment by tisonkun** [comment]
Closed as fixed.
