### ISSUE TITLE
Change the time unit of `patternAutoDiscoveryPeriod` to SECONDS

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#5927]
**Is your feature request related to a problem? Please describe.**

Currently the time unit of `patternAutoDiscoveryPeriod` is MINUTE. People is not able to configure the time duration to be leass than 1 minute.

**Describe the solution you'd like**

It would be good to add an overloaded method in the consumer builder to support passing TimeUnit in.

```
patternAutoDiscoveryPeriod(int interval, TimeUnit unit);
```

**Comment by zhenglaizhang** [comment]
i think i could help add the overload this week.

**Comment by sijie** [comment]
@zhenglaizhang awesome!
