### ISSUE TITLE
Can support read/write properties from/to Message in flink pulsar consumer/producer

### ISSUE THREAD

**Issue by duli559** [apache/pulsar#5934]
**Is your feature request related to a problem? Please describe.**
Currently, flink pulsar consumer/producer can not read/write properties from/to Message, we hope to support it.

**Describe the solution you'd like**
A) For consumer, 
change method `deserialize(Message message)’` access level from private to proteced in class 'PulsarConsumerSource', and we can overrided it in derived class.
B) For producer,
1. add a method like following code,  and we can overrided it in derived class.
`protected Map<String, String> generateProperties(IN value) {
        return new HashMap<>();
 }`
2. invoke TypedMessageBuilder.properties() method addtional in `invoke(IN value, Context context)` method at class 'FlinkPulsarProducer'.

**Comment by duli559** [comment]
@yjshen , hi, can you have a lool, thanks!

**Comment by yjshen** [comment]
Hi @duli559 , thanks for bringing this up.

For the consumer, I think the proposed way is possible, your derived class could return a Tuple (Map, T) for each message, and use the tuple afterward.

For the producer, the `invoke` method is invoked for each `value` in the stream, therefore,  you should use this `value` and tell which part goes into properties and which part went goes into Message body. I think you could extend the existing `FlinkPulsarProducer` directly and just overwrite the `invoke` method?

**Comment by duli559** [comment]
Hi @yjshen , thanks for your reply.

I think Message properties not only created by `value`, but also other ways, eg: some constants, values that are updated periodically, etc. so i think if we extract a method in super class and override in derived class, it is a better way, and we don't need care other details in derived class.

Thanks!

**Comment by yjshen** [comment]
@duli559 that makes sense to me. Please create a PR for this :)

**Comment by duli559** [comment]
ok
