### ISSUE TITLE
Multiple pulsar clusters use the same bookkeeper cluster ?

### ISSUE THREAD

**Issue by SunDapeng1** [apache/pulsar#5935]
Can multiple pulsar clusters use the same bookkeeper cluster? If I had deployed the bk separately in advance and the metadata was stored under  `/ledgers`, how would I configure the pulsar so that every pulsar recognizes `/ledgers` ? 
(According to my test: pulsar initializes metadata to `/pulsar`, then the pulasr cluster can only recognize `/pulsar/ledger` to store metadata of bk)

**Comment by jiazhai** [comment]
Thanks @SunDapeng1 for open this issue. currently `class PulsarClusterMetadataSetup`, which is called by command `bin/pulsar initialize-cluster-metadata`, will do all the metadata setup for Pulsar.
As discussed here with @murong00 , 
https://github.com/apache/pulsar/pull/5879#discussion_r359134619
we should make this configuration more easy. 

But, Seems in current code, of PulsarClusterMetadataSetup, it is using /ledgers for bookies by default? In your deployment, are you using the localzk as: zkhost:2181/pulsar ? maybe just change it back to zkhost:2181 would solve this issue?

**Comment by SunDapeng1** [comment]
Thank you for your reply.  Maybe I didn't describe it clearly. What I want to express is that if the bk metadata is in ` /ledgers`, then when the first pulsar is deployed, the metadata can be initialized to `/`. At this time, the first pulsar cluster can normally identify `/ledgers` Bk cluster, but how can I deploy a second pulsar cluster, so that the second pulsar cluster also uses the same bk cluster `/ledgers`?

**Comment by jiazhai** [comment]
@SunDapeng1 , as we  discussed, the main issue is make bookie service (/ledgers)  configurable. This may involves some change like `PulsarClusterMetadataSetup` `InternalConfigurationData`. 
at present, `ZkLedgersRootPath` that passed into `InternalConfigurationData` is some kind of hard coded.

**Comment by SunDapeng1** [comment]
@jiazhai  How is this issue going?
