### ISSUE TITLE
got HTTP 404 error when running "pulsar-admin functions list" on functions-worker

### ISSUE THREAD

**Issue by wjybupt** [apache/pulsar#5947]
**Describe the bug**
when running "pulsar-admin functions list" on functions-worker, i got HTTP 404 error, however, running "pulsar-admin functions status ..." got the right response

**To Reproduce**
I have 3 functions-worker and 3 broker, and in the client.conf on all functions-worker, webServiceUrl =http://\<functions-worker ip1\>:6750/ 
brokerServiceUrl=pulsar://\<broker ip1\>:6650,\<broker ip2\>:6650,\<broker ip3\>:6650/

**Expected behavior**
get the functions list

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jiazhai** [comment]
Thanks @wjybupt for reporting this issue.  Which version of Pulsar is used? 
@wolfstudy Is this a know issue?

**Comment by wolfstudy** [comment]
> webServiceUrl =http://<functions-worker ip1>:6750/

The pulsar-admin is using `8080`, can you try it again?

**Comment by wjybupt** [comment]
ok, i will try on monday as it was deploy in the product environment which is isolate from the public network. thank u~



---Original---

**Comment by wjybupt** [comment]
according to the official doc, "pulsar-admin functions list" is support by the functions-worker, and in functions-worker's config file(functions_worker.yml), the workerPort is 6750 and workerPortTls is 6751.&nbsp;

when i use 6750, "pulsar-admin functions list" is unavailable, but "pulsar-admin sinks list" works. and other cmd just like "pulsar-admin functions get/state/stats" works well, that why i am confused.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"冉小龙"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月3日(星期五) 晚上8:55
收件人:&nbsp;"apache/pulsar"<pulsar@noreply.github.com&gt;;
抄送:&nbsp;"kiss fire"<wjybupt@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/pulsar] got HTTP 404 error when running "pulsar-admin functions list" on functions-worker (#5947)



 
webServiceUrl =http://:6750/
  
The pulsar-admin is using 8080, can you try it again?

**Comment by liangyuanpeng** [comment]
You can try : 
```
curl http://functions-worker ip1:6750/admin/v2/functions/{TENANT}/{NAMESPACE}
 ```  

Function worker has no ``functions list API (for all tenant)``

**Comment by trexinc** [comment]
Same issue for me on 2.5.1:
```
bin/pulsar-admin functions list --tenant internal --namespace classification
HTTP 404 Not Found

Reason: HTTP 404 Not Found
```

but there is a function there:

```
bin/pulsar-admin functions get  --tenant internal --namespace classification --name classification_out_router
{
  "tenant": "internal",
  "namespace": "classification",
  "name": "classification_out_router",
  "className": "classification_out_router.RoutingFunction",
  "inputSpecs": {
    "persistent://internal/classification/out": {
      "isRegexPattern": false
    }
  },
  "processingGuarantees": "ATLEAST_ONCE",
  "retainOrdering": false,
  "userConfig": {},
  "runtime": "PYTHON",
  "autoAck": true,
  "parallelism": 1,
  "resources": {
    "cpu": 1.0,
    "ram": 1073741824,
    "disk": 10737418240
  },
  "cleanupSubscription": true
}
```

**Comment by Hongten** [comment]
I encountered the same issue when I list brokers. In my case, I change the 8080 port to 8087. The pulsar version is 2.8.1.
```
./bin/pulsar-admin brokers list pulsar-cluster
HTTP 404 Not Found

Reason: HTTP 404 Not Found
```

**Comment by tisonkun** [comment]
Thanks for sharing your investigation @Hongten!

I believe it's something about port conflict or port misconfigured. Closed as information delivered.

If you think it's a bug, feel free to open a new issue with the Pulsar version and reproduce steps (demo repo).

**Comment by Arulvadivel** [comment]
I am facing this issue in pulsar 3.1 or 3.0.1 docker containers. I have tried change the port config as mentioned in the container. still facing this issue. 
Could someone suggest here ?
