### ISSUE TITLE
can't create function on some node of the  functions-worker

### ISSUE THREAD

**Issue by wjybupt** [apache/pulsar#5948]
**Describe the bug**
I have 3 functions-worker and 3 broker, and in the client.conf on all functions-worker, webServiceUrl =http://\<functions-worker ip1\>:6750/
brokerServiceUrl=pulsar://\<broker ip1\>:6650,\<broker ip2\>:6650,\<broker ip3\>:6650/

when webServiceUrl set ip1, i can delete my function but got "HTTP 500 Internal Server Error" when create it again,
but when the ip is set to ip2 or ip3, i can delete and create it either.

**To Reproduce**

the version is 2.4.1, i don't know whether is a common problem or just for me. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jiazhai** [comment]
@wolfstudy to confirm this issue.

**Comment by wolfstudy** [comment]
@wjybupt same with #5947

**Comment by wjybupt** [comment]
if you mean both the problem is about pulsar-admin, they are same issue, but the phenomenons are different


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"冉小龙"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月5日(星期天) 晚上9:34
收件人:&nbsp;"apache/pulsar"<pulsar@noreply.github.com&gt;;
抄送:&nbsp;"kiss fire"<wjybupt@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/pulsar] can't create function on some node of the  functions-worker (#5948)




@wjybupt same with #5947

**Comment by devinbost** [comment]
@wjybupt Is this issue intermittent or constant?

**Comment by wjybupt** [comment]
it is constant




---Original---

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
