### ISSUE TITLE
unknown field "requests" in io.k8s.api.core.v1.Container

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar#5958]
**Describe the bug**

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "requests" in io.k8s.api.core.v1.Container
```

**To Reproduce**

1. helm install test-pulsar --values ./pulsar/values.yaml ./pulsar

**Desktop (please complete the following information):**
 - OS: Mac os

**Additional context**

```
$ helm version

version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

```
$kubectl version

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by wolfstudy** [comment]
When we comment out the following code in `grafana` in `values.yaml`: 

```
#  resources:
#    requests:
#      memory: 4Gi
#      cpu: 1
```

everything is ok.

**Comment by sijie** [comment]
It seems that this is a helm issue.

**Comment by jiazhai** [comment]
helm3 has this issue, while helm2 is Ok

**Comment by jiazhai** [comment]
After comments the config out, it is OK now. would like to work with helm to solve this issue later.

> When we comment out the following code in `grafana` in `values.yaml`:
> 
> ```
> #  resources:
> #    requests:
> #      memory: 4Gi
> #      cpu: 1
> ```
> 
> everything is ok. And in `helm2`, the issue does not appear to occur

**Comment by roman-popenov** [comment]
There is a mistake in the charts pulsar manager template file at line 65:
{{ toYaml .Values.grafana.resources | indent 10 }} should be {{ toYaml .Values.pulsar_manager.resources | indent 12 }}

**Comment by sijie** [comment]
I think the change was for helm3. We might need to consider support both helm3 and helm2.
