### ISSUE TITLE
Remove non-persistent broker-mode once broker can handle both types of topic properly

### ISSUE THREAD

**Issue by rdhabalia** [apache/pulsar#596]
#### Expected behavior

PR #538 has introduced non-persistent topic in pulsar. It also provides broker-configuration to force broker to only load non-persistent topics. This configuration is introduced to learn broker's behavior with non-persistent topics and it should be removed in long run as broker should be able to handle both types of topics together.

Creating this issue to track this task and will mention into code to get detailed explanation.

**Comment by sijie** [comment]
@rdhabalia can you clarify more on this issue? doesn't broker already support both types of topics now?

**Comment by sijie** [comment]
@rdhabalia is this feature still needed?

**Comment by rdhabalia** [comment]
@sijie yes, I will address this issue soon. thanks.
