### ISSUE TITLE
After stopping the bookie and recovering, it can be produced at this time, but cannot be consumed normally. Restarting the broker can resume normal

### ISSUE THREAD

**Issue by liudezhi2098** [apache/pulsar#5962]
**Describe the bug**
Topic(E=3,W=3,A=2), stopped 2 bookie nodes, then recover the 2 bookie, 
The message can be produced normally, but the consumer cannot pull the message unless the broker is restarted.

**To Reproduce**
1. sh pulsar-daemon stop bookie -- A 
2. sh pulsar-daemon stop bookie -- B
3. production message, return result is normal
4. consumers have been unable to pull news

**Comment by jiazhai** [comment]
thanks @liudezhi2098 for helping this this issue
