### ISSUE TITLE
one small barrier in starting the standalone cluster

### ISSUE THREAD

**Issue by fangpengcheng95** [apache/pulsar#5983]
**Describe the bug**
When I started a local standalone cluster according to the documentation, I encountered a small problem that the standalone cluster start failure.
Using the following command
```shell
bin/pulsar standalone
```
The error message is as follows:
```shell
Caused by: java.net.UnknownHostException: failed to resolve 'pdeMacBook-Pro.local' after 4 queries
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:848) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:809) ~[io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
```

**To Reproduce**
```shell
wget https://archive.apache.org/dist/pulsar/pulsar-2.4.2/apache-pulsar-2.4.2-bin.tar.gz
tar xvfz apache-pulsar-2.4.2-bin.tar.gz
bin/pulsar standalone
```

**Desktop (please complete the following information):**
 - OS: Mac OS

**Additional context**
Actually, I have solved this problem by editing "advertisedAddress" configuration in standalone.conf.

**Comment by fangpengcheng95** [comment]
If this issue is important enough, i can add some tips in standalone documentation.

**Comment by fangpengcheng95** [comment]
@Jennifer88huang @codelipenghui @zhaijack @sijie PTAL.

**Comment by jiazhai** [comment]
> Actually, I have solved this problem by editing "advertisedAddress" configuration in standalone.conf.
@fangpengcheng95  right, you need `advertisedAddress` setting in conf file. or use command like: `bin/pulsar standalone -a 127.0.0.1` to assign the advertisedAddress. 

It is appreciate if you could improve the documentation.

**Comment by jiazhai** [comment]
#5998 is for the fix

**Comment by jiazhai** [comment]
Thanks @fangpengcheng95 for the PR
