### ISSUE TITLE
version in PulsarApi.proto(v2) and PulsarApi.pb.go(v3)  not match

### ISSUE THREAD

**Issue by zxbfeng** [apache/pulsar#5984]
The file PulsarApi.pb.go in this project is used proto version 3, but I find the PulsarApi.proto file provided by  https://github.com/apache/pulsar/blob/master/pulsar-common/src/main/proto/PulsarApi.proto is version 2.

**Comment by jiazhai** [comment]
Hi @zxbfeng  PulsarApi wire protocol serialization is generated with a patched version of the protobuf-2.4.1 compiler (for efficiency reasons, eg: pool all the object instances when serializing/deserializing).  So you may find proto 2 and 3 both exist in pulsar

**Comment by sijie** [comment]
the protobuf file is written in v2 syntax. In java client, we use a customized compiler to generate the Java code; in other language clients, we use latest compiler to generate the code. So you will see a newer version in those generated code.

**Comment by sijie** [comment]
Closed this since the question is answered.
