### ISSUE TITLE
New feature 

### ISSUE THREAD

**Issue by Fransvanierland** [apache/pulsar#5987]
I was wondering if we could add Quality of Stream to set stream priority in a stream <kind of QOS>  . Labeling streams based on priority and shortest route,AKA Cost path>  . Something broader than the 3 levels of priority in the queue scheme. Thinking about adding cost of a stream to the 3 different levels.

**Comment by jiazhai** [comment]
@Fransvanierland not quite follow this requirements, what is the priority mainly used for?  Would you please help provide more details.

**Comment by Fransvanierland** [comment]
prio is used in case of congestion in a stream

**Comment by tisonkun** [comment]
Closed as stale.

Feel free to reopen an issue with a concrete proposal. You're welcome to share ideas or early thoughts on the dev@ mailing list or the Discussions forum.
