### ISSUE TITLE
Helm deployment fails to deploy properly

### ISSUE THREAD

**Issue by ckdarby** [apache/pulsar#5992]
**Describe the bug**
Unable to get Pulsar working correctly following the helm deployments.

**To Reproduce**
1. Follow instructions on [helm deployment](https://github.com/apache/pulsar/tree/master/deployment/kubernetes/helm)
2. Try to add a new environment from Pulsar admin manager

**Expected behavior**
Expect Pulsar to come up & be able to use pulsar admin manager to add new environment.

For what I can see in K8 the proxy isn't being exposed properly on the network. Unable to use the minikube ip address for port 30001.

**Comment by ckdarby** [comment]
Since at least commit: 23ae5ec

Everything related to Zookeeper coming up properly is broken in the helm deployment.

**Comment by merlimat** [comment]
@ckdarby  Could you verify just before that commit if it works?

**Comment by ckdarby** [comment]
Works in 811dd45 and it doesn't work with 23ae5e

No idea where it broke between those commits but I know when I pulled master at 23ae5ec the helm deployment stopped working.

**Comment by jiazhai** [comment]
@ckdarby as @merlimat mentioned, would you please help try the commits before 23ae5ec ? , such as 
f95c71f21aae9e8299597295ccb2bc6954d82ae5 or 88fc454173af94d33986e608e94037db556a9226
```
commit 23ae5eca871bde2599f86cebfe9971cb08584bf9
Author: Ali Ahmed <alahmed.se@gmail.com>
Date:   Sat Jan 4 18:30:34 2020 -0800

    Make docker files consistent. (#5949)
    
    Allow volume override for docker commands
    with env variable, this allows the scripts to
    work in dind environments.

commit f95c71f21aae9e8299597295ccb2bc6954d82ae5
Author: Matteo Merli <mmerli@apache.org>
Date:   Sat Jan 4 04:25:04 2020 -0800

    Make standalone to advertise "localhost" to avoid failure when hostname is not resolvable (#5856)
    
    ### Motivation
    
    The standalone service is failing to startup when the hostname is not resolvable to an IP. This is common in laptops.
    
    The reason is that the function worker in standalone is trying to connect to the advertised address rather than "localhost".
    
    To fix this, we should make the standalone to always advertise "localhost" as the the broker address. This is ok because in any case the standalone treats the advertisement as the pulsar proxy, in that it forces the clients to always go through the same service url, so a client connecting from a different host won't have problems.

commit 88fc454173af94d33986e608e94037db556a9226
Author: Jia Zhai <zhaijia@apache.org>
Date:   Fri Jan 3 23:47:21 2020 +0800

    fix reader builder clone error (#5923)
    
    Motivation
    In reader builder, clone() method does not clone the config, and will cause error once we call a builder.clone() concurrently to create readers. This PR mainly try to fix this issue.
    
    Modifications
    use conf.clone(), to make sure conf is cloned.
    add test to verify it.
    fix other small issues, like get() methods, and access level, make it align with consumer/producer builder.
    Verifying this change
    ut passed.
```

**Comment by merlimat** [comment]
cc/ @aahmed-se

**Comment by aahmed-se** [comment]
@merlimat I don't my changes to docker build files can affect this,I did not change the runtime docker images.

**Comment by sijie** [comment]
@ckdarby are you building your image or do you just use the helm chart?

**Comment by ckdarby** [comment]
@sijie Just using the helm charts

**Comment by sijie** [comment]
if you are just using the helm charts, I don't think the changes to images will impact you. What are the errors you have encountered?

**Comment by jack-newbury** [comment]
@sijie I can confirm the issues that are @ckdarby  is having as I'm only using the helm charts and was running into the same issue as described above using the latest release. However, going back to the commit https://github.com/apache/pulsar/commit/811dd45e87600d7163c8f74b40d377831f64bbfb Helm charts work again.

**Comment by sijie** [comment]
@jack-newbury and @ckdarby we have just updated the helm chart. Currently the helm chart is verified by the chart testing framework. You can:

- follow the instructions (http://pulsar.apache.org/docs/en/kubernetes-helm/) to get started
- follow the instructions to configure (http://pulsar.apache.org/docs/en/helm-deploy/) the helm chart to install a production setup

**Comment by ckdarby** [comment]
@sijie Wow, very impressed with the documentation & helm updates! 99% works!

Error with ` helm install --generate-name --values values-mini.yaml .`

Not sure if values.yaml has a bug and that is why the Grafana resources section is commented out or values-mini.yaml is supposed to have that section commented out and match values.yaml.

Got it working with this for the time being:
```diff

diff --git a/deployment/kubernetes/helm/pulsar/values-mini.yaml b/deployment/kubernetes/helm/pulsar/values-mini.yaml
index ff899fcb07..2d7f940aad 100644
--- a/deployment/kubernetes/helm/pulsar/values-mini.yaml
+++ b/deployment/kubernetes/helm/pulsar/values-mini.yaml
@@ -374,10 +374,10 @@ grafana:
   annotations: {}
   tolarations: []
   gracePeriod: 0
-  resources:
-    requests:
-      memory: 64Mi
-      cpu: 0.1
+#  resources:
+#    requests:
+#      memory: 4Gi
+#      cpu: 1
   image:
     repository: apachepulsar/pulsar-grafana
     tag: latest
```

**Comment by sijie** [comment]
@ckdarby Currently the helm chart is maintained in the main source repo while it shouldn't be. Because the changes to the helm chart should be decoupled from the changes to the main code. We are working on moving the helm chart into a separate repo maintained by the PMC - https://github.com/apache/pulsar-helm-chart as part of [PIP-62](https://github.com/apache/pulsar/wiki/PIP-62%3A-Move-connectors%2C-adapters-and-Pulsar-Presto-to-separate-repositories).

**Comment by ckdarby** [comment]
@sijie Sounds good! Was able to get everything running without any issue.

Excellent contributions to whomever did all the changes!
