### ISSUE TITLE
[doc] The link of Pulsar Functions SDK for Java is 404

### ISSUE THREAD

**Issue by huangdx0726** [apache/pulsar#5996]
**Describe the bug**

**To Reproduce**
1. Go to 'https://pulsar.apache.org/docs/en/functions-overview/'
2. Scroll down to 'Word count example'
3. Click on 'Pulsar Functions SDK for Java'

![图片](https://user-images.githubusercontent.com/29513837/71793907-edfa4780-3079-11ea-923f-fe9dc697ed1f.png)

**Comment by Jennifer88huang** [comment]
@huangdx0726 Thank you very much for your report.

**Comment by slominskir** [comment]
I think this is fixed now?   I cannot reproduce.

**Comment by huangdx0726** [comment]
It's fixed.
