### ISSUE TITLE
websocket meet 404 when create producer in standalone mode

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#5997]
**Describe the bug**
This issue is split from issue #5979, which reported by @jeffgrunewald 

I am attempting to build and run pulsar locally for development mode but I receive a 404 whenever attempting to connect to the websocket to create a producer due to a missing "serviceUrl" param. I have set this value to my local host/port in the conf/websocket.conf file but the result is the same. Is there somewhere else this should be set or an undocumented requirement for connecting from the websocket client?

I have not experienced this issue when using the standard Pulsar docker image (apache/pulsar:latest) and running the command bin/pulsar standalone as the CMD directive.

Just to be clear, I am attempting this off a clone of the tip of the master branch, not the latest release tarball. I do see in the logs the `ConsumerStatsRecorderImpl` Pulsar client config is listing the serviceUrl as `"serviceUrl" : "pulsar://127.0.0.1:6650"`. Are the current websocket client connection instructions accurate for the latest unreleased version?

For further context, I am writing a pulsar client library for the Elixir language based on the websocket api. My producer and consumer is connecting to the endpoint `ws://localhost:8080/ws/v2/producer/persistent...` where localhost is dynamically supplied as part of the client configuration and my dockerized pulsar for development purposes is mapping the default service port 8080 from the container to the host.

**Comment by jiazhai** [comment]
@jeffgrunewald  have you use `telnet` to check that the port is OK?

**Comment by jeffgrunewald** [comment]
No but I did confirm that pulling down the latest release tarball and running the same command (`bin/pulsar standalone -a 127.0.0.1`) I get the normal behavior I expect based on the docker image. I have built with the `mvn install` command listed on the readme.

**Comment by jiazhai** [comment]
@jeffgrunewald thanks for the info. so latest 2.4.2 release is fine, while latest master have issues?  We will produce and looking into it.

**Comment by jeffgrunewald** [comment]
> @jeffgrunewald have you use `telnet` to check that the port is OK?

The current commit is failing to build but I checked out a commit 10 back from HEAD (roughly where it was at tip when I last attempted from source over the weekend) and I am still getting the inability to connect, but I am able to successfully telnet to the local host on both ports 6650 and 8080.

When I attempt to connect with my client I see the following two messages in the logs one immediately after the other: 
```
12:04:30.530 [pulsar-web-57-14] WARN  org.apache.pulsar.websocket.ProducerHandler - [127.0.0.1:62817] Failed in creating producer on topic persistent://public/default/integration1: Param serviceUrl must not be blank.
12:04:30.531 [pulsar-web-57-14] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [07/Jan/2020:12:04:30 -0500] "GET /ws/v2/producer/persistent/public/default/integration1 HTTP/1.1" 400 466 "-" "-" 2
```

**Comment by bwalendz** [comment]
Having the same issue with 2.5.0 standalone. WS receives unexpected server response: 400 on connect. This is a complete blocker for anyone using WS. So reverting back to 2.4.2 is working .

**Comment by sijie** [comment]
@bwalendz 2.5.0 has a regression about initializing websocket introduced from #5486. I am working on a fix.
