### ISSUE TITLE
Sending Individual ACK for multiple messages in one command.

### ISSUE THREAD

**Issue by tongsucn** [apache/pulsar#6000]
Shared subscription can only employ Individual ACK, which may limit the throughput. However, from [`PulsarApi.proto`](https://github.com/apache/pulsar/blob/5504dc6e280237ab1abc70fc2889be6149ae518a/pulsar-common/src/main/proto/PulsarApi.proto#L461) we find that Pulsar supports acknowledging multiple messages in one command even in Individual mode.

Java client supports this feature by adding `acknowledgeGroupTime` setting in [`ConsumerBuilder`](http://pulsar.apache.org/api/client/org/apache/pulsar/client/api/ConsumerBuilder.html#acknowledgmentGroupTime-long-java.util.concurrent.TimeUnit-), but C++ client does not.

So the questions are:

1. In Individual ACK mode, does *sending multiple message IDs in one `CommandAck`* really help achieving higher throughput?
2. If we implement this feature in C++ client (and later contribute back to community), shall it be implemented as an ACK interface, or as a setting like in Java. (Seems the previous one is easier.)
3. If it's implemented as an ACK interface, what should it be called? `acknowledgeGroup` or `groupAcknowledge`? We prefer the term `group`, because the C++ client has a data structure called `BatchAcknowledgeTracker`, which may confuse the code reader when we have two similar names for different purpose.

### BTW

**Does `acknowledge` interface in C++ client really send ACK synchronously?**

It actually calls the [`acknowledgeAsync`](https://github.com/apache/pulsar/blob/5504dc6e280237ab1abc70fc2889be6149ae518a/pulsar-client-cpp/lib/Consumer.cc#L87) and waits for triggering of the callback. But the [`doAcknowledge`](https://github.com/apache/pulsar/blob/5504dc6e280237ab1abc70fc2889be6149ae518a/pulsar-client-cpp/lib/ConsumerImpl.cc#L790) calls returns immediately anyway with `ResultOk`, because sending command is actually an asynchronous operation? Is this a known feature/issue? Or I just misunderstand the implementation? Is there any opened issues related to this?

**Comment by jiazhai** [comment]
Thanks @tongsucn for rising up this issue. Cpp client need to catchup with the feature of group-ack. Would you like to contribute to this feature? 

> Does acknowledge interface in C++ client really send ACK synchronously?

Regarding this issue, right, currently java and cpp clients have the same behavior,  acks are in a try-best way.  this will be handled after transaction feature added in.

**Comment by tongsucn** [comment]
@jiazhai Thanks for the reply, I would like to contribute to this feature. I'm a newbee of contributing code to Apache's project, so it may take some time for me to figure out the rules (such as CLA), but it won't be too long.

### About implementation

Similar to the Java client, I would create a new item in `ConsumerConfiguration` called `groupAckTimeMs`, which defines the max. duration (in milli-seconds) of grouping ACK requests. Related trackers will be added as well.

If you have any suggestion, just tell me!

**Comment by jiazhai** [comment]
@tongsucn Great!  Here is the [guide](https://pulsar.apache.org/en/contributing). CLA is not a must at present, only when become a committer, CLA is needed.

the implementation looks great, we should follow the Java client's behavior to implement it.

**Comment by sijie** [comment]
> so it may take some time for me to figure out the rules (such as CLA), but it won't be too long.

You don't need CLA to start contribution. CLA is typically required when you become a committer.

**Comment by tongsucn** [comment]
@sijie @jiazhai Thx, I got it. I'll ignore it for now.

**Comment by tongsucn** [comment]
FYI. The feature is almost done, For now, it improves the throughput bottleneck in shared subscription in our scenario, I'll firstly try it in production envrionment to verify more. After that, I'll add related necessary building and testing code and submit a new pull request.

**Comment by sijie** [comment]
Awesome! @tongsucn

**Comment by tongsucn** [comment]
PR is created. However, the Backwards Compatibility CI checking failed because of docker storage. Retry later.
