### ISSUE TITLE
Push Subscriptions through REST

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [apache/pulsar#6001]
**Is your feature request related to a problem? Please describe.**
Even for the simplest cases, if we want to consume messages from pulsar, we need to write specific pulsar code to do it. And then, we have to deploy this code somewhere. If we have hundreds o consumers, it becomes pretty hard to manage.

**Describe the solution you'd like**
Implement "Push". Pulsar will make an HTTP request to a specified endpoint that will POST a message (or many messages). Acknowledgement can be done by HTTP response status. 2XX status, ack the message, 5XX status, retry.

**Describe alternatives you've considered**
Google Cloud PubSub can do this.

**Additional context**
https://cloud.google.com/pubsub/docs/subscriber#push-subscription

**Comment by jiazhai** [comment]
Thanks @DanielFerreiraJorge for rising up this issue. it is a useful feature.

**Comment by DanielFerreiraJorge** [comment]
Hi @jiazhai thanks for the response,

Actually, I think you misunderstood the functionality I'm suggesting. It is not an endpoint to consume and produce messages, like Kafka REST Proxy, for instance...

With feature I'm suggesting, we would, create a shared subscription and configure an http endpoint to this subscription. Then, the pulsar cluster itself will push every message of this subscription to the http endpoint configured. You see? The pulsar cluster will make the POST to the endpoint!

Thanks

**Comment by jiazhai** [comment]
Thanks @DanielFerreiraJorge for the explanation. So, how about a HTTP connect, through [pulsar-io](http://pulsar.apache.org/docs/en/io-overview/)

**Comment by sijie** [comment]
@DanielFerreiraJorge Are you talking about a webhook in the subscription?

**Comment by DanielFerreiraJorge** [comment]
Sorry for the very late response. I had some personal problems that kept me away.

@jiazhai I believe an HTTP Sink would cover the functionality I'm talking about!
@sijie I wouldn't know about the best way to actually implement but the Pulsar IO HTTP Sink suggestion from @jiazhai perfectly describes the functionality!

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.

> HTTP Sink

This should be implemented by @cbornet recently. I'm unsure what the first version is to deliver this feature, though.

**Comment by tisonkun** [comment]
See also https://github.com/apache/pulsar/pull/17581. Perhaps 2.11.
