### ISSUE TITLE
2.4.2 pulsar dashboard cannot view a message

### ISSUE THREAD

**Issue by youurayy** [apache/pulsar#6002]
- 2.4.2, trying to view a topic message in dashboard fails silently (w/ error 500)
- the dashboard image is actually 2.4.1 as there was another error with 2.4.2 dashboard which completely prevented it from running (https://github.com/apache/pulsar/issues/5847)
- nothing in the dashboard log
- broker log shows:

`16:56:55.159 [pulsar-web-30-6] INFO  org.eclipse.jetty.server.RequestLog - 192.168.21.190 - - [06/Jan/2020:16:56:55 +0000] "GET //admin/v2/persistent/cb/development/topicname/subscription/arch/position/1 HTTP/1.1" 404 408 "-" "python-requests/2.21.0" 10`

**Comment by jiazhai** [comment]
@youurayy Will this appear each time? Would you please help provide a detailed steps to reproduce?

**Comment by youurayy** [comment]
@jiazhai yes happens each time. Steps:
1. install pulsar 2.4.2 from the Helm Chart (I use Helm 3)
    - note: To get 2.4.2 working on Kubernetes, do the following workarounds:
      - turn off functions #5818
      - change the image spec for the Dashboard to 2.4.1 due to #5847 
      - check if admin api works on all proxy pods, and restart those which are stuck #5994
2. create a tenant and a namespace
    - note: I create my namespace with:
       - `bin/pulsar-admin namespaces set-backlog-quota mytenant/mynamespace --limit 300M --policy consumer_backlog_eviction`
       - `bin/pulsar-admin namespaces set-deduplication mytenant/mynamespace --enable`
3. publish some messages into a persistent topic in that namespace
    - note: I use Protobuf serliaization; I don't use message compression at this time
4. go to the Dashboard, navigate to the topic, and try to view some messages currently residing on that topic
   - on the Dashboard webpage, nothing visible will happen
   - you have to open e.g. the Chrome web dev tools and look at Console or Network to see the 500 error returned

**Comment by sijie** [comment]
@youurayy I don't think the current pulsar dashboard supports protobuf serialized messages.

**Comment by youurayy** [comment]
@sijie it probably shouldn't quietly fail with an Error 500 though.

Also, it would be very beneficial to just display the message ID and other metatadata, the message content isn't that important.

Currently, there's just no metadata displayed even in the overview list, just queue sequential numbers which are quite useless.

**Comment by sijie** [comment]
@youurayy agreed. we need to add the support for it.

Although the dashboard is in the process of being deprecated and you are encouraged to use pulsar-manager, I would suggest using pulsar-manager and creating an issue there to request this feature.

http://pulsar.apache.org/docs/en/administration-pulsar-manager/
https://github.com/apache/pulsar-manager

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to maintain versions.
