### ISSUE TITLE
Possibility to add builtin Pulsar Functions with a shared jar copied inside the function folder

### ISSUE THREAD

**Issue by nicolo-paganin** [apache/pulsar#6003]
**Is your feature request related to a problem? Please describe.**
In order to create a pulsar function you have to build a `fat jar` (or `nar`) and the submit the `jar` when you create the function. The jar is copied by default inside `pulsar/tmp/function_name`. Currently it is not possible to load a shared jar containing one or more functions to be used without loading the jar (something similar to what is happening loading the a `nar` containing pulsar IO Sources/Sinks inside che `connectors` folder).

This could have the following benefits:

- Function can be distributed with the installation and users can create functions from builtin `jars` / `nars` without having the `jar` / `nar` file
- In case of multiple functions (with different functions names) using the same jar, the latter is not duplicated every time a new function is created 

**Describe the solution you'd like**
The possibility to create a new function loading the relative jar (if the function is not one of the builtin ones) or instantiate a new function using the builtin ones the are copied inside the `function` folder (like the connectors)

**Comment by nicolo-paganin** [comment]
I found that this feature is part of [PIP 50](https://github.com/apache/pulsar/wiki/PIP-50%3A-Package-Management)

**Comment by jiazhai** [comment]
thanks @nicolo-paganin ,right, this is part of the work in pip-50, which tries to manage the nars in a better way.

**Comment by sijie** [comment]
@itaross I have included this task into the Pulsar release 2.6.0. If you have any features that would like to see in 2.6.0, please comment in #5819. We will prioritize those features.

**Comment by nicolo-paganin** [comment]
@sijie I created a PR for this, could you please look at it? 
Thanks

**Comment by sijie** [comment]
@nicolo-paganin that's cool. will review it.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
