### ISSUE TITLE
[Github Actions]Remove dependence on personal project

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar#6012]
**Is your feature request related to a problem? Please describe.**
The current Github action test run depends on a personal maven project https://github.com/aahmed-se/setup-maven. We need to remove it https://github.com/apache/pulsar/blob/master/.github/workflows/ci-unit.yaml#L45.

**Comment by jiazhai** [comment]
@aahmed-se will you fix this issue? or @tuteng could work on it.

**Comment by aahmed-se** [comment]
I don't have time right now

**Comment by tisonkun** [comment]
Closed as stale. You can report a flaky test with the corresponding issue form if it's still relevant.
