### ISSUE TITLE
reader's subscription not auto delete after reader disconnected on non persistent topic

### ISSUE THREAD

**Issue by sydnash** [apache/pulsar#6021]
**Describe the bug**
On persistent topic, a reader's subscription will auto delete after reader disconnected, but on non-persistent topic, the reader's subscription is not auto deleted.
**To Reproduce**
1. connect a reader on a non-persistent topic
2. then disconnet the reader
3. use bin/pulsar-admin topics stats topicname, the reader's subscription is not been deleted.

**Expected behavior**
on persistent 
**Screenshots**
root@broker1:/pulsar# bin/pulsar-admin topics stats non-persistent://public/default/test_t3
{
  "msgRateIn" : 0.0,
  "msgThroughputIn" : 0.0,
  "msgRateOut" : 0.0,
  "msgThroughputOut" : 0.0,
  "averageMsgSize" : 0.0,
  "storageSize" : 0,
  "publishers" : [ ],
  "subscriptions" : {
    "reader-e8f7d8" : {
      "msgRateOut" : 0.0,
      "msgThroughputOut" : 0.0,
      "msgRateRedeliver" : 0.0,
      "msgBacklog" : 0,
      "blockedSubscriptionOnUnackedMsgs" : false,
      "msgDelayed" : 0,
      "unackedMessages" : 0,
      "type" : "Exclusive",
      "msgRateExpired" : 0.0,
      "consumers" : [ ],
      "isReplicated" : false
    },
    "reader-fb504f" : {
      "msgRateOut" : 0.0,
      "msgThroughputOut" : 0.0,
      "msgRateRedeliver" : 0.0,
      "msgBacklog" : 0,
      "blockedSubscriptionOnUnackedMsgs" : false,
      "msgDelayed" : 0,
      "unackedMessages" : 0,
      "type" : "Exclusive",
      "msgRateExpired" : 0.0,
      "consumers" : [ ],
      "isReplicated" : false
    },
    "reader-16a9a5" : {
      "msgRateOut" : 0.0,
      "msgThroughputOut" : 0.0,
      "msgRateRedeliver" : 0.0,
      "msgBacklog" : 0,
      "blockedSubscriptionOnUnackedMsgs" : false,
      "msgDelayed" : 0,
      "unackedMessages" : 0,
      "type" : "Exclusive",
      "msgRateExpired" : 0.0,
      "consumers" : [ ],
      "isReplicated" : false
    },
    "reader-61c774" : {
      "msgRateOut" : 0.0,
      "msgThroughputOut" : 0.0,
      "msgRateRedeliver" : 0.0,
      "msgBacklog" : 0,
      "blockedSubscriptionOnUnackedMsgs" : false,
      "msgDelayed" : 0,
      "unackedMessages" : 0,
      "type" : "Exclusive",
      "msgRateExpired" : 0.0,
      "consumers" : [ ],
      "isReplicated" : false
    }
  },
  "replication" : { }
}

**Desktop (please complete the following information):**
linux
pulsar 2.4.0

**Comment by jiazhai** [comment]
@sydnash This issue should be fixed in master issue. Would you please help have a try on latest master?

**Comment by sijie** [comment]
This is fixed by #5719 and will be released in 2.5.0.
