### ISSUE TITLE
PulsarSpout emits only to default stream

### ISSUE THREAD

**Issue by dawillcox** [apache/pulsar#6024]
**Is your feature request related to a problem? Please describe.**
We have an application, currently using another streaming ingestion method, that we'd like to replace with either Kafka or Pulsar. Either would be a candidate, _except_ the spout needs to emit to different output streams (to be processed by different bolts) based on the content of individual messages.

The Kafka spout supports this. Topologies implement `RecordTranslator`, an interface that returns the output stream and the `Values` for the tuple.

The equivalent in `PulsarSpout` is `MessageToValuesMapper`, but that returns only the `Values`. There's no way to specify an alternate stream; everything goes to "default."

**Describe the solution you'd like**
Simply put, a way for `MessageToValuesMapper` to specify the output stream for a tuple. (It already has a `declareOutputFields()` method so can declare the appropriate output streams.)

Three possible solutions, all workable. The first avoids any API change but requires an extra check
in `PulsarSpout` on emit. The other two would require backwards-compatible changes to `MessageToValueMapper`. I prefer the first.

1. Define `PulsarTuple` as an extension of `Values` so `MessageToValuesMapper` can return it without changing the API. `PulsarSpout` checks for `PulsarTuple` and emits on the specified stream if found. (_This is the alternative in the pull request._)
1. Change `PulsarSpout` to use a new method in `MessageToValuesMapper` that returns a `PulsarTuple` interface similar to Kafka's `KafkaTuple`. It would return the `Values` _and_ output stream. A default implementation of the new method would just call the existing method (which probably should be deprecated) and return a `PulsarTuple` with stream "default."
1. Add a new method to `MessageToValuesMapper`: `String outputStream(Message msg, Values values)` to return the output stream given the original `Message` and extracted `Values`. The default implementation would just return "default."

**Describe alternatives you've considered**
All of these would require `collector` to be not `private`, and probably other things. None are very satisfying. All would require an application to extend `PulsarSpout`, which can cause compatibility issues with new versions.
1. Change the existing `collector.emit()` calls with a call to a non-private `doEmit(Message msg, Values values)` call. Applications could override that and figure out the output stream as needed. 
1. Make `mapToValueAndEmit()` at least protected so it can be overridden.
1. Override nextTuple() and replicate most of the logic except the `emit()` calls.

Or, just use Kafka, which is what we'd actually do.

**Additional context**
One application receives Avro-encoded events with a header that identifies the schema type and version. (Also some other information not relevant here.) The schema type determines the output stream.

Another application has a fixed Avro schema with two fields, an event type and a serialized protobuf. The event type determines the output stream.

Changing those formats isn't an option.

**Comment by jiazhai** [comment]
Thanks @dawillcox for the help on this issue and PR

**Comment by dawillcox** [comment]
Any guidance on what I I need to do with this going forward would be appreciated. For example, should a do a separate PR to master?

**Comment by dawillcox** [comment]
I'll note that branch-1.20 has quite a bit more extensive unit tests for pulsar_storm. They really ought to be brought forward.

**Comment by merlimat** [comment]
@dawillcox The Storm tests were moved to the integration tests, because of issues with shading dependencies. https://github.com/apache/pulsar/tree/master/tests/pulsar-storm-test
