### ISSUE TITLE
Support bulk write in Elasticsearch Sink

### ISSUE THREAD

**Issue by fantapsody** [apache/pulsar#6030]
**Is your feature request related to a problem? Please describe.**

The [current implementation](https://github.com/apache/pulsar/blob/master/pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java#L84) of Elasticsearch Sink connector write documents to the cluster individually in sync mode, while write documents to Elasticsearch clusters in bulk could [improve the performance significantly](https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-index.html#getting-started-batch-processing) as it minimizes network roundtrips.

**Describe the solution you'd like**

Accumulate a limited number of records for a while and write them in bulk to the cluster asynchronously.

**Describe alternatives you've considered**

As many sink connectors share the idea of writing in bulk to improve performance, maybe it is worth of consideration for a general abstraction of "batch mode" to simplify the development of sink connectors.

**Comment by yuvalgut** [comment]
If we could use the windows semantics for sinks thta would make life easier for batching.

**Comment by chenyg0911** [comment]
When the feature pupported? kafka sink suport bulk index for a long time.

**Comment by eolivelli** [comment]
Yes it is om the current master branch.
It will be available from 2.9.0 onwards
