### ISSUE TITLE
[doc] Add documentation about running Pulsar Functions using LocalRunner

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#6044]
*Motivation*

Besides running or submitting functions using CLI, Pulsar also supports running Pulsar Functions in a programmable way via `LocalRunner` class. It is better to document how to run Pulsar Functions in a programmable way.

See: https://github.com/apache/pulsar/blob/320cebe09f80116a2df81a5df1bcfd518ecf8c08/pulsar-functions/localrun/src/main/java/org/apache/pulsar/functions/LocalRunner.java

**Comment by Anonymitaet** [comment]
Confirmed w/ @wolfstudy, creating a function can not be achieved via the `LocalRunner` class.
Doc is available at [here](https://streamnative.io/docs/latest/process/pulsar-functions/deploy/manage).
Will copy to Pulsar later.
