### ISSUE TITLE
[Broker] Expose lastConsumedTimestamp and lastAckedTimestamp to subscription stats

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#6046]
*Motivation*

Currently, `msgBacklog` measures the number of messages that a subscription has not consumed and it is an *estimated* value. It is hard to tell the difference between a backlog estimate being wrong and messages being otherwise stuck. It would be great to expose `lastConsumedTimestamp` and `lastAckedTimestamp` to measure the activities of dispatch and acknowledge. So people can use these timestamps to tell if acknowledge and consumption are happening.

These two metrics provide a `lag` metric similar to Kafka.

Related Tasks: #5721

**Comment by tuteng** [comment]
This has been solved #6051
