### ISSUE TITLE
[docs] Provide a generator to generate configuration files automatically

### ISSUE THREAD

**Issue by Jennifer88huang** [apache/pulsar#6048]
**Describe the bug**
When parameters in the `broker.conf`, `standalone.conf`  and other configuration files are updated in the code, the docs are not updated synchronously on the [Pulsar configuration page](http://pulsar.apache.org/docs/en/next/reference-configuration/) . And then we have to check those PRs one by one and add those parameters in the md file. Take https://github.com/apache/pulsar/pull/6047 as an example.

**Expected behavior**
The doc content on the [Pulsar configuration page](http://pulsar.apache.org/docs/en/next/reference-configuration/) is updated synchronously with code update.

**Additional context**
We need a generator to generate the configuration files automatically.

**Comment by Jennifer88huang** [comment]
@tuteng Could you share how to implement the auto generator tool? Thank you.

**Comment by Anonymitaet** [comment]
Duplicated with https://github.com/apache/pulsar/issues/10041. I'll close this issue since we've tracked the status in https://github.com/apache/pulsar/issues/10041.
