### ISSUE TITLE
Ftr: The pulsar function specifies the outtopic internally, not when the function is started

### ISSUE THREAD

**Issue by pantianying** [apache/pulsar#6055]
**Is your feature request related to a problem? Please describe.**

I hope to do some message routing works with complex logic in function. I want to distribute messages of the same inTopic to different outTopics. Obviously, the current mode does not support this operation. I believe that many developers will have the same needs as me.

**Describe the solution you'd like**
1.can specify the outtopic of the output within the function code。

**Comment by sijie** [comment]
@pantianying you can use [context.publish](http://pulsar.apache.org/docs/en/functions-develop/#context) to publish the results of a function to different topics.

Example: http://pulsar.apache.org/docs/en/functions-overview/#content-based-routing-example

**Comment by tisonkun** [comment]
Closed as answered.
