### ISSUE TITLE
[docs] Add info on how to choose partition when using a key

### ISSUE THREAD

**Issue by Jennifer88huang** [apache/pulsar#6056]
**Describe the bug**
On [Partitioned topics](https://pulsar.apache.org/docs/en/next/cookbooks-partitioned/) page, it does not say what happens when you use a key. Does that override things? Does it change how a partition is chosen? Looking at the API docs, all of them talk about the absence of keys but don't say what happens with keys.

I see the link now to the routing modes. It doesn't really make sense that you can set round robin and have that overridden by simply adding a key.

With keys, how are partitions chosen? With Kafka it is:
selectedPartition = murmur2(keybytes) % numPartitions

Comments from Jesse Anderson

**Comment by Jennifer88huang** [comment]
@zymap Could you please share a code snippet for this? Thank you.

**Comment by zymap** [comment]
```
// If the message has a key, it supersedes the round robin routing policy
        if (msg.hasKey()) {
            return signSafeMod(hash.makeHash(msg.getKey()), topicMetadata.numPartitions());
        }

        if (isBatchingEnabled) { // if batching is enabled, choose partition on `partitionSwitchMs` boundary.
            long currentMs = clock.millis();
            return signSafeMod(currentMs / partitionSwitchMs + startPtnIdx, topicMetadata.numPartitions());
        } else {
            return signSafeMod(PARTITION_INDEX_UPDATER.getAndIncrement(this), topicMetadata.numPartitions());
        }
```
