### ISSUE TITLE
Subscription metrics name error

### ISSUE THREAD

**Issue by yangwenjie88** [apache/pulsar#6069]
The metric name of the document is pulse_subscription_unacked_messages but Prometheus print is pulsar_subscription_unacked_massages , word messages spelling mistakes

**Comment by wolfstudy** [comment]
> The metric name of the document is pulse_subscription_unacked_messages but Prometheus print is pulsar_subscription_unacked_massages , word messages spelling mistakes

Thanks @yangwenjie88 can you help fix the typo issue?

**Comment by tisonkun** [comment]
Close as fixed.
