### ISSUE TITLE
[website] Download page is messed up

### ISSUE THREAD

**Issue by Jennifer88huang** [apache/pulsar#6071]
**Describe the bug**
It seems like some messed up apache_pulsar prebuilt packages.

Every mirror is only listing 2.5.0 even though 2.4.2 is the last stable version. This especially bad if CI/CD is depending on these mirrors.

https://pulsar.apache.org/docs/en/client-libraries-cpp/ list prebuilt .deb files at 2.4.2.

2.5 is being staged for release and per ASF policy only latest version is kept on mirrors. All the versions are kept at http://archive.apache.org

**Expected behavior**
 The website document should be updated with the archive links as download page (http://pulsar.apache.org/en/download/) for the old releases.

**Comment by sijie** [comment]
The new website has been built. The issue is fixed.
