### ISSUE TITLE
[v2.5.0] Functions dead-letter-topic parameter not supported

### ISSUE THREAD

**Issue by frejonb** [apache/pulsar#6084]
**Describe the bug**
In the Functions reference https://pulsar.apache.org/docs/en/functions-cli/ it shows a parameter `dead-letter-topic`. When using it, it is passed to `/pulsar/instances/python-instance/python_instance_main.py` under the `--function_details` json as
```
"customRuntimeOptions": "persistent://tenant/namespace/dlq-topic"
```
But `customRuntimeOptions` is not recognized:
```
google.protobuf.json_format.ParseError: Message type "proto.FunctionDetails" has no field named "customRuntimeOptions".
 Available Fields(except extensions): ['tenant', 'namespace', 'name', 'className', 'logTopic', 'processingGuarantees', 'userConfig', 'secretsMap', 'runtime', 'autoAck', 'parallelism', 'source', 'sink', 'resources', 'packageUrl', 'retryDetails', 'runtimeFlags', 'componentType']
```

**To Reproduce**
1. Create pulsar function with `--dead-letter-topic` argument

**Expected behavior**
Function should be configured correctly

**Desktop (please complete the following information):**
 - OS: Docker

**Additional context**
pulsar tag v2.5.0

**Comment by sijie** [comment]
@frejonb I don't think python function supports this feature yet. 

@Anonymitaet we need to improve the documentation about this part.

**Comment by sijie** [comment]
The dead letter topic support in java functions also has one problem. #6101 is used for addressing the problem in java functions.

Python functions doesn't support this feature at all.

**Comment by codelipenghui** [comment]
@sijie Looks we can move this issue to 2.7.0 and we can add a help-wanted tag. If anyone contributes this feature before 2.6.0 release, we can move it back.

**Comment by Huanli-Meng** [comment]
The doc is updated and merged, here is the PR link: https://github.com/apache/pulsar/pull/6980
