### ISSUE TITLE
[docs] Document for delete inactive topic when subscriptions caught up

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#6087]
This issue tracks the document for delete inactive topic when subscriptions caught up(#6077)

**Comment by codelipenghui** [comment]
@Huanli-Meng Could you please also add https://github.com/streamnative/streamnative-docs/pull/169 to Pulsar repo?

**Comment by Huanli-Meng** [comment]
update the doc, here is the PR link: https://github.com/apache/pulsar/pull/6990

**Comment by sijie** [comment]
This has been fixed by #6990
