### ISSUE TITLE
libpulsar from homebrew is not updated to v2.5.0

### ISSUE THREAD

**Issue by mileschao** [apache/pulsar#6091]
**Describe the bug**
libpulsar from homebrew is not updated to v2.5.0

**To Reproduce**
```shell
$ brew upgrade libpulsar
==> Upgrading 1 outdated package:
libpulsar 2.4.1 -> 2.4.2_1
==> Upgrading libpulsar
```

**Comment by sijie** [comment]
@mileschao which howbrew formulae are you using? I don't think PMC is maintaining any official homebrew tab.

**Comment by mileschao** [comment]
> @mileschao which howbrew formulae are you using? I don't think PMC is maintaining any official homebrew tab.

thx for your reply. I'm using official now.
I think you can check this [brew libpulsar link](https://formulae.brew.sh/formula/libpulsar)

**Comment by sijie** [comment]
okay. didn't realize that we manage that before. that wasn't discussed by the PMC before.

**Comment by sijie** [comment]
will have to look into it how to update it.

**Comment by tisonkun** [comment]
Closed as stale.

The development of the C++ client has been permanently moved to https://github.com/apache/pulsar-client-cpp. If it's still relevant, please open an issue there.
