### ISSUE TITLE
Update ARM64 supported protobuf version in pom.xml

### ISSUE THREAD

**Issue by nareshgbhat** [apache/pulsar#6093]
I am trying to compile the Apache Pulser on ARM64 board with Debian distribution installed on it,  But the build is getting failed because of the old protobuf version used in the project pom.xml file.  Can we please update the protobuf version of the pom.xml file across all the project files ?

#### Expected behavior

The Apache Pulser project should get compiled on ARM64 Debian distribution.

#### Actual behavior

The Apache pulser uses two versions of protobuf, there is a failure of this package

Logs:
INFO] ------------------------------------------------------------------------
[*INFO*] Reactor Summary for Pulsar 2.4.1:
[*INFO*]
[*INFO*] Pulsar Build Tools ................................. SUCCESS [  2.393 s]
[*INFO*] Pulsar ............................................. SUCCESS [  0.988 s]
[*INFO*] Pulsar Client :: API ............................... SUCCESS [  4.168 s]
[*INFO*] Pulsar Common ...................................... SUCCESS [ 16.152 s]
[*INFO*] Managed Ledger ..................................... SUCCESS [ 11.340 s]
[*INFO*] Managed Ledger ..................................... SUCCESS [ 31.923 s]
[*INFO*] Apache Pulsar :: Jclouds shaded .................... SUCCESS [  6.910 s]
[*INFO*] Apache Pulsar :: Tiered Storage :: Parent .......... SUCCESS [  0.127 s]
[*INFO*] Apache Pulsar :: Tiered Storage :: JCloud .......... SUCCESS [  9.142 s]
[*INFO*] Pulsar ZooKeeper Utils ............................. SUCCESS [ 16.482 s]
[*INFO*] pulsar-broker-common ............................... SUCCESS [  5.369 s]
[*INFO*] Pulsar Functions :: Parent ......................... SUCCESS [  0.128 s]
[*INFO*] Pulsar Functions :: Proto .......................... FAILURE [  1.691 s]
[*INFO*] Pulsar Client Java ................................. SKIPPED
....
...............

The pom.xml file contains, this needs some fixes

<protobuf2.version>*2.4.1</protobuf2*.version>
<protobuf3.version>*3.5.1</protobuf3*.version>

#### Steps to reproduce

The issue can be reproduced as below
$ git clone https://github.com/apache/pulsar.git
$ mvn clean package -DskipTests

will lead to the compilation failure on ARM64 machine with Debian distribution.

#### System configuration
Architecture: ARM64
OS distribution : Debian 9.x
Apache Pulser: Pulsar 2.4.1

**Comment by sijie** [comment]
@nareshgbhat I don't have any ARM64 machine to verify this. Do you know what version of Protobuf supports ARM64?

**Comment by nareshgbhat** [comment]
@sijie The protobuf version 3.6 is officially supported.  We can help to get the ARM64 systems from Linaro side for CI (a developer cloud instance access) or else we can also help to test the same on ARM64 machines.

**Comment by sijie** [comment]
@nareshgbhat Okay. It should be easy to bump the protobuf 3.5.1 to 3.6.

You don't need to worry about protobuf 2.4.1. It is a customized protoc for generating Pulsar Api. The java API has already been generated. So you don't need protoc runtime for 2.4.1.

I can send out a pull request if you can help me verify if it works on the ARM64 systems that would be great.

**Comment by nareshgbhat** [comment]
@sijie sure go ahead and please issue a pull request.  I will verify the same on ARM64 machine and try to continue the compilation.

**Comment by nareshgbhat** [comment]
@sijie I am posting a kind of complete log where you can understand more to debug the issue,

pulsar$ git branch
* branch-2.5
  master
pulsar$ 
pulsar$ mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /use/share/apache-maven-3.6.3
Java version: 1.8.0_232, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk-arm64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.16.0-290-arm64", arch: "aarch64", family: "unix"
pulsar$
$ mvn clean package -DskipTests
....
..........
[INFO] --------------< org.apache.pulsar:pulsar-functions-proto >--------------
[INFO] Building Pulsar Functions :: Proto 2.5.0                        [15/119]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo1.maven.org/maven2/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.pom
Downloaded from central: https://repo1.maven.org/maven2/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.pom (13 kB at 537 kB/s)
Downloading from central: https://repo1.maven.org/maven2/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
Downloaded from central: https://repo1.maven.org/maven2/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar (26 kB at 1.1 MB/s)
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ pulsar-functions-proto ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven) @ pulsar-functions-proto ---
[INFO] 
[INFO] --- git-commit-id-plugin:3.0.0:revision (git-info) @ pulsar-functions-proto ---
[INFO] 
[INFO] --- protobuf-maven-plugin:0.6.1:compile (default) @ pulsar-functions-proto ---
[INFO] Compiling 3 proto file(s) to /home/linaro/LDCG-923/pulsar/pulsar-functions/proto/target/generated-sources/protobuf/java
[INFO] 
[INFO] --- protobuf-maven-plugin:0.6.1:compile-custom (default) @ pulsar-functions-proto ---
Downloading from central: https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.12.0/protoc-gen-grpc-java-1.12.0.pom
Downloaded from central: https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.12.0/protoc-gen-grpc-java-1.12.0.pom (2.2 kB at 92 kB/s)
Downloading from central: https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.12.0/protoc-gen-grpc-java-1.12.0-linux-aarch_64.exe
Downloading from bintray-yahoo-maven: https://yahoo.bintray.com/maven/io/grpc/protoc-gen-grpc-java/1.12.0/protoc-gen-grpc-java-1.12.0-linux-aarch_64.exe
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Pulsar 2.5.0:
[INFO] 
[INFO] Pulsar Build Tools ................................. SUCCESS [  8.137 s]
[INFO] Pulsar ............................................. SUCCESS [  6.639 s]
[INFO] Pulsar Transaction :: Parent ....................... SUCCESS [  0.336 s]
[INFO] Pulsar Transaction :: Common ....................... SUCCESS [  9.030 s]
[INFO] Pulsar Client :: API ............................... SUCCESS [  4.312 s]
[INFO] Pulsar Common ...................................... SUCCESS [ 20.866 s]
[INFO] Managed Ledger ..................................... SUCCESS [ 14.976 s]
[INFO] Apache Pulsar :: Jclouds shaded .................... SUCCESS [  7.361 s]
[INFO] Apache Pulsar :: Tiered Storage :: Parent .......... SUCCESS [  0.247 s]
[INFO] Apache Pulsar :: Tiered Storage :: JCloud .......... SUCCESS [  9.625 s]
[INFO] Apache Pulsar :: Tiered Storage :: File System ..... SUCCESS [ 20.123 s]
[INFO] Pulsar ZooKeeper Utils ............................. SUCCESS [ 16.331 s]
[INFO] pulsar-broker-common ............................... SUCCESS [  5.812 s]
[INFO] Pulsar Functions :: Parent ......................... SUCCESS [  0.219 s]
[INFO] Pulsar Functions :: Proto .......................... FAILURE [  1.713 s]
[INFO] Pulsar Client Java ................................. SKIPPED
[INFO] Pulsar Discovery Service WAR ....................... SKIPPED
[INFO] Pulsar WebSocket ................................... SKIPPED
[INFO] Pulsar Client Admin Original ....................... SKIPPED
[INFO] Pulsar Functions :: API ............................ SKIPPED
[INFO] Pulsar IO :: Parent ................................ SKIPPED
[INFO] Pulsar IO :: IO .................................... SKIPPED
[INFO] Pulsar Functions :: Utils .......................... SKIPPED
[INFO] Pulsar Functions :: Secrets ........................ SKIPPED
[INFO] Pulsar Functions :: Instance ....................... SKIPPED
[INFO] Pulsar Functions :: Runtime ........................ SKIPPED
[INFO] Pulsar IO :: Cassandra ............................. SKIPPED
[INFO] Pulsar IO :: IO Common ............................. SKIPPED
[INFO] Pulsar IO :: Twitter ............................... SKIPPED
 Runner original .......... SKIPPED
[INFO] Pulsar Functions :: API Examples ................... SKIPPED
[INFO] Pulsar IO :: Data Generator ........................ SKIPPED
[INFO] Pulsar Transaction :: Coordinator .................. SKIPPED
[INFO] Pulsar Broker ...................................... SKIPPED
[INFO] Pulsar Shaded Broker ............................... SKIPPED
[INFO] Pulsar Client Java ................................. SKIPPED
[INFO] Pulsar Client 1.x Compatibility Base ............... SKIPPED
[INFO] Pulsar Client 2.x Shaded API ....................... SKIPPED
[INFO] Pulsar Client 1.x Compatibility API ................ SKIPPED
[INFO] Pulsar Client Admin ................................ SKIPPED
[INFO] Pulsar Client Tools ................................ SKIPPED
[INFO] Pulsar Client Tools Test ........................... SKIPPED
[INFO] Pulsar Client All .................................. SKIPPED
[INFO] Pulsar Proxy ....................................... SKIPPED
[INFO] Pulsar Storm adapter ............................... SKIPPED
[INFO] Pulsar Flink Connectors ............................ SKIPPED
[INFO] Spark Streaming Pulsar Receivers ................... SKIPPED
[INFO] Pulsar Test Client ................................. SKIPPED
[INFO] pulsar-broker-auth-athenz .......................... SKIPPED
[INFO] pulsar-client-auth-athenz .......................... SKIPPED
[INFO] Pulsar Kafka compatibility ......................... SKIPPED
[INFO] Pulsar Kafka compatibility :: API (original) ....... SKIPPED
[INFO] Pulsar Kafka compatibility 0.8 :: API (original) ... SKIPPED
[INFO] Pulsar Kafka compatibility 0.9 :: API (original) ... SKIPPED
[INFO] Pulsar Kafka compatibility :: API .................. SKIPPED
[INFO] Pulsar Kafka compatibility 0.8 :: API .............. SKIPPED
[INFO] Pulsar Kafka compatibility 0.9 :: API .............. SKIPPED
[INFO] Pulsar Kafka compatibility :: Tests ................ SKIPPED
[INFO] Pulsar Kafka-0.8 compatibility :: Tests ............ SKIPPED
[INFO] Pulsar Kafka compatibility 0.9 :: Tests ............ SKIPPED
[INFO] pulsar-zookeeper ................................... SKIPPED
[INFO] Pulsar Log4j2 Appender ............................. SKIPPED
[INFO] Pulsar SQL :: Parent ............................... SKIPPED
[INFO] Pulsar SQL :: Pulsar Presto Connector Packaging .... SKIPPED
[INFO] Pulsar SQL :: Pulsar Presto Connector .............. SKIPPED
[INFO] Pulsar SQL :: Pulsar Presto Distribution ........... SKIPPED
[INFO] Apache Pulsar :: Docker Images ..................... SKIPPED
[INFO] Apache Pulsar :: Docker Images :: Pulsar Dashboard . SKIPPED
[INFO] pulsar-client-auth-sasl ............................ SKIPPED
[INFO] pulsar-broker-auth-sasl ............................ SKIPPED
[INFO] Pulsar Functions :: Runtime All .................... SKIPPED
[INFO] Pulsar Functions :: Local Runner Shaded ............ SKIPPED
[INFO] Pulsar IO :: Canal ................................. SKIPPED
[INFO] Pulsar IO :: ElasticSearch ......................... SKIPPED
[INFO] Pulsar IO :: Hdfs2 ................................. SKIPPED
[INFO] Pulsar IO :: Hdfs3 ................................. SKIPPED
[INFO] Pulsar IO :: Jdbc .................................. SKIPPED
[INFO] Pulsar IO :: Kafka ................................. SKIPPED
[INFO] Pulsar IO :: Kinesis ............................... SKIPPED
[INFO] Pulsar IO :: RabbitMQ .............................. SKIPPED
[INFO] Pulsar IO :: Docs .................................. SKIPPED
[INFO] Pulsar IO :: Aerospike ............................. SKIPPED
[INFO] Pulsar IO :: Kafka Connect Adaptor ................. SKIPPED
[INFO] Pulsar IO :: Debezium .............................. SKIPPED
[INFO] Pulsar IO :: Debezium :: Core ...................... SKIPPED
[INFO] Pulsar IO :: Debezium :: mysql ..................... SKIPPED
[INFO] Pulsar IO :: Debezium :: postgres .................. SKIPPED
[INFO] Pulsar IO :: Debezium :: mongodb ................... SKIPPED
[INFO] Pulsar IO :: File .................................. SKIPPED
[INFO] Pulsar IO :: Netty ................................. SKIPPED
[INFO] Pulsar IO :: Hbase ................................. SKIPPED
[INFO] Pulsar IO :: MongoDB ............................... SKIPPED
[INFO] Pulsar IO :: Flume ................................. SKIPPED
[INFO] Pulsar IO :: Redis ................................. SKIPPED
[INFO] Pulsar IO :: Solr .................................. SKIPPED
[INFO] Pulsar IO :: InfluxDB .............................. SKIPPED
[INFO] Pulsar Examples :: Parent .......................... SKIPPED
[INFO] Pulsar Examples :: Flink ........................... SKIPPED
[INFO] Pulsar Examples :: Spark ........................... SKIPPED
[INFO] Pulsar :: Distribution ............................. SKIPPED
[INFO] Pulsar :: Distribution :: Server ................... SKIPPED
[INFO] Pulsar :: Distribution :: IO ....................... SKIPPED
[INFO] Pulsar :: Distribution :: Offloader ................ SKIPPED
[INFO] Apache Pulsar :: Docker Images :: Pulsar Latest Version SKIPPED
[INFO] Apache Pulsar :: Docker Images :: Grafana .......... SKIPPED
[INFO] Apache Pulsar :: Docker Images :: Pulsar Latest Version (Include All Components) SKIPPED
[INFO] Apache Pulsar :: Docker Images :: Pulsar Standalone  SKIPPED
[INFO] Apache Pulsar :: Tests ............................. SKIPPED
[INFO] Apache Pulsar :: Tests :: Docker Images ............ SKIPPED
[INFO] Apache Pulsar :: Tests :: Docker Images :: Java Test Functions SKIPPED
[INFO] Apache Pulsar :: Tests :: Docker Images :: Latest Version Testing SKIPPED
[INFO] Apache Pulsar :: Tests :: Integration .............. SKIPPED
[INFO] Apache Pulsar :: Tests :: Pulsar Kafka Compat Client Tests SKIPPED
[INFO] Pulsar Storm adapter Tests ......................... SKIPPED
[INFO] Spark Streaming Pulsar Receivers Tests ............. SKIPPED
[INFO] Apache Pulsar :: Tests :: Backwards Client Compatibility 2.0.0-rc1-incubating SKIPPED
[INFO] Apache Pulsar :: Tests :: Backwards Client Compatibility 2.0.1-incubating SKIPPED
[INFO] Pulsar Metadata .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:19 min
[INFO] Finished at: 2020-01-22T15:18:26Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.6.1:compile-custom (default) on project pulsar-functions-proto: Unable to resolve artifact: Missing:
[ERROR] ----------
ERROR] 1) io.grpc:protoc-gen-grpc-java:exe:linux-aarch_64:1.12.0
[ERROR] 
[ERROR]   Try downloading the file manually from the project website.
[ERROR] 
[ERROR]   Then, install it using the command: 
[ERROR]       mvn install:install-file -DgroupId=io.grpc -DartifactId=protoc-gen-grpc-java -Dversion=1.12.0 -Dclassifier=linux-aarch_64 -Dpackaging=exe -Dfile=/path/to/file
[ERROR] 
[ERROR]   Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]       mvn deploy:deploy-file -DgroupId=io.grpc -DartifactId=protoc-gen-grpc-java -Dversion=1.12.0 -Dclassifier=linux-aarch_64 -Dpackaging=exe -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR]   Path to dependency: 
[ERROR]   	1) org.apache.pulsar:pulsar-functions-proto:jar:2.5.0
[ERROR]   	2) io.grpc:protoc-gen-grpc-java:exe:linux-aarch_64:1.12.0
[ERROR] 
[ERROR] ----------
[ERROR] 1 required artifact is missing.
[ERROR] 
[ERROR] for artifact: 
[ERROR]   org.apache.pulsar:pulsar-functions-proto:jar:2.5.0
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   central (https://repo1.maven.org/maven2, releases=true, snapshots=true),
[ERROR]   bintray-yahoo-maven (https://yahoo.bintray.com/maven, releases=true, snapshots=false),
[ERROR]   apache.snapshots (https://repository.apache.org/snapshots, releases=false, snapshots=true)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :pulsar-functions-proto
$

**Comment by sijie** [comment]
@nareshgbhat thank you! will take a look.

**Comment by nareshgbhat** [comment]
@sijie Any update ? not sure you guys are on vacation ?

**Comment by ganeshrajuLinaro** [comment]
@sijie We could donate an ARM64 hardware for the project to test and help to setup CI running arm. Shall i create a JIRA for that?

**Comment by merlimat** [comment]
@ganeshrajuLinaro It's not needed to compile the Java stuff on ARM. You can take the regular Pulsar binary distribution from the download page (or build it from sources on a x86 box).

**Comment by sijie** [comment]
@merlimat I think the problem here is the protoc used by maven plugin for compiling proto3 code.

**Comment by Tom-python0121** [comment]
@sijie Is this problem solved?

**Comment by martin-g** [comment]
It seems the problem is solved because protoc is upgraded to 3.11.4 and it has ARM64 binary
https://github.com/apache/pulsar/blob/e67802420d23a9405c6efe4e35c497d19e471109/pom.xml#L132-L133

**Comment by tisonkun** [comment]
Closed as resolved.
