### ISSUE TITLE
[doc] 404 error Pulsar IO

### ISSUE THREAD

**Issue by huangdx0726** [apache/pulsar#6100]
**Describe the bug**
404 error Pulsar IO.

**To Reproduce**
1. Go to 'http://pulsar.apache.org/docs/en/2.4.2/io-quickstart'
2. Click on 'Get started'
3. Scroll down to ' Install Pulsar and builtin connector'
4.Click `here` like.

**Expected behavior**

**Screenshots**
![图片](https://user-images.githubusercontent.com/29513837/72712701-85958500-3ba6-11ea-989c-2f3fae85d423.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by sijie** [comment]
I think this is related to #6110

**Comment by Anonymitaet** [comment]
This issue has been fixed.
