### ISSUE TITLE
[doc] 404 error in pulsar io-use

### ISSUE THREAD

**Issue by huangdx0726** [apache/pulsar#6108]
**Describe the bug**
404 error in pulsar io-use.

**To Reproduce**
1. Go to 'http://pulsar.apache.org/docs/en/io-use'
2. Click on 'Use'
3. Scroll down to 'reload'
4.Click `here` link

**Expected behavior**
Right page is displayed.

**Screenshots**
![图片](https://user-images.githubusercontent.com/29513837/72782364-84c02a00-3c5e-11ea-991e-45b5b8543839.png)
.

**Desktop (please complete the following information):**

**Additional context**

**Comment by sijie** [comment]
This is related to #6110

**Comment by sijie** [comment]
This was fixed by #6125
