### ISSUE TITLE
[doc][suggest]  Tell user the available values of "--sink-type" parameter

### ISSUE THREAD

**Issue by huangdx0726** [apache/pulsar#6109]
**Is your feature request related to a problem? Please describe.**
Tell user the available values of "--sink-type" parameter.

**Describe the solution you'd like**
When i create a Cassandra sink like this.
```bash
bin/pulsar-admin sinks create \
    --tenant public \
    --namespace default \
    --name cassandra-test-sink \
    --sink-type cassandra \
    --sink-config-file examples/cassandra-sink.yml \
    --inputs test_cassandra

```
I could't understand,  Why is the value of  "--sink-type" parameter cassandra ,And when i create the other sinks,  What value should be set for this parameter.

**Describe alternatives you've considered**
Provide a available values list  for this parameter.

**Additional context**

**Comment by huangdx0726** [comment]
--source-type as above

**Comment by tuteng** [comment]
The type `sink-type` or `source-type` of the currently built-in connector should be determined according to the parameter `name` of this file.`pulsar-io.yaml` https://github.com/apache/pulsar/blob/master/pulsar-io/debezium/mongodb/src/main/resources/META-INF/services/pulsar-io.yaml. @huangdx0726 

I think we can consider adding instructions about pulsar-io.yaml to the document. @Anonymitaet

**Comment by huangdx0726** [comment]
```java
@Connector(
    name = "cassandra",
    type = IOType.SINK,
    help = "The CassandraStringSink is used for moving messages from Pulsar to Cassandra.",
    configClass = CassandraSinkConfig.class)
```
This name is same as  `name`  of  `pulsar-io.yaml` ?

**Comment by tuteng** [comment]
Yes, it is the same, but some connectors do not have the annotation `Connector`, but there must be the pulsar-io.yaml file. @huangdx0726
