### ISSUE TITLE
[Doc 2.5.0] The content of Connector Admin CLI is blank 

### ISSUE THREAD

**Issue by huangdx0726** [apache/pulsar#6110]
**Describe the bug**
The content of Connector Admin CLI is blank .

**To Reproduce**
1. Go to 'http://pulsar.apache.org/docs/en/reference-connector-admin/'
2. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by sijie** [comment]
I think this is related to #5700. @tuteng can you check why the content was removed?

**Comment by Huanli-Meng** [comment]
it seems this bug is fixed. in 2.5.0 and later releases, "connector Admin CLI" is moved from reference section to Pulsar IO connection. and the doc name is changed from "connector admin CLI" in reference section to "CLI" in "Pulsar IO" section.

**Comment by Huanli-Meng** [comment]
update docs for : [doc] 404 error in pulsar io-use #6108

here the doc PR: https://github.com/apache/pulsar/pull/6976

**Comment by Anonymitaet** [comment]
@huangdx0726 this file "reference-connector-admin.md" is removed from doc.
If you want to read Connector Admin CLI doc, see http://pulsar.apache.org/docs/en/next/io-cli/.
