### ISSUE TITLE
Download page link text does not agree with file name

### ISSUE THREAD

**Issue by sebbASF** [apache/pulsar#6115]
The displayed text in the links for the Older Releases on the page https://pulsar.apache.org/download/ does not agree with the file to which the link points. e.g.

apache-pulsar-2.4.2-bin-tar.gz
points to a file with the name
apache-pulsar-2.4.2-bin.tar.gz

The links work, but this is confusing.

**Comment by sebbASF** [comment]
The links on the website still show the wrong text

**Comment by sijie** [comment]
@sebbASF the website CI hasn't run yet. I kicked one now. let's see the result.

**Comment by sebbASF** [comment]
AFAICT the web page has not yet been updated.
All the 'Older releases' artifact display names end in '-tar.gz' instead of '.tar.gz'

**Comment by sijie** [comment]
@sebbASF the website failed to build due to some other changes. a fix is in progress : #6142

**Comment by sebbASF** [comment]
Looks like the page has now been updated.

**Comment by sijie** [comment]
yes. we merged #6142 yesterday and the website was built successfully.
