### ISSUE TITLE
FlinkPulsarProducer: Setting topic dynamically based on message content

### ISSUE THREAD

**Issue by parth-sarathy** [apache/pulsar#6117]
While using FlinkPulsarProducer we need to set topic dynamically based on the message content.

In FlinkKafkaProducer, the sink topic can be set dynamically by overriding getTargetTopic method in KeyedSerializationSchema. FlinkPulsarProducer uses SerializationSchema, PulsarKeyExtractor is used to extract key from the message. How can we change the sink topic based on message content in case of FlinkPulsarProducer?

**Comment by sijie** [comment]
@parth-sarathy I don't think this feature is supported. @yjshen can help look into this issue.

**Comment by parth-sarathy** [comment]
Since we are upgrading our application to use Pulsar instead of Kafka as message bus, I had raised this issue as Enhancement Request (to prevent functionality loss after the upgrade).

**Comment by yjshen** [comment]
As sijie said, it's not supported to write to multiple topics in FlinkPulsarProducer.

Currently, there's only one producer who started with the default topic name.
A possible way to enable this is to maintain a HashMap from topic to producer in FlinkPulsarProducer, and get a `getTopicExtractor` for topic extraction from messages.

Or you could try https://github.com/streamnative/pulsar-flink if you are using Flink 1.9.0 or higher.
This feature is supported there.

**Comment by sijie** [comment]
@parth-sarathy since the  https://github.com/streamnative/pulsar-flink connector is the one that is being contributed back to the upstream Flink community. I would suggest trying this connector out since eventually we would like to maintain those connectors in flink repo, rather than in pulsar repo.
