### ISSUE TITLE
Admin rest request for Partitioned topic, like create subscribe, need handle redirect

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#6121]
Admin rest request for Partitioned topic, like create subscribe, need handle redirect. 
This is because some of the sub-partition is not owned by the current broker. 

![image](https://user-images.githubusercontent.com/6348208/72861559-3fa30300-3d05-11ea-9e28-8fd556ddda40.png)

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
