### ISSUE TITLE
Improve recover time from SPOF

### ISSUE THREAD

**Issue by snowcrumble** [apache/pulsar#6123]
**Is your feature request related to a problem? Please describe.**
I have done some testing of SPOF by kill a broker which dealing a topic pub/sub on it, my pulsar is deployed on k8s.
The problem is it cost avg 1 minutes for recover time and I found some possible reasons:

1. I found the broker ip in zk "/loadbalance/brokers" was still exist until about 10 second after the broker down, so I think broker is not unregister when it is killed

2. The cpp may has no option of connect timeout, I found it cost about 30 second on `async_resolve` a broker ip which is not exist any more (k8s pod's ip is remove from iptable after be deleted)

**Describe the solution you'd like**
1. Active  unregister broker ip when not serving any more
2. Add an option of connect timeout for cpp client.

**Describe alternatives you've considered**

**Additional context**

**Comment by merlimat** [comment]
> I have done some testing of SPOF by kill a broker which dealing a topic pub/sub on it, my pulsar is deployed on k8s.

In case of an ungraceful shutdown (eg: the IP of broker stops responding) there are 2 settings that controls how quickly the failure is detected/fixed: 

 1. ZooKeeper session timeout. default 30s. Before the session expires, the ownership of topics still belongs to the failed broker.
 2. Client keep-alive probes. The client sends periodic probes in the connection to detect stale TCP connections. The default time is 1min. In Java client it's possible to configure the interval: https://pulsar.apache.org/api/client/org/apache/pulsar/client/api/ClientBuilder.html#keepAliveInterval-int-java.util.concurrent.TimeUnit-

**Comment by snowcrumble** [comment]
> * ZooKeeper session timeout. default 30s. Before the session expires, the ownership of topics still belongs to the failed broker.
> * Client keep-alive probes. The client sends periodic probes in the connection to detect stale TCP connections. The default time is 1min. In Java client it's possible to configure the interval: https://pulsar.apache.org/api/client/org/apache/pulsar/client/api/ClientBuilder.html#keepAliveInterval-int-java.util.concurrent.TimeUnit-

Hi, I have tried to set broker configuration as below:
```
zooKeeperSessionTimeoutMillis: "10000"
zooKeeperOperationTimeoutSeconds: "10"
```
But the situation has not improved, first my situation is on connecting moment, so it's nothing to do with keep-alive, then I found it finally cost about 1 min on cpp code `async_resolve`, it had no logs within `Created connection for ...` and `Failed to establish connection: No route to host`.
May it be improved to add a timeout on `async_resolve` op?

**Comment by snowcrumble** [comment]
It seems to be related to  cloud k8s network, it's not appear when I used another k8s cluster.
