### ISSUE TITLE
Broker can't start with 2.5.0 helm release and replicaCounts set to 1

### ISSUE THREAD

**Issue by Lanayx** [apache/pulsar#6127]
**Describe the bug**
The broker is stuck in _CrashLoopBackOff_ on both minikube and google cloud with the same errors.

**To Reproduce**
1. use helm template with values-mini.yaml
2. set the following
```
  # Pulsar proxy
  proxy: yes
  # Bookkeeper auto-recovery
  autoRecovery: no
  # Pulsar dashboard
  # Deprecated
  # Replace pulsar-dashboard with pulsar-manager
  dashboard: no
  # pulsar manager
  pulsar_manager: yes
  # Bastion pod for administrative commands
  bastion: yes
  # Monitoring stack (prometheus and grafana)
  monitoring: no
```
3. set zookeeper, bookeeper, broker, proxy replicaCount to 1
4. See error (attached both logs for bookeeper and broker)

**Expected behavior**
Broker can be started normally

**Screenshots**

**Desktop (please complete the following information):**
 - Helm: minikube and google cloud

**Additional context**
Attaching broker and bookeeper logs
[bookeeper.log](https://github.com/apache/pulsar/files/4100280/bookeeper.log)
[broker.log](https://github.com/apache/pulsar/files/4100281/broker.log)

**Comment by sijie** [comment]
@Lanayx 

the error "org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available".

The bookkeeper replicaCount was 3 in values-mini.yaml. If you are changing it to 1, you need to change the ensemble size, write quorum and ack quorum to 1.

```
    PULSAR_PREFIX_managedLedgerDefaultEnsembleSize: "2"
    PULSAR_PREFIX_managedLedgerDefaultWriteQuorum: "2"
    PULSAR_PREFIX_managedLedgerDefaultAckQuorum: "2"
```

**Comment by Lanayx** [comment]
@sijie Unfortunately it didn't help, adding new logs
[bookeeper-new.log](https://github.com/apache/pulsar/files/4107608/bookeeper-new.log)
[broker-new.log](https://github.com/apache/pulsar/files/4107609/broker-new.log)

**Comment by yoavcloud** [comment]
I'm experiencing the same issue. Any assistance will be appreciated.

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Helm Chart has been permanently moved to https://github.com/apache/pulsar-helm-chart. If it's still relevant, please open an issue there.
