### ISSUE TITLE
dependiencis

### ISSUE THREAD

**Issue by nicktoker** [apache/pulsar#6140]
dependencies versions not need to be in the parent pom file, e.g. let the user choose

when using pulsar for example flink-pulsar, it bring a old version of flink

even if i use a new one
flink 1.9 and it bring me from pulsar dependencies flink 1.6 without option to change

don't set a versions in pulsar pom of external  jar if they are not part of the pulsar version
user need to add his dependencies in is app pom

<dependency>
  		<groupId>org.apache.pulsar</groupId>
  		<artifactId>pulsar-flink</artifactId>
  		<version>2.5.0</version>
	</dependency>

<dependency>
  		<groupId>org.apache.flink</groupId>
  		<artifactId>some flink componnet</artifactId>
  		<version>flink verionb</version>
	</dependency>

#### Steps to reproduce
just add in you app pom 

<dependency>
  		<groupId>org.apache.pulsar</groupId>
  		<artifactId>pulsar-flink</artifactId>
  		<version>2.5.0</version>
	</dependency>

#### System configuration
**Pulsar version**: 2.5.0

**Comment by sijie** [comment]
@nicktoker the current flink connector in the main repo only works for 1.6. It doesn't work for 1.9. 

If you want to run a flink connector on Flink 1.9, you can try https://github.com/streamnative/pulsar-flink. That's the connector that is being pushed to Flink upstream.

**Comment by sijie** [comment]
Closed this issue. Since the PMC has deprecated the current pulsar-flink integration maintained in the main repo. We encourage people to use the pulsar-flink connector proposed in FLIP-72, which is contributed to the upstream Flink community: https://cwiki.apache.org/confluence/display/FLINK/FLIP-72%3A+Introduce+Pulsar+Connector
