### ISSUE TITLE
Pulsar manager Negative initial size: -1  error

### ISSUE THREAD

**Issue by roman-popenov** [apache/pulsar#6141]
Following error can be seen in the logs of the pulsar manager:

```
18:04:02.914 [pulsar-external-web-4-5] WARN  org.eclipse.jetty.server.HttpChannel - /admin/v2/clusters
java.lang.IllegalArgumentException: Negative initial size: -1
	at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:74) ~[?:1.8.0_232]
	at org.apache.pulsar.proxy.server.AdminProxyHandler$ReplayableProxyContentProvider.<init>(AdminProxyHandler.java:150) ~[org.apache.pulsar-pulsar-proxy-2.4.2.jar:2.4.2]
```
It happens when the pulsar manager tries to communicate to the broker via the pulsar proxy.  Proxy is working just fine when producing and consuming messages via python client code. The pulsar manager UI just spins.

Possibly similar issue to https://github.com/streamnative/pulsarctl/pull/157

**Comment by sijie** [comment]
@roman-popenov the code repo of pulsar-manager is at  https://github.com/apache/pulsar-manager

**Comment by sijie** [comment]
I have created apache/pusar-manager#252. will close this issue.
