### ISSUE TITLE
Can't control the queue size in shared subscription with multiple topics

### ISSUE THREAD

**Issue by pl6306** [apache/pulsar#6162]
**Describe the bug**
In the use case where I have multiple consumers of the type pulsar.ConsumerType.Shared, the receiver_queue_size=1 parameter is ignored? It works fine when it is a single topic. It also doesn't work in a partitioned topic

**To Reproduce**
pts = ['topic-1','topic-2','topic-3']
consumer = client.subscribe(topic=pts,
                                    subscription_name=subscription,
                                    receiver_queue_size=1,
                                    max_total_receiver_queue_size_across_partitions=1,
                                    consumer_type=pulsar.ConsumerType.Shared,
                                    initial_position=pulsar.InitialPosition.Earliest)

**Expected behavior**
I expect that each consumer to get a receiver_queue_size of 1. But it doesn't

**Additional context**
Using version 2.4.2

**Comment by codelipenghui** [comment]
If topic count of a multi topic consumer greater than the given receiverQueueSize, the receiverQueueSize of the consumer will be the topic count. In java, you can check here: https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java#L164

BTW, what language client do you use?

**Comment by pl6306** [comment]
I use the python client.

**Comment by jiazhai** [comment]
@pl6306 how about change this to 3: `max_total_receiver_queue_size_across_partitions=3`

**Comment by jiazhai** [comment]
In cpp, it is also handled in the similar way.
for each partitioned-topic, the Total queue size is divided by the number of partitions.
```
 // Apply total limit of receiver queue size across partitions
    config.setReceiverQueueSize(
        std::min(conf_.getReceiverQueueSize(),
                 (int)(conf_.getMaxTotalReceiverQueueSizeAcrossPartitions() / partitions)));
```

**Comment by jiazhai** [comment]
@pl6306 Since no reply. I would like to close this issue at present. if above suggestion not work for you, please help re-open it.
