### ISSUE TITLE
Topic auto expiration

### ISSUE THREAD

**Issue by avillev** [apache/pulsar#6165]
I am using Pulsar as a very convenient PubSub system with most of its topics created automatically over time. The problem is that I obviously end up with a lot of unused topics over time.

I would love to have some kind of: "Topic expiration" parameter which could allow me to say: "If a topic does not have any activity (producer, subscription) since X amount of time, then delete it"

I can clean them manually or using some kind of script querying the cluster to find the inactive topics. But this is not the most convenient way to do things.

**Comment by codelipenghui** [comment]
This PR #6077 supports delete inactive topic when subscriptions caught up and added the `brokerDeleteInactiveTopicsMaxInactiveDurationSeconds`,  here 
 is the added configurations for inactive topic deleteion :https://github.com/apache/pulsar/pull/6077/files#diff-429aadcb840118bf9881b1d696e02cfdR103-R113

**Comment by avillev** [comment]
Thanks @codelipenghui 
The ticket mentions "Currently, pulsar support delete inactive topic which has no active producers and no subscriptions". Which configuration is that ?

**Comment by codelipenghui** [comment]
```
# Set the inactive topic delete mode. Default is delete_when_no_subscriptions
# 'delete_when_no_subscriptions' mode only delete the topic which has no subscriptions and no active producers
# 'delete_when_subscriptions_caught_up' mode only delete the topic that all subscriptions has no backlogs(caught up)
# and no active producers/consumers
brokerDeleteInactiveTopicsMode=delete_when_no_subscriptions
```
Not released yet, you can build from master branch.

**Comment by jiazhai** [comment]
Thanks @codelipenghui for the help.
@avillev Does it resolve your issue?

**Comment by avillev** [comment]
It does. Thank you.
