### ISSUE TITLE
Support system env var as functions parameters

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#6170]
**Is your feature request related to a problem? Please describe.**
Hi, I'd like to use YAML functions configurations files to pass creds to functions, but I still want use versioned YAML configurations file without have creds in repo.

**Describe the solution you'd like**
Something in the YAML description that uses `runtimeFlags: -Denv1=${SYSTEM_ENV1}...`

**Comment by jiazhai** [comment]
also added @wolfstudy and @EronWright in this thread. What is your idea on this issue?

**Comment by KannarFr** [comment]
Hi @jiazhai and @wolfstudy, 

The idea I shared is to pass system env vars to the function using the YAML configuration. 

On functions create/update, function worker gets the system env var matching `SYSTEM_ENV1` when `runtimeFlags: -Denv1=${SYSTEM_ENV1}` is defined and replaces it in the injected runtime flags.

WDYT?

**Comment by sijie** [comment]
@KannarFr - @nlu90 has sent out a pull request about this feature. please check if it meets your requirements.

**Comment by KannarFr** [comment]
@sijie commented on PR.
