### ISSUE TITLE
persistent://public/default/extract-text-.* does match everything topic starts with extract-text?

### ISSUE THREAD

**Issue by pl6306** [apache/pulsar#6185]
**Describe the bug**
I am using the python client with pulsar 2.4.2. I made a subscription with persistent://public/default/extract-text-.* expecting that it would subscribe to all topics that start with extract-text but instead pulsar just creates a topic called persistent://public/default/extract-text-.*? Is this a bug or is there a different syntax to subscribe to all topics starting with extract-text?

**Comment by pl6306** [comment]
The multi topic feature does not work as documented. Here is a simple test to show 

bin/pulsar-client consume my-topic-.* -s "first-subscription"

That should make a subscription to all topics that start with my-topic-

That means the consumer should receive a message from producer publishing to my-topic-hello

bin/pulsar-client produce my-topic-hello --messages "hello-pulsar"

It doesn't. Something is broken or the documentation is wrong.

**Comment by jiazhai** [comment]
@pl6306 This is not supported in client tools like `bin/pulsar-client`. But it should be supported in python  client. 
What is your python code looks like?

**Comment by jiazhai** [comment]
Here is the test code that cover's this case:
[test_topics_pattern_consumer](https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/python/pulsar_test.py#L901)

**Comment by jiazhai** [comment]
ping @pl6306

**Comment by pl6306** [comment]
Thanks I get it now. I have to do re.compile first.
