### ISSUE TITLE
`error while create opSendMsg by batch message container`

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#6195]
**Describe the bug**
I'm writing a logstash-output-pulsar plugin, but I've got the issue 

```
error while create opSendMsg by batch message container
```

It's using batches.

[repo of the plugin](https://github.com/CleverCloud/logstash-output-pulsar)

**To Reproduce**
It seems to run smoothly but after some hours, I've got the error and it doesnt recover. Only restart all works.

**Comment by codelipenghui** [comment]
@KannarFr I'll take a look, from your repo, client version is 2.5.0 right?

**Comment by KannarFr** [comment]
Yes it is.

**Comment by KannarFr** [comment]
No stacktrace.

**Comment by KannarFr** [comment]
@codelipenghui Hi, did you get time to take a look?

**Comment by codelipenghui** [comment]
@KannarFr I will take a look, this is indeed a tricky problem, I haven't found a way to reproduce.
