### ISSUE TITLE
Flaky-test:  PulsarStateTest.testPythonWordCountFunction

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6197]
When running tests in Github CI, this exception occasionally occurs:

```
org.apache.pulsar.tests.integration.functions.PulsarStateTest
  -     org.apache.pulsar.tests.integration.functions.PulsarStateTest.pulsar-standalone-suite
  -     PulsarStateTest.testPythonWordCountFunction
         -     which gave: PulsarStateTest.testPythonWordCountFunction:78->publishAndConsumeMessages:410 » ThreadTimeout
```
Interestingly, line 410 of publishAndConsumeMessages is the first line of this block:

```
@Cleanup Producer<byte[]> producer = client.newProducer(Schema.BYTES)
    .topic(inputTopic)
    .create();
```

This issue was first mentioned here: https://github.com/apache/pulsar/issues/6137

**Comment by devinbost** [comment]
Here's a log that includes this test: 
[11_run integration tests.txt](https://github.com/apache/pulsar/files/4207846/11_run.integration.tests.txt)

**Comment by mattisonchao** [comment]
The scenario appears after two years. affect master, branch-2.10, branch-2.9...

FYI:

https://github.com/apache/pulsar/pull/15801
https://github.com/apache/pulsar/pull/15757
https://github.com/apache/pulsar/runs/6602813932?check_suite_focus=true
https://github.com/apache/pulsar/runs/6602339258?check_suite_focus=true

**Comment by RobertIndie** [comment]
Also, it has failed on my PR https://github.com/apache/pulsar/pull/15571/ many times recently.

https://github.com/apache/pulsar/runs/6608041290?check_suite_focus=true

**Comment by mattisonchao** [comment]
The test is recovered.

**Comment by nicoloboschi** [comment]
It's back https://github.com/apache/pulsar/runs/6652119261?check_suite_focus=true

**Comment by tisonkun** [comment]
Closed as stale and no new reports for several months. Please open a new issue if it's still relevant to the maintained versions.
