### ISSUE TITLE
[Client][Reader API] Bypass broker when reading a segment in BookKeeper

### ISSUE THREAD

**Issue by yjshen** [apache/pulsar#6208]
When we are using the reader API, one of the optimizations we could achieve is bypass broker when the segment exists in BookKeeper. Therefore, the preferred workflow should be:

1. check the startingPosition to see if it is pointing to a finished ledger on the bookies, if so, read it from bookies directly.
1. for the in-progress ledger in a broker, read procedure should be identical to the current implementation.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
