### ISSUE TITLE
[Python Function] localrun deployment cannot store state 

### ISSUE THREAD

**Issue by SaturnIC** [apache/pulsar#6215]
**Updated description**
When deploying a localrun python pulsar function i can never store any state successfully over the context object in the pulsar function. After i store some key, value using context.put_state(key=key, value=value) the context.get_state(...) method always returns None!

If i deploy the same function using "create" instead of "localrun" 
the storage of state works fine.

**To Reproduce**
I use version 2.5.0 of the pulsar docker container.
If i deploy the function in the pulsar container, i ll use the pulsar-admin cli like this:
```
/pulsar/bin/pulsar-admin functions localrun \
--broker-service-url pulsar://broker_container:6650 \
--tenant user1 \
--namespace namespace1 \
--py /pulsar_functions/function1.py \
--name function_test \
--user-config '{"output_topic": "persistent://user1/namespace1/output_topic"}' \
--classname function1.Function1 \
--custom-serde-inputs '{"persistent://user1/namespace1/input_topic1":"function1.MyJsonSerDe"}' \
```
I noticed that the input msgs from the broker_container topic are indeed arriving in the function 
and the process hook function gets triggered, but the state never gets stored.

Did i forget to specify something? (like state-storage-service-url?)

**Expected behavior**
Be able to store and retrieve state from the context object no matter if the function is deployed
as "localrun" or with "create".

**Comment by SaturnIC** [comment]
I updated the issue description because i noticed after some experimentation that the problem seems to rest solely in the "localrun" deployment, if i deploy using "create" instead, everything works fine.

I also notice that i cannot use the pulsar-admin cli in localrun deployment of the function to list or inspect the created function.

**Comment by SaturnIC** [comment]
I found the solution, the problem was indeed the --broker-service-url flag.
I found the solution looking at the pulsar logs during function creation when using "create":
**--state_storage_serviceurl bk://127.0.0.1:4181** 

There is no example or hint about this issue anywhere in the documentary so i suggest
to add this information too the documentary.

It is no bug.

**Comment by sijie** [comment]
@SaturnIC thank you! we will update the documentation part.
