### ISSUE TITLE
Python Client for Windows

### ISSUE THREAD

**Issue by KelvinSajere** [apache/pulsar#6220]
**Is your feature request related to a problem? Please describe.**
The Python client library is not supported for windows

```
pip install pulsar-client==2.5.0
  ERROR: Could not find a version that satisfies the requirement pulsar-client==2.5.0 (from versions: none)
ERROR: No matching distribution found for pulsar-client==2.5.0
 ```

**Describe the solution you'd like**
Build python client supported for windows

**Comment by damienburke** [comment]
hey, wondering if there is a workaround here, besides building from source? Thanks

**Comment by nishantvas** [comment]
Similarly, I've noticed that installing pulsar-client on WSL also doesn't work

**Comment by Fischchen** [comment]
Are there any plans to port it to windows?

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Python client has been permanently moved to https://github.com/apache/pulsar-client-python. If it's still relevant, please open an issue there.

IIRC @BewareMyPower implement Windows support recently.
