### ISSUE TITLE
zookeeper connection cause resource leak

### ISSUE THREAD

**Issue by zplinuxlover** [apache/pulsar#6228]
in class `ZookeeperBkClientFactoryImpl`,  the `create` method

```
if (zk.getState() == States.CONNECTEDREADONLY && sessionType != SessionType.AllowReadOnly) {
                    future.completeExceptionally(new IllegalStateException("Cannot use a read-only session"));
                }
```

although this code can not reach, but pulsar should handle 'zookeeper.close' for this code

**Comment by jiazhai** [comment]
Thanks @zplinuxlover for this issue. Would you like to contribute to this?
