### ISSUE TITLE
Intermittent test failure in SLAMonitoringTest.testUnloadIfBrokerCrashes

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#623]
As seen in https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/24/testReport/junit/org.apache.pulsar.broker/SLAMonitoringTest/testUnloadIfBrokerCrashes/

```
java.lang.AssertionError: The SLA Monitor namespace should be owned by some other broker
	at org.apache.pulsar.broker.SLAMonitoringTest.testUnloadIfBrokerCrashes(SLAMonitoringTest.java:215)
```

**Comment by merlimat** [comment]
Happened again at https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/33/testReport/junit/org.apache.pulsar.broker/SLAMonitoringTest/testUnloadIfBrokerCrashes/

**Comment by jiazhai** [comment]
https://builds.apache.org/job/pulsar_precommit_java8/test_results_analyzer/
Seems not happened for a long time, would like to close it currently.
