### ISSUE TITLE
Add support for old version document of pulsar-admin

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar#6234]
**Is your feature request related to a problem? Please describe.**
The current pulsar-admin cli document can be generated automatically. For the latest version, you can view it here http://pulsar.apache.org/tools/pulsar-admin/2.6.0-SNAPSHOT. We need to add support for the old version.

**Comment by jiazhai** [comment]
Thanks @tuteng for working on this issue

**Comment by tuteng** [comment]
This is merged #6240
