### ISSUE TITLE
Intermittent test failure in SimpleProducerConsumerTest.testBlockUnackConsumerAckByDifferentConsumer

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#624]
As seen in https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/21/testReport/junit/org.apache.pulsar.client.api/SimpleProducerConsumerTest/testBlockUnackConsumerAckByDifferentConsumer/

```
java.lang.AssertionError: expected [110] but found [100]
	at org.apache.pulsar.client.api.SimpleProducerConsumerTest.testBlockUnackConsumerAckByDifferentConsumer(SimpleProducerConsumerTest.java:1643)
```

**Comment by jiazhai** [comment]
![image](https://user-images.githubusercontent.com/6348208/71708390-f78e7000-2e2b-11ea-9568-f4591de1afc7.png)
seems not happened for a long time, would like to close this.
