### ISSUE TITLE
Unexpected Github CI Action

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6249]
I got this error while executing a Github CI Action:

    ### ERRORED 19:24:20Z

    - An unexpected error occurred when executing this Action. Please submit a new support request using our Support website:

    https://support.github.com/contact

    Please include this unique ID in your request: D3DB:0CCA:1ED5DD:317EC0:5E3C67C0

The screenshot is below: 

![image](https://user-images.githubusercontent.com/7418031/73972883-cb5c8800-48de-11ea-8ee5-b43d021c2631.png)

Here is the link to the Pull Request where this happened: https://github.com/apache/pulsar/pull/6202/checks?check_run_id=430433107

I filed an issue with Github as per the instructions.

**Comment by devinbost** [comment]
I was given Ticket ID: 552444

**Comment by tisonkun** [comment]
Closed as stale.

It seems vanished on the current workflows.
