### ISSUE TITLE
Need to speed up tests

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6250]
The Pulsar integration tests take very long to run, and as new features are added, this runtime continues to get longer. The tests take so long to run that it impacts the iteration rate for developers who are attempting to add features and fix bugs. As a consequence, it demotivates developers to ensure that all the tests are behaving as they should, and it decreases developer motivation to work on intermittent issues that could be representing race conditions and concurrency issues. 
We need to determine if there's a way to speed up the tests, perhaps by replacing some of the integration tests with unit tests and making greater use of mocks, stubs, and fakes to isolate the code under test. 

I recognize that this may be a challenge to accomplish since Pulsar makes use of distributed technologies, but I still think it may deserve some attention.

**Comment by tisonkun** [comment]
Closes as not actionable.

I support your proposal to speed up tests, and I observe several new issues to reduce concrete test cases running time. However, holding such an abstract issue is not actionable.
