### ISSUE TITLE
Make metadata management more robust

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6251]
When the Zookeeper cluster is under heavy load or when Zookeeper is using poorly optimized hardware, Pulsar metadata can get out of sync and end up in a bad state. 
We need to ensure that additional robustness is added to the Pulsar Brokers' interactions with Zookeeper to ensure that corrupt metadata can be identified and corrected quickly.

**Comment by jiazhai** [comment]
I think @codelipenghui is working on a similar issue.

**Comment by devinbost** [comment]
@codelipenghui In case you want some ideas, I really like the way they handle Zookeeper interactions in Apache Ignite. It's one of the most stable distributed technologies I've ever worked with.

**Comment by codelipenghui** [comment]
@devinbost Thank you very much, I will check it out.

**Comment by lhotari** [comment]
Some of the Zookeeper related issues in the broker might get fixed by #8406 . I documented my experiences in https://github.com/apache/pulsar/issues/6259#issuecomment-719460964 . I haven't yet tested the fix since it was done about 24 hrs ago.

**Comment by lhotari** [comment]
Issue #9711 is also related to metadata management. There's PR #9900 to address #9711 and one of the observations made is that all metadata management operations (classes that use org.apache.pulsar.broker.resources.BaseResources as base class) have a local thread safety issue which is currently being fixed. It might be necessary to file a separate issue that captures this. 
/cc @315157973 @eolivelli

**Comment by tisonkun** [comment]
Closing as answered.

This is an open-ended discussion. We have a few follow-ups to improve metadata management now.
