### ISSUE TITLE
(Flaky-test) - no space left on device: Could not build image

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6268]
When running the `CI - Integration - Sql` Github CI Action, this error appeared:
```
[ERROR] Error processing tar file(exit status 1): write /pulsar/offloaders/tiered-storage-jcloud-2.6.0-SNAPSHOT.nar: no space left on device
[ERROR] Error processing tar file(exit status 1): write /pulsar/offloaders/tiered-storage-jcloud-2.6.0-SNAPSHOT.nar: no space left on device
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (default) on project pulsar-standalone-docker-image: Could not build image: Error processing tar file(exit status 1): write /pulsar/offloaders/tiered-storage-jcloud-2.6.0-SNAPSHOT.nar: no space left on device -> [Help 1]
```

The issue appeared here: https://github.com/apache/pulsar/pull/6202/checks?check_run_id=432618226

Logs are attached.
[logs_14608.zip](https://github.com/apache/pulsar/files/4173390/logs_14608.zip)

**Comment by devinbost** [comment]
@tuteng This might be under your radar since you've been working on similar issues lately.

**Comment by tuteng** [comment]
Thanks, I will take a look at. @devinbost

**Comment by tuteng** [comment]
@devinbost This has been fixed https://github.com/apache/pulsar/pull/6279, can we close it?

**Comment by devinbost** [comment]
@tuteng Thanks for getting this fixed right away!
