### ISSUE TITLE
Segmentation fault when using python client in pyenv environment on OSX Catalina

### ISSUE THREAD

**Issue by adityav** [apache/pulsar#6269]
**Describe the bug**
Getting a segmentation fault when using pyenv to manage python version. Its works fine when I use the system installed python. 
```
(.venv) ~/s/m/test-producer ❯❯❯ python
Python 3.7.6 (default, Feb  7 2020, 17:24:32) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulsar
[1]    24462 segmentation fault  python
```
Python version: 3.7.6
System Python version: 3.7.6. Installed via `brew install python`

libraries installed into pyenv. All of them are dependencies pulled into the venv when installing python client.
```
apache-bookkeeper-client==4.10.0
certifi==2019.11.28
chardet==3.0.4
enum34==1.1.6
fastavro==0.22.9
grpcio==1.26.0
idna==2.8
prometheus-client==0.7.1
protobuf==3.11.3
pulsar-client==2.5.0
pymmh3==0.0.5
pytz==2019.3
ratelimit==2.2.1
requests==2.22.0
six==1.14.0
urllib3==1.25.8
```

**To Reproduce**
Steps to reproduce the behaviour:
1. install pyenv
2. `brew install zstd protobuf`
3. `pyenv install 3.7.6 && pyenv local 3.7.6`
4. pip install pulsar-client==2.5.0
4. run python and try importing the package. 

**Desktop (please complete the following information):**
 - OS: macOS Catalina. Version 10.15.2

Here is an almost useless gdb stacktrace
```
(gdb) run producer.py
Starting program: .venv/bin/python producer.py
[New Thread 0xe03 of process 26565]
[New Thread 0x1103 of process 26565]
warning: unhandled dyld version (16)

Thread 2 received signal SIGSEGV, Segmentation fault.
0x00000001024ab480 in ?? ()
(gdb) bt
#0  0x00000001024ab480 in ?? ()
#1  0x000000010027a970 in _PyLong_One ()
#2  0x00000001038030b0 in ?? ()
#3  0x00007ffeefbfc9e0 in ?? ()
#4  0x00000001039fbe18 in ?? ()
#5  0x000000010599f1f0 in ?? ()
#6  0x000000010027a970 in _PyLong_One ()
#7  0x000000010027a970 in _PyLong_One ()
#8  0x0000000102458410 in ?? ()
#9  0x00007ffeefbfca40 in ?? ()
#10 0x0000000100117d23 in _PyImport_LoadDynamicModuleWithSpec ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by tisonkun** [comment]
Closed as stale. The development of the Python client has been permanently moved to http://github.com/apache/pulsar-client-python. Please open an issue there if it's still relevant.
