### ISSUE TITLE
[offloaders] Define treshold and deletionMaxLag per ns or use the default one.

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#6283]
**Is your feature request related to a problem? Please describe.**
The OffloadPolices per ns is just merged. But it's missing a point on values to trigger auto offloading: we want to define tresholdMaxBytes and deletionMaxLag per ns or use the default one configured.

**Describe the solution you'd like**
Add  tresholdMaxBytes and deletionMaxLag in OffloadPolices and use them to defines triggers.

**Comment by KannarFr** [comment]
I think we should consider adding https://github.com/streamnative/pulsar/issues/221 and https://github.com/streamnative/pulsar/issues/73, they should be done together. WDYT?

**Comment by KannarFr** [comment]
So when the offload check thread is passing it will check for "to offload things" and "to remove from offloaded" and do its stuff consequently.

**Comment by KannarFr** [comment]
Already done, I missread the commit, it's already done, so just streamnative#221 and streamnative#73 are 'to do".

**Comment by KannarFr** [comment]
@gaoran10 you confirm?

**Comment by gaoran10** [comment]
@KannarFr Hi, I think these features are interesting.

**Comment by KannarFr** [comment]
@gaoran10 I'm not sure to understand your answer. I mean, I created the issue because I thought these features don't exist, but IIRC the commits they exist. Your last message tells that they don't, what is the status of these, then? :p

**Comment by KannarFr** [comment]
Ok so it's not done.

**Comment by KannarFr** [comment]
Hum, the deletion max lag and threshold must be defined at ManagedLegerImpl. But the ManagedLedgerFactory is set at topic creation level. We need a way to define them dynamically from OffloadPolicies changes.

Do you think we need to recreate the ManagedLedgerFactory each time OffloadPolicies changes?

@sijie ^

**Comment by KannarFr** [comment]
Maybe @jiazhai have ideas too?

**Comment by KannarFr** [comment]
Or just a way to retrieve OffloadPolicies from ManagedLedgerImpl, but I think we want to keep splitted bookkeeper/broker stuff.

**Comment by sijie** [comment]
Adding the notes between @KannarFr and me

```
kannarfr  3:38 PM
so do you have an opinion about the last comments i posted to https://github.com/apache/pulsar/issues/6283?
KannarFrKannarFr
#6283 [offloaders] Define treshold and deletionMaxLag per ns or use the default one.
Is your feature request related to a problem? Please describe.  
The OffloadPolices per ns is just merged. But it's missing a point on values to trigger auto offloading: we want to define tresholdMaxBytes and deletionMaxLag per ns or use the default one configured.
Describe the solution you'd like  
Add tresholdMaxBytes and deletionMaxLag in OffloadPolices and use them to defines triggers.
Labels
type/feature
Comments
10
<https://github.com/apache/pulsar|apache/pulsar>apache/pulsar | Feb 10th | Added by GitHub






sijieg  3:43 PM
You want this to be configured per namespace ?
3:43
correct?
3:44
oh do you mean making these two settings available in OffloadPolicies?

kannarfr  3:50 PM
yes
3:50
and when tieredstorage deletion will be done, I need to add two more configuration for this deletion in offloadpolicies (edited) 
3:52
so finally offloadpolicies will contains deletionlag/threshold for bk -> tieredstorage, and another couple deletion lag/threshold for tieredstorage -> deleted
3:53
but there is architecture problem/definition to discuss and find solution how to change managedledgerimpl configuration on the fly as offloadpolicies mutate
3:54
WDYT?
3:54
because currently it's only on broker configuration so on broker boot, because of the managedledgerfactory creation
3:55
so something like one managedledgerfactory per ns (because of the deletionlag/threshold per ns) etc.

sijieg  3:56 PM
I think the first thing would be introducing a per manage ledger setting to override the factory setting?
3:56
then after that, you can map offloadpolicies to the per managed ledger setting.
3:56
does that sound like a good approach?
3:56
so two seperate changes and don’t couple them together
```
