### ISSUE TITLE
Hanging ManagedLedgerBkTest.setUp

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6288]
When I try to run any of the ManagedLedgerBkTest instances locally, the tests are hanging on the setUp method. 
The log messages are stuck in a loop with messages like this:

> 17:32:25.009 [LedgerDirsMonitorThread:org.apache.bookkeeper.util.DiskChecker@156] ERROR org.apache.bookkeeper.util.DiskChecker - Space left on device /var/folders/zg/mg9pbwns01d3hnc5p2y0hxnr0000gp/T/bookie3504632864196205720test/current : 8410619904, Used space fraction: 0.9664495 > threshold 0.95.
> 17:32:35.008 [LedgerDirsMonitorThread:org.apache.bookkeeper.bookie.LedgerDirsMonitor@110] WARN  org.apache.bookkeeper.bookie.LedgerDirsMonitor - LedgerDirsMonitor check process: All ledger directories are non writable
> 17:32:35.009 [LedgerDirsMonitorThread:org.apache.bookkeeper.util.DiskChecker@156] ERROR org.apache.bookkeeper.util.DiskChecker - Space left on device /var/folders/zg/mg9pbwns01d3hnc5p2y0hxnr0000gp/T/bookie3504632864196205720test/current : 8410492928, Used space fraction: 0.96645004 > threshold 0.95.
> 17:32:45.007 [LedgerDirsMonitorThread:org.apache.bookkeeper.bookie.LedgerDirsMonitor@110] WARN  org.apache.bookkeeper.bookie.LedgerDirsMonitor - LedgerDirsMonitor check process: All ledger directories are non writable
> 17:32:45.008 [LedgerDirsMonitorThread:org.apache.bookkeeper.util.DiskChecker@156] ERROR org.apache.bookkeeper.util.DiskChecker - Space left on device /var/folders/zg/mg9pbwns01d3hnc5p2y0hxnr0000gp/T/bookie3504632864196205720test/current : 8432586752, Used space fraction: 0.9663619 > threshold 0.95.
> 
> Process finished with exit code 130 (interrupted by signal 2: SIGINT)

If there's a disk space issue (which seems odd because I have 9 GB free), we need a condition to check for that and throw an exception instead of loop infinitely.

I've attached a more complete log here:
[test_log2.txt](https://github.com/apache/pulsar/files/4183692/test_log2.txt)
(It ends when I killed the test.)

**Comment by devinbost** [comment]
It appears to be stuck in this loop:

```
        while (bkc.getZkHandle()
            .exists(ledgerRootPath + "/available/" + InetAddress.getLocalHost().getHostAddress() + ":" + port,
                false) == null) {
            Thread.sleep(500);
        }
```
in `startBookie(..)`

**Comment by devinbost** [comment]
Here's the conf value that's getting passed as the first parameter of startBookie(..):

![image](https://user-images.githubusercontent.com/7418031/74203957-975ecb00-4c2e-11ea-8406-84c18b37f5ef.png)

**Comment by merlimat** [comment]
Bookie is failing to start up because the disk usage is >95%

**Comment by devinbost** [comment]
@merlimat You are right. 
On a production server, if the disk utilization is that high if the bookie crashes, will there be a problem with restarting the bookie? Or, is it just an issue with running the test?

**Comment by devinbost** [comment]
(This is just an issue related to the running environment.) It probably doesn't require a code change.
