### ISSUE TITLE
[Proxy]No active broker is available

### ISSUE THREAD

**Issue by snowcrumble** [apache/pulsar#6290]
**Describe the bug**
My pulsar is running on k8s and our service is using pulsar proxy, I have did some failure testing, I used pulsar-perf tool to continuous pub/sub on a topic at the same time I "force" restart a k8s node, it was affect all the compents such as zk, broker, bookie, proxy. The problem was it reported error message 
`ERROR org.apache.pulsar.client.impl.ClientCnx - [id: 0xf9392f24, L:/172.17.0.2:43802 - R:/172.16.11.200:6650] Close connection because received internal-server error No active broker is available`, It never improve util I restart the proxy. I went deep into the proxy code then found it may be a problem of `localZkCache`

**To Reproduce**
1. Deploy pulsar on k8s
2. use pulsar-perf tool to continuous pub/sub on a topic
3. "force" restart a k8s node
4. The reconnect mechanism doesn't work.

**Expected behavior**
Proxy should found active broker after k8s node restarted.

**Screenshots**
![image](https://user-images.githubusercontent.com/3243173/74209869-86f92f80-4cc4-11ea-8331-e620f6248394.png)

**Comment by SakaSun** [comment]
I'm experiencing the same problem.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
