### ISSUE TITLE
Proxies probably spamming Brokers

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#6291]
**Describe the bug**
Since we updated to v2.5.0, we have some troubles after some days running. Our brokers are seen unreachable (5s timeout, on poll a local daemon) by our monitoring. There are no WARN/ERROR logs on brokers sides and proxies sides. But the messages are not well forwarded by proxies to brokers. And the only way to restore a working situation is to reboot the proxies nodes. We are suspecting kernel connections limits issues.

WDYT?

**To Reproduce**
Can't be done on demand :/.

**Environment (please complete the following information):**
 - 3 proxies -> 3 brokers

**Comment by jiazhai** [comment]
@KannarFr Could this be persist reproduce?

**Comment by KannarFr** [comment]
I'm not sure to understand what do you mean?

**Comment by KannarFr** [comment]
@jiazhai on our cluster case it happens each series of 5-6 days, our usage is very linear this why we suspect connections issues. Like reaching some kernel limits, you have any infos regarding this? 

More, do you have example for specs requirements depending on the following `proxy.conf` fields:

```
##### --- Rate Limiting --- #####

# Max concurrent inbound connections. The proxy will reject requests beyond that.
maxConcurrentInboundConnections=10000

# Max concurrent outbound connections. The proxy will error out requests beyond that.
maxConcurrentLookupRequests=50000
```
