### ISSUE TITLE
(Flaky-test) Possible prod issue - Trying to subscribe with incompatible schema

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6302]
This is the same exception that I observed here: https://github.com/apache/pulsar/issues/5311
I saw it today when I ran two tests locally:

- testDebeziumMySqlSource
- testDebeziumPostgreSqlSource

It's not clear yet if they're related to that bigger issue. 
I've attached their logs.
[testDebeziumMySqlSource_logs.txt](https://github.com/apache/pulsar/files/4189399/testDebeziumMySqlSource_logs.txt)
[testDebeziumPostgreSqlSource_logs.txt](https://github.com/apache/pulsar/files/4189400/testDebeziumPostgreSqlSource_logs.txt)

**Comment by tuteng** [comment]
How do you run this test? Can you show your command? @devinbost 

I run the integration test locally using the following command:

package
```
mvn clean install -DskipTests
mvn -B -f tests/docker-images/pom.xml install -am -Pdocker -DskipTests
```
run test
```
mvn test -pl  tests/integration -DintegrationTests -DredirectTestOutputToFile=false -Dtest=PulsarFunctionsProcessTest -Dgroups=source
```

**Comment by devinbost** [comment]
In the case that I reported above, I actually ran these tests from IntelliJ...
I can try running them as you specified.

**Comment by devinbost** [comment]
@tuteng

**Comment by tisonkun** [comment]
Closed as stale and no recent report. Please open a new issue if it's still relevant in maintained versions.
