### ISSUE TITLE
The C++ Client distribution is basically borked.

### ISSUE THREAD

**Issue by ashwinkapur** [apache/pulsar#6311]
It does not seem possible to build the C++ client except possibly by using your docker image which uses mystery binaries. 

1) Your Cmake files seem to use old style Cmake which specifies each directory and file etc as opposed to just specifying dependencies of groups of objects of libraries and letting Cmake figure it out. I'd be happy to submit a patch fixing this and using Modern Cmake (see https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1)

2) You seem to be using a patched version of google protobuf version 2 to avoid needless memory allocations. Why not use google flatbuffers instead. Designed for precisely this purpose and they have other benefits like vastly more serialization and deserialization. When using C++, there is essentially no serialization or deserialization, it's just writing to a memory location and dereferencing a pointer. With Java you don't have quite the same low level access available  so it's close but not quite that efficient.

3) In the current head on github and the source distribution v 2.5.0 in protobuf/README.md at the bottom of the file you state:

### For C++ Client:

The pre-generated C++ code is at `pulsar-client-cpp/lib/PulsarApi.pb.cc` and `pulsar-client-cpp/lib/PulsarApi.pb.h`.

You don't need to manually generate C++ code. The C++ code is automatically generated by `cmake`.

**_However, these files aren't there in either github or the source distribution._**

4) Also in protobuf/README you state:

We are currently using a modified version of the Google Protocol Buffer code generator, to generate code that can serialize/deserialize messages with no memory allocations (caching already instantiated objects) and also to be able to directly use Netty pooled ByteBuf with direct memory.

To re-generate the `PulsarApi.java` code you need to apply a patch to the protobuf generator. Patch is found in `build/docker/protobuf.patch`.

#### Commands for creating the pre-generated Java code

```shell
export PULSAR_HOME=<Path where you cloned the pulsar repo>

cd $HOME
git clone https://github.com/google/protobuf.git

cd ${HOME}/protobuf
git checkout v2.4.1

### Apply patch
patch -p1 < ${PULSAR_HOME}/build/docker/protobuf.patch

### Compile protobuf
autoreconf --install
./configure
make

### Re-generate PulsarApi
cd ${PULSAR_HOME}/pulsar-common/
export PROTOC=${HOME}/protobuf/src/protoc
./generate_protobuf.sh
```

**_There is no directory called build in the source distribution. In the source distribution find . -name protobuf.patch finds no file. There is a build/docker/protobuf.patch on github on head but now I'm not sure if this is the same patch._**

**Comment by merlimat** [comment]
@ashwinkapur 

> It does not seem possible to build the C++ client except possibly by using your docker image which uses mystery binaries.

We're building C++ client in many different environments on Linux, Mac and Windows. It would be more helpful if you could specify where it's failing to build for you.

> Your Cmake files seem to use old style Cmake which specifies each directory and file etc as opposed to just specifying dependencies of groups of objects of libraries and letting Cmake figure it out. I'd be happy to submit a patch fixing this and using Modern Cmake

Keep in mind that this project was not started a couple of days ago. The version of CMake was probably not supporting these directives back then. If you have any improvement, please submit!

> You seem to be using a patched version of google protobuf version 2 to avoid needless memory allocations. 

It's only used for Java. C++ protobuf is very efficient on its own.

> Why not use google flatbuffers instead.

When the protocol was designed, flatbuffer we relatively new and didn't support many languages (and required C++11 which we couldn't target at that point).

> In the current head on github and the source distribution v 2.5.0 in protobuf/README.md at the bottom of the file you state:

>> For C++ Client:
>>The pre-generated C++ code is at pulsar-client-cpp/lib/PulsarApi.pb.cc and pulsar-client->> cpp/lib/PulsarApi.pb.h.

>> You don't need to manually generate C++ code. The C++ code is automatically generated by cmake.

> However, these files aren't there in either github or the source distribution.

The `protobuf/README.md` section on C++ is out-of-date and misleading. The files are indeed generated by cmake (using the system `protoc`) and therefore are not anymore in the source tree (like they used to be in the past).

> There is no directory called build in the source distribution. In the source distribution find . -name protobuf.patch finds no file. There is a build/docker/protobuf.patch on github on head but now I'm not sure if this is the same patch.

Again, the readme is out of date. `./pulsar-common/generate_protobuf_docker.sh` will use the patched protoc to generate the `PulsarApi.java`.

Please submit PRs to fix the stale README file

**Comment by tisonkun** [comment]
Closed as stale and no response.

The development of the C++ client has been permanently moved to https://github.com/apache/pulsar-client-cpp. If it's still relevant, please open an issue there.
