### ISSUE TITLE
[Helm] Pulsar Manager do not work if Pulsar authentication is enabled

### ISSUE THREAD

**Issue by SakaSun** [apache/pulsar#6314]
**Describe the bug**
If you enabled authentication on brokers, Pulsar Manager is not able to connect since there is no way to inform the required parameters.
Note: Although it is a Pulsar Manager related issue, the problem lies in the Helm Chart located in this repository.

**To Reproduce**
1. Configure authentication on brokers or proxy in `values.yaml`:
```
PULSAR_PREFIX_authorizationEnabled: "true"
authorizationEnabled: "true"
```
Note: Both parameters with and without prefix are required hence the issue #6135 is not fixed yet.

2. Deploy in a custom kubernetes cluster:
`helm install pulsar -f values.yaml ./pulsar/`

3. Proxing the pulsar-manager locally:
`kubectl port-forward -n pulsar svc/pulsar-pulsar-manager 9527

4. Access it at http://localhost:9527

5. The Pulsar Manager interface shows no information about the cluster and sometimes a forbidden message is shown.

**Expected behavior**
All the information about the cluster should be visible in the interface.

**Additional context**
Looking at the `pulsar-manager-deployment.yaml` the environment values are fixed and that way JWT_TOKEN or SECRET_KEY cannot be passed to the container.

Note: Despite this there is another related problem that should be fixed in order to completely solve this issue https://github.com/apache/pulsar-manager/issues/260

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Helm Chart has been permanently moved to https://github.com/apache/pulsar-helm-chart. If it's still relevant, please open an issue there.
