### ISSUE TITLE
[pulsar client] partitioned topic cause connection leak when connection pool disable pooling

### ISSUE THREAD

**Issue by ltamber** [apache/pulsar#6319]
**Describe the bug**
when use partitioned topic, the connection from client to discovery service will grow up and keep alive util application shut down.

**To Reproduce**
1. we used pulsar-perf, command is: ./bin/pulsar-perf consume -n 6 -c 0 -u pulsar://x.x.x.x:6660,x.x.x.x:6660 -s sub-1 -st Failover tenantTest/namespaceTest/partitiontopic2
2. then netstat -anp | grep 6660 | wc -l, the connection number will increasing slowly

**Expected behavior**
if we disable pooling, the connection should close when we done our lookup.

**Screenshots**
![image](https://user-images.githubusercontent.com/5679413/74398752-9fe41b00-4e53-11ea-9dba-74ded0371c22.png)

**Additional context**
there is a timer in partition topic client will autoUpdatePartitions, every getPartitionsForTopic will create a new connection and won't close it

**Comment by ltamber** [comment]
@jiazhai @tuteng @wolfstudy PTAL

**Comment by sijie** [comment]
@ltamber are you interested in contributing a fix to this?

**Comment by ltamber** [comment]
@sijie Yes, but don't have any good way to fix this

**Comment by jiazhai** [comment]
@ltamber Thanks for the help. Seems it can be stable reproduce, and you are close the the root cause. Maybe we need to handle the release of disable-pooling connection in a different way.
In the `ConnectionPool`, (maxConnectionsPerHosts == 0) means a "disable pooling".
