### ISSUE TITLE
Support consume a topic in reverse order

### ISSUE THREAD

**Issue by AllenChien** [apache/pulsar#6320]
**Is your feature request related to a problem? Please describe.**

In some case, we prefer read more recently message first, and move forward if necessary.

**Describe the solution you'd like**

Consume API has a reverse option, thus we can consume from latest to earliest (or specific position).

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.
