### ISSUE TITLE
Pulsar io connector is not run at broker. 

### ISSUE THREAD

**Issue by xiemeilong** [apache/pulsar#6323]
**Describe the bug**
Pulsar io connector is not run at broker.  Status gotted by api says it running. But there is no functions log at /pulsar/logs/ folder. and there is no function effect .
All connector can run at local mode.

**To Reproduce**
create any connector . I have tried source and sink, buildin and custom.

**Expected behavior**
Connector runs normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/2681638/74445791-ebc5ad00-4eb1-11ea-825d-bf696c0822d9.png)
![image](https://user-images.githubusercontent.com/2681638/74445856-03049a80-4eb2-11ea-845e-a9f008f67246.png)
![image](https://user-images.githubusercontent.com/2681638/74446238-8f16c200-4eb2-11ea-8884-892d92d5c026.png)

**Desktop (please complete the following information):**
 - OS:  k8s  apachepulsar/pulsar-all:2.5.0

**Additional context**

**Comment by nicolo-paganin** [comment]
The same for me, in puslar v2.5.0 connectors seems to not work. The same connector is working in version 2.4.2. Also no logs are produced in the logs folder nor for connector neither for pulsar functions

**Comment by tuteng** [comment]
Can you debug according to this document http://pulsar.apache.org/docs/en/io-debug/, I want to see more information. @nicolo-paganin @xiemeilong

**Comment by xiemeilong** [comment]
@tuteng  All connector can run normally in local mode.  No log file in cluster mode.

**Comment by nicolo-paganin** [comment]
@tuteng the problem is that in local mode this is working. In standalone mode if I copy the nar of my sink and a I create the sink it is not working and also no log files are written. 

Try to start pulsar standalone and than add a connector, is this working for you?

**Comment by nicolo-paganin** [comment]
@tuteng I confirm that connectors are working in pulsar 2.5.0 standalone mode. Also log are written but the path is changed from 2.4.2 -> 2.5.0 (maybe it is written in some configuration file).

Now logs are written in `/tmp/functions` folder

**Comment by tuteng** [comment]
Thanks, @nicolo-paganin @xiemeilong, I will take a look at it.

**Comment by tuteng** [comment]
I tried to test in cluster mode, one zookeeper, one bookie, one broker, but there was no reproduce the problem. @nicolo-paganin @xiemeilong Can you show more log information, under folder /tmp/functions

**Comment by xiemeilong** [comment]
@tuteng It is the buildin debezium-mysql connector. 
[iot-mysql-log-source-0.log](https://github.com/apache/pulsar/files/4212055/iot-mysql-log-source-0.log)

**Comment by tuteng** [comment]
Look at the log. There seems to be a problem with your pulsar cluster. There is no broker available. Does your function worker have a connection address to configure pulsar? http://pulsar.apache.org/docs/en/functions-worker/  Is your broker normal and your function-worker normal? @xiemeilong

**Comment by xiemeilong** [comment]
@tuteng  The log is copyed from the broker pod .   The pulsar is deployed using the helm chart of pulsar source repository.   The broker has started  and report can't connect to connector for getting the metrics.

**Comment by xiemeilong** [comment]
@tuteng  Sorry,  I deleted the broker pod and run a new one , the proxy  still not found the new one. I am fixing the issue. I will upload the new log after that.

**Comment by xiemeilong** [comment]
@tuteng  The log seems it working, but still no log generated in /pulsar/logs.

[iot-mysql-log-source-0.log](https://github.com/apache/pulsar/files/4212299/iot-mysql-log-source-0.log)

**Comment by tuteng** [comment]
You can try to get the log from file /tmp/function/`tenant-name`/`namespace-name`/`function-name` @xiemeilong

**Comment by Esakkimuthu991** [comment]
> I tried to test in cluster mode, one zookeeper, one bookie, one broker with function-worker, but there was no reproduce the problem. Use JDBC connector http://pulsar.apache.org/docs/en/io-quickstart/#update-a-jdbc-sink @nicolo-paganin @xiemeilong Can you show more log information, under folder /tmp/functions

Can you guide to run the pulsar in cluster mode. My requirement is to run the kafka source connector using function worker.  Logs are providing the general eception. That;s not helped out
