### ISSUE TITLE
The pulsar-perf generated HdrHistogram file open failed

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#6327]
**Describe the bug**
Use pulsar-perf to start to publish messages and generate HdrHistogram file, when to open the file by https://hdrhistogram.github.io/HdrHistogram/plotFiles.html. The error occurs.
![image](https://user-images.githubusercontent.com/12592133/74520278-2d0d9980-4f52-11ea-9f1f-ed6ac59dfc78.png)

**Comment by codelipenghui** [comment]
To use `hgrm` file that the `pulsar-perf` generated, the following steps can work well.

> 1. clone https://github.com/HdrHistogram/HdrHistogram.git
> 2. cd HdrHistogram
> 3. mvn clean install -DskipTests
> 4. $ ./HistogramLogProcessor -i `<hgrm file path that pulsar-perf generated>` -o `<output path>`

After these steps, you will get two output files, upload the output file that the file name ends with `.hgrm` to https://hdrhistogram.github.io/HdrHistogram/plotFiles.html, you will get a graphical display.

**Comment by jiazhai** [comment]
Thanks @codelipenghui for the help. So It only needs to add documentation to fix this issue?

**Comment by codelipenghui** [comment]
@jiazhai Yes, we need some documentation for pulsar-perf

**Comment by codelipenghui** [comment]
close via #6970

**Comment by Anonymitaet** [comment]
Docs have been added: https://pulsar.apache.org/docs/en/next/performance-pulsar-perf/
