### ISSUE TITLE
C# Client - SharpPulsar

### ISSUE THREAD

**Issue by eaba** [apache/pulsar#6328]
Hi community,
Please I need your help in [SharpPulsar](https://github.com/eaba/SharpPulsar)!
Specifically need your help(s) in these area:
[Schema](https://github.com/eaba/SharpPulsar/tree/master/SharpPulsar/Impl/Schema) - I have worked on it but not fully completed.
[MessageCrypto](https://github.com/eaba/SharpPulsar/blob/master/SharpPulsar/Impl/MessageCrypto.cs) - not perfect yet!
[Tests](https://github.com/eaba/SharpPulsar/tree/master/SharpPulsar.Test) - I need someone who could spend some time cleaning the Tests.

I am reaching out here cause I want to move on from build errors as fast as as possible and focus on the Presto client side!

Thanks!

**Comment by sijie** [comment]
@eaba [DotPulsar]() has been accepted as a sub project of Apache Pulsar. It might be good if you can join the force on developing the .NET client in DotPulsar.

**Comment by eaba** [comment]
With SharpPulsar, I have gone the way of matching the java client 100%, why?
Once it is matched, anyone can easily compare and implement any missing feature from the java client with less time!
I wont always have this much time to spare!!
