### ISSUE TITLE
How can I user "Reed-Solomon error correction" (erasure coding)??

### ISSUE THREAD

**Issue by oeegee** [apache/pulsar#6334]
I was look "Reed-Solomon error correction" keyword at 
 https://pulsar.apache.org/docs/en/concepts-tiered-storage/

But I know how work well it in pulsar.
and additional configuration - linux package, library, configuration, etc...

Thank you!

**Comment by sijie** [comment]
I don’t think we need to handle erasure coding at Pulsar level. Erasure coding is typically implemented in the specific storage implemention. Pulsar just uses external storage systems for tiered storage. Those systems already implement erasure coding. 

If you are looking for erasure coding within bookkeeper, bookkeeper doesn’t implement it yet. But there were discussions about that.

**Comment by tisonkun** [comment]
Closed as information delivered.
