### ISSUE TITLE
[Helm] Wrong/Missing key definition in configData in values-mini.yaml

### ISSUE THREAD

**Issue by liyuntao** [apache/pulsar#6338]
**Describe the bug**
Inconsistent key definition between `values.yaml` and `values-mini.yaml` in line 184. 
It seems the former is correct.

[values-mini.yaml L184](https://github.com/apache/pulsar/blob/df152109415f2b10dd83e8afe50d9db7ab7cbad5/deployment/kubernetes/helm/pulsar/values-mini.yaml#L184)  
1. missing `BOOKIE_GC `, `BOOKIE_MEM ` and `PULSAR_PREFIX_dbStorage_rocksDB_blockCacheSize `.   
2. `PULSAR_MEM `duplicated.

[values.yaml  L184](https://github.com/apache/pulsar/blob/df152109415f2b10dd83e8afe50d9db7ab7cbad5/deployment/kubernetes/helm/pulsar/values.yaml#L184)  as contrast.

**Comment by sijie** [comment]
@liyuntao do you want to contribute a pull request to fix the issue?

**Comment by liyuntao** [comment]
Hi @sijie  I've make the [related pr](https://github.com/apache/pulsar/pull/6340). Please review, thanks.
