### ISSUE TITLE
Korean documentation is not built to the website

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#6342]
*Problem*

The Korean translation has been enabled in Crowdin. But the pages are not built to the website. So when choosing `Korean` in the menu, the documentation is not reachable.

**Comment by oeegee** [comment]
Thank you sijie and jiazhai ~!!

**Comment by oeegee** [comment]
Hi, @sijie. 
How do i do for this problem?

**Comment by oeegee** [comment]
How can I solve this problem?
Is there anything I can help?

**Comment by sijie** [comment]
@tuteng can you help look into this issue?

**Comment by oeegee** [comment]
Is there anything I can help? Having a build problem?

**Comment by tuteng** [comment]
I think it is related to the configuration of this file. https://github.com/apache/pulsar/blob/master/site2/website/languages.js There are two similar configurations in this file, one is true and the other is false. 

```
{
    enabled: false,
    name: '한국어',
    tag: 'ko',
  },
{
    enabled: true, 
    name: '한국어', 
    tag: 'ko-KR'},
```

but their tag is different.  @oeegee

**Comment by sijie** [comment]
@oeegee do you want to create a PR to fix it?

You can remove the entry "ko-KR" and set the entry "ko" to `true`.
