### ISSUE TITLE
DNS configuration

### ISSUE THREAD

**Issue by diegosalvi** [apache/pulsar#6346]
**Is your feature request related to a problem? Please describe.**
You can't configure any aspect of client DNS (servers, timeouts...)

**Describe the solution you'd like**
To ba able to configure at least DNS to use to resolve names

**Describe alternatives you've considered**
...

**Additional context**
I've dived into Pulsar client DNS internal configuration and I didn't found any way to properly configure DNS client properties on my system. Moreover if "autodiscovery" cannot find any dns it will attempt to use Google ones! In a corporate environment this isn't acceptable.

I could write you a patch to add dns configuration but I'm blocked between 3 alternatives:
1. add every needed dns configuration parameter on client configuration (... with some configuration bloating)
1. just require to provide an already configured netty dns and use current one as fallback (but it couldn't be configured via properties but only programmatically and expose internal netty dependences)
1. create a new "DNSClient" interface and a netty implementation and require to provide such dns object (but still cannot be configured via properties...)

**Comment by sijie** [comment]
2 seems to be a reasonable approach to me

**Comment by diegosalvi** [comment]
Created PR for (2)

**Comment by tisonkun** [comment]
Closed as stale. See https://github.com/apache/pulsar/pull/6382#issuecomment-1340126622.
