### ISSUE TITLE
Reader.startMessageIdInclusive() is not working 

### ISSUE THREAD

**Issue by Vanchhay** [apache/pulsar#6350]
**Describe the bug**
I tried to get the latest message from the topic using Reader.
```
client.newReader()
                    .topic(topic)
                    .startMessageId( X )
                    .startMessageIdInclusive()
                    .create();
```
But I got the message from X+1 and so on.

**Expected behavior**
Expected to receive the message from X and so on.

**Additional context**
pulsar version = 2.5.0

**Comment by yjshen** [comment]
I think it's related to #6344 .

**Comment by adrianog** [comment]
Is startMessageIdInclusive available in python?
