### ISSUE TITLE
There is at least one place where sendAsync does not release the semaphore

### ISSUE THREAD

**Issue by scr-oath** [apache/pulsar#6360]
**Describe the bug**

If an error occurs that completes the future without releasing the semaphore then the calling thread may block forever.

https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L354

There may be another case with timeout that tickles this but that's harder to reproduce

**To Reproduce**

Send a bunch of large messages asynchronously; hang

**Expected behavior**
Any failure path should release the semaphore before returning.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jiazhai** [comment]
@scr-oath Would you like to provide a fix for this?

**Comment by jiazhai** [comment]
Thanks a lot for the reporting and analysis.

**Comment by sijie** [comment]
This is fixed by #6488

**Comment by scr-oath** [comment]
Thanks!

**Comment by scr-oath** [comment]
> @scr-oath Would you like to provide a fix for this?

Looks like you got it!
