### ISSUE TITLE
[pulsar-io] Create Google PubSub Source

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6377]
We need to be able to ingest data from Google PubSub into Pulsar. We should create a Source connector.

**Comment by tisonkun** [comment]
Closed as we don't host a wishing list in issues. Feature requests can be opened against the Discussions forum.

BTW, StreamNative provides such integration at https://github.com/streamnative/pulsar-io-google-pubsub. Feel free to give it a try.
