### ISSUE TITLE
[pulsar-io] Create Google PubSub Sink

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6378]
We need to be able to emit data from Pulsar into Google PubSub. We should create a Sink connector.

**Comment by tisonkun** [comment]
Closed as we don't host a wishing list in issues. Feature requests can be opened against the Discussions forum.

BTW, StreamNative provides such integration at https://github.com/streamnative/pulsar-io-google-pubsub. Feel free to give it a try.
