### ISSUE TITLE
(Flaky-test) Intermittent failure of ReaderTest.testReaderReachEndOfTopic

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6385]
I encountered this failure during a Github CI build, but unfortunately, I don't remember which build it was... I'll need to provide more information once I encounter it again. I just wanted to create this issue before I forgot again. 

```
FAILED TESTS (2/161):
249 85 ms: ./main ReaderTest.testReaderReachEndOfTopic
250 76 ms: ./main ReaderTest.testReaderReachEndOfTopicMessageWithoutBatches
```

I did notice that `ReaderTest.testReaderReachEndOfTopic` involves `reader.hasMessageAvailable`, which may relate to one or more of the bugs that have been worked on recently there. @yjshen @codelipenghui FYI.

I'm not sure yet which assertions failed in those tests above though. (These are CPP tests.)

**Comment by tisonkun** [comment]
Closed as stale and no recent report. Please open a new issue if it's still relevant in maintained versions.
