### ISSUE TITLE
(Flaky-test) Intermittent failure of PulsarSpoutTest.beforeMethod(..)

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6387]
I got this in the Github CI Action:

```
[ERROR] Failures: 
[ERROR] org.apache.pulsar.storm.PulsarSpoutTest.beforeMethod(org.apache.pulsar.storm.PulsarSpoutTest)
[ERROR]   Run 1: PulsarSpoutTest.beforeMethod:63->setup:89 » IllegalState Failed to initialize ...
```
It can be seen here: https://github.com/apache/pulsar/pull/6202/checks?check_run_id=459330039

I have attached the log archive: 
[logs_19997.zip](https://github.com/apache/pulsar/files/4234096/logs_19997.zip)

**Comment by tisonkun** [comment]
Closed as stale and no recent report. Please open a new issue if it's still relevant in maintained versions.
