### ISSUE TITLE
Expect an option to disable auto creation of subscriptions

### ISSUE THREAD

**Issue by murong00** [apache/pulsar#6394]
The current pulsar admin rest endpoints have already supported to create/list/delete subscriptions of topics. It will be meaningful to allow administrators to disable auto creation of subscriptions. Some scenarios can benefit from it:
- subscriptions should not be expanded arbitrarily (although subscriptions can be expired)
- public cloud scenario
- better to limit the count of subscriptions

**Comment by murong00** [comment]
@sijie @jiazhai I am trying to work on this, any suggestions? So far I can think of the following:
- provide a flag `allowAutoSubscriptionCreation`, defaults to `true`
- when `allowAutoSubscriptionCreation` is disabled and the specified subscription on the topic does not exist when trying to subscribe via a consumer, the server should reject the request directly by `handleSubscribe` in `ServerCnx`
- create the specified subscription on the topic from pulsar admin rest endpoint before create a consumer

**Comment by murong00** [comment]
cc @codelipenghui

**Comment by sijie** [comment]
@murong00 the proposal looks good to me +1

**Comment by murong00** [comment]
@sijie @codelipenghui The above proposal may not work for `Reader` due to `ReaderBuilderImpl` (i.e. `PulsarClientImpl.doCreateReaderAsync` which calls `ReaderImpl`) does not support to pass `subscription`, its implementation is hard-coded currently. https://github.com/apache/pulsar/blob/760bd1abfa5374bde85e4d938937a0410dfb2674/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ReaderImpl.java#L37-L43
In addition, the current pulsar admin rest endpoints only support to create a `Durable` subscription which can not apply to `Reader`(or `Consumer` with a `NonDurable` subscription) whose subscription is `NonDurable`. https://github.com/apache/pulsar/blob/75a321dfbe23cbd979fa225ef4a3d2fc4201994b/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L741-L744
Should we skip the `Durable` subscriptions when checking to see if a subscription exists? Or maybe we can create it when it is `NonDurable`?

**Comment by murong00** [comment]
Any advice will be appreciated, thanks.

**Comment by sijie** [comment]
We can skip non-durable subscriptions

**Comment by murong00** [comment]
@sijie Thanks for the advice. I have submitted a fix, please help to review when you are available.
