### ISSUE TITLE
Not able to create a Pulsar function

### ISSUE THREAD

**Issue by vishalananth07** [apache/pulsar#6408]
**Describe the bug**
We are trying to create a Pulsar function and deploy that in a bare-metal cluster we already have. We are creating the Exclamation function(exfun.py) given in the example as follows
```
bin/pulsar-admin functions create --py exfun.py --classname ExclamationFunction --tenant public --namespace default --name process --inputs test-in-1 --output test-out-1
```
But it gives the following error
```
null
Reason: java.lang.NumberFormatException: For input string: "8080,fyp2:8080"
```

We are having a 2-node cluster with the following configuration:
```
bin/pulsar initialize-cluster-metadata --cluster pulsar-cluster-1 --zookeeper fyp1:2181 --web-service-url http://fyp1:8080,fyp2:8080 --broker-service-url pulsar://fyp1:6650,fyp2:6650 --configuration-store fyp1:2181
```

Can you please help us here @jiazhai @sijie  ? Thanks :)

**Comment by sijie** [comment]
@vishalananth07 I think this is related to #6365 

for a short-term solution, I would suggest updating the service urls in your cluster configuration to point to one broker one. You can do that via `pulsar-admin clusters update`

**Comment by vishalananth07** [comment]
Are there any tradeoffs of pointing the cluster to one broker? Will it still work in a distributed manner?

**Comment by sundar-10** [comment]
Will this issue get resolved within the next week? @sijie @jiazhai  We are using it for our college project and we need to present a fully working system. Also, won't pointing to a single broker cause other issues? Sorry for the inconvenience caused. Thanks.

**Comment by sijie** [comment]
@vishalananth07 it will still work in a distributed manner. but the initial topic lookup will hit service unavailability if the broker goes down. @zymap is fixing the issue. we hopefully will merge this issue soon next week.

**Comment by brouwerorange** [comment]
@vishalananth07 
in case of me, I faced same issue when I set webServiceUrl as more than one brokers in client.conf.
maybe you can try to set one broker in webServiceUrl.

Best regard

**Comment by elgca** [comment]
> @vishalananth07 it will still work in a distributed manner. but the initial topic lookup will hit service unavailability if the broker goes down. @zymap is fixing the issue. we hopefully will merge this issue soon next week.

When I run the official tutorial, I got the same problem, right?

```shell
[pulsar@pulsar-node3 apache-pulsar-2.6.1]$ bin/pulsar-admin functions create \
>   --jar examples/api-examples.jar \
>   --classname org.apache.pulsar.functions.api.examples.ExclamationFunction \
>   --inputs persistent://public/default/exclamation-input \
>   --output persistent://public/default/exclamation-output \
>   --tenant public \
>   --namespace default \
>   --name exclamation
java.lang.ClassCastException: java.lang.NumberFormatException cannot be cast to org.apache.pulsar.client.admin.PulsarAdminException
        at org.apache.pulsar.client.admin.internal.FunctionsImpl.createFunction(FunctionsImpl.java:324)
        at org.apache.pulsar.admin.cli.CmdFunctions$CreateFunction.runCmd(CmdFunctions.java:657)
        at org.apache.pulsar.admin.cli.CmdFunctions$BaseCommand.run(CmdFunctions.java:97)
        at org.apache.pulsar.admin.cli.CmdBase.run(CmdBase.java:71)
        at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:240)
        at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:282)

```
