### ISSUE TITLE
Pull Request checks detected documentation changes but it's not

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#6409]
**Describe the bug**
On https://github.com/apache/pulsar/pull/6381, the checks are detected as documentation changes but it's not. So checks like units tests are not run while they must be run.

**Comment by sijie** [comment]
@KannarFr there was an issue about `checkout` actions. I think we already fixed it. I looked at https://github.com/apache/pulsar/pull/6381 it seems that all unit tests are running, no?

**Comment by KannarFr** [comment]
Yes.
