### ISSUE TITLE
Pulsar Multi Cluster on Kubernetes (AWS)

### ISSUE THREAD

**Issue by rattanjotsingh** [apache/pulsar#6415]
**Is your feature request related to a problem? Please describe.**
There is no documentation available on how to deploy pulsar on multi cluster on kubernetes.

**Describe the solution you'd like**
Would love to have a Kubernetes deployment files where we can deploy pulsar across different regions like east and west. 

**Describe alternatives you've considered**
http://pulsar.apache.org/docs/en/deploy-bare-metal-multi-cluster/
It has solution for bare metal but not for kubernetes(AWS)

*

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.

@michaeljmarshall @MarvinCai does pulsar-helm-chart support this feature now so we can add some docs?
