### ISSUE TITLE
State Functions - stuck after 3 events?

### ISSUE THREAD

**Issue by Pixelartist** [apache/pulsar#6427]
**Describe the bug**
We are currently experiencing something which I would consider as a bug. If we deploy a function which affects the state, it stops working at one point, to be exact -> after consuming / processing 3 events.
At the same time, it seems that the bookkeeper API is being affected by it - a request to the state of the function will time out.

**To Reproduce**
1. Spawn a standalone pulsar
2. deploy the attached function
3. produce 10 (3+) messages

**Expected behavior**
In case the function is okay - it should consume all events and produce the outputs. In case it is a real error, it should stop the function from running, then either restart or error out (whatever the designed solution is)

**Screenshots**
You can see me reproducing this in the following screencast - https://asciinema.org/a/TqyVCb5lTvO6Y6l0yKKRuPr8g

**Desktop (please complete the following information):**
 - OS: Foundation - MacOS using Docker with the latest pulsar docker image
- function: using python

**Additional context**
Using "querystate" by the cli will return the following error - Reason: javax.ws.rs.ProcessingException

[statefunction.txt](https://github.com/apache/pulsar/files/4255743/statefunction.txt)

**Comment by Pixelartist** [comment]
Additional information - I was able to make it up to a 1000 processed messages, by manually adding messages 1 by 1 ... slowly ramping up to 150 messages every 3 seconds, where it broke with the same result -> being stuck at 3 messages. Will try to find and attach a log of the state table service if I understand where to find it.

**Comment by jiazhai** [comment]
thanks @Pixelartist for the reporting. It would be great if the log of function worker could be provided.

**Comment by Pixelartist** [comment]
Hello,

I reproduced the problem once more - with the following output within the log files:

logs/pulsar-standalone.log - empty
tmp/functions/public/default/StateMe/StateMe-0.log - [StateMe-0.log](https://github.com/apache/pulsar/files/4274256/StateMe-0.log)

Please see below - _input_ has more messages than _output_ where java shows a lot of io-errors during restart.

running: `bin/pulsar-admin functions status   --tenant public   --namespace default   --name StateMe`
```
{
  "numInstances" : 1,
  "numRunning" : 1,
  "instances" : [ {
    "instanceId" : 0,
    "status" : {
      "running" : true,
      "error" : "",
      "numRestarts" : 0,
      "numReceived" : 360,
      "numSuccessfullyProcessed" : 357,
      "numUserExceptions" : 0,
      "latestUserExceptions" : [ ],
      "numSystemExceptions" : 0,
      "latestSystemExceptions" : [ ],
      "averageLatency" : 44.71126457556289,
      "lastInvocationTime" : 1583137556896,
      "workerId" : "c-standalone-fw-localhost-8080"
    }
  } ]
}
```

running: ```
bin/pulsar-admin functions querystate \
  --tenant public \
  --namespace default \
  --name StateMe \
  --key pulsar
```

```
null

Reason: javax.ws.rs.ProcessingException

```

running:
`bin/pulsar-admin topics stats-internal public/default/state-input`

```
{
  "entriesAddedCounter" : 412,
  "numberOfEntries" : 412,
  "totalSize" : 25976,
  "currentLedgerEntries" : 412,
  "currentLedgerSize" : 25976,
  "lastLedgerCreatedTimestamp" : "2020-03-02T08:24:19.889Z",
  "waitingCursorsCount" : 1,
  "pendingAddEntriesCount" : 0,
  "lastConfirmedEntry" : "12:411",
  "state" : "LedgerOpened",
  "ledgers" : [ {
    "ledgerId" : 12,
    "entries" : 0,
    "size" : 0,
    "offloaded" : false
  } ],
  "cursors" : {
    "public%2Fdefault%2FStateMe" : {
      "markDeletePosition" : "12:356",
      "readPosition" : "12:412",
      "waitingReadOp" : true,
      "pendingReadOps" : 0,
      "messagesConsumedCounter" : 357,
      "cursorLedger" : 13,
      "cursorLedgerLastEntry" : 4,
      "individuallyDeletedMessages" : "[]",
      "lastLedgerSwitchTimestamp" : "2020-03-02T08:24:19.916Z",
      "state" : "Open",
      "numberOfEntriesSinceFirstNotAckedMessage" : 56,
      "totalNonContiguousDeletedMessagesRange" : 0,
      "properties" : { }
    }
  }
}
```


running:
` bin/pulsar-admin topics stats-internal public/default/state-output`

```
{
  "entriesAddedCounter" : 326,
  "numberOfEntries" : 326,
  "totalSize" : 58601,
  "currentLedgerEntries" : 326,
  "currentLedgerSize" : 58601,
  "lastLedgerCreatedTimestamp" : "2020-03-02T08:24:36.057Z",
  "waitingCursorsCount" : 1,
  "pendingAddEntriesCount" : 0,
  "lastConfirmedEntry" : "14:325",
  "state" : "LedgerOpened",
  "ledgers" : [ {
    "ledgerId" : 14,
    "entries" : 0,
    "size" : 0,
    "offloaded" : false
  } ],
  "cursors" : {
    "my-subscription" : {
      "markDeletePosition" : "14:325",
      "readPosition" : "14:326",
      "waitingReadOp" : true,
      "pendingReadOps" : 0,
      "messagesConsumedCounter" : 326,
      "cursorLedger" : 15,
      "cursorLedgerLastEntry" : 4,
      "individuallyDeletedMessages" : "[]",
      "lastLedgerSwitchTimestamp" : "2020-03-02T08:24:36.107Z",
      "state" : "Open",
      "numberOfEntriesSinceFirstNotAckedMessage" : 1,
      "totalNonContiguousDeletedMessagesRange" : 0,
      "properties" : { }
    }
  }
}
```



Restart:
```
bin/pulsar-admin functions restart   --tenant public   --namespace default   --name S
tateMe
```
Restarted successfully

after restart:
`bin/pulsar-admin functions status   --tenant public   --namespace default   --name StateMe`
```
{
  "numInstances" : 1,
  "numRunning" : 0,
  "instances" : [ {
    "instanceId" : 0,
    "status" : {
      "running" : false,
      "error" : "UNAVAILABLE: io exception",
      "numRestarts" : 0,
      "numReceived" : 0,
      "numSuccessfullyProcessed" : 0,
      "numUserExceptions" : 0,
      "latestUserExceptions" : [ ],
      "numSystemExceptions" : 0,
      "latestSystemExceptions" : [ ],
      "averageLatency" : 0.0,
      "lastInvocationTime" : 0,
      "workerId" : "c-standalone-fw-localhost-8080"
    }
  } ]
}
```

-> [StateMe-0_after_restart.log](https://github.com/apache/pulsar/files/4274328/StateMe-0_after_restart.log)

[display_log.log](https://github.com/apache/pulsar/files/4274460/display_log.log)

**Comment by Pixelartist** [comment]
[display_log.log](https://github.com/apache/pulsar/files/4274470/display_log.log)

**Comment by Antti-Kaikkonen** [comment]
I'm getting the same error with my java source connector that uses state. I thought it might be because I'm doing too many concurrent state operations, but your StateMe function doesn't seem to use state concurrently... 

My source connector seems to get this error quite randomly. Sometimes it happens after ~1k state operators and sometimes more than 100k, but I think that it usually happens sooner with increased throughput.

I'm getting this error with both standalone deployment and three bookie deployment.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
