### ISSUE TITLE
Log automatic topic compaction failures

### ISSUE THREAD

**Issue by racorn** [apache/pulsar#6432]
**Describe the bug**
If a namespace is set up with a `compaction-threshold`, compaction should be triggered automatically.

I configured a namespace with compaction, produced messages, and in the main log file, I could see that 'phase one' of compaction was started. But there was no sign of phase two, and no WARN or ERROR message. I tried manual compaction with

`bin/pulsar compact-topic --topic persistent://tenant/namespace/topic`

and then there was reported an error (TimeoutException)

**Expected behavior**
If automatic triggered compaction fails, it should be logged in the broker log file.

**Discussion**
`org.apache.pulsar.broker.service.persistent.PersistentTopic#triggerCompaction()` starts compaction, but does not report any failures. For example, one could add logging with

```
public synchronized void triggerCompaction()
            throws PulsarServerException, AlreadyRunningException {
        if (currentCompaction.isDone()) {
            currentCompaction = brokerService.pulsar().getCompactor().compact(topic);
            currentCompaction.whenComplete((ledger, error) -> {
                if (error != null) { log.error( ...
                ...
        } else {
            throw new AlreadyRunningException("Compaction already in progress");
        }
    }
```

**Additional context**
Pulsar 2.5.0 release

**Comment by yjshen** [comment]
This might be related to `hasMessageAvailable` semantics in `ConsumerImpl`. No logs of phase 2 may denote the compaction is hanging forever.

**Comment by racorn** [comment]
Yes, I am quite certain that compaction failed in TwoPhaseCompactor.phaseOneLoop as indicated here
 CompletableFuture<RawMessage> future = reader.readNextAsync();
 scheduleTimeout(future);

The readNextAsync() did not complete in 10 seconds, and the whole compaction was aborted (this could also be reported better, but that is another issue i guess).

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
