### ISSUE TITLE
compile pulsar 2.5.0 meet a question

### ISSUE THREAD

**Issue by chengchampion** [apache/pulsar#6446]
Failed to execute goal on project pulsar-io-flume: Could not resolve dependencies for project org.apache.pulsar:pulsar-io-flume:jar:2.5.0: Failed to collect dependencies at com.github.stefanbirkner:system-rules:jar:1.17.0 -> junit:junit-dep:jar:4.9.1-SNAPSHOT: Failed to read artifact descriptor for junit:junit-dep:jar:4.9.1-SNAPSHOT: Could not transfer artifact junit:junit-dep:pom:4.9.1-SNAPSHOT from/to mirrorId (http://repo1.maven.org/maven2/): Failed to transfer file http://repo1.maven.org/maven2/junit/junit-dep/4.9.1-SNAPSHOT/junit-dep-4.9.1-SNAPSHOT.pom with status code 501
 
someone met this question???

**Comment by jiazhai** [comment]
@chengchampion  Would you please try "mvn clean install -DskipTests"?

**Comment by tisonkun** [comment]
Closed as no response and 2.5.0 is end of life.
