### ISSUE TITLE
Unable to disable logs for python bindings

### ISSUE THREAD

**Issue by mannjani** [apache/pulsar#6459]
**Describe the bug**
I am not able to disable logs from python bindings.
I have tried passing an empty file into log_conf_file_path.
I have tried passing a valid log4cxx configuration file without any console appenders.
It is still printing logs on the console

**To Reproduce**
1. Create an empty file named empty
2. Start python console
3. import pulsar
4. c = pulsar.Client(service_url=<service_url>, log_conf_file_path="empty")
5. p = c.create_producer("topic")
6. See on console:

2020-03-02 08:51:39.476 INFO  ConnectionPool:85 | Created connection for <service_url>
2020-03-02 08:51:39.477 INFO  ClientConnection:330 | ... Connected to broker
2020-03-02 08:51:39.482 INFO  HandlerBase:53 | [persistent://public/default/delete, ] Getting connection from pool
....

**Expected behavior**
There should be no logs

**Comment by rodrigoreis** [comment]
Any updates?

**Comment by jadbin** [comment]
Emmm, any updates?

**Comment by jadbin** [comment]
It maybe because of a c++ client building option named `USE_LOG4CXX`. If this option is not set, the c++ client will create a simple logger (not log4cxx logger) using stdout to output logs.  `log_conf_file_path` will work if and only if c++ client is set to use log4cxx logger.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant in maintained versions.

BTW, the development of the Python Client is permanently moved to https://github.com/apache/pulsar-client-python.
