### ISSUE TITLE
Topics with replicated subscription are not deleted in GC

### ISSUE THREAD

**Issue by hrsakai** [apache/pulsar#6464]
There is a topic with a replicated subscription.
If I delete the replicated subscription and all clients disconnect, the topic has no subscriptions or clients, but GC doesn't delete the topic.
I have to delete the topic manually with pulsar-admin command tool.
This cause seems to be related to marker messages(snapshot request and response).
Replicators in each cluster continue to publish marker messages.

**Comment by congbobo184** [comment]
@hrsakai do you set-retention for the namespace from the topic?

**Comment by hrsakai** [comment]
@congbobo184 I don't set retention.

**Comment by congbobo184** [comment]
is your what brokerDeleteInactiveTopicsEnabled = true in broker.conf?

**Comment by congbobo184** [comment]
How did you delete the replicated subscription by admin api? you forcefully delete the topic manually? I look at the code if you delete the replicated subscription and another cluster will not delete the replicated subscription. so i think the problem is here.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
