### ISSUE TITLE
Improved feature jdbc-sink

### ISSUE THREAD

**Issue by cmdares** [apache/pulsar#6465]
**Is your feature request related to a problem? Please describe.**
I used to confluent formerly, but now I want to switch to plusar. And found jdbc sink slightly weak
1、Mainstream database is not supported like Postgresql Oracle Mssql
2、Sink feature still need to be enhance.
**Describe the solution you'd like**
Reference:
https://docs.confluent.io/current/connect/kafka-connect-jdbc/sink-connector/index.html
https://docs.confluent.io/current/connect/kafka-connect-jdbc/sink-connector/sink_config_options.html
More refined supported by JDBC features，hope to bring more references.

**Describe alternatives you've considered**
Add parameter configuration.

thanks.
regard.

**Comment by tisonkun** [comment]
Thanks for your reference!

Although, we almost use issues to track actionable tasks. Open-ended discussions can be posted in the Discussions forum.

Closed as not an issue.
