### ISSUE TITLE
[website] Foreign language pages are all broken

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6470]
There’s a dead link (http://pulsar.apache.org/en/admin-rest-api/#/) on this page: https://pulsar.apache.org/docs/en/admin-api-overview/

It appears in several places and takes me to an empty web page.

**Comment by jiazhai** [comment]
![image](https://user-images.githubusercontent.com/6348208/76045309-a586d980-5f97-11ea-9957-8677811a465a.png)
this link should be "https://pulsar.apache.org/admin-rest-api?version=2.5.0"

**Comment by jiazhai** [comment]
![image](https://user-images.githubusercontent.com/6348208/76045405-e7b01b00-5f97-11ea-9d45-2a68851bda80.png)

**Comment by jiazhai** [comment]
@devinbost Thanks a lot for the help. I found 2 links in above pictures, which should link to "https://pulsar.apache.org/admin-rest-api?version=2.5.0".  Is there any other places?

**Comment by devinbost** [comment]
It looks like the link works when "/en/" is not part of the URL. For example, this works:
[http://pulsar.apache.org/admin-rest-api/?version=2.5.0](http://pulsar.apache.org/admin-rest-api/?version=2.5.0)
but this does not:
[http://pulsar.apache.org/en/admin-rest-api/?version=2.5.0](http://pulsar.apache.org/en/admin-rest-api/?version=2.5.0)

It looks like the "/en/" part is in the Javascript, so I'd need to dig through the logic there to figure out what all the places are where it's referenced. (See below.)

![image](https://user-images.githubusercontent.com/7418031/76057181-f239c880-5f35-11ea-857d-51ee741641e7.png)

**Comment by devinbost** [comment]
I found over 1300 instances of dead links on this site (before I stopped the process) by using this tool: https://www.brokenlinkcheck.com/broken-links.php#status
(It wouldn't let me export the list of URLs without paying for commercial support.)

A percentage of the links are not real links, such as pulsar://localhost:6650
However, it appears that all of the language-specific links are broken, such as "/fr/", "/zh-CN/", etc.

**Comment by devinbost** [comment]
For example:
![image](https://user-images.githubusercontent.com/7418031/76057772-b30c7700-5f37-11ea-8e8f-69c857cb2e85.png)

**Comment by tisonkun** [comment]
The initiative of translation is archived since no maintainers or contributors work on it. See also #17972.

All related links should be redirected and work well. If you find more broken links, feel free to open new issues.
