### ISSUE TITLE
[pulsar-bookkeeper] Failed to open rocksdb

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6492]
We got this exception in our production logs:

`ERROR org.apache.bookkeeper.statelib.impl.kv.RocksdbKVStore - Failed to open rocksdb at dir /pulsar/data/bookkeeper/ranges/ranges/000000000000000002/000000000000000001/000000000000000000`

This incident was associated with an occurrence of this issue: https://github.com/apache/pulsar/issues/6054
but we haven't been able to track down a distinct cause yet. The error above is the only error that we couldn't pin to some other possible cause, such as a network issue or broker restart, so we're not sure if it's related.

**Comment by tisonkun** [comment]
Closed as stale. Feel free to reopen it if it's still relevant for maintained versions.

Besides, thanks for reporting issues :) I believe the integration with RocksDB has been improved over the years.
