### ISSUE TITLE
create the producer will core in c++

### ISSUE THREAD

**Issue by liujiejie** [apache/pulsar#6497]
**Describe the bug**
When I start the system to create the producer，The program will lose its core。The program is run in linux and Encoding with c++.
and my code is:
    send_callback_ = std::bind(&RegisterPulsar::SendCallbackFunc,
        this, std::placeholders::_1, std::placeholders::_2);
    SendTopicInfo* send_info = new SendTopicInfo;
    send_info->topic = GWConfig::Instance()->ayers_send_topic_;
    pulsar::Result result = pulsar_client_ptr_->createProducer(
        send_info->topic, send_info->producer);

the stack is:
#0  0x00007f91bfc0c574 in boost::system::error_category::operator== (this=0x7f91bac5b4c0, rhs=...) at /home/lj/space/3rd/boost_1_71_0/boost/system/error_code.hpp:235
235     /home/lj/space/3rd/boost_1_71_0/boost/system/error_code.hpp: 
Missing separate debuginfos, use: debuginfo-install glibc-2.17-292.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64
(gdb) bt
#0  0x00007f91bfc0c574 in boost::system::error_category::operator== (this=0x7f91bac5b4c0, rhs=...) at /home/lj/space/3rd/boost_1_71_0/boost/system/error_code.hpp:235
#1  0x00007f91bfc0c9f1 in boost::system::error_category::equivalent (this=0x7f91bac5b4c0, code=..., condition=113) at /home/lj/space/3rd/boost_1_71_0/boost/system/error_code.hpp:839
#2  0x00007f91be3d243a in pulsar::ClientConnection::handleTcpConnected(boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>) ()
   from /home/test/ktp//3rd/lib/libpulsar.so.2.5.0
#3  0x00007f91be3e37b9 in boost::asio::detail::reactive_socket_connect_op<std::_Bind<std::_Mem_fn<void (pulsar::ClientConnection::*)(boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>)> (std::shared_ptr<pulsar::ClientConnection>, std::_Placeholder<1>, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>)> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) () from /home/test/ktp//3rd/lib/libpulsar.so.2.5.0
#4  0x00007f91be3e0751 in boost::asio::detail::task_io_service::run(boost::system::error_code&) () from /home/test/ktp//3rd/lib/libpulsar.so.2.5.0
#5  0x00007f91be429477 in boost::asio::detail::posix_thread::func<pulsar::ExecutorService::ExecutorService()::{lambda()#1}>::run() () from /home/test/ktp//3rd/lib/libpulsar.so.2.5.0
#6  0x00007f91be3dc92f in boost_asio_detail_posix_thread_function () from /home/test/ktp//3rd/lib/libpulsar.so.2.5.0
#7  0x00007f91bd18ce65 in start_thread () from /lib64/libpthread.so.0
#8  0x00007f91bceb588d in clone () from /lib64/libc.so.6

**Comment by tisonkun** [comment]
Closed as stale.

The development of the C++ client has been permanently moved to https://github.com/apache/pulsar-client-cpp. If it's still relevant, please open an issue there.
