### ISSUE TITLE
Update InfluxDB Sink to connect to InfluxDB 2.0 write API

### ISSUE THREAD

**Issue by russorat** [apache/pulsar#6514]
**Is your feature request related to a problem? Please describe.**
The latest InfluxDB release has changed their write path slightly and requires a token to communicate with it. This feature request would add support to the latest InfluxDB 2.0 write API.

**Describe the solution you'd like**
I'd like to be able to choose a version of InfluxDB to write data to, and specifying the Token, Org, bucket, and precision to write data to.

**Describe alternatives you've considered**
None

**Additional context**
https://v2.docs.influxdata.com/v2.0/write-data/#influxdb-api
https://v2.docs.influxdata.com/v2.0/api/#operation/PostWrite

**Comment by jiazhai** [comment]
Thanks @russorat for this reminder. Mark this as help wanted.  Would you like to contribute to it?

**Comment by russorat** [comment]
this is awesome! thank you @sijie !

**Comment by sijie** [comment]
@russorat you are welcome! More contributions are welcome!
