### ISSUE TITLE
health monitoring, alarms

### ISSUE THREAD

**Issue by ilyam8** [apache/pulsar#6518]
**Is your feature request related to a problem? Please describe.**

There is apache pulsar [deploy-monitoring article](https://pulsar.apache.org/docs/en/deploy-monitoring/#__docusaurus), it describes how to to collect metrics.

These are exposes metrics (via prometheus endpoint)

> https://github.com/apache/pulsar/blob/master/site2/docs/reference-metrics.md

Most of them are performance metrics, it is very nice to have them but it is **not clear how to monitor health status of the broker, what alarm rules should we apply**.

___

**Describe the solution you'd like**

There is `CockroachDB` monitoring documtetaion:

> https://www.cockroachlabs.com/docs/stable/monitoring-and-alerting.html#events-to-alert-on

It is `monitoring-and-alerting` and it has `events-to-alert-on` part, which is very helpful.

> Most of them are performance metrics

This is question for devs, probably pulsar should expose some health metrics (errors, etc) in addition.

Are there any internal health metrics that can be added?

Any suggestions about `events-to-alert-on`?

___

**Additional context**

**Comment by sijie** [comment]
@ilyam8 the metrics are documented here https://pulsar.apache.org/docs/en/reference-metrics/. the most common metrics to alert on are "message backlog" and "publish latency". 

In case of how to use the metrics to alert, here are some examples (https://streamnative.io/docs/v1.0.0/configure/control-center/alertmanager/#alert-rules). We will try to improve the documentation to add one page to pulsar website.

**Comment by ilyam8** [comment]
Hi @sijie, thx for the links. However all broker alarms looks quite generic. It looks like it is an example how to configure (value X is over 9k) and alarms we need to use, am i wrong?

**Comment by sijie** [comment]
@ilyam8 it is just an example for your reference. For most of the people, they define their alerting rules based on the metrics you can find on https://pulsar.apache.org/docs/en/reference-metrics/. Some people might care about write latency and some people might care about the backlog. 

If you are looking more for failure-rate like metrics, currently only bookkeeper has metrics about "success" and "failures". You can use them to calculate the rate across the cluster. 

For brokers, currently, it doesn't have such metrics. We can look into adding these metrics.

**Comment by Jennifer88huang** [comment]
@sijie Then shall we add [alert example](https://streamnative.io/docs/v1.0.0/configure/control-center/alertmanager/#alert-rules)) or other examples to Pulsar docs?
