### ISSUE TITLE
Provide support to configure different docker images for go, python, java function

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#6520]
Provide support to configure different docker images for go, python, java function

- [ ] java
- [ ] python 
- [ ] go

**Comment by cckellogg** [comment]
This can already be supported by providing your own implementation of this class 

https://github.com/apache/pulsar/blob/master/pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesManifestCustomizer.java
This class allows you to do anything to the function spec so you can set whatever image you want.

**Comment by vitosans** [comment]
Is there any documentation on how to use this? KubernetesManifestCustomizer

**Comment by tisonkun** [comment]
Closed as stale and no one works on it. Please create a new issue if it's still relevant to the maintained versions.
