### ISSUE TITLE
Consume the last N messages from Pulsar

### ISSUE THREAD

**Issue by terrencehan** [apache/pulsar#6523]
In our product, we need to show the last N messages to users. While using Kafka, we could simply pull messages based on Offset.  Is there an equivalent of method or API for Pulsar?

It seems we could only subscribe to a topic and try to move the cursor to some point based on messageId. But it hard to determine which messageId should be used, because messageId is not sequential.

**Comment by codelipenghui** [comment]
Yes, currently only support reset cursor by time or message ID. Maybe it needs to support reset cursor by messages count(e.g. last 100 messages) in Pulsar and since a message can be a batch message. If we want to reset to precise last 100 messages, This can be an expensive operation since the broker needs to get the message metadata and counting the number of messages.

**Comment by jiazhai** [comment]
@terrencehan Regarding MessageId, It could get from the produce.send or consumer.receive.  Maybe reader api is more suitable for this case. 1), set reader init MessageId, 2) read N messages.  the initial messageId maybe similar to the way how you get kafka Offset.

**Comment by adrianog** [comment]
@jiazhai could you possibly expand on how to go about this. I'm not clear from your explanation.

**Comment by lhotari** [comment]
> Is it possible to consume the last N messages in the special case where N is 1? Ie Just consume the last message that was already produced. 

Yes, that is possible.

**Comment by carl297r** [comment]
How? Tried using a Reader with MessageId.latest and it does not send the latest message already produced. It only send the first message published after the creation of the reader.

**Comment by lhotari** [comment]
> How? Tried using a Reader with MessageId.latest and it does not send the latest message already produced. It only send the first message published after the creation of the reader.

There's an open issue. However a workaround exists: https://github.com/apache/pulsar/issues/10483#issuecomment-833293066 . When using a reader you usually also need to configure a rentention policy. The user manual contains details about that.

**Comment by carl297r** [comment]
> > How? Tried using a Reader with MessageId.latest and it does not send the latest message already produced. It only send the first message published after the creation of the reader.
> 
> There's an open issue. However a workaround exists: [#10483 (comment)](https://github.com/apache/pulsar/issues/10483#issuecomment-833293066) . When using a reader you usually also need to configure a rentention policy. The user manual contains details about that.

Thanks. That is the issue we have but the workaround is effective.

**Comment by tisonkun** [comment]
Closed as answered.
