### ISSUE TITLE
Improved feature pulsar-sql

### ISSUE THREAD

**Issue by cmdares** [apache/pulsar#6525]
**Is your feature request related to a problem? Please describe.**
I used to confluent formerly, but now I want to switch to plusar. And found pulsar-sql slightly weak.
**Describe the solution you'd like**
confluent plays an important role in Kafka ecosystem and is highly innovative. In particular, the function of ksql is revolutionary. At present, the function of pulsar SQL is relatively weak. I hope that the pulsar team will carefully study and learn the confluent software, and add the advantages and features to pulsar-sql.
Reference:
https://www.confluent.io/product/ksql/
https://ksqldb.io/

thanks.
regard.

**Comment by sijie** [comment]
@cmdares thank you for your feedback.

**Comment by tisonkun** [comment]
Thanks for your reference!

Although, we almost use issues to track actionable tasks. Open-ended discussions can be posted in the Discussions forum.

Closed.
