### ISSUE TITLE
Having a Key_Shared mode for functions

### ISSUE THREAD

**Issue by geomagilles** [apache/pulsar#6527]
**Is your feature request related to a problem? Please describe.**
As functions can manipulate states, race conditions may occur if multiple instance of the same function are processed in parallel and update state for the same key. 

**Describe the solution you'd like**
having a Key_Shared mode for a function's instances - similar to Key_Shared subscription mode for consumers  - would provide the guarantee that only one function instance would run at any time for a given key

**Describe alternatives you've considered**
Another solution could be to have transactions enabled for states, but i'm not sure it's even possible with BookKeeper.

**Additional context**

**Comment by Lanayx** [comment]
@sijie Hi, is adding key shared mode on the roadmap soon?

**Comment by sijie** [comment]
@Lanayx I think @wolfstudy is picking that up already.

**Comment by wolfstudy** [comment]
Yes, we already support key_shared mode on pulsar functions in #7647.

**Comment by Lanayx** [comment]
That's great news!

**Comment by geomagilles** [comment]
Does it mean this issue should be closed with 2.7? Is there somewhere in the documentation explaining how to use it this feature?

**Comment by wolfstudy** [comment]
> Does it mean this issue should be closed with 2.7? 

Yes, in 2.7.0, we can use this feature. 

>  Is there somewhere in the documentation explaining how to use it this feature?

@sijie It seems that we need to expose the corresponding parameters to users. Currently, when creating pulsar function, `--retain-key-ordering` is not exposed.

**Comment by geomagilles** [comment]
> @sijie It seems that we need to expose the corresponding parameters to users. Currently, when creating pulsar function, `--retain-key-ordering` is not exposed.

Is there a turnaround to be able to use it?
