### ISSUE TITLE
Restrict permission to create new subscription for given role - force role to use existing subscription

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#6530]
We need a way to restrict a role to only be able to use a subscription that has been assigned (i.e. created with a different role.) This feature would be helpful for our CI/CD automation for when we provision a new tenant/namespace for a team. We need to ensure that we know who is using the subscription that we create, so we need to force users on the team to only be able to use the subscription that we have created for them.

The code change would be to allow a role to be restricted from creating new subscriptions. (It also needs to support token auth.)

I'd like some guidance on what classes will need to be modified since I might be able to help with making this code change (if there are no objections to it.)

**Comment by jiazhai** [comment]
There is some permission related discussions in #5720 (related PR #6428), @KannarFr and @zymap are working on it.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
