### ISSUE TITLE
Create Producer and Consumer failed

### ISSUE THREAD

**Issue by zxbfeng** [apache/pulsar#6542]
**Describe the bug**
The consumer subscribes multi topics, and  at the same time  create the correspond producers  
to produce messages, but I got error , and the errors repeated if I restart the server. 

The client received error like this:
"server error: UnknownError: org.apache.pulsar.broker.service.BrokerServiceException$ServiceUnitNotReadyException: Namespace bundle for topic (persistent://mytenants/payCenter/consumeSuccess) not served by this instance. Please redo the lookup. Request is denied: namespace=mytenants/payCenter" 

The server side error log:
Namespace bundle for topic (persistent://mytenants/payCenter/consumeSuccess) not served by this instance. Please redo the lookup. Request is denied: namespace=mytenants/payCenter
**java.util.concurrent.CompletionException:** java.lang.RuntimeException: org.apache.pulsar.broker.service.BrokerServiceException$ServiceUnitNotReadyException: Namespace bundle for topic (persistent://mytenants/payCenter/consumeSuccess) not served by this instance. Please redo the lookup. Request is denied: namespace=mytenants/payCenter

I surppose the error was caused by the concurrent ???

**Comment by jiazhai** [comment]
Thanks @zxbfeng. This looks like a concurrent issue.  Would you like to share your code example for reproducing this ?

**Comment by zxbfeng** [comment]
yes, I used the pure go client, and in order to adapt to the inner load balance system I wrappered it. the wrapper file as below.
[pulsarwrapper.go.txt](https://github.com/apache/pulsar/files/4339053/pulsarwrapper.go.txt)

The Type "SConsumer and SProducer" is the export type, the use of the this type is in a function,like this:
func  consumeMessage() {
       consumer := plusarwrapper.Consuemer(options)  //this function will create a new consumer ervery time 
       msg, err := consumer.Receive(ctx)
       .........
}

and the producer is used like the consumer:
func produceMessage() {
     producer: = pulsarwrapper.Producer(xxxx)
     producer.Send(msg)
}

PS: in the wrapper, the client will be a global, but the producer and consumer will always create a new one when call function "produceMessage and consumeMessage", so I thought this may casuse the problem, but the error not must appear!!!

**Comment by zxbfeng** [comment]
I have forget the defer producer.Close() and  defer consumer.Close().  These sentences have wrote in the real code

**Comment by zxbfeng** [comment]
Maybe the error was caused by "namespace bundle" ?

**Comment by kongh** [comment]
> 

We also encounter the same error, but when a broker's server is restarted.

We are deploying via k8s, and we have k8s with automatic node configuration lift.

We are load balancing the connection via plusar-proxy.

**Comment by tisonkun** [comment]
Close as stale.

Please open a new issue if it's still relevant on maintained versions (ATM it's >= 2.10) with a reproduce.
