### ISSUE TITLE
java-client:2.4.0 consumer seek by time no use, still consume from earliest message

### ISSUE THREAD

**Issue by 18817872594** [apache/pulsar#6556]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by 18817872594** [comment]
Is this problem confirmed？we are waiting to use the feature

**Comment by yjshen** [comment]
Could you please try 2.4.2 to see if the problem exists?

**Comment by 18817872594** [comment]
I use 2.5.0 also find this problem，go lient also have this problem，but fixed several days ago。

**Comment by 18817872594** [comment]
we are waiting for your reply!

**Comment by yjshen** [comment]
> I use 2.5.0 also find this problem，go client also have this problem，but fixed several days ago。

could you please point out the PR that fixes the bug? we are planning the 2.5.1 release, just want to make sure the bug fix included in the new release.

**Comment by 18817872594** [comment]
PR：https://github.com/apache/pulsar-client-go/pull/199

**Comment by yjshen** [comment]
@18817872594 are you passing in a long value representing the time in millis? seems the go pr you mentioned above is just converting time from nano to millis

**Comment by 18817872594** [comment]
Yes，can you reproduce this problem？

**Comment by yjshen** [comment]
I cannot reproduce it. how did you get the time you want ?  from yesterday, you can construct:

```
long current = System.currentMillis();
long fromTime = current - 24 * 60 * 60 * 1000;
```

**Comment by sijie** [comment]
@18817872594 can you show a code example?

**Comment by sijie** [comment]
@18817872594 are the messages produced by pulsar go clients? what version of pulsar go client are you using?

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Go client has been permanently moved to https://github.com/apache/pulsar-client-go. If it's still relevant, please open an issue there.
