### ISSUE TITLE
producer builder  failed to load config

### ISSUE THREAD

**Issue by pierre94** [apache/pulsar#6594]
**Describe the bug**
producer builder  failed to load config into existing configuration data

**To Reproduce**
```java
        PulsarClient client = PulsarClient.builder().serviceUrl(pulsarServiceUrl).build();
        Map<String, Object> config = new HashMap<>();
        config.put("topicName", topic);
        config.put("producerName", "test-producer");
        ProducerBuilderImpl<byte[]> builder = (ProducerBuilderImpl<byte[]>) client.newProducer().loadConf(config);
        Producer<byte[]> producer = builder.create();
        producer.send("test".getBytes());
```
```
Exception in thread "main" java.lang.RuntimeException: Failed to load config into existing configuration data
	at org.apache.pulsar.client.impl.conf.ConfigurationDataUtils.loadData(ConfigurationDataUtils.java:69)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.loadConf(ProducerBuilderImpl.java:112)
```

**Desktop (please complete the following information):**
 - OS: OSX
 - pulsar.version: 2.4.0

**Comment by yjshen** [comment]
Could you please try pulsar client lib 2.4.2?

**Comment by pierre94** [comment]
> Could you please try pulsar client lib 2.4.2?
> 
> I failed with a different failure for 2.4.0 with your program:
> 
> ```
> Caused by: org.apache.pulsar.shade.com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.apache.pulsar.client.impl.DefaultBatcherBuilder
> ```
 pulsar client lib 2.4.2 and 2.5.0 is ok

**Comment by sijie** [comment]
@pierre94 shall I close this issue? since 2.4.2 and 2.5.0 have fixed this issue.

**Comment by pierre94** [comment]
> @pierre94 shall I close this issue? since 2.4.2 and 2.5.0 have fixed this issue.

ok
