### ISSUE TITLE
View the details of the sources command in the pulsar admin cli document and see 404

### ISSUE THREAD

**Issue by apacheBright** [apache/pulsar#6598]
When I want to view the details of the sources command under pulsar admin cli, there is an exception. See the following figure for details
<img width="800" alt="WechatIMG80" src="https://user-images.githubusercontent.com/27547000/77437823-10e9fb80-6e20-11ea-865d-608ee1dee8ea.png">
![WechatIMG81](https://user-images.githubusercontent.com/27547000/77437846-18a9a000-6e20-11ea-8d75-94a118f1e51c.jpeg)

**Comment by sijie** [comment]
@apacheBright we will take a look and fix it. If you want to make a contribution, a pull request would be great!
