### ISSUE TITLE
Can not deploy zookeeper on minikube

### ISSUE THREAD

**Issue by xiangwangcheng** [apache/pulsar#6614]
**Describe the bug**
When I deploy zookeeper on minikube by using
`kubectl apply -f zookeeper.yaml`
It just stuck on `ContainerCreating`.  Half an hour later, the command `kubectl describe pod  zk-0`  showed that it was still pulling images `apachepulsar/pulsar-all:latest`. But I have already pulled this image by using docker pull.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by sijie** [comment]
> But I have already pulled this image by using docker pull.

did you pull the image within Minikube or at your laptop?

**Comment by xiangwangcheng** [comment]
@sijie I pulled the image on my laptop. 

BTW, the dashboarad gives this error: Failed to pull image "apachepulsar/pulsar-all:latest": rpc error: code = Unknown desc = context canceled.

**Comment by sijie** [comment]
@xiangwangcheng 

Minikube is running a vm. so if you pulled the image at your laptop, the image isn't available at minikube. So when you launch the zk pod, it will pull the image again.

**Comment by xiangwangcheng** [comment]
@sijie How can I pull the image within minikube? Seems it can not connect to the docker hub.

**Comment by sijie** [comment]
@xiangwangcheng I am not sure how did you configure minikube. I would recommend you checkout the minikube documentation: https://kubernetes.io/docs/setup/learning-environment/minikube/#using-minikube-with-an-http-proxy

**Comment by sijie** [comment]
@xiangwangcheng were you able to configure minikube to use proxy?

**Comment by xiangwangcheng** [comment]
@sijie No, I configured the proxy according to the doc but still cannot pull any images.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant in maintained versions.
