### ISSUE TITLE
Which falvor should i deploy and tunning parameter

### ISSUE THREAD

**Issue by Shoothzj** [apache/pulsar#6628]
I am testing ten thousands different topic, per topic 100 QPS, every message is 512Byte. When I add to 3_600 topic, my bookkeeper is OOM which reached 2G limit. 

I want to know, my pulsar and bookie deploy on which falvor of ECS, and what paramenter need to change

**Comment by sijie** [comment]
@Shoothzj 

How do you set up the bookie memory settings? It would be good to share more details about your current set up.

I would also suggest checking out the whitepaper written by Penghui and Devin about a deep-dive into Pulsar Architecture for performance tuning - https://streamnative.io/whitepaper/taking-a-deep-dive-into-apache-pulsar-architecture-for-performance-tuning/

**Comment by Shoothzj** [comment]
According to my business, I want to deploy in two mode:
1. 1U4G for both pulsar and bk
2. 4U16G for both pulsar and bk

I test it last week, I only tunning both pulsar and bk, JVM HEAP to 1G, Directory memory to 1G.

Last week, I didn't thinking the memory of rocks DB, and I will  consider this.

Do you think it's okay? Can 1U4G run well?
