### ISSUE TITLE
Why the Bookkeeper crash

### ISSUE THREAD

**Issue by Shoothzj** [apache/pulsar#6629]
I deploy my pulsar and bookeeper on three 24U96G VM.
Each memory config is
  bk: 18G heap 18G directMemory
  pulsar: 18G heap 32G directMemory
[pulsar-bookie-pulsar.log.zip](https://github.com/apache/pulsar/files/4396834/pulsar-bookie-pulsar.log.zip)

When I am testing pulsar's millions topic ability, When I am adding producer and consumer, My bookkeeper process  often crash quit. I don't know how to position problem

**Comment by jiazhai** [comment]
It looks like the [loadbalance](https://pulsar.apache.org/docs/en/administration-load-balance/#load-balance-across-pulsar-brokers) happened a lot for the cluster. When a topic's service transfer from one broker to another, the owner of bookkeeper ledger need change, and will trigger some fence and recover. If topics number is large, it brings pressure to metadata store and disk.

**Comment by jiazhai** [comment]
@Shoothzj  It looks like the [loadbalance](https://pulsar.apache.org/docs/en/administration-load-balance/#load-balance-across-pulsar-brokers) happened a lot for the cluster. When a topic's service transfer from one broker to another, the owner of bookkeeper ledger need change, and will trigger some fence and recover. If topics number is large, it brings pressure to metadata store and disk.
