### ISSUE TITLE
Context in Pulsar functions not getting mocked

### ISSUE THREAD

**Issue by prasanthkumar2392** [apache/pulsar#6642]
**I am trying to write a unit test for Pulsar functions, and if I am unsuccessful in mocking Context class**

**Steps to reproduce the behavior:**

- I am creating a pulsar function which does some processing logic on the messages.

-  I am using Context interface inside the function to get logger, get output topic and newOutputMessage.

While writing unit tests for functions, I am mocking the context as per this example but I land up in facing null pointer exception as Context class is not getting mocked

[http://pulsar.apache.org/docs/ja/2.4.0/functions-debugging/#use-unit-test](url)

**Pulsar functions -2.5.0**

**Comment by jiazhai** [comment]
@prasanthkumar2392 What is your test looks like?

**Comment by prasanthkumar2392** [comment]
Hi, 

- I am using functions api 2.5.0 and I am using context to set the key and value inside functions and sending it to the output topic.

- But in my test class, I am trying to mock the context and i am unsuccesfull.
(Also tried context configuration of puslar test container to see if context is not null)

My function class to process the messages 
` 

import org.apache.pulsar.client.api.PulsarClientException;
import org.apache.pulsar.client.api.Schema;
import org.apache.pulsar.functions.api.Context;
import org.apache.pulsar.functions.api.Function;
import org.slf4j.Logger;


public class MyFunction implements Function<byte[], Void> {

    @Override
    public Void process(byte[] input, Context context) throws Exception {
        Logger log = context.getLogger();
        log.debug("Entered ");
        
        //Initialize Required classes to process message

        if (input != null) {
            try {
                // assign the key and value and send it to output topic
                log.debug("Key  :");
                log.debug("Value ");
                context.newOutputMessage(context.getOutputTopic(), Schema.STRING)
                        .key("")
                        .value("")
                        .send();

            } catch (PulsarClientException e) {
                log.error("error in " + e.toString());
            }
        }
        return null;
    }

}

`


and my sample test class 
`import com.ericsson.iota.dm.function.MyFunction;
import org.apache.pulsar.functions.api.Context;
import org.junit.jupiter.api.Test;

import static org.mockito.Mockito.mock;

public class FunctionTest {


    @Test
    public void functionProcessing() throws Exception {
        String message ="{\n" +
                "   \"name\": \"XXXXX\",\n" +
                "   \"email\": \"xxxxx@xxx.com\"\n" +
                "}";
        MyFunction myFunction =new MyFunction();
        myFunction.process(message.getBytes(), mock(Context.class));
        // Assert conditions
    }
}

`

**Comment by jiazhai** [comment]
@prasanthkumar2392  It looks more like a mock issue. looks like we need to mock the need classes and methods.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
