### ISSUE TITLE
Retention policy should be respected when there is no traffic

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#6655]
*Motivation*

Currently retention is checked when ledger rollover happens. So if the traffic is stopped, the ledgers are not cleaned up even all the messages are already acknowledged. This issue is to follow up with an enhancement to make sure Pulsar respect to retention policy even there is no traffic.

**Comment by 315157973** [comment]
How about this：
in BrokerService, create a new ScheduledExecutorService to regularly trigger "ManagedLedgerImpl#trimConsumedLedgersInBackground" of all topics

**Comment by sijie** [comment]
@315157973 sounds good to me.

**Comment by codelipenghui** [comment]
close via #6676
