### ISSUE TITLE
The mysql jar used by the jdbc connector has an invalid license.

### ISSUE THREAD

**Issue by phijohns-tibco** [apache/pulsar#6656]
**Describe the bug**
In 2.5.0 release the jdbc connector packages mysql-connector-java:jar:8.0.11. This jar has no valid license. It is GPLV2 with a deprecated FOSS exception

Because this FOSS exception no longer exists, the license is rendered invalid.

**Comment by tisonkun** [comment]
Resolved by https://github.com/apache/pulsar/pull/6835
