### ISSUE TITLE
Add AuthorizationProvider that support a list of AuthorizationProviders.

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#6658]
**Is your feature request related to a problem? Please describe.**
We are developping a custom authz provider and we don't want breaking changes on current authz usages.

**Describe the solution you'd like**
Write a meta AuthorizationProvider that support a list of AuthorizationProviders.

**Comment by KannarFr** [comment]
You can assign it to myself :).

**Comment by KannarFr** [comment]
Finally, the goal is not a support multiple authz provider, but create an authz provider that supports others.

**Comment by KannarFr** [comment]
You can unassign this for now.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
