### ISSUE TITLE
Non-printable characters in subscription name

### ISSUE THREAD

**Issue by wmccarley** [apache/pulsar#6672]
**Describe the bug**
One of my teammates, let's call them SAM managed to create the following subscription in a production environment:

```
"SAM-LoadTEST\b\b\b\b\u001B[D" : {
      "msgRateOut" : 0.0,
      "msgThroughputOut" : 0.0,
      "msgRateRedeliver" : 0.0,
      "msgBacklog" : 14856045,
      "blockedSubscriptionOnUnackedMsgs" : false,
      "msgDelayed" : 0,
      "unackedMessages" : 0,
      "msgRateExpired" : 0.0,
      "consumers" : [ ],
      "isReplicated" : false
    }
```

I am working under the assumption that the actual subscription name in zookeeper is a UTF8 encoded string that has backspaces and an ANSI terminal code in it since I can't delete it by that exact name as displayed.

I have two questions:

1) Does anyone have any good theories on how a subscription (or a topic/namespace for that matter) could be created like this? SAM doesn't remember exactly how they did. I'm guessing it involves copying something out of a xterm window and pasting into a java program and running it but I'm curious on if anyone has other theories.

2) Any suggestions on how to delete the subscription that do not involve:

- deleting the topic
- manually logging into zookeeper or
- modifying subscriptionExpirationTimeMinutes (it's currently set to zero)

PS already tried deleting through the pulsar CLI using bash terminal and passing:
"SAM-LoadTEST\b\b\b\b\u001B[D"
'SAM-LoadTEST\b\b\b\b\u001B[D' and
$'SAM-LoadTEST\b\b\b\b\u001B[D'

**Comment by sijie** [comment]
@wmccarley 

You can use `zookeeper-shell` to connect to zookeeper and check what subscription was created. Once you connect to zookeeper using `zookeeper-shell`, you can use the following command to list the subscriptions.

```
ls /managed-ledgers/<tenant>/<namespace>/persistent/<topic>
```

If you find the actual subscription name, you can run `rmr /managed-ledgers/<tenant>/<namespace>/persistent/<topic>/<sub>` to delete the malformed subscription.

**Comment by sijie** [comment]
Regarding your first question - "Does anyone have any good theories on how a subscription (or a topic/namespace for that matter) could be created like this? "

I am guessing the error was introduced when using some command-line tools.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
