### ISSUE TITLE
Kafka Source Connector in pulsar cluster

### ISSUE THREAD

**Issue by Esakkimuthu991** [apache/pulsar#6675]
**Describe the bug**
Exception in kafka source connector in pulsar cluster function worker

**To Reproduce**
1. Run Pulsar Cluster - one zookeeper, one broker and three bookie
2. Ensure Function worker enabled
3. Create Source for kafka
4. Running kafka container and produce message to it.
5. No Exception thrown instead getting hanged . while checking logs no more meaningful errors

**Expected behavior**
Running Kafka Source Connector through function worker mode in pulsar cluster

**Screenshots**
![image](https://user-images.githubusercontent.com/43499028/78557506-8a291b80-782e-11ea-8060-a7a4c0321d36.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by sijie** [comment]
@Esakkimuthu991 

What version of the Kafka cluster are you running? What version of Pulsar are you using?

**Comment by Esakkimuthu991** [comment]
> @Esakkimuthu991
> 
> What version of the Kafka cluster are you running? What version of Pulsar are you using?

pulsar image - apachepulsar/pulsar-test-latest-version:latest

kafka image - spotify/kafka:latest

**Comment by sijie** [comment]
There are a couple of things to check:

1) I am not sure what version of Kafka is spotify/kafka. I think the Kafka connector is using Kafka version 0.10.2.1. You need to make sure your Kafka cluster for testing is compatible with this version.

2) how do you configure `bootstrapServers` in the Kafka source connector? Is it reachable in pulsar cluster?

**Comment by Esakkimuthu991** [comment]
> There are a couple of things to check:
> 
> 1. I am not sure what version of Kafka is spotify/kafka. I think the Kafka connector is using Kafka version 0.10.2.1. You need to make sure your Kafka cluster for testing is compatible with this version.
> 2. how do you configure `bootstrapServers` in the Kafka source connector? Is it reachable in pulsar cluster?

Earlier I tried the same spotify/kafka with pulsar standalone mode . Its supporting and source connector working fine.

Do we have docker compose file for pulsar cluster running with pulsar 2.5.0 image?

**Comment by sijie** [comment]
@Esakkimuthu991 you can use this docker-compose file for reference. https://github.com/apache/pulsar/blob/master/docker-compose/standalone-dashboard/docker-compose.yml


I think the important thing is to make sure your function worker is able to connect to your Kafka cluster.

**Comment by Esakkimuthu991** [comment]
> @Esakkimuthu991 you can use this docker-compose file for reference. https://github.com/apache/pulsar/blob/master/docker-compose/standalone-dashboard/docker-compose.yml
> 
> I think the important thing is to make sure your function worker is able to connect to your Kafka cluster.

I've already tried with standalone mode pulsar and it is working

**Comment by Esakkimuthu991** [comment]
Trying to run it on pulsar cluster mode . So it would be helpful if sharing any reference for pulsar cluster 2.5.0

**Comment by sijie** [comment]
@Esakkimuthu991 do you mean a docker-compose file for cluster setup?

For step-by-step instruction on setting up a cluster using docker, you can check out this demo:

https://github.com/streamnative/tgip/blob/master/episodes/001/demo.md

I walk through it in this TGIP video: https://www.youtube.com/watch?v=1RQSot5tTuU

Hope this is useful for you.

**Comment by Esakkimuthu991** [comment]
> @Esakkimuthu991 do you mean a docker-compose file for cluster setup?
> 
> For step-by-step instruction on setting up a cluster using docker, you can check out this demo:
> 
> https://github.com/streamnative/tgip/blob/master/episodes/001/demo.md
> 
> I walk through it in this TGIP video: https://www.youtube.com/watch?v=1RQSot5tTuU
> 
> Hope this is useful for you.

Thanks for the link provided

**Comment by sijie** [comment]
@Esakkimuthu991 I am assuming you have gotten the information you need. I am closing this issue now. If you need any more help, feel free to leave a comment and reopen this issue.
