### ISSUE TITLE
Kafka integration Pulsar Schema Registry

### ISSUE THREAD

**Issue by smeadows-abb** [apache/pulsar#6677]
**Describe the bug**
I'm interested in integrating Pulsar Schema Registry with Kafka (documentation, example, howtos) and/or whether Pulsar schema registry will provide support for Golang client (possibly dates).

**Comment by sijie** [comment]
@smeadows-abb thank you for raising this feature request! Do you mean using "Pulsar Schema Registry" for Kafka? Can you explain more about your use cases?

> whether Pulsar schema registry will provide support for Golang client

The c-go pulsar client already supports schema. The native go client [pulsar-client-go](https://github.com/apache/pulsar-client-go) doesn't support schema yet. But it is in the roadmap. Hopefully, we can get that out in next native go client release.

**Comment by smeadows-abb** [comment]
My management selected Kafka, I wanted Pulsar. So, I’m stuck with Kafka for messaging. I need Pulsar Schema Registry (it supports every format I need). I need to know how to integrate the product with Kafka as a Schema Registry?

**Comment by sijie** [comment]
@smeadows-abb I see. Currently, the Pulsar schema registry wasn't exposed as a standalone service yet. If you want to use it, you can still use it. 

You can use the schema restful API to create/retrieve/update the schema: http://pulsar.apache.org/admin-rest-api/?version=2.5.0#operation/postSchema

What you need is just write a Kafka serializer and deserializer to use Pulsar schema library. We did a similar thing that wraps Kafka serializer and deserializer into a Pulsar schema. You just need to do the reverse thing - wrap Pulsar schema into Kafka serializer and deserializer.

I am attaching one example for your reference - https://github.com/apache/pulsar/blob/master/pulsar-client-kafka-compat/pulsar-client-kafka/src/main/java/org/apache/pulsar/client/kafka/compat/PulsarKafkaSchema.java

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
