### ISSUE TITLE
got `null` pointerException when use --window-length-duration-ms

### ISSUE THREAD

**Issue by bback99** [apache/pulsar#6678]
**Describe the bug**

I'd like to implement pulsar functions with **--window-length-duration-ms**
realized only the class that inherited from `java.util.function.Function` class can do.

However, other function that inherited from this 
org.apache.pulsar.functions.api.WindowFunction
throws exception 
_Function class org.apache.pulsar.functions.api.examples.ContextWindowFunction does not implement the correct interface_

other function that inherited from this 
org.apache.pulsar.functions.api.Function
throws exception 
_Exception in thread "main" java.lang.NullPointerException_

Is there any specific reason why those two functions are not supported **windowing** feature?
or
if should work properly, can I find out any better examples with command line?

**To Reproduce**
1. go to org.apache.pulsar.functions.api.examples.ContextWindowFunction in pulsar-function and run with --window-length-duration-ms 6000
or 
go to org.apache.pulsar.functions.api.examples.CustomDerivedToBaseFunction in pulsar-function and run with --window-length-duration-ms 6000

**Comment by qmnonic** [comment]
Fix here?  https://github.com/apache/pulsar/pull/6246

**Comment by jiazhai** [comment]
@qmnonic Thanks for the information. @bback99  which version of Pulsar are you using?

**Comment by bback99** [comment]
I am using 2.4.1.
also tested in 2.5.0, but the same error.

**Comment by qmnonic** [comment]
Looks like it was introduced in 2.4.1, by this PR - https://github.com/apache/pulsar/pull/4844

**Comment by wolfstudy** [comment]
@qmnonic @bback99 Thanks feedback, The issue has been fixed in #6246, this change will be built in 2.6.0.

**Comment by qmnonic** [comment]
@wolfstudy https://github.com/apache/pulsar/pull/6246 appears to be in 2.5.1 , so it's in the release candidate now.

**Comment by wolfstudy** [comment]
> @wolfstudy #6246 appears to be in 2.5.1 , so it's in the release candidate now.

The #6246 will be cherry-pick to 2.5.1, when pulsar 2.5.1 is released, the issue will be fixed. And @tuteng is working this.

**Comment by tisonkun** [comment]
Close as fixed.
