### ISSUE TITLE
[v2.5.0]memory leak during offload to tiered storage

### ISSUE THREAD

**Issue by pheecian** [apache/pulsar#6692]
**Describe the bug**
the feature of "offload to tiered storage" cause severe memory leak and finally shut down the broker due to OOM
**To Reproduce**
setup a simple pulsar deployment with zookeeper, bookie, and broker.
produce message to topic continuously
enable auto-offload by setting  --size-threshold 10M (driver = filesystem)
and the offload works indeed but the memory consumed by broker goes up up and up  
**Expected behavior**
no memory leak
**Screenshots**
<img width="1429" alt="Screen Shot 2020-04-08 at 3 53 24 PM" src="https://user-images.githubusercontent.com/8122303/78758731-2bd87600-79b1-11ea-874b-7e0ce686c479.png">

**Desktop (please complete the following information):**
linux 

**Additional context**
FYI, if disable the aotu-offload, the broker works fine. Once enable "offload", broker will shut down due to OOM

**Comment by pheecian** [comment]
@sijie Please Help

**Comment by codelipenghui** [comment]
@congbobo184 Looks related to the HDFS offloader, could you please help take a look?

**Comment by pheecian** [comment]
@congbobo184 I commented #6697 , Please Read it. Thanks
