### ISSUE TITLE
unsubscribe option for pulsar-client cli

### ISSUE THREAD

**Issue by sbourkeostk** [apache/pulsar#6709]
**Is your feature request related to a problem? Please describe.**
After running `pulsar-client consume` the subscription is kept active and it is not possible to unsubscribe without using the admin interface.

**Describe the solution you'd like**
The option to unsubscribe after consuming. eg:
pulsar-client consume -s testsub --unsubscribe persistent://my/pulsar/topic

**Describe alternatives you've considered**
Using pulsar-admin it's possible to unsubscribe but this requires the user has access to the admin interface.

**Additional context**
none

**Comment by 315157973** [comment]
you can assigne it to me :) @sijie

**Comment by sijie** [comment]
@315157973 since you are not part of ASF org, I am not able to assign it to you in Github. In general, you can leave a message here when you start working on it.

**Comment by sijie** [comment]
@315157973 I don't think we need additional command to do that.

@sbourkeostk  You can use `topics unsubscribe` to unsubscribe a subscription.

```
bin/pulsar-admin topics unsubscribe
The following option is required: -s, --subscription

Delete a durable subscriber from a topic.
		The subscription cannot be deleted if there are any active consumers attached to it

Usage: unsubscribe [options] persistent://tenant/namespace/topic
  Options:
  * -s, --subscription
       Subscription to be deleted
```

**Comment by sijie** [comment]
Closed this issue since we don't need to add `unsubscribe` command to pulsar-client.

**Comment by sbourkeostk** [comment]
@sijie Yes, you can unsubscribe using the admin interface but that is not the same thing. Allowing the CLI client to unsubscribe itself has two main advantages:

1. Users without access to the admin interface can unsubscribe
2. Convenience - I suspect that a lot of users use `pulsar-client consume` to check that messages are flowing on a topic and they do not intend the subscription to persist. On our Pulsar test cluster we often see backlogs on subscriptions that were started with the CLI and the user neglected to unsubscribe.

Going further, I think it would be good practice to the CLI unsubscribe be default with an option to persist the subscription.

I know this would not be high priority but would you be opposed to a pull request for this feature if @315157973 or myself were willing to implement it?

**Comment by fmiguelez** [comment]
This is a serious limitation. 

If you use short-lived subscriptions clients can create new subscriptions which takes up resources. Those resources that are no longer necessary once the client is gone can only be taken back by an administrator. 

We have not many options until NonDurable subscriptions work as expected (e.g. BUG #7619)

**Comment by sijie** [comment]
@sbourkeostk @fmiguelez 

Just to be clear here, the "unsubscribe" operation is supported in Pulsar RESTful admin API. You can call the RESTful API directly or use `pulsar-admin` to unsubscribe a subscription. With that being said, both tools and API are available for you to use.

More specifically, `pulsar-admin` and `pulsar-client` are shipped together as part of the Pulsar binary release. You can get both of the tools out of the box. I don't see the case that users would have access to `pulsar-client` tool but not `pulsar-admin` tool. Step back, even we can add a new command in `pulsar-client`. The `unsubscribe` command will still be protected by access control. You need permissions to call this API no matter the command is in `pulsar-client` or `pulsar-admin`. Hope this clarifies your question on "Users without access to the admin interface can unsubscribe".

> check that messages are flowing on a topic and they do not intend the subscription to persist. On our Pulsar test cluster we often see backlogs on subscriptions that were started with the CLI and the user neglected to unsubscribe.

If you are talking about adding a non-durable subscription option to `client consume` command, I think that's a good idea to me.

**Comment by sbourkeostk** [comment]
Hi @sijie
Yeah, it's clear that the pulsar-admin can be used to unsubscribe - that fact was acknowledged in the original post. The issue is on the usability of pulsar-client. This is a nice simple useful tool but the fact that it is not capable of cleaning up after itself is very odd to me.
I think the main use of this tool is for testing producing and consuming to a topic:

1. Produce:
 `pulsar-client produce -m HiThere persistent://a/b/c `
2. Consume:
 `pulsar-client consume -s s1 persistent://a/b/c`
 `pulsar-admin topics unsubscribe -s s1 persistent://a/b/c`

Why is use case 2 a two-step process and why is a second tool required to clean up?  I would suggest that the default behaviour be that the subscription does not persist but at the very least there should be a `-u`, `--unsubscribe` option so that the use of pulsar-admin is not required after **every** use of `pulsar-client consume`. 

Of course, setting up a subscription is also a valid use case but I would think it's probably much less common than the above.

And sure, it's possible to do the job with the existing tools, it's just inconvenient and non-intuitive - the issue was put in as a feature request not a bug.

**Comment by sijie** [comment]
@sbourkeostk I was under the impression that you are suggesting introducing a "unsubscribe" command in pulsar-client CLI. 

In my previous comment, I am fine with adding an option to `pulsar-client consume`. Although I don't suggest adding `--unsubscribe` option, instead we should just add an option to use a non-durable subscription. So the subscription will be automatically deleted after the command exits.

**Comment by sbourkeostk** [comment]
@sijie sounds great - I was not aware of non-durable subscriptions until this discussion today.
