### ISSUE TITLE
Redelivery count is not getting updated for negatively acknowledged messages.

### ISSUE THREAD

**Issue by pradeep00m** [apache/pulsar#6721]
#### Expected behavior
Whenever I negatively acknowledge a message, the message should be redelivered with its redelivery count incremented by 1.
#### Actual behavior
The redelivery_count is not getting incremented.
#### Steps to reproduce

Step 0: Create a pulsar topic
Step 1: Produce a message to the topic.
Step 2: create a consumer and negatively acknowledge the message
Step 3: After negative_acknowldegment time out(deafult=60sec) consume the message again, you will receive the same message. But it's `redelivery_count` is not updated. It showing as 0.
No matter how many times I negatively acknowledge the message. Its redelovery count is not getting updated.

#### System configuration
OS: ubuntu 18.04.1 LTS
I'm running pulsar in a container.

**Pulsar version**: 2.5.0
I'm using pulsar-client in python
Version: 2.5.0

**Comment by sijie** [comment]
@pradeep00m The `redelivery_count` is currently used by DeadLetterTopic. It is only enabled for `shared` subscription. Are you testing this using `shared` subscription or other subscription types?

**Comment by pradeep00m** [comment]
I'm testing it on a `Exclusive` subscription. Yeah, its working on `shared`, is there anyway I can use `redelivery_count` in `exclusive` subscription.

**Comment by sijie** [comment]
@pradeep00m - I think there is a reason why `redelivery_count` was not enabled for a non-shared subscription. @codelipenghui can you chime in here?

**Comment by codelipenghui** [comment]
> I'm testing it on a Exclusive subscription. Yeah, its working on shared, is there anyway I can use redelivery_count in exclusive subscription.

**Comment by pradeep00m** [comment]
We don't have to do this specifically in Exclusive subscription. Shared subscription also works for us. I was just wondering why it wasn't working for the Exclusive subscription. That's all.
Thanks.

**Comment by sijie** [comment]
@pradeep00m I see. thank you
