### ISSUE TITLE
Errors in baremetal cluster configuration

### ISSUE THREAD

**Issue by kitekite2020** [apache/pulsar#6723]
Cannot get cluster list after initializing cluster metadata. Error message is
Reason: javax.ws.rs.ProcessingException: Connection refused: localhost/127.0.0.1:8080
Start bookie. Got error message:
[main] ERROR org.apache.bookkeeper.discover.ZKRegistrationManager - BookKeeper metadata doesn't exist in zookeeper. Has the cluster been initialized? Try running bin/bookkeeper shell metaformat

## Steps to reproduce
I was deploying a multi-cluster on bare metal following instructions from PULSAR 2.5.0. 
I configured a cluster with 3 nodes of zookeeper. Each node is hosted in a Ubuntu VM.
For each node, 
$ vi conf/zookeeper.conf 
#insert ZooKeeper cluster servers
server.1=10.0.1.50:2888:3888
server.2=10.0.1.51:2888:3888
server.3=10.0.1.52:2888:3888

For zk1, 
$ mkdir -p data/zookeeper
$ echo 1 > data/zookeeper/myid
For zk2,
$ mkdir -p data/zookeeper
$ echo 2 > data/zookeeper/myid
For zk3,
$ mkdir -p data/zookeeper
$ echo 3 > data/zookeeper/myid
Then I can start 3 zookeeper successfully.  
$ bin/pulsar initialize-cluster-metadata --cluster my-cluster --zookeeper 10.0.1.50:2181 --configuration-store 10.0.1.50:2181 --web-service-url http://10.0.1.60:8080,10.0.1.61:8080,10.0.1.62:8080 --broker-service-url pulsar://10.0.1.60:6650,10.0.1.61:6650,10.0.1.62:6650
The ouput log says the cluster is initialized successfully. 
$ bin/pulsar-admin clusters list
I tried to get the cluster list and got the error message above. I tried a few times on other VMs and there is same errors.  Not sure if this is expected behavior.

I followed the instructions to continue to configure Bookies on another 3 Ubuntu VMs. I planned to deploy bookie and broker on same VM. 
$ vi conf/bookkeeper.conf 
zkServers=10.0.1.50:2181,10.0.1.51:2181,10.0.1.52:2181
advertisedAddress=10.0.1.60
When starting bookie, got error message as below. So i think I might get something wrong in zookeeper. 
[main] ERROR org.apache.bookkeeper.discover.ZKRegistrationManager - BookKeeper metadata doesn't exist in zookeeper. Has the cluster been initialized? Try running bin/bookkeeper shell metaformat.

I followed suggested command,bin/bookkeeper shell metaformat. After that, bookie can start and can do bookiesantiy and simplestest test successfully. But I wonder if I did something wrong because later when I did test with broker failover, I got random errors when sending messages and killing one broker. 
Edit file conf/broker.conf
zookeeperServers=10.0.1.50:2181,10.0.1.51:2181,10.0.1.52:2181
configurationStoreServers=10.0.1.50:2181,10.0.1.51:2181,10.0.1.52:2181
advertisedAddress=10.0.1.60 /*ip of the machine */
clusterName=my-cluster
brokerDeduplicationEnabled=true

Brokers can run successfully and I can send and receive messages. But when i did availability test, sending/receiving messages and killing one broker, I got passed and failed test cases. In failed cases, producer and subscriber tried to rebuilt connections and always got refused. 

#### System configuration
**Pulsar version**: 2.5.0
Ubuntu 18.04

**Comment by sijie** [comment]
```
$ bin/pulsar-admin clusters list
I tried to get the cluster list and got the error message above. I tried a few times on other VMs and there is same errors. Not sure if this is expected behavior.
```

This indicates that the cluster initialization you run before didn't succeed. Can you double check if the cluster initialize completed successfully.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant in maintained versions.
