### ISSUE TITLE
Compile client failed with container

### ISSUE THREAD

**Issue by wenxuwan** [apache/pulsar#6724]
**Describe the bug**
When i try to compile client with container,  it failed with link error.

/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-CentOS-linux/4.8.2/ld: /usr/local/lib/libsnappy.a(snappy.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC

In the container, i find the snappy compiled with  CFLAGS="-fPIC -O3" .
# Snappy
RUN curl -O -L https://github.com/google/snappy/releases/download/1.1.3/snappy-1.1.3.tar.gz && \
    tar xvfz snappy-1.1.3.tar.gz && \
    cd snappy-1.1.3 && \
    CFLAGS="-fPIC -O3" ./configure && \
    make && make install && \
    rm -rf /snappy-1.1.3 /snappy-1.1.3.tar.gz

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by wenxuwan** [comment]
Hi, for snappy the flag should be CXXFLAGS="-fPIC -O3"  instead of  CFLAGS="-fPIC -O3".After replacement, the compilation is normal

**Comment by sijie** [comment]
@wenxuwan so the problem is not a pulsar issue, correct?

**Comment by wenxuwan** [comment]
> @wenxuwan so the problem is not a pulsar issue, correct?

No, the dockerFile is pulsar's file.  So the problem is pulsar issue.

**Comment by wenxuwan** [comment]
you can refer https://github.com/apache/pulsar/compare/master...wenxuwan:master?diff=unified#diff-7e19b76e860cce6cafee3c3707d04659

**Comment by sijie** [comment]
@wenxuwan I see. Do you want to submit a pull request for this issue?

**Comment by jiazhai** [comment]
Thanks @wenxuwan for the help.

**Comment by jiazhai** [comment]
@wenxuwan Would you provide more details of how to reproduce it? 
This Dockerfile that you changed in PR #6736 is called by the shell scripts in that dir:
e.g. /pulsar/pulsar-client-cpp/docker/build-wheel-file-within-docker.sh

**Comment by wenxuwan** [comment]
> @wenxuwan Would you provide more details of how to reproduce it?
> This Dockerfile that you changed in PR #6736 is called by the shell scripts in that dir:
> e.g. /pulsar/pulsar-client-cpp/docker/create-images.sh

1. cd /pulsar/pulsar-client-cpp/docker/
2.docker build --build-arg PYTHON_VERSION=3.7 --build-arg PYTHON_SPEC=cp37-cp37m . 
3.start container and login
4.run build-wheel-file-within-docker.sh 
5. when finish compile and link .so file, you will meet the error:

[ 90%] Built target pulsarStatic
[ 90%] Linking CXX shared library _pulsar.so
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-CentOS-linux/4.8.2/ld: /usr/local/lib/libsnappy.a(snappy.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libsnappy.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [python/_pulsar.so] Error 1
make[1]: *** [python/CMakeFiles/_pulsar.dir/all] Error 2

**Comment by jiazhai** [comment]
Thanks @wenxuwan for the details.

**Comment by sijie** [comment]
I think #6741 has fixed this issue.
