### ISSUE TITLE
`pulsar.broker-service-url` is misleading in presto configuration

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#6748]
*Motivation*

`pulsar.broker-service-url` in presto configuration is misleading. The name seems to indicate that you should use a broker service URL. But actually it is expecting the admin/HTTP service URL. So it is better to add a new `pulsar.admin-service-url` to replace this `pulsar.broker-service-url` setting.

At least, we need to document this setting.

**Comment by eaba** [comment]
Yes, truly it is misleading!
I had to look up several examples to understand how to set it!

**Comment by sijie** [comment]
@eaba are you interested in sending out a pull request for fixing it?

**Comment by eaba** [comment]
`pulsar.web-service-url` should be better? `admin-service-url` sounds like a new term.
It is documented that `broker-service-url` is `6650` binary and `web-service-url` is `8080` web.

**Comment by ADHB** [comment]
pulsar.web-service-url will centainly fit better :)
