### ISSUE TITLE
go client: message ID serialization / deserialization does not work with multi-topic consumers

### ISSUE THREAD

**Issue by bschofield** [apache/pulsar#6785]
As noted in [this comment](https://github.com/apache/pulsar/issues/3177#issuecomment-471866729), go code like this can cause a panic:

```golang
id := msg.ID().Serialize()
idParsed := pulsar.DeserializeMessageID(id)
err := consumer.AckID(idParsed)
```

For me, the crash occurs in `pulsar-client-cpp/lib/MultiTopicsConsumerImpl.cc`, here:

```c++
const std::string& topicPartitionName = msgId.getTopicName();
std::map<std::string, ConsumerImplPtr>::iterator iterator = consumers_.find(topicPartitionName);
```

If we look at the definition of a `MessageId` in `pulsar-client-cpp/lib/MessageIdImpl.h`, we see that it contains four ints (`partition`, `ledgerId`, `entryId`, `batchIndex`) **and a private topic name**.

When the go function `msg.ID().Serialize()` is called, it only stores the ints, not the topic name. Then, `pulsar.DeserializeMessageID(id)` only restores the ints, not the topic name. When the C++ code tries to ack a message ID constructed in this way, it crashes because the topic name is missing from the `MessageId` struct, so the _std::map_ lookup fails.

This bug does not occur if we call `consumer.AckID(msg.ID())` directly on a `msg` returned from a consumer, because in that case the corresponding C++ `MessageId` _does_ have the topic name populated. It only occurs if we try to serialize and deserialize the ID.

~This would not be a problem for me if I could store the `pulsar.MessageID` obtained by calling `msg.ID()` directly. Unfortunately, if I try to store these values for any significant period of time, the C++ library seems to modify their values under the hood (not unexpected, because they are just wrappers around pointers). Without the ability to correctly serialize and deserialize message IDs, it seems impossible for me to ack long-running tasks.~

**Comment by bschofield** [comment]
I rescind the last paragraph -- that was a bug in my code :sob:. So this bug still exists, but it is (probably) less critical.

**Comment by zyllt** [comment]
java client has same problem.

**Comment by codelipenghui** [comment]
/cc @wolfstudy please help take a look at this issue.
@zyllt Could you please help provides a Java demo since someone wants to fix this problem but not familiar with Go.

**Comment by bschofield** [comment]
@codelipenghui I'm familiar with go, C and C++ and could fix the go API and/or the C code under `pulsar-client-cpp/lib/c`. The thing I don't understand is _how_ you want this fixed. Should the topic name be serialized into some kind of a packed value along with the ints, or should it be kept separate?

**Comment by sijie** [comment]
@codelipenghui can you point @bschofield how it was done in Java client?

**Comment by zyllt** [comment]
Use the following code to reproduce the problem:
```
public static void main(String[] args) throws PulsarClientException {
        PulsarClient client = getPulsarClient();
        String subName = "sub-1";
        String topicName = "persistent://public/default/topic";
        Consumer<String> consumer1 = null;
        try {
            consumer1 = client.newConsumer(Schema.STRING).topic(topicName + "1", topicName + "2").consumerName("c-1")
                    .subscriptionName(subName)
                    .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
                    .messageListener((consumer, msg) -> {
                        try {
                            String hexString = Hex.encodeHexString(msg.getMessageId().toByteArray());
                            MessageId messageId = MessageId.fromByteArrayWithTopic(Hex.decodeHex(hexString.toCharArray()), msg.getTopicName());
                            consumer.acknowledge(messageId);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    })
                    .subscribe();
            System.out.println("consumer1 start!");
        } catch (PulsarClientException e) {
            e.printStackTrace();
        }

    }
```

the exception:
```
java.lang.IllegalArgumentException
	at org.apache.pulsar.shade.com.google.common.base.Preconditions.checkArgument(Preconditions.java:127)
	at org.apache.pulsar.client.impl.MultiTopicsConsumerImpl.doAcknowledge(MultiTopicsConsumerImpl.java:450)
	at org.apache.pulsar.client.impl.ConsumerBase.doAcknowledgeWithTxn(ConsumerBase.java:294)
	at org.apache.pulsar.client.impl.ConsumerBase.acknowledgeAsync(ConsumerBase.java:262)
	at org.apache.pulsar.client.impl.ConsumerBase.acknowledgeAsync(ConsumerBase.java:250)
	at org.apache.pulsar.client.impl.ConsumerBase.acknowledge(ConsumerBase.java:187)
```

The reason for this bug is:
1.`MultiTopicsConsumerImpl#doAcknowledge` requires  a `MessageId` of type `TopicMessageIdImpl`.
https://github.com/apache/pulsar/blob/c36170c3acc0bd432036baf7d9471a4c34320395/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java#L449
2.when the topics in `MultiTopicsConsumerImpl#topics` is non-partitioned-topic,`MessageId#fromByteArrayWithTopic`can only get `BatchMessageIdImpl` or `MessageIdImpl`
https://github.com/apache/pulsar/blob/c36170c3acc0bd432036baf7d9471a4c34320395/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdImpl.java#L140

**Comment by zyllt** [comment]
In addition, I would like to make a suggestion.
 If the topic is a partitioned-topic, the `Message#getTopicName` API  get the name of the partitioned topic. Is it possible to provide an API to get the original topic name. Because when the partition topic and non-partition topic exist in MultiTopicConsumerImpl at the same time, if you want to obtain the original topicName, you can only manually handle the partition suffix of `Message#getTopicName`.

**Comment by codelipenghui** [comment]
@zyllt Thanks for your feedback, It looks this is obvious bug of method `public static MessageId fromByteArrayWithTopic(byte[] data, TopicName topicName)`. 

> In addition, I would like to make a suggestion.
If the topic is a partitioned-topic, the Message#getTopicName API get the name of the partitioned topic. Is it possible to provide an API to get the original topic name. Because when the partition topic and non-partition topic exist in MultiTopicConsumerImpl at the same time, if you want to obtain the original topicName, you can only manually handle the partition suffix of Message#getTopicName.

You can use `TopicName.get(message.getTopicName).getPartitionedTopicName()`. I have no objection to add a method to get partitioned topic name in the `Message`.

Are you interested in pushing a PR for the issue?

**Comment by bschofield** [comment]
These are not quite the same bug. The problem with the go/C client is that there is no way to set the topic name in a message ID, whereas the problem with the Java library is that the method exists but doesn't work. The two bugs should probably be tracked separately.

For the go/C client, it's a little more complicated than I thought because the C++ `MessageId` type only keeps a reference to the topic name, not the actual topic name. So I think the right way to solve this is to extend out the go struct to include both the message ID pointer, and a C string containing the topic name. That's more work than I thought so I might not get to it, but I'll take a look if I have chance.

**Comment by BewareMyPower** [comment]
It's the flaw of C wrapper. C++ `MessageId` provide `setTopicName()` / `getTopicName()` methods, but the C wrapper doesn't have similar functions like:

```c
void pulsar_message_set_topic_name(pulsar_message_id_t *messageId, const char* topicName);
char* pulsar_message_get_topic_name(pulsar_message_id_t *messageId);
```

**Comment by bschofield** [comment]
Yes. I tried adding those functions to the C wrapper but I got stuck because `MessageId` takes a `std::string&` and there's no `std::string` in C, so nothing to take a reference of.

I guess I could add some C wrapper functions that do `new std::string()` and `delete` but that feels a little weird.

**Comment by BewareMyPower** [comment]
The C wrapper of `MessageId` has a `MessageId` field:

```c++
struct _pulsar_message_id {
    pulsar::MessageId messageId;
};
```

And you can convert `std::string` to c-style string by:

```c++
char* string_to_raw_c_string(const std::string& s) {
  char* c_str = static_cast<char*>(malloc(s.size() + 1));
  memcpy(c_str, s.c_str(), s.size() + 1);  // C++11 ensures that std::string has a '\0' terminator
  return c_str;
}
```

So you can implement the C functions like following code:

```c++
void pulsar_message_set_topic_name(pulsar_message_id_t *messageId, const char* topicName) {
    messageId->messageId->setTopicName(topicName);
}

char* pulsar_message_get_topic_name(pulsar_message_id_t *messageId) {
    return string_to_raw_c_string(messageId->messageId->getTopicName());
}
```

Remind that the return value of `char*` must be freed. And use `PULSAR_PUBLIC` to expose these C functions. I'm not familiar with cgo (we use SWIG to wrap C++ client), it seems that it's convenient to convert between `char*` and go string in cgo.

**Comment by bschofield** [comment]
Take a look at the internals of the `MessageId` class. It keeps a reference to a `std::string`. That means that to set a topic name, a `std::string` has to exist somewhere in memory. You can't just create a `std::string` inside the C wrapper function, because when it goes out of scope the destructor gets called. What is your proposed solution to this?

**Comment by BewareMyPower** [comment]
You're right. I think the the internal `const std::string*` of `MessageImpl` could be changed to `const char*`. Then the relative getter / setter should be reimplemented.

**Comment by bschofield** [comment]
That would be great. Otherwise I think we would have to do something like this:

```C++

const void *pulsar_message_id_set_topic(pulsar_message_id_t *messageId, const char *topic) {
    std::string *p = new std::string(topic);
    messageId->messageId.setTopicName(*p);
    return (void *)p;
}

void pulsar_message_id_free_topic(void *p) {
   delete (std::string *)p;
}
```

...but that seems horrible. I like your solution much better.

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Go client has been permanently moved to https://github.com/apache/pulsar-client-go. If it's still relevant, please open an issue there.

BTW, pulsar-client-go is a pure Golang implementation.
