### ISSUE TITLE
TLS Authentication on proxy prevents Prometheus metrics collection

### ISSUE THREAD

**Issue by bschofield** [apache/pulsar#6789]
I am running a Pulsar deployment with TLS and Authentication on enabled on the proxy only, and neither TLS nor Authentication enabled inside the private cluster.

When Prometheus attempts to scrape metrics from the proxy component, the following errors are produced in the log:

```
15:21:54.630 [pulsar-external-web-4-8] INFO  org.eclipse.jetty.server.RequestLog - 10.244.39.210 - - [20/Apr/2020:15:21:54 +0000] "GET /metrics HTTP/1.1" 302 0 "-" "Prometheus/1.6.3" 27
15:21:54.641 [pulsar-external-web-4-2] WARN  org.apache.pulsar.broker.web.AuthenticationFilter - [10.244.39.210] Failed to authenticate HTTP request: Authentication required
15:21:54.642 [pulsar-external-web-4-2] INFO  org.eclipse.jetty.server.RequestLog - 10.244.39.210 - - [20/Apr/2020:15:21:54 +0000] "GET /metrics/ HTTP/1.1" 401 353 "http://10.244.40.37:8080/metrics" "Prometheus/1.6.3" 20
```

Is there a way to allow Prometheus to gather proxy metrics in my configuration?

**Comment by cdbartholomew** [comment]
You can either configure authentication in your Prometheus scrape job or disable authentication on the proxy metrics endpoint. To disable, you should be able to set the following in your proxy.conf:

```
authenticateMetricsEndpoint=false
```
See https://github.com/apache/pulsar/pull/4921 for more details.

**Comment by bschofield** [comment]
Oh, excellent. I see that is even in the docs -- I don't know how I missed it.

Adding:

```
  PULSAR_PREFIX_authenticateMetricsEndpoint: "false"
```

to the appropriate `ConfigMap` fixed this for me.

Thank you for your help!
