### ISSUE TITLE
Function gets stuck in the context.getState() method

### ISSUE THREAD

**Issue by javard** [apache/pulsar#6813]
**Description**
When using the method *context.getState()* two times in a row sometimes it gets stuck in one of calls. When this happens and the function is restarted, the function always gets stuck launching (I think it can't connect to the bookkeeper) and Pulsar needs to be restarted. 

**To Reproduce**
1. Multiple producers writing to *topic1* 
2. Function inputs *topic1* and outputs to *topic2*
3. Function executes (in this order) :
3.1. *context.getState("key1")* and *context.getState("key2")* consecutively
3.2. *context.putState("key2")* and *context.putState("key1")* consecutively
3.3. returns a message

**Expected behavior**
*topic2* receives all the messages sent to *topic1*.

**Desktop:**
 - OS: Ubuntu 19.10 64-bit
 - CPU: Intel® Core™ i7-4770HQ CPU @ 2.20GHz × 4 
 - Memory: 10.5 GiB

**Additional context**
Pulsar version: 2.5.0
Mode: standalone
Command used to launch the function:
`./pulsar-admin functions localrun --jar path/to/jar/functions.nar --classname org.class.name.DummyFunction --tenant admin-tenant --namespace CHM --name dummy-function --inputs persistent://admin-tenant/CHM/topic1 --output persistent://admin-tenant/CHM/topic2 --processing-guarantees ATLEAST_ONCE --state-storage-service-url bk://localhost:4181 --broker-service-url pulsar://localhost:6650`

**Comment by sijie** [comment]
@javard did you enable bookkeeper state storage?

**Comment by javard** [comment]
@sijie I think it's enabled. When I run in localrun without the flag `--state-storage-service-url` it throws the exception `java.lang.IllegalStateException: State is not enabled`.
But setting the flag (`--state-storage-service-url bk://localhost:4181`) the state storage works.
what is the correct way to enable the state storage?

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to maintained versions.
