### ISSUE TITLE
Persistent topic put request doesn't return 409 error if topic exists

### ISSUE THREAD

**Issue by nitinmuteja** [apache/pulsar#6820]
**Describe the bug**

**To Reproduce**
1. Post a put request to 'persistent/{tenant}/{namespace}/{topic}' with a request for topic
2. Should return an OK response
3. Post the same request again.
4. An OK response is returned.

**Expected behavior**
Should return 409 as per docs. 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by sijie** [comment]
@nitinmuteja did you run pulsar-admin to check if the issue exists in the pulsar-admin tool? I am wondering if you have sent the right command to pulsar admin RESTful service.

**Comment by nitinmuteja** [comment]
@sijie I did not check it with the pulsar admin. I sent the following request to the REST api
curl -X PUT -H "Content-Type: text/plain" -d ${partitions} "http://${brokerip}:${brokerport}/admin/v2/persistent/${tenant}/${namespace}/${topic}/partitions"

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to maintained versions.
