### ISSUE TITLE
Duplicated repository?

### ISSUE THREAD

**Issue by JoseFMP** [apache/pulsar#6823]
Hello,
What is the difference between https://github.com/apache/pulsar-client-go and https://github.com/apache/pulsar/tree/master/pulsar-client-go ? i.e. are they duplicated, or which one is supposed to be the go client for pulsar. I am a bit confused.

**Comment by sijie** [comment]
@JoseFMP - 

https://github.com/apache/pulsar/tree/master/pulsar-client-go is the c-go client that is built using the pulsar-client-cpp library.

 https://github.com/apache/pulsar-client-go is the native go client. 

The c-go client will be deprecated in future releases. If you just start with Pulsar, please use the native go client.

**Comment by tisonkun** [comment]
Closed as answered.
