### ISSUE TITLE
support async send msg can get sequenceId when throw exception

### ISSUE THREAD

**Issue by liudezhi2098** [apache/pulsar#6824]
## Motivation

When sending messages asynchronously fails, an exception will be thrown, but it is not known which message is abnormal, and the user does not know which messages need to be retried。

## Proposed changes

This change can be supported on the client side,   when throwing an exception need to set sequenceId
org.apache.pulsar.client.api.PulsarClientException

```java
public class PulsarClientException extends IOException {
    private long sequenceId = -1;

    public PulsarClientException(String msg, long sequenceId) {
        super(msg);
        this.sequenceId = sequenceId;
    }
```

**Comment by codelipenghui** [comment]
close via #6825
