### ISSUE TITLE
pulsar-client MultiTopicsConsumerImpl frequently fullgc

### ISSUE THREAD

**Issue by yangwenjie88** [apache/pulsar#6829]
300 partitions topic 1200W/s,  pulsar-client 2.5.1

failover SubscriptionType, When using 150 2core 4G vm, fullgc frequently appears, the connection has been reconnected, and the consumption cannot be achieved at all.
Some parameter configuration:
 receiverQueueSize = 1000
maxTotalReceiverQueueSizeAcrossPartitions = 60000
Instead of using 20 16core 32G VMs when consuming, the memory usage is relatively high at startup, and there will be reconnection, which can be consumed after a while, but the speed is only 3000ms / s per partition. The performance is far from enough, 
when the receiverQueueSize=3000, fullgc will appear
When the specified partition is used for single consumption, the performance is normal. MultiTopicsConsumerImpl Multi-partition consumption is estimated to have performance problems

**Comment by jiazhai** [comment]
@yangwenjie88 Would you please have a try on use larger receiverQueueSize?

**Comment by yangwenjie88** [comment]
> @yangwenjie88 Would you please have a try on use larger receiverQueueSize?

Have tried to increase the size, after the increase, the memory is insufficient, resulting in more frequent fullgc

**Comment by lhotari** [comment]
This might be related to #8138.

**Comment by tisonkun** [comment]
https://github.com/apache/pulsar/issues/8138 has been resolved. This issue is stale and thus I'd like to close it as we cannot investigate the problem smoothly in an unmaintained version.

If it's still relevant to maintained versions, feel free to open a new issue.
