### ISSUE TITLE
ReflectionFactory is internal proprietary API and may be removed

### ISSUE THREAD

**Issue by maskit** [apache/pulsar#683]
#### Expected behavior
No warnings during build

#### Actual behavior
```
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ managed-ledger ---
[INFO] Compiling 30 source files to /Users/masakazu/git/pulsar/managed-ledger/target/test-classes
[WARNING] /Users/masakazu/git/pulsar/managed-ledger/src/test/java/org/apache/zookeeper/MockZooKeeper.java:[81,23] ReflectionFactory is internal proprietary API and may be removed in a future release
[WARNING] /Users/masakazu/git/pulsar/managed-ledger/src/test/java/org/apache/zookeeper/MockZooKeeper.java:[81,58] ReflectionFactory is internal proprietary API and may be removed in a future release
```

#### Steps to reproduce

```
mvn install -DskipTests
```

#### System configuration
**Pulsar version**: master c51eaad
**OS**: macOS 10.12

**Comment by merlimat** [comment]
I haven't found a way to fix this. We are using the `ReflectionFactory` in tests to instantiate a Zookeeper client instance without invoking the constructor (in the `MockZookeeper`).

Not calling the constructor is critical because `Zookeeper` class is trying to do many thing (like connecting) from the constructor and there is no other interface.

**Comment by sijie** [comment]
@merlimat is this related to your recent changes for java11?

**Comment by merlimat** [comment]
@sijie Yes, I think it would still be required to be fixed. In #3006 I just verified it compiles and run with Java 11 though I haven't ran the tests with that yet.

**Comment by vcottagiri** [comment]
@sijie - Let me look into this one

**Comment by sijie** [comment]
@vcottagiri great!

**Comment by vcottagiri** [comment]
@sijie - thanks. Raised [PR](https://github.com/apache/pulsar/pull/7582). Hope its what @merlimat was looking for.
