### ISSUE TITLE
deploy pulsar dev,test,pro cluster at the same time , i hope the pulsar-Operator  just like tidb-Operator 

### ISSUE THREAD

**Issue by lookhua** [apache/pulsar#6833]
**Is your feature request related to a problem? Please describe.**
when i deploy pulsar cluster  for dev,test,pro env ,i donot have a  easy way to do it.

**Describe the solution you'd like**
 i hope the pulsar-Operator  just like tidb-Operator futures.

**Comment by sijie** [comment]
@lookhua Currently if you are looking for solutions to deploy Pulsar in kubernetes, you can use Helm chart - https://github.com/apache/pulsar-helm-chart. We are also developing operators and will open-source them at some time.

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.
