### ISSUE TITLE
Apache pulsar Encryption failed using ecdsa

### ISSUE THREAD

**Issue by kjaggann** [apache/pulsar#6834]
Trying to send encrypted messages from producer 
but got this exception:
------------------------------------------------------------------------------------------
```
org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: java.lang.NoSuchMethodError: 'org.apache.pulsar.shade.io.netty.buffer.ByteBuf org.apache.pulsar.client.api.MessageCrypto.encrypt(java.util.Set, org.apache.pulsar.client.api.CryptoKeyReader, java.util.function.Supplier, org.apache.pulsar.shade.io.netty.buffer.ByteBuf)'
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:719)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:117)
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.send(TypedMessageBuilderImpl.java:89)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:63)
	at com.vz.vmb.PulsarProducer.main(PulsarProducer.java:59)
Caused by: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: java.lang.NoSuchMethodError: 'org.apache.pulsar.shade.io.netty.buffer.ByteBuf org.apache.pulsar.client.api.MessageCrypto.encrypt(java.util.Set, org.apache.pulsar.client.api.CryptoKeyReader, java.util.function.Supplier, org.apache.pulsar.shade.io.netty.buffer.ByteBuf)'
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:115)
	... 3 more
Caused by: org.apache.pulsar.client.api.PulsarClientException: java.lang.NoSuchMethodError: 'org.apache.pulsar.shade.io.netty.buffer.ByteBuf org.apache.pulsar.client.api.MessageCrypto.encrypt(java.util.Set, org.apache.pulsar.client.api.CryptoKeyReader, java.util.function.Supplier, org.apache.pulsar.shade.io.netty.buffer.ByteBuf)'
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:477)
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendAsync(ProducerImpl.java:269)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:108)
	... 3 more
Caused by: java.lang.NoSuchMethodError: 'org.apache.pulsar.shade.io.netty.buffer.ByteBuf org.apache.pulsar.client.api.MessageCrypto.encrypt(java.util.Set, org.apache.pulsar.client.api.CryptoKeyReader, java.util.function.Supplier, org.apache.pulsar.shade.io.netty.buffer.ByteBuf)'
	at org.apache.pulsar.client.impl.ProducerImpl.encryptMessage(ProducerImpl.java:567)
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:446)
	... 5 more

--------------------------------------------------------------------------------------------------
Followed the Encryption from the apache pulsar documentation and the sampleProducerConsumerTest class from pulsar client.
Generated a public key and the private key 
created a Pulsarclient object
--------------------------------------------------------------------------------------------------
client = PulsarClient.builder()
					.serviceUrl("pulsar+ssl:xxxxxxxxxxxxxxxxx:6651/")
					.tlsTrustCertsFilePath("src/main/resources/ca.cert.pem")
					.enableTls(true)
					.authentication("org.apache.pulsar.client.impl.auth.AuthenticationTls", authParams).build();

Producer<byte[]> producer = client.newProducer()
					.topic("persistent://tenant/namespace/nonprod-topic-1")
					.cryptoKeyReader(new RawFileKeyReader("src/main/resources/test_ecdsa_pubkey.pem", "src/main/resources/test_ecdsa_privkey.pem"))
					.addEncryptionKey("src/main/resources/test_ecdsa_pubkey.pem")
					.enableBatching(false)
					.create();

String message = "Test Messages";
			int i = 2;
			while(true) {
				i = i + 1;
				message = message + " Mesage # " + i;

				producer.send(message.getBytes());
				System.out.println("Printing the Messages " + message);
				producer.flush();
				if (i == 100) {
					break;
				}
			}
			producer.close();
			client.close();
```

**To Reproduce**
```
1. Go to ' create a producer class in java. add the serviceUrl, generate public key, generate private key, use certificates for tls authentication, and make the topic as encryption enabled'
2. Click on ' run the sample producer'
3. Scroll down to ' console'
4. See error 
'org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: java.lang.NoSuchMethodError: 'org.apache.pulsar.shade.io.netty.buffer.ByteBuf org.apache.pulsar.client.api.MessageCrypto.encrypt(java.util.Set, org.apache.pulsar.client.api.CryptoKeyReader, java.util.function.Supplier, org.apache.pulsar.shade.io.netty.buffer.ByteBuf)'
```

**Expected behavior**
send message encrypted messages using ecdsa public key and private key, 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : I am using macOs  Mojave version(10.14.6)
-Pulsar-client version: 2.5.1

**Additional context**
here are my dependecies i used
```
<dependency>
			<groupId>org.apache.pulsar</groupId>
			<artifactId>pulsar-io-netty</artifactId>
			<version>2.5.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.pulsar</groupId>
			<artifactId>pulsar-client-messagecrypto-bc</artifactId>
			<version>2.5.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.pulsar</groupId>
			<artifactId>pulsar-client</artifactId>
			<version>2.5.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.pulsar</groupId>
			<artifactId>pulsar-client-admin</artifactId>
			<version>2.5.1</version>
		</dependency>
```

**Comment by trexinc** [comment]
Not sure how you got those errors. With 2.5.1 I get:
Class not found for org.apache.pulsar.client.impl.crypto.MessageCryptoBc
Which can be resolved by adding the following dependency 
compile group: 'org.apache.pulsar', name: 'pulsar-client-messagecrypto-bc', version: '2.5.1'

**Comment by kjaggann** [comment]
I have aready added org.apache.pulsar.client.impl.crypto.MessageCryptoBc version 2.5.1 
should i make any more changes to y code

**Comment by kjaggann** [comment]
But how is it related to MessageCrypto should i add any method related to messagecryptobc to encrypt

**Comment by sijie** [comment]
In 2.5.1, we made a few changes regarding to FIPS support. This class has been moved to a separated module and the client already depends on it. So ideally if you are using maven, you should be able to resolve all the dependencies. 

@kjaggann how did you run your code?

@trexinc are you using maven to build your project?

@jiazhai please take a look at this issue.

**Comment by kjaggann** [comment]
I used maven to develop a sample producer and consumer class using java. I am able to send the messages with out encryption. But for this topic i have enabled encryption.
I followed the same steps from the apache pulsar document, generated a public key and private key, used it as the document said.

**Comment by trexinc** [comment]
@sijie I use gradle.
If I do not add the pulsar-client-messagecrypto-bc dependency manually it fails at runtime with 
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/apache/pulsar/client/impl/crypto/MessageCryptoBc

**Comment by kjaggann** [comment]
do you have any sample python script encryption for producer and consumer

**Comment by kjaggann** [comment]
I don't see any document in apache pulsar at-least to try python encryption and decryption

**Comment by jiazhai** [comment]
Cpp and python client is not involved in the FIPS provider support. We may need to confirm this feature is supported, and provide an example.

**Comment by jiazhai** [comment]
For java, this is a dependency issue, need to add dependency as @trexinc mentioned.
```
compile group: 'org.apache.pulsar', name: 'pulsar-client-messagecrypto-bc', version: '2.5.1'
```
would like to close this issue. and opened issue #6914 to track the MessageCrypto status in python.

**Comment by nhathatrinh** [comment]
Hi, I've got a same issue with java too. 
Here are my dependencies i used
[dependencies.txt](https://github.com/apache/pulsar/files/4863826/dependencies.txt)

@jiazhai , If pulsar-client-messagecrypto-bc dependency is not added then it should throw 'NoClassDefFoundError: org/apache/pulsar/client/impl/crypto/MessageCryptoBc'. But this issue is 'NoSuchMethodError: 'org.apache.pulsar.shade.io.netty.buffer.ByteBuf'. Could you please let me know the reason to close this issue?

**Comment by jiazhai** [comment]
Seems this error is
```
Caused by: java.lang.NoSuchMethodError: 'org.apache.pulsar.shade.io.netty.buffer.ByteBuf org.apache.pulsar.client.api.MessageCrypto.encrypt(java.util.Set, org.apache.pulsar.client.api.CryptoKeyReader, java.util.function.Supplier, org.apache.pulsar.shade.io.netty.buffer.ByteBuf)'
```
The related method is 
```

```

**Comment by jiazhai** [comment]
Seems this error is
```
Caused by: java.lang.NoSuchMethodError: 'org.apache.pulsar.shade.io.netty.buffer.ByteBuf org.apache.pulsar.client.api.MessageCrypto.encrypt(java.util.Set, org.apache.pulsar.client.api.CryptoKeyReader, java.util.function.Supplier, org.apache.pulsar.shade.io.netty.buffer.ByteBuf)'
```
looks like related to shade issue： 
`org.apache.pulsar.shade.io.netty.buffer.ByteBuf`  < = > `io.netty.buffer.ByteBuf`

**Comment by jiazhai** [comment]
`MessageCryptoBc` implements the interface of `MessageCrypto`. while `pulsar-client` did a shade to`ByteBuf`, and caused the method parameter changed from `org.apache.pulsar.shade.io.netty.buffer.ByteBuf` to `io.netty.buffer.ByteBuf`

**Comment by nhathatrinh** [comment]
@jiazhai @sijie 
I am having a same issue with pulsar client 2.6.2. Could you please let me know if i miss any dependency? 
dependency:
`<dependency>
     <groupId>org.apache.pulsar</groupId>
     <artifactId>pulsar-client</artifactId>
     <version>2.6.2</version>
 </dependency>`

Error:
`org.apache.pulsar.client.api.PulsarClientException: java.lang.NoSuchMethodError: org.apache.pulsar.client.api.MessageCrypto.encrypt(Ljava/util/Set;Lorg/apache/pulsar/client/api/CryptoKeyReader;Ljava/util/function/Supplier;Lorg/apache/pulsar/shade/io/netty/buffer/ByteBuf;)Lorg/apache/pulsar/shade/io/netty/buffer/ByteBuf;`

**Comment by sijie** [comment]
@jiazhai Can you check the last comment?

**Comment by jiazhai** [comment]
That should be fixed in current master, I will add tests to verify this

**Comment by RobertIndie** [comment]
> I am having a same issue with pulsar client 2.6.2. Could you please let me know if i miss any dependency?
> dependency:
> `<dependency> <groupId>org.apache.pulsar</groupId> <artifactId>pulsar-client</artifactId> <version>2.6.2</version> </dependency>`
> 
> Error:
> `org.apache.pulsar.client.api.PulsarClientException: java.lang.NoSuchMethodError: org.apache.pulsar.client.api.MessageCrypto.encrypt(Ljava/util/Set;Lorg/apache/pulsar/client/api/CryptoKeyReader;Ljava/util/function/Supplier;Lorg/apache/pulsar/shade/io/netty/buffer/ByteBuf;)Lorg/apache/pulsar/shade/io/netty/buffer/ByteBuf;`

You could try to add this dependency `bouncy-castle-bc` by
```
<dependency>
  <groupId>${project.groupId}</groupId>
  <artifactId>bouncy-castle-bc</artifactId>
  <version>${project.parent.version}</version>
  <classifier>pkg</classifier>
</dependency>
```

**Comment by jiazhai** [comment]
@RobertIndie This issue exists in 2.6.2, and should be work now in 2.7 and the latest master. And thanks for working on the verify.

**Comment by jiazhai** [comment]
@nhathatrinh The PR #8850 is merged, I would like to close this issue. Thanks for @RobertIndie 's help
