### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded' is observed when creating producers on a non-existent topic

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#6838]
**Describe the bug**

 if we try to create producer for a non-existent topic the ProducerImpl object is hanging in the dump. Although producer creation fails but we see that ProducerImpl object corresponding to each producing action hanging in the dump. This behavior will lead to OOM in microservice which by mistake tries to produce consistently to a non-existent topic.

**Comment by devprashantksinha** [comment]
Hi, we are consuming your 2.5.2 release we still observe this issue. PulsarProducerImp is hanging in the dump as reported previously.

**Comment by codelipenghui** [comment]
@devprashantksinha Did you upgrade the Pulsar broker? #6879 makes some changes on the broker side.

**Comment by devprashantksinha** [comment]
@codelipenghui : yes we have upgraded both client and pulsar chart components including broker to 2.5.2 . These are the steps I followed to reproduce : 

1. Produce to a non existent topic from one of the application using pulsar-client 2.5.2.
2. Take heap dump after producing we see a lot of instances of **ProducerImpl** in the dump being the top memory consumer. This might lead to OOM after some time.

Ideally,  we should not see any ProducerImpl for a topic that doesn't exist. Right ?

Please let me know if you need more info about the setup.
