### ISSUE TITLE
Allow providing a self-created ObjectMapper instance for Jackson to be able to use Jackson extensions

### ISSUE THREAD

**Issue by Persi** [apache/pulsar#6842]
**Is your feature request related to a problem? Please describe.**
I am trying to use Pulsar Java client in a Spring Boot application and was able to produce and consume messages. I ran in trouble when sending messages with JSON content which contains fields of type OffsetDateTime. My Spring Boot application already uses the same JSON for it's REST API and can serialize and deserialize OffsetDateTime as "jackson-datatype-jsr310" is in my classpath. But the included version of Jackson in the Pulsar Java client, does not know this extension and instead fails while deserialization with erros like the following:
```
...
Caused by: org.apache.pulsar.shade.com.fasterxml.jackson.databind.exc.InvalidDefinitionException: 
Cannot construct instance of `java.time.OffsetDateTime` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
```

**Describe the solution you'd like**
Could you provide a non-shaded version of the Pulsar Java client? This would be really helpful for Spring Boot integrations, as most Spring Boot applications already provide a global configured instance of Jackson ObjectMapper, which the Pulsar Java client could use, to use the same mapping settings as the rest of the application.

The JSONSchema class instanciates it's ObjectMapper as internal ThreadLocal which makes it unchangeble as well as unconfigurable. You could add the opportunity to provide an ObjectMapper instance, e.g. on pulsar client instanciation, which could be used by all producers and consumers created.

**Comment by sijie** [comment]
@Persi the default `pulsar-client` shades all dependencies. You can use `pulsar-client-original` with unshaded dependencies.

**Comment by Persi** [comment]
Using `pulsar-client-original` seems to work as expected :)

But my second point (which actually don't even has to do with Spring Boot) is already an issue. As there is currently no way to configure or provide an ObjectMapper instance, it is impossible to reuse already configured ObjectMapper instances.

I would suggest to add a provider interface for ObjectMapper with the current implementation from JSONSchema as default implementation. That would allow to provide other ObjectMapper instances independent of the environment.

**Comment by hansenc** [comment]
This is all about being able to configure Jackson for use with Pulsar's JSON schema and not about Spring Boot. I would like to see the title and description of this issue updated accordingly.

Since I'm here, given that Jackson use is so prevalent, improving the ability to reuse existing configuration and Jackson-annotated classes would be huge 👍 . Being able to supply your own `ObjectMapper` to the client seems like the most straightforward solution.

**Comment by sijie** [comment]
@hansenc @Persi thank you for your feedback. We will prioritize this issue and come up with a fix. At the same time, if any of you are interested in contributing a fix, you are super welcome as well.
