### ISSUE TITLE
Latest pulsar-all docker image might be broken.

### ISSUE THREAD

**Issue by MarvinCai** [apache/pulsar#6850]
**Describe the bug**
When following instruction to run pulsar with minikube, 
I stuck at the step "$ kubectl apply -f bookie.yaml"
The pod can not start up and I see error log
"Error: Could not find or load main class"
After change to version 2.5.0 it seems working fine.
So there might be some problem with the latest(2.5.1) pulsar-all image.

**To Reproduce**
Follow instruction [here](https://pulsar.apache.org/docs/en/2.5.1/deploy-kubernetes/#deploying-pulsar-components) to run pulsar cluster in Kubernetes.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/13480084/80670164-0e9c4200-8a5b-11ea-8f18-0ffb58764552.png)

**Desktop (please complete the following information):**
 - OS: Mac

**Comment by rueian** [comment]
I run into the same issue.

**Comment by sijie** [comment]
@rueian @MarvinCai I think the change is related to: https://github.com/apache/pulsar/blob/master/conf/bkenv.sh#L36

You might need to add both `BOOKIE_ME` and `PULSAR_ME` to make it work. (https://github.com/apache/pulsar/blob/master/conf/bkenv.sh#L36)

Also I think we have removed the out-of-date kubernetes deployment scripts and the documentation. But it seems that 2.5.1 brought the documentation back. We need to fix the documentation issue.

At the same time, please follow the latest helm documentation for installing Pulsar on Kubernetes.
https://pulsar.apache.org/docs/en/next/kubernetes-helm/
https://pulsar.apache.org/docs/en/next/helm-overview/

**Comment by rueian** [comment]
Thank you, sijie.

I have had set both `BOOKIE_ME` and `PULSAR_ME` to `" -XX:+UseContainerSupport -XX:InitialRAMPercentage=40.0 -XX:MinRAMPercentage=20.0 -XX:MaxRAMPercentage=80.0 "`, and the problem was fixed.

By the way, is there any reason to use `-Xms -Xmx -XX:MaxDirectMemorySize` instead of  `UseContainerSupport, XX:InitialRAMPercentage, XX:MinRAMPercentage, XX:MaxRAMPercentage` in the container ?

**Comment by sijie** [comment]
@rueian I think the settings were coming from running Pulsar in on-premise environment. So they got into the container settings. We haven't changed those settings to adopt the container way. If you are interested in making a contribution, you are super welcome!
