### ISSUE TITLE
Allow non-java clients to start consumer from timestamp

### ISSUE THREAD

**Issue by phemmer** [apache/pulsar#6864]
**Describe the solution you'd like**
#3622 (#3565) granted Java clients the ability to start & seek to a given timestamp. This request is to give that functionality to non-Java clients, in my specific case, Go.

The reasons for wanting this functionality are the same as described in #3565.

**Comment by sijie** [comment]
@phemmer are you using cgo or native-go client?

**Comment by phemmer** [comment]
cgo. This one: https://github.com/apache/pulsar/tree/master/pulsar-client-go/pulsar

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Go client has been permanently moved to https://github.com/apache/pulsar-client-go. If it's still relevant, please open an issue there.
