### ISSUE TITLE
2.5.1 documentation contains the out-of-date documentation of kubernetes deployment

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#6882]
*Motivation*

The out-of-date k8s documentation was already removed from 2.5.0 and master. Somehow the old documentation was brought back to the website. We should remove it.

https://pulsar.apache.org/docs/en/2.5.0/kubernetes-helm/
https://pulsar.apache.org/docs/en/2.5.0/functions-overview/

https://pulsar.apache.org/docs/en/next/kubernetes-helm/
https://pulsar.apache.org/docs/en/next/helm-overview/

**Comment by Anonymitaet** [comment]
OK. This task has been added to the backlog.

**Comment by Anonymitaet** [comment]
@Huanli-Meng Since you worked on this issue and discussed w/ sijie before, could u pls double-check the issue status? thanks

**Comment by Huanli-Meng** [comment]
@sijie , it seems that the issue is fixed as we checked before. if not, could you please identify which are old contents? Thx.

**Comment by Jennifer88huang** [comment]
@Huanli-Meng double confirmed with @sijie that this issue is fixed, so I close it.
