### ISSUE TITLE
Pulsar SQL not returning latest row

### ISSUE THREAD

**Issue by opera33** [apache/pulsar#6884]
**Describe the bug**
As titled, running query on Pulsar SQL, and it doesn't return the last row of the topic

**To Reproduce**
 For example a topic has 0 row, then I add one row by publishing a message (aaa) to pulsar server. I query the table selecting *, it shows 0 rows. Then i publish another message (bbb), and try to query select * again, row "aaa" shows up, but not "bbb", if i publish another message (ccc), and then query, 2 rows returned: "aaa", "bbb"

**Expected behavior**
All the rows to show after the query

**Additional context**
Running on Pulsar 2.4.2
Also as someone is facing issue in 2.5.0
https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1588064084428500

**Comment by codelipenghui** [comment]
@opera33 You can upgrade to 2.5.1 and enable explicit LAC by setting bookkeeperExplicitLacIntervalInMills=10 in the broker.conf.

**Comment by sijie** [comment]
@codelipenghui it is worth adding a note in the documentation about this setting.

**Comment by codelipenghui** [comment]
close via #6908
