### ISSUE TITLE
Slash "/" should be prevented in subscription names

### ISSUE THREAD

**Issue by trexinc** [apache/pulsar#6886]
Currently Pulsar allows a client to create a subscription with slash in its names.
This creates misc administrative issues.

**Comment by trexinc** [comment]
Now that I look at it, it seems that "/" in subscription names is actually valid.
I see that subscriptions for functions are actually "tenant/namespace/function_name"

**Comment by cdbartholomew** [comment]
Those subscriptions on functions are problematic. You can't perform admin actions on them, so I think your original comment holds.

**Comment by merlimat** [comment]
`/` are perfectly supported as subscription names, any operation done on Java admin API or CLI tools will work correctly. 

When using REST API directly, the name needs to properly URL encoded (that's also for any other special character with respect to HTTP).

**Comment by sijie** [comment]
Close this issue based on the last comment.
