### ISSUE TITLE
Expose topic/subscription/consumer number of messages as counter.

### ISSUE THREAD

**Issue by one1zero1one** [apache/pulsar#6891]
**Is your feature request related to a problem? Please describe.**
Topic metrics are expressed as computed rates, e.g. gauges: `pulsar_rate_in` `pulsar_rate_out`. This makes Prometheus scraping miss any change of rate in between the scrape interval.  

**Describe the solution you'd like**
Exposing the metrics as counters instead/in addition to gauges, e.g. `pulsar_count_in`  would allow the rate to be computed in prometheus, and would not miss change of rates within the scraping interval.

**Describe alternatives you've considered**
Increasing the scrape interval to <15s however it still misses spikes. 
I have considered using a sidecar container that would create the counters from gauges, but it adds unwanted complexity.

**Comment by sijie** [comment]
@one1zero1one I think @PierreZ already added this feature. We will check if it will be released as part of 2.6.0.
