### ISSUE TITLE
Jackson shading issues

### ISSUE THREAD

**Issue by hansenc** [apache/pulsar#6902]
**Is your feature request related to a problem? Please describe.**
`pulsar-client`, the Pulsar Java client, shades several of its dependencies and redistributes them in its jar, which makes sense to do. However, shading Jackson in this way leads to behavior that is surprising to new users (see #6842 for one example). Another example is that the shaded Jackson will not pick up `com.fasterxml.jackson.annotation.*` annotations, instead looking for `org.apache.pulsar.shade.com.fasterxml.jackson.annotation.*` annotations which limits users' ability to reuse existing classes.

**Describe the solution you'd like**
- Don't shade Jackson in `pulsar-client` and instead make Jackson an optional Maven dependency for the Java client (both `pulsar-client` and `pulsar-client-original`) since users may not need the JSON schema at all (unless it's needed internally in the client for some reason). Users needing the JSON schema will need to provide their own (compatible) version of Jackson, which eliminates the need for shading.
- Mention shading in [the Pulsar Java client documentation](https://pulsar.apache.org/docs/en/client-libraries-java/) and list `pulsar-client-original` there as the unshaded artifact.
- Consider renaming `pulsar-client` to `pulsar-client-shaded` for clarity. I've seen some other projects do this (https://github.com/rickfast/consul-client is one example).

**Comment by sijie** [comment]
This issue seems to be related to issue #6889 as well.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
