### ISSUE TITLE
Add access to user-config when initializing a function

### ISSUE THREAD

**Issue by hbs** [apache/pulsar#6906]
**Is your feature request related to a problem? Please describe.**
Functions cannot access the info passed via --user-config at initialization time.

**Describe the solution you'd like**
Add an initialization method or call a specific constructor in order to allow for proper initialization before the first message arrives.

**Describe alternatives you've considered**
At the moment proper initialization must be done in the 'process' method when the first message arrives. This leads to additional checks which are only needed because of the lack of proper initialization method and delays the processing of the first message if initialization of the function is costly.

**Additional context**
N/A

**Comment by KannarFr** [comment]
In which way can we extend the `@FunctionalInterface` to add `void initialize(InstanceConfig config)`? @jiazhai

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.
