### ISSUE TITLE
${PYTHONPATH} is not expanded thus leading to incorrect environment variable value

### ISSUE THREAD

**Issue by hbs** [apache/pulsar#6907]
https://github.com/apache/pulsar/blob/00463adfd5c59958479b9b3a8e26140ab07fd8c1/pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/process/ProcessRuntime.java#L347

**Comment by sijie** [comment]
@hbs I don't understand the issue here. The `${PYTHONPATH}` is an environment variable that is passed to the process's environment. Not sure if we need to expand the value.

**Comment by hbs** [comment]
The initial intent was probably to expand the value of PYTHONPATH by appending an additional path to it, what actually happens is that the PYTHONPATH variable is set literally to

${PYTHONPATH}:<NEWPATH>

not <WHATEVER_PYTHONPATH_CONTAINED>:<NEWPATH>

since ${PYTHONPATH} is not expanded

**Comment by tisonkun** [comment]
Closed as stale.

The development of this initiative seems stalled and this thread doesn't contain too much information. If one wants to revive the proposal, please open a brand new thread.
