### ISSUE TITLE
Autocreate tenant/namespace

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#6912]
**Describe the solution you'd like**
Pulsar client should have a configuration to autocreate tenant/namespace if they don't exist. 

Consequently, the authz would be used to ensure every rights are contained in the authstring.

This comes with the granularity possibilities offered by https://github.com/apache/pulsar/pull/6428.

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.
