### ISSUE TITLE
Documentation in v2.5.1 for Key_Shared Subscription for consumer connnects/disconnects is not clearly specified

### ISSUE THREAD

**Issue by vcottagiri** [apache/pulsar#6923]
The [Key_Shared Subscription](http://pulsar.apache.org/docs/en/concepts-messaging/#key_shared) documentation has the following line

> When a consumer connected or disconnected will cause served consumer change for some key of message.

It would be nice if the documentation can be more clear on the message routing when there are new consumers or disconnects.

**Comment by codelipenghui** [comment]
Yes, thanks for the feedback. We are already starting to advance to fix ordering message dispatch related issues when consumer change. And, Will also explain this part in more detail.

**Comment by Huanli-Meng** [comment]
@codelipenghui any progress about this? thanks.

**Comment by rocketraman** [comment]
Agreed, right now the [PIP](https://github.com/apache/pulsar/wiki/PIP-34:-Add-new-subscribe-type-Key_shared) is the only place where one can find important information about how this works when consumers connect and disconnect.

**Comment by momo-jun** [comment]
Hi @vcottagiri @rocketraman, the next version of the doc for Key_Shared Subscription has been enhanced with more tech details, compared with 2.5.1. See [here](https://pulsar.apache.org/docs/next/concepts-messaging/#key_shared). So I'll close the issue at this moment. Feel free to reopen it and add your contributions.
