### ISSUE TITLE
Add C# client documentation

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#6927]
**Is your feature request related to a problem? Please describe.**
Since we have official c# client https://github.com/apache/pulsar-dotpulsar, we'd better add the C# client documentation in the client documentation. 

![image](https://user-images.githubusercontent.com/12592133/81468880-b8768e00-9214-11ea-9ef3-97562a05366b.png)

**Comment by Huanli-Meng** [comment]
@codelipenghui , here are docs that may be impacted by the introduction of C# client. Please help correct me if i miss any doc update. Thanks.

1. Get-started > Use Pulsar with client libraries
- add a bullet for C#
- update feature matrix list (need help)

2. Security: add contents about C# in the following docs
- Transport encryption using TLS
- authentication using TLS
- authentication using JWT

3. Client libraries
- C#: a new doc

**Comment by Huanli-Meng** [comment]
1. Update the following docs: 
- Use Pulsar with client libraries
- Transport encryption using TLS
- authentication using TLS
- authentication using JWT
- sidebar.json doc

2. Add a new doc for C# client

**Comment by Huanli-Meng** [comment]
docs for C# client is approved and merged. Here is the doc PR: https://github.com/apache/pulsar/pull/7003

**Comment by Huanli-Meng** [comment]
doc is updated and merged, here is the PR link: https://github.com/apache/pulsar/pull/7003

**Comment by vzhikserg** [comment]
@sijie @jiazhai @tuteng could you please close this issue? it was implemented in #7003
