### ISSUE TITLE
Early blogs are not shown in the blog list

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#6928]
I remember that we have some early blogs such as the 2.4.0 release post. But we can't find them in the blog list.

![image](https://user-images.githubusercontent.com/12592133/81469050-769a1780-9215-11ea-9a96-90e1486730d9.png)

**Comment by Anonymitaet** [comment]
@codelipenghui you can find legacy blogs [here](https://pulsar.apache.org/blog), so I'll close this issue.
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/50226895/170461310-073881ca-ada0-442b-a404-b1b7347a6205.png">

And I've submitted more ideas to improve the blog page here: https://github.com/apache/pulsar/issues/15804

@signormercurio thanks for your reminder!
