### ISSUE TITLE
KeyValue schema in Function Error

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#6929]
**Describe the bug**
Use KeyValue schema in Producer

            Producer<KeyValue<Student, Student>> producer = client.newProducer(
                    KeyValueSchema.of(Schema.JSON(Student.class), Schema.JSON(Student.class)))
                    .topic("persistent://public/default/test-kvin2")
                    .producerName("producerTest").create();

Function code:
public class PulsarFunctionTest3 implements Function<KeyValue<Student, Student>, KeyValue<Student, Student>> {

    @Override
    public KeyValue<Student, Student> process(KeyValue<Student, Student> studentKeyValue, Context context) throws Exception {
        context.getLogger().info("studentKeyValue key: {}", studentKeyValue.getKey().toString());
        context.getLogger().info("studentKeyValue: {}", studentKeyValue.toString());
        return studentKeyValue;
    }
}

Pulsar Function log shows:
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$IncompatibleSchemaException: Key schemas or Value schemas are different schema type, from key schema type is JSON and to key schema is BYTES, from value schema is JSON and to value schema is BYTES

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by codelipenghui** [comment]
@wolfstudy Could you please take a look at this issue?

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
