### ISSUE TITLE
Potential Deadlock in JavaInstanceRunnable class

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#6932]
**Describe the bug**
When attempting to start a LocalRunner that connects to stream storage, the instance will hang if the streamServiceUrl is incorrect or the service is unresponsive.

**To Reproduce**
1. Create an instance of the LocalRunner class inside a Java class
2. Initialize it like so:
` LocalRunner localRunner = 
	    	LocalRunner.builder()
	    		.brokerServiceUrl(BROKER_URL)
	    		.stateStorageServiceUrl("bk://localhost:4181")
	    		.functionConfig(functionConfig)
	    		.build(); localRunner.start(true);`

3. Attach to the process with a debugger and set a breakpoint at line 342 of the JavaInstanceRunnable class and attempt to step through to line 343

`result(storageAdminClient.getStream(tableNs, tableName));
 return;`

4. Notice that the process never returns, and the test will "hang" indefinitely

**Expected behavior**
I would expect the process to return and notify the user of the underlying issue that is preventing the LocalRunner from communicating with the StateStore.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
It appears that the original author intended for the above call to timeout after one minute, because they wrap the above call in a while loop that uses an StopWatch. However, if the call to the `storageAdminClient.getStream(tableNs, tableName)` call hangs indefinitely, then the 1 minute pause is exceeded. In my experience it was indefinite.

**Comment by david-streamlio** [comment]
Is there a way to confirm that the state store is running inside Pulsar standalone?

**Comment by jerrypeng** [comment]
I just used localrun to execute a source and function that uses state.  I ran against a standalone cluster running directly on my MAC.  Everything is working.  The function and source was able to access state.
