### ISSUE TITLE
loadBalancerSourceRanges on helm templates for pulsar manager and grafana

### ISSUE THREAD

**Issue by lukestephenson** [apache/pulsar#6950]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to whitelist the source IP ranges for the pulsar manager and grafana dashboard to a list of office VPN ips to increase security.

**Describe the solution you'd like**
Update https://github.com/apache/pulsar/blob/master/deployment/kubernetes/helm/pulsar/templates/pulsar-manager-service.yaml to allow specification of `loadBalanacerSourceRanges` as documented in https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service.

**Describe alternatives you've considered**
Alternative is to have it within a private subnet and use a bastion box.

**Additional context**

If this sounds ok, I'd be happy to submit a PR with the proposed changes.

**Comment by sijie** [comment]
@lukestephenson this sounds a great idea. Please submit a pull request. Since we have moved the helm chart to a separate repo, can you submit the pull request directly over there? https://github.com/apache/pulsar-helm-chart

**Comment by lukestephenson** [comment]
@sijie Thanks for pointing me at the new repo.  When will the new repo become the official one that the pulsar deployment docs are pointed to?  Thanks

**Comment by ckdarby** [comment]
@lukestephenson I believe Sijie has mentioned it'll happen in 2.6.0.

I see your PR merged in https://github.com/apache/pulsar-helm-chart/commit/96dbab924fcad80c9586bf3f3c10445c1dec8ee3

Can you close this issue here :) ?

**Comment by lukestephenson** [comment]
Fixed in https://github.com/apache/pulsar-helm-chart/pull/12
