### ISSUE TITLE
PulsarIO [Debezium] - Support MS SqlServer 

### ISSUE THREAD

**Issue by jdunhamvrtx** [apache/pulsar#6957]
This feature request will track work on creating a connector for SqlServer through the Debezium module.

**Comment by huangdx0726** [comment]
I'll work on it

**Comment by codelipenghui** [comment]
Thanks @huangdx0726

**Comment by tisonkun** [comment]
I think this is resolved by https://github.com/apache/pulsar/pull/12256. Please open a new issue if it's not the case.

**Comment by huangdx0726** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
