### ISSUE TITLE
[pulsar-io] Create Pulsar Sink connector for Couchbase

### ISSUE THREAD

**Issue by vzhikserg** [apache/pulsar#6958]
**Is your feature request related to a problem? Please describe.**
Apache Pulsar is missing a sink connector for [Couchbase ](https://www.couchbase.com/)(open-source, distributed multi-model NoSQL document-oriented database). 

**Describe the solution you'd like**
A new module with the implementation of a Pulsar sink connector for Couchbase should be added to Pulsar connectors.

**Describe alternatives you've considered**
N/A

**Additional context**
There is an open [pull request](https://github.com/apache/pulsar/pull/4210) for #4209 with the implementation of a source connector for Couchbase. It makes sense to align these sink and source connectors in one module.

**Comment by deniswsrosa** [comment]
Hi @tisonkun  I would like to work on this one. Let me know if a PR is welcome
