### ISSUE TITLE
Pulsar Admin API / Incomplete OpenAPI Spec

### ISSUE THREAD

**Issue by gotopanic** [apache/pulsar#6962]
**Describe the bug**
it seemed to me that the OpenAPI specification of the [Pulsar Admin REST API (v2)](http://pulsar.apache.org/admin-rest-api/) is incomplete:

- the PUT /namespaces/{tenant}/{namespace} command had a missing in/body parameter for policies
- the GET /non-persistent/{tenant}/{namespace}/{topic}/lastMessageId, POST /non-persistent/{tenant}/{namespace}/{topic}/terminate, GET /persistent/{tenant}/{namespace}/{topic}/lastMessageId and POST /persistent/{tenant}/{namespace}/{topic}/terminate commands specified a MessageId object in their response, but the MessageId object definition has no property unlike the MessageIdImpl object definition.

**To Reproduce**
- Go to: http://pulsar.apache.org/admin-rest-api/
- Download OpenAPI specification
- Observe that the commands above are missing some items

**Expected behavior**
The specification should have the missing items

**Screenshots**
Not a screenshot but a paste from the OpenAPI definitions to illustrate an issue: The MessageId referenced in the response of some commands, doesn't define any property, unlike the MessageIdImpl:

```
    "MessageId" : {
      "type" : "object"
    },
    "MessageIdImpl" : {
      "type" : "object",
      "properties" : {
        "ledgerId" : {
          "type" : "integer",
          "format" : "int64"
        },
        "entryId" : {
          "type" : "integer",
          "format" : "int64"
        },
        "partitionIndex" : {
          "type" : "integer",
          "format" : "int32"
        }
      }
    },
```

**Desktop (please complete the following information):**
Pulsar Admin 2.5.0

**Comment by jiazhai** [comment]
@gotopanic Thanks for reporting this issue. Would you like to contribute to it?

**Comment by gotopanic** [comment]
Sorry, I missed your reply. Yes I will gladly contribute, but I will need some guidance as this would be my first contribution... Would you be the committer who will review as per http://pulsar.apache.org/ja/contributing/ ?

**Comment by zongtanghu** [comment]
If no one else wanted to contribute for this issue, we can do it! @jiazhai @sijie

**Comment by gotopanic** [comment]
I have never contributed before, so I would definitely appreciate some help!

**Comment by gm7y8** [comment]
if no one is working on it can you assign this issue to me?

**Comment by sijie** [comment]
@gm7y8 Assigned.

**Comment by adeal** [comment]
@gm7y8 were you able to make progress?

**Comment by tisonkun** [comment]
Closed as stale. This seems a general issue to improve continuously.

If you find any missing API docs in the latest version, feel free to open a specific issue or submit a patch to fix it.
