### ISSUE TITLE
pulsar cli option documented but the code is not in the 2.5 branche

### ISSUE THREAD

**Issue by Mefl** [apache/pulsar#6967]
**Describe the bug**
The pulsar-client consume command has an option `--subscription-position` documented since 2.5.1, the class in the 2.5 branche does not have the option but it is ok on master branche. I think one part of the code wasn't merged on 2.5 branche.
 
**To Reproduce**
The documentation on 2.5.1 : https://pulsar.apache.org/docs/en/2.5.1/reference-cli-tools/#consume

The CmdConsume class on 2.5 branche : https://github.com/apache/pulsar/blob/branch-2.5/pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdConsume.java 

The CmdConsume class on master branche : https://github.com/apache/pulsar/blob/45f2d80b40523dfc8ae189ec45af44d351408d87/pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdConsume.java#L85

**Comment by jiazhai** [comment]
@Mefl Thanks for the issue reporting. Looks like this is a bug in doc release. Seems 2.5.1 doc included content that should not be included.
@Mefl Would you like to help fix this doc issue?

**Comment by jiazhai** [comment]
also @tuteng who is the release manager of 2.5.1.

**Comment by Anonymitaet** [comment]
@tuteng seems that [2.5.1 doc](https://pulsar.apache.org/docs/en/2.5.1/reference-cli-tools/#consume) (which includes `--subscription-position`) is not generated based on [2.5.0 doc](https://pulsar.apache.org/docs/en/2.5.0/reference-cli-tools/) (which does not include `--subscription-position`), could u pls take a look?

**Comment by Mefl** [comment]
Sure, I will correct it 👍 
You can assign it to me

**Comment by Huanli-Meng** [comment]
@Mefl , how about the process?

**Comment by momo-jun** [comment]
Close the issue since it might have been fixed and cannot be reproduced now.
