### ISSUE TITLE
More visibility for delayed message

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#6979]
**Is your feature request related to a problem? Please describe.**
it might be useful to see a breakdown of message expiration times, like how many messages will be ready in 1 hour, 2 hours, 1 day, etc.

**Comment by jiazhai** [comment]
Seems it would be hard to do the counting in current framework. 
If original using multi-level time wheel, it would be easy to do this. 
We could consider how to improve current code.

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.

For open-ended discussion, you can start a thread on https://github.com/apache/pulsar/discussions/categories/general.
