### ISSUE TITLE
copy webpage doc code includes "$"

### ISSUE THREAD

**Issue by xgdgsc** [apache/pulsar#6981]
**Is your feature request related to a problem? Please describe.**
http://pulsar.apache.org/docs/en/security-tls-transport/ click on "copy" includes "$" so I cannot paste and run at once.

**Describe the solution you'd like**
copy should include only code.

**Comment by jiazhai** [comment]
@xgdgsc Thanks for the reporting. Would you like to contribute a PR to fix this?

**Comment by xgdgsc** [comment]
I' d like to. I saw 
```
<code class="language-shell" data-lang="shell" id="code11"><span class="nv no-select">$ </span>crowdin generate</code>
```
 on crowdin' s webpage source. Is there any magic markdown syntax to add $, or we just remove all of $?

**Comment by jiazhai** [comment]
@xgdgsc 
The md docs is at here:
https://github.com/apache/pulsar/tree/master/site2/docs
https://github.com/apache/pulsar/tree/master/site2/website/versioned_docs

**Comment by xgdgsc** [comment]
https://github.com/facebook/docusaurus/issues/1745 Then I would remove all the $?
