### ISSUE TITLE
pulsar-client-all jar file misses dependencies

### ISSUE THREAD

**Issue by iitsoftware** [apache/pulsar#6982]
This is the fat jar file for a pulsar client. It misses these dependencies:

- `org.lz4-lz4-java-1.5.0`
- `org.apache.pulsar-protobuf-shaded-2.1.0-incubating`
- `org.apache.pulsar-pulsar-client-api-2.5.1`

Might be there are more missing, i.e., the bouncy castle jars when using TLS. 

The `pulsar-client-all.jar` should include everything I need to run a pulsar client.

**Comment by jiazhai** [comment]
@iitsoftware Are you using 2.5.1 version? How do you identified these issues?

**Comment by iitsoftware** [comment]
Here is the code:

`package de.iit;

import org.apache.pulsar.client.api.Producer;
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.Schema;

public class Main {

    public static void main(String[] args) {
        try {
            PulsarClient client = PulsarClient.builder()
                    .serviceUrl("pulsar://localhost:6650")
                    .build();
            Producer<String> producer = client.newProducer(Schema.STRING)
                    .topic("my-topic")
                    .create();
            producer.send("My message");
            producer.close();
            client.close();
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
}`

Run with pulsar-client-all only:

`java -cp classes:lib/pulsar-client-all-2.5.1.jar de.iit.Main
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/pulsar/client/api/PulsarClient
`

Add pulsar-client-api:

`java -cp classes:lib/pulsar-client-all-2.5.1.jar:lib/org.apache.pulsar-pulsar-client-api-2.5.1.jar de.iit.Main
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/pulsar/shaded/com/google/protobuf/v241/UninitializedMessageException
`

Add protobuf:

`java -cp classes:lib/pulsar-client-all-2.5.1.jar:lib/org.apache.pulsar-pulsar-client-api-2.5.1.jar:lib/org.apache.pulsar-protobuf-shaded-2.1.0-incubating.jar de.iit.Main
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
`

And so on... You should actually be able to check the content of pulsar-client-all yourself:

`jar -t pulsar-client-all-2.5.1.jar`

And yes, I'm using the latest 2.5.1.

**Comment by iitsoftware** [comment]
The issue still exists in 2.6.1. There seems also a memory leak. When I stop/start a Pulsar consumer, it consumes 100 MB without releasing it.

**Comment by tisonkun** [comment]
Closed as stale. Feel free to open a new issue if it is still relevant to the latest version (2.10.2).
