### ISSUE TITLE
java.util.concurrent.TimeoutException: Idle timeout expired: 300000/300000 ms

### ISSUE THREAD

**Issue by iravishah** [apache/pulsar#6991]
**Describe the bug**
I am using websocket based producer and getting this error after sometime
**java.util.concurrent.TimeoutException: Idle timeout expired: 300000/300000 ms**

**Expected behavior**
How can I make the socket connection alive?

**Comment by jiazhai** [comment]
in broker.conf, there should be a config：
```
# Enable the deletion of inactive topics
brokerDeleteInactiveTopicsEnabled=true

# How often to check for inactive topics
brokerDeleteInactiveTopicsFrequencySeconds=60

```

**Comment by iravishah** [comment]
How should I tweak these options to keep alive the socket connection?
How this will resolve Idle timeout?

**Comment by jiazhai** [comment]
@iravishah sorry, I see, seems this is a different issue.  fir the idle timeout, you need this config.
```
webSocketSessionIdleTimeoutMillis
```
try set and add it into you conf/broker.conf, or conf/websocket.conf

**Comment by iravishah** [comment]
I have configured this parameter but after the defined time it will close the connection right?
So, How can I keep it alive forever? I can't afford the message drop because of reconnection.

**Comment by tisonkun** [comment]
Closed as stale. Feel free to open a new issue if it is still relevant to the latest version.
