### ISSUE TITLE
The `managedLedgerMaxEntriesPerLedger` parameter does not take effect

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar#7001]
**Describe the bug**

conf/standalone.conf:

```
managedLedgerMinLedgerRolloverTimeMinutes=2
managedLedgerMaxEntriesPerLedger=5000
```

I'm testing offload-related functions locally, expecting the ledger to switch early, so the value of managedLedgerMaxEntriesPerLedger is set to 5000, but it seems that the parameter does not take effect. When the data in a ledger reaches 50000, the switch of ledger occurs

**Expected behavior**
The `managedLedgerMaxEntriesPerLedger` parameter take effect

**Screenshots**
![image](https://user-images.githubusercontent.com/20965307/82416329-6a7f4700-9aac-11ea-9c40-48565a4d2d41.png)

**Desktop (please complete the following information):**
 - Pulsar Version: 2.5.1 and 2.5.2

**Comment by jiazhai** [comment]
both of them take effect. it is aimed to not rollover ledgers too frequently.
