### ISSUE TITLE
There are invalid links in the document

### ISSUE THREAD

**Issue by jiawulin001** [apache/pulsar#7002]
1.`REST API` menu is invalid

![捕获11111](https://user-images.githubusercontent.com/14244944/82417785-a0bdc600-9aae-11ea-952b-8010fa15d8c6.PNG)

2.The page opened through the `REST` link of the `Admin Api` page is blank.
![捕获222222](https://user-images.githubusercontent.com/14244944/82416881-5c7df600-9aad-11ea-8e6c-09c65eeb6b99.PNG)

**Comment by Omega-Ariston** [comment]
Yeah, I found that as well. The button in pic 1 only works in English site.
As for the link in pic 2, I reckon it points to the same endpoint as the one in pic 1, which is : https://pulsar.apache.org/admin-rest-api/?version=2.5.1# (got it from English ver.)
