### ISSUE TITLE
Local Runner is looking for connectors only in default location

### ISSUE THREAD

**Issue by itaross** [apache/pulsar#7004]
If this setting is overridden in the configuration file, the local runner will no longer work.

https://github.com/apache/pulsar/blob/cc15ad58583a640ad311fe5a91a9968ed46bf335/pulsar-functions/localrun/src/main/java/org/apache/pulsar/functions/LocalRunner.java#L465

**Comment by itaross** [comment]
We are preparing a pull request for this

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.

IIRC we made some changes on this logic.
