### ISSUE TITLE
Update documentation with possibility to use local run with Pulsar IO sinks and sources

### ISSUE THREAD

**Issue by itaross** [apache/pulsar#7005]
In the documentation is not specified how to debug locally the connectors directly with Java as for their functions counter part (https://pulsar.apache.org/docs/en/io-debug/)

Update the docs with explanation on how to debug the connectors.

This could further improve the development of new connectors and extend people's contribution for the good of pulsar :)

https://github.com/apache/pulsar/blob/cc15ad58583a640ad311fe5a91a9968ed46bf335/pulsar-functions/localrun/src/main/java/org/apache/pulsar/functions/LocalRunner.java#L465

**Comment by wolfstudy** [comment]
@itaross Thanks for your feedback. Do you want to test the pulsar source or pulsar sink using java code in a [similar way](https://pulsar.apache.org/docs/en/functions-debug/#debug-with-localrun-mode)?

For example:

```
    public static void main(String[] args) throws Exception {
        SourceConfig sourceConfig = new SourceConfig();
        sourceConfig.setName("exclamation");
        sourceConfig.setClassName(ExclamationFunction.class.getName());
        LocalRunner sourceLocalRunner = LocalRunner.builder().sourceConfig(sourceConfig).build();
        sourceLocalRunner.start(false);
    }
```

**Comment by itaross** [comment]
> @itaross Thanks for your feedback. Do you want to test the pulsar source or pulsar sink using java code in a [similar way](https://pulsar.apache.org/docs/en/functions-debug/#debug-with-localrun-mode)?
> 
> For example:
> 
> ```
>     public static void main(String[] args) throws Exception {
>         SourceConfig sourceConfig = new SourceConfig();
>         sourceConfig.setName("exclamation");
>         sourceConfig.setClassName(ExclamationFunction.class.getName());
>         ...
>         LocalRunner sourceLocalRunner = LocalRunner.builder().sourceConfig(sourceConfig).build();
>         sourceLocalRunner.start(false);
>     }
> ```

Yes, exactly. I have developed quite few functions and having the ability to debug them boosted my productivity exponentially.
For the connectors I have developed a modified version of the influxdb2 connector and it has been really hard to get it to work.

**Comment by wolfstudy** [comment]
> For the connectors I have developed a modified version of the influxdb2 connector and it has been really hard to get it to work.

Yes, the difference between sources or sinks and functions is that we need to introduce external dependencies to test, but this is usually difficult. So it looks like we don’t have an easy way to debug source or sink operations like a debug function.

**Comment by momo-jun** [comment]
Checked with @freeznet - It has been covered in this [doc page](https://pulsar.apache.org/docs/next/functions-runtime-java-options).
@Anonymitaet we can close this issue.
