### ISSUE TITLE
pulsar/deployment/kubernetes/helm/scripts not included in release tarball

### ISSUE THREAD

**Issue by xgdgsc** [apache/pulsar#7013]
**Describe the bug**
I'm following the doc at http://pulsar.apache.org/docs/en/kubernetes-helm/#step-1-install-pulsar-helm-chart I thought using version from tarball would be the same and found the path `./scripts/pulsar/prepare_helm_release.sh ` doesn' t exist. Is it intended to force using the git version? 
 

**Expected behavior**
tarball includes same files as repo.

**Comment by sijie** [comment]
@xgdgsc  Yes. The helm chart is intended to not include the source tarball. You can use the git version. Currently, we also moved the helm chart to a separated repo: https://github.com/apache/pulsar-helm-chart. We will publish the helm chart release to the website in the next release.

**Comment by tisonkun** [comment]
Closed as information delivered.
