### ISSUE TITLE
Webhook Size is always zero

### ISSUE THREAD

**Issue by rajasekar33** [apache/pulsar#7019]
I am locally running Apache pulsar and beam for testing purpose. 

Changes I have made:
1.pulsarAsDb option and added dbname, pulsarbrokerURL and all. but when run this application 
console print always showing like **webhook size is 0**

Did I missed something.... I am not sure about the webhook registration with pulsarDB... Tram please help me solve this problem 

After post request I am getting below error:
**dblistener reader unmarshal error invalid character 'T' looking for beginning of value  app=pulsardb**

**Comment by sijie** [comment]
@rajasekar33 Can you clarify which component you are using? There is no "beam" component in pulsar.

**Comment by rajasekar33** [comment]
Hi Team 

Ming Luo helped me to solve this problem, I haven't registered webhook with DB thats why it was showing zero

**Comment by anand-ftc** [comment]
Hi @rajasekar33  can you help me I am getting the same error in the logs continously
