### ISSUE TITLE
In 2.5.2 Prometheus out metrics are always zero

### ISSUE THREAD

**Issue by cdbartholomew** [apache/pulsar#7022]
**Describe the bug**
In 2.5.2, the Prometheus metrics that measure the out rate/throughput for topics are always zero. This is a regression from 2.5.1. Specifically, these two metrics seems to always be zero:

* pulsar_throughput_out
* pulsar_rate_out

Here is a graph while publishing and consuming at the same time so that in rate == out rate:

![image](https://user-images.githubusercontent.com/22917476/82732655-823d1200-9cdc-11ea-9795-7e911ca0cfbb.png)

The green line is in rate and the yellow line is out rate. The first part of the graph is running 2.5.2 and no out rate or throughput is recorded. Then I downgraded to 2.5.1. As you can see, the yellow line jumps up to be even with the green line, which is what I expect based on the producers/consumers. Then I upgraded back to 2.5.2 and the yellow line goes back to zero even though the producers/consumers configuration is unchanged.

Note that the statics on the topics correctly report the out rate. This is only a problem with the Prometheus metrics.

Docker image: apachepulsar/pulsar-all:2.5.2

**To Reproduce**
1. Connect to any topic so that its out rate is not zero.
2. Query the metrics in Prometheus.
3. Metrics always report zero.

**Expected behavior**
Metrics to accurately report the out rate and throughput.

**Comment by sijie** [comment]
The problem has been fixed as part of #7082
