### ISSUE TITLE
Support shared subscriptions on compacted topics

### ISSUE THREAD

**Issue by lukestephenson** [apache/pulsar#7028]
**Is your feature request related to a problem? Please describe.**
I'm evaluating Pulsar. A primary use case of mine is large (more than 1 billion unique keyed messages) compacted topics. To handle these efficiently, I had planned to make use of multiple partitions on the brokers, as well as have multiple consumers with a "key shared" subscription.

Currently the pulsar client rejects setting up a subscription on a compacted topic unless the subscription type is exclusive or failover.
https://github.com/apache/pulsar/blob/v2.5.2/pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java#L309-L315

**Describe the solution you'd like**
Ability to have multiple consumers sharing a subscription to a compacted topic (partitioned or not partitioned).

**Describe alternatives you've considered**
Allocate more resources to a single consumer. Might not be easy in kubernetes, we might get to a point where the pod needs more resources than the nodes in our cluster.  I don't believe this is the correct solution.  We should be building services that can scale out to many small nodes from the beginning.

I'd be happy as well with each consumer being allocated a different partition from the topic (i.e. similar to what Kafka does).

Update:
Another alternative is to manually assign multiple consumers different partitions. It seems possible  from this comment https://github.com/apache/pulsar/issues/3098#issuecomment-443101901.  Although I've not tested to see if this works with `readCompacted(true)`.  However I'd only want to do this as a short term solution.

**Additional context**
Initially asked on pulsar slack https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1590374999408100

**Comment by sijie** [comment]
@lukestephenson 

If you use a partitioned topic, the data is already partitioned. each partition will be compacted if you enable compaction. So each partition can have its own compacted state. Then you can read the compacted topic use Failover subscription. This would achieve the exact same thing as you did in Kafka.

**Comment by gmethvin** [comment]
Is this limitation documented somewhere? I don't see it in https://pulsar.apache.org/docs/en/concepts-topic-compaction/. We should probably update that to clarify.

**Comment by gmethvin** [comment]
Is there a technical reason why we can't use shared or key_shared on a compacted topic? It seems to make sense if we don't care about consuming in order, or we only care about consuming in order per key (key_shared) and want to avoid the overhead of having many partitions.

**Comment by lukestephenson** [comment]
I'm able to get the desired behaviour I needed using a Failover subscription.  Feel free to close this issue, or keep it around if it's still a worthwhile change.  Thanks

**Comment by hozumi** [comment]
Hi, I'm thinking the same use case discussed here.
It would be nice if users could manage the load by simply adding or removing consumers to a single logical subscription, like turning a faucet, instead of manually assigning subscriptions to underlying partitions.

**Comment by miton18** [comment]
Is it a planned feature ?

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
