### ISSUE TITLE
Ledger dir is redundant when using an existing bookkeeper cluster

### ISSUE THREAD

**Issue by ayolivia** [apache/pulsar#7033]
**Describe the bug**
Currently, we can use an existing bookkeeper cluster by parameter `bookkeeperMetadataServiceUri` (based master branch), however, the ledger dir (`/ledgers`) is still created in pulsar metadata store when initialize cluster metadata. This may confuse some users when trying to locate bookie nodes.

**Expected behavior**
Create the ledger dir when necessary.

**Comment by zhanghaou** [comment]
I will fix it. :)

**Comment by codelipenghui** [comment]
Thanks @zhanghaou

**Comment by murong00** [comment]
@codelipenghui @zhanghaou  I think we should make a discussion, I hava already fixed this in my dev branch by adding a option `--bookkeeper-metadata-service-uri` some weeks ago, but I am not so sure it is appropriate. How about the proposal?
