### ISSUE TITLE
Producers failed to open when leader broker shut down

### ISSUE THREAD

**Issue by k2la** [apache/pulsar#7041]
When a leader broker shut down, producers that connected with the broker failed to open on a new broker.

According to the leader broker log, the broker unloaded bundles and closed producers.
Also, according to logs of other brokers, another broker became leader broker and bundles were loaded.

However, producers that connected with the old leader broker reconnected with a new broker but some producers of ones failed to open on the new broker.

After the producers reconnected with the new broker, they didn't send `CommandProducer` messages and stop.
https://github.com/apache/pulsar/blob/d55bc00f34a2fa763a3756fa0adbb1366ae319bd/pulsar-common/src/main/proto/PulsarApi.proto#L406-L430

#### Expected behavior
When producers reconnect with a new broker, open on the broker.

#### Actual behavior
Some producers failed to open on the new broker.

#### Steps to reproduce
We tried but haven't reproduced yet.

#### System configuration
OS(Broker): CentOS 7.7
Pulsar Broker: 2.3.2
Pulsar Client Java: 2.3.2

**Comment by massakam** [comment]
This issue should be fixed by the following PRs:
- https://github.com/apache/pulsar/pull/7096
- https://github.com/apache/pulsar/pull/7126
- https://github.com/apache/pulsar/pull/7200
