### ISSUE TITLE
Make WebSocketService.MaxTextFrameSize configurable

### ISSUE THREAD

**Issue by d-eggert** [apache/pulsar#7049]
**Is your feature request related to a problem? Please describe.**
We use the websocket interface to pulsar. Our current use case demands the transmission of big messages (10MB or even more), which is not possible due to the hardcoded limit in `WebSocketService`

**Describe the solution you'd like**
Make this value configurable, e.g. via websocket.conf

**Describe alternatives you've considered**
Maybe increase the hardcoded default.

**Additional context**
None.

**Comment by zhanghaou** [comment]
Thanks for your feedback, I will fix it.
