### ISSUE TITLE
[python] pulsar-client@2.5.2's dep on enum34@1.1.9 may break build systems

### ISSUE THREAD

**Issue by curtiscook** [apache/pulsar#7050]
Enum34 appears to have had a regression of the below issue in 1.1.9 https://bitbucket.org/stoneleaf/enum34/issues/31/make-the-install-a-noop-on-python36

This breaks builds due to `AttributeError: module 'enum' has no attribute 'IntFlag'`

Related poetry issue: https://github.com/python-poetry/poetry/issues/1122#issuecomment-628037127

Suggest using enum34@1.1.8 until this is fixed

**Comment by sijie** [comment]
@curtiscook since you have already found the issue, are you interested in submitting a pull request to address the issue?

**Comment by curtiscook** [comment]
I looked into this, and it appears that 1.1.8 has a breaking change for python27, which caused the 1.1.9 upgrade. https://github.com/apache/pulsar/pull/6401

I think maybe the best course of action is to leave this as-is and hope that enum34 fixes their bug soon. 

In the interim, maybe we keep this issue open for visibility and close it once enum34 fixes their library? It appears to only directly affect package managers (I was able to directly pip install without issue). Additionally should be able to setup.py only requires enum34 during a python2 install

**Comment by curtiscook** [comment]
It looks like it's possible to work around this issue by upgrading pip. Going to close it

**Comment by languitar** [comment]
This issue also make downstream projects based on poetry fail. The recommended way to fix this ((discussed in this issue)[https://github.com/python-poetry/poetry/issues/1122]) is by declaring the dependency with an environment marker in `setup.py` to ensure that enum34 is only pulled into the dependency tree when it is really needed.

**Comment by coryvirok** [comment]
For anyone else looking for a fix:

I use poetry + pulsar-client and was able to get around this issue by first running `pip install --upgrade pip` followed by `poetry install`.
