### ISSUE TITLE
pulsar client 2.5.2 cli does not support subscription-position when running consumer

### ISSUE THREAD

**Issue by sakthi-prasad** [apache/pulsar#7056]
When running pulsar client cli command for consumer, --subscription-position is shown as unknown option

Note pulsar client version: 2.5.2

Run the below command to start a consumer 
```
./pulsar-client consume "persistent://public/default/my-partitioned-topic-partition-0" -s subcribname  -t Exclusive --subscription-position Earliest
```
            OR
```
./pulsar-client consume "persistent://public/default/my-partitioned-topic-partition-0" -s subcribname  -t Exclusive -p Earliest
```

**Throws below error**
```
Unknown option: --subscription-position
Consume messages from a specified topic
Usage: consume [options] TopicName
  Options:
    --hex
       Display binary messages in he
```

**Expected behavior**
It should allow the option --subscription-position as document for pulsar 2.5.2

**Additional context**
```
I would like to know if the --subscription-position as Earliest will consume all the messages that was sent to topic before starting consumer with the subscriber?
For e.g
1.Create a topic
2.send data to topic "A"
3 start consumer with option --subscription-position as Earliest
4. send data to topic "B"
```

Will I be able to consume the messages sent in step 2 i.e "A" or I will be able to consume only messages sent in step 4 onwards i.e"B"

**Comment by sijie** [comment]
@sakthi-prasad I think the documentation of release 2.5.2 was cut by using the latest master. @jiazhai is looking into fixing the issue.

**Comment by sijie** [comment]
The doc issue has been fixed.
