### ISSUE TITLE
Pulsar Producing Hangs when Kubernertes Node Restarts

### ISSUE THREAD

**Issue by irairdon** [apache/pulsar#7059]
When running pulsar on Kubernetes if you reboot a Kubernetes node any client producing will hand and be unable to produce new messages. 

**To Reproduce**
1. Install helm chart for Pulsar on kubernetes
2. Use pulsar-perf tool to start producing messages on a single topic. 
3. reboot one of the kubernetes nodes.
4. I have not found errors listed but the pulsar-perf tool will start showing 0 messages produced.
5. If you kill the broker pods one at a time eventually the producer will start producing messages again. 

**Expected behavior**
I expect pulsar not to hang if a kuberentes node reboots. 

**Desktop (please complete the following information):**
 - Pulsar 2.5.2
 - Kubernetes 1.13

**Additional context**
I haven't been able to reproduce be restarting individual services. It only occurs in a node restart. When the current producer is hung you can still create new topics and new producers that will not see the hang so it is related only to existing active topics.

**Comment by larslorenzen** [comment]
Don't know if it is related but we had the same problem after a node restart. 
The following logs came from the producer:
`[persistent://mytenant/mynamespace/mytopic] [my-pod-5c5c89dfd4-c9rsn-mytopic] Failed to create producer: Producer is already present on the connection`

The problem was only resolved by restarting the producing pod.

**Comment by sijie** [comment]
@larslorenzen Your issue is different. The "producer is already presented" is a race condition when producer disconnects and reconnects. The problem has been addressed in recent releases.

**Comment by sijie** [comment]
This issue has been fixed by #7401
