### ISSUE TITLE
Pulsar SQL cannot get the latest message

### ISSUE THREAD

**Issue by DGBStarSky** [apache/pulsar#7076]
**Describe the bug**
Pulsar SQL cannot get the latest message of topic.

**To Reproduce**
I use pulsar sql query messages, but  cannot get the latest message of topic.I have configured the parameters in broker.conf, but no effect.

**Screenshots**
![微信图片_20200528112800](https://user-images.githubusercontent.com/35715373/83095621-53f17500-a0d6-11ea-8d43-d250304698ba.png)

**Desktop (please complete the following information):**
 ubuntu 18.04

**Additional context**
chart deployment
2.5.1

**Comment by opera33** [comment]
Tested this in 2.5.2 as well in Standalone mode, not getting latest data from Pulsar SQL

Previously opened this #6884

**Comment by javamrGithub** [comment]
I set up bookkeeperExplicitLacIntervalInMills in broker.conf and standalone.conf, but still couldn't get the latest news

**Comment by javamrGithub** [comment]
I set up bookkeeperExplicitLacIntervalInMills in broker.conf and standalone.conf, but still couldn't get the latest news

**Comment by wen-qiang001** [comment]
I set up bookkeeperExplicitLacIntervalInMills in broker.conf and standalone.conf, but still couldn't get the latest news

**Comment by wen-qiang001** [comment]
I set up bookkeeperExplicitLacIntervalInMills in broker.conf and standalone.conf, but still couldn't get the latest news。

**Comment by bleacha870721** [comment]
@sijie  May I know the current progress of this issue? I still couldn't get the latest messages in 2.6.0

**Comment by sijie** [comment]
@bleacha870721 the setting requires some configuration changes in the bookies' side (e.g. bump journal version).  We need to update the documentation about the full process.

**Comment by ErikJansenIRefact** [comment]
@sijie Any idea when the documentation is updated. We are in the middle of testing Presto with Pulsar.

**Comment by bleacha870721** [comment]
> @bleacha870721 the setting requires some configuration changes in the bookies' side (e.g. bump journal version). We need to update the documentation about the full process.

 Any idea when the documentation is updated？

**Comment by rec7y33** [comment]
bump

**Comment by RobDickinson** [comment]
@sijie I'd pay a cash bounty for a solution -- doesn't need to be full documentation, but just pointing us in the right direction.  We've been trying to figure this out and would really appreciate your help!  And we'd be happy to contribute this back as a pull request to the docs as well.

Anybody else on this thread -- same offer applies, happy to pay you for your time if you can share the answer on this!

**Comment by sijie** [comment]
@RobDickinson I replied in the email. 

for ExplicitLac to work, you need to configure the following settings in bookies:

journalFormatVersionToWrite=6
fileInfoFormatVersionToWrite=1

and then turn on the explicit lac interval on broker.

bookkeeperExplicitLacIntervalInMills=1000

**Comment by bleacha870721** [comment]
@sijie i have tried this on pulsar 2.5.2：
for ExplicitLac to work, you need to configure the following settings in bookies:

journalFormatVersionToWrite=6
fileInfoFormatVersionToWrite=1

and then turn on the explicit lac interval on broker.

bookkeeperExplicitLacIntervalInMills=1000

But still cannot get latest message by pulsar sql.

**Comment by zymap** [comment]
It seems the bookkeeper client still uses the piggyback lac. We need the bookkeeper pr https://github.com/apache/bookkeeper/pull/1901, which can make pulsar read the explicit LAC from the bookkeeper. After this change merged, then update the pulsar to use that bookkeeper version. Then setting the `bookkeeperExplicitLacIntervalInMills` in the broker configuration file,  pulsar SQL can query the last message.

**Comment by codelipenghui** [comment]
Close via #8635.

**Comment by Raven888888** [comment]
> 
> 
> @RobDickinson I replied in the email.
> 
> for ExplicitLac to work, you need to configure the following settings in bookies:
> 
> journalFormatVersionToWrite=6
> fileInfoFormatVersionToWrite=1
> 
> and then turn on the explicit lac interval on broker.
> 
> bookkeeperExplicitLacIntervalInMills=1000

Tried the above for a pulsar cluster of 3 nodes. Still unable to get the latest row. Am using 2.7.0 pulsar release.

Anybody has any idea? Has this been verified on a cluster setup?

Thank you
