### ISSUE TITLE
[website] Make each release contains all the content into versioned directory

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#7083]
currently, website is released in a versioned way. but each versioned directory, contains only part of md files. This is hard to maintain the content of each version. 
It would be better to make each versioned directory contain all the md files.

![image](https://user-images.githubusercontent.com/6348208/83126992-2d4e3100-a10c-11ea-816b-610bca1371fd.png)

**Comment by jiazhai** [comment]
@tuteng Would you please help create a script to make the website release atomic?

**Comment by Jennifer88huang** [comment]
@jiazhai Thank you for raising the issue. It's ok to contain all the .md file in each versioned folder. However, it's time-consuming to maintain those files, meanwhile, it will also confuse external contributors if they want to contribute some content. @Huanli-Meng and @Jennifer88huang will research whether it's OK to add conditional tags in those .md files, and will give feedback later.

**Comment by Jennifer88huang** [comment]
@jiazhai could we create different branches to manage different release versions? For example, when v2.6.0 is ready to release, we can create a branch named `release-2.6` or `release-2.6.0`, and build website with this branch.
- If we have new features for 2.7.0, we add the new contents in the master branch.
- If we have new features for 2.6.x, we create a new branch `release-2.6.1` based on `release-2.6.0` branch.

**Comment by Jennifer88huang** [comment]
When we or external contributors want to modify some content in different releases, they can checkout the release branch and modify files in that branch directly.

**Comment by Anonymitaet** [comment]
We've already implemented this.

**Comment by Anonymitaet** [comment]
@signormercurio thanks for your reminder!
