### ISSUE TITLE
[Helm] Proxy started throwing netty errors even on a new cluster

### ISSUE THREAD

**Issue by ckdarby** [apache/pulsar#7089]
**Describe the bug**
When starting up a new cluster we're getting errors from the proxy related to netty thread allocation problems but I'm confused as the docker image is still using the tagged 2.5.0 and I don't see any pulled in external libs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Helm install
2. k logs dga-detection-pulsar-proxy-0

**Expected behavior**
Proxy to come up as expected

**Screenshots**
k logs with the stacktrace, [netty.txt](https://github.com/apache/pulsar/files/4697235/netty.txt).

**Desktop (please complete the following information):**
 - Kubernetes 1.16
 - helm v3.1.1
- Using helm chart from apache/pulsar-helm-chart

**Comment by ckdarby** [comment]
So, we rolled back everything our side, helm charts back to the known version, nuked the whole k8s cluster, made a new K8s cluster, etc etc. Eventually the only difference we had was a node group had been changed from r5.large to r5.4xlarge to test out #7058 

Looking at Netty docs @nickelozz found
>  The number of threads you need is determined by the components within Jetty you start to use and the hardware present on your system (the number of cpu cores and network interfaces impacts nio and consequently your thread requirements).

He was also nice enough to find this from AWS docs:
![Selection_736](https://user-images.githubusercontent.com/220283/83186198-29191800-a0fa-11ea-8b0f-430abdb4e576.png)

I looked through the Pulsar proxy code, [here](https://github.com/apache/pulsar/blob/master/pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java#L466) and see that it doesn't factor in anything related to interfaces :sob:

**Comment by ckdarby** [comment]
We changed the numThreads in the helm chart from 8->12 and the proxy came up.

We'll make a PR on the apache/pulsar-helm-chart to allow this to be exposed out in the values.yaml.

**Comment by sijie** [comment]
@ckdarby This seems to be a known issue related to jetty. You  need to adjust the number threads to be more than cpu cores.

**Comment by sijie** [comment]
So you need to adjust the settings based on your machine type.
