### ISSUE TITLE
[docker] too many repeated pulsar-all image configs in k8s helm deployment

### ISSUE THREAD

**Issue by dockerzhang** [apache/pulsar#7112]
**Describe the bug**
All releated pulsar components are built in pulsar-all image, but we have to change at least 8  places for using private repositories to set pulsar-all in helm chart, It is redundant.

**To Reproduce**
it's not a bug but tiny enhancement for k8s helm deployment.

**Comment by jiazhai** [comment]
@dockerzhang, thanks for reporting this issue. current way  may be easier for user to config different components using different image

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Helm Chart has been permanently moved to https://github.com/apache/pulsar-helm-chart. If it's still relevant, please open an issue there.
