### ISSUE TITLE
when i start broker, i met that pulsar read broker.conf,initialize backlogQuotaDefaultRetentionPolicy failed

### ISSUE THREAD

**Issue by Gray-Fullbuster** [apache/pulsar#7134]
pulsar version=2.5.0
jdk =1.8
this is start broker error information:
./pulsar broker
[AppClassLoader@18b4aac2] info AspectJ Weaver Version 1.9.2 built on Wednesday Oct 24, 2018 at 15:43:33 GMT
[AppClassLoader@18b4aac2] info register classloader sun.misc.Launcher$AppClassLoader@18b4aac2
[AppClassLoader@18b4aac2] info using configuration file:xxx/pulsar/lib/org.apache.pulsar-pulsar-zookeeper-utils-2.5.0.jar!/META-INF/aop.xml
[AppClassLoader@18b4aac2] info using configuration file:xxx/pulsar/lib/org.apache.pulsar-pulsar-zookeeper-2.5.0.jar!/META-INF/aop.xml
[AppClassLoader@18b4aac2] info register aspect org.apache.pulsar.broker.zookeeper.aspectj.ClientCnxnAspect
[AppClassLoader@18b4aac2] info register aspect org.apache.pulsar.zookeeper.FinalRequestProcessorAspect
[AppClassLoader@18b4aac2] info register aspect org.apache.pulsar.zookeeper.ZooKeeperServerAspect
2020-06-01 08:10:34,251 [sun.misc.Launcher$AppClassLoader@18b4aac2] error Uncaught exception in thread main: failed to initialize backlogQuotaDefaultRetentionPolicy field while setting value producer_request_hold

I have not met this  error before. backlogQuotaDefaultRetentionPolicy is Related to pular start？I can't understant.

**Comment by sijie** [comment]
@Gray-Fullbuster Did you change `broker.conf` before?
