### ISSUE TITLE
Cannot resolve import in BatchSourceExecutor

### ISSUE THREAD

**Issue by aloyszhang** [apache/pulsar#7149]
**Describe the bug**
Cannot resolve dependency of `org.apache.pulsar.functions.utils.Reflections` in BatchSourceExecutor, since `Reflections ` has move to pulsar-common.
**To Reproduce**
pull the master 
**Expected behavior**
should import from the right path

**Screenshots**
![image](https://user-images.githubusercontent.com/48062889/83605735-ff089f80-a5aa-11ea-85de-0e066f75b99a.png)

**Comment by codelipenghui** [comment]
There are some conflicts after merge some PRs, I'm working on fixing them.

**Comment by aloyszhang** [comment]
@codelipenghui Yes, I had found some conflicts too. 
I think rebase the master branch before PR and merge PR in time  is helpful to reduce these conflicts.

**Comment by sijie** [comment]
It is fixed now.
