### ISSUE TITLE
[proxy] pulsar-proxy Caught Connection refused error 

### ISSUE THREAD

**Issue by dockerzhang** [apache/pulsar#7153]
**Describe the bug**
If i produce message for a while, it caught connection refused error
![image](https://user-images.githubusercontent.com/18047329/83620732-55340d80-a5c0-11ea-846f-3ab77dea0c1e.png)
And then i rebuilt proxy pod by delete pulsar-proxy-0/1/2, the refused error will disappear.

**Version**
2.5.2 deployed by k8s helm

**To Reproduce**
1. kubectl exec -it statefulset/pulsar-toolset 
2. execute './bin/pulsar-perf produce fl-tenant/fl-namespace/tt   --rate 10000 -s 5120000 -z LZ4'

**Expected behavior**
If i produce message in pulsar-broker by  pulsar-perf, it works fine.
it caught connection refused error if using pulsar-proxy in pulsar-toolset.

**Comment by sijie** [comment]
@dockerzhang was the proxy restarted during your test?

**Comment by dockerzhang** [comment]
@sijie yes, the proxy restarted during test. 
I check the log  exited of proxy container, it's exited for OOM error. 
![image](https://user-images.githubusercontent.com/18047329/83707408-84905c00-a64c-11ea-880f-271edd7eca18.png)
I increased 2G to 8G and test again, test recovered.
Thanks @sijie , this issue can close now.
