### ISSUE TITLE
Mistake in Pulsar Function Documentation

### ISSUE THREAD

**Issue by skothari-tibco** [apache/pulsar#7158]
**Describe the bug**
In the documentation of pulsar function, under the Logger section there is an mistake in "Go" code sample . Go code sample states  `"github.com/apache/pulsar/pulsar-function-go/log"` in the import but in reality it is  `"github.com/apache/pulsar/pulsar-function-go/logutil"`

**To Reproduce**
1. Go to   `https://pulsar.apache.org/docs/en/functions-develop/#logger`
2. Click on 'Go'

**Expected behavior**
The import section of the code sample should have `"github.com/apache/pulsar/pulsar-function-go/logutil"`

**Screenshots**
<img width="833" alt="Screen Shot 2020-06-03 at 7 48 15 PM" src="https://user-images.githubusercontent.com/43142501/83699847-2c694380-a5d3-11ea-917c-03b2005b8d6a.png">

**Comment by sijie** [comment]
@wolfstudy can you double-check if this is a problem?

**Comment by wolfstudy** [comment]
> @wolfstudy can you double-check if this is a problem?

Sure, will do this

**Comment by wolfstudy** [comment]
@skothari-tibco Thanks your feedback, will fix it.
