### ISSUE TITLE
Fix problems with managed-ledger properties.

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#7161]
### Fix problems with managed-ledger properties.

Refer to https://github.com/apache/pulsar/pull/7054#issuecomment-637843729

- It's not checking that there no other metadata operations in place. That will result in ZK bad version errors.
- It's writing the metadata without updating the in-memory version that the managed ledger keeps. This will result in a managed ledger fenced error each time a property is set, forcing the topic to get closed.
- Why do we need to re-read the metadata from store? We already have that metadata and its corresponding version in memory.
- Finally, from the API is not clear what happens if there are already some properties and I just want to add a new one.

**Comment by zhanghaou** [comment]
I will fix it.

**Comment by jiazhai** [comment]
Thanks @zhanghaou for the help.

**Comment by zhanghaou** [comment]
I have solved the Problem1 and 4 in the PR[https://github.com/apache/pulsar/pull/7222](https://github.com/apache/pulsar/pull/7222), please take a look. 

Problem 2：
The in-memory version of propertiesMap is updated by callback of store.asyncUpdateLedgerIds, is there something wrong with my understanding?
Problem 3：
Re-read the metadata from store is used when the managedLedger is reloaded and we need to reset the propertiesMap in memory.

**Comment by zongtanghu** [comment]
The problem 2 and 3 you said, you put forward other two issues maybe better?

**Comment by liangyuanpeng** [comment]
What's the status of this issue? look like finished.

**Comment by codelipenghui** [comment]
@liangyuanpeng This issue is fixed by #7357
