### ISSUE TITLE
I didnt find the Schema strategy I wanted

### ISSUE THREAD

**Issue by yujun32** [apache/pulsar#7166]
I need a Schema strategy like this:
     Producter can add fields based on business development, but old fields cannot be deleted and modified; (like protobuf).
     Consumers can consume all versions of data with various versions of Schema, and will lack new fields that are newer than the current version.

     I found the pulsar documentation. There is no such Schema strategy that only allows adding fields, and existing fields cannot be deleted and modified, and Consumer can consume all version data without upgrading.

**Comment by jiazhai** [comment]
https://pulsar.apache.org/docs/en/schema-evolution-compatibility/#how-does-pulsar-support-schema-evolution
@yujun32 Seems you want a `BACKWARD_TRANSITIVE`?

**Comment by yujun32** [comment]
> [https://pulsar.apache.org/docs/en/schema-evolution-compatibility/#how-does-pulsar-support-schema-evolution ](https://pulsar.apache.org/docs/en/schema-evolution-compatibility/#how-does-pulsar-support-schema-evolution)
> @ yujun32似乎您想要一个`BACKWARD_TRANSITIVE`？

Thank you for answering,

BACKWARD_TRANSITIVE is still a bit different from the strategy I want:
1. Fields can only be added but not modified or deleted.
2. Consumer can consume the latest data without upgrading.
These two points are just the principles that our other services follow, so that the design rules will help our security upgrade and fault tolerance

**Comment by yujun32** [comment]
> https://pulsar.apache.org/docs/en/schema-evolution-compatibility/#how-does-pulsar-support-schema-evolution
> @yujun32 Seems you want a `BACKWARD_TRANSITIVE`?


Thank you for answering,

BACKWARD_TRANSITIVE is still a bit different from the strategy I want:
1. Fields can only be added but not modified or deleted.
2. Consumer can consume the latest data without upgrading.
These two points are just the principles that our other services follow, so that the design rules will help our security upgrade and fault tolerance

**Comment by Huanli-Meng** [comment]
@jiazhai , any more process about this issue?

**Comment by tisonkun** [comment]
Closed as no response. No news is good news :)
