### ISSUE TITLE
Dashboard not populated with any details like Topics/Message

### ISSUE THREAD

**Issue by sivavijay13** [apache/pulsar#7185]
Started Pulsar and pulsar dashboard both in docker

Created topics in pulsar and sent few messages to topics , waited for long time both message and topic created not showing in dashboard
![image](https://user-images.githubusercontent.com/46527272/83911883-b14a8d80-a78a-11ea-82c9-0ff8ebd6e1ca.png)
Log:
Starting Pulsar dasboard

+ /pulsar/init-postgres.sh

+ rm -rf '/data/*'

+ chown -R postgres: /data

+ chmod 700 /data

+ sudo -u postgres /usr/lib/postgresql/9.6/bin/initdb /data/

The files belonging to this database system will be owned by user "postgres".

This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".

The default database encoding has accordingly been set to "UTF8".

The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /data ... ok

creating subdirectories ... ok

selecting default max_connections ... 100

selecting default shared_buffers ... 128MB

selecting dynamic shared memory implementation ... posix

creating configuration files ... ok

running bootstrap script ... ok

performing post-bootstrap initialization ... ok

syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections

You can change this by editing pg_hba.conf or using the option -A, or

--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

/usr/lib/postgresql/9.6/bin/pg_ctl -D /data/ -l logfile start

+ sudo -u postgres /etc/init.d/postgresql start

Starting PostgreSQL 9.6 database server: main.

+ sudo -u postgres psql --command 'CREATE USER docker WITH PASSWORD '\''docker'\'';'

CREATE ROLE

+ sudo -u postgres createdb -O docker pulsar_dashboard

+ cd /pulsar/django

+ ./manage.py migrate

Operations to perform:

Apply all migrations: admin, auth, contenttypes, sessions, stats

Running migrations:

Applying contenttypes.0001_initial... OK

Applying auth.0001_initial... OK

Applying admin.0001_initial... OK

Applying admin.0002_logentry_remove_auto_add... OK

Applying contenttypes.0002_remove_content_type_name... OK

Applying auth.0002_alter_permission_name_max_length... OK

Applying auth.0003_alter_user_email_max_length... OK

Applying auth.0004_alter_user_username_opts... OK

Applying auth.0005_alter_user_last_login_null... OK

Applying auth.0006_require_contenttypes_0002... OK

Applying auth.0007_alter_validators_add_error_messages... OK

Applying auth.0008_alter_user_username_max_length... OK

Applying sessions.0001_initial... OK

Applying stats.0001_initial... OK

Applying stats.0002_support_deleted_objects... OK

+ supervisord -n

/usr/lib/python2.7/dist-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.

'Supervisord is running as root and it is searching '

2020-06-05 18:20:33,129 CRIT Supervisor running as root (no user in config file)

2020-06-05 18:20:33,129 INFO Included extra file "/etc/supervisor/conf.d/supervisor-app.conf" during parsing

2020-06-05 18:20:33,176 INFO RPC interface 'supervisor' initialized

2020-06-05 18:20:33,180 CRIT Server 'unix_http_server' running without any HTTP authentication checking

2020-06-05 18:20:33,181 INFO supervisord started with pid 71

2020-06-05 18:20:34,187 INFO spawned: 'nginx' with pid 74

2020-06-05 18:20:34,189 INFO spawned: 'collector' with pid 75

2020-06-05 18:20:34,199 INFO spawned: 'uwsgi' with pid 76

2020-06-05 18:20:40,027 INFO success: nginx entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)

2020-06-05 18:20:40,028 INFO success: collector entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)

2020-06-05 18:20:40,028 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)

**Comment by sivavijay13** [comment]
I used both latest version of dashboard and 2.4.2 based on some comments in issues section

**Comment by sijie** [comment]
@sivavijay13 pulsar dashboard is deprecated in favor of using Pulsar Manager.

http://pulsar.apache.org/docs/en/administration-pulsar-manager/

https://github.com/apache/pulsar-manager
