### ISSUE TITLE
Make ledger rollover check task internal

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#7195]
##7111 introduced ledger rollover task to ensure the ledger rollover as expected. The task should be the internal task of the managed ledger.

This issue is tracking move the ledger rollover check task to managed ledger internal.

**Comment by hangc0276** [comment]
My team will move the rollover task to the internal task of the managed ledger soon. @wuzhanpeng

**Comment by codelipenghui** [comment]
Thanks @hangc0276

**Comment by codelipenghui** [comment]
@hangc0276 Are you working on implement this fix?
