### ISSUE TITLE
presto’s catalog config [ pulsar.zookeeper-uri] not support multi uris

### ISSUE THREAD

**Issue by zhaoyu1989** [apache/pulsar#7197]
**Describe the bug**
When I use pulsar-sql, I want to config pulsar.zookeeper-uri with multi uris and seperate by 
divide by semicolon, currently pulsar.properties doesnot support。

**To Reproduce**
1. Go to '/apache-pulsar-2.5.0/conf/presto/catalog/pulsar.properties'
2. config pulsar.properties with 'pulsar.zookeeper-uri=kmr-234487a9-gn-279fcec2-core-1-001:2181,kmr-234487a9-gn-279fcec2-core-1-002:2181,kmr-234487a9-gn-279fcec2-core-1-003:2181'
3. start pulsar-sql
4. See error: cant found root path in zk

**Screenshots**
![image](https://user-images.githubusercontent.com/10680639/83985449-e6620600-a96b-11ea-9242-1b539bad227d.png)
![image](https://user-images.githubusercontent.com/10680639/83985461-f24dc800-a96b-11ea-8e33-1f86326363ff.png)

**Comment by sijie** [comment]
this has been fixed in #6947 and will be released to 2.6.0
