### ISSUE TITLE
Using entryLogPerLedgerEnabled  feature will got NoSuchMethodError

### ISSUE THREAD

**Issue by wangjialing218** [apache/pulsar#7202]
**Describe the bug**
using entryLogPerLedgerEnabled feature by set `entryLogPerLedgerEnabled=true` in bookkeeper.conf and produce some message, when bookie try to flush enties to entrylogfile,  got NoSuchMethodError.

`java.lang.NoSuchMethodError: org.apache.commons.lang3.mutable.MutableInt.incrementAndGet() at org.apache.bookkeeper.bookie.EntryLogManagerForEntryLogPerLedger$EntryLogsPerLedgerCounter.openNewEntryLogForLedger`

**Additional context**
It seems MutableInt.incrementAndGet() is available from commons-lang3(v3.5) but Pulsar is using  commons-lang3(v3.4)  

**Expected behavior**
As BookKeeper is using commons-lang3(v3.6), Pulsar shoud also update to v3.6

**Comment by jiazhai** [comment]
Thanks @wangjialing218 for the issue and PR
