### ISSUE TITLE
Can i use pattern Regex in non-persistent mode?

### ISSUE THREAD

**Issue by zhijianfree** [apache/pulsar#7205]
**Describe the bug**
i use java client to subscribe pattern  topic(like: non-persistent://iot/yy/hu/.*), when i publish a message by "non-persistent://iot/yy/hu/2" , i cannot get the message. but in persistent mdoe i can receive.

**To Reproduce**
use this command to publish message
`./pulsar-client produce non-persistent://iot/yy/hu/2 --messages "message1"`

**Screenshots**
i got the message from broker log:
![image](https://user-images.githubusercontent.com/21210211/84025525-54371d80-a9be-11ea-88bc-b62881ebfe0f.png)

maybe is due to :
`[pulsar-io-50-17] WARN  org.apache.pulsar.broker.service.BrokerService - No autoTopicCreateOverride policy found for non-persistent://iot/yy/hu/2`

**Comment by sijie** [comment]
@zhijianfree I think the feature should work. It seems that you are using a v1 naming pattern that contains the cluster component.  Can you try the v2 naming pattern? http://pulsar.apache.org/docs/en/pulsar-2.0/#no-cluster-component

**Comment by zhijianfree** [comment]
i try  to subscribe this public topic to receive message :
`non-persistent://public/default/hu/.*"`

and publish message:
![image](https://user-images.githubusercontent.com/21210211/84244670-91262000-ab36-11ea-8353-664c6c1c6622.png)


but it's still not work.

**Comment by codelipenghui** [comment]
The v2 naming pattern is <domain>://<tenant>/<namespace>/<local-name>. For example: persistent://public/default/test_1

**Comment by zhijianfree** [comment]
eh..., i show pictures about non-persistent and persisent.
when i use persistent v2 naming parttern works well. look like this:
use persisent command :
![image](https://user-images.githubusercontent.com/21210211/84339628-6d63e800-abd1-11ea-8b10-f593312c0248.png)
result is :
![image](https://user-images.githubusercontent.com/21210211/84339571-532a0a00-abd1-11ea-970b-dd3bd02a9828.png)

but when i use non-persisent command:
![image](https://user-images.githubusercontent.com/21210211/84339818-d9dee700-abd1-11ea-9158-3e20a4e8b44c.png)

![image](https://user-images.githubusercontent.com/21210211/84339791-caf83480-abd1-11ea-8d49-22158d59e95c.png)

**Comment by codelipenghui** [comment]
@zhijianfree I have pushed a PR to clarify subscription to a non-persistent topic with a topic name pattern. The root cause is only matched persistent topic by default because of the subscriptionTopicsMode is `PersistentOnly`. A little confused here, use "persistent://xx/xx" or "non-persistent://xx/xx" are same as use "xx/xx" as the topic name pattern. The right way is specifying the subscriptionTopicsMode of the consumer.
