### ISSUE TITLE
unable to run on rootless kubernetess 

### ISSUE THREAD

**Issue by grzegorz-moto** [apache/pulsar#7210]
Trying to deploy to (generic) kubernetes cluster and following the documentation: http://pulsar.apache.org/docs/v1.22.0-incubating/deployment/Kubernetes/ to deploy zookeepe first I'm getting an error because my cluster is configured to only allow images without root user

> Error: container has runAsNonRoot and image will run as root

I tried to modify deployment zookeeper.yaml with
```
                securityContext:
                  runAsUser: 1000
```
building new Docker image using this simple Dockerfile:
```
FROM apachepulsar/pulsar-all:latest
USER 1000:1000
```
but it only leads to:

> [conf/pulsar_env.sh] Applying config PULSAR_GC = " -XX:+UseG1GC -XX:MaxGCPauseMillis=10"
> [conf/pulsar_env.sh] Applying config PULSAR_MEM = " -Xms100m -Xmx256m "
> Traceback (most recent call last):
>   File "bin/apply-config-from-env.py", line 73, in <module>
>     f = open(conf_filename, 'w')
> IOError: [Errno 13] Permission denied: 'conf/pulsar_env.sh'

Looking into https://github.com/apache/pulsar/blob/master/docker/pulsar/Dockerfile#L65 it makes it difficult to modify `/pulsar/conf` in derived images

**Comment by sijie** [comment]
@grzegorz-moto you were reading a pretty old version of Pulsar. Pulsar has already evolved to 2.5.2 release. Can you please check the latest documentation http://pulsar.apache.org/docs/en/kubernetes-helm/?

@jiazhai At the same time, we should look into redirecting the old versions of documentation to the newer version.

**Comment by sijie** [comment]
@jiazhai 

https://github.com/apache/pulsar/commit/2df0e23d8b2bbbb57af1d3f1a0f8aa31b1a4af9b
https://github.com/apache/pulsar/commit/e8aec22cfa8d96a8a1efe729ecaad9e6d5dedf38

I think I made the changes back in 2018. Not sure why they were overwritten. You can use these two commits as references to fix the issue.

**Comment by grzegorz-moto** [comment]
Sure I can file a PR with the pulsar docker change however it is just the first step to make it possible to deploy pulsar in cluster user space. For example pulsar_manager and other monitoring services seems to rely on container root user and cluster admin privileges

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant in maintained versions.
