### ISSUE TITLE
Message Encryption is not supported in kafka-adaptor

### ISSUE THREAD

**Issue by zuxqoj** [apache/pulsar#7213]
**Describe the bug**
Message Encryption is not supported in kafka-adaptor

**To Reproduce**
there is no kafka producer config for CryptoKeyReader and EncryptionKey

**Expected behavior**
Message Encryption should be supported in kafka-adaptor

**Screenshots**
NA

**Desktop (please complete the following information):**
 NA

**Additional context**
NA

**Comment by zongtanghu** [comment]
@zhanghaou , you see, can you fix this issue?

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Kafka adapter has been permanently moved to https://github.com/apache/pulsar-adapters. If it's still relevant, please open an issue there.
