### ISSUE TITLE
In Key_Shared subscription with stickyHashRange allow hashes in between

### ISSUE THREAD

**Issue by AnkushKhanna** [apache/pulsar#7217]
**Is your feature request related to a problem? Please describe.**
In `Key_Shared` subscription using `stickyHashRange`, consumers interleaving hashes are not allowed. For example, consumer 1 hash: [[0, 99], [400, 65535]], consumer 2 hash: [[100,399]].
throws an exception, `Range conflict with consumer` from [here](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/HashRangeExclusiveStickyKeyConsumerSelector.java#L109).
This does not allow us to use better hashing techniques ex: **consistent hashing**.
Is this a necessary check?

**Describe the solution you'd like**
Avoid the check if this is not necessary. 

**Additional context**
I am not sure if this is a feature or a bug. Reporting as a feature, please feel free to change accordingly. 
To reproduce the error, you can create two consumers with 
```java
client.newConsumer(Schema.STRING)
             ....
             .subscriptionType(SubscriptionType.Key_Shared)
            .keySharedPolicy(KeySharedPolicy.stickyHashRange().ranges(Range.of(0,99), Range.of(400, 65535)))
            .subscribe();
```
```java
client.newConsumer(Schema.STRING)
             ....
             .subscriptionType(SubscriptionType.Key_Shared)
            .keySharedPolicy(KeySharedPolicy.stickyHashRange().ranges(Range.of(100,399)))
            .subscribe();
```

**Comment by sijie** [comment]
@AnkushKhanna This sounds like a bug. Thank you for reporting the issue.

**Comment by AnkushKhanna** [comment]
I would love to contribute. Let me know if I can help.

**Comment by sijie** [comment]
@AnkushKhanna I think you have identified the problem. It would be great if you can send out a pull request to fix the problem and add some tests to cover this corner cases.
