### ISSUE TITLE
Bouncy Castle License check

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#7224]
**Describe the bug**
Currently, when starting release pulsar, we need to update the bouncy-castle-bc-shaded version to the target version in the pulsar-sql distribution module. But the broker can pass the 
license check.

```
Bouncy Castle License
 * Bouncy Castle -- licenses/LICENSE-bouncycastle.txt
    - bouncy-castle-bc-shaded-2.6.0-SNAPSHOT.jar
```

**Comment by tisonkun** [comment]
Resolved by #18171.
