### ISSUE TITLE
Flink Pulsar connector can not set the configuration of SubscriptionType

### ISSUE THREAD

**Issue by gaofc** [apache/pulsar#7229]
We have used the **PulsarSourceBuilder** class to create a Flink Pulsar Source.
Howerver the class does not have the method of **subscriptionType** which is a very important configuration of pulsar.
The default subscription type is **Exclusive**, which means that the topic could only be consumed by one consumer.
We have to set the subscription type of the topic to **Shared** so the other consumers could use it.
So we think PulsarSourceBuilder should add the subscriptionType method.

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Flink Pulsar connector happens at https://github.com/apache/flink. If it's still relevant, please open an issue at: https://issues.apache.org/jira/projects/FLINK/issues.
