### ISSUE TITLE
the throughout of produce decrease to 0.0

### ISSUE THREAD

**Issue by dockerzhang** [apache/pulsar#7232]
**Describe the bug**
we have two geo-replication clusters with different node configurations, but the configurations of pulsar which deployed by k8s helm are the same.
we test throughout using pulsar-perf, and we found one of the clusters the throughout of produce decrease to 0.0.

**To Reproduce**
1.  deploy k8s cluster using k8s helm
2.  execute './bin/pulsar-perf produce fl-tenant/fl-namespace/tt1   --rate 10  -s 5120000 -z LZ4'
3.  about 20 seconds, maybe less.
4.  See error
![image](https://user-images.githubusercontent.com/18047329/84244768-b155df00-ab36-11ea-93a8-e6bb6f9af189.png)

version: 2.5.2/2.5.0

we checked all broker/bookie logs, there is no error exception, and don't have a clue how to fix it.

**Comment by jiazhai** [comment]
hi @dockerzhang , Would you please help try the messages with small size (< 5MB)?

**Comment by jiazhai** [comment]
There should be a PR fixed similar issue: https://github.com/apache/pulsar/pull/5282

**Comment by dockerzhang** [comment]
@jiazhai  the same error appeared when tested with small size.
I tested using one broker pod and found "bookie operation timeout" warning exceptions. 
After I separate brokers and bookies on different nodes,  the throughout of pulsar-perf changed to normal. I thought it's maybe caused by resources.
