### ISSUE TITLE
Documentation for logging to file in standalone mode

### ISSUE THREAD

**Issue by larshelge** [apache/pulsar#7242]
I want to configure Apache Pulsar to log output to file when in standalone mode. I am reading the documentation but it is not clear how to achieve this.

I am running Pulsar in standalone mode from a `systemd` service, with an exec command like this:

```sh
/var/lib/apache-pulsar/bin/pulsar standalone
```

Now the Pulsar log configuration is documented [here](http://pulsar.apache.org/docs/en/2.2.1/reference-configuration/#log4j), and specifies that you can use configuration properties like `pulsar.root.logger` to configure logging through Log4J.

However what is not clear is where do you define these log-related properties? In which configuration file do they go?

Or should you make changes in `log4j2.yaml` directly? This is not covered in the documentation as far as I can see. Changing e.g. `pulsar.routing.appender.default` to `RollingFile` does not seem to have an effect.

Describing the complete steps of enabling logging to file in standalone mode would be very helpful and appreciated.

Thanks in advance for any assistance.

**Comment by zymap** [comment]
@larshelge Here has an example to change the log level or something else. If you want to configure other classes, you need to change the `name` to the class you want to apply to.
https://github.com/apache/pulsar/blob/d557e0aa286866363bc6261dec87790c055db1b0/conf/log4j2.yaml#L155

**Comment by zymap** [comment]
@Jennifer88huang @Anonymitaet Could you please help me to update the example to here: http://pulsar.apache.org/docs/en/2.2.1/reference-configuration/#log4j

**Comment by Jennifer88huang** [comment]
@zymap sure, we're more than glad to do that.

**Comment by Jennifer88huang** [comment]
@larshelge Thank you for raising the issue. Yes,  you can  configure it directly in the `log4j2.yaml` file. I've added a reference in #9365. If you have further issue, feel free to leave comments there.

To make your configuration take effect, you need to configure it in [log4j2.yaml](https://github.com/apache/pulsar/blob/d557e0aa286866363bc6261dec87790c055db1b0/conf/log4j2.yaml#L155) file, and remember to uncomment it.
