### ISSUE TITLE
Pulsar SQL cannot query messages under namespace names with uppercase letters  or topics

### ISSUE THREAD

**Issue by bleacha870721** [apache/pulsar#7256]
#### Expected behavior

query messages under topic: persistent://public/testGroupTest/testTopic

#### Actual behavior

presto> select * from pulsar."public/testGroupTest"."testTopic";
Query 20200612_080208_00080_mxdbe failed: Schema public/testgrouptest does not exist

#### Steps to reproduce

1.create a namespace called testGroupTest in tenant public.
2.create a topic called testTopic in public/testGroupTest
3.send a message to this topic
4.query message by pulsar sql
#### System configuration
**Pulsar version**: 2.5.0

**Comment by jiazhai** [comment]
@bleacha870721 Would you please try low case first?
` select * from pulsar."public/testgrouptest"."testtopic";`

**Comment by lixiajie** [comment]
I tried and still got an error：
presto> select * from pulsar."public/testgrouptest"."testtopic";
Query 20200615_015314_00002_mxdbe failed: Schema public/testgrouptest does not exist

**Comment by lixiajie** [comment]
> @bleacha870721 Would you please try low case first?
> ` select * from pulsar."public/testgrouptest"."testtopic";`

I tried and still got an error：
presto> select * from pulsar."public/testgrouptest"."testtopic";
Query 20200615_015314_00002_mxdbe failed: Schema public/testgrouptest does not exist

**Comment by lixiajie** [comment]
<img width="774" alt="image" src="https://user-images.githubusercontent.com/66289242/84610788-7238dc80-aeee-11ea-8751-870005a45a82.png">

**Comment by lixiajie** [comment]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/66289242/84610939-ed01f780-aeee-11ea-928e-5393a235dad5.png">

**Comment by lixiajie** [comment]
<img width="705" alt="image" src="https://user-images.githubusercontent.com/66289242/84610974-03a84e80-aeef-11ea-8dbe-108c50a43ae5.png">

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
