### ISSUE TITLE
bookkeeper shell listcookies - a, check that the books nodes are all there, but the actual PS process is not at all

### ISSUE THREAD

**Issue by xuesong172500** [apache/pulsar#7258]
**Describe the bug**
bookkeeper shell listcookies - a check that the books nodes are all there, but the actual PS process is not at all.
pulsar-admin brokers list pulsar-cluster is the same.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Ghatage** [comment]
Hi @xuesong172500!
The cookies don't indicate the state of the bookie server process.
The Bookie process might be down but its still valid for it to have a cookie. (As it how it would happen in an upgrade scenario)
Now, if you've decommissioned the bookie and it's still showing up, it might be a problem.
Can you confirm if you had decommissioned the bookie and are still seeing its cookie?

**Comment by sijie** [comment]
Close this issue since it has been answered.
