### ISSUE TITLE
org.apache.zookeeper.server.quorm.QuorumCnxManager- Connenction broken for id 3, my id =2,error = 

### ISSUE THREAD

**Issue by DGBStarSky** [apache/pulsar#7261]
**Describe the bug**
org.apache.zookeeper.server.quorm.QuorumCnxManager- Connenction broken for id 3, my id =2,error = 

**Screenshots**
zookeeper error
![image](https://user-images.githubusercontent.com/35715373/84494303-d3d52d00-acdb-11ea-9139-013f17a43fff.png)
lead to bookkeeper error
![image](https://user-images.githubusercontent.com/35715373/84494411-097a1600-acdc-11ea-9973-0be93beb100b.png)

**Desktop (please complete the following information):**
 - OS: linux
pulsar 2.5.2

**Comment by sijie** [comment]
@DGBStarSky is this a transient issue or it is permanent error?

**Comment by DGBStarSky** [comment]
sorry,I don't remember clearly.
I remember that bookkeeper was not restored.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sijie Guo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月15日(星期一) 上午9:55
收件人:&nbsp;"apache/pulsar"<pulsar@noreply.github.com&gt;;
抄送:&nbsp;" "<862076528@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/pulsar] org.apache.zookeeper.server.quorm.QuorumCnxManager- Connenction broken for id 3, my id =2,error =  (#7261)





 
@DGBStarSky is this a transient issue or it is permanent error?

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
