### ISSUE TITLE
Support partitioned topics in the Reader interface

### ISSUE THREAD

**Issue by yoniiny** [apache/pulsar#7265]
**Is your feature request related to a problem? Please describe.**
Working with large volumes of data requires partitioned topics. Ensuring exactly-once using idempotent operations requires using the Reader interface, but it doesn't support partitioned topics.

**Describe the solution you'd like**
The Reader interface should support partitioned topics

**Describe alternatives you've considered**
The issue #3643 would be a workaround that would allow this to work by creating and destroying Consumers. This is quite clunky though.

**Comment by 315157973** [comment]
Please assign it to me

**Comment by sollecitom** [comment]
Any progress on this? It's a massive blocker for us.

**Comment by codelipenghui** [comment]
https://github.com/apache/pulsar/pull/7518 has fixed the issue, so close for now.
@sollecitom This feature has released in 2.7.0
