### ISSUE TITLE
This should be `isBuiltInSink` not `isBuiltInSource`

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#7271]
https://github.com/apache/pulsar/blob/5d02c70b674a36e5bd36c60e488737db5740d21e/pulsar-functions/localrun/src/main/java/org/apache/pulsar/functions/LocalRunner.java#L291

**Comment by rudy2steiner** [comment]
please assign to me as my first issue!

**Comment by rudy2steiner** [comment]
There are two similar pr #7285 #7272  for this issue, but it's not assigned to any one

**Comment by david-streamlio** [comment]
I submitted 7272 and is just pending approval. But honestly, either one is
fine. Let just get this fix in. =)
