### ISSUE TITLE
Why websocket clients consumer message must encode data in base64?

### ISSUE THREAD

**Issue by TinDang97** [apache/pulsar#7284]
I don't understand why we must encode consumer messages in base64 (by default) before send it via WebSocket?
I know base64 will increase message size by about 30% if compared with raw data (my data are images).

Thank guys
#### System configuration
**Pulsar version**: 2.0
**OS**: Ubuntu 18.04

**Comment by sijie** [comment]
@TinDang97 HTTP protocol is a text-oriented protocol. If you want to send raw bytes over WebSocket port, you need to make sure the raw data is encoded using base64 otherwise you will hit deserialization issues.

**Comment by TinDang97** [comment]
> @TinDang97 HTTP protocol is a text-oriented protocol. If you want to send raw bytes over WebSocket port, you need to make sure the raw data is encoded using base64 otherwise you will hit deserialization issues.

Thanks. Have we any other way else base64?

**Comment by sijie** [comment]
@TinDang97 Sorry, I don't understand what is your question?

**Comment by TinDang97** [comment]
> @TinDang97 Sorry, I don't understand what is your question?

Thanks. ^^
