### ISSUE TITLE
Official Rust Client Support

### ISSUE THREAD

**Issue by al8n** [apache/pulsar#7291]
Please support the official rust client.

Rust is going to be more and more popular and companies are choosing rust to rebuild their project, so it is time to support the official rust client.

**Comment by sijie** [comment]
@ALiuGuanyan there is a Rust client maintained by [@wyyerd](https://github.com/wyyerd). https://github.com/wyyerd/pulsar-rs

**Comment by ALiuGuanyan** [comment]
> @ALiuGuanyan there is a Rust client maintained by [@wyyerd](https://github.com/wyyerd). https://github.com/wyyerd/pulsar-rs

Yep, but it does not provide all Pulsar API like the official client.

**Comment by sijie** [comment]
@ALiuGuanyan sure. but if there is already a group of people developing that client, it would be great to involve in that project and help improve the client there. This would help Pulsar grow the community.

**Comment by tisonkun** [comment]
Closed as information delivered.

pulsar-rs is now located at https://github.com/streamnative/pulsar-rs. Welcome to give it a try and help verify it. I believe that with more usage and as it gets mature we can consider donating it under the apache org.
