### ISSUE TITLE
Non partitioned topic auto created when auto creation is enabled only for partitioned topics (specific scenario)

### ISSUE THREAD

**Issue by trexinc** [apache/pulsar#7293]
Pulsar 2.5.2.

A non partitioned topic exists: internal/test/test
A producer and a consumer are connected to this topic.

Now we do the following:
pulsar-admin namespaces set-auto-topic-creation -d -t non-partitioned internal/test
pulsar-admin topics delete internal/test/test -f
pulsar-admin namespaces set-auto-topic-creation -e -t partitioned -n 3 internal/test

I expect now that a partitioned topic will be created once the publisher and consumer reconnect, but a regular topic is created. 

This happens even if I manually create the partitioned topic before enabling auto creation (then both non-partitioned and partitioned with the same name get created and the consumer and publisher continue to be connected to the non partitioned)

**Comment by trexinc** [comment]
To give more details it seems that it happens because of the publishers. Consumers get reconnected to the partitioned topic, but the publisher reconnects and somehow recreates the non-partitioned topic

**Comment by trexinc** [comment]
Of course if I stop the publisher, delete the non-partitioned topic and then start the publisher - all is ok.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
