### ISSUE TITLE
[pulsar-admin] weird error on wrong command

### ISSUE THREAD

**Issue by trexinc** [apache/pulsar#7301]
Pulsar 2.5.2
If the run "pulsar-admin namespaces list" and by mistake give it a tenant/ns instead of just tenant I get the following error, and it takes some time to figure out what the problem is. Some input validation would help here.

> pulsar-admin namespaces list tenant/ns
null

Reason: javax.ws.rs.client.ResponseProcessingException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<java.lang.Object>` out of START_OBJECT token
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1]

**Comment by jiazhai** [comment]
we should return "format error" when using "tenant/ns" as a tenant name.

**Comment by zongtanghu** [comment]
@zhanghaou You see,  can you fix this issue?

**Comment by zhanghaou** [comment]
OK. I had made a PR to fix it. [https://github.com/apache/pulsar/pull/7369](https://github.com/apache/pulsar/pull/7369)

**Comment by zongtanghu** [comment]
it’s good and nice!


 原始邮件 
发件人: Hao Zhang<notifications@github.com>
收件人: apache/pulsar<pulsar@noreply.github.com>
抄送: Hu Zongtang<huzongtang@cmss.chinamobile.com>; Comment<comment@noreply.github.com>
发送时间: 2020年6月26日(周五) 21:37
主题: Re: [apache/pulsar] [pulsar-admin] weird error on wrong command(#7301)


OK. I had made a PR to fix it. #7369
