### ISSUE TITLE
regex consumer fails to subscribe when partitions are missing

### ISSUE THREAD

**Issue by trexinc** [apache/pulsar#7306]
For reasons unknown some partitioned topics are missing one of the partitions. Should be 3, but not all are created.

When that happens and I start a regex consumer that catches those partitioned topics:
`bin/pulsar-client consume -s test3 --regex 'tenant/ns/topic.*'`
It fails:
`[MultiTopicsConsumer-f47ed] Failed to subscribe for topic [persistent://tenant/ns/topicXYZ] in topics consumer, subscribe error: org.apache.pulsar.client.api.PulsarClientException$TopicDoesNotExistException: Topic does not exist`

I managed to fix it using "create-missed-partitions", but why aren't the missing partitions created automatically when the consumer is connected?

**Comment by trexinc** [comment]
In addition I didn't expect the regex consumer to fail at all, it should subscribe IMHO to what it can and not fail completely if it can't connect to some.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
