### ISSUE TITLE
Pulsar build failed

### ISSUE THREAD

**Issue by sundar-10** [apache/pulsar#7307]
**Describe the bug**
Error in - Building Pulsar Shaded Broker 2.7.0-SNAPSHOT                    [41/137] 

**To Reproduce**
1. Clone the repository 
2. mvn install -DskipTests -e
3. See error

**Expected behavior**
Build successful 

**Desktop (please complete the following information):**
 - Apache Maven 3.6.0                                                                                                                                    │·······Maven home: /usr/share/maven                                                                                                                          │·······Java version: 11.0.7, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64                                                                     │·······Default locale: en, platform encoding: UTF-8                                                                                                          │·······OS name: "linux", version: "5.3.0-1028-azure", arch: "amd64", family: "unix"     

**Logs**
[errors.log](https://github.com/apache/pulsar/files/4800322/errors.log)

**Comment by sijie** [comment]
@sundar-10 Can you try to build this using java8?

**Comment by sundar-10** [comment]
@sijie Yeah I just tried, I am getting the same error.

**Comment by sundar-10** [comment]
@sijie We made it work, we saw the Dockerfile and we ran the following commands and it worked:
`sudo apt-get update && \
     sudo apt-get install -y tig g++ cmake libssl-dev libcurl4-openssl-dev \
                 liblog4cxx-dev libprotobuf-dev libboost-all-dev google-mock libgtest-dev \
                 libjsoncpp-dev libxml2-utils protobuf-compiler wget \
                  curl doxygen openjdk-8-jdk-headless clang-format-5.0 \
                 gnupg2 golang-1.10-go zip unzip libzstd-dev libsnappy-dev
`
