### ISSUE TITLE
pulsar-2.6.0 cpp client build error

### ISSUE THREAD

**Issue by firefeifei** [apache/pulsar#7312]
**Describe the bug**
build error

**To Reproduce**

[root@VM_72_166_tlinux /data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/build]# cmake ..
-- ARCHITECTURE: x86_64
-- BUILD_TESTS:  ON
-- BUILD_PYTHON_WRAPPER:  ON
-- LINK_STATIC:  OFF
-- USE_LOG4CXX:  OFF
-- CMAKE_BUILD_TYPE:  RelWithDebInfo
-- Found Boost: /usr/local/include (found version "1.54.0") found components: program_options regex system 
-- PYTHON: 2.7.10
-- Found Boost: /usr/local/include (found version "1.54.0") found components: python 
-- HAS_ZSTD: 0
-- HAS_SNAPPY: 1
-- Using Boost Python libs: /usr/local/lib/libboost_python.so
clang-tidy not found
clang-format not found
-- Configuring done
-- Generating done
-- Build files have been written to: /data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/build

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - linux 3.10.106

**Additional context**

/data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/lib/CompressionCodecSnappy.cc: In member function 'virtual bool pulsar::CompressionCodecSnappy::decode(const pulsar::SharedBuffer&, uint32_t, pulsar::SharedBuffer&)':
/data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/lib/CompressionCodecSnappy.cc:43:42: error: cannot convert 'snappy::ByteArraySource*' to 'const char*' for argument '1' to 'bool snappy::Uncompress(const char*, size_t, snappy::string*)'
     if (snappy::Uncompress(&source, &sink)) {
                                          ^
make[2]: *** [lib/CMakeFiles/pulsarShared.dir/CompressionCodecSnappy.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/pulsarShared.dir/all] Error 2

**Comment by wolfstudy** [comment]
It looks like you are missing some necessary dependency lib, @firefeifei can you follow this doc: [how to build the CPP client](https://pulsar.apache.org/docs/en/develop-cpp/)

**Comment by firefeifei** [comment]
The above compilation error is required for snappy1.1.8
-----------
A version of the snappy library that you rely on is added to the recommendation document

**Comment by jiazhai** [comment]
Hi @firefeifei.  It is recommend to use `pulsar-client-cpp/docker-build.sh` to build the cpp client.
