### ISSUE TITLE
Standalone docker-compose.yml is invalid for 2.6.0 (standalone container fails with error)

### ISSUE THREAD

**Issue by fmiguelez** [apache/pulsar#7315]
**Describe the bug**
If you start standalone stack with docker-compose using file [docker-compose-yml](https://github.com/apache/pulsar/blob/master/docker-compose/standalone-dashboard/docker-compose.yml) it will fail with error:

> standalone_1      | Error: Could not find or load main class "

**To Reproduce**
Simply start the stack with docker-compose 

`docker-compose up`

Go to  [standalone-dashboard](https://github.com/apache/pulsar/blob/master/docker-compose/standalone-dashboard/) folder and run docker-compose.

**Expected behavior**
Standalone container starts without issues (as with previous versions <= 2.5.2)

**Screenshots**

**Desktop (please complete the following information):**
Tested on Windows 10 with Docker Desktop

**Additional context**
If you change "PULSAR_MEM" for "BOOKIE_MEM" it works.

**Comment by bbl** [comment]
+1 Got this today
