### ISSUE TITLE
Reader interface goes timeout when accessing a non existing topic

### ISSUE THREAD

**Issue by itaross** [apache/pulsar#7318]
**Describe the bug**
When it is requested a message from a topic that is not existing pulsar wait for the entire timeout

**Expected behavior**
Should fail fast

**Comment by sijie** [comment]
@itaross Which version are you using?

**Comment by itaross** [comment]
A modified 2.5.0 which pull requests have been merged in to 2.6.0 (not on the reader interface).

**Comment by merlimat** [comment]
@itaross Can you provide sample code? And which operation is giving timeout, the `createReader()` or the `readNext()` on the reader?

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
