### ISSUE TITLE
pulsar client jar is too fat

### ISSUE THREAD

**Issue by amosJinCloudwise** [apache/pulsar#7321]
![image](https://user-images.githubusercontent.com/31983528/85195490-840eeb00-b305-11ea-9ee4-70304f0d287b.png)

**Comment by sijie** [comment]
@amosJinCloudwise the pulsar-client is a jar that shades all the dependencies. You can use `pulsar-client-original` if you are looking for a smaller jar.

**Comment by amosJinCloudwise** [comment]
> @amosJinCloudwise the pulsar-client is a jar that shades all the dependencies. You can use `pulsar-client-original` if you are looking for a smaller jar.

i will try it, and, What is the difference between them? can you tell me? thx.

**Comment by sijie** [comment]
@amosJinCloudwise The pulsar-client is a jar that shades all the dependencies. The pulsar-client-original doesn't shade any of the dependencies.

**Comment by tisonkun** [comment]
Closed as information delivered.
