### ISSUE TITLE
CryptoKeyReader - Separate Interface for Producer and Consumer

### ISSUE THREAD

**Issue by Subash-Kunjupillai** [apache/pulsar#7325]
**Is your feature request related to a problem? Please describe.**
Currently to encrypt the data, we are supposed to implement CryptoKeyReader which takes in both PublicKey and PrivateKey. But ideally a producer/consumer will have only either one of the keys as providing both the keys to both producer and consumer is not practically done.

**Describe the solution you'd like**
The expectation over here is to expect different interfaces for both producer and consumer end so that only the required keys are provided for encryption and decryption rather than providing both keys to producer and consumer

**Describe alternatives you've considered**
I've no alternatives right now other than passing both the keys.

**Additional context**
This was discussed in user mailing list and based on @Sijie recommendation raising this issue.

**Comment by tisonkun** [comment]
Closed as stale and no one showed interest. Please open a new issue if it's still relevant to the maintained versions.
