### ISSUE TITLE
Pulsar Function creates a produces that is never closed

### ISSUE THREAD

**Issue by psisoyev** [apache/pulsar#7332]
**Describe the bug**
Found this when using Java client API.
When Pulsar Function sends a message to a topic using `newOutputMessage` it creates a new producer, which is then never closed. This leads to topics not being garbage collected.

**To Reproduce**
1. Create a topic A
2. Create a Function that listens to topic A
3. Inside the function send a message to topic B
4. Topic B is never garbage collected

**Expected behavior**
Client B is cleaned up after a while. 

**Desktop (please complete the following information):**
 - OS: Any
- Client: Java, but didn't try others

**Additional context**
Usually, if there are no producers, consumers and subscriptions, the broker will treat a topic as inactive and delete it after a certain time. In scenario above the producer is created by a Function and is never closed even though it might be never used again. Restarting/shutting down the function helps.

**Comment by sijie** [comment]
This is related to #4816

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
