### ISSUE TITLE
The python consumer cannot receive the data of topic.

### ISSUE THREAD

**Issue by xuehuanran** [apache/pulsar#7344]
The consumer of python client somtimes cannot receive the data of a persistent topic. The receive is blocked.
Here is my code example.

# producer.py
client = pulsar.Client("pulsar://localhost:6650")
producer = client.create_producer("topic1")
producer.send(pickle.dumps(obj))

producer = client.create_producer("topic2")
producer.send(pickle.dumps(obj))

# consumer.py
client = pulsar.Client("pulsar://localhost:6650")
consumer = client.subscribe("topic1", "sub1")
msg = consumer.receive()
consumer.acknowledge(msg)
data = msg.data()

consumer = client.subscribe("topic2", "sub2")
msg = consumer.receive()
consumer.acknowledge(msg)
data = msg.data()`

e.g. 
The topic name is "persistent://public/default/huanran_202006232213_public_key", and the stats is shown as below.
{
  "msgRateIn" : 0.0,
  "msgThroughputIn" : 0.0,
  "msgRateOut" : 0.0,
  "msgThroughputOut" : 0.0,
  "averageMsgSize" : 0.0,
  "storageSize" : 2694,
  "backlogSize" : 0,
  "publishers" : [ {
    "msgRateIn" : 0.0,
    "msgThroughputIn" : 0.0,
    "averageMsgSize" : 0.0,
    "producerId" : 0,
    "metadata" : { },
    "address" : "/127.0.0.1:56474",
    "producerName" : "standalone-17-48",
    "connectedSince" : "2020-06-23T22:14:05.502+08:00",
    "clientVersion" : "2.4.1"
  } ],
  "subscriptions" : {
    "huanran_202006232213_public_key_sub" : {
      "msgRateOut" : 0.0,
      "msgThroughputOut" : 0.0,
      "msgRateRedeliver" : 0.0,
      "msgBacklog" : 0,
      "blockedSubscriptionOnUnackedMsgs" : false,
      "msgDelayed" : 0,
      "unackedMessages" : 0,
      "type" : "Exclusive",
      "activeConsumerName" : "914e9d",
      "msgRateExpired" : 0.0,
      "lastExpireTimestamp" : 0,
      "consumers" : [ {
        "msgRateOut" : 0.0,
        "msgThroughputOut" : 0.0,
        "msgRateRedeliver" : 0.0,
        "consumerName" : "914e9d",
        "availablePermits" : 10,
        "unackedMessages" : 0,
        "blockedConsumerOnUnackedMsgs" : false,
        "metadata" : { },
        "address" : "/127.0.0.1:56477",
        "connectedSince" : "2020-06-23T22:14:16.453+08:00",
        "clientVersion" : "2.4.1"
      } ],
      "isReplicated" : false
    }
  },
  "replication" : { },
  "deduplicationStatus" : "Disabled",
  "bytesInCounter" : 2694,
  "msgInCounter" : 2
}

{
  "entriesAddedCounter" : 2,
  "numberOfEntries" : 2,
  "totalSize" : 2694,
  "currentLedgerEntries" : 2,
  "currentLedgerSize" : 2694,
  "lastLedgerCreatedTimestamp" : "2020-06-23T22:14:05.5+08:00",
  "waitingCursorsCount" : 1,
  "pendingAddEntriesCount" : 0,
  "lastConfirmedEntry" : "4644:1",
  "state" : "LedgerOpened",
  "ledgers" : [ {
    "ledgerId" : 4644,
    "entries" : 0,
    "size" : 0,
    "offloaded" : false
  } ],
  "cursors" : {
    "huanran_202006232213_public_key_sub" : {
      "markDeletePosition" : "4644:1",
      "readPosition" : "4644:2",
      "waitingReadOp" : false,
      "pendingReadOps" : 0,
      "messagesConsumedCounter" : 2,
      "cursorLedger" : 4648,
      "cursorLedgerLastEntry" : 0,
      "individuallyDeletedMessages" : "[]",
      "lastLedgerSwitchTimestamp" : "2020-06-23T22:14:16.447+08:00",
      "state" : "Open",
      "numberOfEntriesSinceFirstNotAckedMessage" : 1,
      "totalNonContiguousDeletedMessagesRange" : 0,
      "properties" : { }
    }
  }
}

The `msg = consumer.receive() `  is block.

The pulsar is standalone mode, and the python pulsar client is 2.4.1. I also try on linux server, the python pulsar client and pulsar are both 2.5.0, but it's still not work.

**Comment by sijie** [comment]
Do you have the code example you are using for testing? Also, can you provide the sequence on how to re-produce the issue?

**Comment by xuehuanran** [comment]
Ok, I have updated and add the code example.

**Comment by xuehuanran** [comment]
> Do you have the code example you are using for testing? Also, can you provide the sequence on how to re-produce the issue?

Ok, I have updated and add the code example.

**Comment by ptirupac-tibco** [comment]
I wasn't able to replicate the issue in the following env:

**Environment**
macOS-10.15
python pulsar-client==2.4.2
Puslar-2.5.0

Producer Sample:
![producer_sample](https://user-images.githubusercontent.com/63665447/85588788-9e4c1000-b608-11ea-8f17-028ed19c8e99.png)


Consumer Sample:
![consumer_sample](https://user-images.githubusercontent.com/63665447/85588801-a2782d80-b608-11ea-98a9-43d4a88f7ece.png)


@xuehuanran how often do you see the issue?

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Python client has been permanently moved to https://github.com/apache/pulsar-client-python. If it's still relevant, please open an issue there.
