### ISSUE TITLE
De-duplication cursor is not moving

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#7345]
**Describe the bug**

The de-duplication cursor is not moving if de-duplication is enabled for a namespace but producers don't configure producer names to produce messages. This results in a huge data backlog.

**Comment by merlimat** [comment]
>  but producers don't configure producer names to produce messages

A producer will always have a name, either user-assigned or a unique broker-assigned name.

**Comment by sijie** [comment]
@merlimat I am not entirely sure the exact issue yet. But that's the behavior we have been observed in a production cluster. We are still looking for what will be the cause and how to fix it.

**Comment by codelipenghui** [comment]
close via #7656
