### ISSUE TITLE
Unable to include *.tar.gz python dependencies in the Pulsar Function package

### ISSUE THREAD

**Issue by juliohm1978** [apache/pulsar#7346]
**Describe the bug**
I was able to figure out the internals of the Pulsar Function dependency package looking at PR https://github.com/apache/pulsar/pull/2965 and [python_instance_main.py](https://github.com/apache/pulsar/blob/v2.5.1/pulsar-functions/instance/src/main/python/python_instance_main.py).

However, my `requirements.txt` has dependencies that download as `*.tar.gz` files. For example, if I add `kubernetes` and `pyyaml` to my `requirements.txt`, the resulting `deps` directory will be:

```
-rw-rw-r-- 1 user user 269377 Jun 23 12:37 PyYAML-5.3.1.tar.gz
-rw-rw-r-- 1 user user  11092 Jun 23 12:37 cachetools-3.1.1-py2.py3-none-any.whl
-rw-rw-r-- 1 user user 156576 Jun 23 12:37 certifi-2020.6.20-py2.py3-none-any.whl
-rw-rw-r-- 1 user user 133356 Jun 23 12:37 chardet-3.0.4-py2.py3-none-any.whl
-rw-rw-r-- 1 user user  90944 Jun 23 12:37 google_auth-1.18.0-py2.py3-none-any.whl
-rw-rw-r-- 1 user user  58388 Jun 23 12:37 idna-2.9-py2.py3-none-any.whl
-rw-rw-r-- 1 user user  18159 Jun 23 12:37 ipaddress-1.0.23-py2.py3-none-any.whl
-rw-rw-r-- 1 user user 724559 Jun 23 12:37 kubernetes-11.0.0.tar.gz
-rw-rw-r-- 1 user user 147368 Jun 23 12:37 oauthlib-3.1.0-py2.py3-none-any.whl
-rw-rw-r-- 1 user user  77145 Jun 23 12:37 pyasn1-0.4.8-py2.py3-none-any.whl
-rw-rw-r-- 1 user user 155269 Jun 23 12:37 pyasn1_modules-0.2.8-py2.py3-none-any.whl
-rw-rw-r-- 1 user user 227183 Jun 23 12:37 python_dateutil-2.8.1-py2.py3-none-any.whl
-rw-rw-r-- 1 user user  61826 Jun 23 12:37 requests-2.24.0-py2.py3-none-any.whl
-rw-rw-r-- 1 user user  23560 Jun 23 12:37 requests_oauthlib-1.3.0-py2.py3-none-any.whl
-rw-rw-r-- 1 user user  38251 Jun 23 12:37 rsa-4.0-py2.py3-none-any.whl
-rw-rw-r-- 1 user user 583493 Jun 23 12:37 setuptools-44.1.1-py2.py3-none-any.whl
-rw-rw-r-- 1 user user  10963 Jun 23 12:37 six-1.15.0-py2.py3-none-any.whl
-rw-rw-r-- 1 user user 126746 Jun 23 12:37 urllib3-1.25.9-py2.py3-none-any.whl
-rw-rw-r-- 1 user user 200882 Jun 23 12:37 websocket_client-0.57.0-py2.py3-none-any.whl
```

Since Pulsar Python instance currently only installs `*.whl` dependencies, `kubernetes` and `pyyaml` themselves are not installed in the running Pulsar Instance at runtime.

Would it make sense if I pushed a PR to include `*.tar.gz` files? As far as I can tell, `pip` will install them just the same.

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.
