### ISSUE TITLE
jCloud unit test failure : org.apache.bookkeeper.mledger.offload.jcloud.impl.BlobStoreManagedLedgerOffloaderTest.testS3DriverConfiguredWell

### ISSUE THREAD

**Issue by ptirupac-tibco** [apache/pulsar#7348]
**Describe the bug**
_org.apache.bookkeeper.mledger.offload.jcloud.impl.BlobStoreManagedLedgerOffloaderTest.testS3DriverConfiguredWell_ unit test consistently failing on [branch-2.6](https://github.com/apache/pulsar/tree/branch-2.6)

**To Reproduce**
1. git clone https://github.com/apache/pulsar.git
2. git checkout branch-2.6
3. mvn install -DskipTests
4. cd tiered-storage/jcloud
5. mvn test -fn -e
// Error stack: [jcloud_error.txt](https://github.com/apache/pulsar/files/4823102/jcloud_error.txt)

**Environment**
Ubuntu-18.04
openjdk version "1.8.0_252"
Apache Maven 3.6.1
// Dockerfile: [Dockerfile.txt](https://github.com/apache/pulsar/files/4823110/Dockerfile.txt)

**Comment by codelipenghui** [comment]
@wolfstudy Please help check if this issue is fixed in `branch-2.6`

**Comment by wolfstudy** [comment]
> @wolfstudy Please help check if this issue is fixed in `branch-2.6`

Yes, the flaky test can work in `branch-2.6`.

**Comment by sijie** [comment]
Close it since it has been fixed in branch-2.6.
