### ISSUE TITLE
Pulsar Broker unit test failure : org.apache.pulsar.broker.namespace.NamespaceOwnershipListenerTests.testNamespaceBundleOwnershipListener

### ISSUE THREAD

**Issue by ptirupac-tibco** [apache/pulsar#7349]
**Describe the bug**
_org.apache.pulsar.broker.namespace.NamespaceOwnershipListenerTests.testNamespaceBundleOwnershipListener_ unit test failing on [branch-2.6](https://github.com/apache/pulsar/tree/branch-2.6).

**To Reproduce**
1. git clone https://github.com/apache/pulsar.git
2. git checkout branch-2.6
3. mvn install -DskipTests
4. cd pulsar-broker
5. mvn test -Dtest=NamespaceOwnershipListenerTests -fn -e
// Error stack: [testNamespaceBundleOwnershipListener_error.txt](https://github.com/apache/pulsar/files/4823128/testNamespaceBundleOwnershipListener_error.txt)

**Environment**
Ubuntu-18.04
openjdk version "1.8.0_252"
Apache Maven 3.6.1
// Dockerfile: [Dockerfile.txt](https://github.com/apache/pulsar/files/4823129/Dockerfile.txt)

**Comment by codelipenghui** [comment]
@wolfstudy Please help check if this issue is fixed in `branch-2.6`

**Comment by wolfstudy** [comment]
> @wolfstudy Please help check if this issue is fixed in `branch-2.6`

Yes, in `branch-2.6`, the `testNamespaceBundleOwnershipListener` can pass.

**Comment by sijie** [comment]
Close it since it has passed in branch-2.6. If it is still a problem, please reopen it again.
