### ISSUE TITLE
[website] The latest content about "Effectively_once" is not searched

### ISSUE THREAD

**Issue by Jennifer88huang** [apache/pulsar#7352]
**Describe the bug**
When I search "Effectively_once" on Pulsar doc website, the deprecated ones are displayed; however, the latest ones are not searched.

**To Reproduce**
1. Go to https://pulsar.apache.org/docs/en/standalone/
2. Enter "Effectively_once" in the search box, the latest content about "effectively_once" is not displayed. 
The link of the latest content: The link is http://pulsar.apache.org/docs/en/functions-overview/#processing-guarantees

**Expected behavior**
The latest content about "effectively_once" should also be searched. 

**Screenshots**
![image](https://user-images.githubusercontent.com/47805623/85513234-63100800-b62d-11ea-878f-4004ecaf32a4.png)

**Desktop (please complete the following information):**
 - OS: iOS v10.13.6

**Comment by codelipenghui** [comment]
@Jennifer88huang Any update on this issue?

**Comment by Jennifer88huang** [comment]
@codelipenghui thanks for your reminder. I've fixed in the latest doc, and we'll close this issue after syncing the updates in different versions.

**Comment by Jennifer88huang** [comment]
From the Pulsar doc side, we've removed the deprecated content. There is sth wrong with the algolia search, and I've reported an issue in https://github.com/algolia/docsearch-configs/issues/2725. So we can close this issue.
