### ISSUE TITLE
Support basic-authentication in function jar urls when registering/updating functions via REST API

### ISSUE THREAD

**Issue by jcordeiro** [apache/pulsar#7354]
**Is your feature request related to a problem? Please describe.**

When registering or updating a function via the REST API using a jar url that has the `user:pass` basic auth scheme is unsupported.

Currently when a jar url with basic-auth credentials is used an error like the following is returned and the register/update call to the REST API returns a `400 - Bad Request`

`Bad Request - {"reason":"Encountered error \"Server returned HTTP response code: 401 for URL: <JAR_URL_HERE>" when getting Function package from <JAR_URL_HERE>"}`

**Describe the solution you'd like**
The basic-auth credentials in the jar url should be forwarded along to the destination url and used to download the function jar

**Describe alternatives you've considered**
The only alternative is to manually hit the jar url and download the jar to the server where the application that's hitting the API is running and using the `file://` url type. Though, this approach won't work in many cases and is why the remote jar url option is provided.

**Additional context**
Hitting the same jar url with basic-auth credentials in a browser prompts a download of the jar, so the url is valid.

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.

**Comment by tisonkun** [comment]
It seems @vanhturn0409 open two PRs against this issue.

**Comment by tisonkun** [comment]
Superseded by #19750
