### ISSUE TITLE
Unable to load values from application.yaml to org.apache.pulsar.common.policies.data.Policies

### ISSUE THREAD

**Issue by Esakkimuthu991** [apache/pulsar#7367]
**Trying to load values to polices class from application.yaml**
Unable to load values from application.yaml to org.apache.pulsar.common.policies.data.Policies where i have to configure RetentionPolicy, repliation_cluster kind of settings

**Comment by sijie** [comment]
@Esakkimuthu991 -  Can you describe more about your issue? I have no idea about the `application.yaml` here and how do you load the values from application.yaml.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
