### ISSUE TITLE
@sijie @jiazhai the issue is fixed by #7119 in 2.6.0. If you check https://pulsar.apache.org/admin-rest-api/?version=2.6.0#operation/setMaxProducersPerTopic you can see that all body parameters are in place

### ISSUE THREAD

**Issue by WillyWill415** [apache/pulsar#7368]
@sijie @jiazhai the issue is fixed by #7119 in 2.6.0. If you check https://pulsar.apache.org/admin-rest-api/?version=2.6.0#operation/setMaxProducersPerTopic you can see that all body parameters are in place

_Originally posted by @vzhikserg in https://github.com/apache/pulsar/issues/6625#issuecomment-646966582_

**Comment by sijie** [comment]
@WillyWill415 it is unclear to me what do you need us to do for this issue. I am closing it now. Please reopen one if you have a more specific ask.
