### ISSUE TITLE
Starting Apache Pulsar standalone on Linux Mint 19.3 keeps showing : INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1  - messages

### ISSUE THREAD

**Issue by THX1188** [apache/pulsar#7376]
[pulsar_standalone_2.6.0.log](https://github.com/apache/pulsar/files/4840846/pulsar_standalone_2.6.0.log)
**Describe the bug**
OS : Linux Mint 19.3, vm
java : version  11.0.7
pulsar version downloaded and unzipped 2.6.0

I am new to Apache Pulsar, and I cannot justify if the components are properly started or not
startup allocates approx 2.5H on  the machine, does not show errors but stops in showing these type of messages

> 17:17:42.081 [pulsar-web-69-6] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [27/Jun/2020:17:17:42 +0200] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false HTTP/1.1" 200 1286 "-" "Pulsar-Java-v2.6.0" 2
> 17:18:12.083 [pulsar-web-69-3] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [27/Jun/2020:17:18:12 +0200] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false HTTP/1.1" 200 1286 "-" "Pulsar-Java-v2.6.0" 5
> 17:18:42.082 [pulsar-web-69-4] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [27/Jun/2020:17:18:42 +0200] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false HTTP/1.1" 200 1286 "-" "Pulsar-Java-v2.6.0" 3
> 17:19:12.083 [pulsar-web-69-5] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [27/Jun/2020:17:19:12 +0200] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false HTTP/1.1" 200 1286 "-" "Pulsar-Java-v2.6.0" 4
> 

**Expected behavior**
bin/pulsar standalone

after a while showing these messages ...

> 2017-06-01 14:46:29,192 - INFO  - [main:WebSocketService@95] - Configuration Store cache started
> 2017-06-01 14:46:29,192 - INFO  - [main:AuthenticationService@61] - Authentication is disabled
> 2017-06-01 14:46:29,192 - INFO  - [main:WebSocketService@108] - Pulsar WebSocket Service started

Kind regards
/Thx1188

PS.: logfile attached, ...

**Comment by sijie** [comment]
@THX1188 the logging is coming from function worker. To debug this issue, you can first disable function worker `bin/pulsar standalone -nfw` to see if you can run pulsar first.

**Comment by THX1188** [comment]
Thank you for feedback @sijie !
I took the docker version which runs more isolated, but the behavior was exact the same.

>     docker run -it \
>     -p 6650:6650 \
>     -p 8080:8080 \
>     --mount source=pulsardata,target=/pulsar/data \
>     --mount source=pulsarconf,target=/pulsar/conf \
>     apachepulsar/pulsar:2.6.0 \
>     bin/pulsar standalone

Finally , maybe more accidentally I pulled  yet another Pulsar Docker Image and this was based on nginx. After a few minutes I was able to connect to it's dashboard. which maybe means it is up and running ? Screenshot of Dasboard attached, I will try later python examples, ... but there should be more evidence to a user when the system is up and running. There is too much logging around, which for an app appliance like this for sure is necessary but, there should be a 'channel' showing the core components are up and running fine like for example starting a database. I am working with Oracle, when I start the database it's very clear just a few lines are posted, if there is some logging generated there are extra files and directories where you can find tons of logs if you want ;)
the docker image which seems to work is this : 

> docker run -it -p 80:80 -p 8080:8080 -p 6650:6650 apachepulsar/pulsar-standalone

it 's also different in size 3G instead of 1.8G

> ❯ docker image ls
> REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
> apachepulsar/pulsar-standalone   latest              30707e3866a7        11 days ago         3.04GB
> apachepulsar/pulsar              2.6.0               85891140d39a        11 days ago         1.77GB


in the logs of the the running container I found : 

> 05:43:32.970 [main] INFO  org.apache.pulsar.websocket.WebSocketService - Global Zookeeper cache started
> 05:43:32.971 [main] INFO  org.apache.pulsar.broker.authentication.AuthenticationService - Authentication is disabled
> 05:43:32.971 [main] INFO  org.apache.pulsar.websocket.WebSocketService - Pulsar WebSocket Service started

Thereby a lot of stuff has been starting : 

> ❯ grep -i started pulsar_standalone_2.6.0_docker.log
> 2020-06-29 05:43:22,010 INFO supervisord started with pid 1
> 05:43:27.845 [main] INFO  org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage - Started Db Ledger Storage
> 05:43:28.274 [ForceWriteThread] INFO  org.apache.bookkeeper.bookie.Journal - ForceWrite Thread started
> 05:43:30.064 [main] INFO  org.apache.bookkeeper.stream.server.service.ClusterControllerService - Successfully started the cluster controller.
> 05:43:31.046 [DLM-/stream/storage-OrderedScheduler-4-0] INFO  org.apache.bookkeeper.stream.storage.impl.sc.StorageContainerImpl - Successfully started storage container (1).
> 05:43:31.056 [DLM-/stream/storage-OrderedScheduler-4-0] INFO  org.apache.bookkeeper.stream.storage.impl.sc.StorageContainerRegistryImpl - Successfully started registered StorageContainer ('1').
> 05:43:31.057 [DLM-/stream/storage-OrderedScheduler-4-0] INFO  org.apache.bookkeeper.stream.storage.impl.sc.ZkStorageContainerManager - Successfully started storage container (1)
> 05:43:31.063 [DLM-/stream/storage-OrderedScheduler-4-0] INFO  org.apache.bookkeeper.stream.storage.impl.sc.StorageContainerImpl - Successfully started storage container (0).
> 05:43:31.064 [DLM-/stream/storage-OrderedScheduler-4-0] INFO  org.apache.bookkeeper.stream.storage.impl.sc.StorageContainerRegistryImpl - Successfully started registered StorageContainer ('0').
> 05:43:31.064 [DLM-/stream/storage-OrderedScheduler-4-0] INFO  org.apache.bookkeeper.stream.storage.impl.sc.ZkStorageContainerManager - Successfully started storage container (0)
> 05:43:32.517 [main] INFO  org.apache.pulsar.broker.service.BrokerService - Started Pulsar Broker service on /0.0.0.0:6650
> 05:43:32.970 [main] INFO  org.apache.pulsar.websocket.WebSocketService - Global Zookeeper cache started
> 05:43:32.971 [main] INFO  org.apache.pulsar.websocket.WebSocketService - Pulsar WebSocket Service started
> 05:43:34.334 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@23b3afb4{/,null,AVAILABLE}
> 05:43:34.414 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@2162598{/,null,AVAILABLE}
> 05:43:34.846 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@78a7fccd{/admin,null,AVAILABLE}
> 05:43:35.173 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@a1689e8{/admin/v2,null,AVAILABLE}
> 05:43:35.384 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@15d68a50{/admin/v3,null,AVAILABLE}
> 05:43:35.498 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@4bb644dc{/lookup,null,AVAILABLE}
> 05:43:35.500 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@5d3a238{/metrics,null,AVAILABLE}
> 05:43:35.536 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@4598961d{/ws/producer,null,AVAILABLE}
> 05:43:35.539 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@48619f15{/ws/v2/producer,null,AVAILABLE}
> 05:43:35.542 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@410e043b{/ws/consumer,null,AVAILABLE}
> 05:43:35.546 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@7be85f15{/ws/v2/consumer,null,AVAILABLE}
> 05:43:35.549 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@9fd5dd0{/ws/reader,null,AVAILABLE}
> 05:43:35.553 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@790ea58f{/ws/v2/reader,null,AVAILABLE}
> 05:43:35.556 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.h.ContextHandler@3cf1b5fb{/static,null,AVAILABLE}
> 05:43:35.576 [main] INFO  org.eclipse.jetty.server.AbstractConnector - Started PulsarServerConnector@212be8c{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
> 05:43:35.577 [main] INFO  org.eclipse.jetty.server.Server - Started @12470ms
> 05:43:35.577 [main] INFO  org.apache.pulsar.broker.web.WebService - HTTP Service started at http://0.0.0.0:8080
> 05:43:35.584 [main] INFO  org.apache.pulsar.broker.loadbalance.LeaderElectionService - LeaderElectionService started
> 05:44:02.689 [main] INFO  org.apache.pulsar.broker.PulsarService - Function worker service started
> 

I will try a minimum python send receive message/copy later but as far it seems to work.

![image](https://user-images.githubusercontent.com/61349287/85980113-0ec8a780-b9e2-11ea-8744-70fc4fc33e53.png)

Thank you!

 








Screenshot attached

**Comment by THX1188** [comment]
Just another fact, Apache Pulsar does only run with java 8 jdk not with java 11 jdk?
cheers 
THX1188

**Comment by sijie** [comment]
I think you can use Java 11 to run it.

**Comment by sijie** [comment]
Close this issue since the question has been answered.
