### ISSUE TITLE
[docs] Add docs for "Dispatch batch messages according consumer permits"

### ISSUE THREAD

**Issue by Jennifer88huang** [apache/pulsar#7378]
**Is your feature request related to a problem? Please describe.**
In #7266, @rdhabalia improves dispatching of batch messages.  

**Describe the solution you'd like**
When the feature completes, add related docs to this feature.

**Comment by codelipenghui** [comment]
@Jennifer88huang Seems we don't need to add a document for #7266 Since the PR does not introduce any new features and configurations, so I will close it first, feel free to reopen it if needed.

**Comment by Jennifer88huang** [comment]
@codelipenghui sure,  thank you.
