### ISSUE TITLE
v2.3.2 pulsar-admin CLI return HTTP 502 Bad Gateway

### ISSUE THREAD

**Issue by yingziyu007** [apache/pulsar#7382]
v2.3.2 pulsar-admin persistent peek-messages options or pulsar-admin topics peek-messages options 
return 502 Bad Gateway
why?
![1](https://user-images.githubusercontent.com/54094772/85965021-12622b80-b9ee-11ea-86b0-487d1e7b011a.png)

**Comment by sijie** [comment]
@yingziyu007 Are you using Pulsar proxy? If so, can you check the log of Pulsar proxy to see if there are any error messages?

**Comment by yingziyu007** [comment]
> 
> 
> @yingziyu007 Are you using Pulsar proxy? If so, can you check the log of Pulsar proxy to see if there are any error messages?
There is no error messages. And deploying pulsar-admin by "apache-pulsar-2.3.2\deployment\kubernetes\generic\admin.yaml".

`09:33:10.147 [pulsar-discovery-io-2-1] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/172.20.148.141:56840] New connection opened
09:33:10.148 [pulsar-discovery-io-2-1] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/172.20.148.141:56840] complete connection, init proxy handler. authenticated with none role null, hasProxyToBrokerUrl: false
09:33:10.149 [pulsar-discovery-io-2-1] WARN  org.apache.pulsar.client.impl.ConnectionPool - Failed to open connection to 172.20.62.17:6650 : io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: /172.20.62.17:6650
09:33:10.150 [pulsar-discovery-io-2-1] INFO  org.apache.pulsar.client.impl.PulsarClientImpl - Client closing. URL: pulsar://proxy-ff85bffd-f2cxw:6650/
09:33:10.150 [pulsar-discovery-io-2-1] INFO  org.apache.pulsar.proxy.server.ProxyConnectionPool - Closing ProxyConnectionPool.
09:33:10.150 [pulsar-discovery-io-2-1] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/172.20.148.141:56840] Connection closed
09:33:20.733 [pulsar-discovery-io-2-1] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/172.20.148.141:57036] New connection opened
09:33:20.734 [pulsar-discovery-io-2-1] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/172.20.148.141:57036] complete connection, init proxy handler. authenticated with none role null, hasProxyToBrokerUrl: false
09:33:20.735 [pulsar-discovery-io-2-1] INFO  org.apache.pulsar.client.impl.ConnectionPool - [[id: 0x520d4a52, L:/172.20.84.61:36928 - R:172.20.84.11/172.20.84.11:6650]] Connected to server
09:38:48.132 [JettyHttpClient@7a904f32-scheduler] INFO  org.eclipse.jetty.server.RequestLog - 172.20.31.209 - - [28/Jun/2020:09:38:33 +0000] "GET /admin/v2/persistent/public/default HTTP/1.1" 502 0 "-" "Pulsar-Java-v2.4.0" 15003
10:08:12.074 [main-SendThread(zookeeper:2181)] INFO  org.apache.zookeeper.ClientCnxn - Unable to read additional data from server sessionid 0x103dafadeb30009, likely server has closed socket, closing socket connection and attempting reconnect
10:08:12.175 [main-EventThread] WARN  org.apache.pulsar.zookeeper.ZookeeperClientFactoryImpl - Unexpected ZK event received: WatchedEvent state:Disconnected type:None path:null
10:08:13.569 [main-SendThread(zookeeper:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server zookeeper/172.20.84.78:2181. Will not attempt to authenticate using SASL (unknown error)
10:08:13.570 [main-SendThread(zookeeper:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established to zookeeper/172.20.84.78:2181, initiating session
10:08:13.571 [main-SendThread(zookeeper:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server zookeeper/172.20.84.78:2181, sessionid = 0x103dafadeb30009, negotiated timeout = 30000
00:21:39.984 [pulsar-external-web-4-7] INFO  org.eclipse.jetty.server.RequestLog - 172.20.31.209 - - [29/Jun/2020:00:21:39 +0000] "GET /admin/v2/persistent/public/default/createUser/subscription/ssdc-datasycn/position/1 HTTP/1.1" 502 0 "-" "Pulsar-Java-v2.4.0" 4
00:21:57.603 [pulsar-external-web-4-7] INFO  org.eclipse.jetty.server.RequestLog - 172.20.31.209 - - [29/Jun/2020:00:21:57 +0000] "GET /admin/v2/persistent/public/default/createUser/internalStats HTTP/1.1" 200 16978 "-" "Pulsar-Java-v2.4.0" 24
00:22:53.889 [JettyHttpClient@7a904f32-scheduler] INFO  org.eclipse.jetty.server.RequestLog - 172.20.31.209 - - [29/Jun/2020:00:22:38 +0000] "GET /admin/v2/persistent/public/default/createUser/subscription/ssdc-datasycn/position/1 HTTP/1.1" 502 0 "-" "Pulsar-Java-v2.4.0" 15004
00:28:30.695 [pulsar-external-web-4-1] INFO  org.eclipse.jetty.server.RequestLog - 172.20.31.209 - - [29/Jun/2020:00:28:30 +0000] "GET /admin/v2/persistent/public/default/createUser/subscription/ssdc-datasycn/position/1 HTTP/1.1" 502 0 "-" "Pulsar-Java-v2.4.0" 5
01:12:38.818 [pulsar-external-web-4-1] INFO  org.eclipse.jetty.server.RequestLog - 172.20.31.209 - - [29/Jun/2020:01:12:38 +0000] "GET /admin/v2/persistent/public/default/createUser/internalStats HTTP/1.1" 200 16978 "-" "Pulsar-Java-v2.4.0" 201`

**Comment by yingziyu007** [comment]
There is no error messages. And deploying pulsar-admin by "apache-pulsar-2.3.2\deployment\kubernetes\generic\admin.yaml".

09:33:10.147 [pulsar-discovery-io-2-1] INFO   org.apache.pulsar.proxy.server.ProxyConnection - [/172.20.148.141:56840]  New connection opened 09:33:10.148 [pulsar-discovery-io-2-1] INFO   org.apache.pulsar.proxy.server.ProxyConnection - [/172.20.148.141:56840]  complete connection, init proxy handler. authenticated with none role  null, hasProxyToBrokerUrl: false 09:33:10.149 [pulsar-discovery-io-2-1]  WARN  org.apache.pulsar.client.impl.ConnectionPool - Failed to open  connection to 172.20.62.17:6650 :  io.netty.channel.AbstractChannel$AnnotatedConnectException:  syscall:getsockopt(..) failed: Connection refused: /172.20.62.17:6650  09:33:10.150 [pulsar-discovery-io-2-1] INFO   org.apache.pulsar.client.impl.PulsarClientImpl - Client closing. URL:  pulsar://proxy-ff85bffd-f2cxw:6650/ 09:33:10.150  [pulsar-discovery-io-2-1] INFO   org.apache.pulsar.proxy.server.ProxyConnectionPool - Closing  ProxyConnectionPool. 09:33:10.150 [pulsar-discovery-io-2-1] INFO   org.apache.pulsar.proxy.server.ProxyConnection - [/172.20.148.141:56840]  Connection closed 09:33:20.733 [pulsar-discovery-io-2-1] INFO   org.apache.pulsar.proxy.server.ProxyConnection - [/172.20.148.141:57036]  New connection opened 09:33:20.734 [pulsar-discovery-io-2-1] INFO   org.apache.pulsar.proxy.server.ProxyConnection - [/172.20.148.141:57036]  complete connection, init proxy handler. authenticated with none role  null, hasProxyToBrokerUrl: false 09:33:20.735 [pulsar-discovery-io-2-1]  INFO  org.apache.pulsar.client.impl.ConnectionPool - [[id: 0x520d4a52,  L:/172.20.84.61:36928 - R:172.20.84.11/172.20.84.11:6650]] Connected to  server 09:38:48.132 [JettyHttpClient@7a904f32-scheduler] INFO   org.eclipse.jetty.server.RequestLog - 172.20.31.209 - -  [28/Jun/2020:09:38:33 +0000] "GET /admin/v2/persistent/public/default  HTTP/1.1" 502 0 "-" "Pulsar-Java-v2.4.0" 15003 10:08:12.074  [main-SendThread(zookeeper:2181)] INFO  org.apache.zookeeper.ClientCnxn -  Unable to read additional data from server sessionid 0x103dafadeb30009,  likely server has closed socket, closing socket connection and  attempting reconnect 10:08:12.175 [main-EventThread] WARN   org.apache.pulsar.zookeeper.ZookeeperClientFactoryImpl - Unexpected ZK  event received: WatchedEvent state:Disconnected type:None path:null  10:08:13.569 [main-SendThread(zookeeper:2181)] INFO   org.apache.zookeeper.ClientCnxn - Opening socket connection to server  zookeeper/172.20.84.78:2181. Will not attempt to authenticate using SASL  (unknown error) 10:08:13.570 [main-SendThread(zookeeper:2181)] INFO   org.apache.zookeeper.ClientCnxn - Socket connection established to  zookeeper/172.20.84.78:2181, initiating session 10:08:13.571  [main-SendThread(zookeeper:2181)] INFO  org.apache.zookeeper.ClientCnxn -  Session establishment complete on server zookeeper/172.20.84.78:2181,  sessionid = 0x103dafadeb30009, negotiated timeout = 30000 00:21:39.984  [pulsar-external-web-4-7] INFO  org.eclipse.jetty.server.RequestLog -  172.20.31.209 - - [29/Jun/2020:00:21:39 +0000] "GET  /admin/v2/persistent/public/default/createUser/subscription/ssdc-datasycn/position/1  HTTP/1.1" 502 0 "-" "Pulsar-Java-v2.4.0" 4 00:21:57.603  [pulsar-external-web-4-7] INFO  org.eclipse.jetty.server.RequestLog -  172.20.31.209 - - [29/Jun/2020:00:21:57 +0000] "GET  /admin/v2/persistent/public/default/createUser/internalStats HTTP/1.1"  200 16978 "-" "Pulsar-Java-v2.4.0" 24 00:22:53.889  [JettyHttpClient@7a904f32-scheduler] INFO   org.eclipse.jetty.server.RequestLog - 172.20.31.209 - -  [29/Jun/2020:00:22:38 +0000] "GET  /admin/v2/persistent/public/default/createUser/subscription/ssdc-datasycn/position/1  HTTP/1.1" 502 0 "-" "Pulsar-Java-v2.4.0" 15004 00:28:30.695  [pulsar-external-web-4-1] INFO  org.eclipse.jetty.server.RequestLog -  172.20.31.209 - - [29/Jun/2020:00:28:30 +0000] "GET  /admin/v2/persistent/public/default/createUser/subscription/ssdc-datasycn/position/1  HTTP/1.1" 502 0 "-" "Pulsar-Java-v2.4.0" 5 01:12:38.818  [pulsar-external-web-4-1] INFO  org.eclipse.jetty.server.RequestLog -  172.20.31.209 - - [29/Jun/2020:01:12:38 +0000] "GET  /admin/v2/persistent/public/default/createUser/internalStats HTTP/1.1"  200 16978 "-" "Pulsar-Java-v2.4.0" 201


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sijie Guo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月29日(星期一) 上午10:17
收件人:&nbsp;"apache/pulsar"<pulsar@noreply.github.com&gt;;
抄送:&nbsp;"汤宗任"<tangzr2019@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/pulsar] v2.3.2 pulsar-admin CLI return HTTP 502 Bad Gateway (#7382)





 
@yingziyu007 Are you using Pulsar proxy? If so, can you check the log of Pulsar proxy to see if there are any error messages?

**Comment by sijie** [comment]
@yingziyu007 have you tried a newer version of pulsar like 2.5.2 or 2.6.0?

**Comment by tisonkun** [comment]
Duplicate to https://github.com/apache/pulsar/issues/7423.

Closed as stale. Feel free to open a new issue if it's still relevant for maintained versions.
