### ISSUE TITLE
When creating function application, set parallelism greater than 1, and multiple jars will be copied under the same node.

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#7391]
**Describe the bug**
Function download directory to download function application jars. Why should each instance ID of the same application download the same jar? Download a jar from a node. What is the consideration? If my function fat package is 200MB and a node starts 10 concurrent numbers, 10 jars of this application will be copied out, which will take up a lot of disk space.

![image](https://user-images.githubusercontent.com/54351417/86090396-95fa4600-badc-11ea-9915-bfc5d2e2c4dd.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jiazhai** [comment]
Thanks @xuesong172500 for open this issue. This is a feature request. It may be good it we could do the function package management. @zymap has some investigation on this. @zymap Would you please help provide more information on your investigation?

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.
