### ISSUE TITLE
多集群自动切换问题

### ISSUE THREAD

**Issue by xiaomin0322** [apache/pulsar#7392]
**Is your feature request related to a problem? Please describe.**
多集群geo，当一个集群挂了，怎么自动切换到另外一个集群，对客户端无感知！
**Describe the solution you'd like**
多集群geo，当一个集群挂了，怎么自动切换到另外一个集群，对客户端无感知！
**Describe alternatives you've considered**
1.客户端重连
2.通过pulsar proxy 不无感知切换
**Additional context**

**Comment by xiaomin0322** [comment]
![image](https://user-images.githubusercontent.com/4092286/86103638-96e8a300-baef-11ea-8b07-57a3a8a4ee86.png)

**Comment by jiazhai** [comment]
It seems the DNS cache is not cleared, and cause the consumer connection still using the old address. Could you set a shorter DNS cache time period?

**Comment by jiazhai** [comment]
Would like to close this issue, is issue not solved, we could open new issue.
