### ISSUE TITLE
Conflict when update partitions on non-persistent topic

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#7394]
**Describe the bug**
When updating partitions on a non-persistent topic, 409 returned.

**To Reproduce**
1. Start standalone
2. Create a non-persistent partitioned topic `bin/pulsar-admin topics create-partitioned-topic non-persistent://public/default/xyz -p 3`
3. Update partitions `bin/pulsar-admin topics update-partitioned-topic non-persistent://public/default/xyz -p 5`
4. Error occurs

```
20:58:58.450 [AsyncHttpClient-7-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://localhost:8080/admin/v2/non-persistent/public/default/xyz/partitions?updateLocalTopicOnly=false] Failed to perform http post request: javax.ws.rs.ClientErrorException: HTTP 409 Conflict
Topic is not partitioned topic

Reason: Topic is not partitioned topic
```
**Expected behavior**
The partitions should be updated successfully.

**Additional context**
pulsar 2.6.0

**Comment by aloyszhang** [comment]
@codelipenghui  I think partition update is not support for no-persistent topic  right now. We should implement it first

**Comment by codelipenghui** [comment]
@aloyszhang Thanks for your replay, I think we can return clear information when update partitions on a non-partitioned topic first. Currently, "Reason: Topic is not partitioned topic" is really confusing.

**Comment by jiazhai** [comment]
The first step would be fix the error log:
```
20:58:58.450 [AsyncHttpClient-7-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://localhost:8080/admin/v2/non-persistent/public/default/xyz/partitions?updateLocalTopicOnly=false] Failed to perform http post request: javax.ws.rs.ClientErrorException: HTTP 409 Conflict
Topic is not partitioned topic

Reason: Topic is not partitioned topic
```
It is partitioned topic, but non-persistent

**Comment by aloyszhang** [comment]
@codelipenghui @jiazhai I'll try to fix this problem.
