### ISSUE TITLE
Write a script to sync Pulsar configuration and CLI tools

### ISSUE THREAD

**Issue by Jennifer88huang-zz** [apache/pulsar#7412]
**Is your feature request related to a problem? Please describe.**
When someone update the configuration files in code, they might forget to update the content for docs on https://pulsar.apache.org/docs/en/reference-cli-tools/ and https://pulsar.apache.org/docs/en/reference-configuration/
When users search the usage of newly updated config, they could not search it on the two links.

**Describe the solution you'd like**
We can write a script to sync the configuration code update to doc files. It saves time and ensures correctness.

**Comment by jiazhai** [comment]
Would like to unassign @tuteng . so that anyone interest to contribute to this feature could work on it.

**Comment by tisonkun** [comment]
I believe the doc sync process is working now. And most references' sources are moved to the pulsar-site repo. See also https://github.com/apache/pulsar-site/pull/259.
