### ISSUE TITLE
[Document & Website][Pulsar 2.5.0]--schema registry should be removed from the concept section

### ISSUE THREAD

**Issue by Huanli-Meng** [apache/pulsar#7415]
**Describe the bug**

in Pulsar 2.5.0, The schema registry doc under the concept and architecture section as there is a Pulsar schema section

![image](https://user-images.githubusercontent.com/48120384/86242380-39c81c80-bbd7-11ea-999e-26fe0f387031.png)

**Comment by Jennifer88huang** [comment]
You can refine the sidebar.json in v2.5.0.

**Comment by Huanli-Meng** [comment]
@Jennifer88huang , how about this issue?

**Comment by Jennifer88huang** [comment]
Done.
