### ISSUE TITLE
Pulsar metrics for prometheus does not work for short live consumers

### ISSUE THREAD

**Issue by ksenlaskar** [apache/pulsar#7418]
1.Create pulsar topic , and create a consumer which consume from the topic at an interval of 500 ms.
2. Configure prometheus for pulsar
3. Check the pulsar metrics (pulsar_subscription_msg_rate_out, pulsar_rate_out) value 
4. The value always shows as 0. 
 
**Additional context**
We had a short discussion with Sijie over slack on this. And his response was "
The pulsar_subscription_msg_rate_out is calculated by broker. it is sampled at Prometheus scrap interval (30s).your udx consumer is a short-live consumer.We don’t support well on that". 

![image](https://user-images.githubusercontent.com/67690671/86252467-e2bf4900-bbd0-11ea-998f-2a66d10279e8.png)

**Comment by merlimat** [comment]
Same problem happens for short-lived producers

**Comment by jiazhai** [comment]
@ksenlaskar Thanks for open this issue. Seems it is not easy to handle this kind of behavior. It may be not good to sample the metrics with a very short period.  @merlimat Is there any idea on this issue?

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
