### ISSUE TITLE
Expose pulsar's metrics in topics

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#7419]
**Is your feature request related to a problem? Please describe.**
Metrics fetch is currently using prometheus endpoint that exposes metrics. External metrics collector should now poll this endpoint.

**Describe the solution you'd like**
What do you think about enable pulsar components to directly send their metrics to configuration defined topics?

Maybe we can imagine `metricstenant/brokers/<broker-name>` pattern.

**Comment by jiazhai** [comment]
thanks @KannarFr for open this issue. this is a good feature. mark it as help wanted for anyone interest to contribute to it.

**Comment by KannarFr** [comment]
@jiazhai I'm working on, I will soon add a PR and we will discuss about it :).
