### ISSUE TITLE
how to get messageId when use sparkstreaming

### ISSUE THREAD

**Issue by zhouxin-116** [apache/pulsar#7426]
dependency:pulsar-spark
thanks!

**Comment by sijie** [comment]
@zhouxin-116 Do you have a concrete example of your question? It is a bit hard for me to understand what you are looking for.

**Comment by zhouxin-116** [comment]
val pulsarReceiver = new SparkStreamingPulsarReceiver(
      serviceUrl,
      pulsarConf,
      new AuthenticationDisabled()
    )
    //  receiver DStream
    val pulsarDStream = ssc.receiverStream(pulsarReceiver)
    //  process
    pulsarDStream.foreachRDD(rdd => {
      rdd.foreachPartition(partition => {
              partition.foreach (row=>{
              
  })
 })
})

**Comment by zhouxin-116** [comment]
@sijie 
val pulsarReceiver = new SparkStreamingPulsarReceiver(
serviceUrl,
pulsarConf,
new AuthenticationDisabled()
)
// receiver DStream
val pulsarDStream = ssc.receiverStream(pulsarReceiver)
// process
pulsarDStream.foreachRDD(rdd => {
rdd.foreachPartition(partition => {
partition.foreach (row=>{

})
})
})

**Comment by tisonkun** [comment]
Closed as stale.

Feel free to open a Q&A discussion at https://github.com/apache/pulsar/discussions if it's still relevant for maintained versions.
