### ISSUE TITLE
Pulsar Admin Java Client leaves hanging thread after close called

### ISSUE THREAD

**Issue by epsteina16** [apache/pulsar#7437]
**Describe the bug**
After closing a Java pulsar admin instance, a delayer thread is left hanging in the background in a TIMED_WAITING state that can prevent the parent program from ending.

**To Reproduce**
1. Create a pulsar admin instance.
2. Add a new topic using the pulsar admin.
3. Close the pulsar admin.
4. Do a java thread dump to see the hanging delayer thread.

**Expected behavior**
Calling close should free and end all threads created by the PulsarAdmin. This includes all AsyncHttp related threads.

**Desktop (please complete the following information):**
- Linux

**Comment by rushsky518** [comment]
in `org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector`
set daemon = true can solve this problem?
```java
    private final ScheduledExecutorService delayer = Executors.newScheduledThreadPool(1,
            new DefaultThreadFactory("delayer", true));
````

**Comment by BewareMyPower** [comment]
The reason is executors that were created by `delayer` to run timeout task were still running. Changing these threads to daemon is a way to solve the problem. Calling `delayer.shutdownNow()` in `AsyncHttpConnector.close()` method also works.

Would you like to push a PR? @rushsky518

**Comment by rushsky518** [comment]
i'd like to make a contribution @BewareMyPower
