### ISSUE TITLE
pulsar  proxy 

### ISSUE THREAD

**Issue by curryLzj** [apache/pulsar#7438]
Can the proxy be run in the background and the log path can be configured for a configuration item?just like broker/bookie

**Comment by sijie** [comment]
@curryLzj Yes. You can run `bin/pulsar-daemon start proxy` to start proxies in the background.

**Comment by curryLzj** [comment]
Oh, I read the documentation on the official website, and I didn't notice that it actually exists..Thanks
=.=!
