### ISSUE TITLE
[python-client 2.6.0] ContextualVersionConflict grpcio dependency conflict

### ISSUE THREAD

**Issue by lbenc135** [apache/pulsar#7477]
**Describe the bug**
When installing `pulsar-client==2.6.0` there's a dependency conflict with `grpcio` library.

The dependency tree is (as I understand it):
- pulsar-client (2.6.0)
    - grpcio (any)
    - apache-bookkeeper-client (4.11.0)
        - grpcio >=1.8.2,<1.26.0

**To Reproduce**
1. `pip install pulsar-client==2.6.0`
2. `grpcio==1.30.0` gets installed
3. If I try to build my own pip package with `pulsar-client` as dependency, and try to build it, I get the `ContextualVersionConflict` error

**Expected behavior**
I expect the correct version to be installed and/or the dependency tree to be fixed.

**Screenshots**
![Screenshot from 2020-07-08 09-17-09](https://user-images.githubusercontent.com/20871882/86889531-2e578280-c0fc-11ea-8031-d4759173f9fc.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by sijie** [comment]
@lbenc135 Can you share your python code example so we can reproduce it?

**Comment by sijie** [comment]
Gotcha. Can you also raise an issue at https://github.com/apache/bookkeeper? So we can relax the requirement in bookkeeper side.

**Comment by lbenc135** [comment]
Sure: https://github.com/apache/bookkeeper/issues/2377

**Comment by jbellis** [comment]
I ran into this today.  

It looks like BookKeeper revved its requirement to include up to 1.28, but in the meantime grpcio released even more versions which are not compatible (1.35 is the latest now).

I think Pulsar client needs to specify a grpcio version that matches a version compatible with the appropriate BK release.

Until then the Python client is effectively uninstallable for the majority of people trying to follow the docs.
