### ISSUE TITLE
native go v0.1.1 No support produce batch？

### ISSUE THREAD

**Issue by sxpsxp12** [apache/pulsar#7480]
**Describe the bug**
native go v0.1.1 No support produce batch？

**To Reproduce**

**Expected behavior**
native go support batch producer

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by sijie** [comment]
@sxpsxp12 Can you create the issue at https://github.com/apache/pulsar-client-go?

**Comment by wolfstudy** [comment]
@sxpsxp12 In fact, we have already supported the batch function on the produce side. By default, the batch is enabled.

```
producer, err := client.CreateProducer(ProducerOptions{
		Topic:                   topicName,
		DisableBatching:         false,
		BatchingMaxMessages:     uint(numOfMessages),
		BatchingMaxPublishDelay: time.Second * 10,
		Properties: map[string]string{
			"producer-name": "test-producer-name",
			"producer-id":   "test-producer-id",
		},
	})
	assert.Nil(t, err)
	defer producer.Close()
```

**Comment by sxpsxp12** [comment]
@wolfstudy thanks，it's work ok。

**Comment by wolfstudy** [comment]
> @wolfstudy thanks，it's work ok。

Cool, will close this issue.
