### ISSUE TITLE
Default value and in-line doc for bookkeeper config: openLedgerRereplicationGracePeriod is incorrect

### ISSUE THREAD

**Issue by anvinjain** [apache/pulsar#7481]
**Describe the bug**
Default bookkeeper conf that ships with apache pulsar indicates that the unit of `openLedgerRereplicationGracePeriod` is in seconds, but official bookkeeper doc(and code) mentions that the unit is in milliseconds. Since default is 30seconds, this will be interpreted by BK as 30ms because of incorrect configuration by pulsar

**To Reproduce**
1. Go to https://bookkeeper.apache.org/docs/4.10.0/reference/config/ and read documentation for `openLedgerRereplicationGracePeriod`. It clearly mentions that the period is in milliseconds and default is `30000`. This can be further confirmed by seeing usage of grace period in https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java where it is treated as milliseconds
1. Download apache pulsar release (checked in 2.5.2 and 2.6.0) or go here: https://github.com/apache/pulsar/blob/master/conf/bookkeeper.conf
1. Observe that `openLedgerRereplicationGracePeriod=30` is configured and comments above this mention that the period is in seconds
1. Pulsar will end up configuring grace period as 30ms which is not the expected behaviour (30s is expected)

**Expected behavior**
Pulsar should configure default as `30000` instead of `30` and bookkeeper.conf should mention that the unit of this period is milliseconds instead of seconds.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 9

**Additional context**

**Comment by codelipenghui** [comment]
@anvinjain Thanks for the feedback, are you interested in pushing a fix for it?

**Comment by anvinjain** [comment]
@codelipenghui Sure, I will take this up.
