### ISSUE TITLE
pulsar_msg_backlog metrics very inaccurate

### ISSUE THREAD

**Issue by irairdon** [apache/pulsar#7484]
**Describe the bug**
Metric for pulsar_msg_backlog does not seem to match the true backlog at all. 

**To Reproduce**
1. Install pulsar 2.5.2
2. Install grafana Pulsar dashboards
3.  Create partition with 3 partitions
4. run pulsar-perf tool (bin/pulsar-perf produce -r 200000 -s 10 ts1)
5. Observe backlog values on Overview dashboard or namespace dashboard 
6. Run pulsar-admin topics stats persistent://public/default/ts1-partition-0, pulsar-admin topics stats persistent://public/default/ts1-partition-1, pulsar-admin topics stats persistent://public/default/ts1-partition-2
7. In my test I have seen metric values where around 500K while the topic stats report over 3 millions per partition.

**Expected behavior**
Backlog metric match the backlog from admin api reports. 

**Screenshots**
![Screenshot from 2020-07-08 09-56-57](https://user-images.githubusercontent.com/18467252/86942718-b6408b00-c102-11ea-834c-8838357bb6a4.png)
![Screenshot from 2020-07-08 09-57-49](https://user-images.githubusercontent.com/18467252/86942720-b6d92180-c102-11ea-8e80-c635ad33ae22.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by codelipenghui** [comment]
@irairdon Looks #7082 has fixed this problem.

**Comment by irairdon** [comment]
Source of this issue is we expected msg backlog to reflect number of messages in backlog which after discussion with Sijie the msg backlog reflect the number of message entries/ batches in the backlog. So have added extra documentation to clarify that point.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
