### ISSUE TITLE
CPP client compilation issues.

### ISSUE THREAD

**Issue by tongsucn** [apache/pulsar#7502]
**Describe the bug**

When enabling `-Wall` and `-Werror`, the library cannot be successfully compiled:

1. Non-virtual destructor in base class: `pulsar-client-cpp/lib/auth/AuthOauth2.h:47:7: error: base class 'class pulsar::CachedToken' has accessible non-virtual destructor [-Werror=non-virtual-dtor]`.
2. Unnecessary NULL checking on function pointer: `/pulsar-client-cpp/lib/ClientImpl.cc:100:10: error: the address of 'pulsar::Logger* logger()' will never be NULL [-Werror=address]`.

**To Reproduce**

Compile with `-Wall` and `-Werror`.

**Desktop (please complete the following information):**
 - OS: Linux
 - Compiler: GCC 7.3

**Comment by smazurov** [comment]
#2 is simply wrong and can be null. GCC needs to get its act together :)
