### ISSUE TITLE
Broker znode sometimes remains disappeared

### ISSUE THREAD

**Issue by massakam** [apache/pulsar#752]
In our Pulsar cluster, a broker znode `/loadbalance/brokers/<host>:<port>` is sometimes removed from ZooKeeper and remains disappeared until the broker is restarted.
Steps to reproduce are unknown.

* Pulsar version is 1.19.0-incubating.
* It may occur at the time of rotating a log file of the broker.
* The size of the log file is very large (100MB ~ 1GB).
* A large `*.tmp` file (such as `pulsar_broker.log463886727832637.tmp` if the log file name is `pulsar_broker.log`) is created and remains in the log directory.

**Comment by sijie** [comment]
@massakam it sounds like zookeeper session was gone, but the broker didn't get session expired, so the broker process remained up. did you see similar behaviors recently?

**Comment by sijie** [comment]
close due to no activities.
