### ISSUE TITLE
In some cases, the workerport does not listening after the functions worker process is started.

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#7530]
**Describe the bug**
In some cases, after the functions worker process is started, the workerport does not listen, the process exists, and no error information is found,The broker and functions worker are deployed independently.

pulsar V2.5.2

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jiazhai** [comment]
@xuesong172500 Would you please help provide more details to reproduce this issue? it would be much helpful.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
