### ISSUE TITLE
prebuild protoc incompatible for build project

### ISSUE THREAD

**Issue by Lagranmoon** [apache/pulsar#7531]
**Describe the bug**
I modify the PlusarApi.proto and then use the generate_protobuf_docker.sh to regenerate Java files.But when I rebuild the project using "mvn clean package -DskipTests",it throws errors which says some methods couldn't be found in org.apache.pulsar.common.util.protobuf.ByteBufCodedInputStream, in particular, the pushLimit() method. I revert my code and use master to build again,and the errors still happens.So maybe something wrong with the build environment.

**To Reproduce**
1. Go to pulsar-common module
2. run generate_protobuf_docker.sh to regenerate Java files
3. run mvn package command to rebuild the project

**Expected behavior**
A  new PulsarApi.java file generated with no reference errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS

**Additional context**

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.
