### ISSUE TITLE
Modify the create/update function mode

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#7535]
**Is your feature request related to a problem? Please describe.**

Can the create / update function be used through a storm like framework storm.sh To manage the start and stop of function, some Java options can be modified at will without changing function Runtime code, now function has two class loaders, using similar storm.sh Only one class loader is needed for the command of function. The load balancing of function can be done directly through zookeeper.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.
