### ISSUE TITLE
[Question] How to generate sequenceId for commit marker in partition topic

### ISSUE THREAD

**Issue by gaoran10** [apache/pulsar#7538]
### Context

When publishing messages to a topic, the `sequenceId` param is used for topic message deduplication. 

In the transaction, when the TC receives commit command, the TC needs to write a commit marker append to the topic partition, the commit marker needs a `sequenceId` to avoid duplication, if the commit marker is duplicated the topic partition cursor will send duplication committed messages to the consumer, or we need to find some other approaches to avoid duplication.

Refer to #2664

**Comment by sijie** [comment]
Since the commit is initiated by TC and done by TB. TB first writes a `committing` record to the transaction buffer. You can use the message-id of the `committing` record to create a long number. This can be used as the sequence id to write the commit marker to the data partition.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
