### ISSUE TITLE
Dead code in MultiTopicsConsumerImpl class - occurs if topic name validation failed during subscribing

### ISSUE THREAD

**Issue by git-enzo** [apache/pulsar#7543]
**Describe the bug**

The MultiTopicsConsumerImpl class contains two methods named ```subscribeAsync()``` which return ```CompletableFuture<Void>``` as a result.
The first step in both methods is checking if given topic name is valid using ```topicNameValid()``` method as follow:

```
if (!topicNameValid(topicName)) {
    return FutureUtil.failedFuture(
        new PulsarClientException.AlreadyClosedException("Topic name not valid"));
}
```

The problem is that ```topicNameValid()``` method always returns true or throws an exception. It never returns false, so code inside "if" block is unreachable.

```
   private boolean topicNameValid(String topicName) {
        checkArgument(TopicName.isValid(topicName), "Invalid topic name:" + topicName); // throws Exception
        checkArgument(!topics.containsKey(topicName), "Topics already contains topic:" + topicName); // throws Exception

        return true;
    }
```

**Expected behavior**
Method ```topicNameValid()``` should return false if topic validation failed.

**Comment by sijie** [comment]
@git-enzo Are you interested in contributing a bug fix?

**Comment by 315157973** [comment]
I'm free on the weekend, please assign it to me  :smile:
