### ISSUE TITLE
Create non partition topic err V2.6.0

### ISSUE THREAD

**Issue by lhui1991** [apache/pulsar#7546]
**Describe the bug**

[root@cn-hz-h-test-pulsar00 apache-pulsar-2.6.0]# ./bin/pulsar-admin topics create persistent://picturebook/sale/second_topic
21:34:14.984 [AsyncHttpClient-7-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://localhost:8080/admin/v2/persistent/test/test/test_topic] Failed to perform http put request: java.util.concurrent.CompletionException: org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$RetryException: Could not complete the operation. Number of retries has been exhausted.
null

**Comment by sijie** [comment]
@lhui1991 Did you see any errors at the broker side?
