### ISSUE TITLE
Queue declaration parameters for rabbitMQ source connector configurable 

### ISSUE THREAD

**Issue by joofio** [apache/pulsar#7547]
In the source connector queue declaration, [on line 71](https://github.com/apache/pulsar/blob/master/pulsar-io/rabbitmq/src/main/java/org/apache/pulsar/io/rabbitmq/RabbitMQSource.java) the declaration is hardcoded.

I would like to suggest for this parameters (or at least some of them like durability - the first one) being configurable in the yaml for the connector.

Would bring more configurability and would not enter in error for queues durable (the test i made)

**Comment by sijie** [comment]
@joofio Are you interested in contributing an enhancement to this?

**Comment by liangyuanpeng** [comment]
I want to try this.

**Comment by joofio** [comment]
i am not very handy with java but can help to the best of my knowledge

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.
