### ISSUE TITLE
Function instance/deps class loading mechanism is confused

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#7551]
**Describe the bug**
Function if you use fat jar ${PULSAR_HOME}/instance/deps directory does not work. 
If a non fat jar is used, it will cause many problems. 
For example, 
1. Use a custom schema structure in the input and output types of the function. This schema structure is in another jar, and it must be put into ${PULSAR_HOME}/lib directory, if the schema modifies the member variables, you must restart functions worker;
2. When creating function, function jar must also be placed in ${PULSAR_HOME}/instance/deps directory can it be used normally. In this way, from create function to run successful, the jar of fuction should have 3 copies: 
a) function jar directory specified in bin/pulsar admin --jar ${FUNCTION_JAR_PATH}; 
b) ${PULSAR_HOME}/download directory;
c) ${PULSAR_HOME}/instance/deps directory;

which is too difficult to manage.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
