### ISSUE TITLE
I can't access websocket(embedded) via pulsar-proxy

### ISSUE THREAD

**Issue by darrenx999** [apache/pulsar#7568]
#### Expected behavior

Tell us what should happen

#### Actual behavior

1.I setup a k8s pulsar cluster with values-minikube.yaml. 
2.set webSocketServiceEnabled=true on broker, after restart pod , I can access websocket in pod.
3. I try to access websocket via pulsar-proxy, failed.
error info:
websocket._exceptions.WebSocketBadStatusException: Handshake status 404 Not Found

#### Steps to reproduce

1. helm install --values example/values-minikube.yaml pulsar   apache/pulsar
2. TOPIC = 'ws://localhost:8080/ws/v2/producer/persistent/public/default/message'
    connect ws on broker pod,successful.
3. TOPIC = 'ws://localhost/ws/v2/producer/persistent/public/default/message'
    connect ws on proxy,failed 
#### System configuration
**Pulsar version**: 2.6.0

**Comment by sijie** [comment]
@darrenx999 Current helm chart doesn't support WebSocket. Can you create an issue at https://github.com/apache/pulsar-helm-chart?

**Comment by darrenx999** [comment]
> @darrenx999 Current helm chart doesn't support WebSocket. Can you create an issue at https://github.com/apache/pulsar-helm-chart?

I see,so I modify the  broker config to support ws, but i don't know the workflow of the proxy,why can't access ws via proxy.

**Comment by darrenx999** [comment]
@sijie thanks.

**Comment by sijie** [comment]
@darrenx999 pulsar proxy doesn't support WebSocket protocol. Ideally, you can just add WebSocket as a separate container in the proxy pod and expose the port through proxy loadbalancer.

**Comment by darrenx999** [comment]
> @darrenx999 pulsar proxy doesn't support WebSocket protocol. Ideally, you can just add WebSocket as a separate container in the proxy pod and expose the port through proxy loadbalancer.
@sijie thanks for your advise.
