### ISSUE TITLE
Does puslar-admin support lookup partitioned topic?

### ISSUE THREAD

**Issue by aloyszhang** [apache/pulsar#7571]
Command  
```shell 
$ pulsar-admin topics lookup topic
```
can only search brokerUrl for non-partitioned topic. 
For partition topic we have to use a loop to search each partition which is not convenient

```shell
$ for i in $(seq 0 8); do bin/pulsar-admin topics lookup public/default/test-partition-$i; done
```
Is there any way to search all brokerUrls for patitioned topic by pulsar-admin tool? 
If not,  I think we should add support for it.

**Comment by aloyszhang** [comment]
@sijie Any suggestions about this?

**Comment by sijie** [comment]
That is a great feature to add! +1

**Comment by aloyszhang** [comment]
I'll work on it.
