### ISSUE TITLE
Make encryptionKey property configurable through producer configurations using loadConf method

### ISSUE THREAD

**Issue by 97arushisharma** [apache/pulsar#7579]
Can we make certain extra properties that are supported by pulsar but are not present in the `loadConf()` method implementation, configurable. For Example: Currently I am writing an application that needs to publish messages to apache pulsar with configurations supplied through a properties file. However, I have to explicitly write certain functions while building the producer. And to make these properties optional for my application, I have to supply many if-else statements which is frustrating.

Example: I have the following code already existing in my producer. Now I can work with `cryptoKeyReader=null` but I cannot work with `encryptionKey=null`, if I want to make encryption optional. This will introduce another set of if-else condition.
```
if(partitionColumnIndex > 0 && configProducer.get("messageRoutingMode") != null && configProducer.get("messageRoutingMode").toString().equals(CUSTOM_PARTITION)){
                producer = client.newProducer()
                        .loadConf(configProducer)
                        .messageRouter(this)
                        .topic(topic)
                        .addEncryptionKey(encryptionKey)
                        .cryptoKeyReader(this)
                        .create();

            } else if((partitionColumnIndex == -1 || partitionColumnIndex == 0) && configProducer.get("messageRoutingMode") != null && configProducer.get("messageRoutingMode").toString().equals(CUSTOM_PARTITION)){
                producer = client.newProducer()
                        .loadConf(configProducer)
                        .messageRoutingMode(MessageRoutingMode.RoundRobinPartition)
                        .topic(topic)
                        .addEncryptionKey(encryptionKey)
                        .cryptoKeyReader(this)
                        .create();

            } else {
                producer = client.newProducer()
                        .loadConf(configProducer)
                        .topic(topic)
                        .addEncryptionKey(encryptionKey)
                        .cryptoKeyReader(this)
                        .create();
            }
```

**Describe the solution you'd like**
We can do any of the following:
* Can we supply encryptionKey and any other property that is currently supported by producer, but not supported by loadConf
* Remove the compulsion of using the specified set of properties in producer configurations. And support all props in `ProducerConfigurationData` class.
* Remove the error that is thrown if the encryptionKey is null. Rather turn it to null and then use `isEncryptionEnabled()` while encrypting.

I am not sure if that will be the best solution. You can suggest something more efficient and elegant.

**Describe alternatives you've considered**
I tried passing the `encryptionKey` along with other properties to the `loadConf()` method. However, I got the following error:
```
java.lang.RuntimeException: Failed to load config into existing configuration data
org.apache.pulsar.shade.com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "encryptionKey" (class org.apache.pulsar.client.impl.conf.ProducerConfigurationData), not marked as ignorable (19 known properties: "compressionType", "autoUpdatePartitions", "messageRoutingMode", "maxPendingMessagesAcrossPartitions", "batchingMaxMessages", "batchingMaxBytes", "batchingPartitionSwitchFrequencyByPublishDelay", "properties", "blockIfQueueFull", "hashingScheme", "topicName", "producerName", "sendTimeoutMs", "initialSequenceId", "batchingEnabled", "multiSchema", "maxPendingMessages", "cryptoFailureAction", "batchingMaxPublishDelayMicros"])
```

**Additional context**

**Comment by jiazhai** [comment]
@97arushisharma  all the properties are defined in `ProducerConfigurationData`.  please use `encryptionKeys` instead of `encryptionKey`
