### ISSUE TITLE
Root pom is inconsistent with dependency versions as property variables

### ISSUE THREAD

**Issue by vcottagiri** [apache/pulsar#7583]
Most of the version declarations in the root pom are ${} placeholders, a few are not.
An example of this is

      
      <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>${guava.version}</version>
      </dependency>

     <dependency>
        <groupId>com.beust</groupId>
        <artifactId>jcommander</artifactId>
        **<version>1.48</version>**
      </dependency>

      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-lang3</artifactId>
        **<version>3.6</version>**
      </dependency>

      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-compress</artifactId>
        <version>${commons-compress.version}</version>
      </dependency>

      <dependency>
        <groupId>commons-configuration</groupId>
        <artifactId>commons-configuration</artifactId>
        **<version>1.10</version>**
      </dependency>

      <dependency>
        <groupId>commons-io</groupId>
        <artifactId>commons-io</artifactId>
        **<version>2.5</version>**
      </dependency>

Update the root pom to follow maven recommended conventions.

**Comment by codelipenghui** [comment]
@vcottagiri are you interested in fixing this problem?

**Comment by vcottagiri** [comment]
@codelipenghui - yes, I will fix this one.
