### ISSUE TITLE
LZ4 Compression does not work on Big Endian machines

### ISSUE THREAD

**Issue by epsteina16** [apache/pulsar#7607]
**Describe the bug**
The Pulsar Java Client fails when creating a producer with LZ4 compression with the error "LZ4 requires a little endian platform (found BIG_ENDIAN)". LZ4 is endianness-independent so this is a bug.

**To Reproduce**
1. Configure a Producer with the Java Client to use LZ4 compression.
2. Run the application on a big endian machine.

**Expected behavior**
The producer to compress messages and publish with no error.

**Comment by merlimat** [comment]
@epsteina16 Which kind of machine are you running on?

**Comment by epsteina16** [comment]
AIX based operating system

**Comment by jiazhai** [comment]
This looks like a lib LZ4 issue?

**Comment by epsteina16** [comment]
The error is a io.airlift.compress.IncompatibleJvmException, which indicates it is coming from the underlying LZ4 library. However, https://github.com/lz4/lz4/issues/703 says that this is not an LZ4 issue. Pulsar client 2.4.0 also did not have this issue.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
