### ISSUE TITLE
functions_worker.yml can only configure one pulsarwebserviceurl

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#7614]
**Is your feature request related to a problem? Please describe.**
functions_worker can only configure a pulsarwebserviceurl. If the broker it points to exits abnormally, the functions worker will not work normally and HA will not work. I hope that this can be configured as a pulsarwebserviceurl list for automatic load balancing.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sijie** [comment]
@xuesong172500 You can either use a service URL pointing to a load balancer or DNS. If you don't have a load balancer or DNS, you can also use a multi-broker service URL. It doesn't make sense to add additional HA functionalities beyond the HA functionalities built-in the service URL.

**Comment by tisonkun** [comment]
Closed as answered.
