### ISSUE TITLE
Functions worker load balancing failed

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#7617]
**Describe the bug**
Functions_worker load balancing failed.
Pulsar 2.5.2

**To Reproduce**
My cluster has 3 brokers, 3 bookies and 3 functions workers

1. Start 3 bookies, 3 brokers and 1 functions worker.

2. Create function. Set the parallelism number to 2, so that the 2 parallelism will run on the functions worker that has been started.

3. I start another functions_worker. In theory, the 2 parallelism should be shared equally among the 2 functions_workers. The test results show that there is no parallelism. The 2 parallelism are only on the first function worker that was started originally. Even if the update function operation is executed, the load will not be reloaded, except for delete and then create.

4. If I start 2 functions_workers and set the parallelism number to 2, create Function will load 2 parallelism functions on 2 functions_workers. At this time, 1 functions_worker will be killed, and the function on the functions_worker that has been killed will be loaded on another surviving function worker in 1 minute. However, after I restart the functions_worker that has been killed, the 2 parallelism will not be loaded on this functions_worker.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
