### ISSUE TITLE
[Pulsar Functions] How do I change the "subscriptionposition" of Pulsar Functions and the batching parameters?

### ISSUE THREAD

**Issue by Jye-525** [apache/pulsar#7622]
Hi,

	I am making a comparison between Pulsar Functions and Kafka Streams. I have several questions when using Pulsar Functions.
	
	1) Before creating the Pulsar Functions, I already have a producer. It generates 1000 messages to topic A. Then I start the Pulsar Functions to read data from topic A and do some handling.
	I want the Pulsar Functions could read the 1000 messages which has been existed in topic A when Pulsar Functions starts. How to make the Pulsar Functions to read data from the beginning of a topic?

	2) Does Pulsar Functions use batching when reading data from the input topics and sending data to output topic? How to change the batching parameters, like BacthingMaxSize, BatchingMaxPublishDelay?

	I am looking forward to your response.
	
	Thank you very much

**Comment by sijie** [comment]
@Jye-525 

1) Currently functions doesn't support specifying the subscription initial position. You can use `pulsar-admin topics reset-cursor` to move a subscription to the earliest position. A contribution of adding the functionality is welcomed.

2) Pulsar Functions doesn't expose the producer settings publicly. So you are not able to configure those batch settings. We can consider exposing those settings. Are you interested in contributing a pull request for adding this functionality?

**Comment by 315157973** [comment]
@sijie @codelipenghui Please assign it to me

**Comment by tisonkun** [comment]
Closed by https://github.com/apache/pulsar/pull/7891.
