### ISSUE TITLE
Provide a more accurate message backlog value

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#7623]
*Motivation*

Currently, the message backlog value is measured by the number of entries. It is not based on the number of messages. Hence it is difficult for applications to figure out the exact message count in the backlog. We should provide a mechanism to provide a more accurate message backlog value.

**Comment by diegosalvi** [comment]
I've this exact problem, I need to figure out how many messages are still in the backlog but I receive a backlog count way more lower than the expected number. Finding a message backlog value way lower than excepted give the false feeling that some message has been lost "on the way" (still they are there to be read).

**Comment by codelipenghui** [comment]
@diegosalvi Yes, we are working on a fix currently, the new approach is based on the message index which can provide the message-based backlogs.

**Comment by nicoloboschi** [comment]
Any news here? @codelipenghui

**Comment by diegosalvi** [comment]
Any news on this issue @codelipenghui? It would be really helpful to detect how much "lag" an application has processing events. Currently as fallback I can only know how much "old" is the next event that I have to process but I don't know really if I have 1K events or 1M (just how many entries)

**Comment by eolivelli** [comment]
@diegosalvi 
we already have the 'getPreciseBackLog' option.
Does not work for you ?
https://github.com/apache/pulsar/blob/e2fa1898f7e9a38b1743b2abf21c87eafe126ee2/pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java#L1097

**Comment by diegosalvi** [comment]
I already use the precise backlog but from my understanding still reports entries and not messages.
I should deactivate batches on the producer but it doesn't seem to me a performance wise choice.

**Comment by eolivelli** [comment]
@diegosalvi  would you mind working on this ? the implementation should be pretty straightforward if you take a look to the getPreciseBacklog code path.
The MessageMetadata structure has the number of messages in the Entry.

**Comment by diegosalvi** [comment]
I'm looking into it :)

**Comment by diegosalvi** [comment]
@eolivelli I've looked into getPreciseBacklog code (Topic.getStats -> PersistentSubscription.getStats -> MangedCursor.getNumberOfEntriesInBacklog -> ManagedCursorImpl.getNumberOfEntries).

Probably I'm missing something but from what i saw it "count" entry ranges without looking int any entry at all.
From my undersanding I should read every entry from subscription position up to lac, build theirs metadata and then sum them. It seems very inefficient to me

**Comment by eolivelli** [comment]
@diegosalvi you are correct!
we would need to read all the entries from BK, and that's not doable, because it costs too much, and also you would be going to pollute all the caches.

You can implement it, but we should warn the users that the operation has a very high cost and it should not be done frequently
