### ISSUE TITLE
pulsar-client  ivy resolve problem 

### ISSUE THREAD

**Issue by wangkunSE** [apache/pulsar#7624]
<dependency org="org.apache.pulsar" name="pulsar-client" rev="2.6.0" />
when I use ivy to resolve the dependency on my macbook,  I got this error:

![image](https://user-images.githubusercontent.com/25258968/88134251-ba969900-cc16-11ea-8b55-1ccd5cf68f47.png)

${packaging.type} the suffix break the resolve.

this issue is similar to https://issues.apache.org/jira/browse/IVY-1577.

how about change javax.ws.rs-api to jakarta.ws.rs-api and bump version from 2.1.1 to 2.1.5. it may work.

**Comment by wangkunSE** [comment]
the config is <dependency org="org.apache.pulsar" name="pulsar-client" rev="2.6.0" />.

**Comment by wangkunSE** [comment]
the config is `<dependency org="org.apache.pulsar" name="pulsar-client" rev="2.6.0" />`

**Comment by jiazhai** [comment]
@wangkunSE If 2.1.5 works, Would you like to provide a fix for this?

**Comment by wangkunSE** [comment]
> @wangkunSE If 2.1.5 works, Would you like to provide a fix for this?

ok，I will try

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
