### ISSUE TITLE
[docs] request body description of sinks REST APIs is wrong

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar#7625]
See: https://pulsar.apache.org/sink-rest-api/?version=2.6.0#operation/registerSink

The doc of request body is 

> A JSON value presenting config payload of a Pulsar Sink. All available configuration options are:

And the request sample is:

```json
{  
	"classname": "org.example.MySinkTest",
	"inputs": ["persistent://public/default/sink-input"],
	"processingGuarantees": "EFFECTIVELY_ONCE",
	"parallelism": 10
}
```

But if I changed the header to `Content-Type: application/json` and passed a JSON body, then a 415 response would be received.

From the [source code](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SinksBase.java#L71):

```java
    @Path("/{tenant}/{namespace}/{sinkName}")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    public void registerSink
```

the media type is `multipart/form-data`, and the body contains two parts. The JSON presentation of a `SinkConfig` object is just one part, the other part should be the octet stream of a NAR file or an url of package.

The same goes for `updateSink` REST API.

**Comment by jiazhai** [comment]
Thanks @BewareMyPower . Would you like to help contribute a fix for this issue?

**Comment by BewareMyPower** [comment]
This part of doc seems to be generated by Java annotations, eg. `A JSON value presenting config payload of a Pulsar Sink` is from `@ApiParam` before the following line:

```java
final @FormDataParam("sinkConfig") SinkConfig sinkConfig
```

The above three `@FormDataParam` fields don't have associated `@ApiParam`s. I'm not familiar with JavaDoc, would the addition of `@ApiParam` work? @jiazhai

**Comment by jiazhai** [comment]
From my view,  `ApiParam` should be workable. 
@tuteng @Jennifer88huang Would you please help provide more instructions or examples for @BewareMyPower to reference on this doc fix? It would be better to provide an easy way to verify it.

**Comment by Jennifer88huang** [comment]
@jiazhai got it.

**Comment by srijeyanthan-cerexio** [comment]
Any update on this issue?

**Comment by momo-jun** [comment]
@Anonymitaet seems this issue has been fixed and can be closed.

**Comment by Anonymitaet** [comment]
@momo-jun not yet. Status: https://github.com/apache/pulsar/pull/11716#issuecomment-939882228

**Comment by tisonkun** [comment]
We're using the redoc lib to generate swagger page. It seems not be able to support multipart parameter documents: https://github.com/swagger-api/swagger-core/issues/3070 and https://github.com/Redocly/redoc/issues/707.

Closed as stale. It's far more complex to switch to a better framework or overcome the upstream shortcoming.
