### ISSUE TITLE
Use jackson bom in root pom 

### ISSUE THREAD

**Issue by vcottagiri** [apache/pulsar#7634]
**Describe the bug**
Use the jackson-2.11.1 bom in root pom

**Comment by jiazhai** [comment]
Thanks @vcottagiri what is the potential issues for current version? Would you like to provide a fix for this Jackson upgrade?

**Comment by vcottagiri** [comment]
Will be using the same versions - just pointing it to the bom so that we can we move all of the jackson dependencies in the root pom. 

Tried the same with the jetty dependencies but they had to be [reverted ](https://github.com/apache/pulsar/pull/7638) because unit tests failed, will look into that. There were some issues with the CI builds which does not run unit tests on pom changes. With [#7603](https://github.com/apache/pulsar/pull/7603) - thats fixed. 

I will raise a PR for this

**Comment by vcottagiri** [comment]
@jiazhai - please check [PR](https://github.com/apache/pulsar/pull/7635)
