### ISSUE TITLE
Protobuf Schema support AutoConsumeSchema and Presto table 

### ISSUE THREAD

**Issue by hnail** [apache/pulsar#7642]
**Is your enhancement request related to a problem? Please describe.**
1. Now , `ProtobufSchema` create and persistence dependency Java implementation class of GeneratedMessageV3 , create action code trace is  [ProtobufSchema.of(Class<T> pojo) ](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/ProtobufSchema.java#L102) ->[org.apache.avro.protobuf.ProtobufData.getSchema(Class c)](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/ProtobufSchema.java#L64), but avro-protobuf lib i haven't find method to reflect class by Descriptor，so [ProtobufSchema.loadReader()](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/ProtobufSchema.java#L98) is don't support , and [AutoConsumeSchema.generateSchema()](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java#L149) haven't support PROTOBUF。
3. I am working for  Presto pulsar table , but pulsar current protobuf comsumer need [Java implementation class of GeneratedMessageV3 ](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleTypedProducerConsumerTest.java), Presto is a Long-Running server, so top server then update class is unfriendly。
4.  Regist ProtobufSchema with Java implementation class of GeneratedMessageV3 is unfriendly for other languages instead of JAVA User :  [`SimpleTypedProducerConsumerTest`](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleTypedProducerConsumerTest.java)

------

**Describe the solution you'd like**

**AutoConsumeSchema** support Protobuf , Presto table work with Protobuf schema register

1. ProtobufSchema regist use protoc **descriptor_set_out** file,  persistence this single file content to Schema Registry，.desc conten  is language-independent and readable .
e.g. ``protoc --include_imports --descriptor_set_out=<filename>.desc <filename>.proto <filename>.proto <filename>.proto...``
2.  consumer support Protobuf **AutoConsumeSchema by DynamicMessage** ,e.g.
``` 
BufferedInputStream dscFile = new BufferedInputStream(new FileInputStream(new File ("desc file path")).getPath())
DescriptorProtos.FileDescriptorSet fileDescriptorSet = DescriptorProtos.FileDescriptorSet.parseFrom(dscFile);
```
- **single_message** example:

``DynamicMessage.parseFrom(fileDescriptor.getMessageTypes().get(0), outputStream.toByteArray());``

- **multiple_message** example :
``
DynamicMessage.parseFrom(fileDescriptor.findMessageTypeByName(${MessageName}), outputStream.toByteArray());``
MessageName  persistence with SchemaInfo.properties when create。
3. Then Presto ProtobufSchemaHandler can extract  Field(etc. Value\List\Map ) from DynamicMessage 

------

**Additional context**
If this proposal is approved，I glad to make a more detailed description or PR 。

**tag** : `Client \Schema Registry  with Protobuffer` , `Presto`

**Comment by sijie** [comment]
@hnail That sounds like a good approach! +1 from me. Can you write a PIP for that?

**Comment by hnail** [comment]
ok, thanks for @sijie replying , I will do that a few days
