### ISSUE TITLE
Large message size handling in Pulsar: Chunking support for Shared subscription

### ISSUE THREAD

**Issue by amitkaushal16** [apache/pulsar#7644]
We have requirement of sending large message size over 250 MB for the shared subscription.
As the chunking feature is not enable for shared subscription while we are trying to send the message above 200MB we are getting below error.

2020-07-23 03:53:03,864 -0700 [bookie-io-1-10] ERROR org.apache.bookkeeper.proto.BookieRequestHandler - Unhandled exception occurred in I/O thread or handler
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 406847488 byte(s) of direct memory (used: 1744830464, max: 2147483648)

we have increase nettyMaxFrameSizeBytes value to 2GB which the max value we can set.

**Comment by codelipenghui** [comment]
@amitkaushal16 Looks this issue is same as #7645, close it first.
