### ISSUE TITLE
Large message size handling in Pulsar: Chunking for shared subscription

### ISSUE THREAD

**Issue by amitkaushal16** [apache/pulsar#7645]
We have requirement of sending large message size over 250 MB for the shared subscription.
As the chunking feature is not enable for shared subscription while we are trying to send the message above 200MB we are getting below error.

2020-07-23 03:53:03,864 -0700 [bookie-io-1-10] ERROR org.apache.bookkeeper.proto.BookieRequestHandler - Unhandled exception occurred in I/O thread or handler
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 406847488 byte(s) of direct memory (used: 1744830464, max: 2147483648)

**Comment by rdhabalia** [comment]
@amitkaushal16 yes, right now chunking feature is only available for non-shared subscription. It's little tricky for shared subscription as it requires sequential chunked-messages delivery to one consumer and also need to take other scenarios such as acking, redelivery, keeping multiple chunks in buffers, etc. We will look into this feature soon.

**Comment by tisonkun** [comment]
Closed as stale and no one worked on it. Please open a new issue if it's still relevant to the maintained versions.

**Comment by RobertIndie** [comment]
This feature is implemented in https://github.com/apache/pulsar/pull/16202
