### ISSUE TITLE
AUTO_CONSUME with JSON serialized byte array produces string not byte array

### ISSUE THREAD

**Issue by epsteina16** [apache/pulsar#7657]
**Describe the bug**
When subscribing to a topic with AUTO_CONSUME, where the schema is a JSON serialized class that contains a byte array, Pulsar de-serializes the message value into a string instead of a byte array for the byte array field.

**To Reproduce**
1. Produce to a topic using the Java client with a JSON serialized Java class that contains a byte array (byte[]).
2. Subscribe to that topic with AUTO_CONSUME
3. Get the value of the message with getValue()
4. Get the raw object of the byte array field with getField("name of byte arr field")
5. Check output of .getClass() on that raw object from step 4. This produces java.lang.String. instead of [B or byte[] (simple name).

**Expected behavior**
Step 5 should produce [B or byte[] if using simpleName. Pulsar client should not be encoding a byte array and not decode it to produce the same result.

**Desktop (please complete the following information):**
 - Linux

**Comment by zymap** [comment]
@hangc0276 will handle this issue
