### ISSUE TITLE
Use jersey bom in root pom

### ISSUE THREAD

**Issue by vcottagiri** [apache/pulsar#7658]
Use the [jersey-2.31](https://repo1.maven.org/maven2/org/glassfish/jersey/jersey-bom/2.31/jersey-bom-2.31.pom) bom in root pom

**Comment by sijie** [comment]
@vcottagiri are you working on this?

**Comment by vcottagiri** [comment]
@sijie - yes, i have the changes ready but was waiting for #7665 and #7635 to get merged in first

**Comment by tisonkun** [comment]
Closed by https://github.com/apache/pulsar/pull/13716
