### ISSUE TITLE
Unable to correctly pass JSON object as inline message via CLI pulsar-client

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#7660]
**To Reproduce**
1. Produce message via:
`bin/pulsar-client produce persistent://public/default/testInput -m '{ "test1" : "value1", "test2": "value2" }'`
Also try it like this:
`bin/pulsar-client produce persistent://public/default/testInput -m "{ 'test1' : 'value1', 'test2': 'value2' }"`
and like this:
`bin/pulsar-client produce persistent://public/default/testInput -m '"test1" : "value1", "test2": "value2"'`

2. Try deserializing the message. In none of the above cases will the object deserialize correctly. 
3. 
Save the following text into a file named `test.json`:
`{ "test1" : "value1", "test2": "value2" }`
4. Produce message via:
`bin/pulsar-client produce persistent://public/default/testInput -f test.json`
5. Message deserializes correctly. 

**Expected behavior**
Passing JSON via inline message should produce the same result as passing JSON via file.

**Comment by devinbost** [comment]
With the first attempt, `bin/pulsar-client produce persistent://public/default/testInput -m '{ "test1" : "value1", "test2": "value2" }'`, it only deserializes the first key/value (test1 and value1). The subsequent parameters seem to be ignored.

**Comment by devinbost** [comment]
If only one key/value pair is passed, such as` { "test1" : "value1"}`, it will deserialize correctly. However, it fails if additional pairs are passed.

**Comment by devinbost** [comment]
It appears to be splitting the string on the comma into multiple messages.

**Comment by sijie** [comment]
@devinbost Are you interested in contributing a feature to produce JSON messages to pulsar-client CLI?

**Comment by devinbost** [comment]
@sijie Yes, I can work on this after I complete my current project.

**Comment by afedulov** [comment]
Any progress on this issue?

**Comment by eolivelli** [comment]
There is an open PR of mine that implements this feature

**Comment by billysmt** [comment]
I'm also having issues with this.  Is there a planned fix for this in the future?

**Comment by tisonkun** [comment]
It's about the separator (default to `,`):

```
./bin/pulsar-client produce persistent://public/default/testInput -m '{ "test1" : "value1", "test2": "value2" }' -s "\n"
```
