### ISSUE TITLE
doc for deploying python functions with custom dependencies not explained in 2.6.0

### ISSUE THREAD

**Issue by sergescevenels-naspers** [apache/pulsar#7663]
**Describe the bug**
in the latest version of the documentation (2.6.0), in the function deploy section, it is not explained how to deploy python function with specific dependencies, like for example tensorflow, pandas, numpy,etc...

By looking at the module [python_instance_main.py](https://github.com/apache/pulsar/blob/v2.6.0/pulsar-functions/instance/src/main/python/python_instance_main.py), it looks like you can specify as argument to the key "py":
- a py module
- a zip file
- a wheel file

**Expected behavior**
This should be explained in the doc

**Comment by sijia-w** [comment]
@sergescevenels-naspers The functions are available in the latest version. See https://pulsar.apache.org/docs/en/next/functions-package/#python. Do you have further questions regarding this topic?

**Comment by jcQuartic** [comment]
@sijie Hi bud, is that possible to use TensorFlow as a custom dependency for the pulsar function?

**Comment by momo-jun** [comment]
As @freeznet pointed out, the request has been covered in the [docs](https://pulsar.apache.org/docs/next/functions-package-python/).
@Anonymitaet we can colse this issue.

**Comment by Raunak-Agrawal** [comment]
Is anyone able to run python function locally with custom dependencies? Please share the steps if possible.
