### ISSUE TITLE
stats recorder time unit error

### ISSUE THREAD

**Issue by Lagranmoon** [apache/pulsar#7669]
**Describe the bug**
pulsar client use info level log to record throughput and latency in class org.apache.pulsar.client.impl.ProducerStatsRecorderImpl, but the latency was divided by 1000 by mistake，the ds was already in ms, so there is no need to convert time，it will cause a lot of misunderstanding when testing the producer latency.
![image](https://user-images.githubusercontent.com/24788692/88494152-40d02800-cfe7-11ea-8f2e-fcb023a8cee7.png)

**Comment by codelipenghui** [comment]
Are you interested in fixing it?

**Comment by zymap** [comment]
We can close it because it has been fixed.

**Comment by zymap** [comment]
@codelipenghui
