### ISSUE TITLE
[Java Client] Schema Registry enhancement for protobuf schema

### ISSUE THREAD

**Issue by bigbang489** [apache/pulsar#7674]
We are trying to encode/decode protobuf messages from/to json and we don't have the .class files of protobuf message, there is no way for us to achieve that, because, as my knowledge, we have to have a descriptor file to be able to encode/decode protobuf messages, but the schema registry only store json schema of protobuf message.

**Suggested Solution**
Whenever a producer upload a new schema to a topic, it should also attach the protobuf descriptor file content in schema properties. With the descriptor is attached in schema registry, the client will be able to encode/decode Protobuf binary data correctly

**Comment by sijie** [comment]
@bigbang489 I think this task is related to #7642. 	@hnail is working on a proposal for improving Protobuf schema. I am linking these two issues together for references.
