### ISSUE TITLE
Subscribing to individual partition with AUTO_CONSUME schema results in null pointer exception

### ISSUE THREAD

**Issue by epsteina16** [apache/pulsar#7676]
**Describe the bug**
When subscribing to a single partition with a Java consumer (i.e. subscribing to topic-partition-1 instead of topic), Pulsar does not get the schema back from the server. If the consumer is configured to use AUTO_CONSUME to create generic records, the client fails with a null pointer exception when trying to parse the first message.

**To Reproduce**
1. Use the pulsar-admin CLI to create a partitioned topic
2. With the Java client, create a consumer with Schema.AUTO_CONSUME as the schema type
3. For the topic put a single partition (i.e. topic-partition-1 instead of topic)
4. Receive a Message<GenericRecord> message using consumer.receive()

**Expected behavior**
The client should get the schema for the main topic, as all partitions in the topic share a schema.

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
The null pointer occurs on: org.apache.pulsar.client.impl.schema.AutoConsumeSchema.generateSchema(AutoConsumeSchema.java:150)

The client logs also show that when it is "Configuring schema" for topic it gets back null as the response

**Comment by sijie** [comment]
@epsteina16 what is the version of Pulsar are you using? @codelipenghui recalled that a similar problem was fixed in Pulsar SQL.

**Comment by epsteina16** [comment]
2.6.0 for the client, but 2.4.0 for the broker

**Comment by codelipenghui** [comment]
@epsteina16 Ok, thanks. We will take a look soon.
