### ISSUE TITLE
lookup returns a broker that is no longer in the cluster

### ISSUE THREAD

**Issue by kjaggann** [apache/pulsar#7679]
**Describe the bug**
We have spinned up new brokers, last week, but there is one topic it is still referring to the old broker which is not in the list.
we get following error

```
org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.CompletionException: java.net.UnknownHostException: failed to resolve 'i-073b64a162d0c2a1dfdadfda.ebiz.abc.com' after 8 queries 
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:873)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:93)
```

i-073b64a162d0c2a1dfdadfda.ebiz.abc.com this is an old broker IP which not the part of cluster

we tried to unload the namespace but we got the following error

Reason: java.util.concurrent.CompletionException: org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$RetryException: Could not complete the operation. Number of retries has been exhausted

**Expected behavior**
topic should own the new brokers

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Linux centOs
Pulsar Version: 2.6.0
topic: non-persistent topic

**Comment by merlimat** [comment]
@kjaggann Can you shared (anonymized) broker logs? If the problem is still happening, can you do a ZK stat on what's the state of that bundle? 

eg: 

1. Get the bundle id: 

```
bin/pulsar-admin topics bundle-range $TOPIC
```

2. The bundle Z-Node path:  `/namespace/$TENANT/$NAMESPACE/$BUNDLE`

3. Use zk shell to get stat: `bin/pulsar zookeeper-shell stat /namespace/$TENANT/$NAMESPACE/$BUNDLE`

**Comment by kjaggann** [comment]
@merlimat 
i dont see any thing in the broker logs as this topic is trying to connect to this broker "i-073b64a162d0c2a1dfdadfda.ebiz.abc.com"  which is not in the list 

i checked the zookeeper stats 

WatchedEvent state:SyncConnected type:None path:null
cZxid = 0x1234fff70
ctime = Tue Jul 14 12:10:36 EDT 2020
mZxid = 0x1234fff70
mtime = Tue Jul 14 12:10:36 EDT 2020
pZxid = 0x1234fff70
cversion = 0
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x1000070456b3b87
dataLength = 306
numChildren = 0

**Comment by merlimat** [comment]
Ok, it seems that the z-node is correctly marked as ephemeral at least. 

Could you check the content of that z-node, as in `bin/pulsar zookeeper-shell get /namespace/$TENANT/$NAMESPACE/$BUNDLE`. 

And you could search `0x1000070456b3b87` in both brokers and ZK logs. that should be printing when the ZK session was established and if there were reconnections and so on.

**Comment by kjaggann** [comment]
I dint find any thing in the broker logs with the znode the following are the content of the znode when i tried to get

WatchedEvent state:SyncConnected type:None path:null
{"nativeUrl":"pulsar://i-073b64a162d0c2a1dfdadfda.ebiz.abc.com:6650",
"nativeUrlTls":"pulsar+ssl://i-073b64a162d0c2a1dfdadfda.ebiz.abc.com:6651",
"httpUrl":"http://i-073b64a162d0c2a1dfdadfda.ebiz.abc.com:9200",
"httpUrlTls":"https://i-073b64a162d0c2a1dfdadfda.ebiz.abc.com:8443",
"disabled":false,"advertisedListeners":{}}

**Comment by kjaggann** [comment]
@merlimat 
when i tried to delete the the bundle
./pulsar zookeeper-shell delete /namespace/$Tenant/$Namespace/$bundle
i get
Node does not exist: /namespace/$tenant/$namespace/0x80000000_0xc0000000

even when i tried to do ls /namespace/$Tenant/$Namespace/$bundle
i get node does not exist 

not sure only when i do "get  /namespace/$Tenant/$Namespace/$bundle"
i get the information

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
