### ISSUE TITLE
Pending acks uses lots of heap memory in consumer

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#7680]
**Describe the bug**
![image](https://user-images.githubusercontent.com/12592133/88621285-a0573200-d0d2-11ea-9e1c-8f51f6581b14.png)

As the image shows, a consumer uses more than 2MB heap memory to maintain the pending acks.
**To Reproduce**
This problem can reproduce when doing some performance tests and especially when the batch is disabled.

**Expected behavior**
Reduce the heap memory usages for the pending ack of the consumer

**Additional context**
Pulsar 2.6.0

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
