### ISSUE TITLE
Download maven dependencies into pulsar-build image so that CI builds are faster

### ISSUE THREAD

**Issue by vcottagiri** [apache/pulsar#7684]
**Is your enhancement request related to a problem? Please describe.**
Github CI builds take a of time downloading the maven dependencies every time. Recent CI workflow changes moved to using a builder image for CI. Because of this the github actions/cache step had to be removed.

**Describe the solution you'd like**
If we checkout the master branch and get all the dependencies into the builder docker image, it would reduce the time for subsequent process using this image

**Comment by lhotari** [comment]
#10001 solves maven dependency caching. This issue can be closed.
