### ISSUE TITLE
bouncy-castle-bc-shaded  jar with  bcpkix-jdk jar conflict

### ISSUE THREAD

**Issue by xiaomin0322** [apache/pulsar#7697]
**Describe the bug**

bouncy-castle-bc-shaded  jar with  bcpkix-jdk jar conflict

**To Reproduce**

**Expected behavior**
maven 

<groupId>org.apache.pulsar</groupId>
 <artifactId>bouncy-castle-bc-shaded</artifactId>

 <groupId>org.bouncycastle</groupId>
 <artifactId>bcpkix-jdk15on</artifactId>

class ：org.bouncycastle.jce.provider.BouncyCastleProvider  conflict

code：
Cipher cipher = null;
cipher = Cipher.getInstance("AES/CBC/PKCS7Padding");

Exception:
  Cannot find any provider supporting AES/CBC/PKCS7Padding java.security.NoSuchAlgorithmException: 
 Cannot find any provider supporting AES/CBC/PKCS7Padding at javax.crypto.Cipher.getInstance(Cipher.java:540) 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jiazhai** [comment]
@xiaomin0322 If bc is already included in other module, you could exclude `bouncy-castle-bc-shaded`.

http://pulsar.apache.org/docs/en/security-bouncy-castle/#exclude-bc-non-fips-and-include-bc-fips
https://github.com/apache/pulsar/blob/master/bouncy-castle/bcfips-include-test/pom.xml#L47
