### ISSUE TITLE
Node doest not exist in Zookeeper

### ISSUE THREAD

**Issue by kjaggann** [apache/pulsar#7700]
**Describe the bug**
A Topic when i tried to get the stat in the zookeeper
./pulsar zookeeper-shell get /namespace/$tenant/$Namespace/$Bundle
i got the info
but when i tried to delete 
./pulsar zookeeper-shell rmr /namespace/$tenant/$Namespace/$Bundle
or 
./pulsar zookeeper-shell delete /namespace/$tenant/$Namespace/$Bundle
 i get 
Node does not exist: /namespace/$tenant/$Namespace/$Bundle

Reference:
https://github.com/apache/pulsar/issues/7679

**Comment by codelipenghui** [comment]
Can you get the znode info after you delete the bundle znode failed? Maybe there are some others already deleted this znode after you got info of the znode.

**Comment by kjaggann** [comment]
Hi,
We have investigated the issue, 
when we tried to get the info on zookeeper leader we are getting the error
 "Node does not exist: /namespace/$tenant/$Namespace/$Bundle"

./pulsar zookeeper-shell get /namespace/$tenant/$Namespace/$Bundle
but for the followers we are able to see that the topic is owned by the Broker IP, which is not in the cluster any more

**Investigated weather all the zookeepers are in sync:**
yes,  we have checked all the zookeepers are in the sync

zk_version      3.5.7-f0fdd52973d373ffd9c86b81d99842dc2c7f660e, built on 02/11/2020 11:30 GMT
 zk_avg_latency  0
 zk_max_latency  823
 zk_min_latency  0
 zk_packets_received     30214264
 zk_packets_sent 32424272
 zk_num_alive_connections        7
 zk_outstanding_requests 0
 zk_server_state leader
 zk_znode_count  75190
 zk_watch_count  21394
 zk_ephemerals_count     793
 zk_approximate_data_size        24706628
 zk_open_file_descriptor_count   281
 zk_max_file_descriptor_count    4096
 zk_followers    4
 zk_synced_followers     4
 zk_pending_syncs        0
 zk_last_proposal_size   166
 zk_max_proposal_size    121947
 zk_min_proposal_size    32

so when we tried to delete the znode bundle the leader checks for the node and it throws this exception
we have raised a ticket with zookeeper also
https://issues.apache.org/jira/browse/ZOOKEEPER-3906

please let me know if needed more info

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
