### ISSUE TITLE
support namespace level fuzzy matching

### ISSUE THREAD

**Issue by bin-albin** [apache/pulsar#7709]
We are using Pulsar as a logging service queue to address multiple product and business log output and consumption/alarm issues. We are now using the non-Partiton way to create multiple topics. We now the problem is to maintain a lot of the namespace (different business use different namespace to isolate) so if you create namespace is very much, we need a lot of backend flink pulsar topic data stream to consumption, because of the pulsar is not support namespace level fuzzy matching, the scale is likely to reach thousands of namespace, however, pulsar at the consumer end currently only supports the topic level of regular matching. This will result in a large number of tasks for Flink and high resource consumption. Why not raise the granularity of fuzzy matching to the namespace level?

**Comment by sijie** [comment]
@bin-albin Is your requirement to support namespace matching in regex subscription?

**Comment by bin-albin** [comment]
Yes, it does

**Comment by jiazhai** [comment]
This seems to be a dup to #7846
