### ISSUE TITLE
C++ Client: pulsar.apache.org/api/cpp docs out of date

### ISSUE THREAD

**Issue by Bklyn** [apache/pulsar#7714]
**Is your feature request related to a problem? Please describe.**
The docs at http://pulsar.apache.org/api/cpp/index.html seem to be for an older version of code (i.e. not 2.6.0).  For example, they don't include any mention of  methods on the Message class, like setOrderingKey or getRedeliveryCount.

**Describe the solution you'd like**
I would like to see updated docs

**Describe alternatives you've considered**
Use local docs

**Additional context**
Thanks!

**Comment by Anonymitaet** [comment]
Hi @tuteng, 
1. How can we update [Pulsar C++ client API doc](http://pulsar.apache.org/api/cpp/index.html)? 
2. Does Pulsar C++ client API doc generate from code automatically (like REST API doc or puslar-admin doc)?

**Comment by tuteng** [comment]
https://github.com/apache/pulsar/tree/asf-site/content/api/cpp All api's for cpp have been generated and can be accessed like this https://pulsar.apache.org/api/cpp/2.8.0-SNAPSHOT/ @Bklyn, We can use this command to overwrite the latest version of the api documentation, would you be interested in creating a pr for this file https://github.com/apache/pulsar/blob/master/site2/tools/doxygen-doc-gen.sh?

```
cp -r $ROOT_DIR/target/doxygen/html $ROOT_DIR/generated-site/api/cpp/
```

**Comment by Anonymitaet** [comment]
@Bklyn any thoughts?

**Comment by Bklyn** [comment]
@tuteng not sure what change you're looking for me to make?  Replace the final `mv` with the `cp -r`?

**Comment by Bklyn** [comment]
See linked PR.  Not sure if @tuteng expects two copies of the Doxygen output, one versioned and one not.  I think we may want to cleanup the target dir and not just copy into it as this will potentially accumulate cruft.
