### ISSUE TITLE
How can I reuse consumer?

### ISSUE THREAD

**Issue by become-nice** [apache/pulsar#7717]
If I want to re-subscription some topics for an exist consumer, how can I do it ? I have read the interface of python and C++ client code, but I can't find any interface to do this function. If I use unsubscription interface, it's like that I can't use this consumer anymore. So why not  just close it? Maybe it is my fault, because I don't konw how to use! So can you provide me with some ways or some interface to solve this problem.

Describe the solution you'd like
I want to use the interface to subscription topics for  an exist consumer.

Describe alternatives you've considered
Reuse consumer.

Additional context
Thanks!

**Comment by sijie** [comment]
@become-nice Currently the Multi-Topic consumer is able to support adding and removing topics. But the functionality is not exposed to the API. 

If you are interested in contributing to this feature, feel free to take the issue and make a pull request.

**Comment by MarvinCai** [comment]
@become-nice 
Hi, are you using python or c++ client only or java is also fine?
For java there's already method to do that [subscribeToAdditionalTopic](https://github.com/apache/pulsar/blob/72b9f5d96ca19c358afd83952eed7ab7ebe61e5d/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java#L883), [unSubscribeFromTopic](https://github.com/apache/pulsar/blob/72b9f5d96ca19c358afd83952eed7ab7ebe61e5d/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java#L1042)
For c++ multipleTopicsConsumer we actually also have the ability to subscribe to / unsubscribe from additional topics.
We might able to expose it if necessary.

**Comment by tisonkun** [comment]
Closed as satle. You can ask questions on https://github.com/apache/pulsar/discussions/categories/q-a now.
