### ISSUE TITLE
set-publish-rate  set-dispatch-rate  bug

### ISSUE THREAD

**Issue by xiaomin0322** [apache/pulsar#7718]
**Describe the bug**

set-publish-rate  set-dispatch-rate  No effect

**To Reproduce**

**Expected behavior**

set-publish-rate  set-dispatch-rate  No effect

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by sijie** [comment]
@xiaomin0322 Can you provide more context about the issue your found?

**Comment by xiaomin0322** [comment]
> @xiaomin0322 Can you provide more context about the issue that you found?

 /opt/Apps/pulsar/bin/pulsar-admin namespaces set-publish-rate public/default -m 1000

Producers can send 10000 msg

**Comment by codelipenghui** [comment]
@xiaomin0322 Did you enable the message batching at the producer side?

**Comment by xiaomin0322** [comment]
> @ xiaomin0322您是否在生产方启用了消息批处理？
pulsar-perf   test  

/opt/Apps/pulsar/bin/pulsar-admin namespaces set-publish-rate public/default -b 2242880 

/opt/Apps/pulsar/bin/pulsar-perf produce my-topic  -n 1 -r 10000

Producers can send 10m msg

**Comment by codelipenghui** [comment]
You can try to disable the messaging batch by adding `-bm 1` to the produce perf command

**Comment by xiaomin0322** [comment]
> You can try to disable the messaging batch by adding `-bm 1` to the produce perf command

/opt/Apps/pulsar/bin/pulsar-admin namespaces set-publish-rate public/default -b 2242880

 messaging batch influential ？？

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
