### ISSUE TITLE
Function created but not called

### ISSUE THREAD

**Issue by hansenc** [apache/pulsar#7732]
**Describe the bug**
When I create a function (standalone, Java runtime) and start producing to the function's input topic, I can see that an instance of the function is created in the logs, but the function seems to never be called. Weirdly, if I trigger the function before producing to the input topic, the function is called as expected. I've created a (somewhat) minimal [test project](https://github.com/hansenc/pulsar-scratch) to reproduce this issue. I suspect user error, but I can't figure out what I'm doing wrong.

**To Reproduce**
1. Clone the test project [here](https://github.com/hansenc/pulsar-scratch)
2. `mvn clean package`
3. Run `com.github.hansenc.pulsar.FunctionIT` (from an IDE or otherwise)
4. Notice that `testWithTrigger()` passes while `testWithoutTrigger()` hangs, with the only difference being a call to `pulsar-admin functions trigger...`

**Expected behavior**
I expect the function to be called as messages show up in its input topic without needing to 'trigger' it first.

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
I've tried this with Pulsar version 2.6.0 and 2.5.2 with the same result.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
