### ISSUE TITLE
How can i mock broker ?

### ISSUE THREAD

**Issue by zhijianfree** [apache/pulsar#7740]
in my project system, pulsar is core part. so we need test unit to promise code is correct. but i don't know how to mock pulsar. can offer shou some example about it. we need mock pulsar broker .

**Comment by sijie** [comment]
@codelipenghui @jiazhai Can you provide some guidance on mocking Pulsar broker?

**Comment by jiazhai** [comment]
https://github.com/streamnative/aop/blob/master/tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java

**Comment by sijie** [comment]
@zhijianfree Can you check the example that Jia shared?

**Comment by sijie** [comment]
Closed the issue since Jia has provided the example. If it is not sufficient, please reopen the issue.
