### ISSUE TITLE
[Flaky Test] Pulsar SQL integration test

### ISSUE THREAD

**Issue by gaoran10** [apache/pulsar#7750]
**Describe the bug**
Currently, the Pulsar SQL integration test couldn't work well in ci-action, but it could work well in a local evn, so I add this issue to track this problem.

1. We should update the `ci-integration-sql.yaml`,  we need to add step `build pulsar image` and `build pulsar-all image` to make sure the integration test uses the latest code.

2. We should reopen the test `TestPrestoQueryTieredStorage` for query offload data.

**Comment by sijie** [comment]
This has been fixed.
