### ISSUE TITLE
Producers are Failing to Create when Connecting to a "Non-Persistent Partitioned Replicated" Topic

### ISSUE THREAD

**Issue by Saswatibhoi** [apache/pulsar#7763]
We have found a bug, where the producers are failing to create when connecting to a "non-persistent partitioned replicated" topic. Looks like the replicator fails to start based on the logs we see on the broker. The producer connects fine when it is a "non-persistent partitioned" topic but not replicated. The producer also connects fine when it is a "persistent partitioned replicated" topics. The issue occurs only when it is a "non-persistent partitioned replicated" topic. To make it more clear,

"non-persistent partitioned replicated" >> fails to create producers.
"non-persistent partitioned non-replicated" >> successfully creates producers.
"persistent partitioned replicated" >>  successfully creates producers.
"persistent partitioned non-replicated" >>  successfully creates producers.

**Logs**
18:19:56.844 [pulsar-io-23-3] WARN  org.apache.pulsar.broker.service.ServerCnx - Failed to get Partitioned Metadata [/127.0.0.1:54694] non-persistent://xxxx/yyyyy/zzzzz: non-persistent://xxxx/yyyyy/zzzzz failed to start replicator for us-west
org.apache.pulsar.broker.service.BrokerServiceException$NamingException: non-persistent://xxxx/yyyyy/zzzzz failed to start replicator for us-west

**Comment by congbobo184** [comment]
I haven't tested anything wrong with the current master branch. can you provide specific steps to reproduce? (topic name, namespace name, broker version, autoCreateTopicConfig and what you can think of).thanks.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
