### ISSUE TITLE
Duplicate Pulsar Functions instance (Pulsar 2.5.2)

### ISSUE THREAD

**Issue by opera33** [apache/pulsar#7770]
Recently observe a weird behavior where Pulsar Function will open up multiple instance of its own, we have seen 2 instances, and 3 instances of the same function but we only have the parallelism set at 1.

Deleting the function will only result in stopping one of the instance. and the other one will be running, which on the admin api, it reported the function is stopped.

Anyone seen this or can help out on this?

**Comment by sijie** [comment]
@opera33 Can you provide more context about your setup?

- What runtime are you using (thread vs process)?
- Is it a cluster or standalone?
- Any other information can provide us the context for debugging?

**Comment by opera33** [comment]
1.Process
2. 3 Nodes cluster with only 2 function workers
3. Not sure if I can reproduce this, or which log file will give some meaningful information?

Restarted the brokers, and it seem the issue go away.

**Comment by tisonkun** [comment]
Closed as stale. Feel free to open a new issue if it's still relevant for maintained versions.
