### ISSUE TITLE
Pulsar metrics providing wrong information

### ISSUE THREAD

**Issue by Esakkimuthu991** [apache/pulsar#7799]
**Pulsar metrics endpoint provides irrelevant information**
Wanted to create pulsar grafana dashboard. we rely on */metrics* endpoint. In that *pulsar_topics_count* provides wrong information/ Correct me if the understanding is different.
 
**To Reproduce**
We created two namespaces -> sample1, sample2
In sample1 we have 6 topics.
In sample2 we have 3 topics.

then pulsar_topics_count metrics as below

pulsar_topics_count{cluster="cluster1",namespace="public/sample1"} 6 1597206282645
pulsar_topics_count{cluster="cluster1",namespace="public/sample2"} 9 1597206282645

**Expected behavior**
But the 2nd metric should provide information as below
pulsar_topics_count{cluster="cluster1",namespace="public/sample2"} 3 1597206282645

**Comment by codelipenghui** [comment]
Are the topics partitioned under the namespace `public/sample2`? Pulsar will count each partition into a topic.

**Comment by Esakkimuthu991** [comment]
> Are the topics partitioned under the namespace `public/sample2`? Pulsar will count each partition into a topic.

No, Its not a partitioned topic
