### ISSUE TITLE
Pulsar SQL can't query the InactiveTopics and un-managedLedger

### ISSUE THREAD

**Issue by hnail** [apache/pulsar#7811]
## **Describe the bug**
Pulsar SQL can't query the InactiveTopics and un-managedLedger 

### Pulsar SQL  [PulsarSplitManager.getSplitsForTopic()](https://github.com/apache/pulsar/blob/master/pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarSplitManager.java#L261) split with this code:
``readOnlyCursor = managedLedgerFactory.openReadOnlyCursor(
                    topicNamePersistenceEncoding,
                    PositionImpl.earliest, new ManagedLedgerConfig());``

this will producing two unexpected result for me :

### 1) when producer expired with brokerDeleteInactiveTopicsMaxInactiveDurationSeconds ,the topic will log this on **broker** :

``08:31:43.073 [bookkeeper-..] INFO  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://aa/bb/cc-partition-0] Topic deleted successfully due to inactivity``

 that will raise exception on  **presto** :

``org.apache.bookkeeper.mledger.ManagedLedgerException$ManagedLedgerNotFoundException: org.apache.bookkeeper.mledger.ManagedLedgerException$MetadataNotFoundException: Managed ledger not found``
### 2) adjust brokerDeleteInactiveTopicsMaxInactiveDurationSeconds to infinite :

[PulsarSplitManager.getSplitsForTopic()](https://github.com/apache/pulsar/blob/master/pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarSplitManager.java#L261) only return the managedLedger (look like the Ledger with writing status, only one Ledger for one partiton  ) , that case lost read the history data。

### **Expected behavior**
Pulsar SQL can read history or Inactive Topic data

_is there any interface that  can read all history Ledger data ?_

### **Additional context**
TAG : `managed-ledger` `Pulsar SQL`

**Comment by sijie** [comment]
@hnail Can you disable `deleteInactiveTopics` and enable retention?

**Comment by sijie** [comment]
We can improve the error message. /cc @codelipenghui in the conversation.

**Comment by hnail** [comment]
> @hnail Can you disable `deleteInactiveTopics` and enable retention?

Thanks for your reply, I will try this  and  fed back to this issues today

**Comment by hnail** [comment]
> @hnail Can you disable `deleteInactiveTopics` and enable retention?

@sijie Thanks for your reply , set  `retentionTimeInMinutes` `retentionSizeInMB` works for my test .

I think we should prompted  `retention` and `deleteInactiveTopics` on  [Pulsar SQL Overview doc](https://pulsar.apache.org/docs/en/sql-overview/)

**Comment by sijie** [comment]
@hnail Agreed.

@Huanli-Meng @Jennifer88huang Can you work with @hnail on adding documentation to the Pulsar SQL doc?

**Comment by Huanli-Meng** [comment]
ok

> @hnail Agreed.
> 
> @Huanli-Meng @Jennifer88huang Can you work with @hnail on adding documentation to the Pulsar SQL doc?
