### ISSUE TITLE
functions-worker jvm metrics error

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#7815]
**Describe the bug**
functions-worker process model：
1.After the functions worker is started, if you do not create function, you cannot get any JVM metrics information.
2.The indicators of functions worker shown in the JVM metrics dashboard are not correct. It should be the indicators collected by functions worker. The in heap memory is set to 4G. However, the maximum in heap memory of functions worker shown in the dashboard is always 1g.

functions-worker thread model：
1.After the functions worker is started, if you don't create function, you can't get any metrics information.
2.After create function, only the functions runtime processed metrics information, but no functions worker JVM metrics information.

pulsar 2.5.2
![image](https://user-images.githubusercontent.com/54351417/90207776-b4f93100-de19-11ea-96d0-dfd0fd326444.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by sijie** [comment]
@xuesong172500 Do you mean function worker metrics or function metrics?

**Comment by xuesong172500** [comment]
@sijie function worker

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
