### ISSUE TITLE
Upgrading the presto to the last version

### ISSUE THREAD

**Issue by alexku7** [apache/pulsar#7829]
Hello
Currently the pulsar is using 0.206 presto version.
We have several issues with this relatively old version .
For example we want to use some new feature introduced in this version https://prestosql.io/docs/current/release/release-310.html but can't 
Could i ask to upgrade the presto to the last stable version  ? 

Tanks

**Comment by codelipenghui** [comment]
@gaoran10 Could you please help take a look at this issue?

**Comment by moshonb6** [comment]
We are using http header "X-Presto-Max-Size" but seems that the header is being ignored.
We always get chunks of 2MB. may it be also related to the old presto db version?

**Comment by gaoran10** [comment]
@moshonb6 Hi, the presto version is updated to `332` in the  Pulsar master branch, please have a try, thanks.

**Comment by sijie** [comment]
Closed this issue since the presto version has been upgraded to the latest version.
