### ISSUE TITLE
Add The Ability To Set Log Level From Environment Variables In Docker

### ISSUE THREAD

**Issue by toneill818** [apache/pulsar#7838]
Currently there are not scripts or set to configure the log YAML file from environment variables. There are for other non YAML configuration files. 

**Describe the solution you'd like**
Add a script to the docker container that can read PULSAR_PREFIX_LOG_LEVEL and set it in the yaml file.

**Describe alternatives you've considered**
Being able to set the log level within the configuration files such as the broker.conf. 
I tried setting the following, but still get INFO messages. (I tested this on the broker).
```
PULSAR_LOG_ROOT_LEVEL=WARN
PULSAR_ROOT_LOGGER=WARN,CONSOLE
```

**Comment by jiazhai** [comment]
May need this change (https://github.com/apache/pulsar/pull/7789) as well. It will be available in 2.6.1 release.

**Comment by hangc0276** [comment]
@toneill818 you can try to set `pulsar.log.root.level` in pulsar-env.sh, and it will override the `log4j.yml` default configuration.

**Comment by toneill818** [comment]
@hangc0276 I am running this in Kubernetes. I will see if the helm chart has a way to edit values inside of the pulsar-env.sh or try and add it if there isn't a way.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
