### ISSUE TITLE
Cross-Site Scripting: DOM

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/pulsar#7872]
https://github.com/apache/pulsar/blob/f53c9d33176a06a9a283beea9269d802c467f71e/site2/website/static/js/getSwaggerByVersion.js#L2-L18

Sending unvalidated data to a web browser can result in the browser executing malicious code.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
