### ISSUE TITLE
Unable to disable TTL for a namespace when a default TTL is specified

### ISSUE THREAD

**Issue by rivernate** [apache/pulsar#7875]
**Describe the bug**
When there is a cluster level configuration for `ttlDurationDefaultInSeconds` it's not possible to disable it at a namespace level

**To Reproduce**
1. Set the `ttlDurationDefaultInSeconds` at the cluster level
2. For a namespace try disabling the ttl with `pulsar-admin namespaces set-message-ttl my-tenant/my-ns --messageTTL 0`
3. Get the ttl for the namespace with `pulsar-admin namespaces get-message-ttl my-tenant/my-ns`
4. It returns the cluster level setting.

**Expected behavior**
You should be able to disable the TTL for a namespace

**Additional context**
This causes problems with not being able to consume messages from the begining of a topic, see: GH-6847

**Comment by codelipenghui** [comment]
@rivernate Thanks for your feedback, do you want to disable the TTL on a namespace when the broker level TTL is enabled?

**Comment by rivernate** [comment]
yes, for now I set it to the max, but ideally I would be able to disable it completely.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
