### ISSUE TITLE
Intermittent test failure ReplicatorTest.testResumptionAfterBacklogRelaxed

### ISSUE THREAD

**Issue by rdhabalia** [apache/pulsar#788]
[Jenkins job](https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/450/testReport/junit/org.apache.pulsar.broker.service/ReplicatorTest/testResumptionAfterBacklogRelaxed/)

**Output:**

```
Error Message

expected [0] but found [1]
Stacktrace

java.lang.AssertionError: expected [0] but found [1]
	at org.apache.pulsar.broker.service.ReplicatorTest.testResumptionAfterBacklogRelaxed(ReplicatorTest.java:742)

```

**Comment by merlimat** [comment]
Test was fixed in e4fc42da737f5d62bb4d19e2d306a1d7101ba9bf and 1921bd98f20991248892717bbcfc102545e7c49c
