### ISSUE TITLE
Create partitioned topics from clients

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#7889]
**Is your feature request related to a problem? Please describe.**
Even if autoTopicCreationType is set to `partitioned` we need to call the REST API to create partitioned ones.

**Describe the solution you'd like**
The abitlity for clients to create auto create partitioned topics with field like `.partitioned(true).partitionsNumbers(1)`.

**Comment by sijie** [comment]
@KannarFr If the `autoTopicCreationType` is set to `partitioned`, you don't need to call REST API to create partitioned ones.  The broker should automatically created the partitioned topic and its partitions.  @codelipenghui can chime in about this.
