### ISSUE TITLE
Warning when using compression in producer

### ISSUE THREAD

**Issue by ErikJansenIRefact** [apache/pulsar#7892]
The following warning message is displayed when producing messages in batch with LZ4 compression enabled:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.airlift.compress.lz4.UnsafeUtil (file:/Users/erik/.m2/repository/io/airlift/aircompressor/0.16/aircompressor-0.16.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of io.airlift.compress.lz4.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by sijie** [comment]
@ErikJansenIRefact Are you using JDK 11?

**Comment by ErikJansenIRefact** [comment]
Yep. Changed the JDK for the project. This fixed the warning.
