### ISSUE TITLE
Report compacted topic ledger info when calling get internal stats

### ISSUE THREAD

**Issue by MarvinCai** [apache/pulsar#7895]
For get-internal-stats of persistent topic admin cli: https://pulsar.apache.org/docs/en/2.6.0/admin-api-persistent-topics/#get-internal-stats, we can also return the compacted topic ledger id if compaction is enabled. So we'll able to read from ledger without creating additional subscription, it can benefit like querying compacted topic from Pulsar SQL.

**Comment by MarvinCai** [comment]
please assign to me

**Comment by sijie** [comment]
Done
