### ISSUE TITLE
[docs] Broken link on website

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#7912]
If I click here:
![image](https://user-images.githubusercontent.com/7418031/91357780-02c55000-e7af-11ea-821d-6b42356f3918.png)
I get this:
<img width="642" alt="Screen Shot 2020-08-26 at 3 14 43 PM" src="https://user-images.githubusercontent.com/7418031/91357798-09ec5e00-e7af-11ea-9d7e-e2cf0d4cfe53.png">

**Comment by jiazhai** [comment]
@Jennifer88huang @Huanli-Meng  Would you please help take a look?

**Comment by Jennifer88huang** [comment]
@devinbost thanks for raising the issue.
@jiazhai got it. Will check soon.

**Comment by jiazhai** [comment]
would like to close this issue, since this is a dup to #7915
