### ISSUE TITLE
Active consumer listener is only supported for failover subscription

### ISSUE THREAD

**Issue by harissecic** [apache/pulsar#7913]
**Describe the bug**
Since I tried to update to 2.6.1 I keep getting this error "Active consumer listener is only supported for failover subscription". I have only 1 exclusive consumer per topic with same name. This worked prior to upgrade. Changing subscribers to Failover doesn't help. Changing subscription names also does not help.

**To Reproduce**
1. Upgrade to 2.6.1
2. Try to use Consumer on some topic

**Expected behavior**
Consumer should listen to specified topic

**Desktop (please complete the following information):**
 - OS: Windows 10 and Pop!_OS Linux

**Additional context**
I'm trying to make Micronaut integration for this and tests are made through Testcontainers

**Comment by harissecic** [comment]
Apparently Consumers have builder method _consumerEventListener_ which was not usable by me even if my subscribers were set to _Failover_. After removing such listener it problem was gone. Not sure if I should close the issue or this should be reevaluated by Pulsar team as bug?

**Comment by jiazhai** [comment]
@harissecic , There seem no related changes in 2.6.1 to assign value to `consumerEventListener `.  Did you assign some value in your code?

**Comment by harissecic** [comment]
> @harissecic , There seem no related changes in 2.6.1 to assign value to `consumerEventListener `. Did you assign some value in your code?

Sorry for the confusion, I did assign values myself to produce some events. However I noticed that only Failover subscriptions should be used. I changed my subscriptions to fail-over and it still didn't work. Anyway I removed this and made workaround where I only notify rest of the application when consumers subscribe. I don't really need the feature that much but it would be quite good for monitoring when consumer became active or inactive. I'll close this issue now with the assumption that there's more to it than just Failover.
