### ISSUE TITLE
Update the pulsar admin cli java doc to support set/get/remove deduplication on topic level

### ISSUE THREAD

**Issue by Huanli-Meng** [apache/pulsar#7920]
**Describe the bug**
In PR (https://github.com/apache/pulsar/pull/7821), set/get/remove deduplication policy is on topic level. But the pulsar admin cli java doc is not supported accordingly.

https://github.com/apache/pulsar/blob/master/pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java 

**Expected behavior**
Update the CmdTopics.java doc.

@315157973 , cloud you please help update the CmdTopics.java.

**Comment by codelipenghui** [comment]
@315157973 Could you please help take a look at this issue?

**Comment by 315157973** [comment]
please assign it to me
