### ISSUE TITLE
[Python Client 2.6.1] Unable to pip install 2.6.1 client for Python

### ISSUE THREAD

**Issue by frankjkelly** [apache/pulsar#7923]
**Describe the bug**
Documentation says Python Client for 2.6.1 is available https://pulsar.apache.org/docs/en/client-libraries-python/
but executing `pip install` only shows the latest as 2.6.0

**To Reproduce**
1.  `$ pip3 install pulsar-client==2.6.1`
2.  Get Response `
ERROR: Could not find a version that satisfies the requirement pulsar-client==2.6.1 (from versions: 2.5.1, 2.5.2, 2.6.0)
ERROR: No matching distribution found for pulsar-client==2.6.1`

**Expected behavior**
Python Client for Pulsar 2.6.1 is found and installed

**Screenshots**
See above

**Desktop (please complete the following information):**
` $ python3 --version
Python 3.8.5
 $ pip3 --version  
pip 20.1.1 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)`

**Additional context**

**Comment by codelipenghui** [comment]
@wolfstudy Could you please help take a looks at this issue? look 2.6.1 does not upload to the pypi

**Comment by wolfstudy** [comment]
@frankjkelly Now we can use the client of python 2.6.1 normally

![image](https://user-images.githubusercontent.com/20965307/92573881-f8c84480-f2b8-11ea-9ad5-7b564983f0c4.png)

**Comment by frankjkelly** [comment]
Thanks - confirmed on my side too. Just for my understanding was there some "fix" or perhaps just some delay of some sort in PyPi caches?

**Comment by wolfstudy** [comment]
> Just for my understanding was there some "fix" or perhaps just some delay of some sort in PyPi caches?

Yes, Can you install pulsar_client 2.6.1 locally?

**Comment by frankjkelly** [comment]
Yes I can.

**Comment by wolfstudy** [comment]
> Yes I can.

Thanks @frankjkelly feedback this issue, will close it, If there are other related questions, please reopen it or let me know, thanks.
