### ISSUE TITLE
How to send a c++ struct  using schema in producer ?

### ISSUE THREAD

**Issue by shengjh** [apache/pulsar#7945]
Hello, I'm trying to send a c++ struct(protobuf generated from proto file) in my c++ producer. 
I can set a schema for a producer, but i don't know how to send my struct.(seems the cpp doc does not explain this.)

The question is, what should be passed to MessageBuilder().setContent(...)?
```cpp
Message msg = MessageBuilder().setContent(...).build();
Result res = producer.send(msg);
```

**Comment by BewareMyPower** [comment]
There're 2 ways to create a `Message` with C++ client

```c++
    /**
     * Set content of the message. The message contents will be managed by the system.
     */
    MessageBuilder& setContent(const void* data, size_t size);
    MessageBuilder& setContent(const std::string& data);

    /**
     * Set content of the message to a buffer already allocated by the caller. No copies of
     * this buffer will be made. The caller is responsible to ensure the memory buffer is
     * valid until the message has been persisted (or an error is returned).
     */
    MessageBuilder& setAllocatedContent(void* data, size_t size);
```

- data: the pointer to your struct
- size: the struct's size

**Comment by shengjh** [comment]
In this way, how to deserialize the message in consumer? My consumer is using go client.

**Comment by BewareMyPower** [comment]
You should encode your struct manually, see [#5057](https://github.com/apache/pulsar/issues/5057)

**Comment by shengjh** [comment]
Thanks, @BewareMyPower
