### ISSUE TITLE
Force namespace deletion even if not empty

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#7959]
**Is your enhancement request related to a problem? Please describe.**
Currently namespace needs to be empty to be deleted.

**Describe the solution you'd like**
I think we should have a optional field to force the deletion of all stuffs related to namespace and delete them and finally delete the namespace.

**Comment by murong00** [comment]
We have implemented this feature in our dev branch and I will finish this later when available.

**Comment by KannarFr** [comment]
@murong00 can you create a PR and maybe i can contribute to it?
