### ISSUE TITLE
functions-worker healthCheck fail

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#7967]
**Describe the bug**
![image](https://user-images.githubusercontent.com/54351417/92081102-26af1400-edf5-11ea-8390-3d158dda95b6.png)

pulsar 2.5.2

**To Reproduce**
1. create 100+ functions in functions-worker node
2.Use the ps command to check the existence of the process of function, but the port and metrics port of function are not in the listening state, and there is no normal output in the log file of function instance.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.

Now, you can ask questions in https://github.com/apache/pulsar/discussions/categories/q-a instead, since we almost use issues to track actionable tasks.
