### ISSUE TITLE
pulsar-client not usable in a jpms (java modules) setup

### ISSUE THREAD

**Issue by guyv** [apache/pulsar#7971]
- pulsar-client and pulsar-api both contain the packages org.apache.pulsar.common.schema which causes a split package problem when our application is ran on the module path. (upgrading from 2.5.2 to 2.6.1)

Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules pulsar.client.api and pulsar.client export package org.apache.pulsar.common.schema

- aircompressor and pulsar-client both contain the packages io.airlift.compress.zstd

Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules aircompressor and pulsar.client export package io.airlift.compress.zstd

This was not a problem on the 2.5.x versions.

**Comment by hollander-cegeka** [comment]
This is still an issue:
java.lang.module.ResolutionException: Modules pulsar.client and pulsar.client.admin.api export package org.apache.pulsar.common.naming

**Comment by tisonkun** [comment]
@guyv @hollander-cegeka could you provide a demo repo or minimal file set to reproduce the issue?

Then other community members can verify whether their fix is viable.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
