### ISSUE TITLE
Call to create state table blocks inside the JavaInstanceRunnable class

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#7982]
**Describe the bug**
The call to  storageAdminClient.getStream(tableNs, tableName) inside the JavaInstanceRunnable task blocks forever. 

**To Reproduce**
 1. Start docker container using the following command: docker run -id --name pulsar -p 6650:6650 -p 8080:8080 -p 4181:4181 apachepulsar/pulsar standalone

2. Configure a LocalRunner instance to use the state store as follows: 
        LocalRunner localRunner =
           LocalRunner.builder()
          .brokerServiceUrl("pulsar://localhost:6650")
          .stateStorageServiceUrl("bk://localhost:4181")
          .sourceConfig(sourceConfig)
          .build();

  3. Set a breakpoint at line 345 of the JavaInstanceRunnable class

  4. Start the localrunner in debug mode

**Expected behavior**
The first time you access the table service, and exception should be thrown to indicate that the table does not exist. This exception should be caught and handled accordingly

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
