### ISSUE TITLE
Number format exception when create function with multiple service url address

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#8009]
**Describe the bug**
Number format exception when create function with multiple service url address

**To Reproduce**
1. Use pulsar-admin to createFunction and specify multiple service URL for the function config.
2. See error

**Expected behavior**
Allow using multiple service URL when creating function

**Additional context**
2.6.1

**Comment by zymap** [comment]
Hi @codelipenghui, could you please provide the create function command and the detail of the error message?

**Comment by jianyun8023** [comment]
> Hi @codelipenghui, could you please provide the create function command and the detail of the error message?

I have reproduced the problem and I am solving it.

**Comment by jianyun8023** [comment]
The root of this problem is that PulsarAdmin does not support multiple multiple service url address.
I think the solution to this problem is to **add validation of the `serviceHttpUrl` parameter**.
@sijie @codelipenghui @zymap Everyone, do you think how to solve this problem is better?

for example:
```
final PulsarAdmin admin = PulsarAdmin.builder()
    .serviceHttpUrl("http://localhost:8080,http://localhost:8081")
    .build();
FunctionConfig functionConfig = buildFunctionConfig();
admin.functions().createFunction(functionConfig, "pulsar-functions-api-examples.jar");
```

**Comment by jianyun8023** [comment]
@codelipenghui pr #8143 has solved the NumberException problem. The current question is whether to close or newly open Function to support the multiple service url address.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
