### ISSUE TITLE
always  Received too big frame size  when i use golang lib to consume 

### ISSUE THREAD

**Issue by ericwangdka** [apache/pulsar#8021]
**Describe the bug**
when i use pure golang lib to consumer topic is always shows  Received too big frame size and the handshake error and exit ,how can i to do whit it?

**Comment by sijie** [comment]
@ericwangdka Are you using the binary service URL or HTTP service URL?

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.

Now, you can ask questions in https://github.com/apache/pulsar/discussions/categories/q-a instead, since we almost use issues to track actionable tasks.
