### ISSUE TITLE
create pulsar-io source/sink fail by use "--sink-config-file"

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#8022]
**Describe the bug**
![image](https://user-images.githubusercontent.com/54351417/92605187-02b36d00-f2e4-11ea-95ef-68457c71a7cd.png)
![image](https://user-images.githubusercontent.com/54351417/92605483-5f168c80-f2e4-11ea-84f2-5579bec0d45c.png)
![image](https://user-images.githubusercontent.com/54351417/92605212-09da7b00-f2e4-11ea-98f3-0e225d5f8d1e.png)

create pulsar-io source/sink fail by use "--sink-config-file", but use "--sink-config" key/value is ok.
pulsar 2.5.2

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Technoboy-** [comment]
@xuesong172500 Hi, --sink-config-file should be in YAML format and source-config is JSON format.

**Comment by sijie** [comment]
Close this issue since the question has been answered by @Technoboy-
