### ISSUE TITLE
The consumption performance index cannot be obtained, and the obtained value is all 0

### ISSUE THREAD

**Issue by g0715158** [apache/pulsar#8023]
Describe the bug
The consumption performance index cannot be obtained, and the obtained value is all 0

To Reproduce

1. Send and consume messages
2. Obtain indicator information through the indicator interface  http://ip:8080/metrics/
3. Observe the pulsar_rate_out indicator information

Additional context:
version：2.5.2
class:NamespaceStatsAggregator
method:getTopicStats

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
