### ISSUE TITLE
enableReplicatedSubscriptions is not used.

### ISSUE THREAD

**Issue by k2la** [apache/pulsar#8030]
It seems that "Replicated Subscriptions" is always enabled because `enableReplicatedSubscriptions` is not used.
- https://github.com/apache/pulsar/search?q=enableReplicatedSubscriptions&unscoped_q=enableReplicatedSubscriptions
- https://github.com/apache/pulsar/blob/22b8923a251c3356401090dacb8ff97fd37d14c1/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java#L688

**Comment by k2la** [comment]
Is the behavior decided when Replicated Subscriptions is OFF ?
I think the behavior is as the following in the case:
- Brokers send `NotAllowedException` to consumers that subscribe with replicated subccription.
- Replicators don't send marker messages and deal with them.

I will try to implement the above behavior by the following ways.
Please let me know if there are any problems.

#### Brokers send `NotAllowedException` to consumers that subscribe with replicated subccription.
Like Key_Shared, send `NotAllowedException` in `PersistentTopics#subscribe`:
https://github.com/apache/pulsar/blob/v2.6.1/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L533-L539

#### Replicators don't send marker messages and deal with them.
Broker do not create `ReplicatedSubscriptionsController` instance that sends marker messages.
Fix to enter the following if statement:
https://github.com/apache/pulsar/blob/v2.6.1/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L2158-L2162

**Comment by sijie** [comment]
It is fixed by #8144
