### ISSUE TITLE
Unable to use state store in LocalRunner

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#8040]
**Describe the bug**
When configuring the LocalRunner to use a storageClientURL, the LocalRunner just hangs. This issue is related to the storage client that is used inside the JavaInstanceRunnable class to create and open the table for the function

**To Reproduce**

LocalRunner runner = LocalRunner.builder()
	   .brokerServiceUrl(container.getPlainTextServiceUrl())
	   .stateStorageServiceUrl(container.getStateStoreUrl()
           .build();

runner.start(false); <--- Call hangs and never returns

**Expected behavior**
We would expect the LocalRunner to continue running.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by lzhpo** [comment]
I also encountered the same problem using LocalRunner.

**Comment by david-streamlio** [comment]
This is fixed in PR https://github.com/apache/pulsar/pull/8042 .....please upvote if you need this fix.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
