### ISSUE TITLE
add Pulsar IO :: RocketMQ

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#8043]
**Is your feature request related to a problem? Please describe.**
RocketMQ Source And Sink.

**Describe the solution you'd like**
Add Pulsar IO :: RocketMQ, RocketMQSource and RocketMQSink.

**Describe alternatives you've considered**

**Additional context**

**Comment by tisonkun** [comment]
Closed as stale and no one worked on it. Please open a new issue if it's still relevant to the maintained versions.

**Comment by tjiuming** [comment]
interesting, I'm willing to work on the issue

**Comment by tisonkun** [comment]
@tjiuming That sounds good. Since this issue is simply "Support RocketMQ Source and Sink" without further context, I suggest you open a new issue to track the work - rolling up legacy tickets can improve their visibility, and most of them just fixed among the years or no longer relevant.
