### ISSUE TITLE
proxy SNI routing: must target hostnames be resolvable to the client?

### ISSUE THREAD

**Issue by racorn** [apache/pulsar#8056]
I tried to set up proxy SNI routing with HAProxy - in a reverse proxy configuration, using the features added for PIP-60. The Pulsar cluster behind HAProxy had hostnames that were only resolvable locally in the datacenter where the HAProxy and Pulsar brokers were deployed.

The client failed with an `UnknownHostExeception `that could be traced to the following lines in the `ConnectionPool `class:
```
        String hostname = unresolvedAddress.getHostString();
        int port = unresolvedAddress.getPort();
        try {
            // For non-sni-proxy: Resolve DNS --> Attempt to connect to all IP addresses until once succeeds
            CompletableFuture<List<InetAddress>> resolvedAddress = isSniProxy()
                    ? CompletableFuture.completedFuture(Lists.newArrayList(InetAddress.getByName(hostname)))
                    : resolveName(hostname);
            return resolvedAddress
                    .thenCompose(inetAddresses -> connectToResolvedAddresses(inetAddresses.iterator(), port));
```
As the resolved hostname is only used as the value of the SNI header field, and not for the TCP-connection (the client connects to the host given in ProxyUrl), **I wonder if it should be required that the 'internal hosts' must be resolvable to the client**? (Also the `InetAddress.getByName` invocation seems to involve blocking IO).

#### System configuration
**Pulsar version**: 2.6.1

**Comment by rdhabalia** [comment]
@racorn 
> As the resolved hostname is only used as the value of the SNI header field, and not for the TCP-connection (the client connects to the host given in ProxyUrl), I wonder if it should be required that the 'internal hosts' must be resolvable to the client?

In SNI-reverse-Proxy, pulsar-client always connects to the proxy-host and passes the pulsar-url as part of SNI header without trying to resolve pulsar broker hosts. Proxy-host which supports SNI-routing , gets the target broker-service-url from SNI and creates proxy between pulsar-client and pulsar-server. Therefore, Pulsar client can only resolve proxy host and client can't resolve any broker hosts. so, pulsar-client does not try to resolve broker-host and passes it to proxy in SNI header without resolving the address.


Can you share the stacktrace for your issue? Pulsar client only tries to resolve proxy host so, can you check if you can resolve porxy-host from the client?

**Comment by racorn** [comment]
Hi Rajan,The behavior you describe is what I thought was expected. But, the method createConnection is invoked with the broker host, then invokes connectToResolvedAddresses which in turn invokes connectToAddress where the broker address is set as the SNI host and the proxy URL host is connected to instead.I suggest that in createConnection InetAddress.getByName is replaced with the parameter 'unresolvedAddress'.Anyway, here is a stacktraceERROR: 2020-09-14 22:29:03.218 [pulsar-client-io-1-2] [ConnectionPool] - Invalid remote url pulsar-3-fra1.internal.mycompany.comjava.net.UnknownHostException: No such host is known (pulsar-3-fra1.internal.mycompany.com)                at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)                at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)                at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)                at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)                at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)                at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)                at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)                at java.base/java.net.InetAddress.getByName(InetAddress.java:1248)                at org.apache.pulsar.client.impl.ConnectionPool.createConnection(ConnectionPool.java:231)                at org.apache.pulsar.client.impl.ConnectionPool.createConnection(ConnectionPool.java:166)                at org.apache.pulsar.client.impl.ConnectionPool.lambda$getConnection$4(ConnectionPool.java:154)                at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)                at org.apache.pulsar.client.impl.ConnectionPool.getConnection(ConnectionPool.java:154)                at org.apache.pulsar.client.impl.ConnectionPool.getConnection(ConnectionPool.java:105)                at org.apache.pulsar.client.impl.BinaryProtoLookupService.findBroker(BinaryProtoLookupService.java:110)                at org.apache.pulsar.client.impl.BinaryProtoLookupService.lambda$null$2(BinaryProtoLookupService.java:128)                at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)                at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)                at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)                at org.apache.pulsar.client.impl.ClientCnx.handleLookupResponse(ClientCnx.java:481)                at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:131)                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)                at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1486)                at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)                at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282)                at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)                at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                at java.base/java.lang.Thread.run(Thread.java:834)Thanks14. sep. 2020 21:28 skrev Rajan Dhabalia <notifications@github.com>:
@racorn

As the resolved hostname is only used as the value of the SNI header field, and not for the TCP-connection (the client connects to the host given in ProxyUrl), I wonder if it should be required that the 'internal hosts' must be resolvable to the client?

In SNI-reverse-Proxy, pulsar-client always connects to the proxy-host and passes the pulsar-url as part of SNI header without trying to resolve pulsar broker hosts. Proxy-host which supports SNI-routing , gets the target broker-service-url from SNI and creates proxy between pulsar-client and pulsar-server. Therefore, Pulsar client can only resolve proxy host and client can't resolve any broker hosts. so, pulsar-client does not try to resolve broker-host and passes it to proxy in SNI header without resolving the address.
Can you share the stacktrace for your issue? Pulsar client only tries to resolve proxy host so, can you check if you can resolve porxy-host from the client?

**Comment by rdhabalia** [comment]
> But, the method createConnection is invoked with the broker host, then invokes connectToResolvedAddresses which in turn invokes connectToAddress where the broker address is set as the SNI host and the proxy URL host is connected to instead.I suggest that in createConnection InetAddress.getByName is replaced with the parameter 'unresolvedAddress

yes, client should avoid resolving the broker address and pass it in SNI header.

**Comment by racorn** [comment]
@rdhabalia 
Sorry for the confusion, I will try to clear things up.

The code below is `ConnectionPool.createConnection`:
```
     /**
     * Resolve DNS asynchronously and attempt to connect to any IP address returned by DNS server
     */
    private CompletableFuture<Channel> createConnection(InetSocketAddress unresolvedAddress) {
        String hostname = unresolvedAddress.getHostString();
        int port = unresolvedAddress.getPort();
        try {
            // For non-sni-proxy: Resolve DNS --> Attempt to connect to all IP addresses until once succeeds
            CompletableFuture<List<InetAddress>> resolvedAddress = isSniProxy()
                    ? CompletableFuture.completedFuture(Lists.newArrayList(InetAddress.getByName(hostname)))
                    : resolveName(hostname);
            return resolvedAddress
                    .thenCompose(inetAddresses -> connectToResolvedAddresses(inetAddresses.iterator(), port));
        } catch (UnknownHostException e) {
            log.error("Invalid remote url {}", hostname, e);
            return FutureUtil.failedFuture(new InvalidServiceURL("Invalid url " + hostname, e));
        }
    }
```

The `unresolvedAddress` argument is the broker host (broker service url). As you can see, if SNI routing is used, the `unresolvedAddress `(broker host) is resolved with `InetAddress.getByName`. If the broker host is not resolvable, the method fails with an `UnknownHostException`. On the other hand, **if** the broker is resolvable, `connectToResolvedAddresses` is invoked, which in turn invokes `connectToAddress` where the broker address is set as the SNI host and the proxy URL host is connected to instead. I mentioned this because I think it shows that the code would work without the need to resolve the broker host when using SNI routing.

My suggestions is to replace the `InetAddress.getByName(hostname)` invocation above with `unresolvedAddress.getAddress` you want to enforce that each broker host is resolvable to the client.

**Comment by rdhabalia** [comment]
@racorn I have created a PR with the fix: https://github.com/apache/pulsar/pull/8062
can you please take a look and see if that will fix your issue.

**Comment by racorn** [comment]
@rdhabalia Thank you very much! I think the refactoring improved the code in several ways and is easier to read as well.

As a side note: Would there be any concurrency issues to worry about with the use of `channelInitializerHandler.setSniHostName/setSniHostPort`? I do not know Pulsar very well, but if the ConnectionPool is used by multiple threads, and one thread tries to connect to broker-a at the same time another thread tries to connect to broker-b, could there be a race condition so a connection attempt to broker-a would use the SNI values that apply to broker-b?

**Comment by tisonkun** [comment]
Closed as stale and it seems to be fixed. Please open a new issue if it's still relevant to the maintained versions.
