### ISSUE TITLE
Consumption Stops When Losing a Bookie.

### ISSUE THREAD

**Issue by evfurman** [apache/pulsar#8069]
**Describe the bug**
Consumers stop consuming when bookie service is stopped.

Slack thread: https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1600113955395000

We have a 4 node bookie cluster utilizing rack awareness, running version `2.6.1.` While testing failure scenarios we stopped the `pulsar-bookie` service on one of the nodes. In the Pulsar Manager consumption throughput dropped to zero across all partitioned topics. Production continued fine. This caused an immediate backlog (obviously). We restarted the `pulsar-bookie` service but consumption did not resume. @addisonj recommended trying to unload the partition which caused consumption to resume.

We are using the default namespace with the following config:
```
# Number of bookies to use when creating a ledger
managedLedgerDefaultEnsembleSize=3
# Number of copies to store for each message
managedLedgerDefaultWriteQuorum=2
# Number of guaranteed copies (acks to wait before write is complete)
managedLedgerDefaultAckQuorum=2
```

**Expected behavior**
We expected higher latencies briefly with the loss of a bookie but would have thought production/consumption would not stop working entirely.

**Screenshots**
Consumption stops.
<img width="1608" alt="Screen Shot 2020-09-14 at 4 31 57 PM" src="https://user-images.githubusercontent.com/7016955/93243653-1c264000-f74e-11ea-9ab9-bcf763b5da68.png">

After unloading partition, consumption resumes.
<img width="1550" alt="Screen Shot 2020-09-15 at 11 50 32 AM" src="https://user-images.githubusercontent.com/7016955/93243590-06b11600-f74e-11ea-834a-20f826ba62ad.png">

**Additional context**
Attaching logs from the brokers.
[pulsar-broker-1.log-09-14-2020-1.log.gz](https://github.com/apache/pulsar/files/5226610/pulsar-broker-1.log-09-14-2020-1.log.gz)
[pulsar-broker-2.log-09-14-2020-1.log.gz](https://github.com/apache/pulsar/files/5226611/pulsar-broker-2.log-09-14-2020-1.log.gz)
[pulsar-broker-3.log-09-14-2020-1.log.gz](https://github.com/apache/pulsar/files/5226612/pulsar-broker-3.log-09-14-2020-1.log.gz)

**Comment by sijie** [comment]
@jiazhai Can you check the broker logs?

**Comment by sijie** [comment]
@evfurman what type of subscription are you using?

**Comment by evfurman** [comment]
`Key_Shared`

We're using the pulsar-perf with the following arguments:

`/pulsar/bin/pulsar-perf consume persistent://public/default/mp-explicit-partitioned --subscriber-name mp-pulsar-consumer -t 8 -st Key_Shared -u pulsar://pulsar.qa.corp.mparticle.com:6650`

**Comment by sijie** [comment]
@evfurman If you are using Key_Shared, you might be impacted by https://github.com/apache/pulsar/pull/8024 

You can try the hotfix:

https://github.com/streamnative/pulsar/releases/tag/v2.6.1-sn-3

See discussions on https://github.com/apache/pulsar/issues/7682#issuecomment-693251109

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.

Now, you can ask questions in https://github.com/apache/pulsar/discussions/categories/q-a instead, since we almost use issues to track actionable tasks.
