### ISSUE TITLE
using CLI consume topic from the beginning behavior is not correct

### ISSUE THREAD

**Issue by dreamcatchernick** [apache/pulsar#8083]
Hi
i am using CLI to consume a topic which already has 100 messages. See the screenshot below
<img width="1721" alt="image" src="https://user-images.githubusercontent.com/8153668/93550995-4d497f00-f99f-11ea-9cfb-fc37e34d371c.png">

given the parameter -p, --subscription-position Earliest. i expect the consumer will consume topic from the beginning. However the output config shows subscriptionInitialPosition : "Latest", which means the consumer consumes from the latest

And I don't see any message print out

pulsar version : 2.6.0

Is this a bug ? Please help
Thanks

**Comment by BewareMyPower** [comment]
It's fixed by [#7795](https://github.com/apache/pulsar/pull/7795).

**Comment by sijie** [comment]
Closed this issue since it is fixed by #7795
