### ISSUE TITLE
Enable authentication for presto sql

### ISSUE THREAD

**Issue by alexku7** [apache/pulsar#8091]
Hello

We try to enable password or/and certificate authentication againt the presto SQL

It seems to be supported by presto sql community for example like this https://prestosql.io/docs/current/security/password-file.html

When we tries to implmenet this kind of authentication we encountered with the error restoServer	Password authenticator  is not registered

After some help from the presto guys we understand that we need 2 things:

1. To upgrade the presto version to the 327 version or higher , which already has done and is waiting to the next release.

2. to include the plugin https://mvnrepository.com/artifact/io.prestosql/presto-password-authenticators in the pulsar image and put in the presto plugin folder.

I would like to ask you to complete the second paragraph :) We need this plugin. Currently no way to prevent people to connect to the presto connector without authentication

**Comment by sijie** [comment]
@alexku7 Are you interested in contributing this feature?

**Comment by alexku7** [comment]
Hello @sijie . I have some concerns about it :( .
I am a devops. I have been implementing the pulsar as part of our infrastructure. I am not sure that my programming skill are good enough for contributing although i have fixed few grafana dashboards and pushed it to your repo :)

**Comment by sijie** [comment]
@alexku7 Gotcha! We will take a look at this part.

**Comment by cdbartholomew** [comment]
@alex-rufo I have a patch for this. I will open a PR soon.

**Comment by cdbartholomew** [comment]
Here is the PR: https://github.com/apache/pulsar/pull/9411

**Comment by sijie** [comment]
@alexku7 I believe you are already able to use password and JWT authentication methods in presto. We have enabled that in our helm chart (https://github.com/streamnative/charts/blob/master/charts/pulsar/templates/presto/presto-coordinator-configmap.yaml#L258). If you are running Pulsar on Kubernetes, you can checkout our latest chart.

**Comment by cdbartholomew** [comment]
Adding the configuration will just cause the server to fail to start, like this: 

```2021-02-02T00:54:38.790Z	INFO	main	io.prestosql.server.security.PasswordAuthenticatorManager	-- Loading password authenticator --
2021-02-02T00:54:38.791Z	ERROR	main	io.prestosql.server.Server	Password authenticator 'file' is not registered
java.lang.IllegalStateException: Password authenticator 'file' is not registered
```

To get it to work, you to do item 2, listed above: "include the plugin https://mvnrepository.com/artifact/io.prestosql/presto-password-authenticators in the pulsar image and put in the presto plugin folder."

If you don't believe me, you are welcome try it.
