### ISSUE TITLE
Failing to create a producer/consumer for function worker should not fail broker

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#8096]
*Motivation*

When running a function worker as part of broker, when the function worker failed to create a producer/consumer, it throws runtime exception to fail the broker. This usually causes a broker restarting multiple times before it actually starts to serve the traffic when running function worker as part of the broker.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
