### ISSUE TITLE
Fix the flaky test testRemoveSubscribeRate

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#8121]
**Describe the bug**
`testRemoveSubscribeRate` in the TopicPolicyTest is a flaky test when run all tests under the TopicPolicyTest. But only run `testRemoveSubscribeRate`.

So in #8114 ignore the `testRemoveSubscribeRate` to make sure other PRs does not block here.

**Comment by hangc0276** [comment]
I will fix it.

**Comment by wolfstudy** [comment]
> I will fix it.

@hangc0276 What is the current status of this issue? Has pr fixed this problem?

**Comment by wolfstudy** [comment]
Move this issue to 2.7.0.

**Comment by codelipenghui** [comment]
Seems this issue is fixed by #8557, So close it first.
