### ISSUE TITLE
can't run pulsar on MAC

### ISSUE THREAD

**Issue by lsroudi** [apache/pulsar#8123]
**Describe the bug**
the configuration is :

3 VMS for bookie and broker
3 VMS for zookeeper
**To Reproduce**

I use this playbook ( https://github.com/lsroudi/ansible-apache-pulsar/blob/master/tasks/main.yml ) to deploy pulsar
Step 1. as you can see on the playbook i use the archive pulsar to deploy the cluster

the configuration of my /etc/hosts is :

```
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
10.10.10.11 broker1.pulsar
10.10.10.12 broker2.pulsar
10.10.10.13 broker3.pulsar
10.10.10.14 zookeeper1.pulsar
10.10.10.15 zookeeper2.pulsar
10.10.10.16 zookeeper3.pulsar
```
the configuration of zookeeper.conf is 
```vagrant@zookeeper2:/opt/apache-pulsar-2.6.1$ cat conf/zookeeper.conf


tickTime=2000
initLimit=10
syncLimit=5
dataDir=data/zookeeper
clientPort=2181
admin.enableServer=true
admin.serverPort=9990
autopurge.snapRetainCount=3
autopurge.purgeInterval=1
forceSync=yes

server.1=zookeeper1.pulsar:2888:3888
server.2=zookeeper2.pulsar:2888:3888
server.3=zookeeper3.pulsar:2888:3888

quorumListenOnAllIPs=true
```

the configuration of bookkeeper is

```
vagrant@broker2:/opt/apache-pulsar-2.6.1$ cat conf/bookkeeper.conf 

bookiePort=3181
journalDirectory=data/bookkeeper/journal
minUsableSizeForIndexFileCreation=1073741824
allowLoopback=false
bookieDeathWatchInterval=1000
flushInterval=60000
gcWaitTime=900000
gcOverreplicatedLedgerWaitTime=86400000
numAddWorkerThreads=0
numReadWorkerThreads=8
numHighPriorityWorkerThreads=8
maxPendingReadRequestsPerThread=2500
maxPendingAddRequestsPerThread=10000
auditorPeriodicBookieCheckInterval=86400
rereplicationEntryBatchSize=100
openLedgerRereplicationGracePeriod=30
autoRecoveryDaemonEnabled=true
lostBookieRecoveryDelay=0
serverTcpNoDelay=true
nettyMaxFrameSizeBytes=5253120
journalFormatVersionToWrite=5
journalMaxSizeMB=2048
journalMaxBackups=5
journalPreAllocSizeMB=16
journalWriteBufferSizeKB=64
journalRemoveFromPageCache=true
journalSyncData=true
journalAdaptiveGroupWrites=true
journalMaxGroupWaitMSec=1
journalBufferedWritesThreshold=524288
numJournalCallbackThreads=8
journalAlignmentSize=4096
journalFlushWhenQueueEmpty=false
ledgerStorageClass=org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage
auditorPeriodicCheckInterval=604800
openFileLimit=0
fileInfoFormatVersionToWrite=0
pageLimit=0
zkLedgersRootPath=/ledgers
logSizeLimit=1073741824
entryLogFilePreallocationEnabled=true
flushEntrylogBytes=268435456
readBufferSizeBytes=4096
writeBufferSizeBytes=65536
compactionRate=1000
minorCompactionThreshold=0.2
minorCompactionInterval=3600
compactionMaxOutstandingRequests=100000
majorCompactionThreshold=0.5
majorCompactionInterval=86400
isThrottleByBytes=false
compactionRateByEntries=1000
compactionRateByBytes=1000000
statsProviderClass=org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider
prometheusStatsHttpPort=8000
readOnlyModeEnabled=true
diskUsageThreshold=0.95
diskCheckInterval=10000
zkTimeout=30000
zkEnableSecurity=false
httpServerEnabled=false
httpServerPort=8000
httpServerClass=org.apache.bookkeeper.http.vertx.VertxHttpServer
dbStorage_writeCacheMaxSizeMb=
dbStorage_readAheadCacheMaxSizeMb=
dbStorage_readAheadCacheBatchSize=1000
dbStorage_rocksDB_blockCacheSize=
dbStorage_rocksDB_writeBufferSizeMB=64
dbStorage_rocksDB_sstSizeInMB=64
dbStorage_rocksDB_blockSize=65536
dbStorage_rocksDB_bloomFilterBitsPerKey=10
dbStorage_rocksDB_numLevels=-1
dbStorage_rocksDB_numFilesInLevel0=4
dbStorage_rocksDB_maxSizeInLevel1MB=256
zkServers=zookeeper1.pulsar:2181,zookeeper2.pulsar:2181,zookeeper3.pulsar:2181

advertisedAddress=broker1.pulsar,broker2.pulsar,broker3.pulsar

useHostNameAsBookieID=true
```
**Expected behavior**
a working zookeeper cluster and a working bookkeper cluster

**issue**
only one bookie is alive and i have no idea why i'm facing this issue, i done alla what i found on the documentation

when i run
`sudo bin/bookkeeper shell listbookies -rw`
i got
`16:36:21.276 [main-EventThread] INFO  org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client is connected now.
ReadWrite Bookies :
broker1.pulsar(10.10.10.11):3181
16:36:21.419 [main] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x300001de6360005 closed
16:36:21.420 [main-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x300001de6360005`
**Desktop (please complete the following information):**
 - OS: [e.g. mac OS
]

I need your help please i'm facing this issue at least 10 days i spent a lot of time on it without solution.

**Comment by gaoran10** [comment]
Maybe you could use the command `bin/bookkeeper shell listbookies -a` to check all bookies state, and take a look at logs of bookies to find more information.

**Comment by lsroudi** [comment]
Thank you @gaoran10, I run it and i got the same output as bellow:

```
10:16:02.979 [main-EventThread] INFO  org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client is connected now.
All Bookies :
broker1.pulsar(10.10.10.11):3181
10:16:03.165 [main] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x30001858b590000 closed
10:16:03.166 [main-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x30001858b590000
```

really i have no idea why i'm facing this issue

**Comment by gaoran10** [comment]
Sorry, late response, it seems that only one bookie started successfully, could you check the logs of the start failed bookie?

**Comment by lsroudi** [comment]
Thank you @gaoran10,ok this is the logs for the bookie sart failed :  

[pulsar-bookie-broker2.log-09-22-2020-1.log](https://github.com/apache/pulsar/files/5287935/pulsar-bookie-broker2.log-09-22-2020-1.log)
[pulsar-bookie-broker2.log-09-24-2020-1.log](https://github.com/apache/pulsar/files/5287936/pulsar-bookie-broker2.log-09-24-2020-1.log)
[pulsar-bookie-broker2.log-09-25-2020-1.log](https://github.com/apache/pulsar/files/5287937/pulsar-bookie-broker2.log-09-25-2020-1.log)
[pulsar-bookie-broker2.log-09-26-2020-1.log](https://github.com/apache/pulsar/files/5287938/pulsar-bookie-broker2.log-09-26-2020-1.log)
[pulsar-bookie-broker3.log](https://github.com/apache/pulsar/files/5287947/pulsar-bookie-broker3.log)

when i try to start the bookie 3 with bin/pulsar bookie i got this error : 
`WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
08:23:31.364 [main] ERROR org.apache.bookkeeper.bookie.Bookie - There are directories without a cookie, and this is neither a new environment, nor is storage expansion enabled. Empty directories are [data/bookkeeper/journal/current, data/bookkeeper/ledgers/current]
08:23:31.365 [main] INFO  org.apache.bookkeeper.proto.BookieNettyServer - Shutting down BookieNettyServer
08:23:31.388 [main] ERROR org.apache.bookkeeper.server.Main - Failed to build bookie server
org.apache.bookkeeper.bookie.BookieException$InvalidCookieException: 
	at org.apache.bookkeeper.bookie.Bookie.checkEnvironmentWithStorageExpansion(Bookie.java:468) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:250) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:688) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:136) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:105) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.server.service.BookieService.<init>(BookieService.java:41) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.server.Main.buildBookieServer(Main.java:301) ~[org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.server.Main.doMain(Main.java:221) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.server.Main.main(Main.java:203) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.proto.BookieServer.main(BookieServer.java:313) [org.apache.bookkeeper-bookkeeper-server-4.10.0.jar:4.10.0]`

when i try to start the bookie 2 with the same command i got : 

`redWritesThreshold" : "524288",
  "compactionMaxOutstandingRequests" : "100000",
  "journalPreAllocSizeMB" : "16"
}
08:26:08.959 [main] ERROR org.apache.bookkeeper.server.Main - Failed to build bookie server
io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use`

what i understand bookie 2 is started but not well ( zookeeper know nothing about it), the bookie 3 not started.

it's confirmed by : 
`vagrant@broker2:/opt/apache-pulsar-2.6.1$ ps -ef | grep bookie`
`
root     15696     1  0 Sep26 ?        00:04:21 /usr/bin/java -cp /opt/apache-pulsar-2.6.1/conf:::/opt/apache-pulsar-2.6.1/lib/*: -Dlog4j.configurationFile=log4j2.yaml -Djute.maxbuffer=10485760 -Djava.net.preferIPv4Stack=true -Dpulsar.allocator.exit_on_oom=true -Dio.netty.recycler.maxCapacity.default=1000 -Dio.netty.recycler.linkCapacity=1024 -Xms2g -Xmx2g -XX:MaxDirectMemorySize=4g -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -Dpulsar.log.appender=RollingFile -Dpulsar.log.dir=/opt/apache-pulsar-2.6.1/logs -Dpulsar.log.level=info -Dpulsar.routing.appender.default=Console -Dpulsar.functions.process.container.log.dir=/opt/apache-pulsar-2.6.1/logs -Dpulsar.functions.java.instance.jar=/opt/apache-pulsar-2.6.1/instances/java-instance.jar -Dpulsar.functions.python.instance.file=/opt/apache-pulsar-2.6.1/instances/python-instance/python_instance_main.py -Dpulsar.functions.extra.dependencies.dir=/opt/apache-pulsar-2.6.1/instances/deps -Dpulsar.functions.instance.classpath=/opt/apache-pulsar-2.6.1/conf:::/opt/apache-pulsar-2.6.1/lib/*: -Xms2g -Xmx2g -XX:MaxDirectMemorySize=2g -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.maxCapacity.default=1000 -Dio.netty.recycler.linkCapacity=1024 -Dpulsar.log.file=pulsar-bookie-broker2.log org.apache.bookkeeper.proto.BookieServer --conf /opt/apache-pulsar-2.6.1/conf/bookkeeper.conf`
and by: 
`vagrant@broker3:/opt/apache-pulsar-2.6.1$ ps -ef | grep bookie
vagrant  21268 17165  0 08:28 pts/1    00:00:00 grep --color=auto bookie`

**Comment by gaoran10** [comment]
You could shutdown all bookies and try to initialize the zookeeper again, refer to [DOC](http://pulsar.apache.org/docs/en/deploy-bare-metal/#initialize-cluster-metadata), then start one bookie use the command bin/pulsar bookie check the logs.

Or delete all data in VM, try to deploy a new cluster in manual.

@jiazhai @codelipenghui Hi, is there any suggestions about this problem?

**Comment by lsroudi** [comment]
Really thank you @gaoran10 for your help and reactivity, i try all point you suggest with the same result, only one bookie started, i deploy the cluster multiple time as i use ansible and vagrant, but still facing this issue

**Comment by jiazhai** [comment]
Thanks @gaoran10 for the help on this issue.

**Comment by lsroudi** [comment]
Hello Guys,
i did all point suggested no change still have the same issue, if someone have few times i can communicate my vagrant file and the ansible playbook to reproduce the bug if it's possible, because i have no idea to solve it
Many Thanks

**Comment by eolivelli** [comment]
I see this line
`advertisedAddress=broker1.pulsar,broker2.pulsar,broker3.pulsar`
what is it supposed to do ?

if you put that line the bookie will advertise itself with such name.
you should put a different value in each bookie

**Comment by lsroudi** [comment]
Hello,
thank you @eolivelli for updating this topic, i still have the issue, the line i found it when i tried to solve the issue, what do you suggest ? delete it ?

**Comment by tisonkun** [comment]
Closed as stale.

Feel free to open a Q&A discussion at https://github.com/apache/pulsar/discussions if it's still relevant for maintained versions.
