### ISSUE TITLE
PIP python 2.7 fastavro dependency bug

### ISSUE THREAD

**Issue by nosradom** [apache/pulsar#8126]
fastavro is a required dependency for the pulsar-client.

The newest fastavro version (1.0.0.post1) does not support python 2.7 
https://pypi.org/project/fastavro/#description
 
If pip install pulsar-client on a clean machine it tries to install the latest fastavro version and fails.

A workaround is to pip install fastavro==0.24.2 before running pip install pulsar-client
However, I was unable to find any documentation that was needed.

I would suggest updating the dependency requirements to use the earlier fastavro version instead of the latest when using 2.7.

The output of the bug is as follows

Collecting fastavro (from pulsar-client==2.6.1)
  Using cached https://files.pythonhosted.org/packages/19/b1/3fc23eb5c5f32ec69dc072bc383c79ed013eb1fb178cae4e0b9576527ea5/fastavro-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Nqgi9I/fastavro/setup.py", line 58, in <module>
        if sys.implementation.name != "pypy":
    AttributeError: 'module' object has no attribute 'implementation'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Nqgi9I/fastavro/

I was installing in a docker container starting from the FROM ros:melodic-ros-base

**Comment by scottbelden** [comment]
`fastavro` should now gracefully handle this, but I think your pip cache still has `fastavro==1.0.0` (based on the `Using cached` line) which is the problematic release.

If you try to install with `--no-cache` does it install the `0.24.2` version?

**Comment by nosradom** [comment]
No still have the same error. Below is the dockerfile that I used

FROM ros:melodic-ros-base

RUN apt-get update

RUN apt-get --assume-yes install python-pip 
#RUN pip install fastavro==0.24.2
RUN pip install pulsar-client --no-cache


Output:
Step 4/4 : RUN pip install pulsar-client --no-cache
 ---> Running in 2165355095c6
Collecting pulsar-client
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2fcc86fad0>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/pulsar-client/
  Downloading https://files.pythonhosted.org/packages/f0/10/ce070d01c4d7b359038cb158c53c679366cb541adb65920cccbd43af3ce6/pulsar_client-2.6.1-cp27-cp27mu-manylinux1_x86_64.whl (21.1MB)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from pulsar-client)
Collecting apache-bookkeeper-client>=4.9.2 (from pulsar-client)
  Downloading https://files.pythonhosted.org/packages/51/59/aadde0946a4127a8f5623cb74bfcbc7ac33135ad9ff765aaa9bd6fa1a27d/apache_bookkeeper_client-4.11.0-py2.py3-none-any.whl (70kB)
Collecting protobuf>=3.6.1 (from pulsar-client)
  Downloading https://files.pythonhosted.org/packages/19/f1/e7ea38480048cc073802b9242156b85095586c5b1f66d84447635696be60/protobuf-3.13.0-cp27-cp27mu-manylinux1_x86_64.whl (1.3MB)
Collecting prometheus-client (from pulsar-client)
  Downloading https://files.pythonhosted.org/packages/3f/0e/554a265ffdc56e1494ef08e18f765b0cdec78797f510c58c45cf37abb4f4/prometheus_client-0.8.0-py2.py3-none-any.whl (53kB)
Collecting ratelimit (from pulsar-client)
  Downloading https://files.pythonhosted.org/packages/ab/38/ff60c8fc9e002d50d48822cc5095deb8ebbc5f91a6b8fdd9731c87a147c9/ratelimit-2.2.1.tar.gz
Collecting grpcio (from pulsar-client)
  Downloading https://files.pythonhosted.org/packages/0e/5f/eeb402746a65839acdec78b7e757635f5e446138cc1d68589dfa32cba593/grpcio-1.32.0.tar.gz (20.8MB)
Collecting certifi (from pulsar-client)
  Downloading https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl (156kB)
Collecting enum34>=1.1.9 (from pulsar-client)
  Downloading https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl
Collecting fastavro (from pulsar-client)
  Downloading https://files.pythonhosted.org/packages/19/b1/3fc23eb5c5f32ec69dc072bc383c79ed013eb1fb178cae4e0b9576527ea5/fastavro-1.0.0.tar.gz (658kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-g61IQT/fastavro/setup.py", line 58, in <module>
        if sys.implementation.name != "pypy":
    AttributeError: 'module' object has no attribute 'implementation'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-g61IQT/fastavro/
The command '/bin/sh -c pip install pulsar-client --no-cache' returned a non-zero code: 1

**Comment by scottbelden** [comment]
The version of pip installed is `9.0.1` which is pretty old and doesn't have some of the features needed. If that is upgrade it works. For example:

```
FROM ros:melodic-ros-base

RUN apt-get update

RUN apt-get --assume-yes install python-pip
#RUN pip install fastavro==0.24.2
RUN pip install -U pip
RUN pip install pulsar-client
```

**Comment by nosradom** [comment]
That works. Good information to know.

**Comment by jiazhai** [comment]
Thanks @scottbelden and @nosradom  seems it get resolved, would like to close this issue.
