### ISSUE TITLE
[doc] BookKeeper metadata service url should be documented when init metadata

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar#8130]
[#7196](https://github.com/apache/pulsar/pull/7196) introduced a command argument `bookkeeper-metadata-service-uri` to specify an existed BookKeeper metadata service uri so that a new broker cluster could reuse the existed ZooKeeper node to store bookies' metadata.

It should be documented like other arguments, e.g. see the table in https://pulsar.apache.org/docs/en/deploy-bare-metal/#initialize-cluster-metadata.

Also, the argument may be mistaken as a path to create a new ZooKeeper node to store bookies' metadata. So the doc should emphasize it or just change its name because the argument is not in any current release.

**Comment by murong00** [comment]
@BewareMyPower Thanks for pointing this out, I will refine this later when available.
