### ISSUE TITLE
[python-client] Support key based batching

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar#8135]
**Is your feature request related to a problem? Please describe.**
Now the C++ client support key based batching from #7996, the `BatchingType` should be exposed to the Python wrapper to support key based batching for Python client.

**Describe the solution you'd like**
Expose the `ProducerConfiguration::BatchingType` and related setter/getter to Python client.

**Comment by hangc0276** [comment]
I will try to fix it, Please assign to me.

**Comment by BewareMyPower** [comment]
@hangc0276 thx for your help. It seems that I don't have the permission to assign the issue, please assign this issue to hang, @jiazhai
