### ISSUE TITLE
Question about deleting a topic's schema

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar#8136]
Currently a schema could be deleted by REST API:

```http
DELETE /schemas/:tenant/:namespace/:topic/schema
```

However, the implementation is:

```java
    // org.apache.pulsar.broker.service.schema.SchemaRegistryServiceImpl
    public CompletableFuture<SchemaVersion> deleteSchema(String schemaId, String user) {
        byte[] deletedEntry = deleted(schemaId, user).toByteArray();
        return schemaStorage.put(schemaId, deletedEntry, new byte[]{});
    }
```

I'm not familiar with schema and wonder if it's necessary to create a new ledger instead of delete the current ledger. (for performance or compatibility?)

And `SchemaStorage#delete` is never called. Anyway, I though there should be a way to delete the schema storage from client side.

In addition, the `delete` method of `BookkeeperSchemaStorage`, which implements `SchemaStorage`, also create a new ledger.

```java
    public CompletableFuture<SchemaVersion> delete(String key) {
        return deleteSchema(key).thenApply(LongSchemaVersion::new);
    }

    private CompletableFuture<Long> deleteSchema(String schemaId) {
        return getSchema(schemaId).thenCompose(schemaAndVersion -> {
            if (isNull(schemaAndVersion)) {
                return completedFuture(null);
            } else {
                return putSchema(schemaId, new byte[]{}, new byte[]{});
            }
        });
    }
```

**The only reason I can think of is that creating/appending a new ledger is more efficient than querying the target ledger and delete.**

**Comment by jiazhai** [comment]
@BewareMyPower Seems you have already synced with @codelipenghui, Would you please help post the decision of how to handle this? Since you are working on this, would like to assign it to you.

**Comment by BewareMyPower** [comment]
@jiazhai Just as I've said, appending a ledger is more efficient so it's the default behavior of delete schema. However, when we want to delete the topic but not only delete the schema, we need to delete the ledger instead of creating a new ledger. So we need to add an option to *delete* the schema when delete a topic.

The current `deleteSchema` parameter of `deleteTopic` was not exposed, i.e. the API is like `deleteTopic(deleteSchema = false)` and is always called as `deleteTopic(false)`.

By the way, the behavior of this parameter is also simply appending a new ledger, so we need to change it to deleting the existed schema ledgers.

**Comment by BewareMyPower** [comment]
Close the issue by #8167
