### ISSUE TITLE
consume acknowledged timestamp in subscription

### ISSUE THREAD

**Issue by techzhou** [apache/pulsar#8145]
**Is your feature request related to a problem? Please describe.**
I want to know every message acknowledged timestamp with one subscription

**Describe the solution you'd like**
write to log
read from stats
anything
...

**Comment by codelipenghui** [comment]
@techzhou Could you please describe the detailed requirements? If you want to record the ack timestamp of a message, you can print a log when you call `acknowledge(msg)`. If you want to trace the messages, you can try to leverage some tracing systems such as SkyWalking or Jeager, we already add integration with these two systems. For more details, you can see https://streamnative.io/blog/tech/2019-10-10-use-apache-skywalking-to-trace-apache-pulsar and  https://streamnative.io/blog/tech/2020-06-11-opentracing-instrumentation-for-pulsar

**Comment by techzhou** [comment]
@codelipenghui I just want to record the ack timestamp of a message, PersistentSubscription Logger may help me, I will try it.

**Comment by codelipenghui** [comment]
OK.

**Comment by techzhou** [comment]
- name: org.apache.pulsar.broker.service.persistent.PersistentSubscription
        level: debug
        additivity: false
        AppenderRef:
          - ref: SubHttp

It's OK. I really appreciate your help. Thank you. @codelipenghui
