### ISSUE TITLE
[Pulsar SQL] reduce configuration of ZK/Brokers endpoints to Brokers or Proxies

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#8151]
**Is your enhancement request related to a problem? Please describe.**
Boot Pulsar SQL instances on-demand without direct connection to ZK (as ZK is not exposed publicly).

**Describe the solution you'd like**
Pulsar's Presto connector is requiring a ZK connection. Can we get rid of that and only have brokers or proxies endpoints in the Presto configuration?

**Describe alternatives you've considered**
I'm open to any suggestions.

**Comment by codelipenghui** [comment]
@KannarFr Looks the biggest challenge is how we read data from bookies without ZooKeeper since the BookKeeper client needs to connect to ZookKeeper to get the ledger metadata. And we also have a plan to add a batch read API for Pulsar topics.

**Comment by tisonkun** [comment]
Closed as stale and no one worked on it. Please open a new issue if it's still relevant to the maintained versions.
