### ISSUE TITLE
Extend python client to decode message with the writerSchema

### ISSUE THREAD

**Issue by shiv4289** [apache/pulsar#8154]
**Is your enhancement request related to a problem? Please describe.**
We have a topic with schema-autoupdate-strategy=None. We use different AVRO schema to encode messages and place them on the same topic (for ordering guarantees). 

With java client we can fetch the exact schema  a message was encoded with (_writerSchema as msg.getSchemaVersion()_) , decode with writerSchema schema and get the original message as java objects.

However this is not possible with python client. With python client it is only possible to [specify an AvroSchema at the time of consumer initiation](https://pulsar.apache.org/docs/en/client-libraries-python/#declare-and-validate-schema) as in 

`
consumer = client.subscribe(
                  topic='my-topic',
                  subscription_name='my-subscription',
                  schema=AvroSchema(Example) )
`
 
and decode every message received on this consumer with this schema as in  

`
    msg = consumer.receive()
    ex = msg.value()
`

**Describe the solution you'd like**
Like Java client, it should be possible in python client to

1. Fetch writerSchema from the message
2. Decode message with the writerSchema.

**Describe alternatives you've considered**
No workaround found that can fetch and decode messages with python consumer.

**Comment by codelipenghui** [comment]
@shiv4289 Looks this is a catchup work at the python client, are you interested work on it?

**Comment by shiv4289** [comment]
Sure @codelipenghui . You can assign this to me.

**Comment by tisonkun** [comment]
Closed as stale. The development of the Python client has been permanently moved to https://github.com/apache/pulsar-client-python. If this is still relevant, please open an issue there.
