### ISSUE TITLE
Disable namespace ttl while enable broker level ttl

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#8159]
user reported:

Broker has the ttl set, when I ran the get-message-ttl pulsar-admin CLI command for the namespace, the TTL value was not set to 0, instead it returned the global default value 3600 again.
I tried the same via the CLI command also :
./pulsar-admin namespaces set-message-ttl public/test2 --messageTTL 0
Which again gave me the same result as above. It also defaulted to the global value 3600s.

**Comment by 315157973** [comment]
I will work on it

**Comment by jiazhai** [comment]
thanks
