### ISSUE TITLE
AutoRecovery should respect to the ensemble policy used in Pulsar

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#8171]
*Motivation*

Pulsar uses an ensemble policy to select an ensemble to place the data. We need to configure AutoRecovery to respect to the ensemble policy used in Pulsar.

**Comment by hangc0276** [comment]
I checked bookkeeper autoRecovery logic, it respected to the ensemble policy store in ledgerMetadata for each ledger fragment. The code as follow. `BookKeeperAdmin#getReplacementBookiesByIndexes`
```java
EnsemblePlacementPolicy.PlacementResult<BookieSocketAddress> replaceBookieResponse =
                    bkc.getPlacementPolicy().replaceBookie(
                            lh.getLedgerMetadata().getEnsembleSize(),
                            lh.getLedgerMetadata().getWriteQuorumSize(),
                            lh.getLedgerMetadata().getAckQuorumSize(),
                            lh.getLedgerMetadata().getCustomMetadata(),
                            ensemble,
                            oldBookie,
                            bookiesToExclude);
```
I am a little confused for this issue, would you please give more details. @sijie

**Comment by sijie** [comment]
@hangc0276 This issue is not about the code. BookKeeper has the abstracted logic to find a bookie to replace when changing ensembles. The most important thing here is to ensure AutoRecovery is configured to use the same ensemble placement policy as brokers.
