### ISSUE TITLE
peek message not support partitioned topic

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar#8174]
**Describe the bug**

```
pulsar-admin topics create-partitioned-topic
pulsar-admin topics peek-messages -s sub topic-name-partitioned-0
```

Throw exception:

```
Peek messages on a partitioned topic is not allowed
```

**To Reproduce**

```
pulsar-admin topics create-partitioned-topic
pulsar-admin topics peek-messages -s sub topic-name-partitioned-0
```

Throw exception:

```
Peek messages on a partitioned topic is not allowed
```

**Expected behavior**

Support peek message for partitioned topic
Remove this check https://github.com/apache/pulsar/blob/983266d480f77543a29a74ac1970280abd9f804b/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L2094

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by hangc0276** [comment]
I will fix it, please assign this issue to me.

**Comment by sijie** [comment]
@hangc0276 assigned

**Comment by tuteng** [comment]
I have reconfirmed that this command is OK. Now I close the issue

```
pulsar-admin topics peek-messages -s sub topic-name-partitioned-0
```
