### ISSUE TITLE
Possibility of data loss due to asynchronous checkpointing in kinesis consumer

### ISSUE THREAD

**Issue by priyath** [apache/pulsar#8192]
**Describe the bug**
The KinesisRecordProcessor pushes each record to a blocking queue and proceeds to checkpoint shard progress on every checkpoint interval. But at the point of checkpointing, there is no guarantee of successful delivery of pending records in the queue, which can lead to data loss in case of instance failure.

Source: https://github.com/apache/pulsar/blob/master/pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisRecordProcessor.java

**To Reproduce**
N/A

**Expected behavior**
All records retrieved by a consumer up until a certain checkpoint is expected to be processed successfully since any future retrievals will always return a new batch of records past the latest checkpoint.

**Additional context**
As per my understanding, the fix should ideally cover the following scenarios:

1. Periodic checkpointing at each checkpoint interval should be performed after pending records are processed up until that point

2. Checkpoint when onShardEnded is invoked should be performed after pending records are processed.

3. Checkpoint when shutdownRequested is invoked should be performed after pending records are processed.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
