### ISSUE TITLE
spark Java

### ISSUE THREAD

**Issue by kjaggann** [apache/pulsar#8212]
**Is your enhancement request related to a problem? Please describe.**
Need help in configuring the tls certs in spark java for consumer code

**Describe the solution you'd like**
Sample sparkReceiver in java but unable to configure the tls certs 
String serviceUrl =  "pulsar+ssl://abc-wss-us-east-1-non.abc.com:1234/";
    String inputTopic = "non-persistent://gdfvyv/test-test/ConsumerApproval-Test-Test-3m";
    String subscription = "vmb_test";
    System.out.println("Parameters:");
    System.out.println("\tServiceUrl:\t" + serviceUrl);
    System.out.println("\tTopic:\t" + inputTopic);
    System.out.println("\tSubscription:\t" + subscription);
    SparkConf sparkConf = new SparkConf().setAppName("Pulsar Spark Example");
    JavaStreamingContext jsc = new JavaStreamingContext(sparkConf, Durations.seconds(60));
    ConsumerConfigurationData<byte[]> pulsarConf = new ConsumerConfigurationData();
    Set<String> set = new HashSet<String>();
    set.add(inputTopic);
pulsarConf.setTopicNames(set);
    pulsarConf.setSubscriptionName(subscription);
    SparkStreamingPulsarReceiver pulsarReceiver = new SparkStreamingPulsarReceiver(
        serviceUrl,
        pulsarConf,
        new AuthenticationDisabled());
    JavaReceiverInputDStream<byte[]> lineDStream = jsc.receiverStream(pulsarReceiver);
    JavaPairDStream<String, Integer> result = lineDStream.flatMap(Consumer::call)
        .mapToPair(x -> new Tuple2<String, Integer>((String) x, 1))
        .reduceByKey((x, y) -> x + y);
    result.print();
    jsc.start();
    jsc.awaitTermination();

**Describe alternatives you've considered**
Nothing yet stuck with it 

**Additional context**

**Comment by tisonkun** [comment]
Closed as stale and invalid.

If it's still relevant for maintained versions, please open a new issue following the issue form. The information above is weak to be understood.
