### ISSUE TITLE
Consumer pause does not work properly in case of multi topics consumers.

### ISSUE THREAD

**Issue by git-enzo** [apache/pulsar#8214]
**Describe the bug**
When we pause a consumer which subscribes to multiple topics, for example by parsing a regular expression, and then the new producer sends a message to the new topic that the consumer discovers/subscribes, then messages from that topic will be "consumable" by the consumer during pause.

**To Reproduce**
1. Create a ```multi-topic-consumer``` which subscribes to multiple topics by parsing regular expression, for example ```persistent://public/default/foo.*```. This type of consumer periodically checks if new topics are available based on regexp (patternAutoDiscoveryPeriod). Let's say, we set this property to 10 sec. For example:

```
Pattern topicsPattern = Pattern.compile("persistent://public/default/foo.*");
pulsarClient
        .newConsumer()
        .subscriptionName("subscription")
        .subscriptionType(SubscriptionType.Shared)
        .topicsPattern(topicsPattern)
        .patternAutoDiscoveryPeriod(10, TimeUnit.SECONDS)
        .receiverQueueSize(1)
        .subscribe();
```

2. Create ```producer1``` which sends messages to topic ```persistent://public/default/foo1```. If ```multi-topic-consumer``` discovers this new topic (max after 10 seconds in our case), then messages will be consumed by consumer. Example producer:
```
Producer<byte[]> producer1 = pulsarClient
        .newProducer()
        .topic("foo1")
        .create();
```
3. Now, if ```producer1``` sends messages, a ```multi-topic-consumer``` can receive them.
4. Let's **pause** ```multi-topic-consumer``` by invoking ```pause()```. In this case consumer is a PatternMultiTopicsConsumerImpl type. That means underneath there is a list of internal consumers, where each of them consumes single topic (subscribes single topic). When we invoke ```pause()```, then each consumer of this list will be paused separately.
5. Now, when we send messages from ```producer1```, then ```multi-topic-consumer``` will not consume them. There is an exception, because consumer can still receive messages until receiverQueueSize is used up even if ```pause()``` was invoked, but after that this is impossible. For this case it is irrelevant, we can skip it.
6. Create ```producer2``` which sends messages to topic ```persistent://public/default/foo2```. If ```multi-topic-consumer``` discovers this new topic ```foo2``` (max after 10 seconds in our case), then messages **will be consumed** by consumer **even if consumer is paused**. Underneath new internal consumer is created, which subscribes ```foo2```, but this particular consumer **is not paused**.
7. Now we have following state:
-  ```multi-topic-consumer``` - is paused
- ```producer1``` sends messages to topic ```foo1``` and ```multi-topic-consumer``` cannot receive them - it is OK
- ```producer2``` sends messages to topic ```foo2``` and ```multi-topic-consumer``` is able to receive them - it is not expected behavior

**Expected behavior**
When new topic will be discovered/subscribed by multi-topic consumer during consumer is paused, then this consumer should not be able to receive messages from this topic.

**Comment by aloyszhang** [comment]
Mabe we should add a flag for `MultiTopicsConsumerImpl` which indicates wheter  `MultiTopicsConsumerImpl` has been paused or not.  If the flag is true, we should pause the new added consumers for new added topics.

**Comment by sandrzejczak** [comment]
It seems that the bug described in this issue has not been fixed. The description mentions the case where consumers for new topics are discovered/added. `PatternMultiTopicsConsumerImpl` achieves this by invoking `MultiTopicsConsumerImpl#subscribeAsync(String topicName, boolean createTopicIfDoesNotExist)` method. It is still possible to add unpaused consumers to `MultiTopicsConsumerImpl` by using this method.

The https://github.com/apache/pulsar/pull/8387 PR fixes a similar issue where new consumers are added when the number of topic partitions changes. This is a different case than the one described in this issue.

I volunteer to fix the outstanding issue.

**Comment by codelipenghui** [comment]
Cool @sandrzejczak, looking forward to your PR.
