### ISSUE TITLE
Go SDK: GetUserConfMap() is not getting populated

### ISSUE THREAD

**Issue by flowchartsman** [apache/pulsar#8216]
**Describe the bug**
While the user config is listed as not being implemented for the Pulsar Functions SDK for go, the examples seem to indicate that I should be able to poll the KVs through the context function, specifically:

```
func (c *FunctionContext) GetUserConfValue(key string) interface{} {
    return c.userConfigs[key]
}

func (c *FunctionContext) GetUserConfMap() map[string]interface{} {
    return c.userConfigs
}
```

However, these do not appear to be getting populated.

**To Reproduce**
Deploy a pulsar function for go with the following code in main.go:
```go
package main

import (
	"context"

	log "github.com/apache/pulsar/pulsar-function-go/logutil"
	"github.com/apache/pulsar/pulsar-function-go/pf"
)

func contextFunc(ctx context.Context) {
	if fc, ok := pf.FromContext(ctx); ok {
		log.Infof("function ID is:%s, ", fc.GetFuncID())
		log.Infof("function version is:%s\n", fc.GetFuncVersion())
		for k := range fc.GetUserConfMap() {
			log.Infof("Config %q -> \"%v\"", k, fc.GetUserConfValue(k))
		}
	}
}

func main() {
	pf.Start(contextFunc)
}
```

```
$ pulsar-admin functions create --tenant public --namespace default --name pfunctestconfig --go (pwd)/pfunctest --inputs persistent://public/default/in --output persistent://public/default/out --user-config '{"test":"value","testnum":1}'
```

**Expected behavior**
Logs look like:
```
2020/10/07 21:27:26.022 log.go:46: [info] function ID is:3cbefae6-5a6a-43c5-8427-148625d5f391,
2020/10/07 21:27:26.022 log.go:46: [info] function version is:e215cf0e-2a64-498c-8773-760173de11c3
2020/10/07 21:27:26.022 log.go:46: [info] Config "test" -> "value"
2020/10/07 21:27:26.022 log.go:46: [info] Config "testnum" -> "1"
```

**Actual behavior**
```
2020/10/07 21:27:26.022 log.go:46: [info] function ID is:3cbefae6-5a6a-43c5-8427-148625d5f391,
2020/10/07 21:27:26.022 log.go:46: [info] function version is:e215cf0e-2a64-498c-8773-760173de11c3
```

**Comment by vaihtovirta** [comment]
Hey @flowchartsman 
I added user config support in my PR some time ago https://github.com/apache/pulsar/pull/8290
Have you checked if this solves the issue?

**Comment by flowchartsman** [comment]
Testing has been unsuccessful so far, but I may be doing something wrong. Currently testing #8365 with `--user-config '{"foo":"bar"}'` but getting

```
log.go:76:` [error] unmarshal config content error:invalid character '\'' looking for beginning of value
panic: config file is nil.
```

**Comment by flowchartsman** [comment]
@vaihtovirta I have discovered a couple of issues. The first issue is that spurious single quotes (`'`) are getting added to the arguments to the pulsar function, causing it to fail. The offending line is located in `pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java`:

```java
args.add("'" + configContent + "'");
```

Should be:

```java
```

**Comment by vaihtovirta** [comment]
Hey @flowchartsman 
It seems the change has been introduced here: [k8s runtime with go functions support #8352](https://github.com/apache/pulsar/pull/8352/files#diff-aafe8947b1fae9aec06d90c14db1b3b9fe720eb2a55ca48bfe7b43ecfb39efb4R231)
Also, it looks like python and java functions use a similar technique, but process configuration string through `JsonFormat.printer()`:
https://github.com/apache/pulsar/blob/a045d926c9620a3744a4bc755bf6f2a65209e6b6/pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java#L349

I'll check if it's possible to handle golang runtime the same way.

**Comment by wolfstudy** [comment]
@flowchartsman It seems that #8780 is already solving this problem, can you help to check whether we can close this issue, thanks.
