### ISSUE TITLE
Support limits the max tenants of the Pulsar cluster

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#8223]
**Is your feature request related to a problem? Please describe.**
Support limits the max tenants of the Pulsar cluster. When the tenants reach the max tenants of the cluster, the broker should reject the new tenant request.

**Describe the solution you'd like**
Add `maxTenants=0` in the broker.conf and don't limit by default.

**Comment by 315157973** [comment]
I will work on it
