### ISSUE TITLE
Support limits the max namespaces per tenant

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#8224]
**Is your feature request related to a problem? Please describe.**
Support limits the max namespaces per tenant of the Pulsar cluster. When the namespaces reach the max namespaces of the tenant, the broker should reject the new namespace request.

**Describe the solution you'd like**
Add `maxNamespacePerTenant=0` in the broker.conf and don't limit by default.

**Comment by 315157973** [comment]
I will work on it
