### ISSUE TITLE
Support limits the max topics per namespace

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#8225]
**Is your feature request related to a problem? Please describe.**
Support limits the max topics per namespace of the Pulsar cluster. When the topics reach the max topics of the namespace, the broker should reject the new topic request(include topic auto-created by the producer or consumer). 

**Describe the solution you'd like**
Add `maxTopicsPerNamespace=0` in the broker.conf and don't limit by default.

**Comment by 315157973** [comment]
I will work on it

**Comment by hangc0276** [comment]
I will work for it.
