### ISSUE TITLE
Support limits the max subscriptions per topic 

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#8226]
**Is your feature request related to a problem? Please describe.**
Support limits the max subscriptions per topic of the Pulsar cluster. When the subscriptions reach the max subscriptions of the topic, the broker should reject the new subscription request and reject the consumer to subscribe to this topic.  

**Describe the solution you'd like**
Add `maxSubscriptionsPerTopic=0` in the broker.conf and don't limit by default.

**Comment by 315157973** [comment]
I will work on it

**Comment by hangc0276** [comment]
I will work for it.
