### ISSUE TITLE
pulsar-standalone: use ipv6 error 

### ISSUE THREAD

**Issue by eatSummer** [apache/pulsar#8231]
**Describe the bug**
I used the standalone Pulsar, and IPv4 was normal
but i want use ipv6,for example "[1001:30::152:601]" and i modify "preferIPv4Stack=true" to "preferIPv4Stack=false",
then pulser service is stuck-->
org.apache.bookkeeper.clients.impl.channel.StorageServerChannelManager - 
Added range server (hostname: "1001"port: 30) into the channel manager.
It looks like ip and port error

**Comment by tisonkun** [comment]
Closed as stale. Feel free to open a new issue if it's still relevant for maintained versions.
