### ISSUE TITLE
Support taking de-duplication snapshots based on time

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#8237]
Currently we take de-duplication snapshots based on size. If the topic has relatively low traffic, the de-duplication cursor will not move. This can cause messages that are not able to be deleted based on the retention policy. We should add a policy to take de-duplication snapshots based on time.

- [x] Broker level configuration #8474 
- [x] Namespace level configuration
- [x] Topic level congfiguration

**Comment by 315157973** [comment]
I will solve it
