### ISSUE TITLE
Can pulsar support partition merging and spliting dynamic?

### ISSUE THREAD

**Issue by hxwabc** [apache/pulsar#8238]
Can pulsar support partition merging and spliting dynamic?
If not, is there such a support planning?

**Comment by Jennifer88huang** [comment]
@hxwabc Thanks for raising the issue. You can add partitions in Pulsar based on your requirements.
I was wondering which scenarios/cases require partition merging and splitting? Could you please give some details?

**Comment by sijie** [comment]
@hxwabc Current the feature of auto-scaling partitions is not supported yet. We have a Github issue for adding this support. You can follow the progress at https://github.com/apache/pulsar/issues/3217
