### ISSUE TITLE
Support configure deduplicationEntriesInterval at the namespace/topic level

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#8252]
Currently we take de-duplication snapshots based on size and can only change the configuration at the broker level. It's better to allow to change it at the namespace/topic level.

Related to #8237

**Comment by Jennifer88huang** [comment]
Does it duplicate with #8237? If so, shall we close one?

**Comment by hangc0276** [comment]
I will work for it.

**Comment by codelipenghui** [comment]
@Jennifer88huang No, it's not a dup, #8237 introduces a new mechanism for the deduplication check.
