### ISSUE TITLE
pulsar-functions-go directory needs a little cleanup

### ISSUE THREAD

**Issue by flowchartsman** [apache/pulsar#8263]
**Describe the bug**
`pulsar/pulsar-function-go/examples/producer` and `pulsar/pulsar-function-go/examples/consumer` are not examples of how to use the pulsar functions SDK for go, but rather basic client examples.  Also, the `go.mod` in the examples directory defines a module which is incorrect for that path (`module github.com/apache/pulsar/pulsar-function-go/tests`).

**Comment by Jennifer88huang** [comment]
@wolfstudy could you please help check? Thank you.

**Comment by wolfstudy** [comment]
Thanks @flowchartsman feedback, i send a pull request to fix it, PTAL thanks.
