### ISSUE TITLE
[Java Client] Async Send does not appear to deliver messages in order unless `batchingMaxMessages`=1

### ISSUE THREAD

**Issue by frankjkelly** [apache/pulsar#8264]
**Describe the bug**
I might have found something in relation to message ordering with Async Send. I setup a test program here https://github.com/kellyfj/message-ordering and can reproduce the problem. 

**To Reproduce**
1. See test program attached and associated instructions

**Expected behavior**
Java `sendAsync` should behave the same in terms of ordering as `send` and certainly ordering shouldn't be impacted by batching

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - replicated on Mac Book Pro

**Comment by addisonj** [comment]
I worked with @frankjkelly  to find that this wasn't an issue in pulsar, but there is some strange behavior if the user re-uses buffers as an input to the client.

See https://github.com/kellyfj/message-ordering/pull/1#issuecomment-710760790 for more context, but the tl;dr is that I think the reference to the buffer change out from underneath us in async production. We may need to copy the buffer or use some other technique to ensure that reference can't be modified before we send the buffer

**Comment by frankjkelly** [comment]
I concur - if instead of passing a byte buffer in directly, I make a copy of the byte buffer and pass that in, the problem goes away.

**Comment by tisonkun** [comment]
Closed as resolved.
