### ISSUE TITLE
Make logs more consistent

### ISSUE THREAD

**Issue by losiu97** [apache/pulsar#8298]
**Is your enhancement request related to a problem? Please describe.**
 Broker and bookkeeper logs do not include the date, only time

**Describe the solution you'd like**
I would like the logs from all services to include both date and time

**Describe alternatives you've considered**
A way to configure the logging format for kubernetes deployment of Pulsar. Or maybe there is a way but i missed it in docs?

**Additional context**
Example log missing date (the last entry here)
`18:58:57.243 [pulsar-web-42-8] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [08/Oct/2020:18:58:57 +0000] "GET /admin/v2/persistent/perf-1/_system/_signals_ingest/stats HTTP/1.1" 200 5656 "-" "curl/7.64.0" 4
18:59:06.384 [pulsar-web-42-4] INFO  org.eclipse.jetty.server.RequestLog - 10.0.0.46 - - [08/Oct/2020:18:59:06 +0000] "GET /status.html HTTP/1.1" 200 2 "-" "kube-probe/1.14+" 1
18:59:07.234 [pulsar-web-42-3] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [08/Oct/2020:18:59:07 +0000] "GET /admin/v2/persistent/perf-1/_system/_signals_ingest/stats HTTP/1.1" 200 5656 "-" "curl/7.64.0" 2
18:59:11.409 [pulsar-load-manager-3-1] INFO  org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl - Only 1 broker available: no load shedding will be performed `

**Comment by sijie** [comment]
@losiu97 We can change the default logging format. Are you interested in contributing a fix to this?

**Comment by losiu97** [comment]
Hi, sorry i missed your reply. I found a way of fixing it for myself, but we could change the default format to 
%d{YYYY-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n

**Comment by tomscut** [comment]
Hi @losiu97 @hangc0276 , this problem has been solved. Can we close the issue? Thanks.
