### ISSUE TITLE
Close the consumer graceful

### ISSUE THREAD

**Issue by kent-crypto** [apache/pulsar#8308]
**Is your enhancement request related to a problem? Please describe.**
Yes. I want to stop some of the components of the system without turnoff the inflow.

**Describe the solution you'd like**
 I would like to achieve the goal on closing consumer: the message listener stop receiving any new message, and waits till the ongoing message to be completed. 

**Describe alternatives you've considered**

**Additional context**

The ConsumerImpl.close method set the status to "State.Closing", which stops the on going message to be acked with exception "Consumer not ready. State:  closing". Because of this, the message will be re-consumed when restart the consumer.

**Comment by MarvinCai** [comment]
@kent-crypto Is it possible that we just use consumer.[pause](https://pulsar.apache.org/api/client/)() to stop receiving message from broker and process/ack outstanding messages before closing the consumer. Sounds to me that can also achieve what you describe.

**Comment by zongtanghu** [comment]
This issue can you help to resolve it? @zhanghaou @shaojie

**Comment by tisonkun** [comment]
Closed as stale and no one worked on it. Please open a new issue if it's still relevant to the maintained versions.

**Comment by tisonkun** [comment]
It seems superseded by #18799
