### ISSUE TITLE
Pulsar C client reports a memory leak

### ISSUE THREAD

**Issue by jiangmincong** [apache/pulsar#8309]
**Describe the bug**

Pulsar C client reports a memory leak

![image](https://user-images.githubusercontent.com/22076140/96576302-91b09d80-1304-11eb-990f-43c7fd1f29fc.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by sijie** [comment]
@jiangmincong Your issue is the same as apache/pulsar#8339.

Please refer to https://github.com/apache/pulsar/issues/8339#issuecomment-714579552
