### ISSUE TITLE
Timeout while producing message

### ISSUE THREAD

**Issue by pushkar-engagio** [apache/pulsar#8321]
**Describe the bug**
We are seeing intermittent timeouts while producing message. It's logged as a WARN. 

Exception:
` [java] 2020-10-19 22:26:52,540 [qtp1873635139-96] WARN  c.d.i.d.campaign.DBCampaignQueue - Pulsar PerTenantPubSub persistent://1017/DB/campaign has failed to publish a message 1 times. The failure messageis The producer pulsar-98-446 can not send message to the topic persistent://1017/DB/campaign within given timeout and the message body is {"XXXXXX":"XXXXXX","XXXXXX":"XXXXXX","XXXXXX":true,"XXXXXX":false}. c1017_XXXXXX  172.20.108.8
     [java] org.apache.pulsar.client.api.PulsarClientException$TimeoutException: The producer pulsar-98-446 can not send message to the topic persistent://1017/DB/campaign within given timeout`

In broker logs i see following messages.
`22:26:53.441 [bookkeeper-ml-workers-OrderedExecutor-7-0] INFO org.apache.bookkeeper.mledger.impl.OpAddEntry - [1017/DB/persistent/campaign] Closing ledger 10606 for being full
22:27:41.475 [bookkeeper-ml-workers-OrderedExecutor-7-0] INFO org.apache.bookkeeper.mledger.impl.ManagedCursorImpl - [1017/DB/persistent/campaign] Updated cursor 1017-campaign with ledger id 11191 md-position=10606:0 rd-position=10606:1
22:27:41.478 [BookKeeperClientWorker-OrderedExecutor-0-0] INFO org.apache.bookkeeper.mledger.impl.ManagedCursorImpl - [1017/DB/persistent/campaign][1017-campaign] Successfully closed & deleted ledger 10548 in cursor`

**Expected behavior**
The producer continues to produce the messages without any interruption.

**Screenshots**

**Additional context**
Pulsar 2.6.0 deployed using helm chart.

**Comment by pushkar-engagio** [comment]
The CPU load on zookeeper barely reaches 3%

**Comment by sijie** [comment]
@pushkar-engagio what are your send timeout settings?

**Comment by pushkar-engagio** [comment]
We are using the default timeout ie. 30 secods.

**Comment by ATaurenRideRocket** [comment]
> We are using the default timeout ie. 30 secods.

Have you sloved the problem?

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
