### ISSUE TITLE
Add Wildcard table support to Presto

### ISSUE THREAD

**Issue by mingfang** [apache/pulsar#8322]
BigQuery has a very nice feature called wildcard table here
https://cloud.google.com/bigquery/docs/reference/standard-sql/wildcard-table-reference

Since pulsar supports regex topics, I wonder if it's possible to also add wildcard tables support to Presto.
Currently it (naturally) prints out this error when I try selecting from wildcard
```
presto> select count(*) from pulsar."public/default"."dbserver1.public.github_events_*";
Query 20201021_041700_00011_737vg failed: Table 'public/default.dbserver1.public.github_events_*' not found
```

As a bit of background I'm using Debezium to read from Citus
http://docs.citusdata.com/en/v9.4/use_cases/timeseries.html
This results in many Pulsar topics like `dbserver1.public.github_events_xxxxx`
I would like to use Presto to query from all those topics at once.

**Comment by eaba** [comment]
Hi @mingfang I don't think this has to do with Pulsar, maybe.
Pulsar just acts as the data source, Presto is responsible for executing the SQL command.
I encountered a scenario that needed the wildcard table but Presto does not yet have that feature.
A similar issue is opened [here](https://github.com/prestosql/presto/issues/4124)
You can open an issue [here](https://github.com/prestodb/presto) too.

I am in need of wildcard table name too!!

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
