### ISSUE TITLE
Invalid characters in Pulsar function exceptions crash Prometheus

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#8332]
We discovered today that if non-UTF-8 characters are included in a Pulsar function exception message, due to the way the exception messages are scraped, it stops Prometheus's ability to scrape any metrics from the broker that was running the function that threw the exception.

**Comment by sijie** [comment]
@devinbost This sounds like a problem on Prometheus side, not on the pulsar side, no?

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
