### ISSUE TITLE
Bookie returning from being off for several days resulted in split-brain

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#8333]
We had a bookie in a cluster running Pulsar 2.4.0 that went down due to a memory hardware failure. When the bookie came back online a few days later, the cluster ended up in a split-brain state, resulting in all of the other bookies failing to connect. After a number of hours of troubleshooting, the only resolution was to completely rebuild the cluster, resulting in data loss.  
I didn't think it was possible for split-brain to occur due to the fencing mechanism in Bookkeeper, but the issue seemed to be on the Zookeeper-side.

**Comment by eolivelli** [comment]
what do you mean with "split brain" ?
to have consumers that see different data on topics ?
to have multiple owners of the same topic/partition ?

**Comment by devinbost** [comment]
"Split-brain" meaning all but one of the bookies suddenly couldn't connect to the cluster. 
We tried to resolve the problem by shutting down all the bookies that couldn't connect. 
Then, we provisioned new bookies. They were able to successfully join the cluster with the one that was still up.
Then, after about an hour, we tried starting one of the bookies that hadn't been able to join. 
Almost immediately after we did that, almost all of the bookies (even the ones that were newly provisioned) stopped being able to connect to the cluster. We tried different combinations of restarts, but we weren't able to resolve the issue.

The environment is Pulsar 2.4.0 running bare metal on docker. The docker containers are run as systemd services on CentOS boxes.

**Comment by eolivelli** [comment]
In Bookkeeper there is not a concept of cluster/group of bookies but every bookie is independent from the others.
Each bookie announces itself on the metadata service (zk) and this way clients (pulsar brokers) are able to read/write from/to them.
This is why I was asking for what is a split-brain.

Probably they had problems in connecting to the Zookeeper ensemble.
Do you have logs on the bookies about KeeperException (the error in ZK client) or other kind of errors?

**Comment by devinbost** [comment]
One of the Zookeepers was giving these NodeExists exceptions:

```
    22:09:01.713 [ProcessThread(sid:3 cport:-1):] INFO  org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x106ae1d22100053 type:create cxid:0x1 zxid:0x1de000dfcbd txntype:-1 reqpath:n/a Error Path:/pulsar/functions Error:**KeeperErrorCode = NodeExists for /pulsar/functions**
    22:09:04.339 [ProcessThread(sid:3 cport:-1):] INFO  org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x206ae1a6e50005d type:create cxid:0x178 zxid:0x1de000e098c txntype:-1 reqpath:n/a Error Path:/loadbalance/brokers/server08.domain.com:8080 **Error:KeeperErrorCode = NodeExists for /loadbalance/brokers/server08.domain.com:8080**
```
 
Also, none of the Pulsar functions were getting assignments when this happened. FYI @jerrypeng ^^^

Also, we were seeing errors like these:

```  22:09:02.221 [ProcessThread(sid:3 cport:-1):] INFO  org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x206ae1a6e500001 type:delete cxid:0x9d808 zxid:0x1de000dff81 txntype:-1 reqpath:n/a Error Path:/ledgers/underreplication/ledgers/0000/0000/2a0e Error:KeeperErrorCode = Directory not empty for /ledgers/underreplication/ledgers/0000/0000/2a0e
    22:09:03.207 [ProcessThread(sid:3 cport:-1):] INFO  org.apache.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x206ae0c67f00003 type:delete cxid:0x190d3e zxid:0x1de000e02c5 txntype:-1 reqpath:n/a Error Path:/ledgers/underreplication/ledgers/0000/0001/0990 Error:KeeperErrorCode = Directory not empty for /ledgers/underreplication/ledgers/0000/0001/0990
```

When the brokers started restarting (after the bookies were unhealthy), we also started seeing this repeat in the logs:

```
2020-10-19T21:34:08,200 [main] ERROR org.apache.pulsar.PulsarBrokerStarter - Failed to start pulsar service.
org.apache.pulsar.broker.PulsarServerException: org.apache.pulsar.broker.PulsarServerException: org.apache.pulsar.broker.PulsarServerException: **Broker-znode owned by different zk-session** 145995360955662414
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:453) 
```
We also saw that same exception thrown from ModularLoadManagerImpl:

```2020-10-19T21:13:12,033 [main] ERROR org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl - **Unable to create znode** - [/loadbalance/brokers/server12.domain.com:8080] for load balance on zookeeper
org.apache.pulsar.broker.PulsarServerException: **Broker-znode owned by different zk-session** 73937685957574781
	at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl.start(ModularLoadManagerImpl.java:798)
```

**Comment by Ghatage** [comment]
>"Split-brain" meaning all but one of the bookies suddenly couldn't connect to the cluster.

@devinbost I think we need more Bookie logs for this. Is it possible for you to share some of those?
As @eolivelli said, when bookies come up they announce their membership to the cluster via a cookie. If there is a cookie mismatch, it will fail to come up. Hence for this reason, it would be helpful to see the bookie start up logs for that failed bookie.

Spinning up a new bookie would help when autorecovery notices underreplicated ledgers and starts copying them to the new bookie to satisfy write quorum ratios. Then again, due to our quorum writes you shouldn't have had any actual data loss I hope.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
