### ISSUE TITLE
[pulsar-testclient]Provide options to specify existing topics when allowAutoTopicCreation is disable and using multiple topics

### ISSUE THREAD

**Issue by murong00** [apache/pulsar#8340]
**Is your enhancement request related to a problem? Please describe.**
Some users may encounter the following issues when using multiple topics with option `--num-topics` but `allowAutoTopicCreation` is disable:
```
$ bin/pulsar-perf consume persistent://public/default/test -s sub -st Exclusive -t 2
Exception in thread "main" java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException$TopicDoesNotExistException: Topic does not exist
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at org.apache.pulsar.testclient.PerformanceConsumer.main(PerformanceConsumer.java:343)
Caused by: org.apache.pulsar.client.api.PulsarClientException$TopicDoesNotExistException: Topic does not exist
        at org.apache.pulsar.client.impl.ClientCnx.getPulsarClientException(ClientCnx.java:1003)
        at org.apache.pulsar.client.impl.ClientCnx.handleError(ClientCnx.java:610)
        at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:170)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
```
or using multiple subscriptions with option `--num-consumers` but `allowAutoSubscriptionCreation` is disable:
```
$ bin/pulsar-perf consume persistent://public/default/test -s sub -st Exclusive -n 2
[pulsar-client-io-1-8] WARN  org.apache.pulsar.client.impl.ConnectionHandler - [persistent://public/default/test-partition-3] [sub-1] Could not get connection to broker: Subscription does not exist -- Will try again in 0.1 s
[pulsar-client-io-1-7] WARN  org.apache.pulsar.client.impl.ConnectionHandler - [persistent://public/default/test-partition-4] [sub-1] Could not get connection to broker: Subscription does not exist -- Will try again in 0.1 s
[pulsar-client-io-1-3] WARN  org.apache.pulsar.client.impl.ConnectionHandler - [persistent://public/default/test-partition-2] [sub-0] Could not get connection to broker: Subscription does not exist -- Will try again in 0.1 s
[pulsar-client-io-1-4] WARN  org.apache.pulsar.client.impl.ConnectionHandler - [persistent://public/default/test-partition-1] [sub-0] Could not get connection to broker: Subscription does not exist -- Will try again in 0.1 s
```

**Describe the solution you'd like**
Add some options to specify existing topics or subscriptions to meet the above scenario.

**Comment by codelipenghui** [comment]
@murong00 If users disabled the topic auto-creation or subscription auto-creation. Users should create a Topic or Subscription for perf test, any reason for introducing new options in #8342?

**Comment by murong00** [comment]
@codelipenghui I agree with you, however,  when `--num-topics` or `--num-consumers` is larger than one current `--topic` and `--subscription`(whose size are not allowed to be greater than one) are regarded as a prefix and topics and subscriptions prefixed with this are auto-created.  If we fix it by allowing multi topis/subs, I think it is a break change, what's more, how do users decide whether to automatically create topics(default behavior) with the prefix or to use the specified ones?

**Comment by codelipenghui** [comment]
@murong00 I think we can check if the specified topic name and subscription name is already created, if created we should use the existing topic and namespace directly, if not we should create new topics and subscriptions as expected. I think it's more clear for users(Pulsar client also following this pattern).

**Comment by murong00** [comment]
@codelipenghui Thanks for pointing this out, however, the user may not have permissions to create new topics and subscriptions. In addtion, if we fix --topic (which is `List<String>` but only one is allowed) to support using the specified topics and check its size by `--num-topics`, it is inconvenient when auto-creation is allowed.
