### ISSUE TITLE
[Admin API] Prevent setting an invalid Retention Policy

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#8346]
**Problem**
Currently if one [sets in the retention policy](https://pulsar.apache.org/docs/en/2.6.1/cookbooks-retention-expiry/#set-retention-policy) `--time` to some value and sets `--size` to 0, this will lead to the situation where there is no retention. Such retention policy should be rejected since the time setting will have no meaning when size is 0. (the same applies the other way around, setting time to 0 and size to some value)

**Describe the solution you'd like**
An retention policy where either time or size is non-zero and other is zero should be rejected in validation. This would be useful to prevent users creating invalid retention policies. 

**Additional context**
#8345

**Comment by addisonj** [comment]
As a bit of a truth table for what configurations should be valid:

both greater than zero: valid
both -1: valid
both 0: valid
one greater than, one -1: valid
one 0, the other greater than 0 or -1: invalid
