### ISSUE TITLE
[Github Flow] pom.xml change is considered a documentation change

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#8362]
The current Github Flow's  "Check if this pull request only changes documentation" step (id=docs) considers a pom.xml change as a documentation change. When there's a commit that doesn't contain other changes, all tests will be skipped.

**Expected behavior**
pom.xml shouldn't be considered as a documentation change and when any pom.xml file is change, it should run tests.

**Additional context**
https://github.com/apache/pulsar/pull/8351 passed the checks without running any tests. Example: https://github.com/apache/pulsar/runs/1295771802
There's https://github.com/apache/pulsar/pull/8361 to fix the broken state of CI.
See #7955 which introduced the skipping of tests when changes are only in documents. One possible solution is to revert those changes.

**Comment by lhotari** [comment]
It seems that this script is eventually used in the checks: 
https://github.com/apache/pulsar-test-infra/blob/master/diff-only/entrypoint.sh 
it's missing a feature to specify exception patterns, I guess. If the root pom.xml file changes, it's not a doc change.

**Comment by lhotari** [comment]
To debug the issue I stored the logs from the pipeline to a gist: https://gist.github.com/lhotari/a4b7aa97d240b6914cfbb3935776c2ea#file-ci_bug_logs-txt-L675

**Comment by lhotari** [comment]
It seems that there's a bug in https://github.com/apache/pulsar-test-infra/blob/master/diff-only/entrypoint.sh . 
it doesn't seem to handle the case when a commit includes changes only in the root directory
some log rows:
```
2020-10-23T01:26:37.4699758Z HEAD
2020-10-23T01:26:37.7372668Z CHANGED_DIRS are : 
2020-10-23T01:26:37.7376810Z Changes  only in site2 deployment .asf.yaml .ci ct.yaml, setting 'changed_only' to 'yes'
2020-10-23T01:26:38.9524837Z Post job cleanup.
```

**Comment by lhotari** [comment]
I pushed a fix to diff-only https://github.com/apache/pulsar-test-infra/pull/11

**Comment by jiazhai** [comment]
Thanks @lhotari for the help
