### ISSUE TITLE
Bookie decommissioning documentation from 2.6.0 not present in 2.6.1

### ISSUE THREAD

**Issue by Ghatage** [apache/pulsar#8364]
**Describe the bug**
I had written some [documentation for decommissioning bookies](https://github.com/apache/pulsar/commit/59f160792a6335988c8604e15345e234ef06acb3) which went into the 2.6.0 release documentation [here](https://pulsar.apache.org/docs/en/2.6.0/administration-zk-bk/#decommissioning-bookies-cleanly).
If you go to the Pulsar website at the [2.6.1 documentation link](https://pulsar.apache.org/docs/en/administration-zk-bk/) the decommissioning documentation is missing.

**To Reproduce**
2.6.0 documentation: https://pulsar.apache.org/docs/en/2.6.0/administration-zk-bk/
2.6.1 documentation: https://pulsar.apache.org/docs/en/administration-zk-bk/

**Expected behavior**
2.6.1 documentation should have the decommissioning documentation.

This would have helped with more recent issues with decommissioning like https://github.com/apache/pulsar/issues/7653

**Comment by Jennifer88huang** [comment]
@Ghatage thanks for raising the issue. We'll look into it soon.

**Comment by Jennifer88huang** [comment]
Hi @Ghatage Thanks for your issue. I've just checked the content and found the inconsistent info in the different versions, and fix it in #8368.
Thanks again for your feedback. Any issue, feel free to comment.
