### ISSUE TITLE
Parsing payload commands failed

### ISSUE THREAD

**Issue by turtleDeng** [apache/pulsar#8366]
Hello there,

I am using Erlang to write a Pulsar consumer.

If I used pulsar-2.3 the received message would be as follows:

```
<<0,0,0,68,0,0,0,23,8,9,74,19,8,1,18,15,8,10,16,2,24,255,255,255,255,255,255,255,255,255,1,0,0,0,32,10,14,115,116,97,110,100,97,108,111,110,101,45,48,45,50,16,1,24,157,140,225,201,213,46,50,3,107,101,121,64,0,104,101,108,108,111>>
```

But if I used pulsar-2.6, the received message would be:
```
<<0,0,0,76,0,0,0,23,8,9,74,19,8,1,18,15,8,10,16,2,24,255,255,255,255,255,255,255,255,255,1,0,0,0,32,10,14,115,116,97,110,100,97,108,111,110,101,45,48,45,50,16,1,24,157,140,225,201,213,46,50,3,107,101,121,64,0,0,0,0,4,24,44,64,3,104,101,108,108,111>>
```

No matter which version it is, it is inconsistent with your official document structure: 

http://pulsar.apache.org/docs/en/develop-binary-protocol/#payload-commands

so I am very confused, how can I parse it?

**Comment by codelipenghui** [comment]
@turtleDeng The frame does not change, are you using any protobuf-erlang lib for the command serialization and deserialization? If not, I think it will be more complicated because Pulsar uses the `pb` directly.

**Comment by turtleDeng** [comment]
thank you for your reply.
I use protobuf-erlang to parse.
I can use pb to parse the message, but other fields cannot be parsed according to your document http://pulsar.apache.org/docs/en/develop-binary-protocol/#payload-commands

**Comment by turtleDeng** [comment]
<img width="653" alt="pulsar1" src="https://user-images.githubusercontent.com/1830077/97160541-78ea3100-17b7-11eb-88ad-8449b88036a5.png">
<img width="1114" alt="pulsar2" src="https://user-images.githubusercontent.com/1830077/97160560-7c7db800-17b7-11eb-80c9-c46c324e88e3.png">

**Comment by jiazhai** [comment]
PulsarChannelInitializer.java contains the frame info:
![Uploading image.png…]()

**Comment by jiazhai** [comment]
![image](https://user-images.githubusercontent.com/6348208/97182887-0ccbf500-17d8-11eb-8c66-90a2f10dc390.png)

**Comment by turtleDeng** [comment]
Thank you, everyone. I solved the problem. I need to parse the SingleMessageMetadata before the payload. If my producer is a single message, it will not add SingleMessageMetadata so it cannot be parsed. Thanks again!
