### ISSUE TITLE
[doc] The command bin/pulsarctl cannot be used in the offloader document 

### ISSUE THREAD

**Issue by jianyun8023** [apache/pulsar#8400]
**Describe the bug**
The command bin/pulsarctl cannot be used in the offloader document.

**To Reproduce**
1. Go to 'https://pulsar.apache.org/docs/en/next/tiered-storage-filesystem/#example-2'
2. The command `bin/pulsarctl`  cannot be found in the PULSAR_HOME/bin

**Comment by wolfstudy** [comment]
Yes, maybe we need to remove `pulsarctl` from Apache Pulsar docs, @Jennifer88huang @Huanli-Meng please help to check?

**Comment by Huanli-Meng** [comment]
@wolfstudy , OK, will update the doc accordingly.

**Comment by codelipenghui** [comment]
@Huanli-Meng Any update on this issue?

**Comment by Huanli-Meng** [comment]
> @Huanli-Meng Any update on this issue?

still working on it and will summit a PR by the end of today. Thanks.
