### ISSUE TITLE
Metrics are not grouped by type

### ISSUE THREAD

**Issue by marksilcox** [apache/pulsar#8407]
**Describe the bug**
When calling the metrics endpoint I would expect them to be grouped by type. However, some metrics are grouped under the incorrect type header

**To Reproduce**
1. Run Pulsar v2.6.0
2. Fire some messages to topics
3. Access metrics endpoint

**Expected behavior**
All metrics are grouped appropriately.

**Screenshots**
![image](https://user-images.githubusercontent.com/63227862/97554918-5fbbcd00-19cf-11eb-886d-ad6fc1b9bc69.png)

**Desktop (please complete the following information):**
 - OS: Docker on MacOS, Amazon Linux on AWS

**Comment by codelipenghui** [comment]
@marksilcox The broker just expose the Prometheus formatted metrics, if you want to do some aggregate calculations, it's better to achieve at the Prometheus.

**Comment by marksilcox** [comment]
@codelipenghui I am not wanting to aggregate. As you can see from the screenshot, some metrics are not being grouped under their `# TYPE` header. See `# TYPE pulsar_msg_backlog gauge` header, under that I can see 9 other metrics not related to that header. This happens in a few other places and metrics are scattered across the output.
