### ISSUE TITLE
Add test coverage for the Pulsar IO Batch connectors

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#8408]
**Is your enhancement request related to a problem? Please describe.**
The Pulsar Batch IO classes do not have any unit tests for them

**Describe the solution you'd like**
I will be adding some unit tests for these classes

**Describe alternatives you've considered**
Not implementing unit tests.

**Additional context**
N/A

**Comment by tisonkun** [comment]
Closed as stale and no one worked on it. Please open a new issue if it's still relevant to the maintained versions.
