### ISSUE TITLE
After the bookie service goes down, the broker will go down accordingly

### ISSUE THREAD

**Issue by jiangmincong** [apache/pulsar#8414]
**Describe the bug**
After the bookie service goes down, the broker will go down accordingly
**To Reproduce**
[pulsar-bookie-jxnc-bd-olmc-001.zip](https://github.com/apache/pulsar/files/5466079/pulsar-bookie-jxnc-bd-olmc-001.zip)
[pulsar-broker-jxnc-bd-olmc-012.zip](https://github.com/apache/pulsar/files/5466081/pulsar-broker-jxnc-bd-olmc-012.zip)
[pulsar-broker-jxnc-bd-olmc-013.zip](https://github.com/apache/pulsar/files/5466082/pulsar-broker-jxnc-bd-olmc-013.zip)

**Expected behavior**
Apache Pulsar: 2.5.0
Zookeeper：3.6.1
**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by codelipenghui** [comment]
@jiangmincong From you bookie log and broker log, I think the problem is the session expire on zookeeper, could you please share the zookeeper status?

**Comment by jiangmincong** [comment]
[pulsar-bookie-jxnc-bd-olmc-012.log](https://github.com/apache/pulsar/files/5472339/pulsar-bookie-jxnc-bd-olmc-012.log)
[zk_log.zip](https://github.com/apache/pulsar/files/5472340/zk_log.zip)
[bookkeeper.conf.txt](https://github.com/apache/pulsar/files/5472346/bookkeeper.conf.txt)
[broker.conf.txt](https://github.com/apache/pulsar/files/5472347/broker.conf.txt)

This is my zk log and the bookie log corresponding to another time

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
