### ISSUE TITLE
multiple pulsarAdmin.topics().grantPermission calls created excessive transactions on the zookeepers

### ISSUE THREAD

**Issue by alexku7** [apache/pulsar#8419]
Hello
Recently we started to implement the fine  grained permissions to the topics.

We wrote simple java program which is calling to the pulsarAdmin.topics().grantPermission

Unfortunately after running the program for defining the permissions over few thousands topics (3.5k topics and 2-3 calls for each topics for consume and produce role) we realized that the zookkeeper start to suffer from huge write transactions that filled up the free disk space. The zookeepers during the running script sometimes stopped responding . Finally they crashed after 40 Gb !! disk space was filled up completely

After this case, i played with this API and definitely  could see , that this API somehow causes too much transactions on the zookeeper and even cause to zookkeeper stop responding.

 pulsarAdmin.namespaces().grantPermission is ok!
 pulsarAdmin.topics().grantPermission - cause to wrhite storm on the zookkeepers

Maybe it happens becasue the pulsarAdmin.topics().grantPermission is always async call  but should be the synchronous 

https://github.com/apache/pulsar/blob/656bcb24713f33054d0997f4004c073f8098ed5f/pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java#L278

**Comment by codelipenghui** [comment]
@alexku7 The broker will call `getData` and `setData` for each `grantPermission` operation. If you have 3.5 topics and 2-3 calls for each topic. I think this will introduce almost 10,000 operations on the zookeeper, does this match your zookeeper's index?

**Comment by codelipenghui** [comment]
@alexku7 Is the 3.5k topics is 3.5k partitioned topics or 3.5k partitions?

**Comment by alexku7** [comment]
@codelipenghui  Something about 3.5k partitioned topics with 3 partitions  for each.
So i guess it will be 10.5k calls ?

For each partitions we have few sets of permissions (consume, produce or both)

So, I understand that it's normal to "kill" 40 gb disk space by  this load ?

Btw, what do you mean "zookeeper's index"
Assume.  I put large disks, how can i improve the zookeepers performance in order to prevent "timeouts" during this heavy operations ?

**Comment by alexku7** [comment]
Good explanation for this issue on the slack from @addisonj 


Addison Higham  2 hours ago
is this in a single namespace? if so, then the reason for this is because it is all stored in single document, and because of the way the transaction log works, you are going to see a lot of churn with continuing to add to a single big document.
First off, what is the use case you are trying to solve for? Are these all to unique roles?
Second, you might consider using namespaces to work around this
Finally, if you want to support this easily today, you could implement your own authorization backend and use some alternative store and/or alternative way of defining all the calls. At some point, we expect to rework the build-in ACL implementation to not write to zookeeper

alex kurtser  1 hour ago
Thanks
Actually we have lot of namespaces were each one can have up to 500 topics and the permissions there are per topic , not per namespace.
IF all this information is stored in the single document, it make sens why we  see lot of write transactions.
I don;t know if we can implement now our own authorization back-end..
we will think how to change the design in order to find some workaround
Do you know about the ETA for the eliminating the using of zookkeeper for the permissions store ?

**Comment by alexku7** [comment]
So I believe  , this is bad combination of the permissions storing model in the zookeeper with our per-topic RBAC design :(

**Comment by codelipenghui** [comment]
@alexku7 Yes, currently all permissions of the topic are stored in a zookeeper znode. There are 2 ways to change the situation:

1. Use multiple znodes to store permissions of the topics under the namespace(split by the hash of the topic name)
2. Use system topic to store the namespace policy, currently, we already use the system topic to store the topic level policy. So, this is a more elegant way.

**Comment by alexku7** [comment]
@codelipenghui  What do you mean "system topic" ?

**Comment by codelipenghui** [comment]
@alexku7 It's an internal topic in a namespace. We can store some configurations in the system topic such as the topic policy configurations. After the broker startup, we can recover the configurations from the system topic. And the system topic is a compacted topic, it will only retain the last value of a key, the old values of the key will be deleted automatically.

**Comment by 315157973** [comment]
I will work on it

**Comment by zymap** [comment]
Move this to the next release.

**Comment by michaeljmarshall** [comment]
Since we don't have a PR for this, I am going to remove the 2.7.4 label. We should still try to fix it, of course, but there is no target release if we don't have a commit.

**Comment by tisonkun** [comment]
Closed as stale and no one seems to work on it. Please create a new issue if it's still relevant to the maintained versions.
