### ISSUE TITLE
Adding document for e2e encryption pulsar functions

### ISSUE THREAD

**Issue by nlu90** [apache/pulsar#8431]
**Is your feature request related to a problem? Please describe.**
Document work for #8382 and PR #

**Describe the solution you'd like**
Adding related document for the new e2e support

**Comment by Jennifer88huang** [comment]
@nlu90 thanks for raising the issue.

**Comment by codelipenghui** [comment]
@nlu90 I will start the 2.7.0 release process soon. Do you have time to add the documentation for https://github.com/apache/pulsar/pull/8432?

**Comment by wolfstudy** [comment]
> @nlu90 I will start the 2.7.0 release process soon. Do you have time to add the documentation for #8432?

@codelipenghui Please add this task to me, I will process this task.
