### ISSUE TITLE
Issues producing to Pulsar

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#8433]
We're seeing issues with producing to one of our clusters running Pulsar 2.4.0. 
The chart below shows the occurrences of errors producing to the cluster. 
![image](https://user-images.githubusercontent.com/7418031/97919321-d3821080-1d14-11eb-9930-b607f15d565d.png)

While looking through the logs, we see:

org.apache.pulsar.broker.loadbalance.impl.LeastLongTermMessageRate - Broker x is overloaded

org.apache.pulsar.broker.loadbalance.impl.OverloadShedder - Broker x is overloaded despite having no bundles

We got a thread dump. It's quite large, and it appears that almost all of the threads are in a WAITING (parking) state. 
The thread dump file is attached.
[thread-dump-broker07.txt](https://github.com/apache/pulsar/files/5478053/thread-dump-broker07.txt)

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
