### ISSUE TITLE
Intermittent test failure UnAcknowledgedMessagesTimeoutTest.testFailoverSingleAckedPartitionedTopic

### ISSUE THREAD

**Issue by hrsakai** [apache/pulsar#844]
[jenkins](https://builds.apache.org/job/pulsar-pull-request/org.apache.pulsar$pulsar-broker/599/testReport/junit/org.apache.pulsar.client.impl/UnAcknowledgedMessagesTimeoutTest/testFailoverSingleAckedPartitionedTopic/)/[log](https://gist.github.com/hrsakai/e60967259a2d255cbbf97456d1ce372b)

```
Error Message

expected [10] but found [12]
Stacktrace

java.lang.AssertionError: expected [10] but found [12]
	at org.apache.pulsar.client.impl.UnAcknowledgedMessagesTimeoutTest.testFailoverSingleAckedPartitionedTopic(UnAcknowledgedMessagesTimeoutTest.java:336)
```

**Comment by merlimat** [comment]
I think this was actually fixed in #2590 . I haven't seen this test fail anytime recently and the test code is anyway completely different.  I've run it in a tight loop and consistently passes locally, even when running in a docker inside vm env.
