### ISSUE TITLE
pulsar-admin cli namepsace offload policy labels deletion lag incorrectly

### ISSUE THREAD

**Issue by rivernate** [apache/pulsar#8440]
**Describe the bug**
When using the pulsar-admin cli tool to set an offload policy for a namespace, the deletion lag setting is labeled as "offloadAfterElapsedInMillis" and the documentation for the command describes it as setting the amount of elapsed time before an offload happens. What it actually sets is the deletion lag for the namespace

**To Reproduce**
1. Use the pulsar-admin cli to set a offload policy for a namespace
2. in the policy specify the offloadAfterElapsedTime
3. use the pulsar-admin cli to retrieve the policy
4. The deletion lag setting was changed instead

**Expected behavior**
The documentation and options should be changed to correctly describe it as changing the deletion lag

**Additional context**

See the CLI description here:
https://github.com/apache/pulsar/blob/ec2de258ce39b38311e92bab6882c198070d8975/pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java#L1598

The `OffloadPolicies.create` methods last argument passed the offload after elapsed setting, but is actually for offloadDeletionLagInMillis seen here:

https://github.com/apache/pulsar/blob/ec2de258ce39b38311e92bab6882c198070d8975/pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java#L1688

**Comment by codelipenghui** [comment]
@rivernate Could you please provide the version information of the Pulsar broker and pulsar-client-admin?
@gaoran10 Could you please help take a look at this issue, seems we have already fixed in the master branch, please help double-check.

**Comment by rivernate** [comment]
We have been using 2.5.2, but it looks like it's still in the source code on the current master: https://github.com/apache/pulsar/blob/14c145e3d371c3ceab979277f4b2717d7046b4a5/pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java#L1665

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
