### ISSUE TITLE
Improve branch-2.6 action CI

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar#8443]
**Is your enhancement request related to a problem? Please describe.**

In the current branch-2.6 branch, some test cases are difficult to pass in action CI, but these test cases can be passed multiple local verifications. This may be caused by ignoring the flaky test and not including cherry-pick in the pull request of cherry-pick 2.6.2.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tisonkun** [comment]
Closed as stale and no one worked on it. Please open a new issue if it's still relevant to the maintained versions.
