### ISSUE TITLE
Updating Helm chart to support GCP cert provider for TLS

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#8457]
In most production environments, using self-signed certs is not acceptable for TLS. Certs are expected to be backed by a CA for security reasons. It appears that the Pulsar Helm charts currently only support self-signed certificates. 
The doc https://pulsar.apache.org/docs/en/helm-overview/ seems to suggest that the Helm chart also supports Let's Encrypt, but the Helm chart template appears to only accept "selfsigning" as a parameter: https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/templates/tls-cert-internal-issuer.yaml#L21

It would be helpful to also support GCP as a cert provider for TLS. This article has some information on using cert-manager with GCP: https://cert-manager.io/docs/configuration/acme/dns01/google/

**Comment by codelipenghui** [comment]
@devinbost Is it better to move this issue to https://github.com/apache/pulsar-helm-chart/issues? We have moved all helm charts to https://github.com/apache/pulsar-helm-chart/issues

**Comment by devinbost** [comment]
@codelipenghui Noted. I linked the issue, and I'll close it here.
