### ISSUE TITLE
Converting Schema from STRING to JSON not working in pulsar function

### ISSUE THREAD

**Issue by Esakkimuthu991** [apache/pulsar#8459]
**I have a pulsar function, which will process the incoming STRING message convert it to JSON schema and publish it to output topic. Then pulsar sink will process it and saving into postgres db.**

Implementation for the pulsar functions
`context.newOutputMessage({pulsarsinkinputtopic}, Schema.JSON(POJO.class)).value().sendAsync();`

**To Reproduce**
1. create a pulsar function and pulsar sink for postgres 
2. upload a json schema for sink input topic
3. then produce message from java client
4. check the function log. showing error as class not found exception

Note: I tried Pulsar sink input topic accepts JSON Schema .

**Comment by codelipenghui** [comment]
@Esakkimuthu991 Could you please provide the detailed stacktrace of the class not found exception? This is very useful for troubleshooting the problem.

**Comment by Esakkimuthu991** [comment]
Sorry for late response. The problem was occurred due to the jar generation. Now it resolved

**Comment by thomaeschen** [comment]
Hi Easkkimuthu992, 

How do you solve the issue? I have similar issue while using the class JSONSchema . Cam you give me a hand?
