### ISSUE TITLE
[docs] Duplicate info of using C++ in Pulsar

### ISSUE THREAD

**Issue by Jennifer88huang** [apache/pulsar#8477]
**Describe the bug**
There are duplicated info of using C++ in Pulsar.

**To Reproduce**
1. Go to https://pulsar.apache.org/docs/en/next/client-libraries-cpp and https://pulsar.apache.org/docs/en/next/develop-cpp/
2. Some info are duplicate and distributed, we should integrate info and put info users care together, which is user-friendly

**Comment by sijia-w** [comment]
see 8919 in pulsar repo
