### ISSUE TITLE
ackTimeoutMillis is set to 30000 when ConsumerBuilder.deadLetterPolicy is called

### ISSUE THREAD

**Issue by tomas-c** [apache/pulsar#8484]
Hey everyone,

I'm a bit confused about the usage of Dead Letter Queue with NACKs.

Initially I had a shared consumer like so (apologies for my Kotlin) and was using NACKs:

```
        val jobConsumer = pulsarClient.newConsumer(JSONSchema.of(jobDefinition))
                .topic("<removed>")
                .subscriptionName("<removed>")
                .subscriptionType(SubscriptionType.Shared)
                .receiverQueueSize(0)
                .subscribeAsync()
                .await()
```

Later I decided it would be good to make sure failed messages don't get redelivered too many times so I added a dead letter policy:

```
        val jobConsumer = pulsarClient.newConsumer(JSONSchema.of(jobDefinition))
                .topic("<removed>")
                .subscriptionName("<removed>")
                .subscriptionType(SubscriptionType.Shared)
                .receiverQueueSize(0)
                .deadLetterPolicy(DeadLetterPolicy.builder()
                        .maxRedeliverCount(2)
                        .build())
                .subscribeAsync()
                .await()
```

#### Expected behavior

I expected this to start forwarding messages after 2 deliveries to the DLQ and nothing else to change.

#### Actual behavior

What happened was that the ackTimeoutMillis got set to 30s behind the scenes (this is documented behavior but I didn't expect it...) and then all my messages started timing out because each was originally taking more than 30s to process.

I see this default setting was introduced by #3014

#### System configuration
**Pulsar version**: 2.6.1

Is it safe to override the ackTimeoutMillis timeout that was set by the deadLetterPolicy() call and just set it to 0 again? Is there any reason why DLQ would not work when ack timeouts are disabled and NACKs are used instead?

Thanks!

**Comment by codelipenghui** [comment]
@tomas-c The DLQ should work with NACKs, if it does not work, it should be fixed. Are you interested in fix it?

**Comment by tomas-c** [comment]
Hey @codelipenghui ! 

If it's something small, I could have a try but just to make it clear - I haven't observed DLQ not working with NACKs. 

I was just surprised by deadLetterPolicy() auto-setting ackTImeoutMillis to 30s and breaking my time-consuming message processing. And also confused by changes in #3014 implying that ackTImeoutMillis was necessary (but I now see that NACKs were implemented after the DLQ feature so makes sense why it was the default at that time).

If ackTimeoutMillis is no longer required for DLQ to work, would it make sense to change this default? Or would people be worried about this being a backwards-incompatible change as it would disable ack timeout for people who (possibly accidentally) enabled it by enabling the DLQ?

Besides my confusion, there's another possible one that changing this default would prevent:

```
consumerBuilder
    .ackTimeout(0, TimeUnit.MILLISECONDS)
    .deadLetterPolicy(DeadLetterPolicy.builder().build())
    .subscribe()
```

results in ack timeout set to 30s but

```
consumerBuilder
    .deadLetterPolicy(DeadLetterPolicy.builder().build())
    .ackTimeout(0, TimeUnit.MILLISECONDS)
    .subscribe()
```

results in ack timeout disabled.

**Comment by codelipenghui** [comment]
> I was just surprised by deadLetterPolicy() auto-setting ackTImeoutMillis to 30s and breaking my time-consuming message processing. And also confused by changes in #3014 implying that ackTImeoutMillis was necessary (but I now see that NACKs were implemented after the DLQ feature so makes sense why it was the default at that time).

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
