### ISSUE TITLE
document is err

### ISSUE THREAD

**Issue by sixhj** [apache/pulsar#8496]
look http://pulsar.apache.org/docs/zh-CN/administration-pulsar-manager/

the  docker command  no  -- link,

**Comment by codelipenghui** [comment]
@sixhj Could you please give more details about the problem? Or if you are interested in fix this issue you can push a PR for it.

**Comment by sixhj** [comment]
docker run -it \
  -p 6650:6650 \
  -p 8080:8080 \
  --mount source=pulsardata,target=/pulsar/data \
  --mount source=pulsarconf,target=/pulsar/conf \
  apachepulsar/pulsar:2.6.2 \
  bin/pulsar standalone


 no.  --name. 

docker pull apachepulsar/pulsar-manager:v0.2.0
docker run -it \
    -p 9527:9527 -p 7750:7750 \
    -e SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties \
    apachepulsar/pulsar-manager:v0.2.0


no  --link  , so    pulsar manager  new environment   ,  the service URL    , what is input ?

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
