### ISSUE TITLE
Python lib connectors

### ISSUE THREAD

**Issue by bloodyjuice** [apache/pulsar#8503]
anyone can help me how to use elasticsearch connector in python code?

**Comment by codelipenghui** [comment]
@bloodyjuice I think there are no python connectors now, all connectors are based on Java Function. But Pulsar has python functions, I think it's easy to implement a connector based on the python functions. If you are interested in implement it, you are welcome to push a PR.

**Comment by tisonkun** [comment]
Closed as stale and inactive.
