### ISSUE TITLE
Add topic message counter

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#8516]
I want to view the amount of messages written by topic through pulsar admin or restapi. However, the current amount of messages written is only stored in the broker. If the broker restarts or the bundle is unloaded, the amount of messages written will be incorrect. In practical applications, no matter what the reason is, it must be accurate.

**Comment by codelipenghui** [comment]
Seems this can achieve by leverage https://github.com/apache/pulsar/wiki/PIP-70%3A-Introduce-lightweight-raw-Message-metadata. We can add an offset for a topic, So the `offset of the last message` + 1 is the total messages that sent to this topic.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
