### ISSUE TITLE
encounter ClassNotFoundException when using master branch to create PulsarAdmin

### ISSUE THREAD

**Issue by reswqa** [apache/pulsar#8524]
**Describe the bug**
In order to use transaction to make exactly-once sink of pulsar-flink connector, I packaged the master branch of pulsar. When the dependency was imported to create pulsarAdmin, it happened `java.lang.ClassNotFoundException`

**To Reproduce**
1、Use `mvn clean install` to package pulsar master branch.
2、Create pulsarAdmin by 
`PulsarAdmin.builder().serviceHttpUrl(serviceURL).build();`
3、The error occurred

**Expected behavior**
Create pulsarAdmin correctly.

**Screenshots**
<img width="2310" alt="WeChat74aa2e2f90c1de949308c4a94f5d29df" src="https://user-images.githubusercontent.com/19502505/98830797-c502ca00-2475-11eb-8b82-efdcd52fc3a6.png">

**Desktop (please complete the following information):**
 - OS: macos
 - JDK: jdk1.8.0_271

**Additional context**
None.

**Comment by reswqa** [comment]
This problem has been discussed with @gaoran10 and further track is needed.

**Comment by jiazhai** [comment]
https://github.com/apache/pulsar/pull/7515/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8
in this change, the version of jersey changed, maybe this is related.

**Comment by reswqa** [comment]
This is caused by the previous PR that @jiazhai mentioned, I will fix it and add some tests to prevent similar problems from appearing later.

**Comment by jiazhai** [comment]
@reswqa  Thanks for the work. Maybe have 2 prs is also fine for this issue. one for this direct fix. and also added #8542 for the test coverage.
