### ISSUE TITLE
Certificate and Token revocation

### ISSUE THREAD

**Issue by alexku7** [apache/pulsar#8525]
**Is your feature request related to a problem? Please describe.**
Currently the pulsar doesn't have an ability to check and ensure that the client certificates used for the authentication is not revoked, In case of compromised certificate , an attacker can't continue using the stolen certificate until its expiration date and the only solution here is to replace the whole CA 

**Describe the solution you'd like**
The Pulsar will have a flag  for example enableCRLChecking . When enabled, the Pulsar will verify the CRL list and ensure that the certificate is not revoked. 
The same will be good to implement for the token based authentication.

**Describe alternatives you've considered**
No good and valid alternative exists todate in the pulsar

**Additional context**
Nope

**Comment by tisonkun** [comment]
Closed as stale and no one showed interest. Please open a new issue if it's still relevant to the maintained versions.

**Comment by lhotari** [comment]
This might be related to #8152 . Is it covered with that? We already have support for OIDC in Pulsar 3.0
