### ISSUE TITLE
Export Consumer/Producer connection status to user

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#8532]
Some times consumer/producer get re-connect to broker, but this is the internal connect retry, and user may not know the current connection status. It would be better to export the connection status.

**Comment by 315157973** [comment]
I will solve it

**Comment by jiazhai** [comment]
Thanks @315157973  for the help

**Comment by jiazhai** [comment]
@315157973 some times it will help a lot if we could also provide some connection information, such as the last success time or the first non-success re-connection time.

**Comment by codelipenghui** [comment]
related to #8532

**Comment by codelipenghui** [comment]
Currently, the consumer and the producer has a method to check the isConnected. So I think it's can help users to check the connection state, So I think we can close this issue first.
