### ISSUE TITLE
Is auto delete inactive topic works well on partitioned topic

### ISSUE THREAD

**Issue by Shoothzj** [apache/pulsar#8551]
**Describe the bug**
According to my understanding, **partitioned-topic** is implemented by multi topics which suufix is {partition-index}. We have this situtation in version 2.6.0. When we enable **brokerAutoDeleteInActiveTopic** (aka. aging), our $TOPIC_NAME-partition-index topic is aged, but /admin/../partitioned-topic data remains.Eventually, when client query if topic exist, it exists. But can't subscribe success.

**To Reproduce**
1. Turn on the **brokerAutoDeleteInActiveTopic** 
2. Create a partitioned topic
3. Wait for aging time
4. Create a consumer and U can see

I was wondering what's the design
1. partitioned topic is just logical concept, aging unit is topic
OR
2.partitioned topic is whole, need tobe aging together

**Comment by codelipenghui** [comment]
@Shoothzj Looks the same as #8441 and it fixed by #8442

**Comment by Shoothzj** [comment]
It is ! Thank you very much
