### ISSUE TITLE
[Pulsar Broker] support apache ranger

### ISSUE THREAD

**Issue by ltamber** [apache/pulsar#8553]
**Is your feature request related to a problem? Please describe.**
Currently, Pulsar only support stores authorization policies under local-zookeeper. Is it possible to support [ranger](https://github.com/apache/ranger), apache ranger can provide a framework for central administration of security policies and monitoring of user access.

**Comment by jiazhai** [comment]
Thanks @ltamber for this initiative. It would be a great supplementary to current authorization.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.

Wishing list is not kept. Open-source projects grow with contributions, not requirements :)
