### ISSUE TITLE
[Question] Last-value-queues support

### ISSUE THREAD

**Issue by strangeman375** [apache/pulsar#8562]
Hello!
Does Pulsar support last-value-queue, like [artemis](https://activemq.apache.org/components/artemis/documentation/latest/last-value-queues.html)?

**Comment by aahmed-se** [comment]
pulsar supports topic compaction so in essence it provides the same functionality

**Comment by strangeman375** [comment]
Thanks!
Unfortunately, this is not exactly the same functionality.
Last-value-queues are vital to my project, so i can't use pulsar yet.

**Comment by tisonkun** [comment]
Closed as stale.

You can ask questions on the Discussion forum now. We almost use issues to track actionable tasks.
