### ISSUE TITLE
[document] How to deploy Pulsar SQL on docker/k8s

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#8569]
Currently, Pulsar documentation introduces how to deploy Pulsar SQL manually http://pulsar.apache.org/docs/en/sql-getting-started. It's better to provide a guide for deploying Pulsar SQL on docker/k8s.

**Comment by Jennifer88huang** [comment]
Since we contribute Pulsar SQL to Trino community and will remove the whole documentation from Pulsar doc set, shall we provide the guide for deploying Pulsar SQL on docker/k8s in Pulsar in the future?

**Comment by momo-jun** [comment]
Closed the issue since it hasn't been planned yet at this moment. Feel free to reopen it when it's relevant.
