### ISSUE TITLE
pulsar producter write to 3 node gluster slower than standalone

### ISSUE THREAD

**Issue by cclient** [apache/pulsar#8570]
#### Actual behavior

pulsar producter write to 3 node cluster slower than standalone

#### System configuration
Pulsar version: 2.6.2

all use the default config and same disk(hdd)/net

##### to standalone

time bin/pulsar-client --url pulsar://a.b.c:6650  produce   persistent://public/default/test   -n 1000  -m "Hello Pulsar"
real	0m5.940s
user	0m8.329s
sys	0m0.964s

##### to 3 node gluster

time bin/pulsar-client --url pulsar://a.b.c:36650  produce   persistent://public/default/test   -n 1000  -m "Hello Pulsar"
real	0m38.696s
user	0m9.626s
sys	0m1.539s

is any config can slove this problem?

**Comment by codelipenghui** [comment]
@cclient The data fsync is disabled by default in the standalone but enabled by default in the broker. I think you can try to enable the data fsync in standalone.conf or disable the data fsync in the broker.conf.

**Comment by cclient** [comment]
> @cclient The data fsync is disabled by default in the standalone but enabled by default in the broker. I think you can try to enable the data fsync in standalone.conf or disable the data fsync in the broker.conf.

thanks

cluster:
conf/bookkeeper.conf
journalSyncData=false

standalone:
conf/standalone.conf
journalSyncData=true 

it was my negligence
