### ISSUE TITLE
The RESTAPI "Get the internal stats for the topic" does not show the status of the ledger

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#8583]
**Describe the bug**
The RESTAPI "Get the internal stats for the topic" does not show the status of the ledger，so the status displayed on the pulsar manager page may not be correct。

![image](https://user-images.githubusercontent.com/54351417/99341352-b0cf2a80-28c4-11eb-9643-57aad8cffa3e.png)
![image](https://user-images.githubusercontent.com/54351417/99341476-eb38c780-28c4-11eb-9c3f-1c5cb7fcbdd0.png)
![image](https://user-images.githubusercontent.com/54351417/99341399-c04e7380-28c4-11eb-96e3-3f703813eb4b.png)
![image](https://user-images.githubusercontent.com/54351417/99341733-68643c80-28c5-11eb-8d23-902f8d95c3cb.png)

**Comment by sijie** [comment]
@xuesongxs All the ledgers in the `ledgers` list are all `closed`.

**Comment by tisonkun** [comment]
Closed as answered.
