### ISSUE TITLE
WebSocket broker: url (path and query) args (namespace, topic, etc...) exposed through message fields

### ISSUE THREAD

**Issue by bsergean** [apache/pulsar#8584]
**Is your enhancement request related to a problem? Please describe.**
If a client need to publish to 2 different topics, it will take 2 tcp connections between the client and the broker. 3 topics, 3 tcp connections etc... if ssl is enabled this is more costly.

**Describe the solution you'd like**

It would be very handy to be able to specify all the url info in the websocket message instead. There are multiple websocket apis that do that, like [wamp](https://wamp-proto.org/), [wamp publish doc](https://wamp-proto.org/_static/gen/wamp_latest.html#publish-0) or [cobra](https://machinezone.github.io/cobra/api/). I'm trying to look at the [pusher api](https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol) but cannot find the details, however it looks possible to make multiple subscriptions with a single client.

For publishing, instead of doing this:

url: */ws/v2/producer/persistent/:tenant/:namespace/:topic?param1=too&param2=bar*
```
{
  "payload": "SGVsbG8gV29ybGQ=",
  "properties": {"key1": "value1", "key2": "value2"},
  "context": "1"
}
```

Do this:

url: */ws/v2*
```
{
  "payload": "SGVsbG8gV29ybGQ=",
  "properties": {"key1": "value1", "key2": "value2"},
  "context": "1",
  ---------- Extra args ---------
  "action": "producer",
  "persistence": true,
  "tenant": "a tenant",
  "namespace": "a namespace",
  "topic": "a topic"
  "params": {
     "param1": "foo",
     "param2": "bar"
  }
}
```

**Describe alternatives you've considered**
Writing a proxy broker that does this ?

**Additional context**
If a client needs to publish to 10 topics, or 50, it will need to create 10, 50 tcp connections to the broker which is not scalable.

Thanks !

**Comment by bsergean** [comment]
Some developer notes / the producer is handled here -> https://github.com/apache/pulsar/blob/master/pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketProducerServlet.java

A first good step would be to still have different url for producer/consumer/reader, but be able to still use the same websocket connection for publishing to different topics.

**Comment by bsergean** [comment]
AbstractWebSocketHandler.java and    private TopicName extractTopicName(HttpServletRequest request) {

is where the request is being parsed, and where topic is extracted

```
return TopicName.get(domain, namespace, name);
```

**Comment by hpvd** [comment]
just as crosslink to an other websocket performance relevant issue:
Websocket API should support cumulative acknowledgement
https://github.com/apache/pulsar/issues/5979

**Comment by hpvd** [comment]
if you like to push websocket possibilities in pulsar,
please just add your thoughts and comments or simply vote for or react to it https://github.com/apache/pulsar/issues/8701

**Comment by bsergean** [comment]
FYI I have worked around this by writing a websocket client based on libuv, which allow to have multiple tcp connections using a single thread.

https://github.com/bsergean/uvweb/blob/master/uvweb/PulsarClient.cpp

If someone want to gives this a try (it's very alpha) feel free.

Previously I was planning on using [IXWebSocket](https://github.com/machinezone/IXWebSocket) which is designed to have one thread per connection.

**Comment by hpvd** [comment]
@bsergean many thanks - will have a look into it!

**Comment by tisonkun** [comment]
Closed as stale and workaround presented. Please open a new issue if it's still relevant to the maintained versions.
