### ISSUE TITLE
Update TLS instructions to cover the change in default keystore type from JKS to PKCS12 in Java 9+

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#8586]
**Problem**

TLS instructions in https://github.com/apache/pulsar/blob/master/site2/docs/security-tls-keystore.md break in Java 9+ since the [default keystore type is PKCS12 in Java 9+](http://openjdk.java.net/jeps/229).
Prepare for supporting Java 9+ by updating the instructions.

**Solution**

Add `-storetype JKS` parameter to `keytool` commands in https://github.com/apache/pulsar/blob/master/site2/docs/security-tls-keystore.md .
Another possibility would be to document how the PKCS12 keystore can be used with Pulsar.

**Additional context**

[default keystore type is PKCS12 in Java 9+](http://openjdk.java.net/jeps/229)

**Comment by tisonkun** [comment]
The related page has been removed from the latest(next) docs. Closed as invalid.
