### ISSUE TITLE
Configurable data source for offloaded messages

### ISSUE THREAD

**Issue by Renkai** [apache/pulsar#8591]
Currently, if the data in pulsar was offloaded to the second storage layer, data can still exists in bookkeeper for a period of time, but the client will directly read data from the second layer. 

This may lead to several problems:

- Read from second layer have different performance characteristics, which may lead wrong estimate from users if they didn't know which layer they are reading.
- The second layer may be managed by another team rather than Pulsar management team(for example, a independent HDFS management team), they may have independent quota or authority policy to users.
- The second layer storage can be infinite in theory, if user set cursor to an error time in accident, it will cause a lot of resource waste.

So it's better to make data source configurable if data exists in both layer.

Maybe the below options are enough:

- first layer only
- first layer first
- second layer only
- second layer first

We can make `second layer fist` as the default value, which will result to the same behavior with current version.

Todo list: 

- [ ] publish PIP
- [ ] add configuration
- [ ] implement & test
- [ ] doc

**Comment by gaoran10** [comment]
LGTM

**Comment by Renkai** [comment]
I will try to implement this design.

**Comment by sijie** [comment]
@Renkai Can you write a PIP for that?

**Comment by Renkai** [comment]
> @Renkai Can you write a PIP for that?

Of course, what should I supply to make this issue description a PIP?

**Comment by Renkai** [comment]
I posted a PIP draft at https://gist.github.com/Renkai/e5be927404fbfd8289e7703c55812b1c

**Comment by Renkai** [comment]
PIP draft at google docs:
https://docs.google.com/document/d/1IyTd3GyUjGacu9bP3M1R9YINMTPC8xzhRigApsCpzTo/edit#heading=h.irwvg5wh2y3i

**Comment by Renkai** [comment]
Official PIP: https://github.com/apache/pulsar/wiki/PIP-73%3A-Configurable-data-source-priority-for-message-reading
