### ISSUE TITLE
functions-worker get function instance's metrics error

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#8607]
**Describe the bug**
Prometheus collects metrics from functions-worker and throws the following exceptions. After multiple functions are created, the   metrics returned by functions worker is too large, at present, we solve this problem by modifying the timeout of Prometheus.

![image](https://user-images.githubusercontent.com/54351417/99503183-fc630080-29b8-11eb-8dec-2ccc12a1bf7c.png)
![image](https://user-images.githubusercontent.com/54351417/99503459-316f5300-29b9-11eb-8ac1-b433f4645da4.png)

**Comment by wolfstudy** [comment]
After communicating with @xuesongxs , we found that we have started nearly 2000 function instances, so there is no way to return the required metrics information within the default prometheus timeout period. This problem can be solved by adjusting the prometheus timeout period.
