### ISSUE TITLE
Enrich the usage of Websocket in Pulsar docs

### ISSUE THREAD

**Issue by Jennifer88huang** [apache/pulsar#8610]
Add the following doc in [Websocket docs](http://pulsar.apache.org/docs/en/client-libraries-websocket/):
1. how to deploy websocket and how to enable TLS for websocket; 
2. how to configure your client to connect to a tls-secured websocket endpoint
3. how to connect to our websocket endpoint for each cluster.

**Comment by hpvd** [comment]
if you like to push websocket possibilities in pulsar,
please just add your thoughts and comments or simply vote for it https://github.com/apache/pulsar/issues/8701
