### ISSUE TITLE
Migrate the python2.7 to python3.7

### ISSUE THREAD

**Issue by zymap** [apache/pulsar#8622]
**Motivation** 

[PIP-56](https://github.com/apache/pulsar/wiki/PIP-56:-Python3-Migration) proposed we should upgrade our python version in the Docker image, we did that in the PR #7963.
But I still find some python2.7 usage in the pulsar repository:

function module:
https://github.com/apache/pulsar/blob/master/pulsar-functions/scripts/python/generate.sh

cpp module:
https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/CMakeLists.txt#L175
https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/python/CMakeLists.txt#L40https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/python/pkg/osx/vagrant-build.sh#L38

Should we remove them as well?

**Comment by BewareMyPower** [comment]
The C++ related build and test scripts rely on the docker image `apachepulsar/pulsar-build:ubuntu-16.04`.

`Dockerfile`s under https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/docker directory also need changes.

**Comment by BewareMyPower** [comment]
It's already done by [PIP-155](https://github.com/apache/pulsar/issues/15185).
