### ISSUE TITLE
Pulsar Helm repository index.yaml is not recognized as a valid repository

### ISSUE THREAD

**Issue by LeoSht** [apache/pulsar#8632]
Running the command to register Pulsar charts repository with Helm, as described in the documentation on the apache website (Step 1: Install Pulsar Helm chart) fails.

Produces the following error:

> Error: looks like "https://pulsar.apache.org/charts" is not a valid chart repository or cannot be reached: Get "https://pulsar.apache.org/charts/index.yaml": dial tcp: lookup pulsar.apache.org: getaddrinfow: A non-recoverable error occurred during a database lookup.

**Steps to reproduce**
Steps to reproduce the behavior (with the latest version of Helm, 3.4.1 at the moment) :
1. Follow the steps as described on http://pulsar.apache.org/docs/en/kubernetes-helm/
2. Run command: 'helm repo add apache https://pulsar.apache.org/charts
3. See the error

**Expected behavior**
Helm should register the repository without errors.

**Desktop:**
 - OS: [Linux, Windows]

**Additional context**
At first look, it appears that the content of the index.yaml file is returned without the "Content-Type" header. A working Helm repository (https://charts.helm.sh/stable/index.yaml) returns its file with the header "Content-Type"="text/yaml".

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Helm Chart has been permanently moved to https://github.com/apache/pulsar-helm-chart. If it's still relevant, please open an issue there.
