### ISSUE TITLE
[documentation]  replace old helm contents and replace it with new apache/pulsar-helm-chart in website

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#8640]
We have repo https://github.com/apache/pulsar-helm-chart for the latest Pulsar-helm-chart, but the docs in website: http://pulsar.apache.org/docs/en/helm-overview/ still using the old link:
```
git clone https://github.com/apache/pulsar
cd deployment/kubernetes/helm
``` 
we should search and replace the old helm contents and replace it with new https://github.com/apache/pulsar-helm-chart in the website

**Comment by rajcspsg** [comment]
I would like to work on this issue.

**Comment by rajcspsg** [comment]
@jiazhai what is the old repo that I have to look for to replace?
