### ISSUE TITLE
Topic Stats show proxy address not the actual consumer address

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#8649]
*Motivation*

The `address` field in TopicStats is useful for troubleshooting problems. However, when the clients are connected through a proxy, the `address` field shows the proxy address, not the actual client address. We should improve the way how we capture the address for clients and provide the actual client address in the topic stats.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.

I don't find a `address` field in `TopicSatis` now.
