### ISSUE TITLE
Complex Schema Deserialization Issues

### ISSUE THREAD

**Issue by EliHarper** [apache/pulsar#8672]
**Describe the bug**
message.value() deserialization failing with complex schema defined within the Python client when using Json and Avro schemas.

**To Reproduce**
1. Run the "pulsar-all" image in a Docker container
2. Configure a nested object that uses a previously defined record as a field in another using the Python client
3. Attempt to deserialize the messages from a topic with the nested object using message.value()
4. See error (IndexError: list out of range with Avro, TypeError: '<dict>' found when ${INSERT_YOUR_DEFINED_SUBSCHEMA} expected" with Json)

**Expected behavior**
Objects correctly deserialized from Json/Avro to the type specified in the schemas.

**Desktop (please complete the following information):**
 - OS: CentOS 7, Docker version 19.03.13, build 4484c46d9d

**Comment by jiazhai** [comment]
@EliHarper which version of the Pulsar image are you using?
@gaoran10 @congbobo184  to take a look. Since is easy to reproduce, also mark this as help-wanted, anyone is interested in this issue could also to have a try.

**Comment by EliHarper** [comment]
I'm sorry for the late response, and thanks for getting back to me.

I'm pulled the latest on 11/9, which I believe is 2.6.2, according to the digest (4baf6e...)

Thanks again for your help, and please let me know if there's anything else I can get for you.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
