### ISSUE TITLE
Cannot get lastMessageId for an empty topic (due to message retention)

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#8677]
**Describe the bug**
It looks like that when a topic remains empty due to message retention, it is not possible to ask for the lastMessageId

I see these errors in the HTTP server logs:
> "GET /admin/v2/persistent/XXX/YYY/ZZZZ/lastMessageId HTTP/1.1" 500 53 "-" "Pulsar-Java-v2.6.2" 2

And this line:
>  Error opening ledger for reading at position 178974309:7 - org.apache.bookkeeper.mledger.ManagedLedgerException$NonRecoverableLedgerException: No such ledger exists on Metadata Server

**To Reproduce**
I don't have a reproducer yet, I have only seen this issue in production.

**Expected behavior**
Some non-error code should be returned to the client

** System (please complete the following information):**
 - Linux, JDK14, both Pulsar Broker and Pulsar Client
- Pulsar v. 2.6.2 (server and client)

**Comment by eolivelli** [comment]
I am working on a fix

**Comment by codelipenghui** [comment]
Thanks @eolivelli

**Comment by eolivelli** [comment]
I have found an error in the logs during TrimConsumedLedgers
20-11-22-03-25-41       [XXX/YYY/ZZZZ] End TrimConsumedLedgers. ledgers=11 totalSize=34130
20-11-22-03-25-41       [XXX/YYY/ZZZZ] Removing ledger 180334035 - size: 1964
20-11-22-03-25-41       [XXX/YYY/ZZZZ] Failed to mark delete while trimming data ledgers: Invalid mark deleted position
20-11-22-03-25-41       [XXX/YYY/ZZZZ] End TrimConsumedLedgers. ledgers=1 totalSize=0
20-11-22-03-25-41       [XXX/YYY/ZZZZ] Removing ledger 178974309 - size: 2248

before this errors I see for other topics errors like:
Failed to persist msg in store: Not enough non-faulty bookies available
20-11-19-03-22-59       [persistent://xxx/xxxx/xxxx] Un-fencing topic...

**Comment by eolivelli** [comment]
I have created a reproducer, I will work on a fix tomorrow

**Comment by eolivelli** [comment]
The fix is in #8725
