### ISSUE TITLE
[Java] [v2.6.2] ConsumerBase: Bug: Removed entry wasn't the expected one.

### ISSUE THREAD

**Issue by e-marchand-exensa** [apache/pulsar#8679]
**Describe the bug**
Found this error log:

> ERR|24/022945.868 o.a.p.c.i.ConsumerBase@-client-io-10-16 Bug: Removed entry wasn't the expected one. expected=org.apache.pulsar.client.impl.ConsumerBase$OpBatchReceive@32b8260c, removed=null

**To Reproduce**
I guess hard to reproduce, probably a race condition somewhere.

**Desktop (please complete the following information):**
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

**Comment by codelipenghui** [comment]
Looks related to #8326, @lhotari could you also please help take a look at this issue?

**Comment by e-marchand-exensa** [comment]
Hi, FYI got a new occurrence of this one.

**Comment by e-marchand-exensa** [comment]
Hi @codelipenghui, @sijie , FYI got a new occurrence of this one. There's definitely something wrong with `Consumer.batchReceiveAsync()` (see my last comment on #8307).

**Comment by lhotari** [comment]
>  FYI got a new occurrence of this one. There's definitely something wrong with `Consumer.batchReceiveAsync()` (see my last comment on #8307).

@e-marchand-exensa Thanks for reporting. Would you be able to share what type of Consumer you are using and what settings (f.e. `receiverQueueSize`, `BatchReceivePolicy`,...) are used? This could help spot the issue.

**Comment by e-marchand-exensa** [comment]
Here is an extract of the `consumer` creation
```
final var builder = pulsarClient.newConsumer()
      .consumerName( consumerName )
      .topic( topic )
      .subscriptionName( subscription )
      .subscriptionType( SubscriptionType.Exclusive )
      .subscriptionInitialPosition( SubscriptionInitialPosition.Latest )
      .batchReceivePolicy( batchPolicy )
      .receiverQueueSize( batchPolicy.getMaxNumMessages() > 0 ? 2*batchPolicy.getMaxNumMessages() : 1024 )
      .maxTotalReceiverQueueSizeAcrossPartitions( 32 * 1024 )
      .acknowledgmentGroupTime( 250, TimeUnit.MILLISECONDS );
```
with the following `batchPolicy`
```
BatchReceivePolicy.builder()
      .maxNumMessages( 42 )
      .maxNumBytes( -1 ) // FIXME: because of issue #7696 in Pulsar v2.5.2
      .timeout( 1, TimeUnit.SECONDS );
```
`maxNumMessages` depends on the topic (in [128..4096]).
`timeout` depends on the topic (in [250ms..1000ms]).

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
