### ISSUE TITLE
[Doc]Contradictory documentation of websocket features

### ISSUE THREAD

**Issue by hpvd** [apache/pulsar#8688]
**Describe the bug**
at https://pulsar.apache.org/docs/en/client-libraries-websocket/ is written:
> Through WebSockets you can publish and consume messages and use all the features available in the Java, Go, Python and C++ client libraries.

When looking at the Pulsar client feature matrix
at https://github.com/apache/pulsar/wiki/Client-Features-Matrix

the picture looks different: Websocket seems to offer by far the least number of features.

**Expected behavior**
Same statements of the documentation at both places.

**Screenshots**
![2020-11-24_21h09_54](https://user-images.githubusercontent.com/5681880/100146788-b7e4d280-2e9a-11eb-9c68-db4ce6e8a250.png)

**Additional context**
of course Feature Matrix is for 2.5.0, but latest version of pulsar would not have "solved" all red crosses in Matrix :-)

but for at least one red cross there is an open issue which contains a pull request: https://github.com/apache/pulsar/issues/8247
an other issue asks for feature parity https://github.com/apache/pulsar/issues/2678
which would of course makes this issue obsolete...

**Comment by codelipenghui** [comment]
Thanks @hpvd, we should update the document. @Jennifer88huang @Huanli-Meng Could you please help take a looks at this issue?

**Comment by Jennifer88huang** [comment]
@codelipenghui  Sure.
@hpvd Thanks for raising the issue, we should sync the info in different places. Would you like to submit a PR and fix it?

**Comment by hpvd** [comment]
@Jennifer88huang 
Thanks for asking. I think someone with internal technical deep knowlegde and overview should do this, because it's not only about syncing but also about updating to what is possible with latest/up coming version.
I'm pretty new in the pulsar world and at this time only looking from extern (does not have an own active installation - hopefully this will change next year and we choose pulsar to be part of our core technology ;-)

**Comment by Jennifer88huang** [comment]
@hpvd Thanks for sharing this. Welcome to Pulsar community.
I'll take care of this issue after the Summit, and will sync with you next week.
Thanks for raising the issue. If you find any further issue, feel free to let us know.

**Comment by hpvd** [comment]
@Jennifer88huang Thanks a lot!
I've seen you have already worked on the feature matrix. Looks already a little more friendly for websocket :-)
Just a question: why are red crosses used in the websocket column for "missing features" but empty fields in the other columns?

**Comment by hpvd** [comment]
- effectively once for websocket seems to be still open: https://github.com/apache/pulsar/issues/8175
- for NACK Support there is an open pull request: https://github.com/apache/pulsar/pull/8249, https://github.com/apache/pulsar/issues/8247

**Comment by Jennifer88huang** [comment]
@hpvd Thank you very much for your feedback. I'd like to explain the following points:
1. I've updated the [client feature matrix page](https://github.com/apache/pulsar/wiki/Client-Features-Matrix) accordingly. Some features in Websocket are not supported, yet we have plan to support them in the future. If you are familiar with any feature and would like to help, feel free to contact us.
2. Effectively-once is supported for websocket. We'll provide related info in #8175, and close the issue after @cvuijst agrees.
3. Nack Ack will also be supported once the PR #8249 is merged. Some test issues block #8249. We can update the website again after this PR is merged.
4. Concerning the documentation: "Through WebSockets you can publish and consume messages and use all the features available in the Java, Go, Python and C++ client libraries", it's our ultimate target. Currently, WebSockets could not use some features. To avoid misunderstanding, maybe I can refine it as "Through WebSockets you can publish and consume messages and use features available in the Java, Go, Python and C++ client libraries. For details on the features available for WebSockets, refer to [Client Features Matrix](https://github.com/apache/pulsar/wiki/Client-Features-Matrix)."

**Comment by hpvd** [comment]
@Jennifer88huang 
Many thanks for these details  and work!
4 -> sounds perfect!
