### ISSUE TITLE
advertisedListener should have advertisedPort as well

### ISSUE THREAD

**Issue by abhilashmandaliya** [apache/pulsar#8694]
**Is your enhancement request related to a problem? Please describe.**
From pulsar 2.6.x, you guys have introduced `advertisedListeners` which is a useful feature. But the problem with that is, it uses the broker/web port underneath which is a problem. Let's say I have 2 containers running pulsar broker and they have the same public IP because they are on the same physical host (e.g. IP 192.168.201.202). So both of them tries to create health check topic with 8080 ports and it fails. Both of them forms the address 192.168.201.202:8080 and of course, it's not possible to serve two nodes on the same port on the same machine. 

**Describe the solution you'd like**
There should be an option to advertise ports separately. Maybe 4 separate ports(advertisedBrokerPort, advertisedBrokerPortTls, webServicePort, webServicePortTls) from where the outside world can connect.

**Describe alternatives you've considered**
My colleague and I had created an end-to-end solution for this where we exposed all 4 ports I mentioned above at https://github.com/ashishshinde/pulsar/tree/advertised-ports-master-rebase. While raising a PR, I found that you guys have already worked halfway by creating advertisedListeners. The advertisedListeners is anyways not documented on the main site so we can also think of our alternative.

**Comment by codelipenghui** [comment]
@abhilashmandaliya I think the advertisedListeners does not works for webservice. Could you please send a PIP to the dev mail thread? So that we can have a discussion with the new feature( advertise ports separately) as well.

**Comment by codelipenghui** [comment]
@Huanli-Meng @Jennifer88huang I think we can add a document for the `advertisedListeners`. You can find some details about the advertisedListeners at https://github.com/apache/pulsar/wiki/PIP-61%3A-Advertised-multiple-addresses. If you have any problems you can ping me.

**Comment by abhilashmandaliya** [comment]
> @abhilashmandaliya I think the advertisedListeners does not works for webservice. Could you please send a PIP to the dev mail thread? So that we can have a discussion with the new feature( advertise ports separately) as well.

@codelipenghui  how can I generate PIP?

**Comment by codelipenghui** [comment]
@abhilashmandaliya You can draft a PIP with google doc? and send it to the dev@pulsar.apache.org mail list so that we can discuss the new feature there.

**Comment by abhilashmandaliya** [comment]
> @abhilashmandaliya You can draft a PIP with google doc? and send it to the [dev@pulsar.apache.org](mailto:dev@pulsar.apache.org) mail list so that we can discuss the new feature there.

it is here @codelipenghui https://docs.google.com/document/d/1YelHBuFAAYkmRNWzhVg4j39-VovGb9Ng2_Vg6zbCqGM/edit?usp=sharing

**Comment by Anonymitaet** [comment]
I've removed the `doc-required` label since @Huanli-Meng has added the doc.

**Comment by lhotari** [comment]
resolved by #25851
