### ISSUE TITLE
Http 409 Conflict when running two brokers

### ISSUE THREAD

**Issue by abhilashmandaliya** [apache/pulsar#8699]
**Describe the bug**
Pulsar throws "HTTP 409 Conflict: Subscription already exists for topic" when you launch 2 brokers. Sometimes it fails with "Failed to fence subscription" as well. And sometimes weird 500 internal server error. I handled it by putting this line in try-catch: https://github.com/apache/pulsar/blob/master/pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerService.java#L185
```java
brokerAdmin.topics().createSubscription(coordinationTopic, MembershipManager.COORDINATION_TOPIC_SUBSCRIPTION, MessageId.earliest);
```
**To Reproduce**
Steps to reproduce the behaviour:
1. Launch 1 zookeeper, 2 bookkeeper and 2 pulsar containers on docker. My test environment is distributed among 3 physical hosts so the container can land anywhere. Easily reproducible on the non-dockerized environment as well.

**Expected behaviour**
Should start successfully without any error.

**System info**
1. Zookeeper: 3.6.1
2. Bookkeeper: 4.10.0
3. Pulsar: 2.6.2
4. OS: ubuntu18.04

**Comment by sijie** [comment]
@abhilashmandaliya Are you interested in contributing a fix?

**Comment by abhilashmandaliya** [comment]
yes but I am not sure where to fix this. will need some guidance from you people

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
