### ISSUE TITLE
push websocket

### ISSUE THREAD

**Issue by hpvd** [apache/pulsar#8701]
extracted from: https://github.com/apache/pulsar/issues/2678#issuecomment-733220888

**Is your feature request related to a problem? Please describe.**
imho websocket is for pulsar something like "the window to the realtime website world". It enables universal usage of pulsar for fields like web-tracking, live chat and many more...
If one see the potential of this community, one should give websocket bugs and feature-requests a fair (a reasonable amount of) priority in the next releases
While writing this there are roughly 25 issues open regarding websocket topics.
https://github.com/apache/pulsar/issues?q=is%3Aissue+is%3Aopen+websocket+
3 includes open pull request which may be easy to close (not checked in detail)

**Describe the solution you'd like**
Of course recourses are limited and not all fields have the same importance for adoption of pulsar.
But at least the points
- docs e.g. https://github.com/apache/pulsar/issues/8610, https://github.com/apache/pulsar/issues/8688
- security e.g. https://github.com/apache/pulsar/issues/3493
- performance e.g. https://github.com/apache/pulsar/issues/8584, https://github.com/apache/pulsar/issues/5979

are important for everyone thinking about using pulsar with websocket..

With this said I would vote for the mid-term goal already named 2018 in https://github.com/apache/pulsar/issues/2678 "websocket feature parity" (as far as technical possible..)

**Comment by codelipenghui** [comment]
Hi @hpvd, I think the community didn’t give unfair treatment to the WebSocket Client. If you want that problem to be solved first? you can left a comment on the issue or create a new issue if there is no issue to track the problem.  Also, If you are interested in fixing the WebSocket client related issue, feel free to push a PR and we will review it and merge it as soon as possible.

**Comment by hpvd** [comment]
Hi @codelipenghui,
sorry the word "fair" was not meant as opposite to unfair - of course nothing is unfair here. It is just about a "fair amount of.." which should mean "a reasonable amount" regarding the importance it may have for the adoption of pulsar in the field of websites.
Since i'm not an advanced developer but working in the field of technology prescreening, i'm sadly not able to push a qualified pull request, but like to give some non-code but possibly (hopefully) also helpful input to this awesome project from strategic pov.

**Comment by codelipenghui** [comment]
It does not matter, I will mark some of them that you have mentioned in 2.7.1 release. So that we can push forward the issue fixes for websocket client.

**Comment by codelipenghui** [comment]
I think most of issues that #3493 are been fixed. @hpvd Could you please help double-check?

**Comment by hpvd** [comment]
@codelipenghui of course one can check this versions manually but what do you think of making it an automated routine before every release?

what would help (if not already used):

1. enabling githubs alerts for vulnerable dependencies for pulsar see https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/about-alerts-for-vulnerable-dependencies

-> if possible a bot automatically should open an issue to fix these findings

2. since possible not all vulnerables are reported/found it may also be a idea  having a table of dependencies:
   - row 1: name of of dependency
   - row 2: versions of dependencies used in latest pulsar release e.g. see https://frontbackend.com/maven/artifact/org.apache.pulsar/pulsar/2.6.2
   - row 3: latest version of dependency available ( if hosted at github: acessible with github api)

-> before every release one should look at this table and update all (most) depencies to their latest version (or note a hint why this is not possible at this time (e.g. incomaptible changes)
-> of one could automate open update issues as well, but there these may be to frequent...
