### ISSUE TITLE
protobuf compile error

### ISSUE THREAD

**Issue by holmes07** [apache/pulsar#8718]
**Describe the bug**
1. add one option fileds at proto file 
2. rebuild it by exe :  /d/dev/protobuf-2.4.1/protoc --java_out=src/main/java src/main/proto/PulsarApi.proto

but found error like this ,some method are removed( herer is recycle() )
![企业微信截图_16063763149492](https://user-images.githubusercontent.com/5210343/100321363-88021000-2ffd-11eb-941e-27510819b62c.png)

so which version protobuf should i use ??? 
Is anything wrong with 2.4.1 version any ？

**Comment by holmes07** [comment]
It doesn't work even according to the document protobuf/readme.md . Can anyone provide a working solution？

**Comment by sijie** [comment]
@holmes07 

Please use this following command. It is documented in the README.

```
cd ${PULSAR_HOME}/pulsar-common/
./generate_protobuf_docker.sh
```

---

@Jennifer88huang We might consider update the protobuf/readme.md file to make it clear.

**Comment by holmes07** [comment]
> @holmes07
> 
> Please use this following command. It is documented in the README.
> 
> ```
> cd ${PULSAR_HOME}/pulsar-common/
> ./generate_protobuf_docker.sh
> ```
> 
> @Jennifer88huang We might consider update the protobuf/readme.md file to make it clear.

got it . i will try it later.  thanks ~
