### ISSUE TITLE
Pulsar containers should not run as the root user

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#8751]
**Is your enhancement request related to a problem? Please describe.**
The image produced by pulsar unnecessarily runs as the root user. My company requires applications to run with the least privilege necessary, and the current pulsar docker images do not comply with that policy.

**Describe the solution you'd like**
Given that pulsar only needs privileges to read/write from/to certain directories, the [Dockerfile](https://github.com/apache/pulsar/blob/master/docker/pulsar/Dockerfile) should add a user with the appropriate level of permission, `chown` the appropriate directories, and then run as that user.

**Describe alternatives you've considered**
I don't see an alternative--Pulsar does not _need_ root privileges.

**Additional context**
Note that I want to deploy pulsar on a kubernetes cluster that has a pod security policy that prevents applications from running as root. Given that it is a good security principal to give applications the least permission possible, I see this enhancement as a way to make pulsar more secure and more easy to adopt for other organizations.

**Comment by hpvd** [comment]
related to https://github.com/apache/pulsar/issues/7210

**Comment by frankjkelly** [comment]
@sijie Although originally closed due to this PR https://github.com/apache/pulsar/pull/8796 however this PR appears to have reverted it https://github.com/apache/pulsar/pull/10861 - should the issue be reopened or is there an equivalent issue that covers this request?

**Comment by michaeljmarshall** [comment]
@frankjkelly - I don't know of any equivalent issue. I will open a new issue today with details for what needs to happen in order to get this feature added. Based on a recent pulsar community meeting, there is a desire for more integration testing before merging this change. I plan to help contribute this feature, but I don't expect to be able to work on it for a couple of weeks.

**Comment by frankjkelly** [comment]
@michaeljmarshall thanks - that sounds good

**Comment by michaeljmarshall** [comment]
@frankjkelly - here is the new issue: https://github.com/apache/pulsar/issues/11269.
