### ISSUE TITLE
Mac OSX pulsar-client python wheels missing for 2.6.2

### ISSUE THREAD

**Issue by sp-davidpichler** [apache/pulsar#8753]
**Describe the bug**
The wheels for macosx seem to be missing on the latest release of pulsar: https://pypi.org/project/pulsar-client/#files. The osx wheels are present for https://pypi.org/project/pulsar-client/2.6.1/#files

**To Reproduce**
1. Be on Mac OSX 10.14.6 and python==3.7
2. Run `pip install pulsar-client==2.6.2`

**Expected behavior**
The python client should install

**Comment by sijie** [comment]
@jiazhai @codelipenghui Can you check this issue?

**Comment by zbentley** [comment]
Suggest closing this issue as it is very old and macosx wheels are published more reliably now.
