### ISSUE TITLE
[Function] Support cluster location for input/output topic in Pulsar for different lanaguages

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#8754]
We support cluster location for input/output topic in Java functions (apache/pulsar#8320). We need to provide the same functionality for other languages.

- [ ] Python
- [ ] Go

**Comment by freeznet** [comment]
Golang function can be traced with issue #9012

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
