### ISSUE TITLE
[Go functions]: Spurious single-quotes added to user-conf

### ISSUE THREAD

**Issue by flowchartsman** [apache/pulsar#8757]
**Describe the bug**
When go functions are run with `--user-conf` they fail because single quotes are getting added to the argument when they're not needed.

**To Reproduce**
`pulsar-admin functions create --name test --namespace default --go <path to pfunc binary> --inputs test --output test.o
ut --user-config '{"foo":"bar"}'`

**Expected behavior**
Pulsar function starts

**Additional context**
The offending line is located in `pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java`:

```java
args.add("'" + configContent + "'");
```

Should be:

```java
args.add(configContent);
```

**Comment by flowchartsman** [comment]
cc @vaihtovirta

**Comment by flowchartsman** [comment]
ref: #8216

**Comment by wolfstudy** [comment]
Thanks @flowchartsman feedback, `single-quotes` may be more used for JSON parsing, so we need to confirm whether the string JSON to be parsed is correct?

@freeznet When you implemented the corresponding function, did you encounter the problem of json parsing error, so you added the following code?

```
args.add("'" + configContent + "'");
```
