### ISSUE TITLE
DeadLetterPolicy, If allowAutoTopicCreation enabled in broker, The number of automatically created DLQ topic partitions is not correct

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#8778]
**Describe the bug**
Comsuer code：
            Consumer<String> consumer = getClient().newConsumer(Schema.STRING)
                    .topic("persistent://public/default/test-string8")
                    .subscriptionType(SubscriptionType.Shared)
                    .subscriptionName("my-subscription32")
                    .deadLetterPolicy(DeadLetterPolicy.builder()
                            .maxRedeliverCount(3)
                            .build())
                    .subscribe();

Topic  persistent://public/default/test-string8 has 3 partitions，however, the DLQ topics created automatically are as follows:
![image](https://user-images.githubusercontent.com/54351417/100838868-339fda00-34ae-11eb-951d-78794eaf48a6.png)

My question is, what I set up in the broker is the automatically created non partition topic. Why are there partitions here, and the number of partitions does not look right.

**Comment by WJL3333** [comment]
i think this maybe partition-1 do not have any messages to publish to DLQ. if it has one message, the DLQ topic will be auto create when republish

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.

Now, you can ask questions in https://github.com/apache/pulsar/discussions/categories/q-a instead, since we almost use issues to track actionable tasks.
