### ISSUE TITLE
Add setter for the reader subscription name

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#8787]
In the current reader, we set the subscription name combine with a random part. 
e.g. in java impl:
```
        String subscription = "reader-" + DigestUtils.sha1Hex(UUID.randomUUID().toString()).substring(0, 10);
        if (StringUtils.isNotBlank(readerConfiguration.getSubscriptionRolePrefix())) {
            subscription = readerConfiguration.getSubscriptionRolePrefix() + "-" + subscription;
        }
```

This is OK for most of the case, but some times user may want to track the stats of the reader(e.g. by prometheus), and want to have a way to set the reader to a fixed name to make it easy to track.

It would be helpful to provide a way to set the internal subscription name for reader.

**Comment by aloyszhang** [comment]
Currently, we can set the readername by 
```java
 public ReaderBuilder<T> readerName(String readerName) {
        conf.setReaderName(readerName);
        return this;
    }
```
But  `readerName` is used for setting  consuemrName (not subscription name) for the internal subscription 
```java
if (readerConfiguration.getReaderName() != null) {
            consumerConfiguration.setConsumerName(readerConfiguration.getReaderName());
        }
```
I think we can set the subscription name  by : 
1. if we set the `readerName`, we can set the subcription name to `readerName`
2. if not set the `readerName`, we use the origin logic which is  ”reader-“ or "multiTopicsReader-"  combine with a random part.

**Comment by 315157973** [comment]
If we want to customize the settings of `conusmerName` and `subName` separately, this way cannot be done. So is it better to add a `subName`?

**Comment by aloyszhang** [comment]
It's better to have two seperate setting for `subName` and `consumerName` if we want to distinguish different consumers in a same subscription.  Actually, internal subscription of reader is EXCLUSIVE type,  maybe it's not necessary to distinguish consumers. 
What I'm considering is that if we have all of  `readerName`, `subscriptionName` and `consumerName`, it's will bring some complexity for understanding.
