### ISSUE TITLE
[Python] Publish python clients for macOS Big Sur

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#8794]
Big Sur was released a couple of weeks ago. We should be looking into publishing python clients for macOS Big Sur users.

**Comment by freeznet** [comment]
currently there is no big sur vagrant box available to use [both matching big sur and virtualbox], so we should create vagrant box like `apachepulsar/osx-10.14-python-dev` for big sur first, then build and publish big sur release.

or we should look into issue #3485 to improve the build process, get rid of vagrant way.

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Python client has been permanently moved to https://github.com/apache/pulsar-client-python. If it's still relevant, please open an issue there.
