### ISSUE TITLE
pulsar_ env.sh add different JVM options for different components

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#8797]
**Is your feature request related to a problem? Please describe.**
Multiple components of pulsar are deployed on a machine, and all components share a pulsar when they are PULSAR_MEM environment variable. If the JVM memory settings of each component are different, you can either export PULSAR_MEM when starting different components, or modify PULSAR_MEM in pulsar_env.sh, Each component can be provided with its own JVM variables, so in pulsar_env.sh you only need to modify all the required JVMs of all components once.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
