### ISSUE TITLE
Docker is deprecated in Kubernetes -> identify need for action

### ISSUE THREAD

**Issue by hpvd** [apache/pulsar#8811]
**Is your feature request related to a problem? Please describe.**
Docker is **now deprecated** in Kubernetes.
By the **end of 2021** "dockershim" which implements CRI support for Docker will be **removed.**

> Reason: Why is dockershim being deprecated?
> Maintaining dockershim has become a heavy burden on the Kubernetes maintainers. The CRI standard was created to reduce this burden and allow smooth interoperability of different container runtimes. Docker itself doesn't currently implement CRI, thus the problem.

see:
https://dev.to/inductor/wait-docker-is-deprecated-in-kubernetes-now-what-do-i-do-e4m
https://kubernetes.io/blog/2020/12/02/dockershim-faq/

**Describe the solution you'd like**
Directly support other container technologies for keeping setup of pulsar as easy as possible.
One alternative to look at is probably "containerd" https://github.com/containerd/containerd
which has already a good adoption https://github.com/containerd/containerd/blob/master/ADOPTERS.md

**Comment by hpvd** [comment]
good summarizing thread (with 10 parts): https://twitter.com/Dixie3Flatline/status/1334188913724850177

**Comment by cdbartholomew** [comment]
From Kubernetes web site:

"Docker as an underlying runtime is being deprecated in favor of runtimes that use the Container Runtime Interface(CRI) created for Kubernetes. **Docker-produced images will continue to work in your cluster with all runtimes, as they always have.**"
https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/ (edited) 

Kubernetes
Don't Panic: Kubernetes and Docker
Authors: Jorge Castro, Duffie Cooley, Kat Cosgrove, Justin Garrison, Noah Kantrowitz, Bob Killen, Rey Lejano, Dan “POP” Papandrea, Jeffrey Sica, Davanum “Dims” Srinivas Kubernetes is deprecating Docker as a container runtime after v1.20. You do not need to panic. It’s not as dramatic as it sounds. tl;dr Docker as an underlying runtime is being deprecated in favor of runtimes that use the Container Runtime Interface(CRI) created for Kubernetes. Docker-produced images will continue to work in your cluster with all runtimes, as they always have.

**Comment by hpvd** [comment]
yes, one have to look at this topic in detail when docker is not supported anymore:

> There are a few instances when you might have a dependency on Docker: running privileged Pods executing Docker commands, running scripts on nodes outside of Kubernetes infrastructure (for example, using ssh to troubleshoot issues), or through third-party tools that perform such similarly privileged operations. You might also have an indirect dependency on Docker if some of your tooling was configured to react to Docker-specific log messages in your monitoring system

this and some other interesting stuff in the following paragraph can be found here:
https://cloud.google.com/kubernetes-engine/docs/concepts/using-containerd

**Comment by hpvd** [comment]
so it's about looking at the
- dev-
- build- and
- operation processes
to identify "the need for action" resulting from this topic.

**Comment by sijie** [comment]
@hpvd thank you for bringing this up.
