### ISSUE TITLE
advertisedAddress question

### ISSUE THREAD

**Issue by holmes07** [apache/pulsar#8812]
is a broker can supports both internal and external network ip ?  
i want to  run one cluster support diff network env, is there any solutions？

**Comment by sijie** [comment]
@Jennifer88huang @Huanli-Meng Can you point @holmes07 the documentation about that? If we don't have that, can you work on providing the documentation?

**Comment by Huanli-Meng** [comment]
@holmes07 , you can check this document: https://pulsar.apache.org/docs/en/next/concepts-multiple-advertised-listeners/. If there are more info required, please reach out to us. Thanks.

**Comment by Anonymitaet** [comment]
@holmes07 does the [doc](https://pulsar.apache.org/docs/en/next/concepts-multiple-advertised-listeners/) solve your problem? If yes, we can close this issue.

**Comment by holmes07** [comment]
> @holmes07 does the [doc](https://pulsar.apache.org/docs/en/next/concepts-multiple-advertised-listeners/) solve your problem? If yes, we can close this issue.

yeah
