### ISSUE TITLE
Support  Pulsar Python client for windows 10

### ISSUE THREAD

**Issue by astream2018** [apache/pulsar#8830]
Currently i'm trying to use Python (3.7, 3.8) client for windows 10.
This seems not to work. 
On the Pulsar side the 2 supported platforms are also Linux and MacOs.

As most of the companies laptop are operating on Windows (10). 
It would be a big plus to also make the client work on Windows 10 laptops.

**Comment by tisonkun** [comment]
Closed as stale.

The development of the Python client has been permanently moved to https://github.com/apache/pulsar-client-python. If it's still relevant, please open an issue there.
