### ISSUE TITLE
Failed to start Pulsar in stand alone mode

### ISSUE THREAD

**Issue by moutasemalakkad** [apache/pulsar#8833]
#### Expected behavior
Pulsar Standalone should start using command: bin/pulsar standalone

#### Actual behavior

Error: Could not find or load main class org.apache.pulsar.PulsarStandaloneStarter
Caused by: java.lang.ClassNotFoundException: org.apache.pulsar.PulsarStandaloneStarter

#### System configuration
**Pulsar version**: 2.7.0

**Comment by sijie** [comment]
@moutasemalakkad Can you describe how did you start it? It would be super helpful if you can include detailed steps.

**Comment by moutasemalakkad** [comment]
It worked fine when I downloaded Pulsar from Apache.
