### ISSUE TITLE
Does topic policy plans to be required feature

### ISSUE THREAD

**Issue by Shoothzj** [apache/pulsar#8838]
In future, does topic policy plans to be required feature ? Or an optional feature.

**Comment by codelipenghui** [comment]
@Shoothzj It's an optional feature, please provide more details that you met. Thanks.

**Comment by Shoothzj** [comment]
Well, during running, there are logs like this:
![image](https://user-images.githubusercontent.com/12933197/101422633-12b60980-3932-11eb-9551-c2fb67757a91.png)
I think it induces me to enable it.
I update broker version to 2.7.0, is there any migration must do ?

**Comment by Shoothzj** [comment]
@codelipenghui
