### ISSUE TITLE
Enable spotbugs for pulsar-io module

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar#8843]
**Is your enhancement request related to a problem? Please describe.**

- [x] aerospike(https://github.com/apache/pulsar/pull/8842)
- [x] aws(https://github.com/apache/pulsar/pull/8842)
- [ ] core
- [x] batch-discovery-triggerers(#8889)
- [x] batch-data-generator(#8889 )
- [ ] common
- [ ] docs
- [ ] twitter
- [ ] cassandra
- [ ] kafka
- [ ] rabbitmq
- [ ] kinesis
- [ ] hdfs3
- [ ] jdbc
- [ ] jdbc/core
- [ ] data-generator
- [ ] elastic-search
- [ ] kafka-connect-adaptor
- [ ] debezium
- [ ] debezium/core
- [ ] hdfs2
- [ ] canal
- [ ] file
- [x] netty(#8863 )
- [ ] hbase
- [ ] mongo
- [ ] flume
- [ ] redis
- [ ] solr
- [ ] influxdb
- [ ] dynamodb
- [ ] nsq

**Describe the solution you'd like**
This issue is used to keep track of the spotbugs(https://spotbugs.github.io/) enabled for the pulsar-io module, if you are interested, you can create a pr, here is an example https://github.com/apache/pulsar/pull/8842. 

Test, `mvn clean install -pl pulsar-io/module-name`, for example:

```
mvn clean install -pl pulsar-io/aerospike
mvn clean install -pl pulsar-io/aws
```

**Describe alternatives you've considered**

**Additional context**

**Comment by nlu90** [comment]
I can help with this issue.

**Comment by tisonkun** [comment]
Closed as stale. It's good to continue, but we need to investigate what the remaining packages are processed.
