### ISSUE TITLE
[website] The REST API links in the doc body do not work now

### ISSUE THREAD

**Issue by Jennifer88huang-zz** [apache/pulsar#8853]
**Describe the bug**
When I click the REST API links in the doc body, they do not work properly at the moment. The following two links are just examples.

**To Reproduce**
1. Go to http://pulsar.apache.org/docs/en/admin-api-topics/#list-of-topics
2. Click the link in the REST API tabs.
3. They navigates to a blank page.  Shown as follows:
![image](https://user-images.githubusercontent.com/47805623/101361289-bde6a480-38d9-11eb-8283-a9ac21948dd6.png)

**Expected behavior**
It should navigate to https://pulsar.incubator.apache.org/admin-rest-api/?version=2.7.0&apiversion=v2

**Desktop (please complete the following information):**
 - OS: [ iOS]

**Additional context**
If I click "Admin Rest API" header directly, it works https://pulsar.incubator.apache.org/admin-rest-api/?version=2.7.0&apiversion=v2
![image](https://user-images.githubusercontent.com/47805623/101361432-ea9abc00-38d9-11eb-8229-bd6a2ddc3993.png)

**Comment by Anonymitaet** [comment]
This issue has been resolved. @signormercurio thanks for your reminder!
