### ISSUE TITLE
[website] Search on website not working

### ISSUE THREAD

**Issue by hpvd** [apache/pulsar#8864]
**Describe the bug**
Search on website not working

**To Reproduce**
1. Go to https://pulsar.apache.org/docs/en/standalone/
2. Put something into search field 
3. press enter 
4. nothing happens

**Expected behavior**
search results show up

**Desktop (please complete the following information):**
 - tested with the latest Firefox and Edge

**Comment by Jennifer88huang** [comment]
@hpvd Thanks for raising the issue. There is sth wrong with the search engine, we've tried to fix it in https://github.com/algolia/docsearch-configs/pull/3005
It takes effect 24 hours after that PR merge. Let's wait and check it tonight.

**Comment by Jennifer88huang** [comment]
It does not work well, try to re-open the issue in https://github.com/algolia/docsearch-configs/issues/2994
@hpvd if you need to search some content, use the `next` version http://pulsar.apache.org/docs/en/next/standalone/

**Comment by Jennifer88huang** [comment]
@hpvd it works well now. You can have a try, and I'll close this issue if you agree.

**Comment by hpvd** [comment]
@Jennifer88huang 
yes! with great fast and grouped search suggest :-) many thanks.
closing...

**Comment by Jennifer88huang** [comment]
Thank you~
