### ISSUE TITLE
[docs] REST API issues

### ISSUE THREAD

**Issue by Jennifer88huang-zz** [apache/pulsar#8868]
**Describe the bug**
There are sth wrong with the REST APIs.

**To Reproduce**
1. Go to https://pulsar.apache.org/docs/en/admin-api-functions/
2. Check the REST API tabs, and found they do not work.

**Expected behavior**
It should be displayed as link format, and the link navigates to the REST API pages.

**Screenshots**

![image](https://user-images.githubusercontent.com/47805623/101569178-efad5780-3a0e-11eb-82ea-8f8a53d12874.png)

**Desktop (please complete the following information):**
 - OS: [ iOS]

**Comment by Jennifer88huang** [comment]
Related to https://github.com/apache/pulsar/issues/8853

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
