### ISSUE TITLE
After upgrade pulsar client version to 2.6.2,  getting the Null pointer exception while publishing a message 

### ISSUE THREAD

**Issue by dlsprague** [apache/pulsar#8884]
User upgraded pulsar java client to 2.6.2 due to security vulnerabilities found in lower versions.  Was able to produce messages fine in 2.5.0 and 2.6.0, but after upgrade getting following error:
```
[2020-12-08 09:43:28.837] [AlarmCreate][org.apache.pulsar.client.impl.ProducerImpl] WARN - [persistent://i18v/fault-alarmupdate/Apollo-Fault-AlarmUpdate-1sec-partition-0] [xxx-aws-us-xxxx-1-101050-61003] error while create opSendMsg by batch message container
java.lang.NullPointerException: null
at org.apache.pulsar.shade.io.netty.util.Recycler.recycle(Recycler.java:180) ~[pulsar-client-2.6.2.jar:2.6.2]
at org.apache.pulsar.common.api.proto.PulsarApi$MessageMetadata$Builder.recycle(PulsarApi.java:4571) ~[pulsar-client-2.6.2.jar:2.6.2]
at org.apache.pulsar.client.impl.BatchMessageContainerImpl.getCompressedBatchMetadataAndPayload(BatchMessageContainerImpl.java:121) ~[pulsar-client-2.6.2.jar:2.6.2]
at org.apache.pulsar.client.impl.BatchMessageContainerImpl.createOpSendMsg(BatchMessageContainerImpl.java:176) ~[pulsar-client-2.6.2.jar:2.6.2]
at org.apache.pulsar.client.impl.ProducerImpl.batchMessageAndSend(ProducerImpl.java:1565) [pulsar-client-2.6.2.jar:2.6.2]
at org.apache.pulsar.client.impl.ProducerImpl.access$500(ProducerImpl.java:89) [pulsar-client-2.6.2.jar:2.6.2]
at org.apache.pulsar.client.impl.ProducerImpl$2.run(ProducerImpl.java:1524) [pulsar-client-2.6.2.jar:2.6.2]
at org.apache.pulsar.shade.io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) [pulsar-client-2.6.2.jar:2.6.2]
at org.apache.pulsar.shade.io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) [pulsar-client-2.6.2.jar:2.6.2]
at org.apache.pulsar.shade.io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) [pulsar-client-2.6.2.jar:2.6.2]
at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [pulsar-client-2.6.2.jar:2.6.2]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```
Error seems to suggest message size over limit but have sent very small messages for testing and still fails. 

Pulsar broker is at version 2.6.0.  Could this be a compatibility issue with client at a higher version?

**Comment by 315157973** [comment]
I will see what the problem is

**Comment by 315157973** [comment]
Hello, could you provide more information?
Such as your producer creation parameters、 How does the producer send the message?

I use the latest broker and 2.6.2 client locally, and this problem cannot be reproduced temporarily.
It does not seem to be caused by the message size limit.
When the message size limit is exceeded, the producer of 2.6.2 cannot successfully produce until it times out. The 2.7.0 producer will throw an exception.
@dlsprague

**Comment by dlsprague** [comment]
Here is how producer sends message. 
package com.vz.apollo.alarmdbupdates;
​
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Map;
​
import org.apache.pulsar.client.api.CryptoKeyReader;
import org.apache.pulsar.client.api.EncryptionKeyInfo;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
​
public class RawFileKeyReader implements CryptoKeyReader {
	protected final Logger logger = LoggerFactory.getLogger(this.getClass());
	String publicKeyFile = "";
	String privateKeyFile = "";
	
	public RawFileKeyReader(String pubKeyFile, String privKeyFile) {
		publicKeyFile = pubKeyFile;
		privateKeyFile = privKeyFile;
	}
​
	@Override
	public EncryptionKeyInfo getPublicKey(String keyName, Map<String, String> keyMeta) {
		EncryptionKeyInfo keyInfo = new EncryptionKeyInfo();
		try {
			keyInfo.setKey(Files.readAllBytes(Paths.get(publicKeyFile)));                
		} catch (IOException e) {
			logger.info("ERROR: Failed to read public key from file " + publicKeyFile);
			e.printStackTrace();
		}
		return keyInfo;
	}
​
	@Override
	public EncryptionKeyInfo getPrivateKey(String keyName, Map<String, String> keyMeta) {
		EncryptionKeyInfo keyInfo = new EncryptionKeyInfo();
		try {
			keyInfo.setKey(Files.readAllBytes(Paths.get(privateKeyFile)));
		} catch (IOException e) {
			logger.info("ERROR: Failed to read private key from file " + privateKeyFile);
			e.printStackTrace();
		}
		return keyInfo;
	}
}


_producer_java_client = pulsarClient.newProducer().topic(_topic_java_client).batchingMaxPublishDelay(3, TimeUnit.MILLISECONDS)
    				.cryptoKeyReader(new RawFileKeyReader(publicKey,privateKey))
    				.addEncryptionKey(publicKey)
    				.sendTimeout(10, TimeUnit.SECONDS).blockIfQueueFull(true)
    				.create();
above is the code used for encryption of the messages

**Comment by dlsprague** [comment]
Looking for the rest of the info requested.  User did attempt to use client 2.7.0 but got same exception.

**Comment by dlsprague** [comment]
Also some additional info as I tried to produce a message.  (it failed because I wasnt using encryptiom).  Thought maybe some of these settings would help.
11:08:11.281 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ProducerStatsRecorderImpl - Starting Pulsar producer perf with config: {
  "topicName" : "persistent://i18v/fault-alarmupdate/Apollo-Fault-AlarmUpdate-1sec-partition-0",
  "producerName" : null,
  "sendTimeoutMs" : 30000,
  "blockIfQueueFull" : false,
  "maxPendingMessages" : 1000,
  "maxPendingMessagesAcrossPartitions" : 50000,
  "messageRoutingMode" : "RoundRobinPartition",
  "hashingScheme" : "JavaStringHash",
  "cryptoFailureAction" : "FAIL",
  "batchingMaxPublishDelayMicros" : 1000,
  "batchingPartitionSwitchFrequencyByPublishDelay" : 10,
  "batchingMaxMessages" : 1000,
  "batchingMaxBytes" : 131072,
  "batchingEnabled" : true,
  "chunkingEnabled" : false,
  "compressionType" : "NONE",
  "initialSequenceId" : null,
  "autoUpdatePartitions" : true,
  "multiSchema" : true,
  "properties" : { }
}
11:08:11.290 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ProducerStatsRecorderImpl - Pulsar client config: {
  "serviceUrl" : "pulsar+ssl://localhost:6651/",
  "authPluginClassName" : null,
  "authParams" : null,
  "authParamMap" : null,
  "operationTimeoutMs" : 30000,
  "statsIntervalSeconds" : 60,
  "numIoThreads" : 1,
  "numListenerThreads" : 1,
  "connectionsPerBroker" : 1,
  "useTcpNoDelay" : true,
  "useTls" : true,
  "tlsTrustCertsFilePath" : "/VMB/apache-pulsar-2.6.0/certs/combined.ca.pem",
  "tlsAllowInsecureConnection" : false,
  "tlsHostnameVerificationEnable" : false,
  "concurrentLookupRequest" : 5000,
  "maxLookupRequest" : 50000,
  "maxLookupRedirects" : 20,
  "maxNumberOfRejectedRequestPerConnection" : 50,
  "keepAliveIntervalSeconds" : 30,
  "connectionTimeoutMs" : 10000,
  "requestTimeoutMs" : 60000,
  "initialBackoffIntervalNanos" : 100000000,
  "maxBackoffIntervalNanos" : 60000000000,
  "listenerName" : null,
  "useKeyStoreTls" : false,
  "sslProvider" : null,
  "tlsTrustStoreType" : "JKS",
  "tlsTrustStorePath" : null,
  "tlsTrustStorePassword" : null,
  "tlsCiphers" : [ ],
  "tlsProtocols" : [ ],
  "proxyServiceUrl" : null,
  "proxyProtocol" : null
}

**Comment by dlsprague** [comment]
The message size limit is set at the broker level.  Because we batch on broker side, we did testing by commenting out .bathcingMaxPublishDelay(3, TimeUnit.MILLISECONDS) but it still gave message  error while create opSendMsg by batch message container.  It was clarified that this is also occurring in 2.5.2, 2.6.0, 2.6.2 and 2.7.0.  Problem does not occur in 2.5.0.  User is encrypting and batching, but as mentioned, stopped batching on client side for testing and it still produced error.

**Comment by dlsprague** [comment]
Is there something else we can do to test?    We attempted to turn off the batching on client producer since batching is done on broker side thinking that would help, but we still got same message.  Is there something else we should try.  Will be furloughed the 2 last weeks of December, hoping to try something before then.  Thanks so much!

**Comment by 315157973** [comment]
Sorry, I did not reply in time. I still cannot reproduce. Now there are too many factors. I am not sure which one is different from what you set: encryption, message size, client version, etc.
Can you try to turn off some factors, such as: turn off the message size limit, will it appear? Turn off encryption, will it appear?
Or, provide a piece of code that can definitely be reproduced?

**Comment by dlsprague** [comment]
HI a test was performed on a topic not using encryption and it was successful.  Adding encrpytion and it failed.  I am asking developer for code that is failing to provide.  

Thank you

**Comment by klevy-toast** [comment]
Hey @dlsprague! My team was seeing an identical issue when using client version 2.5.2, where sending a message would trigger that stacktrace regardless of what or how we sent it. We think that it was due to some weird transitive dependencies, where the project was using `org.apache.pulsar:pulsar-client-original:2.5.2`, but was also pulling in a transitive dependency that used `org.apache.pulsar:pulsar-client:2.4.0`. By upgrading the transitive dependency so that they were both using the `client-original:2.5.2` package, the error went away. Hopefully your project has a similar issue and can benefit from a similar fix.

We've definitely had a lot of headaches due to mismatched dependencies..

**Comment by dlsprague** [comment]
Hi Thank you very much..  Yes, I will pass that information on and see if
it helps..   I appreciate it!

**Comment by dlsprague** [comment]
Attaching the sample failing code for further review.  
[Downloads.zip](https://github.com/apache/pulsar/files/5711477/Downloads.zip)

**Comment by dlsprague** [comment]
developer says snakeyaml 1.2.4 dependency is causing a twist lock.  Unfortunately he is not able to upgrade that individually or change that manually.    How are you able to upgrade the dependencies embedded in client?

![image (3)](https://user-images.githubusercontent.com/75750837/102547165-c633a200-4086-11eb-8b85-68eced333b04.png)

**Comment by 315157973** [comment]
I used the complete code you provided, and the certificate used the one used in org.apache.pulsar.client.TlsProducerConsumerTest. The unit test passed normally.

https://github.com/315157973/pulsar/blob/67eb4b81b554b94fb3b51b0a96acd50d7bacceb9/bouncy-castle/bcfips-include-test/src/test/java/org/apache/pulsar/client/TlsProducerConsumerTest.java#L147

**Comment by dlsprague** [comment]
We turned off encryption on the topics namespace and connecting and producing was then successful.   so problem with the upgrade specific to encryption in our case.

**Comment by dlsprague** [comment]
Can I please request a call concerning this issue?  Just to review, our broker is on 2.6.0, user is attempting to use 2.6.2 to alleviate some security vulnerabilities but with encryption turned on he gets Null pointer exception. Works ok with encryption off.  Looks like same code has been tested above and was successful.  Unsure what we need to do to resolve on our end.    Thank you so much!

**Comment by 315157973** [comment]
> Can I please request a call concerning this issue?  Just to review, our broker is on 2.6.0, user is attempting to use 2.6.2 to alleviate some security vulnerabilities but with encryption turned on he gets Null pointer exception. Works ok with encryption off.  Looks like same code has been tested above and was successful.  Unsure what we need to do to resolve on our end.    Thank you so much!


Tried 2.6.2, 2.6.0, and 2.7.0.  I will add 2.6.x unit tests to my code repository.  It is possible that the encrypted package of the client conflicts with the encrypted package in your business code.  You can try to use the shade version of the client.

**Comment by dlsprague** [comment]
thank you.   Update to the issue: 
It is now successful using a different dependency which is bouncy castle and the connection is working with encryption enabled.  However, there are black duck security vulnerabilities being reported.

Using 2.6.2 client Bouncy castle jar file, an inner jar of pulsar client  has some internal transitive dependencies with 1.6.0 version  of bouncy castle which is causing the HIGH vulnerabilities.

Using 2.7.0  High vulnerability is removed but it has  1 CRITICAL vulnerability with the  new  transitive dependency jar (bcprov-ext-jdk15on-1.66.jar

![image262_1](https://user-images.githubusercontent.com/75750837/103815154-ef65a380-5030-11eb-9590-eafa6ff86d4e.png)
![image262_2](https://user-images.githubusercontent.com/75750837/103815168-f4c2ee00-5030-11eb-9bb7-7457a5c1ea56.png)
![image270_2](https://user-images.githubusercontent.com/75750837/103815175-f68cb180-5030-11eb-8cb6-34a11898dfa7.png)
![image270_1](https://user-images.githubusercontent.com/75750837/103815181-f7bdde80-5030-11eb-8909-6db13251aa45.png)

What can we do to resolve this vulverability?  

Thanks again.

**Comment by sijie** [comment]
@dlsprague Can you create a separate Github issue for the vulnerability issue?

**Comment by dlsprague** [comment]
Opened issue #9151 for security vulnerabilities.
