### ISSUE TITLE
Does tiered storage support aliyun oss?

### ISSUE THREAD

**Issue by yufan022** [apache/pulsar#8887]
**Is your feature request related to a problem? Please describe.**
We're using aliyun oss as storage, How can we use aliyun oss offloader with Pulsar?

**Describe the solution you'd like**
Support aliyun oss tiered storage.

**Comment by sijie** [comment]
@yufan022 Currently aliyun oss is not supported yet. You're welcome to contribute a feature to us.

**Comment by yufan022** [comment]
@sijie 
`Pulsar` use `jclouds`  connect to the cloud provider. 
`jclouds` doesn't support `aliyun oss` yet, How can we do this work?

I advise two options:
1. make `jclouds` support `aliyun oss` before adapting pulsar.
2. maybe pulsar need support customized API or SDK to support more cloud provider?

**Comment by yufan022** [comment]
> @yufan022 Currently aliyun oss is not supported yet. You're welcome to contribute a feature to us.

@sijie I create a pr, can you help me review it?
