### ISSUE TITLE
[Doc] The master branch admin rest api page seems has a issue

### ISSUE THREAD

**Issue by zymap** [apache/pulsar#8891]
There has some request example are not in any of a group.

https://pulsar.apache.org/admin-rest-api/?version=master&apiversion=v2

![Screen Shot 2020-12-10 at 3 55 14 PM](https://user-images.githubusercontent.com/24502569/101737710-362eaf00-3b00-11eb-9b4c-c39b0432bc29.png)

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
