### ISSUE TITLE
browser warning: Website unsecure

### ISSUE THREAD

**Issue by hpvd** [apache/pulsar#8895]
**Describe the bug**
Website https://pulsar.apache.org/en/ is unsecure -> browser warning and parts of website is blocked

reason: mixed content, tencent logo is not loaded using https
see
https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox

**To Reproduce**
1. visit https://pulsar.apache.org/en/
2. see browser warning beside url field (seen in firefox and chrome)

**Expected behavior**
all content loaded using https and no browser warning

**Screenshots**
![2020-12-10_10h14_50](https://user-images.githubusercontent.com/5681880/101752544-f2bd4c00-3ad1-11eb-897b-e86402ff8e59.png)

![2020-12-10_10h14_02](https://user-images.githubusercontent.com/5681880/101752441-ce616f80-3ad1-11eb-99e9-d50b636c350c.png)

**Comment by tisonkun** [comment]
Now Chrome tells me that it's secure when opening https://pulsar.apache.org/.

Closed as not an issue. Feel free to open a new issue if it's still relevant.
