### ISSUE TITLE
retention support per topic

### ISSUE THREAD

**Issue by kemburi** [apache/pulsar#8899]
**Is your enhancement request related to a problem? Please describe.**
We have some complex calculations to be performed on specific topics and those calculations are not finishing within the retention period configured. hence we see data loss. since only on few of the topics we need to these calcuations to be performed we dont want to set retention globally for all topics.

**Describe the solution you'd like**
Need the ability to configure message retention to be configurable per topic to override global setting.
**Describe alternatives you've considered**

**Additional context**

**Comment by kemburi** [comment]
we are using pulsar client 2.6.1

**Comment by sijie** [comment]
@kemburi topic-level policy (including retention settings) are supported in 2.7.0. You can use `bin/pulsar-admin topics` to set topic-level retention. The documentation for topic-level policy is being added by @Jennifer88huang

**Comment by Jennifer88huang** [comment]
@kemburi sorry for my late reply. You can set topic-level retention using `bin/pulsar-admin topics`. 
For details, refer to https://github.com/apache/pulsar/pull/9161

From Pulsar 2.7.0, the namespace level policies are available on topic level. To enable topic level policy in Pulsar, you need to configure the following parameters in the `broker.conf` file. 

```shell
systemTopicEnabled=true
topicLevelPoliciesEnabled=true
```

I've added this configuration in #9108 
Once those PRs are merged, all available topic-level policies are live on our website. Thank you for your patience on it. Any issue, feel free to comment.

**Comment by kemburi** [comment]
thank you, you might close this issue.

**Comment by Jennifer88huang** [comment]
@kemburi thanks for your feedback. We'll close this issue when those two PRs are merged.
