### ISSUE TITLE
Stability test, Jetty hang

### ISSUE THREAD

**Issue by Shoothzj** [apache/pulsar#8902]
**Describe the bug**
My pulsar jetty port sometimes can't response. Frequently.
It's like jetty probleam, looks like the java program don't accept. Many requests are CLOSE_WAIT, and can't server new request.
I can only restart the broker. I try to update the broker to version 2.7.0, nothing works better.

**To Reproduce**
Currently, I don't know how to reproduce the probleam. But with half day time, my environment can reproduce the probleam.

**Expected behavior**
8080 container works well.

**Screenshots**
![image](https://user-images.githubusercontent.com/12933197/101785914-46628080-3b38-11eb-8496-bee5b9cc904c.png)

**Desktop (please complete the following information):**
 - OS: Huawei Euler OS based on Open Euler

**Comment by 315157973** [comment]
Use `tcpdump` to capture a packet so that you can know where the problem is
