### ISSUE TITLE
Add support for specifying subscription type when creating subscription

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#8906]
**Is your feature request related to a problem? Please describe.**
I want to create a subscription with a non default subscription type. As it currently stands, the `pulsar-admin` utility and the even the REST endpoints don't support this functionality.

It appears that the only way to specify the type of subscription is to create it while also creating a consumer. In my use case, I have auto subscription creation turned off, so this isn't an option for me.

**Describe the solution you'd like**
Based on reading through the project, it seems to me that this will need to be added to the `PersistentSubscription` and the `NonPersistentSubscription` classes (defined in `pulsar-broker/src/main/java/org/apache/pulsar/broker/service`) as a variable and then added to their constructors. After that, the changes would naturally propagate through the whole project. It would affect the Pulsar Admin API as well as the clients that call in to the affected endpoints.

This change would be an expansion of the API, so it would be backwards compatible in so far as not specifying the `SubType` would result in the default `SubType`, which already happens today.

**Describe alternatives you've considered**
The only alternative I see is turning on allowing auto creation of subscriptions, but I want to keep that setting off. If there are known alternatives, I'm happy to consider them.

**Comment by merlimat** [comment]
At any point in time, if there are no consumers, a subscription has no specified type.
Eg: you can also "change" the type of subscription by restarting all your consumers with a different configuration.

**Comment by michaeljmarshall** [comment]
> At any point in time, if there are no consumers, a subscription has no specified type.
Eg: you can also "change" the type of subscription by restarting all your consumers with a different configuration.

Thanks for your explanation. That explains why creating a subscription without any consumers doesn't, and shouldn't, allow for a subscription type.

I wasn't able to find documentation on this--maybe I missed it. I'll look again, and if I can't find it, it might be worth adding documentation to describe this behavior.
