### ISSUE TITLE
Giggso logo link error

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar#8909]
**Describe the bug**
The company giggso icon link error

**To Reproduce**
http://pulsar.apache.org/powered-by/
![image](https://user-images.githubusercontent.com/1907867/101848876-80ac3c00-3b91-11eb-81b4-c60577b99c19.png)

**Expected behavior**
Update the giggso logo link in the [user.json](https://github.com/apache/pulsar/blob/master/site2/website/data/users.js#L13) file to https://www.giggso.com/wp-content/uploads/2019/11/logo-2.png

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by reswqa** [comment]
The color of this icon seems to overlap with our background color, making it unrecognizable when placed on it.
<img width="520" alt="WeChat96a8e7a122b2299ce3cf9cedf214739a" src="https://user-images.githubusercontent.com/19502505/101935052-6ae25980-3c19-11eb-839a-28e4b417686f.png">

when i change html body's background color to black, it show like below.
<img width="472" alt="WeChat82408395b73d231c79ef15aec228c822" src="https://user-images.githubusercontent.com/19502505/101934791-07f0c280-3c19-11eb-9066-eec882ff5eb2.png">

**Comment by tuteng** [comment]
thanks, you can try add field `logo_white: true` @reswqa
