### ISSUE TITLE
Compile individual module failed

### ISSUE THREAD

**Issue by hangc0276** [apache/pulsar#8911]
**Describe the bug**
When i compile individual module, it failed as following exceptions
```
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:4.0.rc2:check (default) on project pulsar-client-original: Execution default of goal com.mycila:license-maven-plugin:4.0.rc2:check failed: Cannot read header document src/license-header.txt. Cause: Resource src/license-header.txt not found in file system, classpath or URL: no protocol: src/license-header.txt -> [Help 1]
```
It may be introduced by #8706 

**To Reproduce**
1. In pulsar root directory, run `mvn install -DskipTest`, wait for compile success.
2. go to `pulsar-client` module, run `mvn install -DskipTests`, it will compile failed

**Expected behavior**
For each individual module, It should compile success.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Comment by hangc0276** [comment]
@lhotari Would you please help take a look?

**Comment by sijie** [comment]
@hangc0276 you can try run `mvn -pl pulsar-client install -DskipTests`?

**Comment by hangc0276** [comment]
> @hangc0276 you can try run `mvn -pl pulsar-client install -DskipTests`?

@sijie Ok, run `mvn -pl pulsar-client install -DskipTests` in pulsar root directory, compile succeed. 
However, in the past, run `run install -DskipTests` in sub module directory, it may also compile succeed.
I close this issue.
