### ISSUE TITLE
[Spotbugs] Add spotbugs plugin for Pulsar Functions

### ISSUE THREAD

**Issue by wolfstudy** [apache/pulsar#8915]
The currently supported modules are as follows: 

the https://github.com/apache/pulsar/pull/8851 will track these module

- [x] Instance
- [x] API
- [x] Java Examples
- [x] Localrun
- [x] Runtime All
- [x] Secrets

The currently not supported modules are as follows: 

- [ ] Runtime
- [ ] Utils
- [ ] Worker

**Comment by tisonkun** [comment]
Closed as stale. We can start a new coding program to enable spotbugs plugin.
