### ISSUE TITLE
The Equals of the ClientConfigurationData instance does not reach the expected result

### ISSUE THREAD

**Issue by jianyun8023** [apache/pulsar#8953]
**Is your enhancement request related to a problem? Please describe.**

The authentication in ClientConfigurationData does not implement equals and hashcode, resulting in two instances of the same configuration not being equal.

**Describe the solution you'd like**

Add equals, hashCode methods to all Authentication implementation classes.

**Describe alternatives you've considered**

In ClientConfigurationData in the equals, hashCode method to ignore the field authentication.

**Additional context**

**Comment by jianyun8023** [comment]
@codelipenghui Hi, what do you think is a better solution?

**Comment by reswqa** [comment]
`In ClientConfigurationData in the equals, hashCode method to ignore the field authentication.`
Does it mean that Conf's with different authentication only can be considered the same? In our scenario, this would result in Clients with different authentication policies but otherwise the same attributes being shared by the same cache.

**Comment by jianyun8023** [comment]
> `In ClientConfigurationData in the equals, hashCode method to ignore the field authentication.`
> Does it mean that Conf's with different authentication only can be considered the same? In our scenario, this would result in Clients with different authentication policies but otherwise the same attributes being shared by the same cache.

The ClientConfigurationData stores the parameters for creating the authentication object. Of course, there are also methods to set the authentication object directly.

**Comment by 315157973** [comment]
How about adding `@EqualsAndHashCode` to each implementation class of Authentication?

**Comment by jianyun8023** [comment]
> How about adding `@EqualsAndHashCode` to each implementation class of Authentication?

Most of the situations yes, there are also special cases that need to be dealt with. And corresponding tests need to be added for them.

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
