### ISSUE TITLE
Enable skipping missing/corrupted ledgers from offloaded storage

### ISSUE THREAD

**Issue by milos-matijasevic** [apache/pulsar#8964]
**Is your feature request related to a problem? Please describe.**
Regarding #8615  it would be nice that `autoSkipNonRecoverableData` also allows skipping non-recoverable data from offloaded storage too, not only from bookies.

**Describe alternatives you've considered**
An alternative is manually skipping ledgers with `pulsar-admin topics skip` and before that going through `pulsar-admin topics stats-internal` to see where subscription or reader is stuck and how many entries are inside a missing ledger.

Another thing that can be done is manually deleting missing ledgers from topic metadata inside zookeepers. (there is a tool for this [pulsar-managed-ledger-admin](https://github.com/apache/pulsar/blob/master/bin/pulsar-managed-ledger-admin))

**Additional context**
If ledgers are missing from offloaded storage there should be an option to skip those while reading.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
