### ISSUE TITLE
Add docs of how namespace broker isolation policy works

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#8977]
currently, there are no enough docs to describe how namespace broker isolation policy works. We need to add some docs for it.
related with PR #8976

**Comment by eolivelli** [comment]
+1

**Comment by Anonymitaet** [comment]
Related to https://github.com/apache/pulsar/issues/3104

**Comment by zymap** [comment]
Looks like documentation already added. Close this issue.
