### ISSUE TITLE
Broken link for Spark example

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#8994]
On this page: https://pulsar.apache.org/docs/en/adaptors-spark/
it says, "You can find a complete example [here](https://github.com/apache/pulsar/tree/master/examples/spark/src/main/java/org/apache/spark/streaming/receiver/example/SparkStreamingPulsarReceiverExample.java). In this example, the number of messages which contain the string "Pulsar" in received messages is counted."

That link (https://github.com/apache/pulsar/tree/master/examples/spark/src/main/java/org/apache/spark/streaming/receiver/example/SparkStreamingPulsarReceiverExample.java) is broken, and I'm having trouble finding the updated location for this code.

**Comment by Jennifer88huang** [comment]
@devinbost Thanks for the issue. Is this what you want? The example you mention is here https://github.com/apache/pulsar-adapters/blob/master/examples/spark/src/main/java/org/apache/spark/streaming/receiver/example/SparkStreamingPulsarReceiverExample.java

We need to fix it.
