### ISSUE TITLE
https://pulsar.apache.org/api/python/ Points to Very Old Version (Instead of Latest)

### ISSUE THREAD

**Issue by astifter** [apache/pulsar#8999]
https://pulsar.apache.org/api/python/ points to the first ever released Python API. This was confusing me for the longest time until I figured out that the latest API doc is actually at https://pulsar.apache.org/api/python/2.7.0-SNAPSHOT/

https://pulsar.apache.org/api/python/ should redirect to the latest version and the page itself should clearly state which version it documents.

**Comment by Jennifer88huang** [comment]
@tuteng do you have any idea on it?

**Comment by tuteng** [comment]
@astifter You are correct, we don't seem to have updated the latest version of the content, would you be interested in creatin a pr? https://github.com/apache/pulsar/tree/asf-site/content/api/python

You can add a command below this line https://github.com/apache/pulsar/blob/master/site2/tools/python-doc-gen.sh#L46 to copy the latest content:

```
cp -r $DESTINATION/* $ROOT_DIR/generated-site/api/python/
```
