### ISSUE TITLE
[Doc] Full scale example

### ISSUE THREAD

**Issue by hpvd** [apache/pulsar#9008]
**Is your enhancement request related to a problem? Please describe.**

Maybe it's already there, but I couldn't find it...

One thing would complete the documentation: a full scale example
- to learn **basics**,
- some **professional practice** and
- have fast **positive experience** -which could directly be **shared with others**.

**Describe the solution you'd like**

Requirements to fulfil this:
- it needs some kind of **simple web frontend** to show it directly to colleges and decision makers (motivation!)
- **step-by-step guide** how to
   -- setup (just link to https://pulsar.apache.org/docs/en/standalone-docker/) and
   -- build it (text not video, to easily copy code for each step) 
- the complete **project as download** as alternative to build it via guide
- having it as running **Live-Demo on Pulsar's website**, always using the latest pulsar version

-------------
One raw idea would be some kind of simple (one way) **chat system "me->Tom"**
- with some interesting features
- setup in a real **professional** manner (e.g. with schema and encryption)

e.g. only 6 elements on a website webpage:
1. Text field "me" to put text in
2. a **send** button to sent my text **to a topic**
3. Text field "to be removed" with letters or words which should be removed e.g. "e" (via a **pulsar function** and stored in "cleaned up topic")
edit: to show some other good practice functionality it may be an idea not to give this field on the webpage but give these letter/word as **function parameter at deployment**...
4. text field "tom" which **receives** my text in the manipulated version (**from** "cleaned up" **topic**)
5. a check mark near text field "me" to indicate Tom received my message (**acknowledgement**)
6. a simple statistic (text) which uses **function state** to count:
  -- number of messages sent
  -- number of removed "e"

of course this could be enhanced further in many ways...
- bidirectional chat
- possibility to set names of chatting people
- ....

**Comment by hpvd** [comment]
edit point 3:

> to show some other good practice functionality it may be an idea not to give this field on the webpage but give these letter/word as function parameter at deployment...

**Comment by Jennifer88huang** [comment]
@hpvd thanks for raising the issue.
@Huanli-Meng has plan to add it this week.

**Comment by hpvd** [comment]
awesome!

maybe one can use the steps and **original code snippets** shown in this doc not only for this example, but also **directly for** setting up an **automated** test checking everything works smoothly together?

If this test fail:
- there are some new incompatibilities introduced with recent code changes between the different parts used in this example or
- something has changed by intend and this doc has to be updated...

**Comment by hpvd** [comment]
this feature would be a perfect addition for this example:
Using a websocket client with authentication on the browser side https://github.com/apache/pulsar/issues/9854

**Comment by Anonymitaet** [comment]
@Huanli-Meng could you please share your thoughts? Thanks

**Comment by Huanli-Meng** [comment]
@hpvd Thanks for bringing such a great idea. Here are my thoughts:
1: currently, the frontend web console for Pulsar is not available on the website. You can try to use the Pulsar Manager. Pulsar Manager is a GUI dashboard for managing and monitoring Pulsar components. 

2: The[ get-started](https://pulsar.apache.org/docs/en/standalone/) section on the Pulsar website can provide a full example of how to Run Pulsar in different modes. You can check it. If there is more info you need, feel free to contact us.

**Comment by Anonymitaet** [comment]
Hi @hpvd 
This is an awesome idea! 

I also see other similar playgrounds and collected those good ideas [here](https://docs.google.com/document/d/1IV35SI_F8G8cL-Vuzknc6RTGLK9_edRMpZpnrHvAWNs/edit#bookmark=id.v236yundf077)

I've discussed it w/ engineers (@codelipenghui @urfreespace), however, they think that, unlike [Go interactive web tool](https://go.dev/), ASF may need to provide resources (eg. servers) to run this playground, which might be a blocker for implementing this solution.

🔹🔹

Hi @dave2wave 
Please correct me if we're wrong.

🔹🔹

// cc @signormercurio @D-2-Ed @DaveDuggins @momo-jun @Huanli-Meng

**Comment by momo-jun** [comment]
Closed the issue since it hasn't been planned yet at this moment. Feel free to reopen it when it's relevant.
