### ISSUE TITLE
Expose message metadata in Pulsar function Go

### ISSUE THREAD

**Issue by alex-rufo** [apache/pulsar#9022]
When coding a Pulsar function in Golang there is no way to get the ID of the message, the key, the event time or the properties. just the payload is exposed.

**Describe the solution you'd like**
After taking a look at the implementation, I think it will be hard to add this information into the context (the same way it is done for the Python library). I would suggest injecting the whole `pulsar.Message` into the process function rather than just the payload.

**Comment by freeznet** [comment]
`Context` already holds the message metadata in golang function. you can check the Golang part of [context docs](http://pulsar.apache.org/docs/en/next/functions-develop/#context) here.

As for your issue, the message can get from `FunctionContext.GetCurrentRecord()` (https://github.com/apache/pulsar/blob/master/pulsar-function-go/pf/context.go#L168), which will get `pulsar.Message` (https://github.com/apache/pulsar-client-go/blob/master/pulsar/message.go#L66) to access exposed message metadata like id, the key, the event time, etc.

Also, here is an example function (https://github.com/apache/pulsar/blob/master/pulsar-function-go/examples/contextFunc/contextFunc.go) might be helpful as well.

**Comment by alex-rufo** [comment]
Thanks @freeznet, I missed that!
