### ISSUE TITLE
pulsar stat : how to get consumer total lag ?

### ISSUE THREAD

**Issue by xiaotongwang1** [apache/pulsar#9078]
I use getPartitionedStats API to check consumer total lag but the stat of msgBacklog size in subscriptions not eqaul to total lag !!!!!

**Comment by codelipenghui** [comment]
@xiaotongwang1 Sorry for the late response, the total lag is equaled to the `msgBacklogs` in the topic stats.

**Comment by codelipenghui** [comment]
close this issue since no update.
