### ISSUE TITLE
no python client for Mac 11.1  pulsar 2.7 

### ISSUE THREAD

**Issue by sixhj** [apache/pulsar#9086]
no python client for Mac 11.1  pulsar 2.7

**Comment by bry00** [comment]
Python-client 2.7 cannot be installed (using pip) on MacOS 11.1 (Big Sur) regardless of the Python version (verified for 3.7.9, 3.8.6 and 3.9.0).  
The last instalable version of the pulsar-client package is 2.6.1.
Please, provide support for both Python 3.8 and 3.9 environments.

**Comment by sijie** [comment]
@bry00 we will take a look at this issue.

**Comment by zymap** [comment]
@bry00 @sixhj Sorry for the delay.

We already re-upload the python package to PyPI, please try again.

We supported python 3.8 and will consider adding python 3.9 support.

**Comment by codelipenghui** [comment]
@sixhj I will close this issue first since @zymap has fixed this problem.
