### ISSUE TITLE
Function worker service is not done initializing

### ISSUE THREAD

**Issue by lichuan6** [apache/pulsar#9092]
**Describe the bug**

I have a pulsar cluster deployed in EKS. I was trying to run `functions` or `sinks` sub commands, but I got annoying errors.

The commands and errors are:

`functions list`
```shell
export TOKEN="xxxxx" # token generate from Pulsar Admin UI
bin/pulsar-admin --admin-url http://pulsar-broker.pulsar:8080 --auth-params "token:${ADMIN_JWT_TOKEN}" --auth-plugin "org.apache.pulsar.client.impl.auth.AuthenticationToken" functions list
```

`sinks list`
```shell
export TOKEN="xxxxx" # token generate from Pulsar Admin UI
bin/pulsar-admin --admin-url http://pulsar-broker.pulsar:8080 --auth-params "token:${ADMIN_JWT_TOKEN}" --auth-plugin "org.apache.pulsar.client.impl.auth.AuthenticationToken" sinks list
```
error:
```
Function worker service is not done initializing. Please try again in a little while.

Reason: HTTP 503 Service Unavailable
```

**Comment by freeznet** [comment]
Can you provide more details about how you deploy your cluster? Also when you execute `functions ls` command, can you see any log from broker pod?

**Comment by lichuan6** [comment]
After changing the token generated from pulsar UI to the one in `broker.conf`, I can call `functions list` successfully. 

Then I tried to create a sink using `sinks create`, however, I got this error when trying to stats the sink.

In toolset pod:

```shell
bin/pulsar-admin --admin-url http://pulsar-broker.pulsar:8080 --auth-params "token:${TOKEN}" --auth-plugin "org.apache.pulsar.client.impl.auth.AuthenticationToken" sinks status --tenant public --namespace default --name my-elasticsearch-sink
{
  "numInstances" : 1,
  "numRunning" : 0,
  "instances" : [ {
    "instanceId" : 0,
    "status" : {
      "running" : false,
      "error" : "UNAVAILABLE: Unable to resolve host pf-public-default-my-elasticsearch-sink-0.pf-public-default-my-elasticsearch-sink.pulsar.svc.cluster.local",
      "numRestarts" : 0,
      "numReadFromPulsar" : 0,
      "numSystemExceptions" : 0,
      "latestSystemExceptions" : [ ],
      "numSinkExceptions" : 0,
      "latestSinkExceptions" : [ ],
      "numWrittenToSink" : 0,
      "lastReceivedTime" : 0,
      "workerId" : "c-2.6.1-pulsar-fw-pulsar-broker-4.pulsar-broker.pulsar.svc.cluster.local-8080"
    }
  } ]
}
```

**Comment by wolfstudy** [comment]
> "error" : "UNAVAILABLE: Unable to resolve host pf-public-default-my-elasticsearch-sink-0.pf-public-default-my-elasticsearch-sink.pulsar.svc.cluster.local",

This is because your terminal cannot connect to the ip address in the pod. You can use ping or telnet to verify. Under normal circumstances, this network connection is not working. You can consider the following solutions:

- If it is a test environment, you can use kubectl exec -it <your pod name>, enter the pod, and then execute the above command.
- If it is a production environment, you can consider using DNS and other methods to expose the address to be accessed

**Comment by lichuan6** [comment]
After killing broker pods and waiting for hours, my own sink connector ran successfully.

**Comment by codelipenghui** [comment]
@lichuan6 Close this issue first, feel free to reopen it if needed.

**Comment by liwenjielala** [comment]
我有同样的问题
pulsar 版本2.7.5  
我原来有三个bookie节点，由于各种原因丢失了两个节点的数据，集群重启之后，三个节点工作正常，可以正常消费生产数据。但是无法创建debezium ，报错如下
root@pulsar-broker-0:/pulsar# bin/pulsar-admin source create    --source-config-file /pulsar/debezium-mysql-source-config.yaml
Function worker service is not done initializing. Please try again in a little while.

Reason: HTTP 503 Service Unavailable{"reason":"Function worker service is not done initializing. Please try again in a little while."}

这可能依然是 pulsar 中的问题，和 Function worker  有关，但我不知道如何解决他
