### ISSUE TITLE
Introduce Pulsar Auditor

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#9099]
## Background / Description

Currently, Bookie Recovery only audits ledgers. It doesn't understand any Pulsar concepts. From the viewpoint of a Pulsar maintainer, it is crucial to identify which namespaces/topics are impacted or continue to remain under-replicated so that we can surface these metrics to owners of these namespaces. Also, it would help in tracking which topics have become healthy/recovered in an incremental fashion.

## Requirements

- Be able to expose metrics if a topic is _under replicated_ or not. If it is under replicated, how many ledgers are under replicated?
- Be able to expose metrics if a topic is missing any objects in tiered storage.

## Definition of done

- [ ] Code changes
- [ ] Tests are added
- [ ] Integration tests are added
- [ ] Documentation is added

**Comment by sijie** [comment]
This has been resolved by https://github.com/apache/pulsar/pull/10013
