### ISSUE TITLE
admin-api-brokers list failed 

### ISSUE THREAD

**Issue by xiaotongwang1** [apache/pulsar#9128]
[dmq@host-10-33-50-221 bin]$ ./pulsar-admin --auth-plugin org.apache.pulsar.client.impl.auth.AuthenticationToken --auth-params token:CgB6e3x9PKWk714cEg4v8UPagxPZX7mCycV5OsUQle5SHOMO6yAXFeTd2Bjayy0Vj7Vxvj7/bbYr2r4lt+CUUrME brokers list pulsar-cluster-2
Failed to validate Cluster configuration : cluster=pulsar-cluster-2  emsg=For input string: "8080,10.33.50.220:8080,10.33.50.221:8080"

Reason: Failed to validate Cluster configuration : cluster=pulsar-cluster-2  emsg=For input string: "8080,10.33.50.220:8080,10.33.50.221:8080"

Maybe there have bug  in parses cluster service url

**Comment by sijie** [comment]
@xiaotongwang1 How did you set cluster `pulsar-cluster-2`? Can you run `pulsar-admin clusters get pulsar-cluster-2`?
