### ISSUE TITLE
Go Function panics due to config file is nil

### ISSUE THREAD

**Issue by mmussett** [apache/pulsar#9139]
**Describe the bug**
Go function panics due to config file not being found.

github.com/apache/pulsar/pulsar-function-go/pf.newInstanceConf(0x74ee0)
	/home/mmussett/go/pkg/mod/github.com/apache/pulsar/pulsar-function-go@v0.0.0-20210106064818-984bf837489b/pf/instanceConf.go:49 +0x656
github.com/apache/pulsar/pulsar-function-go/pf.NewFuncContext(0x8)
	/home/mmussett/go/pkg/mod/github.com/apache/pulsar/pulsar-function-go@v0.0.0-20210106064818-984bf837489b/pf/context.go:44 +0x26
github.com/apache/pulsar/pulsar-function-go/pf.newGoInstance(0xd35680)
	/home/mmussett/go/pkg/mod/github.com/apache/pulsar/pulsar-function-go@v0.0.0-20210106064818-984bf837489b/pf/instance.go:65 +0x37
github.com/apache/pulsar/pulsar-function-go/pf.Start(0xd35680, 0xe84248)
	/home/mmussett/go/pkg/mod/github.com/apache/pulsar/pulsar-function-go@v0.0.0-20210106064818-984bf837489b/pf/function.go:170 +0x52

**To Reproduce**

function built using go build. Everything looks correct and go.mod has require line of github.com/apache/pulsar/pulsar-function-go v0.0.0-20210106064818-984bf837489b

Tested both as functions create and localrun and both have the same result of function failing.

pulsar-admin functions localrun --go /home/mmussett/Downloads/PulsarFunctions/bin/pflogoFunc -i persistent://public/default/to-flogo -o persistent://public/default/from-flogo --classname empty

2021/01/06 09:56:13.033 log.go:46: [info] The default config file path is: conf/conf.yaml
2021/01/06 09:56:13.036 log.go:76: [error] unmarshal config content error:invalid character '\'' looking for beginning of value
panic: config file is nil.

goroutine 1 [running]:
github.com/apache/pulsar/pulsar-function-go/pf.newInstanceConf(0x74ee0)
	/home/mmussett/go/pkg/mod/github.com/apache/pulsar/pulsar-function-go@v0.0.0-20210106064818-984bf837489b/pf/instanceConf.go:49 +0x656
github.com/apache/pulsar/pulsar-function-go/pf.NewFuncContext(0x8)
	/home/mmussett/go/pkg/mod/github.com/apache/pulsar/pulsar-function-go@v0.0.0-20210106064818-984bf837489b/pf/context.go:44 +0x26
github.com/apache/pulsar/pulsar-function-go/pf.newGoInstance(0xd35680)
	/home/mmussett/go/pkg/mod/github.com/apache/pulsar/pulsar-function-go@v0.0.0-20210106064818-984bf837489b/pf/instance.go:65 +0x37
github.com/apache/pulsar/pulsar-function-go/pf.Start(0xd35680, 0xe84248)
	/home/mmussett/go/pkg/mod/github.com/apache/pulsar/pulsar-function-go@v0.0.0-20210106064818-984bf837489b/pf/function.go:170 +0x52
main.main()
	/home/mmussett/Downloads/PulsarFunctions/src/shim.go:10 +0x39
09:56:13.137 [Timer-0] INFO  org.apache.pulsar.functions.LocalRunner - {
  "instanceId": "0"
}
^C09:56:17.634 [Thread-1] INFO  org.apache.pulsar.functions.LocalRunner - Shutting down the localrun runtimeSpawner ...

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 20.0.4

**Additional context**

**Comment by freeznet** [comment]
If you are using Pulsar 2.7.0, then this issue is duplicated with #8757, and already fixed by #8780.

**Comment by sijie** [comment]
Closed it since it is duplicated of #8757 and fixed by #8780.
