### ISSUE TITLE
Message redelivery delay with exponential back-off

### ISSUE THREAD

**Issue by klevy-toast** [apache/pulsar#9141]
**Is your feature request related to a problem? Please describe.**
I would like to leverage re-deliveries with exponential back-off when my consumer nacks a message. Retries with exponential back-off is often preferred over simple retries when encountering transient errors to give an immediate chance at succeeding on a retry, but to avoid overwhelming a service if it is failing a lot of messages.

**Describe the solution you'd like**
Allow configuration of a retry strategy (fixed interval, exponential back-off) when configuring redelivery delay.

**Describe alternatives you've considered**
I think that this could be hacked together in the consumer code, by checking the delivery count and scheduling one-off redeliveries based on that, but it would be a much more fragile solution.

**Comment by sijie** [comment]
@klevy-toast did you checkout https://pulsar.apache.org/docs/en/concepts-messaging/#retry-letter-topic?

https://github.com/apache/pulsar/wiki/PIP-58-%3A-Support-Consumers--Set-Custom-Retry-Delay

**Comment by klevy-toast** [comment]
Thanks @sijie -- I had not seen the retry-letter-topic. I am having a little trouble picture how it could be utilized for exponential back-off -- would I want to configure the consumer to have a single immediate, retry, and then the retry topic to have a higher delay? How would that delay be configured?

The PIP-58 proposal looks more similar to what I am imagining, without the use of additional topic. It would be even nicer to have pre-configured retry "strategies" (I believe that the AWS Java SDK has this concept), but a `reconsumeLater` would probably be enough to manually implement the back-off logic.

**Comment by sijie** [comment]
@codelipenghui Can you take a look at this?

**Comment by codelipenghui** [comment]
@klevy-toast You are right, the PIP-58 is e enough to manually implement the back-off logic. It's easy to support exponential back-off for the redelivery since we have exposed the redelivery count to the client-side.

**Comment by klevy-toast** [comment]
> @klevy-toast You are right, the PIP-58 is e enough to manually implement the back-off logic. It's easy to support exponential back-off for the redelivery since we have exposed the redelivery count to the client-side.

@codelipenghui would it be reasonable to create a retry strategy as I described, so that many pulsar users could quickly utilize exponential back-off without re-implementing the logic every time?

**Comment by codelipenghui** [comment]
@klevy-toast Yes, It seems reasonable to me. Are you interested in pushing a PR for this issue?

**Comment by klevy-toast** [comment]
@codelipenghui sure, although it may take me a while to find the spare cycles.

**Comment by alivannikov** [comment]
Hi all!

We are also interested in redelivery delay with exponential back-off feature, and while investigating possible ways to implement it I got a bit confused by different existing options and mechanisms. In particular - what is the relation between `reconsumeLater` api and `nacking`? Let's pretend I just want fixed retry delay. Is there any difference between
a. Configuring `NackRedeliveryDelay` option and sending `Nack`
b. Using `reconsumeLater` with same `NackRedeliveryDelay`

One more follow-up question. If I call `reconsumeLater`, do I need to send `Ack` after it? (in some sense I processed message to some result - rescheduling) `Nack`? Nothing?

**Comment by codelipenghui** [comment]
The recosumeLater can works while the client crashes, if use the nack delay and the client crashes at a time, the message will retry immediately.

**Comment by alivannikov** [comment]
@codelipenghui Thank you for reply. One more point regarding the issue.

> It's easy to support exponential back-off for the redelivery since we have exposed the redelivery count to the client-side.

While this is true for `Nack` case, which really increments the counter, `reconsumeLater` flow actually `Ack` original message under the hood and uses internal map structure to track the counter. For me redelivery count exposed by api was always 0 while testing `reconsumeLater`. I was reading real counter from message properties map by `SysPropertyReconsumeTimes` (Go client, similar property exists in Java client) key.

**Comment by klevy-toast** [comment]
close by https://github.com/apache/pulsar/pull/12566
