### ISSUE TITLE
ManagedLedgerException using readers

### ISSUE THREAD

**Issue by dlsprague** [apache/pulsar#9142]
If user needs to stop or some error stops the service and its not noticed for a while on restart the reader might get these  errors. 
 This error is only recoverable when waiting for a couple of hours and then starting the reader again.

Getting the following errors every so often when restarting reader code:g

Received error from server: **Failed to get batch size for entry** org.apache.bookkeeper.mledger.ManagedLedgerException$NonRecoverableLedgerException: **No such ledger exists on Metadata Server**
Received unknown request id from server: 12

Received error from server: Failed to get batch size for entry org.apache.bookkeeper.mledger.ManagedLedgerException: Incorrect parameter input

This only occurs using a reader instead of a consumer or producer. 
The only fix is to keep waiting and restarting the connection until that error doesn't come from pulsar.

Broker is running on 2.6.0 version.

**Comment by sijie** [comment]
@dlsprague Did you set any retention policy on the topic? It seems that the ledgers are deleted because there was no ledger exists on the metadata server.

**Comment by dlsprague** [comment]
HI Thank you for your response.  Yes, the TTL was set at 4 hours.  I increased it to 24 hours.

**Comment by dlsprague** [comment]
User has set up reader to look for earliest message.   Attached is how that is configured along with client log.   

![image (6)](https://user-images.githubusercontent.com/75750837/104358166-0fd3a900-54dc-11eb-9eb9-d0efa3c259a6.png)
![image (5)](https://user-images.githubusercontent.com/75750837/104358169-1104d600-54dc-11eb-9eea-f0fd8ca9f819.png)


Some log information from broker.  
13:56:59.135 [pulsar-ordered-OrderedExecutor-7-0-EventThread] INFO  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://kaov/osqar/network-cdc-offset-dev][reader-fa7825c9ae] Creating non-durable subscription at msg id -1:-1:-1:-1
13:56:59.136 [pulsar-ordered-OrderedExecutor-7-0-EventThread] INFO  org.apache.bookkeeper.mledger.impl.NonDurableCursorImpl - [kaov/osqar/persistent/network-cdc-offset-de ] Created non-durable cursor read-position=13291496:0 mark-delete-position=13291496:-1
13:56:59.136 [pulsar-ordered-OrderedExecutor-7-0-EventThread] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [kaov/osqar/persistent/network-cdc-offset-dev] Opened new cursor: NonDurableCursorImpl{ledger=kaov/osqar/persistent/network-cdc-offset-dev, ackPos=13291496:-1, readPos=13291496:0}

Thanks again.
