### ISSUE TITLE
Please reduce GitHub Actions matrix or improve the build time

### ISSUE THREAD

**Issue by vlsi** [apache/pulsar#9154]
GitHub Actions queue is very high for Apache projects, and it looks like a significant number of executors are occupied by Pulsar jobs :-(

Note: all Apache projects share the same limit of shared GitHub Actions runners, and based on the chart below Pulsar is consuming 30+ runners while the total limit (for all ASF projects) is 180.

See https://lists.apache.org/thread.html/r5303eec41cc1dfc51c15dbe44770e37369330f9644ef09813f649120%40%3Cbuilds.apache.org%3E

>number of GA workflows in/progress/queued per project and they clearly show the situation is getting worse by day:

![number of GA workflows in/progress/queued per project](https://user-images.githubusercontent.com/213894/104056004-c6940880-5200-11eb-802c-6d1e9d9475de.png)

---

For instance, https://github.com/n1hility/cancel-previous-runs might be helpful to cancel old jobs when a newer commit exists.

**Comment by sijie** [comment]
@vlsi will work on this.

@codelipenghui @zymap Can you work on adding cancel-previous-run action back to our Github Actions?

**Comment by vlsi** [comment]
Just in case, there's update from Jarek:

> There is one problem with the charts, They are flawed. **They show
>'workflows' not 'jobs'** and one workflow might mean many jobs :(. For
>example the big number of workflows you can see  in Airflow yesterday come
>from "Label when reviewed" workflows - each of which has 1 job that
>takes 10 seconds or so. One workflow  can be 20/30 times more important
>than another.

> We cannot easily drill down to jobs, because we are using Github API to get
>the information, but there are limits (max num requests/hr) and we are
>already close to hitting it with the current setup.

In any case, it would be nice if you could reduce Actions workload ;-)

**Comment by vlsi** [comment]
I see you've removed https://github.com/apache/pulsar/pull/9069 `styfle/cancel-workflow-action` recently.

However, there's a workaround to use third-party actions (provided you have reviewed them):
https://github.com/apache/calcite/pull/2318/files

The idea is that you clone the action via SHA identifier, so the action can't silently change after your review.

An alternative option is to raise INFRA ticket to allow `styfle/cancel-workflow-action` (and still use SHA-based action ids like `styfle/cancel-workflow-action@123123123...123123`)

WDYT?

**Comment by sijie** [comment]
@vlsi Thank you for your feedback. I will let @codelipenghui @zymap take the actions from here.

**Comment by codelipenghui** [comment]
Thanks, we will start as soon as possible.

Sijie Guo <notifications@github.com>于2021年1月9日 周六04:39写道：

**Comment by sijie** [comment]
This is fixed by #9159

**Comment by eolivelli** [comment]
Probably the fix here is not good
https://github.com/apache/pulsar/pull/9159

see my comments
https://github.com/apache/pulsar/actions?page=4&query=is%3Aqueued

we are still spawning too many job requests
