### ISSUE TITLE
What's the batch Delay default value

### ISSUE THREAD

**Issue by Shoothzj** [apache/pulsar#9168]
![image](https://user-images.githubusercontent.com/12933197/104148191-3fb37b80-540c-11eb-817d-03ae94602ebf.png)
In this annotation, the default value is 10 ms.
But in this code, the default value is 1.
![image](https://user-images.githubusercontent.com/12933197/104148219-6376c180-540c-11eb-9b5b-da5367b9e5d8.png)

Which value is recommended? It seems scheduly task execs per 1 ms easily cause the application OOM

**Comment by sijie** [comment]
1 ms. The comment needs to be updated.

**Comment by Jennifer88huang** [comment]
- In `ProducerConfiguration.java` file, the default value is set to `10ms`.
- In `ProducerBuilder.java` file, the default value is set to `1ms`.
- In [go client](https://pulsar.apache.org/docs/en/next/client-libraries-go/#producer-configuration), the default value for BatchingMaxPublishDelay is `10ms`.

**Comment by Jennifer88huang** [comment]
The comment in the code and the documentation should be changed into `1ms`.

**Comment by Anonymitaet** [comment]
@sijia-w may I know the doc process?
