### ISSUE TITLE
Create documentation for bookieID configuration option

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#9174]
With https://github.com/apache/pulsar/pull/9019 we are updating BookKeeper to version 4.12.1, this change will allow users to use the BookieID feature of BookKeeper.
Basically if you add this line to conf/bookkeeper.conf. (and conf/standalone.conf for standalone execution)
`
bookieId=xxxxx
`
The bookie will advertise itself using 'xxxxx' as identifier, and it won't use address:port.
This way you are able to use a dynamic network address for the bookie
see the BP-41 page for more details
http://bookkeeper.apache.org/bps/BP-41-bookieid/

**Comment by Anonymitaet** [comment]
@eolivelli would you like to add docs for this change?

**Comment by Anonymitaet** [comment]
@eolivelli does this code change apply to 2.7.1?

**Comment by eolivelli** [comment]
@Anonymitaet it is working since 2.7.0

I am sorry I don't have much time to write down the docs.
But I will very happy to answer to all of your questions and review

**Comment by codelipenghui** [comment]
Close this issue since #9779 already merged.
