### ISSUE TITLE
where can i get a correct code formatter xml

### ISSUE THREAD

**Issue by xiaotongwang1** [apache/pulsar#9189]
i import src/formatter.xml to eclipse ,but i do not think it is correct 

sample code of pulsar 
 
![image](https://user-images.githubusercontent.com/6071261/104301003-1d9c2500-5502-11eb-898c-6ba0d9591931.png)

after format with pulsar 

 
![image](https://user-images.githubusercontent.com/6071261/104300971-1543ea00-5502-11eb-866a-9b6f1691b0c9.png)

**Comment by codelipenghui** [comment]
Currently, we do not have a formatter file.

**Comment by Renkai** [comment]
We have a checkstyle file that enabled on many modules, https://github.com/apache/pulsar/blob/cc64889abe94d47f048e2f8e8fb10d6c37e695ec/buildtools/src/main/resources/pulsar/checkstyle.xml

But it's not a formatter, you'd better configure your own formatter to conform to the checkstyle.
