### ISSUE TITLE
[Broker] DEBUG loglevel throw error when originalPrincipal not exists

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#9209]
**Describe the bug**
When loglevel is set to DEBUG,

https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java#L693

Throws an error when original principal does not exist.

**Comment by codelipenghui** [comment]
@KannarFr Could you please provide more details about the error? such as stacktrace?

**Comment by codelipenghui** [comment]
close this issue first since no update for a long time.
