### ISSUE TITLE
Error Code Meanings

### ISSUE THREAD

**Issue by Alxander64** [apache/pulsar#9211]
**Is your enhancement request related to a problem? Please describe.**

I sometimes see this error message:
```
2021-01-14 20:40:03.388 ERROR [140107798095616] ClientConnection:891 | [<SOME_IP:PORT> -> <SOME_IP:PORT>] Failed lookup req_id: X error: 6
```

I'm not sure what `error: 6` means specifically, and I can't easily tell from looking at the code.

I can tell it originates from [here](https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/lib/ClientConnection.cc#L903), but I'm a little lost trying to follow it any further.

**Describe the solution you'd like**

Have some explanation somewhere of what these error codes mean.

**Comment by Jennifer88huang** [comment]
@zymap could you help have a look at it? Thank you.

**Comment by zymap** [comment]
You can find the lookup command handler here: https://github.com/apache/pulsar/blob/b019c4b75348f2e4ff6a9b6c3367b2b951429fad/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java#L375

I think it's a service error code, and all service error code you can find from https://github.com/apache/pulsar/blob/b019c4b75348f2e4ff6a9b6c3367b2b951429fad/pulsar-common/src/main/proto/PulsarApi.proto#L189

**Comment by codelipenghui** [comment]
@BewareMyPower Could you please help take a look at this issue? seems it's a log improvement.

**Comment by BewareMyPower** [comment]
OK
