### ISSUE TITLE
Wrong error message while creating a topic to a non existing namespace

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#9220]
**Describe the bug**

When you try to create a topic to a non existant namespace (in this cae 'defaul' instead of 'default') you got an error that is very hard to understand for the user

```
bin/pulsar-admin topics create persistent://public/defaul/topic1
14:56:09.681 [AsyncHttpClient-7-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://localhost:8080/admin/v2/persistent/public/defaul/topic1] Failed to perform http put request: javax.ws.rs.ClientErrorException: HTTP 412 Precondition Failed
Namespace does not have any clusters configured
```

**Expected behavior**
An error like 'namespace does not exist'

**Comment by johnsmartco** [comment]
+1 to improving product usability with clarifying message text.
