### ISSUE TITLE
[Doc] C++ client's doc is poor

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar#9282]
**Is your enhancement request related to a problem? Please describe.**
The C++ client's [doc](http://pulsar.apache.org/api/cpp/2.7.0-SNAPSHOT/) is poor, a lot of interfaces are not well documented. For example, a lot of setters/getters have no document, see http://pulsar.apache.org/api/cpp/2.7.0-SNAPSHOT/classpulsar_1_1_producer_configuration.html for example. Users cannot get some default config values and its definition.

**Describe the solution you'd like**
Improve the documents. At least we should add documents for those interfaces.

**Additional context**
I'm working on new API of `Producer::send` recently (see #9176), when the PR is pushed, it can be treated as an example.

**Comment by BewareMyPower** [comment]
As the generated docs in my local environment, here's an example from #9287 

<img width="1160" alt="截屏2021-01-22 下午10 45 28" src="https://user-images.githubusercontent.com/18204803/105505215-a46faf80-5d03-11eb-865e-83cb0a7d9737.png">

As we can see, we can link `ProducerConfiguration`'s related methods from `Producer#send`. However it requires these external methods have JavaDoc style comments. If not, these methods cannot be linked, like the current C++ API website:

<img width="884" alt="截屏2021-01-22 下午10 50 12" src="https://user-images.githubusercontent.com/18204803/105505691-3a0b3f00-5d04-11eb-8dda-b41a9f798f12.png">

The methods with dark bold text are not documented and have no link.

**Comment by Anonymitaet** [comment]
Hi @BewareMyPower I've added descriptions for the methods in the [ProducerConfiguration.h](http://pulsar.apache.org/api/cpp/2.8.0-SNAPSHOT/classpulsar_1_1_producer_configuration.html), could you please help review? Thanks 
https://docs.google.com/document/d/1SjO8SCVcbCMuEVW-HI1kf_jJjy-Ej5yFZoY9g4jUAQQ/edit

**Comment by Anonymitaet** [comment]
Hi @BewareMyPower, I've [added descriptions](https://docs.google.com/document/d/1NuPUK4pUx_uXmhw-l3lPE9k4uKeH2IGMQ5o7MtvSp70/edit#) for the methods in the following files:

- ClientConfiguration.h 
- ConsumerConfiguration.h 
- ReaderConfiguration.h 

Could you please help review?

Feedback before 3/31 is highly appreciated, thanks!

**Comment by BewareMyPower** [comment]
@Anonymitaet OK

**Comment by Anonymitaet** [comment]
@BewareMyPower I've added more descriptions for various classes [here](https://docs.google.com/document/d/10Zp0V_R5QCvc3mv0YofU0D1rIGliirtakQZIUVM83xM/edit#).

Could you please review and **give feedback before 4/13**? Many thanks!

**Comment by BewareMyPower** [comment]
@Anonymitaet OK, I'm a little busy these days and may give some feedbacks on 4/11 or 4/12.

**Comment by Anonymitaet** [comment]
@BewareMyPower OK, take your time and thanks for your help.
