### ISSUE TITLE
Flink source connector can not use the same client config with sink connector.

### ISSUE THREAD

**Issue by xiemeilong** [apache/pulsar#9285]
**Describe the bug**
When I pass the same ClientConfigurationData object to source and sink.  The source connector will not recive data any more.
When I use different ClientConfigurationData object for source and sink, all works normally.

The same issue exists in both io.streamnative.connectors:pulsar-flink-connector  and  org.apache.pulsar:pulsar-flink .

**To Reproduce**
pass the same ClientConfigurationData object to source and sink

**Expected behavior**
source and sink works.

**Desktop (please complete the following information):**
 - pulsar 2.7.0
 - flink 1.12

**Comment by V1ncentzzZ** [comment]
Hi @xiemeilong , Could you share the code that can reproduce the problem?

**Comment by codelipenghui** [comment]
@xiemeilong Could you please help add an issue at https://github.com/streamnative/pulsar-flink/issues? Since this is related to the flink connector. I will close this one first.
