### ISSUE TITLE
ReconsumeLaterAsync : Asking for help.

### ISSUE THREAD

**Issue by wangshuyu** [apache/pulsar#9294]
`c#

var msg = await consumer.ReceiveAsync();
var body = Encoding.UTF8.GetString(msg.Data.ToArray());
if (msg.Properties.Count > 0)//retry
{
//retry is error, What should I do here?
_ = consumer.ReconsumeLaterAsync(msg, DateTimeToTimeStamp(DateTime.Now.AddSeconds(20)));
}
else
{
//success
_ = consumer.ReconsumeLaterAsync(msg, DateTimeToTimeStamp(DateTime.Now.AddSeconds(10)));
}
`
以上代码,执行重试消息后, 会发生错误,这里我该如何处理呢?
想实现一个消息延时递增处理.
类似: 1s 5s 10s 30s .... 2h....10h

In the above code, after executing the retrial message, an error will occur. What should I do here?
Want to achieve a message delay incremental processing.
example: 1s 5s 10s 30s .... 2h....10h

**Comment by codelipenghui** [comment]
When the error occurs you should not acknowledge the original message.

**Comment by codelipenghui** [comment]
@wangshuyu Is this the last comment that works for you? I will close this issue first since no update on this issue. Feel free to reopen it if you still have some doubt about this issue.
