### ISSUE TITLE
proxy lookup result still contains unreachable owner broker serviceURL after broker restart and 30s zk session expired

### ISSUE THREAD

**Issue by wuYin** [apache/pulsar#9297]
**Describe the bug**
- Certain issue
  After broker restarted with 30s zk session expired, client take 51s, even 1min40s to reconnect successfully, recovery time is a bit long. 

- Flaky issue
  Client reconnect always failed handshake with proxy, stucked at 1~5

![image](https://user-images.githubusercontent.com/24536920/105634717-7cff1b00-5e9a-11eb-8603-06f16525b9c2.png)

**To Reproduce**
1. use pulsar-helm-chart to deploy [pulsar-all:2.6.0](https://hub.docker.com/layers/apachepulsar/pulsar-all/2.6.0/images/sha256-d93e9ac275fe0a6f71d0fd4c9e68d2efb64d4c6fa165c1c07e6c0928d7762fa5?context=explore) cluster
- 1\*zk, 3\*brokers, 3\*bookies, 3\*proxy, all with 2c 2g resource limit
- 4k QPS, 4MBps In/out, for cpu and memory, load < 35%, see [3_brokers_loadreport.json.log](https://github.com/apache/pulsar/files/5862180/3_brokers_loadreport.json.log)

2. Manually delete one broker and restart, it's owning topics(bundles) will be unloaded, clients disconnect with proxy and reconnect, 0.1s, 0.2s, 0.4s, ..., 25.6s at least needed, 51.2s is common.
In flaky case, client reconnect always failed, it has been seen in production env, but it's not easy to reproduce.

**Expected behavior**
After broker restart, client need reconnect succeed as soon as possible, like within 40s(30s zk session expiration + 10s reconnect)

**Screenshots**
![image](https://user-images.githubusercontent.com/24536920/105629682-7d3ded00-5e7f-11eb-9856-eb45a20dae24.png)

**Other**
How to fix certain case to reduce recovery time?
- Reduce zk session expiration time, default 30s, reduce to 10s, but with what cost?
- Client backoff policy default exponential, may need provide a option to limit the backoff limit, such as 5s, backoff should be 0.1s, 0.2s, 0.4s, ...,3.2s, 5s, 5s, ...
- Reduce broker znode expiration waiting time, default 10s, reduce to 2s, see [broker-statefulset.yaml#L197](https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/templates/broker-statefulset.yaml#L197)

How to fix flaky case?
I tried to fix in [PR#9298](https://github.com/apache/pulsar/pull/9298), but I'm not sure it covered this case.

**Comment by wuYin** [comment]
@zymap thanks for review
Actually, I'm not sure this ownership double check PR will solve the flaky Issue
I'll add test to simulate flaky case by removing the /loadbalance/downBroker zNode directly, and fix existed failure tests

**Comment by jiazhai** [comment]
@congbobo184 Is there any suspicion or improvements that you found for the 1st issue?

**Comment by congbobo184** [comment]
I suspicion the proxy config the brokerServiceURL, this config broker down, proxy can't lookup the topic. So client will connect fail and the client reconnect time will Increasing.When the broker restart, client can connect.

**Comment by jiazhai** [comment]
> Client backoff policy default exponential, may need provide a option to limit the backoff limit, such as 5s, backoff should be 0.1s, 0.2s, 0.4s, ...,3.2s, 5s, 5s, ...
Regarding this issue, There were already backoff supported in java client, maybe we need to add this feature in go client

**Comment by wuYin** [comment]
@congbobo184 Thanks for review
I'm using pulsar-helm-chart to deploy cluster, in proxy.conf, broker connection addresses looks like：
```
brokerServiceURL=pulsar://handshake-pulsar-broker:6650
brokerWebServiceURL=http://handshake-pulsar-broker:8080
```
which generated by [proxy-configmap.yaml#L37](https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/templates/proxy-configmap.yaml#L37),  In proxy pod:
```
> cat /etc/resolv.conf 
search psr.svc.cluster.local svc.cluster.local cluster.local pek02.rack.zhihu.com

> host handshake-pulsar-broker
handshake-pulsar-broker.psr.svc.cluster.local has address 10.113.42.32
handshake-pulsar-broker.psr.svc.cluster.local has address 10.113.43.53 # will be removed
handshake-pulsar-broker.psr.svc.cluster.local has address 10.113.46.57

> host handshake-pulsar-broker-1.handshake-pulsar-broker.psr.svc.cluster.local  # bundle owner host
handshake-pulsar-broker-1.handshake-pulsar-broker.psr.svc.cluster.local has address 10.113.43.53
```
For this issue, during broker1 restarting/terminating, it's service DNS record will be removed quickly(within 1s)
Proxy request to other brokers to do Lookup, due to broker1 related zNode not expired yet, other brokers still returned `broker1.xxx.cluster.local` which has been removed, finally lead to client backoff retry the same Lookup.

I think it's reasonable, but there's still small chance to trigger flaky case
In my production env, I drain a k8s node caused a broker be scheduled to another node, but client even retried 16min Lookup still failed.

**Comment by wuYin** [comment]
@jiazhai Thanks for reminding
I'll add an `backoffLimit` option to pulsar-client-go to do this, or something like that

**Comment by congbobo184** [comment]
![image](https://user-images.githubusercontent.com/39078850/105804679-5c8aaa00-5fdb-11eb-961f-8dba4c15473a.png)
Can you provide any proxy do look up command log, it seem to proxy resolve Dns error.

**Comment by wuYin** [comment]
@congbobo184 Sorry for late reply
I scale out proxy to only one, delete broker2 pod, and trace proxy debug log: [handshake-pulsar-proxy-0.log](https://github.com/apache/pulsar/files/5871610/handshake-pulsar-proxy-0.log)
client:
![image](https://user-images.githubusercontent.com/24536920/105809537-d5423400-5fe4-11eb-9c5f-e95005a9344c.png)

**Comment by congbobo184** [comment]
> @congbobo184 Sorry for late reply
> I scale out proxy to only one, delete broker2 pod, and record proxy debug log: [handshake-pulsar-proxy-0.log](https://github.com/apache/pulsar/files/5871610/handshake-pulsar-proxy-0.log)
> client:
> ![image](https://user-images.githubusercontent.com/24536920/105809537-d5423400-5fe4-11eb-9c5f-e95005a9344c.png)

When you delete broker2 pod, does the client always connect fail?

**Comment by wuYin** [comment]
@congbobo184
After delete broker2, client will backoff to retry connect 0.1s, 0.2s, 0.4s, ..., 51.2s, then connected successfully.
This is normal case, and the latency can be reduced by configuring backoff policy.
But I can't reproduce flaky case, this is the trouble..

**Comment by congbobo184** [comment]
It seems difficult to reproduce this problem. I think this problem may zookeeper cache not update on time. like https://github.com/apache/pulsar/pull/8304, It seem that problem will cause the flaky case.

**Comment by congbobo184** [comment]
@wuYin in the certain case, if we close the broker graceful shutdown, we don't need to wait the zk session timeout. you can look https://github.com/apache/pulsar-helm-chart/pull/59 and upgrade the helm chart to 2.6.1-2 or hight version?

**Comment by wuYin** [comment]
> @wuYin in the certain case, if we close the broker graceful shutdown, we don't need to wait the zk session timeout. you can look [apache/pulsar-helm-chart#59](https://github.com/apache/pulsar-helm-chart/pull/59) and upgrade the helm chart to 2.6.1-2 or hight version. Sorry I still haven't reproduced the flaky case.

Thanks for finding this detail. I really didn't noticed, I'll use release which contains this feature. 
To avoid unavailability caused by flaky case, I implemented serious timeout degradation for my application.
If it happen again and steadily, I'll reopen this issue and add more context.
Thank you for helping.
