### ISSUE TITLE
subscriptionExpiration for topic

### ISSUE THREAD

**Issue by uestczshen** [apache/pulsar#9307]
for some reasons, my subscriptionName changes when my server restarts. But the old subname still exists in pulsar-server and alarms messages heap up.   so maybe there should be expire policies for unused subscription.

**Comment by jiazhai** [comment]
Yes, there is ttl policy for this: https://pulsar.apache.org/docs/en/cookbooks-retention-expiry/
This is a kind of question, would like to close this issue, if the ttl policy could not solve your issue, feel free to reopen this issue.

**Comment by nkurihar** [comment]
@uestczshen 
`subscriptionExpirationTimeMinutes` seems to help you:
https://github.com/apache/pulsar/blob/2dc24705efe61fdfca3315edb29946d3a0a9e599/conf/broker.conf#L178-L180

This setting can be enabled at broker level or namespace level.
cf: https://github.com/apache/pulsar/pull/6851
