### ISSUE TITLE
Pulsar function fails to create because the job name is longer than 55 characters

### ISSUE THREAD

**Issue by TMeireOqton** [apache/pulsar#9310]
**Describe the bug**
When the name of the tenant, namespace and function are long, the generated jobname for the kubernetes runtime exceeds 55 characters. Because this is too long, the runtime does not create the stateful set and the function doesn't run.

**To Reproduce**
* Create a tenant `verylongtenantname`
* Create a new namespace `verylongnamespacename`
* Deploy a new function to the namespace with name `verylongfunctionname` to kubernetes
* The job fails to deploy because the generated job name `pf-verylongtenantname-verylongnamespacename-verylongfunctionname` is longer than the 55 character limit of kubernetes.

**Expected behavior**
The default kubernetes runtime implementation is able to deploy the function, regardless of the length of the tenant, namespace, and function name. The dev experience isn't really great when the deployment of a new function suddenly fails for no obvious reason, while the same function works just fine for other tenants because they happen to have a shorter name.

**Additional context**
It is possible to work around this issue by setting a custom job name with the BasicKubernetesManifestCustomizer, but this is not documented anywhere.

**Comment by nlu90** [comment]
Hi, I checked code and doc. Found that this feature is already available here:
https://github.com/apache/pulsar/blob/master/pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/BasicKubernetesManifestCustomizer.java#L53

But, the current doc doesn't mention it explicitly:
https://pulsar.apache.org/docs/en/functions-runtime/

The provided JSON example could include a `Name` field to indicate user they can customize it.

Also I found #9192 adds the missing field.
https://github.com/apache/pulsar/pull/9192/files#diff-09557ee9a7863d24fc938350d6f9d30abc8cd0e65f941099d0058d98b1240a4dR67

**Comment by codelipenghui** [comment]
Thanks @nlu90, I will close this issue first. @TMeireOqton If this does not helps you feel free to reopen the issue.
