### ISSUE TITLE
Is there a default number of subscriptions for a topic?

### ISSUE THREAD

**Issue by rodrigoreis** [apache/pulsar#9311]
The question is whether there is any configuration that limits the number of subscriptions and producers per topic.

**Describe the bug**
I noticed that the topic stops responding when I reach the number of 10 subscriptions per topic.

**To Reproduce**
1. Create a persistent topic.
2. Produce a considerable number of messages
3. Create 11 consumers to handle this topic.

**Desktop (please complete the following information):**
Ubuntu 20.04.1 LTS (GNU/Linux 4.19.128-microsoft-standard x86_64)
  System information as of Mon Jan 25 10:22:50 -03 2021

  System load:  0.0                Processes:             8
  Usage of /:   1.7% of 250.98GB   Users logged in:       0
  Memory usage: 0%                 IPv4 address for eth0: 172.23.157.248
  Swap usage:   0%.

**Comment by codelipenghui** [comment]
Have you update the `maxSubscriptionsPerTopic` in the broker.conf? By default, Pulsar does not limit the subscriptions of a topic.

**Comment by rodrigoreis** [comment]
@codelipenghui I will check and keep in touch, TY.

**Comment by codelipenghui** [comment]
Thanks @rodrigoreis

**Comment by codelipenghui** [comment]
@rodrigoreis I will close this issue first. Feel free to reopen it if needed.
