### ISSUE TITLE
pulsar-io/hbase fails to build

### ISSUE THREAD

**Issue by klwilson227** [apache/pulsar#9324]
**Describe the bug**
All versions of pulsar hbase have begun to fail to build based on build transitive dependency resulting in javax.el:3.0.1-b06-SNAPSHOT reference. This version of the file no longer exists on central. This results in the following maven error when downloading the artifact:

[ERROR] Failed to execute goal on project pulsar-io-hbase: Could not resolve dependencies for project org.apache.pulsar:pulsar-io-hbase:jar:2.7.0: Failed to collect dependencies at org.apache.hbase:hbase-server:jar:2.3.0 -> org.glassfish.web:javax.servlet.jsp:jar:2.3.2 -> org.glassfish:javax.el:jar:3.0.1-b06-SNAPSHOT: Failed to read artifact descriptor for org.glassfish:javax.el:jar:3.0.1-b06-SNAPSHOT: Could not transfer artifact org.glassfish:javax.el:pom:3.0.1-b06-SNAPSHOT from/to spring-plugins-release (https://repo.spring.io/plugins-release/): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]

**To Reproduce**
cd pulsar-io/hbase
mvn -U clean install

**Expected behavior**
Expected a successful build. 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Since javax.el:3.0.1-b06 is now published, we can simply add dependencyManagement for this artifact, and override the dependent version specified by the transitive dependent poms.

**Comment by MarvinCai** [comment]
@klwilson227 
see https://github.com/apache/pulsar/issues/9332

**Comment by MarvinCai** [comment]
Spring repo is already removed: https://github.com/apache/pulsar/pull/9280, please rebase on the latest master.
