### ISSUE TITLE
Pulsar reader doesn't return correct last message with startMessageIdInclusive()

### ISSUE THREAD

**Issue by maimom1924** [apache/pulsar#9330]
I want to read last message from topic "A"  by using Pulsar Reader as shown in below code:

```
Reader<byte[]> reader= pulsarClient.newReader()
                    .topic("A")
                    .startMessageIdInclusive()
                    .startMessageId(MessageId.latest)
                    .create();
if(reader.hasMessageAvailable()) {
    Message<byte[]> msg= reader.readNext();
}
```
Before executing the above code, I have produced many messages on that topic and as the result:
- The `msg` that I get here is not the last message but `the last message - 1` when I add ` .startMessageIdInclusive()`
- Without adding ` .startMessageIdInclusive()`, `reader.hasMessageAvailable()` will return false. 

Pulsar version that I used:
- Version of pulsar jar: 2.5.0
-  Version of pulsar for run my pulsar instance: 2.7.0

**Comment by zymap** [comment]
@maimom1924 Looks like this issue already addressed by this PR https://github.com/apache/pulsar/pull/6362. You can try with 2.5.1 or higher version to test it.

**Comment by codelipenghui** [comment]
@maimom1924 @zymap I will close this issue first, feel free to reopen it if needed.

**Comment by maimom1924** [comment]
Dear sir/madam,

Thank you so much for your help and support. I tried to test with version
2.5.1 but when there is no message on the topic and I call the
reader.hasMessageAvailable(),  I got true value. Could you please help
check on this?

Regards,
Mai Mom

Reader<byte[]> reader = pulsarClient.newReader()
        .topic(config.getStateTopic())
        .startMessageId(MessageId.latest)
        .startMessageIdInclusive()
        .create();
boolean hasMessage = reader.hasMessageAvailable();

**Comment by zymap** [comment]
@maimom1924 I think it's the right behavior because you specified the `startMessageIdInclusive` which means you can read out the last message.

**Comment by maimom1924** [comment]
so even though there is no message, that should return true, right?

**Comment by zymap** [comment]
Yes. After reading the last message, then the `reader. hasMessageAvailable` will return false.

**Comment by maimom1924** [comment]
@zymap I mean that the topic is completely empty, so the `reader. hasMessageAvailable` should return false, right? but I got true value.

**Comment by zymap** [comment]
@maimom1924 

```
        PulsarAdmin admin = PulsarAdmin.builder()
            .serviceHttpUrl("http://localhost:8080")
            .build();
        admin.topics().createNonPartitionedTopic("test");

        PulsarClient client = PulsarClient.builder()
            .serviceUrl("pulsar://localhost:6650")
            .build();

        Reader reader = client.newReader()
            .topic("test")
            .startMessageId(MessageId.latest)
            .startMessageIdInclusive()
            .create();

        // there hasn't message available
        System.out.println(reader.hasMessageAvailable());
```

I create a empty topic and it returns false.

**Comment by zymap** [comment]
Sorry for my misunderstanding. Yes, if the topic is empty, it should return false. 

I found there has some PRs are fixing this issue: #9316 and #8735

**Comment by adrianog** [comment]
How do you use this in python? I see no provision for it.
