### ISSUE TITLE
Maven profile <core-modules> install problem

### ISSUE THREAD

**Issue by nchuxyz** [apache/pulsar#9332]
I build pulsar from source for the first time,
mvn -DskipTests install -Pcore-modules
it throws an error like this:
[INFO] Pulsar IO :: Kafka Connect Adaptor ................. FAILURE [ 11.475 s]
Could not transfer artifact org.apache.pulsar:kafka-connect-avro-converter-shaded:pom:2.8.0-SNAPSHOT from/to spring-plugins-release (https://repo.spring.io/plugins-release/): Not authorized -> [Help 1]

**Maybe "kafka-connect-avro-converter-shaded" module should be added to the "core-modules" profile?
 (for the user who never use "main" profile to perform a full build before)**

**Comment by MarvinCai** [comment]
probably related to this: https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020

**Comment by MarvinCai** [comment]
@nchuxyz 
remove the spring repo
   ```
 <repository>
      <id>spring-plugins-release</id>
      <url>https://repo.spring.io/plugins-release/</url>
    </repository>
```
from root pom.xml solve the problem, you can give it a try.

**Comment by MarvinCai** [comment]
@sijie Should we just remove the spring repo?

**Comment by nchuxyz** [comment]
It works.
Thanks a lot

**Comment by sijie** [comment]
@MarvinCai I think so.

**Comment by MarvinCai** [comment]
@sijie It's happened to be removed by this pr: https://github.com/apache/pulsar/pull/9280, I think no additional action needed.

**Comment by ni-ze** [comment]
Failed to read artifact descriptor for net.minidev:json-smart:jar:2.3-SNAPSHOT: Could not transfer artifact net.minidev:json-smart:pom:2.3-SNAPSHOT from/to spring-plugins-release (https://repo.spring.io/plugins-release/): Not authorized

**Comment by ni-ze** [comment]
> Failed to read artifact descriptor for net.minidev:json-smart:jar:2.3-SNAPSHOT: Could not transfer artifact net.minidev:json-smart:pom:2.3-SNAPSHOT from/to spring-plugins-release (https://repo.spring.io/plugins-release/): Not authorized

------------
this problem occur in branch 2.7.0

**Comment by eolivelli** [comment]
We could cherry pick #9280 to branch-2.7.0, that repo was useless
