### ISSUE TITLE
Provide a sink/source connector for AMQP-1.0.0

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#9333]
Pulsar supports RabbitMQ sink and source, But RabbitMQ support AMQP_0-9-1, It would be great if Pulsar support AMQP 1.0 connector:
https://pulsar.apache.org/docs/en/io-overview/
https://pulsar.apache.org/docs/en/io-rabbitmq-source/#configuration
https://github.com/apache/pulsar/tree/master/pulsar-io/rabbitmq

And [Qpid](https://qpid.apache.org/) Support AMQP 1.0.0, we could use it to do the test.

Define of done:
- code ready.
- test added.
- doc added.

**Comment by wfnuser** [comment]
I would like to have try. You can assign it to me. 😄

**Comment by jiazhai** [comment]
Thanks a lot . @wfnuser

**Comment by codelipenghui** [comment]
@jiazhai @wfnuser We are planning to move all the connectors out of the pulsar main repo. Here is the proposal https://github.com/apache/pulsar/wiki/PIP-62%3A-Move-connectors%2C-adapters-and-Pulsar-Presto-to-separate-repositories you can get more details here. I think you can create an external repo to maintain the AMQP-1.0.0 connector first, after the PIP-62 completed, we can move back to the https://github.com/apache/pulsar-adapters. Is it works for you?

**Comment by jiazhai** [comment]
Ok, I will close this issue currently.
