### ISSUE TITLE
Setting Version of Python Function

### ISSUE THREAD

**Issue by Svade905** [apache/pulsar#9404]
#### Expected behavior

Upon getting a deployed function's info using the pulsar-admin tool, the version of the function is not outputted. I'm expecting the version to be outputted.

#### Actual behavior

No version is outputted of the deployed function. I'm wondering where the version info is pulled from when deploying a pulsar function written in Python and when deployed using the .py file.

Where do I set the version of the pulsar function so that when its deployed, the version number is set in Pulsar for that function?

#### System configuration
**Pulsar version**: 2.7.0

**Comment by freeznet** [comment]
I think [PIP 50](https://github.com/apache/pulsar/wiki/PIP-50%3A-Package-Management) already give a solution to this issue. Once package management is released, user can define and manage function version by package.
You can also check the pre-released version's document here: http://pulsar.apache.org/docs/en/next/admin-api-packages/
