### ISSUE TITLE
[Doc] Improve documentation on how to build python client wheels

### ISSUE THREAD

**Issue by vkvm** [apache/pulsar#9410]
## Problem

There are several scripts involved. As a new user I fumbled my way through figuring what I needed to run in order to get a python 3.9 wheel built. See PR #9389 . I also fixed a couple of minor issues in the process.

## Desired outcome

The goal is to make it easier to do this for new or existing python versions without any surprises. This may involve more than documentation -- for example some refactoring of the scripts.

**Comment by jiazhai** [comment]
Thanks @vkvm for tracking this issue.

**Comment by Anonymitaet** [comment]
Hi @vkvm, since you did the code job, would you like to add the doc correspondingly? Many thanks

**Comment by Anonymitaet** [comment]
Hi @vkvm, thanks for your work, any progress about the doc?

**Comment by Anonymitaet** [comment]
Hi @vkvm, would you like to add docs accordingly? Then I can help review, thanks

**Comment by Anonymitaet** [comment]
Hi @vkvm, would you like to add docs accordingly? Then I can help review, thanks

**Comment by vkvm** [comment]
Hi @Anonymitaet - I will work on it later this week.

**Comment by Anonymitaet** [comment]
Hi @vkvm  any progress on the docs? I would like to help review, thanks

**Comment by Anonymitaet** [comment]
Hi @vkvm any progress on the docs? We would like to help review, thanks

**Comment by Anonymitaet** [comment]
Hi @momo-jun can you follow up on this doc? Thanks

**Comment by BewareMyPower** [comment]
Since #15024 adds another script to build Python wheel files for macOS, this PR is used to track documents of these two scripts.
- pulsar-client-cpp/docker/build-wheels.sh
- pulsar-client-cpp/python/build-mac-wheels.sh

**Comment by momo-jun** [comment]
Hi @BewareMyPower any updates on this issue or can you pls share your updated plan? Thanks.
Just a quick follow-up because this is involved in 2.11 release.

**Comment by BewareMyPower** [comment]
No update yet.

**Comment by tisonkun** [comment]
Closed as stale. The development of the Python client has been permanently moved to https://github.com/apache/pulsar-client-python. If this is still relevant, please open an issue there.

This can be superseded by https://github.com/apache/pulsar/issues/17918.
