### ISSUE TITLE
[Doc] Optimize helm deploy description about the first deployment

### ISSUE THREAD

**Issue by dragonls** [apache/pulsar#9416]
# Problem
For the first deployment using helm, the command `helm upgrade --install pulsar apache/pulsar --timeout 10m --set [your configuration options]` in current document can not deploy pulsar cluster sucessfully.

The bookie pod will be blocked at `Init:0/1` satus, waiting `bin/bookkeeper shell whatisinstanceid`.

The `--set initialize=true` option is necessary for initializing bookie and pulsar cluster meta.

# Solution
Add `--set initialize=true` option.

**Comment by Anonymitaet** [comment]
Hi @dragonls, this option is documented [here](https://pulsar.apache.org/docs/en/next/kubernetes-helm/#step-1-install-pulsar-helm-chart) as below.

![image](https://user-images.githubusercontent.com/50226895/106727757-c132ae00-6646-11eb-945d-d8f6abc33233.png)

Thanks for your suggestion, we can add the note [here](https://pulsar.apache.org/docs/en/next/helm-deploy/) as well.

**Comment by dragonls** [comment]
@Anonymitaet Thanks for reminding.

The `Run Pulsar in Kubernetes` doc is more likely to be the tutorial doc for k8s, using `examples/value-minikube.yaml`.

If we can add the note in `Deployment` doc, it can be a good point to note the user which is beginner of the helm deployment.

**Comment by Anonymitaet** [comment]
Resolve in https://github.com/apache/pulsar/pull/9417
