### ISSUE TITLE
Force delete subscription is not working

### ISSUE THREAD

**Issue by munir131** [apache/pulsar#9477]
**Describe the bug**
There is provision in admin API to force delete subscription. But, when I am passing ***force=true*** in querystring I am getting response with a 204 status code. But, when checking the subscription list, that subscription is still there.

**To Reproduce**
1. Run pulsar
2. Create producer & consumer on that topic. Here I used pulsar-client-go 2.3.0
3. Now call Delete subscription. e.g `localhost:8080/admin/v2/persistent/public/default/topic-1/subscription/my-subscription-name?force=true`
4. Now check using call to list subscription. e.g `localhost:8080/admin/v2/persistent/public/default/topic-1/subscriptions`

**Expected behavior**
It should delete subscription or return error instead of 204 status code in case of error

**Screenshots**
![delete-subscription](https://user-images.githubusercontent.com/6319375/106870498-31990800-66f7-11eb-83de-0bbf8c673d3d.png)
![get-subscriptions](https://user-images.githubusercontent.com/6319375/106870500-32319e80-66f7-11eb-905b-ddee35ab4fd5.png)

**Desktop (please complete the following information):**
 - OS: NA - Official docker image

**Additional context**
Pulsar version: 2.7.0
Env: Docker
Type: Standalone

**Comment by xxxxpenny** [comment]
If you always run the consumer and use the API to force unsubscribe, the consumer will resubscribe. Maybe this is the reason for this problem? This problem is reproduced using the python client
This is python consumer log
```
2021-02-04 21:12:53.678 INFO  [0x70000ae31000] ConsumerImpl:864 | Broker notification of Closed consumer: 0
2021-02-04 21:12:53.678 INFO  [0x70000ae31000] HandlerBase:131 | [persistent://public/default/my-topic, my-sub, 0] Schedule reconnection in 0.1 s
2021-02-04 21:12:53.782 INFO  [0x70000ae31000] HandlerBase:54 | [persistent://public/default/my-topic, my-sub, 0] Getting connection from pool
2021-02-04 21:12:53.843 INFO  [0x70000ae31000] ConsumerImpl:214 | [persistent://public/default/my-topic, my-sub, 0] Created consumer on broker [[::1]:65521 -> [::1]:6650]
```

**Comment by munir131** [comment]
@xxxxpenny I already removed all permissions from that topic. So, consumer must not be resubscribed. If I am restarting consumer then I am getting an error that your token is unauthorized. Same thing is happening when I have an active producer and try to force delete the topic.

**Comment by codelipenghui** [comment]
@munir131 Have you closed all the consumers under the subscription? By default, the subscription will be  created automatically when the active consumer reconnects to the broker.

**Comment by munir131** [comment]
@codelipenghui No. I haven't closed all the consumers. Consumers can be run on many systems which are not accessible sometime. Doesn't control should be in pulsar server?
You mentioned that 
```By default, the subscription will be created automatically when the active consumer reconnects to the broker.```

Doesn't consumer have to reauthenticate for create consumer. I already removed all permissions then how consumer can create new subscription?

**Comment by codelipenghui** [comment]
Interesting, you can check the topic stats through the pulsar-admin  `bin/pulsar-admin topics stats`, so that you can get the `connectedSince` of the consumer. this can help to determine if the consumer reconnects to the broker.

**Comment by munir131** [comment]
@codelipenghui Thanks for the quick responses. I verified that 2.7.3 and it is working perfectly now.

**Comment by ladhadeepak** [comment]
Hi @munir131, @codelipenghui ,

I'm using v2.10.1 and facing the same issue. I am trying to delete the subscription using the **force** option still it gets listed in the subscriptions list. In my case as well, there are consumers across the servers, and hence not possible to close them all before invoking the deleteSubscription method.

Can you please let me know how did you resolve this issue?

Thanks.

**Comment by ladhadeepak** [comment]
The javadoc entry for **deleteSubscription** with force says -

_**Delete a persistent subscription from a topic. There should not be any active consumers on the subscription. Force flag deletes subscription forcefully by closing all active consumers.**_

So, I would assume that the call would close all the active consumers first and then try to delete the subscription. If that is the case then there is no active consumer remaining to try to subscribe again.

**Comment by shgattu** [comment]
Any update on this issue? Following the chain

**Comment by shgattu** [comment]
@ladhadeepak ,
Did you open a. new issue to track this? Can you update

**Comment by ladhadeepak** [comment]
Hi Shwetha,

I have not logged a new issue.

Thanks.
