### ISSUE TITLE
Support for nested types in pulsar.schema.Record

### ISSUE THREAD

**Issue by matthewgettemy** [apache/pulsar#9483]
Are nested types supported in pulsar.schema.Record?

An example payload that I'd like to de/serialize is
`values={"A": [1.1, 2.2, 3.3], "B": [5.5, 6.6, 7.7]}`

### Minimal example:

```
from pulsar.schema import AvroSchema
from pulsar.schema import Record
from pulsar.schema import Map
from pulsar.schema import Array
from pulsar.schema import Float

class Apex(Record):
    values = Map(Array(Float()))

client = pulsar.Client("pulsar://localhost:6650")
producer = client.create_producer("example", schema=AvroSchema(Apex))
```

### Produces:

2021-02-04 08:53:45.513 INFO  [140206084425536] ConnectionPool:85 | Created connection for pulsar://localhost:6650
2021-02-04 08:53:45.515 INFO  [140205875353344] ClientConnection:353 | [127.0.0.1:54658 -> 127.0.0.1:6650] Connected to broker
2021-02-04 08:53:45.522 INFO  [140205875353344] HandlerBase:54 | [persistent://public/default/example, ] Getting connection from pool
2021-02-04 08:53:45.539 WARN  [140205875353344] ClientConnection:960 | [127.0.0.1:54658 -> 127.0.0.1:6650] Received error response from server: IncompatibleSchema -- req_id: 0
2021-02-04 08:53:45.539 ERROR [140205875353344] ProducerImpl:234 | [persistent://public/default/example, ] Failed to create producer: IncompatibleSchema
2021-02-04 08:53:45.539 INFO  [140205875353344] ProducerImpl:527 | Producer - [persistent://public/default/example, ] , [batching  = off]
Traceback (most recent call last):
  File "producer.py", line 15, in <module>
    producer = client.create_producer("example", schema=AvroSchema(Apex))
  File "/opt/anaconda3/lib/python3.6/site-packages/pulsar/__init__.py", line 562, in create_producer
    p._producer = self._client.create_producer(topic, conf)
**Exception: Pulsar error: IncompatibleSchema**

I'm wondering if I'm specifying the type structure wrong, or is this just not supported?

With the Kafka schema registry, I can setup an avro .json config and specify nested types like Map(Array), but can't figure out how to do it with this interface. If this is not supported I'd be interested in contributing an enhancement for it, if it's agreed it should be supported.

**Comment by codelipenghui** [comment]
@congbobo184 Could you please help take a look at this issue?

**Comment by congbobo184** [comment]
I check the java client can support nested type, can you check the python client @BewareMyPower?  Thanks :)

**Comment by BewareMyPower** [comment]
@congbobo184 OK, I'll take a look.

**Comment by hpvd** [comment]
maybe it should be tested for clients described to have schema support?
see https://github.com/apache/pulsar/wiki/Client-Features-Matrix

**Comment by BewareMyPower** [comment]
Yeah, I also tested for Python client, the nested types don't work. I guess it's an issue with Python `fastavro` library.

**Comment by BewareMyPower** [comment]
I've added more detail logs.

| values | error message |
| :- | :- |
| `Array(Array(Float()))` | `org.apache.avro.SchemaParseException: Undefined name: "array"` |
| `Map(Array(Float()))` | `org.apache.avro.SchemaParseException: Undefined name: "array"` |
| `Map(Map(Float()))` | `org.apache.avro.SchemaParseException: Undefined name: "map"` |
| `Array(Map(Float()))` | `org.apache.avro.SchemaParseException: Undefined name: "map"` |

The error message is thrown by `Schema.Parser#parse` in broker side.

```java
        try {
            Schema.Parser avroSchemaParser = new Schema.Parser();
            avroSchemaParser.setValidateDefaults(false);
            avroSchemaParser.parse(new String(data, UTF_8)); // failed
```

It looks like when the schema bytes generated by Python client cannot be parsed by broker.

**Comment by eolivelli** [comment]
I cited this problem in this issue
https://github.com/apache/pulsar/issues/9004

It was my plan to work on adding support for Array and Map as follow up work for #9004 (that in turn has an open PR)

**Comment by BewareMyPower** [comment]
From the comparison between Java and Python. It looks like Python client doesn't generate a right schema bytes. Here's the Java client code for tests:

```java
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
class Apex {
    private Map<String, List<String>> values;
}

public class SchemaDemo {
    public static void main(String[] args) {
        try (PulsarClient pulsarClient = PulsarClient.builder().serviceUrl("pulsar://localhost:6650").build()) {
            Producer<Apex> producer = pulsarClient
                    .newProducer(Schema.AVRO(Apex.class))
                    .topic("example")
                    .create();
            producer.close();
        } catch (PulsarClientException e) {
            e.printStackTrace();
        }
    }
}
```

And it works well.

Compare these two schema string (they are both formatted).

1. Java

```json
{
  "type": "record",
  "name": "Apex",
  "fields": [
    {
      "name": "values",
      "type": [
        "null",
        {
          "type": "map",
          "values": {
            "type": "array",
            "items": "string",
            "java-class": "java.util.List"
          }
        }
      ],
      "default": null
    }
  ]
}
```

2. Python

```json
{
  "name": "Apex",
  "type": "record",
  "fields": [
    {
      "name": "values",
      "type": [
        "null",
        {
          "type": "map",
          "values": "array"
        }
      ]
    }
  ]
}
```

The key difference is the type of array item, in Python it's just

```json
          "values": "array"
```

But in Java it's

```json
          "values": {
            "type": "array",
            "items": "string",
            "java-class": "java.util.List"
          }
```
