### ISSUE TITLE
Check message backlog size using Reader interface

### ISSUE THREAD

**Issue by hanguyen6** [apache/pulsar#9488]
I am using reader interface to read topic starting from a messageId. 

When I check topicStats the backlogSize seems increasing, even after the reader completed. 

Is it possible  to calculate message back log size when reader interface is used ? Like comparing with current messageId and latest messageId ?

**Comment by MarvinCai** [comment]
I think we can probably add a admin API to calculate backlog size given a current position.

**Comment by gaozhangmin** [comment]
please assign to me, if no one working on this
