### ISSUE TITLE
Allow pulsar-perf to enable or disable batch index acknowledgment.

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#9507]
**Is your enhancement request related to a problem? Please describe.**
PIP-45 https://github.com/apache/pulsar/wiki/PIP-54:-Support-acknowledgment-at-batch-index-level introduced batch index level acknowledge but the pulsar-perf client does not support to enable it for the consumer. It's better to allow users to do the performance test for the batch index acknowledgment.

**Describe the solution you'd like**
Add `--batch-index-ack` for the `pulsar-perf consume` command and keep it as false by default.

**Comment by limingnihao** [comment]
I will fix this issue, please assign it to me.
