### ISSUE TITLE
Add metrics for the cursor ack state

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#9535]
**Is your enhancement request related to a problem? Please describe.**

The acknowledgment state is persistent to the Ledger or Zookeeper(can't persistent to the Ledger). But currently, we don't have any metrics for the persistence of the acknowledgment state such as the total count of the success/failed persistent operations.

**Describe the solution you'd like**
Add metrics for the ManagedCursor:

brk_ml_cursor_persistence_count(ml_name="", cursor_name="", persistent_type:"ledger/zookeeper")

And we should provide a way to enable or disable the per cursor metrics since if enabled the cursor metrics, this will generate many metrics.

exposeCursorMetricsInPrometheus=true (since the topic level metrics exposed by default, we can keep consistent with the topic level metrics)

**Comment by limingnihao** [comment]
I will fix this issue, please assign it to me.
