### ISSUE TITLE
Disable message negative ack for Key_Shared subscription type.

### ISSUE THREAD

**Issue by MarvinCai** [apache/pulsar#9582]
The message negative ack will break the message ordering dispatch guarantee, Key_Shared is an ordering dispatch guarantee subscription, so we should avoid the message negative ack for the Key_Shared subscription.

**Comment by MonicaMagoniCom** [comment]
I also found this issue using Pulsar. We had to insert a timestamp to maintain the order of messages.

**Comment by MarvinCai** [comment]
@MonicaMagoniCom Hi, please see the discussion in this pr: https://github.com/apache/pulsar/pull/9583
I think we decided to still keep the ability for Key_Shared to do negative acknowledge since it's not all about ordering, e.g. guarantee message of same key go to same consumer, instead we added document to warn user that doing negative ack on order subscription type(exclusive, failover, key_shared) can cause message arrives out of original order.
