### ISSUE TITLE
C++ client support for FreeBSD

### ISSUE THREAD

**Issue by sholla** [apache/pulsar#959]
#### Expected behavior
C++ client should build on FreeBSD. Would be good to have support for FreeBSD at least for the client libs.

#### Actual behavior
Various compile errors with NULL and then CRC32.

#### Steps to reproduce
Run a build on FreeBSD

#### System configuration
**Pulsar version**: x.y
I think it is the latest from github i.e. 1.22

**Comment by sijie** [comment]
@sholla can you provide more details about the errors you encountered?

**Comment by tisonkun** [comment]
C++ Client is permanently moved to https://github.com/apache/pulsar-client-cpp.

If this is still relevant, please open an issue there.
