### ISSUE TITLE
Could not find a version that satisfies the requirement pulsar-client==2.7.0

### ISSUE THREAD

**Issue by 0x5e** [apache/pulsar#9594]
**Describe the bug**
Python pulsar-client can't be installed on both Raspberry Pi 4B and M1 MacBook Pro.

**To Reproduce**
```shell
$ pip3 install pulsar-client==2.7.0
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://mirrors.cloud.tencent.com/pypi/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement pulsar-client==2.7.0
ERROR: No matching distribution found for pulsar-client==2.7.0
```

**Desktop (please complete the following information):**
MacBook Pro (13-inch, M1, 2020): 
- OS: macOS Big Sur 11.1 (20C69)
- Python: 3.9.1
- Arch: arm64

Raspberry Pi 4 Model B:
- OS: Raspbian GNU/Linux 10 (buster)
- Python: 3.5.2
- Arch: armv7l

I've tried to build from myself for several days, but many environment issues happened and I finally give up. Could you please provide these arm processor packages? Thanks very very much :-)

**Comment by aahmed-se** [comment]
You can try this, this is what I use to build and distribute python libs
https://github.com/aahmed-se/spack/wiki/Pulsar-python-wheel-spack-instructions-for-macosx

**Comment by TheNotary** [comment]
I noticed this issue too.  You can debug the problem by viewing the files uploaded to [pypi](https://pypi.org/project/pulsar-client/#files).  You'll see file names such as `pulsar_client-2.7.0-cp38-cp38-macosx_10_15_x86_64.whl` wherein the cp38 means C Python 3.8.  They don't have a package for C Python 3.9 or 3.5 (your current python version).  As a work around until they perform more builds, you can use `pyenv` to install Python 3.8 on your mac, and then pip should work.  Use similar debugging to see if you can get a distribution to the Pi ok (Python 3.8 should work on "manylinux").

**Comment by lhotari** [comment]
> I've tried to build from myself for several days, but many environment issues happened and I finally give up. 

btw. One such issue, #7477,  was recently fixed by #9569 .

**Comment by linusmotu** [comment]
Anyone have any success with this? I wanted to try and compile on the Raspberry Pi but I don't know where to even start.

**Comment by nishantvas** [comment]
Did anyone have any success with this ? I've been trying different means to install the python pulsar-client but haven't been able to.

If there is a specific version of python and the pulsar-client library which works, I'm more than happy to try that combination out.

**Comment by lassos** [comment]
i am also always getting errors trying to install pulsar-client, onnxruntime, curl-cffi below, tried 2 days to solve. installed pyhton 9, 3.11.10, 3.12., nothing changed

tried in a env

`/usr/local/bin/python3.11 -m venv ./testvenv
virtualenv testvenv
source ./testvenv/bin/activate`

triend to install all manually like 

`/usr/local/bin/pip3.11   install --no-cache-dir python-dotenv  
/usr/local/bin/python3.11 -m pip install python-dotenv
/usr/local/bin/pip3.11 install "pydantic<2" 
/usr/local/bin/pip3.11 install "google-api-python-client" 
/usr/local/bin/pip3.11 install install --upgrade google-api-python-client`

tried to install dependencies via poetry install. so cant get autochatgpt to run

system: debian bullseye

uname -a 
5.10.0-26-686-pae #1 SMP Debian 5.10.197-1 (2023-09-29) i686 GNU/Linux

`Poetry (version 1.8.2)
(testvenv) root@lars-multihome /usr/share/Auto-GPT/AutoGPT/autogpts/autogpt > CXX=g++-10 CC=gcc-10 /root/.local/bin/poetry install
Installing dependencies from lock file

Package operations: 85 installs, 1 update, 0 removals

  - Installing curl-cffi (0.6.2): Failed

  IsolatedBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  Traceback (most recent call last):
    File "/root/.local/share/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
      main()
    File "/root/.local/share/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/root/.local/share/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 134, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmp_y8h57ne/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmp_y8h57ne/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/tmp/tmp_y8h57ne/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 16, in <module>
    File "/tmp/tmp_y8h57ne/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 104, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmp_y8h57ne/.venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 146, in setup
      _setup_distribution = dist = klass(attrs)
                                   ^^^^^^^^^^^^
    File "/tmp/tmp_y8h57ne/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 307, in __init__
      _Distribution.__init__(self, dist_attrs)
    File "/tmp/tmp_y8h57ne/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 284, in __init__
      self.finalize_options()
    File "/tmp/tmp_y8h57ne/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 658, in finalize_options
      ep(self)
    File "/tmp/tmp_y8h57ne/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 678, in _finalize_setup_keywords
      ep.load()(self, ep.name, value)
    File "/tmp/tmp_y8h57ne/.venv/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 216, in cffi_modules
      add_cffi_module(dist, cffi_module)
    File "/tmp/tmp_y8h57ne/.venv/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
      execfile(build_file_name, mod_vars)
    File "/tmp/tmp_y8h57ne/.venv/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 25, in execfile
      exec(code, glob, glob)
    File "scripts/build.py", line 31, in <module>
      arch = detect_arch()
             ^^^^^^^^^^^^^
    File "scripts/build.py", line 28, in detect_arch
      raise Exception(f"Unsupported arch: {uname}")
  Exception: Unsupported arch: uname_result(system='Linux', node='lars-multihome', release='5.10.0-26-686-pae', version='#1 SMP Debian 5.10.197-1 (2023-09-29)', machine='i686')


  at ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chef.py:82 in _prepare
       78│
       79│             error = IsolatedBuildError("\n\n".join(message_parts))
       80│
       81│         if error is not None:
    →  82│             raise error from None
       83│
       84│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
       85│         from poetry.core.packages.utils.link import Link
       86│

Note: This error originates from the build backend, and is likely not a problem with poetry but with curl-cffi (0.6.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "curl-cffi (==0.6.2)"'.

  - Installing onnxruntime (1.17.1): Failed

  RuntimeError

  Unable to find installation candidates for onnxruntime (1.17.1)

  at ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chooser.py:86 in choose_for
       82│
       83│             links.append(link)
       84│
       85│         if not links:
    →  86│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       87│
       88│         # Get the best link
       89│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       90│

Cannot install onnxruntime.

  - Installing pulsar-client (3.4.0): Failed

  RuntimeError

  Unable to find installation candidates for pulsar-client (3.4.0)

  at ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chooser.py:86 in choose_for
       82│
       83│             links.append(link)
       84│
       85│         if not links:
    →  86│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       87│
       88│         # Get the best link
       89│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       90│

Cannot install pulsar-client.`
