### ISSUE TITLE
Add api to delete retained message for a topic

### ISSUE THREAD

**Issue by rvashishth** [apache/pulsar#9597]
**Is your enhancement request related to a problem? Please describe.**
When retention policies are applied on a topic. Messages acknowledged for all subscription are kept on topic storage because of retention policies. 

At time we are required to clear up all data from topic storage. 

**Describe the solution you'd like**
There should be an api, which allow api user to delete all acknowledged message from topic storage.

**Describe alternatives you've considered**
NA

**Additional context**
Below storage size contains the message retained on topic due to retention policies. These messages were already consumed by subscribers.  We need a way to delete these messages only. while keep the topic around.

<img width="1833" alt="Screenshot 2021-02-16 at 4 41 24 PM" src="https://user-images.githubusercontent.com/6093884/108056964-fba13f80-7077-11eb-9a54-6ea99ac3885f.png">

**Comment by codelipenghui** [comment]
@rvashishth You can try to delete the topic directly. This will delete the ledgers of the topic.

**Comment by rvashishth** [comment]
At least for our use case we can not delete topics but still wants to delete messages. I am not sure if others has the similar use case or not.

**Comment by codelipenghui** [comment]
@rvashishth Ok, make sense. It's better to support drop the data of the topic.

**Comment by MarvinCai** [comment]
@jangwind 
You're using `managedLedgerFactory.asyncDelete` which is delete managed ledger backing the topic and topic metadata, which is essential delete the topic.
You can take a look at `ManagedLedgerImpl.internalTrimConsumedLedgers` which only delete the fully consumed ledger from topic.

**Comment by rvashishth** [comment]
@MarvinCai - so there is no way to simple truncate/delete all data published to a topic irrespective of if those message are consumed by someone or not?
