### ISSUE TITLE
Admin CLI: namespaces set-subscription-expiration-time and get-subscription-expiration-time operations are not documented on web page

### ISSUE THREAD

**Issue by frankjkelly** [apache/pulsar#9599]
**Describe the bug**

**To Reproduce**
1. Downloaded Pulsar 2.7.0 and install it (`gunzip` and `tar -xvf`)
2. 
```
$ cd apache-pulsar-2.7.0/bin
$ ./pulsar-admin namespaces | grep expi
Warning: Nashorn engine is planned to be removed from a future JDK release
    get-subscription-expiration-time      Get subscription expiration time for 
      Usage: get-subscription-expiration-time tenant/namespace
    set-subscription-expiration-time      Set subscription expiration time for 
      Usage: set-subscription-expiration-time [options] tenant/namespace
            Subscription expiration time in minutes
```
No such documentation here --> https://pulsar.apache.org/docs/en/pulsar-admin/

**Expected behavior**
Documentation for `set-subscription-expiration-time` and `get-subscription-expiration-time` are present here
 https://pulsar.apache.org/docs/en/pulsar-admin/

**Additional context**

**Comment by RobertIndie** [comment]
Thanks for reporting this issue. I have added a pr #9611 that fixes this issue.

**Comment by frankjkelly** [comment]
That is excellent - thanks so much!
