### ISSUE TITLE
SubscriptionInitialPosition.Latest should not fetch message from retention storage

### ISSUE THREAD

**Issue by rvashishth** [apache/pulsar#9603]
**Describe the bug**
A subscription with default/latest initial position gets data produces(and retained) before subscription was created. A subscription created with initial position latest acts as if it's a subscription with earliest position.  

**To Reproduce**
1. Create a topic with retention by size/time policy
2. Produce message on this topic. Since no subscription exist, these messages will be retained on topic due to retention policy.
3. Create a subscription with [default initial position: Latest](https://github.com/apache/pulsar/blob/301d42ce04ceb20797cc2a60267e6ec39ff05e95/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L2025) using pulsar admin rest api
4. Subscription backlog contains messages produced before subscription was created

**Expected behavior**
A subscription created with SubscriptionInitialPosition.Latest should not get message produced before the subscription was created

**Screenshots**
NA

**Desktop (please complete the following information):**
 - Pulsar version 2.7.0

**Additional context**
NA

**Comment by rvashishth** [comment]
Refer [this](https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1613041751376900) slack thread

**Comment by rvashishth** [comment]
Following are the example topic stats after running through error steps 
1. create topic 
2. produce message 
3. create subscription 

admin/v2/persistent/{tenant}/{namespace}/{topic}/internalStats
```
{
    "entriesAddedCounter": 2,
    "numberOfEntries": 2,
    "totalSize": 140,
    "currentLedgerEntries": 2,
    "currentLedgerSize": 140,
    "lastLedgerCreatedTimestamp": "2021-02-15T11:09:08.485Z",
    "waitingCursorsCount": 0,
    "pendingAddEntriesCount": 0,
    "lastConfirmedEntry": "60:1",
    "state": "LedgerOpened",
    "ledgers": [
        {
            "ledgerId": 60,
            "entries": 0,
            "size": 0,
            "offloaded": false
        }
    ],
    "cursors": {
        "subscription-1": {
            "markDeletePosition": "60:-1",
            "readPosition": "60:-1",
            "waitingReadOp": false,
            "pendingReadOps": 0,
            "messagesConsumedCounter": 0,
            "cursorLedger": 61,
            "cursorLedgerLastEntry": 1,
            "individuallyDeletedMessages": "[]",
            "lastLedgerSwitchTimestamp": "2021-02-15T11:45:53.569Z",
            "state": "Open",
            "numberOfEntriesSinceFirstNotAckedMessage": 0,
            "totalNonContiguousDeletedMessagesRange": 0,
            "properties": {}
        }
    },
    "compactedLedger": {
        "ledgerId": -1,
        "entries": -1,
        "size": -1,
        "offloaded": false
    }
}
```

/admin/v2/persistent/{tenant}/{namespace}/{topic}/stats

```
{
    "msgRateIn": 0.0,
    "msgThroughputIn": 0.0,
    "msgRateOut": 0.0,
    "msgThroughputOut": 0.0,
    "bytesInCounter": 140,
    "msgInCounter": 2,
    "bytesOutCounter": 0,
    "msgOutCounter": 0,
    "averageMsgSize": 0.0,
    "msgChunkPublished": false,
    "storageSize": 140,
    "backlogSize": 140,
    "publishers": [],
    "subscriptions": {
        "subscription-1": {
            "msgRateOut": 0.0,
            "msgThroughputOut": 0.0,
            "bytesOutCounter": 0,
            "msgOutCounter": 0,
            "msgRateRedeliver": 0.0,
            "chuckedMessageRate": 0,
            "msgBacklog": 2,
            "msgBacklogNoDelayed": 2,
            "blockedSubscriptionOnUnackedMsgs": false,
            "msgDelayed": 0,
            "unackedMessages": 0,
            "msgRateExpired": 0.0,
            "lastExpireTimestamp": 1613390505451,
            "lastConsumedFlowTimestamp": 0,
            "lastConsumedTimestamp": 0,
            "lastAckedTimestamp": 0,
            "consumers": [],
            "isDurable": true,
            "isReplicated": false,
            "consumersAfterMarkDeletePosition": {}
        }
    },
    "replication": {},
    "deduplicationStatus": "Disabled"
}
```

**Comment by codelipenghui** [comment]
@rvashishth I think this issue is related to https://github.com/apache/pulsar/pull/9444. The code that you mentioned before is based on the master branch. I think branch-2.7 uses the earliest position as the default subscription position, #9444 changed to the latest in the master branch. You can try the master branch as well.

**Comment by codelipenghui** [comment]
@rvashishth I will close this issue first. If #9444 does not fix this issue, feel free to reopen it.
