### ISSUE TITLE
Pulsar Admin: functions - NullPointerException in case of disabled Pulsar Functions

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#9633]
**Describe the bug**

I see this NullPointerException on the broker logs while issuing "`pulsar-admin sinks available-sinks`"

I have `functionsWorkerEnabled=false` in _broker.conf_

```
java.lang.NullPointerException                                                                                                                                                          │
│ pulsar-broker     at org.apache.pulsar.broker.admin.impl.SinksBase.sinks(SinksBase.java:53) ~[org.apache.pulsar-pulsar-broker-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]                                                 │
│ pulsar-broker     at org.apache.pulsar.broker.admin.impl.SinksBase.getSinkList(SinksBase.java:522) ~[org.apache.pulsar-pulsar-broker-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]     
```

We should return a more user friendly error that explain the problem.

Tested on current master on 2.8.0-SNAPSHOT

**Comment by golden-yang** [comment]
yes, this NullPointerException is  related to `org.apache.pulsar.functions.worker.WorkerService`. When we set `functionsWorkerEnabled=false`, `org.apache.pulsar.broker.PulsarService#getWorkerService` method  will get a 'null', and no parameter verification has been done wherever it is used(This method is cited in eight places, They all have NullPointerException problems). 

Perhaps we should not allow this function to return a null value. May be we should directly throw an exception that does not support this function_worker function.

`    public WorkerService getWorkerService() {
        return functionWorkerService.orElse(null);
    }
`

Please take a look. If this solution is OK, I will propose a PR to fix it.
@eolivelli  Thanks.

**Comment by eolivelli** [comment]
@golden-yang thanks for picking this up

Probably we could simply throw an exception
`public WorkerService getWorkerService() { return functionWorkerService.orElseThrow(....); }`

**Comment by golden-yang** [comment]
Yes.This is what i want to say.
