### ISSUE TITLE
Project-10: Replace local ZooKeeper and cache access from PulsarService and replace with Metadata-store API

### ISSUE THREAD

**Issue by rdhabalia** [apache/pulsar#9644]
### Goal
PulsarService initializes `Local-ZooKeeper` and that is used by multiple components across pulsar-services. Remove local-zk access from dependent component and eventually remove local-zk initialization from the PulsarService.

### Reference
**Component**: Pulsar-Service
**Class-reference**: "- [PulsarServie:: localZkCacheService](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java#L168), [PulsarServie:: localZooKeeperConnectionProvider](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java#L173)
**Affected Modules**: LoadManager: ModularLoadManagerImpl, NamespaceService, OwnershipCache, BookkeeperSchemaStorage

### Notes
1. [PulsarServie:: localZkCacheService](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java#L168), [PulsarServie:: localZooKeeperConnectionProvider](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java#L173) initializes local zk and that is being used by multiple places eg: LoadManager: ModularLoadManagerImpl, NamespaceService, OwnershipCache, BookkeeperSchemaStorage
2. Replace localZK access with Metadata-store resources in those places
3. Remove localZK reference from the PulsarService

**Comment by eolivelli** [comment]
I am picking this up, @rdhabalia please assign to me

**Comment by eolivelli** [comment]
@rdhabalia  @merlimat 
I am taking a look to `ModularLoadManagerImpl`, field `brokerDataCache`

I cannot find a good replacement for `ZooKeeperDataCache`

https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java#L123

Also I see that `MetadataCacheImpl` is not able to set a listener on updates, and in fact it is not setting any watch on the cached zookeeper subtree.

Am I looking to the wrong place ? or is support still missing ?

**Comment by merlimat** [comment]
@eolivelli I actually had this already almost done locally. I just need to get one other PR in first (the locks reacquiring after the session gets re-established).

**Comment by eolivelli** [comment]
Okay. No problem from my side.
Please assign me any ticket from this project that is still not started.

**Comment by rdhabalia** [comment]
@eolivelli would like to take #9645 ?

**Comment by eolivelli** [comment]
@rdhabalia sure
