### ISSUE TITLE
Project-10: Remove ConfigurationCacheService (global-zk + local-zk) cache with Metadata-store API 

### ISSUE THREAD

**Issue by rdhabalia** [apache/pulsar#9645]
### Goal
[ConfigurationCacheService](https://github.com/apache/pulsar/blob/master/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/cache/ConfigurationCacheService.java) keeps local-zk-cache and global-zk-cache which is used by multiple components eg: Broker, Proxy, Discovery-service, WebSocket, etc. #9586 introduced `ConfigurationMetadataCacheService` which is an alternative of `ConfigurationCacheService` and it uses Pulsar meadata-store resources,. So, replace `ConfigurationCacheService` with `ConfigurationMetadataCacheService`.

### Reference
**Component**: [ConfigurationCacheService](https://github.com/apache/pulsar/blob/master/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/cache/ConfigurationCacheService.java)
**Affected Modules**: Broker, Websocket, Discovery, Proxy

### Notes
1. Replace all references of `ConfigurationCacheService` with `ConfigurationMetadataCacheService` across all pulsar components
2. Remove `ConfigurationCacheService` class

**Comment by eolivelli** [comment]
I am picking this up

**Comment by eolivelli** [comment]
@rdhabalia I see that basically `ConfigurationMetadataCacheService` is only a subclass of `ConfigurationCacheService` that owns a `PulsarResources`.
But it is not possible to implement all methods.

I am thinking about using `ConfigurationMetadataCacheService#pulsarResources` and implement into PulsarResources all of the missing resource types.

I wonder if there is a need to have a `ConfigurationMetadataCacheService` class at all, we could use directly `PulsarResources`

Correct ?

**Comment by rdhabalia** [comment]
The only issue in removing `ConfigurationCacheService` is it's used by `AuthorizationProvider::initialize` and part of the contract. We can deprecate it and eventually remove it. 
However, `PulsarAuthorizationProvider` already uses `ConfigurationMetadataCacheService` now. So, yes, we can replace `PulsarResources` with `ConfigurationCacheService` at other places.

> I wonder if there is a need to have a ConfigurationMetadataCacheService class at all, we could use directly PulsarResources

yes. We can directly use `PulsarResources` where `ConfigurationCacheService` is not part of the contract.

**Comment by eolivelli** [comment]
@rdhabalia @merlimat 
I did not make progress on this work, as I am busy with other priorities.

I can move forward but not in time for 2.8 release
