### ISSUE TITLE
incompatible issue between ExplicitLac and message compression

### ISSUE THREAD

**Issue by pointearth** [apache/pulsar#9658]
**Describe the bug**
When I produce some compressed messages to Pulsar, and use ExplicitLac, get an error from the presto server.

**To Reproduce**

I tried to  fix the issue [#7076](https://github.com/apache/pulsar/issues/7076), so:
1. wrote code to produce messages to pulsar.
`producer = pulsarClient.newProducer(JSONSchema.of(Record.class))`
                   ` .topic(topic)`
                   ` .producerName(NAME_CONST.NAME_PRODUCER_ACCOUNT_NORMAL)`
                    `.compressionType(CompressionType.ZSTD)`
                    `.create();`
2.  I changed some config files, one item is:
in conf/presto/catalog/pulsar.properties
`pulsar.bookkeeper-use-v2-protocol=false`
`pulsar.bookkeeper-explicit-interval=10`
3. I got this error in the presto server when I query from the presto client.

you can see:
`io.airlift.compress.zstd.ZstdDecompressor.decompress(ZstdDecompressor.java:60)` 
4. I removed a line code of my message producer.
`//.compressionType(CompressionType.ZSTD)`
it works well.

**Expected behavior**
I guess there is an incompatible issue between ExplicitLac and message compression

**Screenshots**
![image](https://user-images.githubusercontent.com/1859919/108599868-ac884100-73ce-11eb-9d86-b7a009c8f294.png)

**Desktop (please complete the following information):**
 - OS: macos Bigsur(Pulsar 2.7.0), CentOS (Pulsar 2.7.0)

**Additional context**
@codelipenghui

**Comment by codelipenghui** [comment]
Hi @pointearth This issue is fixed by #8990 and it is cherry-picked to branch-2.7. You can build from branch-2.7 or you can use https://github.com/streamnative/pulsar/releases/tag/v2.7.0.8 directly, we have a weekly release for the branch-2.7.

But I found another problem #9666, @gaoran10 is working on this one. Since 2.7.1 will be released soon, so we need to get this fix merged soon.
