### ISSUE TITLE
Backlog quota: allow time-based quota

### ISSUE THREAD

**Issue by flowchartsman** [apache/pulsar#9680]
Retention policies can be set based on size or time limit (or both), while backlog quotas can only be based on size. The recommendations I've gotten are to set backlog quota to be equal to or less than the retention policy, but if the retention policy is based solely on time, the backlog quota cannot be certain to be less than the retention policy.

**Comment by codelipenghui** [comment]
@flowchartsman You can use the message TTL to expire the backlogs of the subscription.

**Comment by flowchartsman** [comment]
There's no backpressure policy applied to TTL though, unless I missed something. Even if I'm combining them, there's no way for me to ensure that backlog is less than TTL.

**Comment by codelipenghui** [comment]
Yes, it needs to combine them to achieve the purpose.

**Comment by flowchartsman** [comment]
It still feels inconsistent. With TTL there is no good backpressure strategy, and I am then still stuck with trying to guess whether or not backlog-quota fits into TTL time or not, since it is only measured in bytes.

This would also then require me to use retention, TTL _and_ backlog quota, and the docs seem to indicate that this is unusual.

**Comment by codelipenghui** [comment]
Yes, the TTL can't achieve the backpressure strategy by the time duration. Thanks for the clarification, I think this should be a new feature, so I will change the label to `type/feature`.

**Comment by MarvinCai** [comment]
I'll try to add this feature.
