### ISSUE TITLE
non-persistent topics don't seem to work with Key_Shared

### ISSUE THREAD

**Issue by megfigura** [apache/pulsar#9703]
**Describe the bug**
With a non-persistent topic, I see messages published in the topic stats, but consumers do not consume them if they use Key_Shared. Other consumer modes work fine.

**To Reproduce**
1. In one window, start consumer: bin/pulsar-client consume --hex -n 0 -s cli -p Earliest -t Key_Shared non-persistent://public/default/test
2. In another window, start producer: bin/pulsar-client produce -m hi,bye -k a_key non-persistent://public/default/test

**Expected behavior**
The consumer should receive the 2 messages, however nothing happens on the consumer side.

Checking the "topic stats" in the admin client shows the consumer is present, and messages are published, but the consumer stays at 0 messages received.

Changing the consumer to Shared works fine, but of course the key doesn't apply.

**Desktop (please complete the following information):**
 - OS: Pulsar docker image, deployed with Helm chart ("pulsar-mini") on Minikube

**Additional context**
I used the latest Helm chart (with Docker images 2.7.0) and deployed it on Minikube following the instructions here: https://pulsar.apache.org/docs/en/kubernetes-helm/

**Comment by MarvinCai** [comment]
Can reproduce the error, I'll fix it.

**Comment by megfigura** [comment]
Hi @MarvinCai, thank you! Do you know at this point if the bug is in the broker or the java client? Thanks!

**Comment by MarvinCai** [comment]
@megfigura  Hi, I verified the bug is in broker.

**Comment by dsm1212** [comment]
This pretty seriously impacts using non-persistent. Do you have any idea how long it might take for a fix? Or if you pin it down maybe you will see a work-around to share. thx

**Comment by MarvinCai** [comment]
Sorry for the delay, was trying to wait for some issue related to test to be fixed first.
I'll fix this soon.
