### ISSUE TITLE
Documentation: Add a feature/defaults chart for each official Client (e.g. Java, Go, Python etc.) so folks can compare/contrast

### ISSUE THREAD

**Issue by frankjkelly** [apache/pulsar#9723]
**Is your enhancement request related to a problem? Please describe.**
As a microservices developer we have folks who use Java, some who use Go and some who use Python etc.
It appears that the clients are on a slightly different feature development timeline and/or have some different defaults.

**Describe the solution you'd like**
Create a matrix/chart of the clients and the various features that each chart supports e.g. 
1. The Java client default batch publish delay is 1ms but in Go it is 10ms. See https://github.com/apache/pulsar-client-go/blob/21541d6d40a6324db7b3952d9e1d392d872ce231/pulsar/producer_impl.go#L36  vs. https://github.com/apache/pulsar/blob/2a1828ca08f096a94b696737e93e84a2bc60a8cc/pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ProducerConfigurationData.java#L158
2. The Go library does not yet support non-durable subscriptions https://github.com/apache/pulsar-client-go/issues/468
3. to my knowledge the Go and Python client do not yet support SNI (could be wrong).

**Describe alternatives you've considered**
Remain as is - creates a lot of onus on the developer as Pulsar (fortunately!) has so many awesome features and settings. 

**Additional context**
N/A

**Comment by hpvd** [comment]
+1 on this.
A good start is already available but not that easy to find:  
https://github.com/apache/pulsar/wiki/Client-Features-Matrix

**Comment by hpvd** [comment]
and there is something more detailled in work, see https://github.com/apache/pulsar/issues/5959#issuecomment-744968387

- it's till now only about comparing the big feature,
- new is the topic  harmonizing the default values
- personal wish for mid-time: feature parity with especially catching up on websocket side

**Comment by Jennifer88huang** [comment]
@frankjkelly @hpvd Thank you for raising the issue, we've summarized the client matrix and Function Features in https://docs.google.com/spreadsheets/d/1iTzn6QnOpTYK8QQHxXRb6a25nvuTNGPPJDdUQHGBUS4/edit#gid=1784579914
I'll upload this sheet on the [Client Feature Matrix page](https://github.com/apache/pulsar/wiki/Client-Features-Matrix) soon.

**Comment by Jennifer88huang** [comment]
If you find anything to be updated, feel free to comment in the google sheet directly.  Thank you very much for your patience and support~

**Comment by hpvd** [comment]
@Jennifer88huang awesome! Many thanks!  
Great idea to split into code and doc :-)  

Thinking this further one could directly link from matrix to the detail doc...

**Comment by hpvd** [comment]
Having such a great overview, the feature matrix deserves a more prominent place to be found.
Or a least more links pointing to it...

**Comment by Jennifer88huang** [comment]
@hpvd I'm thinking about it. If you have any idea or suggestion, feel free to let me know. Thank you.

**Comment by frankjkelly** [comment]
That is just wonderful news - thank you @Jennifer88huang definitely worth sharing far and wide in Slack, Emails, links from doc. Will be super helpful for current and future developers! Thanks so much!

**Comment by Jennifer88huang** [comment]
@frankjkelly  thank you for your advice, I'll share it in different channels so more people who care about it will know it.

**Comment by frankjkelly** [comment]
@Jennifer88huang I think this can be closed now - what do you think?

**Comment by Jennifer88huang** [comment]
@frankjkelly Yes, thank you for your reminder.
