### ISSUE TITLE
Cleanup the org.apache.pulsar.io.PulsarFunctionE2ETest class

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#9724]
The scope of current implementation of the org.apache.pulsar.io.PulsarFunctionE2ETest class is too broad, it is responsible for the end to end testing of Pulsar Functions, Pulsar Sources, and Pulsar Sinks. These test suites should be implemented in different test classes altogether since they test fundamentally different things.

Furthermore, there is a lot of code inside the setup() method that should be moved into separate individual methods for ease of maintenance going forward

**Is your enhancement request related to a problem? Please describe.**
No functional problem per se, just software maintainability

**Describe the solution you'd like**
Break the PulsarFunctionE2ETest into 4 separate classes: PulsarFunctionE2ETest, PulsarBatchE2ETest, PulsarSourceE2ETest, and PulsarSinkE2ETest along with a base class that contains common code that is required for each Test.

**Describe alternatives you've considered**
Leaving the code as-is

**Additional context**
N/A

**Comment by lhotari** [comment]
There's some cleanup that is handled by PR #9673 . @david-streamlio Please review that before starting refactorings on PulsarFunctionE2ETest. I hope we get that merged first.

**Comment by david-streamlio** [comment]
Thanks. I will revisit this now that the above PR has been merged.
