### ISSUE TITLE
[Website] Coding Guide: link to "Third party dependencies and licensing" is broken

### ISSUE THREAD

**Issue by dlg99** [apache/pulsar#9730]
**Describe the bug**

**To Reproduce**
1. Go to https://pulsar.apache.org/en/coding-guide/
2. Click on 'Third party dependencies and licensing.'
-> get error 404 for https://pulsar.apache.org/community/licensing

**Expected behavior**
a page with required steps to check License files

**Desktop (please complete the following information):**
 - OS: MacOS, Chrome

**Comment by Jennifer88huang** [comment]
@dlg99 thank you for raising the issue.
@Anonymitaet I found that we don't have `licensing` file in the `pulsar` repo. Could you please help check and fix the issue? Thank you.

**Comment by adithyaakrishna** [comment]
@Jennifer88huang Can I take this up?

**Comment by Anonymitaet** [comment]
@adithyaakrishna yes, please go ahead, thanks.

**Comment by Jennifer88huang** [comment]
@abhilashmandaliya Sure. When you submit your PR, you can ping us in the PR directly. Thank you.

**Comment by adithyaakrishna** [comment]
@Jennifer88huang  There was another link too, which I will be fixing in the same PR if it's okay 👀

**Comment by Jennifer88huang** [comment]
@adithyaakrishna sure, that's great.
