### ISSUE TITLE
Consumer receive extra messages when enableRetry and retryLetterTopic and deadLetterTopic are not set

### ISSUE THREAD

**Issue by aloyszhang** [apache/pulsar#9742]
**Describe the bug**
Consumer receive extra messages when enableRetry and retryLetterTopic and deadLetterTopic are not set.

Currently, if enableRetry is set to true for a consumer and retryLetterTopic and deadLetterTopic are not set, ConsumerBuilderImpl will build the default retryLetterTopic and deadLetterTopic like :
`tenant/namespaces/subscriptionName-RETRY` and `tenant/namespaces/subscriptionName-DLQ`.

If we have two topics in the same namespace, assume `tenant/namespaces/topicA` and `tenant/namespaces/topicB`, and then 
1. start subscription for `tenant/namespaces/topicA`  with subscription name `sub-name`, 
2. start subscription for `tenant/namespaces/topicB`  with the same subscription name `sub-name`
3. enableRetry  but not set specify retryLetterTopic and deadLetterTopic for the two subscriptions

subscription for topicA and topicB will have the same retryLetterTopic  `tenant/namespaces/sub-Name-RETRY` and the same deadLetterTopic `tenant/namespaces/sub-Name-DLQ`.

So each subscription may receive message from another topic.

**Expected behavior**
Consuemr should not receive messages from non-subscribe topic

**Comment by eolivelli** [comment]
That's pretty bad.
I am not sure how we can fix this in a compatible way

**Comment by aloyszhang** [comment]
closed by #10129
