### ISSUE TITLE
Support to get which broker is the load coordinator

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#9757]
**Is your feature request related to a problem? Please describe.**
Currently we only print logs if a broker becomes the load coordinator, so if users want to check who is the load coordinator, they must check the logs of the brokers. It's better to add a command to get who is the load coordinator, this is useful for the Pulsar maintainer.

**Comment by eolivelli** [comment]
+1 that would be super useful

**Comment by linlinnn** [comment]
@codelipenghui  hi, is that means to add a command to get who is leader broker?

**Comment by codelipenghui** [comment]
@linlinnn Yes, are you interested in push a PR to add this feature?

**Comment by linlinnn** [comment]
@codelipenghui  ok

**Comment by codelipenghui** [comment]
Thanks, assigned.
