### ISSUE TITLE
[Go Functions] Allow user metrics

### ISSUE THREAD

**Issue by flowchartsman** [apache/pulsar#9772]
Currently Go function metrics are implemented with a Prometheus registry and [instantiated at runtime in an init()](https://github.com/apache/pulsar/blob/206ea82e012af34c5bb7f824826205019f3dd4ff/pulsar-function-go/pf/stats.go#L57-L150). These metrics are exposed to the functions runtime and automatically updated by the SDK, which makes sense, but the registry is inaccessible to the user.

It would be great to be able to support something like `recordMetric` as [provided to the Java SDK](https://pulsar.apache.org/docs/en/2.4.0/functions-metrics/)

A simple implementation could be to mirror this and provide a `context.RecordMetric(metricname string, value float64)`, though we could also provide package-level functions to create and register new metrics by name, like `pf.NewGauge(name string) (prometheus.Gauge, error)` which the user would then be responsible for updating in the code of their pulsar function.

**Comment by flowchartsman** [comment]
I'd be willing to take a crack at this. @codelipenghui, @wolfstudy do you know if it would be enough to register metrics with the registry to have them exposed, or would it be necessary to do work on the runtime as well?

**Comment by wolfstudy** [comment]
Thanks @flowchartsman proposal, This is indeed the missing feature of Go Function. Are you interested in this? Welcome to submit a pull request to support this feature.

**Comment by flowchartsman** [comment]
Yeah, not a problem, any thoughts on implementation? I am tempted to add methods into `pf`
