### ISSUE TITLE
How to fetch all function state？

### ISSUE THREAD

**Issue by Crtrpt** [apache/pulsar#9791]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
```
import org.apache.pulsar.functions.api.Context;
import org.apache.pulsar.functions.api.Function;

import java.util.Arrays;

public class FuncFunction implements Function<String, String> {

    @Override
    public String process(String input, Context context) {
        Arrays.asList(input.split(" ")).forEach(word -> {
            String counterKey = word.toLowerCase();
            context.incrCounter(counterKey, 1);
        });
        return input;
    }

}
```

```
  var stringProducer = client.newProducer(Schema.STRING)
                .topic("my-topic-1")
                .create();
        stringProducer.send("hello json");
```

How to fetch hello counter and json counter at once ?

**Describe alternatives you've considered**

**Additional context**

**Comment by codelipenghui** [comment]
@Crtrpt You can use `bin/pulsar-admin functions querystate` to fetch the current state associated with a Pulsar Function.

**Comment by Crtrpt** [comment]
> @Crtrpt You can use `bin/pulsar-admin functions querystate` to fetch the current state associated with a Pulsar Function.
But only one
