### ISSUE TITLE
Pulsar is deployed in a Kubernetes cluster, but it does not bind to PVCs in the cluster

### ISSUE THREAD

**Issue by houbeibei123** [apache/pulsar#9812]
#### Steps to reproduce

According to the official website to provide the installation method of pulsar (https://github.com/streamnative/charts) in Kubernetes cluster deployment, but it cannot bind the cluster of PVC.
Each component that needs to be bound to PVC will report the following error:
   pod has unbound immediate PersistentVolumeClaims

#### Steps:
helm repo add streamnative https://charts.streamnative.io

helm repo update

git clone https://github.com/streamnative/charts.git
cd charts
./scripts/pulsar/prepare_helm_release.sh  -n pulsar -k sn-platform-pulsar -s -c

helm repo add loki https://grafana.github.io/loki/charts
cd  charts
helm dependency update pulsar
helm repo update

helm install --set initialize=true --set namespace=pulsar  --set namespaceCreate=true   sn-platform-pulsar streamnative/pulsar

**Comment by wolfstudy** [comment]
Can you help determine whether there are PV resources available in your current environment?

Maybe you should Provide a persistentVolume fulfilling the constraints of the claim ( eg: a size >= 100Mi)

**Comment by wolfstudy** [comment]
@houbeibei123 Is it convenient for you to create an issue under `streamNative/charts` to describe your problem? So we can close this issue in the `apache/pulsar` repo?

**Comment by slavitch** [comment]
I have the same issue.

**Comment by eolivelli** [comment]
Probably you have to set the storageClass?
As you are talking about a third party chart I suggest you to open an issue on the issue tracker for that chart as well
