### ISSUE TITLE
No such ledger exists on Metadata Server

### ISSUE THREAD

**Issue by sakurafly123** [apache/pulsar#9818]
#### Expected behavior

when I use  Presto SQL, I encountered a mistake；

presto> select * from pulsar."public/default".test8;
Query 20210305_090629_00024_pnys3 failed: org.apache.bookkeeper.mledger.ManagedLedgerException: java.util.concurrent.CompletionException: **org.apache.bookkeeper.client.BKException$BKNoSuchLedgerExistsOnMetadataServerException: No such ledger exists on Metadata Server**
who can  tell me how to solve this problem? thank.

**Pulsar version**: 2.6.0

**Comment by codelipenghui** [comment]
Have you deleted the ledgers from the bookie? From the error log, it means the topic metadata contains a LedgerId but the LedgerId does not exist in the bookkeeper cluster. Can this reproduce stably? Another possibility is the topic is in the process to delete the Ledger, the ledger is deleted from the bookie cluster but the topic metadata does not update yet. Have you tried run the same SQL query multiple times?

**Comment by sakurafly123** [comment]
> Have you deleted the ledgers from the bookie? From the error log, it means the topic metadata contains a LedgerId but the LedgerId does not exist in the bookkeeper cluster. Can this reproduce stably? Another possibility is the topic is in the process to delete the Ledger, the ledger is deleted from the bookie cluster but the topic metadata does not update yet. Have you tried run the same SQL query multiple times?

i don't delete ledgers from the bookie

> #### Expected behavior
> when I use Presto SQL, I encountered a mistake；
> 
> presto> select * from pulsar."public/default".test8;
> Query 20210305_090629_00024_pnys3 failed: org.apache.bookkeeper.mledger.ManagedLedgerException: java.util.concurrent.CompletionException: **org.apache.bookkeeper.client.BKException$BKNoSuchLedgerExistsOnMetadataServerException: No such ledger exists on Metadata Server**
> who can tell me how to solve this problem? thank.
> 
> **Pulsar version**: 2.6.0

broker conf:
