### ISSUE TITLE
Pulsar IO Source Connectors properties not added to message

### ISSUE THREAD

**Issue by thesquiff** [apache/pulsar#9851]
**Describe the bug**
I have been developing a couple of Pulsar IO Source connectors. They are able to write out message bodies but properties (even though the getProperties() message does appear to be called) are not added to the messages published onto the destination topic.

A minimal test case can be demonstrated by adding properties to the Data Generator Source.

**To Reproduce**
Add the following to DataGeneratorSource.java and then build and deploy the connector:

            @Override
            public Map<String, String> getProperties() {
                HashMap<String, String> props = new HashMap<String, String>();
                props.put("hello", "world");
                props.put("foo", "bar");
                return props;
            }

**Expected behavior**
A message is published onto the destination topic with both the generated message contents (json representation of a person) and the properties as hard coded above. However the properties are missing.

Tested on Pulsar 2.7.0

**Comment by gaoran10** [comment]
Which function mode are you using? Local-run, thread mode, or process mode? 

If you use the thread or process mode, you could try to set the param `--forward-source-message-property` to `true`. 
It seems that the local-run mode doesn't set this param to `true` for source connector.

**Comment by gaoran10** [comment]
It seems that the source connector couldn't publish the properties along with the message content to the Pulsar topic.
There is a config `forwardSourceMessageProperty` to determine whether set properties to the Pulsar message properties.
But the source connector doesn't set this param, so its default value is `false`. If it's a function you could use the param `--forward-source-message-property` to set its value. Maybe we could add a new configuration for the source config to set the param `forwardSourceMessageProperty` or set its default value as `true` for the source connector.

The method in the class `PulsarSink`.
```
@Override
    public void write(Record<T> record) {
        SinkRecord<T> sinkRecord = (SinkRecord<T>) record;
        TypedMessageBuilder<T> msg = pulsarSinkProcessor.newMessage(sinkRecord);
      
        ...
        if (!record.getProperties().isEmpty() && pulsarSinkConfig.isForwardSourceMessageProperty()) {
            msg.properties(record.getProperties());
        }
        ...

        pulsarSinkProcessor.sendOutputMessage(msg, sinkRecord);
    }
```

**Comment by thesquiff** [comment]
My view on this one is that properties should always be sent on by the source. The source should set them if required and not set them if not required. I can't think of a use case for having the switch currently.

**Comment by codelipenghui** [comment]
If I understand correctly, you want to keep `forwardSourceMessageProperty=true` as default right? I think there are some internal properties that the function introduced or others, not the user-defined, maybe the initial motivation is to avoid passing the internal properties.

@nlu90 @freeznet Please help double confirm.

**Comment by freeznet** [comment]
@codelipenghui  according to pr #8158, i think `forwardSourceMessageProperty=true` is the default setting, please let me know if I missed something. 

@thesquiff would you please help to check:
- make sure add `forwardSourceMessageProperty=true` to `functions_worker.yml`
- restart and see if properties are still not pass to the destination topic

Also, please provide what kind of function runtime you are testing, like thread, process or k8s, thanks a lot.

**Comment by thesquiff** [comment]
I have added `forwardSourceMessageProperty: true` to the bottom of functions_worker.yml with pulsar running as a standalone instance for test purposes and there was no change. Properties are still not being sent.

On my main cluster where I initially observed this problem, the function workers are running as threads on the brokers.

**Comment by gaoran10** [comment]
> I have added `forwardSourceMessageProperty: true` to the bottom of functions_worker.yml with pulsar running as a standalone instance for test purposes and there was no change. Properties are still not being sent.
> 
> On my main cluster where I initially observed this problem, the function workers are running as threads on the brokers.

I think SourceConnector couldn't set the config forwardSourceMessageProperty through the functions_worker.yml, it's only used for the Function.

Please check these codes in the class `SourceConfigUtils`, this is the sink spec generation code for the SourceConnector.
The default value of the param `forwardSourceMessageProperty` should be `false`.
```
// set up sink spec.
// Sink spec classname should be empty so that the default pulsar sink will be used
Function.SinkSpec.Builder sinkSpecBuilder = Function.SinkSpec.newBuilder();
if (!org.apache.commons.lang3.StringUtils.isEmpty(sourceConfig.getSchemaType())) {
    sinkSpecBuilder.setSchemaType(sourceConfig.getSchemaType());
}
if (!org.apache.commons.lang3.StringUtils.isEmpty(sourceConfig.getSerdeClassName())) {
    sinkSpecBuilder.setSerDeClassName(sourceConfig.getSerdeClassName());
}

sinkSpecBuilder.setTopic(sourceConfig.getTopicName());

if (sourceDetails.getTypeArg() != null) {
    sinkSpecBuilder.setTypeClassName(sourceDetails.getTypeArg());
}

if (sourceConfig.getProducerConfig() != null) {
    sinkSpecBuilder.setProducerSpec(ProducerConfigUtils.convert(sourceConfig.getProducerConfig()));
}

functionDetailsBuilder.setSink(sinkSpecBuilder);
```

**Comment by freeznet** [comment]
Thanks @gaoran10 for correct me, you are right about this. In this case, I can work on the fix later.
