### ISSUE TITLE
Using a websocket client with authentication on the browser side

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar#9854]
**Is your feature request related to a problem? Please describe.**
Some users want to use a WebSocket client with authentication on the browser to connect to the pulsar service, but the current authentication information, such as the token, cannot be set to the header, which prevents sending authentication information to the pulsar cluster

**Describe the solution you'd like**
Some related solutions: https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api

**Describe alternatives you've considered**

We can consider adding support for some authentication plugins https://github.com/apache/pulsar/blob/1d6aa57f1f8ead378a9d103190156c9b45589e41/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderToken.java#L158, such as reading authentication token information from query parameters, cookies, or `ws://token@example.com/path`

**Additional context**

**Comment by hpvd** [comment]
+1 for this!

would be also a perfect additional component to show in this "Full scale example" https://github.com/apache/pulsar/issues/9008

**Comment by tuteng** [comment]
This fixed #9886
