### ISSUE TITLE
Message properties don't get passed from Pulsar Sources

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#9926]
**Describe the bug**
When a PulsarSource writes a `Record` that has property values set inside its `getProperties()` method. Those properties are not passed through to the Message written to the output topc.

**To Reproduce**
1. Create a class that extends implements the Source interface and a class that implements the Record interface
2. Have the Source instantiate the Record class
3. Have the Source write some properties inside the Record class
4. Have the Source publish the message
5. Inspect the resulting Message in the topic and see that there are no properties associated with the message

**Expected behavior**
One would expect that any properties added to the Record would be included in the published method

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Additional context**

**Comment by thesquiff** [comment]
Looks like a duplicate of [https://github.com/apache/pulsar/issues/9851]

**Comment by david-streamlio** [comment]
> Looks like a duplicate of #9851

You are correct. However, there is an on going discussion w.r.t to the solution to this issue so I will keep this open for now for tracking purposes.

**Comment by david-streamlio** [comment]
Resolved
