### ISSUE TITLE
[docs] Add docs about monitoring Functions/IO with internal metrics. 

### ISSUE THREAD

**Issue by freeznet** [apache/pulsar#9932]
**Is your enhancement request related to a problem? Please describe.**
Functions/Sinks/Sources has metrics support and can be used to monitoring the status. But we dont have detailed documents to show what metrics we already support and how we can use the metrics to monitoring functions/io.

**Describe the solution you'd like**
Add monitoring section to pulsar functions & pulsar io's document.

**Additional context**
- #3261 adds the metrics to java functions / io
- https://github.com/apache/pulsar/blob/branch-2.7/pulsar-function-go/pf/stats.go go functions with metrics support
- https://github.com/apache/pulsar/blob/branch-2.7/pulsar-functions/instance/src/main/python/function_stats.py python functions with metrics support

**Comment by Jennifer88huang** [comment]
@Huanli-Meng @Anonymitaet when you triage doc issues, could you please add the "triage/week-xx" labels? Thank you.

**Comment by Anonymitaet** [comment]
@Jennifer88huang yes, thanks for reminding

**Comment by Anonymitaet** [comment]
@freeznet thanks for raising this up. I've drafted [one](https://docs.google.com/document/d/1lAJE88GLePfI8KqMXsbMnWllEP0feVwpgAongAgSv-w/edit#) to solve this issue, could u pls help review? Feedback before 4/1 is highly appreciated, thanks!

**Comment by Anonymitaet** [comment]
@freeznet thanks for your guidance! 

I've updated the [doc](https://docs.google.com/document/d/1flvqczz1_cKBESwvATuxZqHbila09hfjls0M0VRyS4A/edit#) based on your comments, could u pls provide tech inputs and help review? 

Feedback before 4/3is highly appreciated, thanks!

**Comment by freeznet** [comment]
@Anonymitaet Just did some comments on the latest version, PTAL, thanks.

**Comment by Anonymitaet** [comment]
@freeznet thanks for your guidance! I'll incorporate your comments and send a doc PR.
