### ISSUE TITLE
Messages can get consumed out of order with key_shared subscriptions and small receiverQueueSize

### ISSUE THREAD

**Issue by fransguelinckx** [apache/pulsar#9940]
**Describe the bug**
Messages can get consumed out of order with key_shared subscriptions and small receiverQueueSize

**To Reproduce**
* A producer that produces a relatively high load of messages with different keys. Crucial to have related messages with the same message key in a specific order.
* Partitioned topic on which the messages are produced.
* A lot of key_shared subscriptions on the topic and several consumers within every single subscription.
*  Consumption of messages is synchronous and also should take some time.
* Consumers have a receiverQueueSize of 1.

**Expected behavior**
I expect messages with the same key to be processed in the correct order by the same consumer.

**Additional context**
This issue was already discussed on [Slack](https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1615199642267000) and @codelipenghui asked me to create this issue to track the problem.

**Comment by congbobo184** [comment]
Move this to the next release.

**Comment by michaeljmarshall** [comment]
@fransguelinckx - can you confirm that this is still an issue? I am releasing 2.7.4 now, so I am going to remove the label. I believe there were some recent fixes to the key_shared subscription this past fall, but I am not sure that they address the specific bug you're seeing.

**Comment by tisonkun** [comment]
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.
