### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by tapanbavaliya** [apache/pulsar#9955]
**Describe the bug**
Pulsar search is the broken user can not search anything.

**To Reproduce**
* go to home page
* type something 
* nothing will happand
* 
**Expected behavior**
user can able to search

**Screenshots**
![ggggg](https://user-images.githubusercontent.com/1378636/111592474-d62a6180-87ee-11eb-98f6-fc74c1444a33.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by Jennifer88huang** [comment]
@tapanbavaliya thank you for raising the issue. I tried it on the home page and found the search works on my chrome (shown as follows). Could you try it again? If it still does not work, feel free to let us know.
![image](https://user-images.githubusercontent.com/47805623/112076675-d42d1d80-8bb5-11eb-9145-84765a351f48.png)

**Comment by Anonymitaet** [comment]
Same to @Jennifer88huang, search works on my side as well.
![Uploading image.png…]()

**Comment by tapanbavaliya** [comment]
@Jennifer88huang Yes verified from my side as well, when I checked at the time it's not worked in chrome, firefox. but now it's working, we can close this ticket.

**Comment by Jennifer88huang** [comment]
@tapanbavaliya thank you for letting us know it.
