### ISSUE TITLE
Unable to access StateStore running inside a Docker container

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar#9977]
**Describe the bug**
If you run Pulsar in standalone mode inside a Docker container, calls (direct or indirect) to the StateStore using "localhost", e.g. bk://localhost:4181 fail because the StateStore client is using a different hostname

**To Reproduce**

1. Start a Pulsar standalone instance inside a docker container 
2. Deploy a stateful function to the cluster
3. Trigger the function

**Expected behavior**
One would expect these calls to succeed

**Additional context**

**Comment by eolivelli** [comment]
did you try with` --network=host` ?
